### ISSUE TITLE
Add Location for Where to Provide Feedback for `--import-mode=importlib`

### ISSUE THREAD

**Issue by adam-grant-hendry** [pytest-dev/pytest#10003]
#### What's the problem this feature will solve?

Reading [here](https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html?highlight=import%20mode#import-modes), it says:

> We intend to make importlib the default in future releases, depending on feedback.

However, I don't know where to provide feedback.
#### Describe the solution you'd like

Please add to the docs a location where users should provide feedback.

#### Alternative Solutions

N/A
#### Additional context

I've used `--import-mode=importlib` successfully and I think it should become the new default!

**Comment by adam-grant-hendry** [comment]
Similarly, the note [here](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html?highlight=import%20mode) says:

> The new --import-mode=importlib (see [Import modes](https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html#import-modes)) doesn’t have any of the drawbacks above because sys.path is not changed when importing test modules, so users that run into this issue are strongly encouraged to try it and report if the new option works well for them.

but doesn't state where to provide feedback.

**Comment by nicoddemus** [comment]
The issue is in #7245, however at this point it is clear that we should not change the default, as `importlib` has its own set of drawbacks and changing the default would severely impact a lot of test suites.
