### ISSUE TITLE
fluent writing style for pytest.param objects when id is wanted

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#10024]
#### What's the problem this feature will solve?

listing parmetersets with ids is a pain, however we ruled out using mappings for good reason,

still sometimes one would like to write them shorter

currently i have to write tables like
```python
@pytest.mark.parametrize(["input", "expected_name"], [
    pytest.param("", None, id="empty"),
    pytest.param(b"[metadata]\nmaintainers=wrong", None, id="wrong maintainers key"),
    pytest.param(b"[metadata]\nmaintainer=test", "test", id="has maintainers"),
    pytest.param(b"[metadata]\nmaintainer=\n test\n second", "test", id="picks_first"),
])
```
#### Describe the solution you'd like

additional ways to pass id to param

```python
# getitem
pytest.param["picks fists"](...)

# construction method
pytest.param.with_id("picks first", ...)
# getattr hack

pytest.param.picks_first(...)
```

personally i like the getitem version most, but i recon the construction method version is most non-surprising

**Comment by graingert** [comment]
> however we ruled out using mappings for good reason

ruled out here: https://github.com/pytest-dev/pytest/issues/7568

**Comment by nicoddemus** [comment]
I'm personally 👎 on the idea in general: there's already two ways to do parametrization, I'm not a big fan of adding yet another (even more using a somewhat cryptic syntax). This is probably better live as a plugin instead of being added to the core.

**Comment by RonnyPfannschmidt** [comment]
i can go with that, i'd like to see additional input

**Comment by nicoddemus** [comment]
Sounds good!
