### ISSUE TITLE
`request.addfinalizer` order of execution is undocumented

### ISSUE THREAD

**Issue by fish-face** [pytest-dev/pytest#10023]
This is very important if you are creating fixtures which interact with others which were not written with `yield`, and is extra confusing when writing tests which themselves *do* use `yield`.

**Comment by nicoddemus** [comment]
Hi @fish-face,

Thanks for the report. Would you like to contribute a PR with that? I think a single paragraph to the docs of `request.addfinalizer` would do.

**Comment by fish-face** [comment]
The problem is I still don't really know what the behaviour is, even after examining the code! I could write it but I would be guessing :/

**Comment by nicoddemus** [comment]
Yeah, sounds great, thnaks. I think just a paragraph stating that they are executed in first-in-last-out order is enough. 👍

**Comment by dougmellon** [comment]
@nicoddemus on it, thank you.

**Comment by fish-face** [comment]
> Yeah, sounds great, thanks. I think just a paragraph stating that they are executed in first-in-last-out order is enough. +1

The complexity is how this interacts with the finalizers which are added implicitly through `yield`, and the different possible scopes.

**Comment by ImShivraj** [comment]
is it done ?

**Comment by nicoddemus** [comment]
Not yet.

**Comment by aizpurua23a** [comment]
Hey eveyrone! 
I haven't seen progress on this issue for some time, so I took the liberty to try and address it on https://github.com/pytest-dev/pytest/pull/10171.

I'd love to hear your thoughts on it :pray:
