### ISSUE TITLE
7.2 release planning 

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#10045]
I think we can start planning the 7.2 schedule.

I've created the [7.2 milestone](https://github.com/pytest-dev/pytest/milestone/40) so we can start assigning issues to it and track when 7.2 is ready. 👍 

Also, does anyone volunteer to do the release when the time comes?

**Comment by RonnyPfannschmidt** [comment]
After the 20th I'm happy to volunteer, after all I skipped the honour for a while now

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt gentle ping. 👍

**Comment by nicoddemus** [comment]
Seems everything assigned to the milestone has been resolved, so this is ready to go. 👍

**Comment by RonnyPfannschmidt** [comment]
I shall move those draft prs to the next milestone

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus https://github.com/pytest-dev/pytest/actions/runs/3308445610 was triggered after creating a branch off main
