### ISSUE TITLE
Intersphinx fails to resolve `pytest.FixtureRequest` type annotation

### ISSUE THREAD

**Issue by shoriminimoe** [pytest-dev/pytest#10063]
I am using `FixtureRequest` in a type hint for one of my fixtures.I'm also using sphinx with the intersphinx extension to document my tests. For example I have this `conftest.py`:

```python
# conftest.py
import pytest


@pytest.fixture
def myfixture(request: pytest.FixtureRequest):
    """Get user input"""
    return request.config.getoption("user_input")
```

And this `index.rst`:
```rst
Pytest Configuration
====================

.. automodule:: conftest
   :members:

This reference works: :py:class:`pytest.FixtureRequest`
```

When I build the docs in nitpick mode, I encounter the following warning when resolving the reference to `FixtureRequest` in the type hint:

```
/home/user/bwah/docs/conftest.py:docstring of conftest.myfixture:: WARNING: py:class reference target not found: _pytest.fixtures.FixtureRequest
```

The resolution fails for the type hint, but not for the explicit `` :py:class:`pytest.FixtureRequest` `` reference. I believe the issue is related to how the class is defined in [src/_pytest/fixtures.py](https://github.com/pytest-dev/pytest/blob/fab696dcd1ecd621ed05d2552b7d790ab143efe5/src/_pytest/fixtures.py#L391) vs how it is documented in [request reference](https://github.com/pytest-dev/pytest/blob/main/doc/en/reference/reference.rst#request). The python class path resolves to `_pytest.fixtures.FixtureRequest`, but the sphinx symbol is `pytest.FixtureRequest` since it is created using the top-level namespace.

My intersphinx config is referring to https://docs.pytest.org/en/stable/ on June 21 2022. This is my `pip list`:
```sh
➤ pip list
Package                       Version
----------------------------- ---------
alabaster                     0.7.12
attrs                         21.4.0
Babel                         2.10.3
certifi                       2022.6.15
charset-normalizer            2.0.12
commonmark                    0.9.1
docutils                      0.17.1
idna                          3.3
imagesize                     1.3.0
iniconfig                     1.1.1
Jinja2                        3.1.2
MarkupSafe                    2.1.1
packaging                     21.3
pip                           22.0.2
pluggy                        1.0.0
py                            1.11.0
Pygments                      2.12.0
pyparsing                     3.0.9
pytest                        7.1.2
pytz                          2022.1
requests                      2.28.0
rich                          12.4.4
setuptools                    59.6.0
snowballstemmer               2.2.0
Sphinx                        5.0.2
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
tomli                         2.0.1
urllib3                       1.26.9
```

**Comment by shoriminimoe** [comment]
I am able to workaround this by including the argument type in the docstring like this:

```python
@pytest.fixture
def my_fixture(request: pytest.FixtureRequest):
    """Get user input

    :param request:
    :type request: pytest.FixtureRequest
    """
    return request.config.getoption("user_input")
```

**Comment by nicoddemus** [comment]
Hi @shoriminimoe, 

Strange, because we use the same syntax in our own docs (example [here](https://github.com/pytest-dev/pytest/blob/main/doc/en/deprecations.rst#diamond-inheritance-between-classpytestcollector-and-classpytestitem)).

I would expect the same syntax work for intersphinx. Can you reach with the intersphinx folks and see if it is a bug/feature/a configuration we are missing?
