### ISSUE TITLE
Update `os.environ['PYTHONPATH']` with the contents of `pythonpath`

### ISSUE THREAD

**Issue by xmo-odoo** [pytest-dev/pytest#10067]
#### What's the problem this feature will solve?
Basically what #9134 solved, with the addition of subprocesses being spawned by the SUT or being the SUT itself (I regularly use pytest for non-python utilities and the likes)

#### Describe the solution you'd like
That at the same time the content of `pythonpath` is prepended to `sys.path`, it's also prepended to `os.environ['PYTHONPATH']`

#### Alternative Solutions
`python-dotenv` has understandably rejected special support for `PYTHONPATH` (theskumar/python-dotenv#36). Though I guess `pytest-dotenv` might be open to that? I haven't found any mention of that on their bug tracker.

**Comment by RonnyPfannschmidt** [comment]
has to be rejected, i can think of at least 10 integration testsuites this one would break right off the bat

**Comment by nicoddemus** [comment]
To complement: the `pythonpath` config variable is just meant to help pytest import modules, so users not using the standard development workflow can easily help pytest import their test files. It is not meant as an actual config variable to update also environment variables. Doing so would definitely have consequences in existing test suites, either breaking immediately, or producing confusing errors hard to debug.

You can accomplish the same with an auto-use fixture in your `conftest.py` file.
