### ISSUE TITLE
Make it clear when an auto-use fixture will be discarded due to it being in a file that isn't `conftest.py`

### ISSUE THREAD

**Issue by MiguelGuthridge** [pytest-dev/pytest#10069]
#### What's the problem this feature will solve?

I spent the last 2 hours debugging why a pytest fixture I wrote wasn't being run. It turned out it wasn't in `conftest.py`, it was discarded entirely, without any warnings on errors. It also wasn't clear from the documentation that this would happen (the documentation says their test is there, but reads like putting it there is optional).

#### Describe the solution you'd like

When an auto-used fixture is created in a file that isn't `conftest.py`, and there are no tests in that file, emit a warning that the fixture will not be used outside of that module.

#### Additional context

* [StackOverflow question where I discovered this behaviour](https://stackoverflow.com/questions/72714721/my-auto-used-session-scoped-fixture-isnt-used-even-though-it-is-registered/72715480#72715480)

**Comment by The-Compiler** [comment]
I believe we already have ample documentation on this - do you have a concrete suggestion what bit is missing? I believe the central misunderstanding you had is that `scope` declares how the fixture's values are cached, *not* where the fixture is "visible" (and thus used by `autouse`).

Here is what docs we already have:

# Fixtures reference

- [Fixture availability](https://docs.pytest.org/en/7.1.x/reference/fixtures.html#fixture-availability) explains how fixtures are only available where they have been designed, and even says:

> Similarly, a test can also only be affected by an autouse fixture if that test is in the same scope that autouse fixture is defined in (see [Autouse fixtures are executed first within their scope](https://docs.pytest.org/en/7.1.x/reference/fixtures.html#autouse-order)).

and that in turn says:

> Autouse fixtures are assumed to apply to every test that could reference them

There is even a picture at the end:

![image](https://user-images.githubusercontent.com/625793/175033692-2ce2a0bd-d736-46d7-9028-f21a9b0093cf.png)

#  How to use fixtures

- [Autouse fixtures (fixtures you don’t have to request)
](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#autouse-fixtures-fixtures-you-don-t-have-to-request): Doesn't really have much documentation about which tests will autouse the fixture, maybe a link to the other page here is all that's missing??
- [Scope: sharing fixtures across classes, modules, packages or session
](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#scope-sharing-fixtures-across-classes-modules-packages-or-session): I believe this already makes it clear that this is about caching:

> Fixtures requiring network access depend on connectivity and are usually time-expensive to create. Extending the previous example, we can add a scope="module" parameter to the [@pytest.fixture](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.fixture) invocation to cause a smtp_connection fixture function, responsible to create a connection to a preexisting SMTP server, to only be invoked once per test module (the default is to invoke once per test function). Multiple test functions in a test module will thus each receive the same smtp_connection fixture instance, thus saving time.

# API reference

[API Reference — pytest documentation](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-fixture)

> scope: The scope for which this fixture is shared; one of "function" (default), "class", "module", "package" or "session".

and

> autouse – If True, the fixture func is activated for all tests that can see it. If False (the default), an explicit reference is needed to activate the fixture.

**Comment by The-Compiler** [comment]
Ah, as for the warning - in a more generic sense, I suppose we could warn if there is an autouse fixture which is not requested by any test (either implicitly or explicitly). I have no idea if or how well that would work out with the way they are implemented, though.

**Comment by MiguelGuthridge** [comment]
I believe that it probably was mainly an issue of my understanding of the way Pytest treats fixtures. I think warning on unused fixtures could be a good idea, but that probably deserves its own issue.
