### ISSUE TITLE
Documentation fix to prevent confusion for plugin developers

### ISSUE THREAD

**Issue by Kache** [pytest-dev/pytest#10072]
https://github.com/pytest-dev/pytest/blob/aa55975c7d3f6c9f6d7f68accc41bb7cadf0eb9a/doc/en/how-to/writing_plugins.rst#making-your-plugin-installable-by-others=

Above isn't clear enough about the right thing to do, so naming collisions like the below have occurred:

https://github.com/aresponses/aresponses/issues/71
https://github.com/ipwnponies/pytest-antilru/issues/22

This issue is evident by installing one (or more) of these plugins and running:

```sh
❯ pytest --trace-config
# ... bunch of stuff ...
active plugins:
    name_of_plugin      : /REDACTED/.venv/lib/python3.7/site-packages/aresponses/main.py

**Comment by s1aw1k** [comment]
👍
