### ISSUE TITLE
Add pytest.raises(..., contains='substring')

### ISSUE THREAD

**Issue by timhoffm** [pytest-dev/pytest#10085]
[pytest.raises](https://docs.pytest.org/en/6.2.x/reference.html#pytest.raises) can assert the message content as regexp via the `match` parameter. However, most of the time, I really only need to check if a substring is present in the message. Regexp is quite a heavy machinery for that and I have to constantly think whether my expression is plain text or whether I have to escape literally or via `re.escape`.

### We currently have to do:
```
with pytest.raises(ValueError, match=r'Unsupported file type: \*\.py')
# or
with pytest.raises(ValueError, match=re.escape('Unsupported file type: *.py'))
```
### I would additionally like to have:

```
with pytest.raises(ValueError, contains='Unsupported file type: *.py')
```

On the one hand, this is a bit redundant: You have the functionality with escaped regexes and the two keywords *match* and *contains* would be mutually exclusive. On the other hand, *contains* is much simpler to think about, and I'd claim sufficient for 90% of the use cases.

**Comment by timhoffm** [comment]
While I agree that one likely will check for the first few words in a majority of cases, I still suggest the contains API. First, a common case for these checks are variable parts of the message such as “The parameter foo_dict of bar() does not support the key “xyz”. Supported values are …”. Here, the relevant check is `contains='does not support the key “xyz”'. Second, I usually only care that a phrase is inside the message, but not whether there is more information before or after that phrase. So the more general contains should be good enough, we do not need more specific startswith or endswith.

**Comment by RonnyPfannschmidt** [comment]
How about fnmatch, we have that for the line matches as well

**Comment by nicoddemus** [comment]
If we are to add a new parameter, I agree `contains` will be the most widely used. I agree with @timhoffm that most of the time you want `contains`, with `match` then being used for more complex cases. 👍

**Comment by asottile** [comment]
I still do not think we should expand the api, and I don't think `contains` is a good "default".  when reviewing code I generally suggest changing a `'something' in ...` to startswith / endswith most of the time already.  having `contains=` as an api when `startswith=` is a stronger assertion doesn't feel like we're guiding people to a good pattern of asserting things -- a convenient but weak assertion

**Comment by RonnyPfannschmidt** [comment]
i also do see the point about the strength of the assertion, its a bit like allowing "bad habits" to slip into a api

**Comment by timhoffm** [comment]
#### Strength of the assertion

I'm not even sure I want too strict matching. IMHO the value of validating the message is (in decreasing importance):

- Avoid accidentally catching an unrelated error of the same type. I can be very sure of this by finding a signature phrase
- Making sure, the error message is fundamentally instructive, e.g. for

  > Missing closing quote in: 'grid.color: "aa'. If you need a double-quote inside a string, use escaping: e.g. "the \\" char" 

  I'm happy With `contains="Missing closing quote"`. I don't really care where in the message that string occurs. The message could as well be:
  > Line 'grid.color: "aa': Missing closing quote.

- Validating the exact message.

It's an individual decision how detailed I want to test the message. But being very strict on the message can be like testing an implementation detail.



#### Some statistics

FWIW, I've collected some statistics on the `pytest.raises(..., match=...)` usage in matplotlib tests:

175: direct plain strings - `contains=s` is equal to `match=s`; `contains` would be conceptually simpler/clearer
61: manual escapes - `contains` would remove the need for manual escaping
20: match start - `startswith` would simplify this
13: real regexps
10: full match - `equals` would simplify this

I don't guarantee that every usage is appropriate, but given the current usage patterns 236 / 279 tests could better be written using `containts`.

**Comment by asottile** [comment]
generally what I teach is:

1. if it's important enough to raise a custom exception, have a custom message
2. if it's important enough to have a custom message test the full message exactly

my immediate instinct if `contains` were added were to add a linter to ban usage of it which is why I'm against adding this

**Comment by timhoffm** [comment]
@asottile I appreciate your input and intuition can be a very good guide, in particular with experienced developers. I would like to understand: What is the reason behind 2.?

**Comment by asottile** [comment]
it's the same reason you would want to test your console output: so the messaging is intuitive and as you expect it to be

**Comment by timhoffm** [comment]
I see. In my eyes it's a design choice whether one cares about the exact message and wants to validate that.

How do you feel about `pytest.raises(..., str='...')` with a fnmatch semantics? The standard case would be simple exact matches `str='This is the exact and full message'` but it would allow startwith-checks `str='First words*'`, and contains-like checks `str='*partial phrase*'`.

**Comment by asottile** [comment]
fnmatch kinda feels like a worse regex (less powerful) -- if I were to design the existing api from scratch I'd probably remove the `match` parameter entirely or have it use `.fullmatch(...)` internally (right now it's [`re.search`](https://github.com/pytest-dev/pytest/blob/06738e36dfa0492970017637a1b28f853c229471/src/_pytest/_code/code.py#L679)) -- afaict it's only there for "compatibility" with `unittest.TestCase.assertRaisesRegex`

maybe a better api would be an entirely new function with usage similar to:

```python
with pytest.raises_exact(MyError, 'what you want to match from str(...)'): ...
```

**Comment by nicoddemus** [comment]
FTR I still think `contains` is a good addition, as `contains="foo"` replaces `match=re.escape("*foo*")`, and I usually am interested in only part of the message so the convenience here is worth it.

@asottile are you a strong 👎 on this?

**Comment by nicoddemus** [comment]
(closed by accident)

**Comment by asottile** [comment]
yeah my opinion is we should make strong assertions convenient and weaker assertions less-so -- one can easily write a oneline helper if they need it:

```python
def raises_contains(tp, s):
    return pytest.raises(tp, match=re.escape(s))
```

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus im leaning towads @asottile 


i think a new

```
with pytest.expect_exception(
    LookupError(re_assert.Matches(".* fun :*")),
    ):
```

might be a nice idea as it then gets relatively easy to put "exception templates" into variables and use them

**Comment by timhoffm** [comment]
@asottile I feel that we are not coming together. I'm looking for a contains-like option (that is simpler than a regex). You seem to oppose any addition apart from exact match.

I'm not expecting to get your buy-in with this, because it's going even further the other direction. But I still want to mention the possibility:

*Premise:* pytest should not be opinionated on the exception message validation strategy. That decision should be in the hands of the users.
*Suggestion:* If we accept the premise, pytest should provide simple and clear ways for different kinds of checks. This could be realized through a set of mutually exclusive keywords:
```
pytest.raises(..., exact='...')  # or alternatively str='...'
pytest.raises(..., contains='...')
pytest.raises(..., startswith='...')
pytest.raises(..., match='...')
```

**Comment by RonnyPfannschmidt** [comment]
@timhoffm such polymorphic calls are structurally a antipattern where one starts to encode desired behavior in names instead of parameter types, 

a while back, the matches parameter was only added because people had the wrong idea that the "message" parameter would check the message (when it would only set the error message)

im not exactly keen on expanding the api, i'd rather have assert repr compatible "matchers" one can pass in to say "startswith, containes" 

that way we can easily and consistently replicate it not just for raises, but also for warning and logging checks

**Comment by RonnyPfannschmidt** [comment]
(and even a `exact` matcher has value because it diffs better than a regex escape)

**Comment by timhoffm** [comment]
> a framework should guide individuals towards best practices. 

Fully agree with that. However, I don't follow your argument that weaker assertions on the exception message are necessarily bad. If you all as library authors decide that only partial comparisons of the message are fundamentally bad, then of course you should not do this. The border between guiding and restricting can be thin. I encourage you all to consciously decide how pytest wants to position itself here.

**Comment by RonnyPfannschmidt** [comment]
Additionally I feel we have a responsibility to make right easier than random easily things that pass a test

**Comment by timhoffm** [comment]
Folks, thanks for the discussion. I respect that your design decisions are not a fit for my practical needs here. Keep up the great work!

**Comment by jonas-eschle** [comment]
I just need to raise a point which hasn't been brought up: it's not bad design practice or not. It's all levels of gray.

If the regex takes me more time to write (and yes, I've been again trapping into it), I'll leave it away, the raise is checked in principle.

The argument with the wrapper seems comparably weak to me, as it can go for anything: why even a pytest.approx? Anyone can write a wrapper.

To me, the strongest argument for a good API is the frequency of usage, and as @timhoffm mentioned, this is by far the most usecase in my code-bases as well. At the same time, there is no other parameter that comes even close in frequency used.

I don't see how it hurts (the match does, it yields wrong expectations), I see `contains` helps. 

Just leaving this here to emphasize that this isn't a rare case and others would support the proposal. It's 2 years later and maybe the philosophy regarding the API has changed; maybe not. That's fine, I can only second @timhoffm , thanks for the great package!

**Comment by RonnyPfannschmidt** [comment]
so match objects need to happen instead of doing more magic kwargs -

**Comment by timhoffm** [comment]
> so match objects need to happen instead of doing more magic kwargs -

Match objects are likely a good thing. Though, they pose a bit of overhead in usage. You have to import and write out the comparison definition (`re_assert.Matches` in https://github.com/pytest-dev/pytest/issues/10085#issuecomment-1170051325). Thus, I see their benefit more for complex comparisons. Using them simple checks of message contents feels a bit bulky.

---

I'd like to take one last effort and come up with a minimal consensus on `pytest.raises`, taking into account as much as possible from the above the discussions.

I think we can all agree on:

- It's desirable to check the exception message
- Currently the only way to do this is `pytest.raises(..., match=...)`, which has some issues:
  - The power of regexps is not needed most of the time
  - Regexes are complicated and can trip up users
  - It's based on `re.search` (`re.fullmatch` may have been the better choice https://github.com/pytest-dev/pytest/issues/10085#issuecomment-1169973454) 
- The most common use case is a simple string comparision (excluding the debate whether that means contains, startswith or exact match for now). Thus a sting comparison should be easy.

There are different opinions on:
- How strong string comparisons should be (contains, startswith or exact match)
- Whether one should add more parameters to `pytest.raises`

**Suggestion:** What do you think about adding a single `msg` parameter, that can take a string for an exact match:

```
pytest.raises(expected_exception, msg=None, *, match=None)
```
so that one can do:
```
with pytest.raises(ValueError, "Expected an int but got None")
```
IMHO, this is simple and clear. It's the minimal addition to make simple string comparisons work. It compromizes, to only support strict equality - clarity, safety and a minimal intferface over flexibility. - If a user needs more flexibility, they should still use `match=`.

**Comment by asottile** [comment]
> I'd like to take one last effort and come up with a minimal consensus

we already decided above. and my opinion on this certainly hasn't changed.  you're not bringing anything new to the discussion so there's no reason to believe that the outcome will be different

**Comment by jonas-eschle** [comment]
> you're not bringing anything new to the discussion

it's: it's better to have the one additional keyword that we can agree on than none, as we cannot agree on anything else. Therefore, it's only that or None.

The main issue I see is that we test, in general, for exact matches in unit tests. Sometimes, this is not possible (i.e. numerical, or non-deterministic tests) and we find ways around it, `approx` etc.

*That's not the case for errors*: An error is raised quite deterministic. The expected type and the message are exactly known, it's mostly lazyness to not know it (and a few extra cases). But `pytest.raises` doesn't offer this functionality. One can only test if a regex matches, so it sets the "don't do exact tests" as default.
Similar as if one could not compare numbers directly but only via `approx` with tol set to 0.

And that's a very strong argument, IMO, for `msg`: do the exact thing that tests are expected to do: check the exact output. Akin to doing something like `raises(TypeError("This is an error"))`. More complicated checks? Sure, use match.

I don't see any argument against adding _only_ `msg`: this is the default functionality for unit tests and that seems to be missing?

**Comment by timhoffm** [comment]
@asottile 

> we already decided above. [...] you're not bringing anything new to the discussion

**On the content side**

I don't follow both of your statements. Who has decided what exactly? There have been a number of options on the table and different people voiced opposition or agreement to some of them (I spare us quoting the details, because I'm 
*not* going to follow up). I could not see any clear project decision, only that there has not been a consensus. I've closed the topic back then because there was the tendency that a *contains* parameter won't be added.

*I still believe there's a usage deficit to be solved: The most common use case is a simple string comparision of the exception message, and that should be easy.*

The suggestion of a single exact-equality `msg` parameter *is* a new approach, and in the context of all above discussion appeared at least reasonable to bring up.


**On the communication side**

This is my personal impression. Take or leave this feedback as you like.

[Above](https://github.com/pytest-dev/pytest/issues/10085#issuecomment-2076740386), I summarized the state of the discussion and made a well-intended attempt to find a way forward for a minimal consensus.
[Your answer](https://github.com/pytest-dev/pytest/issues/10085#issuecomment-2077184377) sounds annoyed and angry, and I do not understand why. You're voice and wording signals to me that you fundamentally disapprove my contribution. Moreover, the second sentence insinuates that I'm not adding to the discussion and I'm too stubborn or dumb to see that. I perceive this as rude. This is not how I'm used to or want to communicate in the FOSS community.

On an additional note, thumping down carefully written comments without any further remark may be received as offensive as well. If you take the time to read the comment and bother to respond, I'd expect at least a short comment like "Thanks for your opinion, but please accept that I/we still do not want to change pytest.raises." or "... we're working on different approaches to make this easier".

**Comment by maximlt** [comment]
Another option might be to add a boolean `regex` keyword argument that is True by default. When set to False, regex matching is disabled in favor of the "contains" behavior suggested by the OP. Inspired by [`pandas.Series.str.contains`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.contains.html#pandas.Series.str.contains).
