### ISSUE TITLE
ImportError: No module named cov since 2.7.3

### ISSUE THREAD

**Issue by sebastianneubauer** [pytest-dev/pytest#1008]
I get an error since update to 2.7.3, pytest-cov is installed in the virtualenvironment:

```
Traceback (most recent call last):
  File "setup.py", line 209, in <module>
    setup_package()
  File "setup.py", line 206, in setup_package
    entry_points={'console_scripts': CONSOLE_SCRIPTS})
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/local/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/local/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "setup.py", line 88, in run_tests
    errno = pytest.main(**params)
  File "/local/lib/python2.7/site-packages/_pytest/config.py", line 32, in main
    config = _prepareconfig(args, plugins)
  File "/local/lib/python2.7/site-packages/_pytest/config.py", line 84, in _prepareconfig
    pluginmanager.consider_pluginarg(plugin)
  File "/local/lib/python2.7/site-packages/_pytest/core.py", line 298, in consider_pluginarg
    self.import_plugin(arg)
  File "/local/lib/python2.7/site-packages/_pytest/core.py", line 318, in import_plugin
    mod = importplugin(modname)
  File "/local/lib/python2.7/site-packages/_pytest/core.py", line 370, in importplugin
    __import__(importspec)
ImportError: No module named cov
```

any ideas? by downgrading to 2.7.2 it works again...

**Comment by The-Compiler** [comment]
Hm, odd - 2.7.3 works with pytest-cov in a virtualenv just fine for me.

Can you show the output of `pip freeze` in the virtualenv?

**Comment by sebastianneubauer** [comment]
I call pytest through setup.py, it seems to work if I call it directly via `py.test --cov package --cov-report term-missing`...that might be a hint...

**Comment by The-Compiler** [comment]
Any chance you could do a minimal example, or is the project you're having trouble with available somewhere? Being able to reproduce this will likely make it much easier to find out what's going on.

**Comment by sebastianneubauer** [comment]
here is a minimal setup.py that reproduces this bug:
```python
from setuptools import setup

import sys

from setuptools.command.test import test as TestCommand


class PyTest(TestCommand):
    user_options = [("cov=", None, "Run coverage")]

    def initialize_options(self):
        TestCommand.initialize_options(self)
        self.pytest_args = []
        self.cov = None

    def finalize_options(self):
        TestCommand.finalize_options(self)
        self.test_args = []
        self.test_suite = True

    def run_tests(self):
        #import here, cause outside the eggs aren't loaded
        import pytest
        params = {"args": self.test_args}
        params["plugins"] = ["cov"]
        errno = pytest.main(**params)
        sys.exit(errno)


setup(
    #...,
    tests_require=['pytest-cov','pytest'],
    cmdclass = {'test': PyTest},
    command_options={'test': {'cov': ('setup.py', 'weather_client')}}
    )
```
more specifically it is the line `params["plugins"] = ["cov"]` which worked before just fine but now fails...

**Comment by sebastianneubauer** [comment]
removing that line fixed the problem...and as it is legacy code, I also don't know why it was there...still might be interesting what change lead to the failure...

**Comment by The-Compiler** [comment]
I bisected this to 35bbcc39a28b3464612f1b4060b05877290794ff

Before, the argument was silently ignored - now, it actually works, so that's why you didn't see the error before.

So I think this can be closed.

/cc @nicoddemus

**Comment by nicoddemus** [comment]
Thanks for tracking it down @The-Compiler! :smile:

**Comment by mainframe2017** [comment]
Please help me out on this issue.

![capturejj](https://cloud.githubusercontent.com/assets/25217920/23585005/049b3832-0198-11e7-9d3b-3de57c70c50a.PNG)

**Comment by The-Compiler** [comment]
@mainframe2017 this seems like a syntax error in one of your python files, unrelated to pytest. The Python [tutor mailinglist](https://mail.python.org/mailman/listinfo/tutor) or [IRC channel](https://www.python.org/community/irc/) would be better places for those kind of questions though.
