### ISSUE TITLE
Misleading error message when parameters are missing in the parametrize but presented in the test function

### ISSUE THREAD

**Issue by TommyDew42** [pytest-dev/pytest#10113]
- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

I'm using pytest version 6.2.4.
Say we have the following function and a corresponding test function:
```python
# ./add.py
def add(n1, n2):
  return n1 + n2

# ./test_add.py
@pytest.mark.parametrize(
  "arg1, expected_answer",
  [pytest.param(2, 3, 5)]
)
def test_add(arg1, arg2, expected_answer):
  assert add(arg1, arg2) == expected_answer
```

Running `pytest ./test_add.py::test_add` logs the following error message:
```
ERROR: not found: ./test_add.py::test_add
(no name './test_add.py::test_add' in any of [<Module test_add.py>])
```

But actually it fails because `arg2` is not presented in the parametrize decorator.
Similar issue when the argument name is wrong.

**Comment by The-Compiler** [comment]
This is the full output:

```
============================= test session starts ==============================
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
_________________________ ERROR collecting test_add.py _________________________
test_add.py::test_add: in "parametrize" the number of names (2):
  ['arg1', 'expected_answer']
must be equal to the number of values (3):
  (2, 3, 5)
=========================== short test summary info ============================
ERROR test_add.py
=============================== 1 error in 0.04s ===============================
ERROR: not found: /home/florian/tmp/test_add.py::test_add
(no name '/home/florian/tmp/test_add.py::test_add' in any of [<Module test_add.py>])
```

seems quite clear from that what the error is, no?

**Comment by TommyDew42** [comment]
How much complexity will it bring to the codebase/logic if we want to explicitly display to user that `test_add` was found but it failed to run because there are errors in `parametrize`?
A simple hint will help a lot, e.g. `there are errors in the decorator parametrize. Please refer to the detailed error above`

If it is too complex, we can go for a simpler approach: use `"couldn't collect"` instead of `"not found"`

**Comment by Zac-HD** [comment]
We already report that explicitly - see "errors" in the output example above - so I think it's just fixing the "short test summary info" to avoid claiming that any failure to collect was because the test was not found.

**Comment by RonnyPfannschmidt** [comment]
currently we really cant know (as there wont be a collection  node with the name after collection) since parameterization failed

@The-Compiler i wonder if we could do a indirect parametrize with something that auto marks as "will fail"

alternatively we could have exceptions in generate_tests yield some node that always fails/indicates collection errors

**Comment by RonnyPfannschmidt** [comment]
yeah, its a unfortunate edge case, the error itself causes the item not to be "find-able"

what could help is taking a look at collection errors in requested paths and adding a note that a collection error was in the related files

however thats also tricky, so I'd put it in at low prio

**Comment by jekwatt** [comment]
I was able to duplicate the error.  Working to fix the error message.

**Comment by The-Compiler** [comment]
As per https://github.com/pytest-dev/pytest/pull/10145#issuecomment-1670239803 I think a fix for this makes the message far more confusing for a way more common case. Thus, closing this.
