### ISSUE TITLE
`tmpdir` cannot be safely used as a stand-in for a `Path` type

### ISSUE THREAD

**Issue by komodovaran** [pytest-dev/pytest#10136]
The `tmpdir` fixture uses `py._path.local.LocalPath` which seemingly acts like a normal `Path` for the unsuspecting. However, I found that it broke a test that called `st_mtime` property, e.g. it can be provoked like so:

```python
from py._path.local import LocalPath

LocalPath().stat().st_mtime
```

which gives
```python
  File "/opt/miniconda3/envs/prod/lib/python3.10/site-packages/py/_path/local.py", line 28, in __getattr__
    return getattr(self._osstatresult, "st_" + name)
AttributeError: 'os.stat_result' object has no attribute 'st_st_mtime'. Did you mean: 'st_mtime'?
```

whereas the following works
```python
from pathlib import Path

Path().stat().st_mtime
```

Since https://py.readthedocs.io/en/latest/path.html says the module is in maintenance mode, I thought it would make more sense to tackle the problem within Pytest.

* Python 3.10.5
* Pytest 7.1.2

**Comment by RonnyPfannschmidt** [comment]
closing as already solved
