### ISSUE TITLE
PyTest MonkeyPatch.syspath_prepend persisting between test functions despite function scope

### ISSUE THREAD

**Issue by mgb-ingenuity** [pytest-dev/pytest#10142]
I'm in a situation where I need to test code that uses a library that can't be imported outside of its proprietary runtime environment.

My solution to this: use monkeypatch's syspath_prepend function to patch in a stub library that mimics the proprietary library's API. This works in the forward direction - I can indeed mock the library, and import it where without a mock I normally could not.

**However**, this change persists beyond the function in which I perform the mock - if I mock the library in one test function, it stays mocked in all other functions. This is very bad.

Here's the code - the second test function does not raise a ModuleNotFound error, where I would expect it to.

**NOTE** - the second test will succeed if I only run it and not the first test. It only fails if I run the entire test module as a whole.

```
import pytest


@pytest.fixture(scope="function")
def useFakeLib(monkeypatch):
    monkeypatch.syspath_prepend("path/to/mockLib")


def test_can_import_fake_lib_via_conftest(useFakeLib):
    # Works!
    import proprietary_lib # imports API from mock library, not proprietary library
    assert proprietary_lib.fakeFunction() == "I am fake."



def test_proprietary_lib_is_not_normally_on_path():
    # Not using useFakeLib fixture, so mockLib should not be on path.
    # Fails
    with pytest.raises(ModuleNotFoundError):
        import proprietary_lib 
```

**pytest and operating system versions:** 
platform win32 -- Python 3.7.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- c:\Python37\python.exe

<details open>
<summary><strong>output of `pip list`</strong></summary><br>
Package                       Version<br>
----------------------------- -----------<br>
aiohttp                       3.8.1<br>
aiosignal                     1.2.0<br>
aiosmtplib                    1.1.6<br>
alabaster                     0.7.12<br>
altgraph                      0.17.2<br>
amqp                          5.0.9<br>
anyio                         3.5.0<br>
appdirs                       1.4.4<br>
argon2-cffi                   21.3.0<br>
argon2-cffi-bindings          21.2.0<br>
asgiref                       3.5.0<br>
async-timeout                 4.0.2<br>
asynctest                     0.13.0<br>
atomicwrites                  1.4.0<br>
attrs                         21.4.0<br>
Babel                         2.9.1<br>
backcall                      0.2.0<br>
backports.zoneinfo            0.2.1<br>
beautifulsoup4                4.11.1<br>
billiard                      3.6.4.0<br>
black                         22.1.0<br>
bleach                        4.1.0<br>
blurhash                      1.1.4<br>
boost                         0.1<br>
cached-property               1.5.2<br>
celery                        5.2.3<br>
certifi                       2021.10.8<br>
cffi                          1.15.0<br>
charset-normalizer            2.0.11<br>
chevron                       0.14.0<br>
click                         8.0.3<br>
click-didyoumean              0.3.0<br>
click-plugins                 1.1.1<br>
click-repl                    0.2.0<br>
cloudpickle                   2.0.0<br>
colorama                      0.4.4<br>
commentjson                   0.9.0<br>
coverage                      6.3.2<br>
css-html-js-minify            2.5.5<br>
cycler                        0.11.0<br>
darglint                      1.8.1<br>
dask                          2022.2.0<br>
dateparser                    1.1.0<br>
debugpy                       1.5.1<br>
decorator                     5.1.0<br>
defusedxml                    0.7.1<br>
Deprecated                    1.2.13<br>
dill                          0.3.4<br>
dnspython                     2.2.0<br>
docutils                      0.17.1<br>
email-validator               1.2.1<br>
entrypoints                   0.4<br>
eventlet                      0.33.0<br>
execnet                       1.9.0<br>
exrex                         0.10.5<br>
Faker                         13.11.1<br>
fastapi                       0.73.0<br>
fastjsonschema                2.15.3<br>
ffmpeg-python                 0.2.0<br>
filelock                      3.6.0<br>
fissix                        21.11.13<br>
flake8                        4.0.1<br>
fonttools                     4.29.0<br>
frozenlist                    1.3.0<br>
fsspec                        2022.2.0<br>
furo                          2022.4.7<br>
future                        0.18.2<br>
gevent                        21.12.0<br>
git-filter-repo               2.34.0<br>
greenlet                      1.1.2<br>
groundwork-sphinx-theme       1.1.1<br>
grpcio                        1.43.0<br>
h11                           0.13.0<br>
httptools                     0.2.0<br>
idna                          3.3<br>
imagesize                     1.3.0<br>
importlib-metadata            4.8.2<br>
importlib-resources           3.3.1<br>
iniconfig                     1.1.1<br>
ipykernel                     6.9.1<br>
ipython                       7.31.1<br>
ipython-genutils              0.2.0<br>
ipywidgets                    7.6.5<br>
itsdangerous                  2.1.2<br>
jedi                          0.18.1<br>
Jinja2                        3.0.3<br>
json5                         0.9.6<br>
jsonschema                    4.4.0<br>
jupyter                       1.0.0<br>
jupyter-client                7.1.2<br>
jupyter-console               6.4.0<br>
jupyter-core                  4.9.1<br>
jupyter-server                1.17.0<br>
jupyterlab                    3.2.9<br>
jupyterlab-pygments           0.1.2<br>
jupyterlab-server             2.10.3<br>
jupyterlab-widgets            1.0.2<br>
keyring                       23.5.0<br>
kiwisolver                    1.3.2<br>
kombu                         5.2.3<br>
lark-parser                   0.7.8<br>
libcst                        0.4.1<br>
livereload                    2.6.3<br>
locket                        0.2.1<br>
logzero                       1.7.0<br>
lxml                          4.8.0<br>
m2r2                          0.3.2<br>
markdown-it-py                1.1.0<br>
MarkupSafe                    2.0.1<br>
Mastodon.py                   1.5.1<br>
matplotlib                    3.5.1<br>
matplotlib-inline             0.1.3<br>
mccabe                        0.6.1<br>
mdformat                      0.7.14<br>
mdformat_deflist              0.1.1<br>
mdformat_frontmatter          0.4.1<br>
mdformat_myst                 0.1.4<br>
mdformat_tables               0.4.1<br>
mdit-py-plugins               0.3.0<br>
mdurl                         0.1.1<br>
mistune                       0.8.4<br>
modernize                     0.8.0<br>
MonkeyType                    21.5.0<br>
msgpack                       1.0.3<br>
multidict                     6.0.2<br>
mypy                          0.931<br>
mypy-extensions               0.4.3<br>
myst-parser                   0.17.2<br>
nbclassic                     0.3.5<br>
nbclient                      0.5.11<br>
nbconvert                     6.5.0<br>
nbformat                      5.4.0<br>
nest-asyncio                  1.5.4<br>
notebook                      6.4.8<br>
numpy                         1.21.5<br>
orjson                        3.7.5<br>
packaging                     21.3<br>
pandarallel                   1.6.1<br>
pandas                        1.1.5<br>
pandocfilters                 1.5.0<br>
parso                         0.8.3<br>
partd                         1.2.0<br>
pathspec                      0.9.0<br>
pefile                        2021.9.3<br>
pickleshare                   0.7.5<br>
pigar                         0.10.0<br>
Pillow                        9.0.0<br>
pip                           22.1.2<br>
pkginfo                       1.8.2<br>
platformdirs                  2.4.1<br>
pluggy                        1.0.0<br>
prometheus-client             0.13.1<br>
prompt-toolkit                3.0.28<br>
protobuf                      3.19.4<br>
psutil                        5.9.0<br>
py                            1.11.0<br>
pyarrow                       6.0.1<br>
pycodestyle                   2.8.0<br>
pycparser                     2.21<br>
pydantic                      1.9.0<br>
pydantic-factories            1.3.0<br>
pydocstyle                    6.1.1<br>
pyflakes                      2.4.0<br>
Pygments                      2.11.2<br>
pyinstaller                   4.10<br>
pyinstaller-hooks-contrib     2022.2<br>
PyOpenGL                      3.1.5<br>
pyparsing                     3.0.7<br>
pyrsistent                    0.18.1<br>
PySide2                       5.15.2.1<br>
pytest                        6.2.5<br>
pytest-forked                 1.4.0<br>
pytest-html                   3.1.1<br>
pytest-metadata               1.11.0<br>
pytest-monkeytype             1.1.0<br>
pytest-qt                     4.0.2<br>
pytest-reportlog              0.1.2<br>
pytest-timeout                2.1.0<br>
pytest-xdist                  2.5.0<br>
python-dateutil               2.8.2<br>
python-dotenv                 0.19.2<br>
python-magic                  0.4.24<br>
python-multipart              0.0.5<br>
python-slugify                6.1.2<br>
pytz                          2021.3<br>
pytz-deprecation-shim         0.1.0.post0<br>
pywin32                       303<br>
pywin32-ctypes                0.2.0<br>
pywinpty                      1.1.6<br>
PyYAML                        6.0<br>
pyzmq                         22.3.0<br>
qtconsole                     5.2.2<br>
QtPy                          2.0.1<br>
ray                           1.11.0<br>
readme-renderer               32.0<br>
redis                         4.1.3<br>
regex                         2022.3.2<br>
requests                      2.27.1<br>
requests-toolbelt             0.9.1<br>
rfc3986                       2.0.0<br>
rst-to-myst                   0.3.2<br>
ruamel.yaml                   0.17.21<br>
ruamel.yaml.clib              0.2.6<br>
semver                        2.13.0<br>
Send2Trash                    1.8.0<br>
setuptools                    59.6.0<br>
sgtk                          dev<br>
shiboken2                     5.15.2.1<br>
shotgun-api3                  3.3.3<br>
six                           1.16.0<br>
sniffio                       1.2.0<br>
snowballstemmer               2.2.0<br>
soupsieve                     2.3.2.post1<br>
spark-parser                  1.8.9<br>
Sphinx                        4.5.0<br>
sphinx-autobuild              2021.3.14<br>
sphinx-material               0.0.35<br>
sphinx-pdj-theme              0.2.1<br>
sphinx-rtd-theme              1.0.0<br>
sphinxcontrib-applehelp       1.0.2<br>
sphinxcontrib-devhelp         1.0.2<br>
sphinxcontrib-htmlhelp        2.0.0<br>
sphinxcontrib-jsmath          1.0.1<br>
sphinxcontrib-qthelp          1.0.3<br>
sphinxcontrib-serializinghtml 1.1.5<br>
SQLAlchemy                    1.4.31<br>
starlette                     0.17.1<br>
StrEnum                       0.4.7<br>
tbb                           2021.5.1<br>
terminado                     0.13.1<br>
testpath                      0.5.0<br>
text-unidecode                1.3<br>
tinycss2                      1.1.1<br>
tokenize-rt                   4.2.1<br>
toml                          0.10.2<br>
tomli                         2.0.0<br>
toolz                         0.11.2<br>
tornado                       6.1<br>
tqdm                          4.62.3<br>
traitlets                     5.1.1<br>
twine                         3.8.0<br>
typed-ast                     1.5.2<br>
typing_extensions             4.0.1<br>
typing-inspect                0.7.1<br>
tzdata                        2021.5<br>
tzlocal                       4.1<br>
ujson                         5.4.0<br>
uncompyle6                    3.8.0<br>
Unidecode                     1.3.4<br>
urllib3                       1.26.8<br>
usd-core                      21.11<br>
uvicorn                       0.15.0<br>
vine                          5.0.0<br>
Wand                          0.6.7<br>
watchgod                      0.7<br>
wcwidth                       0.2.5<br>
webencodings                  0.5.1<br>
websocket-client              1.2.3<br>
websockets                    10.1<br>
widgetsnbextension            3.5.2<br>
wrapt                         1.13.3<br>
xdis                          6.0.3<br>
xmltodict                     0.13.0<br>
yarl                          1.7.2<br>
zipp                          3.7.0<br>
zope.event                    4.5.0<br>
zope.interface                5.4.0<br>
<br>
</details>

**Comment by RonnyPfannschmidt** [comment]
This is expected python behaviour

**Comment by Zac-HD** [comment]
Try using `yield` and cleaning up afterwards.
