### ISSUE TITLE
use vdbench tool run long time IO test, io break off

### ISSUE THREAD

**Issue by linglingfa1212** [pytest-dev/pytest#10153]
Hi Devs,
Recently, i an in trouble. In my scenario, i got IO test break off issue. I ran 7*24 disk IO test in linux server by vdbench, and it worked well. But if i start vdbench tool commander in pytest, the IO test always break off after about 48 hours later. So what's the root issue?
I troubleshoot several ways to find the root issue, but all ways not work.
During IO test, i sometimes login to the server to see the io report and io process for keeping it work well. But sometimes checked the io process like flow:
![image](https://user-images.githubusercontent.com/38340208/179654145-cb62a7dd-b440-4db9-a0d3-644fac551926.png)
Only main vdbench proces alived, slave process were dead.
And then, i checked pytest process.
![image](https://user-images.githubusercontent.com/38340208/179654368-ac133a40-c3c4-454f-9a0f-8838a6d97f67.png)

**Comment by Zac-HD** [comment]
Can you reproduce this without vdbench?  Have you reported this *to* vdbench?

As a volunteer open-source project, Pytest devs do not have the resources to help unless you can clearly identify a problem in pytest itself.

**Comment by linglingfa1212** [comment]
> Can you reproduce this without vdbench? Have you reported this _to_ vdbench?
> 
> As a volunteer open-source project, Pytest devs do not have the resources to help unless you can clearly identify a problem in pytest itself.

Hi zac, i ran vdbench command on linux server without pytest. The IO test work well.
One scenario, i run pytest commander, and code is like this:
![image](https://user-images.githubusercontent.com/38340208/179659081-de1040ba-5f0b-46ff-88d3-67bd102fb791.png)
![1658201886339](https://user-images.githubusercontent.com/38340208/179659324-c05ba1ea-ecab-429f-b079-33c80707b6e2.jpg)
And this issue appeard.
The second scenario, i directly ran vdbench command on linux server like this:
/root/vdbench/vdbench -f /root/vdbench/vd_config -jn -o /root/vdbench/output -vr
IO test works well during 7*24 hours.
I think is there some sets like timeout or others, break off the IO?

**Comment by Zac-HD** [comment]
Closing as stale; maybe try StackOverflow?
