### ISSUE TITLE
@pytest.mark.parametrize incorrectly caches results, resulting in incorrect test results

### ISSUE THREAD

**Issue by TimMeiwald** [pytest-dev/pytest#10162]
Since this is for a public project I'm writing I've linked the git repo. The readme contains reproduction steps as well as this report(so it's clear I made an effort).  https://github.com/TimMeiwald/PackratParserGenerator

git clone
run commands in BuildInstructions.txt
Navigate to tests\test_grammar_parser\test_Var_Name.py
Run pytest, note how only "FAILED tests/test_grammar_parser/test_Sequence.py::Test_Sequence::test_Sequence[<This_is_a_name>, <Another_Name>-answer5]" fails
Remove the """ around the parameterized test.
Run pytest, note how
FAILED tests/test_grammar_parser/test_Var_Name.py::Test_Var_Name::test_A - as...
FAILED tests/test_grammar_parser/test_Var_Name.py::Test_Var_Name::test_B - as...
These tests previously passed when the parameterized test was commented out.

Also note how running the copy of the code beneath the if name == "main" works fine.
Since I'm using an LRU_Cache in the code I've checked I'm clearing cache and printed out cache info to verify. Does not seem to solve
the issue. 
Have also checked that the functools lru_cache is getting cleared by using print(.cache_info()) Should also clear in _set_src and also added a seperate clear_cache in the test.

On windows 10, version "10.0.19041.1806"
Also fails on Githubs Ubuntu runner more details in workflow file

See Github actions test runs "Commented" and "Uncommented" for evidence of Ubuntu runners failure.

Have tried rolling back pytest to 7.0.0, didn't work
Have tried setting up venv again and reinstalling pytest, didn't work

**Comment by The-Compiler** [comment]
The `gparser` fixture in your `conftest.py` is defined with a `module` caching scope: https://github.com/TimMeiwald/PackratParserGenerator/blob/main/tests/conftest.py

**Comment by The-Compiler** [comment]
Sorry, I was perhaps a bit too fast with closing this (though it really doesn't seem like a pytest bug at all). Reopening for now, but it's very likely the culprit is your code caching that fixture.

**Comment by TimMeiwald** [comment]
Changing scope did fix my issue.
I'm curious as to why though. 
The gparser is just the class instance and has no input until _set_src is called so theoretically there shouldn't be an issue unless it's because I've failed to clear cache properly somewhere. 

Either way that fixed my issue, so feel free to close. 
My apologies for not figuring that out earlier.

**Comment by The-Compiler** [comment]
Given that you have a `@cache` pretty much *everywhere*, that seems likely. As the saying goes, there are two hard problems when programming: Naming things, cache invalidation, and off-by-one errors :wink:

Unless you profiled your code and determined that to be a performance hotspot, I'd really recommend just not doing that at all.
