### ISSUE TITLE
Support addopts syntax applied to multiple lines

### ISSUE THREAD

**Issue by jxramos** [pytest-dev/pytest#10176]
#### What's the problem this feature will solve?

To make the `pytest.ini` files more diffable and mergable by breaking out long option lines into individual lines per option.

#### Describe the solution you'd like

Support the following syntax in `pytest.ini` files

go from this...
```ini
addopts = --strict-markers --log-file=pytest_debug.log --log-file-level=DEBUG --log-file-format='%(asctime)s - %(threadName)s [%(levelname)s] %(module)s.%(funcName)s  %(message)s'
```

to this
```ini
addopt = --strict-markers
addopt = --log-file=pytest_debug.log
addopt = --log-file-level=DEBUG --log-file-format='%(asctime)s - %(threadName)s [%(levelname)s] %(module)s.%(funcName)s  %(message)s'
```

So essentially having the options break out one line per option.

#### Alternative Solutions

An alternative solution is to put the options back at the command line and to use the line continuation, eg

```bash
pytest --strict-markers \
       --log-file=pytest_debug.log \
...
```

**Comment by RonnyPfannschmidt** [comment]
Multiline adopts should already be supported by indenting the next lines


Using the Same key multiple times won't be supported

**Comment by jxramos** [comment]
Very good!

So the multiple key error was what I originally faced with something like `ERROR: /home/USERX/test_proj/pytest.ini:9: duplicate name 'addopts'`

that next span of indented lines works like a charm! I'm not sure if this is general ini syntax (doesn't appear to be https://stackoverflow.com/a/29194027/1330381) but this is worth expanding the documentation to include a multiline example.

```ini
addopts =
    --strict-markers
    --log-file=pytest_debug.log
    --log-file-level=DEBUG
    --log-file-format='%(asctime)s - %(threadName)s [%(levelname)s] %(module)s.%(funcName)s  %(message)s'
```
