### ISSUE TITLE
TypeError: attr() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by vinitpayal** [pytest-dev/pytest#10200]
PyTest failing with error `attr() got an unexpected keyword argument 'type'.`

**Error Stack Trace**

> **Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/usr/local/lib/python3.9/site-packages/pytest/__init__.py", line 3, in <module>
    from . import collect
  File "/usr/local/lib/python3.9/site-packages/pytest/collect.py", line 8, in <module>
    from _pytest.deprecated import PYTEST_COLLECT_MODULE
  File "/usr/local/lib/python3.9/site-packages/_pytest/deprecated.py", line 13, in <module>
    from _pytest.warning_types import PytestDeprecationWarning
  File "/usr/local/lib/python3.9/site-packages/_pytest/warning_types.py", line 120, in <module>
    class UnformattedWarning(Generic[_W]):
  File "/usr/local/lib/python3.9/site-packages/_pytest/warning_types.py", line 127, in UnformattedWarning
    category = attr.ib(type=Type["_W"])
TypeError: attr() got an unexpected keyword argument 'type'**

**Package dependency list** 

```
Package                  Version
------------------------ ---------
aiohttp                  3.8.1
aiosignal                1.2.0
async-timeout            4.0.2
attrs                    22.1.0
cachetools               4.2.4
certifi                  2022.6.15
charset-normalizer       2.1.0
click                    8.1.3
decorator                5.1.1
Flask                    2.0.1
Flask-Cors               3.0.10
frozenlist               1.3.1
fsspec                   2021.5.0
gcsfs                    2021.5.0
google-api-core          1.32.0
google-auth              1.35.0
google-auth-oauthlib     0.5.2
google-cloud-bigquery    2.17.0
google-cloud-core        1.7.3
google-cloud-datastore   2.1.3
google-cloud-kms         2.2.0
google-cloud-storage     1.38.0
google-cloud-tasks       2.2.0
google-crc32c            1.3.0
google-resumable-media   1.3.3
googleapis-common-protos 1.56.4
grpc-google-iam-v1       0.12.4
grpcio                   1.47.0
gunicorn                 20.1.0
idna                     3.3
iniconfig                1.1.1
itsdangerous             2.1.2
Jinja2                   3.1.2
libcst                   0.4.7
MarkupSafe               2.1.1
multidict                6.0.2
mypy-extensions          0.4.3
numpy                    1.20.3
oauthlib                 3.2.0
packaging                21.3
pandas                   1.1.5
pip                      22.2.2
pluggy                   0.13.1
proto-plus               1.20.6
protobuf                 3.20.1
py                       1.11.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pyparsing                3.0.9
pytest                   7.1.2
python-dateutil          2.8.1
pytz                     2022.1
PyYAML                   6.0
requests                 2.28.1
requests-oauthlib        1.3.1
rsa                      4.9
setuptools               63.1.0
six                      1.16.0
toml                     0.10.2
tomli                    2.0.1
typing_extensions        4.3.0
typing-inspect           0.7.1
urllib3                  1.26.11
uuid                     1.30
Werkzeug                 2.2.2
wheel                    0.37.1
yarl                     1.8.1
```

Tried various combinations, without any success
- Downgrade attrs to 19.1.2
- Downgrading PyTest to 7.1.0

**Comment by nicoddemus** [comment]
Hi @vinitpayal,

The line in the traceback you posted:

```
File "/usr/local/lib/python3.9/site-packages/_pytest/warning_types.py", line 127, in UnformattedWarning
category = attr.ib(type=Type["_W"])
```

Does not match the same line in the 7.1.2 release:

https://github.com/pytest-dev/pytest/blob/2f2f1a601e33aa1a77de42f164ba4b642252f1c0/src/_pytest/warning_types.py#L124-L134 

Please double check if you have the actual versions installed.

**Comment by The-Compiler** [comment]
The code in that traceback got removed in e5468681b0ed125cc6bb0deed9ce9db6077a3256 which was part of 7.0.0, so it looks like OP is actually running 6.2.5 or so: https://github.com/pytest-dev/pytest/blob/6.2.5/src/_pytest/warning_types.py#L127

Also, `attr.ib(type=...)` exists in the specified attrs version ([added in 2017](https://www.attrs.org/en/stable/changelog.html#id200)):

```pycon
>>> import attr
>>> attr.__version__
'22.1.0'
>>> attr.ib(type=int)
_CountingAttr(counter=22, _default=NOTHING, repr=True, eq=True, order=True, hash=None, init=True, on_setattr=None, metadata={})
```

So this looks like a misconfigured and outdated environment rather than a pytest problem. Taking the freedom to close this.
