### ISSUE TITLE
Enable choosing the import mode in pyproject.toml

### ISSUE THREAD

**Issue by a-gn** [pytest-dev/pytest#10201]
#### What's the problem this feature will solve?
My tests currently only work with `--import-mode=importlib` because multiple test files have identical names. I would like to keep doing that because these files concern totally different parts of the project.

Since this is not yet the default mode, VSCode's testing UI cannot shows a discovery error in this project.

#### Describe the solution you'd like

I want to configure the import mode by adding the following to `pyproject.toml`:

```toml
[tool.pytest.ini_options]
import_mode = "importlib"
```

#### Alternative Solutions

I tried to add `import_mode = "importlib"` to `pyproject.toml`'s `[tool.pytest.ini_options]` section, with no effect. Other settings like `pythonpath` and `testpaths` do have an effect. I couldn't find a setting in the docs that does what I want.

I could keep configuring all environments on a per-project basis, but some IDEs don't support this (VSCode's `python.testing.pytestArgs` setting seems to affect test runs, but not test discovery). Also, the import mode is a project-specific decision that impacts the test layout, hence it should be provided by the project and not by the developer's environment.

**Comment by The-Compiler** [comment]
`addopts` lets you persist any command line option in the pytest config file, so I don't think such a change would be needed.

**Comment by a-gn** [comment]
This fixed it, thanks! I hadn't seen this setting.
