### ISSUE TITLE
Warning due to PEP660 editable packages

### ISSUE THREAD

**Issue by fschulze** [pytest-dev/pytest#10235]
The recently added PEP660 support for editable package installs seems to interfere with assert rewriting. I get the following warning:

``PytestAssertRewriteWarning: Module already imported so cannot be rewritten: __editable__...``

This seems to be caused by the new ``__editable__*`` files in ``site-packages``.

If I install the editable packages with ``--no-use-pep517`` the ``__editable__*`` files aren't generated and the warnings are gone.

**Comment by RonnyPfannschmidt** [comment]
closing as dupe of #10230 , which is easy to miss as the same

**Comment by fschulze** [comment]
I actually saw that and didn't realize it has the same cause.
