### ISSUE TITLE
document: 'identify flaky tests' link 404

### ISSUE THREAD

**Issue by LeiYangGH** [pytest-dev/pytest#10244]
in page 
https://docs.pytest.org/en/stable/explanation/flaky.html
there's link [identify flaky tests](https://docs.microsoft.com/en-us/azure/devops/release-notes/2017/dec-11-vsts#identify-flaky-tests)
currently return 404.

**Comment by Zac-HD** [comment]
Given that the page is gone, I think we should just delete that whole "CI tools that rerun on failure" section.

**Comment by Zoorken** [comment]
The commit I prepared could be made into a pull request if the section still adds value.

I follow the [preparing-pull-requests](https://github.com/pytest-dev/pytest/blob/main/CONTRIBUTING.rst#preparing-pull-requests) when making the commit

Please guide me if I missed a step

**Comment by nicoddemus** [comment]
@Zoorken great that you found the original link, feel free to open a PR with that commit!
