### ISSUE TITLE
--durations VS timeit : discrepancy with xarray

### ISSUE THREAD

**Issue by robin-cls** [pytest-dev/pytest#10242]
Hello !

I am reporting a strange behavior concerning pytest and xarray. The setup consists in having a simple xr.open_dataset called in the test
```pytest_durations.py
import glob
import xarray as xr
import numpy as np
import pytest
import os
import timeit

@pytest.fixture(scope="session")
def create_netcdf():
    da = xr.DataArray(np.ones((500, 500)))
    da.to_netcdf("TEST.nc")
    yield
    os.remove("TEST.nc")

def test_1(create_netcdf):
    callee()

def callee():
    xr.open_dataset("TEST.nc")

if __name__ == "__main__":
    da = xr.DataArray(np.ones((500, 500)))
    da.to_netcdf("TEST.nc")
    print(f"{timeit.timeit(callee, number=10) / 10:.3f}s")
    os.remove("TEST.nc")
```

This xr.open_dataset time duration is measured in two ways, using either pytest or timeit :
- pytest pytest_durations.py --durations=0 
- python pytest_durations.py

What I found is the following :
- pytest -> 0.42s
- python main -> 0.06s

What is strange is that this discrepancy seems to be linked to xarray. Switching to another callee that relies on numpy only gives consistent results :
```python
def callee():
    # Another call without xarray
    A = np.ones((1000, 1000))
    A + A**2 + A**3 + A**4
```
- pytest -> 0.07s
- python main -> 0.065s

So it seems pytest is slower at running xr.open_dataset with respect to a notebook or a classic python interpreter.Do you have any idea why ?

**Comment by robin-cls** [comment]
The discrepency comes from using timeit : xarray seems remember opening the same file 10 times in a row. Replacing time by 
```
start = time.time()
callee()
print(time.time() - start)
```
does the trick

**Comment by RonnyPfannschmidt** [comment]
Thanks for the follow up, caching sometimes happens in surprise locations 😁
