### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by Vchenhailong** [pytest-dev/pytest#10240]
- invoking `pytest -m ....` throws an ERROR , cuz I used union-type in functions.
> https://docs.python.org/3/library/stdtypes.html#union-type

- platform infos:
 Test session starts (platform: darwin, Python 3.9.9, pytest 7.1.2, pytest-sugar 0.9.4)

![image](https://user-images.githubusercontent.com/14884326/186310642-5fa40ce0-4c3c-417a-9626-e547ab8382ad.png)

Error Infos Screenshot as below:

![image](https://user-images.githubusercontent.com/14884326/186309299-8819f0a6-e509-4020-bda3-baa368e3105f.png)

**Comment by RonnyPfannschmidt** [comment]
That's a user error, the syntax is supposed to be used with python 3.10 or by enabling the annotations future

**Comment by Vchenhailong** [comment]
> That's a user error, the syntax is supposed to be used with python 3.10 or by enabling the annotations future

Thank you for your prompt reply! I’ve found it's my problem.

**Comment by Vchenhailong** [comment]
Is it a problem ? I don't know why it doesn't work when only invoke `pytest`.

Here are some infos in my MacOS.

`sys.version_info(major=3, minor=10, micro=5, releaselevel='final', serial=0)`

![image](https://user-images.githubusercontent.com/14884326/186367381-ecba1847-7fd5-4a44-acb1-ce0fa6351574.png)

![image](https://user-images.githubusercontent.com/14884326/186367317-519c4c25-4e6b-44c5-a7cc-c6f189f51601.png)

**Comment by The-Compiler** [comment]
You probably have multiple installs of `pytest`, and aren't executing the one you think you are - see `which pytest` to see which one gets picked up. It will be the first one found in your `$PATH`.

**Comment by Vchenhailong** [comment]
> You probably have multiple installs of `pytest`, and aren't executing the one you think you are - see `which pytest` to see which one gets picked up. It will be the first one found in your `$PATH`.

Gotcha, Thanks !     🥇
