### ISSUE TITLE
pytest.warn doesn't appear to be working for deprecation warnings

### ISSUE THREAD

**Issue by alex** [pytest-dev/pytest#1026]
I'm not sure what to make of this, but it appears to be failing on a very simple test:

```
(tempenv-6cb925871591c) ~/.v/tempenv-6cb925871591c $ cat t.py
import warnings

import pytest


def test_foo():
    with pytest.warns(PendingDeprecationWarning):
        warnings.warn("msg", PendingDeprecationWarning)
(tempenv-6cb925871591c) ~/.v/tempenv-6cb925871591c $ py.test t.py
====================================================== test session starts =======================================================
platform darwin -- Python 2.7.10, pytest-2.8.0, py-1.4.30, pluggy-0.3.1
rootdir: /Users/alex_gaynor/.virtualenvs/tempenv-6cb925871591c, inifile:
collected 1 items

t.py F

============================================================ FAILURES ============================================================
____________________________________________________________ test_foo ____________________________________________________________

    def test_foo():
        with pytest.warns(PendingDeprecationWarning):
>           warnings.warn("msg", PendingDeprecationWarning)
E           Failed: DID NOT WARN

t.py:8: Failed
==================================================== 1 failed in 0.01 seconds ====================================================
```

**Comment by The-Compiler** [comment]
This is because Python ignores `DeprecationWarning` and `PendingDeprecationWarning` by default, so in fact there *is no* warning above.

Your above snippet works fine when using `warnings.simplefilter("always")`, so I think everything works like it should.

**Comment by RonnyPfannschmidt** [comment]
after reconsidering, its not a bug on our side, see #1032 for a potential help

we should document that detail

**Comment by Akasurde** [comment]
@RonnyPfannschmidt  I would like to help in this.

**Comment by nicoddemus** [comment]
@Akasurde on documenting the detail about `DeprecationWarning`?

**Comment by Akasurde** [comment]
@RonnyPfannschmidt Yes, I would like to help on documenting. Let me know details about this.

**Comment by nicoddemus** [comment]
Opening a PR with the appropriate changes in the docs is the way to go (you can even do this directly from the GitHub interface). We are planning on a `2.8.1` release real soon (probably Monday), so now would be a good time to get this in. :smile:
