### ISSUE TITLE
[Docs] "simple values" term

### ISSUE THREAD

**Issue by bazabaza** [pytest-dev/pytest#1027]
https://github.com/pytest-dev/pytest/blob/3bcda48ba4a1305a15c4e7dc9b1f12536566ecee/_pytest/python.py#L915
"Simple values" is something not very clear
In that context "simple" is understood as  oposition to tuple
But it's not right. Tuple of course can be used even if number argnames is 1.

**Comment by bazabaza** [comment]
Let's just remove the word "simple"

**Comment by nicoddemus** [comment]
Would you care to provide a PR with the wording you find more adequate? :smile:
