### ISSUE TITLE
pytest ignoring python path in pytest.ini

### ISSUE THREAD

**Issue by msrosenberg** [pytest-dev/pytest#10282]
I have a pytest.ini file to point my test code to the source code. The file is in the test directory. I am running this within PyCharm

With pytest 7.1.2, tests run and work as expected
With pytest 7.1.3, tests raise errors as they are unable to import/access the source code

It is possible this is not pytest error, per se, but might be an interaction between PyCharm and pytest 7.1.3 for some odd reason.

**Comment by RonnyPfannschmidt** [comment]
Without more details it's impossible to reproduce
