### ISSUE TITLE
Don't run tests from git submodules or worktrees

### ISSUE THREAD

**Issue by adigitoleo** [pytest-dev/pytest#10298]
#### What's the problem this feature will solve?

Currently, `pytest` will try to recursively discover test files when collecting tests. I ran into an issue of pytest throwing errors from `parser_addoption` due to having a `git-worktree` subdirectory in my project with duplicates of test files and `conftest.py`. I don't use git sumbodules but I assume there would be similar implications.

#### Describe the solution you'd like

While the `norecursedirs` option provides a manual solution, I propose that the least surprising default for pytest would be to ignore any git submodules or worktrees. I can't think of a situation where running test files from inside those would be helpful, but I suppose an explicit option to allow recursing into such subdirectories could be added.

- clone a repo that uses `pytest` for testing
- `mkdir alt-git-checkout && git worktree add alt-git-checkout my-other-branch`
- oh, wait I want to test the original checkout: run `pytest`
- pytest collects duplicate test files from within `alt-git-checkout` leading to potential conflicts

Information about submodule/worktree paths can be obtained from the project root via:
- `.git/worktrees`
- `.git/modules`

Could the paths listed in those places be excluded by default from test discovery?

There are also `git subtrees` but I think they are included via explicit merges into the main project, so maybe it would not make sense to exclude them? I have never used those so I'm not sure.

#### Alternative Solutions

The mentioned `norecursedirs` option is a manual solution, and for worktrees it is also possible to simply move them outside the original tree to a different location, which is maybe a smarter way to use them (I'm still learning). Still, I see only benefits in avoiding to run tests from nested git projects.

**Comment by adigitoleo** [comment]
I'm happy to work on adding this if it the proposal is acceptable. I'm only not sure if I'm allowed to run git commands in the tests, because to properly test this I'd need to run some kind of `git add worktree` command during the tests.

**Comment by RonnyPfannschmidt** [comment]
This is out of scope for pytest
It may be fine as a 3rd party plugin

**Comment by adigitoleo** [comment]
OK no problem, I'll see if I get around to making a plugin.
