### ISSUE TITLE
Public API for `DoctestItem`

### ISSUE THREAD

**Issue by tony** [pytest-dev/pytest#10312]
I assume by `DoctestItem` only being available from `_pytest.doctest.DoctestItem`, it's an internal / unstable API.

If I'm completely mistaken in that assumption please let me know

#### What's the problem this feature will solve?
Stable import for:
- `isinstance` checking inside of autorun setup fixtures w/ `doctest_namespace` (see my libtmux, libvcs examples, as well and cs.github.com search query)
- other plugins re-using `DoctestItem`, e.g. my docutils plugin

#### Describe the solution you'd like
Perhaps `pytest.DoctestItem` or something of the sort

#### Alternative Solutions
Further battle-testing of `pytest`'s doctest plugin to stabilize the API, then exporting it

#### Additional context
I am using `DoctestItem` on 3+ open source projects and need a stable place to import the type from

1. [libtmux/conftest.py](https://github.com/tmux-python/libtmux/blob/v0.15.3/conftest.py#L22)
2. [libvcs/src/libvcs/conftest.py](https://github.com/vcs-python/libvcs/blob/v0.16.4/src/libvcs/conftest.py#L14)
3. [pytest-doctest-docutils](https://github.com/git-pull/gp-libs/blob/v0.0.1a11/src/pytest_doctest_docutils.py#L240) (overrides pytest's doctest plugin)
4. See [search for `/from.*DoctestItem/ language:Python` on cs.github.com](https://cs.github.com/?scopeName=All+repos&scope=&q=%2Ffrom.*DoctestItem%2F+language%3APython)

**Comment by nicoddemus** [comment]
Hi @tony,

I think we could make `DoctestItem` public for type annotation purposes, but other than that we should also make all its methods private to discourage users from subclassing/calling any public methods on it.

**Comment by tony** [comment]
@nicoddemus Thank you for looking into this

PR created at #10313

>  but other than that we should also make all its methods private to discourage users from subclassing/calling any public methods on it.

It looks like the methods in `DoctestItem` are from `Item` / `Node`, I suppose that's safe then?
