### ISSUE TITLE
How to collect test nodes/names, test outcomes and their associated markers?

### ISSUE THREAD

**Issue by matijadurdek** [pytest-dev/pytest#10320]
### Discussed in https://github.com/pytest-dev/pytest/discussions/10319

<div type='discussions-op-text'>

<sup>Originally posted by **matijadurdek** September 27, 2022</sup>
Hi, I would need some help :) 

I want to collect 3 types of data from a test run:
- test method name/node
- test outcome
- the arguments of a specific custom marker associated with the test method

Is it possible to collect the custom markers associated to test methods/nodes and the corresponding test outcomes?

Here is what I currently have in my setup:

pytest.ini:
```
markers =
    mycustommark: this is my custom marker
```

test examples:
```
@pytest.mark.mycustommark('TEST-1')
def test_1():
    pass


@pytest.mark.mycustommark('TEST-2')
def test_2():
    pass
```

conftest.py:
```
def pytest_runtest_logreport(report: TestReport):
    """Collect test nodes, test outcomes and marker values"""
    if report.when == "call" and 'mycustommarker' in report.keywords.keys() and report.keywords['mycustommarker']:
        print("Test node: ", report.nodeid)
        print("Marker: ", report.keywords.get('mycustommarker'))
        print("Test outcome: ", report.outcome)
```

I tried to use the `pytest_runtest_logreport` hook and it gives me the expected nodes and their outcomes in the output, but I'm not able to fetch the argument values from the `mycustommark` markers. It returns an integer value:
```
Test node:  tests/test_example.py::TestExample::test_1
Marker:  1
Test outcome:  passed

Test node:  tests/test_example.py::TestExample::test_2
Marker:  1
Test outcome:  passed
```

The expected output that I want:
```
Test node:  tests/test_example.py::TestExample::test_1
Marker:  TEST-1
Test outcome:  passed

Test node:  tests/test_example.py::TestExample::test_2
Marker:  TEST-2
Test outcome:  passed
``` 
</div>

**Comment by The-Compiler** [comment]
Closing this as you seem to have opened *both* a discussion and an issue. Please don't do that.
