### ISSUE TITLE
Old-style hookimpl warning has no location information

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#10342]
The old-style hookimpl deprecation warning from #9118 has no way to see where the culprit is implemented. I'm now getting:

```
pytest.PytestDeprecationWarning: The hookimpl pytest_configure uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(trylast=True) decorator instead
```

with no easy way to figure out what the problem is. I have 12 plugins installed, all of which might have a `pytest_configure`, and I'd rather not have to find out manually which one is the culprit. The error message should show either the plugin that's coming from, or at least the Python file it's in.

**Comment by RonnyPfannschmidt** [comment]
I'll ensure to include the filename in the warning, this is another fatal flaw of the warning system

**Comment by The-Compiler** [comment]
Ah, I agree this is somewhat of a problem with Python warnings. The location is indeed included when showing them as normal warnings, but not when turning them into exceptions (via `filterwarnings = error` or `-Werror`.

**Comment by RonnyPfannschmidt** [comment]
i will make warn_explicit_for handle this better
