### ISSUE TITLE
Entry points example should use another format 

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#10344]
Currently [the example for entry points](https://docs.pytest.org/en/stable/how-to/writing_plugins.html#making-your-plugin-installable-by-others) uses `setup.py`.

As I understand we want to recommend other formats in general (`pyproject.toml`/`setup.cfg`), so we should update the example accordingly.

**Comment by RonnyPfannschmidt** [comment]
As pyproject.toml is even supported by setuptools, I strongly recommend only that file

**Comment by doublevcodes** [comment]
Hello, can I make this my first contribution to pytest?

**Comment by nicoddemus** [comment]
@doublevcodes sure, please go ahead!
