### ISSUE TITLE
Internalerror KeyError: 'nodeid'

### ISSUE THREAD

**Issue by logicabrity** [pytest-dev/pytest#1034]
When I try running tests with py.test version 2.8.0 on my Ubuntu 14.04 LTS machine, I get the following internal error:

$ py.test

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 86, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 829, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 729, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/xdist/plugin.py", line 62, in pytest_configure
INTERNALERROR>     __multicall__.execute()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/terminal.py", line 47, in pytest_configure
INTERNALERROR>     config.pluginmanager.register(reporter, 'terminalreporter')
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 206, in register
INTERNALERROR>     ret = super(PytestPluginManager, self).register(plugin, name)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 370, in register
INTERNALERROR>     hook._maybe_apply_history(hookimpl)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 747, in _maybe_apply_history
INTERNALERROR>     res = self._hookexec(self, [method], kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 593, in execute
INTERNALERROR>     args = [all_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR> KeyError: 'nodeid'

$ py.test --version

This is pytest version 2.8.0, imported from /usr/local/lib/python2.7/dist-packages/pytest.pyc
setuptools registered plugins:
  pytest-xdist-1.11 at /usr/local/lib/python2.7/dist-packages/xdist/plugin.pyc

What's wrong?

**Comment by RonnyPfannschmidt** [comment]
at first glance it seems like a hook is expecting an argument that is not given at hook invocation

@hpk42 @flub - please take a deeper look

**Comment by logicabrity** [comment]
@flub assisted on IRC and I removed and reinstalled pytest-xdist using pip and that solved the issue.

$ py.test --version
This is pytest version 2.8.0, imported from /usr/local/lib/python2.7/dist-packages/pytest.pyc
setuptools registered plugins:
  pytest-xdist-1.13.1 at /usr/local/lib/python2.7/dist-packages/xdist/boxed.pyc
  pytest-xdist-1.13.1 at /usr/local/lib/python2.7/dist-packages/xdist/looponfail.pyc
  pytest-xdist-1.13.1 at /usr/local/lib/python2.7/dist-packages/xdist/plugin.pyc

Should I delete this issue?

**Comment by nicoddemus** [comment]
If you don't have any more questions, please do. :smile:

**Comment by RonnyPfannschmidt** [comment]
we should still report a bug to pluggy, since the error messages it gives are subpar atm

**Comment by nicoddemus** [comment]
Thanks Ronny!

**Comment by jerel** [comment]
My project just started throwing this error today on TravisCI. Pinning to pytest 2.7.2 solves the issue for now.

**Comment by nicoddemus** [comment]
Can you share the project? Or at least which plugins it uses?

**Comment by jerel** [comment]
Sure, here's the exact error: https://travis-ci.org/django-json-api/django-rest-framework-json-api/jobs/81470678

**Comment by nicoddemus** [comment]
Thanks!

**Comment by nicoddemus** [comment]
I'm reopening this... I think there's a deeper problem here, because @jerel's project uses pure pytest. Looking at the traceback, perhaps it has something to do with `pytest_cache` and the fact that it is a `historic` hook being called?

@RonnyPfannschmidt what do you think?

**Comment by habnabit** [comment]
:+1: having this issue internally too. I can't share logs, but I can try to make a test-case if it's not obvious from the above error. The build fails with this requirements.txt:
```
pytest
pytest-django
pytest-factoryboy
pytest-cov
```
and passes with this: 
```
pytest != 2.8.0
pytest-django
pytest-factoryboy
pytest-cov
```

**Comment by RonnyPfannschmidt** [comment]
@habnabit can you share the exact versions of the libraries as well?

**Comment by bh** [comment]
Same behavior with the following versions:
```
$ pip freeze | grep pytest                                                                                                                                           
pytest==2.8.0
pytest-bdd==2.15.0
pytest-cov==2.1.0
pytest-django==2.8.0
-e git+https://github.com/mverteuil/pytest-ipdb.git@2b9a5a43a19d22bd16035f5fcfe9d657dc4acba3#egg=pytest_ipdb-dev
pytest-rerunfailures==0.5
pytest-splinter==1.7.0
pytest-xdist==1.13.1
```

```
$ py.test
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/main.py", line 86, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/config.py", line 829, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 729, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/terminal.py", line 47, in pytest_configure
INTERNALERROR>     config.pluginmanager.register(reporter, 'terminalreporter')
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/config.py", line 206, in register
INTERNALERROR>     ret = super(PytestPluginManager, self).register(plugin, name)
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 370, in register
INTERNALERROR>     hook._maybe_apply_history(hookimpl)
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 747, in _maybe_apply_history
INTERNALERROR>     res = self._hookexec(self, [method], kwargs)
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 593, in execute
INTERNALERROR>     args = [all_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR>   File "/home/bhe/.virtualenvs/mx/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 593, in <listcomp>
INTERNALERROR>     args = [all_kwargs[argname] for argname in hook_impl.argnames]
INTERNALERROR> KeyError: 'nodeid'
```

**Comment by habnabit** [comment]
@RonnyPfannschmidt 
no error:
```
pytest==2.7.2
pytest-cov==2.0.0
pytest-django==2.8.0
pytest-factoryboy==1.1.2
```
error:
```
pytest==2.8.0
pytest-cov==2.1.0
pytest-django==2.8.0
pytest-factoryboy==1.1.3
```

**Comment by drcongo** [comment]
Also just run into this, was running fine until I added pytest-factoryboy. Downgrading to 2.7.2 "fixes" it for me.

**Comment by RonnyPfannschmidt** [comment]
recent pluggy made a better exception handler

for anyone testing this, can you install pluggy from git and remove the vendored one in the pytest install

**Comment by vodik** [comment]
Assuming the commit above does the trick, pytest is bailing trying to print the following warning message when using `addhooks`:

> use pluginmanager.add_hookspecs instead of deprecated addhooks() method.

**Comment by vodik** [comment]
Looks like [addhooks may indeed be the problem](https://github.com/pytest-dev/pytest-factoryboy/blob/ab0c73/pytest_factoryboy/plugin.py#L61)

**Comment by drcongo** [comment]
Thanks @vodik and @hpk42
