### ISSUE TITLE
ENH: Allow for optional filterwarnings

### ISSUE THREAD

**Issue by bashtage** [pytest-dev/pytest#10369]
#### What's the problem this feature will solve?
Some upstream projects move warnings and error locations occasionally (pandas specificall).  I have the line

`error::pandas.core.common.SettingWithCopyWarning:`

in my filterwarnings list.  In pandas 1.5.0 the location was moved to  `error::pandas.errors.SettingWithCopyWarning:`.   This causes my CI to fail.

#### Describe the solution you'd like
It would be great if there was a way to may these optional, so that if they failed to import they were ignored. Basically a `try import..., except pass`.  Something like

`error::pandas.core.common.SettingWithCopyWarning::optional`
`error::pandas.errors.SettingWithCopyWarning::optional`

so that I could import the warnign on either the current or old versions of pandas. 

#### Alternative Solutions
I don't know of any but would love a workaround.

**Comment by nicoddemus** [comment]
Hi @bashtage,

Thanks for writing up. While I sympathize with the problem, I don't think this would be a good solution:

1. The fact that pandas moved one of their public imports is a API breakage, not something that should happen normally. In other words I don't think this is a common problem, that happens with a lot of libraries all the time.
2. This is the behavior of the `filterwarnings` in the standard library, which pytest uses in fact to set the filters behind the scenes.
3. I personally tend to avoid solutions that ignore errors like this one.

For those reasons I'm particularly -1 on the idea.

A different solution would be *conditional* filters, based for example on Python or Pandas version, but that's a different proposal and not entirely clear how that would look like.

**Comment by bashtage** [comment]
I agree it isn't easy.  My syntax is certainly problematic since the ::: syntax is totally standard. Can the -W flag be used to set filters at runtime that augment the ones in pyproject?  If so, that would be a way around it for now. 

Another thought I had was to simply add a global flag `filterwarnings_optional=True` (or similar, name bikeshedding to follow) which would make them all try, except.  Again, probably a big lift for not much application.

**Comment by nicoddemus** [comment]
> Can the -W flag be used to set filters at runtime that augment the ones in pyproject? If so, that would be a way around it for now.

Yes you can use `-W` to pass that at runtime:

```
pytest-warnings:
  -W PYTHONWARNINGS, --pythonwarnings=PYTHONWARNINGS
                        set which warnings to report, see -W option of python itself.
```
