### ISSUE TITLE
`importorskip` is spelled wrong

### ISSUE THREAD

**Issue by drhagen** [pytest-dev/pytest#10374]
This is probably not worth fixing, but I think [`importorskip`](https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=importorskip#pytest-importorskip) is spelled wrong. The dictionary is convinced that the English spelling is ["importer"](https://www.merriam-webster.com/dictionary/importer), with ["importor"](https://www.merriam-webster.com/dictionary/importor) not being a word. If you decide this is worth an alias or a deprecation cycle, you may want to switch to snake_case at the same time (i.e. `importer_skip`), but that is not strictly necessary because `pytest` is already not internally consistent with regard to snake_case.

**Comment by nicoddemus** [comment]
It is meant to be "import or skip"... I agree snake case here would be better (`import_or_skip`), but too late to change now.

**Comment by drhagen** [comment]
Ha, I'm an idiot. I guess this is why snake_case has become the standard.
