### ISSUE TITLE
Allow multiple test scripts of the same name

### ISSUE THREAD

**Issue by ytoml** [pytest-dev/pytest#10385]
Hi, I want `pytest` to allow test files of same name (placed in different directories)!

#### What's the problem this feature will solve?
For example, if we try to run `pytest` on a project like:
```
.
├── Pipfile
├── app
│   └── util.py
├── lib
│   └── util.py
└── tests
    ├── app
    │   └── test_util.py
    └── lib
        └── test_util.py
```
but unfortunately, `pytest` complains:
```
import file mismatch:
imported module 'test_util' has this __file__ attribute:
  /path/to/project/tests/app/test_util.py
which is not the same as the test file we want to collect:
  /path/to/ptoject/tests/lib/test_util.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```
Of course, we have no `__pycache__` and this hint might be misleading.

#### Describe the solution you'd like
Just allowing directory structure above by separate namespace according to directory rather than filename.

#### Alternative Solutions
Modifying filenames to like `test_app_util.py` and `test_lib_util.py` will work, but it makes `tests` directory structure different from main implementation. I might be annoying especially when the number of scripts grows.

Thanks!

**Comment by RonnyPfannschmidt** [comment]
Either use the importlib import mode, or place `__init__.py` files in the test folders

**Comment by ytoml** [comment]
Oh, I totally forgot that... Thank you!
