### ISSUE TITLE
`--showlocals` should be overridable, e.g. 

### ISSUE THREAD

**Issue by tony** [pytest-dev/pytest#10381]
#### What's the problem this feature will solve?
- Assume `addopts` is globally set to have `--showlocals`
- It's not possible for `py.test` invocations to override the option on one-off invocations / pytest steps in CI workflows

#### Describe the solution you'd like
`--showlocals=false` or `--no-showlocals` / `--without-locals`

#### Alternative Solutions
Open to hearing others

#### Additional context

Mentioned earlier here: https://github.com/pytest-dev/pytest/issues/8974#issuecomment-891720866

This differs from #8974 in:
- being narrowly tailored solution wise - allow an argument to negate the locals showing
- has a technical solution that can be addressed directly PR'd if maintainers willing

**Comment by RonnyPfannschmidt** [comment]
as this is a flag, `--no-showlocals` should probably be added
