### ISSUE TITLE
pytest_addoption is not listing all arguments and their help(both required and optional args)

### ISSUE THREAD

**Issue by puppet-py** [pytest-dev/pytest#10398]
Pytest Version: 7.1.2
OS: macOS

In my `conftest.py`, I have used `pytest_addoption` for accepting command-line arguments(both required and optional).
The `conftest.py` is at the `test` root directory

Observations:
Below are different command invoked from `test` directory, does NOT list the `help` for the `required=True` arguments.
Case-1
```
(venv) KCQVK694RN:test moab$ python3 -m pytest [-h]
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: the following arguments are required: --enterprise-name, --firmware-blue, --dgm, --dgm-url, --provider
``` 
What could be missing for me to list all the "help" of each of the above args ?

Case-2
```
(venv) KCQVK694RN:test moab$
(venv) KCQVK694RN:test moab$ python3 -m pytest --enterprise-name
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: argument --enterprise-name: expected one argument. << Expected msg from "help" option

(venv) KCQVK694RN:test moab$
```
Expected msg from "help" option for the argument --enterprise-name. What could be missing in this case ?

Case-3: How do I list all the arguments including the optional(which do not have `required` set) ones also

Here is my code snippet:

```
def pytest_addoption(parser):
    """
    Parse commandline options
    """
    parser.addoption(
        "--enterprise-name", action="store", default="",
        help="Name of the enterprise",
        required=True
    )
    parser.addoption(
        "--firmware-blue", action="store", default="",
        help="Compatible firmware required for installing the app.",
        required=True
    )
    parser.addoption(
        "--dgm", action="store", default="",
        help="options: hulu, zulu",
        required=True
    )
    parser.addoption(
        "--dgm-url", action="store", default="",
        help="provide URL of the dgm",
        required=True
    )
    parser.addoption(
        "--provider", action="store", default="drops",
        help="options: hello, world, peter",
        choices=("hello", "world", "peter"),  # This will validate input against the choices
        required=True
    )
    parser.addoption(
        "--rider-pol", action="store", default="",
        help="rider policy which exists in the enterprise."
    )
    parser.addoption(
        "--network-proxy", action="store", default="",
        help="network proxy which exists in the enterprise."
    )
```
Any help is much appreciated.

**Comment by mikigo** [comment]
If `required=True` is passed in addoption, it means that this parameter must be passed in. If you do not pass in the parameter, you will be prompted to pass in the parameter. If you only write the parameter but do not give the corresponding value, you will be prompted to give a value. Depending on your configuration, you can try to give a character string, such as ：`python3 -m pytest --enterprise-name Apple`
