### ISSUE TITLE
Old backport labels

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#10433]
What should we do with old "backport" labels? Currently we have the following labels to backport to old branches that we do not intend to maintain anymore:

* `backport 7.0.x`
* `backport 7.1.x`

I think we can safely delete them, asking here first in case somebody wants to keep them around for some reason.

**Comment by The-Compiler** [comment]
Wish there was a way to archive labels (hide them from the list), but keep them on issues/PRs they are on... but alas, there isn't, so :+1: for just getting rid of them!

**Comment by nicoddemus** [comment]
Cool, deleted them. 👍
