### ISSUE TITLE
pytest 7.2.0 regression: 'py' is not a package - but py library is installed

### ISSUE THREAD

**Issue by amezin** [pytest-dev/pytest#10451]
https://github.com/ddterm/gnome-shell-extension-ddterm/actions/runs/3330468879/jobs/5509011844

`py` is installed in system site packages, `pytest` and `pytest-html` are installed in a virtualenv (system site packages are enabled).

Seems that in this case py module from pytest takes precedence over pylib from system site packages (and breaks pytest-html).

Everything works fine with `pytest==7.1.3`, fails with `pytest==7.2.0`.

**Comment by nicoddemus** [comment]
@amezin just so we understand, why do you have `py` in system packages?

A workaround is to install `py` in your virtual environment.

**Comment by amezin** [comment]
I have `py` in system packages because I install tox system-wide, and tox depends on py. And then I use tox to create the virtualenv.

And I don't want to turn off system site packages because I also need PyGObject. Currently it's installed using distro's package manager. If installing with pip, it will need multiple dependencies - GCC, -dev packages.

**Comment by nicoddemus** [comment]
I see.

Can you check if installing `py` explicitly in your virtualenv solves the issue for you?

**Comment by asottile** [comment]
you'll likely need `--ignore-installed` such that you get a copy of `py` inside your virtualenv -- though admittedly `system-site-packages` is already playing with fire so...

**Comment by amezin** [comment]
Yes, when `py` is installed into the virtualenv (with `--ignore-installed`) it works: https://github.com/ddterm/gnome-shell-extension-ddterm/actions/runs/3380104688/jobs/5612522131

**Comment by nicoddemus** [comment]
Thanks @amezin for following up. 👍

**Comment by The-Compiler** [comment]
Not sure if we should close this? If there is a way for our stub to deal with this (maybe check if `py` is importable or something?), I feel like we should, no?

**Comment by asottile** [comment]
it's too late at that point -- the module has already been shadowed

**Comment by amezin** [comment]
Couldn't it be solved with import hooks?

**Comment by asottile** [comment]
afaict there's nothing to "solve" -- using `--system-site-packages` in general is a bad idea and you've got a solution already

**Comment by sirex** [comment]
It looks, that py was removed as pytest dependency and py was included into pytest itself:

https://github.com/pytest-dev/pytest/commit/19dda7c9bdc8ef71c792e0f77a9595bfad8d9248

I was importing py mainly for type annotations for `tmpdir`, but to fix this, decided to replace `tmpdir` with `tmp_path`, which uses native `pathlib.Path`.
