### ISSUE TITLE
logging file write mode can't be customized

### ISSUE THREAD

**Issue by Mrsong007** [pytest-dev/pytest#10456]
problem : I want my log file to record every log

versions : 7.2.0

file path : _pytest.logging.py

line : 567

Picture ：
![logging](https://user-images.githubusercontent.com/37532377/199184343-72583408-9efc-4c74-bf15-47d61d364eed.png)

**Comment by Mrsong007** [comment]
你好，你的邮件我已收到，尽快给你回复。

**Comment by Mrsong007** [comment]
你好，你的邮件我已收到，尽快给你回复。

**Comment by Mrsong007** [comment]
你好，你的邮件我已收到，尽快给你回复。

**Comment by Pierre-Sassoulas** [comment]
@Mrsong007 could you add detail about what you want to do ? Right now this issue is not actionable :)

**Comment by RonnyPfannschmidt** [comment]
Closing as not actionable, actual feature request or intended usage example missing
