### ISSUE TITLE
Assign readable and stable test id to single test cases

### ISSUE THREAD

**Issue by edmondop** [pytest-dev/pytest#10460]
#### What's the problem this feature will solve?
When you upload tests results to external platform (i.e. junit.xml to upload it somewhere else), if you use parametrized tests you can both make the test name readable and its id stable, so to potentailly refactor the code. 

This doesn't seem to be possible on a single test, and it should be simple to do with a decorator

**Comment by RonnyPfannschmidt** [comment]
Please provide a example of what you mean,

**Comment by edmondo1984** [comment]
Take this test

```python
@pytest(id='Test valid surname')
def test_valid_surname()
     pass
```

after refactoring, the field is named last name

```python
@pytest(id='Test valid surname')
def test_valid_lastname()
     pass
```

In the report junit.xml you would want the same id

**Comment by asottile** [comment]
wouldn't the refactor also correct `surname` -> `lastname` ?

**Comment by edmondo1984** [comment]
If you are pushing these results to a test reporting platform, what you want to do is to keep track that you have been running the test for six months, and you are keeping running it. If you change the ID of the test, it will appear as if you stopped to run test A, and you added a new test called test B

**Comment by RonnyPfannschmidt** [comment]
Based on the current input it reads like you want pytest to be able to lie about the derived test names

Which makes this a no go for me

In particular the code example makes it seem like something I'd oppose to avoid massive headaches

**Comment by edmondo1984** [comment]
> Based on the current input it reads like you want pytest to be able to lie about the derived test names
> 
> Which makes this a no go for me
> 
> In particular the code example makes it seem like something I'd oppose to avoid massive headaches

Why lie? Providing stable test IDS is lying? It's like having an external id in a database,

**Comment by RonnyPfannschmidt** [comment]
So use stable function names?

**Comment by edmondo1984** [comment]
You cannot move a test case in a different function

**Comment by RonnyPfannschmidt** [comment]
As far as I am concerned, self chosen external test ids is something a plugin should provide
