### ISSUE TITLE
Feature: `capsys.enabled()` context manager

### ISSUE THREAD

**Issue by shaunc** [pytest-dev/pytest#10475]
#### What's the problem this feature will solve?

I run my tests with -s frequently, as the only things my code should write is testing diagnostics. However, I just added a test of a plugin using pytester. It writes to stdout, and would like to suppress output just for these tests.

#### Describe the solution you'd like

In order to do this (unless there is another convenient way), I would like to do:

```
    def test_foo_using_pytester(testdir, capsys):
        with capsys.enabled():
            ...
```

Then I would run my overall test suite using `-s` and not have to see the output in the individual cases in which it is not useful.

#### Alternative Solutions

It would seem that the capmanager could be used directly, but source code is hard to read and this functionality is not well documented.

**Comment by Zac-HD** [comment]
I recommend using [the standard library - `with contextlib.redirect_stdout(io.StringIO()):`](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout) 😁
