### ISSUE TITLE
caplog.records throws  AttributeError

### ISSUE THREAD

**Issue by LimingXuIHME** [pytest-dev/pytest#10487]
- [ ] a detailed description of the bug or problem you are having
We used to have a test case calling "caplog.records" that worked like a charm until pytest version 7.1.1. 
Starting from pytest 7.1.2 (we also reproduced this with pytest 7.2.0), we see this error:

    (Pdb) caplog.records
    *** AttributeError: 'function' object has no attribute 'records'

We did further investigation, and noticed that caplog is no longer a LogCaptureFixture object but a function.

pytest 7.1.1:
    (Pdb) type(caplog)
    <class '_pytest.logging.LogCaptureFixture'>
pytest 7.1.2 & pytest 7.2.0:
    (Pdb) type(caplog)
    <class 'function'>

We checked the pytest release notes, and didn't see a deliberate change.

- [ ] output of `pip list` from the virtual environment you are using

Package               Version      Editable project location
--------------------- ------------ --------------------------------
attrs                 22.1.0
blinker               1.5
certifi               2022.9.24
charset-normalizer    2.1.1
click                 8.1.3
cluster-utils         0.3.1
ConfigArgParse        1.5.3
coverage              6.5.0
Deprecated            1.2.13
elastic-apm           6.13.1
exceptiongroup        1.0.1
execnet               1.9.0
filelock              3.8.0
Flask                 2.2.2
Flask-Cors            3.0.10
greenlet              2.0.1
idna                  3.4
importlib-metadata    5.0.0
iniconfig             1.1.1
itsdangerous          2.1.2
Jinja2                3.1.2
jobmon                3.3.0.dev154 /mnt/share/homes/limingxu/jobmon
limits                2.7.1
MarkupSafe            2.1.1
mock                  4.0.3
numpy                 1.23.4
packaging             21.3
pandas                1.5.1
pip                   22.2.2
pluggy                1.0.0
psutil                5.9.4
pylogbeat             2.0.0
PyMySQL               1.0.2
pyparsing             3.0.9
pytest                7.2.0
pytest-cov            4.0.0
pytest-xdist          3.0.2
python-dateutil       2.8.2
python-json-logger    2.0.4
python-logstash-async 2.5.0
pytz                  2022.6
PyYAML                6.0
requests              2.28.1
scipy                 1.8.1
setuptools            65.5.0
six                   1.16.0
slurm-rest            1.0.4
SQLAlchemy            1.4.43
structlog             22.1.0
tabulate              0.9.0
tenacity              8.1.0
tomli                 2.0.1
typing_extensions     4.4.0
urllib3               1.26.12
Werkzeug              2.2.2
wheel                 0.37.1
wrapt                 1.14.1
zipp                  3.10.0

- [ ] pytest and operating system versions

pytest: 7.2.0 (reproducible on 7.1.2; unreproducible on 7.1.1)
OS: Ubuntu 20.04.3 LTS 

- [ ] minimal example if possible
import pytest
def test_workflow_validation(caplog):
      ...
      caplog.clear()
      with caplog.at_level(logging.INFO, logger=...):
             ...<something output to logger>
             assert (
            "Failed validation" in caplog.records[-1].message
             )

Thanks,
Liming

**Comment by The-Compiler** [comment]
Can you please show a complete, standalone example reproducing the issue? Your example clearly isn't runnable, and with a minimal example, I can't reproduce:

```python
import pytest
def test_workflow_validation(caplog):
    assert False, caplog
```

leads to this as expected:

```
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
rootdir: /home/florian/tmp
plugins: anyio-3.6.2, hypothesis-6.54.4
collected 1 item                                                               

test_caplog.py F                                                         [100%]

=================================== FAILURES ===================================
___________________________ test_workflow_validation ___________________________

caplog = <_pytest.logging.LogCaptureFixture object at 0x7ffae54fe350>

    def test_workflow_validation(caplog):
>       assert False, caplog
E       AssertionError: <_pytest.logging.LogCaptureFixture object at 0x7ffae54fe350>
E       assert False
```

**Comment by The-Compiler** [comment]
I've also looked at the [diff between 7.1.1 and 7.1.2](https://github.com/pytest-dev/pytest/compare/7.1.1...7.1.2#diff-c56b97a85117944cf814bbec4de4e1aba1a708b88c963ea5ad2682cf5d487a99) - only some 10-15 lines of actual pytest source code changed, and they are nowhere around things which could possibly cause this. My bet would be on something else being different in the two environments, and perhaps something overriding the `caplog` fixture, but it's difficult to tell without more information.

**Comment by abc20200615** [comment]
When trying to write a directly executable example and switching in between 7.1.1 and 7.2.0, the error suddenly disappeared, and I can no longer reproduce it in either version. I agree there must be something overriding it, but I just haven't been able to pin it down.

Thanks,
Liming

**Comment by LimingXuIHME** [comment]
I can no longer reproduce this issue.

**Comment by caplogebenezere** [comment]
Caplog
