### ISSUE TITLE
how do I set pytest.ini default path by env?

### ISSUE THREAD

**Issue by summy00** [pytest-dev/pytest#10499]
#### What's the problem this feature will solve?
can set pytest.ini default path by env, so I no need type `pytest -c pytest.ini -s ...`, just `pytest -s ...`

#### Describe the solution you'd like

* there is a `pytest.ini` in `/pytest/`
* `export PYTEST_INI_PATH='/pytest'`
* just type `pytest` make `/pytest/pytest.ini` apply

**Comment by nicoddemus** [comment]
Hi,

Use [`PYTEST_ADDOPTS`](https://docs.pytest.org/en/stable/reference/reference.html#envvar-PYTEST_ADDOPTS):

```
export PYTEST_ADDOPTS="-c /pytest/pytest.ini"
```
