### ISSUE TITLE
supply additional info after pytest.raises failure

### ISSUE THREAD

**Issue by noamgot** [pytest-dev/pytest#10508]
#### What's the problem this feature will solve?
When using `pytest.raises`, sometimes there are known solutions to what caused the failure. For example, in the case that made me open this feature request, if the PYTHONPATH is set to the root directory of the project, the test will fail. However, by unsetting it, the test will pass. There could be infinitely many such cases, of course.
I did not find a way to supply an additional message to `pytest.raises` in order to supply additional useful guidance

#### Describe the solution you'd like
I would like to suggest that `pytest.raises` will accept an additional parameter - `message` - that will allow supplying this info.

Here's a possible template for a test with this feature:
```python
import importlib
import pytest

def test_raise():
    with pytest.raises(SomeException, message="this is how to solve the problem"):
        function_that_should_raise_but_does_not()
```
And the output should look something like:
```
E           Failed: DID NOT RAISE <class 'SomeException'>; this is how to solve the problem
```

#### Alternative Solutions
I'm currently using this bypass:
```python
def test_raise():
    try:
        function_that_should_raise_but_does_not()
        pytest.fail("Did not raise SomeException; this is how to solve the problem")
    except SomeException:
        pass
```

#### Additional context
None.

**Comment by RonnyPfannschmidt** [comment]
As proposed This is rejected. 

the message parameters was removed as it was a regular source of wrong tests as people kept presuming the intent was to check the exception message instead of setting the message of the error

I recommend declaring an own context manager

Im not against a solution which won't repeat the error of the initial api

**Comment by nicoddemus** [comment]
@noamgot to complement, that exact same API was initially supported, but was eventually deprecated and then finally removed, for the reasons @RonnyPfannschmidt mentioned above.

**Comment by noamgot** [comment]
thanks @nicoddemus , indeed I was not aware that it existed in the past. I'm closing this issue then.

**Comment by The-Compiler** [comment]
Note that you can also use `with pytest.raises(...):` and then call `pytest.fail` in there, which is actually the recommended way to this: https://docs.pytest.org/en/latest/deprecations.html#raises-message-deprecated
