### ISSUE TITLE
Add class fixtures

### ISSUE THREAD

**Issue by Ovsyanka83** [pytest-dev/pytest#10515]
#### What's the problem this feature will solve?
It is a common pattern to use builder functions to create complex objects for tests. Most of the time we can do so with regular fixtures but some tests require an arbitrary number of objects. In such cases, I commonly see people making the following fixtures:

```python
@pytest.fixture
def make_object(other_fixture1: str, other_fixture2: dict[str, int]):
    def inner(arg1, arg2):
        ...
    return inner
```

I.e. We use the outer function to get that sweet dependency injection and we use the inner function within tests to create objects (it doesn't have to be an object creator. In fact, it can be any inner function that makes use of dependency injection). However, typehinting and keeping the usages of this fixture up to date is not easy. 

#### Describe the solution you'd like
I believe that it makes sense to either disable or properly document the following check in pytest's code:
```python
 if inspect.isclass(function):
    raise ValueError("class fixtures not supported (maybe in the future)")
```

It would enable people to write fixture classes that can be imported and typehinted while also utilizing pytest's DI. So based on the example above, we would have:
```python
@pytest.fixture(name="make_object")
@dataclass(slots=True, frozen=True)
class ObjectMaker:
    other_fixture1: str
    other_fixture2: dict[str, int]
    
    def __call__(self, arg1, arg2):
        ...
```

#### Alternative Solutions
I have written a [plugin](https://github.com/Ovsyanka83/pytest-fixture-classes) that does the same thing but I see no reason to have it if we can just remove a single "if" statement for the same result. 

#### Additional context
The use of frozen dataclasses with DI has been described by @sobolevn in [this article](https://sobolevn.me/2019/03/enforcing-srp)

**Comment by RonnyPfannschmidt** [comment]
As proposed, classes don't add anything to fixtures that's not avaliable already today. 

Classes as fixtures where reserved for when we figure a way to invoke the class in the fixture life cycle

**Comment by Ovsyanka83** [comment]
@RonnyPfannschmidt Would you mind explaining how the problem I mentioned can be solved by functions?

Additionally, would  you mind elaborating on your second statement? I am a bit confused on what you mean here.

**Comment by RonnyPfannschmidt** [comment]
You can just return a instance of the class

**Comment by RonnyPfannschmidt** [comment]
The final deal of. Class fixtures is unclean

**Comment by RonnyPfannschmidt** [comment]
The basic idea of fixture classes is that they would not just be a value, but able to control parameters, life cycle and caching of the fixture itself

**Comment by Ovsyanka83** [comment]
Thanks!
