### ISSUE TITLE
ImportError with Pytest 7.0.2 with Python 3.9

### ISSUE THREAD

**Issue by psxpa3** [pytest-dev/pytest#10516]
Hello, I am using Pytest 7.0.2 version with Python 3.9. However, the py39-test command is failing with the below error. I tried using `--import-mode=importlib`, however that is not working too. Also, tried deleting `__init__.py` file sibling of conftest.py file, but to no avail. I am not getting the root-cause of this error. Could anyone please provide any direction. Appreciate your help on this.

{code}
py39-test run-test: commands[0] | pytest
[966] /sparta/input$ /sparta/input/.tox/py39-test/bin/pytest
ImportError while loading conftest '/sparta/input/tests/conftest.py'.
tests/conftest.py:6: in <module>
    from netcapforecast.models.bayesian import BayesianForecast
.tox/py39-test/lib/python3.9/site-packages/netcapforecast/models/bayesian.py:6: in <module>
    import pyro
.tox/py39-test/lib/python3.9/site-packages/pyro/__init__.py:4: in <module>
    import pyro.poutine as poutine
.tox/py39-test/lib/python3.9/site-packages/pyro/poutine/__init__.py:4: in <module>
    from .handlers import (
.tox/py39-test/lib/python3.9/site-packages/pyro/poutine/handlers.py:58: in <module>
    from .block_messenger import BlockMessenger
.tox/py39-test/lib/python3.9/site-packages/pyro/poutine/block_messenger.py:6: in <module>
    from pyro.poutine.messenger import Messenger
.tox/py39-test/lib/python3.9/site-packages/pyro/poutine/messenger.py:7: in <module>
    from .runtime import _PYRO_STACK
.tox/py39-test/lib/python3.9/site-packages/pyro/poutine/runtime.py:7: in <module>
    from pyro.params.param_store import (  # noqa: F401
.tox/py39-test/lib/python3.9/site-packages/pyro/params/__init__.py:4: in <module>
    from .param_store import (
.tox/py39-test/lib/python3.9/site-packages/pyro/params/param_store.py:9: in <module>
    import torch
.tox/py39-test/lib64/python3.9/site-packages/torch/__init__.py:191: in <module>
    _load_global_deps()
.tox/py39-test/lib64/python3.9/site-packages/torch/__init__.py:153: in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
/usr/lib64/python3.9/ctypes/__init__.py:374: in __init__
    self._handle = _dlopen(self._name, mode)
E   OSError: libcublas.so.11: cannot open shared object file: No such file or directory
{code}

**Comment by The-Compiler** [comment]
It sounds like your codebase needs CUDA set up properly, also see e.g. https://github.com/tensorflow/tensorflow/issues/26209

This isn't anything pytest specific, you'd get the same error when importing your code outside of pytest.
