### ISSUE TITLE
Pytest won't find fixtures after updating to MacOS Ventura (13.0.1, x86)

### ISSUE THREAD

**Issue by piermarcob** [pytest-dev/pytest#10528]
- [x] a detailed description of the bug or problem you are having
I recently upgraded to MacOS Ventura (13.0.1) and tests for my project don't seem to work anymore.
More precisely, pytest will fail finding fixtures, thing that was successful before the update.
I collected debug details while executing pytest, i'll upload the log file right here.
Before executing tests, i have to:
- Optionally run `pipenv install`
- Run `pipenv shell` for starting a pipenv shell
- Run tests with `pytest -xvrP`.
I tried executing this on a Linux machine and it works, so i exclude the software misconfiguration error.

- [x] output of `pip list` from the virtual environment you are using
```
aiosqlite          0.17.0
anyio              3.6.2
asyncpg            0.27.0
attrs              22.1.0
autocommand        2.2.1
base58             2.1.1
bcrypt             4.0.1
biom-format        2.1.12
biopython          1.79
boto3              1.26.8
botocore           1.29.8
cachetools         4.2.4
certifi            2022.9.24
cffi               1.15.1
chardet            5.0.0
charset-normalizer 2.1.1
cheroot            8.6.0
CherryPy           18.8.0
click              8.1.3
colorama           0.4.6
construct          2.10.68
construct-typing   0.5.3
coverage           6.5.0
cryptography       38.0.3
cutadapt           4.1
Cython             0.29.32
dnaio              0.9.1
ed25519            1.5
exceptiongroup     1.0.1
fastapi            0.86.0
fastapi-jwt-auth   0.5.0
graphql-core       3.2.3
h11                0.12.0
h5py               3.7.0
httpcore           0.15.0
httptools          0.5.0
httpx              0.23.0
idna               3.4
inflect            6.0.2
iniconfig          1.1.1
iso8601            1.1.0
jaraco.classes     3.2.3
jaraco.collections 3.8.0
jaraco.context     4.1.2
jaraco.functools   3.5.2
jaraco.text        3.10.0
jmespath           1.0.1
jsonalias          0.1.1
limits             1.6
lxml               4.9.1
mangum             0.16.0
Metaplex           1.1.0
more-itertools     9.0.0
numpy              1.23.4
packaging          21.3
pandas             1.5.1
passlib            1.7.4
Pillow             9.3.0
pip                22.3.1
pluggy             1.0.0
portend            3.1.0
py                 1.11.0
pycparser          2.21
pydantic           1.10.2
PyJWT              1.7.1
PyNaCl             1.5.0
pyparsing          3.0.9
pypika-tortoise    0.1.6
pypng              0.20220715.0
PyQRCode           1.2.1
pytest             7.2.0
pytest-asyncio     0.20.2
python-dateutil    2.8.2
python-dotenv      0.21.0
python-http-client 3.3.7
python-multipart   0.0.5
pytz               2022.6
PyYAML             6.0
requests           2.28.1
rfc3986            1.5.0
s3transfer         0.6.0
scipy              1.9.3
sendgrid           6.9.7
setuptools         65.5.1
six                1.16.0
slowapi            0.1.6
sniffio            1.3.0
solana             0.28.0
solders            0.10.0
starkbank-ecdsa    2.2.0
starlette          0.20.4
strawberry-graphql 0.142.1
stripe             4.2.0
tempora            5.0.2
toml               0.10.2
tomli              2.0.1
tortoise-orm       0.19.2
types-cachetools   4.2.10
typing_extensions  4.4.0
urllib3            1.26.12
uvicorn            0.19.0
uvloop             0.17.0
watchfiles         0.18.1
websockets         10.4
wheel              0.37.1
xopen              1.7.0
zc                 0.1.1
zc.lockfile        2.0
```
- [x] pytest and operating system versions
`pytest --version -> pytest 7.2.0`
MacOS 13.0.1 (x86 architecture)
- [x] minimal example if possible
Available from my dropbox [here](https://www.dropbox.com/s/ps6bllwaiv3ry25/pytest_debug.log?dl=0)

**Comment by The-Compiler** [comment]
Can you please show the full output of your pytest run? Also, in your Dropbox, I can only find a debug log, not a minimal example.

**Comment by piermarcob** [comment]
Hi Florian, thanks for the quick response and sorry if i missed posting all the needed information.

Here is the output of running `pytest -xvrP`.
Please note that this process works on other machines running MacOS (same version of mine or older) and Linux (ubuntu server)
[test.log](https://github.com/pytest-dev/pytest/files/10085674/test.log)

Thanks again for putting effort in looking into this.

**Comment by The-Compiler** [comment]
And where/how exactly is e.g. `remove_all_communities` defined?

**Comment by piermarcob** [comment]
It is defined in contest.py, which is correctly loaded on other platforms.

**Comment by The-Compiler** [comment]
Sorry for the delay, I dropped the ball a bit here.

So I see a `/Users/piermarcobarbe/git/vylto-infrastructure/backend/tests/conftest.py` being loaded in your logs. However, the test seems to be at `/Users/piermarcobarbe/git/vylto-infrastructure/test_analytics.py`. Where exactly is the `conftest.py` (not `contest.py` I hope?) which isn't getting loaded.

Can you perhaps share your repository or a minimal example project exhibiting the same problem? I'm afraid it's almost impossible to debug this like this.

**Comment by piermarcob** [comment]
Hi Florian,

Sorry for the typo (`contest.py` -> `conftest.py`), our project file was and is named correctly.

Hmm, thanks for letting me notice that a file named `test_analytics.py` was found in our project root directory. That is weird as we collect tests in a specific directory and finding a test file outside of it is weird to read.

I am sorry to tell you that I had to wipe my Mac since tests were not running anymore and I couln't afford any more time on this, but i can confirm that there was actually a file named `test_analytics.py` outside test directory and I think this was causing pytest to crash / not to find fixtures.

So, just to be clear, the structure was:
```
- vylto-infrastructure/
  - test_analytics.py
```
as correctly reported by the pytest log.

Certainly this was a mistake on my side, do you think pytest can detect this kind of situations and maybe warn the user about it?

Thanks again for your time.

**Comment by The-Compiler** [comment]
Well, if you have a test in `vylto-infrastructure/test_analytics.py`, but your fixture defined in `vylto-infrastructure/backend/tests/conftest.py`, that's not going to work - a `conftest.py` is only valid for the directory it's in, or any subdirectories.

I don't see what pytest could detect or warn about - this is normal and valid usage of pytest.
