### ISSUE TITLE
pytest --collect-only executes test pipelines

### ISSUE THREAD

**Issue by Karthik-RT** [pytest-dev/pytest#10530]
-When i execute pytest --collect-only [Target directory], it executes test pipelines. Not sure if it is already fixed in the latest version. 

I am using pytest 6.2.4 [Windows 10]

Could you please provide some insight on this?

**Comment by The-Compiler** [comment]
What are "test pipelines"?

**Comment by Karthik-RT** [comment]
It is custom test framework that is written on top of  uninttest.Testcase library python.

**Comment by The-Compiler** [comment]
This sounds like an issue in that framework rather than pytest then. Not really anything we can do with so little information, ideally a reproducible example.

**Comment by Karthik-RT** [comment]
well, i understand i cannot share details beyond that. could you please provide the link of source code for this command (pytest --collect-only)

**Comment by nicoddemus** [comment]
Here is what we have regarding collection: https://docs.pytest.org/en/stable/example/pythoncollection.html

Closing for now, feel free to follow up with further questions.
