### ISSUE TITLE
AttributeError: module 'posixpath' has no attribute 'sep'

### ISSUE THREAD

**Issue by danschef** [pytest-dev/pytest#10547]
Within a Python 3.10 environment and with pytest 7.2.0 installed, it seems like I cannot start the debugger in PyCharm. Instead PyCharm raises the following error:

```python
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0 -- /home/me/mambaforge/envs/myenv/bin/python
cachedir: .pytest_cache
rootdir: /home/me/EnPT
plugins: reporter-html1-0.8.2, cov-4.0.0, reporter-0.5.2
collecting ... 
tests/test_1.py:None (tests/test_1.py)
../../../../mambaforge/envs/myenv/lib/python3.10/site-packages/_pytest/runner.py:339: in from_call
    result: Optional[TResult] = func()
../../../../mambaforge/envs/myenv/lib/python3.10/site-packages/_pytest/runner.py:370: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
../../../../mambaforge/envs/myenv/lib/python3.10/site-packages/_pytest/python.py:532: in collect
    self._inject_setup_module_fixture()
../../../../mambaforge/envs/myenv/lib/python3.10/site-packages/_pytest/python.py:546: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
../../../../mambaforge/envs/myenv/lib/python3.10/site-packages/_pytest/python.py:311: in obj
    self._obj = obj = self._getobj()
../../../../mambaforge/envs/myenv/lib/python3.10/site-packages/_pytest/python.py:529: in _getobj
    return self._importtestmodule()
../../../../mambaforge/envs/myenv/lib/python3.10/site-packages/_pytest/python.py:618: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
../../../../mambaforge/envs/myenv/lib/python3.10/site-packages/_pytest/pathlib.py:547: in import_path
    if module_file.endswith(os.path.sep + "__init__.py"):
E   AttributeError: module 'posixpath' has no attribute 'sep'

```
The environment is running on Ubuntu 20.04 and the error did not appear with Python 3.9. 

When replacing `os.path.sep` with `os.sep` in .../site-packages/_pytest/pathlib.py, the error goes away.

**Comment by nicoddemus** [comment]
The Python [docs say](https://docs.python.org/3/library/os.html#os.sep) it should be available via `os.path.sep`, so this is strange.

However I think a patch to change this would be harmless too, seems `os.sep` is the "official" location and `os.path.sep` is an alias (someone can correct me if this wrong).

**Comment by danschef** [comment]
I just created a pull request to see if this leads to any issues in the CI pipelines: https://github.com/pytest-dev/pytest/pull/10550

**Comment by Zac-HD** [comment]
My only objection to this is that we're mashing buttons to work around a problem that should be impossible, and that means I have no reason to expect that we're actually fixing it.

If [I go look at `posixpath.py` it's definitely got a `sep` attribute](https://github.com/python/cpython/blob/3.10/Lib/posixpath.py#L19), so I think your Python install must be subtly but quite nastily broken.  Up to you @nicoddemus.

**Comment by The-Compiler** [comment]
I have a deja-vu: #9791 - judging from the linked issues, it seems to affect (or at least have affected) various different projects.

**Comment by Zac-HD** [comment]
Fair enough; let's just merge Daniel's PR (thanks!), which I do expect to fix it here, and hope that's the end of the story!

**Comment by danschef** [comment]
Thanks for merging and pointing me to https://github.com/pytest-dev/pytest/issues/9791. That is quite helpful.
