### ISSUE TITLE
Soft assert for pytest

### ISSUE THREAD

**Issue by harmin-parra** [pytest-dev/pytest#10548]
I wonder if it could be possible to have soft assertions in pytest.

The expected behavior would be similar to the existing assert.
If a soft assert fails, the whole test will be flagged as a Failure, but instead of exiting the test execution upon the soft assertion failure, the execution will continue until the end, then the test will ultimately be flagged as a Failure.

I do know there are other python modules that does this, like [softest](https://pypi.org/project/softest/) and [pytest-soft-assertions](https://pypi.org/project/pytest-soft-assertions/), but I wonder if you can consider embedding one of this solutions into pytest.

**Comment by nicoddemus** [comment]
Hey @harmin-parra, 

> I wonder if you can consider embedding one of this solutions into pytest.

There's a few options: [pytest-check](https://pypi.org/project/pytest-check/) and [pytest-subtests](https://pypi.org/project/pytest-subtests/). 👍
