### ISSUE TITLE
Capsys (or alternative) that supports live printout while it is captured

### ISSUE THREAD

**Issue by Decee1** [pytest-dev/pytest#10587]
#### What's the problem this feature will solve?
While debugging testcases with capsys enabled it would be great to be able to visually see the output. If test gets stuck i am unable to read out the data when stopping the test

#### Describe the solution you'd like
For capsys or alternative fixture that supports outputting the capsys data live while still capturing it

Example of a testcase that gets stuck forever
```
def test_no_capture(capsys):
      import time
      def func_under_test():
          # Simulation of test
          print("Extremely important debug info that i would surely have resolved issue by knowing")
          # I will never see the debug info as test is stuck
          time.sleep(10E2)

    func_under_test()
    out, err = capsys.readouterr()
    print(out)

```
#### Alternative Solutions
Haven't found any yet

**Comment by The-Compiler** [comment]
That already exists via the `tee-sys` [capturing method](https://docs.pytest.org/en/7.2.x/how-to/capture-stdout-stderr.html#setting-capturing-methods-or-disabling-capturing).

**Comment by Decee1** [comment]
@The-Compiler Half yes half no
If I try with the function above - yes it does give it's feedback doing error raise but it does not do it live.
BUT in my case and the example I shown it does do what I requested. 
I should just RTFM
I accept the solution - NC
