### ISSUE TITLE
Document `pytest.warns` that matching things with parenthesis needs to be escaped.

### ISSUE THREAD

**Issue by BurnzZ** [pytest-dev/pytest#10595]
There are some cases where we mention a function in a `UserWarning` with the parenthesis. A simple string matching wouldn't work despite the annotation being `match: Optional[Union[str, Pattern[str]]]`.

Example on `pytest==7.2.0`:

```python
>>> with pytest.warns(UserWarning, match="issue with foo() func"):
...     warnings.warn("issue with foo() func")
Traceback (most recent call last):
  ...
Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) matching the regex were emitted.
 Regex: issue with foo() func
 Emitted warnings: [UserWarning('issue with foo() func')]

>>> with pytest.warns(UserWarning, match="issue with foo\(\) func"):
...     warnings.warn("issue with foo() func")
```

**Comment by The-Compiler** [comment]
The docs indeed are rather confusing about this, surprisingly! Both the [how-to](https://docs.pytest.org/en/7.2.x/how-to/capture-warnings.html#warns) and the [reference](https://docs.pytest.org/en/7.2.x/reference/reference.html#pytest.warns) say:

> [...] the keyword argument `match` to assert that the warning matches a text or regex:

and show a rather confusing example:

```python
with warns(UserWarning, match='must be 0 or None'):
    warnings.warn("value must be 0 or None", UserWarning)

with warns(UserWarning, match=r'must be \d+$'):
    warnings.warn("value must be 42", UserWarning)
```

This seems to have been fixed for `pytest.raises` in 8b34d981fc378f06b65d0866e6bd2c66d29680b3 for #5208, looks like we should do a very similar change for `pytest.warns` as well.
