### ISSUE TITLE
pytest does not use colors unless you tell it to or define PY_COLORS=1

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#10596]
I was a bit surprised to see that pytest refused to use ANSI coloring unless we passed PY_COLORS=1. On my machine I already have this in my profile and usually this is also included in  CI/CD pipeline definitions but... why not detecting the tty and using colors by default?

PS. Some new users might believe that the tool has no nice colors.

**Comment by The-Compiler** [comment]
Not sure how you're getting to this conclusion? Of course pytest [automatically enables colors](https://github.com/pytest-dev/pytest/blob/b31db4809be18b43ba714b80b10285b463cc9315/src/_pytest/_io/terminalwriter.py#L36) if the output is a terminal...

**Comment by ajinkyau** [comment]
@The-Compiler I was testing this on the macOS terminal (without any modifications to the same) and it did not show me any colors.
As mentioned by @ssbarnea I had to pass PY_COLORS=1 variable to enable colors.

**Comment by ssbarnea** [comment]
What is the value of your TERM variable?

**Comment by ssbarnea** [comment]
@ajinkyau please try to debug the https://github.com/pytest-dev/pytest/blob/b31db4809be18b43ba714b80b10285b463cc9315/src/_pytest/_io/terminalwriter.py#L26 function manually to see why pytest does not enable color on your macos. I seen it myself on the call, but you need to find-out why it behaves like this, is not expectd.

**Comment by The-Compiler** [comment]
I don't see anything actionable there as long as we don't get any more detailed information. Closing as can't reproduce.
