### ISSUE TITLE
pytest -W: prepend instead of append

### ISSUE THREAD

**Issue by adamjstewart** [pytest-dev/pytest#10613]
#### What's the problem this feature will solve?

I'm maintaining a library and would like to make sure I'm not using features deprecated in my dependencies. I can do this using `pytest -W error`, which will fail in CI if any warnings are raised. However, many of my dependencies also use features deprecated in other dependencies. I'm unaware of a way to filter out issues with deps of deps, so I instead maintain a list of specific warnings to ignore [here](https://github.com/microsoft/torchgeo/blob/v0.3.1/pyproject.toml#L56,L98). This works great in CI, but locally, if I'm not using the latest version of my dependencies, additional warnings may be raised. I would like to see these warnings locally without them being fatal, but still have them be fatal in CI. If I remove "error" from the list, I get the behavior I would like to see locally, but in CI, if I add `pytest -W error`, it overrides all of my ignores.

#### Describe the solution you'd like

I see a few possible solutions to this problem. One possible solution is for `-W` to prepend to the `filterwarnings` listed in `pyproject.toml` instead of appending to it. Another solution that would preserve backwards compatibility would be to add a new flag (`--W-prepend`?) that has this behavior. Yet another solution would be for "error" to have lower precedence than "ignore" such that order is no longer important and an "error" at the end will be superseded by "ignore" earlier in the list.

#### Alternative Solutions

The only workaround I'm aware of at the moment is to remove "error" from `filterwarnings` in `pyproject.toml` (to get the behavior I want locally) and duplicate the entire list on the command line like `pytest -W error -W ignore:... ...` (to get the behavior I want in CI). It might also be possible to maintain two separate `pyproject.toml` files and point to a different one in CI. I could also of course keep adding every warning I encounter that I would like to ignore locally to this file. All of these workarounds are unideal and more difficult for me to maintain than the proposed solutions.

#### Additional context

Let me know if my use case isn't clear. Happy to clarify the behavior I'm trying to achieve.

**Comment by adamjstewart** [comment]
Another workaround is to keep the `pyproject.toml` strict and use `pytest -W default` on the command line. You end up seeing all of the warnings you've silenced in `pyproject.toml` (which is unideal) but it doesn't fail.

**Comment by Zac-HD** [comment]
Unfortunately I think that compatibility constraints make it very hard to ship this in Pytest itself, but I'd love to see a third-party plugin implementing a `--warnings-prepend=` argument.

**Comment by adamjstewart** [comment]
Unfortunately we ended up removing `-Werror` from our `pyproject.toml` as it wasn't sustainable. Hopefully someday it will be possible to optionally cast warnings to errors without repeating the entire contents of `pyproject.toml` on the command line.
