### ISSUE TITLE
How to force pytest to read options from commandline only, and ignore config files?

### ISSUE THREAD

**Issue by jhj0411jhj** [pytest-dev/pytest#10625]
#### What's the problem this feature will solve?

Suppose the pytest config file `pyproject.toml` is in the project directory:
```
[tool.pytest.ini_options]
addopts = "-rap --capture=tee-sys"
```
I usually use the options in this file when running the command `pytest`. And the options are automatically read from the file.

However, sometimes I want to run pytest with `-rA` **only**:
```
pytest -rA    # it becomes: pytest -rA --capture=tee-sys
```
I have to run it with: `pytest -rA --capture=fd` to override the option `--capture=tee-sys` in the config file.

Is there any way to **force pytest to read options from commandline only**?

**What I've tried:**

In @Andrei 's answer of this question: https://stackoverflow.com/questions/32444402/is-there-an-option-for-pytest-to-ignore-the-setup-cfg-file

Use `-c /dev/null` will prevent pytest from finding the config file. I also find that set `-c any-non-exist-path` is ok.

However, I'm afraid if `-c /dev/null` has **side effects**. In pytest docs (https://docs.pytest.org/en/latest/reference/customize.html#finding-the-rootdir), it says `If -c is passed in the command-line, use that as configuration file, and its directory as rootdir`. I don't know what will happen if **rootdir is set as a non exist dir**.

#### Describe the solution you'd like

Add an option in pytest commandline to prevent loading options from config files.

**Comment by Zac-HD** [comment]
Closing as stale; maybe try StackOverflow?

**Comment by q-wertz** [comment]
Stumbled into the same problem:

For the unittests running in a GitLab runner I want different settings than for my local development.
Especially the drop to PDB on failure (`-x --pdb`) does not really make sense on a server but I would like to have it as default for local test execution...

**Comment by The-Compiler** [comment]
@q-wertz Consider perhaps setting `PYTEST_ADDOPTS=-x --pdb` in your environment locally instead.

**Comment by q-wertz** [comment]
Disadvantage of this method is (I think) that everybody would have to do this on his local machine while the `pyproj.toml` enforces the same behavior for everyone who clones the repo...
