### ISSUE TITLE
Distinguish parametrized classes and methods in output strings

### ISSUE THREAD

**Issue by rcomer** [pytest-dev/pytest#10639]
#### What's the problem this feature will solve?

Over at https://github.com/pytest-dev/pytest-xdist/issues/759, a few users agree that they would like loadscope to send parametrized classes to different workers.  If I have understood, pytest-xdist relies on the string generated by pytest to [decide  what goes where](https://github.com/pytest-dev/pytest-xdist/blob/9b0b5b1495b024940e3f5c71583711be46df255b/src/xdist/scheduler/loadscope.py#L270-L292).  At the moment these strings are indistinguishable.  For example

```python
import pytest

class TestA:
    @pytest.mark.parametrize('foo', [1])
    def test_stuff(self, foo):
        pass
    
@pytest.mark.parametrize('foo', [1])
class TestB:
    def test_stuff(self, foo):
        pass
```

The output strings here are

```
test_class_param.py::TestA::test_stuff[1]
test_class_param.py::TestB::test_stuff[1]
```

#### Describe the solution you'd like

Change the parametrized class output so instead we get something like
```
test_class_param.py::TestA::test_stuff[1]
test_class_param.py::TestB[1]::test_stuff
```

**Comment by RonnyPfannschmidt** [comment]
strucutrally parameterization happens always at the function level, its a major change of collection and parametreization to change that

xdist should instead grow a mechanism to transfer details of parameter ids and scopes along with collected test ids
