### ISSUE TITLE
Add varying verbosity option for different tests

### ISSUE THREAD

**Issue by SXHRYU** [pytest-dev/pytest#10633]
#### What's the problem this feature will solve?
Some tests' output need to be very verbose to understand the problem with code, while the same level of verbosity will just waste terminal space for other tests.

#### Describe the solution you'd like
Perhaps a `@pytest.mark.verbosity('-v') | @pytest.mark.verbosity('-vv')` decorator which will overwrite the option given in command line. Meaning if we launch pytest like `pytest .` but we have a test with `@pytest.mark.verbosity('-vv')`, then the result will be non-verbose for every test except the decorated one.

I've come up with this idea while testing that my python app opens the correct file: `pytest -vv`. And when the tast failed I was presented with unending red stream of bytes, which I had to **Ctrl+C** cancel (img below).

![image](https://user-images.githubusercontent.com/93727145/210575522-99d0e064-925f-41dd-86b2-26ed8ab6faed.png)

(I then ran the test with less verbosity to understand the problem, and it just happened that I wrote `open("foo")` instead of `open("foo").read()`)

![image](https://user-images.githubusercontent.com/93727145/210576436-0af7bb1d-c05f-4a99-9879-dc6e1f684f96.png)

The thing is I have different other tests in the same file which **require** verbosity to understand the problem. So as I have it right now, I need all other tests like `-vv`, but the tests regarding files like `-v`. This is the use case that I ran into, but I think this feature would be a good addition to pytest overall.

#### Alternative Solutions
As of now I have separated file-accessing tests into a different pytest module and wrote a shell script that launches these 2 files separately with different verbosity levels. It doesn't clutter terminal output on fail, but there's a lot of extra text overhead from launching 2 pytest instances.

#### Comments
I've tried searching on Github or Google if this is already implemented in pytest, and found nothing. If you know of a working solution on the web for this problem, please link here and sorry for the inconvenience.

**Comment by RonnyPfannschmidt** [comment]
Chances are this feature will get most people into sabotaging debugging for others by chance

[see pauls post on attractive nuisance ](https://blog.ganssle.io/articles/2023/01/attractive-nuisances.html )

**Comment by Pierre-Sassoulas** [comment]
> which will overwrite the option given in command line.

I think "modifying the default value if nothing is given by the user in command line" would make more sense.

**Comment by Zac-HD** [comment]
I recommend using `-v` for verbosity together with `-k` to select just the tests that you want verbose output from.
