### ISSUE TITLE
Junit output is incorrect when run with xdist plugin

### ISSUE THREAD

**Issue by acloyd** [pytest-dev/pytest#1066]
When running a set of tests using xdist, the junit output file is not correct. Sometimes failures are printed in the wrong test. The times for how long the tests take also get messed up. This does not happen using pytest-2.7.3

Installed python modules:
```
pip freeze
apipkg==1.4
configobj==5.0.6
execnet==1.4.1
py==1.4.30
pytest==2.8.0
pytest-xdist==1.13.1
requests==2.7.0
six==1.9.0
wheel==0.24.0
```

Example test file that causes the failure. In this example, the output junit file shows that test_B_1 fails even though it as A_1 that failed.
```
import time
import pytest


def test_A_1(request):
    time.sleep(6)
    assert False

def test_A_2(request):
    return

def test_B_1(request):
    time.sleep(20)
    return

def test_B_2(request):
    return

```

Command to run:
```
py.test --junitxml=/tmp/out.xml -n 2
```

Mac OS 10.5.5

**Comment by nicoddemus** [comment]
Thanks for the report! I'm closing this though as it is the same as #1064.

**Comment by acloyd** [comment]
Ya, sorry. I searched yesterday, but wrote it today.

**Comment by nicoddemus** [comment]
No worries, thanks for taking the time to write an come up with an example!
