### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by oleg-alexandrov** [pytest-dev/pytest#1067]
The link http://pytest.org/latest/pytest.pdf mentioned at http://pytest.org/latest/example/ is broken.

**Comment by nicoddemus** [comment]
Thanks for the heads-up! :smile:

Could someone else push the the PDF documentation? I'm on Windows, and installing LaTeX is not that trivial... :grin:

**Comment by nicoddemus** [comment]
Fixed in `2.8.1`
