### ISSUE TITLE
Backport workflow: maintain authorship

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#10676]
Maintain commit authorship when creating the backport PR.

**Comment by antonblr** [comment]
I believe it will be fine if we limit the PR merge actions to `"Squash and Merge"` button only.

e.g. these PRs merge commit authorship got overridden by the mergers (I assume `"Create a merge commit"` button was used):
* https://github.com/pytest-dev/pytest/pull/10660. (<-- this one caused backport to produce a PR with different commit author)
* https://github.com/pytest-dev/pytest/pull/10632

these are fine - the merge commit author preserved, even it was merged by another person:
* https://github.com/pytest-dev/pytest/pull/10725
* https://github.com/pytest-dev/pytest/pull/10624


The following line gets the commit sha of the merged PR for backporting and depends on merge type the author will be the one who fixed the issue, or the one who merged the PR:
https://github.com/pytest-dev/pytest/blob/31ad577325e571ff68a21de80be1ad8736fc122b/.github/workflows/backport.yml#L43

**Comment by webknjaz** [comment]
#12475 implements this, I believe.
