### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by oleg-alexandrov** [pytest-dev/pytest#1068]
I installed pytest and xdist. Latest version apparently:

py.test --version

This is pytest version 2.8.0,

Following http://pytest.org/latest/xdist.html?highlight=xdist I run:

py.test -n 4

py.test: error: unrecognized arguments: -n

Also for: 

 py.test -d

usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: -d

**Comment by nicoddemus** [comment]
Hi, 

I just installed it into a fresh pytest environment and everything seems to be working. How did you install it? What's the output when you run `py.test`? You should see installed plugins right in the header:

```
============================= test session starts =============================
platform win32 -- Python 2.7.10, pytest-2.8.0, py-1.4.30, pluggy-0.3.1
rootdir: X:\temp\x, inifile:
plugins: xdist-1.13.1
collected 2 items
```

**Comment by oleg-alexandrov** [comment]
I figured out the problem. pytest could not find xdist. It would have been nice to have some kind of informative error message. It is overall confusing that xdist is a separate package.

**Comment by RonnyPfannschmidt** [comment]
@oleg-alexandrov the documentation you referred to has nice big sections about first installing it links to its package and so on, i don't see how we can really improve on that 

also having py.tests own code keep track of options of external plugins or 3rd party plugins add is counterproductive in various ways
