### ISSUE TITLE
Pytest's `--doctest-modules` raises error at line break for linted code

### ISSUE THREAD

**Issue by fxmarty** [pytest-dev/pytest#10688]
Hi, just came across this issue:

````
This is a very dummy example.

```python
>>> from pprint import pprint

# Loading ONNX Model from the Hub
>>> pprint("
>>>     This is me!"
>>> )
'This is me!'

```
````

Using then `pytest --doctest-modules my_doc.mdx --doctest-glob="*.mdx"` will raise:

```
UNEXPECTED EXCEPTION: SyntaxError('EOL while scanning string literal', ('<doctest optimization.mdx[1]>', 1, 9, 'pprint("\n'))
Traceback (most recent call last):
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/doctest.py", line 1334, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest optimization.mdx[1]>", line 1
    pprint("
            ^
SyntaxError: EOL while scanning string literal
```

If I remove the newline, everything is fine.

This makes it inconvenient, because if the code is typically linted in the black style it can't run with doctest.

## system
pytest version: 7.2.1
5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by RonnyPfannschmidt** [comment]
This is incorrect syntax, multiline strings need triple quotes

**Comment by fxmarty** [comment]
Thanks @RonnyPfannschmidt , the issue was using `>>>` instead of `...` for the line breaks.
