### ISSUE TITLE
@pytest.mark.parametrize tag

### ISSUE THREAD

**Issue by ginneapig** [pytest-dev/pytest#10682]
Is it possible to change it to "@pytest.mark.parameterize" ?

- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
It's absolutely unclear what is even being asked for

**Comment by The-Compiler** [comment]
Note also that both "parametrize" and "parameterize" are valid English spellings. There are no plans to change pytest from the former to the later (if that's what you meant), as this would introduce a crazy amount of breakage with pretty much no gain.
