### ISSUE TITLE
Mention CI and BUILD_NUMBER in Environment Variables section in the docs

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#10690]
I'm new to pytest, but should ["CI" and "BUILD_NUMBER"](https://github.com/pytest-dev/pytest/blob/main/src/_pytest/assertion/util.py#L519-L522) be added to the ["Environment Variables" section ](https://docs.pytest.org/en/7.2.x/reference/reference.html#environment-variables)of the reference?

_Originally posted by @TurekBot in https://github.com/pytest-dev/pytest/issues/9933#issuecomment-1397920487_

**Comment by MarcBresson** [comment]
it should also be printed by `pytest -h` and updated in https://docs.pytest.org/en/latest/reference/reference.html#command-line-flags
