### ISSUE TITLE
Docs request: inclusion of flake8-pytest-style

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pytest#10709]
#### What's the problem this feature will solve?

I have been a long time `pytest` user and think it's is amazing.

I discovered [`flake8-pytest-style`](https://pypi.org/project/flake8-pytest-style/) ([repo](https://github.com/m-burst/flake8-pytest-style)) and was quite impressed with it.  I found it makes a lot of quality suggestions on how to better leverage the `pytest` library.  Also, it has good docs on the rationale behind each suggestion.

#### Describe the solution you'd like

There is the [Plugin List](https://docs.pytest.org/en/stable/reference/plugin_list.html) page that lists `pytest` plugins to help one test better with `pytest`.

I think it would be cool to list tools that helps users use the `pytest` library itself better.  `flake8-pytest-style` is one of those tools, I am not sure if there are others.  Perhaps this could be done on the same docs page, or in a new one.

Thanks for entertaining this!  I made this issue because, if I knew about this flake8 plugin, I would have used it much sooner!

**Comment by RonnyPfannschmidt** [comment]
I was unaware of this myself

This certainly should be crosslinked

It could also use some docs for usage with pre-commit

Input from @m-burst would be appreciated

**Comment by The-Compiler** [comment]
I suppose it could be on the [Good Integration Practices — pytest documentation](https://docs.pytest.org/en/latest/explanation/goodpractices.html) page, where we also mention e.g. `tox`.

**Comment by bluetech** [comment]
flake-pytest-style is very nice. Only rule I turn off is PT004 "Fixture does not return anything, add leading underscore".

Also worth mentioning that it's available in [Ruff](https://github.com/charliermarsh/ruff#flake8-pytest-style-pt), with autofixes for some of the rules. That's how I became aware of it at least.
