### ISSUE TITLE
`pytest_assertrepr_compare` doesn't run if subclassing a class from a different file

### ISSUE THREAD

**Issue by mikicz** [pytest-dev/pytest#10703]
`pytest_assertrepr_compare` doesn't run if subclassing a class from a different file. Minimal example at https://github.com/mikicz/pytest-minimal-assertrepr-compare-example.

I have a custom util class for comparing dictionaries (see [tests/utils.py](https://github.com/mikicz/pytest-minimal-assertrepr-compare-example/blob/main/tests/utils.py)), and hook `pytest_assertrepr_compare` to display the results nicely (see [conftest.py](https://github.com/mikicz/pytest-minimal-assertrepr-compare-example/blob/main/conftest.py)).

If I use it in simple test function it works correctly and everything gets printed (see [tests/test_function.py](https://github.com/mikicz/pytest-minimal-assertrepr-compare-example/blob/main/tests/test_function.py)), if I use it in a simple class it also works (see [tests/test_class.py](https://github.com/mikicz/pytest-minimal-assertrepr-compare-example/blob/main/tests/test_class.py)).

If I define a test on a base test class and subclass that class, it works correctly and everything gets printed (see [/tests/test_base_class_same_file.py](https://github.com/mikicz/pytest-minimal-assertrepr-compare-example/blob/main/tests/test_base_class_same_file.py)).
```
______________________________________________________________________________________________________ TestImplementation.test_invalid _______________________________________________________________________________________________________

self = <tests.test_base_class_same_file.TestImplementation object at 0x7f1318588a50>

    def test_invalid(self):
>       assert {"a": True} == ExpectedDict({"a": False})
E       assert dictionary matches expectation
E         a: False != True

tests/test_base_class_same_file.py:9: AssertionError
```

However the moment I move the base class to a separate file ([tests/base_class_separate_file.py](https://github.com/mikicz/pytest-minimal-assertrepr-compare-example/blob/main/tests/base_class_separate_file.py) and [tests/test_base_class_separate_file.py](https://github.com/mikicz/pytest-minimal-assertrepr-compare-example/blob/main/tests/test_base_class_separate_file.py)), `pytest_assertrepr_compare` stops working.

```
______________________________________________________________________________________________________ TestImplementation.test_invalid _______________________________________________________________________________________________________

self = <tests.test_base_class_separate_file.TestImplementation object at 0x7f131843e190>

    def test_invalid(self):
>       assert {"a": True} == ExpectedDict({"a": False})
E       AssertionError

tests/base_class_separate_file.py:9: AssertionError
```

Other details:

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

```
$ cat /etc/fedora-release 
Fedora release 37 (Thirty Seven)
$ python --version
Python 3.11.1
$ pip list
Package    Version
---------- -------
attrs      22.2.0
iniconfig  2.0.0
packaging  23.0
pip        22.2.2
pluggy     1.0.0
pytest     7.2.1
setuptools 62.6.0

[notice] A new release of pip available: 22.2.2 -> 23.0
[notice] To update, run: pip install --upgrade pip
```

**Comment by The-Compiler** [comment]
Does it work after you call [`pytest.register_assert_rewrite("tests.base_class_separate_file")`](https://docs.pytest.org/en/latest/how-to/writing_plugins.html#assertion-rewriting))?

If so, this seems like expected behavior to me, see [How to write and report assertions in tests — pytest documentation](https://docs.pytest.org/en/latest/how-to/assert.html#assertion-introspection-details).

**Comment by mikicz** [comment]
Ah, yes it does! I was not aware that was a thing - pytest always just "worked" with everything I threw at it, so didn't know I had to something extra to make this work. Thanks for pointing me to it!
