### ISSUE TITLE
Include timestamps in reportlog

### ISSUE THREAD

**Issue by HTRafal** [pytest-dev/pytest#10710]
#### What's the problem this feature will solve?

When parsing pytest report (in my case --reportlog file) TestReport objects only contain duration information. I'm missing start and stop timestamps to be able to correlate test results with external events.
#### Describe the solution you'd like

TestReport objects should have .start and .stop attributes set, which can easily be copied from CallInfo objects in TestReport.from_item_and_call

#### Alternative Solutions

I considered adding it to pytest-reportlog here - https://github.com/pytest-dev/pytest-reportlog/pull/22, but we agreed that core pytest is a better place for such change.
#### Additional context

Initial feature request in pytest-reportlog - https://github.com/pytest-dev/pytest-reportlog/issues/19

**Comment by BeyondEvil** [comment]
pytest-html should support this feature.
