### ISSUE TITLE
Issue warning on unconsumed generator

### ISSUE THREAD

**Issue by roysmith** [pytest-dev/pytest#10714]
I was testing a function to see if it logged a particular error message.  Essentially:

```
def test_foo_logs_message(caplog):
    foo(bad_input)
    assert "my error message" in caplog.text
```
The test was unexpectedly failing and I couldn't figure out why.  The problem turned out to be that foo() returned a generator and since this test never consumed the output, the function never actually executed.  Much hair-pulling-out and head-banging-on-desk ensued before I realized my mistake.

I don't know if this is feasible, but it would be very cool if pytest could recognize when you call a function that returned a generator but you never consume it.  In my case, the function was annotated as returning "Iterable[str]", so I think there was enough information to do this via static analysis.  Or maybe it needed to be Generator[str]?

The more general use case would be anytime you're calling a generator to test a side effect.  Might be logging, might be raising an exception.  Might be assertions against calls to back-end mocks.  It's the kind of mistake you'd never make in production code because you're likely to always want the generated output, but not that uncommon in test code.

Anyway, just an idea.

**Comment by RonnyPfannschmidt** [comment]
Static analyst can't help there

A gc collection may trigger builtin warnings of python

**Comment by nicoddemus** [comment]
Python now generates a warning if an async function is not awaited, so perhaps it is possible for Python to generate a warning for a generator which is never consumed?

Anyway does not seem viable/feasible to implement this in pytest reliably, but thanks for the suggestion anyway!
