### ISSUE TITLE
Incorrect documentation describing registering entry points with pyproject.toml

### ISSUE THREAD

**Issue by connorjward** [pytest-dev/pytest#10721]
On the "Writing plugins" page of the documentation the section on [Making your plugin installable by others](https://doc.pytest.org/en/latest/how-to/writing_plugins.html#making-your-plugin-installable-by-others) is not quite right. It states that the recommend way to register `pytest11` entry-points is to write:
```
[project.entry_points]
pytest11 = [
    "myproject = myproject.pluginmodule",
]
```
but since `pyproject.toml` here is set to use Hatchling it should actually be ([source](https://hatch.pypa.io/latest/config/metadata/#plugins)):
```
[project.entry-points.pytest11]
myproject = "myproject.pluginmodule"
```

The sample `pyproject.toml` also includes the lines:
```
[tool.setuptools]
packages = ["myproject"]
```
which I doubt are needed.

**Comment by The-Compiler** [comment]
cc @doublevcodes who seems to have written the example as part of #10359. It looks like it was originally written for `setuptools`, and then @nicoddemus changed the backend to hatchling without adjusting any of the content :slightly_smiling_face:

**Comment by itsmegarvi** [comment]
I can do the correction,if noone else is doing it

**Comment by nicoddemus** [comment]
😅 

@itsmegarvi we would definitely appreciate it, thanks!

**Comment by itsmegarvi** [comment]
I have made the changes please review it

**Comment by ofek** [comment]
Hello! Just to clarify for people stumbling upon this as I have: this is not related to Hatchling per se but rather is due to switching to PEP 621 metadata
