### ISSUE TITLE
INTERNALERROR when skipping a test if using --html=report.html (pytest 7.2.1)

### ISSUE THREAD

**Issue by rock0232** [pytest-dev/pytest#10748]
============================= test session starts =============================
collecting ... collected 1 item

test_b2c.py::Test_commonlogin::test_thalaiva 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\_pytest\main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\_pytest\main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>                                                          ^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\_pytest\main.py", line 349, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>                                                          ^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\_pytest\runner.py", line 112, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\_pytest\runner.py", line 125, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\_pytest\runner.py", line 222, in call_and_report
INTERNALERROR>     report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>                                                          ^^^^^^^^^^^^^^^
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\pluggy\callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "E:\Rock_Selenium\Automation Project\mainproject\venv\Lib\site-packages\_pytest\skipping.py", line 274, in pytest_runtest_makereport
INTERNALERROR>     elif not rep.skipped and xfailed:
INTERNALERROR>              ^^^^^^^^^^^
INTERNALERROR> AttributeError: 'generator' object has no attribute 'skipped'

======================== 1 warning in 66.07s (0:01:06) ========================

Process finished with exit code 3

**Comment by RonnyPfannschmidt** [comment]
With the provided details all we can do is close as not actionable
