### ISSUE TITLE
Session scoped fixture getting invoked multiple times when defined within a class

### ISSUE THREAD

**Issue by hprem** [pytest-dev/pytest#10759]
**Issue:**
On decorating a parent class with `@pytest.mark.usefixtures("setup")`, where the fixture `setup` has `session` scope, the fixture gets triggered once for each child class. But instead it should be invoked only once

This happens only when the fixture is defined with the the parent class. It works fine when the fixture is defined outside of the parent class

**Minimal Example:**
Consider the following simple example

```python
import pytest

@pytest.mark.usefixtures("setup")
class Parent(object):

    @classmethod
    @pytest.fixture(scope='session')
    def setup(cls):
        print (f'\nIn setup {cls=}')
        yield
        print ('\nIn cleanup')

class TestChild1(Parent):
    def test_child1(self):
        pass

class TestChild2(Parent):
    def test_child2(self):
        pass
```

On running the above test, you can see that the `setup` fixture is getting invoked twice (once for each child class). But as it is defined as a fixture with `scope=session`,  it should be run only once
```
❯ pytest -s
==================================================== test session starts =====================================================
platform linux -- Python 3.9.2, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/hprem/tmp2/pytest/test2
plugins: reportportal-5.1.3, anyio-3.6.2, dependency-0.5.1, check-1.0.9, repeat-0.9.1
collected 2 items

test_new.py
In setup cls=<test_new.TestChild1 object at 0x7f7b9afd9670>
.
In setup cls=<test_new.TestChild2 object at 0x7f7b9afd9070>
.
In cleanup

In cleanup
```

**Version:**
``platform linux -- Python 3.9.2, pytest-7.2.1, pluggy-1.0.0``

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell, the observed behaviour is as "intended"

each class has a own fixture  discovered and set up

we should probably warn about this as teardown still happens at session scope teardown, not at last use

**Comment by hprem** [comment]
@RonnyPfannschmidt Does that mean `scope` doesn't have any meaning when attaching fixtures to a class in this manner?

That doesn't make sense. As I said earlier, on slightly modifying the above scenario, by moving the fixture outside the class, the fixture gets invoked only once, as indended. 

```python
import pytest

@pytest.fixture(scope='session')
def setup():
    print ('\nIn setup')
    yield
    print ('\nIn cleanup')

@pytest.mark.usefixtures("setup")
class Parent(object):
    pass

class TestChild1(Parent):
    def test_child1(self):
        pass


class TestChild2(Parent):
    def test_child2(self):
        pass
```

```
❯ pytest -s test2
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.9.2, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/hprem/tmp2/pytest
plugins: reportportal-5.1.3, anyio-3.6.2, dependency-0.5.1, check-1.0.9, repeat-0.9.1
collected 2 items

test2/test_new.py
In setup
..
In cleanup
```

**Comment by RonnyPfannschmidt** [comment]
Scope has a meaning, its just that pytest considers the fixture necessarily different for each class and thus the effect you describe happens

Pytest should warn Abo that case

**Comment by hprem** [comment]
It still doesn't make any sense. why does it work fine in the second scenario?

We are seeing two differnt behaviours for two almost similar cases. One of them is the desired behaviour. Shouldn't the other behaviour be considered a bug?

**Comment by RonnyPfannschmidt** [comment]
It's not a bug, it's intended behaviour

Each fixtures in the class case gets called with a different cls

**Comment by hprem** [comment]
OK... I understand now. Thanks for your patience
