### ISSUE TITLE
ValueError: PurePosixPath('.') has an empty name

### ISSUE THREAD

**Issue by chingc** [pytest-dev/pytest#10764]
Hi, I'm running Python 3.11.2 and pytest 7.2.1 on macOS (Ventura 13.1) with Apple Silicon and I'm running into the following error:

```
ValueError: PurePosixPath('.') has an empty name
```

I was able to trace the error to this change: https://github.com/pytest-dev/pytest/commit/f92c4a77ada65a40700272c5af8cef302dbb4c27

The error occurs when calling `with_suffix` when `parts` is an empty list.  Here's an example:

```
Python 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import os
>>> from pathlib import PurePath
>>> parts = ['']

# result is the same when not dealing with the suffix
>>> PurePath(os.path.sep.join(parts)) == PurePath(*parts)
True

# old code: empty parts with suffix returns the suffix
>>> PurePath(os.path.sep.join(parts) + ".py")
PurePosixPath('.py')

# new code: empty parts with suffix throws an exception
>>> PurePath(*parts).with_suffix(".py")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 694, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: PurePosixPath('.') has an empty name
```

I haven't been able to figure out why `parts` is ever empty, but with what I know I was able to temporarily workaround this problem by downgrading to pytest 7.1.2.

**Comment by theirix** [comment]
Could you please describe a project layout or example where you have got this error? Could not reproduce it.

**Comment by jgarvin** [comment]
@theirix  can confirm this still exists. I use this code to import a module at runtime:

```
def _import_from_filename(file_path: Path) -> ModuleType:
    """Try to import with exactly the module path we would have gotten
    had we imported manually."""
    relative_path = file_path.strict_relative_to(SOURCE_ROOT.get())
    module_name = str(relative_path.with_suffix('')).replace('/', '.')

    if module_name in sys.modules:
        log.info(f"Already imported {module_name}")
        return sys.modules[module_name]  # already imported

    log.info(f"Importing module={file_path}")
    spec = importlib.util.spec_from_file_location(module_name, file_path)
    assert spec
    assert spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module
```

that module contains a relative import:

```
from .rule_a import a_rule
```

which triggers the error

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/pull/11426 should be there fix

**Comment by jgarvin** [comment]
@RonnyPfannschmidt I did a fresh `python3.11 -m pip install 'pytest @ git+https://github.com/pytest-dev/pytest.git'` but still get the error

**Comment by The-Compiler** [comment]
Can you please share the full output and ideally a reproducer we can run?

**Comment by nicoddemus** [comment]
Wait, what does the code posted in https://github.com/pytest-dev/pytest/issues/10764#issuecomment-1720209230 has to do with pytest? IIUC, that's custom code which uses `importlib`, but has no relation to pytest.

**Comment by jonross** [comment]
FYI, with `datadog==0.5.0`, `ddtrace==2.17.2`, and `pytest==8.3.4`

Also triggered by a call to `importlib`.
IDK what causes `importlib` to jump into `pytest`, assertion rewriting maybe?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ddtrace/settings/_inferred_base_service.py", line 189, in detect_service
    metadata = detector.detect(args_to_search)
  File "/usr/local/lib/python3.10/dist-packages/ddtrace/settings/_inferred_base_service.py", line 71, in detect
    if _module_exists(arg):
  File "/usr/local/lib/python3.10/dist-packages/ddtrace/settings/_inferred_base_service.py", line 226, in _module_exists
    return importlib.util.find_spec(module_name) is not None
  File "/usr/lib/python3.10/importlib/util.py", line 103, in find_spec
    return _find_spec(fullname, parent_path)
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 98, in find_spec
    if self._early_rewrite_bailout(name, state):
  File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 209, in _early_rewrite_bailout
    path = PurePath(*parts).with_suffix(".py")
  File "/usr/lib/python3.10/pathlib.py", line 782, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: PurePosixPath('.') has an empty name
```

**Comment by dongfangtianyu** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/ddtrace/settings/_inferred_base_service.py", line 189, in detect_service
>     metadata = detector.detect(args_to_search)
>   File "/usr/local/lib/python3.10/dist-packages/ddtrace/settings/_inferred_base_service.py", line 71, in detect
>     if _module_exists(arg):
>   File "/usr/local/lib/python3.10/dist-packages/ddtrace/settings/_inferred_base_service.py", line 226, in _module_exists
>     return importlib.util.find_spec(module_name) is not None
>   File "/usr/lib/python3.10/importlib/util.py", line 103, in find_spec
>     return _find_spec(fullname, parent_path)
>   File "<frozen importlib._bootstrap>", line 945, in _find_spec
>   File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 98, in find_spec
>     if self._early_rewrite_bailout(name, state):
>   File "/usr/local/lib/python3.10/dist-packages/_pytest/assertion/rewrite.py", line 209, in _early_rewrite_bailout
>     path = PurePath(*parts).with_suffix(".py")
>   File "/usr/lib/python3.10/pathlib.py", line 782, in with_suffix
>     raise ValueError("%r has an empty name" % (self,))
> ValueError: PurePosixPath('.') has an empty name
> ```

@jonross  thanks for the information, can you provide an example that is easy to reproduce? 
I'll try to debug further when I have some time off, but not familiar with `datadog` and `ddtrace`.

Initial guess: the import hook implemented by pytest does not work well with other libraries

**Comment by RonnyPfannschmidt** [comment]
What values get passed in there 

If they are incorrect to begin with then we max need some protection

**Comment by jonross** [comment]
> can you provide an example that is easy to reproduce

No, but

> What values get passed in there

I can tell you that `find_spec` is receiving `"", None, None`

**Comment by RonnyPfannschmidt** [comment]
Its fair to fail ob empty string for fullname
