### ISSUE TITLE
Typewise comparisons

### ISSUE THREAD

**Issue by eugene-bright** [pytest-dev/pytest#10760]
#### What's the problem this feature will solve?

In many cases it's crucial not only compare the values as python does it but also the types.
The following test passes because `1 == 1.0` is `True` in python and during the deep structure comparison pytest doesn't perform the type checking, only plain python comparison.

```python
def test_numeric_comparison_is_not_typewise():
    assert {1: 1} == {1.0: 1.0}
```

#### Describe the solution you'd like

I'd like to have an option to enable strict type checking in addition to the value comparison.
Something like `pytest --strict-compare` should cause the test above to fail.

#### Alternative Solutions

There is an option to make a plugin, but I believe it should be done in the core pytest.

#### Additional context

The feature is in demand
https://stackoverflow.com/questions/38573862/how-to-assert-that-a-type-equals-a-given-value

**Comment by eugene-bright** [comment]
I thought I does rewrite just for that

**Comment by RonnyPfannschmidt** [comment]
No, rewrite adds debugging, it doesn't lie about the detail

**Comment by eugene-bright** [comment]
Ok, then the plugin option is the only way
