### ISSUE TITLE
pytester: add a concenience method to test of availiability of plugins in the host/subprocess

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1078]
with regressions and acceptance tests pytest tests as well as pytest plugin tests have needs for different sets of plugins

there should be helpers to warn/skip/document those needs in tests

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt can you describe this in more details if it is still relevant in your opinion?

**Comment by RonnyPfannschmidt** [comment]
Still relevant, needs a example

**Comment by RonnyPfannschmidt** [comment]
closing as i realized this one has the wrong perspective

theres already a number of issues with how to handle extra plugins installed
