### ISSUE TITLE
`filterwarnings` invalid escape sequence inconsistent behavior on MacOS

### ISSUE THREAD

**Issue by kev-zheng** [pytest-dev/pytest#10780]
- [x] a detailed description of the bug or problem you are having
pytest `filterwarnings` seems to have inconsistent behavior (perhaps due to python caching).

I can reproduce on an MacOS arm laptop that warnings can appear once, but do not appear another time. Also, the `filterwarnings` `error::DeprecationWarning` doesn't work, even though Python will fail it.

I don't have a Mac-intel laptop to test, but on some of our CI instances, we are able to reproduce that the Mac-Intel pytest version *does* discover the escape sequence `DeprecationWarning` and turns them (confusingly) into SyntaxError.

IMO that's not really an issue, since we do want to discover these errors. However, repeat runs *will succeed*, perhaps due to python caching. A combination of these commands have enabled me to help reproduce.
1) use a new PYTHONCACHEPREFIX (export PYTHONPYCACHEPREFIX="${HOME}/.cache/Python")
2) use PYTHONDONTWRITEBYTECODE=True
3) removing all `__pycache__`
- [x] output of `pip list` from the virtual environment you are using
```
pytest ❯❯ pip list
Package    Version
---------- -------
attrs      22.2.0
iniconfig  2.0.0
packaging  23.0
pip        23.0.1
pluggy     1.0.0
py         1.11.0
pytest     7.1.3
setuptools 67.4.0
tomli      2.0.1
wheel      0.38.4

```

- [x] pytest and operating system versions
```
pytest == 7.1.3
python==3.8.6
OS: Darwin-arm64
```
- [x] minimal example if possible

0)
conda version == 4.13.0
`conda create -n pytest`
`conda activate pytest`
`conda install -c conda-forge pytest==7.1.3 python==3.8.6`

1) Dump this into a script `test_stuff.py`
```
import pytest
@pytest.mark.filterwarnings("error::DeprecationWarning")
def test_stuff():
    hello = "\l"
```

2) Run `pytest test_stuff.py`, twice:
```
pytest ❯❯ pytest test_stuff.py
==================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.8.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/kevzheng/work/temporary3
collected 1 item

test_stuff.py .                                                                                                                                                                        [100%]

====================================================================================== warnings summary ======================================================================================
test_stuff.py:6
  /Users/kevzheng/work/temporary3/test_stuff.py:6: DeprecationWarning: invalid escape sequence \l
    hello = "\l"

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================ 1 passed, 1 warning in 0.01s ================================================================================

~/work/temporary3
pytest ❯❯ pytest test_stuff.py
==================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.8.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/kevzheng/work/temporary3
collected 1 item

test_stuff.py .                                                                                                                                                                        [100%]

===================================================================================== 1 passed in 0.00s ======================================================================================

```

3) Observe that python will fail this
```
~/work/temporary2
pytest ❯ python -We test_stuff.py                                                                                                                                                      ✘ 130
  File "test_stuff.py", line 6
    hello = "\l"
            ^
SyntaxError: invalid escape sequence \l
```

**Comment by asottile** [comment]
this warning only appears when compiling a pyc -- that's why you only experience it the first time and when you run python separately (which does not use pytest's modified pyc files)

**Comment by kev-zheng** [comment]
@asottile sorry, would you mind reopening this? I think the sentiment of my issue is really that the invalid escape sequences DeprecationWarning is *not* filtered out by `pytest.mark.filterwarnings`, which definitely seems like a bug.

Here's another quick example:

~/work/temporary4
pytest ❯❯ pytest
==================================== test session starts =====================================
platform darwin -- Python 3.8.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/kevzheng/work/temporary4
collected 2 items

test_stuff.py ..                                                                       [100%]

====================================== warnings summary ======================================
test_stuff.py:6
  /Users/kevzheng/work/temporary4/test_stuff.py:6: DeprecationWarning: invalid escape sequence \l
    hello = "\l"

test_stuff.py:10
  /Users/kevzheng/work/temporary4/test_stuff.py:10: DeprecationWarning: invalid escape sequence \l
    hello = "\l"

test_stuff.py::test_no_ignore_warnings
  /Users/kevzheng/work/temporary4/test_stuff.py:11: DeprecationWarning: test
    warnings.warn("test", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================== 2 passed, 3 warnings in 0.00s ================================

~/work/temporary4
pytest ❯❯ cat test_stuff.py
import pytest
import warnings

@pytest.mark.filterwarnings("ignore::DeprecationWarning")
def test_ignore_warnings():
    hello = "\l"
    warnings.warn("test", DeprecationWarning)

def test_no_ignore_warnings():
    hello = "\l"
    warnings.warn("test", DeprecationWarning)

**Comment by asottile** [comment]
yeah it's _syntax_ -- python compiles at a module unit not at a line unit
