### ISSUE TITLE
Feature Proposal: @mark.parametrize by type

### ISSUE THREAD

**Issue by voidus** [pytest-dev/pytest#10804]
#### What's the problem this feature will solve?

When we want to have an enumeration type as the parametrized arg, we need to repeat ourselves or define it outside of the test

```
@mark.parametrize('scenario', ['alpha', 'bravo'])
def test_foo(foo: Literal['alpha', 'bravo']):
    common_setup()
    match scenario:
         case 'alpha': ...
        case 'bravo': ...
        case other: typing.assert_never(other)
   assert whatever
```

#### Describe the solution you'd like
Add a sentinel value that instructs parametrize to derive the values from the type

```
@mark.parametrize('scenario', pytest.from_type)
def test_foo(foo: Literal['alpha', 'bravo']): ...
```

I'm using this in a few places in my code base. Afaict, the python community is still figuring out how it wants to use type annotations, especially at runtime, so I wouldn't call this idiomatic python, but I think it's neat anyways

#### Alternative Solutions
Repeating it isn't too bad tbh. I don't think we have another approach to avoid it while keeping the type checkers aware of the possible values for the argument though.

#### Feasability

```
In [19]: def foo(x: Literal['yes', 'no']):
    ...:     pass
    ...: 
# Check if it's a Literal
In [29]: typing.get_origin(typing.get_type_hints(foo)['x'])
Out[29]: typing.Literal
# Check for args and use them as value
In [30]: typing.get_args(typing.get_type_hints(foo)['x'])
Out[30]: ('yes', 'no')
```

Seems simple enough in isolation.

**Comment by Zac-HD** [comment]
[I've implemented this in Hypothesis](https://hypothesis.readthedocs.io/en/latest/details.html#inferred-strategies), and it's _way_ harder than you seem to think.  So while I think we shouldn't do this in Pytest, you can:

```python
from hypothesis import given

@given(foo=...)  # literal ellipses
def test_foo(foo: Literal['alpha', 'bravo']):
    print(foo)
```

**Comment by voidus** [comment]
If you have a minute I'd be very curious to hear what aspect makes it more complex. No pressure of course.

**Comment by Zac-HD** [comment]
The quickest way to convey the number of edge cases and version-specific workarounds involved is to just show you the code (and if you're brave, commit history) in Hypothesis:

https://github.com/HypothesisWorks/hypothesis/blob/d16e349dca8b029a8c2b52bc83ea8ca25a399a0b/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L988-L1239 and https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/strategies/_internal/types.py contain most of the logic.
