### ISSUE TITLE
fixture as a variable parameter for inplace change of fixture

### ISSUE THREAD

**Issue by fenchu** [pytest-dev/pytest#10817]
#### What's the problem this feature will solve?

https://stackoverflow.com/questions/73487040/pytest-fixtures-naming-as-a-variable

```
@pytest.mark.usefixtures("wdwire")
def test01_userportal_security(self, wdwire):
  """ using wdwire webdriver """
  url = tools.urls.urls['user-portal']['url']
  wdwire.get(url)
  :
```

```
@pytest.mark.usefixtures("wd")
def test01_userportal_security(self, wd):
  """ using standard webdriver """
  url = tools.urls.urls['user-portal']['url']
  wd.get(url)
  :
```

#### Describe the solution you'd like

```
@pytest.mark.usefixtures("wdwire")
def test01_userportal_security(self, wd=wdwire):
  """ using wdwire webdriver """
  url = tools.urls.urls['user-portal']['url']
  wd.get(url)
  :
```
So I do not have to have two identical tests where only change is wd|wdwire

#### Alternative Solutions

```
@pytest.mark.usefixtures("wdwire")
def test01_userportal_security(self, wd=wdwire):
  """ using wdwire webdriver """
  url = tools.urls.urls['user-portal']['url']
  wd.get(url)
  :
```
gives: NameError: name 'wd' is not defined

```
@pytest.mark.usefixtures("wdwire")
def test01_userportal_security(self, wd="wdwire"):
  """ using wdwire webdriver """
  url = tools.urls.urls['user-portal']['url']
  wd.get(url)
  :
```
gives: AttributeError: 'str' object has no attribute 'get'

#### Additional context

Is there a workaround, we have lots of tests that needs wdwire to be able to manipulate headers, but
it is slow and way to verbose for everything.

**Comment by RonnyPfannschmidt** [comment]
Define a local wd fixture that passes through the correct fixture

In the outlined usecase the use fixtures mark ough not to be used
