### ISSUE TITLE
[FR] give possibilty to warn the user if there is no mark on test cases

### ISSUE THREAD

**Issue by GeorgeFischhof** [pytest-dev/pytest#10813]
Hi,

#### What's the problem this feature will solve?
starting form this doc:
https://docs.pytest.org/en/7.1.x/how-to/mark.html#raising-errors-on-unknown-marks
when the user uses marks heavily, it would be good to get a warning when there is no any mark on a test case,  It would protect against forgetting to add a mark. 

#### Describe the solution you'd like
if --strict-markers or any newly added option is used, for example --warn-on-no-any-markers pytest should warn the user.
Any example for using a hook, create some script would be good as well

BR,
George

**Comment by nicoddemus** [comment]
I do not think this warrants a change in the core, as this seems like a very rare use case: I have never seen a test suite where all tests need a mark.

You can however easily implement this in your project by writing a [`pytest_collection_modifyitems`](https://docs.pytest.org/en/stable/reference/reference.html#pytest.hookspec.pytest_collection_modifyitems) hook in your root `conftest.py` (untested):

```python
# content of conftest.py
import pytest

def pytest_collection_modifyitems(items):
    for item in items:
        markers = list(item.iter_markers())
        if not markers:
            pytest.fail(f"item {item.nodeid} does not have any marks set")
```

You can even customize this to check if some specific marks are set, and even check their parameters if you want.

Closing this for now, feel free to follow up with more questions.

**Comment by GeorgeFischhof** [comment]
Thank you very much.
The above creates an internal error, and stops... this below customized version just prints the info and skips the tests, it is not so scary :)

```
import pytest

def pytest_collection_modifyitems(items):
    for item in items:
        markers = list(item.iter_markers())
        if not markers:
            print(f"item {item.nodeid} does not have any marks set")
            item.add_marker(pytest.mark.skip(reason=f"item {item.nodeid} does not have any marks set"))
```

BR,
George
