### ISSUE TITLE
Print reason of skipping things on running pytest

### ISSUE THREAD

**Issue by abcdenis** [pytest-dev/pytest#10826]
#### What's the problem this feature will solve?
I spent a lot of time figuring out why legacy test suite methods are not called by pytest.
PYTEST_DEBUG=1 gave me nothing.
Stackoverflow.com suggests me that  presence `__init__` method is the root of problem.

#### Describe the solution you'd like
Write to console the reason of skipping files/tests/classes along with reason in debug mode.

#### Alternative Solutions
google -> "test suite class tests are not running with pytest how to diagnose" -> stackoverflow.com

#### Additional context
None.

**Comment by itsJustAbe** [comment]
Trying to understand, you want to pass an argument where you can also see the reason for skipping a test ?

**Comment by Zac-HD** [comment]
Unfortunately, it's probably too difficult to consistently track and usefully report this information when there are so many different mechanisms which can cause tests to not be run.
