### ISSUE TITLE
Need a way to ignore a file during fixture function discovery

### ISSUE THREAD

**Issue by Tegular** [pytest-dev/pytest#10822]
Pytest is trying to discover fixture functions in a python file that I really want it to ignore. I've tried command line args `--ignore` and `--ignore-glob` as well as `collect_ignore` and `collect_ignore_glob` in conftest.py.

Some details.

I have a python implementation file (not a test file) in my code base that has an instantiation of a proxy class basically like this:

```
class LazyProxiedThing:

    def __getattr__(self, name):
        thing = SingletonThing.get()
        return getattr(thing, name)

thing = LazyProxiedThing()
```

During collection phase, pytest is invoking `__get_attr__` with `_pytestfixturefunction`, `__test__`, and `__bases__`.

I've had to add this guard to that function and it made me throw up a little.

```
if name in ('_pytestfixturefunction', '__test__', '__bases__'):
    raise AttributeError(f'object has no attribute {name}')
```

Please provide a way to skip specific files from fixture discovery. Or honor `--ignore` and `--ignore-glob`, `collect_ignore`, and/or `collect_ignore_glob`.

Thanks.

**Comment by nicoddemus** [comment]
`--ignore` and `--ignore-glob` are used only to collect tests, but pytest should not be looking at your file unless it matches the default [`python_files` setting](https://docs.pytest.org/en/stable/reference/reference.html#confval-python_files).

What's the name of the file that contains `LazyProxiedThing`?

**Comment by Tegular** [comment]
Thanks for the reply.

The path of the file in my repo is `lib/core/mongodb.py` (LazyProxiedThing is actually a MongoDB client). So based on that name, pytest will not look inside it. However, perhaps I import `thing` in one of my test files... I will investigate, thank you.

**Comment by RonnyPfannschmidt** [comment]
Im under the impression that a actual traceback would disclose those details

**Comment by Tegular** [comment]
Indeed the issue was due to me inadvertently importing `thing` in my test file.

For anyone who might stumble upon this thread facing the same issue... Invoke pytest with debugging turned on (`--debug=pytest.log`) and inspect it. Mine had this which should have been my clue:

```
        pytest_pycollect_makeitem [hook]
            collector: <Module test_uploads.py>
            name: thing
            obj: <core.mongodb.Thing object at 0x7ff614a0eb90>
```
