### ISSUE TITLE
Regression with parallel tests on 2.7.3 and 2.8

### ISSUE THREAD

**Issue by xavfernandez** [pytest-dev/pytest#1083]
Hello,
Some tests in pip test suite started failing with latest pytest releases:
- https://travis-ci.org/pypa/pip/builds/82695909 is develop with parallel testing and pytest==2.8 (2 tests failing)
- https://travis-ci.org/pypa/pip/builds/82716794 is develop but no parallel testing and pytest==2.8 (all green)
- https://travis-ci.org/pypa/pip/builds/82720894 is develop, parallel testing and pytest==2.7.3 (only test_install_from_local_directory_with_symlinks_to_directories failing, test_install_user_in_global_virtualenv_with_conflict_fails ok)
- https://travis-ci.org/pypa/pip/builds/82721613 is develop parallel testing and pytest==2.7.2 (all green)

**Comment by xavfernandez** [comment]
Bisecting indicated https://github.com/pytest-dev/pytest/commit/330de0a93db404921c7a4c80305b43fd87bc3119 as responsible cc @nicoddemus @RonnyPfannschmidt 

cf https://github.com/pypa/pip/pull/3341

I'm wondering if https://bitbucket.org/pytest-dev/py/src/b9cdab378c58c3c07dce13ab8bb58463ae6a0bba/py/_path/local.py?at=default&fileviewer=file-view-default#local.py-791:796 should be called with a keep number higher than 3 ?

**Comment by RonnyPfannschmidt** [comment]
hmm, indeed - i suspect this bug has been lingering longer, the structural change just makes it trigger more easily

**Comment by RonnyPfannschmidt** [comment]
due to race conditions it seems, that the lockfile creation and the folder creation can intersect badly now, since it got a lot faster - i propose switching to a datetime+pid based folder name in order to reduce the likelihood of collisions

@nicoddemus opinions?


i'd suggest a folder name like `2016-01-04+15:46:33+1337` concatenating date, time and pid

**Comment by nicoddemus** [comment]
> i propose switching to a datetime+pid based folder name in order to reduce the likelihood of collisions

Which folder exactly do you mean @RonnyPfannschmidt? For example, here's what Travis is creating:

```
 /tmp/pytest-of-travis/pytest-1/popen-gw0/<test-name>
```

**Comment by xavfernandez** [comment]
Any new idea ? :)

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt did you notice my question above? :grin:

**Comment by xavfernandez** [comment]
Any advancement ?
I'd like pip to keep on track with pytest :crying_cat_face:

**Comment by RonnyPfannschmidt** [comment]
i can put a focus on it next week, this has been delayed due to unrelated personal life events

**Comment by xavfernandez** [comment]
Any news ? :crying_cat_face:

**Comment by xavfernandez** [comment]
Gentle ping, I'd rather not have pip indefinitely stranded on `pytest==2.7.2` :-/

**Comment by RonnyPfannschmidt** [comment]
atm i cant promise anything wrt getting at it soonish

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt could please you explain in more detail why do you think there is a race condition with the lock creation? I ask because looking at `make_numbered_dir`, the directory creation should avoid any race condition:

```python
            try:
                udir = rootdir.mkdir(prefix + str(maxnum+1))
            except py.error.EEXIST:
                # race condition: another thread/process created the dir
                # in the meantime.  Try counting again
                if lastmax == maxnum:
                    raise
                lastmax = maxnum
                continue
```

IIUC, the lock file only exists so a directory in use won't be deleted by a new py.test session, but on Travis we only ever have one py.test session active at once (we create a temp directory for each session, with each slave reusing it).

Also, the original change only changed the tmp root directory and I suspect Travis's VMs contains a very small number of files in `/tmp`, so I don't see how that could affect the outcome of those tests. 

Any hints on what's on your mind about the problem might be helpful. :grin:

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt any further thoughts?

Either way, we really should tackle and solve this once and for all in the upcoming pytest sprint, in a couple of weeks.

**Comment by RonnyPfannschmidt** [comment]
after some more investigation it seems like the tmpdir initialization/re-initialization at slave startup happens multiple times, once with the xdist configuration, once without

**Comment by RonnyPfannschmidt** [comment]
this is related to #1618

**Comment by nicoddemus** [comment]
Opened pypa/pip#3863 which fixes this problem, although I couldn't identify why the original code did not work in the first place.

**Comment by RonnyPfannschmidt** [comment]
my current impression is that the initialization of the tmpdir handler on a remote pytest is incorrect and happens twice due to the option application happening after the pytest initialization instead of before

**Comment by xavfernandez** [comment]
Well, it's a good news that pip can now use the latest pytest.
But I'm uncomfortable with the fact we don't now why :-/

I guess you've already checked similar logs (`PYTEST_DEBUG = 1`) but I've recreated a branch to have more infos on the failure: https://travis-ci.org/pypa/pip/jobs/146602684

**Comment by nicoddemus** [comment]
@xavfernandez agreed, @RonnyPfannschmidt has hunch that the problem might be regarding how options (specially `basetemp`) is forwarded and handled at the slaves, see #1743.

**Comment by RonnyPfannschmidt** [comment]
@xavfernandez did some tests showing that my hunch was wrong

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt I was thinking, while #1743 makes sense, that wouldn't explain why their old `tmpdir` implementation did not work, after all it was correctly using `config._tmpdir_factory` (see my PR), which is also used by pytest's own `tmpdir`.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus yes, ever since @xavfernandez demonstrated that the issue is in fact not related to that, i do wonder what is the actual cause
