### ISSUE TITLE
Pytest Recursive Logging Redirection within Airflow Task

### ISSUE THREAD

**Issue by JonnyWaffles** [pytest-dev/pytest#10833]
Hi team, I am trying to run Pytest inside of an Airflow task. Doing so causes a recursive logging scenario. As I understand it based on https://github.com/apache/airflow/discussions/30107#discussioncomment-5314709, Airflow tasks redirects logs back to stdout and then Pytest redirects the same, thus causing the recursion. I searched your documentation and tried all the various log capture parameters (`-s`, `--capture=fs`, etc), but nothing seems to do the trick. Apologies for the misunderstanding, but is there a way I can tell Pytest not to perform whichever redirection is causing the behavior described in the Airflow comment?

**Comment by RonnyPfannschmidt** [comment]
A proper integration seems to be necessary

Im under the impression that both stdio capture and log capture have to be disable in airflow

**Comment by Zac-HD** [comment]
`pytest -p no:logging` to disable pytest's logging plugin entirely?
