### ISSUE TITLE
Remove double <system-out> in junit.xml

### ISSUE THREAD

**Issue by kasprka** [pytest-dev/pytest#10841]
When a test is skipped in the testexectuion the <system-out> entry in the junit.xml is created. If afterwards the teardown fails another <system-out> entry is created. This duplicate will lead to an error in the gitlab ci junit parser, so the overview of tests can't be created in gitlab. The error will read: "JUnit data parsing failed: undefined method `match' for #<Array:0x00007f08b9ed2650>"

My solution would be to have only one <system-out> entry in the junit.xml. I suggest to check if an <system-out> exists. If not create a new entry. If it exists just append the text to the existing entry. That way we still would have the content of both but in one <system-out> entry. I implemented it locally and will create a pull request for this solution.

An other option might be, to rename tags. Something like: <system-out-skip>, <system-out-teardown>.

**Comment by nicoddemus** [comment]
Thanks for the issue and PR!

But as I commented in https://github.com/pytest-dev/pytest/pull/10842#pullrequestreview-1370936731, it seems pytest is doing the right thing according to the specification, so we should not try to change pytest here as this will have the side-effect of losing the information that more than one system-out/system-err event ocurred.
