### ISSUE TITLE
Add a way to temporarily import modules, or clean up stale imports

### ISSUE THREAD

**Issue by Kodiologist** [pytest-dev/pytest#10854]
#### What's the problem this feature will solve?
Consider a file like

```python
def f(monkeypatch, tmp_path, n):
    (tmp_path / 'foo.py').write_text(f'value = {n}')
    monkeypatch.syspath_prepend(tmp_path)
    import foo
    assert foo.value == n

def test1(monkeypatch, tmp_path):
    f(monkeypatch, tmp_path, 1)

def test2(monkeypatch, tmp_path):
    f(monkeypatch, tmp_path, 2)
```

`test2` fails (`AssertionError: assert 1 == 2`) because `import foo` gets the old module object, without checking the new `foo.py`.

#### Describe the solution you'd like
Ideally pytest would do some kind of automatic cleanup between tests to ensure that `import` in the test function has no lasting effects. Failing that, perhaps it could allow something like `foo = monkeypatch.temp_import("foo")` to queue `foo` for cleanup when the function ends.

#### Alternative Solutions
My workaround is to manually reload the module, as by adding `import importlib; importlib.reload(foo)` after `import foo` to the above.

**Comment by RonnyPfannschmidt** [comment]
Reload /sys.module cleanup is not safe in the general case

Currently I'm not aware of anyone working on a reasonably safe spin on that, so it's unlikely to happen soon

**Comment by Kodiologist** [comment]
Is there a smarter thing for the user to do in this case than to reload manually?

**Comment by RonnyPfannschmidt** [comment]
Creating a own importlib loader that keeps stuff away from sys. Modules may be a potential solution

Currently I'm not fluent with the finer details, so take with a grain of salt

**Comment by Zac-HD** [comment]
> Ideally pytest would do some kind of automatic cleanup between tests to ensure that import in the test function has no lasting effects. Failing that, perhaps it could allow something like foo = monkeypatch.temp_import("foo") to queue foo for cleanup when the function ends.

Unfortunately imports can do basically _anything_ in the general case, so there's no way for us to provide such functionality.  (the closest I get in my own projects is to have the test run all checks in a subprocess)

**Comment by Kodiologist** [comment]
I guess you're right. Thanks for explaining.

**Comment by nicoddemus** [comment]
> the closest I get in my own projects is to have the test run all checks in a subprocess

I think this is the best advice we can give. Perhaps we could add a section to the docs with this guidance, and explain the reasoning?
