### ISSUE TITLE
pytest raises an invalid UnicodeEncodeError in Python 2.7

### ISSUE THREAD

**Issue by Themanwithoutaplan** [pytest-dev/pytest#1085]
This looks like it has just crept into pytest 2.8.1.

I have a parametrised test where I'm passing in unicode, decoded from bytes. Pytest fails to even collect the test. This didn't used to happen (env's with 2.7.2 are running fine) and I'm pretty sure the code is legitimate across Python 2/3

```
class TestASCII:

    def test_valid(self, ascii):
        ascii.value = b'some text'
        assert ascii.value == b'some text'

    value = b'\xc3\xbc'.decode("utf-8")
    @pytest.mark.parametrize("value",
                             [
                                 value,
                                 10,
                                 []
                             ]
                             )
    def test_invalid(self, ascii, value):
        with pytest.raises(TypeError):
            ascii.value = value
```

**Comment by nicoddemus** [comment]
Thanks for the report! I will take a look as soon as possible, it is clearly related to the fix done for  #1030.

**Comment by nicoddemus** [comment]
@sloria and @Themanwithoutaplan, could you please verify if the branch #1092 solves this problem in your test suites? Thanks!

You can install it directly into your environment:

```
pip install git+https://github.com/nicoddemus/pytest@param-ids-fix
```

**Comment by sloria** [comment]
Confirmed--that branch fixes the problem on my test suite. Thanks for the quick response!

**Comment by Themanwithoutaplan** [comment]
Not sure how to run tox against this branch,

**Comment by RonnyPfannschmidt** [comment]
@Themanwithoutaplan you can probably just copy the git url @nicoddemus posted into the deps section

**Comment by Themanwithoutaplan** [comment]
What deps section? I don't see one in the PR.

**Comment by The-Compiler** [comment]
@Themanwithoutaplan the deps section in your project's `tox.ini` - you should be able to simply replace `pytest` with `git+https://github.com/nicoddemus/pytest@param-ids-fix` there.

**Comment by Themanwithoutaplan** [comment]
@The-Compiler thanks. Tests no longer fail with that.

**Comment by jodal** [comment]
The #1030 change in 2.8.1 broke my test suite too. The branch linked here solves the problem. Hoping for a quick 2.8.2 release.
