### ISSUE TITLE
`tmpdir` creates subfolders at `basetemp` instead of `shutil.rmtree(basetemp)`

### ISSUE THREAD

**Issue by danieloliveira56** [pytest-dev/pytest#10850]
#### What's the problem this feature will solve?
I almost deleted my entire $HOME folder trying to test the tmpdir fixture with --basetemp=$HOME.

While the warning in the documentation is helpful, it's pretty easy to make this mistake.

#### Describe the solution you'd like

I think it makes sense for the --basetemp folder to work like `rootdir` in the `getbasetemp` function. So instead of returning `basetemp`, return a subfolder `basetemp / "pytest-x"`: 
```python
return make_numbered_dir_with_cleanup(
        prefix="pytest-",
        root=basetemp,
        keep=keep,
        lock_timeout=LOCK_TIMEOUT,
        mode=0o700,
    )
```

**Comment by RonnyPfannschmidt** [comment]
Basetemp will be deprecated, different options will provide the proposed behaviour
