### ISSUE TITLE
`pytest.warns` hides type errors in `warnings.warn` calls

### ISSUE THREAD

**Issue by zanieb** [pytest-dev/pytest#10865]
- [x] a detailed description of the bug or problem you are having
- ~[ ] output of `pip list` from the virtual environment you are using~
- [x] pytest and operating system versions
- [x] minimal example if possible

When using `pytest.warns`, incorrect values sent to `warnings.warn` are not reported obscuring bugs:

```python
import pytest
import warnings


def test_example_one():
    with pytest.warns(UserWarning):
        warnings.warn(1)

    # This test passes but should raise a `TypeError` as demonstrated in `example_two`


def test_example_two():
    with pytest.raises(TypeError):
        warnings.warn(1)
```

```
macOS 13.2.1
pytest 7.2.2
python 3.11
```

Related to https://github.com/pytest-dev/pytest/issues/9288

**Comment by nicoddemus** [comment]
Hmm that's unfortunate, thanks for the report!

Should be simple to fix.

**Comment by madkinsz** [comment]
You're welcome! Certainly confused me for a minute :)

I'm happy to contribute a fix — want to just raise a type error if it's not a string?

**Comment by madkinsz** [comment]
Weirdly this is fine

```
❯ python -c "import warnings; warnings.warn(1)"
<string>:1: UserWarning: 1
```

but the `TypeError` is definitely raised in pytest i.e. if I remove the `pytest.raises`:

```
    def test_example_two():
>       warnings.warn(1)
E       TypeError: expected string or bytes-like object, got 'int'
```

I feel like this caused me an error outside of pytest as well though

**Comment by nicoddemus** [comment]
Are you sure? This works for me:

```python
import warnings
def test_example_two():
    warnings.warn(1)
```

Which Python and pytest versions are you using?

**Comment by madkinsz** [comment]
The Python and pytest versions are included in the original post, but consider me very confused — I did not reproduce this with the minimal example and a test matrix at https://github.com/madkinsz/pytest-10865/actions/runs/4714285419/jobs/8360551859

It does however reproduce quite clearly when I'm working in `PrefectHQ/prefect`. Here's the example running in our test suite https://github.com/PrefectHQ/prefect/pull/9231

**Comment by madkinsz** [comment]
The issue appears to be related to `filterwarnings`, for example:

```python
import warnings

# Does not raise a type error
warnings.warn(1)

# Raises a type error
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", "test")
    warnings.warn(1)
```

with the addition of a warnings filter to pytest https://github.com/madkinsz/pytest-10865/commit/1c3e4e37aa1fb7453bfe80946b50f391dd51d32a the type error is raised on all Python and 7.x pytest versions https://github.com/madkinsz/pytest-10865/actions/runs/4714336351

**Comment by madkinsz** [comment]
I've opened a CPython issue as this doesn't really seem like pytest's fault https://github.com/python/cpython/issues/103577

**Comment by zanieb** [comment]
@nicoddemus I don't expect there to be changes upstream for this. Should we validate that argument is of the correct type in pytest?

**Comment by RonnyPfannschmidt** [comment]
as far as im concerned, type metadata in typeshed is provided, and my understandig is, that it would point to the error

**Comment by zanieb** [comment]
@RonnyPfannschmidt the problem here is that when using `filterwarnings` the `TypeError` is raised outside of pytest but not raised inside `pytest.warns` blocks. This means that an error that can occur at runtime for users is hidden during execution of the test suite. I agree that this mistake would also be caught by a type-checker, but many people do not use static analysis tools and it feels rough to obscure the error that the standard library would raise.

**Comment by Zac-HD** [comment]
Retagging as bug based on upstream discussion, where consensus looks like "this should always error" and CPython may change accordingly.

**Comment by whysage** [comment]
HI, please review
https://github.com/pytest-dev/pytest/pull/11804

**Comment by whysage** [comment]
Hi, any comments on pull request?
https://github.com/pytest-dev/pytest/pull/11804
@zanieb @Zac-HD
