### ISSUE TITLE
pytest in mingw64 cannot parse path to individual test

### ISSUE THREAD

**Issue by rodprice** [pytest-dev/pytest#10867]
I'm running msys2 on Windows 10. I've put a test file test-windows.py in directory tests,

```python
def func(x):
    return x + 1
def test1():
    assert func(3) == 5
def test2():
    assert func(3) == 4
```
When I start up the shell Mingw64 provided by msys2 and attempt to use pytest to run an individual test, i.e.
```
pytest test-windows.py::test2
```
I get a successful test, as expected,
```
======================================= test session starts =======================================
platform win32 -- Python 3.9.16, pytest-7.1.2, pluggy-1.0.0
rootdir: C:\Users\rdprice\Apps\msys64\home\rdprice\working\tmp\tests
collected 1 item

test-windows.py .                                                                            [100%]

======================================== 1 passed in 0.02s ========================================
```
However, when I run pytest from one directory higher,
```
cd ..
pytest tests/test-windows.py::test2
```
I get this
```
======================================= test session starts =======================================
platform win32 -- Python 3.9.16, pytest-7.1.2, pluggy-1.0.0
rootdir: C:\Users\rdprice\Apps\msys64\home\rdprice\working\tmp
collected 0 items

====================================== no tests ran in 0.00s ======================================
ERROR: file or directory not found: tests\test-windows.py;test2
```
The double colon `::` is replaced by a single semicolon `;`, and pytest can't collect the test. Replacing the `/` with `\\` does not help. Quoting the path with `''` does not help.

**Comment by Zac-HD** [comment]
I'm not a Windows CLI wizard, but colons (`:`) are a special character and so I'd guess that quoting the test nodeid will fix your problem - even if I can't tell you why the first works but the second doesn't.
