### ISSUE TITLE
Use PyPI Trusted Publishers feature to publish releases

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#10870]
https://docs.pypi.org/trusted-publishers/

This is currently still in beta, and I don't think pytest should be a beta tester, but opening this issue for discussion ahead of time.

Seems like a good improvement over the API token method we currently use.

**Comment by RonnyPfannschmidt** [comment]
I'll play early adoption in setuptools_scm and execnet, then we can transfer to pytest*

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus @bluetech i just made a test mr to setuptools_scm testing it, it works fabulous and is absolutely easy

i'll add some extras for setuptools_scm so that we can have test-pypi uploads and then propose the change to pytest either this or next week

**Comment by bluetech** [comment]
@RonnyPfannschmidt nice!
