### ISSUE TITLE
Without using any plugins, running pytest with multiple threads will result in the KeyError: 'PYTEST_CURRENT_TEST' error.

### ISSUE THREAD

**Issue by Jermin2020** [pytest-dev/pytest#10876]
Package               Version 
--------------------- ----------- 
APScheduler           3.10.1      
backports.zoneinfo    0.2.1       
certifi               2019.11.28
chardet               3.0.4
cloudpickle           2.2.1
colorama              0.4.6
Django                2.2.3
django-cors-headers   3.1.1
django-filter         2.2.0
django-shortuuidfield 0.1.3
djangorestframework   3.10.1
gym                   0.26.2
gym-notices           0.0.8
idna                  2.8
importlib-metadata    6.0.0
mysqlclient           1.4.6
numpy                 1.21.6
pip                   23.0.1
pycryptodomex         3.7.2
pyglet                1.5.21
Pygments              2.4.2
PyJWT                 1.7.1
PyMySQL               0.9.3
python-alipay-sdk     1.10.1
python-memcached      1.59
pytz                  2019.1 
pytz-deprecation-shim 0.1.0.post0
requests              2.22.0
setuptools            67.6.0
shortuuid             0.5.0
six                   1.12.0
sqlparse              0.3.0
tqdm                  4.65.0
typing_extensions     4.5.0
tzdata                2022.7
tzlocal               4.2
urllib3               1.25.7
wheel                 0.38.4
zipp                  3.15.0

pytest 7.2.0

Without using any plugins, running pytest with multiple threads will result in the KeyError: 'PYTEST_CURRENT_TEST' error.

**Comment by RonnyPfannschmidt** [comment]
Pytest is not threadsafe

**Comment by Jermin2020** [comment]
> Pytest is not threadsafe
Thanks, is there a good way to filter out this error?

**Comment by RonnyPfannschmidt** [comment]
errors cannot be filtered

**Comment by goencoder** [comment]
@Jermin2020 
As a best effort you can try to use this hack to mute this error in conftest.py
I have not seen any pytest use of this environment variable, but be aware if others do.

```
def pytest_sessionstart(session):
    """
     This hook is called once, at the beginning of the test session (once per each parallel session),
     before any tests are executed. It can be used to set up resources, initialize variables, or
     perform any actions that need to happen just once before the entire test run.
     """
    # Hack: This is a workaround to assert os env 'PYTEST_CURRENT_TEST' is always set
    # pytest teardown assume it is set, but when running in parallel mode we have multiple attempts to pop it
    if "PYTEST_CURRENT_TEST" not in os.environ:
        # set to empty string
        os.environ["PYTEST_CURRENT_TEST"] = ""


def pytest_sessionfinish(session, exitstatus):
    """
     This hook is called once, after all the tests have in a given session been executed, and just
     before the test session ends. It's useful for cleaning up resources, generating reports,
     or performing any actions needed to wrap up the entire testing process.
    """
    # Hack: This is a workaround to assert os env 'PYTEST_CURRENT_TEST' is always set
    # pytest teardown assume it is set, but when running in parallel mode we have multiple attempts to pop it
    if "PYTEST_CURRENT_TEST" not in os.environ:
        # set to empty string
        os.environ["PYTEST_CURRENT_TEST"] = ""
```

**Comment by RonnyPfannschmidt** [comment]
@goencoder please do not recommend known to be unsafe mechanisms to get something working that not supported

**Comment by goencoder** [comment]
Done @RonnyPfannschmidt Is parallel processes is a safe option (compared to parallel threads in single process)?

**Comment by RonnyPfannschmidt** [comment]
@goencoder parallel processes is what xdist implements and its the safe version
