### ISSUE TITLE
Add `addDuration` to `TestCaseFunction`

### ISSUE THREAD

**Issue by masklinn** [pytest-dev/pytest#10875]
cpython 3.12  (alpha) has added an `addDuration` API to test results (python/cpython#12271).

This would not be an issue, except it was designed to trigger a warning if the test result doesn't have such a method (hence e.g. python/cpython#103309). This means when using pytest as runner for unittest tests *and* running `-We` an error is triggered as pytest's test result (which seems to be `TestCaseFunction`) does not support this protocol.

Now obviously this should be non-blocking, as hopefully nobody is running CI which blocks on testing 3.12, but there you go, I figure an early forewarning can't hurt.

**Comment by nicoddemus** [comment]
Thanks @masklinn, appreciate the report.
