### ISSUE TITLE
FileNotFoundError: pytest-splunk-addon-data.conf not found

### ISSUE THREAD

**Issue by vivek-crest** [pytest-dev/pytest#10877]
Hi ,
I am getting the error as given below 
`NTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_splunk_addon/plugin.py", line 131, in pytest_sessionstart
INTERNALERROR>     test_generator = AppTestGenerator(session.config)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_splunk_addon/standard_lib/app_test_generator.py", line 54, in __init__
INTERNALERROR>     store_sample = sample_generator.get_samples(store_events)
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_splunk_addon/standard_lib/sample_generation/sample_xdist_generator.py", line 67, in get_samples
INTERNALERROR>     tokenized_events = list(sample_generator.get_samples())
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_splunk_addon/standard_lib/sample_generation/sample_generator.py", line 52, in get_samples
INTERNALERROR>     sample_stanzas = psa_data_parser.get_sample_stanzas()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_splunk_addon/standard_lib/sample_generation/pytest_splunk_addon_data_parser.py", line 97, in get_sample_stanzas
INTERNALERROR>     _psa_data = self._get_psa_data_stanzas()
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_splunk_addon/standard_lib/sample_generation/pytest_splunk_addon_data_parser.py", line 134, in _get_psa_data_stanzas
INTERNALERROR>     for stanza, fields in sorted(self.psa_data.items()):
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_splunk_addon/standard_lib/sample_generation/pytest_splunk_addon_data_parser.py", line 88, in psa_data
INTERNALERROR>     raise FileNotFoundError(f"{PSA_DATA_CONFIG_FILE} not found")
INTERNALERROR> FileNotFoundError: pytest-splunk-addon-data.conf not found`

Can someone please help what could be the reason?

**Comment by RonnyPfannschmidt** [comment]
This is a issue with the slunk plugin in use, please refer to their documentation /issue tracker
