### ISSUE TITLE
`pytest_report_teststatus` documentation is contradictory 

### ISSUE THREAD

**Issue by samuelcolvin** [pytest-dev/pytest#10872]
See [here](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.hookspec.pytest_report_teststatus):

<img width="882" alt="image" src="https://user-images.githubusercontent.com/4039449/230132971-7ada26ab-d813-44fa-a4b0-a2abea34c781.png">

The example return value is `"rerun", "R", ("RERUN", {"yellow": True})`, while the return type is documented as 

```py
Tuple[str, str, Union[str, Mapping[str, bool]]]
```

which don't match.

I'm assuming the return type should be

```py
Tuple[str, str, Union[str, Tuple[str, Mapping[str, bool]]]]
```

Or something?

Also some clearer documentation on how the third element of the tuple is sued would be great.

**Comment by nicoddemus** [comment]
Indeed, and the annotation in the code is correct:

https://github.com/pytest-dev/pytest/blob/31d0b51039fc295dfb14bfc5d2baddebe11bb746/src/_pytest/terminal.py#L528-L530

The return value can be, for example:

```python
("rerun", "R", "RERUN")
```

Or:

```python
("rerun", "R", ("RERUN", {"yellow": True}))
```

This signature is like that for historical reasons unfortunately, nowadays we would use probably a dataclass.

**Comment by nicoddemus** [comment]
The possible values that can be used in the mapping are not really documented I think, they are defined here:

https://github.com/pytest-dev/pytest/blob/31d0b51039fc295dfb14bfc5d2baddebe11bb746/src/_pytest/_io/terminalwriter.py#L42-L63

**Comment by samuelcolvin** [comment]
makes sense, thanks for the details.

**Comment by The-Compiler** [comment]
> This signature is like that for historical reasons unfortunately, nowadays we would use probably a dataclass.

I feel like we should do just that, and figure out a way to make it backwards compatible.

If pytest itself would be the only place invoking the hook, it'd just be a matter of an `isinstance` - if we want to keep compatibility with [some 15-20 projects](https://sourcegraph.com/search?q=context:global+.pytest_report_teststatus+lang:python+-file:_%3Fpytest/+-file:/site-packages/+-repo:%5Egithub%5C.com/pytest-dev/pytest%24+-repo:%5Egithub%5C.com/cndn/intelligent-code-completion%24+-repo:%5Egithub%5C.com/qifanyyy/JupyterNotebook%24+&patternType=standard&sm=1&groupBy=repo) invoking the hook themselves, returning an object with a `__getitem__` and `__iter__` implemented (perhaps emitting a `DeprecationWarning`) would probably work smoothly.

**Comment by nicoddemus** [comment]
Perhaps a named tuple would work too?

**Comment by RonnyPfannschmidt** [comment]
I wonder if we could try to mirror rich styled spans and supply easy conversation

This is one of the rarely used apis that tie us into the legacy terminalwriter apis
