### ISSUE TITLE
pytest fails when it uses all cores of m2 macbook pro

### ISSUE THREAD

**Issue by shjeong92** [pytest-dev/pytest#10892]
When I try to run test using all cores it failed with lots of errors [django.db.utils.OperationalError: out of shared memory] 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/75003424/231053897-eda067b0-81e4-4df0-a5ad-24be4215b1b2.png">

it pass all the tests when I use 11 cores
`pytest -n 11`
<img width="671" alt="image" src="https://user-images.githubusercontent.com/75003424/231053918-3a556420-c55a-49c6-85f6-d9bd8821e643.png">

I am not sure it's either `macbook` issue or `xdist` or `pytest`

**Comment by The-Compiler** [comment]
This is probably an issue with your application/config and not with pytest - the same thing would happen with as many cores outside of pytest too.

Please show the full error output you get for a failing test.

**Comment by dev-artisan** [comment]
I had the same problem, and I was misled to think that it was a pytest problem, in fact it's a postgreSQL problem.

I was using a dockerized postgres container and needed to change the config.
Create a file called `my-postgres.conf` and put it somewhere in your project files and below is a sample config that I used to get it working:
```
listen_addresses='0.0.0.0'
port='5432'
max_connections=200
max_locks_per_transaction=256
shared_buffers='256MB'
work_mem='2MB'
maintenance_work_mem='32MB'
effective_cache_size='256MB'
client_encoding='UTF8'
timezone='UTC'
```
The key config here is `max_locks_per_transaction=256` which will allow the db to handle the load that pytest is throwing at it, you may need to increase yours if need be.  You can also play around with `max_connections`.

My docker-compose for the db looks like this:
```docker
services:
  db:
    image: postgres:18-alpine
    container_name: postgres-db
    restart: unless-stopped
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db-config/my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./docker/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
```
It's essential to have the below in the docker compose for this to work:
1. `- ./docker/db-config/my-postgres.conf:/etc/postgresql/postgresql.conf` which will copy your config over to the container
2. `command: postgres -c config_file=/etc/postgresql/postgresql.conf` which will run the container with your custom config


Hope this helps anyone else who finds this and has the same issue

**Comment by RonnyPfannschmidt** [comment]
@dev-artisan thank you for providing a detailed and comprehensible description and solution of/for the problem
