### ISSUE TITLE
More verbose test name parametrization

### ISSUE THREAD

**Issue by HexHummingbird** [pytest-dev/pytest#10909]
Hello.

#### What's the problem this feature will solve?
In a big project especially with CI/CD it is important to quickly pin-point failed tests and, at a glance, see which tests failed and with which parameters. With an option to display not only parametrized values, but also their **names** in generated test function names it would be much easier to understand code flow, which test failed and even why.

#### Describe the solution you'd like
Suppose we have following code:
```python
import pytest

@pytest.mark.parametrize(
  ('is_compatibility_mode'), (True, False)
)
@pytest.mark.parametrize(
  ('some_value', 'important_name', 'is_ready'),
  (
      [30, 5, False],
      [100, 101, True],
      [500, 90, True],
  )
)
def test_case(is_compatibility_mode, some_value, important_name, is_ready):
  # some logic
  assert False

```
If we run it with pytest, we will get this:
```
============================================================= short test summary info ============================================================= 
FAILED example.py::test_case[30-5-False-True] - assert False
FAILED example.py::test_case[30-5-False-False] - assert False
FAILED example.py::test_case[100-101-True-True] - assert False
FAILED example.py::test_case[100-101-True-False] - assert False
FAILED example.py::test_case[500-90-True-True] - assert False
FAILED example.py::test_case[500-90-True-False] - assert False
================================================================ 6 failed in 0.12s ================================================================
```
Short, but quite obscure in some context: What are these boolean values? What is their order? What are these two numbers?
What I'd like to see is something like this:
```
============================================================= short test summary info ============================================================= 
FAILED example.py::test_case[some_value=30-important_name=5-is_ready=False-is_compatibility_mode=True] - assert False
FAILED example.py::test_case[some_value=30-important_name=5-is_ready=False-is_compatibility_mode=False] - assert False
FAILED example.py::test_case[some_value=100-important_name=101-is_ready=True-is_compatibility_mode=True] - assert False
FAILED example.py::test_case[some_value=100-important_name=101-is_ready=True-is_compatibility_mode=False] - assert False
FAILED example.py::test_case[some_value=500-important_name=90-is_ready=True-is_compatibility_mode=True] - assert False
FAILED example.py::test_case[some_value=500-important_name=90-is_ready=True-is_compatibility_mode=False] - assert False
================================================================ 6 failed in 0.12s ================================================================
```
In some situations longer names are **much** better than no names at all. Also, it gives you a lot more context to work with.

#### Alternative Solutions
I know we can use ids to generate names for individual functions, however here I'm looking for an approach that is independent of parameters names. Writing custom name generator for every test is lots of code and it is very inconvenient.

**Comment by Zac-HD** [comment]
Try using [`pytest.param(*args, id="meaningful-label")` with an id](https://docs.pytest.org/en/stable/reference/reference.html#pytest-param) as the elements you pass to parametrize 🙂
