### ISSUE TITLE
How to ensure that teardown_class will be executed at any time ?

### ISSUE THREAD

**Issue by zccyman** [pytest-dev/pytest#10929]
When the last test case is skipped, teardown_class will not be executed; when one or more of several test cases are tested, teardown_class must be executed !!!

**Comment by RonnyPfannschmidt** [comment]
More context required to determine the details

**Comment by zccyman** [comment]
@RonnyPfannschmidt It's a bug in my code. The above problem does not exist! My test code is as follows:

`
import pytest

@pytest.fixture(scope="class", params=[1, 2])
def a(request):
    return request.param

@pytest.fixture(scope="class", params=[1, 2])
def b(request):
    return request.param


class TestLayers(): # type: ignore
    def setup_class(self):
        print("setup_class")
        self.c = -1
        self.input_settings = "setup_class"
        
    def test_layer(self, a, b):
        self.__class__.c = a + b
        self.__class__.input_settings = "test_layer"
        if a==2 and b==1:
            pytest.skip("test_layer") 
            
    def teardown_class(self):
        print("teardown_class")
        
        
if __name__ == "__main__":
    pytest.main(["test.py::TestLayers::test_layer"])
`
