### ISSUE TITLE
Please make _pytest.outcomes.Skipped part of the public API

### ISSUE THREAD

**Issue by dagardner-nv** [pytest-dev/pytest#10946]
#### What's the problem this feature will solve?
I would like to be able to skip some testes on a missing dependency locally (via `pytest.importorskip`), however in CI I want don't want the test to skip, and instead would like to report it as a failure.

#### Describe the solution you'd like
If `_pytest.outcomes.Skipped` were part of the public API then I could wrap `pytest.importorskip` with:
```py
def import_or_skip(modname: str,
                   minversion: str = None,
                   reason: str = None,
                   fail_missing: bool = False) -> types.ModuleType:
    """
    Wrapper for `pytest.importorskip` will re-raise any `Skipped` exceptions as `ImportError` if `fail_missing` is True.
    """
    try:
        return pytest.importorskip(modname, minversion=minversion, reason=reason)
    except Skipped as e:
        if fail_missing:
            raise ImportError(e)
        raise
```

I know there's nothing stopping me from importing `_pytest.outcomes.Skipped` today except the concern that it may break my code in the future.

#### Alternative Solutions
Alternately `pytest.importorskip` could accept a `fail_missing` flag, which would be even better.

**Comment by RonnyPfannschmidt** [comment]
It's exposed as pytest.skip.Exception

**Comment by dagardner-nv** [comment]
@RonnyPfannschmidt Thanks! this works for me.
