### ISSUE TITLE
Issue around usage of raises as context manager

### ISSUE THREAD

**Issue by demianbrecht** [pytest-dev/pytest#1097]
For those who are well versed in context managers, the usage is fairly obvious. However, for those not so well versed, the behavior in the following cases may be unexpected:

Expected:

    with pytest.raises(ValueError):
        assert 1 == 0  # this will fail
        raise ValueError

Unexpected:

    with pytest.raises(ValueError):
        raise ValueError
        assert 1 == 0  # this will never be executed

The best fix for this is likely to beef up the documentation a bit, calling out that anything within the context manager block should only be relevant to the expected exception and that there should be no code after the exception is raised.

There may be other ways to deal with this (i.e. reverting the exception and resuming execution), but I was told I was "batshit crazy" on IRC ;) Also, portability across implementations and versions would be a nightmare as I'm sure that even /if/ there's a method to support this, it would likely be implementation-specific.

**Comment by RonnyPfannschmidt** [comment]
Reverting exceptions is something only common lisp can do 
We certainly won't try to support it

It's not clear how to advance the docs, up for a PR?

**Comment by demianbrecht** [comment]
Absolutely. Just have to get legal approval from work first, so might be at least a week or two before I get to it.

(And yeah, I'd venture to say that not trying to support the alternate suggestion is the Right Thing to do ;))

**Comment by demianbrecht** [comment]
Approval came quicker than anticipated, hope the addition makes sense to you.

**Comment by RonnyPfannschmidt** [comment]
@demianbrecht that was good work :)
