### ISSUE TITLE
Exception while using module scoped fixture (ok in 2.7.3 and broken in 2.8.x)

### ISSUE THREAD

**Issue by skirpichev** [pytest-dev/pytest#1100]
Now with my old [conftest.py](https://github.com/skirpichev/omg/blob/travis-no-split/sympy/conftest.py) doesn't work.  I see such tracebacks (looks similar to #943):
```
________________________________________________________________________ ERROR collecting sympy/abc.py _________________________________________________________________________
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/runner.py:149: in __init__
    self.result = func()
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/main.py:437: in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/main.py:317: in _memoizedcall
    res = function()
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/main.py:437: in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/doctest.py:165: in collect
    fixture_request = _setup_fixtures(self)
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/doctest.py:190: in _setup_fixtures
    fixture_request._fillfixtures()
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/python.py:1514: in _fillfixtures
    item.funcargs[argname] = self.getfuncargvalue(argname)
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/python.py:1557: in getfuncargvalue
    return self._get_active_fixturedef(argname).cached_result[0]
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/python.py:1574: in _get_active_fixturedef
    result = self._getfuncargvalue(fixturedef)
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/python.py:1624: in _getfuncargvalue
    subrequest.node)
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/python.py:1412: in node
    return self._getscopeitem(self.scope)
../../.virtualenvs/pytest-new/local/lib/python2.7/site-packages/_pytest/python.py:1658: in _getscopeitem
    assert node
E   assert None
```
Removing module-scoped fixtures obviously "helps".

Build logs from Travis: [good](https://travis-ci.org/skirpichev/omg/jobs/79522689) and [bad](https://travis-ci.org/skirpichev/omg/jobs/83139232).

**Comment by nicoddemus** [comment]
Hi @skirpichev, thanks for the report!

In case others want to take a stab at this, here's a reproducible example:

**conftest.py**
```python
import pytest

@pytest.fixture(autouse=True, scope='module')
def check_disabled(request):
    assert request.module is not None
```

**test_bug.py**
```python
def test_foo():
    """
    >>> 1 + 2
    3
    """
    pass    
```

Execute with:

```
py.test --doctest-modules
```

* Moving fixture to `test_bug.py` no longer causes the error;
* `py.test` without `--doctest-modules` also doesn't cause the error;

**Comment by nicoddemus** [comment]
Hmmm I found a fix, but then ran into #1057 when trying to execute your test suite with my fix in place. I will need a little more time to fix this and #1057 as well.

**Comment by skirpichev** [comment]
BTW, this looks like a regression.  Can you include fix in the next stable point release (of course, if the fix will be available)?

**Comment by The-Compiler** [comment]
I'll probably be the one releasing 2.8.2 at the beginning of next week - so if it's in until then, sure!

**Comment by nicoddemus** [comment]
Hi @skirpichev, I just opened a PR which fix this. Could you please confirm that it fixes your test suite?

```
pip install git+https://github.com/nicoddemus/pytest@doctest-fixtures-fix
```

**Comment by skirpichev** [comment]
On Sat, Oct 03, 2015 at 12:12:46PM -0700, Bruno Oliveira wrote:
>    Hi [1]@skirpichev, I just opened a PR which fix this. Could you please
>    confirm that it fixes your test suite?
> 
>  pip install git+https://github.com/nicoddemus/pytest@doctest-fixtures-fix

Yep.  Good logs from Travis:
https://travis-ci.org/skirpichev/omg/builds/83483278

Thank you for fix.
