### ISSUE TITLE
pytest collects files when told not to

### ISSUE THREAD

**Issue by CobaltCause** [pytest-dev/pytest#11006]
I can reproduce this with a project set up as follows:

*  `pyproject.toml`:

   ```toml
   [tool.pytest.ini_options]
   python_files = "*.py"
   testpaths = [
       "tests",
   ]
   ```

*  `src/playground/__init__.py` exists and is empty

*  `src/playground/__main__.py`:

   ```python
   import sys


   def main():
       print("Hello, world!")


   sys.exit(main())
   ```

*  `tests` does not exist

When I run `pytest`, I get this output:

```
============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/charles/science/python/playground, configfile: pyproject.toml
plugins: cov-4.0.0
collected 0 items / 1 error

==================================== ERRORS ====================================
_________________ ERROR collecting src/playground/__main__.py __________________
src/playground/__main__.py:11: in <module>
    sys.exit(main())
E   SystemExit
------------------------------- Captured stdout --------------------------------
Hello, world!
=========================== short test summary info ============================
ERROR src/playground/__main__.py - SystemExit
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.03s ===============================
```

I would expect this to succesfully collect nothing and run no tests, but instead it fails because it runs `__main__.py`. Notably, if I remove `python_files = "*.py"` from `pyproject.toml`, it works. It seems like this shouldn't matter, though, because I'm already narrowing `testpaths` to `tests`.

**Comment by nicoddemus** [comment]
Hi @CobaltCause,

This is not really a bug, but an intended (albeit questionable) behavior: 

The values of `testpaths` are actually globs, so globbing for `tests` in the root yields nothing. Given it finds nothing, pytest will behave as if called from the command-line without any parameters, which makes it search recursively from the current directory looking for `python_files` to collect.

https://github.com/pytest-dev/pytest/blob/739408b958f8e5a24de81e17e4cc2d4f34d93991/src/_pytest/config/__init__.py#L1382-L1384

If you create the `tests` directory, then pytest will correctly search in that directory only.

I agree this is very surprising.

Perhaps we should emit a warning if `testpaths` is defined but does not match anything?

**Comment by CobaltCause** [comment]
Oh, interesting. Yeah, this is quite surprising behavior. Making a `tests` directory, even if empty, does make it work the way I wanted. Either a warning or an error and refusal to continue would have really helped me here, yeah. Thanks for the explanation!
