### ISSUE TITLE
@hookspec breaks Sphinx parsing

### ISSUE THREAD

**Issue by ikonst** [pytest-dev/pytest#11012]
In [pytest_ignore_collect docs](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.hookspec.pytest_ignore_collect), the `:param`s are not parsed correctly.

The only difference appears to be the explicit `@hookspec` so I'm suspecting it the culprit.

**Comment by RonnyPfannschmidt** [comment]
it seems to be a restructuredtext mistake, as some of them are parsed correctly

the difference is a space in the first one that trips it up

**Comment by ikonst** [comment]
Thanks!

p.s. tested with sphinx 7, it appears that rST parsing is lax in that `:param foo :` renders as plain text and I couldn't find a way to configure it to parse stricter
