### ISSUE TITLE
Third-Party Plugins 

### ISSUE THREAD

**Issue by mgaldzic** [pytest-dev/pytest#1105]
plugin status links broken. For example, I was looking for pytest-ipynb as I am having no luck getting it to recongize notebooks. 
http://pytest.org/latest/plugins_index/index.html

![image](https://cloud.githubusercontent.com/assets/406285/10255003/25272dda-68fc-11e5-9d4b-d9a10bdde0f4.png)

**Comment by nicoddemus** [comment]
Thanks for the report @mgaldzic!
