### ISSUE TITLE
Update example in "The new config.cache object"

### ISSUE THREAD

**Issue by CarstenGrohmann** [pytest-dev/pytest#11065]
Hi pytest developers,

in the API documentation for [config.cache](https://docs.pytest.org/en/latest/reference/reference.html#config-cache) you wrote that the access should be done with the `pytestconfig` fixture. But in the example in [The new config.cache object](https://docs.pytest.org/en/latest/how-to/cache.html#the-new-config-cache-object) you use the `request` fixture.

Please consider updating the example to be consistent with the API documentation.

Thank you,
Carsten

**Comment by The-Compiler** [comment]
`pytestconfig` and `request.config` both result in the same thing. But I agree it'd make sense to be consistent there - do you want to open a pull request?
