### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Maximus904** [pytest-dev/pytest#11098]
WPS Office-Word,Doc,PDF,Note,Slide&Sheet
Персональная версия совместима с несколькими форматами документов небольшого размера и является бесплатной. Получите ее здесь:
https://www.wps.com/download/?from=AndroidCenterShare&is_from=android

**Comment by The-Compiler** [comment]
Given this is the second time @Maximus904 posts nonsense (#11062) and now spam, I'm blocking them from pytest-dev and reporting them to GitHub.
