### ISSUE TITLE
Clarify rootdir relative nodeid vs cwd relative collection argument 

### ISSUE THREAD

**Issue by jitseniesen** [pytest-dev/pytest#11107]
Preface: I am filing this issue as a bug report but it may well be a misunderstanding on my part. I tried searching through the issue reports but I may not have used the correct search terms so apologies if this has already been discussed.

Summary: It is not clear whether a nodeid is relative to the current working directory or to the root dir.

Example: Consider the following directory structure.
```
pytest.ini
ham
 `--- tests
       `--- test_spam.py
```
The file `pytest.ini` is empty; it is only there to specify the rootdir. The file `ham/tests/test_spam.py` contains:
```
def test_eggs():
    pass

def test_cheese():
    pass
```
When running `pytest -v` in the directory `ham/tests`, I obtain the following output:
```
=============================== test session starts ===============================
platform linux -- Python 3.10.9, pytest-7.3.2, pluggy-1.0.0 -- /home/jitse/mambaforge/envs/spytest/bin/python3.10
cachedir: .pytest_cache
rootdir: /home/jitse/tmp/pytestex
configfile: pytest.ini
collected 2 items                                                                 

test_spam.py::test_eggs PASSED                                              [ 50%]
test_spam.py::test_cheese PASSED                                            [100%]

================================ 2 passed in 0.00s ================================
```
This suggests that the nodeid of the first test is `test_spam.py::test_eggs`. According to your doc page [Usage and Invocations](https://docs.pytest.org/en/6.2.x/usage.html), we can specify the nodeid to run a specific test, and indeed if we run `pytest test_spam.py::test_eggs` in the directory `ham/tests`, only the first test is run. This all suggests that nodeid is relative to the current working directory.

On the other hand, your doc page [Configuration](https://docs.pytest.org/en/latest/reference/customize.html#initialization-determining-rootdir-and-configfile) says "each test is assigned a unique nodeid which is rooted at the rootdir". If we add a file `conftest.py` containing:
```
def pytest_itemcollected(item):
    print(f'pytest_itemcollected: {item.nodeid=}')
```
and then run `pytest` in the `ham/tests` directory, we get the following output:
```
=============================== test session starts ===============================
platform linux -- Python 3.10.9, pytest-7.3.2, pluggy-1.0.0
rootdir: /home/jitse/tmp/pytestex
configfile: pytest.ini
collecting ... pytest_itemcollected: item.nodeid='ham/tests/test_spam.py::test_eggs'
pytest_itemcollected: item.nodeid='ham/tests/test_spam.py::test_cheese'
collected 2 items                                                                 

test_spam.py ..                                                             [100%]

================================ 2 passed in 0.00s ================================
```
Note that the nodeid reported by the hook are relative to the rootdir, not the current working directory.

**Comment by RonnyPfannschmidt** [comment]
Node ids are relative to the root dir

**Comment by RonnyPfannschmidt** [comment]
Thats indeed the case and ought to be clarified, thanks for pointing it out

**Comment by udaymankena** [comment]
Hi, sorry didn't notice a PR was up for this, was meaning to make this my first contribution.
@bluetech I made changes to the effect that tests can't be run by node id, but only by passing the module path relative to working directory. Please let me know if I understood it wrong, I can close my PR.
