### ISSUE TITLE
7.4 and 8.0 release planning

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#11126]
I have some pending breaking changes to pytest, that can't really go through a deprecation cycle. Things like:

- Changing collection of `__init__.py` to collect just the module, not the entire package (#11042)
- Changing `Package` to not be a `Module` (https://github.com/pytest-dev/pytest/issues/7777#issuecomment-1575652688)
- Adding the `Directory`/`Dir` nodes (https://github.com/pytest-dev/pytest/issues/7777#issuecomment-1555963294)

I'd like to include these changes in the next major release, 8.0.

But before that, I suggest we release 7.4 with what we have already.

I can manage these releases.

Proposal:
- [x] Release 7.4 this weekend
- [x] Change main to be 8.*
- [x] Work on the planned features until they're done (1-2 months hopefully)
- [x] Branch 8.0.x, release 8.0.0-rc1
- [x] Wait ~1 month for testing/feedback
- Release 8.0.0

**Comment by RonnyPfannschmidt** [comment]
I like this plan

Unfortunately I'm not sure if i can manage to land the introduction of function definition and item definition within the intended time frame

**Comment by nicoddemus** [comment]
Sounds great @bluetech.

You think it is worthwhile backporting #11125 and release `7.3.3`?

**Comment by akhilramkee** [comment]
Hi Team, (@nicoddemus / @RonnyPfannschmidt / @bluetech )

I am writing to inquire about the timeline for the minor releases of pytest 7.4.
Our team uses pytest to test our codebase and we are waiting on the bug-fixes for `importlib` mainly a4d7254d18a201016b97ce6a6e3f41a124e7e84c and c71b5df7347a84ef270888c8b93f5c8853ff76f0.

Can you please let us know when these bug-fixes will be released?

**Comment by nicoddemus** [comment]
Hi @akhilramkee thanks for the ping.

I can take of this release; I want to also improve the deploy procedure to use the manual deploy mechanism we have used in `pytest-mock` and `pytest-xdist`, if that's alright with you @RonnyPfannschmidt and @bluetech.

**Comment by nicoddemus** [comment]
@akhilramkee `7.4.1` has been released to PyPI. 👍

**Comment by akhilramkee** [comment]
Thanks @nicoddemus!

**Comment by bluetech** [comment]
OK, now that #11646 is in, we're ready to cut the 8.0.x branch and release 8.0.0rc1. I'll aim to do it by Tuesday (2024-01-02). (The main thing is to edit the release notes).

**Comment by bluetech** [comment]
pytest 8.0.0rc1 is now available on PyPI for testing.

**Comment by bluetech** [comment]
pytest 8.0.0rc2 was released a few days ago containing fixes to all known issues/regressions (correct me if I'm wrong).

My current plan is to release pytest 8.0.0 a week from now, Jan 27 (next Saturday).

**Comment by nicoddemus** [comment]
Awesome, thanks @bluetech for leading this release!

**Comment by bluetech** [comment]
8.0.0 is out!
