### ISSUE TITLE
 PytestAssertRewriteWarning when including a plugin via 'pytest_plugins' and importing

### ISSUE THREAD

**Issue by LewisGaul** [pytest-dev/pytest#11150]
Warning when running pytest:
`PytestAssertRewriteWarning: Module already imported so cannot be rewritten: plugin`

#### Steps to reproduce
- Create a local plugin, e.g. empty `plugin.py` file.
- Create a test that includes the plugin via `pytest_plugins` and also imports the plugin:
```python
import plugin
pytest_plugins = ("plugin",)
```
- Run the tests:
```
$pytest test.py
=============================================== test session starts ================================================
platform linux -- Python 3.8.10, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/legaul/tmp/pytest-issue
collected 0 items

================================================= warnings summary =================================================
venv/lib/python3.8/site-packages/_pytest/config/__init__.py:755
  /home/legaul/tmp/pytest-issue/venv/lib/python3.8/site-packages/_pytest/config/__init__.py:755: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: plugin
    self.import_plugin(import_spec)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================ 1 warning in 0.01s ================================================
```

#### Extra information

Obviously this is a contrived minimal example; a more realistic scenario is:
- `conftest.py` contains `pytest_plugins = (...)`
- Some indirect import of the plugin, e.g. for the purpose of type annotations

This is not seen when loading the plugin using `pytest -p plugin` instead (since the import happens earlier?).

Perhaps related to https://github.com/pytest-dev/pytest/issues/10230?

**Comment by The-Compiler** [comment]
See the [relevant docs](https://docs.pytest.org/en/latest/how-to/writing_plugins.html#requiring-loading-plugins-in-a-test-module-or-conftest-file):

> Plugins imported by [pytest_plugins](https://docs.pytest.org/en/latest/reference/reference.html#globalvar-pytest_plugins) will also automatically be marked for assertion rewriting (see [pytest.register_assert_rewrite()](https://docs.pytest.org/en/latest/reference/reference.html#pytest.register_assert_rewrite)). However for this to have any effect the module must not be imported already; if it was already imported at the time the [pytest_plugins](https://docs.pytest.org/en/latest/reference/reference.html#globalvar-pytest_plugins) statement is processed, a warning will result and assertions inside the plugin will not be rewritten. To fix this you can either call [pytest.register_assert_rewrite()](https://docs.pytest.org/en/latest/reference/reference.html#pytest.register_assert_rewrite) yourself before the module is imported, or you can arrange the code to delay the importing until after the plugin is registered.

**Comment by DeflateAwning** [comment]
This is not working with [pytest_jsonreport](https://pypi.org/project/pytest-json-report/):

```python

import pytest
pytest.register_assert_rewrite('pytest_jsonreport', 'JSONReport', 'json_report_plugin') # Source: https://github.com/pytest-dev/pytest/issues/11150; call before importing pytest_jsonreport
from pytest_jsonreport.plugin import JSONReport
pytest.register_assert_rewrite('pytest_jsonreport', 'JSONReport', 'json_report_plugin') # Source: https://github.com/pytest-dev/pytest/issues/11150; call before importing pytest_jsonreport

```

Any suggestions what I'm doing wrong? @The-Compiler

**Comment by The-Compiler** [comment]
@DeflateAwning Sorry, this got lost in my inbox. You should probably call `pytest.register_assert_rewrite('pytest_jsonreport.plugin')` because that's what you import.

If it's not that, make sure it really didn't get imported before, e.g. via `assert "pytest_jsonreport" not in sys.modules` and `assert "pytest_jsonreport.plugin" not in sys.modules`.

**Comment by DeflateAwning** [comment]
Weird, still didn't work

**Comment by bluppfisk** [comment]
I have this issue with the `celery.contrib.pytest` plugin. There's no mention of it in my code anywhere except in **conftest.py** where it must be loaded (or else..!) However, when I run pytest it complains that the module has already been loaded.
