### ISSUE TITLE
tox: `PYTHONWARNDEFAULTENCODING` should only be applied to tests

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#11157]
Currently `PYTHONWARNDEFAULTENCODING` [is set](https://github.com/pytest-dev/pytest/blob/b77d0deaf53697630ba534f62dc871f4eb275f14/tox.ini#L42) for all tox environments. But most tools like pre-commit, mypy, sphinx are not clean of this warning, it causes noise when running `tox`, in some cases a *lot* of noise.

I tried fixing it myself but couldn't figure out how to get tox to only set an envvar only for the py* environments. Hopefully someone who knows more about tox can figure it out.

**Comment by Zac-HD** [comment]
I just add a `setenv =` section to the environments where I want to set it back to zero; see https://github.com/HypothesisWorks/hypothesis/pull/3691 for an example.  I've also opened a bunch of issues and PRs asking upstream projects to run clean themselves, so hopefully it'll get easier over time.

**Comment by bluetech** [comment]
@Zac-HD this works, sent #11173 for this.
