### ISSUE TITLE
./pytest: symbol lookup error: ./pytest: undefined symbol: _PyGC_generation0

### ISSUE THREAD

**Issue by vijay-subramanian-wdc** [pytest-dev/pytest#11161]
- [ ] a detailed description of the bug or problem you are having
My machine contains both python2.7 and python 3.8 installed where pytest picks up python 2.7 to use. Hitting undefined symbol error while using python2.7
- [ ] output of `pip list` from the virtual environment you are using
Package                Version
---------------------- --------------------
apturl                 0.5.2
autopep8               1.5
bcrypt                 3.1.7
blinker                1.4
bottle                 0.12.15
Brlapi                 0.7.0
certifi                2019.11.28
chardet                3.0.4
Click                  7.0
colorama               0.4.3
command-not-found      0.3
cryptography           2.8
cupshelpers            1.0
dbus-python            1.2.16
defer                  1.0.6
distro                 1.4.0
distro-info            0.23ubuntu1
duplicity              0.8.12.0
entrypoints            0.3
exceptiongroup         1.1.1
fasteners              0.14.1
flake8                 3.7.9
frozendict             1.2
future                 0.18.2
httplib2               0.14.0
idna                   2.8
iniconfig              2.0.0
jedi                   0.15.2
keyring                18.0.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
lockfile               0.12.2
louis                  3.12.0
macaroonbakery         1.3.1
Mako                   1.1.0
MarkupSafe             1.1.0
mccabe                 0.6.1
monotonic              1.5
netifaces              0.10.4
oauthlib               3.1.0
olefile                0.46
packaging              23.1
paramiko               2.6.0
parso                  0.5.2
pep8                   1.7.1
pexpect                4.6.0
Pillow                 7.0.0
pip                    20.0.2
pluggy                 1.2.0
protobuf               3.6.1
pycairo                1.16.2
pycodestyle            2.5.0
pycups                 1.9.73
pyflakes               2.1.1
PyGObject              3.36.0
PyJWT                  1.7.1
pymacaroons            0.13.0
PyNaCl                 1.3.0
pyRFC3339              1.1
pytest                 7.4.0
python-apt             2.0.0+ubuntu0.20.4.5
python-dateutil        2.7.3
python-debian          0.1.36ubuntu1
pytz                   2019.3
pyxdg                  0.26
PyYAML                 5.3.1
reportlab              3.5.34
requests               2.22.0
requests-futures       1.0.0
requests-unixsocket    0.2.0
SecretStorage          2.3.1
setuptools             45.2.0
simplejson             3.16.0
six                    1.14.0
ssh-import-id          5.10
systemd-python         234
tomli                  2.0.1
ubuntu-advantage-tools 27.2
ubuntu-drivers-common  0.0.0
ufw                    0.36
unattended-upgrades    0.1
urllib3                1.25.8
usb-creator            0.3.7
wadllib                1.3.3
waitress               1.4.1
wheel                  0.34.2
xkit                   0.0.0

- [ ] pytest and operating system versions

- [ ] minimal example if possible
./pytest: Symbol `PyLong_Type' has different size in shared object, consider re-linking
./pytest: Symbol `PySlice_Type' has different size in shared object, consider re-linking
./pytest: Symbol `PyAsyncGen_Type' has different size in shared object, consider re-linking
./pytest: symbol lookup error: ./pytest: undefined symbol: _PyGC_generation0

**Comment by The-Compiler** [comment]
This is a problem with your Python installation rather than pytest. I'm assuming the same happens if you just run `python` too?

**Comment by vijay-subramanian-wdc** [comment]
Do have python2 (2.8) & python3 (3.8) installations in the OS. Did not see this see problem while running python code from my machine. Current pytest installed is  7.4.0.

**Comment by RonnyPfannschmidt** [comment]
Pytest as normally installed is a python script

The error indicates a actual executable that's a platform binary

So without more details we can't even point out what's wrong

**Comment by vijay-subramanian-wdc** [comment]
To rule out python issues, will reinstall python 2.7 again.
When we say more details needed, can you please share what do we need to RC this problem? Thank you.

**Comment by RonnyPfannschmidt** [comment]
Python 2 Support was dropped from pytest way before version 7.x

Without accurate information on where your pytest binary came from its a lost cause as the common/expected installation mechanism don't created such a binary

It's unclear what to even ask for

**Comment by vijay-subramanian-wdc** [comment]
Agreed. Thank you for the looking into the problem. Closing this as outside scope of pytest.
