### ISSUE TITLE
7.4.0 docs missing

### ISSUE THREAD

**Issue by cjw296** [pytest-dev/pytest#11167]
https://docs.pytest.org/ still redirects to https://docs.pytest.org/en/7.3.x/ and https://docs.pytest.org/en/7.4.x/ returns a 404.

As part of this, I think https://docs.pytest.org/ should redirect to https://docs.pytest.org/en/stable/ instead of to a specific version

**Comment by nicoddemus** [comment]
Hey @cjw296, thanks a lot for the report!

I have updated the configuration, it is working now.
