### ISSUE TITLE
test_pdb.py hangs with tox -e py27-pexpect on Archlinux when run with devpi

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1116]
It works when running `tox -e py27-pexpect`, but not via `devpi test pytest==2.8.2 -e py27-pexpect` where it just hangs:

```
py27-pexpect create: /tmp/devpi-test1/targz/pytest-2.8.2/.tox/py27-pexpect
py27-pexpect installdeps: pexpect
py27-pexpect inst: /tmp/devpi-test1/downloads/pytest-2.8.2.tar.gz
py27-pexpect installed: pexpect==4.0.1,ptyprocess==0.5,py==1.4.30,pytest==2.8.2,wheel==0.24.0
py27-pexpect runtests: PYTHONHASHSEED='2265267001'
py27-pexpect runtests: commands[0] | py.test -rfsxX test_pdb.py test_terminal.py test_unittest.py
============================= test session starts ==============================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /tmp/devpi-test1/targz/pytest-2.8.2, inifile: tox.ini
collected 148 items

test_pdb.py ..............
```

I'm seeing this on three Archlinux machines. I don't see an easy way to add `-v` here (short of doing a new release on devpi with another channel), but if I'm counting the dots correctly, that'd be `test_pdb.py::TestPDB::test_pdb_interaction_capturing_twice`.

**Comment by RonnyPfannschmidt** [comment]
See this on any other distro ?

**Comment by The-Compiler** [comment]
Not on Ubuntu Trusty/Vivid and Debian Jessie...

**Comment by RonnyPfannschmidt** [comment]
the issue can still be replicated on various distrosand the reason is that we use pexpect completely wrong in he tests

**Comment by nieder** [comment]
Just as a datapoint, I'm getting a reliable hang on pytest-3.4.0 at `testing/test_pdb.py ....` with python3.6 on macOS 10.11, but not with python2.7, python3.4 or python3.5.

**Comment by nieder** [comment]
The test hangs with pexpect-pyXX installed if pyXX matches the pytest-pyXX I'm building. I only had the pexpect-py36 variant installed. If I remove that, then the py36 variant of pytest finishes the test suite.

**Comment by blueyed** [comment]
@RonnyPfannschmidt 
> the issue can still be replicated on various distrosand the reason is that we use pexpect completely wrong in he tests

Can you elaborate?

**Comment by blueyed** [comment]
Closing for now, there have been several fixes to the test.
