### ISSUE TITLE
pytest fail for interanl package py

### ISSUE THREAD

**Issue by srikervai** [pytest-dev/pytest#11176]
I installed pytest via `pip install pytest` and with the following simple test:

```
def test_sf_bayer_training(tmpdir):
    print(tmpdir)
    _config = TestingTrainerConfigInstance()
    _config.name = 'test_sf_bayer_training'
    _config.output_path = tmpdir / _config.name
    _curr_p = os.getcwd()
    _config.model_config_path = f'.models/sf.yaml'
    print(_config)
    return
```
I recieve the following error:
```
  File "/home/davids/venvs/vai/lib/python3.10/site-packages/_pytest/_io/terminalwriter.py", line 10, in <module>
    from _pytest.compat import final
  File "/home/davids/venvs/vai/lib/python3.10/site-packages/_pytest/compat.py", line 44, in <module>
    LEGACY_PATH = py.path. local
AttributeError: module 'py' has no attribute 'path'

Process finished with exit code 1

```

When I check locally:

```
(vai) ➜  ~ ipython
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import py

In [2]: py.path. local
Out[2]: py._path.local.LocalPath

```

How can I solve the issue with pytest so it can run?

Edit:
My pytest package:

```
py==1.11.0
pytest==7.4.0
```

**Comment by Zac-HD** [comment]
You will need to rename your internal package; the name `py` was taken by a third-party package [way back in 2004](https://docs.pytest.org/en/stable/history.html).

**Comment by The-Compiler** [comment]
@Zac-HD I think what @srikervai wanted to say is that pytest fails in its `py` internals - I see nothing pointing to a custom `py` package there, or am I missing something?

**Comment by RonnyPfannschmidt** [comment]
Unless shadowed,the py module has a path attribute,the error thus highly suggest a shadowed module

**Comment by srikervai** [comment]
probably there was a shadow py package, I created a brand new environment and then it started working :\
