### ISSUE TITLE
fixtures: change `FixtureDef.cached_result[2]` from exception triplet to exception

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#11208]
I propose changing the type of the 3rd item of `FixtureDef.cached_result` (which indicates a cached exception outcome of the fixture) from a `sys.exc_info` style triplet to just the exception instance.
    
The `sys.exc_info` exception triplet format is legacy from Python 2 and just complicates things nowadays.
    
While `cached_result` is not documented and is a private API, from 680 plugins I have checked out locally, 15 access it. However, none of them care about the type of `cached_result[2]`, except for `pytest-yield` plugin, but it's already broken in recent pytests and only supports pytest<=4.

**Comment by RonnyPfannschmidt** [comment]
+1 from me, but id also like to ensure we move the cache to the setup state in future

**Comment by bluetech** [comment]
> +1 from me, but id also like to ensure we move the cache to the setup state in future

I think something like that will be necessary for fixing #11205. There our preferred approach has a single FixtureDef having multiple values at the same time (for different nested scopes), so a single `cached_result` on the FixtureDef can no longer work.
