### ISSUE TITLE
_Original comment by_ **Ronny Pfannschmidt (BitBucket: [RonnyPfannschmidt](http://bitbucket.org/RonnyPfannschmidt), GitHub: [RonnyPfannschmidt](http://github.com/RonnyPfannschmidt))**:

### ISSUE THREAD

**Issue by Just6789** [pytest-dev/pytest#11207]
_Original comment by_ **Ronny Pfannschmidt (BitBucket: [RonnyPfannschmidt](http://bitbucket.org/RonnyPfannschmidt), GitHub: [RonnyPfannschmidt](http://github.com/RonnyPfannschmidt))**:

---

i identified a bug in escaping the assertion analysis information, further investigation is needed to elevate it

_Originally posted by @pytestbot in https://github.com/pytest-dev/pytest/issues/404#issuecomment-112204015
assets-src/js/main/collapsibles.js_
            
assets-src/js/main.jshttps://bugs.chromium.org/p/dawn/issues/list

**Comment by RonnyPfannschmidt** [comment]
The issue was resolved over a decade ago
