### ISSUE TITLE
Pay

### ISSUE THREAD

**Issue by Just6789** [pytest-dev/pytest#11212]
https://notifications.google.com/g/p/ADa0GC_5oat2hiVbxgMmTdqrnUXrw5hQ__IPD5ox-j3W9ox1MqDNLlUQ3pF0ZMNSpitP8TEnCpXd3ci3KwyzmQcI4sJPIgG6EUQ8HZkOSeOkrIZL_wRVSbWfMUSs_5o5LCEEBmuP_ztNo1FTjcSfRsl7XwtcUE8rOV3x6WpkBg6QMEuIsXniLcb7XoRSNb_FZ6H9jP7DfLiUN1DQjCjV_AUZjww4zG3ARKVXzYx3lY3mxyFMWZsXbEmYr1X2tyoxSa4h77h-eBoHCbx_SvNF

**Comment by The-Compiler** [comment]
Given that this is your second comment here with absolute nonsense, and you seem to like [doing this elsewhere too](https://github.com/Just6789?tab=overview&from=2023-06-01&to=2023-06-30)... banned from pytest-dev and reported to GitHub.
