### ISSUE TITLE
Launch test's dependencies too when executing single test

### ISSUE THREAD

**Issue by Roo4L** [pytest-dev/pytest#11224]
When executing single test using `pytest test_name` if test has a dependency (marked by pytest-dependency extension) the test is simply ignored because it's dependency is skipped.

Launch test's dependency too when executing single test. (Either by default of with a special flag being passed). This allows to quickly debug failing tests without waiting for all tests to complete each time.

**Comment by RonnyPfannschmidt** [comment]
Pytest is unaware of that 3rd party extension

**Comment by Roo4L** [comment]
This one: https://pypi.org/project/pytest-dependency/

**Comment by nicoddemus** [comment]
Hi @Roo4L,

This question is probably more appropriate to be posted in https://github.com/RKrahl/pytest-dependency/issues.

Closing for now.
