### ISSUE TITLE
Changing a variable defined in a script is not registered when running multiple tests

### ISSUE THREAD

**Issue by LoremasterLH** [pytest-dev/pytest#11254]
I have a file `config.py` that contains a variable. This variable is changed in every `test_*.py` script. All tests in all files are run using the same value for this variable regardless of the value that was set in a specific script. This causes some tests that access the variable to fail. If each test file is run individually, there is no problem.

Using Python 3.8.10, 32-bit and pytest 7.4.0 on Win10.

Minimal example project: [pytestProject.zip](https://github.com/pytest-dev/pytest/files/12191821/pytestProject.zip). Run tests with `pytest tests` (project root must be in PYTHONPATH).

**Comment by RonnyPfannschmidt** [comment]
this is a user error

at import time you set variables in another module

 thus when pytest finds all tests, all imports happen and the module thats imported last wins

if you run only a single test file, then only a single import happens and of course things seem to work
