### ISSUE TITLE
pytest hangs if "platform" module is used in multi-threading environment on an Apple Silicon Mac

### ISSUE THREAD

**Issue by avoskresensky** [pytest-dev/pytest#11259]
Here's a simple test file that demonstrates the problem:

```
import concurrent.futures as futures
import platform

def _invoke():
    platform.platform()
    return None

def test_this():
    #platform.platform()   # uncomment this line to fix the problem

    with futures.ThreadPoolExecutor(max_workers=1) as executor:
        executor.submit(_invoke).result()
```

If `platform.platform()` is only called inside the thread pool the test hangs forever.
If `platform.platform()` is first called outside the thread pool, then the platform module will cache the result and use it later, which will prevent the hanging.

This seems to be a MacOS problem, possibly only Apple Silicon, but I can't say for sure as I have no Intel Macs handy to verity.
This test works just fine on Linux.

Running `test_this` function via a regular command line (with no pytest involved) works fine.

It seems to hang somewhere around `platform.uname` method.

My env:
* macOS-13.4.1-arm64-arm-64bit
* Python 3.10.11
* pytest 7.4.0

**Comment by RonnyPfannschmidt** [comment]
Does the hangup happen when running the code with plain python?

My first Impressionen is that this Looks like a stdlib bug

**Comment by avoskresensky** [comment]
> Does the hangup happen when running the code with plain python?
> 
> My first Impressionen is that this Looks like a stdlib bug

No, as I mentioned in the description, it doesn't. When run without pytest in the picture, everything runs fine.

**Comment by nicoddemus** [comment]
I don't have a Mac to test myself, however `pytest` uses `platform` in a few places:

https://github.com/search?q=repo%3Apytest-dev%2Fpytest+platform.+language%3APython&type=code

I quickly glanced:

* `platform.system()`
* `platform.node()`
* `platform.python_version()`
* `platform.machine()`

One could try call some/all of them at the top of your module and execute via `python` to check if they are related to the problem.

**Comment by avoskresensky** [comment]
> One could try to call some/all of them at the top of your module and execute via `python` to check if they are related to the problem.

If called outside of `ThreadPoolExecutor` none of those calls present any problems.

Moreover, as I demonstrated above, because of `platform` module internal caching, calling them first outside of `ThreadPoolExecutor` actually prevents the hangup.

**Comment by nicoddemus** [comment]
> Moreover, as I demonstrated above, because of platform module internal caching, calling them first outside of ThreadPoolExecutor actually prevents the hangup.

Yeah that is strange, unfortunately I'm out of ideas.
