### ISSUE TITLE
Create internal `_pytest.compat` module to host workarounds for different interpreter versions

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1125]
Create a `_pytest._compat` module that contains workarounds for different interpreter versions. 

The benefit would be to concentrate this kind of functionality into a single place making it easy to reuse it and remove compatibility code as support for older python versions is dropped.

**Comment by RonnyPfannschmidt** [comment]
`_pytest` is already internal, no need t double imho

**Comment by RonnyPfannschmidt** [comment]
closing as we have such a module since a while now
