### ISSUE TITLE
documentation: provide best-practise example for multiple tests with one set of parametrised input but different expected outputs

### ISSUE THREAD

**Issue by calestyo** [pytest-dev/pytest#11260]
#### What's the problem this feature will solve?
I read through all of [How to parametrize fixtures and test functions](https://docs.pytest.org/en/7.4.x/how-to/parametrize.html) and [Parametrizing tests](https://docs.pytest.org/en/7.4.x/example/parametrize.html) and while of course one could "hack" something together from the examples already given there, I think one typical use case might deserve it's own description on how one should do it.

Namely, if one has multiple of tests, with multiple inputs (but the same for all tests) and for each test a different set of expected outputs (where each output corresponds to one of the shared inputs.

For example:<br>
I want to test `str` methods that take zero parameters, e.g. `str.capitalize()`, `str.casefold()`, ` str.isalnum()`, ` str.islower()` and so on.

I might want to do this on various strings like `""`, `"abcd"`, `b"\u65"`, perhaps some with awkward unicode chars, control characters etc. pp..<br>
The expected output would obviously differ depending on the input.

#### Describe the solution you'd like
The closest of what I personally (being an absolute noob+beginner in pytest) would consider the most idiomatic something based on the [Parametrizing test methods through per-class configuration](https://docs.pytest.org/en/7.4.x/example/parametrize.html#parametrizing-test-methods-through-per-class-configuration) example:

Like having a class for all tests of that type (`str`-methods that take zero arguments, with one test per function).<br>
There would be one `common_input` which would be a list of the strings. And then, as in the referenced example, per test a `"test_isalnum": […],` which gives the list of expected outputs.<br>
The problem with that of course is, that if the lists get longer, it gets error prone, as the position of the expected input and ouput in their respective lists must match.

So question is also: is there a better way? And if so which?

But if it would be the above, then ideally the example would tell how to set part of the `id`, but only on the `common_input`, so I could use IDs like `empty-string`, `plain-ascii-chars`, `weird-unicode-chars`, etc. pp. but just once, and not having to re-set the IDs per test.

**Comment by RonnyPfannschmidt** [comment]
its not clear what you are asking for

my current understanding is that you have value tables and want to match ids to common values

i'd like to see an example of what you hope to use

**Comment by calestyo** [comment]
Consider e.g.:
```
input = [
         "",
         "abc",
         "𓀵𓁾𓀉𓀺",
         "0",
         "\xFF"
         ]

expected_ouput_capitalise = [
                             "",
                             "𓀵𓁾𓀉𓀺",
                             "Abc",
                             "0",
                             "Ÿ"
                            ]

expected_ouput_isnumeric = [
                            False,
                            False,
                            False,
                            True,
                            False
                            ]
```
and you want to test `str.capitalise()` and `str.isnumeric()`.

The current examples seem to rather just cover the case where expected input would always be written again (for each expected output, like in `[("", False), ("abc", False), …]`.

So as I've said above, it might be helpful to have a best current practise example, that shows how to do it for multiple tests, where the input stays the same, but, depending on the test, the expected output is different.

And perhaps ideally taking `id`s into account, like that one specifies:
```
myids = [
         "empty-string",
         "ascii-letters",
         "unusual-unicode-letters",
         "ascii-digit",
         "non-valid-utf8"
         ]
```

**Comment by kalekundert** [comment]
For what it's worth, my opinion is that the best practice is just to specify the inputs separately for each test case.  Here are some reasons:

- In general, keeping test cases as independent as possible is almost always a good idea.  It's hard to explain why, other than by saying that this is a lesson I've learned over time, and that it keeps the tests more maintainable.  For example, if you want to add a test case to cover a bug in one function, it's annoying to have to simultaneously add a bunch of test cases to unrelated functions.
- Test inputs should be tailored to the function being tested.  For example, if you're writing tests for a `islower()` function, you'll want to include edge cases relating to the meaning of upper/lowercase letters according to the unicode spec.  Such cases are unlikely to meaningfully exercise an `isalnum()` function, though.  To put it another way, I don't think that sharing inputs between tests actually makes your tests much better.
