### ISSUE TITLE
fail test when side_effect is only called once

### ISSUE THREAD

**Issue by upstartjohnvandivier** [pytest-dev/pytest#11267]
#### What's the problem this feature will solve?
Mock.side_effect is tricky to use properly. Problem cases include:
1. setting the value to an array of length less than two, in which case return_value is more readable and debuggable
2. setting the value to an array of length n where the value doesn't change. This can be dangerous when the value is another mock or otherwise mutable byref

Having the test simply fail in these cases prevents other hard-to-trace errors from arising in the first place.

#### Describe the solution you'd like
two options:
1. throw an error which includes an instructive message like "please ensure that a method under side_effect is called more than once, otherwise prefer return_value
2. whenever side_effect is set, automatically create an assertion that the method under side effect is not called only once

this behavior would only trigger when the side_effect has a non-None return value; ie it is exempt if it is actually creating a side effect like throwing an error instead of being used as a sort of dynamic return_value tool

#### Alternative Solutions
feature request also filed on ruff [here](https://github.com/astral-sh/ruff/issues/6199) and we have considered a custom internal linter (not ideal ofc)

**Comment by The-Compiler** [comment]
`unittest.mock` is coming from the Python standard library and not pytest. Even if you're using pytest-mock (in which case this would be the wrong repo), it just expoxes the stdlib object.

**Comment by upstartjohnvandivier** [comment]
Thanks @The-Compiler 

Python language proposal created at https://discuss.python.org/t/feat-unittest-mock-side-effect-fails-on-improper-usage/31003

Support is welcome

**Comment by The-Compiler** [comment]
Note that a `side_effect` can also be an exception, or a callable - and if it's an iterable, it can be any iterable (thus the length isn't necessarily known). IMHO, this is introducing a lot of magic and special casing for a questionable benefit.
