### ISSUE TITLE
documentation: still no assertion introspection if assertion has message?

### ISSUE THREAD

**Issue by calestyo** [pytest-dev/pytest#11265]
Hey.

Sorry if I miss something obvious and just make noise... O:-)

https://docs.pytest.org/en/7.4.x/how-to/assert.html claims:
> However, if you specify a message with the assertion like this:
> assert a % 2 == 0, "value was odd, should be even"
> then no assertion introspection takes places at all and the message will be simply shown in the traceback.

But when I try this, then introspection **does** seem to happen i.e. I see e.g.:
```
>       assert len(pathname) <= len(escaped_pathname), "foobar"
E       AssertionError: foobar
E       assert 2 <= 1
E        +  where 2 = len('//')
E        +  and   1 = len('/')

test_misc.py:48: AssertionError
```
just with the additional message.

Could it be that this has changed at some point in time but documentation wasn't updated?

Thanks,
Chris.

**Comment by The-Compiler** [comment]
That part of the docs is from 2011 (29d58ffdf236a7647bf2ab7324849802e17e5f12, 8de50347fbe424b851cc4ced40a276e292af5c20).

It looks like support for assert introspection was added in 2014: 37bd1e03cb77a26ae80873a8725c87d57fda987c - also see #549.

So yep, it looks like this is indeed just outdated! Would you like to open a PR removing that sentence?

**Comment by calestyo** [comment]
@The-Compiler I didn't remove the sentence but merely replace it with the information that the message is printed, too.

Think it's actually valuable to know that, thus better than removing.
