### ISSUE TITLE
Change of behaviour: `ImportPathMismatchError` with test module + src package layout

### ISSUE THREAD

**Issue by neutrinoceros** [pytest-dev/pytest#11276]
I've found that the dev version `pytest` crashed on collection for a package of mine.
Here's a minimal package which reproduces the problem https://github.com/neutrinoceros/pytest_bug_reprod

Note that the presence of `tests/__init__.py` is essential to reproduce !

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
```
Package    Version
---------- ----------------------
attrs      23.1.0
iniconfig  2.0.0
packaging  23.1
pip        23.2.1
pkg        0.0.0
pluggy     1.2.0
pytest     8.0.0.dev144+g4797deab
setuptools 65.5.
```
- [x] pytest and operating system versions
- [x] minimal example if possible

Is this change intentional ? Is it bad practice to include a `__init__.py` file in `tests/` ? IIRC it's there so that `setuptools` automatically includes test in source distributions/wheels

**Comment by RonnyPfannschmidt** [comment]
It seems that your example worked before due to a bug in pytest

Doctest-modules collects in the checkout, so a non-editable install implies a mismatch

**Comment by neutrinoceros** [comment]
In that case, how should I run my doctest tests instead ?

**Comment by RonnyPfannschmidt** [comment]
As of now the recommended approach is either editable or pyargs

The import roots proposal is supposed to eventually correctly solve mirrored files

**Comment by neutrinoceros** [comment]
Thank you ! I was indeed able to fix my CI by splitting my tests in two runs (`pytest` then `pytest --pyargs pkg --doctest-modules`).
