### ISSUE TITLE
calling pytest.Metafunc.parametrize multiple times

### ISSUE THREAD

**Issue by calestyo** [pytest-dev/pytest#11289]
Hey.

I think this is at least a documentation ambiguity. ;-)

https://github.com/pytest-dev/pytest/blob/cc0adf6bf3c9f356e3473ff8a21004b9c1fb2b93/src/_pytest/python.py#L1242-L1249

AFAIU however, this can be only **called** multiple times on **different** parameters.

Otherwise I get a:
```
ERROR test_foo.py - ValueError: duplicate 'cal'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```

I stumbled over this while trying what [what I've asked for on discord](https://discord.com/channels/810210251398840371/810244286293213204/1137526973346881588)... maybe the behaviour there is another bug, but maybe some pytest expert can look at it and confirm whether it's fishy... I'm still basically a complete pytest beginner... so I don't wanna file issues for everything that seems just strange to me ;-)

**Comment by RonnyPfannschmidt** [comment]
this is expected behaviour, but the user facing error could be better, thanks for pointing it out

**Comment by RonnyPfannschmidt** [comment]
to elaborate a little, if you already did parameterize for a parameter, its a error to add another parameter for it, similar to how one cannot use a keyword name multiple times

**Comment by calestyo** [comment]
> this is expected behaviour, but the user facing error could be better, thanks for pointing it out

Uhm, well I though mostly that sentence of the documentation would need some updating. For that I could do a PR.


> to elaborate a little, if you already did parameterize for a parameter, its a error to add another parameter for it, similar to how one cannot use a keyword name multiple times

Okay that is in principle reasonable, but what I don't get is:<br>
AFAIU, [one can overwrite fixtures with/without parametrisation](https://docs.pytest.org/en/7.4.x/how-to/fixtures.html#override-a-parametrized-fixture-with-non-parametrized-one-and-vice-versa), which I think is really nice, as it's e.g. quite likely that one may want to share common names like `pathname` or so but have them being actually different fixtures.<br>
My understanding was, that this overwriting can be done even within a module (e.g. the one within a class overwrites the one at module level - and not just overwriting those from `conftest.py`).

Good,... but this doesn't seem to work as nice with `pytest_generate_tests`.

Consider:<br>
`conftest.py`:
```
import pytest
import sys

def pytest_generate_tests(metafunc):
    f = open("/tmp/caldebug", "a")
    print("CONFTEST.PY: " + str(metafunc.fixturenames), file=f)
    f.close()
    if "cal" in metafunc.fixturenames:
        metafunc.parametrize("cal", [0, 1, 2])
```
`test_foo.py`:
```
import pytest
import sys

@pytest.fixture(scope="module")
def myfix():
    return ValueError("MYFIX")

def test_foo(myfix, cal1):
    print(id(myfix))
    print(cal1)
    assert 0

def test_bar(myfix):
    print(id(myfix))
    assert 0

def pytest_generate_tests(metafunc):
    f = open("/tmp/caldebug", "a")
    print("FOO: " + str(metafunc.fixturenames), file=f)
    f.close()
    if "cal1" in metafunc.fixturenames:
        metafunc.parametrize("cal1", ["a", "b", "c"])
```
`test_baz.py`:
```
import pytest
import sys

@pytest.fixture(scope="module")
def myfix():
    return ValueError("MYFIX2")

def test_baz(myfix, cal):
    print(id(myfix))
    print(cal)
    assert 0
```


Now running it:
```
$ pytest
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.11.4, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/calestyo/z/x
collected 7 items                                                                                                                                                                            

test_baz.py FFF                                                                                                                                                                        [ 42%]
test_foo.py FFFF                                                                                                                                                                       [100%]

========================================================================================== FAILURES ==========================================================================================
________________________________________________________________________________________ test_baz[0] _________________________________________________________________________________________

myfix = ValueError('MYFIX2'), cal = 0

    def test_baz(myfix, cal):
        print(id(myfix))
        print(cal)
>       assert 0
E       assert 0

test_baz.py:11: AssertionError
------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------
140269563284544
0
________________________________________________________________________________________ test_baz[1] _________________________________________________________________________________________

myfix = ValueError('MYFIX2'), cal = 1

    def test_baz(myfix, cal):
        print(id(myfix))
        print(cal)
>       assert 0
E       assert 0

test_baz.py:11: AssertionError
------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------
140269563284544
1
________________________________________________________________________________________ test_baz[2] _________________________________________________________________________________________

myfix = ValueError('MYFIX2'), cal = 2

    def test_baz(myfix, cal):
        print(id(myfix))
        print(cal)
>       assert 0
E       assert 0

test_baz.py:11: AssertionError
------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------
140269563284544
2
________________________________________________________________________________________ test_foo[a] _________________________________________________________________________________________

myfix = ValueError('MYFIX'), cal1 = 'a'

    def test_foo(myfix, cal1):
        print(id(myfix))
        print(cal1)
>       assert 0
E       assert 0

test_foo.py:11: AssertionError
------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------
140269563293280
a
________________________________________________________________________________________ test_foo[b] _________________________________________________________________________________________

myfix = ValueError('MYFIX'), cal1 = 'b'

    def test_foo(myfix, cal1):
        print(id(myfix))
        print(cal1)
>       assert 0
E       assert 0

test_foo.py:11: AssertionError
------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------
140269563293280
b
________________________________________________________________________________________ test_foo[c] _________________________________________________________________________________________

myfix = ValueError('MYFIX'), cal1 = 'c'

    def test_foo(myfix, cal1):
        print(id(myfix))
        print(cal1)
>       assert 0
E       assert 0

test_foo.py:11: AssertionError
------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------
140269563293280
c
__________________________________________________________________________________________ test_bar __________________________________________________________________________________________

myfix = ValueError('MYFIX')

    def test_bar(myfix):
        print(id(myfix))
>       assert 0
E       assert 0

test_foo.py:15: AssertionError
------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------
140269563293280
================================================================================== short test summary info ===================================================================================
FAILED test_baz.py::test_baz[0] - assert 0
FAILED test_baz.py::test_baz[1] - assert 0
FAILED test_baz.py::test_baz[2] - assert 0
FAILED test_foo.py::test_foo[a] - assert 0
FAILED test_foo.py::test_foo[b] - assert 0
FAILED test_foo.py::test_foo[c] - assert 0
FAILED test_foo.py::test_bar - assert 0
===================================================================================== 7 failed in 0.04s ======================================================================================
```
works, and one sees:
- `test_baz.py` which doesn't "overwrite" `pytest_generate_tests` gets only the one from `conftest.py` called.
- but `test_foo.py` gets **both** called

Now I can imagine that the latter is done to get parametrisation from the "higher" level (i.e. `conftest.py`) which is not overwritten in `test_foo.py`.

But the prolem is, if in `test_foo.py` I `s/cal1/cal/g`, i.e. let it use the same name as the param that's already parametrised in the higher level `conftest.py`, one get's the duplication error.

Wouldn't it be better if, in that case, the parametrisations from `test_foo.py` clear&override those from `conftest.py` - but only those that actually are re-defined?


Also, it would be nice if I could, analogously to overriding fixture functions, have multiple `pytest_generate_tests` per module. I think about being able to put it n class definitions (maybe even at multiple levels, with nested classes).<br>
The benefits would be IMO better readability (keeping the tests in their class close with the code the parametrises them) and also allowing more fine grained overwriting

What do you think? :-)

**Comment by calestyo** [comment]
Oh and the output from the debug file above would be:
```
CONFTEST.PY: ['myfix', 'cal']
FOO: ['myfix', 'cal1']
CONFTEST.PY: ['myfix', 'cal1']
FOO: ['myfix']
CONFTEST.PY: ['myfix']
```

**Comment by RonnyPfannschmidt** [comment]
This one plays into hooks

For generate tests all applying implementations are called

**Comment by calestyo** [comment]
Uhm? What does that mean? That the idea of allowing overwriting via `pytest_generate_tests` couldn't be done?

**Comment by RonnyPfannschmidt** [comment]
As of now its impossible, and enabling it is full of pitfalls

**Comment by calestyo** [comment]
Would it be worth to add a feature request for it in order to track ideas?

**Comment by RonnyPfannschmidt** [comment]
For now id avoid a tracking issue as it's likely it would Just rot

If we get someone actively working on it that may change

**Comment by calestyo** [comment]
How easy do you think would such implementation be? I mean it kinda already works for fixture functions? In that `setmulti()` function that notices the duplicate... couldn't that "simply" overwrite the previous parametrisations if they were made by a higher level (or is that information not available)?

**Comment by RonnyPfannschmidt** [comment]
It's not safely available as the Tracking for single parameter vs multi parameter is not done

For safe replace it's not safely possible in case of a subset


Eg Parametrize with foo and bar at once and then trying to only replace bar

As far as I'm concerned we shouldn't allow that type of replacement as it's very error prone to do in retrospect

Even more so if we introduce covariant parametrization

**Comment by nicoddemus** [comment]
Fixed by #11291

**Comment by calestyo** [comment]
But it **is** supported, that one calls `pytest_generate_tests` (like once from a test module and once from `conftest.py`), or isn't it?<br>
Documentation on that is unfortunately pretty sparse. ;-)

Would the other idea I had above be feasible, i.e. that one could define `pytest_generate_tests` also in classes, and thus allow the definitions of the tests (if made in classes) be more close to the parametrisation?

**Comment by calestyo** [comment]
I played a bit around with the 2nd idea I had above, namely having `pytest_generate_tests` inside class definitions.<br>
And it seems, that already works.

I've had tried something like:
```
class TestFoo():
    def pytest_generate_tests(metafunc):
        ...
```
before (where I thought it wouldn't work)... and that in fact isn't even picked up by `pytest`.

But when I add `@staticmethod` it works like a charm, e.g.:
```
class TestFoo():
    @staticmethod
    def pytest_generate_tests(metafunc):
        print("I'm in TestFoo")
        print(metafunc.cls)
        print(metafunc.function)
        print(metafunc.fixturenames)
        if metafunc.cls is TestFoo:
            metafunc.parametrize("param1, param2", [(1,2),(3,4)])
        else:
            print("Foo: wrong class")
        print("")

    def test_foo(self, param1, param2):
        assert param1 == param2
```
gives:
```
FAILED test_foo.py::TestFoo::test_foo[1-2] - assert 1 == 2
FAILED test_foo.py::TestFoo::test_foo[3-4] - assert 3 == 4
```

even better, if in the same test module I add another:
```
…
class TestBar():
    @staticmethod
    def pytest_generate_tests(metafunc):
        print("I'm in TestBar")
        print(metafunc.cls)
        print(metafunc.function)
        print(metafunc.fixturenames)
        if metafunc.cls is TestBar:
            metafunc.parametrize("param1, param2", [(5,6),(7,8)])
        else:
            print("Bar: wrong class")
        print("")
    
    def test_bar(self, param1, param2):
        assert param1 == param2
```
I get:
```
FAILED test_foo.py::TestFoo::test_foo[1-2] - assert 1 == 2
FAILED test_foo.py::TestFoo::test_foo[3-4] - assert 3 == 4
FAILED test_foo.py::TestBar::test_bar[5-6] - assert 5 == 6
FAILED test_foo.py::TestBar::test_bar[7-8] - assert 7 == 8
```

So despite the same `argnames` it does some sort of "overwriting" (well not really overwriting: it limits the effects to the class).

It seems, that even the check `if metafunc.cls is TestFoo:` is not needed, and pytest calls the function already for the right classes (and their test functions).<br>
I **would** however need it, if I had one common `pytest_generate_tests` on the module level.

Wohoo!


Unfortunately, none of this seems documented.<br>
@RonnyPfannschmidt @nicoddemus  I'd write documentation, if you confirm that the above is supported (and whether or not the check for the class is needed is / is not needed as I assume.

Also, what's IMO missing from documentation is:

That one can have - at module level - `pytest_generate_tests` in both `conftest.py` and other test modules, as long as they don't re-define the same argname combinations.<br>
I just don't realise yet if the same name mustn't be used ever... or if just not for the same test

That is:<br>
Can one have (at module level):
```
def pytest_generate_tests(metafunc):
    if metafunc.function is test_foo:
            metafunc.parametrize("param1, param2", [(1,2),(3,4)])
    elif metafunc.function is test_bar:
            metafunc.parametrize("param1, param2", [(5,6),(7,8)])
```
(or the same using `metafunc.cls` to check for the class)<br>
and the same named params will get different parametrisation for the different funcs?


Cheers,
Chris.

**Comment by calestyo** [comment]
Oh and btw: `@classmethod` does not seem to work... which might have been nice if it would.

**Comment by calestyo** [comment]
Another thing, that might be worth to add as an example (in terms of making people understand how things works) is something like:

```
def test_other():
    assert 1


class TestFoo():
    p = [(1,2),(3,4)]
    
    @staticmethod
    def gen_params():
        print("gen_params called")
        tmp = __class__.p
        __class__.p = [(5,6),(7,8)]
        return tmp

    @staticmethod
    def pytest_generate_tests(metafunc):
        metafunc.parametrize("param1, param2", __class__.gen_params(), scope="class")

    def test_foo(self, param1, param2):
        assert param1 == param2

    def test_bar(self, param1, param2):
        assert param1 == param2+3
```

My background here is, that I have a test function that receives lots(!) of generated parameters (not just the 2 tuples as in the example), here simulated with `gen_params()`.<br>
Since my the values for my parametrisation stay the same (not in the example above - but in my real code) I'd like to generate them only once and ideally only when the test is actually run.

The latter already works with the above schema (i.e. when I generate my data in `pytest_generate_tests` **within** the class), then `gen_params()` is only called when `pytest_generate_tests` is invoked, which doesn't seem to happen when running pytest only for `test_other()`.<br>
But, they're now generated twice (as  `pytest_generate_tests` is called twice), even with `scope="class"`.

At first, I though that it's clear that my parameter generating function (not contained in the example above) is called twice (because `pytest_generate_tests` and thus `metafunc.parametrize` is and thus `gen_params`)… but then I hoped/expected, that the `scope=class` would still cause only the data from the first invocation (that is: `[(1,2),(3,4)]`) to be used.<br>
Like as if once `metafunc.parametrize()` is entered, it sees that the scope is `class` and that the params are already set up and then immediately exits without further changes.

But it doens't - it uses the new params `[(5,6),(7,8)]`.

Actually I'm not 100% what happens there, respectively the concepts… any idea?
