### ISSUE TITLE
don't call pytest_generate_tests called on tests that are not even run

### ISSUE THREAD

**Issue by calestyo** [pytest-dev/pytest#11288]
#### What's the problem this feature will solve?
I have a test, which gets a huge number input/expected output pars via parametrisation. These pairs are themselves generated by some algorithm.<br>
Since not all tests in the module may require that test data I though it would be proper design, to only create the test data if the (requiring) test actually runs.

What, AFAIU, cannot be done is any of the following:
- Parametrising a fixture via (`@pytest.fixture(params=…)` wouldn't help, as the value for `params` would need to be already available and thus be **always** generated (on importing the test module), also, since the test data is really just generated pairs (input / expected output) of strings, a fixture function would do nothing but return the two values for each param pair.
- It doesn't help if I put my test data in a test class, because same as above, the class variable would get set on import.
- AFAIU there is no way that a fixture function itself would generated the param pairs, or is there?

AFAIU, the only way would be using `pytest_generate_tests` called and there, check whether the respective fixture(s) are actually needed and only if so, generate the test data params in the function.

When playing around with that (my problem is that there seems little to no documentation on what `conftest.py` should contain... e.g. should `pytest_generate_tests` go in that, or in the module (the examples do both)... and what if the function is in both? ...etc.) I noticed somewhat unexpected behaviour:

Even if I call e.g. `pytest test_foo.py::test_bar`, and `pytest` in the end actually just runs that test... it nevertheless invokes `pytest_generate_tests` for every test (even though it's clear that another e.g. `test_foo.py::test_blafasl` ain't going to run).<br>
I checked that by printing the requested `metafunc.fixturenames` in some debug file and using different fixture signature for the different test.

Wouldn't it be better if it only runs on the tests that are actually going to be run, if that's anyway already clear like with the invocation above?

Thanks,
Chris.

**Comment by bluetech** [comment]
Hi, I haven't read the issue in detail (sorry), but I think you might be looking for [indirect parametrization](https://docs.pytest.org/en/stable/example/parametrize.html#indirect-parametrization). If that's not it, let me know and I'll read more closely :)

**Comment by RonnyPfannschmidt** [comment]
Currently the problem description is inconsistent with how pytest either works or ought to work


- Parameterization expansion Happens per test function in collection, its currently mandatory, Definition needs to be introduced before a separation is conceivable

- fixtures happen after collection


My impression is that op wants to use a fixture as parameteriz source

**Comment by The-Compiler** [comment]
From what I understand, OP asks that a `pytest test_foo.py::test_one` does not call the `pytest_generate_tests` hook for `test_two`, given that it's guaranteed to never get run anyways.

**Comment by calestyo** [comment]
@bluetech No I don't think it's indirect parametrisation. My main point was simply, why is `pytest_generate_tests` called on tests, when it should in principle be already clear, that some tests aren't run at all.

It's not a big deal, I guess.<br>
I only stumbled over it while playing around `pytest_generate_tests` and trying to get it to work in an "overwriting" fashion, as can be done with fixture functions, but apparently not with `pytest_generate_tests` :-(

So I thought maybe it's just a matter of a simple `if` whether it needs to be run... but if it's more complicated... than just close the issue.

**Comment by RonnyPfannschmidt** [comment]
Currently generate tests is a required part of collection that cannot be slipped
