### ISSUE TITLE
provide all builtin fixtures with a `pytest_` prefix and use that prefix in internal fixtures

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1129]
currently when people override internal fixture names, we break, instead we should be able to gracefully fall back to a `pytest_` prefix

- [] support public aliases for fixtures, that's used for used for display unless a test writer fixture overrides it
- [] rename all internal fixtures to fit that naming scheme
- [] document how interacting plugins can make use of that
  (test-suite writers can pick preferences by making a explicit short-named fixture that depends on and returns the long named fixture

**Comment by auvipy** [comment]
what help is wanted regarding the issue?

**Comment by RonnyPfannschmidt** [comment]
the first step would be some way to alias fixtures (or provide a short name thats overidable)
however this needs discussion with @hpk42

**Comment by RonnyPfannschmidt** [comment]
closing since a different/better plan for fixture namespacing was discussed at the sprint
