### ISSUE TITLE
Pytest/capsys fixture not capturing stdout

### ISSUE THREAD

**Issue by derwolfe** [pytest-dev/pytest#1132]
`Py.test` isn't capturing the output from `stdout` or `stderr`. 

```
import sys

stdout = sys.stdout

def test_use_logger(capsys):
    stdout.write("called")
    out, err = capsys.readouterr()
    assert "called" in out
```

The test case was run and reproduced on OS X 10.11 with pythons 2.7.10 and 3.5.0.

The versions used are:
```
py==1.4.30
pytest==2.8.2
```

Thanks!

**Comment by derwolfe** [comment]
Also, calling `sys.stdout.write` and `sys.stderr.write` directly **do** seem to work correctly (that is, their output is captured).

**Comment by RonnyPfannschmidt** [comment]
capsys will replace the actual object instead of the underlying file descriptor
making a reference to the prior object will of course replace the stream

a solution is in planning, but will at best it 3.0

**Comment by The-Compiler** [comment]
As @RonnyPfannschmidt said, you're "saving" `sys.stdout` before pytest can replace it with the capturing one. The solution pretty much boils down to "don't do that" :wink:

Can this be closed?

**Comment by derwolfe** [comment]
@RonnyPfannschmidt thanks for your response. Yes, this can be closed.
