### ISSUE TITLE
Add a (supported) way to override assertion messages for custom types

### ISSUE THREAD

**Issue by craigds** [pytest-dev/pytest#11332]
#### What's the problem this feature will solve?

It would be useful for comparisons of custom types to be able to raise user-defined assertion messages. This is technically currently possible (for `==` comparisons anyway) by making those types subclass `ApproxBase`, but a supported API would be preferable.

#### Describe the solution you'd like

If pytest is comparing two values of type X and that type has a `repr_compare` method, it could be called by pytest to provide the list of lines for the assertion message (just like `ApproxBase._repr_compare`)

#### Alternative Solutions

Handling comparisons other than `==` might be useful too; I'm not sure what that would look like though. Perhaps we should use a method name like `repr_compare_eq` to leave room for other comparisons to be added later

#### Additional context

We added a `ContainsSubdict` type to check that a dict contains at least a group of items (and ignores any extra items it has). Code is [here](https://gist.github.com/craigds/8383da1b62dbfec54db8e4520c2f26ca) and usage looks like:

```python
    def test_foo():
        value = {"a": 1, "b": 2, "c": 3}
>       assert value == ContainsSubdict({"b": 2, "d": 4})
E       AssertionError: assert {'a': 1, 'b': 2, 'c': 3} == {'b': 2, 'd': 4}
E         Omitting 1 identical items, use -vv to show
E         Right contains 1 more item:
E         {'d': 4}
```

You will note the assertion error ignores the fields on `value` that are irrelevant to the comparison (ie not in the expected value dict) To accomplish this slightly custom error message we had to subclass pytest's `ApproxBase`, since the assertion code special-cases that type to allow an assertion message override. This feels pretty hacky and it would be great if there was an official way to do this instead.

**Comment by The-Compiler** [comment]
Note there already is the `pytest_assertrepr_compare` hook, see [How to write and report assertions in tests — pytest documentation](https://docs.pytest.org/en/latest/how-to/assert.html#defining-your-own-explanation-for-failed-assertions).

**Comment by The-Compiler** [comment]
Based on your example, `conftest.py`:

```python
from utils import ContainsSubdict

def pytest_assertrepr_compare(left, right, op):
    if isinstance(right, ContainsSubdict) and op == "==":
        return right.repr_compare(left)
    return None
```

`utils.py`:

```python
from _pytest.assertion.util import _compare_eq_dict

class ContainsSubdict:
    """
    Tests True for equality against a superdict that contains a subdict
    """

    def __init__(self, subdict):
        self.subdict = subdict

    def __repr__(self):
        return repr(self.subdict)

    def repr_compare(self, superdict):
        if isinstance(self.subdict, list):
            for i, subdict, superdict in enumerate(
                zip_longest(self.subdict, superdict)
            ):
                if not subdict.items() <= superdict.items():
                    return [
                        "comparison failed at item {i} of list:",
                        *self._repr_compare_dicts(subdict, superdict),
                    ]
            return []
        else:
            return self._repr_compare_dicts(self.subdict, superdict)

    def _repr_compare_dicts(self, subdict, superdict):
        # Just return the error message for dict equality, but first subtract the items that are
        # not relevant to the subdict, otherwise the error message will be too noisy.
        smaller_superdict = {k: v for (k, v) in superdict.items() if k in subdict}
        return _compare_eq_dict(smaller_superdict, subdict)

    def __eq__(self, superdict):
        if isinstance(self.subdict, list):
            for subdict, superdict in zip_longest(self.subdict, superdict):
                if not subdict.items() <= superdict.items():
                    return False
        else:
            if not self.subdict.items() <= superdict.items():
                return False

        return True
```

`test_x.py`:

```python
from utils import ContainsSubdict

def test_foo():
    value = {"a": 1, "b": 2, "c": 3}
    assert value == ContainsSubdict({"b": 2, "d": 4})
```

results in the same output as above.

**Comment by craigds** [comment]
oh nice, that actually looks great 👍 thanks!
