### ISSUE TITLE
goodpractises.rst doesn't work for new setuptools

### ISSUE THREAD

**Issue by skirpichev** [pytest-dev/pytest#1134]
test_args is a read-only property since 18.4.

See example of failed build: https://s3.amazonaws.com/archive.travis-ci.org/jobs/84756786/log.txt

**Comment by nicoddemus** [comment]
Thanks for the report! :smile:

Do you know if removing the `self.test_args = []` line from `finalize_options` is enough to fix it?

**Comment by skirpichev** [comment]
On Wed, Oct 14, 2015 at 08:29:06AM -0700, Bruno Oliveira wrote:
>    Do you know if removing the self.test_args = [] line from finalize_options
>    is enough to fix it?

No.  At least not without filtering for self.test_args
later (e.g. in run_tests).  E.g. by default ("./setup.py test" with no args):

    test_args = ['--verbose', None]

The last element is due to self.test_suite.

**Comment by jiffyclub** [comment]
This still seems to work on Python 2.7, but breaks on Python 3. When I comment out the `self.test_args = []` line I get this error when running tests on Python 2.7:

```pytb
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    'License :: OSI Approved :: GNU Affero General Public License v3'
  File "/Users/matt/miniconda3/envs/pandana/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/matt/miniconda3/envs/pandana/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/matt/miniconda3/envs/pandana/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/matt/miniconda3/envs/pandana/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/command/test.py", line 141, in run
TypeError: sequence item 2: expected string, bool found
```

**Comment by jiffyclub** [comment]
I was able to get this to run by completely removing the override of `finalize_options`. Note the relevant setuptools code is at https://bitbucket.org/pypa/setuptools/src/ab1b60d1c77966140b6ed0df78868c26c16d22b4/setuptools/command/test.py?at=default&fileviewer=file-view-default#test.py-44.

**Comment by danijar** [comment]
I needed something like this to make it work both inside virtualenvs and without, probably because of different setuptools versions. Might be worth adding this information to the guide.

```python3
    def finalize_options(self):
        super().finalize_options()
        # New setuptools don't need this anymore, thus the try block.
        try:
            self.test_args = []
            self.test_suite = 'True'
        except AttributeError:
            pass
```
