### ISSUE TITLE
setup_class does not work well with @pytest.fixture

### ISSUE THREAD

**Issue by vipkum2** [pytest-dev/pytest#11340]
### Discussed in https://github.com/pytest-dev/pytest/discussions/11330

<div type='discussions-op-text'>

<sup>Originally posted by **vipkum2** August 21, 2023</sup>
**What I want:** I need a session level setup for some data, this data need by the test scripts/tests, Also test scripts has some class level setup.
**Issue:** I am using below code to achieve the same but "setup_class" in test script, start executing with each test case. I am expecting it to run only once for the class. Without fixture It run once for class.

**Workaround:** I can use fixture directly in test case like: `def test_01(self,abc):`, it works. But I want that If I can only use value of "abc" in `setup_class`, so only one place I need to access the "abc".

```
#conftest.py file:

@pytest.fixture(scope="session")
def abc():
    print("\n\n ### ABC Session Level Setup ###")
    abc = 6
    #os.environ["a"] = str(data)
    yield abc
    print("\n\n ### ABC Session Level TearDown ###")
```

```
#test03.py
import pytest

class Test3:
    @pytest.fixture(autouse=True)
    def setup_class(self,abc):
        self.d = abc
        print("\n Inside Test3 setup_module",)

    def test_01(self,):
        print("test_01",self.d)

    def test_02(self,):
        print("test_02",self.d)

    def test_03(self,):
        print("test_03", self.d)```

```
#Execution logs:
vipin@nmjwr7pwg0 test % python3 -m pytest -s -vv test3.py -x
========================================================================= test session starts =========================================================================
platform darwin -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0 -- /opt/homebrew/opt/python@3.10/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/vipin/my_mac/pyLogger, configfile: pytest.ini
collected 3 items

test3.py::Test3::test_01

 ### ABC Session Level Setup ###

 Inside Test3 setup_module
test_01 6
PASSED
test3.py::Test3::test_02
 Inside Test3 setup_module
test_02 6
PASSED
test3.py::Test3::test_03
 Inside Test3 setup_module
test_03 6
PASSED

 ### ABC Session Level TearDown ###

========================================================================== 3 passed in 0.00s ==========================================================================
```</div>

**Comment by The-Compiler** [comment]
I don't see any kind of pytest bug here, so no need to have a duplicate to the discussion.
