### ISSUE TITLE
-k expression fails for same function name as module

### ISSUE THREAD

**Issue by ynikitenko** [pytest-dev/pytest#11348]
- [x] a detailed description of the bug or problem you are having

I have a test module named *test_variable.py*. I have a function *test_variable* in that module, as well as several others.
When I run

    pytest -vv -k test_variable test_variable.py

it picks other functions, apart from *test_variable*, as well. When I require another function from that module to be tested, it is selected fine.

- [ ] output of `pip list` from the virtual environment you are using
Is it really necessary? It looks violating some privacy issues.

- [x] pytest and operating system versions

7.4.0, Arch Linux 6.4.10-arch1-1.

- [ ] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
Thats expected behavior for -k

Use test ids to select specific tests

**Comment by ynikitenko** [comment]
I tried to use test_variable.test_variable, but that failed. I've no idea of test ids, thanks.
It would be great to add that information somewhere in docs, I didn't see it in the description of the *-k* expression.

**Comment by The-Compiler** [comment]
See [How to invoke pytest — pytest documentation](https://docs.pytest.org/en/7.4.x/how-to/usage.html)

**Comment by ynikitenko** [comment]
Many thanks for the link, @The-Compiler . Now I can actually run my test with

    pytest -vv test_variable.py::test_variable

But it looks really strange. What is the reason I can't select a function with the same name as module?
I can see no documentation about that usage, why it is not allowed.
Besides, it looks very inconsistent: I have to omit the *-k* completely to get it work. Sorry, it doesn't look obvious or logical for people who are not experts (meaning myself, of course :) .

**Comment by The-Compiler** [comment]
> But it looks really strange. What is the reason I can't select a function with the same name as module?
> I can see no documentation about that usage, why it is not allowed.

It is allowed. As mentioned in those docs, `-k` also matches on filenames. All your tests have `test_variable` in their filename, so the filter matches all of them.

> Besides, it looks very inconsistent: I have to omit the _-k_ completely to get it work.

It's a different argument. One is a "fuzzy" filtering by keyword (all tests that contain the given word in their filename or test name), the other is how to refer to a single test.

Not sure what about it "looks really strange" or "very inconsistent". Can you elaborate?

> Sorry, it doesn't look obvious or logical for people who are not experts (meaning myself, of course :) .

For what it's worth, I've been teaching this to beginners for dozens of times (I teach pytest to companies as a living, as well as at Python conferences), and in my experience, this hasn't really been a problem. Happy to see if there's something that can be clearer in the documentation if you can be more specific, though.

**Comment by ynikitenko** [comment]
>  "very inconsistent". Can you elaborate?

*-k* allows one to select specific functions in a module. How can one select the function with the same name as the module using *-k*?

Maybe it is not inconsistent, but rather "incomplete". What I find strange, is that I have to use a completely different mechanism to solve this task; I can't see why this should be really necessary. For me as a user it should not.

**Comment by The-Compiler** [comment]
No, `-k` is not selection for that given function. As described by "Only run tests which match the given substring expression." it is a filtering based on a substring. And you cannot, if the filename matches your filter, your filter will select that test.

If you want to select a specific test, then you probably don't want "-k" at all.

**Comment by ynikitenko** [comment]
```

$pytest --help
usage: pytest [options] [file_or_dir] [file_or_dir] [...]

positional arguments:
  file_or_dir

general:
  -k EXPRESSION         Only run tests which match the given substring expression. An expression is a Python evaluatable expression
                        where all names are substring-matched against test names and their parent classes. Example: -k 'test_method or
                        test_other' matches all test functions and classes whose name contains 'test_method' or 'test_other', while -k
                        'not test_method' matches those that don't contain 'test_method' in their names. -k 'not test_method and not
                        test_other' will eliminate the matches. Additionally keywords are matched to classes and functions containing
                        extra names in their 'extra_keyword_matches' set, as well as functions which have names assigned directly to
                        them. The matching is case-insensitive.

```

First of all, I run pytest with a specific file. I absolutely don't need the substrings to match my file name, because I already provide it on the command line!

Second, nothing is written about "file name matching" in this help string. This is logical, because file name is provided through the command line.

Third, why can't there be a substring matching for a function within a file? Like *my_test.my_test*. This looks incomplete.

Yes, you are right that I may use another selection (now that I know it). However, I used *-k* up to this day, and I still see no fundamental reason why it *should not* work with the function matching the name of the file as it works with any other function.

**Comment by The-Compiler** [comment]
> First of all, I run pytest with a specific file. I absolutely don't need the substrings to match my file name, because I already provide it on the command line!

Surely you'll agree that `-k` doing something different based on whether you provide a file name or not would be confusing and inconsistent.
 
> Second, nothing is written about "file name matching" in this help string. This is logical, because file name is provided through the command line.

I disagree, the help string should probably indeed mention that `-k` matches against file names too.
 
> Third, why can't there be a substring matching for a function within a file? Like _my_test.my_test_. This looks incomplete.

There are all kinds of ways how tests could be matched (there also have been discussions about regex/pattern matching). Adding 10 more ways of doing things surely won't help anyone.

> Yes, you are right that I may use another selection (now that I know it). However, I used _-k_ up to this day, and I still see no fundamental reason why it _should not_ work with the function matching the name of the file as it works with any other function.

It does work. It just happens to also match on the test filename, contrary to what you expect.

Maybe it should not take the filename into consideration when matching. But that would be a backwards incompatible change, so I'm not sure if I'd feel comfortable with it.

**Comment by The-Compiler** [comment]
I don't understand the question - what do you mean with "how *-k* works not being a CL option"?

**Comment by ynikitenko** [comment]
> -k doing something different based on whether you provide a file name or not would be confusing and inconsistent.

no, I don't see that. For me, if I provide a file name, means: search only this file name. Otherwise this option (to provide a file name) should be removed.

> Adding 10 more ways of doing things surely won't help anyone.

I agree. It's better to remove the other 9 ways first. UNIX philosophy says: do one thing and do it well. That's why I find it confusing that to get a *slightly* different (and undocumented!) behaviour I need to look for a whole new option.

> Maybe it should not take the filename into consideration when matching. But that would be a backwards incompatible change, so I'm not sure if I'd feel comfortable with it.

Yes, it will be backward incompatible. But do people use that? If yes, how do they actually use that? Anyway, no backwards incompatible changes mean dead non-evolving software.

Python philosophy says that there should be one and (preferably) only one way to do something. If there are different ways to select one function in a file (depending on its name), this looks complicated. Please, take your time to think over it (maybe with colleagues), but what I see now for *-k* could be:

1. skip filename matching if file name is provided on the command line. This is definitely redundant. Or
2. magnify the power of *-k*-matching to allow for *file::function* precise hit, or
3. forbid using *-k* with file names, and, in any case
4. document it somewhere. Preferably in the command line help; but I couldn't find details on *-k* anywhere else anyway.

As I said, in my honest opinion, if I can use an option to pinpoint all functions in my module *except one*, this looks very shady. A bit frustrating user experience. I would avoid that in my code, but it's up to you as a command. In any case thanks for your quick clarifications here and for your program :)

**Comment by ynikitenko** [comment]
Hi,

I just wondered, how was it completed?

Did you fix the problems with your interface?
Have you updated documentation or CL help strings?
Sorry, did not see any linked commits...

Thank you!

Zac Hatfield-Dodds ***@***.***> schrieb am Do., 7. Sept.
2023, 20:22:
