### ISSUE TITLE
Better explain --last-failed-no-failures in docs

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#11354]
As discussed in https://github.com/pytest-dev/pytest/issues/11346#issuecomment-1694335296, the feature could be made clearer in the docs:

https://docs.pytest.org/en/stable/how-to/cache.html#behavior-when-no-tests-failed-in-the-last-run

**Comment by seanjedi** [comment]
I can work on this if that is ok

**Comment by seanjedi** [comment]
Made a PR here: https://github.com/pytest-dev/pytest/pull/11357

**Comment by nicoddemus** [comment]
Hi @seanjedi, as I commented in the PR, the idea is to change the documentation, not the command-line help message. Would appreciate if you give this another go!

**Comment by DetachHead** [comment]
why not update both?

**Comment by nicoddemus** [comment]
If we can improve on both certainly!

**Comment by seanjedi** [comment]
@nicoddemus 
As per request from DetachHead, I have updated both and created a PR here: https://github.com/pytest-dev/pytest/pull/11361 
Let me know if I should make any other changes or improvements, or if my update is too lengthy.

**Comment by seanjedi** [comment]
@nicoddemus Thanks for the feedback on the PR. 
I have updated my changes as of this commit: 75e815f6c1dd5705c3a1f6d11b320013775b59e4
Feel free to let me know if you have any concerns or changes that I should make.

**Comment by nicoddemus** [comment]
@seanjedi thanks for the heads up, but there's no need for that, GitHub already notifies me of your new commits to the PR. 😁

**Comment by seanjedi** [comment]
Ohh whoops lol, thanks for letting me know!

**Comment by nicoddemus** [comment]
Sure thing!
