### ISSUE TITLE
pytest_collection_modifyitems returns all tests

### ISSUE THREAD

**Issue by allankilpatrick** [pytest-dev/pytest#1135]
Given I have a suite with 5 tests
and I run: py.test -k test_foo  ( this only matches one test )

When I hit pytest_collection_modifyitems hook
len(items) returns 5

Should len(items) not return 1 ?

**Comment by RonnyPfannschmidt** [comment]
marker selectors are implemeted using that hook,

so if yours gets excecuted first, it wont see the change

you can use the hokwrapper or the depreccated `__multicall__` mechanism to deal with surrounding the rest of the hook invoations to see how len(items) is changed while the modifyitems hook executes

**Comment by allankilpatrick** [comment]
@RonnyPfannschmidt  thanks

For anyone interested in getting the items that only meet the criteria when using -k:

```python
@pytest.hookimpl(trylast=True)
def pytest_collection_modifyitems(session, config, items):
    self.foo_selected_items(items)
```

**Comment by The-Compiler** [comment]
@allankilpatrick huh? There's no `self`, and I have no idea what `foo_selected_items` would be :wink:

**Comment by allankilpatrick** [comment]
@The-Compiler better?

**Comment by The-Compiler** [comment]
Oh- I thought the part inside of the function was relevant and didn't focus on the `trylast=True` - sorry!

(I clearly need more coffee :coffee: :wink:)
