### ISSUE TITLE
[suggestion] Change the description of "status: easy" Label in CONTRIBUTING.rst.

### ISSUE THREAD

**Issue by kamiya-s-max** [pytest-dev/pytest#11363]
The [Fix Bugs](https://github.com/pytest-dev/pytest/blob/main/CONTRIBUTING.rst#fix-bugs) section in CONTRIBUTING.rst says the following, but I don't see the "status: easy" Label in the current issue.(I could find "good first issue".)

> Look through the GitHub issues for bugs. See also the "status: easy" issues that are friendly to new contributors.

Does "status: easy" mean the same as "good first issue" Label?

If so, I would suggest replacing "status: easy" in the [Fix Bugs](https://github.com/pytest-dev/pytest/blob/main/CONTRIBUTING.rst#fix-bugs) section with "good first issue".

Sorry for my poor English. thank you.

**Comment by WarrenTheRabbit** [comment]
@Pierre-Sassoulas, did you want to take this issue yourself?
If there are no takers, I would love the opportunity to post this issue out to my LinkedIn network.
I'm connected to a lot of junior devs and maybe one of them would love the opportunity to tackle a *good first issue* and get involved.

**Comment by Pierre-Sassoulas** [comment]
No I just labelled, you can absolutely broadcast it on LinkedIn :)

**Comment by The-Compiler** [comment]
Before you do so: Maybe @kamiya-s-max planned to open a PR for this though?

**Comment by kamiya-s-max** [comment]
I think it is a very good idea.
Please post this issue on LinkedIn!

@The-Compiler 
Thank you for your concern!

**Comment by WarrenTheRabbit** [comment]
> **The-Compiler**: Before you do so: Maybe @kamiya-s-max planned to open a PR for this though?

I'm grateful that @The-Compiler knew what was going on, @kamiya-s-max, because I never would have wanted to skip over you. You should absolutely have the opportunity to do the PR if you want.

> **kamiya-s-max**: I think it is a very good idea :)
Please post this issue on LinkedIn!

I'm glad you think so! Thank you. =) I'll post the issue and see if anyone is interested.

**Comment by WarrenTheRabbit** [comment]
An update. 😊 

I created a LinkedIn [post](https://www.linkedin.com/posts/warrenmarkham_suggestion-change-the-description-of-status-activity-7102427510952361984-69kL?utm_source=share&utm_medium=member_desktop), and *bsour* followed the post up by submitting the PR: [Update CONTRIBUTING.rst #11368 ](https://github.com/pytest-dev/pytest/pull/11368)

**Comment by SanderBeekhuis** [comment]
@WarrenTheRabbit would it then be the correct course of action to close this issue?  I see said PR has been merged.

**Comment by WarrenTheRabbit** [comment]
@SanderBeekhuis I think so yes.

**Comment by The-Compiler** [comment]
Yep! Thanks @WarrenTheRabbit and @bsour!

**Comment by SanderBeekhuis** [comment]
I think this issue can then be closed :)
