### ISSUE TITLE
pytest won't run root conftest.py's pytest_configure in special circumstances

### ISSUE THREAD

**Issue by Redoubts** [pytest-dev/pytest#11365]
Consider the following project: https://github.com/Redoubts/_pytest_bug_report

There's a root level conftest.py, and 3 plugins (two loaded in the conftest, and a third loaded by plugin 2). All define a `pytest_configure` in some way.

with `platform darwin -- Python 3.11.4, pytest-7.4.0, pluggy-1.0.0`, we see

```
% pytest test1.py
mypackage.plugin2 Configured
mypackage.plugin3 Configured
conftest Configured
mypackage.plugin Configured
```

Which is somewhat expected, each `pytest_configure` gets called.

If you update pluggy to 1.2+, you see

```
% pytest test1.py           
mypackage.plugin2 Configured
mypackage.plugin3 Configured
mypackage.plugin Configured
mypackage.plugin3 Configured
============================================================================================ test session starts =============================================================================================
platform darwin -- Python 3.11.4, pytest-7.4.0, pluggy-1.2.0
...
```

Where the third plugin's `pytest_configure` is called twice, but the root `pytest_configure` is never called.

I think this is more specifically due to `mypackage/plugin3.py`'s `@pytest.hookimpl` wrapper. Maybe it's ill advised to do that, but I found this bizarre scenario when testing package updates in a much larger codebase.

**Comment by RonnyPfannschmidt** [comment]
This looks like a bug on the pluggy/pytest side

**Comment by Redoubts** [comment]
solved in pluggy
