### ISSUE TITLE
using pytest 2.8.1, pytest cannot find test function using this syntax:  "py.test test_mod.py::test_func"

### ISSUE THREAD

**Issue by Dowwie** [pytest-dev/pytest#1138]
I have a test function that is @pytest.mark.parametrize 'd .  This test function isn't found by pytest when I explictily try to test it from a directory above.

from this directory https://github.com/YosaiProject/yosai/tree/master/test
I run:  
```python
py.test authz/test_authz.py::test_mra_has_all_roles
```

this fails

**Comment by The-Compiler** [comment]
Arguments to `py.test` are filenames, so this won't work - you probably want `py.test -k test_mra_has_all_roles authz/test_authz.py`.

**Comment by Dowwie** [comment]
indeed.  thanks :)
