### ISSUE TITLE
Keyword selection expressions are limited to python syntax, which excludes some nodeids

### ISSUE THREAD

**Issue by jaysw** [pytest-dev/pytest#1141]
Hi there. 

py.test is fantastic! 

I'm wondering if the following is an error, or, expected behaviour:

With the following:

``` python
@pytest.mark.parametrize('p', ['spam eggs', 'ham'])
def test_me(p):
    assert 1 == 1
```

This works fine:

``` bash
py.test -k 'test_me[ham]'
```

While the following triggers an internal error / syntax error:

``` bash
py.test -k 'test_me[spam eggs]'
```

Looks like condition here:

https://github.com/pytest-dev/pytest/blob/master/_pytest/mark.py#L154

prevents any matching on parameters having spaces in them (and falls through to an eval() call).

**Comment by RonnyPfannschmidt** [comment]
The current mark keyword evaluator uses python syntax,
There is a plan to create a more free evaluator, but its much work and not a priority

**Comment by jaysw** [comment]
So, in the above example, is there a way to select and run just the test, "test_me[spam eggs]" ?

**Comment by RonnyPfannschmidt** [comment]
The exact test can be selected by nodeid just use `py.test $nodeid`

**Comment by RonnyPfannschmidt** [comment]
We don't have a replacement lined up yet
