### ISSUE TITLE
Add flask_fixture to the list of plugins

### ISSUE THREAD

**Issue by pomponchik** [pytest-dev/pytest#11435]
Hello!

I wrote a [plugin](https://github.com/pomponchik/flask_fixture) for Pytest that allows you to automatically start and stop a Flask server. I suggest adding this plugin to the [list of plugins](https://docs.pytest.org/en/7.1.x/reference/plugin_list.html).

I know that in order for my plugin to automatically appear in the list, it would have to be named differently. However, I don't like all the possible names suitable for automatic inclusion in the list. For example, the name "pytest-flask-fixture" seems to me ugly and too long. Therefore, I suggest adding your plugin to the list manually.

**Comment by nicoddemus** [comment]
Hi @pomponchik,

The manual list is maintained here: https://github.com/pytest-dev/pytest/blob/fcb8e73288ba0f3ed88524a1c95413b4cd0efd0c/scripts/update-plugin-list.py#L57

Would you like to open a PR adding your plugin to it?

**Comment by pomponchik** [comment]
@nicoddemus, I've done it

**Comment by nicoddemus** [comment]
Thanks!
