### ISSUE TITLE
Two function scope fixtures are run in reverse order.

### ISSUE THREAD

**Issue by cmdulek98** [pytest-dev/pytest#11441]
Hi, i have such a problem, i have a fixture called appclient which is session scope, it's body looks like this:
@pytest.fixture(scope='session')
def appclient():
   yield SomeClass()

then i have two fixtures to cleanup after test, cleanup_1 and cleanup_2, both are set 'function' scope and both inherit from appclient fixture and have body like:
@pytest.fixture(scope='function')
def cleanup_1(appclient):
   yield
   <cleanup stuff...>

i import them all to test function(i do not use conftest for this fixtures as i am having too many there) and use them like:
def test_1(appclient, cleanup_1, cleanup_2), my problem is that cleanup_2 is always done before cleanup_1 and i can't understand why? Only when i set cleanup_2 scope to module, it started to work.

pip_list:
allure-pytest           2.12.0.1
allure-python-commons   2.12.0.1
ansible                 7.1.0
ansible-core            2.14.10
anyio                   4.0.0
appdirs                 1.4.4
astroid                 2.15.6
attrs                   23.1.0
bcrypt                  4.0.1
black                   23.9.1
Cerberus                1.3.4
certifi                 2023.7.22
cffi                    1.15.1
cfgv                    3.4.0
charset-normalizer      3.0.1
click                   8.1.7
cobs                    1.2.0
contourpy               1.1.0
cryptography            39.0.0
cycler                  0.11.0
decorator               5.1.1
dill                    0.3.7
distlib                 0.3.7
dpkt                    1.9.8
exceptiongroup          1.1.3
Faker                   19.6.1
filelock                3.9.0
flake8                  6.1.0
fonttools               4.42.1
future                  0.18.3
greenlet                2.0.2
grpcio                  1.58.0
grpcio-tools            1.58.0
h11                     0.14.0
httpcore                0.17.3
httpx                   0.24.1
identify                2.5.28
idna                    3.4
importlib-resources     6.0.1
iniconfig               2.0.0
iso8601                 2.0.0
isort                   5.12.0
Jinja2                  3.1.2
junit2html              30.1.3
junitparser             2.8.0
kiwisolver              1.4.5
lazy-object-proxy       1.9.0
lxml                    4.9.2
Managenode              2.1.2
MarkupSafe              2.1.3
marshmallow             2.21.0
matplotlib              3.7.3
mccabe                  0.7.0
mcs-utilities           14.2.7
multi-key-dict          2.0.3
mypy-extensions         1.0.0
nemrest                 17.1.2
netaddr                 0.8.0
netifaces               0.11.0
nodeenv                 1.8.0
numpy                   1.25.2
omniORB                 4.3.0.1
ovirt-engine-sdk-python 4.4.1
packaging               23.0
pandas                  2.1.0
paramiko                3.0.0
pathspec                0.11.2
pbr                     5.11.1
pexpect                 4.8.0
pika                    1.3.1
Pillow                  10.0.0
pip                     23.2.1
platformdirs            3.10.0
playwright              1.35.0
pluggy                  1.0.0
ply                     3.11
polling2                0.5.0
portalocker             2.7.0
pre-commit              3.4.0
protobuf                4.24.3
psycopg2-binary         2.9.5
ptyprocess              0.7.0
py                      1.11.0
pyasn1                  0.4.8
pycodestyle             2.11.0
pycparser               2.21
pycryptodomex           3.18.0
pycurl                  7.45.2
pydocstyle              6.3.0
pyee                    9.0.4
pyflakes                3.1.0
pylint                  2.17.5
pylint-pytest           1.1.2
pyllow                  1.4.1
PyNaCl                  1.5.0
pyparsing               3.0.9
pyrad                   2.4
pyroute2                0.7.9
pyshark                 0.6
pysmi                   0.3.4
pysnmp                  4.4.12
pytest                  7.4.2
pytest-base-url         2.0.0
pytest-playwright       0.3.2
pytest-sugar            0.9.6
pytest-testconfig       0.2.0
python-dateutil         2.8.2
python-jenkins          1.7.0
python-ostinato         1.1
python-slugify          6.1.2
pytz                    2022.1
PyYAML                  6.0
requests                2.28.2
requests-toolbelt       0.10.1
resolvelib              0.8.1
retry                   0.9.2
scapy                   2.5.0
serial                  0.0.97
setuptools              50.3.2
six                     1.16.0
sniffio                 1.3.0
snowballstemmer         2.2.0
sseclient-py            1.7.2
termcolor               2.2.0
text-unidecode          1.3
toml                    0.10.2
tomli                   2.0.1
tomlkit                 0.12.1
typing_extensions       4.7.1
tzdata                  2023.3
urllib3                 1.26.14
urlpath                 1.2.0
virtualenv              20.21.1
wrapt                   1.15.0
XlsxWriter              3.1.3
xmltodict               0.13.0
yamlable                1.1.1
yamllint                1.29.0
zipp                    3.16.2

i have pytest 7.4.2
OS:
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"

![image](https://github.com/pytest-dev/pytest/assets/63788600/3eef3979-4bc3-47f7-bc99-d0e3816ea652)

**Comment by RonnyPfannschmidt** [comment]
This is expected behavior, teardown is in reverse order of setup, if your fixtures are dependents this needs to be expressed

**Comment by cmdulek98** [comment]
But i don't want to use them for setup, i thought that if i have
`
def fixture():
   yield
  <do_something>
`, then it will be only used for teardown
