### ISSUE TITLE
Parametrized test with special node ids is not selectable individually using `-k`

### ISSUE THREAD

**Issue by rdbisme** [pytest-dev/pytest#11440]
pytest version 7.4.2.
Windows 10 on MSYS2

I have a test id like this `test_promote[with_state-spec_toml0-pnl_data__expected0-state::must remove-now3-2022-04-18 20:20:00+00:0001]`. 

I'd like to select the test when running:

`pytest -k 'test_promote[with_state-spec_toml0-pnl_data__expected0-state::must remove-now3-2022-04-18 20:20:00+00:0001]'`

Got: 
`
Wrong expression passed to '-k': test_promote[with_state-spec_toml0-pnl_data__expected0-state::must remove-now3-2022-04-18 20:20:00+00:0001]: at column 68: expected end of input; got identifier
`

Tried also 
`pytest -k 'test_promote[with_state-spec_toml0-pnl_data__expected0-state::must\ remove-now3-2022-04-18 20:20:00+00:0001]'`

And now for some reason is replacing `:` with `;`?

`ERROR: Wrong expression passed to '-k': test_promote[with_state-spec_toml0-pnl_data__expected0-state;must\ remove-now3-2022-04-18 20;20;00+00;0001]: at column 61: unexpected character ";"`

- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
The recommended mechanism is passing the full node is

Keyword expressions Match substrings and cannot express full node ids

**Comment by rdbisme** [comment]
> The recommended mechanism is passing the full node
> 
> Keyword expressions Match substrings and cannot express full node ids

Ok, thanks.  

How do I retrieve the full node id? Isn't what's printed by pytest? `with_state-spec_toml0-pnl_data__expected0-state::must remove-now3-2022-04-18 20:20:00+00:0001`?

**Comment by rdbisme** [comment]
Thanks! 

I have one of the parameters that has the `::` syntax in its name that I think it's making this difficult `state:: must remove`. Can you please help me writing down the pytest invocation using full node?

**Comment by rdbisme** [comment]
Ok this works: 
`pytest 'tests\cli\strat\test_promote.py::test_promote[with_state-spec_toml0-pnl_data__expected0-state::must remove-now3-2022-04-18 20:20:00+00:00]'`

**Comment by rdbisme** [comment]
(also for some reason this only works on Powershell. On MSYS, `:` are being replaced by `;`.

**Comment by rdbisme** [comment]
And this is why: https://www.msys2.org/docs/filesystem-paths/#environment_variables

Need to use `MSYS2_ENV_CONV_EXCL` to disallow that.

**Comment by rdbisme** [comment]
And this is why: https://www.msys2.org/docs/filesystem-paths/#process_arguments

Need to use MSYS2_ARG_CONV_EXC to disallow that.
