### ISSUE TITLE
Add `FutureWarning` to `deprecated_call()`

### ISSUE THREAD

**Issue by chrimaho** [pytest-dev/pytest#11447]
#### What's the problem this feature will solve?

When implementing deprecated features, we are regularly expected to use the [`DeprecationWarning`][DeprecationWarning] and [`PendingDeprecationWarning`][PendingDeprecationWarning] warnings. However, there is another one: [`FutureWarning`][FutureWarning]. This particular warning is used by packages such as [`pydeprecate`][pydeprecate] as the default warning for any functions that will be removed in the future.

However, when I write a function that raises the [`FutureWarning`][FutureWarning] (or use the [`@deprecated`][pydeprecate] decorator), then [`deprecated_call()`][deprecated_call] currently does not catch the test successfully.

#### Describe the solution you'd like

I'd like to add [`FutureWarning`][FutureWarning] to the list of warnings which are captured by [`deprecated_call()`][deprecated_call].

This is the current behaviour:

```py
from warnings import warn
from pytest import deprecated_call

def deprecated_func():
    warn("This function is deprecated", DeprecationWarning)
    pass

def future_deprecation_func():
    warn("This function will be deprecated in the future", FutureWarning)
    pass

def test_deprecated():
    """Expected to pass"""
    with deprecated_call():
        deprecated_func()

def test_futures():
    """Expected to fail"""
    with deprecated_call():
        future_deprecation_func()
```

The expected behaviour would be for both of these two test cases to pass successfully.

#### Alternative Solutions

N/A

#### Additional context

N/A

[DeprecationWarning]: https://docs.python.org/3/library/exceptions.html#DeprecationWarning
[PendingDeprecationWarning]: https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning
[FutureWarning]: https://docs.python.org/3/library/exceptions.html#FutureWarning
[pydeprecate]: https://borda.github.io/pyDeprecate/
[deprecated_call]: https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.deprecated_call

**Comment by RonnyPfannschmidt** [comment]
Closing as invalid, pydeprecate doesn't use warnings

As far as I'm concerned it's completely broken

**Comment by The-Compiler** [comment]
@RonnyPfannschmidt ...huh? It [sure does](https://github.com/Borda/pyDeprecate/blob/main/src/deprecate/deprecation.py#L27C1-L27C20), and given the [Python docs](https://docs.python.org/3/library/exceptions.html#FutureWarning):

> Base class for warnings **about deprecated features** when those warnings are intended for end users of applications that are written in Python.

(emphasis mine), it seems perfectly reasonable to me to have `pytest.deprecated_call()` include that?

**Comment by RonnyPfannschmidt** [comment]
i missed that alias

i think i need to get updated on what futurewarnings mean these days
 as i have commonly seem them used for marking experimental code that may see changes in future (aka marking new features as experimental as opposed to 
 
 i indeed missed the alias to warn(category=...) when reading the code of the library
