### ISSUE TITLE
Setting a fixture scope of "package" is not working 

### ISSUE THREAD

**Issue by YTChiu** [pytest-dev/pytest#11458]
> Structure

my_tests/
    └── my_package/
             ├── __init__.py
             ├──  test_module1.py
             └── test_module2.py
    ├── __init__.py
    ├── test_module3.py
  

>  File1: my_package/test_module1.py
  
```ruby

  import pytest


@pytest.fixture(scope="package")
def mockone():
    config = "This is test method."
    print("This is test method.", end =" ")
    return config
    
    
def test_methodA(mockone):
    print("This is method A.")
    assert mockone == "This is test method."
    
def test_methodB(mockone):
    print("This is method B.")
    assert mockone == "This is test method." `
```

>  File2: my_package/test_module2.py

```ruby
import pytest

def test_methodC(mockone):
    print("This is method C.")
    assert mockone == "This is test method."
    
def test_methodD(mockone):
    print("This is method D.")
    assert mockone == "This is test method."

```

>  File3: my_tests/test_module3py

```ruby
import pytest

def test_methodE(mockone):
    print("This is method E.")
    assert mockone == "This is test method."
    
def test_methodF(mockone):
    print("This is method F.")
    assert mockone == "This is test method."
```

> Result as below: The package scope fixture fails to run in different modules in the same package(which is my_package). As you can 
see, there are two ERRORs for the file my_package/test_module2.py, and that should be PASSED. Besides, I know that it is normal that there are errors when users run test_module3 file not under my_package folder, especially when its functions are applied by the package fixture in the different package . 

```
=============================================================test session starts=============================================================
platform win32 -- Python 3.11.4, pytest-7.4.0, pluggy-1.2.0 -- C:\Users\jennifer.c\AppData\Local\Programs\Python\Python311\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\jennifer.c\Desktop\my_tests
collected 6 items                                                                                                                                   

test_module3.py::test_methodE ERROR
test_module3.py::test_methodF ERROR
my_package/test_module1.py::test_methodA This is test method. This is method A.
PASSED
my_package/test_module1.py::test_methodB This is method B.
PASSED
my_package/test_module2.py::test_methodC ERROR
my_package/test_module2.py::test_methodD ERROR
============================================================= ERRORS =============================================================
____________________________________________________ ERROR at setup of test_methodE____________________________________________________
file C:\Users\jennifer.c\Desktop\my_tests\test_module3.py, line 3
  def test_methodE(mockone):
E       fixture 'mockone' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, 
record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\jennifer.c\Desktop\my_tests\test_module3.py:3
____________________________________________________ ERROR at setup of test_methodF____________________________________________________
file C:\Users\jennifer.c\Desktop\my_tests\test_module3.py, line 7
  def test_methodF(mockone):
E       fixture 'mockone' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, 
record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\jennifer.c\Desktop\my_tests\test_module3.py:7
____________________________________________________ERROR at setup of test_methodC ____________________________________________________
file C:\Users\jennifer.c\Desktop\my_tests\my_package\test_module2.py, line 3
  def test_methodC(mockone):
E       fixture 'mockone' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, 
record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\jennifer.c\Desktop\my_tests\my_package\test_module2.py:3
____________________________________________________ERROR at setup of test_methodD____________________________________________________
file C:\Users\jennifer.c\Desktop\my_tests\my_package\test_module2.py, line 7
  def test_methodD(mockone):
E       fixture 'mockone' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, 
record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

C:\Users\jennifer.c\Desktop\my_tests\my_package\test_module2.py:7
============================================================= short test summary info =============================================================
ERROR test_module3.py::test_methodE
ERROR test_module3.py::test_methodF
ERROR my_package/test_module2.py::test_methodC
ERROR my_package/test_module2.py::test_methodD
=============================================================2 passed, 4 errors in 0.02s =============================================================
```

Module: The scope module runs the fixture per module, which means the fixture setting module scope can be reused in a module(.py file).
Package: The scope package runs the fixture per package, which means the fixture seeting module scope can be reused in multiple modules (.py files) in the same package.  

Please help check whether the scope package does not work or my understanding is incorrect?

**Comment by The-Compiler** [comment]
> Please help check whether the scope package does not work or my understanding is incorrect?

It's the latter. The `scope` argument only influences the *caching* scope of the fixture, it doesn't change the visibility. As explained in [Fixture availability](https://docs.pytest.org/en/7.4.x/reference/fixtures.html#fixture-availability), if you define a fixture in a Python module, it will only be available in that module.

You will want to declare it in a [`conftest.py` file](https://docs.pytest.org/en/7.4.x/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files) instead.

Also see the [documentation for `scope=`](https://docs.pytest.org/en/7.4.x/how-to/fixtures.html#scope-sharing-fixtures-across-classes-modules-packages-or-session) for more details how/where it's used.

**Comment by YTChiu** [comment]
Could explain why the scope of fixture is package in A file but the value of  fixture argument fails to send to function of B file in the same folder?

**Comment by The-Compiler** [comment]
I'm not sure if I understand the question ("fails to send to function"?). I can't really say much more than what I already said above: `scope` is about caching scope only.

**Comment by YTChiu** [comment]
Hi@The-Compiler. 
Let me take another simple example as below.  
> structure
my_tests/
      ├── init.py
      ├── test_module1.py
      └── test_module2.py

I understood that ` scope is about caching scope only.` 
Please check the picture below. The test_function3 in test_module2.py fail to get the caching value of package scope fixture "package_level_fixture" in  test_module1.py.
![image](https://github.com/pytest-dev/pytest/assets/49123244/5559e343-d327-4858-91c2-3b6561777a8e)

**Comment by The-Compiler** [comment]
We're going in circles here. Quoting from the docs I already linked:

> Fixture availability is determined from the perspective of the test. A fixture is only available for tests to request if they are in the scope that fixture is defined in. If a fixture is defined inside a class, it can only be requested by tests inside that class. But if a fixture is defined inside the global scope of the module, than every test in that module, even if it’s defined inside a class, can request it.

If you define a fixture in a test file, it's only visible in that file. Setting a different caching scope isn't going to change anything about that.

**Comment by YTChiu** [comment]
@The-Compiler 
So you mean the value of package scope fixture could be not delivered to another file in the same directory as argument?
It seems to me that function of package scope fixture is like global scope across file like conftest.py.

**Comment by The-Compiler** [comment]
No. All you do by setting the caching scope is telling pytest to reuse the fixture's return value across all tests in the same package.

No matter if you do `@pytest.fixture` or `@pytest.fixture(scope="package")` (or `scope="session"`, or whatever), a fixture you define in a `test_*.py` file will only be available in that file.

**Comment by YTChiu** [comment]
@The-Compiler 
System: Windows 11
Python Version: 3.11.4
IDE: VSCode

Replictated Steps: 

1. Create a directory called my_tests
2. Create two files - test_module1.py and test_module2.py
3. Copy and paste the following code to the correspoding file. 

test_module1
```ruby
# test_module1.py

import pytest

#set a fixture and use scope='package'
@pytest.fixture(scope='package')
def package_level_fixture():
    value = 1000
    return value

def test_function1(package_level_fixture):
    print(package_level_fixture, end=" ")
    print("This test function 1.",  end = " ")

def test_function2(package_level_fixture):
    print(package_level_fixture, end=" ")
    print("This test function 1.",  end = " ")
```

test_module2
```ruby
import pytest


def test_function3(package_level_fixture):
    print(package_level_fixture, end=" ")
    print("This test function 3",  end = " ")
```

4. Save the changes in VSCode
5. Run the command ` pytest -s -v`  under the directory "my test/" in terminal

**Comment by YTChiu** [comment]
@The-Compiler 
Please help look into it! I would much appreciate it.  🙏🙏🙏

**Comment by RonnyPfannschmidt** [comment]
@YTChiu he already explained that you need to move the fixture to a conftest

**Comment by YTChiu** [comment]
@RonnyPfannschmidt 
Okay, I see.
