### ISSUE TITLE
Pytest with filterwarnings hangs on uvloop ResourceWarning

### ISSUE THREAD

**Issue by Olegt0rr** [pytest-dev/pytest#11454]
### 1. Enable filterwarnings mode

```toml
[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
    "error",
]
```

### 2. Create Redis client fixture

```python
import pytest
from redis.asyncio import Redis


@pytest.fixture(name="redis")
async def redis_fixture():
    redis = Redis.from_url("redis://localhost")
    try:
        yield redis
    finally:
        await redis.close()

```

### 3. Create simple test

```python
async def test_foo(redis):
    await redis.ping()
```

### 4. Install uvloop

Add this to your `conftest.py`

```
import uvloop

uvloop.install()
```

### 5. Run tests

I hope you know how to do it ;)

## Expected result

Since `Redis` has unclear behaviour of `redis.close()` method and it doesn't close connection pool, our tests should be failed with `ResourceWarning` about `unclosed TCPTransport`

## Actual result

Test passed and hanged with infinity loading: 

<img width="523" alt="Screenshot 2023-09-23 at 09 11 20" src="https://github.com/pytest-dev/pytest/assets/25399456/6e4ebc64-48d4-477c-8ac0-61d269857aa0">

#### P.S.

Only `terminate` + `re-run with debug mode` helps to understand what's going on:
<img width="983" alt="Screenshot 2023-09-23 at 09 16 20" src="https://github.com/pytest-dev/pytest/assets/25399456/ed9dbcf0-ae68-42af-a643-5d9d8e906b2c">

**Comment by gbarter** [comment]
It has taken me a while to debug, but I think I may be experiencing the same.

**Comment by Olegt0rr** [comment]
caused by uvloop
<img width="699" alt="Screenshot 2023-09-22 at 23 08 52" src="https://github.com/pytest-dev/pytest/assets/25399456/77450fb7-0553-43ff-8483-64070f5b1a8b">

**Comment by Zac-HD** [comment]
I get a different error:

```python-traceback
______________________________________________ test_foo ______________________________________________
Traceback (most recent call last):
  File "repro.py", line 19, in test_foo
    await redis.ping()
AttributeError: 'async_generator' object has no attribute 'ping'
```

More generally, I'm not sure that this is actually a pytest issue.  Can you show a minimal reproducing example, where calling your test function with and without `-Werror` works _without_ pytest, but fails with pytest?

**Comment by Olegt0rr** [comment]
I forget to copy `asyncio_mode = "auto"` to `ini_options`, it seems async fixture is not detected as a fixture.

Okay, I'll make an example
