### ISSUE TITLE
addoption "--run" behaviour is inconsistent.

### ISSUE THREAD

**Issue by EvanTheB** [pytest-dev/pytest#1146]
I created an option with `parser.addoption("--run")`
Using this option worked find with the command line 
`py.test --run argument`
However using the alternative syntax
`py.test --run=argument`
Caused the failure `py.test: error: argument --runxfail: ignored explicit argument 'abc'`. I assume that the option matching is using prefixes. I think the behaviour of runxfail being triggered by --run is fine, however the behaviour should be consistent between the two ways of specifying command line options.

**Comment by RonnyPfannschmidt** [comment]
this seems to be a `argparse` bug known since 2013

**Comment by The-Compiler** [comment]
What's the argparse bug? Looks fine in a quick test to me:

```
>>> import argparse
>>> p = argparse.ArgumentParser()
>>> p.add_argument('--run', nargs=1)
>>> p.add_argument('--runxfail')
>>> p.parse_args(['--run=foo'])
Namespace(run=['foo'], runxfail=None)
>>> p.parse_args(['--run', 'foo'])
Namespace(run=['foo'], runxfail=None)
```

(also, I disagree this should be marked critical)

**Comment by RonnyPfannschmidt** [comment]
https://docs.python.org/2/library/argparse.html#partial-parsing

so in `preparse` we already kow `runxfail` but not `run`, thus runxfail is matched

**Comment by nicoddemus** [comment]
Closing this in favor of #1149
