### ISSUE TITLE
Add an exit code to differentiate full-passed tests from xpassed & xfailed tests executions

### ISSUE THREAD

**Issue by harmin-parra** [pytest-dev/pytest#11463]
#### What's the problem this feature will solve?

In the case of no test failures, I would like to differentiate executions with 100% passed tests from those with at least one xpassed or xfailed test.

#### Describe the solution you'd like

If the execution has
`failed tests = 0 and (xfailed tests > 0 or xpassed tests > 0)`
I want the test execution to return a different exit code (example: `ExitCode.TESTS_XFAILED = 6`)

#### Alternative Solutions

Implement `pytest_runtest_makereport` hook to detect xpassed and xfailed tests
Implement `pytest_sessionfinish` hook to override exit status

#### Additional context

Useful when executing pytest from a CI tool (like jenkins) and set job execution status to `unstable` if `failed tests = 0 and (xfailed tests > 0 or xpassed tests > 0)`

**Comment by The-Compiler** [comment]
-1 on doing this by default. If your CI system isn't explicitly prepared for this, it means that the pytest execution would fail, which doesn't seem like a good default for having an xfailing test. The whole point of xfail is that you expected the failure.

**Comment by RonnyPfannschmidt** [comment]
Originally xpass was considered failure, it was at some point weakend for flaky test suites 

I'm inclined to get back to that as there's now plugins for correct handling of that

**Comment by harmin-parra** [comment]
@The-Compiler Precisely one of the reasons of using xfail is because you are aware of an instability of the software under test.
It is highly desirable for a job Jenkins to be able to reflect such predicted `unstable` state.

@RonnyPfannschmidt  I am happy with the current test status (passed, fail, xfail, xpassed)
They all have a different meaning
It is very easy to add several exit codes.
I don't see the logic or reducing them

The develop even further my idea:

We could consider a different exit code when (`xfailed > 0 and xpassed == 0`) to indicate that the software is in an expected `unstable` state.

And another exit code when (`xfailed == 0 and xpassed > 0`) to indicate that, _potentially_, the software is no longer in an `unstable` state, and force the tester to check out the reason of the unexpected passed tests

**Comment by RonnyPfannschmidt** [comment]
Xfail was always the wrong tool for unstable tests

It was a mistake to shoehorn xfail into being useful for unstable tests by making xpass non failure

**Comment by The-Compiler** [comment]
See https://github.com/pytest-dev/pytest/issues/7233#issuecomment-631613486 for some more background regarding `xfail_strict`.

The predominant usage of xfail is not dealing with flaky tests, but e.g. keeping a test around which is broken due to an upstream bug. The flaky tests usecase is a very exotic one (and indeed not the intended one) - there are better solutions for that, e.g. [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures).

A change which breaks xfail for its intended purpose seems unacceptable to me - and given that I'm not the only core developer with that stance, taking the freedom to close this.

**Comment by RonnyPfannschmidt** [comment]
I opened #11467 to restore xpass as failure by default
