### ISSUE TITLE
Overwrite and add custom tag to junit report

### ISSUE THREAD

**Issue by dosas** [pytest-dev/pytest#11470]
#### What's the problem this feature will solve?
In Gtilab CI it is possible to [attach](https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html#view-junit-screenshots-on-gitlab) screenshots/files to the pipeline test report by adding information to the `system-out` tag:

```
<testcase>
  <system-out>[[ATTACHMENT|/path/to/some/file]]</system-out>
</testcase>
``` 

#### Describe the solution you'd like
In order to achieve this the possibility to write a new tag or overwrite an existing tag has to exist.
* Maybe somehow similar to `record_xml_attribute`
* Maybe access to xml report in  `pytest_runtest_makereport`

#### Alternative Solutions
My current workaround is running with `-o junit_logging=system-err` (so [system-out](https://github.com/pytest-dev/pytest/blob/main/src/_pytest/junitxml.py#L176) tag is not written) and trying to hack it into `makereport` hook:

```
def pytest_runtest_makereport(item, call):
        ...
        from _pytest.junitxml import LogXML
        xml = [i for i in item.config.stash._storage.values() if isinstance(i, LogXML)][0]
        node_reporter = xml.node_reporter(item.nodeid)
        node_reporter._write_content("", f"[[ATTACHMENT|{screenshot_path}]]", "system-out")
```

#### Additional context
https://github.com/pytest-dev/pytest/issues/2827 might be related?

**Comment by RonnyPfannschmidt** [comment]
Currently there's no dedicated maintainers for junitxml

As such new features should best be attempted in a new plugin
