### ISSUE TITLE
update contribution documentation to mention the need to fetch tags

### ISSUE THREAD

**Issue by bnomis** [pytest-dev/pytest#11485]
The documentation for running the tests does not mention the need to set `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYTEST`. Without it when I run `tox -e py39` I get an error like:

`ERROR ... pyproject.toml: 'minversion' requires pytest-2.0, actual pytest-0.1.dev15348+gb73b4c4`

Before running `tox` one needs to set a version like:

`export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYTEST=7.4.2`

Then everything works.

Happy to make a PR as required. Thanks.

**Comment by RonnyPfannschmidt** [comment]
It seems like you clone doesn't include tags

The documentation could mention that

I'm under the impression I need to add unreasonably smart GitHub mode to setuptools-scm

**Comment by bnomis** [comment]
I see. Seems like the defaults in GitHub since https://github.blog/changelog/2022-07-27-you-can-now-fork-a-repo-and-copy-only-the-default-branch/

**Comment by RonnyPfannschmidt** [comment]
:facepalm: https://xkcd.com/1172/

**Comment by eleanorjboyd** [comment]
Hi! Running into the same problem here. In my cloned repo I did `git fetch --tags` once I did that and tried rerunning I still got the error but once I set `export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_PYTEST=7.4.2` it worked. Any idea why I might still be seeing this with that step included? Do I need to reclone instead of just fetching?

**Comment by RonnyPfannschmidt** [comment]
Its necessary to fetch tags from upstream 

These days it's common enough that they are missing in personal forks 

I think its time to update both the docs and setuptools-scm for this new future
