### ISSUE TITLE
option to denote tests using a decorator

### ISSUE THREAD

**Issue by DetachHead** [pytest-dev/pytest#11495]
#### What's the problem this feature will solve?
relying on the function name to determine whether or not it's a test is not that reliable, and can lead to regular functions being mistakenly identified as tests (eg. #11494)

#### Describe the solution you'd like
an option to use a decorator to denote tests instead:
##### before
```py
def test_foo():
    ...
```
##### after
```py
from pytest import test

@test
def foo():
    ...
```

#### Alternative Solutions
can probably be achieved with a plugin, but first party support would be nice

**Comment by JuroOravec** [comment]
+1 for this. My reason for coming across this post is that I'm not a big fan of prefixing all tests / test blocks with `test_` / `Test`, etc, because then the test outputs contain a lot of fluff making it harder to read:

Instead of 
```
my_project/lib/__tests__/test_pairwise_matrix.py::describe_pairwise_comparison_matrix::test_computes_matrix`
```

I could have shorter, easier-to-read format:
```
my_project/lib/__tests__/test_pairwise_matrix.py::pairwise_comparison_matrix::computes_matrix
```

**Comment by SongpengLiu** [comment]
I'm working on this feature
