### ISSUE TITLE
Presumably spelling error in _pytest.outcomes: The bash script for starteding

### ISSUE THREAD

**Issue by MartinsEHUB** [pytest-dev/pytest#11497]
- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by nicoddemus** [comment]
@MartinsEHUB can you add a description please? I did search for `starteding` in the codebase but couldn't find any.

**Comment by RonnyPfannschmidt** [comment]
closing as missing details
