### ISSUE TITLE
drop argparse since its broken by design and unfixable

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1149]
relates to #1146 

`argparse` has a prefix-matching mode that will invariably break user code in the `preparse` step unless they pick option names that cannot share a prefix with arguments known in preparse

**Comment by hpk42** [comment]
why do we need to avoid prefix matching, can you give an example? 
And if we need to avoid it, why can we not hack argparse? 

FWIW I don't think we should drop argparse easily.

**Comment by RonnyPfannschmidt** [comment]
Preparse will prefix match on not yet defined plugin/contest options, and it can't be avoided by design, see the linked issue

**Comment by The-Compiler** [comment]
FWIW argparse has `allow_abbrev=False` with Python 3.5 - maybe it's possible to backport this without too much pain? Commit: https://hg.python.org/cpython/rev/99302634d756

**Comment by RonnyPfannschmidt** [comment]
if the only way to correctly work with stdlib modules is to work with backports in some manner, then please lets stop to depend on the stdlib

**Comment by The-Compiler** [comment]
And break every plugin and testsuite using custom arguments? I'd rather not do that, even in a major release :wink:

I think it could be as easy as subclassing and overriding `_get_option_tuples` to always return an empty list, and that'd be it. And I think the risk is manageable as it's only for old Python versions which probably won't change anymore.

(But of course this needs further testing - I only looked at the 3.4 code, and didn't actually try this approach)

**Comment by nicoddemus** [comment]
Just to give an example of the problem @RonnyPfannschmidt mentions, in #2077 the user tried to define an option named `--conf` in a `conftest` file, but argparse will always match `--confcutdir` instead because that's done in the `preparse` stage to obtain the "known_args". 

That's a difficult problem to solve, because we need to pre-parse the argument list to get some options that are important for the discovery of `conftest` files which in turn might register options that match the which were already parsed.

It seems to me the only real solution would be to remove option prefix matching altogether.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus the prefix matching cannot be disabled until python 3.6

**Comment by nicoddemus** [comment]
You mean 3.5 right? Following what @The-Compiler said:

> about FWIW argparse has allow_abbrev=False with Python 3.5 

which [seems to be the case](http://bugs.python.org/issue14910).

Anyway, perhaps we can hack that into our `MyOptionParser` subclass...

**Comment by nicoddemus** [comment]
I mean, we don't need to backport the entire patch, which is more complete because it makes prefix matching optional; we only need to disable it altogether.

**Comment by DuncanBetts** [comment]
It sounds like backporting parts of the patch would resolve this issue in the most backwards compatible way. If you are seeking an alternative to argparse, perhaps [docopt](https://github.com/docopt/docopt) would be a good choice. Thought it was worth a mention anyway :).

**Comment by RonnyPfannschmidt** [comment]
@DuncanBetts docopts it no option at all, since it works completely contrary to any api pytest currently has,
as such its a backward incompatible change we cannot impose

**Comment by blueyed** [comment]
I also think that we should try to keep argparse, but patch it (temporarily) to make it work.
See https://github.com/pytest-dev/pytest/issues/3413#issuecomment-383173711 for some early investigation.

**Comment by Zac-HD** [comment]
Closed by #5469.
