### ISSUE TITLE
Documentation: "Managing pytest’s output" should mention `-q` and `-s`

### ISSUE THREAD

**Issue by bersbersbers** [pytest-dev/pytest#11507]
Looking at https://docs.pytest.org/en/7.1.x/how-to/output.html, I am missing references to command line options `-q` (`--quiet `) and `-s` (`--capture`), which clearly have an influence on `pytest`s output.

**Comment by nicoddemus** [comment]
Agreed, thanks.

Would you like to contribute a PR with that?

**Comment by bersbersbers** [comment]
Not really, since I don't really have a good grasp of how these options actually work in combination. For example, I had expected `-q` to imply `--tb=no`, but that does not seem to be the case.

**Comment by nicoddemus** [comment]
I see, thanks anyway for the report, appreciate it.

**Comment by Ben-Costa** [comment]
@nicoddemus Is a documentation update still needed for this issue? I was looking to make a first contribution and this one seemed like a good place to start.

**Comment by nicoddemus** [comment]
Yes, thanks @Ben-Costa. 👍
