### ISSUE TITLE
Fixture scope seems to be ignored when running full suite

### ISSUE THREAD

**Issue by shonteag** [pytest-dev/pytest#11500]
Hey there, folks!

First and foremost, thanks for the amazing work you all do on the `pytest` module; I use it in every single one of my projects. I'd also like to clarify that this **might** be user error, but I've been experimenting and googling, and I've never seen this happen before (because the fixture is not being imported anywhere, and it still happens when moving the fixture to the `conftest.py` file).

# The Issue

Pytest version: `7.4.2`
<details>
<summary>Pip list</summary>

```
Package                Version   Editable project location
---------------------- --------- -----------------------------------
alembic                1.9.2
aniso8601              9.0.1
astroid                2.13.3
bcrypt                 4.0.1
black                  22.12.0
boto3                  1.28.53
botocore               1.31.53
certifi                2023.7.22
cffi                   1.15.1
charset-normalizer     3.2.0
click                  8.1.3
cryptography           41.0.4
dill                   0.3.6
environs               9.5.0
exceptiongroup         1.1.0
Flask                  2.2.2
Flask-Bcrypt           1.0.1
Flask-Cors             3.0.10
flask-marshmallow      0.14.0
Flask-Migrate          4.0.3
Flask-RESTful          0.3.9
Flask-SQLAlchemy       3.0.3
gunicorn               20.1.0
idna                   3.4
iniconfig              2.0.0
isort                  5.12.0
itsdangerous           2.1.2
Jinja2                 3.1.2
jmespath               1.0.1
lazy-object-proxy      1.9.0
Mako                   1.2.4
MarkupSafe             2.1.2
marshmallow            3.19.0
marshmallow-enum       1.5.1
marshmallow-sqlalchemy 0.28.1
mccabe                 0.7.0
moto                   4.2.4
mypy-extensions        0.4.3
packaging              23.0
pathspec               0.11.0
pip                    22.3.1
platformdirs           2.6.2
pluggy                 1.0.0
psycopg2               2.9.5
pycparser              2.21
PyJWT                  2.6.0
pylint                 2.15.10
pytest                 7.4.2
python-dateutil        2.8.2
python-dotenv          0.21.1
pytz                   2022.7.1
PyYAML                 6.0.1
requests               2.31.0
responses              0.23.3
s3transfer             0.6.2
setuptools             67.0.0
six                    1.16.0
SQLAlchemy             2.0.0
tomli                  2.0.1
tomlkit                0.11.6
types-PyYAML           6.0.12.12
typing_extensions      4.4.0
urllib3                1.26.16
Werkzeug               2.2.2
wheel                  0.38.4
wrapt                  1.14.1
xmltodict              0.13.0
```

</details>

Ok, so it seems the `scope` argument has some.. let's say "unexpected" behavior to it. I have a fixture that needs to run once, *and only once*. If it runs again, the fixture will fail, throwing an error and causing the tests that rely on it to fail as well. All good, there's an option for that, `scope=session`. This fixture is only used in a single module of tests, so it lives there in the same module, and is never accessed outside said module.

Here's the rub:

✅  Running an individual test in said module using `poetry run pytest tests/test_a_thingy.py::one_of_my_tests`
✅  Running the entire module of tests using `poetry run pytest tests/test_a_thingy.py`
❌  Running the entire suite of tests using `poetry run pytest`

On the last execution vector, it looks like every test in the module fails, and the caught exception is raised inside the fixture (due to being run multiple times). I have also tried this with `scope=module`, but to no avail: the same failures occur when running the entire suite.

If I'm missing something, please let me know where to look.

Cheers!

File layout:
```
project/
  ...
tests/
  serializers/
    test_a_thing.py
    ...
  ...
```

`test_a_thing.py` example layout:

```python
import pytest

@pytest.fixture(scope="session")
def only_once():
    # if this is run more than once, it throws an easily identifiable exception
   ...

def test1(only_once):
    ...

def test2(only_once):
   ...

# many more tests in this file, all of which rely on the "only_once" fixture
```

Note: I have also attempted to move the fixture to `conftest.py`, but I arrive at the same error.

**Comment by shonteag** [comment]
So I tried to recreate the error as follows:

```python

import pytest


class Singleton(object):

    def __new__(cls):
        if not hasattr(cls, 'instance'):
            cls.instance = super(Singleton, cls).__new__(cls)
        else:
            raise RuntimeError("singleton called twice")

        return cls.instance



@pytest.fixture(scope="session")
def called_once():
    return Singleton()


def test_singleton1(called_once):
    assert True


def test_singleton2(called_once):
    assert True


def test_singleton3(called_once):
    assert True

```

Oddly, this seems to pass regardless of how it's run. That tells me something very strange is happening in my code that is interfering with the "singleton" nature of the scope. I'll do some additional digging, and post back if I find it. The bit that confused me is the actual tests conditionally pass, as long as they are not run as part of a larger suite of tests 😕

**Comment by shonteag** [comment]
Oh goodness 🤦 . I was already defining a singleton with the same name in another part of the test suite. So, of course, when I ran it alone, all the tests would pass. As so as I ran the suite, the singleton was getting instantiated in another part of the suite first, causing all the tests to fail. Sorry I wasted everyone's time!

**Comment by RonnyPfannschmidt** [comment]
Thanks for the follow-up, Sometimes it's uncanny how trying to make a reproducer makes us see things we'd otherwise miss 10/10
