### ISSUE TITLE
Pass dinamically command line option into a test body

### ISSUE THREAD

**Issue by fontealpina** [pytest-dev/pytest#1150]
Hi, in my use case I need to set dinamically a self attribute of a test class with a command line option, without passing explicitly the parameter to the test definition, with a plugin.
For example:

    # content test.py 
    class TestSuite():
         my_cmd_opt = 'foo'

         def test_case(self):
              assert self.my_cmd_opt != 'foo' # here the test should pass because self.my_cmd_opt
                                              # has been dinamically changed from pytest

so if i run:
     
       $> pytest --set-my-cmd-opt=alpha test.py
       test.py::TestSuite::test_case PASSED
because I've set self.my_cmd_opt to 'alpha' instead of 'foo'
There is a way to do that?

**Comment by nicoddemus** [comment]
Yes, please take a look at [this section](http://pytest.org/latest/example/simple.html?highlight=pytest_addoption) in the docs.

Based on the example, you can now access the option directly instead:

```python
# content test.py 
class TestSuite():

     def test_case(self, my_cmd_opt):
          assert my_cmd_opt != 'foo'
```

But if you really want to set it as an attribute of the class, you can use an autouse-fixture in the class scope:

```python
class TestSuite():
     my_cmd_opt = 'foo'

     @pytest.fixture(autouse=True)
     def setup_getopt(my_cmd_opt):
         self.my_cmd_opt = my_cmd_opt

     def test_case(self):
          assert self.my_cmd_opt != 'foo' 
```

Hope this helps. :beers:

**Comment by fontealpina** [comment]
Thanks! I tried your suggestion but I get an error:
     
         E       NameError: global name 'self' is not defined

Morover I was wondering if instead of use a fixture solution, there is a chance to do that directly from a 
 
          def pytest_runtest_protocol(item):

Setting the attribute my_cmd_opt before the calling of 
        
          reports = runtestprotocol(item)
There is a way to do something like this?

**Comment by nicoddemus** [comment]
> Thanks! I tried your suggestion but I get an error:

Sorry:

```python
     @pytest.fixture(autouse=True)
     def setup_getopt(self, my_cmd_opt):
         self.my_cmd_opt = my_cmd_opt
```

> Morover I was wondering if instead of use a fixture solution, there is a chance to do that directly from 

It is possible, you can access the `config` object using `item.config` in `pytest_runtest_protocol`, but IIMO this is too implicit... I would go with the fixture approach, it is simple and explicit.

**Comment by fontealpina** [comment]
Thanks! but in which of the item sub-object I need to set the attribute so that the test instance can see the command line option?

**Comment by RonnyPfannschmidt** [comment]
The fixture as shown by @nicoddemus is in the object itself, no need to mess around with items

**Comment by RonnyPfannschmidt** [comment]
Closing due to lack of feedback
