### ISSUE TITLE
preconstructed unittest tests don't work

### ISSUE THREAD

**Issue by o11c** [pytest-dev/pytest#1151]
The following code can be used to run tests under `unittest`, but not under `pytest` (version 2.8.2):

```python
import unittest

class Special(unittest.TestCase):
    def __new__(cls, name):
        return getattr(cls, name)

    test_foo = unittest.FunctionTestCase(lambda: None)
```

This results in the following error in `_pytest/unittest.py`
```text
    def setup(self):
        self._testcase = self.parent.obj(self.name)
>       self._obj = getattr(self._testcase, self.name)
E       AttributeError: 'FunctionTestCase' object has no attribute 'test_foo'
```

**Comment by RonnyPfannschmidt** [comment]
As far as I understand from just reading, we shouldn't care since the object factory override is at fault and its not related to preconstructed testcases

**Comment by nicoddemus** [comment]
Should we close this?
