### ISSUE TITLE
Deprecation of datetime.datetime.utcfromtimestamp()

### ISSUE THREAD

**Issue by jaroslaw-majka** [pytest-dev/pytest#11528]
**DeprecationWarning: datetime.datetime.utcfromtimestamp()**
New Python 3.12 version is deprecating `datetime.datetime.utcfromtimestamp()`. When using `pandas` library within the tests conducted by pytest I get the above mentioned warning, which results in an error because of the way my project is setup. I do have a workaround for now, but I believe this should be fixed.

**pip list output and OS**
OS: macOS Ventura 13.5
```
Package         Version
--------------- ------------
iniconfig       2.0.0
numpy           1.26.1
packaging       23.2
pandas          2.1.1
pip             23.2.1
pluggy          1.3.0
pytest          7.4.2
python-dateutil 2.8.2
pytz            2023.3.post1
six             1.16.0
tzdata          2023.3
```

**Minimal sample script that throws the DeprecationWarning**
```
import pandas

def test_sample():
    assert True
```

**Full warning**
```
DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
    EPOCH = datetime.datetime.utcfromtimestamp(0)
```

**Setting responsible for raising DeprecationWarning to Error**
In `pytest.ini`
```
filterwarnings = 
    error:::^((?!<my_package>).)*$.*: ; raise error for all warning, except those coming from my_package
    ignore:datetime.datetime.utcfromtimestamp()*:DeprecationWarning: ; workaround for this particular case
```

**Comment by The-Compiler** [comment]
There is no such line (`EPOCH = datetime.datetime.utcfromtimestamp(0)`) in pytest. The full output should tell you where the warning is coming from - or if not, turning it into an error will give you a traceback.

**Comment by The-Compiler** [comment]
After some quick digging, likely to be:

- #1284

**Comment by graingert** [comment]
remember that the warning is a regular expression so you need to escape the parenthesis:

eg `ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated and scheduled for removal in a future version:DeprecationWarning:dateutil`
