### ISSUE TITLE
[bug] - cannot access class attributes when trigger run test

### ISSUE THREAD

**Issue by PriveSylvain** [pytest-dev/pytest#11522]
I have a class Entity, a second class PhysicalEntity that heritate from Entity but has a class attributes "manipulator", and a third class Molecule. When i trigger Debug Test, performing with a molecule, the step by step, can access the manipulator attribute. But "Run Test" mode cannot.

i'm using a virtual environment on windows. here under the pip freeze (non exhaustive list):

pytest==7.4.2
pytest-cov==4.1.0
pytest-dotenv==0.5.2
pytest-envfiles==0.1.0
pytest-timeout==2.2.0
python-dateutil==2.8.2
python-dotenv==1.0.0

exemple:
self.assertIsInstance(my_entity, Molecule)
my_entity.manipulator

i tried many ways to access this attributes (__dict__, Molecule.manipulator, PhysicalEntity.manipulator ... etc)
the error raised when Run Test : is "Entity has not attribute "manipulator".

in the code, i have different behavior with the two modes and this issue appears to be the cause.
Any suggestion ?
Thks

**Comment by Zac-HD** [comment]
Please provide a [minimal reproducing example](https://stackoverflow.com/help/minimal-reproducible-example).
