### ISSUE TITLE
Improve pytest's `Full diff` by coloring it's output

### ISSUE THREAD

**Issue by BenjaminSchubert** [pytest-dev/pytest#11520]
#### What's the problem this feature will solve?

The `Full diff` that pytest shows in `-vv` mode is very red and hard to read. Missing, common and extra entries all have the same color!

For reference, this is what it looks like:

![image](https://github.com/pytest-dev/pytest/assets/1672192/7c501be3-a746-40c5-8ca9-6aca5e9c0252)

#### Describe the solution you'd like

This diff is the same kind of diff that people might already be familiar with, typically running `git diff`. Those are often colored already. There is a `pygments` lexer for parsing such diffs.

As such, I would propose to enhance the coloring of those diffs when pygments is install, which would give something like:

![image](https://github.com/pytest-dev/pytest/assets/1672192/8825f0e7-2eab-4be5-9033-8702f1d0faa3)

Which I believe is much easier to read and spot differences.

I'd be happy to implement the solution if you would be willing to accept such a change.

This might require passing the terminal writer into the tooling that provides the diff to check whether colors should be enabled however.

**Comment by The-Compiler** [comment]
I think this would be a good thing to have, I'm for more colors and less red in general. IMHO, we also should highlight all the Python data structures in that output as Python code.

**Comment by BenjaminSchubert** [comment]
@The-Compiler thanks for the prompt answer!

Would that be a somewhat accurate description of what you are thinking? (Except the 'glitch' around the starting `{` that's red)

![image](https://github.com/pytest-dev/pytest/assets/1672192/fa84bfb1-a6c4-4867-ba6c-c07994e24981)

If so, I can try to have a go at it. It might require a few refactors on how the pygments stuff works, but I think it's definitely doable, and can go beyond just dicts

**Comment by BenjaminSchubert** [comment]
Technically, we could go even further with

![image](https://github.com/pytest-dev/pytest/assets/1672192/3444cff3-11bb-4f42-97c9-0019e3ed3c83)

However, I think that might be too much and actually less readable?

**Comment by The-Compiler** [comment]
Honestly personally I'm in the "the more colors, the better" camp, but I know there are people with [differing opinions](https://www.linusakesson.net/programming/syntaxhighlighting/).

I agree your last example might be a tad less readable than the previous one, but I feel like that's just because of some missing visual separation. Some additional blank lines before each "section" would help that, IMHO.

**Comment by RonnyPfannschmidt** [comment]
For error printing,the linked article doesn't strictly apply as it's not code one would write

**Comment by BenjaminSchubert** [comment]
https://github.com/pytest-dev/pytest/pull/11530 is the first step around the diff, I will look at adding more colors in other places afterwards, since it would rely on the same constructs as are introduced by this PR, to avoid refactoring too many times.

**Comment by BenjaminSchubert** [comment]
@bluetech I believe all the various points raised here and on the linked PRs are now handled. Should we close this issue or is it worth keeping open a bit longer?

**Comment by bluetech** [comment]
I'll close, thanks again!
