### ISSUE TITLE
bug fix #10447 not included in newer releases

### ISSUE THREAD

**Issue by dset77** [pytest-dev/pytest#11544]
Hi pytest-devs!

My team needs this bug fix,
https://github.com/pytest-dev/pytest/issues/10447
but it is not included in the newer releases after the PR merge (not in any of the release tags), 
so we had to downgrade to pytest<7.2.

Could you tell me when it is going to be released?

**Comment by The-Compiler** [comment]
See https://github.com/pytest-dev/pytest/pull/11155#issuecomment-1773788459

**Comment by nicoddemus** [comment]
7.4.3 released which includes this fix. 👍
