### ISSUE TITLE
Add a `pytest.mark.raises`, distinct from `pytest.mark.xfail(raises=)` or `pytest.raises`

### ISSUE THREAD

**Issue by tkoft** [pytest-dev/pytest#11555]
[From the docs](https://docs.pytest.org/en/7.1.x/example/parametrize.html#parametrizing-conditional-raising):
>Use [pytest.raises()](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.raises) with the [pytest.mark.parametrize](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-mark-parametrize-ref) decorator to write parametrized tests in which some tests raise exceptions and others do not.

#### What's the problem this feature will solve?

When a parametrized test has lots of cases, it doesn't make sense to add an `expectation` input that will be `does_not_raise()` for the majority of tests, just so I can make sure one case does raise.

#### Describe the solution you'd like

Wouldn't it make more sense to have a `pytest.mark.raises(SomeError)` mark that I can pass to `pytest.param`? Going with the example from the docs, this might look like:
```
@pytest.mark.parametrize(
    "example_input",
    [
        (3,),
        (2,),
        (1,),
        pytest.param(0, marks=pytest.mark.raises(ZeroDivisionError)),
    ],
)
def test_division(example_input):
    """Test how much I know division."""
    assert (6 / example_input) is not None
```

#### Additional context

Of course, there is the `pytest.mark.xfail(raises=ZeroDivisionError, strict=True)` mark, but this ultimately reports the test as XPASS instead of PASS, like `pytest.raises()` would. And since it's possible to detect the raised error with the xfail mark, I assume it'd be possible to do the same here with a new mark.

**Comment by RonnyPfannschmidt** [comment]
-1 on this

The suggested best practice is to have explicit test cases for the error case's

Xfail is not for testing negatives but for managing tests that ought not to fail,but do so for a reason

**Comment by Pierre-Sassoulas** [comment]
Also, I think it would add implicitness when the suggested use of a null context manager named ``does_not_raise`` is very explicit. Writing is done once and reading multiple time, so I think the verbosity is the lesser evil here.

**Comment by tkoft** [comment]
> The suggested best practice is to have explicit test cases for the error case's

This is still quite explicit, it just removes repetitive `does_not_raise` calls. By this argument every pytest test that doesn't raise should have to run in a ‘with does_not_raise()‘ context. 

> Xfail is not for testing negatives but for managing tests that ought not to fail,but do so for a reason 

I'm aware, that's why I said it's not an ideal solution.

**Comment by tkoft** [comment]
> Also, I think it would add implicitness when the suggested use of a null context manager named ``does_not_raise`` is very explicit. Writing is done once and reading multiple time, so I think the verbosity is the lesser evil here.

It doesn't seem like the lesser evil when it has to be repeated hundreds of times in a code base that uses parametrization heavily, for the sake of a few error cases :) 

If I parametrize some test code, I feel I should be able to express every outcome of that code through my set of parameters. It doesn't make sense to add a separate test calling the same code just to evaluate a different outcome.

**Comment by The-Compiler** [comment]
I'm also -1 on this. In my company trainings, I often see beginners struggle with the difference between raises and xfail. I feel like adding a *second* way to check for an exception being raised makes that whole situation even more complicated.

In addition to that, it also encourages having more code in the `raises` block as absolutely needed. Maybe not with your example, but I can see e.g. a `pytest.mark.raises(ValueError)` for the entire test being triggered accidentally by some sort of setup operation or just test logic, rather than the thing that actually should be tested.

IMHO in many scenarios, the better solution is to split the good and the bad cases into two different test functions, with those checking whatever is appropriate (e.g. return value vs. exception message), rather than shoehorning everything into one.

**Comment by RonnyPfannschmidt** [comment]
closing as not planned, the proposed api would lead beginners toward bad practices

**Comment by nicoddemus** [comment]
> IMHO in many scenarios, the better solution is to split the good and the bad cases into two different test functions, with those checking whatever is appropriate (e.g. return value vs. exception message), rather than shoehorning everything into one.

I agree with that sentiment. Perhaps we should change or remove this [section of the docs](https://docs.pytest.org/en/stable/example/parametrize.html#parametrizing-conditional-raising) then? It does encourage this style.
