### ISSUE TITLE
Remove/update recommendation about using nullcontext + parametrize

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#11556]
As discussed in https://github.com/pytest-dev/pytest/issues/11555#issuecomment-1780749198, we should no longer recommend that approach in our documentation.

**Comment by ziadk** [comment]
Hello @nicoddemus,

I am new and would love to work on this.

Could you please maybe provide some details on what to do ? Do I remove the whole section in the docs or modify it ?

Thanks a lot !

**Comment by nicoddemus** [comment]
I see you opened a PR, moving the discussion over there. 👍

**Comment by nicoddemus** [comment]
As discussed in #11557, some people actually think the nullcontext example should stay, so stay it shall. 👍
