### ISSUE TITLE
WDYT if LocalPath behaved even more like Path?

### ISSUE THREAD

**Issue by dimaqq** [pytest-dev/pytest#11569]
Here's an example:

```py
@pytest.fixture(scope="session")
def sample_data(request):
    return (request.config.rootdir / "data/sample.txt").read_text()
```

Today, this fails with `TypeError: LocalPath.read_text() missing 1 required positional argument: 'encoding'`.

I find that quite unexpected, because in other ways, the object works very much like `pathlib.Path`, and therefore I'd expect it to use the default, `UTF-8` encoding.

**Comment by RonnyPfannschmidt** [comment]
We will never go there, use the pathlib variant of the attribute

The local path ones are slated for removal

**Comment by dimaqq** [comment]
Ah!

For future readers, here's what the code should look like:

```py
@pytest.fixture(scope="session")
def sample_data(pytestconfig):
    return (pytestconfig.rootpath / "data/sample.txt").read_text()
```
