### ISSUE TITLE
Document that pytest.raises matches subclasses; consider an opt-in exact mode

### ISSUE THREAD

**Issue by sparrowt** [pytest-dev/pytest#11577]
#### What's the problem this feature will solve?
The [documentation for `pytest.raises`](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-raises) makes no mention of the fact that it will pass if **any subclass** of the provided exception type is raised.

It says things like this which are arguably ambiguous, or at least unclear if you haven't thought of the subclass case:
> Assert that a code block/function call raises expected_exception or raise a failure exception otherwise.
> ...
> If the code block does not raise the expected exception ... the check will fail instead.

I had to look at the internals (it just [uses it in an `except`](https://github.com/pytest-dev/pytest/blob/8fb7e8b31efaa55e760c142e26eb82b42081ca28/src/_pytest/python_api.py#L961)) to confirm this behaviour, after realising soething was up due to coverage flagging a `raise` which was not covered despite a passing test which _appeared_ to test that code path.

#### Describe the solution you'd like

1. At a minimum it would help to update the documentation to make this clearer, e.g. just adding a sentence flagging that subclasses are matched too, just like in `except`.
2. Additionally could we consider an option to `raises` such as `match_exact_type=True`? This would be a much more concise way to achieve the explicit exc_info.type check as shown in the workaround below.

#### Alternative Solutions

Although it was not at all obvious to me, I now realise that I can modify the test to be more specific, e.g. in my case the test did this:
```
with pytest.raises(RuntimeError):
    do_stuff()
```
and the code under test did `raise RuntimeError()`.

It passed but for the wrong reasons: `do_stuff()` was actually raising `NotImplementedError` (a subclass of RuntimeError) for an entirely unrelated reason.

As a workaround now that I've realised this, it's possible to explicitly do an exact match on the exception type like this:
```
with pytest.raises(RuntimeError) as exc_info:
    do_stuff()

# Check it's actually RuntimeError, not just any subclass thereof
assert exc_info.type is RuntimeError
```
However this is quite verbose and only useful once you realise there's a problem, which in my case was long after the test was written and only due to missing coverage being flagged.

Better documentation would hopefully make this clearer and an option to do exact type matching would be a great bonus!

**Comment by sparrowt** [comment]
P.S. the only related issue I could find was https://github.com/pytest-dev/pytest/issues/4475 which is different but similar - clearer documentation would hopefully make it more obvious that `pytest.raises(Exception)` is potentially risky.

**Comment by Zac-HD** [comment]
How about:

> Assert that a code block raises an instance of `expected_exception`, or raise a failure exception otherwise.
>
> Note that this will be satisfied by a subclass, meaning that tests which use `with pytest.raises(Exception):` often pass for the wrong reason.

**Comment by nicoddemus** [comment]
I opened #11578 with improvements meant to address this, @Zac-HD feel free to review and comment over there. 👍

**Comment by sparrowt** [comment]
Thanks folks!
