### ISSUE TITLE
Document `--ignore` CLI option on pythoncollection.html

### ISSUE THREAD

**Issue by edmorley** [pytest-dev/pytest#1158]
Google searches for terms like `pytest ignore directory` returned these pages:
https://pytest.org/latest/example/pythoncollection.html
https://pytest.org/latest/customize.html

Neither of those mentioned the `--ignore` option, so it took a while before I realised it existed.

Please could we document it on them (particularly pythoncollection.html)?

Thanks :-)

**Comment by nicoddemus** [comment]
Thanks for reporting this @edmorley! :smile: 

Would you mind opening a PR?

**Comment by hackebrot** [comment]
Please review #1168, thanks :bow:

**Comment by edmorley** [comment]
The docs added in that PR look great - thank you :-)
