### ISSUE TITLE
CS50 pytest issue

### ISSUE THREAD

**Issue by billlocke** [pytest-dev/pytest#11598]
Results for cs50/problems/2022/python/tests/bank generated by check50 v3.3.9
:) test_bank.py exist
:( correct bank.py passes all test_bank checks
    expected exit code 0, not 1
:| test_bank catches bank.py with incorrect values
    can't check until a frown turns upside down
:| test_bank catches bank.py without case-insensitivity
    can't check until a frown turns upside down
:| test_bank catches bank.py not allowing for entire phrase
    can't check until a frown turns upside down

I execute test_bank.py on bank.py with no errors.
When I use the CS50 "check" command above, I get an error. I've spent a couple of hours, and cannot figure out what is wrong.
Can anyone point me in the right direction? Or who else to submit this issue to?

**Comment by nicoddemus** [comment]
Hi @billlocke,

We will need more information, what is `cs50`? Seems like a class assignment?

**Comment by The-Compiler** [comment]
This seems to be about https://github.com/cs50/check50 which is unrelated to pytest.

**Comment by billlocke** [comment]
Thanks for responding. Will contact CS50 class authors.
    On Tuesday, November 7, 2023 at 03:45:14 PM EST, Florian Bruhin ***@***.***> wrote:  
 
 


Closed #11598 as not planned.
