### ISSUE TITLE
AttributeError: 'module' object has no attribute 'epoll'

### ISSUE THREAD

**Issue by dachary** [pytest-dev/pytest#1161]
<pre>
$ cat test_foo.py
import select

def test_epoll():
    e = select.epoll()
$ py.test -s -v teuthology/test/test_foo.py
================================================================================================ test session starts ================================================================================================
platform linux2 -- Python 2.7.6, pytest-2.8.2, py-1.4.30, pluggy-0.3.1 -- /home/loic/software/ceph/teuthology/virtualenv/bin/python
cachedir: .cache
rootdir: /home/loic/software/ceph/teuthology, inifile: pytest.ini
collected 1 items 

teuthology/test/test_foo.py::test_epoll FAILED

===================================================================================================== FAILURES ======================================================================================================
____________________________________________________________________________________________________ test_epoll _____________________________________________________________________________________________________

    def test_epoll():
>       e = select.epoll()
E       AttributeError: 'module' object has no attribute 'epoll'

teuthology/test/test_foo.py:4: AttributeError
============================================================================================= 1 failed in 0.01 seconds ==============================================================================================
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import select
>>> select.epoll()
<select.epoll object at 0x7f418a76d0f0>
>>> 
</pre>

**Comment by The-Compiler** [comment]
Works fine here. What does `print select.__file__` say in the failing test?

**Comment by dachary** [comment]
<pre>
from gevent import monkey
monkey.patch_all(dns=False)
</pre>
was run implicitly and caused the error, sorry for the noise
