### ISSUE TITLE
Add a `set_filter()` context manager to the caplog fixture

### ISSUE THREAD

**Issue by jenstroeger** [pytest-dev/pytest#11610]
#### What's the problem this feature will solve?

I need to test a custom [filter](https://docs.python.org/3/library/logging.html#filter-objects) for logging, and currently I use one of the following two approaches:
```python
def test_filter(caplog: pytest.LogCaptureFixture) -> None:
    caplog.set_level(logging.INFO)

    logger = logging.getLogger(__name__)  # This test module's logger.
    filter_ = SchnufteCustomFilter()
    logger.addFilter(filter_)

    # Run tests.
    assert len(caplog.record_tuples) == 1
    assert caplog.record_tuples[0] == ("test_custom_filter", 20, "Schnufte!")

    logger.removeFilter(filter_)
```
or
```python
def test_filter(caplog: pytest.LogCaptureFixture) -> None:
    caplog.set_level(logging.INFO)

    filter_ = SchnufteCustomFilter()
    caplog.handler.addFilter(filter_)

    # Run tests.
    assert len(caplog.record_tuples) == 1
    assert caplog.record_tuples[0] == ("test_custom_filter", 20, "Schnufte!")     

    caplog.handler.removeFilter(filter_)
```
#### Describe the solution you'd like

Similar to the [`at_level()`](https://docs.pytest.org/en/6.2.x/reference.html?highlight=logcapturefixture#pytest.LogCaptureFixture.at_level) context manager I think it would be useful to wrap the second of the above filter setups into a custom context manager, that I can then call like so:
```python
def test_filter(caplog: pytest.LogCaptureFixture) -> None:
    caplog.set_level(logging.INFO)

    filter_ = SchnufteCustomFilter()
    with caplog.set_filter(filter_):  # use_filter() or with_filter() or ...
        # Run tests.
        assert len(caplog.record_tuples) == 1
        assert caplog.record_tuples[0] == ("test_custom_filter", 20, "Schnufte!")     
```

#### Alternative Solutions

See above’s examples, I guess.

#### Additional context

I’m happy to give a PR a shot: I suppose the change would be adding a method to the [LogCaptureFixture](https://github.com/pytest-dev/pytest/blob/99f77388107fcee4cbc665659fac61c8468b693d/src/_pytest/logging.py#L391), for example:
```python
@final
class LogCaptureFixture:

    @contextmanager
    def set_filter(filter_: logging.Filter) -> Generator[None, None, None]:  # Type needs to be aligned with _FilterType from stdlib/typeshed.
        self.handler.addFilter(filter_)
        try:
            yield
        finally:
            self.handler.removeFilter(filter_)
```

**Comment by nicoddemus** [comment]
👍  from me.

Bikesheding:

```python
with caplog.with_filter(SchnufteCustomFilter()): ...

with caplog.filtering(SchnufteCustomFilter()): ...
```

I prefer the latter, reads naturally to me (although I'm not a native speaker).

**Comment by jenstroeger** [comment]
@nicoddemus shall I go ahead and create a PR?

**Comment by nicoddemus** [comment]
Yes please

**Comment by jenstroeger** [comment]
@nicoddemus what’s the recommendation regarding testing: the `at_level()` context manager  has its own test functions [here](https://github.com/pytest-dev/pytest/blob/80442ae2f2177039e5395d8a26fc6e3ca3a54f3e/testing/logging/test_fixture.py#L147-L185), so I could add the new `filtering()` context manager into those existing functions, or create new functions?

**Comment by nicoddemus** [comment]
New functions are preferred. 👍
