### ISSUE TITLE
Pytest doesn't print fixture teardown if there is a passing test along side the failing test in a suite

### ISSUE THREAD

**Issue by greenatatlassian** [pytest-dev/pytest#11620]
When a fixture that was used in a test that fails, I expect the fixture teardown output (stdout/stderr) to be printed as part of the test report. This works if the fixture was *only* used in tests that fail, but if the fixture was also used in a test that passes, only the fixture startup output is printed, but not the shutdown output.

`pip list` output:
```
Package    Version
---------- -------
iniconfig  2.0.0
packaging  23.2
pip        22.3.1
pluggy     1.3.0
pytest     7.4.3
setuptools 65.6.3
```

Operating system version: macOS 12.7
Python version: Python 3.11.2

MWE:

```
import pytest

@pytest.fixture(scope='session')
def my_fixture():
    print("My Fixture Set Up")
    yield
    print("My Fixture tear down")

def test_1(my_fixture):
    print("test_1")
    assert False

def test_2(my_fixture):
    print("test_2")
```

Output if only failing test is called, which includes the expected fixture teardown output:
```
pytest test_python.py::test_1
=========================== test session starts ===========================
platform darwin -- Python 3.11.2, pytest-7.4.3, pluggy-1.3.0
rootdir: /Users/agreen/code/constellation/constellation-dev
configfile: pytest.ini
collected 1 item

test_python.py F                                                    [100%]

================================ FAILURES =================================
_________________________________ test_1 __________________________________

my_fixture = None

    def test_1(my_fixture):
        print("test_1")
>       assert False
E       assert False

test_python.py:11: AssertionError
-------------------------- Captured stdout setup --------------------------
My Fixture Set Up
-------------------------- Captured stdout call ---------------------------
test_1
------------------------ Captured stdout teardown -------------------------
My Fixture tear down
========================= short test summary info =========================
FAILED test_python.py::test_1 - assert False
============================ 1 failed in 0.01s ============================
```

Output if both tests are called, which does not include the fixture teardown output.
```
pytest test_python.py
=========================== test session starts ===========================
platform darwin -- Python 3.11.2, pytest-7.4.3, pluggy-1.3.0
rootdir: /Users/agreen/code/constellation/constellation-dev
configfile: pytest.ini
collected 2 items

test_python.py F.                                                   [100%]

================================ FAILURES =================================
_________________________________ test_1 __________________________________

my_fixture = None

    def test_1(my_fixture):
        print("test_1")
>       assert False
E       assert False

test_python.py:11: AssertionError
-------------------------- Captured stdout setup --------------------------
My Fixture Set Up
-------------------------- Captured stdout call ---------------------------
test_1
========================= short test summary info =========================
FAILED test_python.py::test_1 - assert False
======================= 1 failed, 1 passed in 0.01s =======================
```

**Comment by RonnyPfannschmidt** [comment]
This is expected and intented behavior

The teardown didn't not happen as part of the singular tests execution

Only the setup

The teardown happens as part of the execution of another singular test

**Comment by greenatatlassian** [comment]
That surprises me. If I understand correctly, you're saying the behaviour of fixture teardown depends on whatever test 
happened to be executed last among the tests included in the fixture scope? I experimented, and the output does change if I change the order of the tests in the file. 

So the behaviour is dependent on the ordering of tests (in a test file, etc). Is this documented? I'd like to read and make sure I understand for future.

We did some experiments with the `-x` option, in which case the failing test is always the last test executed, but the fixture teardown still doesn't print any captured output.

**Comment by bluetech** [comment]
> That surprises me. If I understand correctly, you're saying the behaviour of fixture teardown depends on whatever test
happened to be executed last among the tests included in the fixture scope? I experimented, and the output does change if I change the order of the tests in the file.

Yes, a fixture is torn down as part of the test that last uses it basically. Pytest tries to do test setups and teardowns, even for higher scopes, in a context of a test.

> So the behaviour is dependent on the ordering of tests (in a test file, etc). Is this documented? I'd like to read and make sure I understand for future.

I don't think it's documented explicitly but you can see this internal docstring which describes the mechanism: https://github.com/pytest-dev/pytest/blob/047ba83dabe492af938104fe0058597f67a672be/src/_pytest/runner.py#L401-L463

**Comment by greenatatlassian** [comment]
Fair enough. I guess this model is just very different from other test frameworks I've used, such as JUnit. From my experience, I expect fixture setup and teardown to be entirely independent of test execution. The fact that the test outcomes differ depending on the ordering of tests (that are not actually interdependent) seems like a smell to me.
