### ISSUE TITLE
Pytest not discovering test classes with custom decorators

### ISSUE THREAD

**Issue by DanielJerrehian** [pytest-dev/pytest#11633]
I have the following decorator:

```py
def orchestrate(cls):
    @functools.wraps(cls)
    def wrap(*args,**kwargs):
        print("Here")
        cls.orchestrator = "Some Value..."
        return cls(*args, **kwargs)
    return wrap
```

That I would like to use with a test class like this:

```py
@orchestrate
class TestSomething:
    def test_something(self):
        print(self.orchestrator) # Expecting "Some Value..." to be printed here
        assert 1 == 1
```
but Pytest does not collect test_something and reports that 0 were collected. I cannot use fixtures in this case and need to be able to use a decorator that adds an attribute to the class it decorates with a certain value.

If I take the decorator away Pytest finds and runs the test. How can I get Pytest to collect the methods inside decorated test classes?

-----------------------------------------------------------------------------------------------------------------------

I am using Windows 10 with Pytest = "7.3.1", the following are installed in my venv:
- python = "^3.10"
- pytest = "7.3.1"
- SQLAlchemy = "2.0.15"
- pyodbc = "4.0.39"
- pandas = "2.0.1"
- python-dotenv = "1.0.0"
- azure-identity = "1.13.0"
- decorator = "^5.1.1"

-----------------------------------------------------------------------------------------------------------------------

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
The decorator returns a function, so it's not a class anymore

The example decorator looks like something that should be replaced by a marker or something that mutates the class and return's it

**Comment by DanielJerrehian** [comment]
Thank you for that. Would you be able to provide an example of what you're referring to?

**Comment by RonnyPfannschmidt** [comment]
```
@pytest.mark.orchestrate(something)
Class TestFoo: ...

```
For more,more context is needed

**Comment by Zac-HD** [comment]
or 
```python
def orchestrate(cls):
    cls.orchestrator = "Some Value..."
    return cls
```
