### ISSUE TITLE
DOC - dead link to the pytest support in tox

### ISSUE THREAD

**Issue by Remi-Gau** [pytest-dev/pytest#11697]
- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [x] minimal example if possible

In this section:

https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html?highlight=tox#tox

The link in "the virtualenv test automation tool and its [pytest support](https://tox.wiki/en/stable/example/pytest.html)." gives a 404:

https://tox.wiki/en/stable/example/pytest.html

--- 

Could not find a decent replacement in the tox doc:

https://tox.wiki/en/4.11.4/search.html?q=pytest&check_keywords=yes&area=default

The closest would be maybe this one: https://tox.wiki/en/4.11.4/user_guide.html#basic-example

--- 

Am happy to fix it if a good replacement target can be found.

**Comment by The-Compiler** [comment]
Looks like this got removed with the tox 4 rewrite. Here is the original page: https://tox.wiki/en/3.27.1/example/pytest.html

IMHO we should just remove the "and its pytest support" part. There is nothing special about pytest going on there really...

**Comment by Remi-Gau** [comment]
OK will just remove this part and let you decide.

**Comment by Remi-Gau** [comment]
Apparently I am late to the party and it was already done a while back:
https://github.com/pytest-dev/pytest/commit/b90e7b84d0082994a87001d408ee8d9d7ca9ddba

I should have checked a more recent version of the doc
https://docs.pytest.org/en/latest/explanation/goodpractices.html#tox
