### ISSUE TITLE
pytest.exit returncode default is poorly documented

### ISSUE THREAD

**Issue by SpecLad** [pytest-dev/pytest#11695]
According to <https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-exit>, the default value of the `returncode` parameter of `pytest.exit` is `False`. However:

* According to the actual source, the default value is `None`, not `False`: <https://docs.pytest.org/en/7.1.x/_modules/_pytest/outcomes.html#exit>.

* It's not clear what a `returncode` of `None` actually means. You can't return `None` to the OS (the return code is an integer), so it must correspond to some integer value.

**Comment by arthuRHD** [comment]
When we're talking about returncode it's generally an [exit status](https://en.wikipedia.org/wiki/Exit_status). 

(i.e. : `pytest.exit(1)` for POSIX is a program exited with an error. And if you provided a message, it will be piped to stderr. It's optional so you can just put `pytest.exit()`to quit gracefully)

**Comment by SpecLad** [comment]
I know what an exit status is, but an exit status can't be `None`. Therefore `None` has to correspond to some other status.

**Comment by nicoddemus** [comment]
It is the same as `sys.exit(None)`, which is the same as `sys.exit(0)`.
