### ISSUE TITLE
Add "--show-capture-success" command line option to display captured stdout/stderr on success

### ISSUE THREAD

**Issue by Delgan** [pytest-dev/pytest#11731]
#### What's the problem this feature will solve?

I'm testing parts of my application that are printing some messages to `sys.stdout`.
In my test, I writing to `sys.stderr` some debugging information to help diagnose failures.

These are only printed when the test fail. However, to better understand and double-check that a test is behaving as expected, being able to visualize captured output is sometimes very convenient even when the test succeeded.

#### Describe the solution you'd like

We could image a new `--show-capture-success` command line argument, similar to `--show-capture`, which would default to `no`. Users could switch it to `all` and be able to show captured output regardless of success or failure of the test.

Other tests framework such as `Catch2` in C++ provides a similar `--success` option: [Showing results for successful tests](https://github.com/catchorg/Catch2/blob/v3.5.0/docs/command-line.md#showing-results-for-successful-tests)

#### Alternative Solutions

Currently, it's possible to use `--capture=no`, but it causes all types of output to be mixed altogether (`sys.stdout`, `sys.stderr`, `logging` and actual `pytest` output) instead of being separately formatted by `pytest`. This hurts readability. 

#### Additional context

I would happily contribute with a PR if such feature request is accepted.

**Comment by The-Compiler** [comment]
`-rP` ("Show extra test summary info as specified by chars: [...] (P)assed with output") already does that (#1232).
