### ISSUE TITLE
markers defined in pytest.ini or pyproject.toml are not considered. It does work when using the command line

### ISSUE THREAD

**Issue by MarcBresson** [pytest-dev/pytest#11738]
# problem

When I use markers in `pyproject.toml` or in `pytest.ini`, all tests are selected.

`pyproject.toml` (I make sure to delete pytest.ini when this config was tested)
```
[tool.pytest.ini_options]
pythonpath = "."
addopts = "--strict-markers"
markers = [
    "slow: mark a test that takes a long time to run.",
]
```

> platform darwin -- Python 3.10.11, pytest-7.4.3, pluggy-1.3.0
> rootdir: /Users/datategy/Documents/o2_ml
> configfile: pyproject.toml
> plugins: fugue-0.8.7, anyio-4.2.0
> collected 3 items

`pytest.ini`
```
[pytest]
pythonpath = .
addopts = --strict-markers
markers =
    slow
```

> platform darwin -- Python 3.10.11, pytest-7.4.3, pluggy-1.3.0
> rootdir: /Users/datategy/Documents/o2_ml
> configfile: pytest.ini
> plugins: fugue-0.8.7, anyio-4.2.0
> collected 3 items

However, when I try with the command line, it works perfectly and only select the tests marked with 'slow'

```
pytest -m slow
```

> platform darwin -- Python 3.10.11, pytest-7.4.3, pluggy-1.3.0
> rootdir: /Users/datategy/Documents/o2_ml
> configfile: pyproject.toml
> plugins: fugue-0.8.7, anyio-4.2.0
> collected 3 items / 2 deselected / 1 selected

# my test

```python
@pytest.mark.slow
@pytest.mark.parametrize("params_model", params_slow_model)
def test_slow_ts_forecasting(params_model):
    ...
```

# environment

python 3.10.11
pytest 7.4.3
Chip Apple M2
MacOS 13.2 (22D49)

- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [ ] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
the markers ini option is for making markers known (so strict markers can be used to fail on typos instead of just warning

the mark expressions do not have a ini variant and must be passed in addopts - its strongly recommended not to do that for lack of a reverse/reset of those options

**Comment by MarcBresson** [comment]
ok, thank you for the explanation ! Does that mean there is no way to have default markers enabled when running the `pytest` command?

I could create a shell script that just calls `pytest -m "not slow"` but that does not seem right.

**Comment by RonnyPfannschmidt** [comment]
https://pypi.org/project/pytest-skip-slow/ is a example of a plugin implementing the pattern

its possible to override the default marker expression on the cli, but its confusing, thus its not recommended

**Comment by MarcBresson** [comment]
ok thank you very much for your help.

Closing this issue.

**Comment by MarcBresson** [comment]
Any reason why "`the mark expressions do not have a ini variant`"?

Btw, i'm gonna open a pull request to clarify the role of the `marker` property in pytest.ini

**Comment by RonnyPfannschmidt** [comment]
There is no sane way to undo a default

So if a default is enforced, it's tricky and hard to comprehend the implications for cli usage

So far nobody proposed a good solution, it's unlikely we'll have a reasonable solution with the current configuration system in place

**Comment by MarcBresson** [comment]
we could have a section `[pytest.defaults]`for "pytest.ini" and `[tool.pytest.ini_options.defaults]` for "pyproject.ini".

In such section, we would find the same parameters than for the CLI. It would give something like

```toml
[tool.pytest.ini_options.defaults]
failed-first = true
quite = true
strict-markers = true
k = "test_pipelines not test_pipelines_prediction"
m = "not slow"
```

**Comment by RonnyPfannschmidt** [comment]
Personally I'm not willing to implement that on the currently existing already broken configuration system and I'm not exactly keen on maintaining a implementation either

**Comment by MarcBresson** [comment]
Is the broken configuration system you refer to the one from python (pyproject.ini), or the one for pytest (with the multiple config file lookup)?

**Comment by RonnyPfannschmidt** [comment]
The pytest Config object and it's lifecycle/lifecycle in xdist
