### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by Noam-Microsoft** [pytest-dev/pytest#11741]
I run Pytest and get the following warning:
```
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import iter_entry_points
```
Is there expected to be a fix? if so, what's the ETA?

Python version: 3.9
Pytest version: 7.43
OS: Windows 64

**Comment by RonnyPfannschmidt** [comment]
More context needed, pytest and plugin don't use pkg-resources since ages

**Comment by The-Compiler** [comment]
Closing this as that line is definitely not coming from pytest (or at least not from a recent version).

You might be able to run something like `python -Werror -m pytest` to get a full traceback to see where the warning is originating from.
