### ISSUE TITLE
timestamps are stripped from log output

### ISSUE THREAD

**Issue by vitaly-krugl** [pytest-dev/pytest#1174]
We love pytest, but this issue frequently gets in the way. We have a large body of existing tests based on the unittest framework. The test scripts configure python logging output format with the details that make sense for our tests. In particular, and this is critical, the logging is configured to output UTC timestamps on each log line. The timestamps are critical for debugging, because they enable us to correlate what the test is doing **and when** with the timestamps of log output of our servers.

When a test fails, pytest emits the captured log output to the console. Our continuous integration build system captures the console output as an artifact for debugging. Critically, we find that pytest doesn't emit the timestamps, so we're unable to correlate the timing of the tests' log output with the logs on the servers.

Unlike using unittest's `unittest.main()` test runner, pytest's logging output actually doesn't match our logging output format configuration at all. Here is what the log output from pytest looks like:

```
INFO:tests.integration.custom_metrics_test:Running test with metric name: testBatchSend.1446946015
INFO:htmengine.test_utils.test_case_base:Attempt 1 of checkMetricCreated: Check that the new metrics show up in custom metrics list.
INFO:htmengine.test_utils.test_case_base:Attempt 2 of checkMetricCreated: Check that the new metrics show up in custom metrics list.
```

Our test console logging format is explicitly specified as `"%(asctime)s - %(name)s(%(process)d) - %(levelname)s - %(message)s"`.

We use `logging.Formatter.converter = time.gmtime` to configure logging to output timestamps in UTC.

It would be ideal if pytest could emit log output in the format that matches the console logging output format exactly as configured by the tests. After all, the test implementers know best what information they need for debugging failures.

Short of matching the test's console logging output format, at least prefixing a UTC timestamp with sub-second granularity to each log line would be useful. I think that a lot of developers/testers would find this very useful, without having to install additional plugins that alter the test function call signatures.

I've looked at `pytest-capturelog`, but their terse doc makes it look like they add an extra arg to each test method, which is not ideal for large volumes of existing tests.

Timestamps are often so useful for debugging test failures that they really need to be incorporated in pytest's standard output (or at least via command-line option). It's important that the timestamps match the exact time that the log output is emitted (versus post-processing that adds timestamps to each line after the fact).

**Comment by codewarrior0** [comment]
For PyInstaller, we were able to set up logging with formatted output for tests run via py.test just by calling logging.basicConfig in one of the modules imported by the test suite. The formatted log output was captured along with the regular stderr output. (We ended up using `pytest-catchlog` with  `--log-format` in our addopts due to weirdness on Windows with xdist...). How/when are you setting the format for your loggers?

**Comment by The-Compiler** [comment]
pytest doesn't capture any logging by itself (without any plugins) - it also doesn't do anything to the log format.

It looks to me like the code which sets up logging correctly in your application isn't run when you use pytest as runner, and *that* is the actual issue.

With this minimal example:

```python
import logging


def test_foo():
    logging.basicConfig(format='%(asctime)s - %(name)s(%(process)d) - %(levelname)s - %(message)s')
    logging.warning("test")
    assert False
```

I get the expected output:

```
-------------------------------------------- Captured stderr call --------------------------------------------
2015-11-09 06:11:45,193 - root(18519) - WARNING - test
```

As for `pytest-capturelog` - it doesn't require any tests to change, it just provides a `caplog` [fixture](http://pytest.org/latest/fixture.html#fixture-function) you can use to e.g. adjust the loglevel for a given test, but you don't *have* to use it.

However I recommend using [pytest-catchlog](https://pypi.python.org/pypi/pytest-catchlog/) instead, as capturelog is outdated and unfortunately abandoned by its author.

**Comment by vitaly-krugl** [comment]
@codewarrior0  and @The-Compiler: I am sorry for the trouble, I just took another look at the test script in question, and noticed that, unlike many of our tests, this specific test didn't configure logging, so it's user error, not pytest issue. Closing...

@The-Compiler, thank you for the info about the obsolescence of `pytest-capturelog`.
