### ISSUE TITLE
conftest undocumented

### ISSUE THREAD

**Issue by avdd** [pytest-dev/pytest#1176]
Do you ever read the documentation for some software that goes like this:

    ... to do this, use <feature of software> ...

and you go "oh, I want to learn about that feature", but you can't find it documented anywhere?

conftest.py is that feature.

**Comment by The-Compiler** [comment]
I don't follow.

I searched for "conftest" in the docs and found this as the first three matches:

* [Installing and Using plugins](http://pytest.org/latest/plugins.html) - talks about loading plugins from `conftest.py`, not what we want.
* [Writing plugins](http://pytest.org/latest/writing_plugins.html#conftest-py-plugins) - Tells us `conftest.py` are local, per-directory pytest plugins, and shows an example of how to define a hook in one.
* [fixtures](http://pytest.org/latest/fixture.html#sharing-a-fixture-across-tests-in-a-module-or-class-session) - Tells us we can put fixtures in `conftest.py` to share them across several test files.

So I'm not sure what you're missing?

**Comment by nicoddemus** [comment]
Agree with @The-Compiler... @avdd could you please be more specific?

**Comment by nicoddemus** [comment]
@avdd feel free to reopen this
