### ISSUE TITLE
Suggest Packages to Install

### ISSUE THREAD

**Issue by bmos** [pytest-dev/pytest#11762]
#### What's the problem this feature will solve?
I recently was using a GitHub Action that utilizes this module.
This GitHub Action requires the pytest-md package, which I didn't notice.
Because of this missing dependency, I got the error `pytest: error: unrecognized arguments: --md=path/to/file.md`.

#### Describe the solution you'd like
Using pytest with certain 'known' but not available args could trigger suggestions to alert users that they need to install other packages.

#### Alternative Solutions

I figured out the package I needed to install and it's fine now, but this could make it easier for others who lack required dependencies for certain args.

**Comment by RonnyPfannschmidt** [comment]
Knowing the options is out of scope for pytest,those projects should list required Plugins to indicate what test need

**Comment by Pierre-Sassoulas** [comment]
Maintaining a centralized list of plugin arguments seem opposite to the design of pytest and its plugins (and that list would never be up to date no matter how many maintainer-hour are thrown at it). On top of that, some args could be used in multiple plugins and complicate things even further.

**Comment by nicoddemus** [comment]
Closing this for now, but thanks for opening the discussion @bmos. :+1:
