### ISSUE TITLE
How to inject fixtures to testcase(function) decorator?

### ISSUE THREAD

**Issue by huntzhan** [pytest-dev/pytest#1177]
I want to define a decorator like this:

```python
def some_decorator(func):

    injected_fixtures = [mocker, cov]

    def wrapper(*args, **kwargs):
        <1. do something with injected_fixtures.>
        <2. remove unnecessary fixtures from kwargs.>
        # run testcase.
        return func(*args, **kwargs)

    <modify function signature of wrapper here>

    return wrapper


@some_decorator
def test_without_fixture():
    pass


@some_decorator
def test_with_overlapped_fixture(mocker):
    pass


@some_decorator
def test_with_non_overlapped_fixture(whatever):
    pass
```

I've tried several implementation, but none of them could stop `py.test` from inspecting the signature of wrapped function.

Here's my implementation to solve the problem, in a dirty way:

```python
def mock_connection(func):

    # just use the signature of wrapped function.
    @wraps(func)
    def wrapper(*args, **kwargs):
        mocker = kwargs.get('mocker', None)
        if mocker is None:
            raise RuntimeError('Missing mocker fixture.')

        # mock class.
        storage_cls = mocker.patch(
            'xxx.ConnectionPool',
        )
        <do something with storage_cls here.>

        # run testcase.
        return func(*args, **kwargs)

    return wrapper

@mock_connection
def test_create_attributes(mocker):
    <testcase logic>

```

**Comment by nicoddemus** [comment]
Hmmm decorator aside, couldn't you accomplish this using fixtures instead? It seems it would be pretty straightforward:

```python
def some_fixture(mocker, cov):
    injected_fixtures = [mocker, cov]
    <1. do something with injected_fixtures.>


@pytest.mark.usefixtures('some_fixture')
def test_without_fixture():
    pass
```

**Comment by huntzhan** [comment]
Thanks for your instruction, `@pytest.mark.usefixtures` would solve my problem.

But still, I am wondering if there is a way to make `py.test` treat the wrapped function(say, the `wrapper`) as final testcase function, and pass whatever fixtures it needs as shown by the signature of wrapped function.

**Comment by nicoddemus** [comment]
I think you can use an approach similar to [pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio) and [pytest-tornado](https://github.com/eugeniy/pytest-tornado) by implementing the `pytest_pyfunc_call` hook (take a look [here](https://github.com/pytest-dev/pytest-asyncio/blob/master/pytest_asyncio/plugin.py#L31)).

**Comment by huntzhan** [comment]
Thanks
