### ISSUE TITLE
"Database access not allowed" in Doctests (Django)

### ISSUE THREAD

**Issue by acjackson** [pytest-dev/pytest#1180]
I'm trying to get database access (django) in a few of my doctests with
```
pytestmark = pytest.mark.django_db
```
or
```
@pytest.mark.django_db
```
But I keep getting the following error:
```
Failed: Database access not allowed, use the "django_db" mark to enable it.
```

Is Django database access supported in doctests?
My other unittests using the Django database work fine.

I use
pytest 1.8.2.dev1 (https://github.com/pytest-dev/pytest/issues/1057)
pytest-django==2.9.1
Django==1.8

**Comment by nicoddemus** [comment]
IIRC doc tests currently can't be marked with pytest marks, so unless you can enable database access somehow using fixture's and the [getfixture](https://pytest.org/latest/doctest.html) API, I'm afraid there's no solution currently. 

Perhaps you could create an issue at [pytest-dev/pytest-django](https://github.com/pytest-dev/pytest-django) to see if there are any known workarounds?

**Comment by acjackson** [comment]
I tested some more and noticed this: some of the doctests, which are requiring a database connection, run successfully on console, but fail in PyCharm. I could not determine, why some tests run and some don't.

I'm now converting my doctests to unittests, which is probably a better practice and causes less problems.

**Comment by nicoddemus** [comment]
That's strange, probably some weird interaction with PyCharm's pytest runner (although I'm a PyCharm user and never experienced any problems). Feel free to reopen this if you happen to have new info.

**Comment by pbx** [comment]
Sorry to drop a comment on a six-year-old closed issue, but I'm facing this problem currently and am still looking for a fix.

* Django 3.2.x
* pytest 6.2.5
* pytest-django 4.4.0

My tests were originally inside docstrings in my codebase, but when the recommended decorators didn't help them pass, I extracted them into a standalone `.txt` file. 

Sanitized output showing the error in response to `pytest tests.txt`:
```
Traceback (most recent call last):
  File "<doctest tests.txt[2]>", line 1, in <module>
  File "models.py", line 611, in save
    super(Foo, self).save(force_insert=force_insert, using=using)
...
  File "django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "pytest_django/plugin.py", line 714, in _blocking_wrapper
    raise RuntimeError(
RuntimeError: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```
