### ISSUE TITLE
Mark.parametrize eccepting type-annotated arguments as argnames string argument

### ISSUE THREAD

**Issue by peroksid** [pytest-dev/pytest#11806]
#### What's the problem this feature will solve?
The decorator pytest.mark.parameterize() could use arglist which contains type-annotated arguments. 
This way one can quickly copy function signature and clean it later.

#### Describe the solution you'd like
I'd like to see

```python
@pytest.mark.parametrize("flag: bool, context: Tuple[BaseModel], error_message: Optional[str]")
def test_func(flag: bool, context: Tuple[BaseModel], error_message: Optional[str]):
    ...
```

For this I change the parsing of string argnames value in https://github.com/pytest-dev/pytest/blob/5645fa45fb063027aab6d49d4d64090446d82292/src/_pytest/mark/structures.py#L128

If I detect colons in the argnames after splitting with ',', I split by colons and take the correct half before stripping spaces.

The existing functionality is not affected, only extended.

**Comment by dolfinus** [comment]
But why?

**Comment by dolfinus** [comment]
But why? What `mark.parametrize` should do with these hints, perform type validation?

**Comment by RonnyPfannschmidt** [comment]
This severely complicated parsing without adding value as of now, unless added value is shown this shouldn't be considered

**Comment by peroksid** [comment]
It could, but it's not essential. It'd be handy to support simple
copy-pasted fragments with typw hints.

Currently you can copy-paste test function arguments to parameterise
arguments list, it's quick. If you use type hints you start stumbling upon.

The implementation will not be super complicated.
