### ISSUE TITLE
Internal Error: AttributeError: 'str' object has no attribute 'relate'

### ISSUE THREAD

**Issue by apallin** [pytest-dev/pytest#1184]
Hello,

I am getting this constant error with my pytest setup and I don't know whats going on.  This seemed to start occurring once we stopped using pytest-xdist and removed it as a dependency on the project.  This error isn't very useful and I have no idea where to begin to debug this.

Packages used:
        "pytest==2.8.2",
        "pytest-rerunfailures==0.5",

I have seen other threads relating to a similar problem but with no resolution.

INTERNALERROR>     return entry.path != cutdir1 and not entry.path.relto(cutdir2)
INTERNALERROR> AttributeError: 'str' object has no attribute 'relto'

**Comment by The-Compiler** [comment]
Can you please try with the current master? This should've been fixed in #1142, but isn't released yet (but hopefully very soon).

**Comment by apallin** [comment]
Seems to be fixed on master.  Any idea when this will come out or a workaround?  This is blocking us quite a bit.

**Comment by The-Compiler** [comment]
I'm closing this then. I hope the 2.8.3 release will be this week, see #1181.

**Comment by The-Compiler** [comment]
2.8.3 just [was released](http://lists.idyll.org/pipermail/testing-in-python/2015-November/006580.html) thanks to @RonnyPfannschmidt :tada:
