### ISSUE TITLE
docs.pytest.org don't have 8.0.x in releases list

### ISSUE THREAD

**Issue by dolfinus** [pytest-dev/pytest#11869]
It looks like there is no 8.0.x version on https://docs.pytest.org:
<details>
<summary>Screenshot</summary>

![Screenshot_20240128_121402_Chrome.jpg](https://github.com/pytest-dev/pytest/assets/4661021/59f223da-8826-479d-9e63-c16a108418f8)
</details>

8.0 documentation is available as [latest](https://docs.pytest.org/en/latest/changelog.html) version, but it is probably built from `main` branch, not 8.0.0 release tag.

[stable](https://docs.pytest.org/en/stable/changelog.html) version has title `pytest-0.1` but contains 8.0.0 documentation:
<details>
<summary>Screenshot</summary>

![Screenshot_20240128_123345_Chrome.jpg](https://github.com/pytest-dev/pytest/assets/4661021/5ee49981-fea0-46cf-9208-53a7880cb94f)
</details>

Also after going to https://docs.pytest.org I was redirected to 7.4.x release documentation, this probably should be updated as well.

**Comment by bluetech** [comment]
I don't have access to the RTD settings, @nicoddemus or @RonnyPfannschmidt maybe you can take a look?

**Comment by nicoddemus** [comment]
Updated the configuration, it is building atm...

**Comment by nicoddemus** [comment]
Fixed, thanks @dolfinus!

@bluetech let me know if you want access to the RTD settings, just give me your user name. :+1:

**Comment by bluetech** [comment]
Thanks @nicoddemus.

> @bluetech let me know if you want access to the RTD settings, just give me your user name. 👍

It's `bluetech`.
