### ISSUE TITLE
flaky behavior that warning log is not captured by caplog in pytest 8

### ISSUE THREAD

**Issue by sfc-gh-aling** [pytest-dev/pytest#11886]
- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

- after upgrading to pytest 8, we have some flaky test failures because of the `caplog` doesn't capture the warnings log.
pytest < 8 does not have this issue. The issue takes place on multiple OS (mac, windows, linux) and different Python versions (3.8 - 3.11).

- details can be found in our pipeline:
https://github.com/snowflakedb/snowpark-python/actions/runs/7701541832/job/20987856477?pr=1221

the way how we use warning is

```
import logging
logger = logging.getLogger("<mymodule>")
logger.warning("some text")
```

I checked the changelog but didn't find anything related to this, did I miss anything here?

**Comment by bluetech** [comment]
I am not aware of any change that will affect this.

Is it possible to run the snowpark-python tests locally?
