### ISSUE TITLE
`pytest` 8.0 keeps returning `AttributeError: 'CallSpec2' object has no attribute 'funcargs'`

### ISSUE THREAD

**Issue by vanloc1808** [pytest-dev/pytest#11890]
After upgrading to `pytest` 8.0, I see a lot of tests failed with the error.  
I observe that failed tests happen when there is usage of `pytest_lazyfixture` with `pytest` 8.0.0.
![image](https://github.com/pytest-dev/pytest/assets/76842571/e4346b3b-2420-4794-a252-49372a5188c3)

Operating System: Ubuntu 22.04

- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by vanloc1808** [comment]
Hi @The-Compiler 
Here is the error
![image](https://github.com/pytest-dev/pytest/assets/76842571/8055fba7-d2a0-451a-b14e-27f2c90c42c0)
Due to security policies, I cannot reveal the test here.
But one note, I observed that the error happens when using
```pytest_lazyfixture.lazy_fixture```
Other tests without `lazy_fixture` are successful

**Comment by The-Compiler** [comment]
As you can see in the stacktrace, this is indeed an issue in `pytest_lazyfixture.py` and not pytest:

- https://github.com/TvoroG/pytest-lazy-fixture/issues/65
