### ISSUE TITLE
When combining multiple marks, it is found that as long as the previous mark is satisfied, the subsequent marks will not be checked

### ISSUE THREAD

**Issue by guoweifeng216** [pytest-dev/pytest#11908]
pytest tests/rdma/perftest_tcp/test_*_bw.py -vx -m "(lv0 or lv1) and smoke and not huge"
 When the “smoke” mark is satisfied, the "not Huge" mark will not take effect

**Comment by bluetech** [comment]
Can't reproduce this, please provide a minimal reproduction example and we can take a look.
