### ISSUE TITLE
re-enable all warnings by default 

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1191]
From @hunse in #1190 

> For interest, here's the reasoning on why DeprecationWarnings are suppressed by default. It looks like unittest re-enables them; maybe pytest should do the same?

**Comment by The-Compiler** [comment]
Should we do this for 3.0 as it's backwards-incompatible but probably relatively straightforward? Or do we just recommend people to use `pytest-warnings` and `-Wall` if they want warnings?

**Comment by RonnyPfannschmidt** [comment]
i think we discussed having it in pytest-warnings for now - @fschulze might recall more details

**Comment by fschulze** [comment]
For 3.0 we should recommend pytest-warnings, which will eventually be integrated into pytest.

**Comment by nicoddemus** [comment]
This task is actually for enabling general warnings by default, I think we should do it in 3.0 as it should be simple enough. I will get to it this week.

**Comment by nicoddemus** [comment]
Just to add more information, [here's](https://docs.python.org/3/whatsnew/2.7.html#changes-to-the-handling-of-deprecation-warnings) the full disclosure on how warnings are now handled. The interesting bit here is this:

> The unittest module also automatically reenables deprecation warnings when running tests.

**Comment by fschulze** [comment]
For 3.0 we decided to only show the pytest internal warnings by default. We hadn't decided on how to handle DeprecationWarnings yet, neither in tests, nor in pytest itself. That's why we wanted to recommend pytest-warnings.

If you just enable them like unittest does, then tests that capture output are likely to break.

For 3.0 I wouldn't change anything regarding the warnings module.

**Comment by nicoddemus** [comment]
> If you just enable them like unittest does, then tests that capture output are likely to break.

Believe me, just by enabling to show pytest-warnings by default some test suites will break already (some tests at work which used `testdir` to test fixtures for example). :wink: 

But I agree that this could be done in 3.1, where we could do all warnings changes we planned:

* Integrate pytest-warnings plugin into core (#1803);
* Replace internal warning system to standard warnings (#1804);
* This issue;

Moving this (as well as the others above) to milestone **3.1**.

**Comment by nicoddemus** [comment]
Fixed by #2072.
