### ISSUE TITLE
a public method to change pytester's working directory

### ISSUE THREAD

**Issue by DetachHead** [pytest-dev/pytest#11942]
#### What's the problem this feature will solve?
i'm writing a test for my own pytest plugin that changes the working directory to a child of the temporary directory created by pytester, because there was a bug in my plugin that caused it to break when it was run in a different directory to where the tests were located. however there doesn't seem to be a public method to do this

#### Describe the solution you'd like
the `Pytester.chdir` method could take an optional argument to specify what path to change the working directory to:
```py
def chdir(self, new_path: Path | None = None) -> None:
    """Cd into the temporary directory.

    This is done automatically upon instantiation.
    """
    if new_path:
        self._path = new_path
    self._monkeypatch.chdir(self.path)
```
#### Alternative Solutions
as a workaround i modified the private `_path` attribute and called `chdir` at the start of the test:

```py
def test_foo(pytester: Pytester):
    pytester.mkdir("foo")
    pytester._path = pytester.path / "foo"
    pytester.chdir()
````

**Comment by nicoddemus** [comment]
The solution sounds to me.

Seems simple to implement too, would you like to contribute that?

**Comment by DetachHead** [comment]
#11951

**Comment by bluetech** [comment]
Have you considered using https://docs.pytest.org/en/latest/reference/reference.html#pytest.MonkeyPatch.chdir? This is available to every test, not pytester specific.

**Comment by DetachHead** [comment]
yeah that seems like a better solution, thanks. i didn't realize monkeypatch was its own fixture
