### ISSUE TITLE
Add custom reporting output

### ISSUE THREAD

**Issue by eldamir** [pytest-dev/pytest#1194]
after reading [this article](http://blog.mathieu-leplatre.info/your-tests-as-your-specs.html), I was wondering whether it would be possible to do something similar with pytest?

quick recap: The ability to customize the output of the test runner to fit a specific structure.

Using tests as specs is pretty common, and having the test runner output a structure that supports this paradigm would be truly great. I did not find anyting in the documentation that instructed me how to implement this. Is it already possible to control the output?

**Comment by RonnyPfannschmidt** [comment]
see pytest-sugar ?

**Comment by eldamir** [comment]
Well, they sure seem to control the output somehow. I'll have a look at the source. Thanks!
