### ISSUE TITLE
pytest 8.1.0.dev gives TypeError: Warning message must be str

### ISSUE THREAD

**Issue by pllim** [pytest-dev/pytest#11954]
Started noticing failures with `pytest 8.1.0.dev171+g9454fc38d`. I suspect it is caused by https://github.com/pytest-dev/pytest/pull/11804 .

In astropy , we have a warning class that is a grandchild of Python built-in `Warning` class, defined as follows (don't ask me why, I am just the messenger):

```python
class IllegalMinuteWarning(AstropyWarning):
    """
    Raised when a minute value is 60.

    Parameters
    ----------
    minute : int, float
    """

    def __init__(self, minute, alternativeactionstr=None):
        self.minute = minute
        self.alternativeactionstr = alternativeactionstr

    def __str__(self):
        message = (
            f"'minute' was found  to be '{self.minute}', which is not in range [0,60)."
        )
        if self.alternativeactionstr is not None:
            message += " " + self.alternativeactionstr
        return message
```

Works fine for years, until today. I think pytest type check is now too strict. Is this something you are able to relax a little on your end? Thanks!

Detailed log and more info here:

* https://github.com/astropy/astropy/issues/16016

**Comment by RonnyPfannschmidt** [comment]
That warning class doesn't implement a expected invariants

AKA it can't be used as category for a string message

I suppose it works by accident

If bug compatibility is easy enough we should support this while warning

**Comment by dhomeier** [comment]
I'd agree that not accepting a `Warning` as reported in #11959 looks like a bug, but for numerical inputs this makes more sense, and would be fairly easy to fix on the Astropy side.
