### ISSUE TITLE
Duplicated test collection when importing

### ISSUE THREAD

**Issue by joaodaher** [pytest-dev/pytest#11952]
### Discussed in https://github.com/pytest-dev/pytest/discussions/11949

<div type='discussions-op-text'>

<sup>Originally posted by **joaodaher** February  7, 2024</sup>
When I import a test in another file, pytest duplicates the test case.
Here's a minimal example:

`/test_a.py`
```
def test_case_a():
    print("Test A :: Case A")
```

`/test_b.py`
```
from test_a import test_case_a

def test_case_b():
    print("Test B :: Case B")
```

When I run `pytest --co` I get:
```
platform darwin -- Python 3.12.0, pytest-8.0.0, pluggy-1.4.0
rootdir: [suppressed]/pytest-dups
collected 3 items

<Dir pytest-dups>
  <Module test_a.py>
    <Function test_case_a>
  <Module test_b.py>
    <Function test_case_a>
    <Function test_case_b>
```

As you can see, `test_case_a` is collected twice (probably due to being present on test_b's namespace?).

This can get a lot worse with class-based tests, since all of them are duplicated.

Is this a feature or a bug?
Is there a way of preventing tests from being imported in the "wrong" module?</div>

**Comment by bluetech** [comment]
Did you see @nicoddemus's answer in the discussion?

In any case, why are you importing tests? It is somewhat unusual, so we need to understand the use case.

**Comment by joaodaher** [comment]
> Did you see @nicoddemus's answer in the discussion?

Yes, I did. Since he stated as a probable "unknown feature" I'd like to investigate further to assure that so I can contribute to fix, if that's really unexpected.

> why are you importing tests?

We use class-based tests. And some of these tests have useful helpers that other tests could reuse.

Our use-case is with Django tests (using pytest): one test has a `classmethod` with a useful serialization, and other tests reuse this method.
I'll give you an example:

`test_views_address.py`
```
from django.test import TestCase

class TestAddressView(TestCase):
    @classmethod
    def serialize_address(cls, address):
        return {"street": address.street}
```

`test_views_user.py`
```
from django.test import TestCase
from test_view_address import TestAddressView

class TestUserView(TestCase):
    @classmethod
    def serialize_address(cls, user):
        return {"name": user.name, "street": TestAddressView.serialize_address(user.address)}
```

There's plenty of workarounds or new designs to avoid the issue, but what lead me to think its an issue it's because **if I import the module and not the class, pytest does not duplicate the tests**.

`test_views_user.py`
```
from django.test import TestCase
import test_view_address

class TestUserView(TestCase):
    @classmethod
    def serialize_address(cls, user):
        return {"name": user.name, "street": test_view_address.TestAddressView.serialize_address(user.address)}
```

If you think it's really unexpected and it should not happen, I'll be glad to contribute.

**Comment by joaodaher** [comment]
Closed by the [discussion](https://github.com/pytest-dev/pytest/discussions/11949#discussioncomment-8415500)
