### ISSUE TITLE
Filter the test cases by the directory name

### ISSUE THREAD

**Issue by markshao** [pytest-dev/pytest#1197]
I have the test cases structure like the following
- tests
  - cm
    - cm1.py
    - cm2.py
  - dm
    - dm1.py
    - dm2.py
  - fm
    - fm1.py
    - fm2.py

I want to filter the test cases for execution by directory, for example I want to execute the .py test cases under cm and fm .

I try to use the -k to do the filter , but looks like the -k is the text match base on the module path and name , how can I filter out the test cases based on the directory name ?

**Comment by nicoddemus** [comment]
(I assume in your example you meant `cmd1.py` to be `test_cmd1.py`, and so on for the others)

> I want to filter the test cases for execution by directory, for example I want to execute the .py test cases under cm and fm .

The only way currently to match something with an `and` operator would be to use [marks](http://pytest.org/latest/mark.html), but you will have to write a few lines of code to add them for you automatically:

```python
# contents of tests/conftest.py
import os
def pytest_collection_modifyitems(items):
    for item in items:
        dir_base_name = os.path.basename(item.fspath.dirname)
        item.add_marker(dir_base_name)
```

This will add a mark to each test item with the same name as its directory, so you can use the `-m` flag in the command line to select those tests:

```
py.test -m "cm and fm"
```

> I try to use the -k to do the filter , but looks like the -k is the text match base on the module path and name , how can I filter out the test cases based on the directory name ?

That's correct, is a text match based on the "test id", which is something like:

```
tests/cm/test_cm1.py::test_foo
tests/cm/test_cm2.py::test_bar
tests/dm/test_dm1.py::test_baz
```

So you can select only the tests from the `cm` directory by passing `-k /cm/` on the command-line, but that won't let you select from both `cm` and `dm` directories as `-k` does not support expressions.

**Comment by The-Compiler** [comment]
You could just pass `tests/cm tests/fm` as directories to pytest (i.e. without `-k`), no?

**Comment by nicoddemus** [comment]
Err yes, that would be simpler instead of using `-k`. :stuck_out_tongue_closed_eyes: 

I assumed that the @markshao actual directory structure was more complicated than the example and went with the more complicated answers. :blush:

**Comment by markshao** [comment]
@The-Compiler  your solution looks easy to implement.  But I think this may not be the best solution for us :blush: . Because we have the deep hierarchy for the test directories . Which means we will have to specify some duplicate folder names like `tests/systest/buildnumber/cm tests/systest/buildnumber/cm  ...`

@nicoddemus I prefer your solution , this is the what I need .  But do you think we shall add a new keyword option to filter the against the relative directory in the future pytest release ?

**Comment by nicoddemus** [comment]
I'm not sure... there are tons of ways to specify how sub-directories should be matched, and that probably varies from project to project. It would warrant more discussion, at least.

But what could be done is to add that example to the documentation. Would you care to open a PR, perhaps? :smile:
