### ISSUE TITLE
Use the `Framework :: Pytest` trove classifier to build the plugin list

### ISSUE THREAD

**Issue by etianen** [pytest-dev/pytest#11973]
#### What's the problem this feature will solve?

I've just released a `pytest` plugin called [`logot`](https://github.com/etianen/logot), but because it isn't named `pytest-XXX`, it needs to be manually added to the plugin list (see #11972).

#### Describe the solution you'd like

It would be great if the `scripts/update-plugin-list.py` discovered plugins based on the `Framework :: Pytest` trove classifier.

As well as `logot`, this would correctly discover the `logassert`, `nuts` and `flask_fixture` plugins that currently require manual adding to the list. It would allow the manual list to be completely eliminated! 🔥 

#### Alternative Solutions

N/A

#### Additional context

Maybe this is impossible! But if you think this feature is a good idea, I'd be happy to investigate more and provide a PR! ❤️

**Comment by The-Compiler** [comment]
We used to have that, but it yields way too many false-positives due to many projects using that classifier to show "this project uses pytest for its tests".
