### ISSUE TITLE
Multiprocessing Issue

### ISSUE THREAD

**Issue by roshant-ska** [pytest-dev/pytest#11994]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by roshant-ska** [comment]
I am facing below issues when using Proces, Manager, Queue modules from multiprocessing package.
Issue 1:
When running unit test case with make python-test job, when I press CNTRL+C, the the processes created with pytest remains there and does not terminate on its own.

Issue2:
In integration test case, though the test case gets passed the pod created for pytest does not terminate and remains there.

The destructor code is as below:
self.process_manager.shutdown()
self.sub_process.terminate()
self.sub_process.join()

After removing the multiprocessing modules pytest behaves normally.

Please guide in this regard to handle the multiprocessing with pytest.
Please let me know if more inputs required.
Awaiting for your response.
Regards.

**Comment by nicoddemus** [comment]
@roshant-ska pytest just executes the test functions, if they never return then pytest will get stuck.

Can you post a minimal example reproducing the problem? Multiprocessing is a complex topic, and many many things can go wrong, so we need to discuss solutions over a MWE.
