### ISSUE TITLE
(🐞) pytester is influenced by an external `CI` environment variable

### ISSUE THREAD

**Issue by KotlinIsland** [pytest-dev/pytest#12009]
- [🚀] a detailed description of the bug or problem you are having
- [🚀] output of `pip list` from the virtual environment you are using
- [🚀 ] pytest and operating system versions
- [🚀] minimal example if possible

pytest 8.0.1, windows/mac/linux

This is very unfortunate, as unexpected differences in behaviour are observed between local development and CI execution.

```py
def test_ci(pytester):
    pytester.makepyfile("""
def test_something():
    assert [1, 2, 3] == [1, 4, 3]
    """)
    pytester.runpytest()
    assert 0
```
```
> pytest test.py
...
================================== FAILURES ===================================
_______________________________ test_something ________________________________

    def test_something():
>       assert [1, 2, 3] == [1, 4, 3]
E       assert [1, 2, 3] == [1, 4, 3]
E
E         At index 1 diff: 2 != 4
E         Use -v to get more diff

test_ci.py:2: AssertionError
=========================== short test summary info ===========================
FAILED test_ci.py::test_something - assert [1, 2, 3] == [1, 4, 3]
============================== 1 failed in 0.11s ==============================
...
```
```
> CI=1 pytest test.py
...
================================== FAILURES ===================================
_______________________________ test_something ________________________________

    def test_something():
>       assert [1, 2, 3] == [1, 4, 3]
E       assert [1, 2, 3] == [1, 4, 3]
E
E         At index 1 diff: 2 != 4
E
E         Full diff:
E           [
E               1,
E         -     4,
E         ?     ^
E         +     2,
E         ?     ^
E               3,
E           ]

test_ci.py:2: AssertionError
=========================== short test summary info ===========================
FAILED test_ci.py::test_something - assert [1, 2, 3] == [1, 4, 3]

  At index 1 diff: 2 != 4

  Full diff:
    [
        1,
  -     4,
  ?     ^
  +     2,
  ?     ^
        3,
    ]
============================== 1 failed in 0.13s ==============================
...
```

**Comment by nicoddemus** [comment]
Hi,

That's intentional, have been added in [`2.9.0`](https://docs.pytest.org/en/stable/changelog.html#id588).

> Comparisons now always show up in full when CI or BUILD_NUMBER is found in the environment, even when -vv isn’t used. Thanks [@The-Compiler](https://github.com/The-Compiler) for the PR.

Is this causing problems for you?

**Comment by nicoddemus** [comment]
That change was made 8 years ago, I wonder why this has not been a problem until now... :thinking: 

cc @The-Compiler in case he wants to chime in

**Comment by The-Compiler** [comment]
I'm honestly not sure if pytester should just paint over this. The output is different on CI in reality, and pytester pretending that's not the case sounds like more trouble than it's worth to me - just like there are output differences between e.g. different platforms.

**Comment by DetachHead** [comment]
this behavior is extremely frustrating especially since explicitly reducing the verbosity (`--verbosity=0`) seems to have no effect in CI

**Comment by RonnyPfannschmidt** [comment]
To My understanding one would need to explicitly monkey patch the ci env var atm
