### ISSUE TITLE
Cannot select parametrised test where there are special characters

### ISSUE THREAD

**Issue by nfx** [pytest-dev/pytest#12018]
we have the following test:

```python
@pytest.mark.parametrize(
    "ext,magic",
    [
        ("py", "# Databricks notebook source"),
        ("scala", "// Databricks notebook source"),
        ("sql", "-- Databricks notebook source"),
    ],
)
def test_uploading_notebooks_get_correct_urls(ext, magic, new_installation):
    ...
```

that results in `Wrong expression passed to '-k': test_uploading_notebooks_get_correct_urls[py-# Databricks notebook source]: at column 46: unexpected character "#"` when invoked with `-k`. I'm trying to figure out if we can escape values before passing them through `-k` or have some more lower-level interface, like [here](https://github.com/databrickslabs/sandbox/blob/main/acceptance/ecosystem/pytest_collect.py), that would allow filtering runs by test (which is also an option). please help.

<img width="987" alt="image" src="https://github.com/pytest-dev/pytest/assets/259697/3c84b331-7348-4f67-b1e1-e0f82638d72f">

# Workaround

Something like this works:

```python
def pytest_collection_modifyitems(items: list[pytest.Item], config: pytest.Config):
    deselected = []
    remaining = []
    for item in items:
        if item.name != os.environ['TEST_FILTER']:
            deselected.append(item)
            continue
        remaining.append(item)
    if not deselected:
        return
    config.hook.pytest_deselected(items=deselected)
    items[:] = remaining
```

**Comment by nicoddemus** [comment]
Hi @nfx,

One way to work around this is to specify the ids explicitly:

```python
@pytest.mark.parametrize(
    "ext,magic",
    [
        pytest.param("py", "# Databricks notebook source", id="py"),
        pytest.param("scala", "// Databricks notebook source", id="scala"),
        pytest.param("sql", "-- Databricks notebook source", id="sql"),
    ],
)
def test_uploading_notebooks_get_correct_urls(ext, magic, new_installation):
    ...
```

Back to your original issue, IFAIK we don't plan to support arbitrary characters in the mini-language used by `-k`.

Closing this for now, feel free to follow up with other questions. 👍
