### ISSUE TITLE
8.0.2 and 8.1.0 release planning

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#12026]
I propose we:

Release pytest 8.0.2 tomorrow (2024-02-24)

Release pytest 8.1.0 next week (~2024-03-02)

**Comment by nicoddemus** [comment]
Sounds good to me.

I will work on #11997 this weekend to hopefully get it into `8.1.0`. :+1:

**Comment by nicoddemus** [comment]
@bluetech do you think #11904 can be fixed by `8.1.0`, or it will need to wait for `8.2.0`?

**Comment by bluetech** [comment]
Will delay 8.1.0 (to next week?) to give #11997 and #12043 a chance to make it in.
