### ISSUE TITLE
Pytest misbehaves if a forked test doesn't exit properly

### ISSUE THREAD

**Issue by spikethehobbitmage** [pytest-dev/pytest#12028]
Currently, `pytest` doesn't properly handle tests that call `os.fork` if the child fails to exit with `os._exit`. This results in a duplicate `pytest` instance, including tearing down fixtures twice, running all subsequent tests twice, and generating two (possibly intermingled) reports.

Pytest 7.4.4 on Debian Linux, 'testing' release

This is the minimal test case that demonstrates the problem. The child returning normally will also trigger the bug.
```
def test_minimal():
    import os
    pid = os.fork()
    if pid == 0:
        # child process
        assert False
    # parent process
    os.waitpid(pid, 0)
```

The simplest solution is to check `os.getpid()` immediately before and after the test, and if they are different to call `os._exit`. These checks should be done after any other setup and before any other tear-down is performed.
```
fixture setup
pid = os.getpid()
run test
if pid != os.getpid():
    os._exit(1)
fixture tear-down
```

Writing a warning to `stderr` just before calling `os._exit` is the simplest method of warning the user that there is a problem. For a more robust solution, a rogue child process can be detected and reported by using a `socketpair`.
```
fixture setup
a, b = socket.socketpair() # call `b.set_inheritable` to also detect rogue subprocess children
pid = os.getpid()
run test
if pid != os.getpid():
  write an error message to a per-test log file
  os._exit(1)
b.close()
a.recv(1) # wait for all children to exit
fixture teardown
check for above error log, fail test if present
```
This method can hang if the child is hung, but that's little different from any other hung test and gives a clear warning that there is a problem.

I'm willing to write a patch, but I'm not familiar with pytest's codebase to know where to start. Any help would be appreciated.

- [X] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [X] pytest and operating system versions
- [X] minimal example if possible

**Comment by bluetech** [comment]
pytest is not going to add this, generally it's the responsibility of the one calling `fork` to handle it, it's not reasonable to ask pytest to do it.

You can perhaps achieve what you want by using [hooks](https://docs.pytest.org/en/stable/reference/reference.html#test-running-runtest-hooks).
