### ISSUE TITLE
Getting permission error with latest pytest versions 8.0.2

### ISSUE THREAD

**Issue by pashupati123** [pytest-dev/pytest#12034]
Description
When attempting to run pytest with a JSON file specified as an argument (pytest <test_file.py> -T <json_file>), I encounter a permission error with pytest versions higher than 7.4.4. The error is as follows:
```
/auto/cafy-ott/pasverma-cafykit/cafykit/env/lib/python3.11/site-packages/pluggy/_hooks.py:501: in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
/auto/cafy-ott/pasverma-cafykit/cafykit/env/lib/python3.11/site-packages/pluggy/_manager.py:119: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
/auto/cafy-ott/pasverma-cafykit/cafykit/env/lib/python3.11/site-packages/_pytest/python.py:211: in pytest_collect_directory
    if pkginit.is_file():
/auto/cafy-ott/python3.11.4/lib/python3.11/pathlib.py:1267: in is_file
    return S_ISREG(self.stat().st_mode)
/auto/cafy-ott/python3.11.4/lib/python3.11/pathlib.py:1013: in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
E   PermissionError: [Errno 13] Permission denied: '/lost+found/__init__.py'
```
This issue occurs specifically when the JSON file has read-only access with pytest version higher than 7.4.4
Steps to Reproduce:
  Upgrade pytest to version 8.0.0 or higher.
  Run pytest with the command pytest <test_file.py> -T <json_file> where <json_file> has read-only access.

Expected Behavior:
Pytest should be able to execute without encountering permission errors, even when the JSON file has read-only access, which is working with pytest version lower than equal to 7.4.4

Observation:
Providing an additional argument --rootdir='<non_empty_root_dir>' along with the pytest command resolves the permission error, even when the JSON file has read-only access.

pytest version : 8.0.2

**Comment by jhanm12** [comment]
@nicoddemus Can you please check this.

**Comment by jhanm12** [comment]
Also, this issue is permission issue is not hit in scripts when we set a single python path. This permission issue is hit, when we set 2 paths via the Python Path Env Variable.
```
export PYTHONPATH="${GIT_REPO}/lib:${OTHER_REPO}/lib"   
```

**Comment by jhanm12** [comment]
From 8.0.0 ::

```
====================================================================================== ERRORS ======================================================================================
________________________________________________________________________________ ERROR collecting . ________________________________________________________________________________
311_env/lib/python3.11/site-packages/pluggy/_hooks.py:493: in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
311_env/lib/python3.11/site-packages/pluggy/_manager.py:115: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
311_env/lib/python3.11/site-packages/_pytest/python.py:210: in pytest_collect_directory
    if pkginit.is_file():
../tools/python3.11.4/lib/python3.11/pathlib.py:1267: in is_file
    return S_ISREG(self.stat().st_mode)
../tools/python3.11.4/lib/python3.11/pathlib.py:1013: in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
E   PermissionError: [Errno 13] Permission denied: '/root/__init__.py'
```

**Comment by jhanm12** [comment]
rootdir is getting set as : From 8.0.0

```
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.11.4, pytest-8.0.0, pluggy-1.3.0
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: /
```

**Comment by bluetech** [comment]
Right, you don't want your rootdir to be `/`. See [here](https://docs.pytest.org/en/stable/reference/customize.html#initialization-determining-rootdir-and-configfile) how the rootdir is determined, the summary is it needs some sort of "anchor", like a `pytest.ini` or `pyproject.toml` or similar. But if you don't want this, explicitly setting `--rootdir` is always an option.
