### ISSUE TITLE
setup_modules seems to be ignored with 8.0.1 + `--doctest-modules`

### ISSUE THREAD

**Issue by skoudoro** [pytest-dev/pytest#12040]
Hi Pytest team,

In [DIPY project](https://github.com/dipy/dipy), we use a lot `setup_module` and `teardown_module` and everything was working like a charm.

Since pytest 8.0.1 and 8.0.2, it seems that `setup_module` and `teardown_module` are incompatible with `--doctest-modules` flag.

All our  tests fails when you add this flag due to unrecognized variable defined in `setup_module`.

This problem appears on Windows, Linux and macOS.

Let me know if you need more information concerning this issue. For now, we will just pin pytest to 8.0.0

Thank you for you feedback

**Comment by bluetech** [comment]
This has been reported in #12011, will be fixed in pytest 8.1, which will be released soon.

If you want a quicker solution, replacing `setup_module`/`teardown_module` with a pytest fixture would do the trick.
