### ISSUE TITLE
Newest version 8.1.0 leads an  unexpected error in my testcase.

### ISSUE THREAD

**Issue by zhulinJulia24** [pytest-dev/pytest#12059]
- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

```

error stack is:

    def _test_fixtures(item):
        fixturemanager = item.session._fixturemanager
        fixturedefs = []
    
        if hasattr(item, "_request") and hasattr(item._request, "fixturenames"):
            for name in item._request.fixturenames:
>               fixturedefs_pytest = fixturemanager.getfixturedefs(name, item.nodeid)
E               AttributeError: 'str' object has no attribute 'iter_parents'


```
Rollback to vertion 8.0.2, it works fine.

**Comment by The-Compiler** [comment]
You're accessing private API, not a bug that it changed, that's why it's not public...

Not much more that can be said without a more detailed stack trace.
