### ISSUE TITLE
ERROR: not found: .yaml

### ISSUE THREAD

**Issue by asztalosdani** [pytest-dev/pytest#12064]
I have a project, where I have a yaml file in the tests folder.
```
tests/
  conftest.py
  mock-send-batch-emails-queue.yaml
  test_email_service.py
main.py
```
Running pytest fails with the following error:
```
pytest -v tests/* --junitxml=test-reports/report.xml
============================= test session starts ==============================
platform linux -- Python 3.12.2, pytest-8.1.0, pluggy-1.4.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /opt/atlassian/pipelines/agent/build
plugins: mock-3.12.0
ERROR: not found: /opt/atlassian/pipelines/agent/build/tests/mock-send-batch-emails-queue.yaml
(no match in any of [<Dir tests>])
```
It fails on bitbucket, running on linux, but succeeds on my dev windows machine. Both are running pytest 8.1.0 and python 3.12

**Comment by bluetech** [comment]
Instead of `pytest tests/*` try `pytest tests/`.

**Comment by bluetech** [comment]
When you write `pytest tests/*` your shell expands it to `pytest tests/conftest.py tests/mock-send-batch-emails-queue.yaml tests/test_email_service.py`. Now pytest sees that you explicitly requested testing a file `tests/mock-send-batch-emails-queue.yaml`, which it can't do, so it fails. On the other hand, running `pytest test/` tells pytest that you want to test the directly, not particular files, and then it knows to omit irrelevant files like the yaml one.
