### ISSUE TITLE
Read tests to be executed from a file instead of from positional arguments

### ISSUE THREAD

**Issue by levsa** [pytest-dev/pytest#12079]
#### What's the problem this feature will solve?

I want to output a set of tests using `pytest --collect-only -q` to a file, and run selected subsets of it using `pytest` 

#### Describe the solution you'd like

I want to collect tests to run and put them in a file (supported today, except `-q` or a similar flag to leave out all output except the actual test names)):

```
> pytest --collect-only -q > tests_to_run.txt
```

And then tell `pytest` to run tests listed in that file (or from stdin), like e.g.:

```
> pytest --from-file tests_to_run.txt
```

I want to run selected subsets of the tests to find bugs caused by interdependencies between a set of tests.

**Comment by bluetech** [comment]
Hi,

We have an accepted issue about this #11871 so I'll close this one.
