### ISSUE TITLE
msg in pytest.exit(msg) doesn't get printed when called in pytest hook

### ISSUE THREAD

**Issue by BeyondEvil** [pytest-dev/pytest#1210]
OSX 10.10.4
pytest version 2.8.2
Python 2.7.6

In Conftest.py
```
import pytest
def pytest_configure(config):
    if condition not met:
        pytest.exit("oh noes")

```
pytest exits silently w/o printing 'msg' ("oh noes") regardless of any -s, -v, -q or -rx flags.

**Comment by markshao** [comment]
I can reproduce this in my environment , looks like the code in pytest_configure function is not executed .
