### ISSUE TITLE
Pytest has not attribute `StashKey`

### ISSUE THREAD

**Issue by EngineerHus** [pytest-dev/pytest#12107]
Hi All,

On our CI environment, we have been running our pytests for some time now, but weirdly now, we are seeing an error, which is `AttributeError: module 'pytest' has no attribute 'StashKey'`

We are running pytest with version 5.3.5 so my initial thought was maybe due to the 2 recent releases last week, maybe `StashKey` is not supported anymore so I had to do trial and error by installing different pytest versions and finding out which is the oldest pytest version that still supports this.

As of now, the oldest pytest version that supports `StashKey` seems to be 7.0.0. Could one of the devs please maybe update the docs so future pytesters would be able to figure this out?

Thanks

**Comment by nicoddemus** [comment]
Not sure what happened in your case, but `pytest.StashKey` is still available.

```
λ pytest --version
pytest 8.2.0.dev2+g0951cbc6e.d20240304

λ python
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytest
>>> pytest.StashKey
<class '_pytest.stash.StashKey'>
```

**Comment by bluetech** [comment]
@EngineerHus thanks for the suggestion, submitted #12108.

**Comment by nicoddemus** [comment]
Sorry @EngineerHus, I misunderstood the original post. Thanks. :+1:

**Comment by EngineerHus** [comment]
> @EngineerHus thanks for the suggestion, submitted #12108.

Much thanks
