### ISSUE TITLE
Make truncation threshold (ellipsis) configurable regardless the verbosity level

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#12111]
I found multiple similar unanswered question online such [stackoverflow.com/questions/38000993/how-can-i-get-my-assertions-in-pytest-to-stop-being-abbreviated-with-ellipsis](https://stackoverflow.com/questions/38000993/how-can-i-get-my-assertions-in-pytest-to-stop-being-abbreviated-with-ellipsis)

We need to make the truncation values configurable regardless of pytest verbosity level, especially as we know that changing general verbosity level has other side effects.

My opinion is that most people would want to run in minimal verbosity level (especially) on CI but have verbose errors for failed tests. If I run in verbose by default displaying the console log in the browser can be problematic, true for github actions and also most CI/CD system I know (none behaves nice with very long console logs).

Related:
- https://github.com/pytest-dev/pytest/issues/6682

**Comment by bluetech** [comment]
Check out https://docs.pytest.org/en/stable/reference/reference.html#confval-verbosity_assertions, added in pytest 8.
