### ISSUE TITLE
Also emit `PytestUnknownMarkWarning` for unknown marks given in `-m`

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#12166]
If we use `@pytest.mark` with a mark that does not exist, pytest warns about it:

```python
import pytest

@pytest.mark.one
def test_one():
    pass
```

results in:

```
  .../test_x.py:3: PytestUnknownMarkWarning: Unknown pytest.mark.one - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.one
```

This is to avoid silent failures, e.g. a test being marked `onne` and then never being executed.

---

However, a similar issue exists with `-m` too! If, with the code above, we use `pytest -m onne`, that results in:

```
============================= test session starts ==============================
collected 1 item / 1 deselected / 0 selected                                   

============================ 1 deselected in 0.43s =============================
```

Thanks to exit code 5 (`ExitCode.NO_TESTS_COLLECTED`), this can still be spotted, more or less. However, when using e.g. `pytest -m "slow or onne"`, it's not trivially visible anymore that a typo was made (assuming that some tests run due to the `slow` mark, of course).

Is there a good reason to not validate all marks passed into `-m` against the list of registered marks as well? Have we had an issue about this before? This gets pointed out every once in a while by participants in my pytest trainings, and I feel like I must have reported it before, but I can't seem to find anything.

**Comment by poulami-sau** [comment]
Hello! If I'm understanding correctly, I think you reported this same issue in #10514? I am interested in working on this issue, but I'm having a hard time trying to simulate the conditions, and would appreciate some guidance on this!

**Comment by The-Compiler** [comment]
Hah, so my memory didn't fail me, and I just didn't find it :see_no_evil:. Thanks, closing this one as a duplicate then. I'll answer the rest over there.

**Comment by The-Compiler** [comment]
Duplicate of #10514
