### ISSUE TITLE
No module named 'exceptiongroup'

### ISSUE THREAD

**Issue by oliverfunk** [pytest-dev/pytest#12177]
Hello,

I'm getting an error when trying to run pytest.

```python
_pytest/_code/code.py", line 56, in <module>
    from exceptiongroup import BaseExceptionGroup
ModuleNotFoundError: No module named 'exceptiongroup'
```
I'm on Python 3.10 and from what I can find, pytest supports 3.8+

ExceptionGroup was only added in Python 3.11

(see https://docs.python.org/3.11/library/exceptions.html#exception-groups vs 3.10)

The following line is causing the issue:
https://github.com/pytest-dev/pytest/blob/381593ccf0610840542ee2f18f565ce692fc4d8c/src/_pytest/_code/code.py#L55

I don't understand how I can be the first to pick up on this though so I'm pretty wary posting this issue.

Here are my versions:

```
pytest                        8.1.1
pytest-cov                    5.0.0
pytest-html                   4.1.1
pytest-json-report            1.5.0
pytest-metadata               3.1.1
```

**Comment by oliverfunk** [comment]
Okay I see what's happened.

For some reason, the `exceptiongroup` dep from this project did not install.

The dep. is listed here
https://github.com/pytest-dev/pytest/blob/381593ccf0610840542ee2f18f565ce692fc4d8c/pyproject.toml#L43

Best

**Comment by whateverforever** [comment]
same install problem here on python3.10 why this external dependency in the first place? especially in light of recent supply chain attacks

**Comment by The-Compiler** [comment]
@whateverforever You'll need to install pytest properly then, this it not a pytest issue. I feel like I'm stating the obvious here, but the response to supply chain attacks is not to stop using dependencies altogether and reinventing the wheel every time. The dependency is used to provide support for [exception groups](https://docs.python.org/3/tutorial/errors.html#tut-exception-groups) on older Python versions.

**Comment by whateverforever** [comment]
sure, every dependency is used for something. but why use a python3.11 feature if you want to support older versions? there are dependencies _on which you depend_, and there is fluff.

**Comment by The-Compiler** [comment]
You're free to use Python 3.11, in which case the backport isn't installed. :shrug:

**Comment by nicoddemus** [comment]
> but why use a python3.11 feature if you want to support older versions?

Just to clarify: we need to support the Python 3.11 feature in the same code base, that's why the backport is used. Note also that users in older versions might also be using the backport, in which case pytest will work as well.
