### ISSUE TITLE
junitxml doesn't escape newlines in attribute values

### ISSUE THREAD

**Issue by aivarannamaa** [pytest-dev/pytest#1218]
If error message has newlines in it then `<failure>`-s attribute `message` contains them verbatim, but they should be encoded, otherwise XML parser will lose them.

**Comment by dajose** [comment]
@nicoddemus has anyone check on this?

**Comment by nicoddemus** [comment]
@dajose I don't think so. I would love to review a PR and merge this in though. 😉

**Comment by nicoddemus** [comment]
Thanks @carlos-jenkins for the investigation.

The patch seems reasonable. I wonder though if we can use `xml.etree` to write that instead; I suppose that module is more well tested and reliable.

**Comment by nicoddemus** [comment]
> what do you think of just changing the bin_xml_escape to use xml.etree instead?

Sure, sounds good; it is definitely a step in the right direction. 👍

**Comment by nicoddemus** [comment]
Hmmm that's unfortunate, thanks again for tackling this. 👍 

> We could then change:
> 
> ```python
>         self.escape = {
>             u('"') : u('&quot;'), u('<') : u('&lt;'), u('>') : u('&gt;'),
>             u('&') : u('&amp;'), u("'") : u('&apos;'),
>             }
> ```
> 
> To:
> 
> ```python
>         self.escape = {
>             u('"') : u('&quot;'), 
>             u('<') : u('&lt;'), 
>             u('>') : u('&gt;'),
>             u('&') : u('&amp;'), 
>             u("'") : u('&apos;'),
>             u("\n") : u('&#x0a;'),
>         }
> ```

Perhaps the above would be simpler then? We don't even need a new pytest release for it, and should be simple to implement (which you already did actually) and test.

**Comment by RonnyPfannschmidt** [comment]
attribute escape and text escape have different rules, we should start to use a real compliant xml generator instead of the hack we have in place which "works"

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt definitely, I mentioned this (see https://github.com/pytest-dev/pytest/issues/1218#issuecomment-474622581). I was about to create #4970 but got side tracked, thanks for commenting which put me back on track. 👍 

@carlos-jenkins I still think that if you want to contribute that fix to `py` it would be great. It is simple and doesn't make current matters worse at all. But definitely we should find the time to use another xml generator for `junitxml` in the future.

**Comment by nicoddemus** [comment]
I'm OK with copying the functions and use them to fix this bug now. But we really should go ahead and rewrite `junitxml` to use `xml.etree` when someone has the time.
