### ISSUE TITLE
--pastebin fails when pasting non-ascii characters

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1219]
The following test fails when using `--pastebin=all` in both Python 2.7 and Python 3.5 (with different errors):

```python
# encoding: utf-8
def test():
    assert '☺' == 1
```

**Comment by RonnyPfannschmidt** [comment]
wasnt this one fixed by the pr?

**Comment by nicoddemus** [comment]
No, unfortunately only after it was merged I realized that this might still
be a problem...

Em qui, 3 de dez de 2015 10:42, Ronny Pfannschmidt <notifications@github.com>
escreveu:

**Comment by RonnyPfannschmidt** [comment]
i understand, i'll try to add a xfailing test after work

**Comment by nicoddemus** [comment]
Thanks but there's no need, I got a failing test already on my computer, just didn't have time yesterday to fix it. :smile:

**Comment by RonnyPfannschmidt** [comment]
ah, good then :)
