### ISSUE TITLE
tmp_path_factory documentation has circular links

### ISSUE THREAD

**Issue by AngledLuffa** [pytest-dev/pytest#12202]
Starting from here:

https://docs.pytest.org/en/6.2.x/reference.html#tmp-path-factory-factory-api

There is a small snippet:

```
[tmp_path_factory](https://docs.pytest.org/en/6.2.x/reference.html#id51)

Tutorial: [The tmp_path_factory fixture](https://docs.pytest.org/en/6.2.x/tmpdir.html#tmp-path-factory-example)

tmp_path_factory is an instance of [TempPathFactory](https://docs.pytest.org/en/6.2.x/reference.html#pytest.TempPathFactory):

final class TempPathFactory[[source]](https://docs.pytest.org/en/6.2.x/_modules/_pytest/tmpdir.html#TempPathFactory)
Factory for temporary directories under the common base temp directory.

The base directory can be configured using the --basetemp option.
```

Clicking on the Tutorial link takes you here:

https://docs.pytest.org/en/6.2.x/tmpdir.html#tmp-path-factory-example

```
The tmp_path_factory fixture

The tmp_path_factory is a session-scoped fixture which can be used to create arbitrary temporary directories from any other fixture or test.

It is intended to replace tmpdir_factory, and returns [pathlib.Path](https://docs.python.org/3/library/pathlib.html#pathlib.Path) instances.

See [tmp_path_factory API](https://docs.pytest.org/en/6.2.x/reference.html#tmp-path-factory-factory-api) for details.
```

where the only thing to do is click back to the same API snippet from above

An actual example of how to make session-scoped temporary directories would be a helpful addition.  It could be as simple as mentioning that the following is the way to make temporary directories:

```
    tmp_directory = tmp_path_factory.mktemp(basename)
```

**Comment by RonnyPfannschmidt** [comment]
at first glance this no longer is the case in the 8.x documentation

**Comment by AngledLuffa** [comment]
Ah, well, I suppose I can thank Google for sending me to the 6.2 docs when I searched `pytest tmp_path`

Thanks for the response!
