### ISSUE TITLE
Conditional test parametrization

### ISSUE THREAD

**Issue by chrysle** [pytest-dev/pytest#12201]
#### What's the problem this feature will solve?

I'm currently writing tests that make use of Windows and POSIX paths to test that a functionality works cross-platform.
ATM, I'm making use of the `pytest.mark.skipif` decorator to detect the platform and just copy my tests, as only the parameters are different.

#### Describe the solution you'd like

I found it might be much more easy if I somehow could parametrize my test according to the platform detected, thus have a conditional parametrization. I'm thinking of something like the following:

```python
@pytest.mark.parametrize("path", {"linux" : ["/opt/path/", "/home/user/", "~/path"], "windows" : ["C:\Program Files\", "D:path"]}, cond="windows" if sys.platform.startswith("win"))
def test_this_path_works(path):
    # ...
```

I'm not sure any of this is feasible.

**Comment by chrysle** [comment]
Thanks for the quick response!

> is there perhaps a more complex use-cases that makes the conditions seem necessary

I know of none, right now. Might think about it some more, but I'm no `pytest` / testing expert.

**Comment by RonnyPfannschmidt** [comment]
thanks, closing this then
