### ISSUE TITLE
setUpModule/tearDownModule not invoked

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#12219]
In #4064, on pytest 2.x, it was determined that unittest supported the unittest `setUpModule` and `tearDownModule`.

However, with pytest 8.x, I'm finding that it's not supported, even though the [docs say it is](https://github.com/pytest-dev/pytest/blob/58844247f7ae4a7a213a73c8af2462253b3d8fc7/doc/en/how-to/unittest.rst?plain=1#L28).

In particular, I'm porting CPython's [test_tarfile](https://github.com/python/cpython/blob/main/Lib/test/test_tarfile.py) to [backports.tarfile](/jaraco/backports.tarfile). When I run the tests, the setUpModule is never called.

Interestingly, the hook does seem to be honored in a minimized example.

```python
 draft @ cat test_.py
def setUpModule():
    print(setUpModule.__name__)

def tearDownModule():
    print(tearDownModule.__name__)

def test():
    print(test.__name__)

def test2():
    print(test2.__name__)
 draft @ pip-run pytest -- -m pytest -s
============================================================== test session starts ===============================================================
platform darwin -- Python 3.12.2, pytest-8.1.1, pluggy-1.4.0
rootdir: /Users/jaraco/draft
collected 2 items                                                                                                                                

test_.py setUpModule
test
.test2
.tearDownModule


=============================================================== 2 passed in 0.00s ================================================================
```

If on the other hand, I add the following to `conftest.py`, the setup/teardown methods are called:

```python
@pytest.fixture(scope='module', autouse=True)
def setup_and_teardown_module(request):
    request.module.setUpModule()
    try:
        yield
    finally:
        request.module.tearDownModule()
```

But it seems like that should be unnecessary if unittest's setUpMethod and tearDownMethod are supported.

**Comment by bluetech** [comment]
It should work, and it does work in the minimal example you gave, so there is probably something in `backports.tarfile` that is causing it. Can you try to narrow the cause down? Like disable plugins, disable certain configs etc?

**Comment by jaraco** [comment]
After bisecting the differences, it seems the issue is isolated to pytest 8.0.x and only when using `--doctest-modules`.

```
 draft @ pip-run 'pytest<8.1' -- -m pytest -s --doctest-modules
WARNING: Skipping /opt/homebrew/lib/python3.12/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
DEPRECATION: Loading egg at /opt/homebrew/Cellar/tbb/2021.12.0/lib/python3.12/site-packages/TBB-0.2-py3.12-macosx-14.0-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
WARNING: Skipping /opt/homebrew/lib/python3.12/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openvino 2024.0.0 requires openvino-telemetry>=2023.2.1, which is not installed.
WARNING: Skipping /opt/homebrew/lib/python3.12/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.12/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.12/site-packages/packaging-24.0.dist-info due to invalid metadata entry 'name'
============================================================== test session starts ===============================================================
platform darwin -- Python 3.12.3, pytest-8.0.2, pluggy-1.4.0
rootdir: /Users/jaraco/draft
collected 2 items                                                                                                                                

test_.py test
.test2
.

=============================================================== 2 passed in 0.00s ================================================================
```

I'd probably not have encountered this issue but for having [pinned against pytest 8.1](https://github.com/jaraco/skeleton/commit/6ff02e0eefcd90e271cefd326b460ecfa0e3eb9e), a pin I'm going to have to [expand](https://github.com/pytest-dev/pytest/pull/12208#issuecomment-2054035740).

**Comment by jaraco** [comment]
Given that it's no longer an issue with pytest 8.2, I guess there's no more to be done. I did confirm that there's no regression with #12208 (using `pip-run git+https://github.com/pytest-dev/pytest@refs/pull/12208/head -- -m pytest -s --doctest-modules`).

**Comment by jaraco** [comment]
By the way, I also tested with `pytest<8` and the behavior worked as expected, so the regression was apparently only in the 8.1.x series.
