### ISSUE TITLE
More granular scripting interface

### ISSUE THREAD

**Issue by joemarshall** [pytest-dev/pytest#12224]
#### What's the problem this feature will solve?
I'm using pytest (running in linux) to run tests in pyodide (in a web browser, scripted via selenium).

For most things, this works like so:

1) Startup pyodide on browser
2) In pyodide call `pytest.main("--collect-only")` to get list of tests
3) Generate (linux side) test functions using `pytest_generate_tests` on a template function.
4) For each test: call `pytest.main("test_path/test_name")`

Where it doesn't work nicely is when tests use session fixtures. Especially session fixtures that modify internal C++ library state somehow and don't provide any way to unmodify it. Because the session fixture thinks everything will be torn down nicely at the end of a session, it leaves stuff broken, so the next pytest.main call breaks everything. Even without that, it is also slow when a session fixture does any amount of processing work.

#### Describe the solution you'd like

What I want is to be able to manually call functions to do each bit of the test run e.g.:
1) `pytest.scripting.collect(args)->TestList` Collect tests, return the list of tests
2) `session = pytest.scripting.start_session(config:Config)->Session`   Initialize session object
3) `session.run_test(test_fn)` Run a single test
4) `session.end()` Finish and teardown everything

That way, my startup function could call `collect`, then I could have a session level fixture on linux side which called `start_session` and `session.end` on the pyodide side, and each of my test functions on linux side could just call `session.run_test(test_fn)`

#### Alternative Solutions

Currently I bring up a new pyodide per call to `pytest.main`. 

However this means:

1) Load pyodide
2) Import required modules 
3) pytest.main <test_file_name>

And step 1 and 2 take approx 10 seconds which is annoying. To workaround, rather than calling through per test (which would take hours or days to complete), I call through per test file, but then I lose the nice output for each test from pytest.

#### Additional context
This is a bit specific to people using pytest to script remote tests, but I suspect there are more use cases than just pyodide / webassembly that I'm not thinking about where one has a high featured python interpreter at one end and something more stupid at the other end.

**Comment by RonnyPfannschmidt** [comment]
the requested feature is not feasible given the design of pytest and the work it would need to change around things that much (its pretty much the size of a rewrite)

for clarity 
* why did you use one call to pytest per test instead of all tests
* why do you generate tests with templates - that sounds hostile to the way pytest usually does things
* why is a list of tests without parameters necessary to inform generate-tests

i

**Comment by RonnyPfannschmidt** [comment]
a different workaround would be to have a pytest plugin object that manages the session scoped details and passing it in to each pytest.main call with the expectation that the teardown happens after all pytest runs

ideally the c++ libraries would stop being test-hostile and provide a way to undo the state

**Comment by joemarshall** [comment]
The reason for one call to pytest per test is because the controlling pytest runner is running in a different python interpreter than the tests are running on. 

So we have 
1. The pyodide python interpreter, running in a web browser. I can currently communicate with that only by dispatching python statements and waiting for the result. This is where the module I want to test is. 
2. linux python. This is where I am running the tests from.  

The idea of this change was that I could essentially proxy pytests through to the pyodide python.

Maybe the answer is just to hack in some way to run the full pytest inside pyodide, and get the output before main returns, I might be able to do that using browser automation somehow...

**Comment by joemarshall** [comment]
If it's hard to do here, I think I'm probably better off dealing with it at my end, so I'll close this.
