### ISSUE TITLE
--pdb causes stderr/stdout output to be hidden

### ISSUE THREAD

**Issue by foxx** [pytest-dev/pytest#1223]
For some reason, if I specify `--pdb`, the stdout/stderr capture output doesn't get printed, neither before or after the `pdb` shell.

Here are the steps to reproduce.

### Test file

```
$ cat hello.py
def test_wtf():
    print("WTFWTFTWF")
    raise Exception()
```

### Without PDB

```
$ py.test hello.py
============================= test session starts ==============================
platform linux -- Python 3.4.3, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /vagrant, inifile:
plugins: cov-2.2.0, capturelog-0.7
collected 1 items

hello.py F

=================================== FAILURES ===================================
___________________________________ test_wtf ___________________________________

    def test_wtf():
        print("WTFWTFTWF")
>       raise Exception()
E       Exception

hello.py:3: Exception
----------------------------- Captured stdout call -----------------------------
WTFWTFTWF
================= 1 failed, 1 pytest-warnings in 0.02 seconds ==================
```

### With PDB

```
$ py.test hello.py  --pdb
============================= test session starts ==============================
platform linux -- Python 3.4.3, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /vagrant, inifile:
plugins: cov-2.2.0, capturelog-0.7
collected 1 items

hello.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    def test_wtf():
        print("WTFWTFTWF")
>       raise Exception()
E       Exception

hello.py:3: Exception
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /vagrant/hello.py(3)test_wtf()
-> raise Exception()
(Pdb)


================= 1 failed, 1 pytest-warnings in 4.39 seconds ==================
```

**Comment by nicoddemus** [comment]
I think here's [the line](https://github.com/pytest-dev/pytest/blob/master/_pytest/pdb.py#L56) with the problem... `suspendcapture` returns the `out` and `err` contents which should be printed at that point, but is thrown away.

**Comment by foxx** [comment]
Thanks for the quick reply, looks like you're right, it should instead be doing something like;

```
out, err = capman.suspendcapture()
    if outcome.excinfo is not None:
        sys.stdout.write(out)
        sys.stderr.write(err)
```

**Comment by RonnyPfannschmidt** [comment]
For correct output you need to obtain the terminal writer plugin, like settrace does for example

**Comment by foxx** [comment]
@RonnyPfannschmidt Sorry I'm not quite following, are you saying this is a code bug or user error?

**Comment by nicoddemus** [comment]
@foxx I think Ronny meant about the code you posted, that you should use the terminal writer plugin instead of writing directly to `sys.stdout` or `sys.stderr`.

**Comment by RonnyPfannschmidt** [comment]
Exactly, thanks for the clarification

**Comment by nicoddemus** [comment]
@foxx any chance of opening a PR with this fix? :grin:

**Comment by foxx** [comment]
Just tried getting this to work locally, but can't seem to figure it out.

```
def pytest_configure(config):
    ....
    PdbInvoke._config = config
    ....

def pytest_exception_interact(self, node, call, report):
    import _pytest.config
    capman = node.config.pluginmanager.getplugin("capturemanager")
    if capman:
        capman.suspendcapture(in_=True)
    tw = _pytest.config.create_terminal_writer(self._config)
    tw.line()
    tw.sep(">", "PDB exception interact (IO-capturing turned off)")
    _enter_pdb(node, call.excinfo, report)
```

This is an almost exact copy of what is being done with `set_trace`, as seen here;

```
            capman = self._pluginmanager.getplugin("capturemanager")
            if capman:
                capman.suspendcapture(in_=True)
            tw = _pytest.config.create_terminal_writer(self._config)
            tw.line()
            tw.sep(">", "PDB set_trace (IO-capturing turned off)")
            self._pluginmanager.hook.pytest_enter_pdb()
```

There's a lot of monkeypatching and magic in here that I don't really understand, I could probably figure it out but it would take me 7396749373 times longer than others with an understanding of the internals.

If someone can give me a pointer in the right direction then I'll happily try again

**Comment by foxx** [comment]
I've also tried calling `write()` directly with `out/err`, with no effect;

```
        if capman:
            out, err = capman.suspendcapture(in_=True)
        tw = _pytest.config.create_terminal_writer(self._config)
        tw.line()
        tw.sep(">", "PDB exception interact (IO-capturing turned off)")
        tw.write(out)
        tw.write(err)
```

Although `tw.write("wtf")` seems to work fine.

**Comment by nicoddemus** [comment]
I would suggest to dig directly into the pytest's source instead of trying to muck around with the plugins. I think it would be just a matter of changing the code around [this line](https://github.com/pytest-dev/pytest/blob/master/_pytest/pdb.py#L56) to something like this (untested):

```python
    def pytest_exception_interact(self, node, call, report):
        capman = node.config.pluginmanager.getplugin("capturemanager")
        if capman:
            out, err = capman.suspendcapture(in_=True)
            sys.stdout.write(out)
            sys.stdout.write(err)
        _enter_pdb(node, call.excinfo, report)
```

I would leave out trying to use `"terminalwriter"` until this was working (and even then I'm not it would give out much).

**Comment by foxx** [comment]
Yeah that works much better, I would have done this before but was stuck trying to make `terminalwriter` work. PR coming shortly.
