### ISSUE TITLE
Inconsistency in skipif example

### ISSUE THREAD

**Issue by zenhack** [pytest-dev/pytest#1224]
The first two examples in this section of the documentation:

http://pytest.org/latest/skipping.html#skip-all-test-functions-of-a-class-or-module

Are internally inconsistent. The docstring for `test_function` says  `"will not be setup or run under 'win32' platform"` (and the class name `TestPosixCalls` is suggestive of this), but the actual condition passed to `skipif` (as well as `reason`) is the opposite: the tests will *only* be run on windows

**Comment by nicoddemus** [comment]
Good catch, thanks!

**Comment by zenhack** [comment]
You're welcome!
