### ISSUE TITLE
Since 8.2.0, automatic multiprocessing causes race conditions in my project

### ISSUE THREAD

**Issue by Schwaneberg** [pytest-dev/pytest#12278]
I got a project that cannot be tested with parallelism, as it requires exclusive access to some resources.
Unfortunately, this also applies during unit testing. This wasn't a problem up to pytest 8.1.2, but it is since 8.2.0.
Since 8.2.0, pytest instantly spawns six child processes, which are blocking each other.
I couldn't find a switch to turn this off nor could I identify the PR that caused this (yet).

**Comment by RonnyPfannschmidt** [comment]
More context needed 

Core pytest doesn't start processes at all

**Comment by alkino** [comment]
Hello, in our case (I and @pramodk that link the issue above):
We have reproducible segfaults with `pytest 8.2.0` on our code.
Once we set pytest back to `8.1.1` it works again.
Running with `pytest 8.2.0` with `-v` or by specifying all files instead of the directory works too (`pytest dir/file1.py dir/file2.py` instead of `pytest dir`).

**Comment by fossdd** [comment]
This can be reproduced by running `pytest` (v8.2.0) on [waitress](https://github.com/Pylons/waitress) or [black](https://github.com/psf/black)

**Comment by Schwaneberg** [comment]
I couldn't generate a minimal failing example yet. I'd like to reopen the
issue soon.

Am So., 26. Mai 2024 um 03:52 Uhr schrieb github-actions[bot] <
***@***.***>:

**Comment by The-Compiler** [comment]
@fossdd What is "this" exactly? As already mentioned, pytest doesn't do any parallelism itself. As for black, it [runs pytest 8.2.0](https://github.com/psf/black/actions/runs/9104541058/job/25028594027#step:6:81) on CI just fine... I also tried running the waitress tests locally with pytest 8.2.1 and they work fine.

Please be more specific - what exactly is happening? Are you sure it's related to this issue at all?
