### ISSUE TITLE
Support marker keyword arguments in marker expression (test selection via `-m`)  

### ISSUE THREAD

**Issue by lovetheguitar** [pytest-dev/pytest#12281]
#### What's the problem this feature will solve?

It's possible to create custom markers like so:
```py
@pytest.mark.my_device_under_test
```

This marker can the be used to de/select tests via marker expressions, e.g.:
`pytest -m "not my_device_under_test"`

It is also possible to define keyword arguments for custom markers, e.g.:

```py
@pytest.mark.my_device_under_test(with_serial="1234")
```

Now, it would be amazing to select tests further depending on their keyword arguments + values, e.g.:

`pytest -m "my_device_under_test(with_serial="1234)"`

So only tests with that specific marker + that specific keyword argument+value would be run.

#### Describe the solution you'd like

Marker keyword argument selection in pytest's marker expression.

#### Alternative Solutions

- There was a `nose` test plugin, which supported something similar [here](https://github.com/nose-devs/nose/blob/master/nose/plugins/attrib.py). This could be ported to pytest but comes with it's own `attr` decorator.

- A pytest plugin could probably do this in an extra step as well, but would somehow need to disable pytest's internal marker selection plugin [here](https://github.com/pytest-dev/pytest/blob/main/src/_pytest/mark/__init__.py#L261) as it would collide/fail otherwise.

#### Additional context
When skimming through the code I saw that @bluetech implemented a custom parsers some years ago. I'm not very familiar with the topic, as in how much effort it would be support such feature. I'd be interested to contribute though.

**Comment by bluetech** [comment]
The feature request makes sense to me, I think it would be great to allow matching on mark arguments (there are two kinds -- positional and keyword arguments), and something like the function call syntax seems natural for this.

For them match expression grammar, it shouldn't pose a big challenge to add. We would need to decide whether the argument values (the `1234` in your example) can be just idents (simple), or more complex, e.g. to support `my_device_under_test(with_serial=1234 or 5678)` etc., which would be more complex.

The bigger implementation issue would be the evaluation of the expression. Currently, to optimize the evaluation, we compile the expression to a python AST, then `eval` the AST with an environment ("locals") where every ident returns either True (if matches) or False. This will need to be extended to support the function-call syntax. As a quick thought, we could replace the `locals` hack with injecting some `$match` symbol into the `eval` environment which has the form `matcher(name, *args: str, **kwargs: str)` (assuming we only allow idents).

**Comment by nicoddemus** [comment]
If we are to implement this, I propose we keep it simple, as it would be possible to also write `my_device_under_test(with_serial=1234) or my_device_under_test(with_serial=5678)`.

**Comment by ckutlu** [comment]
Running into this thought myself, I was wondering if we could instead consider a bit of a tangent to avoid pitfalls mentioned by @The-Compiler. How about introducing a new interface called `pytest.mark.annotated(*args: str)`?

It would look like:
```python
@pytest.mark.annotated("annotation1", "annotation2", ...)
def test_my_function(...):
    pass
```
The selection can be with a slightly specialized syntax:
```
pytest -m [annotation1]
```
which can be combined with other non-annotated markers if needed:
```sh
pytest -m "awesome and [annotation1] and [annotation2]"
```
This is surely limiting, but maybe that's not a bad thing. For my use case, this would help with adding bug number/jira ticket annotations to test cases.
