### ISSUE TITLE
Support Dark Mode for Pytest Docs Website

### ISSUE THREAD

**Issue by cverrier** [pytest-dev/pytest#12290]
#### What's the problem this feature will solve?

Reading the documentation in the evening can be quite uncomfortable due to the current (very bright) theme of [the docs website](https://docs.pytest.org/).

#### Describe the solution you'd like

Having the option to turn on/off a dark theme for [the docs website](https://docs.pytest.org/).

**Comment by The-Compiler** [comment]
We use the [Pallets Sphinx theme](https://github.com/pallets/pallets-sphinx-themes) which [doesn't seem to](https://github.com/pallets/pallets-sphinx-themes/issues/48) offer a dark mode.

It looks like even Pallets has [plans to switch](https://github.com/pallets/pallets-sphinx-themes/issues/97) to [Furo](https://pradyunsg.me/furo/quickstart/) which does.

Maybe we should reevaluate #6402 (where we ended up upgrading our theme to upstream Pallets in #6453) and instead adopt Furo? I'd be +1 on that.

**Comment by nicoddemus** [comment]
👍 from me too, however I probably won't have time to work on this, but would be happy to review the work if someone does tackle this.

**Comment by jwk33** [comment]
👍 I'm all for dark mode docs everywhere. I'd like to have a go at this, though I suspect a switch to Furo might mean a few design changes to the site. It would be useful to use this issue to discuss the design if it's the right forum to do so.

**Comment by samjirovec** [comment]
Hey all, I took some time to do a quick conversion from Flask to Furo. Only big design change was with the side-nav turning into a note + the main side-nav now being scrollable. 

https://github.com/pytest-dev/pytest/pull/12326

**Comment by cverrier** [comment]
Thanks a lot @samjirovec, I tried the dark mode and it looks really good! :rocket:

Since this feature has already been merged with commit cbf6bd9, I will close this issue.
