### ISSUE TITLE
Incorrect confcutdir inferred when rootdir is under a symlink directory

### ISSUE THREAD

**Issue by buddly27** [pytest-dev/pytest#12291]
When a test directory is nested within a symlinked directory, it can lead to errors when the 'rootdir' or the invocation directory targets the unresolved path, especially when the symlink targets a different storage structure.

```bash
> ln -s /tmp/test /path/to/test/path
> cd /tmp/test
> pytest --rootdir=/tmp/test .

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
...
/usr/lib/python3.10/path lib.py:1097: PermissionError
=========================== Short test summary info ============================
ERROR ../../path/to/test/path::dir - PermissionError: [Errno 13] Permission denied: '/..../__init__.py'
=============================== 1 error in 0.14s ===============================

> pytest --rootdir=. /tmp/test 
# Same error ...
```
This issue does not occur when both the 'rootdir' and invocation directory use the same path (resolved or unresolved).

The invocation directory defaults to [Path.cwd()](https://github.com/pytest-dev/pytest/blob/84e59af8c829de659efb339d5a9c7cec98eee719/src/_pytest/config/__init__.py#L1042-L1045) which resolves the symlink, and relative entries seem to be normalized via [pathlib.absolutepath](https://github.com/pytest-dev/pytest/blob/97610067acf220b13cc4c6fca34e5aac4834b04d/src/_pytest/pathlib.py#L927C5-L927C17) (using `os.path.abspath` under the hood), which also returns a resolved path in some situations:
```bash
> pwd
/tmp/test

> python -c "import pathlib; print(pathlib.Path.cwd())"
/path/to/test/path

> python -c "import os; print(os.path.abspath('.'))"
/path/to/test/path
```

By default, the 'confcutdir' value is [inferred from the 'rootdir' value](https://github.com/pytest-dev/pytest/blob/84e59af8c829de659efb339d5a9c7cec98eee719/src/_pytest/config/__init__.py#L1401), which is [inferred from the invocation path](https://github.com/pytest-dev/pytest/blob/84e59af8c829de659efb339d5a9c7cec98eee719/src/_pytest/config/findpaths.py#L201), so it doesn't seem to be a problem. But in cases where the invocation path is defined to use the resolved path, while the 'rootdir' value is defined to use the unresolved path (or vice versa), the Session collector may encounter difficulties determining where to stop when searching for configs:
https://github.com/pytest-dev/pytest/blob/84e59af8c829de659efb339d5a9c7cec98eee719/src/_pytest/main.py#L861-L869

This issue could be solved by automatically resolving the value used for 'rootdir', but I'm not sure if there are any drawbacks to this approach (aside from performance).

I ran these tests on MacOS and Linux using Pytest 8.2.0 and Python 3.10.

I also setup a small repository to reproduce the errors via a Github workflow for more details:
https://github.com/buddly27/pytest-issue/actions/runs/8973032152/job/24642315352

**Comment by bluetech** [comment]
It seems like `Path.cwd()`/`os.getcwd()` always resolve symlinks.

The possible options that I can see:

1. Use `os.environ['PWD']` instead os `cwd()` on unix for the invocation path, this gives the shell-provided unresolved CWD.
2. Resolve the user-provided `--rootdir`.
3. Keep as is.

Option 1 feels a bit dubious. It is tempting but I think it will cause other breakage...

Option 2 seems wrong, the use explicitly specified a path so I think we should respect it.

This leaves option 3. I'd say the best thing to do is what you did, use the resolved rootdir on your side.

I'll close the issue but happy to hear other opinions.
