### ISSUE TITLE
pytest life cycle (fixture scoped session)

### ISSUE THREAD

**Issue by MoElleuch** [pytest-dev/pytest#12298]
### Discussed in https://github.com/pytest-dev/pytest/discussions/12295

<div type='discussions-op-text'>

<sup>Originally posted by **MoElleuch** May  8, 2024</sup>
When using fixtures scoped to session, I initially expected that all fixtures with a session scope would be executed before any test case (for setup) and after all test cases (for teardown). However, I didn't observe the expected behavior. In my first attempt, when I implemented each test case with its own fixture scoped=session, I found that the fixture was executed only for that specific test case. In my second attempt, I tried implementing all fixtures scoped in the file conftest.py i found this behavor :

**INFO     root:conftest.py:7 setup session 5
INFO     root:conftest.py:15 setup session 4**
INFO     root:test_tca1_4.py:12 setup class 4
INFO     root:test_tca1_4.py:19 function setup 4
INFO     root:test_tca1_4.py:28 I'm a test method from a test class 4
INFO     root:test_tca1_4.py:21 function Teardown 4
INFO     root:test_tca1_4.py:14 teardown class 4
INFO     root:conftest.py:17 teardown session 4
INFO     root:conftest.py:10 teardown session 5
**INFO     root:conftest.py:7 setup session 5
INFO     root:conftest.py:15 setup session 4**
INFO     root:test_tca1_5.py:24 setup module 5
INFO     root:test_tca1_5.py:19 setup class 5
INFO     root:test_tca1_5.py:30 function setup 5
INFO     root:test_tca1_5.py:37 function setup 5.1
INFO     root:test_tca1_5.py:45 I'm a test method from a test class 5
INFO     root:test_tca1_5.py:39 function Teardown 5.1
INFO     root:test_tca1_5.py:32 function Teardown 5
INFO     root:test_tca1_5.py:21 teardown class 5
INFO     root:test_tca1_5.py:26 teardown module 5
INFO     root:conftest.py:17 teardown session 4
INFO     root:conftest.py:10 teardown session 5

pytest version tested (7.2.0, 7.2.2, 8.0.0) 

**Could anyone help me understand the behavior of pytest and how I can ensure that pytest executes fixtures scoped at the session level only once, at the start of execution and at the end?**</div>

**Comment by The-Compiler** [comment]
No point in opening a duplicate issue before it's clear that this is actually a pytest issue.
