### ISSUE TITLE
Remove plugins_index from docs?

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1229]
I think currently the plugins index is redundant, since we have [plugincompat](plugincompat.herokuapp.com) which is updated daily with the list of plugins... plus it generates a ton of warnings about external images being used, which is a little annoying.

What do you guys think? 

@RonnyPfannschmidt @hpk42 @The-Compiler @flub @bubenkoff

**Comment by RonnyPfannschmidt** [comment]
i like the idea, it also removes a error prone step

**Comment by nicoddemus** [comment]
If nobody opposes it, I will remove it tomorrow.

**Comment by hpk42** [comment]
fine to remove it.  and i think the columsn should be "name,summary,homepage,compat-py27,compat-py34" because people come from it through the "3rd party plugins" links from pytest.org and may want to first now what a plugin does before checking on compat etc.
