### ISSUE TITLE
dist-info of vendored packages are missing from devpi based releases

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1230]
that makes the life of distro packagers harder than it should i think

**Comment by hpk42** [comment]
sorry, could you be more verbose?  devpi does "setup.py sdist" e.g. and takes the result to upload it.  What exactly is missing and how does it relate to devpi?

**Comment by RonnyPfannschmidt** [comment]
The dist info folder of pluggy, which is a useful artifact of the pip based installation isn't part of the sdist

**Comment by RonnyPfannschmidt** [comment]
i think this is also fixed by #1186
