### ISSUE TITLE
Trying to use mypy and pytest with a multiprocessing.Value - unable to use Synchronized as a type

### ISSUE THREAD

**Issue by davclark** [pytest-dev/pytest#12330]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

Pytest complains that Synchronized is not subscriptable, whether you get it direct from multiprocessing, or from typeshed. I haven't dug into why. I'd be curious to hear if anyone is using Pytest with a "subscripted" Synchronized type.

I am using mypy 1.10.0 which I think should support the use of Synchronized here. Same behavior on 3.9 and 3.12. Both installed with brew on M1 macOS 14.4.1.

The simplest way to illustrate the problem is with these two files:

```python
# define_type.py
import ctypes
import time
from multiprocessing import Value
from typing import Any
from multiprocessing.sharedctypes import Synchronized

def a_value() -> Synchronized[ctypes.c_double]:
    val: Synchronized[ctypes.c_double] = Value(ctypes.c_double, lock=False)
    val.value = time.time()  # type: ignore[assignment]
    return val
```

```python
# test_define_type.py
from define_type import a_value

def test_value():
    v = a_value()
    v.value = 1.2  # type: ignore[assignment]
    assert v is not None
```

This results in a world where mypy complains (unless told to ignore) about assigning a float to a c_double. But that's fine - the type checker is still helping me by making me check that the assignment makes sense.

running pytest in a directory with these two files results in:

```
___________________________________________ ERROR collecting test_define_type.py ___________________________________________
test_define_type.py:1: in <module>
    from define_type import a_value
define_type.py:7: in <module>
    def a_value() -> Synchronized[ctypes.c_double]:
E   TypeError: type 'Synchronized' is not subscriptable
```

Like I mentioned, I see this on 3.9 and 3.12 (the only versions I tested), but here's the pip list from the 3.12 venv:

```
Package           Version
----------------- -------
iniconfig         2.0.0
mypy              1.10.0
mypy-extensions   1.0.0
packaging         24.0
pip               24.0
pluggy            1.5.0
pytest            8.2.0
typing_extensions 4.11.0
```

Note that mypy will complain about duplicate files if I try including `Synchronized` from typeshed. So, this could be addressed by mypy somehow giving me a Synchronized type that will work with pytest. But maybe this is pytest's problem. I'm cross-posting with https://github.com/python/typeshed/issues/8799#issuecomment-2112598415, which includes more discussion of using `Value`s with mypy.

**Comment by bluetech** [comment]
The most likely explanation is that `Synchronized` is only generic in typeshed, but not in runtime, which makes `Synchronized[double]` valid for mypy but invalid at runtime. The fix is to quote it like `"Synchronized[double]"` or to add `from __future__ import annotations` to the top of your file.

**Comment by The-Compiler** [comment]
Note that nothing is pytest specific about this - you'd get the exact same error when just running your function.

```python
Python 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from multiprocessing.sharedctypes import Synchronized
>>> from multiprocessing import Value
>>> import ctypes
>>> val: Synchronized[ctypes.c_double] = Value(ctypes.c_double, lock=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type 'Synchronized' is not subscriptable
```

**Comment by davclark** [comment]
Ack! Thank you @The-Compiler. I obviously should have checked that.
