### ISSUE TITLE
pytest thread safety should be better documented

### ISSUE THREAD

**Issue by ngoldbaum** [pytest-dev/pytest#12356]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

`pytest.warns` is a subclass of the standard library `warnings.catch_warnings` context manager, which is not thread safe (this is noted in [the docs](https://docs.python.org/3/library/warnings.html#warnings.catch_warnings)).

If it's not possible for pytest to have a thread-safe version, it would be nice if the docs for `pytest.warns` could note that it's implemented using `warnings.catch_warnings` and is not thread safe for the same reason.

pytest 8.2.1 on MacOS Sonoma.

Fails about 10-20% of the time on my machine:

```python
import warnings
import threading


def raise_warning():
    warnings.warn(RuntimeWarning())


def test_pytest_warns():
    b = threading.Barrier(2)

    def catch_warning():
        b.wait()
        with pytest.warns(RuntimeWarning):
            raise_warning()

    task1 = threading.Thread(target=catch_warning)
    task2 = threading.Thread(target=catch_warning)

    task1.start()
    task2.start()
    task1.join()
    task2.join()
```

**Comment by The-Compiler** [comment]
pytest in its entirety is not intended to be thread-safe IIRC.

**Comment by RonnyPfannschmidt** [comment]
pytest.warns is implemented in terms of the stdlib catch-warnings helper - which is inherently not threadsave

**Comment by ngoldbaum** [comment]
> pytest in its entirety is not intended to be thread-safe IIRC.

TIL

Best to avoid using pytest constructs inside a thread, then.

This fact could be emphasized more in the docs, I don't see any mention of threads at all besides the discussion about [unhandled exceptions](https://docs.pytest.org/en/latest/how-to/failures.html#warning-about-unraisable-exceptions-and-unhandled-thread-exceptions).

**Comment by ngoldbaum** [comment]
> pytest.warns is implemented in terms of the stdlib catch-warnings helper - which is inherently not threadsave

Yes, I notes that in the issue description. The issue is a request for that fact to be noted in the docs, like the docs for the stdlib helper, if making it thread safe is out of scope for the library.

**Comment by nicoddemus** [comment]
Makes sense to note somewhere that pytest's constructs/helpers are not thread safe.

If somebody wants to take a look and update the docs, would love to review a PR. :+1:
