### ISSUE TITLE
Add newline after test status ouput

### ISSUE THREAD

**Issue by viocha** [pytest-dev/pytest#12366]
#### What's the problem this feature will solve?

The test code is:
```py
def test_hello():
	print("hello")
	print("world")
```
And it ouputs 
```
============================= test session starts =============================
collecting ... collected 1 item

test3.py::test_hello PASSED                                              [100%]hello
world


============================== 1 passed in 0.01s ==============================
```
There should be a newline after the message `PASSED                                              [100%]`. The desired output is like

```
============================= test session starts =============================
collecting ... collected 1 item

test3.py::test_hello PASSED                                              [100%]
hello
world


============================== 1 passed in 0.01s ==============================
```

**Comment by The-Compiler** [comment]
By default, pytest captures output from test functions, and does not display it for passing tests.

If you disable that with `-s` (like you seem to have done here, along with `-v`), your output will be intermixed with pytest's own output - though I don't see how you could get the output you've shown, I'd expect:

```
test_x.py::test_hello hello
world
PASSED
```

and that's what I get locally.

If pytest doesn't capture the output, it has no way to control when something else prints in between it's own output (and no way to easily know about that), so there is no way it can make it look nicer. Either use capturing, or print a newline yourself where you're printing your custom output.
