### ISSUE TITLE
pytest.deprecated_call breaks with TypeError on pytest 2.8.4

### ISSUE THREAD

**Issue by alex** [pytest-dev/pytest#1238]
https://jenkins.cryptography.io/job/cryptography-pr-builder/4650/TOXENV=py27,label=10.10/console

shows a traceback of this occurring.

**Comment by nicoddemus** [comment]
Thanks for the report @alex! 

Oh my, 91909 tests executed, 58284 skipped! :sweat_smile:

**Comment by alex** [comment]
Thanks! Can I ask if there's a plan for when the next release will be?

**Comment by RonnyPfannschmidt** [comment]
this week, if possible i'll do this afternoon european time myself, else i'll delegate

**Comment by alex** [comment]
Awesome, thanks!

On Wed, Dec 9, 2015 at 8:29 AM, Ronny Pfannschmidt <notifications@github.com
> wrote:

> this week, if possible i'll do this afternoon european time myself, else
> i'll delegate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytest-dev/pytest/issues/1238#issuecomment-163232252>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by netme** [comment]
Thanks for fixing that! Waiting for the release.

**Comment by nicoddemus** [comment]
`2.8.5` is out now. :smile:
