### ISSUE TITLE
Help Crash

### ISSUE THREAD

**Issue by datum-scientist** [pytest-dev/pytest#12384]
pytest 8.2.1
Ubuntu 23.10

console help crashes

(venv_new) :~/project$ pytest -h
Traceback (most recent call last):
  File ".../bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File ".../lib/python3.9/site-packages/_pytest/config/__init__.py", line 197, in console_main
    code = main()
  File ".../lib/python3.9/site-packages/_pytest/config/__init__.py", line 174, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/.../lib/python3.9/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File ".../lib/python3.9/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File ".../lib/python3.9/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File ".../lib/python3.9/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File ".../lib/python3.9/site-packages/_pytest/helpconfig.py", line 155, in pytest_cmdline_main
    showhelp(config)
  File ".../lib/python3.9/site-packages/_pytest/helpconfig.py", line 169, in showhelp
    tw.write(config._parser.optparser.format_help())
  File "/usr/local/lib/python3.9/argparse.py", line 2539, in format_help
    return formatter.format_help()
  File "/usr/local/lib/python3.9/argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "/usr/local/lib/python3.9/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.9/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.9/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.9/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.9/argparse.py", line 533, in _format_action
    help_text = self._expand_help(action)
  File "/usr/local/lib/python3.9/argparse.py", line 630, in _expand_help
    return self._get_help_string(action) % params
TypeError: %d format: a number is required, not dict

**Comment by The-Compiler** [comment]
Sounds like an issue with a plugin or `conftest.py`. What's in your `project` folder? What does `pytest --version --version` say? What does `pip list` say? (there is a reason the issue template asks for it...)

**Comment by datum-scientist** [comment]
> Sounds like an issue with a plugin or `conftest.py`. What's in your `project` folder? What does `pytest --version --version` say? What does `pip list` say? (there is a reason the issue template asks for it...)

created empty directory `check', cd to it and call pytest -h cause same error, conftest not defined

pytest version changed from 8.2.1 to 8.1.1

(venv_new) .../check$ pytest -h
Traceback (most recent call last):
  File "/venv_new/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/venv_new/lib/python3.9/site-packages/_pytest/config/__init__.py", line 197, in console_main
    code = main()
  File "/venv_new/lib/python3.9/site-packages/_pytest/config/__init__.py", line 174, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/venv_new/lib/python3.9/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/venv_new/lib/python3.9/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/venv_new/lib/python3.9/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/venv_new/lib/python3.9/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/venv_new/lib/python3.9/site-packages/_pytest/helpconfig.py", line 155, in pytest_cmdline_main
    showhelp(config)
  File "/venv_new/lib/python3.9/site-packages/_pytest/helpconfig.py", line 169, in showhelp
    tw.write(config._parser.optparser.format_help())
  File "/usr/local/lib/python3.9/argparse.py", line 2539, in format_help
    return formatter.format_help()
  File "/usr/local/lib/python3.9/argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "/usr/local/lib/python3.9/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.9/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.9/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.9/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/usr/local/lib/python3.9/argparse.py", line 533, in _format_action
    help_text = self._expand_help(action)
  File "/usr/local/lib/python3.9/argparse.py", line 630, in _expand_help
    return self._get_help_string(action) % params
TypeError: %d format: a number is required, not dict


(venv_new) .../check$ pytest --version --version
This is pytest version 8.1.1, imported from /venv_new/lib/python3.9/site-packages/pytest/__init__.py
setuptools registered plugins:
  pytest-django-queries-1.2.0 at /venv_new/lib/python3.9/site-packages/pytest_django_queries/plugin.py
  pytest-httpbin-2.0.0 at /venv_new/lib/python3.9/site-packages/pytest_httpbin/plugin.py
  pytest-cov-5.0.0 at /venv_new/lib/python3.9/site-packages/pytest_cov/plugin.py
  pytest-func-cov-0.2.3 at /venv_new/lib/python3.9/site-packages/pytest_func_cov/plugin.py
  anyio-3.7.0 at /venv_new/lib/python3.9/site-packages/anyio/pytest_plugin.py
  pytest-xdist-3.3.1 at /venv_new/lib/python3.9/site-packages/xdist/plugin.py
  pytest-xdist-3.3.1 at /venv_new/lib/python3.9/site-packages/xdist/looponfail.py
  pytest-integration-mark-0.2.0 at /venv_new/lib/python3.9/site-packages/pytest_integration_mark/hooks.py
  pytest-forked-1.6.0 at /venv_new/lib/python3.9/site-packages/pytest_forked/__init__.py
  pytest-mock-3.10.0 at /venv_new/lib/python3.9/site-packages/pytest_mock/__init__.py
  Faker-18.9.0 at /venv_new/lib/python3.9/site-packages/faker/contrib/pytest/plugin.py
  pytest-rabbitmq-3.0.2 at /venv_new/lib/python3.9/site-packages/pytest_rabbitmq/plugin.py
  pytest-celery-0.0.0 at /venv_new/lib/python3.9/site-packages/celery/contrib/pytest.py
  pytest-vcr-1.0.2 at /venv_new/lib/python3.9/site-packages/pytest_vcr.py
  datatest-0.11.1 at /venv_new/lib/python3.9/site-packages/datatest/_pytest_plugin.py
  pytest-django-4.5.2 at /venv_new/lib/python3.9/site-packages/pytest_django/plugin.py

(venv_new) .../check$ pip list
Package                              Version
------------------------------------ -----------
Adyen                                8.0.1
aenum                                3.1.12
aiohttp                              3.9.5
aiosignal                            1.3.1
amqp                                 5.1.1
AMQPStorm                            2.10.7
aniso8601                            7.0.0
annotated-types                      0.5.0
anyio                                3.7.0
APScheduler                          3.10.1
Arpeggio                             2.0.2
asgiref                              3.7.2
astroid                              2.15.5
asttokens                            2.2.1
async-timeout                        4.0.2
attrs                                23.1.0
authorizenet                         1.1.4
azure-core                           1.26.3
azure-identity                       1.12.0
Babel                                2.12.1
backcall                             0.2.0
backoff                              2.2.1
backports.entry-points-selectable    1.2.0
beautifulsoup4                       4.7.1
beautifultable                       0.7.0
billiard                             3.6.4.0
black                                23.3.0
blessed                              1.20.0
blessings                            1.7
blinker                              1.7.0
boto3                                1.26.142
botocore                             1.29.142
braintree                            4.20.0
Brotli                               1.0.9
brotlicffi                           1.1.0.0
build                                0.10.0
CacheControl                         0.12.11
cachetools                           5.3.1
cachy                                0.3.0
celery                               5.2.7
cent                                 4.1.0
centrifuge-python                    0.3.0
certifi                              2023.5.7
cffi                                 1.15.1
cfgv                                 3.3.1
chardet                              5.1.0
charset-normalizer                   3.1.0
cleo                                 2.0.1
click                                8.1.3
click-didyoumean                     0.3.0
click-plugins                        1.1.1
click-repl                           0.2.0
codecov                              2.1.13
colorama                             0.4.6
coverage                             6.5.0
crashtest                            0.4.1
cron-descriptor                      1.4.0
cronitor                             4.6.0
cryptography                         40.0.2
cssselect2                           0.7.0
curtsies                             0.4.1
cwcwidth                             0.1.8
dataclasses                          0.6
datatest                             0.11.1
decorator                            5.1.1
Deprecated                           1.2.14
dictdiffer                           0.9.0
dill                                 0.3.6
distlib                              0.3.6
distro                               1.8.0
dj-database-url                      2.0.0
dj-email-url                         1.0.6
Django                               3.2.19
django-admin-tools                   0.9.2
django-anymail                       10.0
django-appconf                       1.0.5
django-cache-url                     3.4.4
django-celery-beat                   2.5.0
django-celery-results                2.5.1
django-cors-headers                  3.14.0
django-countries                     7.5.1
django-db-geventpool                 4.0.1
django-debug-toolbar                 4.1.0
django-debug-toolbar-request-history 0.1.4
django-dotenv                        1.4.2
django-extensions                    3.2.1
django-filter                        23.2
django-graphiql-debug-toolbar        0.2.0
django-js-asset                      2.0.0
django-measurement                   3.2.4
django-mongodb-engine                0.6.0
django-mongoengine                   0.5.4
django-mptt                          0.14.0
django-nose                          1.4.7
django-phonenumber-field             7.1.0
django-postgres-extra                2.0.8
django-prices                        2.3.0
django-prices-openexchangerates      1.2.0
django-prices-vatlayer               1.1.0
django-redis                         5.2.0
django-redisboard                    8.4.0
django-schema-graph                  2.2.1
django-storages                      1.13.2
django-stubs                         4.2.6
django-stubs-ext                     4.2.5
django-timezone-field                5.0
django-versatileimagefield           3.1
djangorestframework                  3.14.0
djangorestframework-camel-case       1.4.2
djangorestframework-simplejwt        5.2.2
djangotoolbox                        1.8.0
djantic                              0.7.0
djongo                               1.3.6
dnspython                            2.3.0
dpath                                2.1.6
draftjs-sanitizer                    1.0.0
drf-spectacular                      0.26.2
drf-spectacular-sidecar              2023.5.1
dulwich                              0.21.5
enmerkar                             0.7.1
et-xmlfile                           1.1.0
exceptiongroup                       1.1.1
execnet                              1.9.0
executing                            1.2.0
Faker                                18.9.0
fawltydeps                           0.15.0
filelock                             3.12.0
flake8                               6.0.0
flasgger                             0.9.7.1
Flask                                3.0.3
flower                               1.2.0
fonttools                            4.39.4
freezegun                            1.2.2
frozenlist                           1.3.3
fuzzywuzzy                           0.18.0
gcloud-aio-auth                      5.3.1
gcloud-aio-pubsub                    6.0.1
gevent                               22.10.2
gitdb                                4.0.10
GitPython                            3.1.31
google-api-core                      2.18.0
google-auth                          2.29.0
google-cloud-core                    2.4.1
google-cloud-pubsub                  2.21.1
google-cloud-storage                 2.16.0
google-crc32c                        1.5.0
google-i18n-address                  3.1.0
google-measurement-protocol          1.1.0
google-resumable-media               2.7.0
googleapis-common-protos             1.59.0
gql                                  2.0.0
graphene                             2.1.9
graphene-django                      2.15.0
graphene-federation                  0.2.0
graphene-file-upload                 1.3.0
graphene-pydantic                    0.4.0
graphql-core                         2.3.2
graphql_query                        1.0.3
graphql-relay                        2.0.1
graphql-utils                        0.4
graphviz                             0.20.1
greenlet                             2.0.2
grpc-google-iam-v1                   0.12.6
grpcio                               1.60.1
grpcio-status                        1.54.2
gunicorn                             20.1.0
h11                                  0.14.0
h2                                   4.1.0
hpack                                4.0.0
html-to-draftjs                      1.0.1
html2text                            2020.1.16
html5lib                             1.1
httpbin                              0.10.2
httpcore                             0.17.2
httpheaders                          2023.2.15
httptools                            0.5.0
httpx                                0.24.1
humanize                             4.6.0
hyperframe                           6.0.1
icecream                             2.1.3
identify                             2.5.24
idna                                 3.4
imageio                              2.30.0
importlib_metadata                   7.1.0
inflection                           0.5.1
iniconfig                            2.0.0
install                              1.3.5
installer                            0.7.0
ipython                              8.13.2
isodatetimehandler                   1.0.2
isort                                5.12.0
itsdangerous                         2.1.2
jaeger-client                        4.8.0
jaraco.classes                       3.2.3
jedi                                 0.18.2
jeepney                              0.8.0
Jinja2                               3.1.2
jmespath                             1.0.1
jsonfield                            3.1.0
jsonpickle                           3.0.1
jsonschema                           4.17.3
keyring                              23.13.1
kombu                                5.2.4
lazy_loader                          0.2
lazy-object-proxy                    1.9.0
Levenshtein                          0.21.0
libcst                               1.0.0
lockfile                             0.12.2
lxml                                 4.9.2
Markdown                             3.4.3
MarkupSafe                           2.1.2
matplotlib-inline                    0.1.6
maxminddb                            2.3.0
mccabe                               0.7.0
measurement                          3.2.2
micawber                             0.5.4
mirakuru                             2.5.2
mistune                              3.0.2
model-bakery                         1.11.0
moesifapi                            1.4.0
moesifdjango                         2.3.1
moesifpythonrequest                  0.3.0
mongoengine                          0.27.0
more-itertools                       9.1.0
mpmath                               1.3.0
msal                                 1.21.0
msal-extensions                      1.0.0
msgpack                              1.0.5
multidict                            6.0.4
mypy                                 1.3.0
mypy-extensions                      1.0.0
netaddr                              0.8.0
networkx                             3.1
nodeenv                              1.8.0
nose                                 1.3.7
numpy                                1.24.3
oauthlib                             3.2.2
objgraph                             3.5.0
opencensus                           0.11.2
opencensus-context                   0.1.3
opencensus-ext-azure                 1.1.9
opencensus-ext-django                0.8.0
opencensus-ext-ocagent               0.7.1
opencensus-proto                     0.1.0
opencv-python                        4.7.0.72
opencv-python-headless               4.7.0.72
openpyxl                             3.1.2
opentracing                          2.4.0
packaging                            23.1
pamqp                                2.3.0
pandas                               2.0.2
parso                                0.8.3
parver                               0.5
pastel                               0.2.1
pathspec                             0.11.1
petl                                 1.7.12
pexpect                              4.8.0
phonenumberslite                     8.13.13
pickleshare                          0.7.5
pika                                 1.3.2
Pillow                               9.5.0
pip                                  24.0
pip-check-reqs                       2.4.4
pip-requirements-parser              32.0.1
pkginfo                              1.9.6
platformdirs                         3.5.1
pluggy                               1.5.0
poetry                               1.5.1
poetry-core                          1.6.1
poetry-plugin-export                 1.4.0
port-for                             0.7.2
portalocker                          2.7.0
posuto                               2023.5.0
pre-commit                           3.3.2
pretty-errors                        1.2.25
prices                               1.1.1
prometheus-client                    0.16.0
promise                              2.3
prompt-toolkit                       3.0.38
proto-plus                           1.23.0
protobuf                             4.25.3
psutil                               5.9.4
psycogreen                           1.0.2
psycopg2-binary                      2.9.6
ptyprocess                           0.7.0
pulumi                               3.113.3
pulumi_rabbitmq                      3.3.2
pure-eval                            0.2.2
py                                   1.11.0
pyasn1                               0.5.0
pyasn1-modules                       0.3.0
pybars3                              0.9.7
pycodestyle                          2.10.0
pycparser                            2.21
pydantic                             1.10.10
pydantic_core                        2.0.1
pydocstyle                           6.3.0
pydyf                                0.6.0
pyflakes                             3.0.1
Pygments                             2.15.1
PyJWT                                2.7.0
pylev                                1.4.0
pylint                               2.17.4
pylint-celery                        0.3
pylint-django                        2.5.3
pylint-plugin-utils                  0.8.2
pymemcache                           4.0.0
PyMeta3                              0.5.1
pymongo                              4.3.3
pyparsing                            3.0.9
pypdf                                4.2.0
PyPDF2                               3.0.1
pyphen                               0.14.0
pyproject_api                        1.5.1
pyproject_hooks                      1.0.0
pyrate-limiter                       3.1.0
pyrsistent                           0.19.3
pyTelegramBotAPI                     4.12.0
pytest                               8.1.1
pytest-celery                        0.0.0
pytest-cov                           5.0.0
pytest-django                        4.5.2
pytest-django-queries                1.2.0
pytest-fixture-classes               1.0.1
pytest-forked                        1.6.0
pytest-func-cov                      0.2.3
pytest-httpbin                       2.0.0
pytest-integration-mark              0.2.0
pytest-mock                          3.10.0
pytest-rabbitmq                      3.0.2
pytest-vcr                           1.0.2
pytest-xdist                         3.3.1
python-crontab                       2.7.1
python-dateutil                      2.8.2
python-dotenv                        1.0.0
python-http-client                   3.3.7
python-json-logger                   2.0.7
python-Levenshtein                   0.21.0
python-magic                         0.4.27
python-magic-bin                     0.4.14
python-slugify                       4.0.1
python-telegram-bot                  20.3
pytimeparse                          1.1.8
pytz                                 2023.3
pytz-deprecation-shim                0.1.0.post0
pyuwsgi                              2.0.21
pywatchman                           1.4.1
PyWavelets                           1.4.1
pywin32-ctypes                       0.2.0
PyXB                                 1.2.5
pyxdg                                0.28
PyYAML                               6.0
rapidfuzz                            2.13.7
razorpay                             1.3.0
redis                                4.5.5
regex                                2023.5.5
reportlab                            3.6.12
requests                             2.31.0
requests-file                        2.0.0
requests-toolbelt                    1.0.0
rfc3986                              2.0.0
rsa                                  4.9
Rx                                   1.6.3
s3transfer                           0.6.1
scikit-image                         0.20.0
scipy                                1.9.1
SecretStorage                        3.3.3
semver                               2.13.0
sendgrid                             6.10.0
sentry-sdk                           1.24.0
setuptools                           68.1.2
shellingham                          1.5.0.post1
singledispatch                       4.0.0
six                                  1.16.0
smmap                                5.0.0
sniffio                              1.3.0
snowballstemmer                      2.2.0
soupsieve                            2.4.1
sqlparse                             0.2.4
stack-data                           0.6.2
starkbank-ecdsa                      2.2.0
StrEnum                              0.4.10
stripe                               5.4.0
svglib                               1.5.1
sympy                                1.12
tabulate                             0.9.0
telegram                             0.0.1
termcolor                            1.1.0
text-unidecode                       1.3
thefuzz                              0.19.0
threadloop                           1.0.2
thrift                               0.16.0
tifffile                             2023.4.12
tinycss2                             1.2.1
toml                                 0.10.2
tomli                                2.0.1
tomlkit                              0.11.8
tornado                              6.3.2
tox                                  4.5.2
traitlets                            5.9.0
transifex-client                     0.14.4
trove-classifiers                    2023.5.24
types-pkg-resources                  0.1.3
types-python-dateutil                2.8.19.13
types-pytz                           2023.3.0.0
types-PyYAML                         6.0.12.10
types-requests                       2.31.0.1
types-urllib3                        1.26.25.13
typing_extensions                    4.6.2
typing-inspect                       0.9.0
tzdata                               2023.3
tzlocal                              5.0.1
Unidecode                            1.3.6
uritemplate                          4.1.1
urllib3                              1.26.15
uvicorn                              0.22.0
uvloop                               0.17.0
vcrpy                                4.3.1
vine                                 5.0.0
virtualenv                           20.23.0
watchgod                             0.8.2
wcwidth                              0.2.6
weasyprint                           59.0
webencodings                         0.5.1
websockets                           11.0.3
Werkzeug                             3.0.2
wheel                                0.38.4
wrapt                                1.15.0
xlrd                                 2.0.1
XlsxWriter                           3.1.2
xlwt                                 1.3.0
xmltodict                            0.13.0
yarl                                 1.9.2
yookassa                             2.4.0
zipp                                 3.15.0
zope.event                           4.6
zope.interface                       6.0
zopfli                               0.2.2

**Comment by The-Compiler** [comment]
This is a [bug](https://github.com/Barbora-Data-Science/pytest-integration-mark/blob/v0.2.0/pytest_integration_mark/hooks.py#L60) in pytest-integration-mark, please report it there instead.
