### ISSUE TITLE
pytest_terminal_summary question 关于运行同一个例子但是结果样式不同问题

### ISSUE THREAD

**Issue by yanghuizhi** [pytest-dev/pytest#12398]
- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

1、An example of the same code, after multiple executions, the results are inconsistent

2、platform win32 -- Python 3.9.0, pytest-7.4.4, pluggy-1.0.0 -- D:\python\python.exe
cachedir: .pytest_cache
metadata: {'Python': '3.9.0', 'Platform': 'Windows-10-10.0.19041-SP0', 'Packages': {'pytest': '7.4.4', 'pluggy': '1.0.0'}, 'Plugins': {'allure-pytest': '2.13.2', 'anyio': '3.7.1', 'Faker': '15.3.1', 'dependency': '0.5.1', 'html': '3.2.0', 'metadata': '2.0.4', 'parallel': '0.1.1', 'repeat': '0.9.1', 'sugar': '0.9.6', 'xdist': '3.2.0'}, 'JAVA_HOME': 'C:\\Program Files\\Java\\jdk1.8.0_202', 
configfile: pytest.ini
plugins: allure-pytest-2.13.2, anyio-3.7.1, Faker-15.3.1, dependency-0.5.1, html-3.2.0, metadata-2.0.4, parallel-0.1.1, repeat-0.9.1, sugar-0.9.6, xdist-3.2.0

3、
![image](https://github.com/pytest-dev/pytest/assets/29268369/df2bb390-0d68-4296-be48-1f96fc675eac)
![image](https://github.com/pytest-dev/pytest/assets/29268369/fb931516-1799-42d8-83ba-73c43ca025ee)
![image](https://github.com/pytest-dev/pytest/assets/29268369/9d61c44d-6d9c-4235-b6e6-696eddee914c)

**yellow font**
In a moment，im update 8.2.0 ，question remain
```
@pytest.hookspec
def pytest_terminal_summary(terminalreporter):
    if socket.gethostname() == 'x':
        total = terminalreporter._numcollected 
        passed = len([i for i in terminalreporter.stats.get('passed', []) if i.when != 'teardown']) 
        failed = len([i for i in terminalreporter.stats.get('failed', []) if i.when != 'teardown'])  
        error = len([i for i in terminalreporter.stats.get('error', []) if i.when != 'teardown']) 
        skipped = len([i for i in terminalreporter.stats.get('skipped', []) if i.when != 'teardown']) 

        if total == 0:
            return LogTool().info("总共0条用例执行,请检查程序")

        total_sum = passed + failed + error + skipped
     
        body = f'Carlcare API测试报告:  用例总数: {total}, ' \
                f'通过用例数: {passed}, 失败用例数: {failed}, 通过率: {"%.2f%%" % (passed / total_sum * 100)}'
        print()
        LogTool().info("------------------执行报告------------------")
        LogTool().info(body)
```

**Comment by yanghuizhi** [comment]
![image](https://github.com/pytest-dev/pytest/assets/29268369/9d61c44d-6d9c-4235-b6e6-696eddee914c)

In a moment，im update 8.2.0 ，question remain

**Comment by The-Compiler** [comment]
Sounds like an issue with pytest-parallel and/or whatever `LogTool()` is. Please provide a complete, runnable example which reproduces the issue. Otherwise there really isn't much that can be said or done.

**Comment by yanghuizhi** [comment]
> Sounds like an issue with pytest-parallel and/or whatever `LogTool()` is. Please provide a complete, runnable example which reproduces the issue. Otherwise there really isn't much that can be said or done.

ok， please see：

```
test_example.py


@allure.feature("******")
class TestExample:

    @allure.story("x")
    @allure.title("xx")
    @allure.description("xxx")
    def test1(self, env, app):
        print("1")
       print("2")

        assert 200 == 200

    def test2(self):
        print("123")

if __name__ == '__main__':
    pytest.main([__file__])
```

```
configtest.py

import os
import time
import pytest


@pytest.hookspec
def pytest_terminal_summary(terminalreporter):
        total = terminalreporter._numcollected  # 总共运行用例数
        passed = len([i for i in terminalreporter.stats.get('passed', []) if i.when != 'teardown'])  # 通过用例数
        failed = len([i for i in terminalreporter.stats.get('failed', []) if i.when != 'teardown'])  # 失败用例数
        error = len([i for i in terminalreporter.stats.get('error', []) if i.when != 'teardown'])  # 报错用例数
        skipped = len([i for i in terminalreporter.stats.get('skipped', []) if i.when != 'teardown'])  # 跳过用例数

        if total == 0:
            return LogTool().info("总共0条用例执行,请检查程序")

        total_sum = passed + failed + error + skipped
        body = f'测试报告:  用例总数: {total}, ' \
                f'通过用例数: {passed}, 失败用例数: {failed}, 通过率: {"%.2f%%" % (passed / total_sum * 100)}'
        print()
        LogTool().info("------------------执行报告------------------")
        LogTool().info(body)

```

```
log.py     (tools)

from . import abs_path, is_file_or_dir_create

class LogTool:

    def __init__(self):
        self.date = f"{time.strftime('%Y_%m_%d')}.log"
        self.log_name = abs_path("logs", self.date)
        # Create a logger and set the log level (anything below this level will be invalid).
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.DEBUG)

    def _console(self, level, message):
        # create FileHandler
        log_handler = logging.FileHandler(is_file_or_dir_create(self.log_name), "a", encoding="utf-8")
        log_handler.setLevel(logging.DEBUG)
        log_handler.setFormatter(
            logging.Formatter("%(asctime)s | %(levelname)s | %(message)s", datefmt="%Y-%m-%d %H:%M:%S")
        )
        self.logger.addHandler(log_handler)

        # create StreamHandler
        terminal_log_handler = logging.StreamHandler()
        terminal_log_handler.setLevel(logging.DEBUG)
        terminal_log_handler.setFormatter(
            colorlog.ColoredFormatter(
                "%(log_color)s %(asctime)s | %(levelname)s | %(message)s",
                datefmt="%Y-%m-%d %H:%M:%S",
                log_colors={
                    "DEBUG": "blue",
                    "INFO": "yellow",  # blue、black、green、cyan、white、purple、red,bg_white
                    "WARNING": "purple",
                    "ERROR": "red",
                    "CRITICAL": "black",
                }
            )
        )
        self.logger.addHandler(terminal_log_handler)

        if level in "debug":
            self.logger.debug(message)
        elif level in "info":
            self.logger.info(message)
        elif level in "warning":
            self.logger.warning(message)
        elif level in "error":
            self.logger.error(message)
        elif level in "critical":
            self.logger.critical(message)

        # removeHandler Avoid duplication of log output
        self.logger.removeHandler(log_handler)
        self.logger.removeHandler(terminal_log_handler)

        log_handler.close()
        terminal_log_handler.close()

    def debug(self, message):
        self._console("debug", message)

    def info(self, message):
        self._console("info", message)

    def warning(self, message):
        self._console("warning", message)

    def error(self, message):
        self._console("error", message)

    def critical(self, message):
        self._console("critical", message)

```

```
.py   

def abs_path(*args: object):
    return os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), *args)


def is_file_or_dir_create(*paths):
    if os.path.exists(*paths):
        return abs_path(*paths)
    else:
        if platform.uname().system == "Windows":
            file = open(*paths, "w")
            file.close()
            return abs_path(*paths)
            # os.makedirs(*paths)
        elif platform.uname().system == "Linux":
            os.mknod(*paths)
```

There are 4 files in total, 1 test file, 1 config, 2 tools

**Comment by The-Compiler** [comment]
Your example is full of missing imports, missing fixtures, syntax errors, and other bugs. After spending some time fixing it, I cannot reproduce the issue you describe.

Please show a [self-contained and ideally minimal example](http://www.sscce.org/) that reproduces the bug, which you can actually run yourself to verify that the bug is still present with it.

**Comment by yanghuizhi** [comment]
> Your example is full of missing imports, missing fixtures, syntax errors, and other bugs. After spending some time fixing it, I cannot reproduce the issue you describe.
> 
> Please show a [self-contained and ideally minimal example](http://www.sscce.org/) that reproduces the bug, which you can actually run yourself to verify that the bug is still present with it.

Sorry teacher, I have made a new copy now, please guide me on the problem。

[py_testes_example_mini.zip](https://github.com/user-attachments/files/15507549/py_testes_example_mini.zip)

**Comment by The-Compiler** [comment]
After a `pip install allure-pytest colorlog pytest py python-dateutil` I can run this (minus it failing the first time when creating the log file).

However, I still cannot reproduce, even when running it multiple times:

```
$ pytest run_test_example.py 
================================================ test session starts =================================================
platform linux -- Python 3.12.3, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/florian/Downloads/py_testes_example_mini
configfile: pytest.ini
plugins: parallel-0.1.1, allure-pytest-2.13.5
collected 2 items                                                                                                    

run_test_example.py ..                                                                                         [100%]

 2024-06-05 11:02:58 | INFO | ------------------执行报告------------------
 2024-06-05 11:02:58 | INFO | Carlcare API测试报告:  用例总数: 2, 通过用例数: 2, 失败用例数: 0, 通过率: 100.00%

================================================= 2 passed in 0.01s ==================================================
```

Can you please show the full output you get with this example?

**Comment by yanghuizhi** [comment]
> After a `pip install allure-pytest colorlog pytest py python-dateutil` I can run this (minus it failing the first time when creating the log file).
> 
> However, I still cannot reproduce, even when running it multiple times:
> 
> ```
> $ pytest run_test_example.py 
> ================================================ test session starts =================================================
> platform linux -- Python 3.12.3, pytest-8.2.2, pluggy-1.5.0
> rootdir: /home/florian/Downloads/py_testes_example_mini
> configfile: pytest.ini
> plugins: parallel-0.1.1, allure-pytest-2.13.5
> collected 2 items                                                                                                    
> 
> run_test_example.py ..                                                                                         [100%]
> 
>  2024-06-05 11:02:58 | INFO | ------------------执行报告------------------
>  2024-06-05 11:02:58 | INFO | Carlcare API测试报告:  用例总数: 2, 通过用例数: 2, 失败用例数: 0, 通过率: 100.00%
> 
> ================================================= 2 passed in 0.01s ==================================================
> ```
> 
> Can you please show the full output you get with this example?

From the picture, teacher, you have run successfully！

Therefore, the teacher asks you to run several times and check the results. I will show you the following results of multiple runs

![image](https://github.com/pytest-dev/pytest/assets/29268369/5c34c7f2-ee57-45e6-b002-e7eda630e71d)

**Comment by The-Compiler** [comment]
As I already said:

> However, I still cannot reproduce, **even when running it multiple times**

Maybe this is something Windows specific (I'm on Linux). The fact that you recreate your log handlers for every message (and also recreate `LogTool()` for every message) strikes me as odd, but even then I'd expect this to print before the output from pytest, not after it.

@nicoddemus Now that we have a (more or less) runnable example, maybe you could give this a spin on Windows and see if you can reproduce? Do we have an issue or something already regarding print order / flushing (?) that's Windows specific?

**Comment by yanghuizhi** [comment]
> As I already said:
> 
> > However, I still cannot reproduce, **even when running it multiple times**
> 
> Maybe this is something Windows specific (I'm on Linux). The fact that you recreate your log handlers for every message (and also recreate `LogTool()` for every message) strikes me as odd, but even then I'd expect this to print before the output from pytest, not after it.
> 
> @nicoddemus Now that we have a (more or less) runnable example, maybe you could give this a spin on Windows and see if you can reproduce? Do we have an issue or something already regarding print order / flushing (?) that's Windows specific?

I'm sorry, teacher, my is windows computer，I've had the same result on my mac.  It does not currently operate on linux
