### ISSUE TITLE
fixtures vs xunit-style setup/teardown, a dependency-injection discussion and real-world example

### ISSUE THREAD

**Issue by BeyondEvil** [pytest-dev/pytest#1239]
The discussion came about in the pylib IRC channel between myself and Ronny P.

As a newbie it's difficult to find more complex, real-world examples of how to use fixtures and why. In essence, how to avoid ending up implementing fixtures with an xunit-style.

He asked me to create an issue with the requirements and examples so that the discussion could take place here and the result be shared with the community as a whole.

The AUT/SUT is a complex Project Management tool (SAAS) and we're using Selenium for our UI testing. The test framework supports both API and UI testing and so when it comes to the creation of test data (objects) that functionality is shared. For the sake of our discussion however, we'll only be looking at the UI/Selenium parts (since selenium adds another level of complexity).

There are a couple of parts to the framework:
- Object Representations (User and Project in the example).
  These are (in memory) test data representations of the real objects used in the testing. The real objects are created in setup-fixtures using API's.
- TestDataCollection (tdc, in memory test DB)
  Basically the object representations collection.
- Page Objects (Selenium)
  https://code.google.com/p/selenium/wiki/PageObjects
- TestDriver
  This is our Selenium wrapper which provides a bunch of convenience methods for the Page Objects.

Requirements:

Each test needs a set of test data. The testdata is setup using fixtures called by the class for shared setup and by the tests for non-shared (destructive). To avoid confusion the TDC does not allow duplicate entries.

Each object has a ttl (time to live) attribute. This is set to the same scope as the fixture. Currently we only use module and function.

After each test, the TDC (DB) is cleared of any function-scoped objects. That way we alleviate the risk of having duplicate entries (yet valid) in the TDC.

Below is the :gist with the code:
https://gist.github.com/BeyondEvil/b70b1d9e4229919d02d3

**Comment by BeyondEvil** [comment]
Feel free to ask me for clarifications.

**Comment by pfctdayelise** [comment]
@BeyondEvil, what outcome are you looking for in this issue?
