### ISSUE TITLE
Allow the user to provide the submission command that will be prepended to the PyTest command that runs individual tests

### ISSUE THREAD

**Issue by yurivict** [pytest-dev/pytest#12403]
#### What's the problem this feature will solve?

It would allow, among others, to distribute tests to run on different machines.

We have a ton of tests in the project, and they run for hours even when run on multiple CPUs using pytest-xdist.
The next step to speed tests up is to distribute them.
For this we need to increase the number of tests run simultaneously, and to send them to other hosts.
We use the LSF command 'bsub' that submits jobs to the farm. Each test should be prepended with the command like this so that it would be sent to another host for execution. All other effects of the run are roughly the same: command's exit code, stdout and stderr printouts, etc.

#### Describe the solution you'd like

Add an option to PyTest to prepend the test command.
For example: pytest -e "bsub" ...
This in combination with pytest-xdist and high CPU count would allow to parallelize tests beyond of what pytest-xdist alone is able to do.

#### Alternative Solutions
Splitting tests into several parts and parallelizing them this way, but this is ugly and requires more manual work.

#### Additional context

This would be useful in a corporate environments which have large projects with lots of tests and large computational farms.

**Comment by RonnyPfannschmidt** [comment]
With the provided information this is not actionable in any sensible manner as both use case and surrounding technical details are very incomplete 

As far as im aware none of the active core developers have experience with the submission system you mentioned 

Additionally the submission system seems to be niche and absolutely mismatched to normal pytest Operation 

Without a more compelling and comprehensive description this is simply very far out of scope

**Comment by yurivict** [comment]
> Without a more compelling and comprehensive description this is simply very far out of scope

Could you please tell me what more details do you need and I'd be happy to provide them?

**Comment by Pierre-Sassoulas** [comment]
If I'm not mistaken [``pytest-shard``](https://pypi.org/project/pytest-shard/) can permit to do what you want somewhat easily

**Comment by RonnyPfannschmidt** [comment]
@yurivict the missing details are unknowns,as mentioned mostly of us are completely unfamiliar with the system you use, as such we completely lack the background knowledge to know what's needed to correctly integrate it 

Based on your description it's likely that your system is at odds with how pytest itself works 

As such it's unclear how feasible a integration is

**Comment by The-Compiler** [comment]
In either case, this sounds like the job of a plugin, and not pytest core. pytest itself does not have a "test command" for every test, tests are not processes.
