### ISSUE TITLE
autouse fixtures named with a leading underscore do not run

### ISSUE THREAD

**Issue by tamird** [pytest-dev/pytest#12404]
Very simple:

```python
@pytest.fixture(autouse=True)
def foo(request: pytest.FixtureRequest) -> None:
  print("this runs")

@pytest.fixture(autouse=True)
def _foo(request: pytest.FixtureRequest) -> None:
  print("this does not run")
```

This causes [ruff's PT004](https://docs.astral.sh/ruff/rules/pytest-missing-fixture-name-underscore/) to emit false positives. Let me know if this is intended behavior (though I didn't find documentation of that fact) and I'll send the bug over to ruff.

**Comment by bluetech** [comment]
I tried it and it works for me. Maybe you're using some plugin which affects this? Do you have a standalone reproduction?

**Comment by tamird** [comment]
Ah yeah, this is PEBKAC. My fixtures are shared between packages and glob imported into each package's `conftest.py` -- and underscored fixtures aren't being imported.
