### ISSUE TITLE
log_file  Does not support formatting？For example, generate the date of the day

### ISSUE THREAD

**Issue by yanghuizhi** [pytest-dev/pytest#12400]
- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

![image](https://github.com/pytest-dev/pytest/assets/29268369/a9916764-5f0c-4e72-8d9a-6c457a4f21dc)

**Comment by RonnyPfannschmidt** [comment]
None of the stdlib logging tools supports something like this, unless there's a well known 3rd party library that handles it,I'm -1 on inventing it for pytest based on prior experience with edge cases around dates and timezones

**Comment by yanghuizhi** [comment]
> None of the stdlib logging tools supports something like this, unless there's a well known 3rd party library that handles it,I'm -1 on inventing it for pytest based on prior experience with edge cases around dates and timezones

Thank you for your answer
，
bug，Can I inherit configuration changes，such as  Dynamically modify pytest-registered logging plug-ins

**Comment by nicoddemus** [comment]
@yanghuizhi if I understood your question, no the logging plugin is not really extendable, your best shot here would be to write your own logging plugin (you can copy `_pytest.logging` and adapt it to your needs).

Closing for now, feel free to follow up.
