### ISSUE TITLE
getexecutable() should sanity-check Python executable

### ISSUE THREAD

**Issue by jdemeyer** [pytest-dev/pytest#1240]
The function `getexecutable()` in `_pytest/pytester.py` should do some minimal sanity checking that the Python executable it finds actually works. It is not because there is _some_ `python3.3` executable on my system that it is actually suitable in my current environment.

A minimal check would be to check that `${executable} -c ""` returns without errors.

**Comment by nicoddemus** [comment]
Thanks for the report!

**Comment by hpk42** [comment]
if you can do a PR going for your suggestion that'd be welcome :)

**Comment by Zac-HD** [comment]
Since e53e45b55c71f92967af9c55c800d7818b5ac073, we check `${executable} --version` before returning.

https://github.com/pytest-dev/pytest/blob/cd72e23f3f3d4e8fe9bd9d8af7fceb681985b9c7/src/_pytest/pytester.py#L147-L170
