### ISSUE TITLE
Question about teardowns when setup fixture fails.

### ISSUE THREAD

**Issue by EugeneBrod** [pytest-dev/pytest#12421]
### Discussed in https://github.com/pytest-dev/pytest/discussions/12420

<div type='discussions-op-text'>

<sup>Originally posted by **EugeneBrod** June  4, 2024</sup>
Hi there.

I'd like to perform a teardown if the setup fails or if the call fails.

I have 2 setup fixtures:
1. create device -> returns: device (won't fail)
3. configure device (might fail)

I'd like a teardown fixture that gets the device and does something if there was a failure in either setup or test call. Here's my attempt.

`
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item):
....outcome = yield
....report = outcome.get_result()
....setattr(item, "rep_" + report.when, report) # https://docs.pytest.org/en/7.1.x/example/simple.html#making-test-result-information-available-in-fixtures

@pytest.fixture(scope="session")
def program_device()
....# known good fixture
....device = Device()
....yield device

@pytest.fixture()
def configure_device(program_device)
....device = program_device
....device.configure() # this could fail
....yield device

@pytest.fixture(autouse=True)
def dump_device_memory_on_failure(program_device, request):
....yield
....device = program_device

.... # if setup or call failed
....if request.node.rep_setup.failed or request.node.rep_call.failed:
........# dump device memory

def test_something(configure_device):
....device = configure_device
....assert(something)
`

This approach works well when the failure occurs in the test call. But if the test setup fails, the fixture teardowns aren't run, so I can't dump the device's memory.

Is it fundamentally an issue that the setup steps can fail?
Maybe if I change the ordering I can run the teardown when the setup fails?

Looking for suggestions. Thanks in advance.

</div>

**Comment by The-Compiler** [comment]
This kind of thing is what discussions are for, don't crosspost the same thing as discussion and issue...

**Comment by EugeneBrod** [comment]
> This kind of thing is what discussions are for, don't crosspost the same thing as discussion and issue...

Sorry! Moving over to the discussion.
