### ISSUE TITLE
make --doctest-glob multi-allowed

### ISSUE THREAD

**Issue by jab** [pytest-dev/pytest#1242]
Currently you can only pass PyTest a single `--doctest-glob` option. If you have doctests in *.txt, *.rst, and *.rst.inc files—i.e. if you have both dedicated *.txt doctests as well as code examples in your Sphinx documentation that you also want checked—there is currently no way to pass --doctest-glob the union of these patterns. Would you consider making the --doctest-glob option multi-allowed, similar to --ignore?

**Comment by jab** [comment]
(To work around this, I'm currently resorting to passing --doctest-glob=*doctest*, and explicitly adding "doctest" to the filenames of any files I want PyTest to find doctests in.)

**Comment by nicoddemus** [comment]
I don't see any problem with making it multi-allowed. Would you consider opening a PR?

**Comment by jab** [comment]
Great, and absolutely, but I'm a new contributor (and currently juggling some deadlines) so if someone can beat me to it, please feel free!

**Comment by jab** [comment]
@nicoddemus please see #1255 :)

**Comment by nicoddemus** [comment]
Fixed by #1297
