### ISSUE TITLE
Pytest documentation website issue: Python code example blocks not rendering properly in pytest documentation

### ISSUE THREAD

**Issue by amittendulkar** [pytest-dev/pytest#12437]
When I refer to say https://docs.pytest.org/en/stable/reference/reference.html#capsys I see that the Python block example in it messed up. I tried with Edge, Firefox, Chrome and it looks broken in all 3.

The Python block seems to be rendering properly in 7.x documentation links and seemed to have broken from 8.x documentation links onward.

Sample (broken Python block) documentation for the stable version (8.2.2),
![image](https://github.com/pytest-dev/pytest/assets/18111340/6cd98b36-f240-4d43-9e3a-cce085cc1d75)

Sample (working) documentation for the 7.x version,
![image](https://github.com/pytest-dev/pytest/assets/18111340/ca9e96bc-9c2a-4e48-8f61-9d4477c75f5f)

NOTE: Both screenshots are taken using Edge Version 125.0.2535.85 (Official build) (64-bit)

**Comment by bluetech** [comment]
Thanks for letting us know, it must have broke when we switched to the Furo theme and we missed it.

**Comment by The-Compiler** [comment]
I think this might actually have been the switch to ruff (4588653b2497ed25976b7aaff225b889fb476756), which removed all the empty lines:

```diff
@@ -988,7 +987,6 @@ def capsys(request: SubRequest) -> Generator[CaptureFixture[str], None, None]:
     Returns an instance of :class:`CaptureFixture[str] <pytest.CaptureFixture>`.
 
     Example:
-
     .. code-block:: python
 
         def test_output(capsys):
@@ -1016,7 +1014,6 @@ def capsysbinary(request: SubRequest) -> Generator[CaptureFixture[bytes], None,
     Returns an instance of :class:`CaptureFixture[bytes] <pytest.CaptureFixture>`.
 
     Example:
-
     .. code-block:: python
 
         def test_output(capsysbinary):
@@ -1044,7 +1041,6 @@ def capfd(request: SubRequest) -> Generator[CaptureFixture[str], None, None]:
     Returns an instance of :class:`CaptureFixture[str] <pytest.CaptureFixture>`.
 
     Example:
-
     .. code-block:: python
 
         def test_system_echo(capfd):
@@ -1072,7 +1068,6 @@ def capfdbinary(request: SubRequest) -> Generator[CaptureFixture[bytes], None, N
     Returns an instance of :class:`CaptureFixture[bytes] <pytest.CaptureFixture>`.
 
     Example:
-
     .. code-block:: python
 
         def test_system_echo(capfdbinary):
```

I remember we had a PR fixing at least one of those, but can't find it. Maybe I'm misremembering and it was in a different project?

**Comment by bluetech** [comment]
@The-Compiler thanks, this makes more sense. I will submit a fix.
