### ISSUE TITLE
investigate automating pushing releases to conda

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1246]
our packages are simple, we should automate publishing them to conda to reach the scientific community better

**Comment by RonnyPfannschmidt** [comment]
postponing

**Comment by RonnyPfannschmidt** [comment]
closing - anyone caring can pick it up

**Comment by nicoddemus** [comment]
For reference, there's been some talk on [conda-forge regarding automatic publishing](https://github.com/conda-forge/conda-forge.github.io/issues/28) of any pure python package.

**Comment by nicoddemus** [comment]
Also FWIW, there's the [pytest-feedstock](https://github.com/conda-forge/pytest-feedstock) (which I'm also a maintainer).
