### ISSUE TITLE
`xfail`ed tests are reported as `skipped` on `TestReport` instead of `passed`

### ISSUE THREAD

**Issue by scratchmex** [pytest-dev/pytest#12539]
- [X] a detailed description of the bug or problem you are having
- [NA] output of `pip list` from the virtual environment you are using
- [X] pytest and operating system versions
- [X] minimal example if possible

## problem

when we mark a test as `xfail` either with strict or not, we expect to fail so in the report we should have it as `outcome=passed`. in the case of not strict, should always be `passed` or either `xpass`. on strict it should be `fail` if it didn't failed and `passed` or `xfail` otherwise

right now the only way of knowing if it was an xfail or skip is to check `report.wasxfail` attribute

## minimal example

```python
# test_example.py
import pytest

@pytest.mark.xfail
def test_fail():
    assert False
```

```python
# pytest_plugin.py
def pytest_runtest_logreport(report):
    print(report)
```

```bash
python -m pytest -vvvv -s -p pytest_explug
```

```
❯ python -m pytest -vvvv -s -p pytest_plugin
================================= test session starts ==================================
platform darwin -- Python 3.11.7, pytest-7.4.2, pluggy-1.3.0 -- /opt/homebrew/opt/python@3.11/bin/python3.11
cachedir: .pytest_cache
rootdir: /private/tmp/testxfail
plugins: anyio-4.0.0
collected 1 item

test_example.py::test_fail 
<TestReport 'test_example.py::test_fail' when='setup' outcome='passed'>
XFAIL
<TestReport 'test_example.py::test_fail' when='call' outcome='skipped'>
<TestReport 'test_example.py::test_fail' when='teardown' outcome='passed'>
```

## reference

https://github.com/pytest-dev/pytest/blob/f74e947c1fdfef238235b7dd18c8fe52108268f2/src/_pytest/skipping.py#L266-L292

in the code above we have some statements marking the outcome as `skipped` and actually one (I am unaware of that flow) as `passed`
```
rep.outcome = "skipped"
# but also
rep.outcome = "passed"
```

**Comment by Zac-HD** [comment]
Unfortunately this is a restriction for compatibility with [the JUnit xml report format](https://github.com/windyroad/JUnit-Schema/blob/cfa434d4b8e102a8f55b8727b552a0063ee9044e/JUnit.xsd#L73-L132), where the only test statuses are pass/fail/error/skip.
