### ISSUE TITLE
After running `pytest -s -q --allure-stories=="vpn_ipsec"` no use cases are collected

### ISSUE THREAD

**Issue by god-pane** [pytest-dev/pytest#12549]
<!--
After running pytest -s -q --allure-stories=="vpn_ipsec" no use cases are collected
pytest version:  8.2.2

-  The use case is the decorator with the addition of @allure.story('vpn_ipsec')
-  But running  pytest -s -q --allure-stories=="vpn_ipsec" , no testcase running.

**Comment by god-pane** [comment]
- The use case is the decorator with the addition of @allure.story('vpn_ipsec')
- After running pytest -s -q --allure-stories=="vpn_ipsec",  no testcase are running and collected

**Comment by Zac-HD** [comment]
It seems unlikely that this is a Pytest issue - can you share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?
