### ISSUE TITLE
Inject CSS via `html_css_files` rather than inline styles in the sidebar

### ISSUE THREAD

**Issue by pradyunsg** [pytest-dev/pytest#12576]
See https://pradyunsg.me/furo/customisation/injecting/#css-or-js for the guidance from the theme for how to inject CSS.

_Originally posted by @pradyunsg in https://github.com/pytest-dev/pytest/pull/12326#discussion_r1666516622_

**Comment by nicoddemus** [comment]
Thanks @pradyunsg!

Marking @samjirovec here in case he would like to tackle this.
