### ISSUE TITLE
AttributeError raised from junitxml with  pytest-flakes and pytest-pep8

### ISSUE THREAD

**Issue by cazino** [pytest-dev/pytest#1259]
An exception is raised from junitxml when used with pytest-flakes and pytest-pep8.

```
_pytest/junitxml.py", line 334, in update_testcase_duration
AttributeError: '_NodeReporter' object has no attribute 'duration'
```

To reproduce : 

```
#!/bin/bash
virtualenv node_reporter_bug_env
. node_reporter_bug_env/bin/activate
pip install pytest pytest-flakes pytest-pep8
touch src.py
py.test --flakes --pep8 --junit-xml=report.xml src.py
```

This was introduced by the 2.8.5 release, it does not occur in 2.8.4. It is related to this : https://github.com/pytest-dev/pytest/pull/1091/files#diff-d2b19ef5068babedac3db6153497a347R188

I don't know if the 'finalize' method is called too early or if it should not do so much cleaning. If someone could give some hints on what is wrong, I would be glad to try to provide a patch.

**Comment by nicoddemus** [comment]
Thanks for the report @cazino!

IMHO we should get rid of the `finalize` method and instead just store the converted XML representation at that point, discarding the `_NodeReporter` instance, instead of keeping the instance around without any attributes.

**Comment by RonnyPfannschmidt** [comment]
after finalization the item should be removed from the mapping finalization needs to be reordered
this regression is my mistake - i expected the test for double id's to catch it

**Comment by nicoddemus** [comment]
> after finalization the item should be removed from the mapping finalization needs to be reordered

I agree, but perhaps it would be simpler still to just get rid of `_NodeReporter.finalize()` at all? I mean, instead of:

```python
    if report.when == "teardown":
        self.node_reporter(report).finalize()
```

We can just get the xml representation and save it separately, while discarding the reporter instance:

```python
    if report.when == "teardown":
        reporter = self.node_reporter(report)
        self.xml_testsuites.append(reporter.to_xml())
        del self.node_reporters[reporter.key]
```

`xml_testsuites` would replace `node_reporters_ordered`, as there's no need to keep the node reporters sorted anymore, `xml_testsuites` will contain the xml snippets ready for dumping to the file during `pytest_sessionfinish`. 

Hope my explanation makes sense! :sweat_smile: 

> this regression is my mistake - i expected the test for double id's to catch it

No worries, it happens. :smile:

**Comment by RonnyPfannschmidt** [comment]
its missing a call to unicode(), we dont want to keep the xml tree

the main reason finalize clears things up so radically is to show bugs
in the long term i'd rather se py.test return to creating unique test ids per node

**Comment by nicoddemus** [comment]
> its missing a call to unicode(), we dont want to keep the xml tree

`to_xml()` doesn't already return a `unicode`?

**Comment by RonnyPfannschmidt** [comment]
no, the finalize method makes the unicode as of now

**Comment by cazino** [comment]
As the bug is critical, I'll leave the patch to you guys.

**Comment by RonnyPfannschmidt** [comment]
the patch itself is small i think, the test is whats tricky

**Comment by charlax** [comment]
Happening to me as well.
