### ISSUE TITLE
provide pathlib based paths in compat and plain flavours to enable removal of py.path usage in pytest 3.0

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1260]
in order to get rid of the py.path legacy it is neccessary to provide a upgrade path
i propose adding a config option to handle legacy, compat and path based path objects for tmpdir, cache & co

leacy should be the default in the 2.9 release
if there is a 2.10 it should make compat the default

3.0 should drop the legacy and only offer pathlib

the canonical implementation should be pathlib2, since its on a recent state and works on 2.7, and 3.x

the compat flavour should warn with deprecationwarning subclasses to note the method removal in pytest 3.0

**Comment by The-Compiler** [comment]
I'm really sorry for hijacking this thread, but I'm trying to debug an issue with github support: Does anyone else see missing dots (`pypath`, `29` and `110` instead of `py.path`, `2.9` and `1.10`) in the issue mail sent for this issue from GitHub?

**Comment by astraw38** [comment]
@The-Compiler I do not see the dots in the email received from github.

**Comment by nicoddemus** [comment]
@The-Compiler Yep, me too.

**Comment by RonnyPfannschmidt** [comment]
clearing the milestone, perhaps aiming for 4.0 is more realistic

**Comment by Zac-HD** [comment]
Closed by #3988, I think - `py.path` is only a shim now and emits deprecation warnings 🎉
