### ISSUE TITLE
Security issue introduced in pytest@7.4.4 - zipp@3.15.0

### ISSUE THREAD

**Issue by igorgiumellizup** [pytest-dev/pytest#12602]
Hello

My Snyk check reported the following:

> ![image](https://github.com/user-attachments/assets/a458e008-fa5f-4575-8136-e42cc3f9e708)

The remediation recommended is:

> ![image](https://github.com/user-attachments/assets/8ee158e7-2c93-451d-8fbc-50dfd95304fc)

Source:
https://github.com/jaraco/zipp/commit/fd604bd34f0343472521a36da1fbd22e793e14fd
https://github.com/jaraco/zipp/issues/119
https://github.com/jaraco/zipp/pull/120

**Comment by RonnyPfannschmidt** [comment]
Based on the dependency tree this only applies when python path has been compromised severely 

That not part of the thread model for pytest 


Users that pin can sort it in their own pins

**Comment by igorgiumellizup** [comment]
Is there a way to force pytest import the latest zipp?
My `requirements.txt` is:
zipp
pyyaml
pexpect
pytest
pytest-split-tests

But the vulnerability still exists
