### ISSUE TITLE
With pytest.mark.parameterize(), Chinese is displayed in Unicode encoding

### ISSUE THREAD

**Issue by two867** [pytest-dev/pytest#12612]
When using pytest to parameterize the test case, if the parameter value contains Chinese characters, then the Chinese characters in the test result will be displayed in Unicode encoding form. Can the original characters be displayed?

pytest version: 8.2.2

If you look at the picture, it will be clearer.

![Snipaste_2024-07-15_15-20-58](https://github.com/user-attachments/assets/799c6f43-b6e3-4edc-8067-b323171a383c)

**Comment by two867** [comment]
It can lead to unexpected multilevel directories. see
![Snipaste_2024-07-15_16-01-15](https://github.com/user-attachments/assets/22b95f2b-920f-4a59-9259-7100b4709dd1)

**Comment by RonnyPfannschmidt** [comment]
the boolean configuration option `disable_test_id_escaping_and_forfeit_all_rights_to_community_support` was introduced to enable this

as unicode normalization differences between file-systems, platforms & co still create havoc such a off-putting name was picked
