### ISSUE TITLE
Cannot install in custom directory

### ISSUE THREAD

**Issue by davidedelvento** [pytest-dev/pytest#1261]
In py.test v2.7.0 the following worked:

pip install pytest --install-option="--prefix=/path/to/my/dir"

In current 2.8.5 the option is silently ignored, and it tries to install in /path/to/my/python/install/lib/python2.7/site-packages/ (it may succeed or fail depending on the permissions)

**Comment by davidedelvento** [comment]
This may be related to https://github.com/pypa/pip/pull/3252 (I'm running pip v1.5.6 from python v2.7.7) but the current workaround of using --target instead does not work since py.test needs to install scripts, beside pure python modules.

**Comment by nicoddemus** [comment]
Sorry but I think this is clearly a `pip` issue, so I'm closing this, but feel free to reopen if you disagree. :smile:

**Comment by davidedelvento** [comment]
Yes, it is a pip issue, which it affects everything up to the latest release.
The fix has been merged, however it is not clear when it will be available for install. Until then, pytest is not usable for me. As a workaround, I could use pip's `--target` option, but that installs only stuff that would be installed into `lib/python2.7/site-packages/`, which clearly is not enough for pytest.

Can you confirm that in the current version only bin/py.test  and bin/py.test-2.8 needs to be installed outside of `lib/python2.7/site-packages/`

**Comment by nicoddemus** [comment]
I think if the directory for your `--target` option is on `PYTHONPATH`, `python -m pytest` should work.
