### ISSUE TITLE
A problem with the pytest library not having the hookimpl attribute.

### ISSUE THREAD

**Issue by sakura040616M** [pytest-dev/pytest#12617]
- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible
 
I am currently deploying yolov8 and expect it to accept images from Intel d435 cameras for real-time object recognition. I'm using python3.11, and I've tried many versions of pytest with this problem, including the latest versions 8.2.2 to 8.1.1.

This is the error:
AttributeError: module 'pytest' has no attribute 'hookimpl'

This is my code:
`import` pyrealsense2 as rs
import numpy as np
import cv2
from ultralytics import YOLO

def initialize_realsense():
    # Configure depth and color streams
    pipeline = rs.pipeline()
    config = rs.config()
    config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
    config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)

    # Start streaming
    pipeline.start(config)
    return pipeline

def get_frame(pipeline):
    frames = pipeline.wait_for_frames()
    color_frame = frames.get_color_frame()
    if not color_frame:
        return None

    # Convert image to numpy array
    color_image = np.asanyarray(color_frame.get_data())
    return color_image

def draw_boxes(image, detections):
    for detection in detections:
        x1, y1, x2, y2 = map(int, detection.xyxy[0].tolist())  # Extract the bounding box coordinates
        conf = detection.conf[0]  # Extract the confidence score
        cls = detection.cls[0]  # Extract the class I
        label = f'{detection.names[int(cls)]} {conf:.2f}'  # Extract the class name
        cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(image, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

def main():
    pipeline = initialize_realsense()
    model = YOLO('yolov8n.pt')  
    try:
        while True:
            frame = get_frame(pipeline)
            if frame is None:
                continue

            # Perform object detection
            results = model(frame)

            # Draw bounding boxes on the frame
            for result in results:
                draw_boxes(frame, result.boxes)  # 修改为 result.boxes

            # Display the frame
            cv2.imshow('RealSense YOLOv8', frame)

            # Exit on ESC key
            if cv2.waitKey(1) & 0xFF == 27:
                break
    finally:
        # Stop streaming
        pipeline.stop()
        cv2.destroyAllWindows()

if __name__ == "__main__":
    main()
`
And this is my pip list:
Package                   Version
------------------------- -----------
altair                    5.3.0
attrs                     23.2.0
blinker                   1.8.2
Bottleneck                1.3.7
Brotli                    1.0.9
cachetools                5.4.0
certifi                   2024.7.4
charset-normalizer        2.0.4
click                     8.1.7
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.2.0
cycler                    0.11.0
exceptiongroup            1.2.0
filelock                  3.13.1
fire                      0.6.0
flatbuffers               2.0
fonttools                 4.51.0
fsspec                    2024.3.1
gitdb                     4.0.11
GitPython                 3.1.43
gmpy2                     2.1.2
huggingface_hub           0.23.1
humanfriendly             10.0
idna                      3.7
importlib-metadata        7.0.1
iniconfig                 1.1.1
Jinja2                    3.1.4
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.4
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.8.4
mdurl                     0.1.2
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
mpmath                    1.3.0
networkx                  3.3
numexpr                   2.8.7
numpy                     1.26.4
onnxruntime               1.17.1
opencv-contrib-python     4.10.0.84
opencv-python             4.9.0.80
opencv-python-headless    4.10.0.84
packaging                 24.1
pandas                    2.2.2
pillow                    10.4.0
pip                       24.0
pluggy                    1.5.0
ply                       3.11
protobuf                  3.20.3
psutil                    5.9.0
pyarrow                   16.1.0
pybboxes                  0.1.6
pydeck                    0.9.1
Pygments                  2.18.0
pyparsing                 3.0.9
PyQt5                     5.15.10
PyQt5-sip                 12.13.0
pyreadline3               3.4.1
pyrealsense2              2.55.1.6486
PySocks                   1.7.1
pytest                    8.1.2
python-dateutil           2.9.0.post0
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
regex                     2023.10.3
requests                  2.32.2
rich                      13.7.1
rpds-py                   0.19.0
safetensors               0.4.2
sahi                      0.11.18
scipy                     1.13.1
setuptools                69.5.1
shapely                   2.0.1
sip                       6.7.12
six                       1.16.0
smmap                     5.0.1
streamlit                 1.36.0
streamlit-select          0.3
sympy                     1.12
tenacity                  8.5.0
termcolor                 2.4.0
terminaltables            3.1.10
tokenizers                0.15.1
toml                      0.10.2
tomli                     2.0.1
toolz                     0.12.1
torch                     2.2.2
torchaudio                2.2.2
torchvision               0.17.2
tornado                   6.4.1
tqdm                      4.66.4
transformers              4.37.2
typing_extensions         4.11.0
tzdata                    2023.3
unicodedata2              15.1.0
urllib3                   2.2.2
watchdog                  4.0.1
wheel                     0.43.0
win-inet-pton             1.1.0
zipp                      3.17.0

**Comment by RonnyPfannschmidt** [comment]
Please use code blocks and inform us about the filenames you use 

Also please paste a traceback
