### ISSUE TITLE
8.3.0 release?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#12611]
We have a [fair share of improvements and new features](https://docs.pytest.org/en/latest/changelog.html#to-be-included-in-vrelease-if-present) lined up, also things from the sprint such as #12281 or #389.

I think it might be time for a 8.3? Not volunteering unfortunately, as I'm off for two weeks of holidays now :wink:

cc @lovetheguitar

**Comment by bluetech** [comment]
I can volunteer for this weekend.

**Comment by nicoddemus** [comment]
Yeah a new release sounds good. Thanks @bluetech for stepping in. :+1:

**Comment by winstonsung** [comment]
It seems the default version in the [Read the Docs Settings](https://readthedocs.org/dashboard/pytest/advanced/) was not pointed to the new branch `8.3.x` .

<https://github.com/pytest-dev/pytest/blob/643845f/RELEASING.rst#releasing>

**Comment by nicoddemus** [comment]
Thanks @winstonsung!

I changed the default version to point to `stable`, which [according to ReadTheDocs](https://docs.readthedocs.io/en/stable/versions.html#versions):

> If your project has any tags or branches with a name following [semantic versioning](https://semver.org/), we also create a stable version, tracking your most recent release. If you want a custom stable version, create either a tag or branch in your project with that name.


Closing this issue now.

**Comment by The-Compiler** [comment]
> I changed the default version to point to `stable`

We deliberately avoided doing that, see #9606. Though admittedly I don't remember the details of *why*. At the very least I suppose we should revert that commit then, no?

**Comment by nicoddemus** [comment]
Ahh thanks!

Yeah I did test after the setting and it seemed to work: https://docs.pytest.org goes to https://docs.pytest.org/en/stable, and that is the correct version.

Probably this has been fixed since then?

**Comment by The-Compiler** [comment]
I don't think it was an issue with RTD on its own, I think it was more that we didn't want external links to `/stable` getting outdated and pointing to invalid locations for newer updates maybe? But I suppose there's also value in people seeing the newest documentation by default.
