### ISSUE TITLE
pytest.mark.xfail from inside the test is ignored

### ISSUE THREAD

**Issue by tsyg** [pytest-dev/pytest#12649]
When `pytest.mark.xfail` is used inside a test - it is not causing the test to be marked as xfail.
The sample code:

```python
import pytest

@pytest.mark.parametrize("way", [
    "fresh",  # OK
    pytest.param("mix", marks=pytest.mark.xfail(reason="known_issue_with_MIX", strict=True)),
    "mixed",
])
def test_demo(way):
    print(f"testing - {way}")
    if way.startswith("mix"):
        pytest.mark.xfail(reason="mix has known issue!")  # Here - is ignored?
        print("NOTE: Marked sa xfail - see the result..")
    assert way.startswith("fr"), "only 'fr*' way is OK"

``` 
Expected result: 
 "fresh" test passed, "mix" and "mixed" ones treated as known issue (xfail)

Actual result: "mixed" test is shown failed.

```
> pip list
Package            Version
------------------ ----------
AllPairs           2.0.1
allpairspy         2.5.1
certifi            2023.11.17
charset-normalizer 3.3.2
colorama           0.4.6
idna               3.6
iniconfig          2.0.0
packaging          23.2
pip                23.3.1
pluggy             1.3.0
pyserial           3.5
pytest             7.4.3
requests           2.31.0
setuptools         69.0.2
urllib3            2.1.0
wheel              0.41.3
``` 
got the same in another venv:
pytest: 8.1.1
Python: 3.12.2
Platform: Windows-11-10.0.22631-SP0
pluggy: 1.5.0
Plugins:
- html: 4.1.1
- metadata: 3.1.1

![Screenshot 2024-07-22 192401](https://github.com/user-attachments/assets/379b4c5d-3b48-4115-9fdb-38853208d758)

**Comment by RonnyPfannschmidt** [comment]
creating a mark object without pitting it onto a test node is not going to do anything, did you mean to invoke pytest.xfail?

for applying the xfail mark later, its necessary to apply it to the current test item

**Comment by tsyg** [comment]
Thank you for the quick response. 
Yes, I mean invoking pytest.xfail.  I now found the sample in docs.
Once I replaced with `pytest.xfail(reason="mix has known issue!") ` - Got the expected behavior.

Sorry for false alarm. Let's close the ticket.
Thanks!
