### ISSUE TITLE
Too tight a type constraint on ExceptionInfo.errisinstance

### ISSUE THREAD

**Issue by gmc444-b** [pytest-dev/pytest#12667]
- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions (pytest versions; error should be OS-independent)
- [x] minimal example if possible

With pytest 8.2.2 the declaration of `ExceptionInfo.errisinstance` was

```Python
     def errisinstance(
        self, exc: Union[Type[BaseException], Tuple[Type[BaseException], ...]]
    ) -> bool:
```

With 8.3.1, this has changed, first by introducing a type spec, and then using that typespec for the function signature

```Python
EXCEPTION_OR_MORE = Union[Type[Exception], Tuple[Type[Exception], ...]]
    ...
    def errisinstance(self, exc: EXCEPTION_OR_MORE) -> bool:
```

Version 8.2.2 would pass a `mypy` check with the following reproducer. Version 8.3.1 fails (I didn't test with 8.3.0 but I'd expect that to also fail). I tested this with mypy versions 1.10.1 and 1.11.0, but I'd expect it to fail for pretty much any supported version of mypy.

```Python
import sys
import pytest


def test_iserrinstance() -> None:
    def bad() -> None:
        sys.exit()

    with pytest.raises(BaseException) as exc:
        bad()
    assert exc.errisinstance(SystemExit)

# Error output:
python3.10 -m mypy reproducer.py
reproducer.py:12: error: "ExceptionInfo[BaseException]" has no attribute "iserrinstance"; maybe "errisinstance"?  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

The change was made in [this commit ](https://github.com/pytest-dev/pytest/commit/9295f9ffffc11595cc4d7241008f60783f1f46c2#diff-ac2099a172465905236568f8c175328fb75ebc1b80ce39f4799e61373d355418) but I'm not finding an explanation there as to why the type was changed from `BaseException` to `Exception`.

To me, it looks like the best fix is to change EXCEPTION_OR_MORE to

```Python
EXCEPTION_OR_MORE = Union[Type[BaseException], Tuple[Type[BaseException], ...]]
```

restoring backward compatibility.

**Comment by RonnyPfannschmidt** [comment]
This is a oversight on my part,it needs a fix

**Comment by nicoddemus** [comment]
Just to clarify @RonnyPfannschmidt is that something you will tackle, or PRs are welcome?

**Comment by RonnyPfannschmidt** [comment]
Prs Welcome, I'm not at capacity ATM
