### ISSUE TITLE
CLI flag for supporting env variables from .env file

### ISSUE THREAD

**Issue by HardFlashDisk** [pytest-dev/pytest#12674]
#### What's the problem this feature will solve?
This solution is going to make easier for retrieving environnement variables without specifing them into the `pytest` command.

#### Describe the solution you'd like
```python
pytest --env foobar.env
```

#### Alternative Solutions
```python
import os

import pytest
from dotenv import load_dotenv


@pytest.fixture(scope='session', autouse=True)
def load_env():
    load_dotenv()
```

**Comment by webknjaz** [comment]
Have you considered making a plugin instead?

**Comment by RonnyPfannschmidt** [comment]
This is out of scope for core 

The env plugin might be a better place

**Comment by The-Compiler** [comment]
[pytest-dotenv](https://pypi.org/project/pytest-dotenv/) already exists, plus a trivial `conftest.py` implementation. I don't think there's anything to gain from this living in the core.
