### ISSUE TITLE
Fixtures for single method in unittest.TestCase

### ISSUE THREAD

**Issue by brickgao** [pytest-dev/pytest#1271]
Hi,

I found there is support for fixtures for unittest.Testcase in class scope.

But when I try to use fixtures for single method in unittest.TestCase like this, it's not work:

```python
# conftest.py
import pytest


@pytest.fixture(scope="function")
def smtp():
    import smtplib
    return smtplib.SMTP("smtp.gmail.com")

# test_smtp.py
import unittest


class TestSMTP(unittest.TestCase):

    @pytest.mark.usefixtures("smtp")
    def  test_ehlo(self, smtp):
        response, msg = smtp.ehlo()
        assert response == 250
        assert b"smtp.gmail.com" in msg
        assert 0  # for demo purposes
```

How could I use the fixtures for single method in unittest.TestCase? Thanks :)

The version of Python is 2.7.11, the version of pytest is 2.8.4 .

**Comment by nicoddemus** [comment]
This is not supported, as the [docs](http://pytest.org/latest/unittest.html?highlight=unittest) say:

> While pytest supports receiving fixtures via test function arguments for non-unittest test methods, unittest.TestCase methods cannot directly receive fixture function arguments as implementing that is likely to inflict on the ability to run general unittest.TestCase test suites. 

So I'm closing this for now. :smile:

**Comment by brickgao** [comment]
@nicoddemus Thanks :)

**Comment by RonnyPfannschmidt** [comment]
a workaround is a intermediate fixture that will set an instance attribute in combination with the usefixtures marker
