### ISSUE TITLE
support having pytest.ini inside a configuration folder

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1272]
this relates to 
https://bitbucket.org/hpk42/tox/issues/298/support-having-toxini-in-a-configuration and
https://bitbucket.org/hpk42/tox/issues/297

in order to stop littering the project root folder lets start to support a configuration folder, the name i propose is `.config`

**Comment by RonnyPfannschmidt** [comment]
closing as abandoned for now

**Comment by gnikonorov** [comment]
Can we re-open this @RonnyPfannschmidt ? I'd like to implement this if that's ok

**Comment by RonnyPfannschmidt** [comment]
As neither the idea for the standard catched on, nor did the implementation happen timely, i would prefer to leave it as is

**Comment by gnikonorov** [comment]
Sure
