### ISSUE TITLE
Fixture with session scope runs more than once unless placed in conftest.py

### ISSUE THREAD

**Issue by bradleyharden** [pytest-dev/pytest#12727]
I'm not sure if this is intended behavior or not.

I'm trying to create a fixture with `scope="session"`. However, I would prefer to use explicit import of fixtures rather than `conftest.py`. Is that supported? If I use an explicitly imported fixture, it's always evaluated once per module, even with `scope="session"`.

Here's a minimal example:

Directory structure:
```
.
└── src
    ├── conftest.py
    ├── __init__.py
    ├── test_one.py
    └── test_two.py
```

`__init__.py`:
```python
import pytest

@pytest.fixture(scope="session")
def init_fixture():
    print("\ninit setup")
    yield
    print("\ninit teardown")
```

`conftest.py`:
```python
import pytest

@pytest.fixture(scope="session")
def conftest_fixture():
    print("\nconftest setup")
    yield
    print("\nconftest teardown")
```

`test_one.py`:
```python
from . import init_fixture

def test_a(init_fixture, conftest_fixture):
    pass
```

`test_two.py`:
```python
from . import init_fixture

def test_b(init_fixture, conftest_fixture):
    pass
```

Execution
```
$ pytest -s
================ test session starts =================
platform linux -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/...
collected 2 items                                    

src/test_one.py 
init setup

conftest setup
.
src/test_two.py 
init setup
.
init teardown

conftest teardown

init teardown


================= 2 passed in 0.01s ==================
```

```
$ pip list
Package   Version
--------- -------
iniconfig 2.0.0
packaging 24.1
pip       24.0
pluggy    1.5.0
pytest    8.3.2
```

**Comment by The-Compiler** [comment]
At the very end of [How to use fixtures - pytest documentation](https://docs.pytest.org/en/latest/how-to/fixtures.html#how-to-fixtures):

> Sometimes users will import fixtures from other projects for use, however this is not recommended: importing fixtures into a module will register them in pytest as *defined* in that module.
> 
> This has minor consequences, such as appearing multiple times in `pytest --help`, but it is not **recommended** because this behavior might change/stop working in future versions.

**Comment by bradleyharden** [comment]
Ah, importing is explicitly discouraged. I didn't catch that. Sorry about that. I probably saw "Using fixtures from other projects" and didn't bother to read it, because I'm importing from my own code.

I'll stick with `conftest.py` for now. That being said, I think it would be nice if importing were better supported. Fixtures in general are a bit magical, and `conftest.py` doesn't do much to lessen that. With explicit imports, at least I can say, "I am using _these_ fixtures defined in _these_ files". But maybe I'm just misunderstanding or misusing `pytest`? I'm not sure.

Anyway, thanks for your help.
