### ISSUE TITLE
Enable test cases to be executed in a coroutine manner

### ISSUE THREAD

**Issue by tdxs8848** [pytest-dev/pytest#12721]
#### What's the problem this feature will solve?

I hope all test cases can be initiated through coroutines to efficiently utilize the waiting time of the program. With the increase in the number of use cases, it has become increasingly difficult to improve by simply adding the number of processes

#### Describe the solution you'd like

Use the same event loop to start all use cases simultaneously
#### Alternative Solutions

I have used pytest syncio cooperative, pytest parallel, etc., but they have encountered many exceptions when running
#### Additional context

Although this approach may disrupt the data independence between test cases or lead to competition for some shared variables. But for long waiting or IO intensive test cases, it can significantly reduce testing time

**Comment by RonnyPfannschmidt** [comment]
The ask here is for pretty much a completely breaking change of most internals to run tests in a ways that breaks dozens of common patterns 


I believe the answer is a solid no
