### ISSUE TITLE
drop python 2.6 support when pip does

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1273]
python 2.6 is eol since a while now - if people want to stay on old version they can pin py.test 2.8

**Comment by nicoddemus** [comment]
Some blog posts related:

* [Stop Supporting Python 2.6 (For Free)](http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html)
* [Stop using Python 2.6 pleas](http://www.snarky.ca/stop-using-python-2-6)

**Comment by nicoddemus** [comment]
Perhaps it would be nice to post a link to the mailing list to gather feedback? I don't have a clear idea of how many users still only use 2.6.

One thing I've missed when working on py.test is dict comprehensions and set literals... other than that I have not hit any major roadblocks, so I'm +0 on the idea.

**Comment by flub** [comment]
Other then one less version to test for, is there anything which is gained
from dropping 2.6?  If there's a specific patch/feature which struggles
with 2.6 support then it makes sense to drop for me, but if not I'm
probably -0

**Comment by RonnyPfannschmidt** [comment]
We have a few 2.6 only bugs and 2.6 is eol

Also 2.6 prevented details like pytest as a package

**Comment by nicoddemus** [comment]
To me pinning 2.6 for projects which depend on that seems reasabable...

**Comment by RonnyPfannschmidt** [comment]
twitter feedback seems positive, what other channels should i stir up?

**Comment by nicoddemus** [comment]
I would send an email to the mailing list

**Comment by RonnyPfannschmidt** [comment]
closing after crosschecking with pip

**Comment by nicoddemus** [comment]
> closing after crosschecking with pip

What do you mean @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
pip tries to follow pytest latest and will support python 2.6 in the 7 series and possibly in the 8 series

**Comment by nicoddemus** [comment]
So in conclusion, we will follow `pip`'s lead here, and drop 2.6 when they also drop it?

**Comment by nicoddemus** [comment]
Oh sorry, I just now saw #1308... sorry for the noise

**Comment by nicoddemus** [comment]
I think we should re-open this, because we will eventually drop 2.6. We should just rename it to make it clear that we are following pip's lead on this (*"Drop python 2.6 support after pip does the same"* or something like that).

Creating a new one is also valid, but I think re-using this would be better because it will keep the history of this conversation.

**Comment by The-Compiler** [comment]
Removing the 2.9 milestone as we agreed to postpone this until pip drops 2.6

**Comment by nicoddemus** [comment]
We're close: pypa/pip#4343 has been merged. I suppose pip `10.0` will drop it. 👍

**Comment by nicoddemus** [comment]
Dropping 2.6 support would warrant a pytest-4.0 release?

**Comment by RonnyPfannschmidt** [comment]
i think so

**Comment by nicoddemus** [comment]
Fixed in #2822
