### ISSUE TITLE
Use proper RST in the CHANGELOG

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1274]
Currently the `CHANGELOG` file is included in [the docs](http://pytest.org/latest/changelog.html), but we don't ask people to write correct RST on it, with links, formatting, and etc.

Recently I have changed [pytest-qt's changelog](https://pytest-qt.readthedocs.org/en/1.10.0/changelog.html) to use correct formatting, and the results seem much better to my eyes.

I propose we start doing the same with `2.9.X` CHANGELOG.

Applying formatting, [here's how](https://gist.github.com/nicoddemus/e2e1dda5740dce17b029) the change log would look like, and here it is in plain text:

```rst
2.9.0.dev
---------

* New ``pytest.mark.skip`` mark, which unconditional skips marked tests.
  Thanks `@MichaelAquilina`_ for the complete PR (`#1040`_).

* Fix `#680`_: the -s and -c options should now work under xdist;
  ``Config.fromdictargs`` now represents its input much more faithfully.
  Thanks to `@bukzor`_ for the complete PR.

.. _#1040: https://github.com/pytest-dev/pytest/pull/1040
.. _#680: https://github.com/pytest-dev/pytest/issues/680
.. _@MichaelAquilina: https://github.com/MichaelAquilina
.. _@bukzor: https://github.com/bukzo
```

It of course is harder to read, but the benefits out-weight the disadvantages IMO. I'm proposing doing it only for the 2.9 series and onward, as converting it is a manual and boring process. I also volunteer on doing it. :smile:

This was taken from a discussion with @RonnyPfannschmidt on gtalk. @hpk42, @The-Compiler, @flub, any opinions?

**Comment by RonnyPfannschmidt** [comment]
I'm +1 on this, how hard would a longer be ?

**Comment by nicoddemus** [comment]
>  how hard would a longer be ?

What do you mean @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
I meant to write "linter", then autocomplete made it to longer

**Comment by nicoddemus** [comment]
Good idea, we can use [rst-lint](https://pypi.python.org/pypi/restructuredtext_lint).

**Comment by RonnyPfannschmidt** [comment]
Looks good, +1
