### ISSUE TITLE
ModuleNotFoundError: No module named '_time_machine'

### ISSUE THREAD

**Issue by Halcyon905** [pytest-dev/pytest#12751]
When I try to run pytest in my project, it gives the error:
```
ModuleNotFoundError: No module named '_time_machine'
```
I am using PDM to manage the packages and dependencies, when using 'pdm list' it gives out:
| package                 | version   | tmp |
|-------------------------|-----------|-----|
| alembic                 | 1.13.2    |     |
| aniso8601               | 9.0.1     |     |
| annotated-types         | 0.7.0     |     |
| anyio                   | 4.4.0     |     |
| asttokens               | 2.4.1     |     |
| attrs                   | 24.2.0    |     |
| backoff                 | 2.2.1     |     |
| beautifulsoup4          | 4.12.3    |     |
| boto3                   | 1.35.9    |     |
| botocore                | 1.35.9    |     |
| bs4                     | 0.0.2     |     |
| catboost                | 1.2.5     |     |
| certifi                 | 2024.8.30 |     |
| charset-normalizer      | 3.3.2     |     |
| click                   | 8.1.7     |     |
| click-plugins           | 1.1.1     |     |
| cligj                   | 0.7.2     |     |
| cloudpickle             | 3.0.0     |     |
| cmdstanpy               | 1.2.4     |     |
| colorama                | 0.4.6     |     |
| coloredlogs             | 14.0      |     |
| contourpy               | 1.3.0     |     |
| croniter                | 3.0.3     |     |
| cycler                  | 0.12.1    |     |
| dagster                 | 1.6.6     |     |
| dagster-aws             | 0.22.6    |     |
| dagster-docker          | 0.22.6    |     |
| dagster-graphql         | 1.6.6     |     |
| dagster-pipes           | 1.6.6     |     |
| dagster-postgres        | 0.22.6    |     |
| decorator               | 5.1.1     |     |
| docker                  | 7.1.0     |     |
| docker-image-py         | 0.1.13    |     |
| docstring_parser        | 0.16      |     |
| et-xmlfile              | 1.1.0     |     |
| exceptiongroup          | 1.2.2     |     |
| executing               | 2.0.1     |     |
| Farama-Notifications    | 0.0.4     |     |
| fast-ml                 | 3.68      |     |
| filelock                | 3.15.4    |     |
| fiona                   | 1.9.6     |     |
| fonttools               | 4.53.1    |     |
| fsspec                  | 2024.6.1  |     |
| geopandas               | 0.14.0    |     |
| geovoronoi              | 0.4.0     |     |
| gower                   | 0.1.2     |     |
| gql                     | 3.5.0     |     |
| graphene                | 3.3       |     |
| graphql-core            | 3.2.3     |     |
| graphql-relay           | 3.2.0     |     |
| graphviz                | 0.20.3    |     |
| greenlet                | 3.0.3     |     |
| grpcio                  | 1.66.1    |     |
| grpcio-health-checking  | 1.62.3    |     |
| gymnasium               | 0.29.1    |     |
| holidays                | 0.55      |     |
| humanfriendly           | 10.0      |     |
| idna                    | 3.8       |     |
| importlib_resources     | 6.4.4     |     |
| iniconfig               | 2.0.0     |     |
| ipython                 | 8.25.0    |     |
| jedi                    | 0.19.1    |     |
| Jinja2                  | 3.1.4     |     |
| jmespath                | 1.0.1     |     |
| joblib                  | 1.4.2     |     |
| kiwisolver              | 1.4.5     |     |
| lightgbm                | 4.5.0     |     |
| Mako                    | 1.3.5     |     |
| markdown-it-py          | 3.0.0     |     |
| MarkupSafe              | 2.1.5     |     |
| matplotlib              | 3.9.0     |     |
| matplotlib-inline       | 0.1.7     |     |
| mdurl                   | 0.1.2     |     |
| mpmath                  | 1.3.0     |     |
| multidict               | 6.0.5     |     |
| networkx                | 3.3       |     |
| numpy                   | 1.26.1    |     |
| openpyxl                | 3.1.4     |     |
| osmnx                   | 1.9.3     |     |
| overpy                  | 0.7       |     |
| packaging               | 24.1      |     |
| pandas                  | 2.2.2     |     |
| parso                   | 0.8.4     |     |
| patsy                   | 0.5.6     |     |
| pendulum                | 3.0.0     |     |
| pillow                  | 10.4.0    |     |
| plotly                  | 5.24.0    |     |
| pluggy                  | 1.5.0     |     |
| prompt_toolkit          | 3.0.47    |     |
| prophet                 | 1.1.5     |     |
| protobuf                | 4.25.4    |     |
| psutil                  | 6.0.0     |     |
| psycopg2-binary         | 2.9.9     |     |
| pure_eval               | 0.2.3     |     |
| py-spy                  | 0.3.14    |     |
| pyarrow                 | 16.1.0    |     |
| pydantic                | 2.8.2     |     |
| pydantic_core           | 2.20.1    |     |
| Pygments                | 2.18.0    |     |
| pykan                   | 0.0.5     |     |
| pyparsing               | 3.1.4     |     |
| pyproj                  | 3.6.1     |     |
| pyreadline3             | 3.4.1     |     |
| pytest                  | 8.3.2     |     |
| python-dateutil         | 2.9.0.post0|    |
| python-dotenv           | 1.0.1     |     |
| pytz                    | 2024.1    |     |
| pywin32                 | 306       |     |
| PyYAML                  | 6.0.2     |     |
| regex                   | 2024.7.24 |     |
| requests                | 2.32.3    |     |
| requests-toolbelt       | 1.0.0     |     |
| rich                    | 13.8.0    |     |
| s3transfer              | 0.10.2    |     |
| scikit-learn            | 1.5.0     |     |
| scipy                   | 1.14.1    |     |
| seaborn                 | 0.13.2    |     |
| setuptools              | 74.0.0    |     |
| shapely                 | 2.0.6     |     |
| six                     | 1.16.0    |     |
| sniffio                 | 1.3.1     |     |
| soupsieve               | 2.6       |     |
| SQLAlchemy              | 2.0.32    |     |
| stable_baselines3       | 2.3.2     |     |
| stack-data              | 0.6.3     |     |
| stanio                  | 0.5.1     |     |
| starlette               | 0.38.2    |     |
| statsmodels             | 0.14.2    |     |
| structlog               | 24.4.0    |     |
| sympy                   | 1.13.2    |     |
| tabulate                | 0.9.0     |     |
| tenacity                | 9.0.0     |     |
| threadpoolctl           | 3.5.0     |

I am doing project on windows 11 version 22H2. I have tried reinstalling the packages and matched the versions of pytest and time-machine to my friends and it still gives out the same error.

**Comment by dongfangtianyu** [comment]
Hi @Halcyon905 ，can you supplement the complete tracking stack ? This analysis of the problem provides great help.


For example:
```
>pytest --import-mode=importlib

==================== test session starts ===================
platform win32 -- Python 3.12.0, pytest-8.3.2, pluggy-1.5.0
rootdir: D:\app
plugins: allure-pytest-2.13.5
collected 0 items / 1 error

========================== ERRORS ==========================
____________ ERROR collecting a/b/c/test_demo.py ____________
<frozen importlib._bootstrap_external>:1533: in find_spec
    ???
<frozen importlib._bootstrap_external>:1334: in __init__
    ???
<frozen importlib._bootstrap_external>:1350: in _get_parent_path
    ???
E   KeyError: 'a.b'

=================== short test summary info =================
ERROR a/b/c/test_demo.py - KeyError: 'a.b'
!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!
========================= 1 error in 0.10s ===================
```

**Comment by Halcyon905** [comment]
Thanks for the reply! However, it seems that I have solved the issue by changing the python I was using to a different one.
