### ISSUE TITLE
Separate issues in the CHANGELOG into sections

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1275]
Currently we don't have any organization on how issues are displayed in the `CHANGELOG`. This makes it harder for people reading it to focus on what might affect then, for example the recent changes in behavior for `2.8` (returning non-zero when no tests were executed, yellow status bar when there are warnings, etc).

In my opinion an excellent introduction to what's changed between versions is the excellent [What’s New In Python 3.5](https://docs.python.org/3/whatsnew/3.5.html), but I think this is too big a change for pytest and would probably need a champion to work properly.

What I propose then is to just create two sections in the `CHANGELOG`, *New Features* and *Bug Fixes*. This would allow people to more easily see the new exciting features and notice changes that might affect then in `2.9` and onward. :grin:

So here's what the `CHANGELOG` would look like:

```
2.9.0.dev
=========

New Features
------------

* New `pytest.mark.skip` mark, which unconditional skips marked tests.
  Thanks Michael Aquilina for the complete PR.

* `pytest_enter_pdb` now optionally receives the pytest config object.
  Thanks Bruno Oliveira for the PR.

* New `-rp` and `-rP` reporting options give the summary and full output
  of passing tests, respectively. Thanks to David Vierra for the PR.

Bug Fixes/Adjustments
---------------------

* fix issue #680: the -s and -c options should now work under xdist;
  `Config.fromdictargs` now represents its input much more faithfully.
  Thanks to Buck Evan for the complete PR.

* fix #1226: Removed code and documentation for Python 2.5 or lower versions,
  including removal of the obsolete ``_pytest.assertion.oldinterpret`` module.
  Thanks Bruno Oliveira for the PR.
```

As with #1274, this was also brought up by me while talking with @RonnyPfannschmidt on gtalk.  @hpk42, @flub, @The-Compiler, any opinions?

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Comment by The-Compiler** [comment]
Sure, why not - makes sense!

**Comment by flub** [comment]
+1
