### ISSUE TITLE
The function is not overwritten when using monkeypatch or mocker (pytest-mock)

### ISSUE THREAD

**Issue by maxim-f1** [pytest-dev/pytest#12757]
## When you use a mock function from a module, it does not overwrite it

**main.py**
```python
def func():
    return 'in function'
```
**test_bug.py**
```python
from main import func

def test_bug(monkeypatch):
    def mock_func(*a, **k):
       return 'in mock'

    monkeypatch.setattr('main.func', mock_func)
    result = func()
    assert result == 'in mock'
```
**pytest -vv**
```
FAILED tests/test_bug.py::test_bug - AssertionError: assert 'in function' == 'in mock'
  
  - in mock
  + in function
```

## But if you add the import inside the function it works correctly

**test_bug.py**
```python
def test_bug(monkeypatch):
    def mock_func(*a, **k):
       return 'in mock'

    monkeypatch.setattr('main.func', mock_func)
    from main import func   # Import to fix 
    result = func()
    assert result == 'in mock'
```
**pytest -vv**
```
 tests/test_bug.py::test_bug PASSED                                                                  [100%]
```

## Same thing when using pytest-mock

```python
from main import func

def test_bug(mocker):
    function = mocker.patch('main.func')
    function.return_value = 'in mock'
    result = func()
    assert result == 'in mock'
```
**pytest -vv**
```
tests/test_bug.py::test_bug - AssertionError: assert 'in function' == 'in mock'
  
  - in mock
  + in function

```
```python
def test_bug(mocker):
    function = mocker.patch('main.func')
    function.return_value = 'in mock'
    from main import func   # Import to fix
    result = func()
    assert result == 'in mock'
```
**pytest -vv**
```
 tests/test_bug.py::test_bug PASSED                                                                  [100%]
```

depends:
```toml
pytest-asyncio = "^0.23.7"
pytest-dotenv = "^0.5.2"
pytest-mock = "^3.14.0"
pytest-env = "^1.1.3"
```

My guess is that this is because when you import a function at the beginning of a module, it is saved in that module. And when mockers start overwriting the path to the function, they do not touch the already imported objects.

**Comment by RonnyPfannschmidt** [comment]
Import creates a new name 

The mock replaces the old name 

Import the module and call it on the module

**Comment by The-Compiler** [comment]
There is nothing pytest-specific here, this is just how Python works.

Recommended reading:

- [unittest.mock: where to patch](https://docs.python.org/3/library/unittest.mock.html#where-to-patch)
- [Why your mock doesn’t work | Ned Batchelder](https://nedbatchelder.com/blog/201908/why_your_mock_doesnt_work.html)
