### ISSUE TITLE
[windows] pyreadline + py.test on a single file sets terminal color to black

### ISSUE THREAD

**Issue by ratiotile** [pytest-dev/pytest#1279]
After running `py.test test.py`, the terminal color becomes black on black, rendering everything afterward unreadable.
This does not happen when running only `py.test`
This bug only occurs when pyreadline is installed.

pytest==2.8.5
pyreadline==2.1
Windows 8.1, Python 3.4

**Comment by nicoddemus** [comment]
Thanks!

**Comment by RonnyPfannschmidt** [comment]
this was fixed by #1281
