### ISSUE TITLE
asyncio_default_fixture_loop_scope behavior unexpected

### ISSUE THREAD

**Issue by MarcoZCert** [pytest-dev/pytest#12803]
- [X] a detailed description of the bug or problem you are having
- [X] output of `pip list` from the virtual environment you are using
- [X] pytest and operating system versions -> see output
- [X] minimal example if possible

## Situation 1 - not setting this option in pytest.ini
```ini
[pytest]
asyncio_mode=auto
# Unsetting this will cause testing to fail with a key error for any VALID value
# Leaving it out allows pytest to run, but will generate a warning
#asyncio_default_fixture_loop_scope="session"
filterwarnings=ignore::DeprecationWarning
trio_mode=false
```
Results of running python -m pytest -v:
```
/home/marco/PycharmProjects/zoo/.venv/lib/python3.12/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0 -- /home/marco/PycharmProjects/zoo/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/marco/PycharmProjects/zoo
configfile: pytest.ini
plugins: typeguard-4.3.0, trio-0.8.0, anyio-4.4.0, asyncio-0.24.1.dev20+gb1dc0c3
asyncio: mode=Mode.AUTO, default_loop_scope=None
collected 2 items                                                                                                                                                                  

test/test_countries.py::test_country_count PASSED                                                                                                                            [ 50%]
test/test_root.py::test_root PASSED                                                                                                                                          [100%]

================================================================================ 2 passed in 1.42s =================================================================================
```
Seems to be working fine, except for the warning message.

## Situation 2 - setting the option to *any* value from the list: "module", "package", "session", "class" or "function"
The test fails because of an internal key error!

```
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0 -- /home/marco/PycharmProjects/zoo/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/marco/PycharmProjects/zoo
configfile: pytest.ini
plugins: typeguard-4.3.0, trio-0.8.0, anyio-4.4.0, asyncio-0.24.1.dev20+gb1dc0c3
asyncio: mode=Mode.AUTO, default_loop_scope="session"
collected 2 items                                                                                                                                                                  

test/test_countries.py::test_country_count ERROR                                                                                                                             [ 50%]
test/test_root.py::test_root PASSED                                                                                                                                          [100%]

====================================================================================== ERRORS ======================================================================================
_______________________________________________________________________ ERROR at setup of test_country_count _______________________________________________________________________

request = <SubRequest 'db' for <Coroutine test_country_count>>
kwargs = {'engine': Engine(postgresql://postgres:***@localhost:5432/zoo_test), 'testing_session_local': <sqlalchemy.orm.scoping.scoped_session object at 0x7942847d5040>}
func = <function db at 0x7942851111c0>

    @functools.wraps(fixture)
    def _asyncgen_fixture_wrapper(request: FixtureRequest, **kwargs: Any):
        func = _perhaps_rebind_fixture_func(fixture, request.instance)
>       event_loop_fixture_id = _get_event_loop_fixture_id_for_async_fixture(
            request, func
        )

.venv/lib/python3.12/site-packages/pytest_asyncio/plugin.py:317: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv/lib/python3.12/site-packages/pytest_asyncio/plugin.py:381: in _get_event_loop_fixture_id_for_async_fixture
    event_loop_node = _retrieve_scope_root(request._pyfuncitem, loop_scope)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

item = <Coroutine test_country_count>, scope = '"session"'

    def _retrieve_scope_root(item: Union[Collector, Item], scope: str) -> Collector:
        node_type_by_scope = {
            "class": Class,
            "module": Module,
            "package": Package,
            "session": Session,
        }
>       scope_root_type = node_type_by_scope[scope]
E       KeyError: '"session"'

.venv/lib/python3.12/site-packages/pytest_asyncio/plugin.py:1012: KeyError
------------------------------------------------------------------------------ Captured stdout setup -------------------------------------------------------------------------------
Getting engine
Getting testing session local
============================================================================= short test summary info ==============================================================================
ERROR test/test_countries.py::test_country_count - KeyError: '"session"'
============================================================================ 1 passed, 1 error in 1.17s ============================================================================
```

So I really do wonder what is going on?

## Pip list output
pip list
Package              Version
-------------------- ---------------------
alembic              1.13.2
annotated-types      0.7.0
anyio                4.4.0
asyncpg              0.29.0
attrs                24.2.0
build                1.2.1
CacheControl         0.14.0
certifi              2024.7.4
cffi                 1.17.0
charset-normalizer   3.3.2
cleo                 2.1.0
click                8.1.7
crashtest            0.4.1
cryptography         43.0.0
distlib              0.3.8
dnspython            2.6.1
dulwich              0.21.7
email_validator      2.2.0
fastapi              0.112.0
fastapi-cli          0.0.5
fastjsonschema       2.20.0
filelock             3.15.4
greenlet             3.0.3
h11                  0.14.0
httpcore             1.0.5
httptools            0.6.1
httpx                0.27.0
idna                 3.7
inflect              7.3.1
iniconfig            2.0.0
installer            0.7.0
jaraco.classes       3.4.0
jeepney              0.8.0
Jinja2               3.1.4
keyring              24.3.1
Mako                 1.3.5
markdown-it-py       3.0.0
MarkupSafe           2.1.5
mdurl                0.1.2
more-itertools       10.4.0
msgpack              1.0.8
outcome              1.3.0.post0
packaging            24.1
pexpect              4.9.0
pip                  24.2
pkginfo              1.11.1
platformdirs         4.2.2
pluggy               1.5.0
pluralizer           1.2.0
poetry               1.8.3
poetry-core          1.9.0
poetry-plugin-export 1.8.0
psycopg2             2.9.9
psycopg2-binary      2.9.9
ptyprocess           0.7.0
pycparser            2.22
pydantic             2.8.2
pydantic_core        2.20.1
Pygments             2.18.0
pyproject_hooks      1.1.0
pytest               8.3.2
pytest-asyncio       0.24.1.dev20+gb1dc0c3
pytest-trio          0.8.0
python-dotenv        1.0.1
python-multipart     0.0.9
PyYAML               6.0.2
rapidfuzz            3.9.6
requests             2.32.3
requests-toolbelt    1.0.0
rich                 13.7.1
SecretStorage        3.3.3
setuptools           72.2.0
shellingham          1.5.4
sniffio              1.3.1
sortedcontainers     2.4.0
sqlacodegen          2.3.0.post1
SQLAlchemy           1.4.53
starlette            0.37.2
tomlkit              0.13.2
trio                 0.26.2
trove-classifiers    2024.7.2
typeguard            4.3.0
typer                0.12.3
typing_extensions    4.12.2
urllib3              2.2.2
uvicorn              0.30.6
uvloop               0.19.0
virtualenv           20.26.3
watchfiles           0.23.0
websockets           12.0

## Test code sample
```python3
## Imports left out

@pytest.mark.asyncio
async def test_country_count(client: AsyncClient) -> None:

    response = await client.get(up.create_path("count"))

    assert response.status_code == HTTP_200_OK
    assert response.json() == {"count": 0}
```

**Comment by dongfangtianyu** [comment]
> KeyError: '"session"'

Hi, @MarcoZCert ,
Can you try changing `"session"` in the configuration to `session`?

**Comment by MarcoZCert** [comment]
Ah! That works. Overlooked that one. Thanks!

**Comment by idemintsev** [comment]
> > KeyError: '"session"'
> 
> Hi, [@MarcoZCert](https://github.com/MarcoZCert) , Can you try changing `"session"` in the pytest.ini to `session`?

Thank you so much!
