### ISSUE TITLE
assertion rewriting ignores the original source positions

### ISSUE THREAD

**Issue by 15r10nk** [pytest-dev/pytest#12818]
The assertion rewriting in pytest changes the source position for all nodes in the assertion to the source range of the assertion.

https://github.com/pytest-dev/pytest/blob/9515dfa58a144f3644fd29b256113d723c9c1955/src/_pytest/assertion/rewrite.py#L976-L978

This causes problems for tools like [executing](https://github.com/alexmojaki/executing) which uses these source ranges (since python 3.11) to provide a mapping back to the ast-node.

This causes the following problems.
- https://github.com/alexmojaki/executing/issues/2#issuecomment-553738141 executing does not work inside assertions.
- https://github.com/15r10nk/inline-snapshot/issues/57 I have to disable assertion rewriting to be able to find ast-nodes with executing.
- ... maybe more

I already created a pull-request to solve this problem #12815.

**Comment by johnslavik** [comment]
Older issue: #3463.
