### ISSUE TITLE
More GitHub friendly "CONTRIBUTING" file

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1282]
GitHub provides a link to the `CONTRIBUTING.rst` file when users create a new issue or open a pull request: 

![img](https://help.github.com/assets/images/help/pull_requests/Contributing-guidelines.jpg)

According to [GitHub help](https://help.github.com/articles/setting-guidelines-for-repository-contributors/):

> For contributors, these guidelines help them verify that they're submitting well-formed pull requests and opening useful issues.

Currently our `CONTRIBUTING.rst` file (which was created pior our move to GitHub) is a general overview of all the ways users can contribute: write docs, create a plugin, submit an issue, etc.

In order to better make use of this GitHub feature, I propose:

* Move the contents of our current `CONTRIBUTING.rst` file inside `en/doc`, possibly rearranging things a little. For example, the first section is "submit a plugin/co-develop pytest", while the last is "submit a pull request"... IMHO it would be better to start from simplest ("submit an issue") to more advanced ("plugins/pull requests").

* Change `CONTRIBUTING.rst` at the root to be succinct and informative for users which are already versed with GitHub and are in the process of writing an issue or opening a PR:
  * For issues, be descriptive, include py.test and operating system versions, minimal example, etc.
  * For Pull Requests, `master` vs `branch`, make sure to include one or more tests, add yourself to `AUTHORS`, add a new `CHANGELOG` entry, etc.

**Comment by Zearin** [comment]
:+1:

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt @hpk42 @The-Compiler @bubenkoff  any thoughts on this?

**Comment by The-Compiler** [comment]
To be honest, looking at issues/PRs for my own project, I sometimes wonder if anyone opening an issue/PR even reads that document :wink:

**Comment by nicoddemus** [comment]
I actually agree :grin: 

But I figure some users do read it, and since it is easy to make it friendlier to them I think this is worth spending a few minutes with this. :smile:

**Comment by nicoddemus** [comment]
As discussed by email, also add to CONTRIBUTING how to handle permissions and teams in pytest-dev. Quoting @The-Compiler 
> - Every project has a pytest-xyz-admin team, with its projects admins
  in it, having admin permissions on the repo.

>  This was already present, I now also added it as a repo admin team,
  so you should have full permissions to the repo again.

> - Every project has a pytest-xyz-developers team, having write (but
  not admin) permission to the repo. I added the team and permissions,
  and it's currently empty. If you want to add any people there, I
  think we'll need to add them to the organization, and then you can
  add them to the team.

> - The 'Contributors' group has write access to every project, and
  every project admin is in it. I added it to pytest-rerunfailures,
  and added you to the group.:
