### ISSUE TITLE
expose `fixture.manual` as context-manager for yield fixtures

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#12823]
#### What's the problem this feature will solve?

unlike normal context managers, fixtures functions cannot easily be used in a manual way as a contextmanager

#### Describe the solution you'd like

```python
# typed in untested in web form - slightly pathological example
@fixture
def manager():
    yield SomeResourceManager()

@fixture
def managed_resource(manager, login_data):
   with manager.client(login_data) as client:
     yield client
     
def test_happy(managed_resource):
    assert managed_resouce.interact() == "happy"
    
def test_failed_login_triggers_xfail(manager):
   with pytest.raises(pytest.xfail):
        with managed_resource.manual(manager, {"bad": "login"}):
          pass
```

#### Alternative Solutions
wrapping a fixtures function into contextmanager as api makes for a ugly api

```python
hacked_cm = contextlib.contextmanager(managed_resource.__pytest_wrapped__.obj)
```

**Comment by nicoddemus** [comment]
I understand the rationale, but in those cases I think a reasonable workaround is to refactor the fixture code into a contextmanager, and use that in the fixture:

```python
@contextmanager
def managed_resource(manager, login_data): 
   with manager.client(login_data) as client:
     yield client


@fixture(name="managed_resource")
def managed_resource_fixture(manager, login_data):
   with my_managed_resource(manager, login_data):
     yield client
``` 

Not sure we need to add this to the pytest core, given this is not common occurrence (at least in my experience).

My 2 cents

**Comment by RonnyPfannschmidt** [comment]
closing as not planned, going with refactoring
