### ISSUE TITLE
Configuration option to avoid square brackets in parametrized test names

### ISSUE THREAD

**Issue by djungelorm** [pytest-dev/pytest#12859]
#### What's the problem this feature will solve?

I would like to be able to configure pytest to avoid the use of square brackets in parametrized test names, as this causes issues when using the pytest-cmake integration. This integration allows for pytest to be run from cmake, but there are issues when using `cmake -R` to run a specific test. I opened a PR on pytest-cmake, but the author suggested this might be better implemented as a pytest configuration option: https://github.com/python-cmake/pytest-cmake/pull/38

For example, consider a test with name: `test_foo.py::test_bar[a-1]`

I would like to be able to run just this test via cmake using: `cmake -R test_foo.py::test_bar[a-1]`

However this does not work as the string is treated as a regular expression, and `[a-1]` is not valid regex. Instead I have to write: `cmake -R "test_foo.py::test_bar\[1-2-3\]"` which is clumsy, and precludes copy pasting test names in the terminal without manual edits.

#### Describe the solution you'd like

I would like to be able to customize parametrized test name generation (possibly via conftest.py) to generate names of the form: `test_foo.py::test_bar::a-1`, or similar, avoiding square brackets or other characters that have special meaning in regular expressions.

#### Alternative Solutions

I have tried modifying pytest-cmake (https://github.com/python-cmake/pytest-cmake/pull/38) which worked, but the author of that integration thought this would be better added to pytest itself. 

I tried adding the following to conftest.py, this but it not a complete solution. Whilst the test names appear correct when running all tests, it does not work when trying to run a specific test. For example using:
```python -m pytest test_foo.py::test_bar::a-1```
the collector does not find any tests and reports:
```ERROR: found no collectors for .../test_foo.py::test_bar::a-1```

```python
def pytest_itemcollected(item):                                                                                                                          
    item._nodeid = item.nodeid.replace("[", "::").replace("]", "")
```

**Comment by nicoddemus** [comment]
Thanks folks,

I don't think we should add yet another configuration knob to pytest, even more so one that changes how something fundamental as nodeids are built... the use of `[]` to denote parametrized values in a nodeid is permeated through pytest and the plugin ecosystem.

Sorry but we need to close this one as "won't fix".

**Comment by djungelorm** [comment]
FYI https://gitlab.kitware.com/cmake/cmake/-/issues/26357
