### ISSUE TITLE
Add support for bytes literals

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#1287]
In #710, I described a need for better unicode literals support in doctests.

I now see that I [have the same need for bytes literals](https://github.com/jaraco/jaraco.itertools/issues/1#issuecomment-167272413).

Perhaps @nicoddemus would be interested in replicating the behavior from #938 to also add an ALLOW_BYTES doctests option flag.

**Comment by nicoddemus** [comment]
Sure, I'll give it a go. :smile:

**Comment by RonnyPfannschmidt** [comment]
Merged
