### ISSUE TITLE
Incompatibility with unittest?

### ISSUE THREAD

**Issue by twmacro** [pytest-dev/pytest#1288]
All my testing (via nose) was working fine until I included pandas in one of my tests. Now I'm getting the following error:

    Traceback (most recent call last):
      File "/home/macro/anaconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/home/macro/code/pyyeti/pyyeti/tests/test_n2y_nose.py", line 1380, in test_badrbe3_error
        with assert_warns(RuntimeWarning) as cm:
      File "/home/macro/anaconda3/lib/python3.5/unittest/case.py", line 225, in __enter__
        for v in sys.modules.values():
    RuntimeError: dictionary changed size during iteration
      File "/home/macro/anaconda3/lib/python3.5/unittest/case.py", line 225, in __enter__
        for v in sys.modules.values():
    RuntimeError: dictionary changed size during iteration

The `__enter__` method of the class `_AssertWarnsContext` in file `unittest/case.py` has this loop in it:

        for v in sys.modules.values():
            if getattr(v, '__warningregistry__', None):
                v.__warningregistry__ = {}
 
Unfortunately, the `getattr` call on the AliasModule (repr(v) == "`<AliasModule 'py.test.cmdline' for 'pytest'>`" was one offender) causes additional modules (like `_pytest.terminal`) to be loaded which causes the runtime error.

My user-land avoidance of this issue was simply to add this prior to my `with assert_warns...`:

    import sys
    for v in list(sys.modules.values()):
        if getattr(v, '__warningregistry__', None):
            v.__warningregistry__ = {}

**Comment by RonnyPfannschmidt** [comment]
Py.test is unrelated to nose

**Comment by nicoddemus** [comment]
Yes, I suggest posting this at https://github.com/nose-devs/nose/

**Comment by twmacro** [comment]
Hmm, this doesn't look like a nose issue to me, but what do I know? I was blaming the `AliasModule` function in `py/_apipkg.py` since it adds modules on the `getattr` call from unittest. Is it because of nose that this situation comes up at all?

Thank you for you help; I do want to report this in the proper place! :)

**Comment by nicoddemus** [comment]
Just to be clear, are you using pytest to run nose tests?

**Comment by twmacro** [comment]
No. I use nosetests and everything worked great until I started including a pandas feature in my code. I was guessing that pandas was including somehow getting pytest involved.

**Comment by nicoddemus** [comment]
I see, thanks for the clarification. Would you please post your pip freeze contents?

**Comment by twmacro** [comment]
abstract-rendering==0.5.1
alabaster==0.7.6
anaconda-client==1.2.1
argcomplete==1.0.0
astropy==1.0.6
Babel==2.1.1
beautifulsoup4==4.4.1
bitarray==0.8.1
blaze==0.8.3
bokeh==0.10.0
boto==2.38.0
Bottleneck==1.0.0
cffi==1.2.1
clyent==1.2.0
colorama==0.3.3
conda==3.19.0
conda-build==1.18.1
conda-env==2.4.5
configobj==5.0.6
coverage==4.0
cryptography==0.9.3
cycler==0.9.0
Cython==0.23.4
cytoolz==0.7.4
datashape==0.4.7
decorator==4.0.4
docutils==0.12
dynd==9b63882
fastcache==1.0.2
Flask==0.10.1
greenlet==0.4.9
h5py==2.5.0
idna==2.0
ipykernel==4.1.1
ipython==4.0.1
ipython-genutils==0.1.0
ipywidgets==4.1.0
itsdangerous==0.24
jdcal==1.0
jedi==0.9.0
Jinja2==2.8
joblib==0.8.4
jsonschema==2.4.0
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.0.3
jupyter-core==4.0.6
llvmlite==0.8.0
lxml==3.4.4
MarkupSafe==0.23
matplotlib==1.5.0
mistune==0.7.1
multipledispatch==0.4.8
nbconvert==4.0.0
nbformat==4.0.1
networkx==1.10
nltk==3.1
nose==1.3.7
notebook==4.0.6
numba==0.22.1
numexpr==2.4.4
numpy==1.10.1
odo==0.3.4
openpyxl==2.2.6
pandas==0.17.1
path.py==0.0.0
patsy==0.4.0
pep8==1.6.2
pexpect==3.3
pickleshare==0.5
Pillow==3.0.0
ply==3.8
psutil==3.3.0
ptyprocess==0.5
py==1.4.30
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.5.1
pyflakes==1.0.0
Pygments==2.0.2
pyOpenSSL==0.15.1
pyparsing==2.0.3
pytest==2.8.1
python-dateutil==2.4.2
pytz==2015.7
PyYAML==3.11
pyyeti==0.75
pyzmq==14.7.0
qtconsole==4.1.1
redis==2.10.3
requests==2.9.0
rope-py3k==0.9.4.post1
scikit-image==0.11.3
scikit-learn==0.17
scipy==0.16.0
simplegeneric==0.8.1
six==1.10.0
snowballstemmer==1.2.0
sockjs-tornado==1.0.1
Sphinx==1.3.1
sphinx-rtd-theme==0.1.7
spyder==2.3.8
SQLAlchemy==1.0.9
statsmodels==0.6.1
sympy==0.7.6.1
tables==3.2.2
terminado==0.5
Theano==0.7.0
toolz==0.7.4
tornado==4.3
traitlets==4.0.0
ujson==1.33
unicodecsv==0.14.1
Werkzeug==0.11.2
wheel==0.26.0
xlrd==0.9.4
XlsxWriter==0.7.7
xlwt==1.0.0

**Comment by nicoddemus** [comment]
I did take a quick look, but I don't see how a `getattr` for `__warningregistry__` on an `AliasModule` object would trigger an import.

Is this code public somewhere so I can debug it locally? Or can you reproduce this in a minimal example?

I wonder though if `unittest` should guard itself against this type of error, because iterating on `sys.modules` like that might cause problems, as `getattr(v, '__warningregistry__')` might execute arbitrary code (like importing other modules). We had a similar issue in #1243.

**Comment by twmacro** [comment]
I concur, it seems like unittest probably should protect itself against this.

My code is not public yet; soon I hope :). I will try to make a mini example tonight or tomorrow. When I followed the debugger through, it went something like this:

``getattr() --> AliasModule.__getattribute__() --> getmod() --> x = importobj()``

That's when modules `_pytest.terminal`, `_pytest.capture`, `_pytest.junitxml`, `_pytest.resultlog`, etc get loaded. (I imagine if I used pytest myself instead of nose, these would be loaded from the get-go and never cause trouble ... ?)

**Comment by nicoddemus** [comment]
> My code is not public yet; soon I hope :). I will try to make a mini example tonight or tomorrow. 

Great, thanks! :smile:

> That's when modules _pytest.terminal, _pytest.capture, _pytest.junitxml, _pytest.resultlog, etc get loaded.

Hmm yeah, but I wonder why that is being triggered by that `getattr` call for `__warningresgistry__` though.

> I imagine if I used pytest myself instead of nose, these would be loaded from the get-go and never cause trouble ... 

Hmm perhaps. Out of curiosity, could you give it a try? Just type `py.test tests` and see what happens. :smile:

**Comment by twmacro** [comment]
> Hmm yeah, but I wonder why that is being triggered by that getattr call for __warningresgistry__ though.

On that call to `getmod`, the "mod" variable was empty ... , so `importobj` got called to do its magic :) It doesn't find the `__warningregistry__` entry ... though maybe that goes without saying.

I can confirm that using py.test instead of nose worked like a charm :smile:. I'll start work on a mini example shortly.

**Comment by nicoddemus** [comment]
OK, thanks!

**Comment by twmacro** [comment]
Making a small example was easier than I thought! :smile: Just put these two files in a directory, rename them to get rid of the .txt extension, and try these two commands:

    nosetests --with-doctest -v
    py.test --doctest-modules

The first fails with the error I reported; the second works just fine.

[stats.py.txt](https://github.com/pytest-dev/pytest/files/72563/stats.py.txt)
[test_stats.py.txt](https://github.com/pytest-dev/pytest/files/72564/test_stats.py.txt)

**Comment by nicoddemus** [comment]
Thanks! I will take a look later or tomorrow, as I'm still on "vacation mode" :smile:

**Comment by RonnyPfannschmidt** [comment]
still a nose bug,

**Comment by nicoddemus** [comment]
TBH seems like a unittest bug, but I want to see if there's anything we can do on our side to prevent that.

**Comment by RonnyPfannschmidt** [comment]
Not without dropping apipkg from pylib

**Comment by nicoddemus** [comment]
True, but I wonder how that came to be just by importing `pandas`...

**Comment by kernc** [comment]
I opened [a new issue](https://github.com/pytest-dev/py/issues/110) on what seems to be another culprit, _py_, and also proposed a [quick patch](https://github.com/pytest-dev/py/pull/111) accompanied with a unit test.
