### ISSUE TITLE
Test function argument prevents execution of autouse fixture when used in @pytest.mark.parametrize

### ISSUE THREAD

**Issue by kkmarv** [pytest-dev/pytest#12899]
## Description

I've accidentally named an argument of a test function after a fixture with `autouse=True` which I didn't notice at first. The test function uses paramatrized arguments and also depends on the setup done in the autouse fixture. Since the autouse fixture wasn't executed and thus didn't run the setup anymore, the test function failed.

The documentation does not seem to acknowledge this quirk. A warning at test runtime would be great tho.

## Minimal Working Example

```python
import pytest


@pytest.fixture(scope="session", autouse=True)
def config():  # Very original fixture name
    raise ZeroDivisionError() # This should raise when the fixture runs


@pytest.mark.parametrize("config", ["whatever"])
def test_stuff(config):  # This parameter shadows the autouse fixture!
    assert True
```

## Versions

```console
$ uname -r
5.15.153.1-microsoft-standard-WSL2
```

```console
$ pip list
Package   Version
--------- -------
iniconfig 2.0.0
packaging 24.1
pip       24.0
pluggy    1.5.0
pytest    8.3.3
```

**Comment by webknjaz** [comment]
I think I'd expect this to happen, since only one thing by the name can be dependency-injected into the function args. And narrowly scoped fixtures are supposed to substitute the broad-scoped ones…

Does this happen when you have two tests where the other one does not shadow the fixture? In general, it does sound like the fixture design is imperfect in your project. However, I do agree that unobvious things would be nice to document.

**Comment by kkmarv** [comment]
Yes, I agree. I would've expected the argument name to overwrite the fixture name too if I'd been aware of the name clash, which I wasn't. That's where I'd see the possibility for pytest to detect that and print a warning for the user. I think it's more helpful when working on a large test suite than on smaller ones.

It actually doesn't happen with other tests. Only the one with the shadowed argument.

**Comment by webknjaz** [comment]
Alright, so it behaves as I'd expect: https://docs.pytest.org/en/stable/how-to/fixtures.html#override-a-fixture-with-direct-test-parametrization.

I don't think a warning would be useful because this is documented, and a warning would imply that it is incorrect to override things when it's not.

**Comment by kkmarv** [comment]
Oh okay then. Thank you for your time!
