### ISSUE TITLE
Adding skip marker no longer skips calling `__new__` after upgrading from 6.2.5

### ISSUE THREAD

**Issue by stefan6419846** [pytest-dev/pytest#12896]
I recently upgraded from *pytest* 6.2.5 to 8.3.3 after having been restricted to do this for some legacy applications. My use case basically is to use *pytest* as a collector only to skip specific tests depending on some external parameters. My tests are methods defined in `unittest.TestCase`-based classes.

The implementation more or less looks like this in my plugin:

```python
def pytest_collection_modifyitems(session: 'Session', config: 'Config', items: 'Function'):
    for item in items:
        is_safe, reason = is_safe(item)
        if not is_safe:
            item.add_marker(pytest.mark.skip(reason=reason))
```

With `pytest==6.2.5`, this would only call `__new__` on the test classes if the skip marker has been missing (and possibly not display that these tests have been skipped with `-v`). With `pytest==8.3.3`, this will now always call `__new__` on the test classes (and seems to show all skipped tests in the `-v` output). This only becomes obvious as the code has additional safety measures in place to raise an exception if `__new__` is called for a test class under the wrong conditions.

Looking at the changelog and especially the breaking changes, I could not find a direct hint for this - although [#12089](https://redirect.github.com/pytest-dev/pytest/pull/12089) might be related, it is not obvious for me that this is indeed related and how to cleanly fix it.

**Comment by RonnyPfannschmidt** [comment]
It was pure luxk the `__new__` hack ever worked

A contract for unittest based classes is that one is allowed to make instances

**Comment by stefan6419846** [comment]
Thanks for the quick response. So apparently this only has been a hack which did not cause any troubles at least until 6.2.5.

What would you consider a clean solution for this topic?

**Comment by The-Compiler** [comment]
Why do your test classes have `__new__` defined in the first place?

**Comment by stefan6419846** [comment]
Some of the tests might run in production environments as well. The *pytest* plugin filters them to check for further properties whether running the tests is allowed in the current situation (only read-only tests are allowed in production environments for example). To avoid additional side effects (like using plain *unittest* runners), `__new__` is overwritten on the common test class where all test classes involving write operations are based upon to raise an exception if the environment does not match.

**Comment by RonnyPfannschmidt** [comment]
If you always use pytest, then you can have it filter thevtests however you want

**Comment by stefan6419846** [comment]
Even when using *pytest* only, some circumstances might lead to the plugin not loading correctly, thus having a fallback is something to still consider.

After some testing, we decided to override `setUpClass` and `setUp` in these cases instead which should avoid these side effects. This depends on having the correct `super()` calls now, but this is something which can be ensured with linting.

From your previous comments, it seems like you consider this a bug on my side despite somehow being connected to a change within *pytest*, thus I am going to close this issue.

**Comment by RonnyPfannschmidt** [comment]
The bug in your code existed before pytest started to trigger it 

The change in pytest then triggered it
