### ISSUE TITLE
`ValueError: 'int' is not callable` when running pytest

### ISSUE THREAD

**Issue by stur86** [pytest-dev/pytest#12900]
I am using pytest 8.3.3. in an Ubuntu 20.04 WSL system. When I try to run `pytest`, before even any test is loaded, I get a crash that looks like this:

```
File "/usr/lib/python3.10/argparse.py", line 1447, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'int' is not callable
```

Going back through the trace I find that it originates in `_pytest/config/argparsing.py`, specifically at line 131:

```py
arggroup.add_argument(*n, **a)
```

Printing out the contents of `n` and `a` the line before, it crashes on:

```js
['--element-number'] {'action': 'store', 'type': 'int', 'default': 20, 'help': 'defines how many elements will display in a result', 'dest': 'element_number'}
```

apparently because `'type'` is a string rather than the function `int`. If I replace the value before, pytest works. Any clue what causes this?

**Comment by uglide** [comment]
It's a bug in the pytest-profiling plugin https://github.com/man-group/pytest-plugins/issues/242

**Comment by webknjaz** [comment]
Sounds like this can be closed, then.
