### ISSUE TITLE
`EXCLUDE_PROJECTS` mechanism for `update-plugin-list.py`

### ISSUE THREAD

**Issue by amotl** [pytest-dev/pytest#12901]
#### What's the problem this feature will solve?

We are trying to exclude `pytest-crate` from the [Pytest Plugin List](https://docs.pytest.org/en/latest/reference/plugin_list.html) page. The new designated canonical package `pytest-cratedb` has already been included into the page.

#### Describe the solution you'd like

Similar to the list of `ADDITIONAL_PROJECTS` for adjusting behavior of `update-plugin-list.py`, it would be nice to have an `EXCLUDE_PROJECTS` definition. For a start, it will be good enough to also define this list inline with the generator program?

https://github.com/pytest-dev/pytest/blob/9295f9ffffc11595cc4d7241008f60783f1f46c2/scripts/update-plugin-list.py#L64-L69

#### Additional context
`pytest-crate` is not maintained any longer, `pytest-cratedb` is the designated successor package, just modernized recently.
- https://github.com/chaudum/pytest-crate/issues/6

#### Thoughts
If you think our request to remove certain items from the list is not applicable, feel free to close this ticket right away.

**Comment by nicoddemus** [comment]
Hi @amotl, sounds good. Would you like to take a stab at that? The script itself is very simple.

**Comment by nicoddemus** [comment]
As discussed on https://github.com/pytest-dev/pytest/pull/12902#issuecomment-2426751917.
