### ISSUE TITLE
monkeypatch application is needlessly(?) O(n)

### ISSUE THREAD

**Issue by DRMacIver** [pytest-dev/pytest#1292]
This came up because someone noticed that using the monkeypatch fixture with [Hypothesis](https://hypothesis.readthedocs.org/) was really slow. Looking at the implementation it does an insert at [the beginning of a list on every patch application](https://github.com/pytest-dev/pytest/blob/master/_pytest/monkeypatch.py#L129), which is O(n) (whereas appending is amortized O(1)). This means doing a lot of patches results in a huge slow down.

I'm insufficiently familiar with either the use or implementation of monkeypatch to know if this is strictly necessary, but it seems like you could probably just append and then read from the right where necessary?

Presumably this rarely matters, but in the Hypothesis case it makes this nearly unusable.

**Comment by RonnyPfannschmidt** [comment]
How much monkey patching goes hypothesis do, and why?
An algorithmic optimisation can easily be done by order change or use of deque

**Comment by DRMacIver** [comment]
Hypothesis itself doesn't do any monkeypatching. Sorry if I was unclear on that.

The problem is if a user does something like

```python

@given(integers())
def test_stuff(monkeyatch, n):
    monkeypatch.setattr(foo, bar, baz)
```

then this will be run n times.

To some extent this can be fixed by a solution to https://github.com/pytest-dev/pytest/issues/916 because it will not be run N times then, but it's strictly an independent issue.

**Comment by RonnyPfannschmidt** [comment]
I see

**Comment by RonnyPfannschmidt** [comment]
We still should fix monkeypatch
