### ISSUE TITLE
Parametrizing a test with an empty list calls `ids` callback with the private constant `NOTSET`

### ISSUE THREAD

**Issue by mon** [pytest-dev/pytest#13031]
I parametrize tests based on a user-provided list. Sometimes this list is empty, which disables some tests as a result. However, I would expect the `ids` callback that I provide to not be called at all in that case, but it is actually called with the private `NOTSET` sentinel. As this is not exported, I can't easily check for it in my `ids` function and return a useless value to match it.

### Reproduction:

`conftest.py`
```python
import logging

def idmap(obj):
    logging.info(obj)

def pytest_generate_tests(metafunc):
    if "arg" in metafunc.fixturenames:
        metafunc.parametrize(
            "arg", [], ids=idmap
        )
```

`test_demo.py`
```python
def test_demo(arg):
    pass
```

```
$: pytest --collect-only --log-cli-level=DEBUG
...
INFO     root:conftest.py:4 NotSetType.token
...
```

Python: 3.10.15
pytest: 8.3.4
OS: macOS Sonoma 14.6.1

**Comment by RonnyPfannschmidt** [comment]
For empty id lists we generate a single test with a warning

**Comment by mon** [comment]
Yes, which is reasonable - but I can't detect this in my ID mapping function because it's a hidden type. Perhaps the sentinel can just be exported? Or don't call the ID map for the "no parametrization" case.

I can make a PR in either case!

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/blob/main/src%2F_pytest%2Fmark%2Fstructures.py#L182-L186

**Comment by mon** [comment]
I don't quite understand - I don't get access to the ParameterSet, and thus can't see its marks. I simply get `NOTSET` passed to the `ids` callback. Because `NOTSET` is internal to Pytest, I cannot compare the arg against it nor type annotate my ids function to accept it.

**Comment by RonnyPfannschmidt** [comment]
indeed - we should use a string that indicates it

**Comment by RonnyPfannschmidt** [comment]
i have a wip pr that sets the string NOTSET as direct id to avoid this - 'll polish it a litlle and push

**Comment by mon** [comment]
Fantastic, thank you so much!
