### ISSUE TITLE
Error loading entry points are silently swallowed

### ISSUE THREAD

**Issue by wichert** [pytest-dev/pytest#1307]
I just had my tests fail due to an unrecognised pytest parameter. This had me puzzled for quite some time: the parameter was defined by fixtures in another package and should work fine. Looking at ``py.test  -fixtures`` output shows that there were a lot of missing fixtures. I eventually traced that down to an import error in one of my fixture entry points. As far as I can see the pytest behaviour for fixture discovery works like this:

1. get a list of `pytest11`` entry points
1. try to load the first entry point. This failed with an ImportError. The error is *not* shown, but silently discarded. There is a `self.warn` statement, but that is not shown normally.
1. IF a single entry point import fails abort loading any more entry points.

This behaviour is not very friendly: fixture errors are silently ignored, and errors in one fixture will prevent other fixtures from being loaded.

**Comment by The-Compiler** [comment]
Hm, I'm sure I stumbled upon the same issue myself some while ago, but I can't find a report.

**Comment by The-Compiler** [comment]
Closing this in favour of #1479 - my bad for opening a duplicate, but there's some initial debugging there, so I think it makes more sense to close this one.

**Comment by The-Compiler** [comment]
Proposed fix in #1564.
