### ISSUE TITLE
Avoid erroring out on unrecognized option until after conftests.py are read

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [pytest-dev/pytest#13094]
#### What's the problem this feature will solve?

My project, [IntelPython/dpctl](https://github.com/IntelPython/dpctl), includes its test suite in the package layout, so that `pytest --pyargs dpctl` can be used to run the test suite. 

I recently added to `conftest.py` (which is included in the layout) support for an option, which I tested in the editable build setting, i.e., `python -m pytest dpctl/tests --myoption` worked as expected.

When the package is installed, however, `pytest --pyargd dpctl --myoption` fails with `ERROR: unrecognized arguments: --myoption`.

The only work-around I could find was to copy test folder from the project checkout to a temporary directory `dpctl_tests` from where I 
would run `python -m pytest dpctl_tests --myoptions`.

My understanding is that when `--pyargs` is used, arguments must be parsed before test discovery is attempted, and the unknown option causes the error.

#### Describe the solution you'd like 

I would like `pytest` to defer erroring out on unknown option, only parse `--pyargs` option to determine where tests are located, and reparse options after `conftests.py` files are loaded.

**Comment by RonnyPfannschmidt** [comment]
Pyargs are evaluated after initial contests loading  manage this better 

That won't change 

Eventually testtpathd eill be expanded to

**Comment by oleksandr-pavlyk** [comment]
I think this issue is a duplicate of https://github.com/pytest-dev/pytest/issues/1596

**Comment by RonnyPfannschmidt** [comment]
Indeed it is
