### ISSUE TITLE
TestReport.longrepr is a string when pytest.fail(..., pytrace=False) is used

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1316]
I'd expect the `assert` in my `conftest.py` to pass, but it doesn't:

``` python
# test_foo.py

import pytest

def test_foo(foo):
    pytest.fail("Hello World", pytrace=False)
```

``` python
# conftest.py
import pytest

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    assert not isinstance(report.longrepr, str)
```

Without `pytrace=False`, it's a `py._code.code.ReprExceptionInfo` instance, which means I can use `report.longrepr.addsection` to add additional information.

With `pytrace=False`, it's a `str`, and even appending something to that string won't get pytest to show the output I'd like to show.

**Comment by nicoddemus** [comment]
I've also faced this situation in some other occasion... it would be nice to have `longrepr` always be an `ReprExceptionInfo` instance. Hopefully this will be easier to fix once we merge `py,code` in.

**Comment by RonnyPfannschmidt** [comment]
imho longrepr is a bit problematic, i hope we can get reporting work different in the long term
