### ISSUE TITLE
The registration for pytest.org just expired

### ISSUE THREAD

**Issue by nchammas** [pytest-dev/pytest#1319]
It looks like [pytest.org](http://pytest.org/) just expired. (!)

![screen shot 2016-01-09 at 2 39 22 pm](https://cloud.githubusercontent.com/assets/1039369/12217972/d0b2efb0-b6de-11e5-8bff-ab777aa78183.png)

**Comment by RonnyPfannschmidt** [comment]
We are aware and waiting for @hpk42 to return

**Comment by sigmavirus24** [comment]
For others looking, pytest.readthedocs.org will resolve the docs for you until the domain is re-registered.

**Comment by nicoddemus** [comment]
Although they are pretty out of date :)

**Comment by RonnyPfannschmidt** [comment]
The domain is back

**Comment by nchammas** [comment]
:+1:
