### ISSUE TITLE
using `input` for test paramtrization is confusing

### ISSUE THREAD

**Issue by jeffwidman** [pytest-dev/pytest#1321]
I'm trying to understand how parametrization works, as I'm not getting it to work correctly in my tests. Reading the docs: https://pytest.org/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions

leaves me a little confused whether the word `'input'` is just a convention or a required label. In particular, `input` is a built-in function in python, so this leaves me a confused whether pytest is actually using the built-in somehow under the covers, or just overriding the built-in. 

If overriding, could we rename it to something else in the docs so that it's less confusing? `input_` is fine

If actually using the built-in, could a note be added in the docs there that it needs to always use `'input,expected' in the fixture paramtrization?

**Comment by pfctdayelise** [comment]
Good point, that is confusing for no good reason! Overriding a builtin is not a great thing to have in the docs.

@jeffwidman, would you be able to prepare a pull request to improve the docs? You can edit the docs directly at https://github.com/pytest-dev/pytest/blob/master/doc/en/parametrize.rst and prepare a PR without needing to clone the repo locally, although you're welcome to do it that way too of course.

**Comment by jeffwidman** [comment]
I would except I'm confused here whether it's just a convention or a required label? Happy to change the label if that's all it is

**Comment by pfctdayelise** [comment]
@jeffwidman it's not required at all, it could be foo, or input_, or test_input, or whatever!

**Comment by jeffwidman** [comment]
Thanks, PR submitted
