### ISSUE TITLE
--pdb and yield tests

### ISSUE THREAD

**Issue by anntzer** [pytest-dev/pytest#1324]
Currently, `py.test --pdb` are not optimal for generative tests, as the backtrace goes into the part of nose's code that runs the generator, instead of going into the generator itself.  I'd guess it should be possible (if somewhat hackish) to retrieve the traceback of the generator instead (`gen.gi_frame`) and stitch it into the current traceback, so that the generator's frame becomes accessible in pdb via `up`.

Thoughts?

(crossposted as nose-devs/nose2#260)

**Comment by RonnyPfannschmidt** [comment]
Py.test Wants to deprecate yield tests

The current implementation is problematic, see #16 and #167 
A proper fix will hopefully arrive py.test 3.0

**Comment by RonnyPfannschmidt** [comment]
addressed via #1714
