### ISSUE TITLE
False possitive, when class has empty tests

### ISSUE THREAD

**Issue by eldamir** [pytest-dev/pytest#1325]
OS: Ubuntu 14.04 64-bit
Env: python 3.4.3, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
plugins: xdist-1.13.1, mock-0-9-0, django-2.9.1, cov-2.2.0
Django 1.8.5

I started writing a test, as I use to. I write a `class Test<something>:` and fill in empty methods with names describing what I want to test, and simply have them pass (until I get around to filling them in)

```python
class TestSomething:
    def test_that_stuff_works(self):
        pass

    def test_that_something_else_works(self):
        pass
```

Then I went ahead and filled in the body of the first test and leaving the other to pass. I expected my test to fail (TDD approach), but it didn't. I suspected that the test had been skipped because of a naming error, but it was not.

I Inserted `1/0` and `assert False` to try to force a fail, but it still succeeded. Here is a shot of the code and test output

![false_possitive](https://cloud.githubusercontent.com/assets/2298514/12288403/88fe62dc-b9d4-11e5-97e1-19627c87af7a.png)

When I commented out all the tests with `pass` in their body, I got expected result

![now_works](https://cloud.githubusercontent.com/assets/2298514/12288413/979a10a2-b9d4-11e5-8560-03b4a013d873.png)

I haven't been able to reproduce this in an isolated environment.

**Comment by nicoddemus** [comment]
Look at the names of the first and last methods :wink:

**Comment by eldamir** [comment]
Herp de derp de copy/paste... Well spotted :P shouldn't expect that sort of bugs in a test framework either. I mean. If anyone knows how to test...

Thanks :+1:

**Comment by nicoddemus** [comment]
No worries :smile:
