### ISSUE TITLE
feature request for conftest fixture which need to be autoused in some module and accessed in the testcase.

### ISSUE THREAD

**Issue by hackrole** [pytest-dev/pytest#1326]
the situation is like this.
I need init an application for the web API functional test. So this fixtures will use in many places.
so I defined it at the conftest.py. and then I have to write it as the paramters of the test-case.

but indeed, I would like to write all the functional test seperated from the unit test.
 So I want to mark this fixtures as module fixture in these functional test modules, so I do not have to write in every test-case paramters. like below.
```python
def test_hello(test_web_application):
    response = test_web_application.get('/hello')
```
I can do this with the follow to make the fixture autouse in the module.
```python
pytestmark = pytest.mark.usefixtures('test_web_application')
```
but I cannot get access to it at all now. So this way not works for me.
I search throught the google and the stackoverflow. 
It seems this was the design that only fixture not need access should be use like above and all others need to be the pamaters.

So I am here for the feature requests. cause I think this was a really common situation.

**Comment by The-Compiler** [comment]
Yeah, if you want to access the value of a fixture, you'll need to have it as an argument. Autouse fixtures are pretty much only useful for some kind of setup/teardown without having to access the fixture.

So what you're asking for is basically having some kind of global in the test module namespace for the fixture? I don't see a clean way to do that I'm afraid, and I think if you need the fixture in the testcase, the current approach works fine.

**Comment by RonnyPfannschmidt** [comment]
the request as given here will not be implemented,
but im open to discuss the surrounding situation and help to come up with a different feature request

**Comment by nicoddemus** [comment]
> I can do this with the follow to make the fixture autouse in the module.
> ...
> but I cannot get access to it at all now.

@hackrole please realize that you **can** access an auto-use fixture from a test function/method, you just have to declare it in the parameter list as usual. IOW, the following is perfectly valid and works:

```python
pytestmark = pytest.mark.usefixtures('test_web_application')

def test_hello(test_web_application):
    response = test_web_application.get('/hello')
```

If your request though is more aligned to having a global `test_web_application` in the module then I agree with @RonnyPfannschmidt and @The-Compiler that we probably won't implement it like this... too implicit and hard to implement reliably.

**Comment by hackrole** [comment]
I got it. I know this design was much clean. I just feel write the fixture in every test_function was a repeat.
as the `test_web_application` was require by every functional test case.
