### ISSUE TITLE
xpass logic

### ISSUE THREAD

**Issue by HPotter** [pytest-dev/pytest#1327]
I'm trying to understand what exactly "xpass" and "xfail" are.

I understood that when my xfail test fails, that's expected and OK. But when my xfail test passes - is it success or failure? I suggest that it's also success, because py.test command exits with 0 exit code even if there were any xpassed tests.

Why I'm asking: I'm running my tests on Teamcity CI with teamcity-messages module to report pytest results to Teamcity. And teamcity-messages interprets xpassed tests as failures.

PS How can I determine from TestReport object (in pytest_runtest_logreport) if test xfailed\xpassed (or at least marked as xfail)?

**Comment by RonnyPfannschmidt** [comment]
see #1299 

in hindsight being lax on xpass was a mistake

i don't recall offhand how its decided - i invite you to take a look at how it works, the code in question should reasonably discoverable

**Comment by HPotter** [comment]
OK, I've got it.
It seems that I've incorrectly understood meaning of xfail decorator because of my not-so-good English and wrong testrunner behavior.

Thanks for your answer, it was pretty useful for me

**Comment by nicoddemus** [comment]
Could you close this if you don't have any further questions @HPotter?

**Comment by HPotter** [comment]
Sure.
