### ISSUE TITLE
Show license on homepage

### ISSUE THREAD

**Issue by cool-RR** [pytest-dev/pytest#1328]
Don't make me look for it.

**Comment by RonnyPfannschmidt** [comment]
is there a specific location where you would expect it?

i'm happy to commit that information but i#m a bit at loss where to add it best

**Comment by cool-RR** [comment]
I did ctrl-f license so any place would work for me. I don't have a strong
opinion where it should be. A sentence like "Pytest is open-source,
released under the MIT license." would be good.

**Comment by hackebrot** [comment]
Please review #1393, thanks :bow:

**Comment by cool-RR** [comment]
With this PR, will there be a line on the very front page (
http://pytest.org/latest/ ) saying what the license is without needing to
click a link?

On Tue, Feb 16, 2016 at 10:25 PM, Raphael Pierzina <notifications@github.com

**Comment by hackebrot** [comment]
Yes.. :relaxed:

**Comment by cool-RR** [comment]
Awesome, thanks!
