### ISSUE TITLE
Allow running directly on pyc files

### ISSUE THREAD

**Issue by cool-RR** [pytest-dev/pytest#1329]
I want to run pytest in an environment where I don't have the py files, only pyc files. I looked at file _pytest/python.py line 291, it has `if ext == ".py":` which seems to rule out pyc files. Is there a way to run tests from pyc files?

**Comment by RonnyPfannschmidt** [comment]
Thats not supported in core
I'd suggest creating a plugin for it

**Comment by cool-RR** [comment]
If the line I referred to was changed, would it work? Any more meaningful
changed needed? Because needing a plugin for this is a bit annoying...

**Comment by RonnyPfannschmidt** [comment]
Oft course it would work, but it is contrary to what pytest is intended to do, hence a Plugin is a good place

**Comment by cool-RR** [comment]
Why not add .py to the default python_files, so people will get only py
files by default, and the people who want other types of python files could
still use them?

**Comment by nicoddemus** [comment]
This would make collection slightly slower... this hook is called for every file, hence the shortcut.

As this seems like a rare use-case, a "plugin" might be sufficient. Do you need this in a lot of projects, or just one?

Anyway, a "plugin" can be just a `conftest.py` file in the root tests directory containing this code:

```python
def pytest_collect_file(path, parent):
    ext = path.ext
    if ext == ".pyc":
        if not parent.session.isinitpath(path):
            for pat in parent.config.getini('python_files'):
                if path.fnmatch(pat):
                    break
            else:
               return
        ihook = parent.session.gethookproxy(path)
        return ihook.pytest_pycollect_makemodule(path=path, parent=parent)
```

Also configure `python_files` to `test_*.pyc`... untested but should work.

**Comment by RonnyPfannschmidt** [comment]
Can this be closed?

**Comment by cool-RR** [comment]
Thanks Bruno and Ronny for your help!

**Comment by cool-RR** [comment]
Bruno, I tried your method but I got this: 

    import file mismatch:
    imported module 'tests.test_simulator' has this __file__ attribute:
      /bla/tests/test_foo.py
    which is not the same as the test file we want to collect:
      /bla/tests/test_foo.pyc
    HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules

So maybe it's not possible to write a plugin for this?

**Comment by nicoddemus** [comment]
Hmm it seems that error is due to assertion rewrite... TBH I don't know much about that part to know if there's a workaround for that.

**Comment by RonnyPfannschmidt** [comment]
Seems like py.path bug, we should perhaps replace pyimport usage

**Comment by RonnyPfannschmidt** [comment]
A work aound would've be a custom collector + a module subclass

**Comment by cool-RR** [comment]
Eh... Are these easy to write?

**Comment by RonnyPfannschmidt** [comment]
The code amount needed should be relatively low, the understanding of pytest internals needed might be a problem
