### ISSUE TITLE
Fixtures leak on assertion

### ISSUE THREAD

**Issue by pborsutzki** [pytest-dev/pytest#1332]
Using python x64 2.7.9 and pytest 2.8.5 on Windows 7 x64 I noticed that objects returned by a fixture are leaking when an assertion fails. I am using the following test setup:
```python
import pytest

class MyClass(object):
    def __init__(self):
        print("### INIT ###")
        
    def __del__(self):
        print("### DELETE ###")

@pytest.fixture
def myFixture():
    return MyClass()

def test_1(myFixture):
    print("test 1")
    
def test_2(myFixture):
    print("test 2")
    assert False # MyClass leaks after this

def test_3(myFixture):
    print("test 3")
```
The result shows the init print three times, but the delete print only twice:
```
$ py.test -s
============================= test session starts =============================
platform win32 -- Python 2.7.9, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: D:\work\test, inifile:
plugins: instafail-0.3.0
collected 3 items

test_bla.py ### INIT ###
test 1
.### DELETE ###
### INIT ###
test 2
F### INIT ###
test 3
.### DELETE ###


================================== FAILURES ===================================
___________________________________ test_2 ____________________________________

myFixture = <test_bla.MyClass object at 0x00000000036F80B8>

    def test_2(myFixture):
        print("test 2")
>       assert False # MyClass leaks after this
E       assert False

test_bla.py:19: AssertionError
===================== 1 failed, 2 passed in 0.03 seconds ======================
```

**Comment by nicoddemus** [comment]
I'm not sure this is a problem, I guess the fixtures are alive probably because they are one of the locals in a frame of the exception raised by the failed `assert`. This is common and happens with all locals when an exception is raised.

**Comment by pborsutzki** [comment]
For our test scenario it gets a problem as we are executing hundreds of tests, all allocating resources (host memory, video memory, threads, file locks, handles, etc.) in ``__init__`` while releasing them in ``__del__``. If a test fails we'd still like to know if other tests run fine. Now we run into problems when multiple tests are failing "semantically" (through the assertion, not by failing to allocate resources) other tests that wouldn't fail "semantically" now fail due to resource allocation failures (e.g. not enough memory). We initially hoped pytest would handle these cases as assertions are a common way of making tests fail due to semantic errors and in my opinion resources should always be cleaned up - no matter if something fails or not.

If it is not possible or wanted to fix this behavior can you propose an alternative?

**Comment by nicoddemus** [comment]
Unfortunately using `__del__` is generally problematic in Python, it is recommended to have an explicit `close` or `release` method instead. Here are a few suggested readings:

http://www.electricmonk.nl/log/2008/07/07/python-destructor-and-garbage-collection-notes/
http://www.algorithm.co.il/blogs/programming/python-gotchas-1-__del__-is-not-the-opposite-of-__init__/
http://www.andy-pearce.com/blog/posts/2013/Apr/python-destructor-drawbacks/

**Comment by pborsutzki** [comment]
Ok, thanks for the help and the read. Maybe I can figure out how to wire this together with the finalizer that is referred to [in the pytest docs](http://pytest.org/latest/example/simple.html#making-test-result-information-available-in-fixtures) as cleaning up manually is not really an option for us. Close this ticket as you see fit.

**Comment by nicoddemus** [comment]
To write the finalizer it is simple, you can use:

```python
@pytest.fixture
def fix(request):
    resource = NewResource()
    request.addfinalizer(lambda: resource.close())
    return resource
```

Or even better IMO:

```python
@pytest.yield_fixture
def fix():
    resource = NewResource()
    yield resource
    resource.close()
```
