### ISSUE TITLE
[monkeypatch] Regression in 2.8.6: requests.sessions.Session.request doesn't exist

### ISSUE THREAD

**Issue by untitaker** [pytest-dev/pytest#1338]
This works under 2.8.5, but not 2.8.6:

    def test_foo(monkeypatch):
        monkeypatch.delattr('requests.sessions.Session.request')

>Failed: import error in requests.sessions.Session.request: No module named 'requests.sessions.Session'; 'requests.sessions' is not a package

The example has been taken from the documentation: http://pytest.org/latest/monkeypatch.html#example-preventing-requests-from-remote-operations

**Comment by untitaker** [comment]
https://github.com/pytest-dev/pytest/commit/8d49abb0d1b30d8692ed7d4ae09f1d183132a29a introduced this.

**Comment by untitaker** [comment]
cc @ulope 

There are some inconsistencies between failed_name on both platforms:

* Python 2: `failed_name = "Session.request"`
* Python 3: `failed_name = "requests.sessions.Session"`

I propose disabling this usability helper on Python 2 and just continue with the while-loop until the old error message appears.

Also, this code:

    any(p == failed_name for p in target_parts)

is a very roundabout variant of `failed_name in target_parts`.

**Comment by RonnyPfannschmidt** [comment]
i have a different idea, pull request in a bit

**Comment by lavacat** [comment]
also run into this issue
any(p == failed_name for p in target_parts) should be 
any(p == failed_name.rsplit('.', 1)[-1] for p in target_parts)

compare only to the last part of failed_name

**Comment by untitaker** [comment]
The bigger problem I see here is that the current code with `target_parts` treats these import paths as equivalent (since order is lost)

* `sessions.request`
* `requests.sessions`

Under Py2, `failed_name` doesn't give us enough information to determine where the ImportError originated from.

**Comment by RonnyPfannschmidt** [comment]
hmm, while refactoring it made me intensely remember why setuptools uses a module:attr separation

dotted path name discovery is insane to do reliable and with good errors

**Comment by untitaker** [comment]
If a proper fix takes a while I suppose reverting that PR and pushing a patch release is the best intermediate step.

**Comment by RonnyPfannschmidt** [comment]
please test the pull request,

@ulope please confirm whether the solution i implemented also fits your original needs
