### ISSUE TITLE
optional argument whit strings makes pytest.main fail

### ISSUE THREAD

**Issue by mexcoder** [pytest-dev/pytest#1348]
when using an custom optional argument that stores a string pytest.main would fail whit the following error:
`ERROR: file not found: --port COM10`

my code is something like 
`pytest.main(["q","--port COM10",testDir], plugins=[serialConection() ])`
as shown in http://pytest.org/latest/usage.html

serialConections class only has one method:
`def pytest_addoption(self, parser):
        parser.addoption('-P', '--port', help='set the serial port to use', type="string" ,action='store', default='')`

**Comment by RonnyPfannschmidt** [comment]
the correct way is to either use a `=` instead of the space, or pass it as separate strings

**Comment by nicoddemus** [comment]
Yes, this should be:

```python
pytest.main(["q", "--port", "COM10", testDir], plugins=[serialConection()])
```

**Comment by mexcoder** [comment]
using -P=port works but putting it on the array raises an 
`unrecognized arguments: -P testDir`
when the array is something like 
`[-q,-P,COM10,testDir]`

also on a side note, if `-P COM10` works from the command line, it should work the same from the pytest.main method, shouldn't it?

**Comment by nicoddemus** [comment]
To be clear, are you calling `pytest.main` like this?

```python
pytest.main(["-q", "-P", "COM10", testDir], plugins=[serialConection()])
```

**Comment by mexcoder** [comment]
yes, im actuallyy uding the '-P=COM10' version

**Comment by nicoddemus** [comment]
Sorry, what do you mean by "uding"?

Previously you said:

> when the array is something like 
[-q,-P,COM10,testDir]

And I asked if you were calling `pytest.main` like this:

```python
pytest.main(["-q", "-P", "COM10", testDir], plugins=[serialConection()])
``` 

To which you said:

> yes, im actuallyy uding the '-P=COM10' version

Which is not what I suggested... I'm confused that what you are actually passing to `pytest.main`. Could you post your code?

**Comment by mexcoder** [comment]
sorry i mistyped "using", my finger slide one key to the right, and what i mean was that i was using something like 

`pytest.main(["-q", "-P=COM10", testDir], plugins=[serialConection()])`

 as @RonnyPfannschmidt sugested

**Comment by nicoddemus** [comment]
I see, thanks for the clarification.

Could you try my suggestion? 

```python
pytest.main(["-q", "-P", "COM10", testDir], plugins=[serialConection()])
```

**Comment by mexcoder** [comment]
just ran it, i got the following error

`error: unrecognized arguments: -P testDir`

(testDir is the actual path to de test files, not the constant "testDir")

**Comment by nicoddemus** [comment]
Hmm that's strange... don't know why `-P` and `testDir` are not being treated as different arguments...

**Comment by RonnyPfannschmidt** [comment]
more context is needed now :)
we are guessing to much, to help you we need more concrete details

**Comment by nicoddemus** [comment]
If you could put together a minimal example for us to reproduce the problem, it would be helpful.

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of feedback
