### ISSUE TITLE
Class properties are called before setup_class

### ISSUE THREAD

**Issue by m3talstorm** [pytest-dev/pytest#1356]
This is pytest version 2.8.7

Example:

```
import unittest


class classproperty(object):
    """
    """

    def __init__(self, func):
        """
        """
        self.func = func

    def __get__(self, instance, cls):
        """
        """

        return self.func(cls)


class TestBase(unittest.TestCase):


    @classproperty
    def info(cls):

        print "info"

        # Expensive operation
        info = {}

        return info

    @classmethod
    def setup_class(cls):

        print "setup_class"

    def test_one(self):

        print "test_one 1"

        info = self.info
        # Etc

        print "test_one 2"
```

Running:

> py.test test_base.py

You will get the output:

> info
> setup_class
> test_one 1
> info
> test_one 2

It looks like  python.py::parsefactories::1973

`obj = getattr(holderobj, name, None)`

Tries to access the property with no check if it is a method or not, is this expected?

**Comment by RonnyPfannschmidt** [comment]
this is expected, making expensive operations class properties is a problematic practice

**Comment by m3talstorm** [comment]
The expensive operation was just an example.

My real use case is that my setup/configuration/command line args/etc are fetched in setup_class (where they should be right?) then later on in setup_class it accesses 'info' which requires these values. However when 'info' is accessed before setup_class (because of this issue) these values are not present. I would have expected the execution order (as stated in the docs) to be maintained.

**Comment by RonnyPfannschmidt** [comment]
the property is accessed at collection time, not test execution time

we cant account for all potentially bad behaviors that users implement

**Comment by nicoddemus** [comment]
> obj = getattr(holderobj, name, None)
> Tries to access the property with no check if it is a method or not, is this expected?

But how would pytest check if an attribute is a method or not without accessing it in the first place? 

The issue is not related to execution order, but collection: before even finding out which members are tests, fixtures, etc, pytest has to access them... that's why putting properties in classes might lead to this kind of problems.

**Comment by m3talstorm** [comment]
Using properties is not 'bad behaviors'

**Comment by m3talstorm** [comment]
@nicoddemus Have a look at the patch, you don't have to access them to work out if they are a property or not.

**Comment by nicoddemus** [comment]
@m3talstorm hmm I didn't notice that patch, thanks.

I'm not sure why using `get` instead of `__getitem__` doesn't trigger property access...

TBH I would be a little weary of introducing this change, member discovery is a sensitivity issue. Did you try your patch with the rest of the pytest suite? Your patch might fix your use case, but I wouldn't be surprised if it broke collection in other situations...

**Comment by m3talstorm** [comment]
Also have a look further down the function it is already doing a: 

```
                if not callable(obj):
                    continue
```

To check if it can call it or not, this just essentially needs to be moved up to the top of the for loop.

Another benifit, but super micro optimizations, is it will be skipping all other attributes on the class/object.

**Comment by m3talstorm** [comment]
@nicoddemus You can use __getitem__, but you will get a KeyError when it tries to access __class__, hence the .get()

**Comment by RonnyPfannschmidt** [comment]
the patch is broken on python3 due to usage of callable and it does potentially break downstream code due to sidesteping the descriptor protocol

**Comment by RonnyPfannschmidt** [comment]
please keep in mind any class property that is sensitive to surrounding code execution order is broken per definition

**Comment by m3talstorm** [comment]
@nicoddemus It works for all the features I use, but I'd assume the PR would go through the CI to weed out any breakages to other features/areas.

@RonnyPfannschmidt Ah ye, I forgot about Python3 not having callable ;) From limited memory the Python 3 varient is hasattr(thing, '__call__') ?

**Comment by RonnyPfannschmidt** [comment]
correct, the python3 invariant is `__call__`

**Comment by nicoddemus** [comment]
@m3talstorm feel free to open a PR, we can move the discussion there, with the benefit of having CI results to discuss over.

**Comment by m3talstorm** [comment]
In reguards to:

> the patch is broken on python3 due to usage of callable and it does potentially break downstream code due to sidesteping the descriptor protocol

What happens with the:
```

                if not callable(obj):
                    continue
```

A few lines below it, which already exists, and does in Python 3.1+ ?

**Comment by RonnyPfannschmidt** [comment]
oh, fun, now i'm aware i have to unlearn python 3.0 + damage, sorry for the false positive
