### ISSUE TITLE
Simplify running parametrized tests by node ID

### ISSUE THREAD

**Issue by shapiy** [pytest-dev/pytest#1360]
Please consider such a case. Contents of test_mod.py:

``` python
class TestClass(object):
    @pytest.mark.parametrize('date', [datetime.date.today()])
    def test_method(self):
        pass
```

So, to run the particular test method, I need to call the command:

```
py.test test_mod.py::TestClass::test_method[date0]
```

But if there are two parameter values, it's not gonna work. Also, I need to keep in mind how parameters of different types are mapped to ID parts. Currently I do this:

```
py.test test_mod.py::TestClass -k test_method
```

But it would be really nice to run the method (including all parameters) simply by truncating the square brackets:

```
py.test test_mod.py::TestClass::test_method
```

**Comment by RonnyPfannschmidt** [comment]
that feature is in the list

its currently unreliable to implement due to collection being misshaped,
as collectors materialize parametrization of items instead of the items having parametrized calls as sub nodes

**Comment by RonnyPfannschmidt** [comment]
would acceptable alternative solution to your case be to give the randomized item a hardcoded id, so the test name is `test_mod.py::TestClass::test_method[today]`

**Comment by Apteryks** [comment]
I too was bitten by this limitation. The documentation [here](https://pytest.org/latest/usage.html#specifying-tests-selecting-tests) clearly states that:

> py.test test_mod.py::test_func  # only run tests that match the "node ID",
>                                 # e.g "test_mod.py::test_func" will select
>                                 # only test_func in test_mod.py

I would have expected doing py.test test_mod.py::TestClass::test_method to run the parametrized test with all the parameters.

**Comment by Apteryks** [comment]
Also, the scheme used by shapiy to access the first parametrized parameter 'date' (if I understand correctly) doesn't seem to work for every object type.

For example, this works with ``py.test test_mod.py::test_foo[someparameter0]``

    @pytest.mark.parametrize('someparameter', [object()])
    def test_foo(someparameter):
        pass

But the following doesn't (it returns: ``ERROR: not found: /home/user/test_mod.py::test_foo[someparameter0]``)

    @pytest.mark.parametrize('someparameter', ['some string'])
    def test_foo(someparameter):
        pass

And what happens when a parametrized test takes multiple parameters? I don't think the current scheme of appending the parametrized iteration to the parameter name makes much sense. What I would like to be able to do would rather be:

``py.test test_mod.py::test_foo[0]`` for the first parametrized set of params, 
``py.test test_mod.py::test_foo[1]`` for the second, etc.

**Comment by nicoddemus** [comment]
@Apteryks I agree with your points... I'm not sure how easy it is to support them under the current architecture though.

**Comment by tgoodlet** [comment]
@Apteryks  @shapiy As a workaround for now you guys might find [pytest-interactive](https://github.com/tgoodlet/pytest-interactive) handy.

I originally tossed it together to accommodate making more complex selections of dynamically generated tests from the cli. It's been on the back burner for far too long and I've been meaning to write tests for it as required by [plugincompat](https://github.com/tgoodlet/pytest-interactive) before throwing it up on PyPI.

The whole idea is to select tests after all test gen is complete using `IPython`'s attribute tab-completion facilities. I'd like to add fuzzy matching support eventually as well. It's basically a "generate then filter" approach as opposed to expecting the user to know `pytest`'s internal dynamically generated names convention at the inset.

**Comment by Apteryks** [comment]
@tgoodlet, thank you for letting us know about this project of yours, it does seem very promising! I'll be trying it soon :)

**Comment by bluetech** [comment]
This does work these days (although it's implemented with a hack).
