### ISSUE TITLE
show trace on keyboardinterrupt

### ISSUE THREAD

**Issue by hpk42** [pytest-dev/pytest#1366]
When CTRL-C/keyboard-interrupt a hanging test pytest does not show a stacktrace.  You can enable it via "--fulltrace" but that's not obvious.  So we should add a hint when ctrl-c happens.

we could also show the traceback by default but sometimes one hits ctrl-c because one realizes the invocation was wrong or something and then showing long tracebacks by default is obnoxious.  So i suggest we stick with how things are and add something to the message

**Comment by RonnyPfannschmidt** [comment]
:+1: we had a similar request before and already decided we shouldnt always show the trace

**Comment by The-Compiler** [comment]
Closing as #1374 was merged (@RonnyPfannschmidt, if you say "fix #1366" instead of "fix *issue* #1366", GitHub will autoclose the issues)
