### ISSUE TITLE
Print out pytest-warnings?

### ISSUE THREAD

**Issue by Daenyth** [pytest-dev/pytest#1370]
When I run my tests, I get `1 pytest-warnings` in the summary line.

How do I find out what the warning was? It's not printed out and there's no instruction on what flags to pass

**Comment by The-Compiler** [comment]
You can pass `-rw` to show the warnings. See #1173 and #1179 for some related discussions - I agree it's not really a good UI how things are right now.

**Comment by Daenyth** [comment]
Thanks
