### ISSUE TITLE
pytest-xdisat hangs if max-slave-restart is set and the restart limit is reached

### ISSUE THREAD

**Issue by fizyk** [pytest-dev/pytest#1371]
It can be observed in this build:
https://travis-ci.org/ClearcodeHQ/pytest-dbfixtures/jobs/108118580

I'm testing if a package is configured properly (all non py files are included, hence change to install) and installing the package with "pip install ." before the test. 
`pytest_load_initial_conftests` throws a ValidationError if the additional files can not be accessed. however I end up with a loop of restarting slaves indefinitely, or if I set `--max-slave-restart`, I end up with hanging py.test as well.

**Comment by RonnyPfannschmidt** [comment]
please report to pytest-dev/pytest-xdist

**Comment by fizyk** [comment]
okay,

Reported it here since the pytest-xdist's README states:

> Issue and Bug Tracker
Please use the pytest issue tracker for reporting bugs in this plugin.

**Comment by RonnyPfannschmidt** [comment]
thats my misstake ^^ i didnt remove them
