### ISSUE TITLE
deselection incorrectly determines the deselection reason

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1372]
the combination of the terminal plugin and the mark plugin assume, only the mark plugin can deselect tests

so that's whats being used in the terminal summary, and the hook for Deselection does not consider getting a deselection Reason

i propose adding a deselection reason too the hook and requiring plugins that deselect to pass it
starting in 3.0

in order to support that we might need to add support for defaults to hook invocation and specification in pluggy

**Comment by nicoddemus** [comment]
Fixed in #1779
