### ISSUE TITLE
Idea: make FixtureLookupError show prettier fixture list

### ISSUE THREAD

**Issue by ionelmc** [pytest-dev/pytest#1392]
Currently it just list fixture names (unordered, on py27 at least).

It would be nice to show them ordered with providers maybe.

What do you think? Would this create too much output? (`--fixtures` is quite long, not sure how to abbreviate that significantly)

**Comment by Zac-HD** [comment]
Closing this issue as inactive; we'd be happy to take a pull request but nobody has yet volunteered to write one.
