### ISSUE TITLE
yield_fixture incompatible with other decorators

### ISSUE THREAD

**Issue by n1ywb** [pytest-dev/pytest#1396]
I'd like to be able to use other decorators on my yield_fixtures, but doing so causes the error `yield_fixture requires yield statement in function` regardless of the decorator ordering.

```
from mock import patch
import pytest

@pytest.yield_fixture
@patch('os.path')
def brokenfixture(mockpath, request):
    with open('/tmp/foobar', 'wb') as foobar:
        yield

def test_brokenfixture(brokenfixture):
    pass

```

```
$ py.test example.py  -v -s
====================================================== test session starts ======================================================
platform linux2 -- Python 2.7.11, pytest-2.8.5, py-1.4.31, pluggy-0.3.1 -- /home/jeff/.virtualenvs/wsm/bin/python
cachedir: .cache
rootdir: /home/jeff/jlconsulting/clients/wdsolutions/wsm_phpstorm/services, inifile: pytest.ini
plugins: cov-2.2.1
collected 1 items 

example.py::test_brokenfixture ERROR

============================================================ ERRORS =============================================================
_____________________________________________ ERROR at setup of test_brokenfixture ______________________________________________
yield_fixture requires yield statement in function:

    @wraps(func)
    def patched(*args, **keywargs):
        extra_args = []
        entered_patchers = []

        exc_info = tuple()
        try:
            for patching in patched.patchings:
                arg = patching.__enter__()
                entered_patchers.append(patching)
                if patching.attribute_name is not None:
                    keywargs.update(arg)
                elif patching.new is DEFAULT:
                    extra_args.append(arg)

            args += tuple(extra_args)
            return func(*args, **keywargs)
        except:
            if (patching not in entered_patchers and
                _is_started(patching)):
                # the patcher may have been started, but an exception
                # raised whilst entering one of its additional_patchers
                entered_patchers.append(patching)
            # Pass the exception to __exit__
            exc_info = sys.exc_info()
            # re-raise the exception
            raise
        finally:
            for patching in reversed(entered_patchers):
                patching.__exit__(*exc_info)
/home/jeff/jlconsulting/clients/wdsolutions/wsm_phpstorm/services/example.py:4
==================================================== 1 error in 0.03 seconds ====================================================

```

**Comment by nicoddemus** [comment]
Hi @n1ywb,

I don't have an answer to your specific question, but I see you are using `@patch`. As an alternative you might consider using [pytest-mock](https://github.com/pytest-dev/pytest-mock/) instead, which lets you use `mock` with pytest more easily. One of the [reasons](https://github.com/pytest-dev/pytest-mock/#why-bother-with-a-plugin) for me to write it was that using `@patch` doesn't mix nicely with pytest's fixtures. 

For illustration your example using `pytest-mock` would be:

```python
import pytest

@pytest.yield_fixture
def brokenfixture(mocker, request):
    mockpath = mocker.patch('os.path')
    with open('/tmp/foobar', 'wb') as foobar:
        yield

def test_brokenfixture(brokenfixture):
    pass
```

**Comment by RonnyPfannschmidt** [comment]
mock.patch severely messes up signatures, and needs to be explicitly supported by support code to work

**Comment by n1ywb** [comment]
It's a common pattern for decorators to add leading arguments to functions.
mock.patch is hardly unique in that respect.

On Thu, Feb 18, 2016 at 2:47 AM, Ronny Pfannschmidt <
notifications@github.com> wrote:

> mock.patch severely messes up signatures, and needs to be explicitly
> supported by support code to work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytest-dev/pytest/issues/1396#issuecomment-185583603>.
>



-- 
73 de n1ywb

**Comment by Zac-HD** [comment]
Closing because `yield_fixture` is deprecated and will be removed in pytest 4.0

**Comment by nicoddemus** [comment]
@Zac-HD just a clarification: `yield_fixture` and `fixture` are functionally the same, so I issues about `yield_fixture` will probably apply to `fixture` functions that use `yield` too. Also we don't plan to actually remove the `yield_fixture` decorator anytime soon, as it doesn't incur any maintenance overhead (it is just an alias to `fixture`).

Having said that, we have since in recent versions improved how signatures are handled, so the original example actually works in recent pytest versions. 👍
