### ISSUE TITLE
"collecting" output with --color=yes in Continuous Integration output

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1397]
Hi,

We like to use `--color=yes` when running py.test in continuous integration services like Jenkins (with the [Ansi Color Plugin](https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin)). This enables us to see the same nice colors in Jenkins that we see on the terminal.

The only problem is that the "collecting" display progress actually piles up in the terminal because py.test output is being redirected and captured by the server. This can easily be reproduced by redirecting to a file instead:

```python
import pytest
@pytest.mark.parametrize('i', range(10))
def test_foo(i):
    if i == 5:
        assert 0
```

```
py.test --color=yes test_foo.py > out
```

Contents of `out`:

```
[1m============================= test session starts =============================[0m
platform win32 -- Python 2.7.11, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: x:\jobs_done10, inifile: 
[1m
collecting 0 items[0m[1m
collecting 10 items[0m[1m
collected 10 items 
[0m
foo.py .....F....

================================== FAILURES ===================================
[1m[31m_________________________________ test_foo[5] _________________________________[0m

i = 5

[1m    @pytest.mark.parametrize('i', range(10))[0m
[1m    def test_foo(i):[0m
[1m        if i == 5:[0m
[1m>           assert 0[0m
[1m[31mE           assert 0[0m

foo.py:6: AssertionError
[1m[31m===================== 1 failed, 9 passed in 0.02 seconds ======================[0m
```

The color codes are correct, but the "collecting" messages are a problem because they occupy many lines of output in test suites with hundreds of tests.

Is there any way to prevent those "collecting" messages from appearing? `-q` gets rid of them, but I want the header to appear, specially in CI.

**Comment by The-Compiler** [comment]
This is the same as #1363, no? FWIW, I'd be okay with falling back to a static `collecting...` when stdout is not a terminal, independent of what `--color` is set to.

**Comment by nicoddemus** [comment]
Ooops, completely forgot that I had already reported that. :grin:

I agree with @The-Compiler, seems like a reasonable solution. The ideal solution proposed in #1363 would probably take a very long while to happen... just falling back to simple `collecting...` here would fix this problem for a ton of users without incurring too many workarounds in the code.

**Comment by RonnyPfannschmidt** [comment]
I'm ambivalent, we might want to separate coloring and progress displays at some point

**Comment by nicoddemus** [comment]
How about a `--no-fancy-progress` option then?

**Comment by RonnyPfannschmidt** [comment]
We should strictly base the decision on whether the stdio is a terminal

**Comment by nicoddemus** [comment]
Hmm I agree, I don't see any point in directing the multiple "collecting" messages anywhere else other than the terminal.

> I'm ambivalent, we might want to separate coloring and progress displays at some point

I agree, but that would be a 3.0 thing right? That said, are you OK with me working on a PR for this? :grin:

**Comment by RonnyPfannschmidt** [comment]
Correct
