### ISSUE TITLE
counter intuitive fixture importing behaviour

### ISSUE THREAD

**Issue by segv** [pytest-dev/pytest#1401]
(this behaviour is with py.test 2.8.7 (running in an otherwise empty virtual env))

if i have two fixtures defined in the file `tests/fixtures.py`:

``` python
import pytest

@pytest.fixture
def base_fixture():
    return 1

@pytest.fixture
def other_fixture(base_fixture):
    return base_fixture + 1
```

and i would like to use `other_fixture` in my test:

``` python
from tests.fixtures import other_fixture

def test_whatever(other_fixture):
    assert other_fixture == 2
```

running just this test will fail with

```
file tests/fixtures.py, line 7
  @pytest.fixture
  def other_fixture(base_fixture):
        fixture 'base_fixture' not found
        available fixtures: tmpdir_factory, pytestconfig, cache, recwarn, other_fixture, monkeypatch, record_xml_property, capfd, capsys, tmpdir
        use 'py.test --fixtures [testpath]' for help on them.
```

if i edit my test file to import both `other_fixture` and `base_fixture` the tests work as expected. i would have expected importing `other_fixture` to be enough. is this a known issue i just have to like with or is there something i can do to make this work as i expect?

thanks,

**Comment by nicoddemus** [comment]
I think currently fixtures should exist in test modules or `conftest.py` files only.

If you rename `fixtures.py` to `conftest.py` and remove the explicit import it should work.

**Comment by segv** [comment]
fair enough. would you accept a patch which changed this behavior?

just so you know where i'm coming from, the  behaviour of conftest.py makes it hard to share fixtures between "sister" python files (because you can only have one conftest for each module anything you put there is shared across all the files in the module), makes it impossible for the linter (or my ide's go-to-source) to give sane output, and makes it harder to see when you've made a typo or when you're reusing an existing name.

that said, py.test is the best python test runner around, and thanks for the work.

**Comment by nicoddemus** [comment]
> fair enough. would you accept a patch which changed this behavior?

There's some more semantics attached to how fixtures are discovered and used. pytest collects test items in a tree structure, with test items being leafs, which are attached to "modules", all the way up to the root directory. Fixtures are attached to nodes on that tree, not only by being imported in some module. For example, it is perfectly valid for you to "override" a fixture declared in a top node in a bottom node, often reusing the original fixture in the new one's implementation. IOW, fixtures are looked-up lazily at the point they're requested.

Having said all that, you are welcome to take a look at the code and see if you can come up with a patch with keeps the same semantics, but others would have to give their opinion too. :smile:

> just so you know where i'm coming from, the behaviour of conftest.py makes it hard to share fixtures between "sister" python files (because you can only have one conftest for each module anything you put there is shared across all the files in the module), makes it impossible for the linter (or my ide's go-to-source) to give sane output, and makes it harder to see when you've made a typo or when you're reusing an existing name.

That's reasonable. While it won't help with the linter, you can do this:

```python
pytest_plugins = ['fixtures']

def test_whatever(other_fixture):
    assert other_fixture == 2
```

This tells pytest that it should load the module `fixtures` as a plugin, so all fixtures from that module will be available in the calling module (plus it will call hooks as well).

**Comment by nicoddemus** [comment]
Closing this for now, feel free to reopen if you would like to discuss this further.
