### ISSUE TITLE
conftest.py loaded in wrong order.

### ISSUE THREAD

**Issue by AndreiPashkin** [pytest-dev/pytest#1404]
# Description of the bug:

[Docs](https://pytest.org/latest/writing_plugins.html#conftest-py-local-per-directory-plugins) says:

> Hook Session and test running activities will invoke all hooks defined
> in conftest.py files closer to the root of the filesystem.

But my tests shows, that this is happens in some other way. Here is my directory structure.

```
.
├── a
│   ├── b
│   │   ├── conftest.py
│   │   └── test_b.py
│   ├── conftest.py
│   └── test_a.py
├── c
│   ├── conftest.py
│   └── test_c.py
├── conftest.py
└── test_root.py
```

Each `conftest.py` file has such content:

```
def pytest_runtest_setup(item):
    # called for running each test in 'a' directory
    print ("setting up <name directory>", item)
```

Here is what I get, executing `py.test -svvv .`:

```
test_root.py::test_root ('setting up b', <Function 'test_root'>)
('setting up root', <Function 'test_root'>)
PASSED
a/test_a.py::test_a ('setting up a', <Function 'test_a'>)
('setting up root', <Function 'test_a'>)
PASSED
a/b/test_b.py::test_b ('setting up b', <Function 'test_b'>)
('setting up a', <Function 'test_b'>)
('setting up root', <Function 'test_b'>)
PASSED
c/test_c.py::test_c ('setting up c', <Function 'test_c'>)
('setting up root', <Function 'test_c'>)
PASSED
```

Notice the first entry - for `test_root.py` loaded `conftest.py` files from root directoriy  and `b`. But `b` is not closer to the filesystem root. Also it is not clear for me, why in some cases two `conftest.py` are loaded and in some - three?
# Output of `pip list`:

pip (8.0.2)
py (1.4.31)
pytest (2.8.7)
setuptools (18.2)
# Versions:

OS: Linux Mint 17.3 Rosa
PyTest: 2.8.7
# Example project:

https://github.com/AndrewPashkin/pytest_issue_1404

**Comment by nicoddemus** [comment]
Hi @elinxie,

Seems like this issue has been fixed, as I obtain the expected results in `7.2.2`:

```
λ pytest .tmp\1404 -sv --no-header
======================== test session starts ========================
collected 4 items

.tmp\1404\test_root.py::test_root setting up root <Function test_root>
PASSED
.tmp\1404\a\test_a.py::test_a setting up a <Function test_a>
setting up root <Function test_a>
PASSED
.tmp\1404\a\b\test_b.py::test_b setting up b <Function test_b>
setting up a <Function test_b>
setting up root <Function test_b>
PASSED
.tmp\1404\c\test_c.py::test_c setting up c <Function test_c>
setting up root <Function test_c>
PASSED

========================= 4 passed in 0.02s =========================
``` 

So, for each test file, the hooks in each `conftest.py` file are called from the directory of the test file, upwards in the file system.
