### ISSUE TITLE
Enhance ResultLog to allow extension of outcomes

### ISSUE THREAD

**Issue by florianpilz** [pytest-dev/pytest#1419]
The plugin [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures) adds a new outcome to py.test: `rerun`. When using py.test with the option `--result-log`, it tries to retrieve a `longrepr` of the outcome.

However, the if-clauses are limited to known outcomes (fail, pass, ...). Since there is no else-clause, the logger fails with an error if an unknown outcome should be logged. This is a excerpt from the current implementation of `_pytest.resultlog.ResultLog`:

    def pytest_runtest_logreport(self, report):
        if report.when != "call" and report.passed:
            return
        res = self.config.hook.pytest_report_teststatus(report=report)
        code = res[1]
        if code == 'x':
            longrepr = str(report.longrepr)
        elif code == 'X':
            longrepr = ''
        elif report.passed:
            longrepr = ""
        elif report.failed:
            longrepr = str(report.longrepr)
        elif report.skipped:
            longrepr = str(report.longrepr[2])
        self.log_outcome(report, code, longrepr)

As you can see in the last line, `longrepr` may be used before it was assigned, since there is no else-clause.

My suggestion is to

a) add an else-clause which reads `longrepr` from `report` (which I think is the best solution)
b) add an else-clause setting `longrepr = None` or `longrepr = ''` (whatever is more appropriate)

This allows to extend possible outcomes and can still use `ResultLog`.

**Comment by RonnyPfannschmidt** [comment]
resultlog is planned to be removed in favour of a more expressive format

**Comment by florianpilz** [comment]
Well, OK. In that case I will live with a workaround for my case.
