### ISSUE TITLE
Add a `get_marker` method to metafunc

### ISSUE THREAD

**Issue by birdsarah** [pytest-dev/pytest#1425]
I would like to use a marker to specify if I want a test parametrized. At the moment, I have to do the following:

``` python
def pytest_generate_tests(metafunc):
    if hasattr(metafunc.function, "cross_browser"):
         metafunc.parametrize('the fixture', params_list)
```

I was expecting an interface like item: `item.get_marker('cross_browser')` and it took me a while to hunt down this solution.

It seems like it would be a fairly straight forward addition, and I'd be willing to try rustling up a PR. Is there a reason that this isn't a feature already or is it just a matter of someone doing it?

**Comment by hpk42** [comment]
indeed, a ``metafunc.get_marker()`` looks like a very useful addition.  Please go for a PR :)

**Comment by RonnyPfannschmidt** [comment]
Btw, Imho we should Phase out metafunc in 3.x, its a artifact of unfortunate structure

**Comment by hpk42** [comment]
ronny, i see that as an orthogonal issue and one which i don't understand in detail.  Maybe you can take it to the pytest-dev ML sometime to detail your reasoning behind the suggestion.

**Comment by RonnyPfannschmidt** [comment]
Will do at the office

**Comment by RonnyPfannschmidt** [comment]
closing this one as superseeded

**Comment by ThomasWaldmann** [comment]
```
def pytest_generate_tests(metafunc):
    argnames = metafunc.fixturenames

    if 'store' in argnames:
        klasses = 'BytesStore', 'FileStore'
        argname = 'store'
    elif 'bst' in argnames:
        klasses = 'BytesStore',
        argname = 'bst'
    elif 'fst' in argnames:
        klasses = 'FileStore',
        argname = 'fst'
    else:
        klasses = None
        argname = None

    if klasses is not None:
        ids = []
        argvalues = []
        for storename in STORES:
            for klass in klasses:
                ids.append('{0}/{1}'.format(storename, klass))
                argvalues.append((storename, klass))
        metafunc.parametrize(argname, argvalues, ids=ids, indirect=True)

    multi_mark = getattr(metafunc.function, 'multi', None)
    mm = metafunc.function.get_closest_marker('multi')
    if multi_mark is not None:
        # XXX: hack
        ids = []
        argvalues = []
        stores = multi_mark.kwargs['Store']    # XXX blows up on pytest4
        for store in stores:
            ids.append(store.__name__)
            argvalues.append(store)
        metafunc.parametrize('Store', argvalues, ids=ids)
```

So, how can I access markers "the new way" from this function?

I read some docs, but that is still totally unclear to me and it seems that I also miss a `get_marker` function on the metafunc.

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann `metafunc.node.iter_markers`

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt thanks!

Is `node` a undocumented feature? https://docs.pytest.org/en/latest/reference.html#metafunc

**Comment by ThomasWaldmann** [comment]
```
E   AttributeError: 'Metafunc' object has no attribute 'node'
```

**Comment by RonnyPfannschmidt** [comment]
i'm sorry, i did miss remember, based on https://github.com/pytest-dev/pytest/blob/9dec146edf5baf74a82b91fc85762c8676b604b8/src/_pytest/python.py#L875 its `definition` not node

**Comment by ThomasWaldmann** [comment]
Also undocumented, but works. I get the `Mark` instance now.

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann the plan was to introduce the FunctionDefinition node in the official collection tree since quite a while, but i failed 2 different structural attempts to integrate it already
