### ISSUE TITLE
Documentation inconsistency: should pytest_addoption be implemented in conftest.py?

### ISSUE THREAD

**Issue by philandstuff** [pytest-dev/pytest#1427]
The latest docs for parameterized tests give [an example of implementing pytest_addoption in conftest.py](https://pytest.org/latest/parametrize.html#basic-pytest-generate-tests-example).

But [the docs for pytest_addoption itself](https://pytest.org/latest/writing_plugins.html?highlight=addoption#_pytest.hookspec.pytest_addoption) say:

> Implementing this hook from `conftest.py` files is **strongly** discouraged because `conftest.py` files are lazily loaded and may give strange *unknown option* errors depending on the directory `py.test` is invoked from.

I am confused because I have just followed the example in the latest parameterized test docs, only to discover I'm doing something that seems to be strongly discouraged.

**Comment by nicoddemus** [comment]
Good catch, we probably should change the example.

Just to be clear, here's why it is discouraged:

```python
# contents of ~/src/app/conftest.py
def pytest_addoption(parser):
    parser.addoption("--stringinput", action="append", default=[],
        help="list of stringinputs to pass to test functions")

# contents of ~/src/app/test_foo.py
def test_foo():
    pass
```

```sh
[~/src/app] $ py.test --stringinput foo -q
.
1 passed in 0.01 seconds

[~/src/app] $ cd ..
[~/src] $ py.test --stringinput foo -q
usage: py.test-script.py [options] [file_or_dir] [file_or_dir] [...]
py.test-script.py: error: unrecognized arguments: --stringinput
  inifile: None
```

**Comment by The-Compiler** [comment]
I wonder - having `pytest_addoption` in the project root's `conftest.py` shouldn't be an issue though, right? At least I didn't have trouble with that so far :wink:

**Comment by nicoddemus** [comment]
Hmmm good point, that works without problems. We probably should mention this special case in the docs as well. :grin: 

At the time I probably just felt it that it complicated things because `pytest_addoption` is called during pre-parsing time, and explaining that seemed to be more confusing than just discouraging using `pytest_addoption` in `conftest` files.

**Comment by hpk42** [comment]
I so far gave the advise to only use pytest_addoption in a conftest if it is situated at project root -- that should usually be totally fine and not get discouraged.

**Comment by nicoddemus** [comment]
We should also mention this in the documentation for `pytest_addoption` as well in the example.

**Comment by philandstuff** [comment]
just want to say I'm really impressed with the response to this issue. thank you very much! :+1:

**Comment by nicoddemus** [comment]
Thanks! :smile:
