### ISSUE TITLE
During teardown, it's not possible to use `request.node.add_report_section`

### ISSUE THREAD

**Issue by vincentbernat** [pytest-dev/pytest#1448]
Hey!

During teardown, it doesn't seem to be possible to include an additional report section.

``` python
import pytest

@pytest.yield_fixture
def fixture1(request):
    request.node.add_report_section('setup', 'hello', 'during setup')
    try:
        yield
    finally:
        request.node.add_report_section('teardown', 'hello', 'during teardown')


def test_simple(fixture1):
    assert False
```

(`try`/`finally` not needed)

I get the section for setup, but not for teardown. It seems that the "makereport" hook is done before teardown.  Using a finalizer instead of a `yield_fixture` gives the same result.

py.test 2.8 and python 3.5.1.

**Comment by nicoddemus** [comment]
Thanks for the report! :grin:

**Comment by RonnyPfannschmidt** [comment]
There is 3 times make report, at call, setup and teardown

**Comment by vincentbernat** [comment]
Yes, in fact `add_report_section` works in `pytest_runtest_makereport()`, only on `setup` and `call`.

**Comment by DahlitzFlorian** [comment]
I believe we can close this issue. I tested the code with pytest 5.4.1 and it works as expected.

**Comment by nicoddemus** [comment]
Thanks for checking up @DahlitzFlorian!
