### ISSUE TITLE
Conftest fixtures might not be found on case-insensitive file system

### ISSUE THREAD

**Issue by jgosmann** [pytest-dev/pytest#1453]
I'm trying to run unit tests for a project with `tox` on Windows. However, `py.test` is unable to find the fixtures even though the `conftest.py` file gets loaded (verifyed with `--traceconfig`). The command invoked by `tox` is:

```
C:\cygwin64\vagrant\.tox\py27\Scripts\py.test.EXE C:\cygwin64\vagrant\.tox\py27\Lib\site-packages/nengo
```

It works if I invoke the following command (note the lowercase `l` instead of uppercase in `lib`):

```
C:\cygwin64\vagrant\.tox\py27\Scripts\py.test.EXE C:\cygwin64\vagrant\.tox\py27\lib\site-packages/nengo
```

A bit of digging around revealed that `py.test` generally keeps the case of the argument passed in. However, the paths of test functions are [derived from Python code objects](https://github.com/pytest-dev/pytest/blob/master/_pytest/_code/code.py#L38) and these paths turn out to be all lowercase on my test system.

Furthermore, the `conftest.py` file has to be in a parent directory of the tests to get the fixtures applied. But because of the mismatch in case in the filenames the `conftest.py` file does not get recognized as being in a parent directory.
### pip list of the virtualenv

```
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
certifi (2016.2.28)
colorama (0.3.7)
cycler (0.10.0)
decorator (4.0.9)
functools32 (3.2.3.post2)
ipykernel (4.3.1)
ipython (4.1.2)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.2.2)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
mistune (0.7.2)
nbconvert (4.1.0)
nbformat (4.0.1)
nengo (2.1.0.dev0)
notebook (4.1.0)
numpy (1.10.4)
path.py (8.1.2)
pickleshare (0.6)
pip (8.1.0)
py (1.4.31)
Pygments (2.1.3)
pyparsing (2.1.0)
pyreadline (2.1)
pytest (2.9.0)
python-dateutil (2.5.0)
pytz (2016.1)
pyzmq (15.2.0)
qtconsole (4.2.0)
setuptools (20.2.2)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
tornado (4.3)
traitlets (4.1.0)
wheel (0.29.0)
```
### Versions

py.test 2.9.0
Python 2.7.11
Windows 7
### Minimal example

Might follow ...

**Comment by jgosmann** [comment]
I'm having some trouble putting together a minimal example. There seems to be something particular about the package under test and I haven't figured out what.

**Comment by kchawla-pi** [comment]
I am facing a similar issue. I am just starting out with pytest, and the function I wrote to establish the root path of my project becomes all lowercase and errs. If you wish I can try and push the files to my repo and share the link for you to study.

**Comment by RonnyPfannschmidt** [comment]
please take a look if `py.test --pyargs nengo` works for your usage
i suspect a issue with path normalization
