### ISSUE TITLE
Parameterized list parameter is displayed as [paramX] where X is the index of the test

### ISSUE THREAD

**Issue by nitrocode** [pytest-dev/pytest#1457]
I have a parameterized test and I have a parameter that can take either a string or a list of strings. If I give it a string, 

Using pytest 2.9.0 and Windows 8.1

test_params.py
```
import pytest
class TestParams:
    @pytest.mark.parametrize(("val"), [
        ("c"),
        (["c", "other"]),
    ])
    def test_function(self, val):
        if not isinstance(val, list):
            val = [val]
        for v in val:
            print v
```

```
$ py.test test_params.py
pytests/test_params.py::TestParams::test_function[c]
PASSED
pytests/test_params.py::TestParams::test_function[val1]
PASSED
```

The result shows **valX** instead of **(c,other)**

Given a list as a param within a parameterized function test, it would be nice if the list was expanded instead of showing the parameter name plus the index of its parameterized test.

**Comment by The-Compiler** [comment]
There is a [whitelist of types](https://github.com/pytest-dev/pytest/blob/master/_pytest/python.py#L1104-L1131) pytest considers suitable as test IDs. I guess it'd make sense to expand that so it also accepts iterables consisting only of such types, perhaps using `, ` or so as delimiter.

**Comment by RonnyPfannschmidt** [comment]
that works as expected, we only make textual id's in simple cases

you can supply own id's for complex cases

**Comment by The-Compiler** [comment]
@RonnyPfannschmidt Is there a reason we shouldn't do what I just described?

**Comment by RonnyPfannschmidt** [comment]
we would have to add a heusterics that is certainly very fragile

we would suddenly need to decide "simple sequence" - i really dont want to get into that until someone provides a external implementation that makes sense

else we will start to hunt edge cases

i strongly prefer "only simple hash-able types string-ify" for node ids

so any sequence/container is not part of that

**Comment by The-Compiler** [comment]
Can you explain what's fragile/complicated about doing something like:

```python
[...]
elif isinstance(val, collections.Iterable):
    return ', '.join(val)
```

**Comment by RonnyPfannschmidt** [comment]
your particular example will have inconsistent results for all unordered iterables - leading to even different test id's in parallel testing :)

sequences are a no go for node id's - never more than simple types, and best avoid anything with spaces

else we create error surfaces for endusers - and i don't want to end up fixing those without taking features away again

**Comment by nicoddemus** [comment]
I agree with @RonnyPfannschmidt on this one. Having to deal with sequences of arbitrary objects will lead to all kinds of edge cases, specially recursive iterables and iterables which are too big/expensive to convert to a an appropriate node id, not to mention items which might raise an exception when you call `str` on them. :grimacing: 

Having the ability to specify the node id yourself seems like an acceptable compromise in this case.

**Comment by nitrocode** [comment]
Ok. So what's the alternative then? Should I remove the list and replace it with a delimited string and then split that string within the test?

**Comment by nicoddemus** [comment]
I understand the example you posted was just for illustration and not really the original use case, so it is hard to tell what would be a good alternative because it really depends on the situation. Having said that your suggestion might make be the way to go, another one would be to use the `ids` parameter to pass custom made ids.

**Comment by nitrocode** [comment]
The original use case has the exact same arguments. I just slimmed it down for brevity.

Ah I wasn't aware of parameterize function's `ids` optional parameter. I also found an example on the [pytest fixtures](https://pytest.org/latest/fixture.html) page. Thank you.

**Comment by nicoddemus** [comment]
Glad we could help!
