### ISSUE TITLE
Help request: debugging scope-related failure

### ISSUE THREAD

**Issue by Zearin** [pytest-dev/pytest#1459]
## Description

- I’m testing a different testing framework using pytest
    - (FYI: I love pytest!  I actually discovered it in the process of working on this other project.  So I’m still a bit new to some of the magic pytest uses, but know that I plan on sticking with pytest for most projects in the future. ☻)
- The project is currently **pre-alpha**; for now it is only being written for Python 3 (Python 2 support is planned once out of pre-alpha)
- Pytest does some scope-related magic
- The project *also* needs to properly manage scopes
- Something scope-related is causing the test to fail, but I cannot determine why

The test needs to:

- declare a function-level variable, `result`
- run the fake tests (which contain nested functions, which are supposed to modify `result`)
- run assertions on `result` (to verify that the fake tests executed properly)

### Special Request

The project repository is currently private on GitHub.  I plan on making it public, but I want to get it to a minimally viable state first.  Therefore, if anyone on the pytest-dev team has a really solid knowledge of how Python scoping works—when doing weird things like testing a testing framework, each of which deviates from the scoping behavior of “normal” code—please add a comment, and I will add you as a collaborate to the project so you can run the test yourself.  

Thank you!   :D

## `pip list`

(Remember Python 3!  It’s really `pip3 list`, and the virtual env was created using `python3 -m venv`.)

```
appnope (0.1.0)
astroid (1.4.4)
blessings (1.6)
colorama (0.3.7)
decorator (4.0.9)
docopt (0.6.2)
eventemitter (0.2.0)
gherkin-official (3.2.0)
gnureadline (6.3.3)
ipython (4.1.2)
ipython-genutils (0.1.0)
lazy-object-proxy (1.2.1)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.6)
pip (8.1.1)
ptyprocess (0.5.1)
py (1.4.31)
pyee (1.0.2)
pylint (1.5.4)
pytest (2.9.0)
pytest-asyncio (0.3.0)
pytest-catchlog (1.2.2)
pytest-colordots (0.1)
pytest-pylint (0.4.1)
setuptools (20.3)
simplegeneric (0.8.1)
six (1.10.0)
termcolor (1.1.0)
traitlets (4.2.1)
Unidecode (0.4.19)
wrapt (1.10.6)
```

If you really know your scoping, let me know, and I’ll add to the private repo.

**Comment by nicoddemus** [comment]
Without looking at the code (so I'm not sure if you are doing something similar already), I recommend using a black box approach where tests executed by `py.test` actually call your framework's test runner in a separate python process, which in turn executes small, temporary tests. You then verify the expected output.

Pytest itself uses this approach in several of its internal tests, see [acceptance_test.py](https://github.com/pytest-dev/pytest/blob/master/testing/acceptance_test.py) for inspiration. 

Hope that helps! :grin:

**Comment by RonnyPfannschmidt** [comment]
if its open source in any case, just open up the repo - its hard to discuss things that are behind a wall

**Comment by RonnyPfannschmidt** [comment]
whats the state on this? i#d like to close or get a feedback

**Comment by Zearin** [comment]
I figured it out.  Sorry to leave this hanging; it’s an awkward position till I open up the repo (soon).

**Comment by RonnyPfannschmidt** [comment]
thanks for closing, best with the project, i hope it will met the public eye soon
