### ISSUE TITLE
Comparison with unittest2

### ISSUE THREAD

**Issue by philfreo** [pytest-dev/pytest#1476]
Apologies if this question is too broad, but I didn't see anywhere in the documentation where you explicitly compare pytest to unittest2. It would be nice to understand what high level use cases pytest solves over unittest2.

One article for example states:

> Although with unittest2 the convenience of py.test is coming to the standard library.

from http://halfcooked.com/presentations/pyconau2013/why_I_use_pytest.html

(e.g. now that unittest2 is available, does this mean I shouldn't use pytest?)

**Comment by nicoddemus** [comment]
Hi @philfreo,

That article is quite old, so it might not be a good reference. 

According to [PyPI](https://pypi.python.org/pypi/unittest2):

> unittest2 is a backport of the new features added to the unittest testing framework in Python 2.7 and onwards.

It basically allows you to use `unittest` features released in Python 3+ in Python 2.7, so I suspect that sentence in the article refers that `unittest2` has test [auto discovery](https://docs.python.org/3/library/unittest.html#command-line-interface), which `pytest` has had for a long time, along with a ton of other features not available in `unittest` or `unittest2`.

To an overview of all features of `py.test`, `nose` and `unittest` I suggest the excellent [pythontesting.net](http://pythontesting.net/).

HTH!

**Comment by philfreo** [comment]
Thanks

Overall I would suggest still adding a bit more of an explanation to https://pytest.org/latest/faq.html#how-does-pytest-relate-to-nose-and-unittest, outlining some of the major features/differences

**Comment by nicoddemus** [comment]
Thanks for the suggestion. I created a separate issue in #1477, so I'm closing this one for now. :grin:
