### ISSUE TITLE
Using yield_fixture as function causes fixtures to run twice

### ISSUE THREAD

**Issue by Wilfred** [pytest-dev/pytest#1481]
``` python
import pytest

def inner_function():
    print "begin inner_function!"
    yield
    print "end inner_function!"

my_fixture = pytest.yield_fixture(scope='session', autouse=True)(inner_function)

def test_foo():
    assert True
```

Running `pytest -s foo.py` gives:

``` python
foo.py begin inner_function!
begin inner_function!
.end inner_function!
end inner_function!
========= 1 passed in 0.01 seconds ============
```

It seems that py.test is erroneously thinking that `inner_function` is a fixture. Sometimes (because I want to use my function in other contexts too) I want to use yield_fixture as a function and pass my target function directly. When this happens, py.test tries to run my fixture twice.

**Comment by nicoddemus** [comment]
From #1480 it seems you are using pytest 2.6... could you try upgrading and see if you still have this problem?

**Comment by RonnyPfannschmidt** [comment]
the fixture decorator does indeed modify the function in-place by adding a new attribute

**Comment by Wilfred** [comment]
I can reproduce this on pytest 2.9.1 too.

**Comment by RonnyPfannschmidt** [comment]
the current implementation cannot support usage as non-decorator, since it modifies the function on passtrough

**Comment by nicoddemus** [comment]
Should we close this?

**Comment by RonnyPfannschmidt** [comment]
No, its still "broken" as far as I can tell

**Comment by nicoddemus** [comment]
I understand, I was asking more in the sense of "closing as not supported"

**Comment by RonnyPfannschmidt** [comment]
well, we should issue a pytest warning in case more than one active fixture has the same identity

**Comment by nicoddemus** [comment]
This is fixed by #2849

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus nope, #2849 fixes double use of the decorator

this is about naming the decorator result and the original function differently
in that case pytest find 2 fixtures with the same identity but different name in the globals

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt  OK, thanks for the clarification

**Comment by nicoddemus** [comment]
This is now fixed, `inner_function` is called only once:

```
test-foo.py begin inner_function!
.end inner_function!
                                                                                [100%]

==================================== 1 passed in 0.04 seconds =====================================
```
