### ISSUE TITLE
"Yield from" can result in crash in pytest

### ISSUE THREAD

**Issue by jleahy** [pytest-dev/pytest#1483]
The following code throws an exception in assertion/reinterpret.py when the assertion fails. Although I've tried to reduce this as much as possible the issue only appears when you have multiple files involved (moving the code from x.py into x_test.py fixes the problem).

output:

    self = <_pytest.assertion.reinterpret.DebugInterpreter object at 0x7f2da5c9f128>
    source = <_ast.Expression object at 0x7f2da5c9f208>, mode = 'eval'
    
        def _compile(self, source, mode="eval"):
    >       return compile(source, "<assertion interpretation>", mode)
    E         File "<assertion interpretation>", line 1
    E       SyntaxError: 'yield' outside function
    
    vv/lib/python3.5/site-packages/pytest-2.9.2.dev1-py3.5.egg/_pytest/assertion/reinterpret.py:184: SyntaxError

x.py:

    def returns_zero():
        yield 0
        return 0
    
    def has_failing_assert():
        assert (yield from returns_zero()) != 0

x_test.py:

    import x
    
    def test_example():
        for i in x.has_failing_assert():
            print(i)

This was tested using Python 3.5.1 in a fresh virtualenv with only pytest installed, here is the pip list:

    pip (8.1.1)
    py (1.4.31)
    pytest (2.9.1)
    setuptools (20.3.1)
    wheel (0.29.0)

I also tested this with pytest from git and received the same output.

**Comment by nicoddemus** [comment]
Thanks for the report!

**Comment by RonnyPfannschmidt** [comment]
this one no longer applies in pytest 3.0 as we removed reinterpretation
