### ISSUE TITLE
running py.test

### ISSUE THREAD

**Issue by hooman96** [pytest-dev/pytest#1484]
I am using python 3.5 and installed the latest pytest package with pip install.

I noticed in order to run py.test when I had example.py in my directory, I had to mention example.py as one of the command arguments. The guide said we can simply run py.test but it says: collected 0 items.

**Comment by The-Compiler** [comment]
Where in which guide are you seeing that? It doesn't work in your case because your file is named `example.py` - pytest only picks up files named `test_*.py` by default.

**Comment by The-Compiler** [comment]
Closing this for now - if there's anything still unclear, feel free to ask!
