### ISSUE TITLE
Online doc typo => bug

### ISSUE THREAD

**Issue by jorgehatccrma** [pytest-dev/pytest#1491]
There's a typo in your most excellent online documentation. In the [_integrating with setuptools_](http://pytest.org/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) section, the code snippet says `tests_require=['pytest', ...],`, but it should read `tests_requires=['pytest', ...],` (note the trailing _s_ in `test_requires`). This threw me off for a couple hours. The same mistake happens again in the [_manual integration_](http://pytest.org/latest/goodpractices.html#manual-integration) section.

**Comment by nicoddemus** [comment]
Thanks, but [setuptools' docs](https://pythonhosted.org/setuptools/setuptools.html) state that the correct keyword is `tests_require`. Perhaps you are using an old setuptools version?

**Comment by jorgehatccrma** [comment]
Ok, thanks.

**Comment by nicoddemus** [comment]
No problem, thanks for taking the time to write the report.
