### ISSUE TITLE
Bug in pyimport => samefile for relative path with '..' in the middle of path

### ISSUE THREAD

**Issue by qualab** [pytest-dev/pytest#1492]
- detailed description of the bug or suggestion:
  In case when samefile got path to file with '..' in the middle it fails with ImportMismatchError.
  It occurs because samefile does not apply os.path.abspath before comparing two path and related to bad behaviour function isabs.

``` python
    def samefile(self, other):
        other = getattr(other, "strpath", other)
        if not isabs(other):
            other = abspath(other)     # <= that should be applied for case of '..' in the middle of path
        if self == other:
            return True
```
- bug reproduced only on Windows, because of bad check of isabs() function in ntpath used to check is abspath need in samefile
- simply add something like this where is for example conftest.py :
  sys.path.append(os.path.join(PATH_TO_TEST_SCRIPT, '..', '..'))
  and try to run via pytest.main()

**Comment by nicoddemus** [comment]
Thanks @qualab for the report.

I could not reproduce the problem following your instructions... could you post more detailed steps on how to reproduce the problem? Thanks!
