### ISSUE TITLE
PDF Documentation lind redirects on 404 page

### ISSUE THREAD

**Issue by rojaster** [pytest-dev/pytest#1494]
Good time of day, The PDF documentation link is broken, it redirects to the page 404.

http://pytest.org/latest/pytest.pdf

**Comment by nicoddemus** [comment]
We are aware of that, thanks! Meanwhile please find the PDF docs generated by readthedocs [here](http://readthedocs.org/projects/pytest/downloads/pdf/2.9.1/).

Duplicate of #1436

**Comment by rojaster** [comment]
Ok, thank you

**Comment by The-Compiler** [comment]
I did a build of the 2.9 docs and uploaded them. Sorry for the delay!
