### ISSUE TITLE
can't pull conftest fixtures from doctests

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#1495]
If I create a fixture in tests/conftest.py I can't access it in a doctest in package_name/module.py with `getfixture`

See also https://stackoverflow.com/questions/25653147/pytest-doctest-with-fixtures-in-conftest-py

**Comment by nicoddemus** [comment]
Thanks for the report. :grin: 

Where is the doctest defined?

**Comment by graingert** [comment]
`package_name/module.py`

**Comment by bilderbuchi** [comment]
I can reproduce, with a file structure like this:
```
.
├── mypackage
│   ├── __init__.py
│   └── module.py
└── tests
    ├── conftest.py
    └── test_issue.py
```
File contents:
```
==> ./tests/test_issue.py <==
import mypackage.module

def test_plain_fixture(myfixture):
    """Fixture discovery in a plain test works"""
    assert mypackage.module.somefunc() == 2

==> ./tests/conftest.py <==
import pytest

@pytest.fixture
def myfixture():
    print('In my defined fixture')

==> ./mypackage/__init__.py <==

==> ./mypackage/module.py <==
def some_tmpdir():
    """built-in fixture are discovered normally
    >>> tmp = getfixture('tmpdir')
    """
    pass


def somefunc():
    """self-made fixture in a doctest is not discovered
    >>> tmp = getfixture('myfixture')
    In my defined fixture
    """
    return 2

```
If I move `conftest.py` into the root dir, it starts to work correctly.

**Comment by RonnyPfannschmidt** [comment]
conftests are always local for the directory tree they are defined in, so as far as i can tell this works as intended

**Comment by bilderbuchi** [comment]
OK, then I guess the docs should be updated? [Here](https://docs.pytest.org/en/latest/doctest.html#doctest-integration-for-modules-and-test-files) it says that "it is possible to use fixtures using the `getfixture` helper" -- I think (correct me if I'm wrong) that in typical/best practice/recommended test layouts, `conftest.py` would often end up outside the package's directory tree, so the above statement should probably be qualified somehow.

@graingert I don't know what you were trying to accomplish, but maybe it can be done by injecting into the doctest's namespace using https://docs.pytest.org/en/latest/doctest.html#the-doctest-namespace-fixture. A quick test seems to indicate that *that* fixture doesn't get discovered, either, if `conftest.py` is not above the module in the directory tree. I guess here also the docs could be improved regarding conftest.py location for doctests in modules and documentation.

**Comment by RonnyPfannschmidt** [comment]
@bilderbuchi it is possible that way, but for that the conftest must be in a shared folder tree - if it is in a sibling tree, it does no longer apply

**Comment by nicoddemus** [comment]
@bilderbuchi I agree the docs should at least mention those pitfalls; usually users won't be aware of them.
