### ISSUE TITLE
Xfail does not work with condition keyword argument. 

### ISSUE THREAD

**Issue by astraw38** [pytest-dev/pytest#1496]
In the docs, you provide a signature of the xfail marker:

`def xfail(condition=None, *, reason=None, raises=None, run=True, strict=False):`

However, trying to use the xfail marker with a condition keyword argument will cause it to always xfail the test, no matter the evaluation of the argument. 

Quick example:

```python

import pytest

@pytest.mark.xfail(condition=False, reason="this test should pass")
def test_xfail1():
     assert True

@pytest.mark.xfail(False, reason="this test actually passes")
def test_xfail2():
     assert True
```

**Comment by nicoddemus** [comment]
Thanks for the report!

**Comment by tomviner** [comment]
PR for this issue: https://github.com/pytest-dev/pytest/pull/1524
