### ISSUE TITLE
`py.test --doctest-modules` for C extension modules (Cython)

### ISSUE THREAD

**Issue by lgpage** [pytest-dev/pytest#1498]
Currently `py.test --doctest-modules` does not pick up C extension modules unless I am doing something completely wrong.
Request: Please look into adding py.test doctest support for C extension modules (Cython)

This link may also prove useful:
http://stackoverflow.com/questions/25131630/doctests-fail-with-unicodedecodeerror-on-c-extension-and-python3

**Comment by lgpage** [comment]
Plugin created:
https://github.com/lgpage/pytest-cython

Feedback / comments regarding the implementation is welcome.

**Comment by nicoddemus** [comment]
That's excellent work! Would you like to move this plugin under the pytest-dev organization? :grin:

**Comment by lgpage** [comment]
Not yet. Need people to use / test it a bit first.
Also windows isn't supported yet.
Need to ask the Cython community to help me with that, I'm clearly missing something and lack the experience w.r.t. builds on appveyor.

**Comment by Zac-HD** [comment]
Closing this issue as inactive with a published plugin.
