### ISSUE TITLE
missing evaluated value in report when asserting a boolean attribute (using --assert=rewrite)

### ISSUE THREAD

**Issue by bagerard** [pytest-dev/pytest#1503]
Hi there,

First of all, thank you for the amazing work you've done on pytest! It is really cool!
When asserting a boolean attribute of an object, the actual value isn't printed in the output as it would be with other types (int, str, etc). I'm using latest pytest 2.9.1

```
def test_a():
    class AA():
        pass
    a = AA()
    a.t = False
    assert a.t is True
```

Provides the following output (using with ---assert=rewrite):

> ...
> \>       assert a.t is True
> E       assert \<test.AA instance at 0x7fb9399169e0\>.t is True

And if run with ---assert=reinterp:

> ...
> \>       assert a.t is True
> E       <b>assert False is True</b>
> E        +  where False = \<test.AA instance at 0x7f24de4740e0\>.t

Thanks

**Comment by tomviner** [comment]
This is caused by the [_collapse_false](https://github.com/pytest-dev/pytest/blob/3155d0ca9c75d3c984de84251ff12d97253134f3/_pytest/assertion/util.py#L47) function, which aims to trim away trivial explanations.

For example this test:
```python
def test_false_value():
    x = 0
    assert bool(x)
```

Full explanation, with `_collapse_false` patched out:
```python
    def test_false_value():
        x = 0
>       assert bool(x)
E       assert False
E        +  where False = bool(0)
```

Trimmed explanation, with `_collapse_false` back in place:
```python
    def test_false_value():
        x = 0
>       assert bool(x)
E       assert bool(0)
```

I'm having trouble recreating an example where useful information is trimmed away.

**Comment by bagerard** [comment]
Hi tomviner, Thanks for your reply. I wasn't aware of such behaviour and in my case I wasn't sure if my asserted value was a boolean or not. In fact if you take the following test:

```
def test_foo2():
    mo = Foo(a=False)
#>       assert mo.a
#E       assert <test.Foo instance at 0x7f28a5ff0dd0>.a
```

The output isn't telling me if mo.a is False or if it's anything else that evalues to False (0 for instance). It turns out that the output is different if it is 0 but without knowing this, you can't tell... 
I understand that you want to trim away trivial explanations but personally I find it confusing for newcomers.
This ticket can be switched to "proposal", I suggest to trim away the _collapse_false method :)
