### ISSUE TITLE
PDF Documentation on Home Page not available - 404 Not Found

### ISSUE THREAD

**Issue by mh182** [pytest-dev/pytest#1513]
All links to the PDF Documentation on "http://pytest.org" return a "404 Not Found".

**Comment by nicoddemus** [comment]
Thanks for the report.

Closing as duplicate of #1436, but you can access docs.pytest.org for PDF docs meanwhile.

**Comment by The-Compiler** [comment]
I did a build of the 2.9 docs and uploaded them. Sorry for the delay!
