### ISSUE TITLE
ANSI codes instead of colors when importing colorama in conftest

### ISSUE THREAD

**Issue by grovduck** [pytest-dev/pytest#1515]
When running tests on a package (mapbox/rasterio) that imports colorama (directly or indirectly - in this case `click`) through `conftest.py`, I get raw ANSI codes in the output of the tests instead of colors.

Here is my configuration:

```
Windows 7 64-bit / Python 2.7 32-bit
Relevant packages:
colorama==0.3.7
py==1.4.31
pytest==2.9.1
```

I am using the default CMD shell and the environmental variable `TERM` is not set.  Here's a simple example to recreate the issue:

**tests/test_foo.py**

```
def test_answer():
    assert 5 == 5
```

**conftest.py**

```
import colorama
```

**Output**

```
C:\Users\gregorma\Desktop\foo>py.test
←[1m============================= test session starts =============================←[0m
platform win32 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: C:\Users\gregorma\Desktop\foo, inifile:
collected 1 items ←[0m←[1m
←[0m
tests\test_foo.py .

←[32m←[1m========================== 1 passed in 0.03 seconds ===========================←[0m
```

If I comment out `import colorama` in conftest.py, it behaves as expected.  

![bug](https://cloud.githubusercontent.com/assets/1706997/14543812/e034212c-024a-11e6-995b-cfab55888328.png)

The same behavior is observed either using my standard Python or within a virtualenv.  I'm guessing I'm doing something really dumb, but have yet to find documentation or bug reports on this issue.

**Comment by skygeo** [comment]
Same thing here. Except that the text is transparent.
For me, issue appeared after version 0.3.3

**Comment by The-Compiler** [comment]
I've seen black-on-black test on Windows in my testsuite for a while too. While I don't import `colorama` directly in my `conftest.py`, my project under test *does* import it, so this might be why!

**Comment by grovduck** [comment]
It took my feeble brain hours to trace through why this was happening, but I think I now understand what's going on.  `conftest.py` is getting loaded as a plug-in module and imports `colorama` in turn for this scenario.  Drilling way deep, `colorama` defines a dictionary called `handles` [here](https://github.com/tartley/colorama/blob/master/colorama/win32.py#L92-L95).  This sets the `handles` dictionary as of the plugin import.

When pytest sets up its terminal writer, it re-loads colorama, but at this point, the handles have changed, yet functions like `winapi_test`, `GetConsoleScreenBufferInfo` and other functions are relying on the `handles` dictionary to provide the information.  If one changes:

    handle = handles[STDOUT]

to:

    handle = _GetStdHandle(STDOUT)

in these functions, it seems to fix the problem.  One other issue is that the `winterm` instance gets set in `ansitowin32.py` (again on plugin load) and then isn't set correctly when formatting the text.  I introduced a ugly second instantiation of a `WinTerm` object right at the top of the `get_win32_calls` function which sets it correctly when the terminal writer is set.

It seems like this is only an issue when the module first gets imported through the plugin loading process, so I'm not sure if this should be considered an issue with `pytest` or `colorama`.  Forgive my naive explanation ...

**Comment by nicoddemus** [comment]
@grovduck thanks for the detailed investigation!

It makes sense now: pytest changes the stdout/stderr handles when importing conftest files to capture output, and that might be a problem if `colorama` is getting stdout and stderr handles later. 

It seems to me that `colorama` should not store those handles but just call `_GetStdHandle(OUT)` when needed. `pytest` can't do anything to prevent users to import `colorama` first and make it store handles which will be different from the actual stdout/stderr handles later.

@grovduck would you care to open an issue at the [colorama issue tracker](https://github.com/tartley/colorama/issues)?

**Comment by grovduck** [comment]
Thanks, @nicoddemus.  Submitted a `colorama` issue ...

**Comment by nicoddemus** [comment]
Thanks @grovduck, I'm watching the issue to see how it progresses.

**Comment by The-Compiler** [comment]
https://github.com/tartley/colorama/issues/114 is the link, by the way :wink:
