### ISSUE TITLE
Line numbers not being shown in traceback

### ISSUE THREAD

**Issue by chrisspen** [pytest-dev/pytest#1517]
I'm running py.test with options to show the full uncut traceback like:

    py.test -rxs -rf -rs --ff --tb=long --full-trace -x -k mytest

However, the traceback shown is nonsensical and doesn't reference my code nor show the line number where the exception occurred.

self = <_pytest.config.PytestPluginManager object at 0x7f77b52b5c10>, conftestpath = local('/myproject/tests/functional_tests/conftest.py')

    def _importconftest(self, conftestpath):
        try:
            return self._conftestpath2mod[conftestpath]
        except KeyError:
            pkgpath = conftestpath.pypkgpath()
            if pkgpath is None:
                _ensure_removed_sysmodule(conftestpath.purebasename)
            try:
                mod = conftestpath.pyimport()
            except Exception:
>               raise ConftestImportFailure(conftestpath, sys.exc_info())
E               ConftestImportFailure: (local('/myproject/tests/functional_tests/conftest.py'), (<type 'exceptions.ImportError'>, ImportError('cannot import name disable_module',), <traceback object at 0x7f77b0844128>))

The conftestpath indicates one of my source files, but the code shown is from some internal py.test file.

**Comment by nicoddemus** [comment]
Fixed in #1746.
