### ISSUE TITLE
strange path error after re-installing python

### ISSUE THREAD

**Issue by DSLituiev** [pytest-dev/pytest#1518]
I recently removed anaconda and installed Python3.5 from scratch. Called `pip3 install pytest`. `PYTHONPATH` is not set. Now calling:

```
py.test
bash: /Applications/anaconda2.7/anaconda/bin/py.test: No such file or directory
```

Checking path:
```
which py.test
/Library/Frameworks/Python.framework/Versions/3.5/bin/py.test
```

From the shell:
```
python3
>>> import pytest
>>> pytest.__file__
 '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pytest.py'
```

**Comment by RonnyPfannschmidt** [comment]
at very first glance this looks like a shell command cache issue, please verify if `hash -r` rectifies it

else looks like some left around by anaconda installation,

also check if by chance a py.test binary in the error folder exists, but refers to the removed interpreter
(a broken binary that wins by path priority is another likely option)

**Comment by DSLituiev** [comment]
`hash -r` helped. Thank you!
