### ISSUE TITLE
show deselected info after collected info and before test execution

### ISSUE THREAD

**Issue by fontealpina** [pytest-dev/pytest#1527]
In my workflow, may be useful get the informations about deselected tests after the collected info an before the beginning of tests executed, because (especially if the test execution takes a long time), I would check if I have properly selected the test to run.  
For instance, would be nice something like this:  

```
$pytest -v -s test_try.py -m fast
============================ test session starts ============================
platform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.9.1 -- /usr/bin/python
collected 4 items 
===================== 3 tests deselected by "-m 'fast'" =====================
test_try.py .
```

Currently this info is shown after the test execution.
I was wondering if there is an easy way to get this also before the test execution, maybe writing a plugin?

Thanks

**Comment by nicoddemus** [comment]
A plugin is possibly I guess, but I wonder if it makes sense to change this behavior in pytest itself:

```
$pytest -v -s test_try.py -m fast
============================ test session starts ============================
platform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.9.1 -- /usr/bin/python
collected 4 items (3 deselected by "-m 'fast'")
test_try.py .
```

**Comment by RonnyPfannschmidt** [comment]
sounds like a good idea

**Comment by fontealpina** [comment]
ok, for me this would be super.
Maybe wouldn't be better print the number of 'selected' tests instead of the 'deselected' ones?

**Comment by RonnyPfannschmidt** [comment]
if we just print the number of selected ones we also avoid the bug wrt deselection reasons

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt hmm which bug do you mean?

**Comment by RonnyPfannschmidt** [comment]
#1372

**Comment by nicoddemus** [comment]
I see, thanks!

**Comment by arunksaha** [comment]
+1. A list of deselected tests would be useful.

**Comment by The-Compiler** [comment]
I don't think it's a good idea to print such a list by default. If I use `-m foo` or `-k foo`, I don't want a list of hundreds/thousands of tests I'm explicitly not interested in.

**Comment by arunksaha** [comment]
@The-Compiler Agree, listing hundreds/thousands of tests **by default** won't be a good idea :)

How about listing them when an additional flag, such as `--list-deselected`, is specified?

**Comment by nicoddemus** [comment]
I agree with @The-Compiler, if this functionality is implemented it should definitely be opt-in. 😁

**Comment by thisch** [comment]
The following patch adds the deselection count to the 'collected' line, but does not yet remove the deselection summary (`==== X tests deselected ====`). 

WDYT should we remove this summary line if the deselection count is part of the 'collected' line?  

```diff
diff --git a/_pytest/terminal.py b/_pytest/terminal.py
index 51d21cb..e5c5d9d 100644
--- a/_pytest/terminal.py
+++ b/_pytest/terminal.py
@@ -356,6 +356,8 @@ class TerminalReporter(object):
 
         errors = len(self.stats.get('error', []))
         skipped = len(self.stats.get('skipped', []))
+        deselected = len(self.stats.get('deselected', []))
+
         if final:
             line = "collected "
         else:
@@ -365,6 +367,8 @@ class TerminalReporter(object):
             line += " / %d errors" % errors
         if skipped:
             line += " / %d skipped" % skipped
+        if deselected:
+            line += " / %d deselected" % deselected
         if self.isatty:
             self.rewrite(line, bold=True, erase=True)
             if final:
@@ -372,6 +376,7 @@ class TerminalReporter(object):
         else:
             self.write_line(line)
 
+    @pytest.hookimpl(trylast=True)
     def pytest_collection_modifyitems(self):
         self.report_collect(True)
```
