### ISSUE TITLE
Not able to fetch testcase docstring with item.obj.__doc__ 

### ISSUE THREAD

**Issue by reddypdl** [pytest-dev/pytest#1528]
item.obj.__doc__ used to fetch the test case doc-string in pytest 2.7.0 version, but in 2.9.1 it shows None.

Code to fetch doc string from current test case.

```
@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):   
    outcome = yield
    report = outcome.get_result()
    
    if report.when == 'call':    
        if item.obj.__doc__:
            report.nodeid = 3 * '-' + item.obj.__doc__.strip()
        else:
            report.nodeid = 3 * '-' + "Test Case Description is missing, please add"
```
as explained in http://stackoverflow.com/questions/28898919/use-docstrings-to-list-tests-in-py-test

Could you please help , how to get this done?

**My test case is**
```
import pytest
@pytest.mark.parametrize("test_input,expected", [
        ("3+5", 8),
        ("2+4", 6),
        ("6*9", 42),
                ],ids=["3+5","2+4",'6*9'])
def test_TC_eval(test_input, expected):
    ''' test case for '''+ test_input
    assert eval(test_input) == expected

```

Expecting output as:

test case for 3+5
test case for 2+4
test case for 6*9

**Environment:**
platform linux2 -- Python 2.7.6, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /home/symbol/work/automation/concierge/venv/bin/python
cachedir: .cache
rootdir: /home/symbol/work/pytest/report_parameterizse, inifile: pytest.ini
plugins: html-1.8.0, xdist-1.14, repeater-0.1.0, remove-stale-bytecode-2.1, timeout-1.0.0, rerunfailures-2.0.0, random-0.2, instafail-0.3.0

**Comment by RonnyPfannschmidt** [comment]
standard python behaviour is only strings go to the doc-string
however you used a expression

```pycon
>>> def foo(bar):
...     'a' + bar
... 
>>> foo.__doc__ is None
True
```

**Comment by RonnyPfannschmidt** [comment]
```
>>> def baz(bar):
...     'a'
...     bar
...     
... 
>>> baz.__doc__
'a'
