### ISSUE TITLE
2 tests fail when conftest.py file exists in /tmp folder

### ISSUE THREAD

**Issue by palaviv** [pytest-dev/pytest#1536]
While working on another issue I noticed that the following tests fail if there is a conftest.py file in /tmp:

- testing/test_conftest.py::test_conftest_import_order
- testing/python/fixture.py::TestAutouseManagement::()::test_class_function_parametrization_finalization

It seems both tests find the conftest.py file in /tmp instead the one they were looking for.

**Comment by RonnyPfannschmidt** [comment]
Looks like pytestr needs to set a confcutdir

**Comment by RedBeardCode** [comment]
Added the link in the Changelog
