### ISSUE TITLE
UnboundLocalError unless `global` is used

### ISSUE THREAD

**Issue by gglanzani** [pytest-dev/pytest#1538]
I have the following code

```python
RawRecord, record_struct = create_tuple_struct('RawRecord', raw_record_fields)

def parse_record(record_type=None, input=None, offset=0):
    """
    Return the namedtuple corresponding to the given `record_type`
    """
    #global record_struct  # this is needed for pytest
    if record_type is 'raw':
        return create_namedtuple(input, RawRecord, record_struct)
    else:
        record_namedtuple, record_struct = record_types.get(record_type)
        return create_namedtuple(input, record_namedtuple, record_struct, offset=offset)
```

Note the global commented out. `py.test` is failing me with an `UnboundLocalError`. However `create_namedtuple` is NOT trying to modify `record_struct` and the code runs fine if I just run it. See more info on the system below. If I uncomment the `global` line (which, again, is not needed to have the code run just fine), then `py.test` does not complain. If more info's are need, don't hesitate to let me know.

`pip freeze` output

```sh
colorama==0.3.7
py==1.4.31
pytest==2.9.1
```

`py.test` output

```sh
============================= test session starts =============================
platform win32 -- Python 3.5.0, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: C:\Users\Giovanni\.babun\cygwin\home\Giovanni\code\sam-spark\sam, inifile:
collected 1 items

tests\test_records.py F

================================== FAILURES ===================================
_________________________________ test_header _________________________________

    def test_header():
        header = b'raw

                                                                                                                                                           '
>       record = parse_record(record_type='raw', input=header)

tests\test_records.py:5:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

record_type = 'raw'
input = b'raw       ...
                                                                                 '
offset = 0

    def parse_record(record_type=None, input=None, offset=0):
        """
        Return the namedtuple corresponding to the given `record_type`
        """
        #global record_struct  # this is needed for pytest
        if record_type is 'raw':
>           return create_namedtuple(input, RawRecord, record_struct)
E           UnboundLocalError: local variable 'record_struct' referenced before assignment

records.py:103: UnboundLocalError
========================== 1 failed in 0.09 seconds ===========================
```

**Comment by RonnyPfannschmidt** [comment]
you reuse a global variable name as local variable name, that is a basic python misuse and unrelated to pytest

**Comment by The-Compiler** [comment]
I agree with @RonnyPfannschmidt here - I'm pretty sure this doesn't run with python either. Can you show a working example which works with python but not pytest?

Sidenote: You do `if record_type is 'raw':` in your code, you should use `==` instead. If `is` works for string comparisons, that's purely by accident. `is` is used if two objects are the same (not just equal), and there's rarely a reason to use it except for `is None`.

**Comment by gglanzani** [comment]
@The-Compiler I know how `is` works, thanks :)

@RonnyPfannschmidt I'm not reusing, I'm merely referencing to it. My gripe it that I should not be able to access RawRecord as well, but I only need to uncomment the `global` line, and `pytest` stops complaining. 

@The-Compiler See example below (and, I repeat, the code above is working, but it fails without the `global`):

```python
>>> a = 1
>>> def a_p_1():
...     return a + 1
...
>>> a_p_1()
2
>>>
```

**Comment by RonnyPfannschmidt** [comment]
your minimal example does not use and assign

```
>>> a = 1
>>> def bad():
...     if a:
...         a = 0
...     return a
... 
>>> bad()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    bad()
  File "<input>", line 2, in bad
    if a:
UnboundLocalError: local variable 'a' referenced before assignment
>>> 
```

`record_namedtuple, record_struct = record_types.get(record_type)` is a assignment

**Comment by The-Compiler** [comment]
And that works fine in pytest too:

```python
a = 1
def a_p_1():
    return a + 1


def test_foo():
    assert a_p_1() == 2
```

```
======================== test session starts =========================
platform linux -- Python 3.4.2, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/florian, inifile: 
plugins: services-1.1.11, catchlog-1.2.0
collected 1 items 

x.py .

====================== 1 passed in 0.00 seconds ======================
```

As for your original example, I won't believe you this works with python until I see it, sorry :wink:

Random guess: Your wrong `is` comparison happens to be true when you try with python (and thus the failing branch is never taken), but false with pytest.

**Comment by gglanzani** [comment]
@RonnyPfannschmidt Clear, thanks.

**Comment by RonnyPfannschmidt** [comment]
@gglanzani you might want to simply put the default value for raw into the mapping for record types

 i suspect that will be a welcome simplification since the code no longer has to be smart

**Comment by gglanzani** [comment]
@RonnyPfannschmidt It is a welcome addition, thanks!
