### ISSUE TITLE
pytest.main causes grief when called with a unicode string

### ISSUE THREAD

**Issue by Kuzmin** [pytest-dev/pytest#1543]
Hello!

I'm writing a wrapper for the pytest tests at our company. Some of our `pytest.main` calls fail with 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/yolo/tests/aws/system_stress/stress_test_iteration.py", line 241, in run
    test_iter)
  File "/home/ubuntu/yolo/tests/aws/system_stress/stress_test_iteration.py", line 324, in run_fancy_tests
    exit_code = self.execute_fancy_tests(test_iter, test)
  File "/home/ubuntu/yolo/tests/aws/system_stress/stress_test_iteration.py", line 307, in execute_fancy_tests
    return pytest.main(test_command)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 39, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 106, in _prepareconfig
    raise ValueError("not a string or argument list: %r" % (args,))
ValueError: not a string or argument list: u'REDACTED'
```

I read the source code available at https://pytest.org/latest/_modules/_pytest/config.html and saw that you are checking the input with `isinstance(args, str)`. This works in python3 since `str` has unicode support, but in python2 it causes issues since there are two string types, `str` and `unicode`.

Checking for strings in python2 is usually done with `isinstance(args, basestring)` ([source](https://stackoverflow.com/questions/1979004/what-is-the-difference-between-isinstanceaaa-basestring-and-isinstanceaaa)), but of course this doesn't work in Python 3. There are a few options to get cross-python compatible solutions on StackOverflow [here](https://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility), unfortunately none of them are very simple.

Would a PR be welcome for this?

Thanks!

**Comment by nicoddemus** [comment]
I don't have any problems about accepting this.

[py](https://bitbucket.org/pytest-dev/py/src/4617fe465cfc3289cefb8e7b8ce28ed5168f139f/py/_builtin.py?at=default&fileviewer=file-view-default) already has some code for this, it probably wasn't used by oversight. I think the check could be (untested):

```python
isinstance(arg, py._builtin._basestring)
```

> Would a PR be welcome for this?

Certainly! :smile:

**Comment by RonnyPfannschmidt** [comment]
closing this one as unsupported, in pytest 3.0 we will also deprecate passing a string to `pytest.main`

**Comment by Kuzmin** [comment]
That sounds like a good solution :) Thanks!
