### ISSUE TITLE
pytest command (entry point) spams with DeprecationWarning messages related ipython

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#1545]
It seems that `pytest` command (entry point) behaves differently than the module calling approach `python -m pytest` and reports a dozen on screens of warnings related to ipython (4.1.1) if it happens to be installed. (used py3 to test)

It looks inside the code of the entry point and it seems that it does enable DeprecationWarning which is clearly not something desired, especially as it does introduce different behaviour than the module calling method.
```
#!/usr/local/opt/python/bin/python2.7

import warnings
warnings.simplefilter('default', DeprecationWarning)

from logilab.common.pytest import run
run()
```

The problem is even worse because pytest, well, is used to test python code so all pytest users will have to endure seeing tons of warnings that have nothing to do with their tested modules, as they are inside other modules.

**Comment by The-Compiler** [comment]
`pytest` from `logilab.common` has nothing to do with the pytest project, and is something which is probably not used anywhere outside of [logilab](https://www.logilab.fr/) (but it got installed via `logilab-common` in older versions of pylint)

**Comment by ssbarnea** [comment]
Wow, I am wondering how did this endup installed on my system and now is the first time when I read about `logiclab`.

What is even worse is that uninstalling all pytest modules from my system did not remove the `pytest` command. Even locate seems to fail to find any `logiclab` files on my disk.

Sorry for raising the non bug, seems to be a local issue.

**Comment by The-Compiler** [comment]
Note it's "logilab", not "logiclab" :wink: As said, most likely this was installed as a dependency of pylint (logilab-common), but newer versions don't depend on it.

**Comment by ssbarnea** [comment]
I guess I was hit by this http://www.christianlong.com/blog/pytest-vs-pytest.html
