### ISSUE TITLE
Provide way to extract error information when assertion failed

### ISSUE THREAD

**Issue by purpleP** [pytest-dev/pytest#1547]
I need to filter output of py.test and store it in a log file. What I actually need is full path to the function/class/method that's failed, docstring and explanation.

For example

_______________________________________________________ test_1 ```
________________________________________________________

    def test_1():
        """
        some info
        """
        a = {1, 2, 3}
        b = {2, 3, 4}
>       assert a == b, 'Something went wrong'
E       AssertionError: Something went wrong
E       assert set([1, 2, 3]) == set([2, 3, 4])
E         Extra items in the left set:
E         1
E         Extra items in the right set:
E         4
E         Use -v to get the full diff
```

The log file should look like that

tests/test_foo.py:10
some info
AssertionError: Something went wrong
assert set([1, 2, 3]) == set([2, 3, 4])
Extra items in the left set:
1
Extra items in the right set:
4

I've read the docs and and figured out first part of the task

```
@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    rep = outcome.get_result()
    if rep.when == 'call' and rep.failed:
        with open('/tmp/failures', 'a+') as f:
            f.write(rep.nodeid + '\n')
```

But I can't find any way to get other parts except parse the output with regex (which is doable of course).
What's complicating things more is that I can't run py.test with pdb to actually see how it works, so I can only read the code. I've found ```util.format_explanation```, but can't figure out where how exactly it's used and how pytest works in general.

**Comment by RonnyPfannschmidt** [comment]
the item object has both the node ide, the fs location fo the file and the actual function object

if i recall correct, you want to take a look at the `item.obj` attribute

**Comment by purpleP** [comment]
@RonnyPfannschmidt Okay, I've found that item._obj has function and from there I can extract docstring. But what about a so called 'explanation' e.g. the last part that I need?

**Comment by RonnyPfannschmidt** [comment]
out off rough memory, it should be in the sections of the report - for details on how to get/obtain parts i'd have to check the code myself

**Comment by purpleP** [comment]
@RonnyPfannschmidt Could you do that for me? Because I can extract thing called longrepr, but that's not what I want as you probably understand.

**Comment by RonnyPfannschmidt** [comment]
the test report object has a sections attribute, if the element for traceback/ doesnt contain what you need, something more manual is needed and i#d have to look the code up myself (as in i wont get to it at least this week)

**Comment by purpleP** [comment]
@RonnyPfannschmidt sections are empty list for me.

**Comment by nicoddemus** [comment]
I wonder, why can't you debug pytest using `pdb`? I ask because I do that all the time, both using `pdb` and PyCharm's pydev debugger.

**Comment by purpleP** [comment]
@nicoddemus I can debug the tests without a problem. 

```
import pytest

import pdb;pdb.set_trace()
pytest.main('/Code/experiments/pytest_test')
```
Well try to run this with any tests in pytest_tests/tests folder. I don't know about you and pycharm, but for me this results in
`termios.error: (25, 'Inappropriate ioctl for device')`

**Comment by nicoddemus** [comment]
Try to pass the `-s` flag, this disables pytest's capture.
