### ISSUE TITLE
junit output doesn't add skipped tests into tests total

### ISSUE THREAD

**Issue by fushi** [pytest-dev/pytest#1549]
If you have a test that is skipped, the test case still is inserted into the xml, and the skips attribute is incremented, but the tests attribute is not. This causes a mismatch between the number of test cases, and the number in the tests attribute:

<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="1" tests="1" time="0.046"><testcase classname="test_uninstall" file="test_uninstall.py" line="11" name="test_fail" time="0.000958919525146"><failure message="assert False">def test_fail():
&gt;       assert False
E       assert False

test_uninstall.py:13: AssertionError</failure></testcase><testcase classname="test_uninstall" file="test_uninstall.py" line="14" name="test_skip" time="0.000383853912354"><skipped message="Skipped on this environment: stg1" type="pytest.skip">/Users/jtowler/source/clover/web_testing/conftest.py:164: &lt;py._xmlgen.raw object at 0x10ac03d50&gt;</skipped></testcase></testsuite>

**Comment by nicoddemus** [comment]
```python
import pytest

def test1():
    pass

def test2():
    pytest.skip('reasons')
```

XML:

```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="1" tests="1" time="0.038">
    <testcase classname="foo" file="foo.py" line="2" name="test1" time="0.0009999275207519531"/>
    <testcase classname="foo" file="foo.py" line="6" name="test2" time="0.0">
        <skipped message="reasons" type="pytest.skip">X:\pytest\foo.py:8: &lt;py._xmlgen.raw object at 0x032D6E90&gt;</skipped>
    </testcase>
</testsuite>
```

So the `tests` attribute of the `testsuite` node should be total number of tests, instead of tests actually executed?

**Comment by fushi** [comment]
That's correct.

**Comment by fushi** [comment]
https://github.com/pytest-dev/pytest/pull/1551
