### ISSUE TITLE
assertion rewriting should report errors when passing tuples to assertions

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1562]
in a downstream project we suffered some false passes due to a new programmer using code like

`assert(condition, message)` which is always true and certainly wasn't the intention

**Comment by Akasurde** [comment]
@RonnyPfannschmidt I would love to work on this. Could you please explain more about this issue?

**Comment by RonnyPfannschmidt** [comment]
@Akasurde the idea is, that when the ast rewriter sees a Assert node whose assertion is a tuple, it should issue a pytest-warning

the problem is that python has an equivalence of `assert (False , 'foo')` and `ohjoy = (False , 'foo'); assert ohjoy`

so we can take it for sure, that the test-writer meant to write `assert False , 'foo'` however we should not correct and/or hide that, instead just inform them

**Comment by The-Compiler** [comment]
Would it be possible to only issue the warning if it's a tuple literal? I think if `assert some_tuple` would show a warning that'd be quite bad.

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler thats how i meant it, i just used the example to show what python does

**Comment by nicoddemus** [comment]
Fixed in #1675
