### ISSUE TITLE
Return informations from test body to pytest 

### ISSUE THREAD

**Issue by fontealpina** [pytest-dev/pytest#1570]
In my workflow I have the necessity to return an information from the test body to pytest framework, in order to process it in some plugin. To my best knowledge, the only thing that can be returned is the assertion failure message, but this only when the test fails. If the test pass, there is no way to get back the message or a local variable in pytest.

For instance:
```python
class  TestSuite:
   def test_case:
         local_variable = 10
         # can be used as assert message
         assert True, 'failure msg'
```
I could append `local_variable` to failure message, like `assert True, 'failure msg %s' % local_variable`, and then filter it into the plugin, but this is an hack and it works only when the assertion fails.
I would return back `local_variable` both when test pass or fail,  in order to use it into a plugin. 
Is there a way to do it?
Thanks

**Comment by RonnyPfannschmidt** [comment]
that needs a custom plugin and a fixture

you can take a example with the code of the junitxml plugin thats shipped in pytest - it supports adding properties as metadata to junitxml suites and cases by using methods on a fixture

in any case the reporting has to be explicit in some way, since python doesn't do the implicit one by default

**Comment by fontealpina** [comment]
Thanks for the suggestion.
I checked junitxml plugin, and the solution I think may work. 
I have 2 questions about this:
1.  Basically I have two custom plugin for junitxml and resultlog, cause I need a customized log format.
So my idea was to create a fixture in order to add an attribute to `report` object, like:
```python
@pytest.fixture
def custom_fixture(request):
     # here how can be added a report attribute
     # e.g.
     setattr(report, 'new_value', 10)
```
How is possible modify a `report` attribute from a `request` attribute?

2. In a testing structure like this: 
```Python
class Tester:
    def __init__():
        # setup stuff

    def run_test(a, b):
        local_variable = 10
        # call fixture
        custom_fixture(local_variable)
        assert a==b

class BaseTS:
    def setup_class(cls):
        cls.tester = Tester()

class TS(BaseTs):
    def test_case_01(self):
        self.tester.run_test(a='1', b='2')
    def test_case_02(self):
        self.tester.run_test(a='2', b='2')
```
How can I pass the `custom_fixture` to the `run_test` method?
Thanks in advance

**Comment by RonnyPfannschmidt** [comment]
the report is not directly available in fixtures, instead you should attach data to the item and pass it on via a make-report hook/hookwrapper

**Comment by fontealpina** [comment]
I report the solution that I have adopted, maybe will be helpful to other people.  
Basically my test structure is like layered as shown above, and to me it was a bit hard to apply fixture as you proposed (maybe my lack of knowledge). 
So I adopted a solution based on: 
http://stackoverflow.com/questions/10754970/in-which-py-test-callout-can-i-find-both-item-and-report-data
basically adding a plugin like: 
```python
@pytest.mark.tryfirst
def pytest_runtest_makereport(item, call, __multicall__):
    rep = __multicall__.execute()
    # your code follows and you can use rep.passed etc.
    return rep
```
In the `run_test` method I set the variable, e.g. `self.my_var = 'foo'`
By inspecting the `item` object is possible to get the variable value from the `Tester` class and set it in the `rep` object.
After that, it will be possible to use the rep parameter in my customized xml and resultlog plugins.
Maybe it is a bit tricky but for the moment seems to work in my project.

**Comment by RonnyPfannschmidt** [comment]
note that `__multicall__` is deprecated and will very likely be removed in pytest 3.0

**Comment by fontealpina** [comment]
this is a bad news.
So there will be an alternative solution to do this work, without using fixture?
I think generally would be useful have something like an hook that allows to get info from `item` object and attach to `report` object.

**Comment by nicoddemus** [comment]
It is deprecated in prol of [hookwrapper](https://pytest.org/latest/writing_plugins.html#hookwrapper-executing-around-other-hooks) :wink::

```python
@pytest.hookwrapper(tryfirst=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    rep = outcome.get_result()
    # your code follows and you can use rep.passed etc.
```

**Comment by fontealpina** [comment]
This sounds very good.
I tested it, and just to be precise, I think the proper decorator syntax should be:
`@pytest.hookimpl(hookwrapper=True, tryfirst=True)`
instead of
`@pytest.hookwrapper(tryfirst=True)`
Right?

**Comment by nicoddemus** [comment]
Oops you're absolutely right; sorry, wrote from memory without checking properly. :grin:
