### ISSUE TITLE
Sharing data between test\fixtures

### ISSUE THREAD

**Issue by Ignalion** [pytest-dev/pytest#1571]
Hi, guys.

I'd like to ask a couple of questions. Would you mind?

First thing first.
We're decided to move our tests to some framework other than python's defaul unittest.TestCase because obviously it's horrible. Fortunately, we have both the time and an inspiration to do this (of course, for new tests only).

So, without any other posisble alternative we've chosen pytest to do the job as pure functional framework without any boilerplate like setUp and state inside class instance.

However, there are a couple of things that seem to be undoable with current realization of pytest.

Let's say we have three fixtures. They sure enough do some very important job but besides that they share single data that is producing (partially) by the test and do smth with this data. Let's say they return it to db\post to rabbitMQ or send it to CI.
The question is (really, there's a couple of them).
Is there a way to return to the yield_fixture a value? (regarding to the code, there is not)

For a moment, I have some code like this:

```
@pytest.yield_fixture
def fixture_1():
    data = create_some_data()
    yield data
    data.send_to_CI
```

and test like:

```
@pytest.mark.usefixtures('fixture_1')
def test_1(fixture_1):
    fixture_1.useful_data.update({'some_test_value': some_value}
```

It works (actually, brings all the cons from mutable data) however it works only for one fixture.
If the same data (kind of test result) also is needed to be used by other fixture that would write it to DB, I don't see any way to do it.

Maybe, you have any suggestions regarding the question? Any help would be appreciated.

**Comment by RonnyPfannschmidt** [comment]
uhm you would do `fixture1.update(...)` and you wouldnt need the `usefixtures` mark

and as for common usage, you would make a fixture for the common data, and the other fixtures would use it

could you help us understand how the documentation made it hard to arrive at that (because we are so used to the framework that we might be missing a few places where hints for new users are needed)

**Comment by nicoddemus** [comment]
> It works (actually, brings all the cons from mutable data) however it works only for one fixture.

Actually it should works for multiple fixtures, they all just have to receive the same "data" fixture.

```python
@pytest.yield_fixture
def data():
    data = create_some_data()
    yield data
    data.send_to_CI()

@pytest.yield_fixture
def processor(data):
    yield Processor(data)

@pytest.yield_fixture
def solver(data):
    solver = Solver(data)
    yield solver
    solver.cleanup()

def test_1(solver, processor, data):
    data.read_input_from_file('/some_file')
    processor.pre_process()  # mutates data
    solver.solve()  # mutates data again
    preprocessor.post_process()  # mutates data yet again
    assert data.success
```

Here I took the liberty of using some abstractions to make the example make some sense, hope it does.

**Comment by Ignalion** [comment]
@nicoddemus Thanks! That would work, I think.
As I understand it, there is no way to return value back to fixture (actually, it could be implemented by making coroutine fixture, similar to yield_fixture).
So, I think, updating data instance from fixture in test should do the job. Still, it doesn't bring much consistance but it should work, thanks.

**Comment by RonnyPfannschmidt** [comment]
fixtures are not co-processes on their own, just return a object implementing an api

**Comment by Ignalion** [comment]
@RonnyPfannschmidt It isn't about documentation, it is more likely about best practices and use cases. Any search attempt by any pattern using 'pytest' and 'fixture' in search query leads to the https://pytest.org/latest/fixture.html page that doesn't help much either.
However, I believe, it's the matter of practice and time to achieve. Or maybe nobody writing tests in fact and when they say they do, they're just lying :)

**Comment by RonnyPfannschmidt** [comment]
hmm, https://pytest.org/latest/fixture.html#modularity-using-fixtures-from-a-fixture-function outlines what we told you

**Comment by Ignalion** [comment]
Thank you very much for your answers.
Sorry about misunderstanding with documentation, everything seems to work, I'm closing this one.
