### ISSUE TITLE
Making _CallOutcome.result private in 3.0

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1572]
I propose to rename `pluggy._CallOutcome.result` to `_result` with pytest 3.0. It seems to be a common mistake to use `.result` instead of `get_result()`:
- https://github.com/pytest-dev/pytest-qt/issues/98
- https://github.com/rvprasad/pytest-finer-verdicts/issues/1

If there was an exception in the wrapped hook, the `result` attribute will [not exist at all](https://github.com/pytest-dev/pytest/blob/master/_pytest/vendored_packages/pluggy.py#L262-L266), which will cause an `AttributeError` which hides the exception which actually happened.

To avoid that mistake, I think it'd be better to only use the attribute internally and only provide `get_result` as external API.

**Comment by RonnyPfannschmidt** [comment]
please report against pluggy

i think we could get by by creating a non-data descriptor that raises the actual exception from the actual traceback when used

(non-data descriptors get only triggered if the instance does not have an attribute of the same name)

**Comment by The-Compiler** [comment]
I reported it here because it'll be a backwards compatibility break in pytest and mainly affect pytest code and users :wink:

I guess that'd work as well, but it strikes me as quite weird that an attribute access would raise a (non-AttributeError) exception.

**Comment by RonnyPfannschmidt** [comment]
i think a nice way to solve this is to make `get_result` use `_result` and to have result as a alias property for `get_result`

**Comment by nicoddemus** [comment]
I like @RonnyPfannschmidt's idea. :grin: 

I also have been bitten by this issue myself.

**Comment by nicoddemus** [comment]
This has been changed already on `pluggy`, but will become again a read-only property that calls `get_result()` under the covers in pytest-dev/pluggy#88.
