### ISSUE TITLE
doc/en/example/pythoncollection.rst uses multiple python versions in regendoc examples

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1573]
thats pretty much unsupported :(

**Comment by RonnyPfannschmidt** [comment]
@omarkohl bisect got me to bdb3581a52f018a489abca0 - do you recall how you created the example output back then

i'll fix it by using `#` instead of `$` for the upcoming release (so its no longer checked/replaced with regendoc)
but i feel we might want a solution with multi python version regendoc as a followup

**Comment by omarkohl** [comment]
@RonnyPfannschmidt I created the example output by creating the files on my PC (running Ubuntu 15.10) and executing the tests with Python 2.7 and Python 3.4 ...

**Comment by omarkohl** [comment]
> but i feel we might want a solution with multi python version regendoc as a followup

sound like a good idea :-)

**Comment by RonnyPfannschmidt** [comment]
@omarkohl thanks for the update - i will take a look at the details

**Comment by nicoddemus** [comment]
Closing as I don't see this example in the docs anymore.
