### ISSUE TITLE
auto-upload documentation from travis

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1576]
in order to automatically keep the documentation up2date, we should always build it in one travis job, that will also rsync it to the server for tags

in order to handle credentials it we have the following options

* need to travis encrypt a new ssh keypair and deploy the pubkey to the server
* ask travis to sponsor a pro account that allows to use ssh keys

in either case we need to deploy rrsync on the repo as a way to prevent rsync from too much access

**Comment by nicoddemus** [comment]
I thought our plan was to ditch our documentation at all eventually and start using http://pytest.readthedocs.io, no?

**Comment by The-Compiler** [comment]
Using RTD definitely would be the easier solution :wink:

**Comment by RonnyPfannschmidt** [comment]
rtd cant do a regendoc run before the sphinx build

**Comment by nicoddemus** [comment]
> rtd cant do a regendoc run before the sphinx build

True, but that doesn't completely prevents us from using RTD... it takes care of all else you mentioned in the issue. Plus RTD is already working, we really only need to implement the proper redirection in the `pytest.org` server.

We could automate running regendoc on Travis, but TBH having that as part of the PR for the release seems OK for now. We could certainly improve this later by making Travis run regendoc and pushing that automatically.

**Comment by RonnyPfannschmidt** [comment]
agreed

**Comment by nicoddemus** [comment]
Great!

Just to reiterate my request on the mailing list, I really would like for someone with Linux and some server admin to implement the redirect on pytest.org... :worried:

**Comment by The-Compiler** [comment]
> Just to reiterate my request on the mailing list, I really would like for someone with Linux and some server admin to implement the redirect on pytest.org...

I have access to the server, but it's been years since I last configured an Apache server - I suggest we look at it with @hpk42 at the sprint.

**Comment by RonnyPfannschmidt** [comment]
i also see myself unable to fix the webserver
plus i think we should take a look at changing the domain setup instead of the webserver setup?

**Comment by nicoddemus** [comment]
> I have access to the server, but it's been years since I last configured an Apache server - I suggest we look at it with @hpk42 at the sprint.

Agreed.

> plus i think we should take a look at changing the domain setup instead of the webserver setup?

IIUC we have to configure the webserver to also redirect pytest.org/latest to pytest.readthedocs.io to keep existing links from breaking, and enable google to now index the new location.
