### ISSUE TITLE
doctest marks readme files without doctests as skipped.

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#1578]
Here's the issue, https://travis-ci.org/graingert/dockhand/jobs/134400724#L202

on these files: https://github.com/graingert/dockhand/tree/69be7c180e67407aca462b899ff1259b3e09f080

**Comment by RonnyPfannschmidt** [comment]
i think this is related to the stdlib doctest limits, i'm not sure how easy a fix is, i hope someone else will take a look

**Comment by graingert** [comment]
found the issue working on a fix now

**Comment by graingert** [comment]
it's a ∀ x: P(x) ↛ ∃ x: P(x) issue

**Comment by RonnyPfannschmidt** [comment]
can you explain that for a non-mathematican?

**Comment by graingert** [comment]
All does not imply exists
