### ISSUE TITLE
Order of fixture finalization

### ISSUE THREAD

**Issue by Ignalion** [pytest-dev/pytest#1581]
Hi guys.

Have a little question.

Let's say I have two fixtures:

```
@pytest.yield_fixture
def fixture_a():
    a = create_some_data()
    yield a
    del a
```

```
@pytest.yield_fixture
def fixture_b(fixture_a):
    fixture_a.some_other_things()
    yield
    fixture_a.some_very_other_things()
```

Clearly, I want fixture_b run after fixture_a because it uses it's data.
But if I want to do some cleanup work in fixture_a, is it guaranteed that fixture_b finalization would run BEFORE fixture_a one?

**Comment by The-Compiler** [comment]
Maybe someone knows a definitive answer - I don't know and I didn't check, but that's very much the behaviour I'd expect.

**Comment by RonnyPfannschmidt** [comment]
Use print?

**Comment by nicoddemus** [comment]
You can pass `-s` to py.test to disable output capturing. This makes it easy to test this kind of thing:

```python
import pytest

@pytest.yield_fixture
def fixture_a():
    print('setup a')
    yield
    print('teardown a')

@pytest.yield_fixture
def fixture_b(fixture_a):
    print('setup b')
    yield
    print('teardown b')


def test_foo(fixture_b):
    print
```

```
$ py.test -s
...
collected 1 items

foo.py setup a
setup b

.teardown b
teardown a
```

**Comment by Ignalion** [comment]
@nicoddemus yeah, it seems to work that way.
I'd like to have confirmation that it is the designed behaviour actually, that's it.
Like I can be sure that it'll always work that way

**Comment by nicoddemus** [comment]
Yes, it is by design, fixtures are meant to be used as reusable resources so their setup/teardown must be ordered correctly. :grin:

**Comment by Ignalion** [comment]
@nicoddemus Thanks, that's all needed to know:)
