### ISSUE TITLE
Proposal to expand fixtures

### ISSUE THREAD

**Issue by vodik** [pytest-dev/pytest#1588]
Hey, so this is something I have some interest in hacking on, and wondering if there's any interest in inclusion and/or if other people are already working towards this.

Internally, at my workplace, we "abuse" pytest for functional testing. Its been as wonderful of a framework for that as it has been for unit testing. To support this, we've been writing various plugins and custom test types. However, I can't seem to make fixtures as equally flexible.

Looking under the hook, it looks like fixtures are more focused and somewhat coupled with how tests are written. There is an assumption that fixture names will come from the introspect library (sorry if things have changed - at least that's how it was last time I looked).

What I want to work on:
- Add an API that tests can override to provide a list of interested fixtures. So, for example, in the yaml test example those tests could still use fixtures (maybe this is possible and its eluded me. I'm also aware its probably not desirable for those tests, but its just an example).
- Collect fixtures the same way that tests are collected and generated

And with that last point, it opens the door for experimenting with different ways of providing fixtures, just like pytest has different ways of expressing tests. Where this would be useful in my line of work is we have these repeating patterns like this over and over again:

``` python
@pytest.fixture
def configure_machine_under_test(remote, some_other_fixture):
    "simplified example"
    requests.put(remote + '/...', data={'token': some_other_fixture, ...})
    yield some_data_based_from_data
    requests.delete(...)
```

And it would be really interesting if I could have the power to remove boilerplate:

``` python
configure_machine_under_test = config_fixture(foo='bar')

def test_machine(configure_machine_under_test):
    # ...
```

I have found ways to do this, but in practice they've been hacky, fragile, and/or break when these custom fixtures need to depend on each other. Generalizing the system would be a great boon for me.

Thanks again!

**Comment by The-Compiler** [comment]
I wonder if something like this also would help [pytest-bdd](https://github.com/pytest-dev/pytest-bdd) as I think it also needs to do quite some magic to provide custom fixtures?

cc @olegpidsadnyi @bubenkoff

**Comment by bubenkoff** [comment]
@The-Compiler definitely pytest-bdd will benefit if there will be a way to register fixtures dynamically

**Comment by vodik** [comment]
Yeah, so I posted this while I was at pycon and then been slammed with personal life. Is there any development on this? Or free to just dive right in?

**Comment by Zac-HD** [comment]
Closing this inactive proposal, because fixtures are already complex enough to cause a range of subtle (and unsubtle) problems and we don't want to complicate them further.
