### ISSUE TITLE
Failed to generate junit.xml after importing sure

### ISSUE THREAD

**Issue by timofurrer** [pytest-dev/pytest#1589]
I'm not sure if this is a bug in *pytest* or *sure*. However, some of you might be able to give me hint to solve this problem. 
There is also an issue at https://github.com/gabrielfalcao/sure/issues/74

## Good case

When generating a `junit.xml` with `py.test test_demo.py --junit-xml=junit.xml` where as `test_demo.py` contains the following simple test everything works as expected:

```python
def test_demo():
    assert True
```

## Bad case

When I `import sure` in this file the generation of the `junit.xml` does not work properly anymore.
The `junit.xml` will contain the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
    <testsuite errors="0" failures="0" name="pytest" skips="0" tests="0" time="0.023">
        <testcase time="0.00041389465332">
    </testcase>
</testsuite>
```

You can see that the `testcase` is missing important information.

The test looked like this:

```python
import sure
def test_demo():
    assert True
```

### pip list
```
funcsigs (1.0.2)
mock (2.0.0)
pbr (1.10.0)
pip (8.1.2)
py (1.4.31)
pytest (2.9.2)
setuptools (22.0.5)
six (1.10.0)
sure (1.2.24)
wheel (0.29.0)
```

Operating system is Ubuntu 16.04.
Using cpython 2.7 but same issue in cpython 3.5

### pytestdebug log

The `pytestdebug.log` can be found here:
https://gist.github.com/timofurrer/c563cf226d763783faca8137ce6a90b7

**Comment by RonnyPfannschmidt** [comment]
sure does patch builtins with ctypes, that is pretty much a "evil" hack, unless they show its a mistake in pytest i'm inclined to think its the fault of sure

**Comment by timofurrer** [comment]
This is fixed in [sure](https://github.com/gabrielfalcao/sure) **1.4.0**.
