### ISSUE TITLE
Fixture with this same scope "module"

### ISSUE THREAD

**Issue by wasikadam** [pytest-dev/pytest#1590]
Hi.
I have question about fixture with this same scope "module". This is my example:

```
import pytest

class A:
    pass

@pytest.fixture(scope = "module", params = ["one1", "two1"])
def fixture1():
    return A()


@pytest.fixture(scope = "module", params = ["one2", "two2"])
def fixture2():
    return A()


def  test_a(fixture1, fixture2):
    print("1: ", fixture1)
    print("2: ", fixture2)

```

When I run test the result is:
- test_a[one1-one2]: 

```
1:  <test_a.A object at 0x02E4BC10>
2:  <test_a.A object at 0x02E4BC30>
```
- test_a[one1-two2]:

```
1:  <test_a.A object at 0x02E4BC10>
2:  <test_a.A object at 0x02E4BB50>
```
- test_a[two1-two2]:

```
1:  <test_a.A object at 0x02E4B430>
2:  <test_a.A object at 0x02E4BB50>
```
- test_a[two1-one2]:

```
1:  <test_a.A object at 0x02E4B430>
2:  <test_a.A object at 0x02E4BD50>
```

Why in result test "test_a[two1-one2]" and "test_a[one1-one2]" object for "one2" is different ("test_a.A object at 0x02E4BC30" and "test_a.A object at 0x02E4BD50")? Fixture2 have scope "module"?

**Comment by sallner** [comment]
Hi, 
as you use parametrized fixtures here and, therefore, the module scope is not that easily satisfied in the way you might think. During the sprint, we  implemented new cli flags which should make this debugging clearer (`--setup-only` and `--setup-plan`) They show the actual setup and teardown of fixtures in the testrun. Applying that to your example above results in:
```  
  SETUP    M fixture1[one1]
  SETUP    M fixture2[one2]
        test_me.py::test_a[one1-one2] (fixtures used: fixture1, fixture2)
  TEARDOWN M fixture1[one1]
  SETUP    M fixture1[two1]
  TEARDOWN M fixture2[one2]
  SETUP    M fixture2[one2]
        test_me.py::test_a[two1-one2] (fixtures used: fixture1, fixture2)
  TEARDOWN M fixture1[two1]
  SETUP    M fixture1[two1]
  TEARDOWN M fixture2[one2]
  SETUP    M fixture2[two2]
        test_me.py::test_a[two1-two2] (fixtures used: fixture1, fixture2)
  TEARDOWN M fixture1[two1]
  SETUP    M fixture1[one1]
  TEARDOWN M fixture2[two2]
  SETUP    M fixture2[two2]
        test_me.py::test_a[one1-two2] (fixtures used: fixture1, fixture2)
  TEARDOWN M fixture2[two2]
  TEARDOWN M fixture1[one1]

```

As a fixture can only have one cached result at a time, `one2` in your case is being created first, then torn down while keeping `one1` the same and then later reevaluated in the scope of the `two1`.

Do you have further questions on that issue, or can it be closed?
