### ISSUE TITLE
Printing assert statement with Function call 

### ISSUE THREAD

**Issue by cksagni91** [pytest-dev/pytest#1592]
We are reading the exception output of Pytest using hooks. 
The issue we are facing is that if function call in assert statement returns False, then it gives back the function statement itself

PyTest Version : 2.9.2
OS : Windows 8 - 64bit

Code :

```
def check_even(number):
    if number%2==0:
        return True
    else:
        return False
```
Testcases :
```
def test_check_even1():
    assert check_even(2) == False
    
def test_check_even2():
    assert check_even(3) == True
```

Output:

```
test_sol.py FF

================================== FAILURES ===================================
______________________________ test_check_even1 _______________________________

    def test_check_even1():
>       assert check_even(2) == False
E       assert True == False
E        +  where True = check_even(2)

test_sol.py:5: AssertionError
______________________________ test_check_even2 _______________________________

    def test_check_even2():
>       assert check_even(3) == True
E       assert check_even(3) == True

test_sol.py:8: AssertionError
========================== 2 failed in 0.08 seconds ===========================
```

As it can be seen, for the testcase test_check_even2, the error report is returned with 
**function_call == expected output** [check_even(3) == True] , rather than
 **return_value_of_function  == expected_output** [ False == True ]

This issue occurs only if the **function returns FALSE.**

**Comment by nicoddemus** [comment]
Thanks for the report!

**Comment by sallner** [comment]
Hi @cksagni91,

I think the main idea was to return `assert check_even(3)` to show the 'False' assert instead of rewriting the function completely. But you are right, that if it is compared to some value, the rewriting should be done. 

I am working on a fix and am almost done with it, so a PR will follow in the next days. There are good chances that this comes in the next release.

**Comment by sallner** [comment]
@nicoddemus, @hpk42 
it seems that is is rather complex to find exactly the conditions under which the rewrite is done as intended. 
in case of 
```
assert check_even(3) 
assert check_even(3)  and check_even(3)
```
there seems to be the intention to do no rewrite, but for the following:

```
assert check_even(3) == True
assert check_even(3) is True
assert check_even(3) > True
assert check_even(3) > 5
assert check_even(3) => True
```
and maybe other cases, it is not so easy to find a rule to rewrite it. 

So again the question, do we want to change the rewrite in a way @cksagni91 suggested?

**Comment by sallner** [comment]
As it seems, the `collapse_false()` was removed completely (PR #1654) and this should also solve this issue. Can be closed now. @nicoddemus
