### ISSUE TITLE
Get marker list of an item

### ISSUE THREAD

**Issue by fontealpina** [pytest-dev/pytest#1603]
Is there a way to get the list of markers assigned to an item?
I know that is possible to check it by marker name, like:
```python
def pytest_runtest_setup(item):
    g = item.get_marker("foo")
```
in this case I have to know the name "foo", 
but what if I want to get the list of all the markers of the item?
Thanks

**Comment by RonnyPfannschmidt** [comment]
all non-boolean elements in `item.keywords`

**Comment by fontealpina** [comment]
right, it works with something like:  
```python
def pytest_runtest_setup(item):
   for i in list(item.keywords):        
       if not item.keywords[i] in [True, False]:
           print i
```
Thanks
