### ISSUE TITLE
Accept multiple -m and -k marks

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1608]
I have the need more than once for pytest to understand multiple `-m` and `-k` options, so:

```
py.test -m serial -m slow
```

Would collect _both_ tests with `serial` and `slow` marks.

**Comment by crazymerlyn** [comment]
@nicoddemus Was this issue created before `py.test -m 'serial or slow'` was possible or is it something you would prefer over the current options?

**Comment by RonnyPfannschmidt** [comment]
@crazymerlyn i beleive the intent is to make them lists over values

**Comment by nicoddemus** [comment]
Hmm it might have been a brainfart on my part, `serial or slow` was probably my intent when writing this issue.

> i beleive the intent is to make them lists over values

What do you mean @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus as far as i understood/remember the -m options override each other

**Comment by nicoddemus** [comment]
Yeah, I think only the last `m` option is considered. But given that `serial or slow` works, I think it enough for the original purposes that led me to write this issue in the first place, so I'm closing this.

Thanks everyone for bringing this up to attention again. 👍
