### ISSUE TITLE
Drop duplicated tests by default

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1609]
`py.test` will happily run the same tests more than once if you provide multiple path arguments which contain the same test files:

```
py.test model/tests model
```

This will execute all tests from `model/tests` twice.

While there are some edge use cases where this useful (#1187), it seems in general users are confounded by this behavior more than delighted it exists (#1607).

I think we should discuss if we should drop duplicated tests by default, perhaps introducing a new `--keep-duplicates` *if* we want to preserve the old behavior.

**EDIT**: if we decide to keep running duplicated tests, we should at least document the behavior (see [comment](https://github.com/pytest-dev/pytest/issues/1607#issuecomment-225863482)), possibly mentioning [pytest-drop-dup-tests](https://pypi.python.org/pypi/pytest-drop-dup-tests) as a workaround.

**Comment by RonnyPfannschmidt** [comment]
i#d be happy to see this removed as well,
note that this will break a number of plugins doing alternative collection due to duplicate node-ids
it would also allow us to turn back on the pytest-xdist implementation detail that uses collection index instead of nodeid
