### ISSUE TITLE
Rename getfuncargvalue to getfixturevalue

### ISSUE THREAD

**Issue by tomviner** [pytest-dev/pytest#1625]
`getfuncargvalue` will be deprecated but will still be supported for the moment.

As @hpk42 mentioned this morning, this is independent of replacing / removing this feature.

**Comment by tomviner** [comment]
Fixed by https://github.com/pytest-dev/pytest/pull/1626 Please close @nicoddemus 

(I'll do the magic commit message that closes issues next time)

**Comment by RonnyPfannschmidt** [comment]
thanks
