### ISSUE TITLE
Drop Python 3.0/3.1/3.2/2.6?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1627]
After talking to some people at the sprint I'd like to propose dropping older Python versions in pytest 3.0.

In other issues we commonly told people we'll drop things when pip does, so we could safely drop 3.0/3.1/3.2 with pytest 3.0.

Looking at https://github.com/pypa/pip/issues/3796 3.2 usage on PyPI is 0.03% (pip8) or 0.08% (earlier pip versions), so I think we should drop <= 3.2. Other testing related tools like coverage.py and various pytest plugins did so as well already.

As for 2.6, it's more commonly used, and still what people on e.g. CentOS are stuck with, so I'd rather not drop it before pip does (also because that's kind of what we promised to various people).

**Comment by nicoddemus** [comment]
Regarding Python 3: we already only support 3.3 onwards, if I'm not mistaken. Actually, on `tox` we only test 3.3 onwards, but our `setup.py` still declares 3.2 support, so we should fix that.

About Python 2.6, I agree.

**Comment by The-Compiler** [comment]
We should also make sure to adjust the docs accordingly - for example, pytest.org still says "Python 2.6-3.5" which IMHO includes 3.0-3.3.

**Comment by RonnyPfannschmidt** [comment]
We also have strange support code around

**Comment by The-Compiler** [comment]
@RonnyPfannschmidt should this be closed or is there still code left we can get rid of before dropping 2.6?

**Comment by RonnyPfannschmidt** [comment]
there is code for python 2.4 assert statement range, that in part relates to a python 2.5/2.6 issue as well,
atm i suggest keeping until python 2.6 removal

**Comment by The-Compiler** [comment]
Closing this then.
