### ISSUE TITLE
Introduce pytest command as recommended entry point

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest#1629]
It should be possible to run pytest using `pytest` command in addition to the existing `py.test`. This resolves a naming confusion that has existed for many years.

Explanation of py.test vs pytest from FAQ:
> Some of the reasons are historic, others are practical. ``pytest`` used to be part of the ``py`` package which provided several developer utilities, all starting with ``py.<TAB>``, thus providing nice TAB-completion. If you install ``pip install pycmd`` you get these tools from a separate package. These days the command line tool could be called ``pytest`` but since many people have gotten used to the old name and there is another tool named “pytest” we just decided to stick with ``py.test`` for now.

The issue with the 'other tool' has been resolved for some time now, so from pytest 3.0 we will supported and recommend use of `pytest` as the main command instead of `py.test`. It's possible that in future we will deprecate `py.test` and potentially even remove it.

**Comment by davehunt** [comment]
This was fixed in https://github.com/pytest-dev/pytest/commit/ef9dd1496384cb703bf31a0788ea77bc4184faac

**Comment by swiesend** [comment]
Shoud the `py.test` still be around in pytest-3.0.2? Or shouldn't it be better behave like `pytest`?

I ran into this...
http://stackoverflow.com/questions/39495429/py-test-vs-pytest-command

**Comment by The-Compiler** [comment]
It should still be around (for backwards-compatibility), and it should behave the same - I answered on StackOverflow.
