### ISSUE TITLE
Remove py.test* commands as entry points

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest#1632]
For historical reasons we have ``py.test`` as a valid entry point. We also have entry points for ``pytest-jython``, ``py.test-pypy*``, and ``py.test-X.X``, which were introduced before the convenience of virtual environments for managing multiple environments.

Explanation of py.test vs pytest from FAQ:
> Some of the reasons are historic, others are practical. ``pytest`` used to be part of the ``py`` package which provided several developer utilities, all starting with ``py.<TAB>``, thus providing nice TAB-completion. If you install ``pip install pycmd`` you get these tools from a separate package. These days the command line tool could be called ``pytest`` but since many people have gotten used to the old name and there is another tool named “pytest” we just decided to stick with ``py.test`` for now.

We will be introducing ``pytest`` as the recommended command entry point in #1629, which is expected to be included in pytest 3.0. Once we have lived with this for some time (until 3.1?) we should deprecate or remove the various ``py.test`` entry points.

**Comment by nicoddemus** [comment]
Actually I'm not sure if we should remove `py.test` commands anytime soon, but of course I'm in favor of adding `pytest` entry points. :grin:

**Comment by RonnyPfannschmidt** [comment]
i think we should remove all entrypoints that are not `pytest` and `py.test`

**Comment by nicoddemus** [comment]
Fixed in #1662
