### ISSUE TITLE
Allow users to explicitly specify the path of the root directory

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest#1642]
The root directory discovery is convoluted, and there are cases where it fails to resolve to a suitable path. We should improve the discovery as much as possible, but it also makes sense to provide a way for users to explicitly specify the root directory.

We could add a `--rootdir` command line option, which would be relative to the invocation directory. We could also add a `rootdir` configuration key, which would override the command line option, and would be relative to the configuration file.

**Comment by The-Compiler** [comment]
Didn't someone work on this during the sprint? Also, while this is a nice feature, it shouldn't block 3.0. Changing the milestone to 3.1 for now.

**Comment by feuillemorte** [comment]
I take it

**Comment by nicoddemus** [comment]
@feuillemorte awesome, let us know if you hit any roadblock. 👍

**Comment by feuillemorte** [comment]
https://github.com/pytest-dev/pytest/pull/3127

All checks have passed

Please review :)

**Comment by feuillemorte** [comment]
Merged
