### ISSUE TITLE
plugins resolved by pip instead of core pytest packages

### ISSUE THREAD

**Issue by asmodehn** [pytest-dev/pytest#1652]
Firstly I am not sure if this is problem of : 

- pytest & plugins design
- pip-8.1.2
- how I use setuptools

But it s quite tricky to figure out what is going wrong, so I though I d post it here first.

Here is the issue : 

```
Installed /home/travis/build/asmodehn/pyros/build/install/lib/python2.7/dist-packages/importlib-1.0.3-py2.7.egg
Searching for pytest-timeout
Reading https://pypi.python.org/simple/pytest-timeout/
Best match: pytest-timeout 1.0.0
Downloading https://pypi.python.org/packages/cf/92/ab29b9baa54d47dfd50e43be35577de9af4e7ebf27d29f546ddeb6c3b6f5/pytest-timeout-1.0.0.tar.gz#md5=f9f162bd079689980b5614673ddfdae4
Processing pytest-timeout-1.0.0.tar.gz
Writing /tmp/easy_install-kn4E4k/pytest-timeout-1.0.0/setup.cfg
Running pytest-timeout-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kn4E4k/pytest-timeout-1.0.0/egg-dist-tmp-wIPOxa
zip_safe flag not set; analyzing archive contents...
Moving pytest_timeout-1.0.0-py2.7.egg to /home/travis/build/asmodehn/pyros/build/install/lib/python2.7/dist-packages
Adding pytest-timeout 1.0.0 to easy-install.pth file
Installed /home/travis/build/asmodehn/pyros/build/install/lib/python2.7/dist-packages/pytest_timeout-1.0.0-py2.7.egg

Searching for pytest
Best match: pytest timeout-1.0.0
Downloading https://pypi.python.org/packages/cf/92/ab29b9baa54d47dfd50e43be35577de9af4e7ebf27d29f546ddeb6c3b6f5/pytest-timeout-1.0.0.tar.gz#md5=f9f162bd079689980b5614673ddfdae4
Processing pytest-timeout-1.0.0.tar.gz
Writing /tmp/easy_install-D8H9iA/pytest-timeout-1.0.0/setup.cfg
Running pytest-timeout-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-D8H9iA/pytest-timeout-1.0.0/egg-dist-tmp-BPZAJW
zip_safe flag not set; analyzing archive contents...
Removing /home/travis/build/asmodehn/pyros/build/install/lib/python2.7/dist-packages/pytest_timeout-1.0.0-py2.7.egg
Moving pytest_timeout-1.0.0-py2.7.egg to /home/travis/build/asmodehn/pyros/build/install/lib/python2.7/dist-packages
pytest-timeout 1.0.0 is already the active version in easy-install.pth
Installed /home/travis/build/asmodehn/pyros/build/install/lib/python2.7/dist-packages/pytest_timeout-1.0.0-py2.7.egg

error: The 'pytest' distribution was not found and is required by pyzmp
```

The full log is available at : https://travis-ci.org/asmodehn/pyros/jobs/139666793

This is _probably_ reproducible by running : 
```
python setup.py build --build-base ./build install --install-layout=deb --prefix=./build/install --install-scripts=./build/install/bin
```
with this package https://github.com/asmodehn/pyros/pull/78/commits/2baf3fd6e9ea9c3da12ff3c6f390fc848fef30d8, that uses this package https://github.com/asmodehn/pyzmp/releases/tag/0.0.10 that itself has pytest and pytest-timeout as a dependency.

**Workaround**
It seems I need to always list pytest after all pytest plugin packages in the dependency list. This triggers the pytest installation first...

**Comment by asmodehn** [comment]
Note this uses a virtualenv and works : https://travis-ci.org/asmodehn/pyros/jobs/139666794
It seems the problem appears only when we are using system + PYTHONPATH setup instead of virtualenv...

**Comment by asmodehn** [comment]
This confirms the workaround works : https://travis-ci.org/asmodehn/pyros/builds/139680687

**Comment by RonnyPfannschmidt** [comment]
This is a setuptools usage misstake

**Comment by RonnyPfannschmidt** [comment]
@asmodehn any updates on this, it still looks to me unrelated to pytest and i'd like to close the issue

**Comment by asmodehn** [comment]
I dont have anything more to report.

I fixed it for me, so feel free to close this, it s probably not a pytest
issue anyway.

But I find it strange that the order of dependencies in setup.py would
matter...

Sadly, I also dont have enough time and setuptools experience to
investigate that issue.
