### ISSUE TITLE
fix marker interaction in a backward incompatible way

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1670]
problem:
markers transfer between subclasses and base classes due to marker trasnfer mutating objects belonging to base classes from subclasses

related issues:
- [ ] #1540
- [ ] #1296 
- [ ] #1111
- [ ] #902 
- [ ] #899 
- [ ] #896
- [ ] #891 
- [ ] #750
- [ ] #719
- [ ] #568 
- [ ] #535
- [ ] #277

**Comment by nicoddemus** [comment]
I'm thinking we want to fix this for 3.0?

**Comment by RonnyPfannschmidt** [comment]
im not sure we can, the more i look into markers and how we use them, the more bugs and edge-cases show up

**Comment by The-Compiler** [comment]
So... is this 4.0 material then?

**Comment by RonnyPfannschmidt** [comment]
fixed in #3317
