### ISSUE TITLE
assertion rewriting should be sensitive of the pytest version

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1671]
currently pytest updates do not trigger recreation of the cached bytecode
we should have the pytest version of part of it

**Comment by nicoddemus** [comment]
Any ideas how to do that @RonnyPfannschmidt? I don't think we can write anything to the byte code (I don't know the format to say that for sure though), do you suggest writing that information in a separate file perhaps?

**Comment by RonnyPfannschmidt** [comment]
we should either add the pytest version to the cache tag in the filename, or make it part of the cached pyc file and recreate on different pytest versions

**Comment by nicoddemus** [comment]
Oh we can control the generated filename? This seems like the correct approach then. 👍

**Comment by asottile** [comment]
marking this one as easy, would just need someone to pick this up

The code hint is here: https://github.com/pytest-dev/pytest/blob/3d01dd3adf56abecfda4b785ef280217b615c527/src/_pytest/assertion/rewrite.py#L25-L38

Though my branch simplifies this a bit so you'll probably want to wait until #5468 lands

**Comment by nicoddemus** [comment]
This would also resolve https://github.com/pytest-dev/pytest/issues/4969 and make `pytest-remove-stale-bytecode` obsolete. 😁 

(cc @sallner)
