### ISSUE TITLE
pytest.org SSL cert expired 26/6/2016

### ISSUE THREAD

**Issue by michaeljoseph** [pytest-dev/pytest#1676]
<img width="483" alt="screen shot 2016-06-26 at 15 43 23" src="https://cloud.githubusercontent.com/assets/169933/16362651/d543c2d8-3bb4-11e6-85d6-f6a8c38f6df6.png">

**Comment by The-Compiler** [comment]
Confirmed - seems like no let's encrypt cronjob is running on the server like it should.

I don't have root access to the server, but I pinged @hpk42 who does.

**Comment by The-Compiler** [comment]
The cert is now up to date again, and letsencrypt/certbot running automated like it should :tada:
