### ISSUE TITLE
document disabling byte-code writing via conftest

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1680]
when developing projects that are subject to change,
its easy to forget to remove stale pyc files,

thus i propose adding a ini option that sets sys.dont_write_bytecode before importing the first conftest

```
[pytest]
dont_write_bytecode = true
```

**Comment by nicoddemus** [comment]
Hey Ronny, in which situations one would get stale `.pyc` files? Python doesn't take care of that automatically?

**Comment by RonnyPfannschmidt** [comment]
delete a module, have a pyc around, imports wont fail

**Comment by nicoddemus** [comment]
Ohhh I see, thanks. 

Couldn't the user just call that at the top of the root contest file?

**Comment by RonnyPfannschmidt** [comment]
experimenting with that now, we might want to document it

**Comment by SanketDG** [comment]
@RonnyPfannschmidt I would be interested in doing this.

Do we want to implement this as a `ini` setting? Or just document it?

**Comment by RonnyPfannschmidt** [comment]
it should be documented for use with conftest
