### ISSUE TITLE
Use a callable to define fixture scoped dynamically

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1682]
Allow `scope` parameter of fixtures to receive a callable instead of a string. When a callable, it will be called with the `config` object (passed as keyword argument) and should return a string, which will determine the scope of the fixture. This function will evaluate only once.

The idea is that developers might be interested to have different scopes for a fixture depending on a command line option, so that one might choose to change a fixture scope to `session` to avoid costly initialization during development, but opt to change it to `function` in a C.I. server.

Suggested by @hpk42

**Comment by RonnyPfannschmidt** [comment]
we should allow this to take the current request as well (so one can be function scoped, and defer module/class scope session for example)

**Comment by nicoddemus** [comment]
The idea was to evaluate the scope function only **once**, in which case the request object would not be useful.

**Comment by RonnyPfannschmidt** [comment]
i see

**Comment by nicoddemus** [comment]
But don't let that stop you from making a suggestion :smile:

**Comment by The-Compiler** [comment]
While this is a nice feature, it shouldn't block 3.0. Changing the milestone to 3.1 for now.

**Comment by itaykatz** [comment]
Is there any workaround for the suggested mechanism (maybe scope changing using pytest_generate_tests() ?

**Comment by rajivgup** [comment]
I still see the status of this issue is open. Is this change committed?

**Comment by nicoddemus** [comment]
> I still see the status of this issue is open. Is this change committed?

It has not been implemented yet if I understood your question correctly (usually when something gets implemented we close the issue with a link to the related PR).

**Comment by nicoddemus** [comment]
@itaykatz 

> Is there any workaround for the suggested mechanism (maybe scope changing using pytest_generate_tests() ?

Not that I'm aware of, I'm afraid.

**Comment by aklajnert** [comment]
@nicoddemus, I wanted to implement this, so I did some research. It seems to conflict with the direct decoration for the fixtures. The scope parameter already can be callable, I assume it is because it is the first argument for the fixture decorator. It allows defining fixture by executing the decorator as a function.  

Any idea how to implement the dynamic scope without breaking the current functionality? Maybe the callable should have a specific name?

**Comment by RonnyPfannschmidt** [comment]
`def fixture(scope="function", params=None, autouse=False, ids=None, name=None):`

should be turned into 
`def fixture(maybe_callable_or_scope=None,* , scope="function", params=None, autouse=False, ids=None, name=None):`

there should be a warning for non-kwarg scope passover it should override while its in transition period

**Comment by NargiT** [comment]
the release notes link for dynamic-scope is broken
expecting https://docs.pytest.org/en/5.2.0/fixture.html#dynamic-scope not https://docs.pytest.org/en/fixture.html/#dynamic-scope

**Comment by asottile** [comment]
here's a fix for that -- thanks @NargiT https://github.com/pytest-dev/pytest/pull/5910

**Comment by asottile** [comment]
closing this out since it landed in 5.2 🎉
