### ISSUE TITLE
Add "advanced fixtures" topic to docs

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1683]
We should add a "advanced topics" chapter to the documentation, possibly:
- Invocation-scoped fixtures (#1681)
- scope defined by a callable (#1682)

**Comment by The-Compiler** [comment]
Since I changed the milestone for #1682 to 3.1 and we have some basic docs for invocation-scoped fixtures, I'm changing the milestone here too.

**Comment by hackebrot** [comment]
Hmm given that the referenced features have yet to be added, I wonder if it makes sense to wait for the according pull requests before we add the section to the docs.

**Comment by nicoddemus** [comment]
I think we can close this given that we are refactoring the entire documentation structure.
