### ISSUE TITLE
Deprecate "pytest_funcarg__" prefix for fixtures

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1684]
Start to issue deprecation warnings when fixtures are declared using this legacy idiom, to be removed at some point later in time.

**Comment by nicoddemus** [comment]
cc @obestwalter

**Comment by nicoddemus** [comment]
Not sure if it's worth, as keeping support for this old form is simple enough too

**Comment by RonnyPfannschmidt** [comment]
i want to see this removed :) it complicates things as its not sanely layered

**Comment by obestwalter** [comment]
It's not explicitly deprecated yet. Shall we add a deprecation warning before 3.0? I just grepped through the code and there are loads of tests using it. Updating those tests to use the fixture decorator would be a nice low hanging fruit task.

**Comment by nicoddemus** [comment]
OK, I think we should introduce a deprecation warning for 3.0 then. Added it to the [Wiki](https://github.com/pytest-dev/pytest/wiki/pytest-3.0-checklist).

**Comment by RonnyPfannschmidt** [comment]
dine in #1714

**Comment by jsn1993** [comment]
For pytest_funcargs__, what is the alternative approach?

**Comment by nicoddemus** [comment]
Just replace this:

```python
def pytest_funcargs__hello():
    ...
```

with:

```python
@pytest.fixture
def hello():
    ...
```

:wink:

**Comment by nickdirienzo** [comment]
@nicoddemus after updating to 3.0.1, I started seeing the warning even though I don't use `pytest_funcarg__` anywhere in my code (I only use new-style fixture decorators). Happy to share more info if needed—and tbh, I haven't dug into why this is popping up for my fixtures.

**Comment by The-Compiler** [comment]
@nickdirienzo Can you show the full, exact warning you get?

**Comment by nickdirienzo** [comment]
@The-Compiler sure:
```
WC1 None pytest_funcarg__cov: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
```

After quickly grepping for `pytest_funcarg__cov`, I learned that it's a fixture in `pytest_cov`'s tests. Whoops. I wonder if it'd be helpful to provide the fully qualified name for the location of the fixture in question?

**Comment by The-Compiler** [comment]
That might be useful indeed - and you should upgrade to pytest-cov 2.3.1 :wink:

**Comment by nickdirienzo** [comment]
Heh, thanks. 😄

**Comment by standage** [comment]
I got this message with pytest_cov installed, even though my project wasn't using it. Upgrading pytest_cov made it go away.
