### ISSUE TITLE
Fixture scope doesn't work when it is parametrized

### ISSUE THREAD

**Issue by bubanoid** [pytest-dev/pytest#1697]
Please look at the following tests

    import pytest

    ind = [0]

    @pytest.fixture(scope="session")
    def fixture_0(request):
        print('\n')
        ind[0] += 1

    @pytest.mark.parametrize('fixture_0', ['smth'], indirect=True)
    def test_1(fixture_0):
        print('test_1:  ind={ind}'.format(ind=ind[0]))

    def test_2(fixture_0):
        print('test_2:  ind={ind}'.format(ind=ind[0]))

and their output:

    test_1:  ind=1
    test_2:  ind=2

however I expected to get the

    test_1:  ind=1
    test_2:  ind=1

I guess it is a bug. This issue is connected to the issue https://github.com/pytest-dev/pytest/issues/634 See also another presentation of this issue: https://bitbucket.org/pytest-dev/pytest/issues/634/metafuncparametrize-overwrites-scope

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell this is exactly related to #634

**Comment by Stranger6667** [comment]
After merging #1766 test above produces the following output:

```
collected 2 items

test_x.py::test_1[smth]

test_1:  ind=1
PASSED
test_x.py::test_2 test_2:  ind=1
PASSED```

So, it is fixed as I see.
