### ISSUE TITLE
pytest.main fails on Windows when path contains whitespace

### ISSUE THREAD

**Issue by Juanlu001** [pytest-dev/pytest#1703]
When invoking pytest from a Python script using `pytest.main` (as recommended in the docs http://pytest.org/latest/usage.html#calling-pytest-from-python-code), the program fails if the path contains whitespace with an error that suggests that it was splitted too soon.

```
C:\Users\me\Development>python -c "import pytest; pytest.main('C:\Program Files')"
============================= test session starts =============================
platform win32 -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: C:\Users\me\Development, inifile:

======================== no tests ran in 0.00 seconds =========================
ERROR: file not found: C:Program
```

Windows 7, both latest Python 2 and 3, py.test 2.9.1.

**Comment by Juanlu001** [comment]
Well, and I understood why just by reading the docs - it's assuming they are separate arguments. I can fix the issue enclosing the path in a list or in surrounding quotes.

Closing this, sorry for the noise!

**Comment by The-Compiler** [comment]
Also note you should use `\\` or a raw string (`r'...'`) for windows paths to make sure the backslash isn't interpreted as an escape.
