### ISSUE TITLE
Syntax Error on a string containing quotation marks

### ISSUE THREAD

**Issue by andsok75** [pytest-dev/pytest#1707]
Running 

    py.test --doctest-modules

in a directory containing a single test.py file with

    """
    >>> a = " x = '\"' "
    """

fails with this error:

    001 
    002 >>> a = " x = '"' "
    UNEXPECTED EXCEPTION: SyntaxError('EOL while scanning string literal', ('<doctest test[0]>', 1, 15, 'a = " x = \'"\' "\n'))
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest test[0]>", line 1
        a = " x = '"' "
                      ^
    SyntaxError: EOL while scanning string literal

Platform: linux2 -- Python 2.7.11+, pytest-2.8.7, py-1.4.31, pluggy-0.3.1, Ubuntu 16.04

**Comment by RonnyPfannschmidt** [comment]
looks like yet another bug of the stdlib doctest module

**Comment by RonnyPfannschmidt** [comment]
after taking a deeper look,
this is a python issue

since the string you put there is not a raw string, python will in fact process escape sequences

thus on order for this to work, either use raw strings, or escape the `\` as `\\`
