### ISSUE TITLE
New main page now that docs reside in doc.pytest.org

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1708]
Now that http://doc.pytest.org is officially up, I propose we change our `pytest.org` landing page. 

pytest.org currently is the same `index` page for the docs, but I see that other projects usually follow a different direction, containing a short project description, a short snippet right at the beginning and proper links to the rest of the documentation, contact, etc etc. I would say pretty much like our current `README`.

Examples:

* http://www.fabfile.org (docs: http://docs.fabfile.org)
* http://flask.pocoo.org (docs: http://jinja.pocoo.org/docs)
* http://jinja.pocoo.org (docs: http://flask.pocoo.org/docs)

In order to do that, we would probably move a few things in `docs`, but I propose to keep `index.rst` as the main *docs* page, and create another `landing-page.rst` or something like this (suggestions welcome), and only it would be uploaded to `pytest.org`, with proper links to http://doc.pytest.org.

I think it would be really nice to have this for 3.0.

cc @pfctdayelise @hackebrot

**Comment by pfctdayelise** [comment]
I think this is a great idea. Some pages like the list of talks/tutorials and the pages on adopt pytest month and the sprint, shouldn't really be part of the docs IMO. Maybe a page on the history of the project and philosophy too (eg prioritising backwards compat).

Should we try to preserve documentation links (eg http://pytest.org/latest/fixture.html#fixture goes to some page about fixtures) or do we accept a one-time mass breaking of links? I'm not sure if you're proposing that the docs are still accessible under pytest.org/ pages, or only docs.pytest.org/

**Comment by nicoddemus** [comment]
>  or do we accept a one-time mass breaking of links?

I think so, unless someone has a solution to avoid this.

>  I'm not sure if you're proposing that the docs are still accessible under pytest.org/ pages, or only docs.pytest.org/

Only through doc.pytest.org, I think. 

Any chance of someone tackling this before 3.0? :grin:

**Comment by The-Compiler** [comment]
I think we really should try having some kind of forward rules in pytest.org's webserver config. Breaking links is really frustrating for people, and we have *a lot* of pages linking to pytest docs I'd imagine.

**Comment by nicoddemus** [comment]
That would be neat... we could redirect every `pytest.org/latest/*` to `doc.pytest.org/latest/*`. Do you know how to do it @The-Compiler? I'm sure @hpk42 would give you access to configure this. :grin:

**Comment by hackebrot** [comment]
I think this is a great idea and goes well with our overall concept for the documentation.

I'd prefer if we refer to the documentation as ``http://docs.pytest.org/`` rather than doc. Seems to be the more common term (and I like it better than *doc*). 😄 

That's also how I will refer to it during my talk and both ``docs`` and ``doc`` already work from a technical standpoint.

**Comment by hackebrot** [comment]
FYI: I personally won't be able to contribute much to the docs reorganization at this point, as I am busy with my presentation. 😿

**Comment by nicoddemus** [comment]
Oh I didn't know both doc and docs worked... I agree, personally I also like "docs" better.

**Comment by The-Compiler** [comment]
> That would be neat... we could redirect every `pytest.org/latest/*` to `doc.pytest.org/latest/*`. Do you know how to do it @The-Compiler? I'm sure @hpk42 would give you access to configure this. :grin: 

Depends on the webserver used (Apache, I think?). For Apache I did it some years ago, I guess I could figure it out.

**Comment by nicoddemus** [comment]
It should be simple for someone who has done it before. Would you mind ask @hpk42 to give you access on signal or by email? I'm not sure Holger is getting notifications from GH.

**Comment by The-Compiler** [comment]
done

**Comment by nicoddemus** [comment]
Thanks! Just a note: the redirect must be from http://pytest.org/latest to http://docs.pytest.org/en/latest.

**Comment by The-Compiler** [comment]
@hpk42 added the redirect, seems to work fine! :+1:

**Comment by nicoddemus** [comment]
Awesome! :grin:
