### ISSUE TITLE
No reference documentation?

### ISSUE THREAD

**Issue by darkfeline** [pytest-dev/pytest#1713]
pytest has no reference documentation (as far as I can tell).  This is problematic, because while the documentation tells me pytest's basic usage, I have no idea what anything actually does.

Even something as simple as `pytest.fixture` is undocumented.  What does it do?  What arguments does it take?  What, specifically, do `scope='function'`, `scope='class'`, and `scope='session'` do?

It's quite possible however that I simply haven't _found_ the documentation, as silly as that sounds.  Consider for example [this page](http://pytest.org/latest/mark.html), which doesn't seem to be linked from anywhere and hence isn't included in the PDF documentation either.  Perhaps there's some reference documentation hidden in the pytest Deep web that I'm missing?

**Comment by The-Compiler** [comment]
We're aware the current documentation structure is suboptimal, and we're trying to come up with something better soon for pytest 3.0.

FWIW, you can find the documentation for `pytest.fixture` here:
http://pytest.org/latest/builtin.html#_pytest.python.fixture
http://pytest.org/latest/fixture.html
