### ISSUE TITLE
Deprecate support for passing command-line as string to pytest.main()

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1723]
As discussed in #1706.

I think a deprecation warning in 3.0 is the way to go.

**Comment by H0R5E** [comment]
Hi this has cause a warning to appear when following the "Manual Integration" section of the Good Integration Practices page. Can you advise?

http://doc.pytest.org/en/latest/goodpractices.html

**Comment by H0R5E** [comment]
The warning is:

`WC1 None passing a string to pytest.main() is deprecated, pass a list of arguments instead.`

**Comment by nicoddemus** [comment]
@H0R5E this is a left-over in the documentation, passing a string to `pytest.main()` is deprecated.

Updating the docs in #2017, thanks for the pointer.
