### ISSUE TITLE
Interpreter crashes on exit if things are printing

### ISSUE THREAD

**Issue by gappleto97** [pytest-dev/pytest#1725]
When things are actively printing on pytest exit, and there are locks involved in the method of printing, the interpreter crashes. I can semi-consistently replicate this on win8.1 using python 3.5.1 and pytest 2.9.2. It also is using the plugin cov (2.2.1), but this error occurs without it as well.

When pytest exits while code is printing, it crashes the interpreter, throwing `Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads`.

A fairly minimal example to replicate this would be [file](http://pastebin.com/aPB7AVbZ), [test](http://pastebin.com/06sX9T3d). It's not quite minimal, as it maintains some style elements from my actual code, but I wanted these elements to remain because they're an important part of the object model I've been using.

**Comment by gappleto97** [comment]
I cannot replicate this in python 2.7, nor can I replicate it in the interpreter of either version, whether by defining in the interpreter, or defining via import.

**Comment by gappleto97** [comment]
This also works for RLocks and Semaphores, though I don't see any reason why it wouldn't have.

**Comment by gappleto97** [comment]
The lowest value I can replicate this at is 29 nodes, though it happens significantly less often. I haven't yet replicated it anything below this, though it may happen on weaker systems.

I'm actively working to replicate it on lower values, but I recommend using the high value on pastebin for reliable replication.

**Comment by nicoddemus** [comment]
@gappleto97 this is a very old issue, is this still an issue or can we close this?
