### ISSUE TITLE
Have a way to force session scope teardown 

### ISSUE THREAD

**Issue by kalidasya** [pytest-dev/pytest#1738]
Hi,

I have a session scope fixture what provisions vms in openstack. Sometimes something else during the setup goes wrong, or there is keyboard interruption or jenkins job is terminated (probably similar to keyboard interrupt) in these cases the teardown is not executed and the vms remain in openstack. It would be nice if there can be a way to force the execution of the teardown.

**Comment by kalidasya** [comment]
any update on this?

**Comment by nicoddemus** [comment]
Hi @kalidasya, thanks for the ping on this.

There's nothing in `pytest` per-se, but you can take advantage of the fact that the `finally` block on a yield fixture will be guaranteed to be executed by Python:

```python
import pytest

@pytest.fixture
def vm():
    try:
        raise ValueError
        yield 1
    finally:
        print('teardown')


def test(vm):
    pass
```

```
 pytest foo.py -q
E
=================================== ERRORS ====================================
___________________________ ERROR at setup of test ____________________________

    @pytest.fixture
    def vm():
        try:
>           raise ValueError
E           ValueError

foo.py:6: ValueError
---------------------------- Captured stdout setup ----------------------------
teardown
1 error in 0.03 seconds
```

**Comment by kalidasya** [comment]
@nicoddemus thanks for the tip, I will try it out

**Comment by nicoddemus** [comment]
No worries. Please let us know if it worked so we can close the issue.

**Comment by nicoddemus** [comment]
Closing for now
