### ISSUE TITLE
Feature request: doctest report format as an option

### ISSUE THREAD

**Issue by troianow** [pytest-dev/pytest#1749]
Adding an option to the plugin to choose the type of report (e.g. None, REPORT_UDIFF, REPORT_NDIFF, REPORT_CDIFF) rather than the hard-coded REPORT_UDIFF

For example

py.test foo.py --doctest-module --doctest-report NONE

Would set `REPORT_UDIFF = 0` in _pytest/doctest.py:68 and return:
```
================================== FAILURES ===================================
______________________________ [doctest] foo.bar ______________________________
013     '''
014     >>> bar()
Expected:
       a  b
    0  1  4
    1  2  4
    2  3  6
Got:
       a  b
    0  1  4
    1  2  5
    2  3  6
```

while 
py.test foo.py --doctest-module --doctest-report UDIFF

would set `REPORT_UDIFF = doctest.REPORT_UDIFF

` in _pytest/doctest.py:68 and return 
```
================================== FAILURES ===================================
______________________________ [doctest] foo.bar ______________________________
013     '''
014     >>> bar()
Differences (unified diff with -expected +actual):
    @@ -1,4 +1,4 @@
        a  b
     0  1  4
    -1  2  4
    +1  2  5
     2  3  6
```

**Comment by nicoddemus** [comment]
Thanks for the suggestion! :grin:

**Comment by hartym** [comment]
@nicoddemus I made a basic implementation (see commit 625b603 in my fork, above), still need to do doc and tests but wanted your input on wether or not it's the right way to do it. Basically, I've seen that all `doctest` module imports are local and tried to implement it in a way that respects this, can you confirm (or infirm) it's the right way to to it ? Thanks (cc @hackebrot)

**Comment by RonnyPfannschmidt** [comment]
@hartym if i recall correctly the code was made that way so we do not need to import doctest in case of no doctest test

so your function pretty much removes that, since it does import dpoctest to get the options

**Comment by The-Compiler** [comment]
> if i recall correctly the code was made that way so we do not need to import doctest in case of no doctest test

What's the point of that?

**Comment by RonnyPfannschmidt** [comment]
no idea actually i think that came in before my time

**Comment by hartym** [comment]
I understand that, I'd like to avoid this but can't think of a "clever" way to do it without having to duplicate informations found in the `doctest` module. Any idea? Or is it fine to duplicate this to obtain this more efficient argparse builder thing?

The only implementation I can think off (and did this before refactoring to this dict getter) is to getattr(...) the thing at the last minute, but looks nasty ...

**Comment by hartym** [comment]
@The-Compiler apparently, some test check for example that the `logging` module is not in sys.modules at some point, probably between argument parsing and actual run, and my patch breaks that.

**Comment by hartym** [comment]
PR at #1754

**Comment by The-Compiler** [comment]
Seems like that change was originally made in 9b4cca2bf46f4c6c7e490df050a26efac7727049 - maybe @hpk42 knows why he did that back then :laughing:

**Comment by hartym** [comment]
f8f690d @ PR #1754
