### ISSUE TITLE
py.test wheel creates "py.test-2.7" executable for all Python versions.

### ISSUE THREAD

**Issue by mhils** [pytest-dev/pytest#1750]
In a nutshell, when creating the pytest wheel, the version-specific entrypoint is hardcoded to `py.test-2.7`. This results in `pip3` installing an executable called "py.test-2.7", but no executable called `py.test3` or `py.test-3.5`.

Thanks for the awesome project! :smiley:

**Comment by nicoddemus** [comment]
Fixed in the next release, thanks for the report! :smile:

**Comment by nicoddemus** [comment]
For reference: #1632.
