### ISSUE TITLE
Traceback swallowed upon ConftestImportFailure

### ISSUE THREAD

**Issue by jgehrcke** [pytest-dev/pytest#1752]
This is the exception handler for exceptions that occur upon conftest module import:

```python
            try:
                mod = conftestpath.pyimport()
            except Exception:
                raise ConftestImportFailure(conftestpath, sys.exc_info())
```
(https://github.com/pytest-dev/pytest/blob/38e0e0807467c41ec02d1289d00ca3530ae96dd3/_pytest/config.py#L322)

So, the exception is rewritten into a ConftestImportFailure. The handling code for ConftestImportFailure does not emit the formatted traceback of the original exception (the exception that occurred before ConftestImportFailure) to stderr.

In other words, the traceback corresponding to the underlying issue is not visible to the user.

In consequence, users can have a hard time identifying the root cause of the issue at hand, as described in these two tickets:

https://github.com/pytest-dev/pytest/issues/1482
https://github.com/pytest-dev/pytest/issues/1517

Quotes:

> but the second test will leak the ConftestImportFailure, hiding the underlying cause

> The conftestpath indicates one of my source files, but the code shown is from some internal py.test file.

Being rather new to the pytest codebase, I am not sure what the best way is to tackle this. Could be done in the ConftestImportFailure handler, but could also be done straight in `_pytest/config.py`. I have seen that we already directly write to stderr in that file. Doing so (writing the formatted traceback there) seems to be a viable and simple solution.

**Comment by nicoddemus** [comment]
Thanks for the issue and the PR @jgehrcke, but as I commented on the PR this has been fixed already in #1746. :+1:
