### ISSUE TITLE
Django's TEST_RUNNER setting is ignored

### ISSUE THREAD

**Issue by barbolani** [pytest-dev/pytest#1775]
Using Django 1.9 it seems that Py.test ignores the TEST_RUNNER specified in Django's settings. Looking in pytest_django.compat, I see that it directly tries to instantiate a DjangoTestRunner instead of using the settings.TEST_RUNNER

At least in Django 1.9 there is django.test.utlils.get_runner which locates and returns the runner class.

**Comment by The-Compiler** [comment]
This sounds like a [pytest-django issue](https://github.com/pytest-dev/pytest-django/issues) and not a pytest core one, correct?

**Comment by RonnyPfannschmidt** [comment]
exactly, please report at the correct issue tracker
