### ISSUE TITLE
sigalrm fails test

### ISSUE THREAD

**Issue by Nick0001** [pytest-dev/pytest#1777]
Test session starts (platform: linux2, Python 2.7.11, pytest 2.9.2, pytest-sugar 0.7.1)

My Program uses a timer with sigalrm for a timeout. If I run a test to test this feature via pytest and I only run this one test, the test passes, but if I run the "group" or all tests, the problem is that py.test seems to recognize the sigalrm and counts it as an error.

Is there any way to filter this signal so that it does not count as error?

**Comment by The-Compiler** [comment]
I don't think pytest handles sigalrm itself. Can you show your test and the output you get?

**Comment by Nick0001** [comment]
OK, my test was wrong, sorry.
