### ISSUE TITLE
pytest_assertrepr_compare not being used?

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1784]
Running regendoc in #1780, @The-Compiler noticed that an example from the docs regarding `pytest_assertrepr_compare` was not working as it should:

```python
# conftest.py
from test_foocompare import Foo
def pytest_assertrepr_compare(op, left, right):
   if isinstance(left, Foo) and isinstance(right, Foo) and op == "==":
       return ['Comparing Foo instances:',
               '   vals: %s != %s' % (left.val, right.val)]

# test_foocompare
class Foo:
    def __init__(self, val):
        self.val = val

    def __eq__(self, other):
        return self.val == other.val


def test_compare():
    f1 = Foo(1)
    f2 = Foo(2)
    assert f1 == f2
```

```
$ py.test

================================== FAILURES ===================================
________________________________ test_compare _________________________________

    def test_compare():
        f1 = Foo(1)
        f2 = Foo(2)
>       assert f1 == f2
E       AssertionError

test_foocompare.py:12: AssertionError
```

**Comment by flub** [comment]
This looks like it's using plain assertion instead of re-write at first glance.  So the hook probably doesn't come to the question.  I suspect this would have been done by reinterpret before but that's now gone...

**Comment by nicoddemus** [comment]
Hmm that's weird, I have the same effect even if I explicitly pass `--assert=rewrite`... why would this fall back to plain? :open_mouth:

**Comment by RonnyPfannschmidt** [comment]
at first glance it seems the rewritten import of conftest triggers a non-rewritten import of the test module before attempting a rewritten import of the test module
how/when does the rewriting logic add test modules to the paths to consider, and is there a way to do this earlier?

**Comment by nicoddemus** [comment]
Good point. Does it work if test_foocompare is imported locally inside the hook function? (not in front of a computer to test this myself)

**Comment by nicoddemus** [comment]
PR opened at #1787

**Comment by The-Compiler** [comment]
PR merged, so I'm closing this. I guess it wasn't auto-closed because it was merged to `features`?

**Comment by nicoddemus** [comment]
Yep! Thanks.
