### ISSUE TITLE
pip3 install creates py.test-2.7

### ISSUE THREAD

**Issue by MadWombat** [pytest-dev/pytest#1786]
When I am installing pytest, two scripts are created in /usr/local/bin. py.test and py.test-2.7. Both of these use python3.5 I have installed. My system us OS X El Captain 10.11.6. I have python 3.5 installed using Homebrew. The OS supplies both python 2.6 and 2.7. The default python binary in /usr/bin/python is the OS supplied version 2.7. I am guessing somewhere in the code default version is being used instead of the version calling.

**Comment by nicoddemus** [comment]
Hey @MadWombat,

This was a known issue and was fixed in #1662, but will only be released in pytest 3.0 which is due soon(tm).

Closing this for now, feel free to re-open if you still have any questions.

**Comment by MadWombat** [comment]
Thanks for the fast response. Sorry I wasn't thorough enough in my checking.

**Comment by nicoddemus** [comment]
No worries! :grin: 

Cheers!

**Comment by rustyhowell** [comment]
I'm seeing something similar on Ubuntu 14.04 LTS with python 3.4.3, where it appears to be dropping files in python2.7 install directory. Is this a different issue?

$ sudo pip3 install pytest 

Requirement already satisfied: pytest in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already satisfied: py>=1.4.29 in /usr/local/lib/python2.7/dist-packages (from pytest)

**Comment by The-Compiler** [comment]
@rustyhowell This is a different issue, and probably more related to Ubuntu's weird patching of pip and Python stuff than pytest :wink: However, you should never use `sudo pip` or you risk breaking your system - use `pip install --user` or a [virtualenv](https://virtualenv.pypa.io/en/stable/) instead.
