### ISSUE TITLE
Internal adjustments for easier integration with IDEs

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1790]
Here are a check-list of things discussed in #1613 which are actionable:
- [ ] ~~Disable capture in the config step (currently it seems options have a read-only configuration, but ideally a plug in should be able to change one of those). With this the PyDev plugin wouldn't need to do manual capturing out of pytest.~~
  This is not as simple as it looks because some plugins are loaded very early on (with `capture` being one of them). An existing and simple solution is to add `-p no:capture` to the `PYTEST_ADDOPTS` environment variable right before invoking pytest:
  
  ``` python
  os.environ['PYTEST_ADDOPTS'] = os.environ.get('PYTEST_ADDOPTS', '') + ' -p no:capture'
  pytest.main(args)
  ```
  
  Another option would pass it to the command-line. That's how PyCharm loads their own plugin into pytest:
  
  ```
  E:\PyCharm\helpers\pycharm\pytestrunner.py -p pytest_teamcity E:/ws/Souring/Projects/souring/souring20/source/python/souring20/io/export/_tests/test_export_grids.py "-k testExportGrids"
  ```
- [ ] xfail: document better on how to detect fail/pass/skip on items (possibly an API better than hasattr(report, 'wasxfail') too? -- but without breaking the current 'informal' hasattr API).
- [ ] ~~Provide some API to get the absolute path for items (currently things are relative to the collect working dir and changes to the current working dir could affect how the current relative path is resolved later on).~~ 
  Verified that `str(item.fspath)` or `item.fspath.strpath` already provide the full path to the item.
- [ ] ~~`ReprFileLocation`: provide a way to customize the format and whether the absolute path should be used.~~ 
  Not possible in 3.0 because `ReprFileLocation` changes the color of the path to make it easier to copy/paste paths from the terminal (#1781).
- [x] Provide a way to get the original method name of items (i.e.: so that it's less 'fickle' to deal with parametrized tests).
- [x] report: provide public API to get report contents (equivalent to report.toterminal, as the TerminalWriter doesn't seem to be part of the public API).
- [x] report.sections: document what's in the keys (ideally provide constants for that so that it's possible to identify an stderr/stdout section).

Code for reference: [pydev_runfiles_pytest2.py](https://github.com/fabioz/Pydev/blob/master/plugins/org.python.pydev/pysrc/_pydev_runfiles/pydev_runfiles_pytest2.py).

cc @fabioz

**Comment by fabioz** [comment]
Regarding:

- ReprFileLocation: provide a way to customize the format and whether the absolute path should be used. 

I think it's still possible: if a format is specified, use it, otherwise use the default behavior (with the highlighting). Another option would not be specifying the format, but a callable which is responsible for doing the print (supporting that in a public API should suffice too).

**Comment by nicoddemus** [comment]
Can't you just parse the native format from the output? I just tested this with PyCharm and it underlines file links as expected using the native pytest format, even when paths are relative. Seems to be the best option, because users will see exactly what they already see in the terminal.

**Comment by nicoddemus** [comment]
Closing this for now... @fabioz feel free to reopen another issue if there are still pain points.
