### ISSUE TITLE
Proposal: Verbose output from tests through decorators.

### ISSUE THREAD

**Issue by karandesai-96** [pytest-dev/pytest#1792]
Sometimes there are thousands of tests which may print too much on `stdout` or `stderr`. In that case, we need verbose output from ten of the tests. To facilitate this, we may introduce a marker for not capturing the output for certain tests.

Final mechanism can be as follows:

``` python
def test_foo():
    foo()
    print "foo called"

@pytest.mark.verbose
def test_bar():
    bar()
    print "bar called"
```
- Captured outputs can roughly be depicted as:
- `py.test`  
  
  > `bar called`
- `py.test --capture=no`  
  
  > `foo called`
  > `bar called`
- It may be taken up a step further to have verbose output from a module / directory recursion through `pytest.ini` support.

**Comment by karandesai-96** [comment]
Another alternative is:

1. `py.test` (Everything captured)
2. `py.test --capture=some` (Marked tests will not be captured)
3. `py.test --capture=no` (All tests will not be captured)

**Comment by nicoddemus** [comment]
Just FYI in pytest-3.0 `capsys` and `capfd` have a `disabled()` context manager method which disables capturing in the block:

```python
def test_bar(capsys):
    with capsys.disabled():
        bar()
        print "bar called"
```

**Comment by karandesai-96** [comment]
Thanks :smile: I am on `2.9` yet and was not aware about it ! Let's see where this discussion heads over, meanwhile I'll upgrade pytest and use this fixture.

**Comment by nicoddemus** [comment]
3.0 is not out yet (will be out probably next year), sorry for not being clearer.

Also, I think your proposal is independent from the disabled() context manager and could be implemented as an alternative. :grin:

**Comment by karandesai-96** [comment]
Awesome :smiley:

**Comment by The-Compiler** [comment]
I'm not sure if it's worth having yet another way™ to disable capturing in the core :wink:

I guess if someone wants a marker like this, it'd probably be some 5-line hook in `conftest.py` to do it using `capsys.disabled()`?

**Comment by karandesai-96** [comment]
Pytest 3 has been released and I have the feature what I wished to. Thanks, closing this. :smile:
