### ISSUE TITLE
pytest_runtest_makereport of custom conftest doesn't get called when running with xdist with -n option

### ISSUE THREAD

**Issue by ssrikanta-scea** [pytest-dev/pytest#1800]
I have noticed registering new custom plugin having the method `pytest_runtest_makereport(item, call)` doesn't get call back, when running with `pytest-xdist` plugin with `-n` option  However it woks if we do sequential execution without `-n`  option.

**Comment by RonnyPfannschmidt** [comment]
can you report this one in the xdist but tracker ( pytest-dev/pytest-xdist) and attack some logs/examples

with just your issue it would require a unsustainable amount of work to figure whats wrong for you

also note that the hook is if ever only executed on the slave

**Comment by ssrikanta-scea** [comment]
ok.. i will add it to py-test xdist

**Comment by nicoddemus** [comment]
@ssrikanta-scea thanks! I'm closing this one know then.
