### ISSUE TITLE
#1435 rootdir discovery: re-open

### ISSUE THREAD

**Issue by matthiasha** [pytest-dev/pytest#1801]
Playing around with the current pytest sources after merging #1621, I figured out that my example
``py.test --cli-option ../../test.log``

does still not work if you do ``touch ../../test.log`` before executing pytest.

Sorry for finding this out only after the merge :(

**Comment by matthiasha** [comment]
Please reopen #1435

**Comment by nicoddemus** [comment]
Done!

**Comment by matthew-piziak** [comment]
What is the current status of #1435? I've been getting the GitHub unicorn for that issue.

**Comment by nicoddemus** [comment]
I'm getting the unicorn too unfortunately, but I could salvage it from mailbox: it has been fixed by #1819. I closed it now without opening it direclty from the "Issues" page.
