### ISSUE TITLE
Documentation unclear about search discovery

### ISSUE THREAD

**Issue by tommyjcarpenter** [pytest-dev/pytest#1808]
Here is the blurb in reference:

> Conventions for Python test discovery
> pytest implements the following standard test discovery:
> If no arguments are specified then collection starts from testpaths (if configured) or the current directory. Alternatively, command line arguments can be used in any combination of directories, file names or node ids.
> recurse into directories, unless they match norecursedirs
> test_*.py or *_test.py files, imported by their test package name.
> Test prefixed test classes (without an __init__ method)
> test_ prefixed test functions or methods are test items

This list does not state whether this list is ordered or additive. This should be clarified to state whether `test_ prefixed test functions` are searched within files that do not follow `test_*.py or *_test.py`. Meaning, does it first look for files called `test_*.py or *_test.py`, _then_ looks inside _only those_ for all `test_ prefixed`, or are `test_ prefixed` searched in all files in all `testpaths`.

**Comment by nicoddemus** [comment]
Thanks!

Btw, a PR for that would be greatly appreciated, and can even be done directly in the GitHub web interface. :wink:

**Comment by ApaDoctor** [comment]
This issue can be closed. It's already solved
Current reference:

> pytest implements the following standard test discovery:
> 
> If no arguments are specified then collection starts from testpaths (if configured) or the current directory. Alternatively, command line arguments can be used in any combination of directories, file names or node ids.
> Recurse into directories, unless they match norecursedirs.
> In those directories, search for test_*.py or *_test.py files, imported by their test package name.
> **From those files**, collect test items:
> test_ prefixed test functions or methods outside of class
> test_ prefixed test functions or methods inside Test prefixed test classes (without an __init__ method)

**Comment by nicoddemus** [comment]
Agreed, thanks @ApaDoctor for the pointer.

**Comment by tommyjcarpenter** [comment]
I hope this was solved after I raised this issue and that I didn't miss something obvious. Thanks all!
