### ISSUE TITLE
tests fail with Error code 245

### ISSUE THREAD

**Issue by yurivict** [pytest-dev/pytest#1838]
On FreeBSD tests fail in 3.0.0:
```
testing/test_tmpdir.py ...........s
testing/test_unittest.py ......................*** Error code 245
```
It should at least say what is wrong.

**Comment by RonnyPfannschmidt** [comment]
that looks like a operating system error - its not clear what happens on bsd there
can you provide more information?

**Comment by yurivict** [comment]
While tracing system calls I see that this number is the return code of some shell process. It started early on, and then its error code is printed this way.

**Comment by RonnyPfannschmidt** [comment]
does py.test actually fail, or is it just the output of your other process?
i have literally no idea what is happening, at a first uneducated guess however it looks like pytest is not at fault

**Comment by yurivict** [comment]
I don't have any other process. The shell that fails is launched from under py.test.

**Comment by nicoddemus** [comment]
@yurivict do you see this problem in other test suites, or only on pytest's?

**Comment by yurivict** [comment]
Only in pytest. The problem existed before 3.0.0 too.

**Comment by The-Compiler** [comment]
As others said, that really doesn't look like an error coming from pytest... Could you maybe try running `strace` on it and showing the output somewhere?

**Comment by yurivict** [comment]
```Error code``` came from the framework. I narrowed it down to this command failure:
```
# py.test -rfsxX test_unittest.py
=========================================================================== test session starts ============================================================================
platform freebsd10 -- Python 2.7.12, pytest-3.0.0, py-1.4.31, pluggy-0.3.1
rootdir: /usr/ports/devel/py-pytest/work/pytest-2.8.7, inifile: tox.ini
plugins: xdist-1.13.1, hypothesis-1.18.1
collected 39 items 

test_unittest.py ...............FF.....FBus error
```

Furthermore, failure happens in ```test_trial_testcase_runtest_not_collected``` inside the call ```reprec = testdir.inline_run()```

**Comment by yurivict** [comment]
It turned out that reinstalling py-cryptography helped. Was some random, unexplainable thing.

**Comment by nicoddemus** [comment]
Thanks for the follow up!

**Comment by henryiii** [comment]
I'm getting the same error, with Plumbum and the python nightlies (all other versions work in Travis). Is there something in the (python 3.6) nightlies that might cause an incompatibility?

https://travis-ci.org/tomerfiliba/plumbum/jobs/160885522

**Comment by The-Compiler** [comment]
245 is -11 which is a segmentation fault - so yeah, something in Plumbum or pytest is probably causing Python to segfault.

**Comment by RokeJulianLockhart** [comment]
You might find https://stackoverflow.com/q/72121892/9731176 useful.
