### ISSUE TITLE
register_assert_rewrite warns for already imported and rewritten modules

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1840]
edited

it appears some code is reloading conftest which in turn runs a register once before and once after import

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt any more information on this? I ask because I would like to release 3.0.1 soon (like tomorrow) if possible. :grin:

**Comment by RonnyPfannschmidt** [comment]
Im still investigating

**Comment by RonnyPfannschmidt** [comment]
close in favour of #2005

**Comment by nicoddemus** [comment]
👍
