### ISSUE TITLE
test_doctest.py fails 

### ISSUE THREAD

**Issue by raquel-ucl** [pytest-dev/pytest#1852]
I got a fresh clone on my  of pytest's master branch. I created a virtual environment and installed tox. When I run:

```
python3 runtox.py -e linting,py27,py35
```

I get one test that fails (although `expected` and `got` results look very similar!):

```
__________________________________________________ [doctest] test_doctest.txt ___________________________________________________
002
003 Testing doctest::
004
005     >>> 1 + 1
Expected:
    2
Got:
    2

/Users/raquelalegre/workspace/pytest/testing/freeze/tests/test_doctest.txt:5: DocTestFailure
```

Here's my `pip list`:

```
pip (8.1.2)
pluggy (0.3.1)
py (1.4.31)
setuptools (26.0.0)
tox (2.3.1)
virtualenv (15.0.3)
wheel (0.29.0)
```

**Comment by nicoddemus** [comment]
that's strange given current tests on both Travis and AppVeyor are passing...

perhaps it is related to your eol settings on Git?

**Comment by raquel-ucl** [comment]
You were very right :) Sorry! Closing...
