### ISSUE TITLE
No assertion rewriting in files imported from conftest

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1871]
I guess I can't be the only one importing some utility code from `conftest.py`, or can I? :wink:

With this `conftest.py`:

```python
import pytest
from testutils import SomeClass

@pytest.fixture
def some_obj():
    return SomeClass()
```

And a `testutils.py`:

```python
class SomeClass():

    def __init__(self):
        x = 23
        y = 42
        assert x + y == 1337
```

And a `test_foo.py`:

```python
def test_foo(some_obj):
    pass
```

With pytest 2.9, I guess assertion reinterpretion kicks in and I get:

```
>       assert x + y == 1337
E       AssertionError
```

With 3.0, that's removed and I get plain asserts:

```
>       assert x + y == 1337
E       AssertionError
```

Since I have some custom assertion helpers and stuff in separated files, that's quite a bummer.

I'm not sure what the best way to fix this would be - ideas I had so far:

- Rewrite everything under the testpath if an explicit one is given
- Rewrite everything in directories where there are `conftest.py` files
- Rewrite everything imported from `conftest.py` files (probably cleanest, but maybe hard to implement?)

**Comment by nicoddemus** [comment]
You will have to call `register_assert_rewrite` before trying to import `testutils`:

```python
import pytest
pytest.register_assert_rewrite('testutils')
from testutils import SomeClass

@pytest.fixture
def some_obj():
    return SomeClass()
```

This now works as expected:

```
    def __init__(self):
        x = 23
        y = 42
>       assert x + y == 1337
E       assert (23 + 42) == 1337
```

**Comment by The-Compiler** [comment]
Oh - thanks, that worked beautifully (even with a package)!

Do you think we should do something automatically (like I outlined above) or should I close this? I don't really have a strong opinion on it.

**Comment by nicoddemus** [comment]
> Rewrite everything under the testpath if an explicit one is given

This would mean that projects which decide to place tests next to the code would get their own non-test code rewritten, which is something @flub and @RonnyPfannschmidt are against.

> Rewrite everything in directories where there are conftest.py files

Same problem as above.

> Rewrite everything imported from conftest.py files (probably cleanest, but maybe hard to implement?)

That might not be safe as well because `conftest.py` files can easily import application code to implement fixtures etc.

I would really love some way to automate this in some way, but I don't really have an idea for that at the moment. :grin:

**Comment by flub** [comment]
Ideally you'd do that `register_assert_rewrite()` in the `__init__.py`.

More importantly however is that you did not find the documentation for this when you upgraded to 3.0.  How can we improve that?

**Comment by nicoddemus** [comment]
> Ideally you'd do that register_assert_rewrite() in the __init__.py.

Agreed, it's just that @The-Compiler's test suite doesn't [have any `__init__.py`](https://github.com/The-Compiler/qutebrowser/tree/master/tests) files.

**Comment by The-Compiler** [comment]
> Agreed, it's just that @The-Compiler's test suite doesn't [have any `__init__.py`](https://github.com/The-Compiler/qutebrowser/tree/master/tests) files.

Do we have some agreed-upon recommendation whether to do that or not yet? Seems like the answer changes depending on whom I ask :laughing: 

> More importantly however is that you did not find the documentation for this when you upgraded to 3.0. How can we improve that?

As Bruno pointed out, what I usually do when doing an upgrade (and certainly with a major one) is reading the changelog. `register_assert_rewrite` seems to be not mentioned at all - something like this would've helped me:

> - Reinterpretation mode has now been removed. Only plain and rewrite mode are available, consequently the `--assert=reinterp` option is no longer available. **This also means files imported from `conftest.py` will not benefit from improved assertions by default, you should use `pytest.register_assert_rewrite` to explicitly turn assertion rewriting on for those files.** Thanks @flub for the PR.

**Comment by nicoddemus** [comment]
FWIW I think it is still valid to add that to the CHANGELOG, it might be helpful for someone else down the road. :grin:
