### ISSUE TITLE
test_suite support

### ISSUE THREAD

**Issue by anntzer** [pytest-dev/pytest#1877]
nose (http://nose.readthedocs.io/en/latest/setuptools_integration.html) supports passing `nose.collector` as the `test_suite` kwarg of `setup()` to enable `python setup.py test` without having to mess with `setup_requires`, which has a bunch of issues of its own (unlike `pytest-runner`).  A similar addition for pytest would be appreciated.

**Comment by RonnyPfannschmidt** [comment]
py.test does not support unittest internals - its unittest support is purely for legacy support, as such by design we do not expose unittest suites
