### ISSUE TITLE
Ignore class name pattern

### ISSUE THREAD

**Issue by JamshedVesuna** [pytest-dev/pytest#1879]
It would be great to have an `ignore_python_classes` configuration pattern in conjunction with [`python_classes`](http://doc.pytest.org/en/latest/customize.html#confval-python_classes). This is especially useful when using private base test classes:

```python
class _BaseTest():

    def test_something(self):
        assert self.var == 1  # self.var only exists in child classes.
        ...

class TestSomething(_BaseTest):
    var = 3
    # Run test_something with self.var = 3.
    ...
```
I couldn't find an existing issue or question about this. Is there a better way of doing this than setting an ignore pattern of `_Base*`?

**Comment by nicoddemus** [comment]
pytest by default will only search for classes with the `Test` prefix. Running your own example:

```
============================= test session starts =============================
collected 1 items

foo.py::TestSomething::test_something FAILED

================================== FAILURES ===================================
________________________ TestSomething.test_something _________________________

self = <foo.TestSomething instance at 0x00000000038B9888>

    def test_something(self):
>       assert self.var == 1  # self.var only exists in child classes.
E       assert 3 == 1
E        +  where 3 = <foo.TestSomething instance at 0x00000000038B9888>.var

foo.py:4: AssertionError
========================== 1 failed in 0.03 seconds ===========================
```

You will notice it only collected `TestSomething`. Can you post a complete example of the problem you are having?

**Comment by JamshedVesuna** [comment]
More specifically, I am switching from using `nosetests` to `pytest`, and have some `_Base` test classes that inherit from `unittest.TestCase`. These are getting picked up by `pytest` and `pytest --collect-only`. Would make the transition much faster if I could just explicitly ignore these test classes. Or, is there an alternative solution here?

**Comment by The-Compiler** [comment]
I *think* setting `__test__ = False` in those classes should prevent them from being picked up - can you try that?

In the long run, those should probably be converted [parametrized](http://docs.pytest.org/en/latest/parametrize.html) plain tests though :wink:

**Comment by nicoddemus** [comment]
> I think setting __test__ = False in those classes should prevent them from being picked up - can you try that?

Also you will need to set `__test__ = True` on the subclasses.

**Comment by JamshedVesuna** [comment]
Darn, this might be a lot of overhead. Is there a plan to add `ignore_python_classes` to the config setup? Is this a reasonable PR request?

**Comment by nicoddemus** [comment]
I guess so... it would have to be implemented by the `unittest` plugin. But that's a new feature, so it will be available in `3.1.0` only, and that might take a awhile to be released.

**Comment by JamshedVesuna** [comment]
Thanks for the information and quick response! Going to close this out for now.

**Comment by nicoddemus** [comment]
No problem, glad to help!
