### ISSUE TITLE
tryfirst and trylast markers doesn't work 

### ISSUE THREAD

**Issue by wnetel** [pytest-dev/pytest#1893]
Hi, 

I need to setup test case execution ordering and I would like to use markers (tryfirst is most important for me in my particular issue). It seems to doesn't work as expected or maybe I'm doing something wrong. Could you please help with this.   

**I expected that test_c_case should be executed as first item.**  

**EXAMPLE INFO:**  
-bash-4.2$ pwd
/tmp/markers

-bash-4.2$ ls 
test_markers.py

**content of test_markers.py:** 
`import pytest

def test_a_case():
    a = 5
    assert a == 5

def test_b_case():
    b = 6
    assert b == 6

@pytest.mark.tryfirst
def test_c_case():
    c = 7
    assert c == 7
`  

**execution output:** 

> -bash-4.2$ py.test -sv
> platform linux2 -- Python 2.7.5, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
> cachedir: .cache
> rootdir: /tmp/markers, inifile:
> collected 3 items
> 
> test_markers.py::test_a_case PASSED
> test_markers.py::test_b_case PASSED
> test_markers.py::test_c_case PASSED

REQUIRED INFO: 
OS: RHEL 7.2

-bash-4.2$ py.test --version
This is pytest version 2.9.2, imported from /usr/lib/python2.7/site-packages/pytest.pyc

bash-4.2$ pip list 
certifi (2015.9.6.2), chardet (2.2.1), configobj (4.7.2), cycler (0.9.0), decorator (3.4.0), distribute (0.7.3), ecdsa (0.13), ethtool (0.8), freetype-py (1.0.2), iniparse (0.4), ipaddr (2.1.9), kitchen (1.1.1), lxml (3.2.1), M2Crypto (0.21.1), Magic-file-extensions (0.2), matplotlib (1.5.0), nose (1.3.7), numpy (1.10.1), paramiko (1.16.0), pciutils (1.7.3), perf (0.1), pip (8.1.2), py (1.4.31), pycrypto (2.6.1), pycurl (7.19.0), pygobject (3.14.0), pygpgme (0.3), pyliblzma (0.5.3), pyOpenSSL (0.13.1), pyparsing (1.5.6), pyserial (2.7), pytest (2.9.2), python-augeas (0.5.0), python-dateutil (1.5), python-dmidecode (3.10.13), pytz (2015.7), pyudev (0.15), pyxattr (0.5.1), PyYAML (3.11), redhat-access-insights (1.0.6), requests (2.6.0), rhnlib (2.5.65), rhsm (1.15.4), setuptools (0.9.8), singledispatch (3.4.0.3), six (1.9.0), slip (0.4.0), slip.dbus (0.4.0), tornado (4.3), urlgrabber (3.10), urllib3 (1.10.2), yum-metadata-parser (1.1.4)

**Comment by The-Compiler** [comment]
Those markers are intended for plugin hook implementations and do nothing for tests (they also got replaced by `@pytest.hookimpl(tryfirst=True)`.

Why do you need a test to run before others? Maybe a [fixture](http://docs.pytest.org/en/latest/fixture.html) would be a better fit?

There is also the [`pytest-ordering` plugin](https://github.com/ftobia/pytest-ordering) FWIW.

**Comment by RonnyPfannschmidt** [comment]
closing this one as invalid, the markers are used for hooks

**Comment by wnetel** [comment]
I need to verify rpm package before removing it, which is done by the next case.  I can't use any of external plugins - only included in standard pytest. I need to consider fixture using. Sorry for inconvenience.

**Comment by RonnyPfannschmidt** [comment]
just order the test cases then?

**Comment by wnetel** [comment]
Only, what I need is to force particular test case (test function) execution before another.

**Comment by RonnyPfannschmidt** [comment]
the most simple way would be to order them accordingly and to document that dependency

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt is right, but if you describe your problem with more detail using some pseudo-code we might be able to provide a cleaner alternative.

**Comment by The-Compiler** [comment]
> the most simple way would be to order them accordingly and to document that dependency

You mean via `pytest_collect_modifyitems` or what?

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler py.test orders by source location as long as parameters are not involved

**Comment by wnetel** [comment]
Thanks guys, for all your opinions. I just placed source code before another test method, but it is short time solution. I've just started working in quite huge test environment and it is hard to describe in details for me at this moment.

**Comment by The-Compiler** [comment]
@RonnyPfannschmidt huh, what's the point of [pytest-sourceorder](https://pypi.python.org/pypi/pytest-sourceorder) then?

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler at first glance no idea

**Comment by nicoddemus** [comment]
From usage:

> Methods are ordered by line nuber of their definition, so spreading them between multiple files or otherwise defining them outside of their class might cause the plugin to order them wrong.

> When inheriting from an ordered test class, the superclass' methods will be run first (even if overridden), followed by the ones from subclasses. You generally do *not* want to apply an additional @ordered decorator to the subclasses – doing so will reset the inheritance-based ordering.
