### ISSUE TITLE
Pytest hangs after printing out all test results when CUDA wrapper code is called.

### ISSUE THREAD

**Issue by yoons1** [pytest-dev/pytest#1903]
I have generated python wrapper for a simple CUDA code using a very simple SWIG interface file.
After compiling, I can import the module and call the python wrapper function successfully. 
But if I call the same python wrapper function inside a test function using pytest and run the pytest, everything seems to go well, but I don't get back the prompt. It hangs indefinitely until I kill the process. 

* python (2.7.12)  -- Anaconda distribution
* pytest (3.0.1)
* Windows 7 64-bit
* CUDA 7.5

Example:
test.h
----------------
extern "C" size_t getCudaAvailableMem();

test.cpp
----------------
size_t getCudaAvailableMem()
{
	size_t cudaAvailBytes, cudaTotalBytes;
	cudaMemGetInfo( &cudaAvailBytes, &cudaTotalBytes );
	return cudaAvailBytes;
}

**Comment by The-Compiler** [comment]
Can you check if [pytest-timeout](https://pypi.python.org/pypi/pytest-timeout) shows you where it's hanging?

**Comment by yoons1** [comment]
Tried
py.test --timeout=60 --timeout_method='thread' test_file.py

Still hangs after all the report print to console.

**Comment by The-Compiler** [comment]
So you don't get a stacktrace for the hang? Can you try with [`pytest-faulthandler`](https://github.com/pytest-dev/pytest-faulthandler) and `--faulthandler-timeout` maybe?

**Comment by yoons1** [comment]
Thanks for the pointers.
Tried with pytest-faulthandler, but same result: hangs indefinitely.
Unfortunately, --faulthandler-timeout is unavailable in Windows.

I attached the python process to 2 different pytest cases: one with the hanging post CUDA wrapped function call and another without such CUDA wrapped function call.
One big difference is that there are worker threads named nvcuda.dll for the hanging case.

Finally, I ran the same CUDA wrapped function outside the pytest frame, and attached the process.
nvcuda.dll worker threads are also there, but none of the hanging experienced using pytest.

**Comment by The-Compiler** [comment]
I'm still pretty sure this hang happens somewhere in CUDA's C code, and whatever pytest does just happens to trigger that. Unfortunately, I'm out of ideas on how to further debug this.

**Comment by yoons1** [comment]
First of all, thanks for your help in the matter.

The hanging I reported occurs only when run under a pytest test function. If I run it outside the pytest test function, I observed no hanging. You may be correct in that the CUDA code may be triggering something in pytest.

One last thing I noticed when I attached a debugger to "python.exe" before running the test. After all the tests are done, python hangs, and there is what seems like an infinite loop of worker threads being terminated. As a consequence, the cpu is not idle in this hanging state. 

I don't know if the last bit of information is helpful, but that's my attempt at trying to hold on to the last straw...

**Comment by nicoddemus** [comment]
Just a shot in the dark, what happens if you run with `pytest -s`?

**Comment by yoons1** [comment]
This issue is caused by the SWIG wrapper when wrapping for Python.
For example, assume I have 2 static libraries. If I directly link the 2 static libraries to a .pyd file using SWIG, then this hanging occurs. In contrast, if I link the 2 static libraries to a shared library, and then create a .pyd file using SWIG, the hanging does not occur. Therefore, I think this hanging is not associated with pytest.

**Comment by RonnyPfannschmidt** [comment]
@yoons1 thanks for following up
