### ISSUE TITLE
ValueError: Cannot run multiple SparkContexts at once

### ISSUE THREAD

**Issue by xiaohan2012** [pytest-dev/pytest#1916]
I have several test cases using `pyspark.context.SparkContext`.

When using `py.test` to run all my test cases, the following error occurred:

`ValueError: Cannot run multiple SparkContexts at once`

I am using `pytest.fixture` to pass in the `SparkContext` instance like this:

```
import findspark  # this needs to be the first import                                                                        
findspark.init()

import pytest
from pyspark import SparkConf
from pyspark import SparkContext

@pytest.fixture(scope="session")
def spark_context(request):
    """ fixture for creating a spark context                                                                                 
    Args:                                                                                                                    
    request: pytest.FixtureRequest object                                                                                    
    """
    conf = (SparkConf().setMaster("local[2]").setAppName("SparkTest"))
    sc = SparkContext(conf=conf)
    sc.setCheckpointDir('checkpoint')         
    request.addfinalizer(lambda: sc.stop())
    return sc
```

`pip list`:

```
cycler (0.10.0)
decorator (4.0.10)
findspark (1.1.0)
line-profiler (1.0)
matplotlib (1.5.1)
networkx (1.11)
nose (1.3.7)
numpy (1.11.1)
pandas (0.18.1)
pip (8.1.2)
pkg-resources (0.0.0)
py (1.4.31)
pyparsing (2.1.5)
pytest (2.9.2)
python-dateutil (2.5.3)
pytz (2016.6.1)
rope (0.10.3)
scikit-learn (0.17.1)
scipy (0.17.1)
setuptools (24.3.0)
six (1.10.0)
sklearn (0.0)
tqdm (4.8.4)
wheel (0.29.0)
yapf (0.11.0)
```
OS and Python:

`platform linux -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1`

How to fix this problem? Is pytest running the cases in parallel?

**Comment by The-Compiler** [comment]
Do you have an example where we can reproduce this somewhere?

The things I can imagine so far is that `findspark.init()` creates a `SparkContext` or that you import your fixture somewhere and thus it gets defined twice.

**Comment by xiaohan2012** [comment]
Hi, the code is here, https://github.com/xiaohan2012/snpp

The spark-related tests are in `tests/test_lowrank.py`. 

And if you run (assuming virtualvenv is activated):

```
cd tests/
py.test
```

The error should reproduce.

**Comment by The-Compiler** [comment]
There we go, you import your `spark_context` feature causing it to be defined twice:

```python
from contexts import spark_context
```

(line 7 in `test_lowrank.py`).

Instead, you should define your fixture in a `conftest.py` file (see the [relevant docs](http://docs.pytest.org/en/latest/fixture.html#sharing-a-fixture-across-tests-in-a-module-or-class-session)) and let pytest take care of the rest :wink:

**Comment by xiaohan2012** [comment]
It works! That's really handy! Thanks!
