### ISSUE TITLE
Link to PDF documentation is broken

### ISSUE THREAD

**Issue by alexwlchan** [pytest-dev/pytest#1917]
The main pytest page (http://docs.pytest.org/en/latest/) links to PDF documentation in the sidebar:

http://docs.pytest.org/en/latest/pytest.pdf

Visiting that link takes me to a 404 page on ReadTheDocs.

**Comment by The-Compiler** [comment]
Seems like the link in the sidebar got forgotten with the migration to readthedocs :wink: Thanks for the report, #1919 should fix this!
