### ISSUE TITLE
no output from pytest_assertrepr_compare in conftest

### ISSUE THREAD

**Issue by virhilo** [pytest-dev/pytest#1929]
In versions later than 2.9.1 when pytest_assertrepr_compare is defined py.test displays just generic 'E      AssertionError' instead of value returned there.

conftest.py:
```
import foo

def pytest_assertrepr_compare(config, op, left, right):
    if isinstance(left, foo.Foo) and isinstance(right, foo.Foo) and op == "==":
        return [
            'Comparing Foo:',
            'failed on val: {} != {}'.format(left.val, right.val)
        ]
```
foo.py:
```
class Foo(object):
   def __init__(self, val):
       self.val = val

   def __eq__(self, other):
      return self.val == other.val

def test_compare():
   f1 = Foo(1)
   f2 = Foo(2)
   assert f1 == f2
```
output (in versions > 2.9.1):
```
$ pytest -q foo.py
F
================================== FAILURES ===================================
________________________________ test_compare _________________________________

    def test_compare():
       f1 = Foo(1)
       f2 = Foo(2)
>      assert f1 == f2
E      AssertionError

foo.py:15: AssertionError
1 failed in 0.01 seconds
```
expected output(works on 2.9.1):
```
$ py.test -q foo.py
F
================================== FAILURES ===================================
________________________________ test_compare _________________________________

    def test_compare():
       f1 = Foo(1)
       f2 = Foo(2)
>      assert f1 == f2
E      assert Comparing Foo:
E        failed on val: 1 != 2

foo.py:12: AssertionError
1 failed in 0.00 seconds

```

Here is link to all the code samples pasted above: https://gist.github.com/virhilo/1eb5c1fd952b8b5141c1646a88a51943

**Comment by The-Compiler** [comment]
This is because assertion reinterpretion is now gone, and the rewriting is turned off by default - you'll need to do `pytest.register_assert_rewrite('foo')` before `import foo` (see [docs](http://docs.pytest.org/en/latest/writing_plugins.html#pytest.register_assert_rewrite)).

**Comment by RonnyPfannschmidt** [comment]
i missed that detail

basically importing test code removes the ability of the rewriter to change it

@virhilo please try when moving the import for "foo" to the actual hook

that way the import happens after test module rewriting

**Comment by virhilo** [comment]
@The-Compiler @RonnyPfannschmidt Can confirm, both solutions pytest.register_assert_rewrite('foo') or moving import to the actual hook work.

In that case maybe example in documentation here: http://docs.pytest.org/en/latest/assert.html#defining-your-own-assertion-comparison should have import moved as well?

**Comment by RonnyPfannschmidt** [comment]
yes, i'll move that on into #1930 and close this issue
