### ISSUE TITLE
Nested conftest.py

### ISSUE THREAD

**Issue by Ignalion** [pytest-dev/pytest#1931]
Hi guys,

We have integrated pytest and actually we're using it for a couple of month. You're done the great work, so far it is the best testing framework for Python I've ever seen.

However, now we moved our tests in different folders and we'd like to have some hierarchy in our fixtures and conftest.py files.
Let's say, we have nested test directory structure and I want to have like general fixtures in parent conftest.py and component-like fixtures in the nested conftest.py.

So fat pytest seems to use only the deepest one. Is it possible to make one test use fixtures from different conftest.py files?

Thanks,
Constantine

**Comment by The-Compiler** [comment]
Do you have an example project somewhere? Using fixtures from a root `conftest.py` as well as fixtures from a `conftest.py` in some subdirectory from a test in that subdirectory should work without any issues.

**Comment by Ignalion** [comment]
Well, indeed it is working correctly. I think there was some misunderstanding with my colleagues of what they're trying to achieve. Sorry about that and thanks for your time!

**Comment by MaheshKok** [comment]
Just a thought ... I too face the same issue

Here is how i handled it

Session related fixtures are kept in root directory 
and module relates fixture in corresponding modules


all sub conftest imports from root conftest and this way sub conftest has their and parents conftest features and this helps in maintaining a readable and clean code.
