### ISSUE TITLE
Test Generator similar to pythoscope?

### ISSUE THREAD

**Issue by Nick0001** [pytest-dev/pytest#1946]
Is there a way to use pytest to generate test cases similar to pythoscope? pythoscope only supports unittest and seems to abandoned. The generators for pytest only seem to address test data for existing cases. pythoscope generates non-existant tests. Tools like this also exist for other languages.

**Comment by RonnyPfannschmidt** [comment]
@Nick0001 at least i am not aware of such a project

**Comment by nicoddemus** [comment]
Closing this for now then.
