### ISSUE TITLE
--pdbcls implies --pdb

### ISSUE THREAD

**Issue by davidszotten** [pytest-dev/pytest#1948]
is this intentional?

(my use case is setting pdbcls in my pytest.ini so that whenever i _do_ invoke pdb it uses a custom pdb class)

**Comment by RonnyPfannschmidt** [comment]
good find, i think its a bug,

its intentionally handled that way atm

**Comment by davidszotten** [comment]
ok. will have a look at a patch.

**Comment by nicoddemus** [comment]
Fixed in `features`
