### ISSUE TITLE
Allow pytest to exit with status 0 if even if there are failing tests

### ISSUE THREAD

**Issue by mattkatz** [pytest-dev/pytest#1969]
I'm using Bamboo as my build system.
It can consume the junit style output that pytest can provide.
When pytest executes, it exists with a non-zero status if it finds any violation.

Bamboo interprets this as a build error and stops the build - which prevents the junit xml from being read.  Is there a way to let pytest exit zero so that my build system can parse xml and let me know about errors in a pretty way?

**Comment by RonnyPfannschmidt** [comment]
if you just use a shell command to invoke, `pytest || true` ?

i dont know bamboo, but pytest doesn't have builtin support for a different exit status
maybe its possible to create a plugin

**Comment by nicoddemus** [comment]
A quick google search gives [this answer](https://answers.atlassian.com/questions/209503/best-way-to-handle-non-zero-exit-code-from-test-results), apparently from Atlassian's support itself.

FWIW Jenkins still parses the XML even if pytest returns non-zero.

**Comment by mattkatz** [comment]
Hmm - we are using bamboo on windows so I'll give the answer from @nicoddemus a shot. My very long googling did not turn that one up! much appreciated.

**Comment by nicoddemus** [comment]
@mattkatz, @RonnyPfannschmidt's suggestion will also work on `.bat` files. 😉

**Comment by nicoddemus** [comment]
I'm closing this for now @mattkatz, but please do follow up if it works or in case you have other questions.

**Comment by OrangeDog** [comment]
> if you just use a shell command to invoke, `pytest || true` ?

The problem with that is you then miss all the other exit codes that should indicate a build failure.

**Comment by parched** [comment]
> > if you just use a shell command to invoke, `pytest || true` ?
> 
> The problem with that is you then miss all the other exit codes that should indicate a build failure.

This should work as exit code one explicitly means test failures, but I think an argument for it would be better
```
pytest || [ $? = 1 ]
```
