### ISSUE TITLE
set comparison assertion failures less descriptive in v3 than in v2

### ISSUE THREAD

**Issue by cjellick** [pytest-dev/pytest#1972]
When you compared two sets in v 2.X and the assertion failed, you got useful output like this:
```
>       assert set_a == set_b
E       assert set(['c', 'd', 'r', 'u']) == set(['c', 'd', 'r'])
E         Extra items in the left set:
E         'u'
E         Use -v to get the full diff
```

in 3.X you get this:
```
>       assert set_a == set(set_b)
E       AssertionError
```

**Comment by RonnyPfannschmidt** [comment]
@cjellick this looks like your code was imported either outside of assertion rewriting or before it was enabled

**Comment by cjellick** [comment]
Thanks for the quick response @RonnyPfannschmidt. Sorry if this should not have been reported.
Is there any documentation that you could point me at that explains this concept of assertion rewriting?

**Comment by RonnyPfannschmidt** [comment]
its fine to report, its not necessarily easy to instantly know the issue and its a quick way to get an answer

http://docs.pytest.org/en/latest/writing_plugins.html#assertion-rewriting and the following sections are a help

**Comment by cjellick** [comment]
We've been using 2.X for a couple years (most recently 2.7.1) without issue and with the expected verbose output. This only appeared once we upgraded to 3.X. We're on python 2.7.X.

**Comment by RonnyPfannschmidt** [comment]
3.x removed half broken unmaintained fallback code

**Comment by The-Compiler** [comment]
To elaborate on what @RonnyPfannschmidt said: pytest had assertion rewriting (the abstract syntax tree gets rewritten to get verbose assertions) and assertion reinterpretation (assertions get run twice with the information collected the second time).

The latter is problematic as it was only used in special cases like yours, and also is troublesome with assertions with side-effects.

That code was removed in pytest 3.0, and only rewriting is used - however, it's only used selectively, to not mess with code under test.

More specificially, it's used for `test_*.py` files and `conftest.py` files. For anything else (like a helper module you import from there), you should call `pytest.register_assert_rewrite` like mentioned in the documentation ronny linked.

**Comment by nicoddemus** [comment]
(@the-compile beat me to it by a few minutes 😁 )

To help you out, in which file is the code `assert set_a == set_b` you posted?

**Comment by cjellick** [comment]
Ah, I see. Yes, the function doing that assertion is indeed in a helper module.
Thank you all for your patience and detailed explanations.

**Comment by The-Compiler** [comment]
I'm closing this then - but if anything is still unclear, feel free to ask!

**Comment by nicoddemus** [comment]
Calling `pytest.register_assert_rewrite`  to the top of your root `conftest.py` file before importing the helper module should be sufficient:

```python
import pytest
pytest.register_assert_rewrite('project.helper')

import project.helper
```
