### ISSUE TITLE
pytest not finding any tests under module

### ISSUE THREAD

**Issue by grantmcconnaughey** [pytest-dev/pytest#1978]
I am working on a Django 1.9 application. When I run `pytest` it picks up tests in all the directories *except* the `build` directory. The `build` directory has a `tests` directory just like all of the other modules. Inside of `tests` is `test_models.py`, `test_utils.py`, and `test_views.py`.

When I run `pytest myapp/apps/build/` then it picks up the tests just fine. But when I simply run `pytest` (or `pytest myapp/apps/`) then the build directory is completely excluded.

`myapp.apps.build` _is_ in my `INSTALLED_APPS` setting, so that is not the issue. I've tried removing the `__init__.py` file from the `build/tests/` and that did not work. Is the name "build" reserved to pytest or something?

Here is the output:

```
=== test session starts ===
platform linux2 -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
Django settings: myapp.settings.testing (from ini file)
rootdir: /code, inifile: pytest.ini
plugins: django-3.0.0
collected 66 items

myapp/apps/authentication/tests/test_models.py ......
myapp/apps/core/tests/test_core_tags.py ...........
myapp/apps/core/tests/test_validators.py ........
myapp/apps/hooks/tests/test_utils.py ............
myapp/apps/hooks/tests/test_views.py ....
myapp/apps/issues/tests/test_models.py .
myapp/apps/issues/tests/test_views.py ..
myapp/apps/notifications/tests/test_models.py ........
myapp/apps/project/tests/test_decorators.py ....
myapp/apps/project/tests/test_models.py ...
myapp/apps/project/tests/test_views.py .......
```

Here is my project structure. I've truncated all of the apps except build.

```
├── myapp
│   ├── __init__.py
│   ├── apps
│   │   ├── __init__.py
│   │   ├── authentication
│   │   │   ├── __init__.py
│   │   │   ├── tests
│   │   ├── build
│   │   │   ├── __init__.py
│   │   │   ├── admin.py
│   │   │   ├── constants.py
│   │   │   ├── factories.py
│   │   │   ├── managers.py
│   │   │   ├── tests
│   │   │   │   ├── __init__.py
│   │   │   │   ├── test_models.py
│   │   │   │   ├── test_utils.py
│   │   │   │   └── test_views.py
│   │   │   ├── urls.py
│   │   │   ├── utils.py
│   │   │   ├── views.py
│   │   ├── core
│   │   │   ├── __init__.py
│   │   │   ├── tests
│   │   ├── hooks
│   │   │   ├── __init__.py
│   │   │   ├── tests
│   │   ├── issues
│   │   │   ├── __init__.py
│   │   │   ├── tests
│   │   ├── notifications
│   │   │   ├── __init__.py
│   │   │   ├── tests
│   │   ├── project
│   │   │   ├── __init__.py
│   │   │   ├── tests
```

**Comment by nicoddemus** [comment]
Hi,

That's strange, it should be picking up the tests. Could you please show the contents of your `pytest.ini` file? Also, can you provide a reproducible example or a public repository which exhibits the problem?

**Comment by tomviner** [comment]
`build` is in the default `norecursedirs` setting:
> Default patterns are '.*', 'build', 'dist', 'CVS', '_darcs', '{arch}', '*.egg'

See http://doc.pytest.org/en/latest/customize.html#confval-norecursedirs

@grantmcconnaughey you can override this with a `pytest.ini` file containing, for example just the other default directories not to recurse into, but without "build":
```ini
[pytest]
norecursedirs = .* dist CVS _darcs {arch} *.egg
```

**Comment by grantmcconnaughey** [comment]
@tomviner Thank you, that fixed it!

**Comment by tomviner** [comment]
@grantmcconnaughey \0/
