### ISSUE TITLE
Parallel tests break capsys.disabled() context manager

### ISSUE THREAD

**Issue by jackmac92** [pytest-dev/pytest#1991]
I'm having selenium webdriver tests store chrome console messages and would like all test runs to print certain log messages. I have a finalizer fixture setup to print these messages, using `with capsys.disabled():`. This works as intended unless I run the tests in parallel, even `-n 1` causes the finalizer to raise `AttributeError: CaptureFixture instance has no attribute 'disabled'`.  Capsys.disabled provides the precise functionality I'm looking for, is there any way to make it work with xdist parallel tests?

py.test 3.03
pytest-xdist 1.15
Python 2.7.12

**Comment by RonnyPfannschmidt** [comment]
xdist currently does not support printing or usage without capture

**Comment by nicoddemus** [comment]
We should probably mention that in pytest's xdist README, this question comes up quite frequently.

I'm closing this because it is really not actionable right now.
