### ISSUE TITLE
XPass is not documented on site

### ISSUE THREAD

**Issue by AutomatedTester** [pytest-dev/pytest#1997]
When looking to setup XPasses in a test suite. When looking how to do this could only find [skipping/xfail](http://docs.pytest.org/en/latest/skipping.html) and the [TOC](http://docs.pytest.org/en/latest/contents.html#toc) doesnt have it.

Here's a quick checklist in what to include:
- [X] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by The-Compiler** [comment]
There's nothing to set up - xpass simply means a test marked as `xfail` (expected to fail) did unexpectedly pass.

The skipping/xfail docs briefly mention that:

> Instead terminal reporting will list it in the “expected to fail” (`XFAIL`) or “unexpectedly passing” (`XPASS`) sections.

I'm not sure what else we could add to make this more clear - do you have an idea?

**Comment by davehunt** [comment]
I believe @AutomatedTester was specifically looking for a way to report XPasses in the summary. The documentation currently mentions including skips and xfails with `-rsx` but does not mention XPasses, which would be shown by using `rsxX` or even `-ra`. It's also not made clear that imperative xfails could never xpass - it was his understanding that they could.

**Comment by xuanluong** [comment]
I guess this can be closed, @RonnyPfannschmidt @nicoddemus ?

**Comment by RonnyPfannschmidt** [comment]
thanks for the note
