### ISSUE TITLE
Using fixture decorator as a function

### ISSUE THREAD

**Issue by westhomas** [pytest-dev/pytest#2001]
I have an autogenerated unit test class that I'd like to decorate with a fixture for some injected functionality. Knowing that decorators are "just functions" led me to something like this...

``` python
import logging
import random
import unittest
from pytest import fixture, mark

logger = logging.getLogger(__name__)

@fixture(scope='class')
def unique_bed(request, worker_id):
    request.cls.bed = random.randint(1, 12)

def _build_config_test_case_class():
    test_case_class = type('TestConfig', (unittest.TestCase,), {})

    def test_method(cls):
        logger.debug(cls.__class__)
        logger.debug(cls.bed)

    setattr(test_case_class, "test1", test_method)
    setattr(test_case_class, "test2", test_method)
    setattr(test_case_class, "test3", test_method)

    return mark.usefixtures(test_case_class, "unique_bed")
    #return test_case_class #Returning the class works as expected

ConfigTestCase = _build_config_test_case_class()
```

However this leads to pytest being unable to find the "unittest.TestCase" base classes.

Perhaps my python-fu is just not strong enough to see the obvious answer, but what's the solution here? How can I keep my existing autogenerated test classes and add a fixture decorator programmatically?

(Editted by @nicoddemus: updated syntax highlight)

**Comment by nicoddemus** [comment]
Hi, sorry for the delay.

I think the simplest solution is to decorate your class with the [`usefixtures` marker](http://doc.pytest.org/en/latest/unittest.html?highlight=usefixtures#mixing-pytest-fixtures-into-unittest-testcase-style-tests):

```python
@pytest.mark.usefixtures('unique_bed')
class TestConfig(unittest.TestCase):
    ...
```

**Comment by westhomas** [comment]
But I don't have a class declaration. It's generated using `type()`.

**Comment by nicoddemus** [comment]
Oh my bad, completely missed this line:

```python
return mark.usefixtures(test_case_class, "unique_bed")
```

If you add this to your test case:

```python
print(ConfigTestCase)
```

You will see that it is not really the class being returned, but a `MarkDecorator` instance:

```
<MarkDecorator 'usefixtures' {'args': (<class 'foo.TestConfig'>, 'unique_bed'), 'kwargs': {}}>
```

What's happening is:

A decorator is a syntax sugar, so the two are equivalent:

```python
@dec
class T:
    pass

# Equivalent to:
T = dec(T)
```

A decorator with an argument is a little different in that it should return a callable which is then applied to the class:

```python
@dec('param')
class T:
    pass

# Equivalent to:
T = dec('param')(T)
```

So you have to change your example to:

```
return mark.usefixtures("unique_bed")(test_case_class)
```

**Comment by westhomas** [comment]
This was very helpful. Thanks!
