### ISSUE TITLE
Add a way to get "--collectonly" output as a Python list

### ISSUE THREAD

**Issue by Alphare** [pytest-dev/pytest#2002]
Hi,
I'm trying to force tests in certain files to have the same name as the function they test (but with a `test_` prefix). I seem to have the only option of parsing the output of a `--collectonly` call within my `conftest.py` file... maybe I'm mistaken, please enlighten me if that's the case.
Stepping through pytest's code, I saw that `Session.perform_collect()` seems to return an `items` list which contains every test present in the output of the `--collectonly` call. I would love to have access to that list without building a `Session` object, a `config`, etc..
I will resort to parsing for now, thanks in advance.

**Comment by RonnyPfannschmidt** [comment]
more context is needed, but it seems like you can just hook into makeitem as a hookwrapper to take a look at each test as it is collected

**Comment by Alphare** [comment]
I don't want to operate while the test is collected, I want to get a list of all my tests to prevent testing if any functions in a file don't have a test with the same name (save the prefix).

**Comment by RonnyPfannschmidt** [comment]
intercepting a collect report for files in that folder seems pretty helpful then,

the idea is that after the collection of a file you can take a look at all items it contains

**Comment by Alphare** [comment]
@RonnyPfannschmidt:
Sorry, I now understand what you said. I looked into the plugins doc and using `pytest_collection_modifyitems` is indeed the answer to my problem. Thank you for pointing me towards the right direction.
Cheers.
