### ISSUE TITLE
Pytest options with more than one metavar don't have the correct help

### ISSUE THREAD

**Issue by okulynyak** [pytest-dev/pytest#2004]
automated_test_scripts\tests>pytest -v -s --firefox-preference="browser.helperApps.neverAsk.openFile"="application/excel" test_login.py"
i got error:
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --firefox-preference: expected 2 argument(s).
I tried different combination and all the time i got the same error.
I using a synthax in command line from >pytest -h

Here is link for temporary resolve of this problem: https://github.com/pytest-dev/pytest-selenium/issues/86#issuecomment-253465732

Thanks for your time

**Comment by davehunt** [comment]
To give a little more context, pytest-selenium uses [a command line option](https://github.com/pytest-dev/pytest-selenium/blob/fc542e21a30cc0e3b7e401a829595434b240daf6/pytest_selenium/drivers/firefox.py#L15-L21) that appends values to a list, and expects two arguments. In the `--help` text this is indicated by the `--name=value1=value2` prompt, however this doesn't work as expected. It is necessary to use `--name value1 value2` instead.

**Comment by nicoddemus** [comment]
Thanks @davehunt and @okulynyak for the report.

Not sure how easy it is to fix this though, pytest's argument parsing is quite complicated (I think).

**Comment by The-Compiler** [comment]
FWIW `--name=value1=value2` for an argument with two values seems like an odd syntax to me, does that work with other tools? IMHO the right thing to do here is just fixing the `--help` output to show `--name value1 value2`.

**Comment by okulynyak** [comment]
Hi. As for me, i vote for The-Compiler says: "IMHO the right thing to do here is just fixing the --help output to show --name value1 value2."
it is a weard a little bit to see something like --something=something=something

**Comment by nicoddemus** [comment]
Oh right sorry, TBH I just glanced at the issue before bed and thought we would have to change the parsing of the option. My bad. 

I agree, we should just update the help message.
