### ISSUE TITLE
False-positive warning about assertion rewrite 

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2005]
Consider:

```python
# contents of conftest.py
pytest_plugins = 'plugin1'

# contents of test_foo.py
pytest_plugins = 'plugin1'

def test():
   pass

# plugin1.py is an empty file
```

`pytest-3.0.3` provides this warning:

```
WP1 None Modules are already imported so can not be re-written: plugin1
```

But this is a false positive; what happens is that the code which verifies that a module needs to be rewritten but is already imported doesn't remember that the file was already rewritten on import.

**Comment by RonnyPfannschmidt** [comment]
this is a duplicate ^^

**Comment by RonnyPfannschmidt** [comment]
#1840

**Comment by nicoddemus** [comment]
Oh right. Do you mind if we close the other one? This one contains more information. 😁
