### ISSUE TITLE
Deselecting class prefixed with "Test"

### ISSUE THREAD

**Issue by syre** [pytest-dev/pytest#2007]
Is it possible to deselect a class prefixed with "Test" from collection without renaming it?

The class is imported from several test modules and thus generates several warnings:
`====================================== pytest-warning summary =======================================
WC1 /vagrant/publish/marketplace/tests/test_models.py cannot collect test class 'TestPrintProduct' because it has a __init__ constructor
WC1 /vagrant/publish/marketplace/tests/test_signals.py cannot collect test class 'TestPrintProduct' because it has a __init__ constructor
WC1 /vagrant/publish/salechannels/tests/test_signals.py cannot collect test class 'TestPrintProduct' because it has a __init__ constructor`

i've tried the following to no avail:
- the pytest.mark.skip decorator on the class
- setting __test__ = False on the class as attribute
- k flag with "not TestPrintProduct"

**Comment by syre** [comment]
From correspondences on IRC, it seems the only way to ignore the warnings is a conftest.py file containing the following:

`import pytest


@pytest.hookimpl(tryfirst=True)
def pytest_pycollect_makeitem(collector, name, obj):
    if name == "TestPrintProduct":
        return IgnoreCollector(name, parent=collector)


class IgnoreCollector(pytest.Collector):
    def collect(self):
        return []

    def reportinfo(self):
        return ""
`

**Comment by The-Compiler** [comment]
FWIW I'd expect setting `__test__ = False` to work, but it doesn't

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler the code involved warns before that attribute is ever tested

**Comment by nicoddemus** [comment]
> the code involved warns before that attribute is ever tested

But should be fixable, right? Setting `__test__ = False` seems like an acceptable workaround.

**Comment by lwm** [comment]
Oh, we forgot to close this one too ;)

**Comment by nicoddemus** [comment]
@lwm in the future, you can add a string like `Fix #2007` to the commit message so the issue will be closed automatically when the PR gets merged. More info [here](https://help.github.com/articles/closing-issues-via-commit-messages/). 😉

**Comment by lwm** [comment]
Sure, will do. Thanks!
