### ISSUE TITLE
Installing by copying folder and running like unittest

### ISSUE THREAD

**Issue by vlad1777d** [pytest-dev/pytest#2025]
Hello dear friends.

Sorry, I did not knew where to write, but what do you think about such idea to place
pytest near project by simple copying (in pytest folder would be all needed dependencies) or by adding it's folder's address to sys.path (without pip)?

And about running it just like unittest:
`import pytest`
at first of file, and
`pytest.main()`
to run tests themselves?

Because it's not comfortable to install and use it now when I need portable program with it's testing modules included with only Python 3 interpreter installed on target machine.

Best regards,
Vladislav

**Comment by The-Compiler** [comment]
You [can do the latter](http://docs.pytest.org/en/latest/usage.html#pytest-main-usage) though that's not typically done inside the test files - why would you want to?

I'm not sure about the former, it might just work. But why can't you just install pip?

**Comment by vlad1777d** [comment]
@The-Compiler , thank you very much. I had not read about this in manual.

I don't want use pip because of these matters: https://pythonrants.wordpress.com/2013/12/06/why-i-hate-virtualenv-and-pip/

Also I would get confused with three package managers: one - syste (apt) and for two languages two package managers. It's too much for me. 

I make my programs so, that if to move them to another directory, they'll find their dependencies in subdirectories. It's much easier for me to make simulink to folder with complete package to add relative path to sys.path, than confusing with three package managers. 
I prefer installing system packages with apt, all other - manually without changing environment variables.

**Comment by RonnyPfannschmidt** [comment]
@vlad1777d that article amends itself at the first paragraph ^^

**Comment by vlad1777d** [comment]
@RonnyPfannschmidt , but it's not convenient anyway =)

**Comment by RonnyPfannschmidt** [comment]
@vlad1777d why not just store a set of wheel files and add them to sys.path

**Comment by vlad1777d** [comment]
@RonnyPfannschmidt , I tried to do so:
![2016-10-24 20-35-12](https://cloud.githubusercontent.com/assets/12682937/19656622/6f9652d8-9a29-11e6-90f7-bf9c9c912d24.png)

**Comment by nicoddemus** [comment]
Perhaps [rwt](https://pypi.org/project/rwt/) can help?

**Comment by The-Compiler** [comment]
You'd also need to install pytest's dependencies (the `py` library) by hand this way...

I really fail to see how whatever you're doing would be more convenient than simply doing `pip install pytest` and running `pytest` (optionally adding a `virtualenv .venv; ./.venv/bin/activate` before, or using `pip install --user`).

**Comment by RonnyPfannschmidt** [comment]
also closing this since its not an issue with py.test, but an issue with how op choose to deploy it

**Comment by vlad1777d** [comment]
@The-Compiler , the problem is in what I already downloaded and py module.
I added it's location to sys.path, but pytest doesn't see it.

I could edit pytest and add there pattern to search for py's location by relative path, but after pytest will update, I would need to edit this again.

Also the py library is used only for pytest, as I understood, so it would be great to combine this two packages to one (py will be in subdirectory and pytest will search for it by relative path, doesn't matter where user placed folder with them).

I could make this for myself, but after update of pytest I'll need to make this again.

So I suggested to add such possibility to the pytest itself. User could download .tar.gz archive with newest module, than place it whenever he wants and make only one import:
`import pytest` (he'll add path to pytest to sys.path or to environment variable)
And after this to run tests just like unittest does:
`pytest.main()`,
or by the standart way - from command line.

Do you think it's a rare problem for myself?

**Comment by The-Compiler** [comment]
> Also the py library is used only for pytest, as I understood, so it would be great to combine this two packages to one

It's not. It's used for other projects like tox too.

> Do you think it's a rare and invented problem, or, my way is too long?

I do think you're making things much more complicated than they would be when just using the easy way everyone else uses :wink:

**Comment by vlad1777d** [comment]
I got stacked with 
![2016-10-25 02-47-28](https://cloud.githubusercontent.com/assets/12682937/19668017/69d5ff4a-9a5d-11e6-9579-b41fcbc1a750.png)

I know, that I could read this all: http://doc.pytest.org/en/latest/customize.html , but I'm tired.
Maybe my way is to use unittest and do not go here )
