### ISSUE TITLE
Please include test ordering as a standard feature in pytest

### ISSUE THREAD

**Issue by mherkazandjian** [pytest-dev/pytest#2029]
This has been already implemented as a plugin, but it would be nice to have it as a default feature.

https://github.com/ftobia/pytest-ordering/
pip install pytest-ordering

**Comment by The-Compiler** [comment]
Why not keep it as a plugin?

**Comment by mherkazandjian** [comment]
maintenance. it is a useful feature and could break in the future in not maintained properly.

**Comment by nicoddemus** [comment]
> maintenance. it is a useful feature and could break in the future in not maintained properly.

IMHO, that's not a good reason to move it to the core, but it is a good reason to ask the plugin to be moved to the pytest-dev organization. Also, the plugin seems to be maintained just fine.

Created ftobia/pytest-ordering#32 for it, so I'm closing this for now. @mherkazandjian please feel free to reopen if you want to.

**Comment by RonnyPfannschmidt** [comment]
At first glance, doesn't this break setup order reordering, which is a important feature

**Comment by mherkazandjian** [comment]
i am not really sure how the plugin works... i thought i'd ask a quick question about the idea i had.

**Comment by nicoddemus** [comment]
>  i thought i'd ask a quick question about the idea i had.

Sure, no worries!

**Comment by mherkazandjian** [comment]
cool :)
