### ISSUE TITLE
ensure compat properties trigger DeprecationWarnings

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2034]
https://github.com/pytest-dev/pytest/blob/master/_pytest/main.py#L191

should do a warnings.warn so we can safely remove later on

**Comment by lwm** [comment]
Is there some policy on adding these warnings (ala Django's [deprecation](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#deprecating-a-feature) docs)? Maybe not important on this one in particular ...

**Comment by nmundar** [comment]
https://github.com/pytest-dev/pytest/pull/2088

**Comment by nicoddemus** [comment]
> Is there some policy on adding these warnings (ala Django's deprecation docs)?

Our policy is written here: http://doc.pytest.org/en/latest/backwards-compatibility.html

It is very recent though so we are still maturing it.

**Comment by lwm** [comment]
Oh, nice one, thanks for passing that link @nicoddemus!

**Comment by nicoddemus** [comment]
Fixed by #2088
