### ISSUE TITLE
Collection failure for setuptools extension wrapper scripts 

### ISSUE THREAD

**Issue by marscher** [pytest-dev/pytest#2035]
When testing an (installed) setuptools package via the pyargs argument, I get a py._path.local.LocalPath.ImportMismatchError, because the wrapper has a .py extension, wraps around a .so and is given by a dotted name (recursion within the pyargs package).

python-3.5
pytest-3.0.3
pytest-cov-2.4.0
python-xdist-1.15
[full-env.txt](https://github.com/pytest-dev/pytest/files/561767/env.txt)

Maybe this is an user error (I would be glad). I wonder if this case can be handled somehow in the config (I tried to ignore the file in a package contained conftest.py like this:
```
collect_ignore=['covartools.py']
```
However the file still causes the collection error, eg. it is considered/inspected by py, which leads to the following error.

The covartools.py is a wrapper script generated by setuptools with the following contents:
```
def __bootstrap__():
    global __bootstrap__, __loader__, __file__
    import sys, pkg_resources, imp
    __file__ = pkg_resources.resource_filename(__name__, 'covartools.cpython-35m-x86_64-linux-gnu.so')
    __loader__ = None; del __bootstrap__, __loader__
    imp.load_dynamic(__name__,__file__)
__bootstrap__()
```
Note that this file is only generated on Python3+, as part of setuptools bdist_egg command:
https://github.com/pypa/setuptools/blob/7d984bbdc111fcdfef816265e159a3054dbee132/setuptools/command/bdist_egg.py#L42

The error message looks like this:
``` 
collection failure
/home/ubuntu/miniconda/conda-bld/conda-recipe_1477764720844/_t_env/lib/python3.5/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('pyemma._ext.variational.covar_c.covartools', '/home/ubuntu/miniconda/conda-bld/conda-recipe_1477764720844/_t_env/lib/python3.5/site-packages/pyEMMA-2.2.7+19.gfec3dac-py3.5-linux-x86_64.egg/pyemma/_ext/variational/covar_c/covartools.cpython-35m-x86_64-linux-gnu.so', local('/home/ubuntu/miniconda/conda-bld/conda-recipe_1477764720844/_t_env/lib/python3.5/site-packages/pyEMMA-2.2.7+19.gfec3dac-py3.5-linux-x86_64.egg/pyemma/_ext/variational/covar_c/covartools.py'))
```

So I think this case needs to be treated, since setuptools extensions are quite common. Pytest fails with a non-zero exit code because of these kind of collection errors.

**Comment by RonnyPfannschmidt** [comment]
the collect_ignore for a local file can't match a installed file

as far as i can tell this isn't easily solved - you might need to hook into collecting files

**Comment by marscher** [comment]
On 10/31/2016 02:35 PM, Ronny Pfannschmidt wrote:
> the collect_ignore for a local file can't match a installed file
> 
> as far as i can tell this isn't easily solved - you might need to hook into collecting files

Thanks for the quick reply. How do I hook into the collection mechanism?

**Comment by RonnyPfannschmidt** [comment]
my first idea to handle your problemn would be to hook into `pytest_collect_file` returning a colelctor that does not collect anything else 

here a untested example written from rough memory:
```
class NullCollector(pytest.Collector):
  def collect(self): return []
```

**Comment by marscher** [comment]
Thanks for the hint. I solved it with the pytest_ignore_collect hook.
