### ISSUE TITLE
isfile check fails within pytest

### ISSUE THREAD

**Issue by satra** [pytest-dev/pytest#2040]
the test below fails when running with `pytest test.py` but not with `pytest -s test.py`

- [X] `pip list` of the virtual environment you are using

```
$ pip list
pip (8.1.2)
py (1.4.31)
pytest (3.0.3)
setuptools (27.2.0)
wheel (0.29.0)
```

- [X] pytest and operating system versions

python 3.5.2
pytest 3.0.3
OS X (but i believe this fails on other OSes as well)

- [X] Minimal example if possible

```python
import os

def test_isfile():
    assert os.path.isfile(True) == False
```

**Comment by nicoddemus** [comment]
Oh wow, that's strange. Thanks for the report!

**Comment by nicoddemus** [comment]
It also passes with `pytest test.py --capture=sys`, so definitely has to do with file-descriptor capture.

**Comment by nicoddemus** [comment]
I think it's related to the fact that capfd is redirecting file descriptor `1` to a file, and `1` equals `True`. The same test fails if we pass `1` or `2` instead of `True` (equivalent to `stdout` and `stderr`), but not integers higher than that.

**Comment by The-Compiler** [comment]
I don't think this is a bug. The same code (which simply tests if `stdout` is a file, in a rather obfuscated way) also fails without pytest involved when doing `python foo.py > file`.

**Comment by satra** [comment]
@The-Compiler - you are correct in that python 3 treats `1` and `True` identically even though they have different datatypes. on python 2 this raises a TypeError.

would the recommendation for this test be to do: `with capfd.disabled():` ? we will also look to see if we can modify the upstream code that this is testing.

**Comment by The-Compiler** [comment]
`bool` is a subclass of `int` (`isinstance(True, int) == True`) both on Python 2 and Python 3. The reason this doesn't work on Python 2 is that `os.path.isfile` only accept paths (and not ints as file descriptors) there.

What's the point of this test, or how is the actual test looking like? At least with your minimal example, I think the test should just not exist at all :wink:

**Comment by satra** [comment]
essentially it's an embedded test of hashing a hierarchical dictionary. the key value pairs could have as value a file path. and the `os.path.isfile(value)` checks to see if it's a file and replaces the value with content hash of the file. since some of the values are `True` bools the test started failing with pytest, when it didn't fail with nose.

**Comment by nicoddemus** [comment]
I would recommend using `capfd.disabled()` in this case if it solves this specific problem. IMO this is a very edge-case and not much can be done on our side to fix this. Feel free to reopen if you feel otherwise and this warrants more discussion.
