### ISSUE TITLE
--setup-plan and --setup-only seem to claim different things

### ISSUE THREAD

**Issue by oscarh** [pytest-dev/pytest#2049]
I have the following example:
```python
from pytest import fixture


@fixture(scope='module')
def fixture1():
    print('Setup of fixture1')
    yield 'fixture1'
    print('Teardown of fixture1')


@fixture(scope='module')
def fixture2():
    print('Setup of fixture2')
    yield 'fixture2'
    print('Teardown of fixture2')


def test_1(fixture1):
    print('Running test with {}'.format(fixture1))


def test_2(fixture1, fixture2):
    print('Running test with {} and {}'.format(fixture1, fixture2))


def test_3(fixture2):
    print('Running test with {}'.format(fixture2))

```

When running with `--setup-plan`, I get the following output (indicating extra teardown of fixture1 and 2):
```
test_fixture_lifetime.py 
  SETUP    M fixture1
        test_fixture_lifetime.py::test_1 (fixtures used: fixture1)
  TEARDOWN M fixture1
  SETUP    M fixture1
  SETUP    M fixture2
        test_fixture_lifetime.py::test_2 (fixtures used: fixture1, fixture2)
  TEARDOWN M fixture2
  SETUP    M fixture2
        test_fixture_lifetime.py::test_3 (fixtures used: fixture2)
  TEARDOWN M fixture2
  TEARDOWN M fixture1
```

When running with `--setup-show`, the SETUP and TEARDOWN markers occur where my actual setup and teardown code executes:
```
test_fixture_lifetime.py Setup of fixture1

  SETUP    M fixture1
        test_fixture_lifetime.py::test_1 (fixtures used: fixture1)Running test with fixture1
.Setup of fixture2

  SETUP    M fixture2
        test_fixture_lifetime.py::test_2 (fixtures used: fixture1, fixture2)Running test with fixture1 and fixture2
.
        test_fixture_lifetime.py::test_3 (fixtures used: fixture2)Running test with fixture2
.Teardown of fixture2

  TEARDOWN M fixture2Teardown of fixture1

  TEARDOWN M fixture1
```

**Comment by sallner** [comment]
Hi @oscarh,
could you state your expectations a little bit clearer? Are you surprised, that in your first output, the setup and teardown is announced more often than they would actually occur? I try to have a look into it over the weekend, but as far I remember, it was not straightforward to arrange the fixtures at this point of collection.

**Comment by oscarh** [comment]
Hi @sallner,

Sorry about the late reply. As you have guessed, I was surprised that the setup and teardown are printed more ofter than they're executed. In other words, the plan, and what happens seem to differ.

**Comment by ts-mk** [comment]
This is really confusing. While both `--setup-show` and `--setup-only` display the setup correctly, `--setup-plan` makes no sense.

**Comment by blueyed** [comment]
The plugin implementing this is https://github.com/pytest-dev/pytest/blob/cc464f6b96e59deafbe1e393beba7a21351c2e9d/src/_pytest/setupplan.py - in case you want to investigate / fix this.
