### ISSUE TITLE
Unhelpful traceback while trying to create a helper context manager based on raises

### ISSUE THREAD

**Issue by jck** [pytest-dev/pytest#2057]
I'm trying to create a helper function to simplify a common case in a test suite. For example:

```
from contextlib import contextmanager

import pytest

@contextmanager
def raises_value(exc, val):
    __tracebackhide__ = True
    with pytest.raises(exc) as e:
        yield
    assert str(e.value) == val

def test_raisesvalue():
    with raises_value(ValueError, 'a'):
        raise ValueError('b')
```

This works fine, but the traceback is not very helpful.

with `__tracebackhide__`:
```
========================================== FAILURES ===========================================
______________________________________ test_raisesvalue _______________________________________

exc = <class 'ValueError'>, val = 'a'

    @contextmanager
    def raises_value(exc, val):
        __tracebackhide__ = True
        with pytest.raises(exc) as e:
>           yield

rais.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def test_raisesvalue():
        with raises_value(ValueError, 'a'):
>           raise ValueError('b')
E           ValueError: b

rais.py:14: ValueError

During handling of the above exception, another exception occurred:

    def test_raisesvalue():
        with raises_value(ValueError, 'a'):
>           raise ValueError('b')

rais.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <contextlib._GeneratorContextManager object at 0x7f549282b9e8>
type = <class 'ValueError'>, value = ValueError('b',)
traceback = <traceback object at 0x7f549283bbc8>

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
                next(self.gen)
            except StopIteration:
                return
            else:
                raise RuntimeError("generator didn't stop")
        else:
            if value is None:
                # Need to force instantiation so we can reliably
                # tell if we get the same exception back
                value = type()
            try:
>               self.gen.throw(type, value, traceback)
E               assert 'b' == 'a'
E                 - b
E                 + a

/usr/lib/python3.5/contextlib.py:77: AssertionError
```

Without `__tracebackhide__`:

```========================================== FAILURES ===========================================
______________________________________ test_raisesvalue _______________________________________

exc = <class 'ValueError'>, val = 'a'

    @contextmanager
    def raises_value(exc, val):
        with pytest.raises(exc) as e:
>           yield

rais.py:8: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def test_raisesvalue():
        with raises_value(ValueError, 'a'):
>           raise ValueError('b')
E           ValueError: b

rais.py:13: ValueError

During handling of the above exception, another exception occurred:

    def test_raisesvalue():
        with raises_value(ValueError, 'a'):
>           raise ValueError('b')

rais.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.5/contextlib.py:77: in __exit__
    self.gen.throw(type, value, traceback)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

exc = <class 'ValueError'>, val = 'a'

    @contextmanager
    def raises_value(exc, val):
        with pytest.raises(exc) as e:
            yield
>       assert str(e.value) == val
E       assert 'b' == 'a'
E         - b
E         + a

rais.py:9: AssertionError


```

**Comment by brianmaissy** [comment]
This seems unnecessary now that `pytest.raises` takes the `match` keyword, I recommend to close.

**Comment by RonnyPfannschmidt** [comment]
indeed, thanks for bringing it to attention

**Comment by nyh** [comment]
Even though the original requester's need was solved with raises(match=...), this is still a problem for other similar helpers that people might want to write. For example, I wanted to use the following helper for allowing some code with either pass - or throw a specific exception:

```python
# raises_or_not is similar to pytest.raises(), except that while raises()
# expects a certain exception must happen, the new raises_or_not() function
# expects the code to either *succeed*, or if it throws, it should throw the
# specific specified exception.
@contextmanager
def raises_or_not(expected_exception, match=None):
    __tracebackhide__ = True
    try:
        yield
        # The user's "with" code is running during the yield. If it didn't
        # throw we return from the function - the raises_or_not() passed as
        # the "or not" case.
        return
    except expected_exception as err:
        if match == None or re.search(match, str(err)):
            # The raises_or_not() passed on as the "raises" case
            return
        pytest.fail(f"exception message '{err}' did not match '{match}'")
    except Exception as err:
        pytest.fail(f"Got unexpected exception type {type(err).__name__} instead of {expected_exception.__name__}: {err}")
```

The backtrace is full of unhelpful pieces of stack, which `__tracebackhide__ = True`  doesn't eliminate, and like @jck I couldn't figure out how to elliminate them.

**Comment by bluetech** [comment]
@nyh Can you show an example?

If I had to guess, `@contextmanager` is causing the trouble, so first I'd try to get rid of it in favor of an explicit context manager (a class which implements `__enter__`/`__exit__`). [Here's](https://github.com/pytest-dev/pytest/blob/df033f3ab1ee6d965fdcf04d9d28e72155bc39f9/src/_pytest/python_api.py#L933) what pytest.raises itself uses.

**Comment by altendky** [comment]
Yes, you can work around this by by writing out the generally more verbose and harder to manage enter and exit class form.  No, that does not alleviate the value of being able to combine the two useful idea of traceback frame hiding and the context manager decorator for functions.  I personally think the request stands as valid and useful, even if what the specific example creates is now provided directly.  My case is a context manager for code to be benchmarked that handles GC preparation, time measurement, and time limit assertion.

**Comment by altendky** [comment]
I'm still working on cleanup, but here's my actual code.  https://github.com/Chia-Network/chia-blockchain/pull/11589/files#diff-da330cc758138bafc4cf701b1dc8a0e489598b43c6c38940ba0bfb3c4c8106b3R278

Other similar tooling, such as [`warnings.warn()](https://docs.python.org/3.10/library/warnings.html#warnings.warn)`, let you control not just the local stack frame but some number above as well.  I know it isn't exactly the same situation, but I think it is relevant to consider.  If that were supported then we could specify extra layers as needed to account for the overhead of `@contextlib.contextmanager`.  Of course, that depends in the internal implementation of the decorator which makes it fragile.  That's certainly a point against encouraging developers to do this.  Curiously, since `True` is an instance of `int` with a value of `1`, we could just switch to allowing `__tracebackhide__ = 5` as well and be backwards compatible.  `:]`

Anyways, maybe there's another cleaner alternative.  Just putting the thoughts out in case anyone else is interested.

**Comment by altendky** [comment]
I fiddled briefly with:

```python
    def getcrashentry(self) -> TracebackEntry:
        """Return last non-hidden traceback entry that lead to the exception of a traceback."""
        layers = 0
        for i in range(-1, -len(self) - 1, -1):
            entry = self[i]
            layers = max(layers, entry.ishidden())
            if layers < 1:
                return entry
            layers -= 1
        return self[-1]
```

But we actually pre-filter differently with:

```python
    def filter(
        self, fn: Callable[[TracebackEntry], bool] = lambda x: not x.ishidden()
    ) -> "Traceback":
        """Return a Traceback instance with certain items removed

        fn is a function that gets a single argument, a TracebackEntry
        instance, and should return True when the item should be added
        to the Traceback, False when not.

        By default this removes all the TracebackEntries which are hidden
        (see ishidden() above).
        """
        return Traceback(filter(fn, self), self._excinfo)
```

So even if this were a good API to provide, there would be a bit more to figure out around the duplicate filtering.  But, that also gives me another lead to look at for options.

**Comment by altendky** [comment]
https://github.com/pytest-dev/pytest/issues/283 could be another approach for this specific case by blacklisting the contextlib layers, potentially.
