### ISSUE TITLE
Failing tests in 3.0.4 due to warnings

### ISSUE THREAD

**Issue by thmo** [pytest-dev/pytest#2069]
In 3.0.4, `pytest_funcarg__` being deprecated causes a whole bunch of pytest's own tests to fail.

They are looking for strings like `*2 failed in*` but get `2 failed, 1 pytest-warnings in`, or `*=== 3 passed in *` and get `=== 3 passed, 1 pytest-warnings in ` instead.

Here's the list of failed tests:
```
testing/code/test_excinfo.py:1121
testing/python/collect.py:1229
testing/python/collect.py:603
testing/python/collect.py:616
testing/python/collect.py:629
testing/python/collect.py:642
testing/python/collect.py:655
testing/python/collect.py:668
testing/python/metafunc.py:1091
testing/python/metafunc.py:1112
testing/python/metafunc.py:1127
testing/python/metafunc.py:1152
testing/python/metafunc.py:921
testing/python/metafunc.py:933
testing/test_cache.py:285
testing/test_cache.py:57
testing/test_capture.py:440
testing/test_collection.py:727
testing/test_collection.py:747
testing/test_doctest.py:443
testing/test_doctest.py:681
testing/test_doctest.py:710
testing/test_doctest.py:736
testing/test_pastebin.py:50
testing/test_pastebin.py:70
testing/test_recwarn.py:156
testing/test_recwarn.py:227
testing/test_terminal.py:841
```

**Comment by nicoddemus** [comment]
It is passing on Travis and AppVeyor currently and we don't have any fixtures declared using the deprecated  `pytest_funcarg__ ` prefix. How are you executing the tests?

**Comment by thmo** [comment]
I am running
```
PATH=%{buildroot}%{_bindir}:${PATH} \
PYTHONPATH=%{buildroot}%{python2_sitelib} \
  %{buildroot}%{_bindir}/pytest-%{python2_version} -r s testing --timeout=20
```
i.e., in the top-level dir of the unpacked sources, I run `pytest -r -s testing`.
(See http://pkgs.fedoraproject.org/cgit/rpms/pytest.git/tree/pytest.spec#n137, which is the spec file for 3.0.3, but the spec file is basically the same for 3.0.4.)

**Comment by RonnyPfannschmidt** [comment]
@thmo what other py.test plugins are installed while you run that?

**Comment by thmo** [comment]
Thanks for the hint. I had pytest-cov 2.2.1 installed system-wide.
