### ISSUE TITLE
Case Scenario long integration test - including reference data

### ISSUE THREAD

**Issue by wkerzendorf** [pytest-dev/pytest#2076]
This started out as a discussion with @RonnyPfannschmidt @nicoddemus and I thought I make an issue out of it to document it.

given the following scenario

```python

@pytest.fixture(params=['a', 'b', 'c'])
def parameter(request):
    return request.param

class TestClass():

    def setup(self, parameter):
        self.calculation = expensive_evaluation(parameter)

   def test_property_a(self):
      assert self.calculation == 'a'
```

What is the best way to run those. Let's for now assume these are the only tests.

**Comment by RonnyPfannschmidt** [comment]
@wkerzendorf a usefull way to disengage those is, to add a commandline arugment with choices

untested:
```
def pytest_addoption(parser):
  parser.addoption('--foo-kind', choice=['a', 'b', 'c'], default=None)

@pytest.fixture(params=['a', 'b', 'c'])
def calculation(request):
    if param is None:
        pytest.skip('--foo-kind is None')
    param = request.config.getoption('foo-kind')
    return expensive_evaluation(param)

class TestClass():

   def test_property_a(self, calculation):
      assert calculation == 'a'

```

**Comment by RonnyPfannschmidt** [comment]
now that the parameter is disengaged, the long running tests can be turned into a build matrix for example

**Comment by wkerzendorf** [comment]
@RonnyPfannschmidt that would now again work with `xdist` - because it essentially would only parallelize the parameterize?

**Comment by RonnyPfannschmidt** [comment]
it would not at all work with xdist

**Comment by wkerzendorf** [comment]
why not?

**Comment by RonnyPfannschmidt** [comment]
@wkerzendorf because the parameter is a cli option now, so each run would do only one variant

**Comment by wkerzendorf** [comment]
yes - me being stupid - sorry. But without the cli option it would work.

**Comment by RonnyPfannschmidt** [comment]
without the cli option it would skip, also not usefull

**Comment by nicoddemus** [comment]
Does this need more discussion or can be closed?

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of feedback
