### ISSUE TITLE
Add commands to the 'Writing Documentation' section

### ISSUE THREAD

**Issue by lwm** [pytest-dev/pytest#2086]
On the [Write documentation](http://docs.pytest.org/en/latest/contributing.html#id7) section, I couldn't find exactly how to get started easily. 

I was able to find out what I need to do:

``` bash
$ tox -e docs
$ firefox doc/en/_build/index.html
```

Then I could check my changes locally. I think it might be nice to add a note in the 'Writing documentation' section for those commands, especially for people not used to working with tox/sphinx/looking in the setup.cfg. 

Or it's written somewhere else?

I'll submit a PR if that is useful :beers:

**Comment by nicoddemus** [comment]
> I'll submit a PR if that is useful 

Yes please! We have decided for `tox -e docs` to be the official command for building documentation locally but never got around to write it somewhere.
