### ISSUE TITLE
Change `--junit-xml=path` to accept directories or change help text.

### ISSUE THREAD

**Issue by lwm** [pytest-dev/pytest#2089]
I was working on https://github.com/pytest-dev/pytest/issues/595 and ran into this.

When running:

``` bash
$ pytest --junit-xml=.
```

I receive a `IsADirectoryError: [Errno 21]` error.

What I need to pass to make this work is:

``` bash
$ pytest --junit-xml=somefile
```

Could `--junit-xml=.` default to create some report file? 

Otherwise, should the help text be altered to highlight that it must be a file name?

**Comment by nicoddemus** [comment]
I think we should warn the user that the option must be a filename and not an existing directory, similar that what was done in #2080.

The check would have to reside somewhere in `xunitxml.py` thought... I wonder if `argparse` doesn't support some validation mechanism for this instead?

**Comment by lwm** [comment]
> I wonder if argparse doesn't support some validation mechanism for this instead?

Well, it seems that `argparse` gives us a [type kwarg](https://docs.python.org/dev/library/argparse.html#type). Check the diff in https://github.com/pytest-dev/pytest/pull/2097
