### ISSUE TITLE
-s does not disable capturing if output is sent to --junit-xml due to cdist / nocapture incompatibility

### ISSUE THREAD

**Issue by bhatiardnb** [pytest-dev/pytest#2102]
From: https://github.com/pytest-dev/pytest/issues/680#issuecomment-217225049

> I'm using -n3 -d and each of my tests have print statements that are ignored by pytest. Im using pytest 2.9.1 and pytest-xdist-1.14.
> 
> py.test -sv -rx --color=yes -n3 -d --junit-xml=output.xml
> py.test -sv -rx --color=yes -n3 -d --junit-xml=output.xml --capture=no
> 
> How do I see stdout? Doesn't appear in my junit xml file either when I'm parallelizing the tests.

From: https://github.com/pytest-dev/pytest/issues/680#issuecomment-223664538

> currently cdist and nocapture is not compatible, the next major version of xdist will be

I thought it would be helpful to create this ticket to track the feature since the original ticket is closed.

**Comment by RonnyPfannschmidt** [comment]
closing this issue after making one in xdist
