### ISSUE TITLE
Plugin imports might use cwd sys.path entry

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#2104]
Here's an interesting one where I could use some advice.

In pypa/setuptools#852, I discovered that a plugin (pytest-flake8 by way of pyflakes and flake8) will `import setuptools` during plugin setup. For the setuptools project in particular, this poses a problem because that causes setuptools to be imported from the current directory and with a relative `__file__` attribute. Later, when the cwd has changed, that `__file__` attribute no longer resolves to the actual file path of the setuptools module, and a test fails.

My first question is - how is it that deferring the import of setuptools until later bypasses the issue? Is pytest doing something to the import mechanism to ensure that `__file__` attributes are absolute, but only after plugins have been setup? Or is pytest manipulating sys.path such that the relative path is replaced by an absolute path?

Then, the question becomes, what's the proper solution here? Should all plugins defer their third-party imports as late as possible? Should pytest protect the `__file__` attribute during plugin setup the same way it appears to be doing for later imports? What other options are there?

**Comment by RonnyPfannschmidt** [comment]
the common solution is to do develop installs and either use the src layout, or to skip having a __init__.py in the tests folder in order to keep py.test from adding the checkout itself to sys.path

in general its also advised to avoid chdir in tests without having rollback on failure

also note that even pytest itself imports at least pkg_ressources

**Comment by jaraco** [comment]
Please see [this minimal example in this comment](https://github.com/pypa/setuptools/issues/852#issuecomment-263907404). 

> the common solution is to do develop installs and either use the src layout, or to skip having a init.py in the tests folder in order to keep py.test from adding the checkout itself to sys.path

In the example, develop install is irrelevant (nothing is installed but dependencies). The test is simply run. The discrepancy exists in what the state of the sys.path when plugins are loaded versus when tests are run.

> in general its also advised to avoid chdir in tests without having rollback on failure

I'm pretty sure a fixture is being used to handle the rollback. That doesn't help when the issue occurs during the test run. In any case, chdir isn't relevant to the example I've presented, which simply is asserting that the imported package will have an absolute `__file__` attribute.

Do you know when it is that pytest prepends `abspath('.')` to the `sys.path` and why?

**Comment by RonnyPfannschmidt** [comment]
when conftests or test modules import roots are imported, py.test usually adds the absolute path of a module root (last parent folder with a `__init_.py`)

when running `python -m` the python interpreter itself adds `.` to pythonpath

**Comment by jaraco** [comment]
In that child ticket, I've worked out a workaround to monkeypatch the module path for modules resolved from the empty path, but I wonder if there's something pytest should be doing to ensure that `abspath('')` (or whatever module root resolves to) is added to `sys.path` before plugins are enumerated, thus working around the issue in general.

**Comment by RonnyPfannschmidt** [comment]
Python is at fault not pytest, please don't use python -m if you want a working sys.path

**Comment by jaraco** [comment]
Well, that's annoying. I would really have hoped that `python -m pytest` would behave identically to `py.test`, but I sort-of understand why that's not the case.

I in pypa/setuptools@5c940698, I did as you suggested and switched from using `python -m` to simple invocation, but as it turns out, that caused a new problem where the pytest plugins that setuptools itself supplies would no longer work, because they are excluded from a regular build. The error message was `ImportError: Error importing plugin "setuptools.tests.fixtures": No module named tests.fixtures`. Additionally adding `usedevelop` worked around that issue.

I hate how there are so many interleaved concerns in this issue (relative paths for `__file__` in older pythons, behavior of -m launcher and sys.path, timing of sys.path module root prepend).

It's still not obvious to me that it's necessary or intentional to only prepend the module root after plugins have been loaded. My instinct is it would be preferable to do that before plugins are loaded (for consistency in sys.path across those two steps), but I'm also willing to just accept that the behavior is how it is for a good reason and not worry too much about it.

With regard to the `python -m` behavior, I do think it's unlikely that this use case will provide sufficient justification to suggest that CPython be adapted to make `-m` launch not prepend `''` to sys.path. In fact [the docs explicitly state that the current directory will be added to sys.path](https://docs.python.org/3/using/cmdline.html#cmdoption-m). Given that, I still think it makes sense for something like pytest to compensate for this behavior and remove that from sys.path before launching, such that one could reasonably expect `-m` launch to match the behavior of the script launcher. Leaving the subtle differences in behavior just leaves open the possibility of more issues like this one arising.

**Comment by jaraco** [comment]
And I've found [there's already a bug filed about the inconsistency](http://bugs.python.org/issue16737).

**Comment by RonnyPfannschmidt** [comment]
@jaraco if you dont ship tests as part of a pacakge, dont put them into the package

**Comment by nicoddemus** [comment]
@jaraco any news or action points still to be done in this issue?

**Comment by jaraco** [comment]
> Given that, I still think it makes sense for something like pytest to compensate for this behavior and remove that from sys.path before launching, such that one could reasonably expect -m launch to match the behavior of the script launcher. Leaving the subtle differences in behavior just leaves open the possibility of more issues like this one arising.

> any news?

No news. I'm torn between this being an inevitable behavior of Python that should be avoided (i.e. avoid `python -m pytest`), something that should be corrected upstream in Python (by providing -nopath0 or another module invocation that matches script execution), or something that each application (pytest, pip, ...) should provide a workaround.

Let me push on the upstream ticket and see if there's any guidance from the core devs.

**Comment by nicoddemus** [comment]
Thanks! Please share a link if you have one. 👍

**Comment by jaraco** [comment]
Here's [what I said](https://bugs.python.org/issue16737#msg304662).

**Comment by steaksauce-** [comment]
No updates from upstream on two bug reports in quite sometime: 
https://bugs.python.org/issue16737#msg304662
https://bugs.python.org/issue31874

are there any plans to press the issue?

**Comment by nicoddemus** [comment]
I don't think there are plans to press the issue, and due to backward compatibility concerns I don't think this will change either.

I'm closing this as there's nothing really to do on pytest's side.
