### ISSUE TITLE
pytest alias in setup.cfg not working

### ISSUE THREAD

**Issue by dkirkby** [pytest-dev/pytest#2107]
I followed the instructions [here](http://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) and this works:
```
python setup.py pytest
```
but this does not invoke pytest:
```
python setup.py test
```
My `setup.cfg` contains only these two lines:
```
[aliases]
test=pytest
```
My environment is:
```
% python --version
Python 2.7.12 :: Anaconda 2.3.0 (x86_64)
% uname - a
Darwin dk-2.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
```

**Comment by RonnyPfannschmidt** [comment]
at first glance this is an issue with setuptools/conda, not pytest

**Comment by dkirkby** [comment]
The underlying problem may be with setuptools/conda, but there is also an issue with the [pytest documentation](http://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) if it provides instructions that do not work with a mainstream distribution (anaconda).

**Comment by dkirkby** [comment]
I had another look and realized that my setup.cfg was not in the package top-level dir.  After fixing this, `python setup.py test` works as advertised.  Sorry for the noise.
