### ISSUE TITLE
Could pytest --last-failed skip test collection?

### ISSUE THREAD

**Issue by anntzer** [pytest-dev/pytest#2114]
python 3.5.2, pytest 3.0.4 with no plugins, Arch Linux repo packages

`pytest --last-failed` currently re-runs a full collection of the test suite, even though it does not need to do so to know which are the tests that need to be run.

**Comment by RonnyPfannschmidt** [comment]
Collection determines test IDS, it would be possible to extend looponfail to cut down collection, its impossible to avoid it

**Comment by nicoddemus** [comment]
I think we can close this, it is not really possible in the current architecture.
