### ISSUE TITLE
Question: Possible to load different setup.cfg in different folder

### ISSUE THREAD

**Issue by rarelam** [pytest-dev/pytest#2115]
Hi all,

I would like to ask do pytest support to load different setup.cfg if those files are on different folder?

let say I have folder structure as below:

root dir/
    ---- folder a/
        ----> test_a.py
        ----> setup.cfg
    ---- folder b/
        ----> test_b.py
        ----> setup.cfg

both setup.cfg contains different values (base url) for different tests, it is possible for pytest to load different value in setup.cfg when run time?

**Comment by RonnyPfannschmidt** [comment]
Nno, the config file is loaded exactlz once, usw conftest files for runtime

**Comment by rarelam** [comment]
ok, thank you for your answer.
