### ISSUE TITLE
_pytest.python.getfuncargnames provides unhashable values for unpacking arguments

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2117]
```
>>> def test((a, b)): pass
>>> import pytest; import _pytest.python
>>> _pytest.python.getfuncargnames(test)
(['a', 'b'],)
```
raises an hard to debug exception when someone does that for a test function because we do not consider the possibility of a part of it not being a string

**Comment by Zac-HD** [comment]
Closing because this is a SyntaxError in Python 3.
