### ISSUE TITLE
Passing fixture to pytest.main

### ISSUE THREAD

**Issue by amarao** [pytest-dev/pytest#2125]
(sorry for writing as issue, I found no maillist)

I want to use pytest to run my tests from python application. I want to pass those tests fixture, which allows them to get access to internals of my application.

How should I create that fixture and how can I pass it to the tests?

It would looks like this:

    import pytest
    ...
    prepare_fixtures()
    result = pytest.main(path_to_tests)
    if result == OK:
        ...
    else:
       ...

Thanks.

**Comment by nicoddemus** [comment]
Hi,

You will have to put them in a module, them import the module and pass that to `pytest.main` using the `plugins` parameter:

```python
import myfixtures
result = pytest.main(path_to_tests, plugins=[myfixtures])
```

No problem posting questions on the issue tracker, but FWIW the mailing list can be found in the [Contact](http://doc.pytest.org/en/latest/contact.html) page and the address is http://mail.python.org/mailman/listinfo/pytest-dev.

**Comment by amarao** [comment]
Thank you! Amaizing!

I wrote a small article about this: https://medium.com/@george.shuklin/passing-fixtures-to-test-in-pytest-e8dade1f01ff#.bbk4574da (cc-by-sa).

**Comment by nicoddemus** [comment]
Nice! Would you consider contributing that post to [pytest-tricks](http://hackebrot.github.io/pytest-tricks/)? 😁 

Closing this issue then.

**Comment by amarao** [comment]
Gladly. How can I do this?

**Comment by nicoddemus** [comment]
Here's the repository: https://github.com/hackebrot/pytest-tricks

Basically you just create a new sub-directory in `content` and write an article with the `.md` extension, take a look at hackebrot/pytest-tricks#24 for an example (perhaps there should be a simple "how-to" on the README?)

@hackebrot may want to comment as well. 😁

**Comment by hackebrot** [comment]
@nicoddemus that's a great idea. I'll add a contribution guide to [pytest-tricks](https://github.com/hackebrot/pytest-tricks) 👍

**Comment by amarao** [comment]
Hello. I've tried to send a pull request, but it can't pass CI and I can't understand why.

Can someone help me? Thanks.

https://travis-ci.org/hackebrot/pytest-tricks/builds/182587780

**Comment by hackebrot** [comment]
I've commented on your PR! Let's move this conversation over to pytest-tricks to not notify everybody on this project 😄
