### ISSUE TITLE
assertion rewrite confuses coverage

### ISSUE THREAD

**Issue by dachary** [pytest-dev/pytest#2131]
When running tests via [coverage](https://pypi.python.org/pypi/coverage) on python2.7 or python3.4, assertion rewrite [confuses code coverage](https://bitbucket.org/ned/coveragepy/issues/515/coverage-of-multiline-generator-set-dict). It works as expected with python3.5 or when --assert=plain is specified.

The reproducer is available at https://gist.github.com/rouge8/0fd866f8122bb4c59938fab79f658c42

**Comment by nicoddemus** [comment]
Thanks for the report. I don't really understand if this is a problem on py.test's side or coverage's.

I will watch the BitBucket issue to see how it develops.

**Comment by RonnyPfannschmidt** [comment]
@benjaminp might know more

**Comment by dachary** [comment]
I [narrowed down the reproducer](https://bitbucket.org/ned/coveragepy/issues/515/#comment-32883742) and I'm inclined to think it could be a pytest issue. coverage.py [relies on compile()](https://bitbucket.org/ned/coveragepy/src/24aff3d7bfd592eb9d085ec9257e254b65772863/coverage/phystokens.py?at=default&fileviewer=file-view-default#phystokens.py-286) to figure out which byte code maps to which line. My theory is that prior to python-3.5 multiline asserts are mapped to multiple lines and coverage.py collects events from sys.setttraces that reference these lines and matches them to the bytecodes reported by compile() to verify coverage. When pytest rewrites asserts, I think it does so by assigning the line number of the first line of the assert to all bytecodes of the assert regardless. That works fine with python-3.5+ because that is the default behavior anyway. But that creates a problem with versions prior to python-3.5 because compile() will claim that byte code are associated with source lines for which events are never generated by sys.setttrace because the assert was written in a way that is not consistent with the source.

Does that make sense ?

**Comment by nicoddemus** [comment]
Hi @dachary, thanks.

I posted on the BitBucket issue the rewritten AST using [pytest-ast-back-to-python](https://pypi.python.org/pypi/pytest-ast-back-to-python). It might help others investigate the issue further.

**Comment by dachary** [comment]
Closing this issue while working on the assumption that it is [a coverage.py bug](https://bitbucket.org/ned/coveragepy/issues/515/coverage-of-multiline-generator-set-dict#comment-32893043).

**Comment by nicoddemus** [comment]
Thanks @dachary for the detailed investigation. I will continue to watch the issue on coverage's repository closely, we can reopen this if we have further findings.

**Comment by jfinkhaeuser** [comment]
So I followed this here from nedbat/coveragepy#605 and it now seems to be the case that both projects have been waiting on the other for some years. What's the status, then?
