### ISSUE TITLE
Pytest.mark doesn't work on a list of markers as suggested in the documentation

### ISSUE THREAD

**Issue by swapnamishra** [pytest-dev/pytest#2133]
```python
pytestmark = [pytest.mark.sm3, pytest.mark.sm2]
def test_function(self):
        assert True

@pytest.mark.sm1
def test_function(self):
        assert True
```
The command py.test -v -m "sm1" executes all tests and ignores the tags or should i say the -m option doesn't work at all.

(edited by @RonnyPfannschmidt to use a code block)

**Comment by RonnyPfannschmidt** [comment]
at first glance your example code has 2 functions named the same, thus the second one overriding the prior one (as python itself behaves that way)

please provide a full demonstrating example and your py.test output of that example

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of feedback
