### ISSUE TITLE
Accessing test instance object from pytest_runtest_makereport

### ISSUE THREAD

**Issue by westhomas** [pytest-dev/pytest#2138]
I'm modifying some results within `pytest_runtest_makereport` and I'm trying to access the instance of the test object.

But `item.parent.cls` and `item.parent.obj` or `item.parent.instance` never seem to be my actual instance.

Is it possible to access the underlying object instance within this makereport override?

**Comment by nicoddemus** [comment]
What do you mean exactly by "instance of the test object"?

If you mean the instance of a test class, `item.obj.__self__` works for me on Python 3:

```python
# test_foo.py
class Test:
    def test_method(self):
        pass

def test_function():
    pass

# conftest.py
def pytest_runtest_makereport(item, call):
    if call.when == 'call':
        print(item.nodeid, 'obj self:', getattr(item.obj, '__self__', None))
```
```
$ pytest -q
.tmp/test_foo.py::Test::()::test_method obj self: <test_foo.Test object at 0x039C6F70>
..tmp/test_foo.py::test_function obj self: None
.
2 passed in 0.01 seconds
```

**Comment by westhomas** [comment]
That's exactly what I need! Thanks!
