### ISSUE TITLE
pytest-xdist: Multi-thread or multi-process?

### ISSUE THREAD

**Issue by jzsimbiose** [pytest-dev/pytest#2152]
The documentation on pytest-xdist for "-n" and "-d" options says:

> To send tests to multiple CPUs, type:
> 
> py.test -n NUM

> Running tests in a Python subprocess
> To instantiate a python2.5 sub process and send tests to it, you may type:
> 
> py.test -d --tx popen//python=python2.5

It seems to me clear that -d will spawn OS processes, but I'm in doubt when it comes to -n.

The thing is: sending tests to multiple CPU may mean:

1) one process with many threads, each thread running one test
2) many processes, each single threaded process running a test

More specifically to my problem, will  **tests sent to multiple CPUs (by use of the -n option) share any memory space (such as static variables) among them**?

**Comment by The-Compiler** [comment]
...huh?

**Comment by RonnyPfannschmidt** [comment]
xdist always uses processes
