### ISSUE TITLE
basicConfig settings overlap from separate tests

### ISSUE THREAD

**Issue by r0fls** [pytest-dev/pytest#2158]
When using logging `basicConfig` in two tests in the same suite, the settings seem to overlap and interfere with each other.

I'm using pytest version 3.0.4 on Mac OSX Sierra

Here is a minimal example:

Create the following two files:

**test_1.py**
```
import logging

logging.basicConfig()
log = logging.getLogger()
def test_foo():
    foo = 1
    log.warn(foo)
    assert foo == 1
```

**test_2.py**
```
from io import StringIO
import logging

log_stream = StringIO()

def test_log():
    logging.basicConfig(stream=log_stream, level=logging.INFO)
    log = logging.getLogger()
    log.warn('test')
    assert log_stream.getvalue() == 'WARNING:root:test\n'
```

Then run `python3 -m pytest -v`.  Note that running each test individually works. The settings should not interfere, since they are in separate files.

**Comment by nicoddemus** [comment]
As discussed in #2159, the recommendation (at least for now) is to use the [pytest-catchlog](https://github.com/eisensheng/pytest-catchlog) plugin.
