### ISSUE TITLE
Replace raise StopIteration with return - adhere to Pep 479 

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pytest#2160]
As per pytest-dev/pluggy#38 and [pep 479](https://www.python.org/dev/peps/pep-0479/), it seems that some `pluggy` hook wrappers implemented in `pytest` are still using the soon to be deprecated `raise StopIteration` mechanism to signal early generator termination.

An example would be [`pytest_pycollect_makeitem`](https://github.com/pytest-dev/pytest/blob/3c81f83602e5fa38cb6187dfc7b131ed88bf8b7d/_pytest/python.py#L177).

As indicated in the pep all such usage should be changed to simple `return`s in Py3.6+.

**Comment by RonnyPfannschmidt** [comment]
its impossible to fix this as of now due to support for old python versions

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt I'm not sure that's true?

Supposedly all code [can be made backwards compatible](https://www.python.org/dev/peps/pep-0479/#writing-backwards-and-forwards-compatible-code) even in Py2.6 as per the original generator's [Pep 255](https://www.python.org/dev/peps/pep-0255/). Maybe I'm forgetting something though?

**Comment by RonnyPfannschmidt** [comment]
@tgoodlet indeed, the example looks perfectly valid to convert, i may have been overly pessimistic
we should go and try at least, perhaps we can convert everything just fine

**Comment by nicoddemus** [comment]
Unless I'm missing something (and that's a possibility since I didn't read PEP-479 thoroughly), can we just replace the `raise StopIteration` by a `return`?

This patch seems to work fine in Py2.6, 2.7 and 3.5:

```diff
diff --git a/_pytest/python.py b/_pytest/python.py
index e46f2f1..2973d43 100644
--- a/_pytest/python.py
+++ b/_pytest/python.py
@@ -174,7 +174,7 @@ def pytest_pycollect_makeitem(collector, name, obj):
     outcome = yield
     res = outcome.get_result()
     if res is not None:
-        raise StopIteration
+        return
     # nothing was collected elsewhere, let's do it here
     if isclass(obj):
         if collector.istestclass(obj, name):
```

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt Sounds good :)
@nicoddemus Yep you've got it.

You guys want me to make a PR?

**Comment by nicoddemus** [comment]
Please go ahead. 😁 Thanks!

**Comment by tiran** [comment]
The problem is causing test failures in Custodia on Python 3.6. The test turn all deprecation warnings into fatal failures. For Custodia I put a band-aid on the issue and filter out deprecation warnings from ```'_pytest\..*'```.

https://github.com/latchset/custodia/pull/105#issuecomment-276653031
