### ISSUE TITLE
AttributeError: 'SubRequest' object has no attribute 'param'

### ISSUE THREAD

**Issue by renewang** [pytest-dev/pytest#2162]
I have a code using cascaded fixtures that is the first fixture will create raw data with different parameters and the second fixtures will use the first fixture and create parameterized test cases based on the exhaustive enumeration of parameters specified in first and second.   
 
A oversimplified version of aforementioned problem is listed below:   

```python
@pytest.fixture(scope='session')
def treesampler():
      trees = get_trees()
      return(trees)

@pytest.fixture(scope="module", params=[True, False], ids=["ordered", "unordered"])
def expect_raw(request, treesampler):
       trees = treesampler
       #AttributeError: 'SubRequest' object has no attribute 'param'
       #when executing TestDemo::test_expect_stream
       is_sorted = request.param  
       if is_sorted:  
          print('is_sorted')
       else: 
         print('not sorted')

@pytest.fixture(scope="function", params=list(range(1, 11)))
def expect_batch(request, expect_raw):
      is_sorted = expect_raw
     bsize = request.param
     print(is_sorted, bsize)
     return(bsize, is_sorted)

# testing unbound function
def test_expect_stream(expect_batch):
       bsize, is_sorted = expect_batch
       assert True

# testing bound function
@pytest.mark.usefixtures(expect_batch)
class TestDemo(unittest.TestCase):
     def test_expect_stream(self):
           bsize, is_sorted = expect_batch
           assert True
```
The cascaded fixtures work well when the test case is unbound (not bound to any TestCase instance) but not when being an instance method of a TestCase. The TestCase will complain SubRequest has no param attribute for the first fixture. I wonder what’s the logics behind SubRequest and what causes the differentiate behaviors in bound / unbound test function.  
   
Would you be so kind as to sharing insights or tips about the pytest code design and maybe indicate which part of code I should look into in order to shed some light of this problem?   Or maybe a better design to solve this problem. 
Many thanks in advance.

pytest version 2.9.1
OS: Darwin Kernel Version 15.6.0: x86_64
[sandbox_pip_list_output.txt](https://github.com/pytest-dev/pytest/files/673517/sandbox_pip_list_output.txt)

**Comment by nicoddemus** [comment]
Hi @renewang sorry for the lack of answers.

`request.param` has been changed some time ago to at least provide a good error message when it is used in an invalid situation. Can you try your example with the latest version and see if that improves your understanding? Thanks.

**Comment by RonnyPfannschmidt** [comment]
@renewang the unittest support does not support parameterization, the error message on that should be more clear
