### ISSUE TITLE
[Question] is it possible to use configargparse instead of argparse for pytest_addoption() ?

### ISSUE THREAD

**Issue by nitrocode** [pytest-dev/pytest#2164]
I use a tox file for my pytest configuration and the command line args using pytest_addoption() but I'd also prefer to use a `config.ini` file or command line arguments and [configargparse](https://github.com/bw2/ConfigArgParse) allows me to do both. Is there a way to easily use that package instead of `argparse` for `parser`?

Thanks!

**Comment by RonnyPfannschmidt** [comment]
no, argparse is an implementation detail not fully exposed and not at all replacable
