### ISSUE TITLE
Don't let callable ids in parametrized tests fail silently

### ISSUE THREAD

**Issue by fogo** [pytest-dev/pytest#2169]
As it has been discussed in #2167, the current implementation just swallowed any error that happened in a callable `ids`, without any feedback to developers.

@RonnyPfannschmidt suggested we didn't straight-up change it to raise and the changes are only going to warn developers. But the plan is that in future version 4.0 that it just raises instead, so people have some time to fix any usage that may relying in current behavior.

**Comment by nicoddemus** [comment]
Thanks for creating the issue!

**Comment by Phantomphyre** [comment]
Help...

**Comment by The-Compiler** [comment]
@Phantomphyre ... huh?
