### ISSUE TITLE
Support passing a matrix to parametrize

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pytest#2171]
This is just an idea.

[`parametrize()`](http://doc.pytest.org/en/latest/parametrize.html#_pytest.python.Metafunc.parametrize) accepts a *list of N-tuples* to it's `argvalues` argument. This in turn generates a set of tests from the Cartesian product of the paired tuple's elements.

I propose that support is added to allow `argvalues` to be a matrix (the underlying data structures are up for debate) generated by the user.
This optionally allows for a user to generate tests only for the pairs of data they are interested in instead of having to filter down from the set of all pairs in `pytest_modify_collectitems()`.

Of course the requirement on `argvalues` is that it must be a MxN matrix where `argnames` is of length N.

**Comment by nicoddemus** [comment]
> This in turn generates a set of tests from the Cartesian product of the paired tuple's elements.

A Cartesian product of the argument values is only generated when using multiple `parametrize` calls, otherwise only the tuples specified in the call are used for parametrization.

Sorry if it is obvious (I should have gone to bed by now), perhaps you can post an example to clarify what you mean?

**Comment by tgoodlet** [comment]
@nicoddemus Let me drum up a test and I'll get back to you.

**Comment by RonnyPfannschmidt** [comment]
@tgoodlet sup on this one, can we close?

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt i'm pretty sure i found a bug with this so if you don't mind can we keep it open until i rexamine?

**Comment by nicoddemus** [comment]
@tgoodlet gentle ping. 😁

**Comment by tgoodlet** [comment]
@nicoddemus finally back and yes will try to take a look this week!

**Comment by nicoddemus** [comment]
Cool, let us know if you need help. 👍

**Comment by nicoddemus** [comment]
@tgoodlet should we close this for now? We can re-open this later when you get the time, no worries.

**Comment by tgoodlet** [comment]
@nicoddemus yeah close it if it it helps with your checklists.
I'm way down a different rabbit hole atm and probably won't get back to this in the near term.
