### ISSUE TITLE
watch-mode feature

### ISSUE THREAD

**Issue by ymmn** [pytest-dev/pytest#2181]
Dunno if you guys got this feature request before, but here goes!

[Mocha](https://github.com/mochajs/mocha) is a JS test framework that has an awesome watch-mode feature.

In a nutshell, it watches the filesystem for changes, kills the running set of tests when a change is detected, reloads all the appropriate set of modules (the JS equivalent of `importlib.reload(module)`), and runs the tests again. It ends up super fast. it's a really fun testing experience for users.

AFAIK, pytest's ecosystem just has [pytest-watch](https://github.com/joeyespo/pytest-watch) which isn't nearly as fast.

I'm assuming that a feature like that can't be implemented as a plugin and would have to be part of `pytest` itself (correct me if I'm wrong).

I wanted to get y'all's opinion on this suggestion, namely:

- is this in scope of the project at all? or is it unlikely to be important enough anytime soon
- is this a nice to have, but really challenging given current architecture
- is this a nice to have, and might even be doable

**Comment by The-Compiler** [comment]
I don't think this is doable, at least not using `importlib.reload` - because that doesn't really work reliably in Python, and has a lot of gotchas.

Have you seen [testmon](http://testmon.org/)?

**Comment by RonnyPfannschmidt** [comment]
@ymmn pytest-ydist ships with a `--looponfail` mode that also reruns on changes 

there are plans to make this a simpler plugin at some point, volunteer time is a factor, if you want to look into it i can brief you

**Comment by lwm** [comment]
`pytest-watch` and `testmon` already cover this? They're amazing.

**Comment by RonnyPfannschmidt** [comment]
pytest-watch isn't that integrated and leaves out loop-on-fail features, so im thinking of investigating a more complete solution

testmon solves a different part and recommends pytest-watch as integration

**Comment by ymmn** [comment]
I'm familiar with `pytest-watch` and `testmon`. They're awesome!

The main thing I'm wondering is if it's possible to cut out the overhead of initial config and initializing pytest plugins, and only have to do collect + execute tests on every file change.

**Comment by RonnyPfannschmidt** [comment]
@ymmn well, the python module system actively prevents sane reload  - as such i don't see any chance to do this better without breaking the world really strangely

**Comment by nicoddemus** [comment]
> I'm assuming that a feature like that can't be implemented as a plugin

It should be possible, pytest is almost entirely implemented in terms of plugins. You can even overwrite the main function if you like, so trying this as a plugin should be possible.

> The main thing I'm wondering is if it's possible to cut out the overhead of initial config and initializing pytest plugins, and only have to do collect + execute tests on every file change.

Preventing some plugins from running might be problematic for some test suites, but I understand that might be a known limitation of the system.

But as the others mention, I think the biggest limitation is getting the `reload` functionality working correctly, so I would not attempt to implement this in the core.

**Comment by ymmn** [comment]
@RonnyPfannschmidt ah ok, looks like module replacement is less straightforward than i thought
@nicoddemus nice, glad to know that it's possible thru a plugin

thank you guys for the feedback!
