### ISSUE TITLE
Test runner hangs during collection with doctest-modules and mock.call in module

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#2188]
Consider this test:

```
$ mkdir mock_call
$ cd mock_call 
$ cat > test_this.py
from unittest.mock import call

$ python -m rwt pytest -- -m pytest --doctest-modules --collect-only
Collecting pytest
  Using cached pytest-3.0.5-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest)
  Using cached py-1.4.32-py2.py3-none-any.whl
Installing collected packages: py, pytest
Successfully installed py-1.4.32 pytest-3.0.5
====================================== test session starts =======================================
platform darwin -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/jaraco/mock_call, inifile: 
collecting 0 items^C
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
to show a full traceback on KeyboardInterrupt use --fulltrace
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/mock.py:2069: KeyboardInterrupt
================================== no tests ran in 5.85 seconds ==================================
$ 
```

The test will hang for a long time and eventually exit. It seems the doctest logic is attempting to test the `call` function and causes trouble during collection.

**Comment by RonnyPfannschmidt** [comment]
this is a cpython bug ^^

**Comment by nicoddemus** [comment]
Could you provide more information @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus mock object are a easily the cause of endless recursions and errors, py.test had to add special support to avoid stumbling over those magical objects, i am certain the stdlib didn't brother to get things right

**Comment by nicoddemus** [comment]
I see thanks, but is that conclusion is a general feeling or did you investigate the report by @jaraco and reached that conclusion?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus we hit similar issues with some prior bugs related to py.tests own collection

**Comment by nicoddemus** [comment]
I see thanks @RonnyPfannschmidt 

Hmm `mock.call` is not a mock object, but does some [`getattr magic`](https://github.com/testing-cabal/mock/blob/master/mock/mock.py#L2091)... it warrants more investigation.

**Comment by jaraco** [comment]
I don't know why I didn't think to try this before - when running `python -m doctest test_this.py`, it also hangs. That excludes pytest as a factor and points pretty squarely at CPython.

**Comment by jaraco** [comment]
Which [has been reported here](http://bugs.python.org/issue25532).

**Comment by jaraco** [comment]
Ugh, and I reported this previously in #1217. I thought it seemed familiar, and I did search for it.

**Comment by nicoddemus** [comment]
Thanks @jaraco! 

@RonnyPfannschmidt was right after all! 😄
