### ISSUE TITLE
add an option to warn about Python 3.x possible incompatibilities

### ISSUE THREAD

**Issue by jedie** [pytest-dev/pytest#2191]
Is it possible to enable **"-3"** by default?!?

The Python Interpreter parameter **"-3"** will warn about Python 3.x possible incompatibilities, see: https://docs.python.org/2/using/cmdline.html#cmdoption-3

Normally i just run **pytest**
To enable the warnings, i can run via **python -3 -m pytest**

**Comment by RonnyPfannschmidt** [comment]
there will be a path to it after we integrate warnings support

its technically not possible to trigger -3 from entry-points as of now - so unless someone fixes that we simply cannot do

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt 

> there will be a path to it after we integrate warnings support

I'm curious, is there a way to programmatically enable `-3` by default?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus -3 just makes python skip on ignoring certain warnings - that can easily be configured

**Comment by nicoddemus** [comment]
> that can easily be configured

That was my question, how to do it. 😁 I didn't see how after a quick look at the 2.7's docs.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus uppon investigation, its disturbingly simple because the stdlib has an utterly hacky solution

just set `sys.py3kwarning` to true

**Comment by RonnyPfannschmidt** [comment]
so we could actually support it just as a cli option

**Comment by nicoddemus** [comment]
Heh that's interesting.

Yeah simple enough to support. We probably we should add it as an INI option, and users can use the new `-o` cli option if they want to enable it on the command line. I think most users will want to enable that option permanently on `pytest.ini` and on CI rather than as a one time shot on the command line (which would still be possible).

**Comment by jedie** [comment]
> just set sys.py3kwarning to true

But the docs says:

> This should be considered read-only; setting it to a different value doesn’t have an effect on Python 3 warnings.

see: https://docs.python.org/2/library/sys.html#sys.py3kwarning

**Comment by nicoddemus** [comment]
I'm not sure that is possible to fix then.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus based on 

```
>>> print inspect.getsource(warnings.warnpy3k)
def warnpy3k(message, category=None, stacklevel=1):
    """Issue a deprecation warning for Python 3.x related changes.

    Warnings are omitted unless Python is started with the -3 option.
    """
    if sys.py3kwarning:
        if category is None:
            category = DeprecationWarning
        warn(message, category, stacklevel+1)

```
on python 2 it should be possible to just set it and get agood deal out of it

**Comment by RonnyPfannschmidt** [comment]
the option should named in a way that signifies we try and hack a readonly var

**Comment by rhuard** [comment]
I was looking around at the help wanted tags for a first contribution. So I started exploring this issue a little bit.

I may be misunderstanding some of this discussion, as I am still not super familiar with the code base. However, I do not believe that setting sys.py3kwarning to True will be sufficient.

I wrote a quick example:
```python
import sys 

class CauseWarning(object): 

    def __eq__(self, other):
        return self._foo == other._foo

if __name__ == '__main__':
    print(sys.py3kwarning)
```

when run with python2 and no -3 flag one gets:
```
False
```

which is expected

when running with the -3 flag one gets:
```
test_warn.py:6: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class CauseWarning(object):
True
```
also expected

However, when you add in the line `sys.py3kwarning = True` you get:
```
True
```
but no warning.

Please let me know if I am missing anything, but with some quick investigations, it appears setting sys.py3kwarning my not be sufficient.

**Comment by nicoddemus** [comment]
@rhuard I'm not sure, indeed it doesn't seem to be enough.

To check if this was something that only takes effect if set before importing a module, I also tried to:

```
py -2 -c "import sys; sys.py3kwarning=1; import foo"
```

(where `foo.py` contains your example code)

But this also doesn't produce any warning.

**Comment by rhuard** [comment]
@nicoddemus I was trying something similar with the python interactive interpreter:

entering into interactive with `python -3`:
```
+>>> import sys
+>>> sys.py3kwarning = False
+>>> import test_warn
test_warn.py:8: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class CauseWarning(object)
```
where test_warn.py is the code spinet I put up earlier. If you start interactive interpreter without the `-3` and then set sys.py3kwarning = True, there is no warning. Which is consistent with what we have seen.

Since the docs say py3kwarning is read-only. I am thinking `-3` is doing more internally in python than setting a bool. I haven't had time yet today to dig much deeper though.

**Comment by nicoddemus** [comment]
I see @rhuard, thanks for confirming. 👍

**Comment by RonnyPfannschmidt** [comment]
it seems we cant fix the python internals

will close this one as wontfix

**Comment by RonnyPfannschmidt** [comment]
@rhuard thanks for confirming
