### ISSUE TITLE
How use in pytest_generate_tests paramrters list from setup_module 

### ISSUE THREAD

**Issue by braunman** [pytest-dev/pytest#2192]
HI!
I need to use the same test with different parameters, it is possible if you use pytest_generate_tests, but the problem is that the test papametry are generated in setup_module , here's a little example of test:
import pytest

```
lst = []
def setup_module():
	global lst
	print " -- setup_module"
	lst = range(3)

def teardown_module():
	print " -- teardown_module"

def pytest_generate_tests(metafunc):
  	global lst
  	if "num" in metafunc.funcargnames:
		metafunc.parametrize("num", lst)

def test_one(num):
	print " -- test_one {0}".format(num)	
	assert True

def test_two():
	print " -- test_two"	
	assert True
```

```

λ py.test.exe  test1\ -vs
============================= test session starts =============================
platform win32 -- Python 2.7.12, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- c:\python27\python.exe
cachedir: .cache
rootdir: c:\TEMP\test, inifile:
plugins: spec-1.1.0, html-1.13.0, catchlog-1.2.2
collected 2 items

test1/test_1.py::test_one[num0] SKIPPED
test1/test_1.py::test_two  -- setup_module
 -- test_two
PASSED -- teardown_module

```
as a result of test parameters will not start because the parameter list is empty, how to solve this problem that would first run setup_module and then test generator? 
Or maybe there is other variant to run these tests?

**Comment by RonnyPfannschmidt** [comment]
at setup_module time test parameterization is already done, its impossible to use it that way

**Comment by nicoddemus** [comment]
Just to complement what @RonnyPfannschmidt mentioned, pytest executes in two phases:

* collection: at this point all test modules are imported, fixtures are registered and test parametrization occurs. At the end of this phase all tests "items" are collected and ready to run.
* run: at this points all test items collected in the previous phase are executed, including fixture setup/teardown.

The "setup module" happens during the *run* phase, so you can't parametrize tests at that point anymore (IOW, create more test items). 

That's central to how pytest works, and unfortunately I can't think of any workarounds except make your tests execute a for loop themselves which is of course not the same thing:

```python
    def test_one():
        for num in lst:
            print " -- test_one {0}".format(num)	
            assert True
```

I'm closing this for now because it is not actionable on our part, but feel free to follow up with more questions.

**Comment by braunman** [comment]
It's potentially to run test in pytest with my logic? 
I try to use yield, but caught another problem:
```
test structur:
- test2
  -test2.py
- test3
  -test3.py
```
Code of test3 (use yeild):
```
# /test3/test_3.py
import pytest

def setup_module():
	global lst
	print " -- setup_module"
	lst = range(3)

def teardown_module():
	print " -- teardown_module"

def one(num):
	print " -- one {0}".format(num)	
	assert True

def test_one():
	print " -- test_one" 	
	for i in lst:
		yield one, i

def test_two():
	print " -- test_two"	
	assert True

```
stdout:
```
λ py.test.exe  -sv
============================= test session starts =============================
platform win32 -- Python 2.7.12, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- c:\python27\python.exe
cachedir: .cache
rootdir: c:\TEMP\test, inifile:
plugins: spec-1.1.0, html-1.13.0, catchlog-1.2.2
collecting 1 items -- setup_module
 -- test_one
collected 5 items

test2/test_2.py::test_try  -- teardown_module
 -- setup_module TEST_2 22222
 -- run TEST_2 22222
PASSED -- teardown_module TEST_2 22222

test3/test_3.py::test_one::[0]  -- setup_module
 -- one 0
PASSED
test3/test_3.py::test_one::[1]  -- one 1
PASSED
test3/test_3.py::test_one::[2]  -- one 2
PASSED
test3/test_3.py::test_two  -- test_two
PASSED -- teardown_module
```
Problem that when collecting tests, run setup_module from test3.py, but not run teardown_module, in real tests in setup_module raise connection in teardown_module down connection, for one user only one connection.

**Comment by braunman** [comment]
@nicoddemus  you right 

> That's central to how pytest works, and unfortunately I can't think of any workarounds except make your tests execute a for loop themselves which is of course not the same thing:

it's not the same (

**Comment by nicoddemus** [comment]
yield tests are deprecated and really should not be used in new tests because we plan to remove them at some point. Can you convert the tests to use `parametrize` instead?

**Comment by braunman** [comment]
I try but have same problem as with pytest_generate_tests.

**Comment by nicoddemus** [comment]
Yeah I'm sorry, then what you are trying to do is not really possible currently. ☹️

**Comment by braunman** [comment]
Thanks for the quick answers, I hope to run the tests it will be possible sooner or later
