### ISSUE TITLE
Yield Method for Finalizing Fixtures Not Same as addfinalizer()

### ISSUE THREAD

**Issue by fxfitz** [pytest-dev/pytest#2195]
I think this is more of a documentation change that might be needed, but I noticed today that there is a [new way](http://doc.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code) of adding finalizers using `yield`.

This way worked fine for me, but I just wanted to note that it doesn't work _exactly_ the same as the old way of using `addfinalizer()`.  Specifically, we noticed that when using the `yield` method, if a user Control-C's out of the test, the finalizer code will not be executed. In the old way, with `addfinalizer()`, Control-C is handled correctly in that if a user exits out of a test prematurely, the finalization code is still evaluated.

Handling of the interrupts the old way helped us immensely, and I would hope that a documentation change to acknowledge the different ways of doing it (as opposed to just old way vs new way) might provide extremely helpful to other users because I doubt we would be the only one.

Thanks! I hope you find this useful! :-)

**Comment by RonnyPfannschmidt** [comment]
@fxfitz without an code example its not clear what you mean, in order to ensure we correctly understand, please provide a example

**Comment by fxfitz** [comment]
Aaaaactually, looks like I was wrong here! I wrote a few tests yesterday before I submitted the issue, but when I looked today, I saw a bug in my test... so I'll go ahead and close this issue (because I was way wrong --- sorry!)

Thanks!
