### ISSUE TITLE
assert function has been called

### ISSUE THREAD

**Issue by tgy** [pytest-dev/pytest#2197]
I am using `pytest-asyncio` but I think this is not related to my question.

I would like to `assert` that a function has been called`.

Here is what I am doing

```python
@pytest.yield_fixture
def service(event_loop):
    pass # yield a service instance

class TestClass:
    @pytest.mark.asyncio
    async def test_hook_called(self, service):
        async def hook(message):
            assert message == 'hello'
        await service.attach_hook(hook)
        await service.send('hello')
```

**Whether or not the `hook` is actually triggered, the test will pass.**

How can I `assert` that the `assert message == 'hello'` statement is reached?

**Comment by RonnyPfannschmidt** [comment]
@tgy your service seems to make exceptions disappear, so its your responsibility to make them bubble up

py.test cant see exceptions you hide from it

**Comment by RonnyPfannschmidt** [comment]
@tgy a common structural pattern however is, to have the hook modify a list, then after the call assert the change to the list
```
@pytest.yield_fixture
def service(event_loop):
    pass # yield a service instance

class TestClass:
    @pytest.mark.asyncio
    async def test_hook_called(self, service):
        messages = []
        async def hook(message):
            messages.append(message)
        await service.attach_hook(hook)
        await service.send('hello')

        assert messages == ['hello']

**Comment by tgy** [comment]
@RonnyPfannschmidt thank you for your reply. Those tests are actually meant to test the service in question. This particular test makes sure a hook attached to the service is called when a message is received.

I had thought about the `list` work-around but I thought there was a cleaner way to do it.

Looks like there isn't!

Thanks again.

**Comment by RonnyPfannschmidt** [comment]
@tgy testing side-effects is always a bit unclean,
