### ISSUE TITLE
Doc error in fixtures section

### ISSUE THREAD

**Issue by borisozegovic** [pytest-dev/pytest#2201]
In section 'Parametrizing fixtures' all instances have the same address (0xdeadbeef).  The text below 'example box' is correct and it states there should be two different instances.

[http://doc.pytest.org/en/latest/fixture.html#fixtures](url)

**Comment by nicoddemus** [comment]
Hah, I was suspicious that `deadbeef` was too funny to [be accidental](https://bitbucket.org/pytest-dev/regendoc/src/4387e18989c867261ecf9fd2905a676e306b646b/regendoc/__init__.py?at=default&fileviewer=file-view-default#__init__.py-113). 😆 

All address are replaced by `deadbeef` by [regendoc](https://bitbucket.org/pytest-dev/regendoc), so this is actually a feature. 😉

**Comment by RonnyPfannschmidt** [comment]
this is indeed a feature for the documentation, we replace all memory addresses,

but tbh imho its a bug we have all those reprs with random addresses instead of meaningfull data

**Comment by nicoddemus** [comment]
Closing this then. 👍

**Comment by EdwardBlair** [comment]
Reopen.
