### ISSUE TITLE
Exclude some test modules from assertion rewriting

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2203]
Sometimes users do some "black magic" like patching builtins (for example #2180) and that might completely break pytest.

While of course we should not encourage too much black magic, I was wondering if we could alleviate the problem for users which don't want or can't change their tests to disable assertion rewriting for some of the test modules.

I was thinking of something like the `# encoding` comment used by Python to declare the encoding of a file. An alternative would be to list some test files on `pytest.ini`, but I think the comment is better because it is written in the file itself, rather than far away from it. 

How about `# pytest-no-rewrite` or something like this?

**Comment by The-Compiler** [comment]
I don't think this would help with #2180 though, would it? I suppose we'd still need to use `open()` to read the comment :wink:

**Comment by nicoddemus** [comment]
@The-Compiler you're right. 😁

**Comment by nicoddemus** [comment]
From #743, there's an undocumented `PYTEST_DONT_REWRITE` in place already, perhaps we are halfway there already (save builtin `open()`, skip bytecode rewriting, docs, etc).

**Comment by jacebrowning** [comment]
`PYTEST_DONT_REWRITE` is exactly what I needed. Any chance we could get this formally documented?

My use case is a pytest plugin that manages its own assertion messages: https://github.com/jacebrowning/pytest-expecter

**Comment by nicoddemus** [comment]
> Any chance we could get this formally documented?

FWIW this is now on the [reference page](https://docs.pytest.org/en/latest/reference.html#pytest-dont-rewrite-module-docstring). :wink:

**Comment by laike9m** [comment]
Would be cool if there's a flag to always disable rewrite.

**Comment by blueyed** [comment]
@laike9m 
`--rewrite=plain`?
You can use this in a config via `addopts`.

**Comment by laike9m** [comment]
Ah interesting. Found that in the documentation. Thanks!

https://docs.pytest.org/en/latest/assert.html#disabling-assert-rewriting
