### ISSUE TITLE
Migrating from nose "setup_package" and "teardown_package"

### ISSUE THREAD

**Issue by tadas-subonis** [pytest-dev/pytest#2210]
I am migrating from nose to py.test, however I've ran into an issue where "setup_package" aren't supported from __init__.py .

Has anyone had experience regarding this and maybe there is a quick work around to make it work? I would really hate going all over the code and moving initialization code from there.

Any ideas welcome.

**Comment by RonnyPfannschmidt** [comment]
@tadas-subonis currently this isnt supported in pytest at all, pytest is not even aware of folder __init__.py modules

**Comment by tadas-subonis** [comment]
For future reference

I've found a workaround because all of the setup_package calls are the same (so it might be for this specific case only as it was mainly for CherryPy).

I've a folder with tests/integration . There I've created setup.cfg with
```
[pytest]
usefixtures = setup_server
```

and a file tests/integration/conftest.py with
```
import cherrypy
import pytest

@pytest.fixture(scope="session")
def setup_server(request):
    cherrypy.config.update(conf)
    cherrypy.config.update({
        'log.screen': False
    })
    cherrypy.config.update({'engine.autoreload.on': False})
    cherrypy.tree.mount(create_root(), '/', conf)
    cherrypy.engine.signals.subscribe()
    cherrypy.engine.start()

    def fin():
        cherrypy.engine.exit()

    request.addfinalizer(fin)
```

**Comment by RonnyPfannschmidt** [comment]
in that case it may make sense to just make it a autouse fixture

**Comment by RonnyPfannschmidt** [comment]
closing as you found a sustainable answer for your case, thanks for sharing 👍

**Comment by adiroiban** [comment]
Just a few more comments here.

I see that the "how to" documentation does not talk about `setup_package`

*  https://docs.pytest.org/en/7.3.x/how-to/xunit_setup.html  - this can be expected, since setup_package is only nose related

* https://docs.pytest.org/en/7.3.x/how-to/nose.html  this looks like nose specific info but the `setup_package` migration is not mentioned

I guess that the answer here is to use `@pytest.fixture(scope="package")` as documented here https://docs.pytest.org/en/7.3.x/how-to/fixtures.html#fixture-scopes

Thanks

**Comment by RonnyPfannschmidt** [comment]
package scope was added in https://docs.pytest.org/en/stable/changelog.html#pytest-3-7-0-2018-07-30 which is more than a year after the close of the issue

i believe we missed adding nose package scope setup back when it was relevant to pytest

its unlikely we will add it ourself anytime soon

**Comment by adiroiban** [comment]
Thanks for the context

> its unlikely we will add it ourself anytime soon

I fully understand this.

I have added this just in case someone else will look into this.

I am planning to move a project from nose to pytest and I hope I will not forget to review the current docs and send any changes.

Thanks again for your time!

**Comment by nicoddemus** [comment]
> I hope I will not forget to review the current docs and send any changes.

That would be greatly appreciated! :+1:
