### ISSUE TITLE
please implement analog of unittest.mock`assert_called_with`

### ISSUE THREAD

**Issue by vitaly-zdanevich** [pytest-dev/pytest#2214]
As I understand now this [is not possible out of the box](http://stackoverflow.com/questions/28716832/how-to-test-function-is-called-with-correct-arguments-with-pytest/28719648#28719648)?

**Comment by The-Compiler** [comment]
All `monkeypatch` does is patching, i.e. do `setattr` and undo changes at the end of the test. If you actually need the features of `unittest.mock`, why not use that (with the `pytest-mock` plugin ideally) instead?

**Comment by RonnyPfannschmidt** [comment]
also from my pov mock support is intentionally not part of the core

**Comment by RonnyPfannschmidt** [comment]
closing this one as its provided by pytest-mock
