### ISSUE TITLE
fixture as parameter/filter

### ISSUE THREAD

**Issue by mieszkosluzewski** [pytest-dev/pytest#2218]
Hi. 
I want to add feature, which will allow for running tests witch using specified fixture.
For example I have a lot of tests fixtures etc. I modify one fixture and I want to run all tests which using that. 
Something like: 
   py.test -f "fixture_name" ...
Maybe there is something like that, but I can't find it. If you have any suggestions where I can started?

Sorry if I break any rules, feel free to reprimand me. Tell me, If you have any issues for new contributor.

**Comment by RonnyPfannschmidt** [comment]
hi @mieszkosluzewski and welcome 😄 
no need to worry, you certainly did not break any rules

selecting tests by the fixtures they use, and maybe even by the combination of fixture * parameter is a nice idea,
it would be a great help if you started a discussion on pytest-dev@python.org (you will need to register) about the ux of this feature
(please prepare for being confronted with a multitude of ideas and opinions)

i suspect it will be reasonably easy to integrate this with the common mechanisms of test selection
as test items do have fixture names and parameter values readily available

if you want to get started with the codebase i can recommend taking a try at one of the issues with the easy label, in case something is unclear feel free to visit us in the `#pylib` channel on freenode (IRC)

**Comment by The-Compiler** [comment]
Also check https://hackebrot.github.io/pytest-tricks/run_tests_using_fixture/ - it would be quite easy to write such a hook which simply adds a marker for every fixture.

**Comment by mieszkosluzewski** [comment]
Thanks. I was looking for something like this. Yes it's easy to implement, but I'm new in pytest, so I don't know where I can put this feature, how can I test this etc. Maybe it's should be a plugin, not feature?

**Comment by Zac-HD** [comment]
Closing this issue as inactive, because the proposed feature can be implemented as a plugin.
