### ISSUE TITLE
Excetption must be classified 

### ISSUE THREAD

**Issue by GeorgeFischhof** [pytest-dev/pytest#2233]
Excetption must be classified

Hi Guys,
 
The place of files is indifferent. (I tried 2 paths). 

The python files now are in 
c:\tdd\
folder

----

```
# C:/tdd/shapes.py
class NegativeSideValue(Exception):
    pass

def square_area(side):
    if side < 0:
        raise NegativeSideValue
    return side ** 2
```

----

```
# C:/tdd/test_shapes.py
import pytest
import shapes

def test_square_area_negative():
    with pytest.raises(NegativeSideValue):
        shapes.square_area(-1)

```
----

result:

```
c:\tdd>pytest
============================= test session starts =============================
platform win32 -- Python 3.5.2, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: c:\tdd, inifile:
collected 1 items

test_shapes.py F

================================== FAILURES ===================================
__________________________ test_square_area_negative __________________________

    def test_square_area_negative():
>       with pytest.raises(NegativeSideValue):
E       NameError: name 'NegativeSideValue' is not defined

test_shapes.py:8: NameError
========================== 1 failed in 0.09 seconds ===========================

```
----

If I classify the exception as 

```
def test_square_area_negative():
    with pytest.raises(shapes.NegativeSideValue):
        shapes.square_area(-1)

```

The the test runs welll
(Maybe I am wrong, but I think / thought that exception is just exception, that is raised, and pytest catches it.

used versions:
python 3.5.2
pytest: 3.0.5
windows 8.1 64 bit

installed packages:
click (6.7)
colorama (0.3.7)
pip (9.0.1)
py (1.4.32)
pytest (3.0.5)
requests (2.12.4)
setuptools (32.1.2)

**Comment by The-Compiler** [comment]
That's just normal Python behavior - `NegativeSideValue` is a class in the `shapes` module, so if you imported the module you'll need `shapes.NegativeSideValue` to access it. It'd be exactly the same if you used python's `except shapes.NegativeSideValue:`.

> Maybe I am wrong, but I think / thought that exception is just exception, that is raised, and pytest catches it.

Correct.
