### ISSUE TITLE
pytest-dev/pytest installs same script as logilab-common

### ISSUE THREAD

**Issue by dlangille** [pytest-dev/pytest#2243]
Both pytest-dev/pytest and logilab-common (https://www.logilab.org/project/logilab-common) install the same script.  Specifically pytest

This creates a problem in that both code sets cannot be installed concurrently.  One overwrites the other.  

I'm asking both projects for their suggestion as to how we can resolve this problem. Ideally, the resolution would occur in the project, so it solve the issue for all packaging systems.

Thank you.

**Comment by RonnyPfannschmidt** [comment]
as per #1833 this is intentional and pytest will stay as is

**Comment by dlangille** [comment]
Thank you.  That saves me from contacting logilab-common.  Cheers.
