### ISSUE TITLE
drop python3.2 support in assertion rewriter

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2250]
https://github.com/pytest-dev/pytest/pull/2249/files#diff-df93604d69f53ce9e844b6f769512319L206

points to some code thats better handled now

**Comment by Zac-HD** [comment]
Is this about the wish to use `imp.load_compiled`?  AFAICT it's not supported on Python 2.7, so we'll have to wait until 2020.  (and if not, can you share enough detail that someone else could work on this issue?)

**Comment by RonnyPfannschmidt** [comment]
@Zac-HD correct assessment, however we will just have to wait until EOL python 3.4

**Comment by nicoddemus** [comment]
No longer relevant
