### ISSUE TITLE
`pytest_report_header` not working based on location of `conftest.py`

### ISSUE THREAD

**Issue by vmuriart** [pytest-dev/pytest#2257]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [x] Minimal example if possible

### Environment

```
platform linux2 -- Python 2.7.9, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/travis/build/vmuriart/sqlparse, inifile: setup.cfg
plugins: travis-fold-1.2.0, cov-2.4.0
```

Issue seen on all python versions tested (`PY27`, `PY33`-`PY37`)
Issue seen on both Windows(`AppVeyor`) and Linux(`Travis`)

### Details

-   Describe what you were trying to get done.

Trying to add a custom header information per the [docs](http://doc.pytest.org/en/latest/example/simple.html#adding-info-to-test-report-header)

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

If tests and `conftest.py` is located on `./src/tests/conftest.py` then the custom information **isn't** added to the [report](https://travis-ci.org/vmuriart/sqlparse/jobs/202111487#L181).

If tests and `conftest.py` is located on `./tests/conftest.py` then the custom information **is** added to the [report](https://travis-ci.org/vmuriart/sqlparse/jobs/202111649#L181).

If tests and `conftest.py` is located on `./test/conftest.py` then the custom information **is** added to the [report](https://travis-ci.org/vmuriart/sqlparse/jobs/202139194#L181).

If tests and `conftest.py` is located on `./foo/conftest.py` then the custom information **isn't** added to the [report](https://travis-ci.org/vmuriart/sqlparse/jobs/202136114#L181).

I've tried setting `testpaths` to `src/tests` and `src` but neither worked.

**Comment by vmuriart** [comment]
Probably somewhere close to [this section](https://github.com/pytest-dev/pytest/blob/9c809f5ad091c7235c7c8b5bcf0c08f8a086c34e/_pytest/config.py#L321-L343) of code

**Comment by nicoddemus** [comment]
Thanks for the report, I think `pytest_report_header` falls in the same spot of `pytest_addoption` (see [the note](http://doc.pytest.org/en/latest/writing_plugins.html?highlight=pytest_addoption#_pytest.hookspec.pytest_addoption) on the docs). In that case unfortunately this is not easily fixable, but we should update the docs to add a similar note to `pytest_report_header` so it doesn't trip users.

**Comment by vmuriart** [comment]
@nicoddemus that sounds about right from what i'm experiencing.

This part has me confused though. `if no test paths are specified use current dir as a test path` Wouldn't that imply that when I added `testpaths` to pytest's section in `setup.cfg` that it would have found it?

**Comment by nicoddemus** [comment]
Hmmm good point, that might be something particular to how `testpaths` is configured internally though.

Regardless, perhaps you would like to open a quick PR to add the note to `pytest_report_header` in the docs?

**Comment by vmuriart** [comment]
I have no experience w `.rst` so I'm not sure I wrote it correctly. I'll take a look at `testpaths` to see whats up.

**Comment by vmuriart** [comment]
On second thought, I'm going to push to just move our `tests` folder.

**Comment by nicoddemus** [comment]
Updated docs in #2261.

Thanks again @vmuriart.
