### ISSUE TITLE
parametrize report should not print parametrize annotation

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest#2259]
having large parametrized tests when fail the parametrize annotation takes up way to much space, do we really need to print that? :+1: Should we have a print last n lines only option perhaps?

**Comment by nicoddemus** [comment]
Good point, thanks for the report, we probably should limit that to some number of characters unless `-v` is used.

**Comment by gaborbernat** [comment]
I can try to create a PR for this :+1:

**Comment by nicoddemus** [comment]
That would be greatly appreciated, thanks.

**Comment by gaborbernat** [comment]
can you point me towards the place I need to look? is it _pytest/assertion/__init__.py? Thanks!

**Comment by nicoddemus** [comment]
Please take a look [here](https://github.com/pytest-dev/pytest/blob/master/_pytest/terminal.py#L483), that `msg` variable contains the test name, including the parametrization values.

**Comment by gaborbernat** [comment]
Hello, 

So I've looked into this, and played around a bit with it, and came to the following conclusions: the reason we get the entire function definition is how the traceback printing works, the default is auto, which prints the full trace of the first and last function. So the modification potentially probably fall under how we format the traceback in general, rather than just for the terminal. The code snippet relevant to this should be [here](https://github.com/pytest-dev/pytest/blob/master/_pytest/_code/code.py#L511), in case of a long exception format, we should have something around the lines:

```python
         if short:
             lines.append(space_prefix + source.lines[line_index].strip())
         else:
-            for line in source.lines[:line_index]:
+            context_before = 3  # 3 lines before, but include class/def to have context
+            context_after = 1  # one line after should suffice
+            from_line = max(0, line_index - context_before)
+            for line in source.lines[from_line:line_index]:
                 lines.append(space_prefix + line)
             lines.append(self.flow_marker + "   " + source.lines[line_index])
-            for line in source.lines[line_index+1:]:
+            to_line = min(len(source.lines), line_index + context_after)
+            for line in source.lines[line_index+1:to_line]:
                 lines.append(space_prefix + line)
         if excinfo is not None:
             indent = 4 if short else self._getindent(source)
```

So instead of getting blindly the entire source, limit the number of lines to use. Naturally we can have that a negative (or zero) context number means take all to keep the current functionality. The problem with this is that you loose locality (e.g. you may not see what class/function you are inside. Therefore I think maybe we should prepend before the context limit, the first line matching a function/class definition. This could be done via heuristic, e.g. regex match of ``def [func_char]``. So what do you think @nicoddemus? 

Thanks!

**Comment by nicoddemus** [comment]
@gaborbernat thanks for following up!


I think I have misunderstood your original request: when you meant we don't need the entire report for parametrized tests with long arguments, I thought something like this:

```python
class Test:

    @pytest.mark.parametrize('i', ['A' * 120])
    def test(self, i):
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        assert 0
```

```
================================== FAILURES ===================================
 Test.test[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]

self = <foo.Test object at 0x03BC3A50>
i = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'

    @pytest.mark.parametrize('i', ['A' * 120])
    def test(self, i):
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
        y = 1
>       assert 0
E       assert 0

.tmp\foo.py:40: AssertionError
===================== 1 failed, 1 passed in 0.03 seconds ======================
```

And that you wanted to display something like `Test.test[AAAAAAAAA...]` instead of the full parameter name.

I'm now realizing that meant to limit the number of lines that we show in tracebacks. Applying your patch here's what we get instead:

```
================================== FAILURES ===================================
 Test.test[AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA]

self = <foo.Test object at 0x0378DAB0>
i = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'

        y = 1
        y = 1
        y = 1
>       assert 0
E       assert 0

.tmp\foo.py:40: AssertionError
===================== 1 failed, 1 passed in 0.03 seconds ======================
```

I think this is a nice idea, but the current traceback has its uses and I find it very useful specially when seeing output on CI. 

Perhaps we can include a new traceback style option instead?

**Comment by gaborbernat** [comment]
I definitely would not want to change the default behavior, so yeah it's a traceback option. However I have a feeling this is an extra option for all long trackbacks instead of an extra type. Don't you think?

**Comment by nicoddemus** [comment]
>  However I have a feeling this is an extra option for all long trackbacks instead of an extra type. Don't you think?

You got a point there. `--tb-context` perhaps? What do others think?

**Comment by gaborbernat** [comment]
@ anyone else? so what's your guys take on this?

**Comment by gaborbernat** [comment]
I will close this issue for now; it's a non trivial change; getting an arbitrary number of lines often leads towards a hard readability. The best solution would be to strip away the annotation I think, but that's non-trivial at best.
