### ISSUE TITLE
Docs clarification: using `yield` and `with`

### ISSUE THREAD

**Issue by pkch** [pytest-dev/pytest#2262]
In [Fixtures section](http://doc.pytest.org/en/latest/fixture.html#fixtures), the docs say:

> Note that we can also seamlessly use the yield syntax with with statements:

```
# content of test_yield2.py
import pytest
@pytest.fixture
def passwd():
    with open("/etc/passwd") as f:
        yield f.readlines()
def test_has_lines(passwd):
    assert len(passwd) >= 1

```
At first glance, there seems to be no reason to write this code; `return f.readlines()` would work just as fine, and there is no special connection between the `yield` statement and the `with` statement. (Normally, `yield` would have created teardown code - but there's nothing here that follows `yield`, so it's equivalent to `return`. Of course, the teardown code is implicitly created by the use of of `with` statement - but it works equally well with `yield` or `return`.)

Might be worth either removing this example, or clarifying why it's useful.

**Comment by nicoddemus** [comment]
You got a point, in that case there's really no reason to use `yield` since we are already inside the `with` block.

Do you have a suggestion of a yield fixture where using a `with` block makes sense? I can't really think of any right now.

**Comment by pkch** [comment]
Hmm, at first glance I think of `yield` and `with` as the two roughly equivalent ways to achieve the same result (elegantly specify teardown code). 

In fact, for any fixture that uses `yield`, I can create a context manager using `contextlib.contextmanager` decorator, which would allow me to use `with` instead, for example, if I understand right:

```
@pytest.fixture
def smtp():
    smtp = smtplib.SMTP("smtp.gmail.com")
    yield smtp
    print("teardown smtp")
    smtp.close()
```

is equivalent to

```
@contextmanager
def smtp_cm(name):
  smtp = smtplib.SMTP(name)
  yield
  print("teardown smtp")
  smtp.close()

@pytest.fixture
def smtp():
    with smtp_cm("smtp.gmail.com") as smtp:
      return smtp  # can use yield too, but won't make a difference
``` 

So I feel there is little chance of both `yield` and `with` being useful at the same time (unless there are two separate resources being torn down, and they just happen to use different syntax).

**Comment by The-Compiler** [comment]
If we used something where the time of the teardown matters (say mock patches using `with`), wouldn't `yield` vs. `return` matter a lot? With `return`, the teardown would happen before the test starts, no?

**Comment by nicoddemus** [comment]
Right @The-Compiler, thanks. 

@pkch in this example:

```python
@pytest.fixture
def smtp():
    with smtp_cm("smtp.gmail.com") as smtp:
      return smtp  # can use yield too, but won't make a difference
```

Using `return` here will close the connection right before returning the object, while `yield` will yield the object, execute the test, then resume execution of the fixture which then closes the connection, so it's not the same.

Quick example:

```python
from contextlib import closing
import pytest

class SMTP:
    def close(self):
        print('SMTP closed')

@pytest.fixture
def smtp():
    with closing(SMTP()) as smtp:
      return smtp 

def test(smtp):
    print('test')
```

Prints:

```
SMTP closed
test
.
1 passed in 0.00 seconds
```

Using `yield`:

```
test
.SMTP closed

1 passed in 0.01 seconds
```

**Comment by pkch** [comment]
Oh of course, thanks, I completely didn't notice that! Maybe add this example to the docs?

**Comment by nicoddemus** [comment]
Sounds good, would you like to open a PR? We could change the original
example to yield the file object instead of the lines, which makes me sense
then
