### ISSUE TITLE
Trailing whitespace in terminal output if no inifile detected

### ISSUE THREAD

**Issue by fbjorn** [pytest-dev/pytest#2281]
Hi,

I'm running pytest inside Sublime Text 3. I have some plugin which highlights all trailing whitespaces found inside the editor.  
If no inifile presented, then output of pytest will contain such one, and it will be highlighted:
![image](https://cloud.githubusercontent.com/assets/9670990/23450123/87e6bd1e-fe6a-11e6-9f65-da3e6d11a8ad.png)

It's a dead simple fix and I can submit PR on that, but I understand that my usage model is kind of uncommon so the question is if this change is relevant? Does it have any chances of being accepted?

**Comment by nicoddemus** [comment]
@fbjorn a PR would be greatly appreciated, thanks!

**Comment by flub** [comment]
agree, nothing wrong with cleaning this up so a PR would be accepted.
