### ISSUE TITLE
File not found error not reported when using multi processes 

### ISSUE THREAD

**Issue by orenovadia** [pytest-dev/pytest#2282]
Hi,
I've noticed that when specifying positional arguments `file_or_dir`, The usual `ERROR: file not found: dir_does_not_exist/` does not appear when running py.test with the `-n` option.

Example:
`py.test -n2  dir_does_not_exist/`

Thanks

**Comment by nicoddemus** [comment]
Thanks for the report! I took the liberty of moving this to pytest-dev/pytest-xdist#129, so I'm closing this ticket here.
