### ISSUE TITLE
py37-nightly currently failing on Travis due to assertion rewriting

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2285]
Here are the failures:

```
=================================== FAILURES ===================================
_______________ TestAssertionRewrite.test_place_initial_imports ________________
self = <test_assertrewrite.TestAssertionRewrite object at 0x7fda6cb5b8d0>
    def test_place_initial_imports(self):
        s = """'Doc string'\nother = stuff"""
        m = rewrite(s)
>       assert isinstance(m.body[0], ast.Expr)
E       AssertionError: assert False
E        +  where False = isinstance(<_ast.Import object at 0x7fda6cb5bd30>, <class '_ast.Expr'>)
E        +    where <class '_ast.Expr'> = ast.Expr
testing/test_assertrewrite.py:65: AssertionError
____________________ TestAssertionRewrite.test_dont_rewrite ____________________
self = <test_assertrewrite.TestAssertionRewrite object at 0x7fda6cb31ba8>
    def test_dont_rewrite(self):
        s = """'PYTEST_DONT_REWRITE'\nassert 14"""
        m = rewrite(s)
>       assert len(m.body) == 2
E       assert 5 == 2
E        +  where 5 = len([<_ast.Import object at 0x7fda6cb310f0>, <_ast.Import object at 0x7fda6cb31b00>, <_ast.Assign object at 0x7fda6cb317b8>, <_ast.If object at 0x7fda6cb31470>, <_ast.Assign object at 0x7fda6ca558d0>])
E        +    where [<_ast.Import object at 0x7fda6cb310f0>, <_ast.Import object at 0x7fda6cb31b00>, <_ast.Assign object at 0x7fda6cb317b8>, <_ast.If object at 0x7fda6cb31470>, <_ast.Assign object at 0x7fda6ca558d0>] = <_ast.Module object at 0x7fda6cb31e10>.body
testing/test_assertrewrite.py:101: AssertionError
======= 2 failed, 1682 passed, 53 skipped, 13 xfailed in 113.48 seconds ========
ERROR: InvocationError: '/home/travis/build/pytest-dev/pytest/.tox/py37/bin/pytest --lsof -rfsxX testing'
___________________________________ summary ____________________________________
ERROR:   py37: commands failed
```

**Comment by flub** [comment]
I believe this can now be closed.  Would be nice if github could do this magically somehow... ;-)

**Comment by nicoddemus** [comment]
Heh, but my idea is to have an open issue describing the actual problem; the intent of my PR was just to allow that build to fail so we don't have to merge broken PRs. It is still very early on the Python 3.7 life cycle, after all.

**Comment by flub** [comment]
oops, sorry.  misread the issue

**Comment by nicoddemus** [comment]
no worries. 👍

**Comment by pawelad** [comment]
I was planning to help with this but began to wonder if its worth it at this time - per Brett Cannon (Python core developer):
> (...) Since Python 3.7 is under active development I can't guarantee it's stability or that things won't change from underneath you, so I'm not going to recommend testing against it yet. But when we announce 3.7.0b1, expect a plea from me to add 3.7-dev to your build matrix (...)
> 
> [Source](https://snarky.ca/how-to-use-your-project-travis-to-help-test-python-itself/#testingthenextfeaturerelease)

What do you guys think?

**Comment by nicoddemus** [comment]
Thanks @pawelad for consider to help out!

I wouldn't spend much time as well, it might be a bug in Python itself. It might be worth investigating though to report the problem to Python if that's the case, otherwise we can wait for the first betas to make sure pytest works with Python 3.7. That's my 2 cents.
