### ISSUE TITLE
Follow symlinks when collecting files

### ISSUE THREAD

**Issue by raddessi** [pytest-dev/pytest#2291]
I have a repo with a python module symlinked to various locations, running the current pytest at the head of the repo re-tests each symlink as if it's new code. Using realpaths instead of relative paths would let us skip already tested code.

This seems to work but may not be ideal, I haven't read through all the collection code yet. Thoughts?
[CHANGELOG.txt](https://github.com/pytest-dev/pytest/files/825790/CHANGELOG.txt)

**Comment by nicoddemus** [comment]
> I have a repo with a python module symlinked to various locations

Do you mean a test file or python module? The rest of the question suggests the first.

Not sure what would be the implications of changing collection to follow symlinks, probably wouldn't matter as this seems somewhat rare.

May I ask why you have test modules symlinked in your repository? It will probably confuse all manner of tools besides pytest.

**Comment by raddessi** [comment]
Im sorry, yes you are correct. I have a python module that does contain test files which is linked in to multiple places in the repo. Its a terrible solution to a terrible problem, but it is what it is and im trying to work around it.

On March 9, 2017 3:58:08 PM MST, Bruno Oliveira <notifications@github.com> wrote:
>> I have a repo with a python module symlinked to various locations
>
>Do you mean a test file or python module? The rest of the question
>suggests the first.
>
>Not sure what would be the implications of changing collection to
>follow symlinks, probably wouldn't matter as this seems somewhat rare.
>
>May I ask why you have test modules symlinked in your repository? It
>will probably confuse all manner of tools besides pytest.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pytest-dev/pytest/issues/2291#issuecomment-285511063

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicoddemus** [comment]
I see. I suggest to take a look at the [collection hooks](http://doc.pytest.org/en/latest/writing_plugins.html#collection-hooks), I'm sure you can use one of them to skip the symlinks. At a glance it seems `pytest_ignore_collect(path, config)` would be simpler to use:

```python
# contents of conftest.py at the root directory
def pytest_ignore_collect(path, config):
    if path.isfile() and path_is_symlink(path):
        return True
```

**Comment by raddessi** [comment]
Oh, that's cool. Doesn't pytest do a recursive search though? The symlink is only to the module directory so it would still see the files inside right? Ill try it out and get back to you. Thanks!

On March 10, 2017 4:33:47 AM MST, Bruno Oliveira <notifications@github.com> wrote:
>I see. I suggest to take a look at the [collection
>hooks](http://doc.pytest.org/en/latest/writing_plugins.html#collection-hooks),
>I'm sure you can use one of them to skip the symlinks. At a glance it
>seems `pytest_ignore_collect(path, config)` would be simpler to use:
>
>```python
># contents of conftest.py at the root directory
>def pytest_ignore_collect(path, config):
>    if path.isfile() and path_is_symlink(path):
>        return True
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pytest-dev/pytest/issues/2291#issuecomment-285647244

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicoddemus** [comment]
> Doesn't pytest do a recursive search though? The symlink is only to the module directory so it would still see the files inside right?

Yes it is recursive, in that case you will have to check if `path` is a directory and a `symlink`; if you ignore a directory, pytest will not recurse in that directory any longer.

I'll close this for now but please let us know if this has worked for you or not as it can be helpful to others.

**Comment by raddessi** [comment]
The collection hook works just fine, thank you :)

On March 10, 2017 4:33:47 AM MST, Bruno Oliveira <notifications@github.com> wrote:
>I see. I suggest to take a look at the [collection
>hooks](http://doc.pytest.org/en/latest/writing_plugins.html#collection-hooks),
>I'm sure you can use one of them to skip the symlinks. At a glance it
>seems `pytest_ignore_collect(path, config)` would be simpler to use:
>
>```python
># contents of conftest.py at the root directory
>def pytest_ignore_collect(path, config):
>    if path.isfile() and path_is_symlink(path):
>        return True
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pytest-dev/pytest/issues/2291#issuecomment-285647244

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wimglenn** [comment]
This worked for my use-case (wanted not to traverse symlinked dirs):

```
# contents of conftest.py at the root directory
def pytest_ignore_collect(path, config):
    if path.isdir() and path.islink():
        return True
```
