### ISSUE TITLE
unique basename for your test file modules

### ISSUE THREAD

**Issue by philtay** [pytest-dev/pytest#2296]
Any news regarding the "unique basename for your test file modules" bug? Is there any solution / best practice to follow? This bug is starting to bite us and I can't find any info about this problem in the docs.

Ref. https://github.com/pytest-dev/pytest/issues/529

**Comment by RonnyPfannschmidt** [comment]
best practice suggestions are in that bug

**Comment by nicoddemus** [comment]
@philtay please take a look at #2297 if you can.
