### ISSUE TITLE
Is dynamic updation of fixture scope possible ? 

### ISSUE THREAD

**Issue by tejas3190** [pytest-dev/pytest#2300]
Like using the same fixture that may have a different scope for setup & teardown based on test cases calling? Are this possible, Thanks

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by nicoddemus** [comment]
Hi,

This is not possible, and probably very hard (impossible?) to implement in the current architecture. I would recommend just using different fixture names. You can avoid duplication by making the fixture call another function which is responsible to create the fixture value. For example:

```python
@pytest.fixture(scope='session')
def foo_session():
    return create_foo()

@pytest.fixture(scope='module')
def foo_module():
    return create_foo()
```

And so on. Then each fixture can decide the scope as usual.

I'm closing this for now but feel free to follow up with any questions.

**Comment by tejas3190** [comment]
Thanks for the suggestion @nicoddemus Great work 👍
