### ISSUE TITLE
searching for help on docs.pytest.org fails with "page does not exist yet".

### ISSUE THREAD

**Issue by slippers** [pytest-dev/pytest#2302]
searching for help on docs.pytest.org fails with "page does not exist yet".  
### steps

searching for "fixture"

[fixture](http://docs.pytest.org/en/latest/search.html?q=fixture&check_keywords=yes&area=default)

returns this page

[pytest.fixtures](http://docs.pytest.org/en/latest/builtin.rst.html?highlight=fixture#_pytest.fixtures.fixture)

### fix?
removing the "rst." from the search result url returns the correct page.

**Comment by nicoddemus** [comment]
Thanks for the report @slippers. It does seem to be related to some configuration related to search, do you have any suggestions on how to fix it?

**Comment by slippers** [comment]
_best guess_ is that this is in the conf.py file for your sphinx site.  could have sensitive stuff.
* check your sphinx version
* determine if you are using a custom search [adapter](http://www.sphinx-doc.org/en/stable/_modules/sphinx/websupport/search.html#BaseSearch)
* if custom then find the adapter that extends BaseSearch?
* end of _best guess_:)

**Comment by RonnyPfannschmidt** [comment]
@slippers we do use readthedocs

**Comment by slippers** [comment]
[bug](https://github.com/rtfd/readthedocs.org/issues/2708) already exists.  so it might fix itself.

uses the rest api elasticsearch for index.  
[pyelasticsearch](https://github.com/pyelasticsearch/pyelasticsearch) for composing the url. build is failing there but no bugs reported.
