### ISSUE TITLE
--last-failed and --failed-first precedence

### ISSUE THREAD

**Issue by ojii** [pytest-dev/pytest#2308]
If I run pytest with `--failed-first` and `--last-failed`, all tests are run. This is unintuitive for me, since I actually include `--failed-first` in my `pytest.ini` so it defaults to running failed tests first. However, sometimes I just want to run the failed tests so I add `--last-failed` at the commend line, but that has no effect.

I think this behaviour should be changed to `--last-failed` taking precedence over `--failed-first`. 

I'd be happy to provide a patch for this if there's an agreement that this is should be changed.

**Comment by RonnyPfannschmidt** [comment]
this is a bugfix that would require a major release due to breaking behavior
i'm in favor, but would shoot a mail to the ml before working on a pr

**Comment by nicoddemus** [comment]
I agree that changing the behavior would make more sense and I can't think of a use-case for the existing behavior, so I'm 👍.

**Comment by flub** [comment]
Another +1 from me. If  you'd like to have a go at submitting a patch that would be great.

**Comment by RonnyPfannschmidt** [comment]
i submit https://xkcd.com/1172/ for version number considerations ^^

**Comment by ojii** [comment]
Submitted #2357

**Comment by nicoddemus** [comment]
Fixed by #2357, thanks again @ojii!
