### ISSUE TITLE
I am using Spyder(Python 3.5) with Ipython console.. How should I test a  function using pytest using Spyder Ipython console??

### ISSUE THREAD

**Issue by yewalenikhil65** [pytest-dev/pytest#2309]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
py.test is currently not compatible with usage from ipython consoles for longer sessions, its not clear what you want to do

**Comment by nicoddemus** [comment]
Closing for lack of follow up
