### ISSUE TITLE
tox needed?

### ISSUE THREAD

**Issue by guettli** [pytest-dev/pytest#2310]
I found this while reading the docs:
> ...  you can use tox to make sure that the package is really correct and tests pass in all required configurations.

Source http://docs.pytest.org/en/latest/goodpractices.html#goodpractices

I am unsure.

Most open source software gets hosted in github today.

On github you have travis.

Travis can do this (test different configurations and Python versions).

For the common use case I see no use for tox.

Since the audience of above text are new comers, I would provide the simple solution first.

Before advising to use tox, I would state that you can use travis at github.

What do you think?

**Comment by RonnyPfannschmidt** [comment]
tox is locally usable, travis isnt and needs different setup, its not even closely the same

**Comment by nicoddemus** [comment]
Not only that, tox is considered the defacto standard for running tests in python projects, so much that most projects have a tox file and use tox on Travis for CI.
