### ISSUE TITLE
capsys fails to capture the output by stdout

### ISSUE THREAD

**Issue by hellock** [pytest-dev/pytest#2314]
Environment:
- OS: macOS 10.12.3
- Python version: 2.7.13/3.6.0
- pytest version: 3.0.7

I find that the outputs by `sys.stdout` can be captured, but those by `stdout` will not.

Example:
```python
# a.py
import sys

def func1():
    sys.stdout.write('a')
    sys.stdout.flush()

# b.py
from sys import stdout

def func2():
    stdout.write('a')
    stdout.flush()

# test.py
def test_func1(capsys):
    func1()
    out, err = capsys.readouterr()
    assert out == 'a'  # ok

def test_func2(capsys):
    func2()
    out, err = capsys.readouterr()
    assert out == 'a'  # AssertionError, out is '' other than 'a'
```
```

**Comment by RonnyPfannschmidt** [comment]
this is expected python behavior, alias by import wont be corrected - we cant search all objects in the active python process for stdout just to be sure
