### ISSUE TITLE
take the authormap trick from pip for release notes

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2324]
as per https://github.com/pypa/pip/blob/master/tasks/generate.py#L12
git can use a authormap to generate release notes,
we should use something similar to fix up our own mapping

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i believe #2397 solves this one, correct?

**Comment by nicoddemus** [comment]
#2397 was about generating release notes, but that pip task you refer to actually is about generating an AUTHORS file automatically.

**Comment by RonnyPfannschmidt** [comment]
i see, thanks

**Comment by recursivelycurious** [comment]
@RonnyPfannschmidt is this still an open issue? Looking for a good first time contribution.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt you still think this would be useful? TBH I'm not sure it is worth doing...

@recursivelycurious great that you are looking for first contributions. We sometimes mark issues with the [easy label](https://github.com/pytest-dev/pytest/labels/status%3A%20easy) which are good candidates for a first contribution. 👍

**Comment by RonnyPfannschmidt** [comment]
valid concerns, i'll agree - thanks for bringing the details up
