### ISSUE TITLE
allow capture to output while also storing the data internally (like tee)

### ISSUE THREAD

**Issue by sangmeshcp** [pytest-dev/pytest#2325]
when i run the test case i have lot of logs which use logger and print in my testcase.. i need mechanism where i can print all the logs while its being executed on screen and capture it to a file descriptor simultaneously .

pytest -s test.py (pytest --capture=no test.py ) 

when I run the logs are printed to sys.stdout which is right ..

what I'm looking for is 

pytest --capture=no,fd

this will ensure i can see what is happening while the test is being executed and the logs are written to the fd which is a file.

example : 

```
$ pytest --capture=no test.py 
============================================================= test session starts =============================================================
platform linux -- Python 3.4.3, pytest-3.0.7, py-1.4.32, pluggy-0.4.0
rootdir: /tmp, inifile:
collected 8 items 

printing testing 123 123 123 from test.. 
None
.



------------------------------------------------------------- Test Summary Begin --------------------------------------------------------------
test.py::test::()::                    : Passed   

-------------------------------------------------------------- Test Summary End ---------------------------------------------------------------
```

the output "printing testing 123 123 123 from test.. " need to written to file as well

**Comment by nicoddemus** [comment]
IIUC, you want pytest to capture stdout and simultaneously print it to screen and write it into a file?

**Comment by sangmeshcp** [comment]
@nicoddemus  yes exactly

**Comment by nicoddemus** [comment]
OK thanks for clarifying.

**Comment by RonnyPfannschmidt** [comment]
i would propose a `py.test --capure=tee_fd`

**Comment by sangmeshcp** [comment]
any update on this ?? anybody implementing this proposal

**Comment by RonnyPfannschmidt** [comment]
@sangmeshcp atm im not aware of anyone having the volunteering time availiable atm,

would you like to try, we def can give guidance, but it will be a while before we can tackle this ourselfes

**Comment by dnut** [comment]
One of these answers recommends monkey patching pytest to implement this use case:
https://stackoverflow.com/questions/14405063/how-can-i-see-normal-print-output-created-during-pytest-run
Maybe this can be adapted to add a new option to pytest?

**Comment by nicoddemus** [comment]
I just remembered that the internal `pastebin` does exactly that:

https://github.com/pytest-dev/pytest/blob/4cb60dac3d7f8b5295d029eaf6ab061bc5e700e7/_pytest/pastebin.py#L17-L36

This definitely could be done by the terminal writer based on an option, like `--tee=file.txt` (which could even be used multiple times).

Seems simple to do, if anyone wants to try it we can give guidance. 👍

**Comment by RonnyPfannschmidt** [comment]
at second glance however, the implementation is incorrect for capture

**Comment by nicoddemus** [comment]
> at second glance however, the implementation is incorrect for capture

You are right, it only works for things pytest is writing out. If we do implement the `--tee` feature (or whatever it is called) we should also update this `pastebin` code.

**Comment by dhood** [comment]
Am I correct in thinking that this has been closed by https://github.com/pytest-dev/pytest/pull/3176?

**Comment by dhood** [comment]
Thanks for the clarification!

**Comment by nicoddemus** [comment]
@rmcgregor1990 interesting, please post an update to this issue when you have something to show. 👍

**Comment by kchawla-pi** [comment]
I would like this feature and I'm willing to invest the time to implement it. However I may not know enough to do it. Where should I start?

**Comment by ssbarnea** [comment]
Did anyone manage to work on this or to have an experimental implementation? I do have some long running functional tests which are triggered by pytest and I really need both, live display and capture. Without this CI may not display any progress for even an hour. If I enable -s mode, I lack the ability to display a html reports with the results.

**Comment by blueyed** [comment]
tee-sys was added in https://github.com/pytest-dev/pytest/pull/6315.
