### ISSUE TITLE
[pytest-xdist] [FR] Pytest-xdist should have its own remote agent

### ISSUE THREAD

**Issue by GeorgeFischhof** [pytest-dev/pytest#2326]
Hi There,

I started to used pytest not too far ago. And I found the xdist plugin. I would like to run test on a remote windows macine.

I saw in the documentation 
(https://pypi.python.org/pypi/pytest-xdist/1.15.0)
the reference for socketserver.py 

I checked the source, and found that it is mainly for unix/linux systems.  
I tried it on windows 7, python 3.5. I sent only a print command to the remote, and it was printed successfully, but after that it wrote some errors. ...

Then I read the docs further and found that it says that __init__.py files should put next to my tests as the remoting handles them this way.

So I bet I would be able to rewrite the socketserver.py, but I think it would be better to create an authentic agent.

And of course I would install pytest on the remote as well (to have all the capabilities on the remote too)
As Python is installed on remote, I think there is no reason not install pytest as well.
(instead of socketserver.py third party stuff)

With this the xdist would be more complete.

Kind regards,
George

**Comment by RonnyPfannschmidt** [comment]
completing this is surprisingly hard once more than pylib and pytest are involved,
as such i would like to see a better idea for this first before just implementing a dead end

we basically need a provisioning and a transfer layer as well as base libraries for this

**Comment by The-Compiler** [comment]
this should probably go to the pytest-xdist issue tracker though.

**Comment by RonnyPfannschmidt** [comment]
oh, right ^^

**Comment by GeorgeFischhof** [comment]
Moved to pytest-xdist issue tracker, #134 
https://github.com/pytest-dev/pytest-xdist/issues/134
