### ISSUE TITLE
What is __multicall__ warning?

### ISSUE THREAD

**Issue by amarao** [pytest-dev/pytest#2332]
I writing an application which relies on pytest as method to perform tests of virtual machines. I wrote a simple plugin to provide VM-related fixtures. It works great, but pytest emits warning:

`WI1 /usr/lib/python2.7/dist-packages/pytest_timeout.py:68 'pytest_runtest_protocol' hook uses deprecated __multicall__ argument`.

Problem is that I never use `__multicall__` and don't really understand what it is. Can you help clarify and fix it?

Actual code is here: https://github.com/serverscom/dibctl/blob/master/dibctl/pytest_runner.py
Stackoverflow question is here: http://stackoverflow.com/questions/43009164/what-is-multicall-argument-and-why-it-is-deprecated

Thanks!

**Comment by RonnyPfannschmidt** [comment]
the pytest_timeout plugin you use seems to be outdated and using that old hook mechanism, i beleive it should be updated

**Comment by amarao** [comment]
Thank you. I reported it as issue for Ubuntu Xenial: https://bugs.launchpad.net/ubuntu/+source/python-pytest-timeout/+bug/1676301

**Comment by RonnyPfannschmidt** [comment]
thank you for the followup, its good to see people act with care 👍
