### ISSUE TITLE
Confusing pytestmark documentation

### ISSUE THREAD

**Issue by asmeurer** [pytest-dev/pytest#2333]
The pytestmark documentation at http://pytest.org/dev/skipping.html#skip-all-test-functions-of-a-class-or-module says:

```py
@pytest.mark.skipif(sys.platform == 'win32',
                    reason="requires windows")
class TestPosixCalls:

    def test_function(self):
        "will not be setup or run under 'win32' platform"
```

The reason given is `"requires windows"`, but if I understand the test correctly, it should be `"requires POSIX"`.

**Comment by RonnyPfannschmidt** [comment]
thats a wrong operator, i believe it should be `!=`
it would be a good contribution

**Comment by asmeurer** [comment]
The class is called TestPosixCalls and the docstring says "will not be setup or run under 'win32' platform". If I understand skipif correctly, the operator is correct, but the reason is wrong.

**Comment by nicoddemus** [comment]
That link is out of date, this has been fixed sometime ago already! 👍 

Where did you find that link btw? It seems like we are redirecting only pytest.org/latest to readthedocs.

**Comment by asmeurer** [comment]
It's the fourth result from Googling "pytest skip". I see the first result is the right one, but I chose that one because of the "dev" in the URL. If those docs are out of date I would suggest removing them.

**Comment by nicoddemus** [comment]
Agreed, thanks for pointing it out.

@RonnyPfannschmidt @hpk42 should we just remove them or redirect them as well?
