### ISSUE TITLE
find the early initialization bug that makes keeping internal pytest_namespace necessary

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2335]
in #2315 i had to commit  afb1778
in order to keep pytest-xdist working correctly

this clearly indicates a bug in early initialization, and i'd like to rectify it
as its a requirement for deprecating pytest_namespace altogether

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt I remember you tackling this, has this been fixed already perhaps?

**Comment by RonnyPfannschmidt** [comment]
Still not tackled, config is a utter mess

**Comment by RonnyPfannschmidt** [comment]
superseeded by my work on #3080 in #3376
