### ISSUE TITLE
how to add options using parser.addoption from a file (not ini, something like fromfile_prefix_chars='@')

### ISSUE THREAD

**Issue by shreyashah** [pytest-dev/pytest#2340]
I know how to do this if this was a python script, where i 
"import argparse "
and do 
"parser = argparse.ArgumentParser(fromfile_prefix_char='@')"

But, I am not understanding this with respect to pytest, as in using the fixture parser.
Any help is appreciated, thanks.

**Comment by nicoddemus** [comment]
There's several examples in the docs, search for `pytest_addoption` and you should hit a few.

Closing this for now, hope that helps, feel free to post more questions here though.

**Comment by shreyashah** [comment]
I looked at pytest_addoption. 
The understanding is:  this method uses parser class which doesn't have a method to read options from a given file.
Note: What I am looking is to open the given file on the cmd line, and read each line as an option 

The reason I want this is because: If I have a long list of cmd line arguments, instead of typing that long list overtime, I can put those options in a file and ask pytest.addoption to use that file to obtain the options

**Comment by nicoddemus** [comment]
Oh I see, thanks for the clarification.

AFAIK that option does not exist, but others could correct me if I'm wrong.

**Comment by shreyashah** [comment]
Right, the argparse module has this feature of reading options from a given file using argparse.ArgumentParser(fromfile_prefix_char='@')

@nicoddemus : Could you please reopen this as a question, instead of closing it. I could get more answers. Thanks.

**Comment by nicoddemus** [comment]
People can still answer even if it is closed. 😉

**Comment by The-Compiler** [comment]
If this is a static set of arguments, you could use `addopts` in a `pytest.ini` instead.

**Comment by RonnyPfannschmidt** [comment]
the basic answer is: py.test does not support this

**Comment by shreyashah** [comment]
ok, thank you all for the answers. I will just take a .ini file or if it is an json file, i will parse that file to a dict and store that dict of my optional arguments and their values in the pytest global namespace hook.

**Comment by nicoddemus** [comment]
No problem. Should we close this now?

**Comment by shreyashah** [comment]
Yes.

**Comment by nicoddemus** [comment]
Thanks!
