### ISSUE TITLE
MPI

### ISSUE THREAD

**Issue by loikki** [pytest-dev/pytest#2345]
Hi,

I am currently trying to develop some tests for a parallel python code using mpi4py, but I was not able to find anything about pytest with MPI.

Is there any support for MPI and, if not, are you planning on adding it?

If you plan to add it, I would like to suggest the possibility to specify the number of threads for each test (or switching from parallel to serial).

Thank you very much!
Best regards

**Comment by RonnyPfannschmidt** [comment]
there are no plans to add MPI support

im not aware of any of the core developers using mpi

there is pytest-xdist for parallel testing

**Comment by nicoddemus** [comment]
> Is there any support for MPI and, if not, are you planning on adding it?

You mean to run tests in parallel or something else?

No plan at all in this regard, and I believe if some kind of support is wanted in the future it should be implemented as a plugin instead of in the core.

**Comment by loikki** [comment]
Thank you for your answer, I will take a look to pytest-xdist.

I mean testing a parallel code as it can go through different path depending if the thread is the master or not.

The tests are quite fast as I am using a reduced problem, but I am getting a low coverage because I am not covering the "slave" part of the code.

**Comment by nicoddemus** [comment]
That seems like a coverage issue instead of pytest... `coverage` and `pytest-coverage` have extensive docs on how to track coverage in other processes/threads, I suggest to take a look there. 👍

**Comment by loikki** [comment]
Ok Thank you very much!

**Comment by loikki** [comment]
I have solved my problem by looking at the coverage done in mpi4py (https://github.com/mpi4py/mpi4py/commit/99844bfe99ac9c628a4bc2a14f116a628df72a77).

Thank you again for your help
