### ISSUE TITLE
Is there a way to pass a dictionary value to an option on cmd line ? 

### ISSUE THREAD

**Issue by shreyashah** [pytest-dev/pytest#2348]
Or a dictionary inside quotes because all the args on cmd line are treated as strings.

**Comment by nicoddemus** [comment]
You mean an arbitrary dictionary, where any key/value is possible? The short answer is no.

If it is simple key/value pairs (without spaces, quotes, special characters) you might get around this by using simple "key=value" strings which can be passed multiple times:

```
py.test --user-info "name=Bruno" --user-info "location=Brazil" 
```

And then turning that into a `dict` yourself inside the plugin.

But (at least without an example) I would urge to avoid that, and use a simple configuration file instead.

PS: In the future, please include an example of what you are trying to accomplish. Just posting an example of the dict you mean to pass would avoid a lot of guessing on the reader's part and might point you to a better alternative if possible. Thanks! 👍

**Comment by shreyashah** [comment]
Ok, sure.
What I am trying to do is pass an extra set of options  thru a dictionary instead of composing a file (If the number of additional options is big, its better to put that in a file and then parse that file).
But say if I just want to pass some 4 to 5 additional options, I would want to create a dict of these options and its values and pass that dict on cmd line.

Say Example:

pytest --custom {'opt1: 'val1', 'opt2': 'val2', 'opt3' : 'val3'}

**Comment by nicoddemus** [comment]
Those are hard-coded options or could be anything?

Passing a dict like that will bring all sort of problems to your users due to shell escaping because of all the special characters (`'`, `:`, `{}`).

If they could be anything I think my previous suggestion would be suitable:

```
pytest --custom "opt1=val1 opt2=val2 opt3=val3"
```

**Comment by RonnyPfannschmidt** [comment]
its perfectly fine to pass  json as argument, however when using shell, use the propper escape mechanism

**Comment by nicoddemus** [comment]
I agree it is possible, but it's certainly not a walk on the park for the user. :smile:

**Comment by nicoddemus** [comment]
Closing as this has not seen activity in awhile.
