### ISSUE TITLE
pytest install on macOs doesn't use venv

### ISSUE THREAD

**Issue by lsenta** [pytest-dev/pytest#2362]
I use virtualenvs with python3 (`brew install python3`),
when I `pip install pytest` the command uses the wrong shebang.

(pytest 3.0.7)

```
> head ~/.virtualenvs/dod-tests/bin/py.test
#!/usr/local/Cellar/python3/3.6.1/bin/python3.6
...
```

so pytest will use a "clean" python:
```
> pytest
Traceback (most recent call last):
  File "/Users/laurent/.virtualenvs/dod-tests/bin/pytest", line 7, in <module>
    from pytest import main
ModuleNotFoundError: No module named 'pytest'
```

The correct shebang would look something like:
```
#!/Users/laurent/.virtualenvs/myvenv/bin/python3.6
...
```

**Comment by The-Compiler** [comment]
Those shebangs should be generated by setuptools. Are you sure you're using the virtualenv's `pip`?

**Comment by lsenta** [comment]
Yes
```
› which pip
/Users/laurent/.virtualenvs/dod-tests/bin/pip
```

**Comment by The-Compiler** [comment]
So you *upgraded* it? Not sure if pip/setuptool rewrites shebangs in existing files. Either way, this sounds like a setuptools and not like a pytest issue.

**Comment by lsenta** [comment]
I did both, I usually fix the shebang but I was already writing a ticket for another pytest issue.
I'll create a ticket for setuptools, thanks for the clarification.

**Comment by lsenta** [comment]
FYI https://github.com/pypa/setuptools/issues/1011

**Comment by nicoddemus** [comment]
Thanks for the xref. 👍
