### ISSUE TITLE
pytest does not display an error or warning when a QWidget is created without a QApplication

### ISSUE THREAD

**Issue by HashSplat** [pytest-dev/pytest#2373]
I was running pytest and was trying to create a QWidget. I forgot to create a QApplication.

I only had one test. The console said 0 of 1 tests run.

Console Output:
...\python.exe "...\PyCharm 2017.1\helpers\pycharm_jb_pytest_runner.py" –path .../tests
Testing started at 11:26 AM ...
 Launching py.test with arguments .../tests
============================= test session starts =============================
platform win32 – Python 3.4.4, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: .../project, inifile:
collected 1 items
 
test_basic_widgets.py     
Process finished with exit code 1

It took me an hour to figure out why the test wouldn't run. There was no error or warning. Once I created a QApplication in the test file everything worked fine. It would be really nice if an error message would pop up. Running pytest in verbose mode did not give a proper error or warning either.

venv:
Python 3.4.4
PySide==1.2.2
pytest==3.0.7

on Windows 7

**Comment by nicoddemus** [comment]
There is really nothing Pytest can do here: if you create a `QWidget` without a `QApplication`, `Qt` will abort the current process and there's nothing pytest can do to prevent that.

I strongly suggest using the [pytest-qt](https://github.com/pytest-dev/pytest-qt) plugin. 😉

**Comment by HashSplat** [comment]
Qt normally shows a warning when you try to do this. Something in pytest
prevents the warning from displaying.

I did not know there was a pytest-qt plugin. Thank you.

**Comment by nicoddemus** [comment]
Does the warning show up if you pass `-s` to pytest?

**Comment by The-Compiler** [comment]
It does (I had the same issue myself before too). This is happening due to pytest's output capturing - and since pytest can't predict the future, and at the point Qt calls `abort()` pytest can't do anything anymore, I don't see anything pytest could do about this either.

**Comment by HashSplat** [comment]
No, the warning does not show up when you pass -s to pytest. I actually do
not know if Qt/PySide does give an error or warning. Qt might just be
printing to stderr.

My console displays the below message in red if I try to create a QWidget
without a QApplication.
"QWidget: Must construct a QApplication before a QPaintDevice"

I thought that was from a warning, but I think Qt or PySide just prints
that message to stderr.

**Comment by HashSplat** [comment]
Ah, I see. pytest has to capture stderr to avoid all of the assertion
errors from displaying. Yeah, I can't think of anything that would help
unless the pytest-qt plugin automatically created a QApplication at
startup, but then if someone did create their own QApplication it would
cause a RuntimeError for creating two QApplications (for PySide at least).
This is an interesting problem.

**Comment by nicoddemus** [comment]
There's more information at the docs, but you should use the `qtbot` fixture to test your widgets, and if you need your own `QApplication` object you can override pytest-qt's `qapp` fixture in your test suite. 😉
