### ISSUE TITLE
Allow customizing showlocals cutoff

### ISSUE THREAD

**Issue by emil-petersen** [pytest-dev/pytest#2382]
The `-l` flag - showlocals - for PyTest allows a test to include the state of local variables in case of test failure.

However, it seems there is a hard-coded limit of 70 characters in this output. From diving through the code, I believe this happens in the SafeRepr object in `py`.

This is an issue in my case because the local variables are dictionaries, and trying to understand a test failure is heavily reliant on the exact content of those variables.

I can log them myself, but doing so defeats the purpose of having `-l` available.

Therefore, I would like to request the ability to configure the cutoff for showing locals. Thank you.

**Comment by ApaDoctor** [comment]
What is the best way to make possible to configure the unlimited locals output?
In config or as command line argument?

**Comment by nicoddemus** [comment]
Today `-l` is a bool flag, I believe we can change it to be an int flag instead, so users can still pass `-l` and obtain the default `70` characters cuf-off, or `-l 200` to set the cut-off to 200.

**Comment by emil-petersen** [comment]
@nicoddemus Assuming it could easily be set in pytest.ini, that would be a great solution from my perspective.

**Comment by The-Compiler** [comment]
> Today `-l` is a bool flag, I believe we can change it to be an int flag instead, so users can still pass `-l` and obtain the default `70` characters cuf-off, or `-l 200` to set the cut-off to 200.

I don't think that'd work - presumably `-l` would then always eat the following argument and show an error if it isn't an int?

**Comment by nicoddemus** [comment]
@The-Compiler yeah when I proposed I wasn't sure it would work, I would say it is worth trying. 

If that doesn't work we will need a separate variable for that, I suggest `-l-cutoff=X` which sets the cut-off to `X` and implies `-l`.

**Comment by ApaDoctor** [comment]
Cut-off to 200 is problem. Because cutoff implemented in py module. 
And _strrepr  allows to change only string length, but not other objects.
So to implement possibility to change cut-off limits we need to change 'py' module first and then provide changes to pytest.
I think great solution is to allow to off cutoff. 
And after release of py changes we can make possible to change cut-off size in oytest.

**Comment by nicoddemus** [comment]
> Cut-off to 200 is problem. Because cutoff implemented in py module.

I believe this is implemented in `pytest._code`:

https://github.com/pytest-dev/pytest/blob/966391c77e8f5c528487b7165af908df4c09ce1d/_pytest/_code/code.py#L541-L562

Although here the `70` limit is commented out. Hmm this warrants more investigation.

**Comment by ApaDoctor** [comment]
Yes, but at line 554 we call self._saferepr()
Which using `py`
`    def _saferepr(self, obj):
        return py.io.saferepr(obj)
`

**Comment by nicoddemus** [comment]
@ApaDoctor I see thanks. Indeed `py.io.saferepr` has some hard-coded values.

**Comment by ApaDoctor** [comment]
@nicoddemus exactly:)
So letls return to my proposal:)) 

> So to implement possibility to change cut-off limits we need to change 'py' module first and then provide changes to pytest.
> I think great solution is to allow to off cutoff.
> And after release of py changes we can make possible to change cut-off size in pytest

**Comment by nicoddemus** [comment]
We might consider just copying the `saferepr` code and modify it as needed; pylib is in maintenance mode and has to be 2.6 compatible, while in pytest we have no such restriction. The `py.io.saferepr` module has only 70~ lines after all.

**Comment by RonnyPfannschmidt** [comment]
as we start to copy more and mnore sublibs of pylib into pytest i start to seriously question that approach

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt in your opinion should we change `pylib's py.io.reprlib` then?

**Comment by blueyed** [comment]
Relavant code: https://github.com/pytest-dev/py/blob/5f1f794f5c5aa25802ea61b4430648438c8d4b93/py/_io/saferepr.py#L59-L71 - it uses maxsize=240 by default.
Python's Repr's has some more limits: https://github.com/python/cpython/blob/20d68dfcc07bd389ce2ea7b0773c44d97ebeb68d/Lib/reprlib.py#L36-L49
It might be hard to transform `--showlocals-length` into that, but it could be applied just on the result then, and maxing out all other limits.
Something to consider test there then is recursion, i.e. without any limit (which does not seem to be supported by Repr itself, but could be hacked by using a never-decreasing int maybe) it might run into a RecursionError.

Apart from that I would say that with `-v` or `-vv` it should not apply limits - similar to other places where you need `-vv` to get the whole diff with assertion errors.

**Comment by blueyed** [comment]
This should work with `-vv` via https://github.com/pytest-dev/pytest/pull/3681 by now at least.
See https://github.com/pytest-dev/pytest/issues/3962 for references / ideas to have a distinct option to have this not be bound to `verbosity`.
