### ISSUE TITLE
How to run python unittests in parallel with each using a separate in-memory SQLite database

### ISSUE THREAD

**Issue by petroslamb** [pytest-dev/pytest#2384]
Hi, I am trying to parallelize an extensive testsuite in Python and each test uses an SQLite in-memory database to mimic the actual db. 

I keep getting database errors like:

 - `OperationalError: (sqlite3.OperationalError) disk I/O error [SQL: u'\nCREATE TABLE myplot (\n\tid INTEGER NOT NULL, \n\tplot_id INTEGER NOT NULL, \n\tactivity_time INTEGER NOT NULL, \n\ty FLOAT NOT NULL, \n\tPRIMARY KEY (id)\n)\n\n']`

 - `OperationalError: (sqlite3.OperationalError) no such table: blacklists`

 - `OperationalError: (sqlite3.OperationalError) database is locked`

Not sure what to do here, my setup is like:

- platform linux2 -- Python 2.7.6, pytest-3.0.7, py-1.4.33,pluggy-0.4.0
- plugins: xdist-1.16.0, cov-2.4.0

and I am running things with:

`$ pytest --cov=src -n 8`

The application it self is using SQLAlchemy and most tests create the database with more or less the classic:

```python
def _initialize_connection(*args, **kwargs):
    """
    It connects to the database and create a working session
    """
    global engine, ScopedSession
    engine = create_engine(*args, **kwargs)
    Session.configure(bind=engine)
    ScopedSession = scoped_session(Session)
```

and set things with a URI of the form:

```python
db.connect('sqlite:///:memory:')
db.rebuild()
```

Thank you for your help and work.

**Comment by nicoddemus** [comment]
Did you find the solution yourself @petroslamb? If so please post it here so others can benefit from it. 😁

**Comment by petroslamb** [comment]
Yes @nicoddemus it was a mistake on my part. My database was initialized to a in-file one (yes just the same one name for all the suite) by a forgotten switch, which does not work in parallel. Once I properly switched to the in-memory implementation, everything worked fine.

**Comment by nicoddemus** [comment]
Thanks!
