### ISSUE TITLE
Segmentation fault on pytest process exit

### ISSUE THREAD

**Issue by nicoulaj** [pytest-dev/pytest#2394]
On my CI server, the test process randomly crashes with a segmentation fault on exit.

My project uses scientific libraries with native extensions, so I guess this is some cleanup/shutdown stuff missing, but I am not sure how to investigate this...

I tried using `pytest-faulthandler` but it does not provide any more information, probably because it crashes at a later stage.

Here is some information:
 * OS: CentOS 6.8 x86_64
 * Python 2.7.13 (from [IUS](https://ius.io) repository)
 * Pytest 3.0.7
 * Pytest command:

       py.test \
           --html=build/tests/tests.html \
           --junitxml=build/tests/tests.xml \
           --cov XXXXXXXXX \
           --cov-report term \
           --cov-report html:build/tests/coverage \
           --cov-report xml:build/tests/coverage.xml \
           --log-format="%(message)s" \
           --log-date-format="%H:%M:%S"

 * Virtualenv contents:

       future [required: ==0.15.2, installed: 0.15.2]
       h5py [required: ==2.6, installed: 2.6.0]
       - numpy [required: >=1.6.1, installed: 1.11.2]
       - six [required: Any, installed: 1.10.0]
       matplotlib [required: ==1.5.0, installed: 1.5.0]
       - cycler [required: Any, installed: 0.10.0]
         - six [required: Any, installed: 1.10.0]
       - numpy [required: >=1.6, installed: 1.11.2]
       - pyparsing [required: !=2.0.4,>=1.5.6, installed: 2.2.0]
       - python-dateutil [required: Any, installed: 2.6.0]
         - six [required: >=1.5, installed: 1.10.0]
       - pytz [required: Any, installed: 2017.2]
       numpy [required: ==1.11.2, installed: 1.11.2]
       scikit-image [required: ==0.12.3, installed: 0.12.3]
       - dask [required: >=0.5.0, installed: 0.14.2]
       - matplotlib [required: >=1.3.1, installed: 1.5.0]
         - cycler [required: Any, installed: 0.10.0]
           - six [required: Any, installed: 1.10.0]
         - numpy [required: >=1.6, installed: 1.11.2]
         - pyparsing [required: !=2.0.4,>=1.5.6, installed: 2.2.0]
         - python-dateutil [required: Any, installed: 2.6.0]
           - six [required: >=1.5, installed: 1.10.0]
         - pytz [required: Any, installed: 2017.2]
       - networkx [required: >=1.8, installed: 1.11]
         - decorator [required: >=3.4.0, installed: 4.0.11]
       - pillow [required: >=2.1.0, installed: 4.1.1]
         - olefile [required: Any, installed: 0.44]
       - scipy [required: >=0.9.0, installed: 0.17.0]
       - six [required: >=1.7.3, installed: 1.10.0]
       scipy [required: ==0.17, installed: 0.17.0]
       Shapely [required: ==1.5.17.post1, installed: 1.5.17.post1]
       statsmodels [required: ==0.6.0, installed: 0.6.0]
       - pandas [required: Any, installed: 0.19.2]
         - numpy [required: >=1.7.0, installed: 1.11.2]
         - python-dateutil [required: Any, installed: 2.6.0]
           - six [required: >=1.5, installed: 1.10.0]
         - pytz [required: >=2011k, installed: 2017.2]
       - patsy [required: Any, installed: 0.4.1]
         - numpy [required: Any, installed: 1.11.2]
         - six [required: Any, installed: 1.10.0]
       - scipy [required: Any, installed: 0.17.0]
       pytest-catchlog==1.2.2
         - py [required: >=1.1.1, installed: 1.4.33]
         - pytest [required: >=2.6, installed: 3.0.7]
           - py [required: >=1.4.29, installed: 1.4.33]
           - setuptools [required: Any, installed: 35.0.2]
             - appdirs [required: >=1.4.0, installed: 1.4.3]
             - packaging [required: >=16.8, installed: 16.8]
               - pyparsing [required: Any, installed: 2.2.0]
               - six [required: Any, installed: 1.10.0]
             - six [required: >=1.6.0, installed: 1.10.0]
       pytest-cov==2.4.0
         - coverage [required: >=3.7.1, installed: 4.3.4]
         - pytest [required: >=2.6.0, installed: 3.0.7]
           - py [required: >=1.4.29, installed: 1.4.33]
           - setuptools [required: Any, installed: 35.0.2]
             - appdirs [required: >=1.4.0, installed: 1.4.3]
             - packaging [required: >=16.8, installed: 16.8]
               - pyparsing [required: Any, installed: 2.2.0]
               - six [required: Any, installed: 1.10.0]
             - six [required: >=1.6.0, installed: 1.10.0]
       pytest-faulthandler==1.3.1
         - faulthandler [required: Any, installed: 2.6]
         - pytest [required: >=2.6, installed: 3.0.7]
           - py [required: >=1.4.29, installed: 1.4.33]
           - setuptools [required: Any, installed: 35.0.2]
             - appdirs [required: >=1.4.0, installed: 1.4.3]
             - packaging [required: >=16.8, installed: 16.8]
               - pyparsing [required: Any, installed: 2.2.0]
               - six [required: Any, installed: 1.10.0]
             - six [required: >=1.6.0, installed: 1.10.0]
       pytest-html==1.14.2
         - pytest [required: >=2.3, installed: 3.0.7]
           - py [required: >=1.4.29, installed: 1.4.33]
           - setuptools [required: Any, installed: 35.0.2]
             - appdirs [required: >=1.4.0, installed: 1.4.3]
             - packaging [required: >=16.8, installed: 16.8]
               - pyparsing [required: Any, installed: 2.2.0]
               - six [required: Any, installed: 1.10.0]
             - six [required: >=1.6.0, installed: 1.10.0]
         - pytest-metadata [required: Any, installed: 1.3.0]
           - pytest [required: >=2.9.0, installed: 3.0.7]
             - py [required: >=1.4.29, installed: 1.4.33]
             - setuptools [required: Any, installed: 35.0.2]
               - appdirs [required: >=1.4.0, installed: 1.4.3]
               - packaging [required: >=16.8, installed: 16.8]
                 - pyparsing [required: Any, installed: 2.2.0]
                 - six [required: Any, installed: 1.10.0]
               - six [required: >=1.6.0, installed: 1.10.0]
       pytest-pep8==1.0.6
         - pep8 [required: >=1.3, installed: 1.7.0]
         - pytest [required: >=2.4.2, installed: 3.0.7]
           - py [required: >=1.4.29, installed: 1.4.33]
           - setuptools [required: Any, installed: 35.0.2]
             - appdirs [required: >=1.4.0, installed: 1.4.3]
             - packaging [required: >=16.8, installed: 16.8]
               - pyparsing [required: Any, installed: 2.2.0]
               - six [required: Any, installed: 1.10.0]
             - six [required: >=1.6.0, installed: 1.10.0]
         - pytest-cache [required: Any, installed: 1.0]
           - execnet [required: >=1.1.dev1, installed: 1.4.1]
             - apipkg [required: >=1.4, installed: 1.4]
           - pytest [required: >=2.2, installed: 3.0.7]
             - py [required: >=1.4.29, installed: 1.4.33]
             - setuptools [required: Any, installed: 35.0.2]
               - appdirs [required: >=1.4.0, installed: 1.4.3]
               - packaging [required: >=16.8, installed: 16.8]
                 - pyparsing [required: Any, installed: 2.2.0]
                 - six [required: Any, installed: 1.10.0]
               - six [required: >=1.6.0, installed: 1.10.0]
       pytest-timeout==1.2.0
         - pytest [required: >=2.8.0, installed: 3.0.7]
           - py [required: >=1.4.29, installed: 1.4.33]
           - setuptools [required: Any, installed: 35.0.2]
             - appdirs [required: >=1.4.0, installed: 1.4.3]
             - packaging [required: >=16.8, installed: 16.8]
               - pyparsing [required: Any, installed: 2.2.0]
               - six [required: Any, installed: 1.10.0]
             - six [required: >=1.6.0, installed: 1.10.0]
       pytest-xdist==1.16.0
         - execnet [required: >=1.1, installed: 1.4.1]
           - apipkg [required: >=1.4, installed: 1.4]
         - py [required: >=1.4.22, installed: 1.4.33]
         - pytest [required: >=2.7.0, installed: 3.0.7]
           - py [required: >=1.4.29, installed: 1.4.33]
           - setuptools [required: Any, installed: 35.0.2]
             - appdirs [required: >=1.4.0, installed: 1.4.3]
             - packaging [required: >=16.8, installed: 16.8]
               - pyparsing [required: Any, installed: 2.2.0]
               - six [required: Any, installed: 1.10.0]
             - six [required: >=1.6.0, installed: 1.10.0]
       requests==2.13.0
       toolz==0.8.2
       wheel==0.30.0a0

* Core dump backtrace:

       #0  _dl_fini () at dl-fini.c:239
       #1  0x00000038ea035d92 in __run_exit_handlers (status=0) at exit.c:78
       #2  exit (status=0) at exit.c:100
       #3  0x0000003849506a5f in Py_Exit (sts=0) at /usr/src/debug/Python-2.7.13/Python/pythonrun.c:1793
       #4  0x0000003849506ba1 in handle_system_exit () at /usr/src/debug/Python-2.7.13/Python/pythonrun.c:1159
       #5  0x0000003849506e2d in PyErr_PrintEx (set_sys_last_vars=1) at /usr/src/debug/Python-2.7.13/Python/pythonrun.c:1169
       #6  0x000000384950731e in PyRun_SimpleFileExFlags (fp=<value optimized out>, filename=<value optimized out>, closeit=<value optimized out>, flags=
           0x7fff7fa218e0) at /usr/src/debug/Python-2.7.13/Python/pythonrun.c:960
       #7  0x0000003849518d36 in Py_Main (argc=<value optimized out>, argv=<value optimized out>) at /usr/src/debug/Python-2.7.13/Modules/main.c:640
       #8  0x00000038ea01ecdd in __libc_start_main (main=0x400710 <main>, argc=14, ubp_av=0x7fff7fa21a08, init=<value optimized out>, 
           fini=<value optimized out>, rtld_fini=<value optimized out>, stack_end=0x7fff7fa219f8) at libc-start.c:226
       #9  0x0000000000400649 in _start ()

Any idea how to investigate this ?

**Comment by RonnyPfannschmidt** [comment]
it might help if you can provide a container that runs into the same error - its hard to replicate your issue,

you might need to try a debug build of python in gdb to get at this issue

**Comment by The-Compiler** [comment]
You could also try to run the tests inside [valgrind](http://valgrind.org/) (with the [Python valgrind suppression file](https://github.com/python/cpython/blob/master/Misc/valgrind-python.supp), also see [README.valgrind](https://github.com/python/cpython/blob/master/Misc/README.valgrind).

I'd first try to narrow it down to one specific test though, and then reimplement that without pytest (or ideally without Python).

Closing this issue, as it's very unlikely pytest has anything to do with this.
