### ISSUE TITLE
Xdist hook equivalent to pytest_runtest_call

### ISSUE THREAD

**Issue by westhomas** [pytest-dev/pytest#2402]
The hook `pytest_runtest_call` is very useful, but doesn't seem to fire for xdist enabled runs.

What is the equivalent hook for xdist?

**Comment by RonnyPfannschmidt** [comment]
The hook is fired in workers, without knowing your usecase we can't help

**Comment by westhomas** [comment]
Here's a sample. The `pytest_runtest_call` doesn't seem to be run when `-d` is used.


```python
#test.py
import unittest
import pytest

def test_foo():
    assert True

def test_bar():
    assert True

def main():

    class MyPlugin(object):
        def __init__(self, data):

            self.__name__ = "myplugin"
            self.data = data
            self.collected = set()

        def pytest_runtest_call(self, item):
            print('item: %s' % item)    <==== this line never seems to be hit

        def pytest_xdist_node_collection_finished(self, node, ids):
            self.collected.update(set(ids))

        def pytest_collection_modifyitems(self, items):
            for item in items:
                self.collected.update({item.nodeid})

        @pytest.fixture(autouse=True)
        def info(self, request):
            test = request.config.pluginmanager.get_plugin('myplugin')
            print("fixture: ", test.data)

    myplugin = MyPlugin('information')

    args = ["test.py", "-s",]
    args += "-d --tx 4*popen//python=python3".split(' ')
    pytest.main(args, plugins=[myplugin])

    print("Collected:", myplugin.collected)

if __name__ == "__main__":
    main()
```

**Comment by RonnyPfannschmidt** [comment]
that plugin is never added in subprocesses that do the actual testing
the plugin is only added on the master process and will not run a test

**Comment by westhomas** [comment]
So is there some Xdist hook equivalent that I can get to fire every time a test is executed?

**Comment by nicoddemus** [comment]
I think the problem here is that the plugin is being installed via the `plugins=[myplugin]` argument to `pytest.main()`; if it is a conventional plugin (installed via setup tools) or a conftest file then `pytest_runtest_call` will be called in the slaves as expected.

The `plugins` argument to `pytest.main()` is just a shortcut for quick prototyping and unfortunately it doesn't work in all cases as a full fledged plugin. This is an unfortunate inconsistency of course, but I'm not sure if it is solvable to cover all possible cases. For pytest-xdist for example, normal plugins are executed because each worker will load the plugin as part of its bootstrap process, whereas the plugin *instance* passed via the `plugins=` argument would have to be transported to the worker processes somehow.

**Comment by westhomas** [comment]
Thanks for the pointers. That makes sense.  Here's a sample of what you described as the proper way to do it, but I'm still not seeing `pytest_runtest_call` fire when xdist is used.


```python
# test-plugin.py
import pytest
from _pytest.config import get_plugin_manager

# Tests
def test_foo():
    assert True

def test_bar():
    assert True

# Plugins
def pytest_configure(config):
    config.pluginmanager.register(MyPlugin())

class MyPlugin(object):
    def __init__(self):
        self.__name__ = "myplugin"
        self.collected = set()

    def pytest_runtest_call(self, item):
        print('pytest_runtest_call')
        print('item: %s' % item)

    def pytest_xdist_node_collection_finished(self, node, ids):
        self.collected.update(set(ids))
        print('pytest_xdist_node_collection_finished')

    def pytest_collection_modifyitems(self, items):
        print('pytest_collection_modifyitems')
        for item in items:
            self.collected.update({item.nodeid})
            
# Execute Tests
def main():

    # This run causes `pytest_runtest_call` to fire
    args = ["test-plugin.py", "-s",]
    pytest.main(args)

    # This run will not fire `pytest_runtest_call`
    args += "-d --tx 4*popen//python=python3".split(' ')
    pytest.main(args)

    # Gather data about execution
    mgr = get_plugin_manager()
    myplugin = mgr.getplugin("myplugin")
    print("Collected:", myplugin.collected)

if __name__ == "__main__":
    main()
```

**Comment by RonnyPfannschmidt** [comment]
2 bits to consider
* `-s` does not work for xdist. 
* pytest_xdist_node_collection_finished happens only on the master, the rest happens only on the slaves whose output you will not be able to see

**Comment by nicoddemus** [comment]
@westhomas, the remark about `-s` is important, could you try logging to a file instead of printing?

**Comment by nicoddemus** [comment]
@westhomas closing this for now, but feel free to post more information in which case we can reopen this. 👍
