### ISSUE TITLE
Class decorator marks multiple classes

### ISSUE THREAD

**Issue by tetianakh** [pytest-dev/pytest#2404]
If test classes inherit from a base class, marking one of them as `xfail` marks the next classes also.
Here's a minimal example:

```
import pytest

class FooCase:
    def test_foo(self):
        assert True

class TestFoo(FooCase):
    pass

@pytest.mark.xfail()
class TestBar(FooCase):
    pass

class TestMoreFoo(FooCase):
    pass
```
When running this, the 2nd test is XPASS (as expected), and the third one is XPASS too (unexpectedly):

```
(.venv) ➜  pytest-fail pytest -vv
=========================== test session starts===============================
platform linux -- Python 3.5.2, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /home/tetiana/stuff/pytest-fail/.venv/bin/python3.5
cachedir: .cache
rootdir: /home/tetiana/stuff/pytest-fail, inifile:
collected 3 items 

test_poc.py::TestFoo::test_foo PASSED
test_poc.py::TestBar::test_foo XPASS
test_poc.py::TestMoreFoo::test_foo XPASS
```
Environment: Ubuntu 16.04, Python 3.5.2; pip freeze output:
```
pkg-resources==0.0.0
py==1.4.33
pytest==3.0.7
```

In my project, I have a suite of functional tests, where the tests are the same, but setup fixtures are different. So the tests are defined in a base class, and there's a subclass for each kind of setup.
Sadly, I can't mark a subclass as `xfail`, because then classes which are collected later (even in different files!) get marked as `xfail`.

Any help is much appreciated.

If someone could point me to the part of the source code where the problem might be, I'll gladly look into it.

**Comment by The-Compiler** [comment]
See #568, #1670.
