### ISSUE TITLE
Move pytest-xprocess to github

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#2409]
I'd like to propose we migrate pytest-xprocess to Github. It's currently in Bitbucket without an issue tracker leading to issues like #953 and this one having no proper home. Plus, Github seems to be the preferred home for pytest projects.

I'm happy to do the work of converting the repo, and since there are no issues to migrate, that should be easy, but the most important part will be cutting a new release with a reference to the new home and redirecting from the old repo, where I probably don't have access. If someone would grant PyPI and Bitbucket access (same username jaraco), then I'll do the legwork.

**Comment by hpk42** [comment]
hey jason.  thanks for the offer.   are you sure you can't admin the bitbucket repos?  You are part of the pytest- development group which has admin access to https://bitbucket.org/pytest-dev/pytest-xprocess  .  to be sure, i also added you as explicit admin.

**Comment by jaraco** [comment]
@hpk42: I hadn't checked bitbucket, but you're probably right.

**Comment by hpk42** [comment]
@jaraco you are also maintainer for pytest-xprocess now.

**Comment by jaraco** [comment]
Repository is migrated and plugin is re-released to [PyPI with a reference to Github](https://pypi.python.org/pypi/pytest-xprocess). I see now that I missed a reference, so I'll update that subsequently.

**Comment by nicoddemus** [comment]
Awesome! Thanks @jaraco, we appreciate it! 👍
