### ISSUE TITLE
How can I get a fixture value without running any tests

### ISSUE THREAD

**Issue by sedefass** [pytest-dev/pytest#2417]
Is there a way to save the value of parameter, provided by pytest fixture:

>  # content of conftest.py
>
>import pytest
>
>def pytest_addoption(parser):
>   parser.addoption("--parameter", action="store", default="default",
>                     help="configuration file path")
>
>@pytest.fixture
>def param(request):
>    parameter = request.config.getoption("--parameter")
>    return parameter

>  # content of my_test.py
>
>def test_parameters(param):
>    assert param == "yes"

OK - everything works fine, but is there a way to get the value of param outside the test - for example with some build-in pytest function `pytest.get_fixture_value["parameter"]` that returns `my_prameter` as a string if I have run my tests with the command `pytest --parameter=my_parameter my_tests.py::my_test`

**Comment by nicoddemus** [comment]
`request.config` object is the same `config` object passed to a lot of the builtin hooks (for example `pytest_configure(config)`, so that can be accessed from those hooks in the same manner.

**Comment by sedefass** [comment]
Ok, but can I use in such a case:

>#content of my_test.py
> my_global_variable = request.config.getoption("--parameter")

**Comment by nicoddemus** [comment]
`request` by definition comes from a test-function-request, so the short answer is no.

You can do this though:

```python
# conftest.py
my_global_variable = None

def pytest_configure(config):
    global my_global_variable
    my_global_variable = config.getoption("--parameter")
```

**Comment by sedefass** [comment]
And how to pass that `my_global_variable ` from `conftest.py` to `my_test.py`

**Comment by nicoddemus** [comment]
```python
# conftest.py
import my_test

def pytest_configure(config):
    my_test.my_global_variable = config.getoption("--parameter")
```

But keep in mind that this variable will only be set when executed with `pytest` (naturally).

**Comment by sedefass** [comment]
I think I got it, cheers for the support.

**Comment by nicoddemus** [comment]
No problem! 👍
