### ISSUE TITLE
[Py2] UnicodeDecodeError in doctest with Unicode

### ISSUE THREAD

**Issue by inducer** [pytest-dev/pytest#2434]
Save this file as `x.rst`:

```rst
.. doctest::

    >>> print(
    ...    "Hi\n\nByé")
    Hi
    ...
    Byé
    >>> 1/0
    1
```

Run with
```
python -m pytest x.rst 
```

on pytest 3.1.0 with Python 2.7.11, observe lengthy [stacktrace](https://gist.github.com/inducer/be75c9aff6cee25ac7f6babacee2853c) ending with a `UnicodeDecodeError` in `_ellipsis_match`. Pytest 3.0.4 works fine.

**Comment by nicoddemus** [comment]
Thanks for the report and the reproducible example, we appreciate it.

**Comment by NiklasMM** [comment]
I was still able to reproduce this issue with the following file:

```python
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

def fix_bad_unicode(text):
    """
        >>> print fix_bad_unicode('Ãºnico')
        único
    """
    return "único"

```

Save as `test.py` and run `python -m pytest --doctest-modules test.py`. This results in an equally unpleasant [stacktrace](https://gist.github.com/NiklasMM/fe34154aad29e837e0efbd100647523d).

For what it's worth: I made this file while debugging the same error generated by the file embedded in [this](http://code.activestate.com/recipes/578243-repair-common-unicode-mistakes-after-theyve-been-m/) blog post.

**Comment by nicoddemus** [comment]
Indeed I can reproduce the problem using you example, thanks!

**Comment by inducer** [comment]
I don't have time to come up with another reproducer, but this issue is not entirely fixed: https://gitlab.tiker.net/inducer/loopy/-/jobs/40102.
