### ISSUE TITLE
--strict option is not related to warnings at all

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2444]
```
(venv) $ pytest --help
...
  --strict              run pytest in strict mode, warnings become errors
...

(venv) $ pytest --strict test_something.py 
========================== test session starts ==========================
platform darwin -- Python 3.6.1, pytest-3.1.0, py-1.4.33, pluggy-0.4.0
rootdir: /Users/okken/projects/book/bopytest/Book/code/foo, inifile:
collected 0 items 

=========================== warnings summary ============================
test_something.py::TestHelper
  cannot collect test class 'TestHelper' because it has a __init__ constructor

-- Docs: http://doc.pytest.org/en/latest/warnings.html
====================== 1 warnings in 0.01 seconds =======================
```

**Comment by RonnyPfannschmidt** [comment]
it seems to be used only and explicitly only in the mark module which doesnt issue warnings about unknown marks at the moment

so strict was never implemented correct

**Comment by The-Compiler** [comment]
`--strict` was added before pytest had a concept of warnings really - I also remember there was a discussion about how it'd be bad for `--strict` to introduce more failures (a viewpoint I'm not sure I agree with, FWIW), because everyone is using it for marker warnings already anyways.

**Comment by RonnyPfannschmidt** [comment]
so we either start a rename process so its named for what it actually does or make it fail more things

**Comment by okken** [comment]
If it never worked as described, I would recommend changing the help text to state that --strict turns on the requirement that markers have to be declared and remove the reference to warnings.

**Comment by nicoddemus** [comment]
Definitely!

**Comment by nicoddemus** [comment]
I propose we just update the help text related to `--strict`, and document more prominently how to turn warnings into errors: `-W error`.
