### ISSUE TITLE
warnings: support for logging.captureWarnings

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#2449]
Moved from https://github.com/pytest-dev/pytest/pull/2445#issuecomment-304906417:

The warnings plugin does not handle the case where the logging module's `captureWarnings` mechanism is used to route warnings through the logging module, and therefore allows to filter them:

```python
logging.captureWarnings(True)
logging.getLogger('py.warnings').addFilter(filter_deprecation_warnings)
```

`logging.captureWarnings` monkeypatches `warnings.showwarning` (in Python 3.6) to log them instead (as a warning).
pytest could maybe check if `logging._warnings_showwarning is not None` to detect if warnings are supposed to go through `logging`.

With or without this in setup.cfg:
```ini
[tool:pytest]
filterwarnings =
    once::DeprecationWarning
    once::PendingDeprecationWarning
```

This mechanism is useful if you want to have fine-grained support on filtering, e.g. based on some (dynamic) path in the warning message.

I am not sure if it is worth the effort to do something in this regard, and if so what the best option would be: maybe transferring it into a log record and see if the `py.warnings` handlers would filter them?

**Comment by nicoddemus** [comment]
Thanks for posting the issue @blueyed.

IIUC the idea is for pytest to no longer capture warnings if `logging.captureWarnings` is set, IOW, just let the `logging` module handle warnings itself?

Just to make sure I understand the issue: if you disable the warnings plugin using `-p no:warnings`, the logging methods works as usual correct?

**Comment by blueyed** [comment]
Yes, and yes.

It is really a corner case, and I am going to remove this from the affected project anyway, but rather rely on what filtering `warnings` provides (via pytest's settings also).

**Comment by nicoddemus** [comment]
Would it be sufficient to mention this as a blurb in the docs, or do you feel we need additional support in the code?

**Comment by blueyed** [comment]
Don't let this hold back a release, not even for the blurb in the docs, please.

I will have to think myself (and would appreciate any input of course) about how this should get handled / documented: after all you want to filter warnings by redirecting them through `logging`.

The issue here is that `warnings.catch_warnings` (used by pytest) disables that.
So it might even be considered to be an issue in the stdlib - depending on where you look at it from.  I can see that you really might want to catch all warnings with that.

**Comment by nicoddemus** [comment]
> Don't let this hold back a release, not even for the blurb in the docs, please.

Docs should not hold a release, given that they are published directly from `master`. 😉 

> I will have to think myself (and would appreciate any input of course) about how this should get handled / documented: after all you want to filter warnings by redirecting them through logging.

I think just documenting this use case in `warnings.rst` might be enough, something like a blurb/section stating to disable the plugin if you are using this feature from `logging`.

**Comment by exhuma** [comment]
I think I've run into the same issue.

I have an old test-suite which has not yet been converted to pytest-style tests (it still uses subclasses of `unittest.TestCase`). So I can't use pytest fixtures. I now plan to invalidate an old set of API calls in this application and want to make sure that I emit proper deprecation warnings.

To make sure they are emitted I planned to use `logging.captureWarnings` and inspect the recorded logs. But if I understood this issue correctly, this is currently impossible with pytest?

I tried using `-p no:warnings` but now I don't get any warnings at all.
