### ISSUE TITLE
provide redirects for docs.pytest.org/latest/foo.html to docs.pytest.org/en/latest/foo.html

### ISSUE THREAD

**Issue by mika** [pytest-dev/pytest#2453]
Lately I stumbled upon several places where URLs are pointing to e.g. https://docs.pytest.org/latest/tmpdir.html while this is a 404 nowadays and should instead be https://docs.pytest.org/en/latest/tmpdir.html

Example for two such sites which point to https://docs.pytest.org/latest/tmpdir.html:

* https://stackoverflow.com/questions/36070031/creating-a-temporary-directory-in-pytest
* https://github.com/jiffyclub/pytest-features/blob/master/README.md

(IIRC this affects more than just the tmpdir docs since I stumbled upon some 404s when looking for docs)

Reporting here-by as follow up on IRC, thanks for pytest!

**Comment by fschulze** [comment]
Fixed

**Comment by The-Compiler** [comment]
Thanks @fschulze!

**Comment by nicoddemus** [comment]
👍
