### ISSUE TITLE
build is broken due to hypothesis/setuptools

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2456]
https://travis-ci.org/pytest-dev/pytest/jobs/238224785

**Comment by The-Compiler** [comment]
See https://github.com/pypa/setuptools/issues/1042

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup, now i dont have to do it ;P do we fix, or wait for a fix

**Comment by The-Compiler** [comment]
I'm still waiting for a fix for qutebrowser FWIW, hoping something will be out over the next few hours.

**Comment by hynek** [comment]
FWIW this fixes it for me: https://github.com/python-attrs/attrs/commit/f8dab9b7ac9306169aee2b740c2e42c96b51c228

And this little incident seems like a good nudge to maybe adopt it. :)

**Comment by RonnyPfannschmidt** [comment]
pypa/setuptools#1043 will fix this - the pattern is nice to have tho, we should upstream it into tox perhpas,

**Comment by The-Compiler** [comment]
I don't think `VIRTUALENV_NO_DOWNLOAD=1` is a good idea in the general case - that probably means your virtualenv has your system's pip, which might be either ancient or patched in funny ways (Debian, Ubuntu), no?

Also, the affected pip version was pulled from PyPI as a hotfix, so this should be fixed. Let's hope the next update works better 😆

**Comment by nicoddemus** [comment]
Nice. Didn't know it was possible to pull packages from PyPI.
