### ISSUE TITLE
Document all warnings not shown by default

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2457]
when implementing #2445 to fix  #2430 we only mention the cases of warning subtypes we where made aware of

@hynek brough to attention that other warning subclasses are affected as well and we should update the documentation/changelog to reflect that

this is also a good first contribution

**Comment by nicoddemus** [comment]
With 3.1.1 we are not messing with the warning filters anymore, so we are displaying what Python does by default. Perhaps we should document just that instead?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus whatever documents the current situation best should be used - but im not sure what bits to explain there

**Comment by nicoddemus** [comment]
> whatever documents the current situation best should be used

Agreed. I guess just mentioning that pytest will display the warnings respecting the filters currently configured.
