### ISSUE TITLE
What is idiomatic way of sharing global state across tests?

### ISSUE THREAD

**Issue by jurisbu** [pytest-dev/pytest#2461]
Hello!

My uses case is as follows: I want to share a test environment configuration (servers, IPs, hostnams, users etc.) across all tests. This configuration should be accessible from tests, fixtures and helper/util functions (which are not pytest aware). On top of that configuration should be environment specific e.g. I should be able to select environment with pytest cmdline option.

## What I have

1. Using `pytest_addoption` hook add `--env` option to select desired test environment.

## What I have tried in regards to configuration sharing

1. Using `pytest_configure` hook read appropriate configuration (depending on `config.getoption('env')` value). Then add my test configuration as new attribute `config.testconfig`.

The downside of this is that configuration is only available from `request` fixture as `request.config.testconfig` which works for tests and fixtures, but does not work for helper functions that are pytest unaware.

2. Similar to `#1`, but instead use `pytest` module namespace e.g. add configuration in `pytest.testconfig`.

This seems to have advantage that configuration is available even to helper functions as long as `pytest` module is imported.

3. Similar to `#2`, but instead of `pytest` namespace add configuration in some dummy module like `globals` e.g. `globals.testconfig`.

Any suggestion on what is most idiomatic way to approach this? Maybe there is already a known pattern for this. I read through pytests diocumentation and did not notice anything related to my use case.

**Comment by RonnyPfannschmidt** [comment]
indirect dependencies are generally strongly discouraged as they are a common source of fragility/errors
if you need to configure/setup them, use a singleton object you configure for the test session

**Comment by jurisbu** [comment]
@RonnyPfannschmidt Right. I agree with you premise in context of unittests, not so much in context of higher level tests. In my case I am bending pytest for functional tests. Also the _test configuration_ that I need to share is static once it is setup.

Can you elaborate on singleton object? When it will be created? In which namespace should it be placed? Example would be much appreciated :)

**Comment by RonnyPfannschmidt** [comment]
the singleton object can basically be in any python module, you just invoke code to configure it, and then use it

btw, its not hard to do functional tests with pytest, but if you need to bend things, then its due to poor test-ability of your code

**Comment by jurisbu** [comment]
OK, seems your suggested singleton object is pretty similar to what I tried as option `#3`.

**Comment by nicoddemus** [comment]
I agree that option `#3` is the way to if you must share this kind of state. Ideally you should configure your `app.config` object at application startup and when starting the test session. To initialize it during testing the `pytest_configure` approach is sufficient IMO.

I'm closing this as I think we have reached an answer, but feel free to follow up with further questions.

**Comment by jurisbu** [comment]
OK, thanks for your input!

**Comment by SaturnIC** [comment]
> indirect dependencies are generally strongly discouraged as they are a common source of fragility/errors

Tbh this line of argumentation makes little sense to me since the whole pytest architecture is then 
nothing but indirect dependencies (fixtures, hooks, etc.)

I think jurisbu's own argument:
>The downside of this is that configuration is only available from request fixture as request.config.testconfig which works for tests and fixtures, but does not work for helper functions that are pytest unaware.

Is the only reason not to store static test configuration in pytests internal variables.
