### ISSUE TITLE
Segfault with unittest + custom __getattr__

### ISSUE THREAD

**Issue by dplepage** [pytest-dev/pytest#2470]
I get a segmentation fault if I run `pytest` on a file where A) I have imported `unittest`, and B) an object in the root namespace has a `__getattr__` that returns a tuple of length > 1 where the object itself is the first argument.

```sh
$ pip list --format=columns
Package    Version
---------- -------
pip        9.0.1
py         1.4.33
pytest     3.1.1
setuptools 36.0.1
```
I'm running Mac OS X 10.12.4.

Here's a minimal test case:
```python
import unittest

class Failure(object):
    def __getattr__(self, attr):
        return (self, None)

t = Failure()
```

Running `pytest fail.py` yields:
```sh
$ pytest fail.py
================================================ test session starts =================================================
platform darwin -- Python 3.5.2, pytest-3.1.1, py-1.4.33, pluggy-0.4.0
rootdir: /Users/dplepage/tmp/pytest_failure, inifile:
collecting 0 itemsSegmentation fault: 11
```

This may be the same issue as in #2330, which I see also uses both `unittest` and objects with custom `__getattr__`s.

**Comment by dplepage** [comment]
Of note: If I change the return value to just `(self, )`, then I get an infinite loop instead of a segfault.

**Comment by dplepage** [comment]
Hmm. Apparently this isn't a `pytest` bug, it's a bug in python's `issubclass`. The following also generates a segfault:
```python
class Failure(object):
    def __getattr__(self, attr):
        return (self, None)

issubclass(Failure(), int)
```

**Comment by nicoddemus** [comment]
Indeed I can reproduce this in Python 3.6. Perhaps you could report that in cpython?

**Comment by dplepage** [comment]
Yes, I've just reported it ([issue 30570](http://bugs.python.org/issue30570)). The problem seems to be that `issubclass` fails if `obj.__bases__` contains `obj`.

**Comment by nicoddemus** [comment]
Awesome, thanks! Can we close this then?

**Comment by dplepage** [comment]
Yes, please do.
