### ISSUE TITLE
task for vendoring pluggy

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2474]
Next time we vendor pluggy, we should create an `invoke` task to do that automatically; also, the same task should update all internal links in the docs to point to the new location, for example:

```rst
same arguments as ``before`` but also a :py:class:`_CallOutcome`` object
```

To:

```rst
same arguments as ``before`` but also a :py:class:`_CallOutcome <_pytest.vendored_packages.pluggy._CallOutcome>` object
```

**Comment by The-Compiler** [comment]
FWIW pip has https://github.com/pypa/pip/blob/master/tasks/vendoring/__init__.py - though they also do import rewriting and patching there.

**Comment by nicoddemus** [comment]
xref: #2473
