### ISSUE TITLE
max recursion depth in 3.1.2

### ISSUE THREAD

**Issue by bedwards** [pytest-dev/pytest#2485]
I noticed my build started failing with a simple change to my source and tracked it down to grabbing the latest pytest. I have `pytest>=3` changing it to `pytest==3.1.1` works around the problem. I am using django-pytest 3.1.2.

Attaching the traceback.

I will work on a minimal example. This is happening inside tox. It happens both on Mac OS X and on Bitbucket Pipelines (docker container running inside debian if I am not mistaken).

[traceback.txt](https://github.com/pytest-dev/pytest/files/1064590/traceback.txt)

**Comment by nicoddemus** [comment]
Hi @bedwards, I think this is related to #2140. Which version of `py` are you using?

cc @pelme

**Comment by bedwards** [comment]
This seems to be related to the specific version of py along with pytest 3.1.2

fails: 1.4.31 and 1.4.32

works: 1.4.33 and 1.4.34

**Comment by nicoddemus** [comment]
Weird that it is failing for you, [pytest requires py>=1.33](https://github.com/pytest-dev/pytest/blob/master/setup.py#L46) on `setup.py`.

**Comment by bedwards** [comment]
Yes. I think this is not a bug. Just incompatible versions. I had a bad requirements.txt file.

py==1.4.31
pytest>3

**Comment by nicoddemus** [comment]
Even so, that should give some conflict... hmm although pip is known to not have true dependency resolution, that might be it.

@bedwards should we close this?

**Comment by bedwards** [comment]
Yes, you can close it.

Regards,
Brian Edwards
(512) 584-6841
