### ISSUE TITLE
Namespaced plugins fail to get used on a Heroku environment.

### ISSUE THREAD

**Issue by cormac-yobota** [pytest-dev/pytest#2494]
Hi,

As stated above I am currently facing an issue where namespaced plugins defined using `pytest_plugins = ".."` fail to get used during a test run.

I have created a couple of repo's that replicate the issue:
[Package containing the fixtures](https://github.com/cormac-yobota/pytest-demo-parent)
[Package that uses the above's fixtures](https://github.com/cormac-yobota/pytest-demo-child)

**_To replicate a heroku env locally, you will need to follow a few steps:_**
**Clone the child repo.**
`git clone https://github.com/cormac-yobota/pytest-demo-child.git`
`cd pytest-demo-child/`

**Create a virtualenv called .heroku.**
`virtualenv .heroku`
`virtualenv --relocatable .heroku`

**Load the virtualenv.**
`source .heroku/bin/activate`
`pip install -e git+https://github.com/cormac-yobota/pytest-demo-parent.git@0.1.0#egg=pytest-demo-parent
`

**Run pytest.**
`pytest --fixtures/`
`pytest --fixtures-per-test tests/`

**Versions.**
`pip list`
`pip (9.0.1)
py (1.4.34)
pytest (3.1.1)
setuptools (36.0.1)
wheel (0.29.0)`

`pytest --version`
`This is pytest version 3.1.2, imported from /home/cormac/workspace/temp/interaction-referencedata/.heroku/lib/python3.5/site-packages/pytest.py`

`uname -a`
`Linux yobota 4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Let me know if there is anything else you need.
Thanks,
Cormac

**Comment by RonnyPfannschmidt** [comment]
`pytest_plugins` is only supported in `conftest.py`, not in a actual test module
to redeem, please move the line from the tests to `conftest.py`

if that works (as i expect) please close this issue

**Comment by cormac-yobota** [comment]
@RonnyPfannschmidt No Luck I have updated the pytest-demo-child repo as suggested if you want to give it a try.

**Comment by RonnyPfannschmidt** [comment]
i noticed that the plugin name you use cant be used/shared as they share the same folder name,

so both files are literally in the same logical place and it cant be helped easily

**Comment by cormac-yobota** [comment]
You're right I resolved this by creating a plugin directory in the tests namespace, and adding `pytest_plugins = "tests.plugin.{...}` in the conftest files.

Thanks for your quick response and help and apologies for the confusion.
Cormac

**Comment by nicoddemus** [comment]
> pytest_plugins is only supported in conftest.py, not in a actual test module

Are you sure @RonnyPfannschmidt? I have used `pytest_plugins` in test modules before and I'm sure they work.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus test modules are never used for plugin lookup, only for fixture lookup

**Comment by nicoddemus** [comment]
That doesn't seem to be true:

```python
pytest_plugins = ['foo']

def test_foo():
    pass
```

```
pytest .tmp\test_foo.py
============================= test session starts =============================
platform win32 -- Python 3.6.0, pytest-3.1.3.dev2+gf0541b6, py-1.4.33, pluggy-0.4.0
rootdir: C:\pytest, inifile: tox.ini
plugins: xdist-1.17.0, hypothesis-3.7.0
collected 0 items / 1 errors

=================================== ERRORS ====================================
______________________ ERROR collecting .tmp/test_foo.py ______________________
_pytest\config.py:437: in import_plugin
    __import__(importspec)
E   ModuleNotFoundError: No module named 'foo'

During handling of the above exception, another exception occurred:
_pytest\runner.py:157: in __init__
    self.result = func()
_pytest\runner.py:328: in <lambda>
    lambda: list(collector.collect()),
_pytest\python.py:401: in collect
    self.session._fixturemanager.parsefactories(self)
_pytest\fixtures.py:1048: in parsefactories
    holderobj = node_or_obj.obj
_pytest\python.py:204: in fget
    self._obj = obj = self._getobj()
_pytest\python.py:398: in _getobj
    return self._importtestmodule()
_pytest\python.py:445: in _importtestmodule
    self.config.pluginmanager.consider_module(mod)
_pytest\config.py:415: in consider_module
    self._import_plugin_specs(getattr(mod, 'pytest_plugins', []))
_pytest\config.py:420: in _import_plugin_specs
    self.import_plugin(import_spec)
_pytest\config.py:444: in import_plugin
    raise new_exc
E   ImportError: Error importing plugin "foo": No module named 'foo'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.24 seconds ===========================
```

`pytest_plugins` is always considered during import of test modules, see [this line](https://github.com/pytest-dev/pytest/blob/master/_pytest/python.py#L445).
