### ISSUE TITLE
Historical notes in the documentation

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2512]
On our docs it is common to have historical notes explaining how something was done in previous versions and is no longer recommended or has been deprecated. 

For example in [the fixture docs](https://docs.pytest.org/en/latest/fixture.html?highlight=addfinalizer#fixtures-as-function-arguments):

> In versions prior to 2.3 there was no ``@pytest.fixture`` marker
    and you had to use a magic ``pytest_funcarg__NAME`` prefix
    for the fixture factory.  This remains and will remain supported
    but is not anymore advertised as the primary means of declaring fixture
    functions.

While these blurbs are very useful for users looking for them in the docs after seeing them in old code, I think it is distracting for first time users.

How about:

1. Move all historical notes to the bottom of their files?
2. Move all historical notes to a separate file?

I like `2` best because it won't distract new readers at all and are still searchable by the users who are interested in them.

Opinions?

@hackebrot @pfctdayelise

**Comment by hackebrot** [comment]
Sorry for the delay @nicoddemus, I'm 👍 for option 2.
