### ISSUE TITLE
How to separate pytest output from standart output

### ISSUE THREAD

**Issue by sedefass** [pytest-dev/pytest#2513]
Here I have <b>tests.py</b> containing:

    import sys
    sys.stdout = open('log2.log', 'w')
    
    
    class TestH5Client:
        def test_something(self):
            print("Start")
            assert True
            print("End")
    
        def teardown_class(cls):
            print("OK")

I am running my test with the following shell command 

`pytest tests.py::TestH5Client::test_something >>log.log`

and I want that <b>log.log</b> to contain the information of the test run and <b>log2.log</b> to contain all the prints, but <b>log2.log</b> is empty

Content of <b>log.log</b> (the content is what I expect):

	============================= test session starts =============================
	platform win32 -- Python 3.6.0, pytest-3.1.0, py-1.4.33, pluggy-0.4.0
	rootdir: C:\Stefans\01.Learning_Python\27.pytest_std_ouput, inifile:
	collected 2 items

	tests.py .

	========================== 1 passed in 0.01 seconds ===========================

Content of <b>log2.log</b>: the file is empty

Expectation for <b>log2.log</b> content:

    Start
    End
    OK

So my question is is there a way to separate the both outputs so I can put the pytest output to one file and all test printings into another?

Thank you in advance.
Stefan

**Comment by nicoddemus** [comment]
If you found a solution @sedefass, would you mind posting it? This can help others in the future in the same situation if they happen to search the issue tracker. Thanks.

**Comment by sedefass** [comment]
Of course, I was going to do so, just had some urgent tasks.

So here are three possible solutions:

1. Instead of overriding `sys.stdout`, overriding the print function, for example `print = lambda x: open('log2.log', 'a').write(str(x)+"\n")`
2. Disable py.test's output capturing by adding the -s option to the execution command.
   Note: it is very important to have the following statement in the test script:

       import sys
       sys.stdout = open('log2.log', 'w')

3. Use a decent logger framework - this comes from an advice, haven't tried it so I can't recommend such a framework.

PS: Keep all the good work, pytest crew, your are great.

**Comment by nicoddemus** [comment]
> Of course, I was going to do so, just had some urgent tasks.

Sure, no worries. Thanks for following up.

> PS: Keep all the good work, pytest crew, your are great.

Thanks, we appreciate it! 😁
