### ISSUE TITLE
staticmethod functions are not collected for testing

### ISSUE THREAD

**Issue by waisbrot** [pytest-dev/pytest#2528]
When using classes to group functions, I'm interested in this pattern:

"test_http_requests.py"
```python
class TestGet:
  @staticmethod
  def test_simple_get():
    pass

  @staticmethod
  def test_query_string():
    pass

class TestPut:
  @staticmethod
  def test_no_data():
     pass

  @staticmethod
  def test_binary_data():
    pass
````

Using the `@staticmethod` decorator makes it clear that I'm not using the class for anything but grouping.

Unfortunately, pytest fails to collect any method so decorated. If I remove the decorator and add the `self` argument in the above example, pytest collects as expected.

Pytest 3.1.2, Python 2.7.13, no virtualenv, MacOS 10.12.5

**Comment by ceridwen** [comment]
I was attempting to use this, and it doesn't seem to be working quite right with fixtures.  Running the following code,

```python
import pytest

@pytest.fixture
def foo():
    return 'foo'

def test_foo(foo):
    assert foo == 'foo'

class TestFoo:
    @staticmethod
    def test_foo(foo):
        assert foo == 'foo'
```

Produces the following error:

```
pyfuncitem = <Function 'test_foo'>

    @hookimpl(trylast=True)
    def pytest_pyfunc_call(pyfuncitem):
        testfunction = pyfuncitem.obj
        if pyfuncitem._isyieldedfunction():
            testfunction(*pyfuncitem._args)
        else:
            funcargs = pyfuncitem.funcargs
            testargs = {}
            for arg in pyfuncitem._fixtureinfo.argnames:
                testargs[arg] = funcargs[arg]
>           testfunction(**testargs)
E           TypeError: test_foo() missing 1 required positional argument: 'foo'

../../Library/Python/3.6/lib/python/site-packages/_pytest/python.py:143: TypeError
======================= 1 failed, 1 passed in 0.32 seconds =======================
```

The first `test_foo()` function passes correctly.

**Comment by nicoddemus** [comment]
Thanks @ceridwen for the report. Moving this discussion to #2699 as this is a new issue.

Closing this as #2531 was merged some time ago.
