### ISSUE TITLE
re-use pytest assertion logic for complex objects

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest#2529]
Hello,

How can I reuse the python "smart" reporting for objects?

E.g.:

```python
class Foo(object):
    def __init__(self, text, sequence):
        self.text = text
        self.sequence = sequence
        
    def __eq__(self, other):
        return type(self) == type(other) and self.text == other.text and self.sequence == other.sequence
    
    def __ne__(self, other):
        return not self.__eq__(other)
```

What I want is to get the assertion report, just as I would assert the primitive fields, e.g. (of course makes sense to not print attributes that satisfy the comparison operator - and concatenate together the failing attribute reports). Something like:

```python
    def test_magic():
>       assert Foo(text='a', sequence=[1]) != Foo(text='a', sequence=[1, 2])
E       assert Foo(text='a', sequence=[1]) != Foo(text='a', sequence=[1, 2])
E           attribute `sequence`:
E              [1] == [1, 2]
E              Right contains more items, first extra item: 2
E        Use -v to get the full diff
````

Can I do this by writing some plugin, etc and calling in that the internal comparator? Or what is the recommended solution?

**Comment by nicoddemus** [comment]
You can use the [pytest_assertrepr_compare](https://docs.pytest.org/en/latest/writing_plugins.html#_pytest.hookspec.pytest_assertrepr_compare) hook in a `conftest.py` file or plugin.

I think this solves your issue so I'm closing this, feel free to follow up with other questions here.
