### ISSUE TITLE
TypeError on conftest.py during collection

### ISSUE THREAD

**Issue by crisAD** [pytest-dev/pytest#2532]
Hello,

I am new to pytest.
I was just trying to run the pytest sample from the PYTEST_C_RUNNER repository(https://github.com/jmcnamara/pytest_c_testrunner) and I encountered this error: 

_________________ ERROR collecting test/test_basic_integers.c _________________
conftest.py:38: in collect
    lines = test_output.split("\n")
E   TypeError: a bytes-like object is required, not 'str'
_______________________________________________________________________________

I did not do anything, I was just simply running pytest.
My pytest version is 3.1.2 and my python version is 3.5.2 running on anaconda version 2.5.0 (32-bit)

How do I fix this error?
Thanks.

**Comment by RonnyPfannschmidt** [comment]
i suspect adding a `b` to make it `b"\n"` should suffice, please report back and close if that was the case

**Comment by The-Compiler** [comment]
You'd probably need to ask @jmcnamara but it looks like that code was written for Python 2, not Python 3.

Also, note there's [pytest-cpp](https://github.com/pytest-dev/pytest-cpp) which should also work for testing C code.

Either way, I'm closing this as it's not a pytest issue :wink:

**Comment by crisAD** [comment]
thanks guys
