### ISSUE TITLE
Slow?

### ISSUE THREAD

**Issue by jonathan-s** [pytest-dev/pytest#2536]
I'm trying out py.test on a django project. Running `py.test` tells me it's using the following plugins: `sugar-0.8.0, django-3.1.2, celery-4.0.2, betamax-0.8.0`. I get the results in about 10s but if I were to run the tests using `python manage.py test` the tests would only take 1.6 seconds. 

More specifically it seems like the start up procedure, just before the tests are running that is slow. The actual tests themselves seems to be running at the same speed. 

So any ideas what's going on here?

Running osx, python 3.6, pytest==3.1.2

```
amqp (2.1.4)
appnope (0.1.0)
argon2-cffi (16.3.0)
awesome-slugify (1.6.5)
betamax (0.8.0)
billiard (3.5.0.2)
celery (4.0.2)
cffi (1.10.0)
coverage (4.4)
cssselect (1.0.1)
decorator (4.0.11)
demjson (2.2.4)
Django (1.11.1)
django-bulk-update (2.1.0)
django-coverage-plugin (1.5.0)
django-debug-toolbar (1.8)
django-environ (0.4.3)
django-extensions (1.7.9)
django-meta (1.3.2)
django-test-plus (1.0.17)
factory-boy (2.8.1)
Faker (0.7.17)
flake8 (3.3.0)
html2text (2016.9.19)
ipdb (0.10.3)
ipython (6.1.0)
ipython-genutils (0.2.0)
jedi (0.10.2)
kombu (4.0.2)
lxml (3.7.3)
mccabe (0.6.1)
olefile (0.44)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (4.1.1)
pip (9.0.1)
prompt-toolkit (1.0.14)
psycopg2 (2.7.1)
ptyprocess (0.5.2)
py (1.4.34)
pycodestyle (2.3.1)
pycparser (2.17)
pyflakes (1.5.0)
Pygments (2.2.0)
pytest (3.1.2)
pytest-django (3.1.2)
pytest-sugar (0.8.0)
python-dateutil (2.6.0)
pytz (2017.2)
regex (2017.6.23)
requests (2.14.2)
setuptools (28.8.0)
simplegeneric (0.8.1)
six (1.10.0)
sqlparse (0.2.3)
termcolor (1.1.0)
traitlets (4.3.2)
Unidecode (0.4.20)
vine (1.1.3)
wcwidth (0.1.7)
Werkzeug (0.12.1)
wheel (0.29.0)
```

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by nicoddemus** [comment]
Not sure, but I agree that discrepancy is weird at first glance. Did you try to uninstall some /all plugins just to see what times you get? You don't have to actually uninstall the, you can use `-p no:sugar` in the command line to disable sugar for example.

**Comment by jonathan-s** [comment]
I tried the no:sugar the result was about the same. The django one I can't
uninstall since it's needed for running the tests. I'll see about betamax,
but since that is caching responses it's pretty crucial too.

**Comment by RonnyPfannschmidt** [comment]
i strongly suspect a difference in pytest-django startup so i would suggest to report against pytest-django instead

**Comment by jonathan-s** [comment]
Cool, I'll do that :)

**Comment by RonnyPfannschmidt** [comment]
im closing this one then, if it falls back to pytest please open a new issue

thanks 👍
