### ISSUE TITLE
pytest_configure calling order

### ISSUE THREAD

**Issue by Ignalion** [pytest-dev/pytest#2539]
Hi guys. Have a little question about order of calling different pytest_configure from conftest.py and plugins files.
Is there a documented or some unspoken order of calling this hook when it's present in different conftest.py files and\or plugins?

**Comment by RonnyPfannschmidt** [comment]
for initial conftests and plugins the call order is random and affectable via tryfirst/trylast,

for other conftests it hapens right at loading time 

we should document this indeed

**Comment by RonnyPfannschmidt** [comment]
oh, and extra note - due to python3.6 dict ordering it ill happen in import order on python 3.6+ for now

**Comment by Ignalion** [comment]
Thus, as I understand, I can't rely on theirs order. Thanks!

**Comment by RonnyPfannschmidt** [comment]
Reopened as we should document this one in the own docs

**Comment by nicoddemus** [comment]
Perhaps @Ignalion would like to take a stab at contributing this? 😉
