### ISSUE TITLE
Report "pytestmark = skip" only once

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#2549]
When using `pytestmark = pytest.mark.skip("reason")` on a module you will get a `SKIP` report for every test in that module (in the `short test summary info`).

There happens some folding already, which could be extended: https://github.com/pytest-dev/pytest/blob/6908d93ba1c4a5282f58f65a1bd5bb93318764e8/_pytest/skipping.py#L351-L360

**Comment by bilderbuchi** [comment]
@nicoddemus @RonnyPfannschmidt as the PR is merged this can be closed I think.
