### ISSUE TITLE
Parametrized tests are grouped across files/modules

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#2550]
pytest reorders tests in order to separate parametrized setups (in [pytest_collection_modifyitems](https://github.com/pytest-dev/pytest/blob/6908d93ba1c4a5282f58f65a1bd5bb93318764e8/_pytest/fixtures.py#L1049)).

This gets done across file/module names though, which results in a confusing test order when using verbose mode (or something like pytest-sugar), where file names get displayed and the parametrization is used across files.

I think it would be better to only group them per module, or is there a reason not to do so?

Using pytest 3.1.2

**Comment by RonnyPfannschmidt** [comment]
the cross module reordering only happens for session scope fixtures - any other case is a bug

however the code is hairy and has a few bugs with fixture vs parameterize interactions

**Comment by blueyed** [comment]
> the cross module reordering only happens for session scope fixtures - any other case is a bug

Will check that, but might be the case here.

Why is the grouping done in the first place?
There is no benefit from it by being able to teardown earlier (for session scoped fixtures), which I could imagine to be useful for "heavy fixtures" like services that should get handled in a block.

I'm now overriding this in our plugin's `pytest_colletion_modifyitems`, and it seems to be OK:

```py
items[:] = sorted(items, key=lambda item: item.module.__name__)
```

**Comment by RonnyPfannschmidt** [comment]
@blueyed the grouping is done so fixtures dont have to be torn down between tests
you can override them with a sort key just fine tho

**Comment by nicoddemus** [comment]
> grouping is done so fixtures dont have to be torn down between tests

Just to exemplify, a session-scoped fixture `fix` parametrized with `[1, 2, 3]` and used by tests `test_foo` and `test_bar` would normally be executed in this order:

```
test_foo(fix[1])
test_foo(fix[2])
test_foo(fix[3])
test_bar(fix[1])
test_bar(fix[2])
test_bar(fix[3])
```

So each `fix` instantiation would be created and destroyed twice. By reordering, pytest will execute instead:

```
test_foo(fix[1])
test_bar(fix[1])
test_foo(fix[2])
test_bar(fix[2])
test_foo(fix[3])
test_bar(fix[3])
```

So each `fix` instantiation only happens once.

Just realized that one thing that might not be clear is that only one `fix` instantiation exists at the same type, so `fix[1]` and `fix[2]` cannot coexist currently.

**Comment by blueyed** [comment]
It is triggered in our tests via this:

```py
def pytest_generate_tests(metafunc):
    # Only parametrize "image" fixture when explicitly requested.
    if 'image_ext' in metafunc.fixturenames:
        exts = ['png']
        if metafunc.config.option.parametrize_image:
            exts += ['jpg']
        metafunc.parametrize('image_ext', exts, scope='session')
```

I've removed the `scope='session'` there now, which fixes it for me.

We are using different fixtures with `image_ext`, both in `function` and `session` scope.
`image_ext` itself is not a real fixture.

**Comment by RonnyPfannschmidt** [comment]
There are fundamental bugs in fixture based ordering there

**Comment by blueyed** [comment]
..to clarify: I also had to change the scope for our `b64_image(image_ext)` fixture `'function'`, otherwise it  would cause a `ScopeMismatch` (which is expected probably at least).

**Comment by blueyed** [comment]
@RonnyPfannschmidt 
> the grouping is done so fixtures dont have to be torn down between tests

Is this because parametrized fixtures have to be torn down / recreated per param?!
In general, they should/could be kept just like normal fixtures until the end of the session (or rather until the last test used them)?!

**Comment by nicoddemus** [comment]
> Is this because parametrized fixtures have to be torn down / recreated per param?!

No, it is because of this bit I mentioned: "... so fix[1] and fix[2] cannot coexist currently."

That's because there can only be one `fix` active at any moment; in order to instantiate `fix[2]`, `fix[1]` must be torn down, hence the need to reorder the tests to avoid that.

I wonder if it is possible to change the design so each parametrization is a separate fixture entirely and can co-exist. But on second thought, I'm not sure if that is not also by design, to avoid instantiating multiple session fixtures simultaneously in order to avoid spawning multiple services (for example).

> There are fundamental bugs in fixture based ordering there

So far I'm not sure it is a bug... if some of the fixtures involved in the paramerametrization are session-scoped, re-ordering will kick in.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus we do have various bugs around fixture ordering when it comes to direct vs indirect vs parameterize

we have been it by one of those at my work

**Comment by nicoddemus** [comment]
> we do have various bugs around fixture ordering when it comes to direct vs indirect vs parameterize

Oh I know we have bugs related to parametrize, I was asking regarding the problem mentioned by @blueyed in specific was a bug (it doesn't seem to me so far).

**Comment by blueyed** [comment]
I agree, closing this for now.
Thanks!
