### ISSUE TITLE
calling pytest or python -m pytest should have identical behaviour

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#2564]
It seems that at this moment running `pytest` does not have the same behaviour as running `python -m pytest` and that's related to Python system path but in a very weird way.

This is causing confusions and frustration among users that may call python in various ways, with or without a virtualenv (provided manually, or via tox).

I know that the documentation mentions this aspect but this does almost nothing to the real-work experience which can be described like **some tests are failing when calling in one way**. What is even worse is that these failures are not simple ones like import failures, they seem to be quite deep and with very weird and hard to understand. 

I encountered plenty of such examples over time, the last one was https://github.com/softwarefactory-project/rdopkg/blob/master/run_tests.sh

I that case I encountered this:
* no-venv: `PYTHONPATH=. pytest` - works
* no-venv: `pytest` - fails some tests
* no-venv: `PYTHONPATH=. python -m pytest`  - fails some tests
* venv: `PYTHONPATH=. pytest` - works
* venv: `pytest` - fails totally due to failure to find package (not installed)
* venv: `python -m pytest` - fails some tests
* venv: `PYTHONPATH=. python -m pytest` - fails some tests

I am looking for a solution where a user would be able to call pytest in either mode, without having to add extra parameters or environment variables and to get the same behaviour in the end.

**Comment by nicoddemus** [comment]
Hi @ssbarnea,

I agree it is really bad from a user's perspective, but I also don't know a solution to this problem other than recommending people to install pytest and their code into a virtual environment.

Please do post here if you find an approach to solve this. 👍

**Comment by ssbarnea** [comment]
@nicoddemus be sure that I will post it here once I find the bug and a solution. It may take few days as this is not on the top of the pile.

Please note that not all use cases are involving virtual environments and with docker introduction more and more usage patterns are not using them anymore, in many cases the build jobs are also running as root.

This may sound a really bad practice but if for micro-services it may not be bad anymore, as the isolation happens at container level.

**Comment by nicoddemus** [comment]
> Please note that not all use cases are involving virtual environments and with docker introduction more and more usage patterns are not using them anymore, in many cases the build jobs are also running as root.
  This may sound a really bad practice but if for micro-services it may not be bad anymore, as the isolation happens at container level.

Definitely, that's an excellent point, thanks. I'm curious though: is `pytest` installed into the system Python in that case? And how about the user's application/project? I suppose the former is true but the latter is not. Just trying to get a clear picture of that use case.

**Comment by nicoddemus** [comment]
Closing as this has not seen activity in awhile.

**Comment by intchanter** [comment]
One possible solution to this divergence would be to replace the current pytest script, (already distinct from the pytest module) with a system script that would simply call `python -m pytest $@` or its equivalent on non-Unix-y systems.

From my experience with this so far, it does appear that `python -m pytest` gives the expected behavior, though I can't speak to it being so in every case.

**Comment by intchanter** [comment]
In answer to @nicoddemus on 2017-07-12, yes, the most common use case I've seen with Docker has the various Python packages, including pytest, installed at the system level within the container.

**Comment by nicoddemus** [comment]
> One possible solution to this divergence would be to replace the current pytest script, (already distinct from the pytest module) with a system script that would simply call `python -m pytest $@` or its equivalent on non-Unix-y systems.

That would make pytest work differently from every other setuptools-based script... I don't think that's a good idea. We might want to add a note to the docs for this special case then, along with how to use virtual environments.
