### ISSUE TITLE
Test report text issue

### ISSUE THREAD

**Issue by hackebrot** [pytest-dev/pytest#2579]
Hi! 👋 

I'm working off the features branch right now and noticed that the test output reads:

```text
collected 1 item s

tests/test_helloworld.py .
```

Looks like we have tiny issue with ``item s`` 😁

/cc @flub

**Comment by nicoddemus** [comment]
Should have been fixed by #2571... are you still seeing this even after it?

**Comment by hackebrot** [comment]
I just cherry-picked the commit from the bugfix PR. Looks like it's still showing the extra space, but only if a single test is collected

```python
def test_helloworld():
    assert "Hello"
```

```text
$ pytest test_unwanted_space.py

collected 1 item s

test_unwanted_space.py .
```

**Comment by hackebrot** [comment]
I'm writing a test for it. 👍

**Comment by hackebrot** [comment]
Can't get my unittest for the bug to fail. Most probably because ``pytester`` works differently than if you run ``pytest`` from the CLI 😢

**Comment by RonnyPfannschmidt** [comment]
i suspect it will be hard to test unless we run pytest against a pty and a terminal emulator

**Comment by asottile** [comment]
Here's a screenshot from my dupe bug report:

![](https://i.fluffy.cc/0RXVwd30CcClMMtXMSz6rh4BZpNs1hTz.png)

**Comment by asottile** [comment]
From some testing, the "rewrite" needs to overwrite the entire previous line:

```
$ echo -e 'hello\rhi'
hillo
$ echo -e 'hello     \rhi'
hillo     
$ echo -e 'hello\r     \rhi'
hi   
$ echo -e 'hello     \rhi'
hillo     
$ echo -e 'hello\r     \rhi'
hi   
$ echo -e 'hello\r\rhi'
hillo
```

[this SO post](https://stackoverflow.com/questions/11283625/bash-overwrite-last-terminal-line) implies there's a better solution but I'm unsure how portable it is...

**Comment by RonnyPfannschmidt** [comment]
vt100 has escape codes to do stuff like clearing lines, i believe colorama ports those to windows

**Comment by RonnyPfannschmidt** [comment]
but this has to be fixed in pylib

i should note that terminalwriter is fairly aged, i wish we could remove it, but people depend on it too much :/

**Comment by hackebrot** [comment]
Thank you for looking into this @nicoddemus @RonnyPfannschmidt! 🙇
