### ISSUE TITLE
doc: filterwarnings is only documented in README

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#2603]
It was added in https://github.com/pytest-dev/pytest/commit/bc94a51a965ef20e9a66fc678718ce20746a1a0b (via https://github.com/pytest-dev/pytest/pull/2072), but has only documentation in the README.

**Comment by blueyed** [comment]
Sorry, missed it.

**Comment by blueyed** [comment]
I wanted to report `pythonwarnings` being not documented instead - not even in the README.

Is that OK?

**Comment by The-Compiler** [comment]
FWIW, `warnings.rst` talks about `-W`, which is the short version of `--pythonwarnings`.
