### ISSUE TITLE
document mark.with_args

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2604]
followup to #2600  #2540 

there should be a few examples of `mark.with_args`

**Comment by xuanluong** [comment]
@RonnyPfannschmidt Can I work in this issue in case you haven't worked on it yet? I'll probably add a subsection before [this](https://github.com/pytest-dev/pytest/blob/master/doc/en/example/markers.rst#reading-markers-which-were-set-from-multiple-places) in `examples/markers.rst` that will contain 2 examples demonstrating that:
- `pytest.mark.NAME.with_args` is the same as `pytest.mark.NAME.__call__` in most cases
- `pytest.mark.NAME.with_args` allow having a callable as single positional argument while `pytest.mark.NAME.__call__` doesn't.

**Comment by RonnyPfannschmidt** [comment]
@xuanluong please do - but put emphasis on that with_args is for extending the parameter set while call tries to decorate first if it can
