### ISSUE TITLE
request: add commandline option not to import from current directory

### ISSUE THREAD

**Issue by xoviat** [pytest-dev/pytest#2605]
Adding a commandline option not to import from the current directory would allow cleaner workflow for scipy. All that needs to be done is this if the commandline is passed.

```
import sys
sys.path.remove('')
```

**Comment by nicoddemus** [comment]
Pytest by default doesn't add the current directory... are you running `python -m pytest`? If so take a look at [this docs](https://docs.pytest.org/en/latest/usage.html#calling-pytest-through-python-m-pytest):

> except that python will also add the current directory to sys.path.

**Comment by xoviat** [comment]
Hrm... something else may be going on here. I will look into this further later today.

**Comment by nicoddemus** [comment]
OK, sounds good

**Comment by xoviat** [comment]
This is not caused by pytest.

**Comment by xoviat** [comment]
Update: this issue occurs with pytest-xdist. Should I file there?

**Comment by RonnyPfannschmidt** [comment]
yes please
