### ISSUE TITLE
--last-failed is ignored when using xdist and rootdir

### ISSUE THREAD

**Issue by poletti-marco** [pytest-dev/pytest#2609]
When using xdist and rootdir, `--last-failed` has no effect (apart from the message saying "run-last-failure: rerun last N failures").

Steps to reproduce:

```bash
mkdir foo bar

cat <<EOF >foo/pytest.ini
[pytest]
testpaths = $PWD/bar
EOF

cat <<EOF >bar/test_truth.py
def test_truth():
  assert 4 == 4
def test_alternative_truth():
  assert 4 == 5
EOF

(cd bar; py.test-3 -n 1)
# This (correctly) runs only test_alternative_truth
(cd bar; py.test-3 -n 1 --lf)
# This contains {"test_truth.py::test_alternative_truth":true}
cat bar/.cache/v/cache/lastfailed

rm -rf foo/.cache bar/.cache
(cd foo; py.test-3)
# This (correctly) runs only test_alternative_truth
(cd foo; py.test-3 --lf)
#  This contains {"::test_alternative_truth":true}
cat foo/.cache/v/cache/lastfailed

rm -rf foo/.cache bar/.cache
(cd foo; py.test-3 -n 1)
# This (incorrectly) runs both tests
(cd foo; py.test-3 -n 1 --lf)
# This contains {"bar/test_truth.py::test_alternative_truth": true}
cat foo/.cache/v/cache/lastfailed
```

This is the output of the last command:

```bash
============================== test session starts ==============================
platform linux -- Python 3.5.3, pytest-3.0.6, py-1.4.33, pluggy-0.4.0
run-last-failure: rerun last 1 failures
rootdir: /tmp/playground/foo, inifile: pytest.ini
plugins: xdist-1.15.0
gw0 [2]
scheduling tests via LoadScheduling
.F
=================================== FAILURES ====================================
____________________________ test_alternative_truth _____________________________
[gw0] linux -- Python 3.5.3 /usr/bin/python3
def test_alternative_truth():
>     assert 4 == 5
E     assert 4 == 5

../bar/test_truth.py:4: AssertionError
====================== 1 failed, 1 passed in 0.37 seconds =======================
```

So py.test correctly says that there was only 1 failure and only that should be re-run, but then it runs both tests anyway.

I tried manually changing the content of the `lastfailed` file in the 3rd case to match the content in the 1st and 2nd case to see if that makes the last command work, but it doesn't.

If it wasn't already clear, the expected behavior is that the last command only runs `test_alternative_truth`.

**Comment by carver** [comment]
It may be that xdist doesn't play nice with pytest's last-failed data. I have a manual setup that has the same problem.

My setup is:
* python2 installed in a virtualenv in `$PROJECT_DIR/venv-py2`
* python3 installed in a virtualenv in `$PROJECT_DIR/venv-py3`
* Two open consoles, running pytest on loop (using pytest-watch). With `--failed-first --max-fail=1`

So slightly different setups, but I suspect the same problem. I believe what's happening is that the saved last failure from one run is overwriting the last failures from the other run.

If py2 fails and py3 succeeds, then most likely the py3 run finishes second and overwrites the py2 failed test log. So when the py2 test re-runs, it thinks there were no failures previously.

A workaround would be to change where pytest saves the cache for each runner, but I haven't found out how to specify it. It defaults to `$PROJECT_DIR/.cache/v/cache`. I'd rather have it save the cache in each virtual environment

**Comment by poletti-marco** [comment]
Not sure if your case is affected by this issue too, but that seems a different scenario. In the example I mentioned in my comment I was having issues even when running just one instance of py.test and using `-n 1` (so there there's no issue with one run overwriting another).

**Comment by carver** [comment]
Ah, yes, re-reading it I see that it's probably unrelated. Sorry for the noise.

In your last example, I was curious to make sure the correct cache was being detected, so I tried:
`(cd foo; py.test-3 --cache-show -n 1 --lf)`

```
================== test session starts ===================
platform linux -- Python 3.5.3, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /tmp/playtest/foo, inifile: pytest.ini
plugins: xdist-1.20.0, forked-0.2
gw0 Ccachedir: /tmp/playtest/foo/.cache
---------------------- cache values ----------------------
cache/lastfailed contains:
  {'bar/test_truth.py::test_alternative_truth': True}

============== no tests ran in 0.20 seconds ==============

```

Everything looks in order, but I see the same behavior as you.

**Comment by nicoddemus** [comment]
Closing as this has not seen activity in awhile.

**Comment by marianobianchi** [comment]
As a comment, I had the same issue and was able to solve it by making sure --last-failed comes before the xdist parameters. So, instead of calling: `pytest -n 4 --last-failed` I ran `pytest --last-failed -n 4` and it worked
