### ISSUE TITLE
get an own ci state for linting so linting doesnt shadow into normal tests

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2612]
linting issues give us false negatives for the normal ci tests
lets have a own github status for linting issues

**Comment by nicoddemus** [comment]
Can you clarify this a bit @RonnyPfannschmidt ? You mean to have a separate CI service to separate linting from tests?

That's possible, but what would that accomplish? I mean, if a PR passes Travis and AppVeyor but fails this separate linting service we still wouldn't merge it, so it wouldn't really change much.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt still want to pursue this? It is not clear (at least to me) exactly how this should work.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus currently travis is too limited to do this nice - e can either configure something like sideci/coala, or let it slip -- im leaning torwards letting it slip by now
