### ISSUE TITLE
New report hook to display messages after collection is finished

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2622]
Introduce a new hook called by the terminal plugin after collection has been completed and before starting to run tests.

This allows plugins that modify the collection to more accurately report what will actually be executed, for example the `--lf` option from the cache plugin (see [comment](https://github.com/pytest-dev/pytest/pull/2621/files#r129834462) on #2621).

**Comment by RonnyPfannschmidt** [comment]
closing as fixed by #2623
