### ISSUE TITLE
Introduce six to the codebase to deal with Python 2/Python 3 differences

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2642]
It would be nice to remove a good portion of our Python 2/Python 3 own compatibility layer. Ultimately we must see if the change is worthwhile (my initial feeling is that it is, but that is to be seen yet).

**Comment by RonnyPfannschmidt** [comment]
this also would remove a lot of the messy pylib dependencies

**Comment by nicoddemus** [comment]
Realized that we should discuss if `six` should be vendored or not, given that `six` also tests itself using `pytest`, similar to the discussion taking place in #2641. I guess the exact same arguments to vendor `attrs` or not apply to `six`.

**Comment by nicoddemus** [comment]
Fixed by #2650
