### ISSUE TITLE
Repository of sample tests

### ISSUE THREAD

**Issue by Lothiraldan** [pytest-dev/pytest#2643]
Hi,

I'm working on a pytest plugin that output JSON line per test: https://github.com/Lothiraldan/pytest-json

 I was wondering if there is repository with examples of tests in all possible combinations, something like:

- Passing function/class tests
- Failing function/class tests
- Test cases that randomly fails
- Tests with fixtures
- Tests with xfail

I think it might helps plugins author check that their plugins covers all possible cases and might be used by people to see how plugins output looks in all the cases.

If it doesn't exists, I plan to create one, would you prefer I create the repository under my name or under the pytest-dev organisation?

**Comment by RonnyPfannschmidt** [comment]
@Lothiraldan we are thinking about such details and started as part of #2207 

an extra repository may make sense as well - i think a discussion on the ml is needed to pick a good place for this

it may be a good idea to take pytester and move it out of pytest and have it ship a repository of different testsuites that then plugin authors can invoke on their plugins

but this is challenging topic for infrastructure, so a consensus and rough plan with buy-in is needed ^^

**Comment by Lothiraldan** [comment]
Thx @RonnyPfannschmidt, I will answer on #2207
