### ISSUE TITLE
Terminal writing with a single test produces "collected 1 item s"

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#2654]
![](https://i.fluffy.cc/0RXVwd30CcClMMtXMSz6rh4BZpNs1hTz.png)

I'm using `Terminal` in ubuntu 16.04

The pytest versions are listed in the screenshot.  My repository contains a single test.

I did some debugging work and it *does* seem it is placing the `\r` characters properly (to clear the line) but it doesn't seem to be clearing the entire contents (leaving artifacts from the previous writes).

**Comment by asottile** [comment]
It seems that the `final` print needs to have space padding to cover the previous writes?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i recall that we got a fix in for that recently, did it by chance happen on master in the release window

**Comment by asottile** [comment]
I also tried on master (where I was poking with the code)

**Comment by RonnyPfannschmidt** [comment]
#2571 was supposed to fix this, i suppose thats solution is incorrect after all

**Comment by RonnyPfannschmidt** [comment]
i see now -  #2579 records that the issue wasnt solved

**Comment by asottile** [comment]
Ah cool, #2579 looks like an exact dupe, I'll follow that issue instead!
