### ISSUE TITLE
pexpect using tests regulary hang/die

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2673]
we pretty much have broken tests there,
whenever i have pexpect installed, py.test hangs testing terminal or pdb

**Comment by RonnyPfannschmidt** [comment]
i keep hitting this one, i'm tempted to just remove pexpect since its all broken atm

**Comment by nicoddemus** [comment]
That doesn't happen on CI though does it?

**Comment by RonnyPfannschmidt** [comment]
yes, which makes it even more of a pain, since ithappens in tox/local usage and its typically due to badly set timeouts/interactions in each test

**Comment by nicoddemus** [comment]
In this case I would think twice about removing it, specially if we can't pin point the actual cause *and* it currently passes on CI.

**Comment by RonnyPfannschmidt** [comment]
what value does a test have, where we dont know why it works when it works

**Comment by nicoddemus** [comment]
I thought the `pexpect` tests ensured that user interaction work as expected in situations like `--pdb`. I never took a deeper look at them though.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus all i know that they regularly fall apart for me - and its starting to be really irritating

**Comment by srinivasreddy** [comment]
I can confirm this on my local. 
![image](https://user-images.githubusercontent.com/198396/34118829-067fe530-e446-11e7-9e5c-181df6a6e5bb.png)

**Comment by stanislavlevin** [comment]
ping

**Comment by RonnyPfannschmidt** [comment]
it wont pong, its hanging

**Comment by blueyed** [comment]
Is this still happening for you?

I've noticed "hacks" / code for Mac OS, but are you all using MacOS for when it happens/hangs?
(never seen it myself on Linux)

**Comment by blueyed** [comment]
So if you're seeing this, please use `-vv` to see the test that hangs.. see https://github.com/pytest-dev/pytest/pull/3116 for a possible fix in this regard.

**Comment by nicoddemus** [comment]
Closing as no more information has been provided. We can reopen once the suggestion by @blueyed has been tried. 👍

**Comment by blueyed** [comment]
Turns out you have to `read()` with pending output before `wait()` - likely related to different behavior with regard to output buffering then maybe, but https://github.com/pytest-dev/pytest/pull/5313 should fix it.
