### ISSUE TITLE
Document default values for 'python_classes', 'python_functions' and 'python_files'

### ISSUE THREAD

**Issue by edmorley** [pytest-dev/pytest#2676]
Hi!

The default values for these config parameters aren't listed here:
https://docs.pytest.org/en/latest/customize.html#confval-python_classes
https://docs.pytest.org/en/latest/customize.html#confval-python_functions
https://docs.pytest.org/en/latest/customize.html#confval-python_files

...nor in the "changing naming conventions" page that the above link to:
https://docs.pytest.org/en/latest/example/pythoncollection.html#change-naming-conventions

After a while I managed to stumble across something that implies the defaults:
https://docs.pytest.org/en/latest/goodpractices.html#test-discovery

...however it would be good to document along with the config options too.

The defaults are defined in the source here:
https://github.com/pytest-dev/pytest/blob/3.2.1/_pytest/python.py#L76-L83

I'll try and open a PR at some point in the future, but may not be for a bit. If anyone wants to take this in the meantime, please do!

Many thanks :-)

**Comment by RonnyPfannschmidt** [comment]
@edmorley thanks for brining this detail to attention, i believe the labels will help a reasonable resolution

**Comment by jespino** [comment]
I have created a PR with this changes, I hope you like it :) #2678
