### ISSUE TITLE
getfuncargvalue deprecation warning does set the proper stacklevel

### ISSUE THREAD

**Issue by pelme** [pytest-dev/pytest#2681]
Calling `request.getfuncargvalue()` gives this rather unhelpful message which makes it hard to figure out where the call happens:

```
...

=== warnings summary ===
system/test_asdf.py::test_fghj
  /bla/bla/bla/_pytest/fixtures.py:431: DeprecationWarning: use of getfuncargvalue is deprecated, use getfixturevalue
    DeprecationWarning)
```

**Comment by RonnyPfannschmidt** [comment]
@pelme i wonder if we have other warnings with that mistake as well

**Comment by pelme** [comment]
I did not look into it at this point. I have just been annoyed by this single instance for a while but not gotten around to fixing it.

Btw, I think stacklevel=2 would be a saner default in Python but anyways...
