### ISSUE TITLE
Use tox release candidates in pytest CI

### ISSUE THREAD

**Issue by obestwalter** [pytest-dev/pytest#2683]
With [tox 2.8](https://github.com/tox-dev/tox/issues/538) we start using release candidates and it would be nice if you could start using them in pytest CI tests.

All that needs to be done is to add the `--pre` flag to the install command in the CI configs. I can open a PR if there are no objections.

**Comment by RonnyPfannschmidt** [comment]
main question is what will that cost pytest - while i trust in the stability of tox - i don't see the direct need to make pytest a "testbed"

on the other hand its a quite nice fallout connection

**Comment by obestwalter** [comment]
As we have some developer overlap I thought it might not hurt to propose to use tox release candidates here. The cost is that maybe sometimes CI builds fail due to a new bug in a tox rc, which is hopefully easy to recognize then.

**Comment by RonnyPfannschmidt** [comment]
yup - i think i'm +0 on this one, ^^

**Comment by nicoddemus** [comment]
I'm 👍!

**Comment by obestwalter** [comment]
He thanks :)
