### ISSUE TITLE
Consider using Build Stages in Travis CI

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2688]
`pytest-html` recently switched over to using Build Stages in pytest-dev/pytest-html#127. Consider if this would be worthwhile for us.

**Comment by RonnyPfannschmidt** [comment]
im +1

**Comment by nicoddemus** [comment]
Took a deeper look while working on pytest-dev/pytest-xdist#223 and I think this is worthwhile only if we have other stages than "test", which is not the case for pytest currently.

I see some possibilities for the future:

* "Deploy" stage to deploy "latest" builds from `master` directly to `devpi`; 
* Automatically push PRs with regendocs updates from `master` and `features`.

**Comment by nicoddemus** [comment]
We have been using stages for some time now. 👍
