### ISSUE TITLE
document setup/teardown mismatch in the unittest integration

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2692]
follow-up to #2677

due to fundamental incompatibility we have to run certain details of unittest in the call phase instead of setup/teardown

this is surprising to users but necessary, unfortunately it is not documented

**Comment by OwenTuz** [comment]
First pass for this in https://github.com/pytest-dev/pytest/pull/2859

I've just appended a note with a quick description: it could be moved to be nearer to (or linked from?) the mention of setup/teardown under 'unittest features' if you think it's worthwhile. Please let me know if you'd like any changes made.

**Comment by nicoddemus** [comment]
Fixed by #2859
