### ISSUE TITLE
UnicodeDecodeError instead of AssertionError while comparing UTF-8 encoded strings

### ISSUE THREAD

**Issue by vishalvpoojary** [pytest-dev/pytest#2694]
While asserting equality of two unequal (different) UTF-8 encoded string pytest gives UnicodeDecodeError instead of Assertion Error. The test file and the output of pytest is attached. 
OS: linux mint, pytest_version: 2.5.1
[error.txt](https://github.com/pytest-dev/pytest/files/1227858/error.txt)

[test_file.txt](https://github.com/pytest-dev/pytest/files/1227860/test_file.txt)

**Comment by The-Compiler** [comment]
That's an ancient pytest - can you try with something newer?

**Comment by vishalvpoojary** [comment]
Sorry about that. Its fixed in newer version.
