### ISSUE TITLE
warning filters incorrectly apply for conftests and collection in pytester

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2701]
#2696 uncovered that pytest invocations with selected warning filters dont pass trough to the nested pytest correctly, in turn making tests even with the filter fail at importing a conftest and running a collection

CC @nicoddemus

**Comment by nicoddemus** [comment]
@jbasko thanks for the ping on this. This will be fixed by #4164. 👍
