### ISSUE TITLE
PY3 only: assumes that argument (from decorator) is a fixture

### ISSUE THREAD

**Issue by yarikoptic** [pytest-dev/pytest#2702]
- [x] Include a detailed description of the bug or suggestion

incorrectly (well... I think ;) ) assumes that argument is a fixture and then fails.

- [x] `pip list` of the virtual environment you are using
http://www.onerussian.com/tmp/pip-env-20170818.txt

- [x] pytest and operating system versions

Debian... python  3.5.3. pytest 3.2.1

- [x] Minimal example if possible

In our code base some tests are still nose-styled, but in this file everything seems to be more or less kosher.  Besides that we are using our helper decorator `@with_tempfile` which provides filename into the function as an argument, e.g.
(more at https://github.com/ReproNim/niceman/pull/97/files#diff-150b2bcb7c628e3fe5a356fc36555f55R50)

```python
@with_tempfile(content="""
echo "Enabling special environment"
echo "We could even spit out an stderr output">&2
export EXPORTED_VAR="
multiline
"
export PATH=/custom:$PATH
NON_EXPORTED_VAR=2         # but may be those should be handled??
""")
def test_source_file(script):
    ses = ShellSession()
    assert ses.get_envvars() == {}
```

works just fine while running using python2 (the same pytest version) but with python3 error:

```shell
$> python -m pytest -s -v  niceman/resource/tests/test_shell.py::test_source_file   
============================================= test session starts ==============================================
platform linux -- Python 3.5.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /home/yoh/proj/repronim/niceman/venvs/python3/bin/python
cachedir: .cache
rootdir: /home/yoh/proj/repronim/niceman, inifile:
plugins: localserver-0.3.6
/home/yoh/proj/repronim/niceman/niceman/dochelpers.py:160: FutureWarning: split() requires a non-empty pattern match.
  entries = __re_spliter1.split(paramdoc)
collected 1 item                                                                                                

niceman/resource/tests/test_shell.py::test_source_file ERROR

==================================================== ERRORS ====================================================
______________________________________ ERROR at setup of test_source_file ______________________________________
file /home/yoh/proj/repronim/niceman/niceman/resource/tests/test_shell.py, line 51
  @with_tempfile(content="""
  echo "Enabling special environment"
  echo "We could even spit out an stderr output">&2
  export EXPORTED_VAR="
  multiline
  "
  export PATH=/custom:$PATH
  NON_EXPORTED_VAR=2         # but may be those should be handled??
  """)
  def test_source_file(script):
E       fixture 'script' not found
>       available fixtures: cache, capfd, capsys, demo1_spec, doctest_namespace, httpserver, httpsserver, monkeypatch, niceman_cfg_path, pytestconfig, record_xml_property, recwarn, reprozip_spec2, smtpserver, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/home/yoh/proj/repronim/niceman/niceman/resource/tests/test_shell.py:51
```
I guess in python3  `functools.wraps` may be preserves function signature (better than in pythonr2) which obscures it for pytest?

strange thing is that we do use it in other tests without this side-effect.  How could I may be instruct pytest that this is not a fixture???

**Comment by yarikoptic** [comment]
any cues?

**Comment by nicoddemus** [comment]
@yarikoptic thanks for the ping.

No clue unfortunately, Pytest supports Python 2 and 3 so this should work. Can you provide a minimal reproducible example? Or point to the code in question if it is public so we can try to reproduce it ourselves?

**Comment by RonnyPfannschmidt** [comment]
this looks like we have a case of a bad decorator there, python3 has better metadata, so on python2 pytest just cant follow up and it works by accident, on python3 however we get a correct error

**Comment by RonnyPfannschmidt** [comment]
i followed up, and its using a plain functools.wraps, its not surprising that pytest is confused there

https://github.com/python/cpython/blob/2.7/Lib/functools.py#L35 vs https://github.com/python/cpython/blob/3.5/Lib/functools.py#L69

more recent python has a bugfix which lets pytest find the function of origin

the python3 behaviour is correct (aka fail)

**Comment by yarikoptic** [comment]
Thank you @nicoddemus and @RonnyPfannschmidt for looking into it!  

> more recent python has a bugfix which lets pytest find the function of origin

do you mean that the behavior you pointed out to was changed since then (seems to be not the case -- reproduced with 3.6.2 and I see no changes in cpython source for ./Lib/functools.py since then) or that in recent versions of python now it is expected behavior to be unable to use functool.wraps'ed decorators with the pytests (which would be ... suboptimal)? ;)

My main confusion also comes also from the fact that given decorator does not cause such an "effect" in other test files... I am yet to figure out why not...

**Comment by yarikoptic** [comment]
d'oh -- I remembered now that we hit this issue before and worked out a workaround -- convert those args into kwargs, then pytest doesn't try to assume that they are fixtures, i.e.

```python
@with_tempfile
def test_blah(filename):
  ..
```
into

```python
@with_tempfile
def test_blah(filename=None):
  ..
```
may be not elegant but keeps us going. Cheers.  Feel free to close unless you would like to make other decorator-junkies happier ;)

**Comment by yarikoptic** [comment]
actually -- I will just close it since I don't think there is anything you could at pytest side for my abuse of decorators and somewhat "incompatible" use of @wraps (ideally should be able to filter out the signature of the function, but it needs to be me to do it)

**Comment by nicoddemus** [comment]
Thanks for the follow up!
