### ISSUE TITLE
Sanitize paths in failure reports

### ISSUE THREAD

**Issue by wjakob** [pytest-dev/pytest#2705]
Pytest (3.0.7) currently reports unnecessarily long paths containing redundant portions and ``..`` elements, as in ``path-to-tests/../path-to-tests`` when it picks up files in a deeply nested project. Below is an example, which was executed in the ``mitsuba2`` directory -- I find the path format quite distracting.

```
====================================== test session starts =======================================
platform darwin -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /Users/wjakob/anaconda/bin/python
cachedir: .cache
rootdir: /Users/wjakob/Dropbox/projects/mitsuba2, inifile: pytest.ini
plugins: xdist-1.17.1
collected 4 items

src/libcore/tests/test_random.py::test_pcg32 <- ../../../projects/mitsuba2/src/libcore/tests/test_random.py FAILED
src/libcore/tests/test_random.py::test_tea_float32 <- ../../../projects/mitsuba2/src/libcore/tests/test_random.py PASSED
src/libcore/tests/test_random.py::test_tea_float64 <- ../../../projects/mitsuba2/src/libcore/tests/test_random.py PASSED
src/libcore/tests/test_random.py::test_tea_vectorized <- ../../../projects/mitsuba2/src/libcore/tests/test_random.py PASSED

============================================ FAILURES ============================================
___________________________________________ test_pcg32 ___________________________________________

    def test_pcg32():
        ...
>           assert 'H' if p.next_uint32(2) == 1 else 'T' == v
E           TypeError: next_uint32(): incompatible function arguments. The following argument types are supported:
E               1. (self: mitsuba.core.PCG32) -> int
E
E           Invoked with: PCG32[state=0xbeb6d0b73fdb974a, inc=0x6d], 2

../../../projects/mitsuba2/src/libcore/tests/test_random.py:31: TypeError
=============================== 1 failed, 3 passed in 0.28 seconds =========================
```

To fix this issue, I've applied the following patch to ``py``:

```
diff --git a/py/_path/local.py b/py/_path/local.py
index 194ebed4..4a4c6670 100644
--- a/py/_path/local.py
+++ b/py/_path/local.py
@@ -155,6 +155,7 @@ class LocalPath(FSBase):
                                  "or non-empty strings to LocalPath")
             if expanduser:
                 path = os.path.expanduser(path)
+            path = os.path.realpath(path)
             self.strpath = abspath(path)

     def __hash__(self):
```

Afterwards, I get the following much more pleasant output:

```
====================================== test session starts =======================================
platform darwin -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /Users/wjakob/anaconda/bin/python
cachedir: .cache
rootdir: /Users/wjakob/Dropbox/projects/mitsuba2, inifile: pytest.ini
plugins: xdist-1.17.1
collected 4 items

src/libcore/tests/test_random.py::test_pcg32 FAILED
src/libcore/tests/test_random.py::test_tea_float32 PASSED
src/libcore/tests/test_random.py::test_tea_float64 PASSED
src/libcore/tests/test_random.py::test_tea_vectorized PASSED

============================================ FAILURES ============================================
___________________________________________ test_pcg32 ___________________________________________

    def test_pcg32():
        ...
>           assert 'H' if p.next_uint32(2) == 1 else 'T' == v
E           TypeError: next_uint32(): incompatible function arguments. The following argument types are supported:
E               1. (self: mitsuba.core.PCG32) -> int
E
E           Invoked with: PCG32[state=0xbeb6d0b73fdb974a, inc=0x6d], 2

src/libcore/tests/test_random.py:31: TypeError
=============================== 1 failed, 3 passed in 0.30 seconds ===============================
```

I'm not sure if this patch to ``py`` is the way to go -- that said, it would be great if the behavior of ``pytest`` could be adopted accordingly.

**Comment by srinivasreddy** [comment]
That looks like reasonable request.

**Comment by nicoddemus** [comment]
Agreed, @RonnyPfannschmidt do you see a problem with that approach? Otherwise a patch to `py` would be appreciated.

**Comment by RonnyPfannschmidt** [comment]
without a opt in this would be a incompatible api change, so it would need a option we seet to true

perhaps something like pathlibs resolve is needed

**Comment by wjakob** [comment]
An opt-in sounds fine to me (e.g. an option in ``pytest.ini``)

**Comment by nicoddemus** [comment]
Alternatively we might normalize that path in pytest after it is created? We could avoid the option then.

I'm not sure what this is supposed to mean:

```
src/libcore/tests/test_random.py::test_pcg32 <- ../../../projects/mitsuba2/src/libcore/tests/test_random.py FAILED
```

[Here's the code](https://github.com/pytest-dev/pytest/blob/master/_pytest/terminal.py#L442) that handles that:

```python
    def _locationline(self, nodeid, fspath, lineno, domain):
        def mkrel(nodeid):
            line = self.config.cwd_relative_nodeid(nodeid)
            if domain and line.endswith(domain):
                line = line[:-len(domain)]
                l = domain.split("[")
                l[0] = l[0].replace('.', '::')  # don't replace '.' in params
                line += "[".join(l)
            return line
        # collect_fspath comes from testid which has a "/"-normalized path

        if fspath:
            res = mkrel(nodeid).replace("::()", "")  # parens-normalization
            if nodeid.split("::")[0] != fspath.replace("\\", "/"):
                res += " <- " + self.startdir.bestrelpath(fspath)
        else:
            res = "[location]"
        return res + " "
```

**Comment by wjakob** [comment]
Curious. I tried to make a small testcase to reproduce this issue, and wasn't able to. Then I tried to understand into what distinguished my test setup from the actual project.

The differences were:

The small example was in my home directly, while the project exhibiting the issue was in a subdirectly that was reachable using different paths due to symlinks, e.g. ``~/Dropbox/projects/my_project`` and ``~/projects/my_project``. The project exhibiting the issue had pre-generated ``__pycache__`` directories due to prior runs. After wiping those, the path issue disappeared.

That leads me to believe that pytest somehow relies on cached path data in ``__pycache__``. When the project is moved or executed via a different symlink, this can lead to these odd-looking paths showing up in ``pytest`` output.

**Comment by nicoddemus** [comment]
Hmm thanks @wjakob for looking into this.

Indeed that might be the reason, in which case this might be considered a "feature". 😝 

Not sure, would like to hear more opinions.

**Comment by RonnyPfannschmidt** [comment]
sounds like a feature to me, we should make the code sane and comprehensible as its not clear from the code anymore

**Comment by nicoddemus** [comment]
> we should make the code sane and comprehensible as its not clear from the code anymore

Agree, at the least adding a docstring will be good. Adding a small note somewhere on the docs would also be good so users can find an explanation in the docs.

**Comment by RonnyPfannschmidt** [comment]
i#d prefer to give the variables names that convery what we do ^^

**Comment by nicoddemus** [comment]
Definitely, that's why I said *at the least* 😉

**Comment by blueyed** [comment]
There has been done some work in this regard lately, so I think the initial issue can be closed.

@wjakob 
Please confirm and re-open if that's not the case.
