### ISSUE TITLE
Consider exporting MonkeyPatch to enable type hints

### ISSUE THREAD

**Issue by CaselIT** [pytest-dev/pytest#2712]
I would like to use type hints for the `monkeypatch` fixture, but the class `MonkeyPatch` is not exported by pytest, so at the moment it needs to be imported from the internal package `_pytest`. 

Example: 
```py
from pytest import MonkeyPatch 

def test_something(monkeypatch: MonkeyPatch):
    # monkeypatch has type hints here if the IDE supports them
    monkeypatch.delattr(...)
```

**Comment by RonnyPfannschmidt** [comment]
currently we dont export internal classes, and deciding which internal **interfaces** to export will be a really interesting future experience

**Comment by CaselIT** [comment]
It it because `MonkeyPatch` should not be instantiated directly, or just to avoid polluting the pytest module?
Maybe they could be exposed in an `interfaces` module (or similar) so they can be imported with `from pytest.interfaces import MonkeyPatch `

**Comment by nicoddemus** [comment]
> It it because MonkeyPatch should not be instantiated directly, or just to avoid polluting the pytest module?

The latter, specially regarding the name of the class and the API to initialize it.

Alternatively I remember that it was possible to provide some `.pyi` files instead (or something similar). I wonder if this would solve this problem as well.

**Comment by CaselIT** [comment]
@nicoddemus Thanks for the clarification.

I'm not familiar with how the strub files work. I'll try look into it.

**Comment by Zac-HD** [comment]
Closing as obsoleted by discussion in #3342.

**Comment by CaselIT** [comment]
I'll follow the other issue then. Thanks for the heads-up
