### ISSUE TITLE
[RFC] equivalent to numpy's assert_no_warning

### ISSUE THREAD

**Issue by massich** [pytest-dev/pytest#2714]
Somewhere I've seen that `raises` can take `None` as `expected_exception` to indicate that nothing is raised. (it seems that I can't find where i've seen it right now. does anyone know or I just dream it?). 
Anyhow, `excpected_exception=None` does not make much of sense unless it wants to get passed as a fixture which in this case it is great.

```py
def foo(bar=None):
     if bar is not None:
         raise Exception
@pytest.mark.parametrize("expected,bar", [
    (None, None),
    (Exception, 'something')])
def test_eval(expected, bar):
    with pytest.raises(expected):
           foo(bar)
```

With the same idea I would like to know what you think about using `warns(None)` to mimic numpy's `assert_no_warning`. Right now `warns(expected_warning=None)` has no effect:

```py
>>> import pytest
>>> import warnings
>>> with pytest.warns(None):
...     pass
>>> with pytest.warns(None):
...     warnings.warn(FutureWarning)
```

And here's is an example of the proposed functionality
```py
>>> def new_warns(x):
...     with pytest.warns(x) as w:
...             yield
...     assert len(w) == 0, "warning was triggered and expected None"
... 
>>> with new_warns(None):
...     pass
... 
>>> with new_warns(None):
...     warnings.warn(FutureWarning)
... 
Traceback (most recent call last):
  ...
AssertionError: warning was triggered and expected None
```

What do you think?

**Comment by The-Compiler** [comment]
That's not the case currently (as it was bikeshedded to death), see #1830. I agree it'd make sense to have the same API for `warns` though.

**Comment by nicoddemus** [comment]
FWIW I think it is also a sensible idea.

**Comment by RonnyPfannschmidt** [comment]
same pain all over again -  if you encode reversed behaviour by magic constants its time to consider just giving it a new name in the first place

**Comment by massich** [comment]
Since this proposal has the same scope that the one in #1830. We can close this issue and follow the discussion there.
