### ISSUE TITLE
Please consider adding context manager versions of setup/teardown

### ISSUE THREAD

**Issue by NeilGirdhar** [pytest-dev/pytest#2718]
This question describes an example of the problem: https://stackoverflow.com/questions/8416208/in-python-is-there-a-good-idiom-for-using-context-managers-in-setup-teardown.  You want to invoke a context manager in your setup/tearing-down, but the easiest way to do that is to override `run` or use an `ExitStack`, which seem ugly.

Why not add two methods to `TestCase` whose default implementations are given below:

```
class TestCase:

    @contextmanager
    def method_context(self):
        self.setup()
        try:
            yield
        finally:
            self.teardown()

    @contextmanager
    def class_context(self):
        self.setupClass()
        try:
            yield
        finally:
            self.teardownClass()


Then, if for example someone wants to use a context manager in setUp, they can do so:

class SomeTest(TestCase):

    @contextmanager
    def method_context(self):
        with np.errstate(all='raise'):
            with super().method_context():
                yield
```

---

Incidentally, it's unfortunate that `setup` and `teardown` (nouns) were not called `set_up` and `tear_down` (verbs).

**Comment by RonnyPfannschmidt** [comment]
fixtures already support that - its not clear what you are asking for and your examples are full of legacy `TestCase` subclasses - we only support it on a reasonable effort case, we certainly wont build extensions for it

**Comment by nicoddemus** [comment]
Complementing @RonnyPfannschmidt's answer, I believe you are talking about `unittest.TestCase` subclasses, in which case we are reluctant to add extra features to it: pytest supports it to run existing `unittest`-based suites, not to add more features to that framework. 

For pytest based test suites thought (classes prefixed with `Test` and which *don't* subclass `unittest.TestCase`) you can use pytest's [fixtures](https://docs.pytest.org/en/latest/fixture.html), which are a more powerful concept and support context managers natively.

To understand what `unittest` features are supported by pytest, please take a look at [the docs](https://docs.pytest.org/en/latest/unittest.html). Also, it is possible to mix pytest fixtures with `unittest` classes [to a certain degree](https://docs.pytest.org/en/latest/unittest.html#using-autouse-fixtures-and-accessing-other-fixtures) and with some limitations.

**Comment by NeilGirdhar** [comment]
Sorry, I went from unittest to nose to pytest.  Looking at fixtures, it looks like they're better.
