### ISSUE TITLE
Pytest not detecting local .ini file when running specific part of test

### ISSUE THREAD

**Issue by KayaLukenIncapptic** [pytest-dev/pytest#2723]
root/
.ini
root/sub
.ini
root/sub/tests/
test_this.py

Detects root .ini, but not local when I specify exact test case to run in subfolder:
pytest sub/tests/test_this.py::TestCase

If I just run subfolder
`pytest sub/tests/test_this.py`
 it detects local .ini.

I dont think this is good behaviour. Why doesnt pytest walk back up to local subfolder and find local .ini when I run specific test case?

**Comment by nicoddemus** [comment]
Thanks @KayaLukenIncapptic 

I'm not sure I understand the problem question, could you please add more information? Thanks!

**Comment by nicoddemus** [comment]
Closing for now; we will be happy to re-open this once we get more information.
