### ISSUE TITLE
argcomplete global bash completion doesn't work

### ISSUE THREAD

**Issue by pavelrad** [pytest-dev/pytest#2725]
According to [documentation](https://docs.pytest.org/en/latest/bash-completion.html), the bash completion may be activated globally with `activate-global-python-argcomplete` command, and this really works for other scripts, but not for pytest. 
This type of completion works when it finds `PYTHON_ARGCOMPLETE_OK` string in the head of a script, that you're trying to use completion for. `pytest.py` has this string, but console scripts are created by setuptools during installation, therefore they don't have this string and argcomplete's global completion doesn't work.

Verified with pytest 3.0.7 and 3.2.1.

**Comment by nicoddemus** [comment]
Thanks @pavelrad, would you like to verify that this works and submit a PR?

**Comment by pavelrad** [comment]
I'm not sure how to fix this. This also could be an issue in argcomplete itself, I'll try to investigate further.

**Comment by nicoddemus** [comment]
Thanks @pavelrad. Please follow up once you discover something. 👍

**Comment by pavelrad** [comment]
This happens due to the specific behaviour of 'wheels'. See https://github.com/kislyuk/argcomplete/issues/225 for more details.

**Comment by nicoddemus** [comment]
Thanks for the follow up!

**Comment by stduolc** [comment]
+1
