### ISSUE TITLE
Use latest pluggy

### ISSUE THREAD

**Issue by tgoodlet** [pytest-dev/pytest#2730]
Latest version is now [0.5.1](https://pypi.org/project/pluggy/).

The list of benefits includes:
- speedier `_MultiCall` loop using `for` instead of `while`
- warnings for the deprecation of `__multicall__`
- warnings for hook impls which mismatch specs
- more comprehensible error messages on incorrect usage
- important fix for callbacks where historic hooks would not be called for already registered plugins

**Comment by nicoddemus** [comment]
Took a quick stab at this but it seems there's a problem (or misinterpretation on my part) on how `firstresult` works:

```
Traceback (most recent call last):
  File "C:\pytest\.env27\Scripts\pytest-script.py", line 11, in <module>
    load_entry_point('pytest', 'console_scripts', 'pytest')()
  File "c:\pytest\_pytest\config.py", line 50, in main
    config = _prepareconfig(args, plugins)
  File "c:\pytest\_pytest\config.py", line 160, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "c:\pytest\.env27\lib\site-packages\pluggy\__init__.py", line 680, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\pytest\.env27\lib\site-packages\pluggy\__init__.py", line 240, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\pytest\.env27\lib\site-packages\pluggy\__init__.py", line 234, in <lambda>
    methods, kwargs, specopts=hook.spec_opts, hook=hook
  File "c:\pytest\.env27\lib\site-packages\pluggy\callers.py", line 104, in execute
    gen.send(outcome)
  File "c:\pytest\_pytest\helpconfig.py", line 70, in pytest_cmdline_parse
    if config.option.debug:
AttributeError: 'list' object has no attribute 'option'
```

Here's the code for `pytest_cmdline_parse()` impl:

https://github.com/pytest-dev/pytest/blob/0824076e119cc06fbfb41155938004c19b583354/_pytest/helpconfig.py#L65-L70

`outcome.get_result()` is returning a `list`, while we expected it to return a single `Config` object.

That's using `pluggy-0.5.1`.

**Comment by RonnyPfannschmidt** [comment]
@tgoodlet yay - this means  we missed and important core detail of pluggy that @hpk42 never had a correct test for ^^ and 0.5.1 is not actually good, just not completely broken

**Comment by tgoodlet** [comment]
@nicoddemus hah! Nice catch.
This `firstresult` stuff seems to be quite subtle (and untested) hehe.

I think the difference here is that the way the original `_LegacyMultiCall` terminates its `while` loop when `firstresult` is used. The recursion unwinds returning a single value in a very sneaky way.

I can see 2 ways to handle this:
- make `_Result` aware of the `firstresult` notion
- handle and reset the `outcome` based on the `firstresult` condition before sending to hookwrappers

I personally vote for the latter.

I'll suggest a test and fix first tomorrow morning.
It's a good thing we're catching this stuff now so we can add tests for it 👍

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt yes you're totally right.
I guess it's not all bad because at least we're figuring out the tests we need.
This is why I was partial a while back to running `pytest` unit tests as part of `pluggy` CI.

Either way sounds like we'll have 2 patch releases in 2 days...yey

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt yeah definitely not great. 
At least it seems like none of those projects are using `firstresult` hook wrappers.

Alright looking at a fix.

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt @nicoddemus please see pytest-dev/pluggy#72

**Comment by RonnyPfannschmidt** [comment]
@tgoodlet we also need a job on pytest to test regulary with latest pluggy and in future attrs as well

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt sounds like a good plan.
