### ISSUE TITLE
Better guidance in --result-log deprecation warning

### ISSUE THREAD

**Issue by thebjorn** [pytest-dev/pytest#2739]
The current warnings summary when using `--result-log` looks like this:
```
============================== warnings summary ===============================
None
  --result-log is deprecated and scheduled for removal in pytest 4.0
 
-- Docs: http://doc.pytest.org/en/latest/warnings.html
 
==================== 17 passed, 1 warnings in 3.76 seconds ====================
```
which doesn't give any information on what to use instead, possible work-arounds, links to more information, etc.

The link to warnings.html looks promising but is a red-herring. Perhaps a more distinctive way of indicating that it isn't related to the `--result-log` warning can be found?

I wasn't actually using the output of `--result-log` for anything so the easiest solution was just to remove the usage of the switch (but I didn't think to look at the contents until after I'd found #1812 and #830..)

**Comment by nicoddemus** [comment]
@thebjorn you are absolutely right, we should include a link in the warnings message to the `Creating resultlog format files` section in the docs, and update that section with guidance for users on how to deal with the deprecation.

I think one of the suggestions was to use [pytest-tap](https://pypi.python.org/pypi/pytest-tap) or create a new external plugin which would generate a stream of JSON objects.
