### ISSUE TITLE
Add a broader "traceback hiding" mechanism

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2745]
The current `__tracebackhide__` mechanism to hide internal code details from traceback entries is too brittle; some small refactor might start to show internal code details to users.

I propose adding a new `__tracebackhideall__` mechanism which when found and set to `True` will strip all frames below it. This way we can add to `__tracebackhideall__` at the module level of a package and any traceback from it will be hidden.

**Comment by nicoddemus** [comment]
xref: pytest-dev/pluggy#80

**Comment by RonnyPfannschmidt** [comment]
duplicate of #283

**Comment by RonnyPfannschmidt** [comment]
also i'm against adding more hooks and magic values, lets talk about what is internal and not via a better configuration

for consumers of sqlalchemy for example sqlalchemy may be internal (and those tracebacks can be long)

same goes for other frameworks

**Comment by RonnyPfannschmidt** [comment]
also in addition - for stuff like pytest-html it may be awesome to know which traceback bit belongs to which framework

because it can just make those expandable

CC @davehunt

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt thanks for pointing it out, I have forgotten about the discussion that took place in that other thread. Closing this as duplicate.
