### ISSUE TITLE
argparse exits with code 2 on (usage) errors, should be mapped to UsageError

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#2753]
With pytest-watch I've noticed that `pytest.main` exits with code 2 (via `SystemExit`) in case there is an argparse error (unrecognized args).

This could be mapped into throwing `UsageError` instead:

```diff
diff --git i/_pytest/config.py w/_pytest/config.py
index 364ac13c..0e879f34 100644
--- i/_pytest/config.py
+++ w/_pytest/config.py
@@ -801,6 +801,9 @@ def parse_args(self, args=None, namespace=None):
             getattr(args, FILE_OR_DIR).extend(argv)
         return args
 
+    def error(self, message):
+        raise UsageError(self.format_usage(), message)
+
 
 class DropShorterLongHelpFormatter(argparse.HelpFormatter):
     """shorten help for long options that differ only in extra hyphens
```

But at least it sounds sensible to wrap it and exit with pytest's "usage error" code, which would be 4 according to https://docs.pytest.org/en/latest/_modules/_pytest/main.html.

**Comment by RonnyPfannschmidt** [comment]
@blueyed care to provide a pr with a patch + test?

**Comment by blueyed** [comment]
@RonnyPfannschmidt 
Not currently - a patch would be above, but I wanted to ask for opinions first, since I have not much experience with argparse (integration).

**Comment by nicoddemus** [comment]
Seems sensible at first glance, if a test proves it works I don't see any problems with it. 😁

**Comment by nicoddemus** [comment]
A note: this should definitely go into `features`.

**Comment by crazymerlyn** [comment]
I believe #3925 closes this.

**Comment by blueyed** [comment]
@crazymerlyn 
Re-opening, #3925 does not look like it solved this.

But https://github.com/pytest-dev/pytest/pull/4651 includes this.
