### ISSUE TITLE
How do you capture all the sysouts and syserrs?

### ISSUE THREAD

**Issue by hyginous29** [pytest-dev/pytest#2755]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by nicoddemus** [comment]
Pytest uses a number of techniques, take a look at the [`capture.py`](https://github.com/pytest-dev/pytest/blob/master/_pytest/capture.py) module. Do you have a specific question in mind?

**Comment by RonnyPfannschmidt** [comment]
closing as to me it looks like OP didn#t even try

not even the default message for issues seems changed

from my pov that's just the bad kind of lazyness
