### ISSUE TITLE
MarkDecorator __eq__ override can lead to bad side effects

### ISSUE THREAD

**Issue by astraw38** [pytest-dev/pytest#2758]
The MarkDecorator ``__eq__`` method assumes that it will always be compared with another mark. If you do large parametrizations based on lists, then you'll likely run into scenarios where this isn't the case (especially if you do combinations of lists).

Simple example:

```py
import pytest
TEST_DATA = ['a', 'b', 'c', pytest.mark.xfail('d')]
SUBSET_TESTS = [x for x in TEST_DATA if x in ('a', 'b')]

@pytest.mark.parametrize('data', SUBSET_TESTS)
def test_me(data):
     pass
```

You'll get an error on collection:

```py
    return self.mark == other.mark
E   AttributeError: 'str' object has no attribute 'mark'
```

This affects sets, lists (including ``list.index``!), anything that checks for equality.

**Comment by xuanluong** [comment]
@astraw38 This seems to be easy to fix. Do you plan to create a PR on this? If not, can you assign this to me, @RonnyPfannschmidt ?

**Comment by RonnyPfannschmidt** [comment]
@xuanluong please go ahead and accompany it with a small unittest

**Comment by astraw38** [comment]
@xuanluong I hadn't planned on it -- not for lack of desire, but lack of time :)
