### ISSUE TITLE
refactor and unittest mark evaluator

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2767]
its api is a mess and the thing that directly intervened with brining the mark api replacement forward
so i need it tested distinctly, ideally trimming down the testsuites massive tests that basically do acceptance tests on this one down

**Comment by bilderbuchi** [comment]
Is this closed by #2773?

**Comment by RonnyPfannschmidt** [comment]
yes, thanks 👍
