### ISSUE TITLE
Testing - Issue 1

### ISSUE THREAD

**Issue by Raghu-Periyasamy** [pytest-dev/pytest#2768]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by The-Compiler** [comment]
More like issue #2768 :wink: (huh?)
