### ISSUE TITLE
from unittest.mock import call

### ISSUE THREAD

**Issue by dfroger** [pytest-dev/pytest#2769]
foo.py:

    from unittest.mock import call

Running:

    pytest foo.py

never finish to collect tests, and consume all CPU and Memory of my computer.

Tested on Debian 8 with 3.1.0 and 3.2.2, Python 3.6.1

**Comment by The-Compiler** [comment]
Duplicate of #1217

**Comment by dfroger** [comment]
thanks, I did not search enough...
