### ISSUE TITLE
some tests just hang outside of tox runs

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2774]
as far as i can tell its not possible to correctly test pytest outside of tox since years now
this is starting to impede my testing/re-factoring seriously

common issues happen with terminal/pdb tests

**Comment by RonnyPfannschmidt** [comment]
i was typically experiencing hangups when just using my normal testing virtualenv with pexpect availiable, (pexpect using tests would hang, i didnt yet verify against #3116

**Comment by darwinyip** [comment]
I just experienced this issue when running tests for https://github.com/vertica/vertica-python on osx.

**Comment by blueyed** [comment]
Closing as possible duplicate of #2673 (pexpect related), since this has no additional info, except for the hint to https://github.com/pytest-dev/pytest/pull/3116.
