### ISSUE TITLE
Customizing the debug level of a py.test plugin (specified by a setuptools entry_point)

### ISSUE THREAD

**Issue by mikeage** [pytest-dev/pytest#2787]
Hi,

Is there any way to customize the logger that will be used by a py.test plugin? From https://docs.pytest.org/en/latest/writing_plugins.html#plugin-discovery-order-at-tool-startup, it seems that plugins registered with setuptools are loaded before conftest.py and before `-p foo` options, but is there any way to run some code (say, `logging.getLogger("foo").setLevel(...)` before the plugin is loaded?

**Comment by RonnyPfannschmidt** [comment]
pytest is not integrated with logging at all

**Comment by mikeage** [comment]
Right; I'm just giving logging as an example of why I'd want to run my code before a setuptools registered plugin is loaded.

**Comment by RonnyPfannschmidt** [comment]
currently its not possible to run code before setuptools plugin loading,
you cam however push in code by registring a own setuptools plugin/conftest and running code in it globally

in case thats too late (aka at plugin registration time but before pytest configuration time, you are currently out of luck

**Comment by mikeage** [comment]
ok, thanks!
