### ISSUE TITLE
Overwriting a fixture in a plugin

### ISSUE THREAD

**Issue by rth** [pytest-dev/pytest#2793]
I'm attempting to overwrite a fixture (defined at the session level, but I don't think it matters) in a plugin using the following setup.

**test_definition.py**
```py
import pytest

@pytest.fixture(scope='session')
def fixture_a():
    return 'defined_in_module'

def test_1(fixture_a):
    print(fixture_a)
```
when run with `py.test -s .` the output illustrates that `test_1` uses `fixture_a` defined in the same file.

Now if I  run this file programmatically with a custom plugin that re-defines the `fixture_a`,
```py
import pytest

class FixtureRegPlugin(object):

    @pytest.fixture(scope='session')
    def fixture_a(self):
        return "fixture_from_plugin"

pytest.main(['-s', './test_definition.py'], plugins=[FixtureRegPlugin()])
```
the original fixture is neverless used (i.e. it is not overwritten).  If the fixture is not originally registed in the `test_definition.py` file, this works as expected. 

Maybe that is the intended behavior (although it is counter-intuitive) but then I could not find anything about fixture overwriting or priority in the documentation (unless I missed something, or if [this section](https://docs.pytest.org/en/2.7.3/plugins.html?highlight=re#plugin-discovery-order-at-tool-startup) is related) ...

Using Pytest 3.2.1 with Python 3.6 (on Linux) in a clean virtualenv.

**Comment by rth** [comment]
The only workaround I found so far is to conditionally define the fixture in `test_definition.py` with,
```py
if sys.argv[0].startswith(('py.test', 'pytest')):
    @pytest.fixture(scope='session')
    def fixture_a():
        return 'defined_in_module'
```
so it is registered only when run with pytest from the command line and would be defined in the plugin otherwise. Still, this feels a bit hacky and I wish the documentation would state what fixture definition get priority and how to change that (but maybe I missed something)..

**Comment by RonnyPfannschmidt** [comment]
a fixture in a test moule/class superseeds a fixture in a plugin

if you want to make a fixture replacable, you need to put its general definition into a switchable plugin

**Comment by rth** [comment]
@RonnyPfannschmidt Thank a lot for your response!

> to make a fixture replacable, you need to put its general definition into a switchable plugin

Could you please elaborate on this? What's a "switchable plugin"? I couldn't find anything in the docs...

**Comment by RonnyPfannschmidt** [comment]
@rth to add more context, it would mean something like having a plugin that registers a different fixture bad on options

that plugin could be added in a conftest

**Comment by rth** [comment]
Actually, I missed the whole documentation [section on fixture priorities](https://pytest.readthedocs.io/en/3.2.2/fixture.html#overriding-fixtures-on-various-levels) (was searching or "overwrite" instead of "override")... 

So if I understood correctly the priority for fixtures is
 
    root conftest.py < directory conftest.py < local function  

and since `conftest.py` is a local plugin, I guess plugins have the same priority as the root `conftest.py`. 

If I put my fixture directly in the `conftest.py` it's still going to override the one defined in the plugin. I'm not sure how to define a plugin in a `conftest.py` (since if I understood correctly `conftest.py` is a local plugin). But anyway, thank you for your explanations, I have enough elements to get a way around it.

Sorry of if Github is not the best medium for such discussion but it doesn't seem like pytest has a user mailing list or a gitter channel..

**Comment by obestwalter** [comment]
> Sorry of if Github is not the best medium for such discussion but it doesn't seem like pytest has a user mailing list or a gitter channel..

https://docs.pytest.org/en/latest/contact.html
