### ISSUE TITLE
How to add a decorator to each collected test?

### ISSUE THREAD

**Issue by cuyu** [pytest-dev/pytest#2797]
Hi, 

I'm using pytest==2.9.2 and I'd like to write a pytest plugin to automatically add specific decorators to all the collected test items. Is this possible in current pytest framework?

**Comment by nicoddemus** [comment]
Sure, just add this to your `conftest.py` file:

```python
def pytest_collection_modifyitems(session, config, items):
    for item in items:
        if some_condition(item):
            item.add_marker(pytest.mark.mymark(argument=1))
```

I would take a look in [the list of plugins](http://plugincompat.herokuapp.com/) first, there might be a plugin which already does this.

Closing this for now, but feel free to follow up with more questions.

**Comment by cuyu** [comment]
@nicoddemus Thanks for your quick response. I'm not just wanting to add pytest marks on the collected test items. Here, the decorator is a function written by myself.

I found this may be a solution:
```python
from my_libs import my_decorator  # Import the decorator function

def pytest_runtest_call(item):
    testfunction = item.obj
    item.obj = my_decorator(testfunction)  # Replace the item function with the decorated one
```

**Comment by nicoddemus** [comment]
Oh OK my bad.

Yes you can access the original function object like you did. 👍
