### ISSUE TITLE
Compatibility issue with allure/xdist/pytest

### ISSUE THREAD

**Issue by leightonlee** [pytest-dev/pytest#2811]
Hi there, I am having trouble with an allure/xdist/pytest compatibility issue. When I run a test and an exception is raised, _pytest/_code/code.py throws an exception on line 764 in class ReprTraceback, method toterminal. 

`if entry.style == "long":`

When I do not use allure or when I do not use xdist, it works perfectly fine.  The problem only happens when I use both allure and xdist.  When I debugged the problem, entry is a dict representation of the class object.  (If I change the dict to the class object along with a few other classes that have the same problem, it works fine).  I could not find a similar bug so I'm not sure if it's already known.

If I made a PR that checks to see if the object is a dict and transforms it to the class object if it is a dict, would you accept that?  This would make it compatible for when it is a dict or the class object and would not break any functionality. If this is not acceptable, can you please advise on what would be an appropriate approach to solve this problem? Thank you.

E.g.
```
if isinstance(item, dict): 
    item = self.from_dict(item)
```

my virtual env is the following and I am using python 3.6.1:
apipkg==1.4
babel==2.5.0
bravado==9.1.0
bravado-core==4.8.4
certifi==2017.7.27.1
chardet==3.0.4
colorama==0.3.9
decorator==4.1.2
docutils==0.14
et-xmlfile==1.0.1
execnet==1.4.1
idna==2.6
imagesize==0.7.1
jdcal==1.3
jinja2==2.9.6
jsonpath-ng==1.4.2
jsonschema==2.6.0
lxml==3.8.0
markupsafe==1.0
namedlist==1.7
ply==3.10
py==1.4.34
pygments==2.2.0
pymongo==3.4.0
pyodbc==4.0.17
pytest==3.2.2
pytest-allure-adaptor==1.7.8
pytest-assume==1.2
pytest-cache==1.0
pytest-forked==0.2
pytest-pep8==1.0.6
pytest-xdist==1.20.0
python-dateutil==2.6.1
pytz==2017.2
PyYAML==3.12
requests==2.18.4
rfc3987==1.3.7
simplejson==3.11.1
six==1.10.0
snowballstemmer==1.2.1
sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
strict-rfc3339==0.7
swagger-spec-validator==2.1.0
urllib3==1.22
webcolors==1.7

I am using windows 7 Enterprise SP1 64bit OS with python 3.6.1

A minimal working example is:
```
    @pytest.mark.allurexDistCheck
    def test_allure_xdist_check_negative(self):
        assert (False)
```
with cmd line arguments: -d --tx 2*popen --alluredir C:/<your_path>/PycharmProjects/<project_name>/reports/target/allure-results

**Comment by nicoddemus** [comment]
Hi @leightonlee,

Are you using [allure-python](https://github.com/allure-framework/allure-python) for the integration? I never used it, but it seems it should make working with pytest + allure a breeze.

**Comment by nicoddemus** [comment]
> If I made a PR that checks to see if the object is a dict and transforms it to the class object if it is a dict, would you accept that? 

In general this is tricky, it would be better for us to first understand who is producing a `dict` object and not a `TracebackEntry` as they should.

**Comment by leightonlee** [comment]
I have not tried allure-python yet but I will check on it and let you know the results.

**Comment by leightonlee** [comment]
Hi, just letting you know the results. I got it working by using allure-python/xdist/pytest. Just in case other people wanted to know, I am using:
pytest 3.2.2
pytest-xdist 1.20.0
allure-pytest 2.2.2b2

and I had to upgrade my python version to 3.6.3.  Python 3.6.1 was giving me errors with enum34 but apparently python 3.6.3 wasn't.  Thanks for the help.

**Comment by nicoddemus** [comment]
Awesome, thanks for following up!
