### ISSUE TITLE
finally drop python2.6 support

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2812]
i just verified with @dstufft that pip master no longer supports python2.6 and we can drop it for all purposes

**Comment by obestwalter** [comment]
Is a release of pip 10 in sight then? Last time I checked I found a comment by @dstuff that there is no ETA.

**Comment by nicoddemus** [comment]
I thought we would wait for the actual release of pip 10 no?

**Comment by nicoddemus** [comment]
Btw, should we drop 3.3 at the same time?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus yup wrt 3.3

@nicoddemus wrt release waiting, the work time spend on pip ha been reduced, so its in need of more volunteer work as well,

as such i think for pytest its reasonable to change before the release,
with a bit of luck pips release wil be before our next feature release

**Comment by hugovk** [comment]
Here's a reference to pip dropping 2.6: https://github.com/pypa/pip/issues/3955

Here's the last few issues remaining for pip 10: https://github.com/pypa/pip/milestone/23

Here's the earlier PR to drop it here: https://github.com/pytest-dev/pytest/pull/2031

**Comment by dstufft** [comment]
FWIW we don't run tests against old versions of pip really, so it's pretty much just the master branch that matters, and it doesn't run against 2.6 now.

**Comment by RonnyPfannschmidt** [comment]
since attrs doesnt support 2.6 i#ll take a stake at working this one out - i want attrs asap in pytest ^^
