### ISSUE TITLE
adapt the python 3.7 ast additions/changes

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2818]
python3.7 did away with pyo and it did add/change some details about the ast

this causes the current failures and should be reasonably fixabl

**Comment by tomviner** [comment]
> python3.7 did away with pyo

wasn't that in 3.5? https://www.python.org/dev/peps/pep-0488/

**Comment by RonnyPfannschmidt** [comment]
@tomviner thanks correcting - i misinterpreted the pr output back then

**Comment by Perlence** [comment]
Alpha versions of Python 3.7.0 don't respect PYTHONDONTWRITEBYTECODE https://bugs.python.org/issue31845
This makes `test_dont_write_bytecode` fail.

**Comment by Perlence** [comment]
Looks like PYTHONOPTIMIZE has no effect either.

**Comment by nicoddemus** [comment]
Thanks @Perlence for finding this.
