### ISSUE TITLE
Please consider to support python_files other than .py extensions

### ISSUE THREAD

**Issue by rajivgup** [pytest-dev/pytest#2831]
Thanks for submitting an issue!

I'm using pytest version 3.0.7 to build functional test cases for my application. That application runs under a framework that understands python and executes python script by calling python at the command line. Definitely, it does some magic before running the application. We have written test cases for that application which we want to run using pytest within that framework. Now if my test cases and application's extension is both are .py then I'm not able to differentiate my test cases and end up running everything with python. I want to keep my test cases extension different than my application. I want to givel all my test cases extension to .test. Currently in pytest it is not possible even providing python_files=*.test in ini file.

It is not supported currently by pytest due to this:

in https://github.com/pytest-dev/pytest/blob/master/_pytest/python.py

```
def pytest_collect_file(path, parent):
    ext = path.ext
    if ext == ".py":
        if not parent.session.isinitpath(path):
            for pat in parent.config.getini('python_files'):
                if path.fnmatch(pat):
                    break
            else:
                return
        ihook = parent.session.gethookproxy(path)
        return ihook.pytest_pycollect_makemodule(path=path, parent=parent)
```
There is no else condition. I'm not sure why it is hardcoded to .py. 

Please consider to provide that support or let me know if there any other workaround for this problem.

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
py.test uses the python import system to import normal tests

so in order to support your use case quite a deal of extra work is needed to begin with, so you will need a own hook and a own Module type for those anyway

as such pytest doesnt have to change, all you need is either exported or availiable via hook
