### ISSUE TITLE
exit code 2 when using '-x' flag

### ISSUE THREAD

**Issue by cmccandless** [pytest-dev/pytest#2832]
pytest v3.2.1

#### Conditions: 
A test fails while running `pytest -x`

#### Expected Behavior: 
Exit code is 1 (according to [usage](https://docs.pytest.org/en/latest/usage.html))

#### Actual Behavior: 
Exit code is 2

#### Confirmed environments:
- [x] Windows, Python3
- [ ] Windows, Python2
- [x] Linux, Python3
- [x] Linux, Python2

**Comment by jespino** [comment]
I can confirm that it happens on Arch Linux with Python 3.6.2 and Python 2.7.14

**Comment by jespino** [comment]
I have made a PR here to fix the problem #2845 but It may be the expected behavior, currently return a 2 which is a "Interrupted" error code in pytest, which have sense. Anyway, a fail error code (1 in pytest) have a lot of sense too.

**Comment by cmccandless** [comment]
Fixed in #2845
