### ISSUE TITLE
feature suggestion: allow ppl to use  "fixtures.py" as well as/instead of "conftest.py" 

### ISSUE THREAD

**Issue by hjwp** [pytest-dev/pytest#2835]
i'm not the world's biggest pytest user, but i've never used conftest.py as anything other than a place to store fixtures.  i think newcomers would find "fixtures.py" to be a more obvious name for "the place where you put fixtures".  presumably you could support both for a while.

just my drive-by suggestion for the day! <3

**Comment by RonnyPfannschmidt** [comment]
personally im `-1` on the idea - its a place where a pytest plugin is, and its a complete pytest plugin

in addition the proposed filename is already used in projects in the wild, so it would need quite some time to handle it

**Comment by robert-cody** [comment]
-1, in my conftest.py: sum(fixtures) = 1, sum(other_items) = 23.

**Comment by hjwp** [comment]
you wouldn't have to remove conftest.py.  just make using fixtures.py an option.

**Comment by RonnyPfannschmidt** [comment]
@hjwp each option we create has a backward compat cost and a maintenance cost,
maintenance is primarily volunteering atm

**Comment by hjwp** [comment]
absolutely. up to y'all to decide whether the small improvement in new-user-friendliness / intuitiveness is worth it. just thought i'd mention it in case it hadn't occurred to anyone.  i totally understand if you want to close the issue.

**Comment by nicoddemus** [comment]
@hjwp I appreciate the proposal, never be shy of proposing changes to OS projects!

As @RonnyPfannschmidt and @robert-cody mention though, `conftest.py` files don't contain only fixtures, they can also contain hooks (they are local plugins). I agree with you that "conftest" sounds weird at first, I thought the same thing when I started using pytest.

But ultimately I think it falls down to an additional backward compatibility and maintenance cost. It might seem small, but we can introduce new bugs and this small change would probably not be considered "worth" it, and all the small changes and bugs ultimately take a look of maintainer time.

So I'm closing this for now, as I said we appreciate your suggestion and understanding. 👍
