### ISSUE TITLE
Contributing to pytest-dev

### ISSUE THREAD

**Issue by vaibhav6451956** [pytest-dev/pytest#2838]
Hi Developers,

How can I start contributing to this project being a newcomer in the world of python?

Any documentation to set this project up on my local and get on with it?

**Comment by RonnyPfannschmidt** [comment]
this is a normal python project, so cloning, setting up a virtualenv should get you started reasonably well

**Comment by tomviner** [comment]
Hi @vaibhav6451956 thanks for your interest :smiley:  

there's a [page about contributing here](https://docs.pytest.org/en/latest/contributing.html). And a couple of useful filters on the issue list are <kbd>[help wanted](https://github.com/pytest-dev/pytest/labels/status%3A%20help%20wanted)</kbd> & <kbd>[easy](https://github.com/pytest-dev/pytest/labels/status%3A%20easy)</kbd>.

**Comment by nicoddemus** [comment]
There are a few also marked as "Hacktoberfest". 👍

**Comment by The-Compiler** [comment]
See https://hacktoberfest.digitalocean.com/ for what the hacktoberfest @nicoddemus mentioned is about :wink:

**Comment by vaibhav6451956** [comment]
Thank you, everyone, for replying...Will refer the resources pointed out! 👍
