### ISSUE TITLE
update existing junit when rerunning previously failed tests

### ISSUE THREAD

**Issue by dirk-thomas** [pytest-dev/pytest#2852]
Consider the following steps:

* invoke `pytest` with `--junit-xml=...`
* some tests fail
* invoke `pytest` again with the same `--junit-xml=...` and additionally `--last-failed`

**Current behavior:** the JUnit result file generated during the second invocation only contains the tests which failed in the first run. So e.g. Jenkins won't be able to tell how many tests have actually been run overall.

**Desired behavior:** the JUnit result file should contains all test result - the ones which succeeded during the first invocation as well as the ones from the second invocation. This behavior might need an option `--junit-update` to distinguish it form the current behavior of overwriting the existing file (or an option `--junit-previous-xml=...` to specify the junit file which content should be merged with the newly generated one).

Is this a feasible feature request for this package and should it be implemented in `_pytest/junitxml.py`? If yes and if there is a consensus how this should look like (new option?) I would be happy to work on a pull request for this.

**Comment by nicoddemus** [comment]
@dirk-thomas can you describe your use case? I'm curious why you need this.

Are you aware that Jenkins supports parsing multiple `.xml` files? Perhaps it would be interesting to generate two separate files and see how Jenkins interprets that.

**Comment by dirk-thomas** [comment]
>  can you describe your use case? I'm curious why you need this.

Of course One use case is to "ignore" flaky tests. Some flaky tests might fail form time to time. By rerunning the failed ones they might pass on a repeated invocation. So afterwards the "merged" JUnit result file would should only test which repeatedly fail (and not any flaky tests).

If there would be a `--last-passed` option the invert logic to detect flaky tests would be another use case in mind.

> Are you aware that Jenkins supports parsing multiple .xml files? Perhaps it would be interesting to generate two separate files and see how Jenkins interprets that.

Yes, each invocation could generate a new `.xml` file and Jenkins could use them all. I am just not sure about the override logic within the Jenkins plugin (I will need to check how it behaves: does only one of duplicate results makes it into the final result? If yes, is the order of that deterministic?). Anyway I would prefer having a single result file with the complete information rather than relaying on the behavior of the tool reading them to do the "right" thing since there are potentially more tools processing the JUnit result files after they have been generated :wink:

**Comment by nicoddemus** [comment]
Glad I asked then, take a look at the pytest-rerunfailures, it's exactly
what you need

Em qua, 18 de out de 2017 23:42, Dirk Thomas <notifications@github.com>
escreveu:

**Comment by dirk-thomas** [comment]
> Glad I asked then, take a look at the pytest-rerunfailures, it's exactly
what you need

I am glad I filled this issue before jumping in to implement something. I briefly tried `pytest-rerunfailures` and it seems to do exactly what I need. Thank you for the quick feedback. I only searched for "junit" in the plugin list - will try to perform a more thorough search next time.
