### ISSUE TITLE
"parametrize" misspelled

### ISSUE THREAD

**Issue by jpchen** [pytest-dev/pytest#2853]
`parametrize` -> `parameterize`.

i have a local method `parameterize()` which is confusing when used or grepping because it is misspelt in pytest. will this be fixed in future releases?

**Comment by nicoddemus** [comment]
`parametrize` is the [English spelling](https://en.wiktionary.org/wiki/parametrize), so it is not actually a bug. 😉 

But it is so common a misspelling that we even have internal code to detect that and issue an error.

**Comment by Wyrmwood** [comment]
Parametrize is not "the" spelling, it's a variant, at least in Merriam Webster and Oxfords, where parameterize is the primary spelling. It doesn't even exist in the Cambridge dictionary.

**Comment by The-Compiler** [comment]
Already discussed at length in #3159 - not going to happen for the reasons mentioned there.
