### ISSUE TITLE
Support keywords or annotations in `parametrize`.

### ISSUE THREAD

**Issue by coady** [pytest-dev/pytest#2855]
Proposal to enhance `parametrize` with support for keyword params.  This seems more pythonic than the zipped format, for simple params.  Reference implementation (under a different name):

```python
def params(**kwargs):
    if len(kwargs) == 1:
        return pytest.mark.parametrize(*kwargs.popitem())
    return pytest.mark.parametrize(','.join(kwargs), zip(*kwargs.values()))
```
An example from the docs:
```python
@pytest.mark.parametrize("test_input,expected", [
    ("3+5", 8),
    ("2+4", 6),
])
def test_eval(test_input, expected):
    assert eval(test_input) == expected
```
becomes:
```python
@params(test_input=["3+5", "2+4"], expected=[8, 6])
def test_eval(test_input, expected):
    assert eval(test_input) == expected
```
Relatedly, it also seems a perfect use case for Python 3 annotations:
```python
def parametrized(func):
    return params(**func.__annotations__)(func)

@parametrized
def test_eval(test_input: ["3+5", "2+4"], expected: [8, 6]):
    assert eval(test_input) == expected
```

**Comment by RonnyPfannschmidt** [comment]
at first glance im strictly opposed to passing along data values this way as its much less comprehensible what elements belong together

in addition this looks confusingly similar to combinatoric parametrization

after all 

```
@parametrize("test_input",  ["3+5", "2+4"])
@parameterize("expected", [8, 6])
```
would result in 4 tests instead of 2

**Comment by nicoddemus** [comment]
I'm not a very fan of increasing the ways to parametrize tests, I don't think it would make it easy on the users.

@coady you should consider making that into a plugin.

**Comment by coady** [comment]
Based on feedback, made this into a plugin:  [pytest-parametrized](https://pypi.org/project/pytest-parametrized/), and made it explicit on how to combine params.
```python
@parametrized           # only one param allowed
@parametrized.zip       # zipped
@parametrized.product   # cartesian product
```
And I'll mention another use case for anyone looking for this feature:  when the param values aren't literals to start.  Enums are a good example:
```python
@paremetrized.zip
def test(myenum=MyEnum, ...):
```

**Comment by nicoddemus** [comment]
Awesome @coady, thanks for sharing. After you release 1.0, please consider opening a PR adding a note about this plugin to the official parametrize docs. 👍
