### ISSUE TITLE
unable to turn off ellipses in stack traces

### ISSUE THREAD

**Issue by smurfix** [pytest-dev/pytest#2871]
Even when using `py.test -vvvv`, variables in stack traces are ellipsized when their representation gets "too long".

This is controlled by hard coded constants in `py._io.saferepr.py::saferepr()` (and more constants in Python's `reprlib`, which it inherits from), which is called from multiple locations in `py._code/code.py`.

Proposed solution: use pretty printing instead, at high verbosity levels.

**Comment by smurfix** [comment]
https://stackoverflow.com/questions/38000993/how-can-i-get-my-assertions-in-pytest-to-stop-being-abbreviated-with-ellipsis

**Comment by nicoddemus** [comment]
I believe #pytest-dev/py/pull/154 is a step in this direction.

Also I think we can close as duplicate of #980?

**Comment by smurfix** [comment]
Right … didn't find that due to wholly different search keywords. Let's continue there.

I'm somewhat unhappy with that pull request because when you have a complex data structure to report it's nearly indecipherable as a one-liner, so merely increasing the limits doesn't help that much.

**Comment by domantasjurkus** [comment]
Having the same issue, comparing two objects is cumbersome:
```
pytest tests/logic/test_branded_ratios.py -vvvv
...
expected = [{'asessions': 1, 'growth_categorisation': 'brand', 'hostname': 'www.blah.net', 'landingpage': '/', ...}, {'ases...', ...}, {'asessions': 1, 'growth_categorisation': 'unpaid', 'hostname': 'www.blah.fr', 'landingpage': '/', ...}]
actual = [{'asessions': 2, 'growth_categorisation': 'brand', 'hostname': 'www.blah.ru', 'landingpage': '/', ...}, {'asess...', ...}, {'asessions': 1, 'growth_categorisation': 'brand', 'hostname': 'www.blah.net', 'landingpage': '/', ...}]
```

**Comment by blueyed** [comment]
=> https://github.com/pytest-dev/pytest/pull/5936
