### ISSUE TITLE
investigate why we need the changedir usage in the xdist envs

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2884]
followup to #2874

the underlying issue is something we should resolve over time

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt still want to pursue this? Should we move this to `pytest-xdist` perhaps?

**Comment by RonnyPfannschmidt** [comment]
for now it should stay here since it happens for the pytest repo

**Comment by nicoddemus** [comment]
We have for awhile now no longer used `changedir` for xdist testenvs, so I'm closing this.
