### ISSUE TITLE
ModuleNotFoundError on public pypi modules having underscore in their name

### ISSUE THREAD

**Issue by stockersky** [pytest-dev/pytest#2890]
Hello,

I developed and tested code on my windows workstation. While pushing it on Linux, I can run the code but pytest returns this error:

```
ImportError while importing test module '<HOSTNAME>/home/<USER>/DEV/letstry/tests/test_module.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_module.py:2: in <module>
    import weather_tools
E   ModuleNotFoundError: No module named 'weather_tools'

```

**Every modules with '-' in their pypi names and which would install through pip with a '_' generate this issue. I first encountered this issue with 'Flask-RESTful'. But realized 'Flask-RESTless' would do it too, and so on.**

This is easy to reproduce : 
- create new virtualenv
- just install a module with '-' in their names that will translate in '_' in the package name.
Weather-tools is a good candidate cause it has no dependancies 👍 
Also install another one with a regular name and also no deps : pygments

`  pip install weather-tools pygments`

- pkg structure : 
```
.
├── letstry
│   └── __init__.py
└── tests
    └── test_module.py
```

file test_module.py
only two lines : 

```
import pygments
import weather_tools
```

- go in . directory and run :
```
$> pytest .
or
$> pytest tests/test_module.py
or
$> cd tests
$> pytest test_module.py
```

Always same error : only weather_tools or any package with '-' / '_' are problems (ex : flask-RESTful).

Actually, the error message starts from a kind of absolute path, wherever I run it from... : 

```
ImportError while importing test module **'<HOSTNAME>/home/<USER>/DEV/letstry/tests/test_module.py'.**
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_module.py:2: in <module>
    import weather_tools
E   ModuleNotFoundError: No module named 'weather_tools'

```

**System** : Red Hat Enterprise Linux Server release 7.2 (Maipo)
**Python** : Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux

** pip list **
pip (9.0.1)
Pygments (2.2.0)
setuptools (28.8.0)
weather-tools (0.0.1)
wheel (0.29.0)

Thanks for your help !

**Comment by RonnyPfannschmidt** [comment]
as a extra note - pypi names do not have to match  module names
