### ISSUE TITLE
introduce ci test envs and cronjobs against attr master

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2898]
followup to #2641

we need to ensure prerelease versions work nicely against attrs thats in development to avoid the fallout possible when attrs is forced to change api

**Comment by Zac-HD** [comment]
Closing this as it's been inactive for years, and `attrs` is super-stable - even though it's just released a big API overhaul, the backwards-compatible API is also sticking around.
