### ISSUE TITLE
Exception info is missing?

### ISSUE THREAD

**Issue by keeprocking** [pytest-dev/pytest#2900]
In one of my test cases I need to catch an exception and log it in order to test the custom logging handler logic (https://github.com/keeprocking/pygelf/blob/master/pygelf/gelf.py#L41). I tried the following:

    with pytest.raises(Exception) as e:
        raise Exception('something went wrong')
    logging.exception(e)

but it seems like log record's exc_info (https://docs.python.org/3/library/logging.html#logrecord-objects) is filled with empty values (None, None, None), as well as `sys.exc_info()`.

However, the following code works just fine when using unittest instead of pytest:

    try:
        raise Exception('something went wrong')
    except Exception as e:
        logging.exception(e)

Could you please advise how to make pytest to keep the actual exc_info?

macOS 10.11.3, pytest 3.2.3

    $ pip list
    certifi (2017.11.5)
    chardet (3.0.4)
    idna (2.6)
    mock (2.0.0)
    pbr (3.1.1)
    pip (9.0.1)
    py (1.4.34)
    pygelf (0.3.1)
    pytest (3.2.3)
    requests (2.18.4)
    setuptools (36.6.0)
    six (1.11.0)
    urllib3 (1.22)
    wheel (0.30.0)

**Comment by The-Compiler** [comment]
It makes sense that a simple `logging.exception` does not work here (and that `sys.exc_info()` gives you that), as you're not in an exception handler anymore. There isn't really much pytest can do about that.

`pytest.raises` gives you an [ExceptionInfo object](https://docs.pytest.org/en/latest/builtin.html#_pytest._code.ExceptionInfo). You can probably use `(info.type, info.value, tb)` to get the equivalent and pass that as `exc_info`, but I'm not sure. Note that the docs for `logging.exception` say:

> This function should only be called from an exception handler.
