### ISSUE TITLE
Teardown higher-scoped fixtures when not used

### ISSUE THREAD

**Issue by iwanb** [pytest-dev/pytest#2902]
I expected that if a test does not use a fixture (whatever its scope), then the test would be executed before the setup of that fixture, or the fixture would be teared down before executing the test.

This is apparently not the case, for example given these tests:

```
import pytest

shared_state = None

@pytest.fixture(scope="module")
def fix():
    global shared_state
    shared_state = "set"
    yield
    shared_state = None

def test_1(fix):
    # "set"
    print(shared_state)

def test_2():
    # still "set", would expect it None
    print(shared_state)

def test_3(fix):
    # "set"
    print(shared_state)
```

Results in this:
```
$ pytest -s --setup-show test_me.py 
============================================================== test session starts ==============================================================
platform linux -- Python 3.6.3, pytest-3.2.3, py-1.4.34, pluggy-0.5.2
rootdir: /tmp/mytests, inifile:
collected 3 items                                                                                                                                

test_me.py 
  SETUP    M fix
        test_me.py::test_1 (fixtures used: fix)set
.
        test_me.py::test_2set
.
        test_me.py::test_3 (fixtures used: fix)set
.
  TEARDOWN M fix

=========================================================== 3 passed in 0.01 seconds ============================================================
```

While I would expect the TEARDOWN of the fixture would be executed before test_2 and the tests would be reordered to avoid doing useless TEARDOWN/SETUP if possible.

This prevents using fixtures to change state which some tests within that scope expect to be unchanged. 

I think changing this behaviour should be doable from a plugin, but IMO it should be the default.
Another option would be to add an argument to the fixture decorator to have a strict teardown/setup or not.

What do you think?

Iwan

**Comment by RonnyPfannschmidt** [comment]
fixture scope are explicit tools to keep things around, even if they change as the cost having a shared dependency is less than the cost of the repeated setup/teardown

from my pov its a no go to change it

**Comment by iwanb** [comment]
Sure I understand.
For me it means you cannot really create reusable fixtures with side effects in a scope other than function as that side effect might leak to tests without the fixture depending on the test order. But I would still like to avoid the repeated setup/teardown when possible.

Would adding an argument to the fixture decorator be an option?

I will look into implementing the behaviour in a plugin.

**Comment by RonnyPfannschmidt** [comment]
well - what you describe basically amounts to forcing all scopes to be function scope
thats directly and correctly available as function scope

and from my pov anything else is a "lie"

**Comment by nicoddemus** [comment]
I agree with @RonnyPfannschmidt, I don't think this change is doable it defeats much of the reason why scopes exist in the first place. I believe it is perfectly acceptable to have that as a plugin if indeed you really need that functionality.

Also side effects in tests in general are undesirable, but I understand sometimes you just have to have them because of the system under testing.

I'm also 👎 on this.

**Comment by iwanb** [comment]
Ok, I am indeed using pytest with plenty of rather slow state changes to the system under test, which is not the regular use for pytest. The fixture system really fits well though, so I will implement this behaviour through a plugin.

Thank you for taking the time to review this !

**Comment by nicoddemus** [comment]
Thanks for the follow up @iwanb! Closing this then. 👍
