### ISSUE TITLE
test_py2_unicode in test_warnings is failing (PyPy2/Windows)

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2905]
It seems it is an issue or difference in implementation between CPython and PyPy2, I opened an issue: [pypy/pypy#2699](https://bitbucket.org/pypy/pypy/issues/2699/warningswarn-fails-with-non-ascii-unicode).

**Comment by nicoddemus** [comment]
Marked that test as `xfail` for PyPy2 5.9 on Windows in #2894.

**Comment by Zac-HD** [comment]
Fixed upstream in PyPy as of https://bitbucket.org/pypy/pypy/commits/bc4acc4caa28
