### ISSUE TITLE
pytest should be overriding the interpreter's default warnings filter

### ISSUE THREAD

**Issue by ncoghlan** [pytest-dev/pytest#2908]
When DeprecationWarning was hidden by default, the expectation was that 3rd party test runners would follow the `unittest` module's lead and re-enable them when running tests (see https://docs.python.org/3/whatsnew/2.7.html#changes-to-the-handling-of-deprecation-warnings and and https://docs.python.org/3/library/unittest.html#unittest.TextTestRunner)

This currently isn't the case for pytest - it requires developers to explicitly opt-in to seeing deprecation warnings, rather than requiring them to opt-out the way unittest does.

**Comment by merwok** [comment]
Would this be configurable?  I’m all for getting warnings for code in my app, but not looking forward to the avalanche of messages from third-party django libs.

**Comment by nicoddemus** [comment]
Thanks @ncoghlan for the feedback!

Our intention is to do that when we refactor the warnings system. We had a few discussions about this but I can't find them in the issue tracker right now, I will see if I can find them tomorrow.

**Comment by nicoddemus** [comment]
>  I’m all for getting warnings for code in my app, but not looking forward to the avalanche of messages from third-party django libs.

Currently warnings are already configurable by the [`filterwarnings` ini option](https://docs.pytest.org/en/latest/customize.html?highlight=filterwarnings#confval-filterwarnings). An user would be able to for example ignore every `DeprecationWarning` if so desires.

**Comment by ncoghlan** [comment]
@merwok The only assumption we made at the interpreter level was that *unconfigured* test runners would be updated to still report deprecation warnings by default.

Once a developer actually starts configuring the warnings settings for their test runner explicitly, I figure how that interacts with the default settings is a question entirely for the developers of the particular test runner.

**Comment by nicoddemus** [comment]
Relevant: https://www.python.org/dev/peps/pep-0565/#id14

**Comment by nicoddemus** [comment]
Closed by #3931
