### ISSUE TITLE
Duplicate of site in docs "Good Integration Practices"

### ISSUE THREAD

**Issue by Q-back** [pytest-dev/pytest#2915]
Hello.
Idk if it's a good place to post it, but I found, that your doc page seems to have duplicate, which is a bit confusing. This seems to be [duplicate](https://docs.pytest.org/en/2.7.3/goodpractises.html#goodpractises) of [original](https://docs.pytest.org/en/latest/goodpractices.html#goodpractices). Also [duplicate](https://docs.pytest.org/en/2.7.3/goodpractises.html#goodpractises) is available in v: 2.7.3 and not available in v: latest, while [original](https://docs.pytest.org/en/latest/goodpractices.html#goodpractices) is available in v: latest, but not in v: 2.7.3.
[duplicate]: https://docs.pytest.org/en/2.7.3/goodpractises.html#goodpractises
[original]: https://docs.pytest.org/en/latest/goodpractices.html#goodpractices

**Comment by The-Compiler** [comment]
The file was renamed in 99072ea8c9caf1fd7ae56296b9848787d1947074 due to a typo - so it makes sense it's available under the old name in an old version and under the new name in a new version :wink:
