### ISSUE TITLE
Option to choose which modules to doctest?

### ISSUE THREAD

**Issue by rogual** [pytest-dev/pytest#2918]
When using `--doctest-modules` it seems to try to import all the modules it can find, except for a special hardcoded exception for `setup.py`.

I have a project where a file `alembic/env.py` (required for Alembic, an SQL migration tool) also breaks when imported, but couldn't find how to exclude it from `--doctest-modules`. Is there a way?

For me it'd be ideal if you could just say `--doctest-modules=my_code_dir` and then it would only doctest stuff in that directory.

pytest v3.2.3, centos 7

**Comment by nicoddemus** [comment]
You can use the [`pytest_ignore_collect`](https://docs.pytest.org/en/latest/writing_plugins.html#_pytest.hookspec.pytest_ignore_collect) in your root `conftest.py` file (untested):

```python
def pytest_ignore_collect(path):
    if str(path) == 'alembic':
        return True
```

**Comment by rogual** [comment]
If I add a `pytest_ignore_collect` function, it seems to only be called with the paths of the tests themselves. But the doctests (and the problematic `alembic/env.py`) are in the code being tested, not the tests.

**Comment by rogual** [comment]
Ah OK, I need a `conftest.py` in my project root, not in my tests dir. This works. Thank you!
