### ISSUE TITLE
-p no:plugin not working

### ISSUE THREAD

**Issue by rpuntaie** [pytest-dev/pytest#2920]
OS: Windows 10
Python 3.6
Py.test 3.2.3

From the sources of `pytest`:

           group._addoption('-p', action="append", dest="plugins", default=[],
                     metavar="name",
                     help="early-load given plugin (multi-allowed). "
                     "To avoid loading of plugins, use the `no:` prefix, e.g. "
                     "`no:doctest`.")

My `conftest.py`  is

          pytest_plugins = "integration"

But 

          py.test test.py -p no:integration

does still include `integration`, which is in the same folder.

If I remove `conftest.py`, then `integration` is not included.
I would like to keep `conftest.py` and still by able to NOT include `integration` via command line.

Do I do something wrong or is this a bug?

**Comment by RonnyPfannschmidt** [comment]
off hand this seems to be an issue with early initialization, unfortunately i wont be able to investigate soon

**Comment by nicoddemus** [comment]
Yes, thanks @Sup3rGeo!
