### ISSUE TITLE
Assertion rewrite should match files completely and avoid rewriting setup.py

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#2939]
[Quoting](https://github.com/pypa/setuptools/issues/1170#issuecomment-346174810) @hroncok in pypa/setuptools#1170:

> * _pytest.config._mark_plugins_for_rewrite should not register setup when it sees setup.py
> * _pytest.assertion.rewrite._should_rewrite should probably match things that startswith mark + '.', not just mark (although I'm not very sure here)

**Comment by hroncok** [comment]
Ad _should_rewrite: when I think about it,  it should either be exact match or it should start with the thing plus dot.

**Comment by nicoddemus** [comment]
Heh exactly what I came up with. 😁 

I will open a PR shortly.

**Comment by nicoddemus** [comment]
```diff
diff --git a/_pytest/assertion/rewrite.py b/_pytest/assertion/rewrite.py
index d48b664..27026b0 100644
--- a/_pytest/assertion/rewrite.py
+++ b/_pytest/assertion/rewrite.py
@@ -168,7 +168,7 @@ class AssertionRewritingHook(object):
                 return True

         for marked in self._must_rewrite:
-            if name.startswith(marked):
+            if name == marked or name.startswith(marked + '.'):
                 state.trace("matched marked file %r (from %r)" % (name, marked))
                 return True
```

😉 

I'm finishing up the test.

**Comment by hroncok** [comment]
Note that blacklisting setup.py from _pytest.config._mark_plugins_for_rewrite is not needed anymore to fix this particular problem, but I'd still rather fo it,  because having it there  can bring other problems some day.

**Comment by nicoddemus** [comment]
Hmm not sure about `setup.py` now, I've seen code in the wild which used `setup.py`, although usually inside packages so this probably wouldn't be an issue. Let's see if others have an opinion on this.

**Comment by hroncok** [comment]
Ok, not blacklist ot, but reconsider the code that produces it as it's result for sdist installed packages. (I cannot reopen, not my issue)

**Comment by nicoddemus** [comment]
I see, it makes sense to ignore `setup.py` files that are available in the root of the metadata. Created #2941 for that. 👍
