### ISSUE TITLE
Error when importing module  pytest

### ISSUE THREAD

**Issue by arita37** [pytest-dev/pytest#2952]
pytest 3.2.5
When doing
     import py

I have this message :

python2.7/site-packages/_pytest/_code/code.py in <module>()
      7 builtin_repr = repr
      8
----> 9 reprlib = py.builtin._tryimport('repr', 'reprlib')
     10
     11 if sys.version_info[0] >= 3:

AttributeError: 'module' object has no attribute 'builtin'

**Comment by RonnyPfannschmidt** [comment]
closing as per pytest-dev/py#176
