### ISSUE TITLE
pytest 3.3.0 immutable fixture params

### ISSUE THREAD

**Issue by popravich** [pytest-dev/pytest#2959]
Before v3.3.0 it was possible to mutate fixture parameters, since v3.3.0 params gets "frozen"
(I guess its introduced with this commit 07b2b18a01a3ba12757a4eb1c0e082922f5299e5)

I was using this feature to setup fixture parameters based on command-line options:
```python
BINS = []

@pytest.fixture(scope='session', params=BINS, ids=...)
def server_bin(request):
    return request.param

@pytest.fixture(scope='session')
def run_server(server_bin):
    pass # start application

def pytest_configure(config):
    BINS[:] = config.getoption('--server')[:]
```
* Here is the real use case https://github.com/aio-libs/aioredis/blob/pyup/tests/conftest.py#L245-L254
* Here are the travis builds [before](https://travis-ci.org/aio-libs/aioredis/jobs/307971350#L685) and [after](https://travis-ci.org/aio-libs/aioredis/jobs/308313356#L699) update;

So my questions:
* Is this new behavior intended or its a bug?
* And if its intended what is new way to make dynamic parameters?

**Comment by popravich** [comment]
The same case is here https://github.com/aio-libs/aiohttp/blob/master/aiohttp/pytest_plugin.py#L195-L200

**Comment by RonnyPfannschmidt** [comment]
its neither intended, not was it a bug

we simply didn't fall over because users would mutate random aliased objects that would then end up in the internals

the correct way to make fixtures dynamic is something like this:

```
def pytest_configure(config):
  class DynamicFixturePlugin(object):
     @pytest.fixture(scope='session', params=config.getoption(
--servers'), ids=...)
     def server_bin(request):
        return request.param
    config.pluginmanager.register(DynamicFixturePlugin(), 'server-bin-fixture')
```

**Comment by popravich** [comment]
Ok, thanks, 
I will try it

**Comment by nicoddemus** [comment]
Do we still consider this `regression`?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus it practically is a regression, but its one i'd like to not fix since fixing it makes things worse in the internals again

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt I agree, doesn't seem like something we want to actually fix, at least not in its current form where it was working by accident rather than by design.

@popravich when you can please let us know if the workaround worked for you.

**Comment by nicoddemus** [comment]
@argaen and @popravich agree, thanks for the suggestion: #2980
