### ISSUE TITLE
How to test a function in a specified class?

### ISSUE THREAD

**Issue by livc** [pytest-dev/pytest#2972]
```python
class abc1():
    def test_abc():
        pass

class abc2():
    def test_abc():
        pass
```

if I run `pytest filename -k test_abc`, both function `test_abc` will be selected, so how to select a function in a specified class? Because I only want to select `test_abc` in `class abc2` to test.

Thanks.

**Comment by The-Compiler** [comment]
Changing the example so it actually works:

```python
class Test1():
    def test_abc(self):
        pass

class Test2():
    def test_abc(self):
        pass
```

You can then either use `-k Test1` to run all tests in that class, or use `-v` to get the IDs of the tests (optionally with `--collect-only`):

```
test_x.py::Test1::test_abc PASSED
test_x.py::Test2::test_abc PASSED
```

and then use `pytest test_x.py::Test1::test_abc`.

**Comment by livc** [comment]
Thanks for your reply.
