### ISSUE TITLE
Use pytest 3.2 output in v3.3?

### ISSUE THREAD

**Issue by Naatan** [pytest-dev/pytest#2978]
Version 3.3 appears to have changed the way results are printed. This breaks integration in Komodo IDE 11 which provides integration with pytest. Is there a way to have it output the same format as 3.2 used?

Of course the intend is to support the 3.3 output, I'm looking for an interim solution that could go out in a maintenance / bugfix release (no major changes).

Thanks!

**Comment by The-Compiler** [comment]
See [the changelog](https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#pytest-330-2017-11-23):

> Now pytest displays the total progress percentage while running tests. The previous output style can be set by configuring the `console_output_style` setting to `classic`.

**Comment by Naatan** [comment]
Can this be passed from the command line? We can't be updating users .ini files.

**Comment by nicoddemus** [comment]
Yes, you can use `-o console_output_style=classic` in the command line. 👍 

`-o` can be used to set any `ini` option directly in the command line.

**Comment by Naatan** [comment]
Thanks!
