### ISSUE TITLE
Typo in blog post of 3.3 release

### ISSUE THREAD

**Issue by gtr-fpr** [pytest-dev/pytest#2991]
I am not sure where to signal this so feel free to move this wherever it should be.

The example provided in the blog [article](http://blog.pytest.org/2017/whats-new-in-pytest-33/) of pytest.skip has a typo. The argument of _pytest.skip()_ is **msg** not **reason**.

wrong:
```pytest.skip(reason='this whole module is TODO', allow_module_level=True)```
correct:
```pytest.skip(msg='this whole module is TODO', allow_module_level=True)```

**Comment by nicoddemus** [comment]
Thanks @gtr-fpr for taking the time to point it out. The blog repository is at https://github.com/pytest-dev/blog.pytest.org.
