### ISSUE TITLE
trigger deprecation warning for py.test cli command

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2993]
we provide a dropthedot variant since a good while now, in order to support the transition we should trigger a deprecationwarning

**Comment by nicoddemus** [comment]
TBH I don't think we should deprecate/remove `py.test` at all, for the reason that it is not a maintenance burden for us (1 line of code), and removing it will break old scripts without a good reason.

IMHO we should deprecate/remove old implementations/APIs that are:

1. A maintenance burden for us;
2. Bad practices (`message` parameter of `pytest.raises`);
3. Confusing terminology (`getfuncargvalue` vs `getfixturevalue`).

It doesn't really matter if users use `py.test` in old scripts after all. We just recommend the new `pytest` command in the docs, and that's it.

Same goes for `yield_fixture` IMO.

What do you think?

**Comment by blueyed** [comment]
I agree with @nicoddemus.
`py.test` is still used a lot.

**Comment by Zac-HD** [comment]
Closing this as wontfix; while we all prefer the new form there's little to gain from deprecating the old.
