### ISSUE TITLE
PYTEST_DONT_REWRITE is not checked for plugins

### ISSUE THREAD

**Issue by anntzer** [pytest-dev/pytest#2995]
Adding PYTEST_DONT_REWRITE to the docstring of a test module suppresses assertion rewrites; however, this does not work for plugins.

Minimal (contrieved) example:
plugin.py
```
"""PYTEST_DONT_REWRITE"""
print("hello, world")
```
 run:
```
$ python -c 'import pytest, plugin; pytest.main()' -p plugin
hello, world
===================================== test session starts ======================================
platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0
rootdir: /tmp/foo, inifile:
collected 0 items                                                                              

======================================= warnings summary =======================================
None
  Module already imported so can not be re-written: plugin

-- Docs: http://doc.pytest.org/en/latest/warnings.html
================================== 1 warnings in 0.00 seconds ==================================
```

```
$ pip list
attrs (17.3.0)
pip (9.0.1)
pluggy (0.6.0)
py (1.5.2)
pytest (3.3.0)
setuptools (28.8.0)
six (1.11.0)
```

Python 3.6 on Arch Linux.

Alternatively, it may also be nice if the warning was only output if there actually is at least one assert in the unrewritable module (or if -O is on which may make that impossible to check, perhaps).

**Comment by nicoddemus** [comment]
> (or if -O is on which may make that impossible to check, perhaps).

Actually pytest already checks for that 😉 
https://github.com/pytest-dev/pytest/blob/964c29cb939d511d709b99dbf9f2134e0f787a2b/_pytest/config.py#L1045-L1060

**Comment by RonnyPfannschmidt** [comment]
the demo code explicitly imports the plugin before assertion rewriting, the warning is about not even trying (i.e. before we even check the docstring)

https://github.com/pytest-dev/pytest/blob/5c6d7739bcd7a1ea33eecff37bd2c2271cf5309c/_pytest/assertion/rewrite.py#L603 is responsible for the actual check on all modules

so the real issue here is that op triggers a warning that in that particular case could be left out since we wouldn't rewrite to begin with

**Comment by RonnyPfannschmidt** [comment]
i propose we ensure the warning triggers only for modules that dont have a dont rewrite tag

https://github.com/pytest-dev/pytest/blob/5c6d7739bcd7a1ea33eecff37bd2c2271cf5309c/_pytest/assertion/rewrite.py#L189-L192 is the code that would need a update, it should be a nice first conribution

@anntzer please verify if my hypothesis is correct

**Comment by nicoddemus** [comment]
> so the real issue here is that op triggers a warning that in that particular case could be left out since we wouldn't rewrite to begin with

IIUC, the `-p` flag is intended to force `plugin` to be imported as a plugin, so pytest would in that case attempt to rewrite asserts.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus thing is, the already imported module is marked as **dont rewrite** - so i beleive its fine to firego thatr warning in that case - in any case it wouldn't happen if the unneeded import was either left out, or the plug in was passed as plugin object to main

**Comment by nicoddemus** [comment]
Ahh true, thanks for the clarification

**Comment by anntzer** [comment]
I think something like the following patch should suffice:
```
diff --git a/_pytest/assertion/rewrite.py b/_pytest/assertion/rewrite.py
index 92deb653..110b189c 100644
--- a/_pytest/assertion/rewrite.py
+++ b/_pytest/assertion/rewrite.py
@@ -180,10 +180,10 @@ class AssertionRewritingHook(object):
         be rewritten on import.
         """
         already_imported = set(names).intersection(set(sys.modules))
-        if already_imported:
-            for name in already_imported:
-                if name not in self._rewritten_names:
-                    self._warn_already_imported(name)
+        for name in already_imported:
+            if (not self.is_rewrite_disabled(sys.modules[name].__doc__ or None)
+                    or name not in self._rewritten_names):
+                self._warn_already_imported(name)
         self._must_rewrite.update(names)
 
     def _warn_already_imported(self, name):
```

However I would appreciate help as to how to test this feature (do you have any helper for generating a fake module going into sys.modules, for example?).  Or feel free to just take over the patch yourself, either way works.

**Comment by nicoddemus** [comment]
@anntzer thanks for posting the patch.

I'm short on time right now so we would appreciate a PR if you have the time

Here's an example of test which uses the `testdir` fixture to generate a test and module file, run pytest against it and check the output:

https://github.com/pytest-dev/pytest/blob/5c6d7739bcd7a1ea33eecff37bd2c2271cf5309c/testing/test_assertion.py#L132-L148

You can use this test as basis, I believe if you add a docstring to the `ham` module marking it to skip rewrite and import it in `conftest.py` you will obtain the same result you posted. Then by making an assert like this:

```python
result = testdir.runpytest_subprocess('--assert=rewrite') 
assert 'Module already imported so can not be re-written: ham' not in result.stdout.str()
```

The test should fail without your patch and pass with it applied.

Let us know if you need further guidance. 👍
