### ISSUE TITLE
Update public api for getting finalizers

### ISSUE THREAD

**Issue by ProSerg** [pytest-dev/pytest#2999]
Hello!
Could you add method for getting finalizers? It is wrong to use a private members.  For example, It is necessary for such library as allure-pytest. [There is a issue](https://github.com/allure-framework/allure-python/issues/181)  

[allure-pytest/listener.py](https://github.com/ProSerg/allure-python/blob/master/allure-pytest/src/listener.py#L132)

Thanks!

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt any opinions here? I'm not so familiar with the finalizers/setupstate of the code, so I'm not sure if exposing the finalizers from a `request` objects is something we want to do.

**Comment by RonnyPfannschmidt** [comment]
exposing the finalizers them selfesis a no go - thats why im closing this issue

now for enabling allure there is a need for a discussion on the actual use-cases and goals

as far as i can tell what they want to do is hook into finalizers - ad thats something really tricky to expose well without handing a planet size footgun as well

from my pov this first needs a laid out use-case and a longer discussion on the ml/in person
