### ISSUE TITLE
RFE: add an option to run tests in batches

### ISSUE THREAD

**Issue by jonathanunderwood** [pytest-dev/pytest#3000]
- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

I have a pytest suite that uses fixtures extensively to run some functions with all combinations of options. The result is that pytest collects and runs something like 13,000 tests. Unfortunately, on Appveyor/Windows at least, this exhausts the system memory, and the tests fail. No large objects are created by the test themselves, it's simply that the pytest in-memory overhead of 13000+ tests is significant. It would be great to be able to tell pytest to step through these tests 1000 at a time or somesuch, such that the test suite will still run on memory constrained systems. Something like --batch-size=1000.

**Comment by RonnyPfannschmidt** [comment]
i beleive this is a topic for pytest-xdist

**Comment by jonathanunderwood** [comment]
> i beleive this is a topic for pytest-xdist

Possibly.. Without knowing the details of the implementation though, I think it may require changes to the test collection process in coore pytest. That's just a dumb guess though.

**Comment by nicoddemus** [comment]
@jonathanunderwood no worries. Please follow pytest-dev/pytest-xdist#255 which I believe is the same requirement (or closely related).
