### ISSUE TITLE
AttributeError: 'TerminalReporter' object has no attribute 'writer'

### ISSUE THREAD

**Issue by oviwankenobi** [pytest-dev/pytest#3002]
this is new, a week ago our code was working fine, now it is failing with below error:

line 39, in pytest_terminal_summary
    terminalreporter.writer.line(
AttributeError: 'TerminalReporter' object has no attribute 'writer'

I guess it is pretty clear where is failing and the error as well
question is, what happened with the writer member of the TerminalReporter?

**Comment by nicoddemus** [comment]
Hi @oviwankenobi, this was fixed in #2989 and will be released in `3.3.1`, which should come out today. 👍
