### ISSUE TITLE
Possible race-condition while writing bytecode when rewriting assertions

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#3008]
Since we started porting to Python 3, our builds on Windows fail sometimes, say 5-10% of the runs, in a bizarre and random manner:

```
___________ ERROR at setup of testMeshAssemblyPlaneControllerNoBBox ___________
[gw3] win32 -- Python 3.5.3 W:\Miniconda\envs\_sci20-win64g-py35\python.exe
file K:\etk\sci20\source\python\sci20\app\mesh_assembly\plane\_tests\test_mesh_assembly_plane_controller.py, line 83
  def testMeshAssemblyPlaneControllerNoBBox(almost_equal):
E       fixture 'py5' not found
```

Strangely the "name" being reported is always `py` and some digits, like `py2`, `py7` or `py44`.

This always happens when running with `xdist` and in a random test or `contest` file, which suggest that the assertion rewriting code might some bug in its locking code when writing the rewritten bytecode to the disk, corrupting it.

**Comment by nicoddemus** [comment]
Also, it seems it always changes an *identifier* to something else, rather than corrupting actual code.

**Comment by nicoddemus** [comment]
Hopefully fixed in #3390. Will re-open if I see this problem again in pytest>=3.6.

**Comment by maiksensi** [comment]
great job for debugging this. Can't actually :+1: enough!

**Comment by nicoddemus** [comment]
@maiksensi were you experiencing this as well?
