### ISSUE TITLE
Python 3.7 Nightly failures due to Python bug or travis

### ISSUE THREAD

**Issue by cryvate** [pytest-dev/pytest#3011]
[See for example this job.](https://travis-ci.org/pytest-dev/pytest/jobs/313008163) [They fail because of a bug in python introduced for 3.7.](https://bugs.python.org/issue31845)

The state of this bug is 'fixed' on the bugtracker. So I think there is two possible problems:
- travis "nightly" is not actually the head of the master branch of cpython
- this bug has reappeared
I tried to find out the answer to the former, but could not ascertain. The log says it is running ``3.7.0a0`` which is not [the latest ``3.7.0a3``](https://docs.python.org/3.7/whatsnew/3.7.html).

**Comment by nicoddemus** [comment]
Thanks @cryvate! 

Because of lack of time, I'm personally will start to really worry about 3.7 when it goes into beta. 😓
