### ISSUE TITLE
Remove support for strings to pytest.main

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#3085]
Deprecated in 3.1, related to #1727.

**Comment by feuillemorte** [comment]
I take it

**Comment by RonnyPfannschmidt** [comment]
@feuillemorte this one cant be done/merged unless we do a major release

**Comment by feuillemorte** [comment]
ok. then let me know when I can take it, please :)

**Comment by nicoddemus** [comment]
This is scheduled for `4.0` (see the Milestone link on the right panel), so this will need to wait a bit. 👍

**Comment by feuillemorte** [comment]
ok. then let me know when I can take it, please :)

**Comment by nicoddemus** [comment]
Will do thanks!
