### ISSUE TITLE
How can I use global variables through tests?

### ISSUE THREAD

**Issue by UANEMESIS** [pytest-dev/pytest#3118]
In my example:

```
@pytest.fixture
def global_var():
    pytest.global_variable_1 = 100

def test_1(global_var):
	pytest.global_variable_1 +=1
	print(pytest.global_variable_1)

def test_2(global_var):
	pytest.global_variable_1 +=1
	print(pytest.global_variable_1)

def test_3(global_var):
	pytest.global_variable_1 +=1
	print(pytest.global_variable_1)

```
Global variable pytest.global_variable works only in test_1. output:
101
101
101

What do I wrong in?

**Comment by RonnyPfannschmidt** [comment]
for each function you set it back to 100 in the setup, then increment it by 1

so its doing exactly what you told it to

**Comment by nicoddemus** [comment]
Every time a fixture is requested in a test (`def test_1(global_var)`) the fixture function will be called and the result will be passed as the parameter value: what's happening here is that because each test requires the global variable, `global_var` is being executed each time and resetting the value of `pytest.global_variable_1 ` to `100`.

Fixtures are meant to avoid using global variables in the first place, they are meant to provide *resources* to test functions that are isolated and particular for each test.

You can update your code as follows:

```python
import pytest
pytest.global_variable_1 = 100

def test_1():
	pytest.global_variable_1 +=1
	print(pytest.global_variable_1)

def test_2():
	pytest.global_variable_1 +=1
	print(pytest.global_variable_1)

def test_3():
	pytest.global_variable_1 +=1
	print(pytest.global_variable_1)
```

This will behave like you expect it to.

**Disclaimer**: using global variables in general (and in testing in particular) is generally a *bad idea*(tm); if you look it up you will find dozens of posts/articles explaining why this is bad in general.

**Comment by UANEMESIS** [comment]
Thank u!

**Comment by FelipeJung** [comment]
@nicoddemus I just ran into this problem and I have a question on the declarations of variables in pytest like this...
I'd like to know if, when you declare a global variable like this: 
`pytest.globalvariable = 0`
Would this variable be global to all session of tests or only for this module?

For example, if I am running several modules in a pytest session, can tests on other modules access this variable? And if they can, is there a way of making this variable global only for the module?

Thanks in advance!

**Comment by UANEMESIS** [comment]
> @nicoddemus I just ran into this problem and I have a question on the declarations of variables in pytest like this...
> I'd like to know if, when you declare a global variable like this:
> `pytest.globalvariable = 0`
> Would this variable be global to all session of tests or only for this module?
> 
> For example, if I am running several modules in a pytest session, can tests on other modules access this variable? And if they can, is there a way of making this variable global only for the module?
> 
> Thanks in advance!

For all session (for all tests in file)

**Comment by UANEMESIS** [comment]
> > > @nicoddemus I just ran into this problem and I have a question on the declarations of variables in pytest like this...
> > > I'd like to know if, when you declare a global variable like this:
> > > `pytest.globalvariable = 0`
> > > Would this variable be global to all session of tests or only for this module?
> > > For example, if I am running several modules in a pytest session, can tests on other modules access this variable? And if they can, is there a way of making this variable global only for the module?
> > > Thanks in advance!
> > 
> > 
> > For all session (for all tests in file)
> 
> Yeah, right... But what if my session is composed by several different files? Would every test in every file have access to that variable? Or only the tests on the file that I declared this variable have access to it?
> Thanks!

I think it will be applied for all .py file. But, not sure at 100%, just try and you will know^)

**Comment by amitkhomane** [comment]
>  the result will be passed as the parameter value: what's happening here is that because each test requires the global variable, `global_var` is being executed each time and resetting the value of `pyte`

``

> Every time a fixture is requested in a test (`def test_1(global_var)`) the fixture function will be called and the result will be passed as the parameter value: what's happening here is that because each test requires the global variable, `global_var` is being executed each time and resetting the value of `pytest.global_variable_1 ` to `100`.
> 
> Fixtures are meant to avoid using global variables in the first place, they are meant to provide _resources_ to test functions that are isolated and particular for each test.
> 
> You can update your code as follows:
> 
> ```python
> import pytest
> pytest.global_variable_1 = 100
> 
> def test_1():
> 	pytest.global_variable_1 +=1
> 	print(pytest.global_variable_1)
> 
> def test_2():
> 	pytest.global_variable_1 +=1
> 	print(pytest.global_variable_1)
> 
> def test_3():
> 	pytest.global_variable_1 +=1
> 	print(pytest.global_variable_1)
> ```
> 
> This will behave like you expect it to.
> 
> **Disclaimer**: using global variables in general (and in testing in particular) is generally a _bad idea_(tm); if you look it up you will find dozens of posts/articles explaining why this is bad in general.

This seems to be deprecated now, isn't it ? @RonnyPfannschmidt  @nicoddemus

**Comment by nicoddemus** [comment]
> I'd like to know if, when you declare a global variable like this:
pytest.globalvariable = 0
Would this variable be global to all session of tests or only for this module?

For the entire session, but there's nothing special about `pytest` here; it is just a Python module as any other. You will get the same effect if you set the same variable to `sys` or `os` for example (or any other module).

> This seems to be deprecated now, isn't it ? @RonnyPfannschmidt @nicoddemus

Not sure I understand the question, what do you mean by "this" in this context?
