### ISSUE TITLE
Pytest within zipped Python package

### ISSUE THREAD

**Issue by horta** [pytest-dev/pytest#3134]
Is there a recommended approach to test a zipped Python package using pytest?
From [calling-pytest-from-python-code](https://docs.pytest.org/en/latest/usage.html#calling-pytest-from-python-code) I came up with the following approach:

```
from os import chdir, getcwd
from os.path import abspath, basename, dirname, realpath

def test(verbose=True):
    r"""Run tests to verify this package's integrity.

    Parameters
    ----------
    verbose : bool
    ``True`` to show diagnostic. Defaults to ``True``.

    Returns
    -------
    int
    Exit code: ``0`` for success.
    """

    pkgname = basename(dirname(realpath(__file__)))

    p = __import__(pkgname).__path__[0]
    src_path = abspath(p)
    old_path = getcwd()
    chdir(src_path)

    try:
        return_code = __import__('pytest').main(
            ['--doctest-modules', '-x', '--pep8'])
    finally:
        chdir(old_path)

    return return_code

```

The problem is that it does not work for installed, zipped package.

**Comment by nicoddemus** [comment]
Hi @horta,

I think it will work if the zipped module is in the PYTHONPATH and you use the `--pyargs` to pass the full qualified package name of the test modules.

**Comment by horta** [comment]
Hi @nicoddemus Thanks for the answer =)
It worked using that approach with zipped installation. I will soon post the recipe I'm using.

Interestingly, it does not work when I install a package from the project folder via "python setup.py install" but that might be a setuptools problem....

**Comment by nicoddemus** [comment]
> Interestingly, it does not work when I install a package from the project folder via "python setup.py install" but that might be a setuptools problem....

Strange. Can you import the project package using Python? For example `python -c "import app.tests.test_foo"`?

**Comment by horta** [comment]
Here are the tests I did: https://asciinema.org/a/WOUQFQU5pjxuKcNg3mCVHXqjv

**Comment by horta** [comment]
Recipe

```
def test(verbose=True):
    r"""Run tests to verify this package's integrity.

    Parameters
    ----------
    verbose : bool
        ``True`` to show diagnostic. Defaults to ``True``.

    Returns
    -------
    int
        Exit code: ``0`` for success.
    """

    args = ['--doctest-modules', '-x', '--pep8']
    if not verbose:
        args += ['--quiet']

    args += ['--pyargs', __name__.split('.')[0]]

    return __import__('pytest').main(args)

```

**Comment by nicoddemus** [comment]
@horta it seems `python setup.py install` is installing an `egg` file (at `1:16`). 

Please try installing with:

```
python setup.py install --single-version-externally-managed
```

instead.

**Comment by nicoddemus** [comment]
Actually I believe the recommended command nowadays is:

```
pip install .
```

Which will also do the "correct" thing.

**Comment by horta** [comment]
It works by doing 

```
python setup.py install --single-version-externally-managed --record record.txt
```

**Comment by nicoddemus** [comment]
OK @horta thanks for confirming.

I believe the `egg` format is deprecated so we don't plan to support it on pytest (I couldn't find any references on the web about this though, @RonnyPfannschmidt might be able to shed some light here).
