### ISSUE TITLE
Include the name "pytest" somewhere in the cache directory name

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#3138]
As commented by @nedbat on [twitter](https://twitter.com/nedbat/status/955080497000013824):

> I am unreasonably annoyed that pytest writes a JSON file to “.cache/v/cache/lastfailed”. Why no “pytest” in the directory? Why “cache” twice? What is “v”? Why no file extension?

People in that thread agreed with the sentiment.

**Comment by alanbato** [comment]
Hey! I'll try to take this on if you don't mind :)

**Comment by nicoddemus** [comment]
Awesome. I took a quick look at the code and keeping backward compatibility might be too tricky; if it proves itself too complicated don't mind about it, the cache is supposed to be data that might get lost eventually anyway.

**Comment by brianmaissy** [comment]
Awesome idea! +1

**Comment by nicoddemus** [comment]
Fixed by #3150

**Comment by asottile** [comment]
A bit unfortunate that I have to run around to every repository and `s/\.cache/.pytest_cache/g` in `.gitignore` due to this change.

I've at least automated this for repos I own using [all-repos](https://github.com/asottile/all-repos)

I used the following command:

```
all-repos-sed 's/\.cache/.pytest_cache/g' .gitignore --commit-msg 'Change ignored cache dir for pytest 3.4.0'
```

**Comment by nicoddemus** [comment]
Nice work on `all-repos`, I will be definitely giving it a go sometime soon. 👍
