### ISSUE TITLE
Question: is there any way to get durations of fixtures using a pytest hook

### ISSUE THREAD

**Issue by mikeage** [pytest-dev/pytest#3154]
Like it says in the title :)

I can measure the time in the actual test using
```python
def pytest_runtest_logreport(report):
    if report.when == "call":
        print report['duration']
```
And I can get the entire setup time by checking `report.when == 'setup'` and `teardown`. But this represents all the fixtures that ran, which is (a) not granular enough for my purposes and (b) not accurate if I want to calculate how long a test with a session, class, or module scoped fixture would run if it had to run alone (i.e., if it actually ran all of its fixtures, as opposed to having them run on another test in the same scope).

Is there another hook I can use to get this information? I've seen `pytest_fixture_setup()` and `pytest_fixture_post_finalizer()`, but this is before the test starts and after it finishes and includes other fixtures, so it seems like it might be a bit complicated to extract just the time the fixture in question ran (both during setup and a finalizer, if present)

**Comment by RonnyPfannschmidt** [comment]
there is no reporting yet for fixtures, you can put a hookwrapper around the `pytest_fixture_setup()` hook for now

**Comment by mikeage** [comment]
Thanks. Maybe I'm missing something, but how would I use pytest_fixture_setup() to know when the fixture finishes? Will the next (significant) event be pytest_fixture_setup() again and/or pytest_runtest_logreport with when=setup? [I don't need perfect precision; +/- 100ms would be far more than enough, and even +/- 1 second wouldn't be too bad.]

Any suggestions for capturing the timings of the finalizers? Same thing, starting from the test finish until each call to pytest_fixture_post_finalizer()? Is there a better way to know when the fixture finalizers start?

Thanks

**Comment by RonnyPfannschmidt** [comment]
@mikeage by using a hookwrapper you can track the time from between and after the yield to run the rest of the hooks - its not as accurate as desired, but the most accurate you can get right now

**Comment by mikeage** [comment]
Gotcha... thank you!

**Comment by mikeage** [comment]
For future reference, if anyone else finds this, this code worked perfectly:
```python
@pytest.hookimpl(hookwrapper=True)
def pytest_fixture_setup(fixturedef, request):
    start = time.time()
    yield
    total = time.time() - start
    # Do something with total

```

**Comment by RonnyPfannschmidt** [comment]
thanks for providing this example, its extremely helpful for others facing the same problem

**Comment by Mathanraj-Sharma** [comment]
> For future reference, if anyone else finds this, this code worked perfectly:
> 
> ```python
> @pytest.hookimpl(hookwrapper=True)
> def pytest_fixture_setup(fixturedef, request):
>     start = time.time()
>     yield
>     total = time.time() - start
>     # Do something with total
> ```

@mikeage thanks for the example it works perfectly, but it is not working with session-level fixtures, do you know why??

**Comment by mikeage** [comment]
Sorry, I haven't been writing tests in python (i.e., pytest) for a few years now. I'm afraid I can't help.
