### ISSUE TITLE
Parameterized test with a bytes value raises an exception on teardown

### ISSUE THREAD

**Issue by thedrow** [pytest-dev/pytest#3157]
The bug happens on Python 3.6. I'm using pytest 3.3.0.
You can see the traceback [here](https://travis-ci.org/python-odin/odin/jobs/334040755#L621).

I'm not able to reproduce this bug locally, probably due to a locale setting difference between my computer and Travis-CI.

The bug happens when a parameterized tests uses a bytes sequence as a parameter.

This is not a severe bug since adding an ids argument renames the tests.

**Comment by RonnyPfannschmidt** [comment]
#2583 introduced it and fixed in #2957

**Comment by nicoddemus** [comment]
@thedrow please update pytest and let us know if you still have this problem
