### ISSUE TITLE
How to return from hookwrapper in python < 3.3

### ISSUE THREAD

**Issue by fruch** [pytest-dev/pytest#3169]
I have a warning that ___multicall__ is deprecated, so I have to change the code I have
``` python
@pytest.hookimpl(tryfirst=True)
def pytest_runtest_makereport(___multicall__):
    # Execute all other hooks to obtain the report object.
    rep = ___multicall__.execute()
    if rep.failed:
            # my logic to figure out I want to xfail
            if 'decided I want to xfail':
                TestApi.add_analysis('socket hang up')
                setattr(rep, "outcome", "skipped")
                setattr(rep, "wasxfail", 'socket hang up')
                return rep
    return rep
```
to this code:

```python
@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport():
    # Execute all other hooks to obtain the report object.
    outcome = yield
    rep = outcome.get_result()
    if rep.failed:
            # my logic to figure out I want to xfail
            if 'decided I want to xfail':
                TestApi.add_analysis('socket hang up')
                setattr(rep, "outcome", "skipped")
                setattr(rep, "wasxfail", 'socket hang up')
                return rep
    return rep
```

problem python < 3.3 doesn't support returning from a generator, so how am I supposued to return a modified result ? 
changing the object in-place would be enough ?

**Comment by fruch** [comment]
after looking at `skipping.py` seem like changing in place does work.

but that's the way to return anything in python < 3.3

**Comment by nicoddemus** [comment]
@fruch use [`outcome.force_result`](http://pluggy.readthedocs.io/en/latest/api_reference.html#pluggy.callers._Result.force_result) when changing in-place is not feasible/desired.

**Comment by fruch** [comment]
can you point to example of this api ?

**Comment by nicoddemus** [comment]
Sure, here: http://pluggy.readthedocs.io/en/latest/#wrappers

I'm opening a PR to add this to pytest's docs too.

**Comment by nicoddemus** [comment]
Opened #3177, please take a look.

**Comment by fruch** [comment]
I'm happy now, closing...
