### ISSUE TITLE
Pytest internal error with last release on travis

### ISSUE THREAD

**Issue by Natim** [pytest-dev/pytest#3173]
With py.test 3.4 NoneType has no attribute testcollected.

- https://travis-ci.org/Kinto/kinto/jobs/335549257
- https://travis-ci.org/mozilla/PollBot/jobs/335527508

```
INTERNALERROR>   File "/home/travis/build/mozilla/PollBot/.tox/py35/lib/python3.5/site-packages/_pytest/terminal.py", line 315, in pytest_runtest_logfinish
INTERNALERROR>     last_item = len(self._progress_nodeids_reported) == self._session.testscollected
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'testscollected'
```

**Comment by Natim** [comment]
Same issue with circle-ci: https://circleci.com/gh/mozilla/PollBot/411

**Comment by nicoddemus** [comment]
It seems you are using `pytest-sugar` correct? If so this is a duplicate of #3170.

**Comment by Natim** [comment]
Yes it is thanks.

Refs https://github.com/Frozenball/pytest-sugar/pull/133
