### ISSUE TITLE
tmpdir is magic, contrary to "explicit is better than implicit"

### ISSUE THREAD

**Issue by basak** [pytest-dev/pytest#3178]
I was surprised to find the name `tmpdir` had magic behaviour even though I never imported that name into my namespace. This is contrary to everything else in Python, where names are always explicitly brought into to the namespace by the developer using an `import` statement, or are otherwise qualified by being accessed through such a name. I'd go as far as to claim that this magic behaviour is non-Pythonic and thus inappropriate in a Python library.

IMHO, the name `tmpdir` should have no magic behaviour unless the developer explicitly requests it using `from pytest import tmpdir` or similar. I can already do this kind of import with other fixtures, for example from my project-wide fixture library; `tmpdir` (and `tmpdir_factory`) should be no different.

An example of how this tripped me up: not originally knowing about the `tmpdir` special fixture, I defined my own, and happened to call it `tmpdir` (honestly, this really happened!). Later, during some refactoring, I accidentally dropped the definition of this fixture. I started getting some really odd test failures because `tmpdir` suddenly became a fixture returning an object of type `py.path.local`, which I also didn't know about, and has some different behaviour from the `str` my custom fixture returned. This was very confusing to debug; particularly because, as a Python developer, I expected names to only be defined when explicitly imported like everything else in Python. There is no trail to find why `tmpdir` behaves differently when working from this failure case.

This is obviously a subjective design decision, and to change it you'd have to deprecate the previous behaviour and only break it on a major version bump.

**Comment by nicoddemus** [comment]
Hi @basak, thanks for writing.

> I was surprised to find the name tmpdir had magic behaviour even though I never imported that name into my namespace.

Actually this behavior is not specific to `tmpdir`, but any pytest fixture. pytest automatically creates and injects fixtures in test functions based on the parameter names of those functions, you can read more about it [in the docs](https://docs.pytest.org/en/latest/fixture.html).

While it might seem magical at first, it is restricted only to test functions and one gets used to it very quickly and then it feels natural and very straightforward, after all the test functions are called by the framework, not by the user.

> An example of how this tripped me up...

Indeed fixtures can be overwritten by user code, which has its uses as well as disadvantages, but the same can be said about any kind of override done by the user IMHO. To use an example closer to our topic, one can override `assertEqual` of `unittest.TestCase` without knowing about the original function and run into the same kind of problems. 

> This is obviously a subjective design decision, and to change it you'd have to deprecate the previous behaviour and only break it on a major version bump.

Fixtures being injected into test functions is one of the core pytest features and a very liked feature, so I don't think this will ever be changed to be honest. 😁

**Comment by basak** [comment]
Thank you for the fast response.

On Thu, Feb 01, 2018 at 04:16:38AM -0800, Bruno Oliveira wrote:
> > I was surprised to find the name tmpdir had magic behaviour even though I never imported that name into my namespace.
> 
> Actually this behavior is not specific to `tmpdir`, but any pytest fixture. pytest automatically creates and injects fixtures in test functions based on the parameter names of those functions, you can read more about it [in the docs](https://docs.pytest.org/en/latest/fixture.html).
> 
> While it might seem magical at first, it is restricted only to test functions and one gets used to it very quickly and then it feels natural and very straightforward, after all the test functions are called by the framework, not by the user.

I really like this fixture mechanism in py.test. It's not the fixture
mechanism itself that I'm calling magical. It's the way that fixtures
are namespaced. I'm not suggesting changing the fixture feature itself;
only the way that fixtures references are found in terms of namespacing.

I think the relevant documentation is: "You don’t need to import the
fixture you want to use in a test, it automatically gets discovered by
pytest. The discovery of fixture functions starts at test classes, then
test modules, then conftest.py files and finally builtin and third party
plugins."

What I'm proposing is that discovery of fixture functions should be
strictly limited to looking in the same scope as where the test is
defined, which is what I'd expect from a Pythonic perspective. So I'd
exclude "finally builtin and third party plugins" from your definition
above, but that'd be the only change in behaviour I think.

> > An example of how this tripped me up...
> 
> Indeed fixtures can be overwritten by user code, which has its uses as well as disadvantages, but the same can be said about any kind of override done by the user IMHO. To use an example closer to our topic, one can override `assertEqual` of `unittest.TestCase` without knowing about the original function and run into the same kind of problems. 

Sure, they can be overwritten by user code. This itself isn't my
concern. In your example, the difference is that a programmer knows that
by inheriting from unittest.TestCase it is necessary to consider the
definition of that class when following how a method lookup is resolved.
That's just standard OOP and standard Python, rather than magic
behaviour added by a library.

Something that remains true everywhere else in Python today is that,
barring the use of `from X import *`, a Python programmer new to a
particular module can follow every behaviour in that module because
every single name used in that module is explicitly defined or imported.
The beginning of a trail exists to understand the behaviour of all code
in the module in its entirety with only an understanding of the language
and no required knowledge of any libraries.

> > This is obviously a subjective design decision, and to change it you'd have to deprecate the previous behaviour and only break it on a major version bump.
> 
> Fixtures being injected into test functions is one of the core pytest features and a very liked feature, so I don't think this will ever be changed to be honest. 😁 

I don't see how what I'm suggesting would change the mechanism of
fixtures being injected into test functions. The feature wouldn't
change; it'd just be the namespace use that'd be cleaned up and
formalised.

It would be a behaviour change, but the use of the fixture feature
wouldn't change. Developers would simply need to explicitly declare
`from pytest.fixtures import tmpdir` when `tmpdir` is being used; that's
all.

The behaviour of `conftest.py` could remain the same, as developers
using `conftest.py` have explicitly written that file to request a
specific behaviour, and explicit is fine.

As it stands, you're effectively injecting
`from pytest.fixtures import *` into every module when running tests. I
think this is wrong for the same reason that any `from X import *` is
generally frowned upon in Python.

It's your decision, but I'd first like to make sure you understand
exactly what I'm suggesting. If you think that I'd be destroying the
fixture feature, I don't think I've communicated what I mean well
enough.

**Comment by nicoddemus** [comment]
> It's your decision, but I'd first like to make sure you understand
exactly what I'm suggesting. 

Oh now it is clear, thanks for the clarification. 

Perhaps you can write a new issue with a more former proposal? From the title and the discussion it is hard to grasp what the actual underlying proposal is.

FWIW I'm 👎 on the idea so far, but by all means we can open this for discussion.

**Comment by The-Compiler** [comment]
Note that there's not actually anything injected into a Python namespace here. As far as Python is concerned, there's simply a function being called with an argument.

If you'd want the normal Python import semantics here, there are two solutions:

- Add some more magic to imitate the Python semantics. From a Python perspective, you now have an unused import and an argument shadowing that import, and many linters will (rightly) complain about that.

- Add more boilerplate, something like:

```python
from pytest import fixtures

@pytest.inject(tmpdir=fixtures.tmpdir)
def test_foo(tmpdir):
```

which is IMHO just too much boilerplate. I (and other pytest developers, I think) have thought about this in detail, and so far everyone came to the conclusion that having argument names to "select" a fixture takes a bit of getting used to, but is still by far the best solution. Either way, you said you aren't proposing to go that route.

Like I said above, I think this is mainly more magic and making things *more* confusing, because as a Python programmer I don't expect argument names (which is what fixtures are) to be namespaced in some way.

**Comment by basak** [comment]
On Fri, Feb 02, 2018 at 08:22:14AM +0000, Florian Bruhin wrote:
> Note that there's not actually anything injected into a Python
> namespace here. As far as Python is concerned, there's simply a
> function being called with an argument.

Agreed.

> If you'd want the normal Python import semantics here, there are two solutions:
> 
> - Add some more magic to imitate the Python semantics. From a Python perspective, you now have an unused import and an argument shadowing that import, and many linters will (rightly) complain about that.

That magic would be in the implementation in pytest though. I think that
from a pytest user's perspective, it would be less magical.

It would indeed be an unused import and an argument shadowing that
import in the case of Python interpreting a module as-is, instead of via
pytest. This would most likely be in the case where tests are integrated
in the same module as the code being tested.

This isn't fundamentally any different, though, from a fixture defined
in the same module in which it is being used. In this case, the fixture
function itself remains "unused" in the same way that you say an import
would be unused. Perhaps a linter won't complain about that by default
because it assumes it is a function being intended for export. From a
Python perspective, however, this is fundamentally no different to an
_import_ existing just to export the name. It is only different in what
linters may assume.

While you may now have an unused import, the fact that you have an
unused _binding_ remains the same.

> - Add more boilerplate, something like:
> 
> ```python
> from pytest import fixtures
> 
> @pytest.inject(tmpdir=fixtures.tmpdir)
> def test_foo(tmpdir):
> ```
> 
> which is IMHO just too much boilerplate. I (and other pytest developers, I think) have thought about this in detail, and so far everyone came to the conclusion that having argument names to "select" a fixture takes a bit of getting used to, but is still by far the best solution. Either way, you said you aren't proposing to go that route.

Yeah. I agree this would be too inconvenient.

> Like I said above, I think this is mainly more magic and making things *more* confusing, because as a Python programmer I don't expect argument names (which is what fixtures are) to be namespaced in some way.

Fixtures are *not* argument names. The more Pythonic way of looking at
this is that a fixture "constructor" is an object (a callable) bound to
a name, just like any other Python object. This is what a Python
programmer expects (IMHO) and is the core of my argument. This is
consistent with the syntax that pytest uses today: we decorate the
fixture (@pytest.fixture), not its use. No magic yet.

When a test is collected (or run; not sure about pytest internals), the
test function's arguments are _mapped_ to fixture constructors, which
are called (as is needed subject to pytest's scoping and caching), and
the fixture instances that result are passed in via arguments as usual.
This is still not magical.

The only magic is that to determine the mapping, the function's argument
name is used as a key to find the fixture constructor. This could be
surprising to some, which is why it's magic. The scope (or scopes) in
which to search for the fixture constructor to use isn't defined by
Python as a consequence of this magic behaviour.

Let's say that you are a Python developer not familiar with the pytest
docs, but you do understand the basic concept of how pytest fixtures
work. You understand that because of the way Python works, the scope in
which to search for the fixture constructor isn't defined by Python. You
assume that surely it must be defined by pytest. What would be your best
guess as to how pytest defines it?

I think it's reasonable to expect the scope used to be exactly the scope
in which the function is defined, and nothing more. You perhaps disagree
and think that the scope should be...something else that includes
defaults that the programmer hasn't explicitly requested.

Put another way, I think there are two "magics" here:

 1. The magic that the argument name is used as a key.

 2. The magic that the scope _isn't_ the scope in which the function is
    defined.

We both agree on 1 I think. My claim is that 2 is an unnecessary extra
piece of magic, and that if you were to follow my suggestion, the total
amount of magic would be reduced.

As an aside, I wonder if function annotations could help rid us of all
of the magic. Then you wouldn't need an additional decorator:

    from pytest.fixtures import tmpdir
    def test_foo(foo: tmpdir):
        ...

Whether you were to adopt this or not, consider what the scoping rules
here would be. They'd follow what I'm requesting precisely. And this is
why I'm arguing that the current behaviour is surprising and should be
changed.

**Comment by The-Compiler** [comment]
I like the idea with the annotations. It could even be supported in a backwards-compatible way, by leaving fixture injection as it is, but using namespaced Python objects where there is an annotation.

In addition, if done carefully those can actually be valid type annotations for IDEs and things like mypy. It won't be available for legacy Python 2, but that seems fine to me.

As @nicoddemus suggested, can you please open a new issue with that?

**Comment by basak** [comment]
On Sat, Feb 03, 2018 at 02:14:58AM -0800, Florian Bruhin wrote:
> As @nicoddemus suggested, can you please open a new issue with that?

Sure, but what should the new issue title be, and which part of the
discussion here should it cover?

**Comment by RonnyPfannschmidt** [comment]
"investigation and implementation of annotation supported fixture lookup/creation/parameterization"
off hand its not clear how to use it in detail, since recent peps restricted annotations, and keep restricting them even more (ultimately stored annotations will be unevaluated strings in upcoming python versions"

**Comment by nicoddemus** [comment]
Closing this for now as I think we've concluded the discussion here.
