### ISSUE TITLE
Interactive pytest in REPL

### ISSUE THREAD

**Issue by jbrockmendel** [pytest-dev/pytest#3182]
pytest's code-rewriting introduces a wedge between the test code I write and the test code that runs.  It would be helpful to be able to see the intermediate representation.  I'm imagining something like:

```
>>> suite = pytest.collect(dirname, **kwargs)
>>> dir(suite)
[... information that helps me grok whats going on ...]
```

A motivating example is an attempt to implement something similar to [this](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/indexing/test_coercion.py#L18):

```
@pytest.fixture(autouse=True, scope='class')
def check_comprehensiveness(request):
    # Iterate over combination of dtype, method and klass
    # and ensure that each are contained within a collected test
    cls = request.cls
    combos = itertools.product(cls.klasses, cls.dtypes, [cls.method])

    def has_test(combo):
        klass, dtype, method = combo
        cls_funcs = request.node.session.items
        return any(klass in x.name and dtype in x.name and
                   method in x.name for x in cls_funcs)

    for combo in combos:
        if not has_test(combo):
            msg = 'test method is not defined: {0}, {1}'
            raise AssertionError(msg.format(type(cls), combo))

    yield
``` 

I don't know off the top of my head what type `request` is, where it is instantiated, what attributes it has... I would never guess on my own to look at `request.node.session.items`... I can look through the pytest code, but I need to be able to see what is actually running in order to know where to look in the code.

**Comment by The-Compiler** [comment]
The only thing pytest rewrites is `assert` statements. You seem to talking about things like fixtures though, which are unrelated to any rewriting. You can however invoke a debugger (e.g. via `import pdb; pdb.set_trace()`) inside a test and explore things (or read the [docs](https://docs.pytest.org/en/latest/fixture.html#request-context)).

**Comment by The-Compiler** [comment]
Closing this as I don't think it's actionable in any way. Note that there's [reference documentation](https://docs.pytest.org/en/latest/reference.html) since some days.

**Comment by jbrockmendel** [comment]
Sounds good, thanks for taking a look.  FWIW pytest is growing on me as I get up the learning curve (though I still wish there were a way to interactively run the collection step and "look at" the results)

**Comment by nicoddemus** [comment]
Also it might be worth to take a look at https://pypi.python.org/pypi/pytest-ast-back-to-python
