### ISSUE TITLE
Live logger error before 'when' is set

### ISSUE THREAD

**Issue by uSpike** [pytest-dev/pytest#3184]
Hi,

The live logger `_LiveLoggingStreamHandler` will emit messages in `emit()`:

```
self.stream.section('live log ' + self._when, sep='-', bold=True)
```

If `self._when` is `None`, which may be the case before a test is actually started, this will raise an exception:

```
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I ran into this issue with a plugin I created which emits log messages before the first test starts.  It's a pretty simple fix which I'm fine creating a PR for, but what should the text be if `self._when` is `None`?

**Comment by nicoddemus** [comment]
Hi @uSpike, thanks for the report. I believe #3175, already fixes this though, can you give that branch a try?

**Comment by uSpike** [comment]
@nicoddemus it does seem that #3175 fixes the issue, thanks for linking me to that.

**Comment by nicoddemus** [comment]
Thanks, but lets keep this open because we don't have an issue to track this bug anyway. 👍

**Comment by s0undt3ch** [comment]
https://github.com/pytest-dev/pytest/pull/3188
