### ISSUE TITLE
multiple configure hooks in one conftest file

### ISSUE THREAD

**Issue by Drew-Ack** [pytest-dev/pytest#3195]
From looking in the documentation for the pytest_configure(config) hook it seems I should be able to implement multiple of these hooks inside on conftest.py file for my entire project, but in practice this doesn't seem to be the case. 

I was wanting multiple so that it was just easier to separate different components that need to be in the configure hook but its starting to get pretty large. 

Would it be better to seperate the chunks of code out into functions so that way the hook isn't so large?

**Comment by nicoddemus** [comment]
> From looking in the documentation for the pytest_configure(config) hook it seems I should be able to implement multiple of these hooks inside on conftest.py file for my entire project, but in practice this doesn't seem to be the case.

Given that pytest identifies hooks by their name this is not really possible (as you pointed it out).

> Would it be better to seperate the chunks of code out into functions so that way the hook isn't so large?

That would be my suggestion. 👍

**Comment by Drew-Ack** [comment]
So if hooks are pulled in by name, does it only collect one per conftest file? Im assuming this is the behaviour from what i've gathered from the test docs and plugins. 

Is this purposeful behaviour so that things won't get out of control in some conftest files?

**Comment by nicoddemus** [comment]
> Is this purposeful behaviour so that things won't get out of control in some conftest files?

This is how Python works, if you define two functions with the same name:

```python

def foo():
    return 1

def foo():
    return 200
```

Only the last definition will end-up available in the module.

**Comment by Drew-Ack** [comment]
*Facedesk* 
Thank you
