### ISSUE TITLE
How to parameterize the entire test suite?

### ISSUE THREAD

**Issue by Drew-Ack** [pytest-dev/pytest#3196]
I want to be able to have pytest run the test suite in firefox, then chrome, then IE. All in one swoop. 

I know its possible to parameterize test functions, but i'm not sure if this is possible to do on a test suite level. 

Is this possible to do in pytests scope?

**Comment by nicoddemus** [comment]
> I want to be able to have pytest run the test suite in firefox, then chrome, then IE. All in one swoop.

Usually this is done by parametrizing a fixture which is used by some/all your tests, for example:

```
@pytest.fixture(params=['firefox', 'chrome', 'IE']
def browser(request):
    return request.param
```

Now every test which requests `browser` will be executed multiple times, once for each parameter.

**Comment by Drew-Ack** [comment]
Wouldnt this cause a staggered behaviour though?

Test A - Firefox
Test A - Chrome
Test A - IE

Instead of what i want which is
Test A - FireFox
Test B - Firefox
Test C - Firefox

Test A - Chrome...
and so on.

**Comment by nicoddemus** [comment]
pytest will automatically reorder session-scoped fixtures to avoid creating/destroying them too much, so it will execute in the order you want. 😁

**Comment by nicoddemus** [comment]
I'm closing this for now @Drew-Ack, but feel free to post further question.

**Comment by sjpotter** [comment]
is it possible to make it work with dependencies, where you depend on the depency called with the same fixture value.

currently we depend on function name, but that breaks, as the fixture value becomes part of the signature.

**Comment by The-Compiler** [comment]
@sjpotter Using the same fixture multiple times during a test will give you the same (cached) value. I don't really follow though, do you have an example?

**Comment by sjpotter** [comment]
something like this (though this isn't quite)

```python
@pytest.fixture(scope="session", params=[False, True])
def tags(request):
    return request.param


class TestTestyMcTester
    @pytest.mark.dependency()
    def test_create_database(self, tags):
         ....

     @pytest.mark.dependency(depends=["TestTestyMcTester::test_create_database"])
     def test_database_services(self, tags):
     ....
```

perhaps not the best way to do it, but until I removed the depends lines, it is skipping all those tests as they don't match (I think) because the fixture changes the signature.

when I remove them, the tests run as I expect (i.e. test_create_database(False) -> test_database_service(Fales) -> test_create_database(True) -> test_database_service(True), but would prefer that dependency handling was still there (i.e. all my test functions with proper dependencies)

**Comment by The-Compiler** [comment]
I guess whatever `pytest.mark.dependency` is depends on the so-called "node id", which indeed changes when parametrized. That's something which would need to be changed in whatever project implements `@pytest.mark.dependency`, though.

**Comment by sjpotter** [comment]
ah, ok, I thought it was part of core pytest, apparently it isn't, hence when figuring out how to do it, found this.  will investigate
