### ISSUE TITLE
Ignore individual tests

### ISSUE THREAD

**Issue by uSpike** [pytest-dev/pytest#3198]
It would be useful for my workflow to be able to ignore specific tests while still collecting an entire directory.

For example, I have:

```
tests/
    test_a.py # contains test_foo(), test_bar()
    test_b.py # contains test_baz(), test_buz()
```

I can currently use `--ignore` to ignore an entire file, but not a specific test.  If I want to run every test except for `test_a.py::test_foo` I will have a very long command line.

I propose to accept test ids with `--ignore`:

```
$ pytest tests --ignore tests/test_a.py::test_foo
$ pytest tests --ignore tests/test_a.py::test_foo[param]
```

Thoughts?  I'd be glad to submit a PR.

**Comment by nicoddemus** [comment]
Seems useful at first sight. Feel free to submit a PR. 👍

**Comment by uSpike** [comment]
I submitted #3201 with a different implementation than I proposed.  I opted to add `--deselect [node_prefix]` which would deselect tests during collection.  I came to the conclusion that `--ignore` is too tied to paths to be extended for individual tests.  What I wanted to implement was a way to ignore individual nodeids, and other options like `-k` didn't quite fit the bill.

**Comment by Hi-Angel** [comment]
FTR, I figured there's a more convenient way to ignore tests, which supports a pattern match, that is `-k "not test_foo"`
