### ISSUE TITLE
Testreport.keywords is a dict with constant values

### ISSUE THREAD

**Issue by numirias** [pytest-dev/pytest#3200]
[`TestReport.keywords`](https://github.com/pytest-dev/pytest/blob/c04e248de54741b39f93d4ad07bd81e6bc6a2b3e/_pytest/runner.py#L330) is documented as:

> a name -> value dictionary containing all keywords and markers associated with a test invocation.

But looking at [the source](https://github.com/pytest-dev/pytest/blob/c04e248de54741b39f93d4ad07bd81e6bc6a2b3e/_pytest/runner.py#L287), it's a dictionary that doesn't actually have values other than `1`, so only its keys are significant:

```python
keywords = dict([(x, 1) for x in item.keywords])
```

- Is there a reason why it doesn't just pass the original `item.keywords` to the report but obscures the values? (Is it a dict for legacy reasons?)
- If that's intentional, it would still be great to have clarified in the docs that the dict doesn't actually contain the same information as `dict(item.keywords)` does (details about a marker, etc.), but the values are constant `1`.

**Comment by nicoddemus** [comment]
Hi @numirias thanks for writing.

@RonnyPfannschmidt can probably shed some light here, we're in the middle of a large refactoring involving marks (which affects `TestReport.keywords`).

**Comment by RonnyPfannschmidt** [comment]
this is a artefact from before python had sets, instead a `dict` with the value 1 where used as stopgap,

its mainly still there for backward compatibility reasons as far as i understood (keywords and their interaction with marks is the main reason why we have so massive troubles with marks)

**Comment by numirias** [comment]
Thanks for clarifying! I'm closing because as I understand you don't require this to be tracked in an extra issue, but feel free to re-open.
