### ISSUE TITLE
"<-" in verbose test output

### ISSUE THREAD

**Issue by thisch** [pytest-dev/pytest#3211]
In my integrationtests the verbose text output does not seem to be consistent. There are three different types of lines in the output of pytest:

```
relpath::TestClass::testmethod1 PASSED
relpath::TestClass::testmethod2 <- ../../path/to/testbase.py SKIPPED
relpath::TestClass::testmethod3 <- abspath PASSED
```

I don't understand why the last two lines contain '<-' and a subsequent path. I've studied the code in https://github.com/pytest-dev/pytest/blob/master/src/_pytest/terminal.py#L517 but I don't understand it. Can anyone help me?

The "<-" in the pytest output was introduced in https://github.com/pytest-dev/pytest/commit/d73e689991ec3867aee56f2efe5212a6a6e18924

**Comment by thisch** [comment]
I've found a few tests in test_terminal.py which indicate that the lines containing "<-" have sth to do with baseclasses in different test modules. I think this behavior should be configurable and preferably opt-in.

**Comment by nicoddemus** [comment]
IIRC your assessment is correct, here's a minimal reproducer:

```python
# contents of base.py
class D:
    def test_foobar(self):
        pass

# contents of test_foo.py
from base import D

class Test(D):

    def test_foo(self):
        pass
```

```
$ python -m pytest .
============================= test session starts =============================
platform win32 -- Python 3.6.3, pytest-3.4.2.dev61+g54e63b7.d20180222, py-1.5.2, pluggy-0.6.1.dev -- C:\pytest\.env36\Scripts\python.exe
cachedir: ..\.pytest_cache
rootdir: C:\pytest\.tmp, inifile: pytest.ini
plugins: forked-0.2, hypothesis-3.38.9
collected 2 items

test_foo.py::Test::test_foobar <- base\base.py PASSED                    [ 50%]
test_foo.py::Test::test_foo PASSED                                       [100%]

========================== 2 passed in 0.02 seconds ===========================
```

I wouldn't mind adding an option and also changing to not use the `<-` indicator by default: I think it in general just confuses people.

**Comment by fontealpina** [comment]
@nicoddemus I agree

**Comment by pfctdayelise** [comment]
What would be better to use instead of `<-` ?

How about just removing the reporting of base classes completely?

**Comment by thisch** [comment]
I'm totally in for removing the reporting of the base classes.

**Comment by RonnyPfannschmidt** [comment]
can we take a look at how and when it was introduced beforehand

**Comment by thisch** [comment]
Edit: added the link to the commit, where this output format was introduced to the description of this issue.

**Comment by RonnyPfannschmidt** [comment]
thanks for the research, i do wonder if we should move it to a higher verbosity level instead of removing it since its quite useful for debugging various legacy codebases

**Comment by thisch** [comment]
@RonnyPfannschmidt thx for the suggestion, I'll simply change the verbosity level.
