### ISSUE TITLE
Having all options from all conftest.py for all collected tests

### ISSUE THREAD

**Issue by bechaos** [pytest-dev/pytest#3212]
Hello.
In directory structure:
```
/conftest.py
/tests_A/conftest.py
/tests_A/tests_A.py
/tests_B/conftest.py
/tests_B/tests_B.py
```
i have "pytest_addoption" hook in `/tests_A/conftest.py` and `/tests_B/conftest.py` with options which are related to tests in `tests_A.py` and `tests_B.py`, and in `/conftest.py` options common for both.

If i call ptyest from `/tests_A/` or `/tests_B/` i have options available for those tests. However if i call pytest from `/` specific options are unrecognized. Im aware that i could write all options in `/conftest.py`. but due clean code, I'd rather have it separated.

I there a way to achieve this?

Thank you for your time.

**Comment by nicoddemus** [comment]
@bechaos unfortunately due to how `pytest_addoption` works the recommended way is to declare all options in the root `conftest.py` level, there's a note explaining that in [the docs for pytest_addoption](https://docs.pytest.org/en/latest/writing_plugins.html#_pytest.hookspec.pytest_addoption).

**Comment by nicoddemus** [comment]
Closing as this has not seen activity in awhile.
