### ISSUE TITLE
Session scoped fixture is called twice

### ISSUE THREAD

**Issue by bdjellab** [pytest-dev/pytest#3217]
Hello,

**Version**: I'm running Ubuntu 14.04 with pytest 3.4.0.

**Use case**: I am using a session scoped fixture which I import and use in two different test files.

**Issue**: The fixture is run one time for each file when I expect it to be run only once for the whole session.

**Example**: 

fixtures.py
```
import pytest

@pytest.fixture(scope="session")
def my_fixture():
    print "Hello"
```

test1.py
```
from fixtures import my_fixture

def test_example(my_fixture):
    pass
```

test2.py
```
from fixtures import my_fixture

def test_example2(my_fixture):
    pass
```

Hello is printed twice instead of once.

**Workaround**: A workaround is to import it in the conftest but since I am using hundred of fixtures, I prefer not to import everything in the conftest.

**Comment by feuillemorte** [comment]
You don't need to import fixtures

You can use fixtures in test files like
```
@pytest.fixture()
def print_word():
    print('This is fixture!')
    

def test_one(print_word):
    assert 1
```
or you can add your fixture file to conftest as plugin:
my_custom_fixtures.py
```
import pytest


@pytest.fixture(scope='session')
def print_word():
    print('This is fixture!')

```
conftest.py
```
pytest_plugins = ['my_custom_fixtures']
```
test_one.py
```
def test_one(print_word):
    assert 1
```
test_two.py
```
def test_one(print_word):
    assert 1
```
result:
```
collected 2 items                                                                                                                                                                                                                                                                                                     

tests/test_one.py This is fixture!
.
tests/test_two.py .
```
if you have different files with your fixtures you can add it in coftest like 
```
pytest_plugins = [
    'path.to.fixtures',
    'path.to.another.fixtures',
    'path.to.third.fixtures.file',
    ...
]
```

**Comment by bdjellab** [comment]
Hi,

Thanks for the info, I knew you could import fixtures in the conftest but I didn't knew you could do it as a plugin.

However, do you mean that I must not import fixtures like that?
Am I doing something that's against pytest rules or is it a limitation/bug of pytest?

**Comment by feuillemorte** [comment]
I might be wrong, but I guess:
When you import fixture pytest create another base_id for test file. And your scope session starts to work in this file and you have another session fixture fo this file. Check my tests:
structure:
```
tests
|- conftest.py
|- test_one.py
|- test_two.py
\- test_three.py
```
files:
conftest.py:
```
import random
import pytest

@pytest.fixture(scope='session')
def print_word():
    print('This is fixture!')
    return random.randint(1, 100)
```
test_one.py:
```
from conftest import print_word

def test_one(print_word):
    print(print_word)
    assert 1

def test_one_2(print_word):
    print(print_word)
    assert 1
```
test_two.py:
```
def test_two(print_word):
    print(print_word)
    assert 1


def test_two_2(print_word):
    print(print_word)
    assert 1
```
test_three.py:
```
def test_three(print_word):
    print(print_word)
    assert 1


def test_three_2(print_word):
    print(print_word)
    assert 1
```

start tests by command
```
pytest tests -s
```
FixtureDef objects:
```
test_one.py:  (<FixtureDef name='print_word' scope='session' baseid='tests' >, <FixtureDef name='print_word' scope='session' baseid='tests/test_one.py' >)
test_two.py: (<FixtureDef name='print_word' scope='session' baseid='tests' >,)
test_three.py: (<FixtureDef name='print_word' scope='session' baseid='tests' >,)
```
Output and results:
```
tests/test_one.py
This is fixture!
40
.
40
.
tests/test_three.py 
This is fixture!
91
.
91
.
tests/test_two.py
91
.
91
.
```

I don't think that it's a bug, but you can ask more core team (@nicoddemus , @The-Compiler , @RonnyPfannschmidt ) for details.

**Comment by RonnyPfannschmidt** [comment]
bascially - fixtures come from plugins, or the test module - if each module import the fixture, then pytest considers each imported fixture as own separate fixture of the test module

so pytest basically sees 2 fixtures with the same name, one in the one test module, the other in the other test module

the most simple way to consolidate is a conftest, followed by having a pytest plugin

**Comment by bdjellab** [comment]
Okay thanks ! 

It seemed strange to me because  - correct me if I'm wrong - importing the same function in two different files actually gives the exact same object in memory.

I will import all my session scoped fixtures in the conftest then.

**Comment by RonnyPfannschmidt** [comment]
correct, thats a good solution 👍 

in general we consider it good practice put fixtures that are shared across modules/folders into conftests for consistency

i closing this issue as the problem seems to be solved, if you feel there is more to solve please dont hesitate to call out

**Comment by erwinkinn** [comment]
May the force be with you, folks! I've smashed helluva day to understand what the heck is happening with those scopes! 
Cannot believe pytest works this way. Whatever framework specific rules they must be a subset of  the rules of Python.
I couldn't expect I import the same name from module and get different objects in terms of pytest.
Thank you!
