### ISSUE TITLE
Question: How to get the skip reason in a pytest_runtest_logreport(report) hook

### ISSUE THREAD

**Issue by mikeage** [pytest-dev/pytest#3220]
Is there any way to get the value of `reason=` in a skipped test? For `xfail(reason="foo")` the reason shows up as `report.wasxfail`, but I didn't see the skipped reason anywhere in the report's object or `__dict__`.

**Comment by mikeage** [comment]
I actually just saw that https://github.com/pytest-dev/pytest/blob/71a7b3c062d51c61ee8b1ac479b1260d541918c6/_pytest/junitxml.py#L177 has

```python
        if hasattr(report, "wasxfail"):
           ...
        else:
            filename, lineno, skipreason = report.longrepr
            if skipreason.startswith("Skipped: "):
                ...
```
Is this the best option?

**Comment by nicoddemus** [comment]
https://github.com/pytest-dev/pytest/blob/44fa5a77d4544d22220704fab5ab494fb57f52ae/_pytest/skipping.py#L252-L253

I think if `outcome == "skipped"` you can get the reason from the `wasxfail` attribute; this is indeed far from intuitive. I assume when the `skipping` plugin was developed it was not designed to be consumed by plugins outside the pytest core, hence it doesn't really have a public and well specified API I'm afraid.
