### ISSUE TITLE
Error using parametrize with default arguments

### ISSUE THREAD

**Issue by ndevenish** [pytest-dev/pytest#3221]
With pytest 3.4.0:
```python
import pytest

@pytest.mark.parametrize("something", [True, False])
def test_something(something=False):
  pass
```
You get the error:
```
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/pluggy/__init__.py:617: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/pluggy/__init__.py:222: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/pluggy/__init__.py:216: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/python.py:200: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/python.py:378: in _genfunctions
    self.ihook.pytest_generate_tests(metafunc=metafunc)
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/pluggy/__init__.py:617: in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/pluggy/__init__.py:222: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/pluggy/__init__.py:216: in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/python.py:125: in pytest_generate_tests
    metafunc.parametrize(*marker.args, **marker.kwargs)
../../base/Python.framework/Versions/2.7/lib/python2.7/site-packages/_pytest/python.py:805: in parametrize
    self.function, name, arg))
E   ValueError: <function test_something at 0x10e4969b0> uses no argument 'something'
```
It seems pytest is separating the concept of normal python arguments and 'fixtures' here, only classifying only default-free arguments as potential fixtures - and then only considering 'fixtures' as valid targets for parametrisation - but the error message completely obfuscates this: by any regular python interpretation the function *definitely* has an argument 'something'. 

The documentation on this - https://docs.pytest.org/en/latest/parametrize.html doesn't show this as an example but also doesn't mention that it's a constraint; it's only through reading the pytest source that I could work out what the problem was.

Related: The wording of this was changed to 'argument' from 'fixture' in https://github.com/pytest-dev/pytest/issues/1539 which makes sense in the context of that error, but only confuses this one.

**Comment by RonnyPfannschmidt** [comment]
pytest doesnt consider arguments with default values as targets for fixtures/parameterization

**Comment by ndevenish** [comment]
Yes, that is the root cause. But this isn't a question; my point is that the error is completely confusing and the solution non-obvious unless you read the source code:

> pytest doesn't consider arguments with default values

*and then complains that there is no argument.*

So I'd consider it either a bug with error messages, argument-as-potential-fixture classification (although I assume this was rigorously discussed in the past and is like this for a reason), or a documentation problem.

**Comment by RonnyPfannschmidt** [comment]
thanks for expressing what you need for better understanding of the issue
i consider it an issue with the error message as well

**Comment by feuillemorte** [comment]
As I can see pytest ignores arguments with default values:

https://github.com/pytest-dev/pytest/blob/e7bcc854d975e981c090e37e747d91fc7999500e/_pytest/compat.py#L112-L115

Do we need to raise exception here? In this case all arguments with default value will catch this error

**Comment by RonnyPfannschmidt** [comment]
that function in particular is working exactly as documented, so just raising an error there is not a good way to sort it out

**Comment by andrzejnovak** [comment]
Stumbling into and old issue, but...

I am curious what the usual/recommended workflow for dev/debug is here. If I am developing new tests or indeed fixing failures, I would tend to copy the test function into my jupyter notebook and debug it there live. Now if the default kwargs are set, the function will essentially run as it. However, if they are not, I will have to fill a potentially complex list of dummy inputs. This is needless overhead for me rn. 

All that is to say, why can't parametrize just overwrite the default kwarg value?

**Comment by RonnyPfannschmidt** [comment]
please open a discussion - a issue closed more than 5 years ago is an very wrong place to start a discussion for something very different
