### ISSUE TITLE
enter debugger when warning is raised

### ISSUE THREAD

**Issue by thisch** [pytest-dev/pytest#3223]
Is it possible to enter the debugger when a warning is raised similar to the usage of the `--pdb` flag when normal exceptions are raised?

The reason why I'm asking is that I have the following warning in the warnings summary and I wan't to know where and why it is raised:

```
=============================== warnings summary ===============================
integrationtests/test_blocks.py::TestA::test_a
  /usr/lib64/python2.7/site-packages/numpy/core/_methods.py:83: RuntimeWarning: Degrees of freedom <= 0 for slice
    warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
```

**Comment by thisch** [comment]
`-W error` turns warnings into erros and is a cpython paramter. However if I pass it to pytest using `python -W error -m pytest` I get the following exception:

```
  File "/usr/lib/python2.7/site-packages/_pytest/fixtures.py", line 834, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
  File "/usr/lib/python2.7/site-packages/attr/_make.py", line 153, in attrib
    DeprecationWarning, stacklevel=2
DeprecationWarning: The `convert` argument is deprecated in favor of `converter`.  It will be removed after 2019/01.
```

**Comment by blueyed** [comment]
The exception with `python -W error -m pytest` seems to be good/expected, no?
And you can see where it is coming from there (pytest itself causes it apparently).

Does `python -W error -m pytest --pdb` give you a pdb prompt then?

**Comment by thisch** [comment]
No this exception is not expected, since it is raised before the tests are executed. Here is the full traceback:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/usr/lib/python2.7/site-packages/_pytest/fixtures.py", line 832, in <module>
    class FixtureFunctionMarker(object):
  File "/usr/lib/python2.7/site-packages/_pytest/fixtures.py", line 834, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
  File "/usr/lib/python2.7/site-packages/attr/_make.py", line 153, in attrib
    DeprecationWarning, stacklevel=2
DeprecationWarning: The `convert` argument is deprecated in favor of `converter`.  It will be removed after 2019/01.
```

**Comment by blueyed** [comment]
Ah, it is another one - sorry for the confusion.
I wonder if it (using `--pdb` to get to yours) works after fixing the one in pytest (and any others).

**Comment by RonnyPfannschmidt** [comment]
this is a pytest issue actually - we use a deprecated attrs api and should fix that bit

a more specific warning filter s (matching only numpy for errors) should help

**Comment by blueyed** [comment]
@RonnyPfannschmidt 
Yes, but the issue itself is about using `--pdb` to get to a warning (after pytest starts up after all).
@thisch 
Please try this after fixing the warning in pytest itself (and/or using `-W` with some filter to skip pytest's warning - not sure if that is possible).

**Comment by blueyed** [comment]
Ah.. that's what Ronny meant likely: only match numpy's warning, and then use `--pdb`.
Please try that.

**Comment by RonnyPfannschmidt** [comment]
i propose updating the requirement and changing the call

**Comment by thisch** [comment]
I don't understand why the coveralls job failed.

**Comment by RonnyPfannschmidt** [comment]
seems like a config issue, i believe merging is just fine

**Comment by thisch** [comment]
I've just discovered that there is already a `-W` option for pytest. This is great!! Therefore I don't have to start pytest with `python -W error -m pytest --pdb` but can write `pytest -W error --pdb`. I think we can close this issue then.
