### ISSUE TITLE
pytest runs into process thread overrun/over flow 

### ISSUE THREAD

**Issue by satishmovvar** [pytest-dev/pytest#3227]
When I run my test suite after a 10-15mins of testing I see that the Python process thread count starts increasing from 40threads up to 500threads. The tests get stuck at this moment and doesn't continue further. 
![image](https://user-images.githubusercontent.com/35823859/36277172-1b7f402a-125e-11e8-8940-4186dea83d06.png)

OS: Windows 7 - 64bit
Python Package: Anaconda 5.0.1 - 32bit version
Pytest : 3.4.0

I am using pytest to do system testing; The test setup needs to communicate external HW by simulating CAN/Serial RS232 messages constantly using DotNet Libraries; So I am using pythonnet libraries along with the all other packages part of Anaconda. 

I would really appreciate any suggestions to debug this issue.

**Comment by RonnyPfannschmidt** [comment]
pytest itself does not use any threads - so it mist be on of the libraries/tools you use

**Comment by satishmovvar** [comment]
@RonnyPfannschmidt  thanks for the info. I was wondering if you have any suggestion to debug; Any tools which can trace which object is actually launching the new threads. 
I tried to use the pyutil to monitor the process threads and I can also get the list of threads but I am not sure if there is a way I can identify what is causing the thread count to increase. 

```python
import os, psutil, logger
cp = psutil.Process(os.getpid())
if (cp.num_threads()>55):
	logger.getDefault().critical("Thread count = %d"%cp.num_threads())
	pdb.set_trace()
```

While debugging I felt that one of the plugin I wrote seem to cause the issue faster compared to without the plugin; It didn't make sense to me how it can impact but I would really appreciate if you can review and confirm.

This is extension of delayed assertion implemented by @ionelmc . I customized it a little.
```python

def _log_failure(node, msg=''):
	# get filename, line, and context
	(filename, line, funcname, contextlist) =  inspect.stack()[2][1:5]
	filename = os.path.basename(filename)
	context = contextlist[0]
	# format entry
	msg = '%s\n' % msg if msg else ''
	entry = '>%s%s%s:%s\n--------' % (context, msg, filename, line)
	# add entry 
	if not hasattr(node, '_failed_expect'):
		node._failed_expect = []
	node._failed_expect.append(entry)

def expect(expr, msg=''):
	if not expr:
		(frame, filename, line, funcname, contextlist) = inspect.stack()[1][0:5]
		request = frame.f_back.f_locals["funcargs"]["request"]
		_log_failure(request.node, msg)

def pytest_namespace():
	def expectation():
		frame = inspect.stack()[1][0]
		request = frame.f_back.f_locals["funcargs"]["request"]
		if hasattr(request.node, '_failed_expect'):
			return False
		else:
			return True
	return {'expect': expect, "expectation":expectation}

@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
	outcome = yield
	report = outcome.get_result()
	if (call.when == "call") and hasattr(item, '_failed_expect'):
		summary = 'Failed Expectations:%s' % len(item._failed_expect)
		item._failed_expect.append(summary)
		if report.longrepr:
			report.longrepr = str(report.longrepr) + '\n--------\n' + ('\n'.join(item._failed_expect))
		else:
			report.longrepr = '\n'.join(item._failed_expect)
		report.outcome = "failed"
	if (cp.num_threads()>55):
		logger.getDefault().critical("Thread count = %d"%cp.num_threads())
		pdb.set_trace()
```

**Comment by satishmovvar** [comment]
After reinstalling the Ananconda package I didn't have any issue so closing this for now
