### ISSUE TITLE
sub-steps progress report

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest#3235]
Would it be possible to add sub-steps reporting to test? :-) e.g. imagine I have some integration test cases that run reasonably long (e.g. 2 minutes, I would like to give some progress report to the user, to not let him wander around what's happening). E.g. with -vvvv to say:

```
plugins/test_init_integration.py::test_flow
    create db
    populate tables
    simulate_parallel_add
   ...
```

Do you guys think that's a good idea?

**Comment by RonnyPfannschmidt** [comment]
linking - #153 for documentative purposes

**Comment by nicoddemus** [comment]
This can be implemented a simple fixture:

```python
import pytest

@pytest.fixture
def print_sub_report(pytestconfig):
    dummy = lambda *args: None
    #print('option', pytestconfig.getoption('verbose'))
    if pytestconfig.getoption('verbose') <= 0:
        return dummy

    terminal_reporter = pytestconfig.pluginmanager.getplugin('terminalreporter')
    if terminal_reporter is None:
    	return dummy

    first_call = [True]

    def print_sub_report(msg):
    	if first_call[0]:
    		terminal_reporter.write('\n')
    		first_call[0] = False
    	terminal_reporter.write('  ' + msg + '\n')

    return print_sub_report


def test_something(print_sub_report):
	print_sub_report('create db')
	print_sub_report('populate tables')
	print_sub_report('simulate_parallel_add')
```

Output:

```
collected 1 item

foo.py::test_something
  create db
  populate tables
  simulate_parallel_add
PASSED                                                                                                           [100%]

============================================== 1 passed in 0.04 seconds ===============================================
```

While adding this to the core is simple, not sure if a separate plugin would be better at least as a first interaction, to nail down the API and see which other integrations would be necessary (`junitxml` comes to mind for example).

**Comment by nicoddemus** [comment]
This is identical to #1602 as well.

**Comment by gaborbernat** [comment]
@nicoddemus I like what you propose. Do you want to release it as a plugin, and let';s see where it goes, or should I?

**Comment by nicoddemus** [comment]
@gaborbernat feel free to go for it if you have the time! 👍

**Comment by gaborbernat** [comment]
@nicoddemus it's not finished and posted yet to PyPi, but can you have a first look at it https://github.com/gaborbernat/pytest-print

Will publish next week but would be nice an eye on it before. The timestamps thing mirrors how https://docs.python.org/3/library/logging.html#logrecord-attributes relativeCreated works.

Thanks!

**Comment by nicoddemus** [comment]
Looks nice to me. I'm fine with moving under `pytest-dev` as well. 😁

**Comment by gaborbernat** [comment]
@nicoddemus https://pypi.org/project/pytest-print/, done :-D there is a test failing  on windows, seems the pytest flag is not picked up for some reason, will check

**Comment by gaborbernat** [comment]
@nicoddemus want to invite the project under pytest then? :smiley:

**Comment by nicoddemus** [comment]
Sure! Transfer the project to me and I will complete the transfer.

**Comment by gaborbernat** [comment]
```
Repository transfer to nicoddemus requested
```

**Comment by nicoddemus** [comment]
Done. 😁

**Comment by nicoddemus** [comment]
@gaborbernat could you also add me as maintainer on PyPI? Thanks!

**Comment by gaborbernat** [comment]
Done :+1:

**Comment by nicoddemus** [comment]
Thanks!
