### ISSUE TITLE
xfail condition should include `platform` module in namespace

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#3236]
One can currently write:

```
@pytest.xfail("sys.platform == 'darwin'")
```

But not 

```
@pytest.xfail("platform.platform() == 'Darwin'")
```

If one tries that, an error is raised:

```
Error evaluating 'xfail' expression
    platform.platform() == "Darwin"
NameError: name 'platform' is not defined
```

It seems reasonable to me the `platform` module should be exposed in the namespace for these conditional methods for the same reason `sys` is.

I searched but could not find an existing issue or even a definition of what these conditional expressions are guaranteed to support, so I hope this is not a duplicate report.

**Comment by nicoddemus** [comment]
Definitely, thanks for the suggestion.

**Comment by nicoddemus** [comment]
This is a great first contribution, cc @feuillemorte.

**Comment by blueyed** [comment]
For what it's worth: I do not see the NameError when trying that (pytest
3.4.0):
```
collected 0 items / 1 errors                                                                

================================== short test summary info ==================================
ERROR tests/test_t.py
========================================== ERRORS ===========================================
_____________________________ ERROR collecting tests/test_t.py ______________________________
tests/test_t.py:4: in <module>
    @pytest.xfail("platform.platform() == 'Darwin'")
E   _pytest.outcomes.XFailed: platform.platform() == 'Darwin'
!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!
================================== 1 error in 0.21 seconds ==================================
```

I wanted to try if `@pytest.xfail("__import__('platform').platform() !=
'Darwin'")` could be used as a workaround, but the outcome is the same as above
for me.

**Comment by nicoddemus** [comment]
Now that I think about it, perhaps it uses the global namespace of the module of the test?

**Comment by svuki** [comment]
If I'm understanding correctly the problem isn't outcomes.xfail but the xfail mark which is talked about in the docs [here](https://docs.pytest.org/en/latest/skipping.html#xfail-mark-test-functions-as-expected-to-fail). 

If that's the case then the relevant code for what's available during evaluation of conditions is here:
https://github.com/pytest-dev/pytest/blob/bedceaacc46aefab78c8f29db36dab03c24f1646/_pytest/skipping.py#L110-L114.

So it's the global namespace of the module of the test plus os, sys, and item.config.

**Comment by nicoddemus** [comment]
@svuki thanks for clarifying that! I believe we can just add `platform` to that initial directory in there then, I believe `platform` is as useful as `sys`.
