### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: '/path/to/bin/bin' - bin as file

### ISSUE THREAD

**Issue by hevi9** [pytest-dev/pytest#3241]
https://github.com/pytest-dev/pytest/blob/053fc118b7af3b77c42daddd6ceacd13394cf64a/_pytest/main.py#L173

Should be ?

if not bindir.is_dir():
 ..

**Comment by nicoddemus** [comment]
@hevi9 indeed, would you like to contribute a PR?
