### ISSUE TITLE
Broken link and formatting issue in Getting Started docs

### ISSUE THREAD

**Issue by brettcannon** [pytest-dev/pytest#3256]
In https://docs.pytest.org/en/latest/getting-started.html#request-a-unique-temporary-directory-for-functional-tests there is a link with the text "Temporary directories and files." which points to a non-existent page.

There is also " `pytest fixtures <fixtures>`_" which is not rendering appropriately.

**Comment by nicoddemus** [comment]
Thanks for the report @brettcannon!

**Comment by brettcannon** [comment]
And thanks for the PR! I tried to fix it in-browser but my brain was not remembering to add `ref` so I couldn't get it to work.

**Comment by nicoddemus** [comment]
I know the feeling, I only remember the syntax because I was doing some documentation work last week. 😁
