### ISSUE TITLE
Issue warning when "[pytest]" section is used in a ".cfg" file passed with "-c"

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#3268]
See https://github.com/pytest-dev/pytest/pull/3267#discussion_r171010795

**Comment by feuillemorte** [comment]
I take it

**Comment by feuillemorte** [comment]
@nicoddemus But I need to merge master to features after PR will be merged

**Comment by nicoddemus** [comment]
Cool @feuillemorte! I'm merging `master` into `features` in #3269.

**Comment by nicoddemus** [comment]
Merged! 🙇
