### ISSUE TITLE
Issue with console prints

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest#3271]
Hi,
I have the same code with I'm using to create some connection to one of our product, the console logs different output every time I run it. 

Ones't run :
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.5, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /root/PycharmProjects/new/playground/mor/ncso, inifile:
collected 1 item

test_ncso_login.py 2018-02-28 10:46:02,664 [INFO] - test_create_customer_001 - location=test_ncso_login.py:test_create_customer_001 - STEP 1 - Login to NCSO
2018-02-28 10:46:02,664 [INFO] - test_create_customer_001 - location=test_ncso_login.py:test_create_customer_001 - Start Test
2018-02-28 10:46:02,850 [INFO] - test_create_customer_001 - location=test_ncso_login.py:test_create_customer_001 - STEP 2 - getting user role
2018-02-28 10:46:02,893 [INFO] - test_create_customer_001 - location=test_ncso_login.py:test_create_customer_001 - STEP 3 - TC passed , number of role is 1
.

=========================== 1 passed in 0.45 seconds =========================== 
```

2nd run :
```
============================= test session starts ==============================
platform linux2 -- Python 2.7.5, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /root/PycharmProjects/new/playground/mor/ncso, inifile:
collected 1 item

test_ncso_login.py 2018-02-28 10:46:46,438 [INFO] - test_create_customer_001 - location=test_ncso_login.py:test_create_customer_001 - STEP 1 - Login to NCSO
2018-02-28 10:46:46,438 [INFO] - test_create_customer_001 - location=test_ncso_login.py:test_create_customer_001 - Start Test
2018-02-28 10:46:46,621 [INFO] - test_create_customer_001 - location=test_ncso_login.py:test_create_customer_001 - STEP 2 - getting user role
.

=========================== 1 passed in 0.42 seconds ===========================
2018-02-28 10:46:46,684 [INFO] - test_create_customer_001 - location=test_ncso_login.py:test_create_customer_001 - STEP 3 - TC passed , number of role is 1 
```

What I'm missing here?

**Comment by RonnyPfannschmidt** [comment]
this looks like a potential issue in logging based on not flushing logging handlers

**Comment by Formartha** [comment]
@RonnyPfannschmidt - It might seem that it's related to multithreading?

The log I'm exporting seem to be OK, it's just the console..

**Comment by RonnyPfannschmidt** [comment]
i beleive its related to flushing logs, - my current idea is that the logged elements get written out to late for stdio logging

do you use threads in your code? because pytest certainly doesnt

**Comment by Formartha** [comment]
nope, I don't got any specific multithreading support ..

**Comment by nicoddemus** [comment]
@Formartha are you using `--log_cli`?

**Comment by Formartha** [comment]
that's the logger I had created to print it. I'm using pycharm to run tests..

That's the logger code 
`def logger_setup(logger_name, log_file, level=logging.INFO):
    l = logging.getLogger(logger_name)
    formatter = logging.Formatter(
        '%(asctime)s [%(levelname)s] - %(funcName)s - location=%(filename)s:%(funcName)s - %(message)s')
    fileHandler = logging.FileHandler(log_file + ".log", mode='w')
    fileHandler.setFormatter(formatter)
    streamHandler = logging.StreamHandler()
    streamHandler.setFormatter(formatter)

    l.setLevel(level)
    l.addHandler(fileHandler)
    l.addHandler(streamHandler)
    return l`

and I'm using logger fixture in my tests :+1: 
`@pytest.fixture(scope="module")
def logger(request):
    """
    This fixture creates a logger object so we could pass it into our tests and construct the logger
    :param request:
    :return:
    """
    test_file_name = request.fspath.purebasename
    return core_framework.logger_interface.logger_setup(test_file_name, ProjectPaths.build_log_path(test_file_name))`

**Comment by nicoddemus** [comment]
Oh we have assumed you were using pytest's logging integration.

Do you have the same output if you run in the command line, or only from PyCharm?

**Comment by Formartha** [comment]
maybe the logging integ is better than what I had built :) I will be more than happy to try to adopt it.

I got no output about it, however, I will be more than happy to give it a shot - could you share the command to do it?

**Comment by nicoddemus** [comment]
Use `-o log_cli=true -o log_cli_level=INFO` on the command line.

Btw do you need to see the log output while the tests are running, or showing the captured log when a test fails would be enough for your needs? Here's more info: https://docs.pytest.org/en/latest/logging.html

**Comment by Formartha** [comment]
Thanks buddy!

I will need to view the logs during the run (for debug only..), but, as long as it works fine I don't care if we'll see such glitches. 
However, I'm worried that it's more than that .. maybe there is a hidden bug there.

**Comment by nicoddemus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/pytest-dev/pytest/issues/3271](https://trello.com/c/7aYXi6MN/5-https-githubcom-pytest-dev-pytest-issues-3271)

**Comment by Formartha** [comment]
@nicoddemus - what is the link you had shared?

**Comment by nicoddemus** [comment]
Sorry, it was posted by Trello automatically, I was trying it out to see how to manage my personal TODO's. 😁

**Comment by Formartha** [comment]
Oh, LOL :) - well, let's hope it will work..

**Comment by ruslanoid** [comment]
I have a similar use case.
We're using our own logging configuration to print out the tests flow which got "interrupted" by pytest's reporting of test status in a single letter ('F' for Failure, etc...).

What I ended up doing is:
`
def pytest_report_teststatus(report, __multicall__):
    res = __multicall__.execute()
    return (res[0], res[1], "\n{}\n".format(res[2])) if res[2] else res
`

this way pytest's reporting has it's own line - and our own reporting it's own.
hope this helps.

**Comment by ruslanoid** [comment]
not yet, but plan to

**Comment by Zac-HD** [comment]
Closing as inactive.
