### ISSUE TITLE
[question] Multithreaded support in a function

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest#3320]
Hello,

I got some usecase where I will need some multithreaded support.
Basically, I got some implementation of a Rest API call which loades some .zip files.

The implementation basically scans a given directory and than it pushes the file to one API.

The main issue is that the time it takes to load a file is about 30 sec and I want to cut it down.
Multithreading this request might help, as it will open a thread per file and will send it to the server.

Do we have any limitation of doing it in pytest?
If so, care to assist with building it correctly?

Cheers,
Mor

**Comment by RonnyPfannschmidt** [comment]
pytest itself is unaware of thread and not designed to support working with threads inside of itself

on the same page there is also zero issue with spinning up a thread pool and submitting work to it

for the use-case as you described, i believe just having a thread pool is more than sufficient,

**Comment by Formartha** [comment]
Thank you for your response Ronny. I will deep dive into what you suggested.

Any plans to have some native threading support?

Plus,
Do you know any way to let Pycharm know I'm using an imported fixture? It shows that my module isnt being used (while importing it), however, it is used.

**Comment by RonnyPfannschmidt** [comment]
@Formartha as far as i understand the pytest support of pycharm is simply unaware of key features of pytest, so no idea how to add it

**Comment by RonnyPfannschmidt** [comment]
as for adding native threading support to pytest - thats highly unlikely as it very likely requires a complete rewrite of key parts

**Comment by nicoddemus** [comment]
> Do you know any way to let Pycharm know I'm using an imported fixture? It shows that my module isnt being used (while importing it), however, it is used.

You don't need to import fixtures in order to use them, mind you; you should put fixtures into a `conftest.py` file and pytest will find and inject them automatically in tests that need it.

I think we can close this for now, feel free to follow up with further questions.
