### ISSUE TITLE
Pytest doesn't add PYTHONPATH itself

### ISSUE THREAD

**Issue by MichaelYusko** [pytest-dev/pytest#3341]
Hello, and thank you for the cool tool! but I noticed that, when I tried to run tests via `pytest` command.

I'm always got the `E   ModuleNotFoundError: ` in order to fix the issue, we need to run `python -m pytest` manually, or just `export PYTHONPATH` to root directory.

Will be cool, if Pytest will do it itself, thank you;)

**Comment by RonnyPfannschmidt** [comment]
this is expected and planned behaviour, actually it caome to attention that module execution is a problematic way to run things

if we always add the wroktree we completely run sanely testing packages that where installed with tests from the worktree

**Comment by MichaelYusko** [comment]
@RonnyPfannschmidt Got it, thank you for the clear explanation

**Comment by nicoddemus** [comment]
Closing this for now then. 👍
