### ISSUE TITLE
Is there a way to provide mark with fixture params

### ISSUE THREAD

**Issue by cauveryguda** [pytest-dev/pytest#3351]
Currently I don't see and did not find any documentation on a way to provide mark for the params given in fixtures.  

For example I have a fixture with 3 params and I would like the test you use only some of the params for test run depending on the -m option given on command.  I don't think currently the marks are supported at fixture param level. 

FYI I am using mark at the test level parameterize, so looking for something similar at the fixture level param. 

Thank you,
Cauvery.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt is correct, a quick example:

```python
import pytest

@pytest.fixture(params=[1, pytest.param(2, marks=pytest.mark.slow)])
def fix(request):
    return request.param

def test_f(fix):
    pass
```

```
pytest params.py -m "not slow" -q
.
1 passed, 1 deselected in 0.01 seconds
```

**Comment by nicoddemus** [comment]
Noticed there was nothing about that on the docs: #3353

I'm closing this for now @cauveryguda since your question has been answered, but feel free to follow with more.

**Comment by cauveryguda** [comment]
Thank you for the answers. Sorry for some reason I have been searching for this and could not find in the documentation.  I will give a try for this and keep posted if any issues.

-Cauvery.
