### ISSUE TITLE
caplog documentation is incorrect

### ISSUE THREAD

**Issue by OrangeDog** [pytest-dev/pytest#3406]
As seen here: https://docs.pytest.org/en/latest/builtin.html

    caplog
        Access and control log capturing.

        Captured logs are available through the following methods::

        * caplog.text()          -> string containing formatted log output
        * caplog.records()       -> list of logging.LogRecord instances
        * caplog.record_tuples() -> list of (logger_name, level, message) tuples
        * caplog.clear()         -> clear captured records and formatted log output string

However, `text`, `records` and `record_tuples` are properties. Using them as described results in an exception:

> TypeError: 'list' object is not callable

**Comment by rachel1792** [comment]
Yes, you seem to have found an error in the docs.  @nicoddemus @RonnyPfannschmidt , can I take a stab at a PR?  I'm a first-time contributor :)
