### ISSUE TITLE
What does Pytest use to determine the error runtime.

### ISSUE THREAD

**Issue by tmuhimbisemoses** [pytest-dev/pytest#3411]
import turtle
turtle.forward(200)
turtle.down(100)
done()
![query](https://user-images.githubusercontent.com/443810/38994210-604abc5e-43ee-11e8-9202-d4f8d8b675a1.PNG)

**Comment by RonnyPfannschmidt** [comment]
its not even remotely clear what is being asked for, please provide basic context
