### ISSUE TITLE
error running pytest -k <given_path>

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest#3447]
While trying to run pytest -k <given_path> i'm getting the following error ;

rootdir: /root/PycharmProjects/orion, inifile:
plugins: xdist-1.22.2, sugar-0.9.1, pylint-0.9.0, metadata-1.7.0, instafail-0.3.0, html-1.16.1, forked-0.2, flakes-2.0.0, cov-2.5.1, allure-pytest-2.3.2b1

????????????????????????????????????????????????????????????????????????? ERROR collecting  ?????????????????????????????????????????????????????????????????????????
/usr/lib/python2.7/site-packages/py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
/usr/lib/python2.7/site-packages/py/_path/common.py:429: in gen
    for p in self.gen(subdir):
/usr/lib/python2.7/site-packages/py/_path/common.py:429: in gen
    for p in self.gen(subdir):
/usr/lib/python2.7/site-packages/py/_path/common.py:419: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
/usr/lib/python2.7/site-packages/_pytest/main.py:434: in _recurse
    ihook = self.gethookproxy(path)
/usr/lib/python2.7/site-packages/_pytest/main.py:338: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
/usr/lib/python2.7/site-packages/_pytest/config.py:348: in _getconftestmodules
    mod = self._importconftest(conftestpath)
/usr/lib/python2.7/site-packages/_pytest/config.py:376: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: SyntaxError("'return' with argument inside generator",)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I'm using python 2.7.14

**Comment by RonnyPfannschmidt** [comment]
at first glance this looks like an issue with a conftest file, not with pytest -k

**Comment by nicoddemus** [comment]
Indeed, in some `conftest.py` there's a function with `yield` and `return X` in the body, which is supported by Python 3 but not Python 2.

**Comment by Formartha** [comment]
@nicoddemus you are correct.
Just discovered the mess I made with trying to introduce a root source conftest file.

This thread can be closed :)

**Comment by nicoddemus** [comment]
Thanks for following up @Formartha
