### ISSUE TITLE
Provide a way for a single fixture to expand into multiple arguments

### ISSUE THREAD

**Issue by BrenBarn** [pytest-dev/pytest#3453]
Right now a single fixture always maps to a single argument in a test function.  The feature I'd like to request is the ability to define a single fixture function which "expands" to fill up multiple arguments in a test function.  Something like this:

    @pytest.multifixture("foo, bar")
    def foobar():
        return "blah", "whatever"
    
    def test_stuff(foo, bar):
        assert foo == "blah" and bar == "whatever"

I want to define the two objects `foo` and `bar` together (not as separate fixtures) because they are related in some fashion.  I may sometimes also want to define a fixture that depends on another fixture, but have the second fixture incorporate the result of the first and return it along with its own addition:

    @pytest.fixture
    def foo():
        return "blah"
    
    @pytest.multifixture("foo, bar")
    def foobar():
        f = foo()
        return f, some_info_related_to(f)

This example may seem silly, but in some cases `foo` is something like a Request object, and the `bar` object needs to be linked to that same request object.  (That is, I can't define `foo` and `bar` as independent fixtures because I need both to be derived from a single request.)

In essence, what I want to do is decouple the name of the fixture function from the name of the test-function argument, so that I can define a fixture which is "triggered" by a particular *set* of argument names in a test function signature, not just a single argument whose name is the same as that of the fixture function.

Of course, I can always just return a tuple as the result of the fixture and then unpack it myself inside the test function.  But given that pytest provides various magical tricks for automatically matching names to arguments, it seems like it's not unthinkable that it could magically handle this as well.  As far as I can tell, though, it's not currently possible.  This would be a useful feature.

**Comment by RonnyPfannschmidt** [comment]
this would require a very major refactoring of the interals to get reasonably correct, so i dont expect this to happen anytime soon unless someone starts it

right now to map thing all you need is 3 fixtures "foo_bar", and `foo(foo_bar) -> foobar.foo` plus bar in kin

so the problem you described is relatively simply solveable

**Comment by BrenBarn** [comment]
Sorry, I can't understand the second paragraph in your message.  You say

> all you need is 3 fixtures "foo_bar", and `foo(foo_bar) -> foobar.foo` plus bar in kin

What does that mean?

**Comment by Zac-HD** [comment]
> Of course, I can always just return a tuple as the result of the fixture and then unpack it myself inside the test function. But given that pytest provides various magical tricks for automatically matching names to arguments, it seems like it's not unthinkable that it could magically handle this as well.

While this *would* be useful, it could also be very confusing to users who don't understand the exact rules for matching names (which does already happen!).  The implementation would also be extremely difficult.

Manually unpacking a tuple remains the recommended approach - but note that you can create a fixture `foobar` which takes the `foo` and `bar` fixtures, and returns `(foo, bar)`, so while the unpacking has to be manual you can still define each of the fixtures individually.

**Comment by smarie** [comment]
You can now do this using [`pytest-cases`](https://smarie.github.io/python-pytest-cases/#unpack_fixture-unpack_into), as you already saw in https://stackoverflow.com/a/56869423/7262247 (thanks for connecting !)
