### ISSUE TITLE
`--doctest-modules` causes `py.test` to consume all memory and then crash

### ISSUE THREAD

**Issue by tadams42** [pytest-dev/pytest#3456]
WARNING: Please don't run code sample from below, it can block / crash your machine. Instead, use Vagrant machine for testing it. 

So, on Ubuntu 17.10 , Python 3.6:

~~~sh
mkdir foobar
cd foobar
mkdir src
mkdir tests
mkdir docs
python3 -mvenv .venv
source .venv/bin/activate
pip install -U pip wheel
pip install "pytest>=3.0.0"

cat <<EOT > setup.cfg
[tool:pytest]
norecursedirs = .git tmp* .hg .venv .tox .eggs
testpaths = tests docs src
addopts =
    -r=xEfsw
    --strict
    --ignore=docs/conf.py
    --ignore=setup.py
    --ignore=.eggs
    --doctest-modules
    --doctest-glob=*.rst
    --tb=short
    --color=auto
EOT

echo "from unittest.mock import Mock, call" > tests/test_with_mock_package.py
~~~

Running `py.test` will cause it to consume all RAM it can get and then either kernel will kill it or system will start swapping wildly until it blocks completely.

To make above thing work:

~~~diff
--- setup.cfg   2018-05-08 13:03:47.058679203 +0000
+++ setup.cfg.new       2018-05-08 13:09:46.650678324 +0000
@@ -7,7 +7,7 @@
     --ignore=docs/conf.py
     --ignore=setup.py
     --ignore=.eggs
-    --doctest-modules
+    # --doctest-modules
     --doctest-glob=*.rst
     --tb=short
     --color=auto
~~~

After which:

~~~
$ py.test
============================================================ test session starts ============================================================
platform linux -- Python 3.6.3, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/vagrant/foobar, inifile: setup.cfg
collected 0 items

======================================================= no tests ran in 0.01 seconds ========================================================
~~~

**Comment by tadams42** [comment]
And here are version and environment details:

~~~sh
$ source .venv/bin/activate
$ pip list                                                                                                          [.venv]
Package        Version
-------------- -------
attrs          18.1.0
more-itertools 4.1.0
pip            10.0.1
pkg-resources  0.0.0
pluggy         0.6.0
py             1.5.3
pytest         3.5.1
setuptools     32.3.1
six            1.11.0
wheel          0.31.0
~~~

~~~sh
$ lsb_release -a                                                                                                    [.venv]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
~~~

~~~sh
$ py.test --version                                                                                                 [.venv]
This is pytest version 3.5.1, imported from /home/vagrant/foobar/.venv/lib/python3.6/site-packages/pytest.py
~~~

**Comment by RonnyPfannschmidt** [comment]
the issue comes from passing the mock object to doctest inadvertently
i believe this is an issue with the stdlib being broken, im not sure if pytest can do something about it

**Comment by tadams42** [comment]
hmm, I'd also found another workaround, through `pytest-mock` plugin, using `mocker` fixture and avoiding import of `unittest.mock`:

~~~python
# tests/test_with_mock_package.py

def test_simple(mocker):
    mock_obj = mocker.Mock()
~~~

* note that in this case there is no `from unittest.mock import Mock, call`

Going that route doesn't break `py.test`...

I guess this one can be invalidated then? As for the stdlib, I might find time to figure out if this was reported, and report it there...

**Comment by RonnyPfannschmidt** [comment]
as long as there is no superseeding upstream issue i'd like to leave this one open

**Comment by RonnyPfannschmidt** [comment]
indeed, seems python is broken enough there to fall to warrant a workaround

**Comment by nicoddemus** [comment]
Can we close this or @RonnyPfannschmidt are you we should do something in pytest as a workaround?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus we should investigate the cost of a workaround at least

**Comment by Zac-HD** [comment]
Previously reported as #1217.

It's easy enough to [check if an object is a mock](https://github.com/HypothesisWorks/hypothesis/blob/0b9d1a5d713e8c1bd29343ebbd079ad57e31ecb9/hypothesis-python/src/hypothesis/internal/reflection.py#L49-L60), but turning that into a workaround in pytest (instead of Python) might be difficult.

**Comment by nicoddemus** [comment]
@Zac-HD thanks for that snippet, interesting approach to the problem.

I propose to close this, because (IIUC) we can't fix this because the parsing is done by the builtin `doctest` module.

**Comment by RonnyPfannschmidt** [comment]
there is a semi-simple workaround requiring a wrapper - i fixed it on python2, but need some more to fix it on modern python3 (which detects the actual wrapper loop) - the fix itself already makes the situation better on python2, but still fails users on python3 in a way

**Comment by dahluwalia-ag** [comment]
Also, FYI I do already use a python wrapper to run pytest. It eventually calls:
```
import pytest
return pytest.main(args)
```
One workaround I can think of is to inspect the errors and ignore these specific "wrapper loop" errors. How do we get access to the error list using pytest module?

Another work around, as I mentioned in my first comment, is to disable running doctests for the suspect files. Do we have ability to run doctests only in a specific directory, to detect doctests only with a specific file name, or to skip doctests for certain files?

Thanks!

**Comment by RonnyPfannschmidt** [comment]
im just picking up my branch to set up the finder object correctly
