### ISSUE TITLE
Hook for passing assertions

### ISSUE THREAD

**Issue by Sup3rGeo** [pytest-dev/pytest#3457]
Hi,

I am writing some reporting plugin for pytest and I find important that it mentions the assertions on the test, basically saying that it passed and the values involved in the comparison.

Because `assert` is a statement, we cannot override it or monkey patch to make it run custom reporting code. I also don't want to resort to unittest-style assertion functions as the purpose of pytest after all is making as much boilerplate free as possible.

So I was wondering if pytest has/could have some sort of hook that would be called whenever we have a passing assertion on the test, with the same assertion introspection information as showed when an assertion fails. I suppose this would have do be done around the assertion rewriting.

Can it be done right now with current features and, if not, could you give some directions on where to look for? If my abilities are enough for this I would be willing code it and make a PR if you think it is a worthy feature and everything goes fine.

Thanks!

**Comment by Sup3rGeo** [comment]
Checking assertion rewrite code on pytest it seems that it could be relatively easily done by changing `rewrite.py::AssertionRewriter` in the `visit_Assert` method:

        # Rewrite assert into a bunch of statements.
        top_condition, explanation = self.visit(assert_.test)
        # Create failure message.
        body = self.on_failure
        negation = ast.UnaryOp(ast.Not(), top_condition)
        self.statements.append(ast.If(negation, body, []))

It appears we could replace the `[]` by another set of AST with a call to a hook that passes forward the `explanation` generated for the comparison?

**Comment by manoj23** [comment]
@Sup3rGeo Can you upload your code?
I am really interested in having passing assertions (with their values) in the test report.

**Comment by Sup3rGeo** [comment]
So basically these are the updates:

- Now explanation variables are declared before if-else clause. Inside them thus we only have the `raise AssertionError` if it fails or the hook call if it passes
- Hook update to have three arguments `pytest_assertion_pass(config, orig, expl)`: one string with the original assertion statement, and another with pytest explanation. For the first one I had to use `astunparse` to get code from the AST, and it would have to become a pytest dependency. The alternative would be to return the AST tree, but I think that is too low level.
- No tests written yet for this new feature
- Pytest tests passes except three related to cycle reference, garbage collector stuff that I am not really sure about the cause.

**Comment by manoj23** [comment]
Thanks @Sup3rGeo, I tested this branch https://github.com/Sup3rGeo/pytest/commits/features-assertion-pass-hook and the hook works.

**Comment by nicoddemus** [comment]
Hey @Sup3rGeo, thanks a lot for tackling this!

I think this would be a great addition to the core.

About the tests: take a look at the test suite, specially those using the `testdir` fixture: it allows you to test pytest as a "blackbox" by running tests and checking the output. You could for instance write a simple test file and a `conftest.py` file which implements your hook. The hook dumps its parameters to a file, which you then can check after the test has finished.

> Possible drawback is that we are always creating the explanation variables, not only if assertion fails anymore. I don't know if this could be a performance issue.

Usually not, but in some cases it might be a problem (think for example comparing huge strings: this would always produce an expensive diff even when not needed), so we should avoid this if possible. 

One solution I can think of is to instead of passing the full explanation to the hook, to instead pass a lazy callable that the hook can call to obtain the explanation (which would then compute it if requested). Something along the lines of `pytest_assertion_pass(config, orig, expl_getter)`. This is not very elegant but the only idea I can think of right now.

**Comment by Sup3rGeo** [comment]
@manoj23 great, do you miss anything other than the original assert statement and explanation?

@nicoddemus
Thanks for the tips! What is your opinion about having `astunparse` as an additional dependency?

**Comment by Sup3rGeo** [comment]
I am really having a hard time debugging three tests that are not passing, all of them related to garbage collection:

    FAIL testing/acceptance_test.py::test_fixture_values_leak
    FAIL testing/python/raises.py::TestRaises::()::test_raises_cyclic_reference[function]
    FAIL testing/python/raises.py::TestRaises::()::test_raises_cyclic_reference[with]

I tried to make a minimal example with the problem and reverted my feature branch as much as possible to resemble pytest feature branch. I figured out the problem was on `assertion/rewrite.py::AssertionRewriter.visitAssert()`.

 I got the method to this, which causes the problem but if I comment out the `self.statements.extend(self.on_failure)` then tests pass.

        (... same as feature branch ...)
        err_name = ast.Name("AssertionError", ast.Load())
        exc = ast_Call(err_name, [], [])
        if sys.version_info[0] >= 3:
            raise_ = ast.Raise(exc, None)
        else:
            raise_ = ast.Raise(exc, None, None)
        self.statements.extend(self.on_failure)
        self.statements.append(ast.If(negation, [raise_], []))
        (... same as feature branch ...)

I have no idea on the reason why it is causing garbage collection problems. I could use some help from more experienced guys.

**Comment by manoj23** [comment]
> @manoj23 great, do you miss anything other than the original assert statement and explanation?

Nope, I have everything, thanks. Currently, I am trying to figure out how to insert the assert statement and explanation in the Junit XML report in a specific "passed" node.

**Comment by Sup3rGeo** [comment]
Guys, should I create a PR so it is easier to review the code? The same three tests related to garbage collection are failing but should it be easier to talk about this with a PR?

**Comment by manoj23** [comment]
@Sup3rGeo 
> Nope, I have everything, thanks. Currently, I am trying to figure out how to insert the assert statement and
> explanation in the Junit XML report in a specific "passed" node

Actually, I want to write a report of passed assert with:
* the class name
* the file name

**Comment by Sup3rGeo** [comment]
@manoj23 I updated the hook to receive a `item` object (instead of `config`) and also added `lineno` as an argument. Check if this helps.

**Comment by nicoddemus** [comment]
> Guys, should I create a PR so it is easier to review the code? The same three tests related to garbage collection are failing but should it be easier to talk about this with a PR?

Sure, please don't hesitate to open a WIP PR so we can discuss over the code. 😁

**Comment by Sup3rGeo** [comment]
Closed by #3479

**Comment by kyochujoho** [comment]
Hi, I'm just giving my support for this hook. This is really useful for official reporting purposes. Please keep it.

**Comment by nicoddemus** [comment]
Thanks @kyochujoho, noted. 👍 

So far we did not have any reports of problems related to the hook, so it will probably have the *experimental* status changed to *official* sometime in the future.

**Comment by chintanvadgama** [comment]
Is the hook still available? 

I am using `pytest-5.4.1` and this seems to be not working

**Comment by nicoddemus** [comment]
That's by design @chintanvadgama: pytest only rewrites `asserts` if they don't include a message (`assert [expr]`). If they do include a message (`assert [expr], [msg]`) then the assertion rewriter intentionally doesn't try to rewrite it.

**Comment by kfirdo** [comment]
Just like @chintanvadgama, I find uses for the provided error message.
I would like to log the passing assertion's custom message, but I cannot use it under current implementation.
I would expect to get it as `expl` instead of the current value, and for my use, implementing `pytest_assertrepr_compare` is a lot of unnecessary work.
