### ISSUE TITLE
Hanging on finishing test output if capturing output

### ISSUE THREAD

**Issue by revmischa** [pytest-dev/pytest#3458]
platform darwin -- Python 3.6.4, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/cyber/dev/jb/backend, inifile: tox.ini
plugins: xdist-1.22.2, forked-0.2, flake8-1.0.0, cov-2.4.0

I really wish I could provide more details or a failing example, but I have a very large and time-consuming (30min) test suite. And if I run with `-s`, it completes, and if I don't, it hangs after the last test forever. I can't even interrupt it and get a stack trace. `dtruss` is less than helpful. Any idea what could be going on?

**Comment by nicoddemus** [comment]
Hi @revmischa,

It is hard to tell without more details, but some things to try:

1. Try running half the test suite and see if the problem still persists; if it doesn't, try with the other half. If you can't reproduce the problem running fewer tests, it means then that the problem might be the output size being generated by the entire suite. If you can only reproduce this with one half of the test suite, repeat the process by halving that half with the problem and checking if the problem still happens, and so on; eventually you might find a single test which causes the problem, which will make it easier to diagnose.

2. Are there failures or you it hangs even when all tests pass? 

3. Are you using `--junitxml`? Keep in mind that it waits until the end of the suite to dump the XML file, and with it the captured stdout/stderr.

**Comment by Formartha** [comment]
@nicoddemus - out of curiosity, what is considered an output that will stuck pytest and why?

**Comment by nicoddemus** [comment]
@Formartha I'm not aware of a known output format or such that would cause pytest to get stuck; my suggestions above were just things that I would try myself to figure out the cause of the problem.
