### ISSUE TITLE
Print out only the test cases name

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest#3478]
Hi folks,
I wanted to know if there is a way print to terminal only the name of the tests and not the **path.to.module:testname**.

**Comment by RonnyPfannschmidt** [comment]
by default there is not, if you describe your use-case a bit in more detail we might be able to provide you with a solution or at least a path to one

**Comment by Formartha** [comment]
Hi @RonnyPfannschmidt,
So, it's pretty hard to understand what happened in Jenkins because of the structure of printout in pytest.
for example :

09:23:22 testsuite/integration/aai/test_aai_model_loader_check_ingestion.py::TestAaiModel::test_retrieve_model PASSED [  3%]
09:24:29 testsuite/integration/aai/test_aai_ncso_adapter_add_topology.py::TestAaiNcsoAdapterTopologyAdd::test_ncso_adapter_ncso_topoolgy PASSED [  6%]
09:24:34 testsuite/integration/ncso/authorization/test_3595_authorization_prohibit_use_of_x_last_passwords.py::test_3595_authorization_prohobit_use_of_x_last_passwords PASSED [  9%]
09:24:35 testsuite/integration/ncso/authorization/test_ncso_invalid_login.py::test_ncso_invalid_login PASSED [ 12%]
09:24:39 testsuite/integration/ncso/data_store/test_4469_gds_crud.py::test_4469_gds_crud PASSED [ 16%]
09:25:32 testsuite/integration/ncso/operability/test_2809-cloudmanager_add_plugins_both.py::test_2809_cloudmanager_add_plugins_both PASSED [ 19%]

That's not readable, I would wish to see the following :

test_ncso_adapter_ncso_topoolgy PASSED [  6%]
test_3595_authorization_prohobit_use_of_x_last_passwords PASSED [  9%]
test_ncso_invalid_login PASSED [ 12%]
test_4469_gds_crud PASSED [ 16%]
test_2809_cloudmanager_add_plugins_both PASSED [ 19%]

**Comment by nicoddemus** [comment]
If we still want to pursue this we probably should open a new issue with a concrete proposal. 👍
