### ISSUE TITLE
Add an additional flag in order to make the -k parameter match exact 

### ISSUE THREAD

**Issue by david-fliguer-ws** [pytest-dev/pytest#3483]
Hi, let's say that we have three tests on a file called test_johndoe.py

def test_one():
       print("Test one")

def test_onetwo():
       print("Test onetwo")

def tests_onetwothree():
      print("Test onetwothree")

if I run like this

pytest test_johndoe.py -k one

Then all tests will be run

Is it possible to add a parameter that forces to match exact, something like

pytest test_johndoe.py -k one -matchexact

in order to run only the first test ?

I know that I can do something like 

pytest test_johndoe.py::test_one but that makes a different syntax for running a specific test and running a group of them

Do pytest test_johndoe.py -k one and not onetwo and not onetwothree is not an option for obvious reasons

Any ideas ?

PS: Keep the good job with pytest amazing framework !!!

**Comment by blueyed** [comment]
> pytest test_johndoe.py -k one -matchexact

You would need `-k test_one` here then.

Maybe modifiers like `^` and `$` could be used, so that `-k '^test_one$'` would work?
Could regexp be supported in general?  How would it work with `and`, e.g. in `-k 'foo and bar'`?

I usually find the `test_johndoe.py::test_one` to be the best in this case.

**Comment by RonnyPfannschmidt** [comment]
`-k` is for matching parts of keywords, we pretty much cant expand it without breaking prior usages so it should stay as is and eventually be removed
