### ISSUE TITLE
optimize travis builds

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#3502]
followup to #3485

we should reduce the build time for travis builds,
il## investigate the speed for the linting env and various others as well

**Comment by asottile** [comment]
For speeding up the linting env, I've found this to be helpful:
- [.travis.yml](https://github.com/pre-commit/pre-commit/blob/4e27dbddf01bf2474e0f905aa40d3d47bf38b453/.travis.yml#L33)
- [appveyor.yml](https://github.com/pre-commit/pre-commit/blob/4e27dbddf01bf2474e0f905aa40d3d47bf38b453/appveyor.yml#L28)
