### ISSUE TITLE
Pytest fails because of pytest_django

### ISSUE THREAD

**Issue by harry-7** [pytest-dev/pytest#3508]
- I installed both pytest and pytest-django libraries in my laptop. Then I wanted to run pytest in a folder in which tests have no dependency of django.
  * Expected: I expected everything to run smoothing
  * What actually happeened? pytest failed with the error 
```
django.core.exceptions.ImproperlyConfigured:` Requested settings, but settings are not configured.
You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

- Pytest version:  3.5.1, Operating System :  Ubuntu Linux 18.04 LTS

I don't know whether this is an intended feature or a bug.

**Comment by nicoddemus** [comment]
Seems to me like this is [pytest-django](https://github.com/pytest-dev/pytest-django) specific, would you mind report this issue there? Thanks!
