### ISSUE TITLE
pytest_pyfunc_call hookwrapper not called with tests that subclass unittest.TestCase

### ISSUE THREAD

**Issue by lita** [pytest-dev/pytest#3550]
I am in the middle of writing a pytest plugin and noticed that `pytest_pyfunc_call` is not called on tests that have `unittest.TestCase` subclassed. This method is called correctly when the test class subclasses `object` or just plain function tests.

I have created a simple example to explain the bug.

conftest.py
```python
@pytest.hookimpl(hookwrapper=True)
def pytest_pyfunc_call(pyfuncitem):
    outcome = yield

    try:
        outcome.get_result()  # will raise if outcome was exception
        print('success')
    except Exception:
        print('Failed')
```

```test.py
import unittest


class TestStupid(unittest.TestCase):
    def test_a(self):
        assert 1 == 1


    def test_b(self):
        assert 2 == 2


    def test_error(self):
        assert 2 != 2
```

I am using pytest==3.6.1 on Python 3.6. Tried it on a Mac and Ubuntu Trusty.

I can get around the issue by using `pytest_runtest_setup` and `pytest_runtest_teardown` but unable to get the result of the test this way.

**Comment by nicoddemus** [comment]
Hi @lita,

Indeed it is not called because we rely on the underlying `unittest` mechanism to execute the actual function call, and it doesn't know about pytest hooks. 

I'm afraid this is not fixable by design.
