### ISSUE TITLE
Order of execution of fixtures

### ISSUE THREAD

**Issue by LexLootor** [pytest-dev/pytest#3596]
In version  of pytest 3.5.0 appeared execution of fixtures by higher scope. #3306 

But I need to use autouse fixture with scope=function first, at least before fixtures with other scope and without autouse. There are any possibilities to do this?

```
def test_1(fixture_module):
    assert True

@pytest.fixture(autouse=True, scope="function")
def fixture_function():
    print("scope function")

@pytest.fixture(scope="module")
def fixture_module():
    print("scope module")
```

Code output:
```
scope module
scope function
```

pytest version 3.6.0
On version 3.2.2 this example work in this order:
```
scope function
scope module
```

**Comment by nicoddemus** [comment]
Hi @LexLootor,

Unfortunately I don't think there's a way to override the order, currently all functions are instantiated based on their scope.

Can you describe in more details what your fixtures do exactly? We might able to provide alternatives based on that information.

**Comment by LexLootor** [comment]
Hello @nicoddemus, thank you for answer. 

I found solution for me in hook pytest_runtest_setup. 

I think if there are no way to override the order, i can close this issues.
