### ISSUE TITLE
Add ability to use globs when using --ignore

### ISSUE THREAD

**Issue by machinekoder** [pytest-dev/pytest#3711]
There is no command line option for pytest to ignore a specific directory pattern.

For example:

```
-- code.py
-- tests
---- test_code.py
---- integration
------ test_code_integration.py
```

I would like to disable all integration tests.

The argument `--ignore=integration` does not work.

I have also tried `-k="not integration"` which works, but for some reason is ignored when executing pytest via `pytest.main`.

Note: Of couse I could specify the full path using the `--ignore` argument, but the actual project is much more complex and contains many `tests` and `integration` folders.

**Comment by nicoddemus** [comment]
Thanks @machinekoder for the suggestion.

I've labeled this as an improvement, given that what you describe a feature request. Your title alone suggests that this is a bug though, could you please rephrase it? Something along the lines of *Add ability to use globs when using --ignore*, which better conveys that this is a feature request. Thanks!

**Comment by asottile** [comment]
@machinekoder could you show how you're invoking `pytest.main` - - I expect it to work the same there too
