### ISSUE TITLE
pdb: report test location / integrate pytest-pdb

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#3725]
When pdb gets invoked it would be useful to report the test location already.

See https://github.com/fschulze/pytest-pdb/pull/5 where I've added methods for pytest-pdb to go to the current test etc.

It would be nice if pytest could provide this functionality by itself already, and especially report the location/status when pdb kicks in (via the "PDB set_trace (IO-capturing turned off)" message).

/cc @fschulze

**Comment by fschulze** [comment]
> When pdb gets invoked it would be useful to report the test location already.

That's a great idea and works beautifully. I just added it to pytest-pdb (no release yet).

**Comment by blueyed** [comment]
JFI: a new release was created, thanks!

**Comment by blueyed** [comment]
JFI: I find the displaying of it by default too distracting, and reverted it for me (https://github.com/blueyed/pytest-pdb/commit/ccf733aeb20ae3cc5bf807bfe8855b4c1efa3c61).
`wt` / `whichtest` is still useful, of course.
