### ISSUE TITLE
Turn off (parts of) GitMate

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#3743]
So, we've been running GitMate for a while, and I'd propose to turn at least two features of it off:

- Linking "related" issues. From what I've seen so far, it links some 5 mostly random issues in every issue. It's not helpful at all, and also means cross-links between issues (i.e. related issues you see when looking at an issue) become useless.
- Adding labels. Those turn out to be mostly wrong as well from what I've seen, and it's repeatedly removed the proper labels (which have been added by humans). See e.g. https://gitlab.com/gitmate/open-source/gitmate-2/issues/378 but I'm pretty sure there's an older issue I opened as well.

Not sure if there are still other GitMate features we use at that point...

Opinions?

**Comment by RonnyPfannschmidt** [comment]
i disabled gitmate for all pytest related projects as we only used those 2 functions

**Comment by The-Compiler** [comment]
I guess this can be closed then :wink: FWIW I still use it for qutebrowser, but only the PR related features ("review needed" label, applying label issues to the PR).
