### ISSUE TITLE
internally dependent n gcc package and thereby on python.h

### ISSUE THREAD

**Issue by khimanshu** [pytest-dev/pytest#3750]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [x] Minimal example if possible
the latest version 3.7.0 requires gcc and which in turn requires a header file python.h. I did not need these when I used older version I.e. 3.6.4.

![issue1](https://user-images.githubusercontent.com/10536398/43481667-6fd4b6de-94bb-11e8-9fed-fafac3641f97.png)
build failure

![solution2](https://user-images.githubusercontent.com/10536398/43481769-b94776c6-94bb-11e8-8d86-ecd52adfc126.png)
build success with older version

**Comment by RonnyPfannschmidt** [comment]
it seems the issue can be solved by supporting building without the extension in that package

**Comment by omgjlk** [comment]
I ran into this, which broke my CI for a while. I had to chase down exactly what was dragging in scanlib (because that info isn't really shown when things go south). For now I'm pinning down to below pydev 3.7.0 until this gets resolved.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/benhoyt/scandir/pull/106 should fix it

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus in https://github.com/benhoyt/scandir/issues/105#issuecomment-409446613 it was demonstrated - the pr i linked needs to be merged and released

**Comment by nicoddemus** [comment]
Great, thanks for the link!

**Comment by nicoddemus** [comment]
This should have been fix with `scandir 1.8`, just released to PyPI. Please let us know if it still doesn't work.

**Comment by JonSchuff** [comment]
@nicoddemus we're seeing the following warning on both 2.7.12 and 2.7.15 before pip fails the build:

> /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'

Looks like the `optional` kwarg for Extension is only supported in python 3 :(

**Comment by RonnyPfannschmidt** [comment]
@JonSchuff good find, please install setuptools first, i will push a pr in a bit to scandir

**Comment by JonSchuff** [comment]
Great thx @RonnyPfannschmidt 

Tested it with setuptools==20.1.1 as well as the latest, but both runs yielded the same result as above

**Comment by RonnyPfannschmidt** [comment]
https://github.com/benhoyt/scandir/pull/107 is supposed to sort out that oversight

**Comment by nicoddemus** [comment]
`scandir-1.9.0` (just released) should fix this, so I'm closing this but please let us know if that's not the case so we can reopen this issue.
