### ISSUE TITLE
Generating valid mark names dynamically?

### ISSUE THREAD

**Issue by anowlcalledjosh** [pytest-dev/pytest#3759]
I'm parametrizing one of my tests over several versions of an external tool, and I'd like to add a mark to each of the parametrized tests so I can easily run tests for a particular version (e.g. `pytest -m v4_0_5_0`). Is there a pytest-provided way to escape an arbitrary string into a valid mark name? It looks like they have to be valid Python identifiers, so I've hacked up a function to ensure the first character is a letter and replace all other non-alphanumeric characters with an underscore, but it would be nice if it were a little easier to add dynamically-generated marks to parametrized tests.

**Comment by Zac-HD** [comment]
> Is there a pytest-provided way to escape an arbitrary string into a valid mark name?

No, but hacking your own sounds like a decent solution 😄
