### ISSUE TITLE
 KeyError: 'features'

### ISSUE THREAD

**Issue by shivaksingh** [pytest-dev/pytest#3766]
I'm using a json file to fetch data from a local folder but it's showing an key error. 
- [ I'm using VS Code ]
- [ pytest version 3.6.1, OS: Ubuntu 16.04]

![screenshot from 2018-08-02 11-34-16](https://user-images.githubusercontent.com/26733899/43565496-7e200f8e-9648-11e8-9d9a-5fe5ab20a421.png)

**Comment by RonnyPfannschmidt** [comment]
that error is clearly in your code and unrelated to pytest - its not clear what pytest can do there

**Comment by shivaksingh** [comment]
@RonnyPfannschmidt  I'm sorry I just realized what you meant, you were right my bad.
Apologies for waisting your time.
