### ISSUE TITLE
Pytest 3.7 not collecting tests on mixed Package and Modules

### ISSUE THREAD

**Issue by ZaiusDR** [pytest-dev/pytest#3768]
Hi!

I've found an issue with pytest 3.7 while collecting tests on a mixed Python packages and modules folder structure, which worked correctly on previous versions of pytest. For instance if I setup a folder structure like this:

```
.
└── src
    ├── folder_1
    │   └── test
    │       └── test_1.py
    └── folder_2
        └── test
            └── test_2.py
```

Each `test_*.py` file containing a dummy test like:

```
def test_1():
    assert True
```

pytest collects tests correctly:

```
$ py.test --collect-only
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 2.7.10, pytest-3.7.0, py-1.5.4, pluggy-0.7.1
rootdir: /Users/eduardo/tests, inifile:
collected 2 items
<Module 'src/folder_1/test/test_1.py'>
  <Function 'test_1'>
<Module 'src/folder_2/test/test_2.py'>
  <Function 'test_2'>

======================================================================================= no tests ran in 0.05 seconds =======================================================================================
```

However if I convert one of the folders to a Python package, only the tests inside that folder are being collected:

```
.
└── src
    ├── __init__.py
    ├── folder_1
    │   ├── __init__.py
    │   └── test
    │       └── test_1.py
    └── folder_2
        └── test
            └── test_2.py
```

```
$ py.test --collect-only
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 2.7.10, pytest-3.7.0, py-1.5.4, pluggy-0.7.1
rootdir: /Users/eduardo/tests, inifile:
collected 1 item
<Package '/Users/eduardo/tests/src'>
  <Package '/Users/eduardo/tests/src/folder_1'>
    <Module 'test_1.py'>
      <Function 'test_1'>

======================================================================================= no tests ran in 0.03 seconds =======================================================================================
```

I'm not pretty sure if this is the intended behaviour or not.

---------------------------------------------------------------------
Debugging info:

`pip list` (fresh venv tested with python2.7 and 3.6 with same results)
```
$ pip list
Package        Version
-------------- -------
atomicwrites   1.1.5
attrs          18.1.0
funcsigs       1.0.2
more-itertools 4.3.0
pathlib2       2.3.2
pip            18.0
pluggy         0.7.1
py             1.5.4
pytest         3.7.0
scandir        1.7
setuptools     40.0.0
six            1.11.0
wheel          0.31.1
```

**Comment by nicoddemus** [comment]
Thanks @ZaiusDR for the report, we appreciate it.

@jonozzz

**Comment by nicoddemus** [comment]
I can confirm that unfortunately this bug still exists on `master` (and soon to be released `3.7.1`).

**Comment by jonozzz** [comment]
I think I thought about this corner case and decided to not look at anything that's not part of a package, from inside a package. Will take a look and see if there's an easy fix.

**Comment by jonozzz** [comment]
`py.test --collect-only src` would produce the expected behavior though.

**Comment by ZaiusDR** [comment]
Hey guys, would you be interested in a "minimum expected test number" feature? I mean, if something like this issue happens, it can be oversight. Maybe with a parameter to indicate a minimum number of tests ran it would be easier to notice that some of the tests haven't been executed. I could try to work on that and make a PR for you if you want.
