### ISSUE TITLE
Best way to apply parameterization to test functions quickly and efficiently. 

### ISSUE THREAD

**Issue by Drew-Ack** [pytest-dev/pytest#3770]
Its time to start having test functions use two different logins. 

Example:

```
def test_MainPageNavigation()
    login_function(username, password)
    .... test case stuff
```

To start using multiple users I then added parameterization. 

```
@pytest.mark.parameterization
@pytest.mark.parametrize("username,password", [
    ("username_one", "password_one"),
    ("username_two", "password_two")
])
def test_MainPageNavigation(username, password):
    login_function(username, password)
    .... test case stuff
```

The problems:

1. Hundreds of test cases that need to use this parameterization.
2. Some test cases that do not need this paramaterization.
3. What happens if a password pemanantly changes? I dont want to go through 100's of tests to change the parameter set. 

Solutions:

1. Make a user class for these parameter sets. That way all users are pulled from one spot. 

Questions:

1. Is there a way I can make a custom decorator that then applies the above paramaterize mark? Something like:

@login_params

Then I can manually apply this mark where I need and its a layer of abstraction i can work with.

**Comment by nicoddemus** [comment]
The `@login_params` approach you suggest is possible today:

```python
login_params = pytest.mark.parametrize("username,password", [
    ("username_one", "password_one"),
    ("username_two", "password_two")
])

...

@login_params
def test_MainPageNavigation(username, password):
```

Another solution is to use a parametrized fixture:

```python
@pytest.fixture(params=[
    ("username_one", "password_one"),
    ("username_two", "password_two"),
])
def user_and_pass(request):
    return request.param


...

def test_MainPageNavigation(user_and_pass):
    username, password = user_and_pass

```

**Comment by Drew-Ack** [comment]
The second solution, parametrized fixture, how does Pytest realize that it needs to run the function twice?

**Comment by nicoddemus** [comment]
Because the fixture is parametrized with two values, so pytest knows that it needs to instantiate `user_and_pass` twice, hence the tests will end up being parametrized as well.

**Comment by Drew-Ack** [comment]
I completely forgot about that fixture feature. 
Thank you

**Comment by Drew-Ack** [comment]
Is there a way to apply multiple sets of paramatrize marks to one function? 

@username_one_mark
@username_two_mark
def test_function()
...


From what ive looked at there is not, even though i remember Marks are additive.

**Comment by SalmonMode** [comment]
I would recommend the parameterized fixtures approach. Using `pytest.mark.parametrize`, as far as I know, is only supported for test functions. For your test though, anything that requests a parametrized fixture will happen once per param set. If it has a request to multiple parameterized fixtures, you will get a cartesian product of all the params, and the test will be run once per set still. For example, if you have these fixtures with this test:

```python
@pytest.fixture(scope="class", params=["a", "b"])
def fix_1(request):
    return request.param

@pytest.fixture(scope="class", params=["x", "y"])
def fix_2(request):
    return request.param

def test_it(fix_1, fix_2):
    assert True
```

you'll get the following tests:

```
test_it[x-a]
test_it[x-b]
test_it[y-a]
test_it[y-b]
```


This also scales up to larger scopes, so you can parametrize whole classes/modules/packages/sessions, and fixtures can also request parameterized fixtures .

Hope this helps!

**Comment by Zac-HD** [comment]
> Is there a way to apply multiple sets of parametrize marks to one function?  From what I've looked at there is not, even though I remember Marks are additive.

Unfortunately, `@parametrize` can only be applied once per argument.
