### ISSUE TITLE
Pytest 3.7.1 is not collecting `__init__.py` files

### ISSUE THREAD

**Issue by deeechun** [pytest-dev/pytest#3773]
Hi! I seem to have run into a bug on the latest build. Pytest is not collecting `__init__.py` files, even after specifying `python_files` to `*.py` in `pytest.ini`. I have all of my test functions named correctly, starting with `test_*` as well.

Here is a quick example.

Tree:

```
tests/
├── __init__.py
├── sample
│   ├── __init__.py
│   └── sample_test.py
```

Command + output:
```
pytest --collect-only tests/sample/
============================= test session starts ==============================
platform linux -- Python 3.7.0, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
rootdir: /home/deebs/playground/radish_steps, inifile: pytest.ini
collected 1 item                                                               
<Module 'tests/sample/sample_test.py'>
  <Function 'test_sample'>

========================= no tests ran in 0.02 seconds =========================
```

If you need any more details, please feel free to reach out

**Comment by nicoddemus** [comment]
Thanks for the report @deeechun!

**Comment by jonozzz** [comment]
Wait a minute, maybe I'm not understanding this correctly. Are you expecting it to collect tests from __init__.py? If so, then it's not a regression. pytest==3.6 didn't have this feature either.

What's the contents of tests/sample/__init__.py and what would you expect the output to be?

**Comment by deeechun** [comment]
Hey @jonozzz, sorry for the late reply. This worked correctly pre 3.7! The contents were something like this:

__init__.py
```def test_something():
    print('##########')
    print('##########')
    print('i've done it!')
    print('##########')
    print('##########')```

Tests were collected and run as long as i chang the `python_files` config to `*.py`.

**Comment by jonozzz** [comment]
Ah, you're right. I was missing the `python_files` setting.

**Comment by nicoddemus** [comment]
This was closed but the final code does not contain the fix, reopening.
