### ISSUE TITLE
Importing module of pytest plugin triggers a PluginValidationError: unknown hook

### ISSUE THREAD

**Issue by abotalov** [pytest-dev/pytest#3775]
I use Pytest 3.6.4.

When I import `from pytest_selenium import pytest_selenium` and then use `pytest_selenium` in conftest.py I get `PluginValidationError: unknown hook`.

This error has been also encountered by some users:
* https://github.com/jantman/biweeklybudget/commit/81845710a0b8ef4574e1516ab1a583f65459259b
* https://github.com/pytest-dev/pytest-django/issues/607
* https://github.com/shawnbrown/datatest/commit/5ad76f3171f159d678cf271625cd833fdd031c5a

How is one expected to deal with it?

**Comment by nicoddemus** [comment]
Hi @abotalov,

One way is to rename the module to something else that doesn't have the `pytest_` prefix:

```python
from pytest_selenium import pytest_selenium as pselenium
```

I suppose `pluggy` could check if the object is actually callable to consider it as a candidate for a hook, which would work for this case.

cc @RonnyPfannschmidt @tgoodlet

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pluggy/issues/91 should have fixed it via https://github.com/pytest-dev/pluggy/issues/17 and https://github.com/pytest-dev/pluggy/commit/ca39b4bec195da030cfa0bf85650a339cf2c1d21
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L264 might be at fault
