### ISSUE TITLE
deprecate the builtin junitxml module and plan for moving it to a external plugin

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#3777]
followup to  #1126 

junitxml in pytest itself is broken and not seeing any real maintenance, as such it should be considered for removal from the core

- [ ] create a timeline
- [ ] create a external copy of the plugin that may replace/superseed the building plugin
- [ ] deprecate the builtin plugin
- [ ] remove the builting plugin

as the plugin is not part of the public api, it can be turned into a required dependency even in a minor release without needing to have a breaking release

it can however only turned into a optional thing by a major release

**Comment by nicoddemus** [comment]
Not sure I like the idea of the core depending on an external plugin, because the external plugin will also depend on pytest.

**Comment by rustyhowell** [comment]
I wouldn't mind taking a stab at updating and maintaining junitxml. I depend on this feature for work and am currently stuck on older Junit test report plugin in Jenkins because the newest one changes schema. I hastily submitted a merge request a few days ago, but it's clear that more thought has to be involved here.

**Comment by RonnyPfannschmidt** [comment]
@rustyhowell i'd like to coordinate this on the ml

i'd really like to get into a place where the junitxml plugin is aware of flavors and versions, and able to function in a context where pytest was executed logging serialized reports, and then using those reports to genrate the junitxml

**Comment by nicoddemus** [comment]
@rustyhowell has the new `junit_family` option been working for you?

**Comment by nicoddemus** [comment]
Closing this the plugin has seen both interest and maintenance in the last releases, so it seems it should stay on the core (for now).
