### ISSUE TITLE
pytest.mark.skipif failed if relays on outpof of request.config.getoption

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest#3783]
Hi,

I have a usecase where I need to use external output files to parser a file I'm working on (it's the SUT, system under test parameters) and one of it's values will indicate if a test could be skipped or not.

the problem is that if I use pytest.mark.skipif(output_from_pytest_get_adoption) the statement failed due to 'NoneType' error.

any idea what to do?

**Comment by nicoddemus** [comment]
Closing as this has not seen activity in awhile.
