### ISSUE TITLE
Option to disable plugin autoload entirely

### ISSUE THREAD

**Issue by hsoft** [pytest-dev/pytest#3784]
I'm wondering what you would think about adding a new option to entirely disable the auto-loading of plugins though setuptools entrypoints, either through a command line argument or through an environment variable.

Test runs don't always run in isolated environments and there are some disruptive pytest plugins out there such as [pytest-relaxed](https://github.com/bitprophet/pytest-relaxed) that will break test runs of projects that aren't made for it.

We get this problem in Gentoo when running some packages in test mode, as we can see [in this issue](https://bugs.gentoo.org/661218). We're patching things around to make things work, but really, the most elegant way to solve this problem would be if we could somehow disable autoloading entirely and explicitly load required plugins for each package.

Would a PR that add this feature be welcome?

**Comment by RonnyPfannschmidt** [comment]
,i recall planning for this in another issue in order to prevent unbounded loading of plugins and to give people control

**Comment by hsoft** [comment]
@RonnyPfannschmidt oh, sorry if this is a duplicate. I searched opened and closed issue but didn't find anything that looked like this.

**Comment by RonnyPfannschmidt** [comment]
@hsoft its good to have this explicit and in the open now - if its unfindable, its easy to loose it ^^

**Comment by hsoft** [comment]
(hum, sorry for the commit spam)

So here's a tentative PR that gives an idea of what's involved in adding this feature.

**Comment by nicoddemus** [comment]
Fixed in #3787
