### ISSUE TITLE
Changing the final log message

### ISSUE THREAD

**Issue by abhishekarya286** [pytest-dev/pytest#3786]
I would like to customize the final log message that gets printed on my terminal after I run all the tests.

`==================== 2 failed in 0.02 seconds =====================`.

Is this possible?

`pytest-version = 3.6.2`

**Comment by abhishekarya286** [comment]
Hi @RonnyPfannschmidt. Actually, I'm using pytest to run benchmarks and not tests. So, I want to change the final message so that it looks appropriate when I run benchmarks.

**Comment by abhishekarya286** [comment]
Also, if you can tell me where in code this statement is executed which prints this final message. That will be quite great. I'm finding it a bit difficult to find it in pytest's code. Can you explain what happens when I run `pytest test_file.py` at the backend?
Thanks.

**Comment by tgoodlet** [comment]
>Can you explain what happens when I run pytest test_file.py at the backend?
Thanks.

@abhishekarya286 as mentioned in [the gitter channel](https://gitter.im/pytest-dev/pytest?at=5b68675c945df30dc15f30cb) you likely will want to read:

- [standard test discovery rules](https://docs.pytest.org/en/latest/goodpractices.html#conventions-for-python-test-discovery)
- [`--collect-only`](https://docs.pytest.org/en/latest/example/pythoncollection.html#finding-out-what-is-collected) flag usage

**Comment by hoangphucITJP** [comment]
@abhishekarya286 , You can check here:
https://github.com/pytest-dev/pytest/blob/308d789d9246a9beb97e935c4ce3efc615a66f71/src/_pytest/terminal.py#L456

**Comment by hoangphucITJP** [comment]
@abhishekarya286 Ah, sorry! Here is the correct part
https://github.com/pytest-dev/pytest/blob/308d789d9246a9beb97e935c4ce3efc615a66f71/src/_pytest/terminal.py#L766
