### ISSUE TITLE
Attribute error in TestCaseFunction.teardown when exception encountered before TestCaseFunction.setup is run.

### ISSUE THREAD

**Issue by westhomas** [pytest-dev/pytest#3788]
The sample code below raises an exception in a unittest.TestCase class in the `__init__` method. This will produce an exception in `TestCaseFunction.teardown()` because `self._testcase` isn't defined, but `teardown()` attempts to call it here: https://github.com/pytest-dev/pytest/blob/cbaa7dd56a685c887e25d4c94b62aa49e8a6a0ca/src/_pytest/unittest.py#L97

```python
# cat test_setup_exception.py
import unittest
import pytest


class MuhUnitTests(unittest.TestCase):

    def __init__(self):
        raise Exception("testing123")

    def test_passing(self):
        assert True


# Execute Tests
def main():
    pytest.main(['test_setup_exception.py', '-s'])


if __name__ == '__main__':
    main()
```

```
self = <TestCaseFunction 'test_passing'>

    def teardown(self):
>       if hasattr(self._testcase, "teardown_method"):
E       AttributeError: 'TestCaseFunction' object has no attribute '_testcase'

../python3.6/site-packages/_pytest/unittest.py:96: AttributeError
```

Adding a check in teardown for existence of _testcase solves the issue and allows the exception to bubble correctly:

```python
    def teardown(self):
        if hasattr(self, "_testcase") and hasattr(self._testcase, "teardown_method"):
            self._testcase.teardown_method(self._obj)
        # Allow garbage collection on TestCase instance attributes.
        self._testcase = None
        self._obj = None
```

**Comment by westhomas** [comment]
Submitted: https://github.com/pytest-dev/pytest/pull/3792

**Comment by RonnyPfannschmidt** [comment]
i believe we should instead ensure that a unittestcase never is in a state where that attribute is missing

**Comment by westhomas** [comment]
You'd have to at least move ` self._testcase = self.parent.obj(self.name)` from the `setup()` method into the `__init__()` method.

But I'm not sure of the impact of that change or whether more of the `setup()` method should be moved as well. That's above my pay grade ;-)

**Comment by RonnyPfannschmidt** [comment]
@westhomas existence of the attribute doesn`t imply the actual value - if its set to `None` in `__init__` it should be fine

i believe even a hack like setting it on the actual class as class level attribute would suffice

**Comment by westhomas** [comment]
@RonnyPfannschmidt Good call. Remade PR and added unit test:

**Comment by bindupatnaik** [comment]
I have same issue when i am trying to use __init__ method in pytest class. I tried to un-install and install the pytest to get the latest code fix of the bug. But unfortunately i am not seeing above code fix in my local .
I am using 
PS C:\Test\Win10DA> pytest --version
This is pytest version 3.7.1, imported from c:\program files (x86)\python36-32\lib\site-packages\pytest.py

Can anyone guide me how to overcome the problem?
my code looks like below

*******************************
import unittest
from com.xxx.Main import Main
class GUI_tests(unittest.TestCase):

def __init__(self):
        self.main = Main()
        self.logger = logging

    def setUp(self):
        pass
        
    def tearDown(self):
        pass
    
    def test_1(self):
          assert True
        
    def test_2(self):
          assert True
