### ISSUE TITLE
Advice on parametrization using values obtained from a fixture

### ISSUE THREAD

**Issue by danieljacobs1** [pytest-dev/pytest#3793]
Hi,

I'd like to ask for some help/advice on parametrizing some tests.

We have a Flask app that is instantiated in a testing configuration by a test fixture we have written. One of the things we want to test is that the URL routes in the app don't have any "bad" characters.

At the moment, we have a single test method that uses the Flask app fixture, gets the full list of routes and tests that entire list. While this does the job, the test feels ungainly and cumbersome.

Ideally, I'd like to refactor this test so that it tests a single URL route at a time rather than the whole list, and parametrize this somehow.

I've experimented with `pytest_generate_tests`,  parametrized tests and parametrized fixtures, but haven't been able to figure out a way to use the Flask app fixture in them.

The nearest I've managed (which still doesn't use the Flask app fixture) is to create an app factory that caches the instance of the Flask app and use that app factory in both the Flask app fixture and in the parametrized fixture that gives the routes. However, this feels ugly and I feel like I've overlooked something in the pytest API. Is there some way to use the Flask app fixture to get the routes?

Thanks in advance for any advice.

Example code:
```python
# conftest.py
import pytest


class App:
    """ Simulate creation of a Flask app; this could be any object in reality
        not only a Flask app.
    """
    def __init__(self, name):
        self._name = name

    def routes(self):
        """ Return a list of routes
        """
        # In real life, this is a function that takes a Flask app instance,
        # rather than being a method on the Flask app.
        return [
            "/".join([self._name, "route", str(index)])
            for index in range(1, 10)
        ]

    @property
    def name(self):
        """ Get the app name
        """
        return self._name


def app_factory():
    """ Create an App
    """
    # This is ugly. We cache the App instance on this function, so that
    # the entire test run only uses that single instance.

    if not hasattr(app_factory, "_app"):
        setattr(app_factory, "_app", App("test-config"))

    return getattr(app_factory, "_app")


@pytest.fixture(scope="session")
def test_app():
    """ Fixture yield the App configured for testing env.
    """
    app = app_factory()
    yield app


# Here, we use the app_factory().routes()
# Is it possible to use the test_app fixture here somehow to
# get the routes?
@pytest.fixture(scope="function", params=app_factory().routes())
def route(request):
    """ Fixture yield the App configure for testing env.
    """
    yield request.param
```

```python
# test_param.py

def test_routes(route):
    """ Test that test-config is in route
    """
    assert "test-config" in route
```

**Comment by Zac-HD** [comment]
Closing as inactive, sorry.  I'd suggest trying https://stackoverflow.com/questions/tagged/pytest

**Comment by danieljacobs1** [comment]
For reference, someone else got there first with an [almost identical question on SO](https://stackoverflow.com/questions/54105134/pytest-fixture-with-parametrization-from-another-fixture) but no answer as yet.

**Comment by nicoddemus** [comment]
Hi @danieljacobs1,

Sorry for not answering earlier, must have missed it.

Given that the object providing the routes() will also be the result of a fixture, it needs to be created during collection time, so caching like you did feels like a small hack but I don't think there's a much better way to do than the way you did.

You can perhaps also try `pytest-subtests`, which allow you to have multiple reports per test, but the plugin is in very early stages.
