### ISSUE TITLE
Pytest hangs when passing multiple user-defined fixtures to a single test function

### ISSUE THREAD

**Issue by ajbois24** [pytest-dev/pytest#3811]
I'm trying to create a test module using parameterization through `conftest.py`. When I try to call multiple fixtures into a single test function Pytest will hang on `collected 0 items`. I'll wait for several minutes on a test that should take a few seconds to execute, and nothing happens.

Code example:
```python
# from conftest.py
variable_names = ["list of var names as strings"]

@pytest.fixture(scope='session')
def test_fixture():
    # Some code
    # argvalues is a nested list of values
    # idlist is a nested list of indices
    return [argvalues, idlist]

def pytest_generate_tests(metafunc):
    for ind,value in enumerate(variable_names):
        if value in metafunc.fixturenames:
            metafunc.parametrize(value, test_fixture[0][ind], ids=test_fixture[1][ind])
```
And from my test module:
```python
# from test_module.py
def test_compare(varname_1, varname_2):
    # varname_1 and varname_2 come from variable_names
    assert varname_1 == varname_2
```
When I run pytest:
```
pytest test_module.py
============================== test session starts ==============================
platform win32 -- Python 3.6.4, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: "directory name"
plugins: hypothesis-3.38.5
collected 0 items
```
This is all I'll get before I keyboard out. Is there something wrong with how I set up my test? If I concatenate what I want to test into one fixture name it works fine, but that's not ideal for my case. I just have no clue what is causing it to take so long to collect.

**Comment by Zac-HD** [comment]
Closing as inactive :cry:
