### ISSUE TITLE
Cannot recognize the command genscript

### ISSUE THREAD

**Issue by echo557** [pytest-dev/pytest#3812]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible
D:\Work\Django\Interface>py.test --genscript=runtests.py
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --genscript=runtests.py
  inifile: None
  rootdir: D:\Work\Django\Interface

**Comment by RonnyPfannschmidt** [comment]
https://docs.pytest.org/en/latest/changelog.html#id429 - genscript has been removed in pytest `3.0.0`
