### ISSUE TITLE
Collection behavior different for path vs. file

### ISSUE THREAD

**Issue by chris-greenlight** [pytest-dev/pytest#3820]
I have a file structure like this: `oobleck/format/posted_transaction.py`

`posted_transaction.py` includes both doctests and a separate `test_Something` function.

When I run pytest with the directory as the parameter like `pytest oobleck/format/`, the doctests are collected but the test_ function is not.  When I run pytest with the file as the parameter like `pytest oobleck/format/posted_transaction.py`, the doctests and the test_ function are collected.

Here's the console:

```
$ pytest oobleck/format/
========== test session starts ==========
platform darwin -- Python 2.7.15, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
collected 2 items

oobleck/format/posted_transaction.py::oobleck.format.posted_transaction.PostedTransaction PASSED
oobleck/format/posted_transaction.py::oobleck.format.posted_transaction._Loader PASSED
```

```
$ pytest oobleck/format/posted_transaction.py
========== test session starts ==========
platform darwin -- Python 2.7.15, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
collected 3 items

oobleck/format/posted_transaction.py::oobleck.format.posted_transaction.PostedTransaction PASSED
oobleck/format/posted_transaction.py::oobleck.format.posted_transaction._Loader PASSED
oobleck/format/posted_transaction.py::test_PostedTransaction PASSED
```

And here is the contents of pytest.ini:

```ini
[pytest]
addopts =
    --doctest-modules
    --verbose
    --cov
    --cov-report=html
    --cov-config=pycoverage.ini
```

The collection protocol should be the same whether specifying directories or individual files.  However a file gets included in the scan, the tests within that file should be collected the same way.

**Comment by bluetech** [comment]
This is expected, doctests are embedded in code not test files, so the `test_*` filtering etc. does not apply to them.
