### ISSUE TITLE
Glob patterns for multiple python-file patterns fails

### ISSUE THREAD

**Issue by jennirinker** [pytest-dev/pytest#3824]
Background
--------------
I would like `pytest` to run all my tests but also my examples to make sure they still run. So I want the `python_files` to test both `test_*.py` and `example_*.py`. I'm trying to use global pattern matching to get `pytest` to check both, but it doesn't seem to work.

MWE
-------
In my `setup.cfg` file...
```
[tool:pytest]
python_files={example,test}_*.py
```
Now `pytest` discovers neither `test_*` or `example_*`.

pytest and OS
-----------------
Windows 7 - Miniconda3  
pytest: 3.7.1 <pip>

pip list
--------
simplegeneric            0.8.1
six                      1.11.
snowballstemmer          1.2.1
Sphinx                   1.7.6
sphinx-fortran           1.0.1
sphinx-rtd-theme         0.4.1
sphinxcontrib-websupport 1.1.0
spyder-kernels           0.2.6
sqlitedict               1.5.0
testflo                  1.3.0
topfarm                  2.0
tornado                  5.1
traitlets                4.3.2
urllib3                  1.23
utm                      0.4.2
wcwidth                  0.1.7
wheel                    0.31.
wincertstore             0.2
windIO                   0.1

**Comment by jennirinker** [comment]
Found the solution:
`python_files = test_*.py *_test.py testing/*/*.py example_*.py`

I'm leaving the issue open, because it might be nice to change the documentation to clarify the usage of spaces in the `python_files` definition (and that true glob matching doesn't seem to occur).

**Comment by asottile** [comment]
Your `{foo,bar}` syntax is not a feature of globs, but of shell expansion.

**Comment by nicoddemus** [comment]
Yep, here are the docs for how Python interprets globs:

https://docs.python.org/3/library/fnmatch.html#fnmatch.fnmatch

But indeed it would be nice to update the example in [the reference docs](https://docs.pytest.org/en/latest/reference.html#confval-python_files) to add an example on how to use multiple globs. 👍

**Comment by nicoddemus** [comment]
@jennirinker that sounds great!

**Comment by jennirinker** [comment]
Just made the [pull request](https://github.com/pytest-dev/pytest/pull/3856). Sorry it took so long.
