### ISSUE TITLE
Option to use counter instead of percentage for progress

### ISSUE THREAD

**Issue by DanaGoyette** [pytest-dev/pytest#3829]
With pytest (I'm currently using 3.6.1), there's support for showing progress of tests, but when running a collection of 1300 tests, each test contributes very little to the percentage.  I'd prefer to be able to show the bare counter.   Example (with space padding): `test_whatever   [    1/1357]`

In my framework, I'm monkey-patching pytest to get what I want, but it would be more maintainable if pytest supported that style officially.

My current monkey-patch:
```python
    def _get_progress(self):
        """
        Report progress in number of tests, not percentage.
        Since we have thousands of tests, 1% is still several tests.
        """
        collected = self._session.testscollected
        self._PROGRESS_LENGTH = len(' [%d/%d]' % (collected, collected))
        if collected:
            spacing = len(str(collected))
            current = len(self._progress_nodeids_reported)
            fmt = ' [{:%sd}/{}]' % spacing
            return fmt.format(current, collected)
        return ' []'

    TerminalReporter._PROGRESS_LENGTH = len(' [9999/9999]')
    TerminalReporter._get_progress_information_message = _get_progress
```

**Comment by nicoddemus** [comment]
@DanaGoyette I thought about this while developing the feature and imagined using percentages would be more useful, but I of course see the case for a bare counter. It would be great if you would like to contribute a patch with that.

I suspect an ini option would be appropriate: `progress_display_mode=percentage/count`.
