### ISSUE TITLE
Can't assert on xpassed and xfailed in runresult

### ISSUE THREAD

**Issue by wimglenn** [pytest-dev/pytest#3837]
Just need to be added here:

https://github.com/pytest-dev/pytest/blob/28aff051ab88ab055b315f10287a6657c437e47d/src/_pytest/pytester.py#L409

**Comment by RonnyPfannschmidt** [comment]
i invite you to do that and add a test for it as well

**Comment by wimglenn** [comment]
Done already Ronny, just needed to create the issue first to get the issue # for the filename in changelog

**Comment by wimglenn** [comment]
I was trying to use it here:  https://github.com/wimglenn/pytest-custom-report/blob/73cda3603dd096a6e185167d9cd7e94bc2ff54f7/tests/test_custom_report.py#L133-L146

**Comment by RonnyPfannschmidt** [comment]
oh great job then, note that you could have used the # of the pull request as well

**Comment by wimglenn** [comment]
So no need to make the issue if you have a PR ready?

**Comment by RonnyPfannschmidt** [comment]
correct

**Comment by tucked** [comment]
I was looking for this issue, but nothing popped up when I searched for this error:
```
TypeError: assert_outcomes() got an unexpected keyword argument 'xpassed'
```
Maybe it'll help someone in the future.
