### ISSUE TITLE
remove specification of language_version on black pre commit hook

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#3840]
followup to #3839

once black does a release which allows to use any python3 in turn enabling python3.7 and newer we should drop our mirror of their setup

**Comment by asottile** [comment]
Note that `blacken-docs` v0.2.0-1 allows this already 🎉

**Comment by RonnyPfannschmidt** [comment]
@asottile great job :+1:

**Comment by RonnyPfannschmidt** [comment]
@wimglenn thanks for that note - for that one i actually want to open a tox issue
