### ISSUE TITLE
pytest_generate_tests would execute on every test method in module even if args indicating 'module::function'

### ISSUE THREAD

**Issue by truebit** [pytest-dev/pytest#3847]
I defined a `pytest_generate_tests` hook to load a data file with the same name of the test method, like below:
```python
def pytest_generate_tests(metafunc):
    iterator = test_data_generator(metafunc.function.__name__,
                                       Path(metafunc.module.__file__).absolute().parent)
    if 'test_data' in metafunc.fixturenames:
        metafunc.parametrize("test_data", iterator, indirect=True)
```
`test_data_generator` contains 2 arguments, first is the file name and second is the file path, these two args help to locate the test data file.
I used `metafunc.function.__name__` to locate current test method, the find the same name of test data file. It works fine when passing .py test file as argument.

But when I use `test_file::test_method`, this `pytest_generate_tests` hook would execute on every test_method in the test_file.py

Is `pytest_generate_tests` acted as expected or it's a bug? How could I only pass the collected test method name to `pytest_generate_tests`

**Comment by RonnyPfannschmidt** [comment]
this is per design - `pytest_generate_tests` is executed per found test definition

**Comment by truebit** [comment]
Thanks for the quick reply. 
Is there any workaround to only generate test data on selected test method?

**Comment by RonnyPfannschmidt** [comment]
use `pytest.mark.parametrize` -

**Comment by truebit** [comment]
I thought to use `metafunc.config.args`, `matafunc.function.__name__` and `metafunc.module.__file__` to determine if the current function and module is indictated in args, but that's a lot of work to do...

**Comment by truebit** [comment]
finally I used `pyteset_configure` to save the module func pairs to accomplish my requirement. hope below code would help someone:

```
def pytest_configure(config):
    """for args like module::function, save the dict to be used in pytest_generate_tests"""
    args = config.args
    arg_result = {}
    for arg in args:
        if '::' in arg:
            file, method = arg.split('::')
            arg_result.setdefault(Path(file).name, []).append(method)
    config.modulefunc_pairs = arg_result

def pytest_generate_tests(metafunc):

    def is_function_included(module, func, check_dict):
        if not check_dict:
            return True
        module_name = module.name if isinstance(module, Path) else module.name
        if module_name in check_dict.keys():
            if func in check_dict[module_name]:
                return True
            else:
                return False
        else:
            return True

    function_name = metafunc.function.__name__
    module_path = Path(metafunc.module.__file__)

    if 'test_data' in metafunc.fixturenames and is_function_included(module_path, function_name,
                                                                     metafunc.config.modulefunc_pairs)::
        iterator = test_data_generator(metafunc.function.__name__,
                                           Path(metafunc.module.__file__).absolute().parent)
        metafunc.parametrize("test_data", iterator, indirect=True)

```
