### ISSUE TITLE
tests: fix "FD leakage detected" / turn --lsof into error again

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#3879]
There are some "FD leakage detected" errors in builds, and pypy appears to has a lot of them: https://travis-ci.org/pytest-dev/pytest/jobs/420632250#L658

I think CI should fail (at least in one job) in case this happens, i.e. on any warning.

**Comment by RonnyPfannschmidt** [comment]
This breaks builds over things we have no control over

**Comment by blueyed** [comment]
Just noticed that there are likely more with pypy due to the garbage collector being called explicitly?!
https://github.com/blueyed/pytest/blob/84e4909f5bd505a88b8ddf7e0aee191de0f3f631/src/_pytest/pytester.py#L112-L113

**Comment by blueyed** [comment]
@nicoddemus 
This one is not in there though - but it is also not a real warning, but emitted by pytest itself (IIRC): https://github.com/blueyed/pytest/blob/84e4909f5bd505a88b8ddf7e0aee191de0f3f631/tox.ini#L207-L218

**Comment by blueyed** [comment]
Ok, `--lsof` was added in d4fe273b initially, to report and fail on FD leakage, but then later was turned into a warning (see https://github.com/pytest-dev/pytest/issues/2366).
I think there is some real issue here, and that it does not make sense to run it for all tests, if it is only ignored then in the end (it is two subprocesses on top, and the explicit GC for pypy might also be the reason for pypy being slower in general, and especially with coverage tracking).
