### ISSUE TITLE
Reading fixtures from 

### ISSUE THREAD

**Issue by omriben** [pytest-dev/pytest#3890]
I'm working for a long time with all my fixtures written in the **pytest_plugin.py** file and all tests ran fine, but for some unknown reason, pytest can't read this file anymore (even though it's path hasn't changed) - when I try to run my tests they failed because fixtures can't be read ("fixture '' not found")
I tried to change it's name back to **conftest.py** and it did work...

What seems to be the problem? the only different thing is the name...

**Comment by RonnyPfannschmidt** [comment]
based on the provided information my first thought is i am surprised this ever worked

for more we'd have to see more about your project structire

**Comment by omriben** [comment]
OK, problem solved by typing:
export PYTHONPATH=<MY_PROJECT_PATH>

It shouldn't be related to the fixtures but maybe the python runner path was changed and from it's new path didn't "see" the pytest_plugin.py file.
