### ISSUE TITLE
What is the best way to do setup for test functions and test classes

### ISSUE THREAD

**Issue by Drew-Ack** [pytest-dev/pytest#3901]
I was thinking about a way to leverage Pytest for setup and teardown of test cases and test classes. 
The ability to setup and teardown various settings is very important for testing a website. 

Way one, use marks and hooks:

```python
@super_expensive_setup_mark
    def test_Setup_Success():
    .... do stuff
```

Use the pytest_runtest_setup hook to look at the marks applied to the test case and see what setup needs to be perfromed. 

Way Two, use fixtures:

```python
def test_Setup_Success(config): 
     config.super_expensive_setup()
     .... do stuff
```

Way Three, a config class:

```python
def test_Setup_Success():
     config = ConfigClass()
     config.super_expensive_setup()
     .... do stuff
```

Im thinking a combination of marks and hooks is the best option for being able to perform setup and teardown for a test case. 
Is it possible to mark a test class to perform the setup and teardown once for a group of test functions?

**Comment by nicoddemus** [comment]
All the ways you propose are viable. I personally prefer using a fixture, as I think it is more straightforward and easier to understand than mark+hooks.

> Is it possible to mark a test class to perform the setup and teardown once for a group of test functions?

You can use a class-scoped fixture for that.

**Comment by Drew-Ack** [comment]
I will go for that then and report back before closing the issue

**Comment by Drew-Ack** [comment]
@nicoddemus 
After looking into fixtures Ive noticed scaling problems. Am I using them to the best of their ability?

Round 1:
Make a fixture for each changeable setting following pattern 1:

```
@pytest.fixture(scope="function")
def turn_on_locations():
    ... code that turns on location tracking
    yield
    ... code that turns off location tracking. This gets us back to "default" state
```


or pattern 2:
```
@pytest.fixture(scope="function")
def turn_on_locations():
    ... code that turns on location tracking
```

Problems found in round 1:
-  When having 20-30 different settings to test in the application, both pattern 1 and pattern 2 cause a long chain of dependent fixtures to be appended to the test cases signature. 
- Hard to keep track of so many separate fixtures, not even accounting for fixtures that might have to be duplicated to class level scope. 


Round 2:
Make fixtures yield a setup object at class level.

Pattern 3 fixture:
```
@pytest.fixture(scope="class")
def setup_fixture():
    ... Code to instantiate Setup class
    yield SetupClass()
    ... Code that sets everything back to a default known state?
```

Pattern 3 test case:
```
def test_transaction_with_location(setup_fixture):
      setup_fixture.turn_locations_on()
      ... Transaction code
```


I think Pattern 3 is a better alternative to pattern 1 or pattern 2. Im just not sure. 

I also have a few questions that I don't have the experience to answer. 
- What is the best way to change environmental state? 
- Should every test go in and make sure it has the correct state every-time? Or is it better to have tests clean up after themselves and revert state back to default ? 
- Perhaps I'm grouping test cases when I should be breaking them apart?


To reiterate what I am looking for:
```
class TestCheckTransaction(object):
    # Apply settings that all  test functions will need. 

    def test_view_posting_report(setup_fixture):
        # Apply additional settings if needed, or just roll with the ones the test class already applied. 
        # Test Stuff
```

Im trying to find the best case scenario that reduces test case setup and teardown time as its already taking hours to run the test cases themselves.

**Comment by nicoddemus** [comment]
Hi @Drew-Ack,

I was indeed thinking about option 3, having a fixture which returns a "config" object which can be used by tests to change the existing configuration. The fixture can use pytest's [monkeypatch](https://docs.pytest.org/en/latest/reference.html#monkeypatch) fixture to apply the changes in a way that they are all undone automatically at the end of the tests.

One issue with this approach is that `monkeypatch` is function-scoped. If your config loading is slow and you want to make that class-scoped to save time, one way to do this is to create two fixtures, one class or module-scoped fixture which loads the config, and another fixture which is used by the tests to mutate the config object using `monkeypatch`. This way you will load the configuration once, but each test can mutate the configuration object at will, with the changes being undone automatically. 

Something like:

```python

@pytest.fixture(scope='module')
def _prestine_config():  # _ prefix so it is clear that tests should not use it directly
    config = load_config() # slow
    return config

@pytest.fixture
def config(_prestine_config, monkeypatch):
    return TestConfig(prestine_config, monkeypatch)

class TestConfig:
    def __init__(self, prestine_config, monkeypatch):
        ...

    def turn_locations_on(self):
        self.monkeypatch.setattr(self.prestine_config, 'locations', True)


def test_transaction_with_location(config):
   config.turn_locations_on()
   ...   
```

Hope I was clear in the explanation.

Cheers

**Comment by Drew-Ack** [comment]
Thank you, I will look into the monkey patch fixture. 

In the mean time, can I get your advice on this as well? 

1. What is the best way to change environmental state?
2. Should every test go in and make sure it has the correct state every-time? Or is it better to have tests clean up after themselves and revert state back to default ?
3. Perhaps I'm grouping test cases when I should be breaking them apart?
4. How do i account for failures in the setup or teardown phase, settings could be applied and mess up test cases that follow.

**Comment by nicoddemus** [comment]
> What is the best way to change environmental state?

You mean environment variables? `monkeypatch.setenv` does exactly that.

> Should every test go in and make sure it has the correct state every-time? Or is it better to have tests clean up after themselves and revert state back to default ?

Ideally you should not leave for the tests to do it, the fixture should be responsible for that.

> Perhaps I'm grouping test cases when I should be breaking them apart?

Not sure, depends on the actual test suite. Implementing the fixture like I suggest it won't matter much from the POV of state management being correct in terms of tests not leaving garbage that might affect other tests.

> How do i account for failures in the setup or teardown phase, settings could be applied and mess up test cases that follow.

Again the fixture will handle this correctly. 😉

**Comment by Drew-Ack** [comment]
Im sorry, I should've been much more specific. 

How are these issues solved in general. What are good methodologies or steps to follow in general, not just in Pytest.
