### ISSUE TITLE
xfail: mismatch between docs and the actual behaviour

### ISSUE THREAD

**Issue by hoefling** [pytest-dev/pytest#3907]
I know this is kinda nitpicky, but for the sake of completeness:

The docs [state](https://github.com/pytest-dev/pytest/blob/master/doc/en/skipping.rst#raises-parameter):

> If you want to be more specific as to why the test is failing, you can specify a single exception, or a **list of exceptions**, in the ``raises`` argument.

However, the actual implementation of the `xfail` marker expects a tuple instead of a list, raising an internal error otherwise. May I suggest to replace ``list`` with ``tuple`` in the above sentence?

**Comment by nicoddemus** [comment]
Oh good catch @hoefling. Sure, would you like to open a quick PR with that? Thanks!

**Comment by hoefling** [comment]
@nicoddemus with pleasure! My first time proposing a pull request, so please be gentle :-)
