### ISSUE TITLE
Pytest exit codes for command line errors look incorrect

### ISSUE THREAD

**Issue by rdadolf** [pytest-dev/pytest#3913]
According to [the documentation](https://docs.pytest.org/en/latest/usage.html), the CLI return value for a bug on the command line should be 4. From what I can tell, all bugs return 2.

```bash
$ pytest -invalid-
pytest: error: unrecognized arguments: -invalid-
  inifile: None
  rootdir: /tmp
$ echo $?
2
$ pytest -v-v
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument -v/--verbose: ignored explicit argument '-v'
$ echo $?
2
```

It looks like interrupting PyTest does return 2, however:
```
$ pytest xgt_test.py 
================================ test session starts ================================
platform linux2 -- Python 2.7.15rc1, pytest-3.7.2, py-1.5.4, pluggy-0.7.1
rootdir: /gems/build/apps/mygems, inifile:
collected 26 items                                                                  

xgt_test.py EEEEEEEEEEE^C
<snip>
$ echo $?
2
```

System configuration:
```
$ pytest --version
This is pytest version 3.7.2, imported from /usr/local/lib/python2.7/dist-packages/pytest.pyc
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

Happy to answer questions, and apologies if I've misunderstood the intended behavior.

**Comment by crazymerlyn** [comment]
This [line](https://github.com/pytest-dev/pytest/blob/15ede8aab83bd8b8e69298a05a8cd0618d8cf566/src/_pytest/config/argparsing.py#L341) seems to be the culprit.
`argparse.ArgumentParser.error` exits with status code 2.

One possible solution is to override the `error` function and change the status code to `EXIT_USAGEERROR`.
Another is to raise a `UsageError` with an appropriate message.
Not sure which one would be better.

**Comment by nicoddemus** [comment]
I think overriding `error` is simple enough:

```
    def error(self, message):
        """error(message: string)

        Prints a usage message incorporating the message to stderr and
        exits.

        If you override this in a subclass, it should not return -- it
        should either exit or raise an exception.
        """
        self.print_usage(_sys.stderr)
        args = {'prog': self.prog, 'message': message}
        self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
```

**Comment by rdadolf** [comment]
Thanks for the diagnosis and fix, folks. Much appreciated!
