### ISSUE TITLE
junitxml plugin changes discovery method, and attempts to load test files from dependencies.

### ISSUE THREAD

**Issue by daicoden** [pytest-dev/pytest#3916]
pytest runs great, and tests pass in CI. After adding the --junitxml flag, the build breaks.  

I've upgraded to latest (3.7.4) and the failure occurs on both linux and mac. 

Two things happen when you add the junitxml flag:
1) It appears the doctest plugin is attempting to run tests in dependencies.
2) after turning off the doctest plugin, I get failures about development dependency - dependencies are not available, so it appears to be loading test code from direct dependencies.

I use bazel as a build system, so it works slightly differently than dependencies through pip. All the dependencies are put into a sandbox directory, and the PATH variable is modified so the dependencies are available. To use pytest, I import the library and invoke it using the CLI, and that looks like:

```
import os
from os import path

import pytest

if __name__ == "__main__":
   # points to cfht_cli/test
    args = [path.normpath(path.join(os.path.dirname(path.realpath(__file__)), '../'))]
    # Coupled to .circleci/config.yml
    if os.getenv('JUNIT_XML_ROOT_DIR'):
        args = ["--junitxml", os.path.join(os.getenv('JUNIT_XML_ROOT_DIR'), "cfht_cli.xml")]
    exit(pytest.main(args, plugins=['no:cacheprovider']))
```

For debugging, I have changed the arg to run one test file, and turned off doctest, but I still receive failures from files in dependencies.  The crazy thing is, if you don't specify JUNIT_XML_ROOT_DIR then everything passes.

I've tried going through the junitxml code - but maybe you could point me in the right direction. What are some things junitxml might be doing to cause these failures?

If you don't have an aha moment when reading the bug description, you can close this and I'll work on a minimal example.

**Comment by RonnyPfannschmidt** [comment]
im unfamiliar with your tooling, could you show a depth limited folder tree of the CWD of a testrunner call

**Comment by daicoden** [comment]
Roger!

```
Init files are in each folder - put a few in the tree to make it clear.

├── unit.runfiles
│   ├── __init__.py
│   ├── __main__ 
│   │   └── (see below for contents)
│   ├── pypi__PyYAML_3_12
│   │   ├── __init__.py
│   │   ├── PyYAML-3.12.dist-info
│   │   │   ├── __init__.py
│   │   └── yaml
│   │      └── __init__.py
│   ├── pypi__astropy_2_0_1
│   │   ├── astropy
│   │   │   ├── _erfa
│   │   │   │ ...
│   │   └── astropy-2.0.1.dist-info
│   ├── pypi__click_6_6
│   │   ├── click
│   │   └── click-6.6.dist-info
│   ├── pypi__numpy_1_15_1
│   │   ├── numpy
│   │   │   ├── compat
│   │   │   ├── core
               | ....
...

For compaction, the source code is located at:
unit.runfiles/__main__/client_lib/python/cfht_cli

Source is in,
unit.runfiles/__main__/client_lib/python/cfht_cli/src

Test is in:
unit.runfiles/__main__/client_lib/python/cfht_cli/test

Test file is:
__main__/client_lib/python/cfht_cli/test/bin/unit.py
```

then the following is added to python path.

`PYTHON_PATH='__main__/client_lib/python/cfht_cli/src:pypi__numpy_1_15_1:pypi__py_1_6_0:pypi__setuptools_40_2_0:pypi__pytest_3_2_1:pypi__astropy_2_0_1:pypi__PyYAML_3_12:pypi__click_6_6:pypi__MarkupSafe_1_0:pypi__Jinja2_2_10:pypi__Werkzeug_0_14_1:pypi__click_6_7:pypi__itsdangerous_0_24:pypi__Flask_0_12_2:__main__/client_lib/python/cfht_cli/external/pypi__jaraco_functools_1_20:__main__/client_lib/python/cfht_cli/external/pypi__jaraco_classes_1_5:pypi__cheroot_6_4_0:pypi__jaraco_classes_1_5:pypi__portend_2_3:pypi__six_1_11_0:pypi__CherryPy_11_1_0:pypi__backports_functools_lru_cache_1_5:pypi__tempora_1_13:pypi__more_itertools_4_3_0:pypi__pytz_2018_5:__main__/client_lib/python/cfht_cli/test'
`

Lastly, the unit.py is invoked via

`python __main__/client_lib/python/cfht_cli/test/bin/unit.py`


It should be pretty much the same as if each egg was put on disk and individually included. A weird thing I noticed were all the init files, making modules where there aren't normally modules.  But like I mentioned, the PYTHON_PATH variable seems to wire everything up right, because all the tests pass with no junitxml flag.  My theory was that there was python module discovery happening with the junitxml flag which escaped the targeted test.  Or maybe it looks in each path element and sees that it is a module, instead of a library root? etc...

**Comment by daicoden** [comment]
Yes very hard to debug too - because you don't get to see the invocations... eep thank you for taking a look, it now fails consistently, and I was able to fix it.

🐑
