### ISSUE TITLE
Question: How to do "manual" collection of tests to tailor test suites

### ISSUE THREAD

**Issue by Wramberg** [pytest-dev/pytest#3927]
I have a series of folders with python test files inside. I would like to mix these tests in different ways to create multiple test suites. Example

```
├── run_suite_1.py
├── run_suite_2.py
├── some_other_tests
│   ├── k_test.py
│   └── u_test.py
└── some_tests
    ├── a_test.py
    └── b_test.py
```

Suppose I want `run_suite_1.py` to run `a_test.py` and everything from the `some_other_tests` dir. Conversely I would like `run_suite_2.py` to run `u_test.py` and everything from the `some_tests` dir.

I can do this via the command line obviously but that would get tedious real quick.

I can also do it with marks I suppose but  I dislike having to spread marks around. I would prefer defining a python file that points to all the different files and dirs that goes into a single suite. I guess you can call that manual collection ?

Is this is any way possible ?

**Comment by RonnyPfannschmidt** [comment]
pytest currently has no such mechanism in a direct manner
its possible to do this indirectly but i dont have the time to collect the required details in a timely manner

**Comment by Wramberg** [comment]
Alright thanks for the quick answer. I have been able to do somewhat what I want with a custom plugin that uses the `pytest_collect_file` hook. I have changed the extension of the `run_suite` files to .suite to be able to recognize them easily. I can then do something like

```
def pytest_collect_file(path, parent):
    # Omitted some checking against extension etc here.
    files = path.readlines()
    test_file_path = os.path.abspath(os.path.join(path.dirname, files[0]))
    return pytest.Module(test_file_path, parent)
```

As illustrated however it seems that I can only return back one file/module. Is there any way that I can return multiple files ?

**Comment by Wramberg** [comment]
Diving a bit more into the whole tree structure pytest uses I've gotten it working. For reference if anyone reads this I ended up making a custom `pytest.Collector` with a `collect` method that returns a list of `pytest.Module`.
