### ISSUE TITLE
QUESTION: make get.addoption run before pytest.mark.skipif

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest#3929]
Hi folks,

I have a usecase where I'm using get.addoption in order to provide an external path to load a xml file which I parse. this file, acts as an SUT (system under test) with specific values in it (such as IPs, ports, passwords and more).

In my CI/CD configuration, we have couple of spesific setups that some of the tests can't run against. what I wanted to do is to use the skipif fixture in order to check if a spesific SUT name is being passed in. if it's valid, than I can run the test otherwise, I can't.

the problem is that the get.addoption (and parsing) happens **AFTER** the pytest.mark.skipif occurs - which leads me to unable to parse the SUT object.

Any way to handle it?

**Comment by RonnyPfannschmidt** [comment]
what the heck is `get.addoption` please provide enough information to get at least a basic idea of what you do

**Comment by Formartha** [comment]
ok, so that's what I'm doing.

parser.addoption('--sut', action="store",
                            help='Name of the system under test (SUT)')

passing to the test suit the "sut" path.
than, I'm using

pytest.fixture(scope="session", autouse=True)
def parse_args(request):
    sut = request.config.getoption("--sut")

to parse the response (leave aside the internals on how I'm prasing it. it's just filling a singlton dict)

now for the use case:
trying to call sut.mysut.some_item() - it's not being instantiated yet, so, I can't really use it untill the parser will be triggered.

**Comment by RonnyPfannschmidt** [comment]
its still very unclear what you are doing - all i can see from your example is a cli option that works and a question for a random object that you'd have to make to begin with

if you want good answers please put in the effort to make a good question http://www.catb.org/esr/faqs/smart-questions.html has a good description on how to do that effectively

**Comment by Formartha** [comment]
I will try to elaborate by providing more info.

the sut file is being pushed in, so, after reading the data we'd have some sort of a singleton with I can call to whenever I need.,
sut = {
         "sut_name" : "test_123", 
          "skip_in_pipeline": True
           }

--
from parsed_sut import sut
def test_1():
print sut["sut_name"]

the problem is if I want to do the following:

@pytest.mark.skipif(sut["skip_in_pipeline"])
from parsed_sut import sut
def test_1():
print sut["sut_name"]

the reason is that the sut parsing should occur before running the fixture itself. 
p.s I'm using conftest in order to achieve this parsing.

**Comment by RonnyPfannschmidt** [comment]
so you import something thats not configured yet and try to use it

a easy workaround is to declare 

```
suite = {}
```

and later on do a 

`suite.update(parsed_data)`



then a test can be declared using runtime evaluation

using 
```
from ... import suite
@pytest.skipif("suite['skip_in_pipeline']")
def test_foo():
   ...
```

**Comment by Formartha** [comment]
YOU ARE THE BEST!
I just tried to use None instead of Empty dict.

Thank you :)

**Comment by RonnyPfannschmidt** [comment]
@Formartha switch form fixture to a `pytest_configure` hook

**Comment by Formartha** [comment]
Thanks! Great works like a charm.

**Comment by nicoddemus** [comment]
@Formartha anything else? If not, could you please close the issue? Thanks!
