### ISSUE TITLE
Is it possible to get logging output to terminal when using xdist?

### ISSUE THREAD

**Issue by BeyondEvil** [pytest-dev/pytest#3930]
When running without xdist, logging ("regular" and cli) works as expected. But when running with xdist, I can't seem to get any logging.

OSX: 10.12.6 (16G29)
python 3.7.0
pytest: 3.7.1
xdist: 1.22.5

pytest.ini
```
[pytest]
addopts = -s --tb short
testpaths = tests
base_url = local.dporganizer.com
sensitive_url = foo
log_level = INFO
log_cli = true
log_cli_level = INFO
```

**Comment by RonnyPfannschmidt** [comment]
xdist currently doenst integrate logging, which is a xdist issue

**Comment by BeyondEvil** [comment]
Got it! Thanks @RonnyPfannschmidt 

On a related note: Is it possible to hook into the logging system and fetch them so that I can add them to the pytest-html report generated by pytest-selenium?

**Comment by RonnyPfannschmidt** [comment]
if they arent on the rport, then thats a bug
