### ISSUE TITLE
Getting started doc should include Python 3.7

### ISSUE THREAD

**Issue by okken** [pytest-dev/pytest#3932]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
This link: https://docs.pytest.org/en/latest/getting-started.html
Includes this text: "Pythons: Python 2.7, 3.4, 3.5, 3.6, Jython, PyPy-2.3"
Should be extended to include 3.7

- [x] `pip list` of the virtual environment you are using
N/A
- [x] pytest and operating system versions
N/A
- [x] Minimal example if possible
N/A

**Comment by nicoddemus** [comment]
Thanks @okken! Would you like to open a PR with that? 😉

**Comment by okken** [comment]
sure. I'll give it a shot.
