### ISSUE TITLE
Progress indicator does not count up to 100% when using multiple test functions in a single test file

### ISSUE THREAD

**Issue by jansipke** [pytest-dev/pytest#3934]
Version 3.3 of pytest added a progress indicator. When there are multiple test functions in a single test file, the percentages do not add up to 100%. In the function _get_progress_information_message in terminal.py, the progress is calculated by the following statement:

progress = len(self._progress_nodeids_reported) * 100 // collected

The collected value is the number of collected *functions* while the length of self._progress_nodeids_reported gives the number of *files* that have been tested. One of these two should be changed.

platform linux2 -- Python 2.7.12, pytest-3.7.4, py-1.5.4, pluggy-0.7.1
rootdir: /jansipke, inifile: pytest.ini
plugins: shutil-1.3.0, pyramid-server-1.3.0, server-fixtures-1.3.1, pep8-1.0.6, flakes-4.0.0, cov-2.5.1

**Comment by nicoddemus** [comment]
Hi @jansipke,

Can you please provide an example that demonstrates your problem? We have tests in place that show that the progress indicator does count up to 100%, plus pytest's own test suite shows the correct progress, so if you are experiencing this it might be a corner case.
