### ISSUE TITLE
pytest.approx() support for list to scalar comparison

### ISSUE THREAD

**Issue by carlodri** [pytest-dev/pytest#3935]
I was quite surprised by the fact that this code:

```python
from pytest import approx
a=[1.0, 1.1, 1.2]
a == approx(1)
```

gives an error:

```
C:\Miniconda3x64\envs\pythr02-env\lib\site-packages\_pytest\python_api.py in __eq__(self, actual)
    282
    283         # Return true if the two numbers are within the tolerance.
--> 284         return abs(self.expected - actual) <= self.tolerance
    285
    286     __hash__ = None

TypeError: unsupported operand type(s) for -: 'int' and 'list'
```

Maybe I'm missing something fundamental, but why doesn't `approx` work normally as expected with a simple, homogeneous python list of floats?

I'm using `pytest` version 3.7.4.

**Comment by RonnyPfannschmidt** [comment]
`approx([1,1,1])` is not the same as `approx(1)`

**Comment by carlodri** [comment]
@crazymerlyn thanks, that was the piece of info I was missing...sorry for the noise...
