### ISSUE TITLE
Warning filters: ini files take precedence over -W command-line option

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#3946]
Considering a simple test which raises a warning and a `pytest.ini` file:

```python
import warnings

def test_foo():
    warnings.warn(UserWarning('oh no'))
```

```ini
[pytest]
filterwarnings =
    error   
```

Running with `$ pytest -W ignore` still makes the warning an error. I believe this is a bug and command-line options should take precedence over ini-options.

(Follow-up from https://github.com/pytest-dev/pytest/issues/3945).

In summary the current precedence order is:

1. mark
2. ini file
3. cmdline option

IMHO this should be instead:

1. mark
2. cmdline option
3. ini

**Comment by crazymerlyn** [comment]
Why is this issue still open if the PR fixing it has been merged?

**Comment by RonnyPfannschmidt** [comment]
we missed the trigger keyword to auto-close it, thanks for bringing it to attention

**Comment by nicoddemus** [comment]
Actually it was present in the PR's description, but GH only auto-closes when it gets merged to `master` (the default branch), and the PR targeted `features`.
