### ISSUE TITLE
Move 'short test summary info' to the end of the output again (regression)

### ISSUE THREAD

**Issue by mgedmin** [pytest-dev/pytest#3952]
I find the short test summary info displayed by `py.test -ra` very useful, but I have trouble finding it when there are multiple failures with long tracebacks.  I have to page up my terminal scrollback buffer very carefully, so I don't skip over it by accident, especially when I've multiple py.test runs visible in my scrollback.

My life would be markedly improved if the short test summary info got printed _after_ all the failure tracebacks, to be visible right above my shell prompt (and the 'N tests failed' summary line).

**Comment by mgedmin** [comment]
This appears to be a duplicate of #3255 and I should be upgrading version pins in my requirements.txt more often.  Sorry for the wasted time!

**Comment by mgedmin** [comment]
So I upgraded to pytest 3.8.0 and now `short test summary info` is shown after the tracebacks, but before the warnings (of which there are 3483 lines printed my cursed test suite).

The changelog entry says the summary should be shown after the warnings, so it looks like it has regressed.

**Comment by asottile** [comment]
I made an attempt in #3956 but it appears this feature is in direct conflict with #1305 -- not sure what to do here

**Comment by blueyed** [comment]
Maybe warnings from `pytest_terminal_summary` etc (#1305) should come afterwards still, but only if there are any (with a special header then)?

**Comment by blueyed** [comment]
New attempt in https://github.com/pytest-dev/pytest/pull/4399.
