### ISSUE TITLE
pytest_report_teststatus does not work on ubuntu

### ISSUE THREAD

**Issue by guangs** [pytest-dev/pytest#3961]
I define pytest_report_teststatus hook in conftest.py like this:

# hook test result, if passed, then check dump. if there is dump, then override the case result to failed
def pytest_report_teststatus(report):
    if report.when == 'call':
        if report.outcome == 'passed':
            if check_dumps():
                report.outcome = 'failed'

I want to check dump in the last line of running test cases, before running teardown. If found dumps, then override the test result to 'failed'.

pytest_report_teststatus can work on windows, but it does not work on ubuntu. pytest_report_teststatus seems to be skipped on ubuntu.

**Comment by RonnyPfannschmidt** [comment]
more context is needed - what versions of pytest do you use on each system for example, and whats the actual output

do you perhaps have a minimal example we can actually run

**Comment by nicoddemus** [comment]
Closing as this has not seen activity in awhile.
