### ISSUE TITLE
Add distinct option to show full (assertion) diffs always

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#3962]
Currently you have to use `-vv` to show the whole diff for dicts, and not to truncate in general.

Code:

 - https://github.com/pytest-dev/pytest/blob/c00d934b213606fac60c2502e5bc8fe5b3e2aecb/src/_pytest/assertion/util.py#L295-L296
 - https://github.com/pytest-dev/pytest/blob/c00d934b213606fac60c2502e5bc8fe5b3e2aecb/src/_pytest/assertion/truncate.py#L27-L32

1. there should be a distinct option additionally, because I usually have to re-run the test with `-vv` then, but would rather have it by default - without using very verbose mode by default

2. `pytest.assertion.truncate` checks if it is running on CI and enables this then always.  This should also be done for comparing dicts anyway.  Should I file a separate issue / create a PR for this already?

I would like to add this to the config file for projects where it makes sense, e.g. https://github.com/Vimjas/covimerage, where most of the tests are comparing program output (by lines), which usually gets truncated.
`-vv` would still have the same effect of course.

**Comment by cheezman34** [comment]
A potential workaround that might work for some:

Add to your conftest.py
```
from _pytest.assertion.util import assertrepr_compare
def pytest_assertrepr_compare(config, op, left, right):
    # hack the verbosity so we always show full diffs on assertion failures,
    # even if we're otherwise not fully verbose
    config.option.verbose = 2
    return assertrepr_compare(config, op, left, right)
```

**Comment by blueyed** [comment]
The hack does not for truncation via `saferepr` unfortunately (for a overlong assertion message itself).

See also https://github.com/pytest-dev/pytest/issues/2382 and https://github.com/pytest-dev/pytest/issues/3693.

This is really frustrating, but at least `--assert=plain` can be used to get the full assertion message.

**Comment by blueyed** [comment]
@pytest-dev/contributors 
Any input on this (given that there are already some WIP PRs to fix issues in this regard), please?

**Comment by blueyed** [comment]
btw/JFI: for skipping truncation (just one part of it), you can use `CI=true` as a workaround:
https://github.com/pytest-dev/pytest/blob/cbe3e3ebd3ca941118254025764aefd392383a8a/src/_pytest/assertion/truncate.py#L23-L34

**Comment by nicoddemus** [comment]
> Any input on this (given that there are already some WIP PRs to fix issues in this regard), please?

I guess they are being discussed in each PR? If not, please feel free to ping any stale PRs.

**Comment by bwoodsend** [comment]
This is closed by 56d9ea038ad8ef2ff8efa6d274868ddb75dadd7d is it not? You can now just pop `assert_truncate_level=0` into the `pytest.ini` and never end up on the wrong end of the _Full output truncated_ message again.

**Comment by asottile** [comment]
@bwoodsend that commit is not in pytest, but in a fork

**Comment by bwoodsend** [comment]
:facepalm: So it is...

**Comment by Pierre-Sassoulas** [comment]
Done in https://github.com/pytest-dev/pytest/pull/11473
