### ISSUE TITLE
request.applymarker(pytest.mark.skip) has no effect.

### ISSUE THREAD

**Issue by rainwoodman** [pytest-dev/pytest#3969]
Test case:

```python
@pytest.fixture(params=[0, 1, 2, 3, 4])
def mine(request):
    if request.param == 2:
        request.applymarker(pytest.mark.skip(reason="Not using communicator %d" % request.param))
    return request.param

def test_fixture(mine):
    assert mine != 2
```

Expected Result:

mine == 2 is skipped

Actual Result:

mine == 2 fails

Note that if skip is replaced with xfail(run=False), the test is skipped; but here we just want to skip a test, not marking it as a known failure.

**Comment by RonnyPfannschmidt** [comment]
skip markers are evaluated before fixtures are even run
same goes for `xfail(run=False)`
thing is xfail of any configuration is evaluated after the test

the canonical way for the example you posted is (just written in the gh up, not actually tested)

```python
@pytest.fixture(params=[0, pytest.param(1, marks=pytest.mark.skip(...)), 2, 3, 4])
def mine(request):
  return request.param

def test_fixture(mine):
    assert mine != 1
```
or

```python
@pytest.fixture(params=[0,1, 2, 3, 4])
def mine(request):
    if request.param == 2:
        pytest.skip("Not using communicator %d" % request.param)
    return request.param

def test_fixture(mine):
    assert mine != 2
```
