### ISSUE TITLE
Provision to display summary/reason of the deselected tests in pytest

### ISSUE THREAD

**Issue by gopishrk** [pytest-dev/pytest#3971]
Current pytest implementation has the provision to display the skipped tests at the end if we pass the option '-rs'. But there is no option available to display similar summary for the deselected tests. It only shows how many tests are deselected, but not printing the name of deselected test and reason regarding why it is deselected.

**Comment by RonnyPfannschmidt** [comment]
deselection is currently unable to pass trough reason and the api is a mess to evolve, so its currently not being touched

**Comment by Zac-HD** [comment]
Closing as stale per https://github.com/pytest-dev/pytest/issues/12465#issuecomment-2175596712
