### ISSUE TITLE
pytest.mark usefixture vs usefixtures 

### ISSUE THREAD

**Issue by bertjwregeer** [pytest-dev/pytest#3972]
I know that this is something that bites me every so often, and it recently bit a colleague of mine, however when using fixtures and marking a class/function as require a fixture, it is very unintuitive to use `usefixtures` when you intend to use only a single fixture.

Would it be possible to register `usefixture` as an alias for `usefixtures` to avoid this confusion and a lot of head scratching?

Especially because pytest does not seem to error when you use a non-existent mark.

**Comment by Zac-HD** [comment]
> Especially because pytest does not seem to error when you use a non-existent mark.

As discussed on #4506, we're more likely to make it an error to use an undefined mark.  From a perspective of ["there should be one-- and preferably only one --obvious way to do it."](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python), that's arguably better than an alias anyway!

**Comment by bertjwregeer** [comment]
@Zac-HD I would be perfectly happy with that solution too :-)

**Comment by nicoddemus** [comment]
@bertjwregeer you can make pytest error out on unknown marks by passing `--strict`. You might decide to add this to your `pytest.ini` as well so you enforce it across the project:

```ini
[pytest]
addopts = --strict
```
