### ISSUE TITLE
Add option to force absolute paths shown in tracebacks

### ISSUE THREAD

**Issue by joaompinto** [pytest-dev/pytest#3976]
When running `python -m pytest`, the tracebacks randomly report full path/relative path of the failing modules.

Some editors integrated terminals depend on full paths to redirect to the in editor file, as such, pytest should have an option to always report full path of the modules.

**Comment by joaompinto** [comment]
Closind to the lack of activity, meanwhile this is no longer an issue for the editor I am using.

**Comment by nicoddemus** [comment]
Thanks @joaompinto, thanks for the follow up.

Sorry you got no response, anyway indeed feels more like an editor issue than a pytest issue, as I've worked with several editors and never had this problem before. Thanks again!
