### ISSUE TITLE
*_test.py tests are not discovered

### ISSUE THREAD

**Issue by awiss** [pytest-dev/pytest#3981]
macOS 10.13.5
Python 3.6.5
Tested on pytest 3.6.3 and 3.8.0

It appears that pytest only recognizes test files of the form `test_*.py` and `*_tests.py`, instead of `*_test.py` as the documentation indicates.

I have the following directory
`tests/`
  - `__init__.py`
  - `conftest.py`
  - `{test_name}.py`

And am running `pytest tests/`

When {test_name} is `test_experiment` or `experiment_tests`, the test runs. However, with {test_name} as `experiment_test`, nothing runs.

**Comment by blueyed** [comment]
> as the documentation indicates

Reference: https://docs.pytest.org/en/latest/reference.html#confval-python_files

**Comment by RonnyPfannschmidt** [comment]
this needs a bit of investigation, https://github.com/pytest-dev/pytest/blob/49800ea13434ee08e2d8e5b1d1b7a3fb4061b4af/src/_pytest/python.py#L121 clearly sets it up for what is intended to be documented - if pytest acts different then we should takea good liik at why, and what triggers that effect

**Comment by asottile** [comment]
I name all my tests `xxx_test.py` and it is working fine for me, I suspect either a `pytest.ini` setting overriding this or a typo in the filename?

**Comment by RonnyPfannschmidt** [comment]
@awiss can you perhaps provide a zip file with a minimal reproducer?

**Comment by awiss** [comment]
Minimal repro... didn't reproduce. Sorry! Don't worry about fixing for my specific case, I'll figure it out.

**Comment by RonnyPfannschmidt** [comment]
@awiss please get back once you actually figure it
