### ISSUE TITLE
Introduce tmp_path fixture

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#3985]
After the excellent brain-storming with @gaborbernat in https://github.com/pytest-dev/pytest/pull/2230#issuecomment-421454260, I came to realize we already depend now on `pathlib2`, so we could already introduce a new `tmp_path` fixture which works exactly like `tmpdir`, but returns a `pathlib.Path` instance. 

Even if we don't ever adopt the `pathlib`-switch discussed in #2230, still seems like a good idea given that `pathlib` is part of the standard library, so makes perfect sense.

**Comment by nicoddemus** [comment]
For completeness, we should include a `path_factory`, similar to `tmpdir_factory`.

**Comment by RonnyPfannschmidt** [comment]
full stop - im currently porting the complete internals of tmpdir to pathlib - i will open a pr within the next 12 hours

**Comment by RonnyPfannschmidt** [comment]
#3988 fixes this one

**Comment by crazymerlyn** [comment]
Closing this as #3988 was merged.
