### ISSUE TITLE
Actual and Expected are being mixed up in assert diffs

### ISSUE THREAD

**Issue by abotalov** [pytest-dev/pytest#3992]
Currently the verbose diff looks like:

```py
def test_function():
  assert 3 == 4
```

```
4 != 3

Expected :3
Actual   :4
 <Click to see difference>

def test_function():
>     assert 3 == 4
E     assert 3 == 4

../../test_sample.py:4: AssertionError
```

As the usual idiom is `assert actual == expected`, these words are mixed up.

Similar to https://github.com/pytest-dev/pytest/issues/3333.

**Comment by nicoddemus** [comment]
I think you are copying pasting the output from PyCharm, right? In that case that's PyCharm producing that output, and pytest really cannot do anything about it.

**Comment by abotalov** [comment]
Yes, I copy pasted it from PyCharm, thought it's from Pytest.

**Comment by abotalov** [comment]
This a bug https://youtrack.jetbrains.com/issue/PY-27267

**Comment by nicoddemus** [comment]
Thanks for the link. 👍
