### ISSUE TITLE
getattr is returning MarkInfo object which is deprecated

### ISSUE THREAD

**Issue by otrejoso** [pytest-dev/pytest#4004]
I started to get these annoying warnings:

` RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code`

I wasn't able to find any of the documentation about how to get around this.

I have simple repro case

test_compute.py
```
import pytest


@pytest.mark.configure("test2")
def test_compute(param1):
    assert param1 < 4
```

conftest.py
```
# content of conftest.py


def pytest_generate_tests(metafunc):
    configuration = getattr(metafunc.function, "configure", None)
    if configuration is not None:
        arg = get_configuration(configuration)
        metafunc.parametrize("param1", range(arg))


def pytest_configure(config):
    config.addinivalue_line(
        "markers",
        "configure: my configure"
    )


def get_configuration(configuration_marker):
    assert len(configuration_marker.args) == 1
    arg = configuration_marker.args[0]
    if arg == "test1":
        arg = 5
    else:
        arg = 2
    return arg

```

My command line:

`pytest -v test_compute.py`

My virtual enviroment:
```
>pip list
Package        Version
-------------- -------
atomicwrites   1.2.1
attrs          18.2.0
colorama       0.3.9
funcsigs       1.0.2
more-itertools 4.3.0
pathlib2       2.3.2
pip            18.0
pluggy         0.7.1
py             1.6.0
pytest         3.8.0
scandir        1.9.0
setuptools     40.4.1
six            1.11.0
wheel          0.31.1
```

This seems to me a bug on pytest... Maybe? If MarkInfo object is deprecated, then nothing else should be returning that object, but getattr is.

I hope I can hear from anyone. Thanks :)

**Comment by RonnyPfannschmidt** [comment]
markerinfo objects obtained by getattr are deprecated because they are pretty much broken and cant be fixed in a compatible way

instead `metafunc.definition.get_closest_marker(name)` or `metafunc.definition.iter_markers(name)`

**Comment by nicoddemus** [comment]
For more information: https://docs.pytest.org/en/latest/mark.html#marker-revamp-and-iteration

Closing for now, feel free to follow up with more questions @otrejoso.

**Comment by otrejoso** [comment]
Cool. That got rid of the warnings. Thanks.
