### ISSUE TITLE
Upstream bug in backports raises already imported PytestWarning

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#4014]
On projects that have `backports` modules in use, I see this warning after running the tests:

```
/Users/jaraco/code/yg/G/panoptic/.tox/python/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:274: PytestWarning: Module already imported so cannot be rewritten: backports
  self.config,
```

`backports` is a namespace package, so maybe the warning should be suppressed for it.

Here's how to reproduce the issue:

```
 $ cat > test_this.py
def test():
        pass
$ python2.7 -m rwt -q pytest backports.unittest_mock pytest-flake8 -- -m pytest
============================================================================================ test session starts ============================================================================================
platform darwin -- Python 2.7.15, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: /Users/jaraco/draft/backports, inifile:
plugins: flake8-1.0.2, backports.unittest-mock-1.4
collected 1 item

test_this.py .                                                                                                                                                                                        [100%]

============================================================================================= warnings summary ==============================================================================================
/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-7YqacE/_pytest/assertion/rewrite.py:274: PytestWarning: Module already imported so cannot be rewritten: backports
  self.config,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================================================================================== 1 passed, 1 warnings in 0.01 seconds ====================================================================================
```

The issue only seems to happen on Python 2.7.

Interestingly, it also only seems to happen if pytest-flake8 is included even though I don't see any references to backports in pytest-flake8 or its dependencies.

Is there something that backports.unittest_mock should do to help suppress this warning?

**Comment by RonnyPfannschmidt** [comment]
it seems backports.unittest_mock contains a pytest plugin  - which triggers some loading/behaviour - the order would be interesting

**Comment by nicoddemus** [comment]
> Is there something that backports.unittest_mock should do to help suppress this warning?

That's an interesting question which I don't believe has come up before: how can plugins customize the warnings filter, and if that's a good thing?

**Comment by jaraco** [comment]
I’m not even confident that it’s the plugin’s responsibility here. Consider another scenario, where maybe a plug-in pulls in a different namespace package that it doesn’t own? Which package would be responsible for suppressing the warning. I wonder if there’s something about the scenario that pytest could handle as a matter of course, such as suppressing warnings like these for namespace packages.

I can try making that warning an error and see if I can discern when it occurs to understand better what’s going on.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus hmm, i recall if actual namespace packages are involved, then setuptools namespace fixup will preimport the namespace declarations

as such, the pytest assertion rewriter should auto-ignore te declared namespaces as a impoted thing

**Comment by nicoddemus** [comment]
> as such, the pytest assertion rewriter should auto-ignore te declared namespaces as a impoted thing

But doesn't that mean that assertion rewrite did not rewrite the module?

**Comment by jaraco** [comment]
In the case of `backports.*`, that namespace uses native namespaces ([not declaring them to setuptools/pkg_resources](https://github.com/jaraco/backports.unittest_mock/blob/a4f9fbe456ae8e1072ab4863ca8cc4340b46a50e/setup.py#L9)), so I would expect it not to be influenced (much) by pkg_resources.

```
~ $ python2.7 -m rwt -q backports.unittest_mock
Python 2.7.15 (default, Jun 20 2018, 13:24:23)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import pkg_resources, sys
>>> 'backports' in sys.modules
False
```

**Comment by jaraco** [comment]
> I can try making that warning an error and see if I can discern when it occurs to understand better what’s going on.

I haven't had any luck making that error raise. I tried `-Werror` to Python (with `-m pytest`) as wells as `-m pytest -Werror`, but always the error shows as a warning at the end of the test run.

It even emits as a warning when running the help:

```
draft $ python2.7 -m rwt -q pytest backports.unittest_mock pytest-flake8 -- -W error -m pytest --help
usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
...
to see available fixtures type: pytest --fixtures
(shown according to specified file_or_dir or current dir if not specified; fixtures with leading '_' are only shown with the '-v' option
warning : /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-Amy5m0/_pytest/assertion/rewrite.py:268: PytestWarning: Module already imported so cannot be rewritten: backports
  self.config,
```

**Comment by jaraco** [comment]
I don't yet understand what's special about backports (or namespace packages) that causes this warning to emit... or why it would only happen when pytest-flake8 is also included.

**Comment by jaraco** [comment]
This is interesting - I added `raise ValueError()` to line 2 of `backports/__init__.py` in `backports.unittest_mock`, and when running the test, the error is never triggered... so it's apparently not that package that's actually creating the `backports` that's in sys.modules.

**Comment by jaraco** [comment]
This is interesting:

```
> /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-hrhYx0/_pytest/assertion/rewrite.py(256)mark_rewrite()
-> if not AssertionRewriter.is_rewrite_disabled(
(Pdb) sys.modules['backports']
<module 'backports' (built-in)>
```

At the point the module is being detected as already imported, it's a "built-in" module.

**Comment by jaraco** [comment]
Even more interesting, I think I'm getting closer to understanding why pytest-flake8 is implicated:

```
draft $ python2.7 -m rwt -q backports.unittest_mock -- -c "import sys; print(sys.modules['backports'])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'backports'
draft $ python2.7 -m rwt -q backports.unittest_mock pytest-flake8 -- -c "import sys; print(sys.modules['backports'])"
<module 'backports' (built-in)>
```

Note, there, I'm not involving pytest at all, but the mere presence of pytest-flake8 installed in the environment causes 'backports' to appear in sys.modules.

**Comment by jaraco** [comment]
Wow. You don't even need backports.unittest_mock for that module to be present.

```
draft $ python2.7 -m rwt -q pytest-flake8 -- -c "import sys; print(sys.modules['backports'])"
<module 'backports' (built-in)>
```

**Comment by jaraco** [comment]
So it's the pth file of configparser:

```
rwt-0EQgzw $ cat configparser-3.5.0-py2.7-nspkg.pth
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('backports',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('backports', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('backports', [os.path.dirname(p)])));m = m or sys.modules.setdefault('backports', types.ModuleType('backports'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
```

```
draft $ python2.7 -m rwt -q configparser -- -c "import sys; print(sys.modules['backports'])"
<module 'backports' (built-in)>
```

**Comment by jaraco** [comment]
That [explains why it doesn't happen on Python 3](https://gitlab.com/pycqa/flake8/blob/master/setup.py#L39-40).

**Comment by jaraco** [comment]
Related: https://bitbucket.org/ambv/configparser/issues/17/importerror-when-used-with-other-backports

**Comment by jaraco** [comment]
And I've found the [underlying culprit](https://bitbucket.org/ambv/configparser/src/78998f2ded2e840376adc712337545014fa9b622/setup.py#lines-45).

**Comment by jaraco** [comment]
Filed [upstream issue](https://bitbucket.org/ambv/configparser/issues/21/configparser-should-not-declare-a).

**Comment by jaraco** [comment]
Confirmed that the proposed patch corrects the issue:

```
draft $ python2.7 -m rwt -q backports.unittest_mock hg+https://bitbucket.org/jaraco/configparser pytest-flake8 -- -m pytest
============================================================================================ test session starts ============================================================================================
platform darwin -- Python 2.7.15, pytest-3.8.1, py-1.6.0, pluggy-0.7.1
rootdir: /Users/jaraco/draft, inifile:
plugins: flake8-1.0.2, backports.unittest-mock-1.4
collected 1 item

test_this.py .                                                                                                                                                                                        [100%]

========================================================================================= 1 passed in 0.01 seconds ==========================================================================================
```

**Comment by nicoddemus** [comment]
Awesome detective work, thanks @jaraco!

Want to close this or leave this open until upstream is fixed?

**Comment by onkam** [comment]
So what is exactly the workaround please ?
The ../configparser/diff/setup.py did not look like the "culprit" to me...

**Comment by RonnyPfannschmidt** [comment]
@onkam as far as i can tell from its current tip its using multiple conflicting name-spacing techniques and adds files it shouldn't add - which in turn triggers the importing issue

**Comment by onkam** [comment]
Thanks for the tip, but which files I can comment out just as a workaround to avoid the errors.

**Comment by jaraco** [comment]
I should also point out that I'm still having these issues with `jaraco.*` packages.

If a package is using `pkg_resources`-style namespace packages, that namespace package is created by `-nspkg.pth` files when the interpreter starts up, so the namespace package will have been imported prior to rewrite and the warning will be emitted.

> But doesn't that mean that assertion rewrite did not rewrite the module?

True, the module which is the namespace package container module will not have been rewritten, but that's okay because by definition, these modules are not supposed to contain any behavior except for the namespace declaration. There should be no meaningful behavior that would be invoked during the test run, and so nothing should need to be rewritten.

So although the original issue led me to discover that `configparser` is incorrectly using `pkg_resources`-style namespace packages (and should be corrected), there's still a broader issue for other packages using `pkg_resources`-style namespace packages... and one that I believe pytest should support.

I do wish to convert these namespaces to `pkgutil` or native namespace packages, but doing so requires doing across all projects in the namespace simultaneously and breaks compatibility across the transition, so is far from trivial to enact.

I propose that pytest could systematically suppress these warnings by not warning about a package if it's known to be a `pkg_resources`-style namespace package.

I believe we could devise a way to detect these packages, or at least a heuristic that's close enough for this deprecated approach.

Would you consider a PR to suppress these warnings if I could put together a reasonable routine to do the detection?

**Comment by jaraco** [comment]
> Thanks for the tip, but which files I can comment out just as a workaround to avoid the errors.

I tried defining a `filterwarnings` section in pytest.ini, but I was unable to filter the warnings. @onkam, are you getting errors or just warnings?

**Comment by onkam** [comment]
I got errors..

**Comment by jaraco** [comment]
One thing pytest _could_ do is during the "already imported" test, specifically exclude any pkg_resources-based namespace packages from the warning. That would address the issue more directly, but I don't think it's worth the trouble given the progress on other fronts.

**Comment by asottile** [comment]
hello, first off thank you for the issue!

python 2.x support has ended for pytest core.

we've decided in #7296 to close the python-2-specific issues to free up some space in our backlog.  however, in accordance to our [python 2.7 and 3.4 support](https://docs.pytest.org/en/latest/py27-py34-deprecation.html) community patches *will still be accepted* to the `4.6` series to fix bugs for python 2.  (so if this issue is important to you and you have a patch to fix it, feel free to make a PR targeting the 4.6.x branch despite this ticket being closed).
