### ISSUE TITLE
Volunteer to release 3.8.1?

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4015]
I was about to start 3.8.1 when I remembered that recently more people have been demonstrating that they wanted to make a release. Any maintainers that want to volunteer? The process is described in the HOWTORELEASE docs. 😁 

If nobody manifests I will get to the release tomorrow. 👍

**Comment by asottile** [comment]
having done it, it's not that hard! hopefully someone steps up 🎉

**Comment by crazymerlyn** [comment]
I tried doing `tox -e release -- 3.8.1` and got this error:
```
An error has occurred: InvalidConfigError:
==> File /home/merlyn/pytest/.pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='local')
==> At key: hooks
==> At Hook(id='changelogs-rst')
==> At key: language
=====> Expected one of docker, docker_image, golang, node, pcre, pygrep, python, python_venv, ruby, rust, script, swift, system
but got: 'fail'
Check the log at /home/merlyn/.cache/pre-commit/pre-commit.log
Traceback (most recent call last):
  File "scripts/release.py", line 111, in <module>
    main()
  File "scripts/release.py", line 107, in main
    pre_release(options.version)
  File "scripts/release.py", line 86, in pre_release
    check_call(["git", "commit", "-a", "-m", msg])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'commit', '-a', '-m', 'Preparing release version 3.8.1']' returned non-zero exit status 1.
ERROR: InvocationError: '/home/merlyn/pytest/.tox/release/bin/python scripts/release.py 3.8.1'
___________________________________________________________ summary ____________________________________________________________
ERROR:   release: commands failed
```
It seems it's looking for the key `language` in hooks while the `.pre-commit-config.yaml` file contains `language_version`. Not sure if this is an error in the config or my setup.

**Comment by nicoddemus** [comment]
That happened to me before, the solution was to remove the `.cache/pre-commit` in my HOME directory. @asottile do you have any other tips about what to do in those situations?

**Comment by crazymerlyn** [comment]
Turns out my setup was at fault. I was using an old version of pre-commit which didn't support `language: fail`.

**Comment by asottile** [comment]
Yep, old version of pre-commit (I thought I put the necessary `>=` in tox.ini but I guess not?) . Generally you should never need to clear the cache (in those cases report a bug!)

**Comment by RonnyPfannschmidt** [comment]
@asottile how about having a pre-commit option in the configfile itself? so pre-commit can know if its outdated

**Comment by asottile** [comment]
it already exists! [`minimum_pre_commit_version`](https://pre-commit.com/#new-hooks)

**Comment by crazymerlyn** [comment]
The release is complete (can't believe it only took three tries!). Closing the issue.
