### ISSUE TITLE
Wrong module reported when collecting tests in a package

### ISSUE THREAD

**Issue by CaselIT** [pytest-dev/pytest#4024]
When collecting tests from a directory is a package with (has a `__init__.py` file), the wrong module is reported if the files are in a subfolder

With a file structure like
```
- tests
|- __init__.py
|- bar_test.py
|- subfolder
   |- foo_test.py
```

The reported output of pytest is
```
<Package 'C:\\path\\to\\pytest-discovery-bug\\tests_package'>
  <Module 'bar_test.py'>
    ...
  <Module 'foo_test.py'>
    ...
```
There is no indication that `foo_test.py` is inside the folder `subfolder`

I've created a minimal example: https://github.com/CaselIT/pytest-discovery-bug

This issue prevent the function of the python extension for vscode. https://github.com/Microsoft/vscode-python

**Comment by CaselIT** [comment]
Indeed adding `__init__.py` into `subfolder` changes the output to the correct one
```
<Package 'C:\\path\\to\\pytest-discovery-bug\\tests_package'>
  <Module 'bar_test.py'>
    ...
  <Package 'C:\\path\\to\\pytest-discovery-bug\\tests_package\\subfolder'>
    <Module 'foo_test.py'>
      ...
```

**Comment by RonnyPfannschmidt** [comment]
@CaselIT thanks for the feedback - we will add a acceptance test in future to sort this out

**Comment by jonozzz** [comment]
Sorry, I just got back from vacation and just saw this.
Can you try this change and see if it fixes your issue?
https://github.com/jonozzz/pytest/commit/58f7b174d8e27d88a2c11e4604e7ed36c9d18ec3#diff-adadbb411b38936fe8a465a285a5dd0f

Why are you looking at the module's name attribute anyway? That should informative only, external code should not rely on that.

**Comment by CaselIT** [comment]
@jonozzz I will try and report back.

I'm not directly looking at it. The vscode extension for python parses the collect output to provide the code lens functionality on the test so they can be ran or debugged individually
![image](https://user-images.githubusercontent.com/16175304/46099059-17b19700-c1c6-11e8-99f6-6d36c635a529.png)

i just noticed that sometimes it was gone and found that the problem was this

**Comment by RonnyPfannschmidt** [comment]
@CaselIT please also report a bug against them, they should run collect-only against a plugin getting the actual objects instead of parsing messy output

**Comment by CaselIT** [comment]
I did https://github.com/Microsoft/vscode-python/issues/2663

**Comment by nicoddemus** [comment]
Thanks @CaselIT for testing it!

@jonozzz could you open a PR with the fix when you have the time? Thanks! 🙇

**Comment by symonk** [comment]
Is this fixed already?

```
<Package tests>
  <Module foo_test.py>
    <Function test_it>
<Module tests/subdir/bar_test.py>
  <Function test_it>
```

is the output today as of head of master, unsure if thats correct or not but it looks OK to me?

**Comment by CaselIT** [comment]
I had honestly forgot about this issue.
I no longer face the problem mentioned in the op. Looking at the output I guess it's fixed, since the path does appear in the module name without init.
