### ISSUE TITLE
Using caplog in custom fixtures clears caplog.records

### ISSUE THREAD

**Issue by markus1978** [pytest-dev/pytest#4033]
Thx for the great framework. But, I have one tiny issue with it.

When I use the build-in `caplog` fixture in my own fixtures, the `caplog.records` list is correctly filled in the fixture using test case, but empty in my fixture.

The following mini example `test/test_test.py`
```
import pytest
import logging


@pytest.fixture()
def my_caplog(caplog):
    yield caplog
    assert len(caplog.records) > 0  # passes not


def test_nowarn(my_caplog):
    logging.getLogger().warning('Hello, anybody there')
    assert len(my_caplog.records) > 0  # passes
```
yields this `pytest -sv test/test_test.py` output:
```
================================================== test session starts ==================================================
platform darwin -- Python 3.6.3, pytest-3.8.1, py-1.6.0, pluggy-0.7.1 -- /Users/markus/Documents/Projects/check_pytest/.pyenv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/markus/Documents/Projects/check_pytest, inifile:
collected 1 item

tests/test_test.py::test_nowarn PASSED
tests/test_test.py::test_nowarn ERROR

======================================================== ERRORS =========================================================
___________________________________________ ERROR at teardown of test_nowarn ____________________________________________

caplog = <_pytest.logging.LogCaptureFixture object at 0x10ee2f278>

    @pytest.fixture()
    def my_caplog(caplog):
        yield caplog
>       assert len(caplog.records) > 0
E       assert 0 > 0
E        +  where 0 = len([])
E        +    where [] = <_pytest.logging.LogCaptureFixture object at 0x10ee2f278>.records

tests/test_test.py:8: AssertionError
--------------------------------------------------- Captured log call ---------------------------------------------------
test_test.py                12 WARNING  Hello, anybody there
=========================================== 1 passed, 1 error in 0.06 seconds ===========================================
```

There are two things that I don't understand and think should behave differently:
- Pytest runs the test case twice, one passing, one failing. Why? Shouldn't this be one test case.
- The failing test shows that the `caplog.records` has the entry within the test case (as expected), but the entry is gone in the fixture (unexpected). The capture log shows the entry (as expected).

If one could access the `caplog.records` in the fixture, one could write fixtures that check for unexpected warnings, errors, etc. At least, this is what I wanted to do :-(.

**Comment by blueyed** [comment]
> Pytest runs the test case twice, one passing, one failing. Why? Shouldn't this be one test case.

It runs only once, but reports the error in the teardown (your failing assert) separately (AFAIK).

I guess this is related to the caplog fixture's teardown handling, see https://github.com/pytest-dev/pytest/blame/4474beeb8294a8f8759e967484b7a932ca4c22fb/src/_pytest/logging.py#L448.

Related commit: https://github.com/pytest-dev/pytest/commit/7ea5a22657027d87e7b35f456e9b044a097c910e.

**Comment by jeffreyrack** [comment]
This can be handled by using the caplog.get_records function instead, and specifying the when parameter.

Example Python file:
```
import pytest
import logging

@pytest.fixture
def my_caplog(caplog):
    yield caplog
    assert len(caplog.get_records(when='call')) > 0  # passes not


def test_nowarn(my_caplog):
    logging.getLogger().warning('Hello, anybody there')
    assert len(my_caplog.records) > 0  # passes
```

And then when ran, it passes with the behavior you expected:
```

example.py .                                                             [100%]

========================== 1 passed in 0.07 seconds ===========================

```

**Comment by markus1978** [comment]
Yes, that works for me. Thank you very much.
