### ISSUE TITLE
TestReport.user_properties is documented as a list, actually a tuple

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#4034]
https://github.com/pytest-dev/pytest/blob/253419316ce09b952862811db229a9e9383a332b/src/_pytest/reports.py#L137-L139

This makes me nervous when using it in plugins, e.g. to pass Hypothesis statistics around in HypothesisWorks/hypothesis#1577.  My code handles either a list or a tuple here, but it would be nice to - one way or another - make the code and the documentation consistent.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/search?q=user_properties&unscoped_q=user_properties lists the instantiation sites

the declaration as is is clearly mistake, it should use None in the argument spec and create a list as default

**Comment by Zac-HD** [comment]
`self.user_properties = list(user_properties)` would also work.

**Comment by RonnyPfannschmidt** [comment]
@Zac-HD indeed, however i beleive it fits python expectations better if the original reference is used if possible

**Comment by Zac-HD** [comment]
Sure - I was thinking about users who might currently be passing a tuple, but given the `.append` calls I doubt that would work at the moment anyway!
