### ISSUE TITLE
Deprecate item parameter of pytest_warning_captured hook

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4036]
As discussed in pytest-dev/pytest-xdist#341, the `item` parameter of `pytest_warning_captured` hook is unfortunately incompatible with `pytest-xdist` because we can't send the `item` object through the wire from workers to master.

**Comment by RonnyPfannschmidt** [comment]
we might want to reopen for a followup with an actual parameter deprecation

**Comment by nicoddemus** [comment]
Let me create another issue
