### ISSUE TITLE
implement `rm -rf` in terms of pathlib

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#4061]
followup to https://github.com/pytest-dev/pytest/pull/3988#discussion_r221742040

as it turns out `shutil.rmtree` is unable to be harsh
its fine if we aren't for a while, but we need eventual parity

**Comment by Zac-HD** [comment]
That is, implement the following using `pathlib` rather than `shutil`:

https://github.com/pytest-dev/pytest/blob/dc0b4efffa85340d5d1f8df2ff116ddd5266bf7a/src/_pytest/pathlib.py#L49-L56

**Comment by RonnyPfannschmidt** [comment]
also ref #4222

**Comment by gnikonorov** [comment]
I'm going to take a look at this one as I'm freeing up a bit.
@RonnyPfannschmidt - can you elaborate what you mean by `shutil.rmtree` is unable to be harsh? If I understand correctly, all we need to do is what @Zac-HD has suggested but I am curious about your comment

**Comment by RonnyPfannschmidt** [comment]
@gnikonorov shutil.rmtree doesn't try as hard as py.path.local does

It's basically a rm -r and we need the -f on top as well

**Comment by gnikonorov** [comment]
Thanks for confirming @RonnyPfannschmidt

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i think we can consider this fixed with #5588 merged?

**Comment by nicoddemus** [comment]
Yes, thanks!
