### ISSUE TITLE
[Feature?] Minimal maintenance for certesian product test input and output.

### ISSUE THREAD

**Issue by WloHu** [pytest-dev/pytest#4071]
- [ ] Include a detailed description of the bug or suggestion
- [ ] Minimal example if possible

Description is mostly [here](https://stackoverflow.com/q/52102065/5492820).

The point is that I've tried to create cartesian product test which is best exmplained by given multiplication table example. To allow minimal maintenance I've created custom marker and I generate tests inside a **simple** hook but the problem is that to support `pytest` features like `pytest.param` I would have to exted the logic to the point where I would be copying `pytest`' implementation. The hook and marker:
```python
# conftest.py
from itertools import product
from typing import Iterable, Any, List

Matrix = List['Matrix']

def pytest_generate_tests(metafunc):
    for mark in metafunc.definition.iter_markers(name='parametrize_matrix'):
        arg_names, *input_values, results_matrix = mark.args
        mix = merge_arguments(input_values, results_matrix)
        metafunc.parametrize(arg_names, mix, **mark.kwargs)

def merge_arguments(inputs: List[List[Any]], results: Matrix):
    args = [list(values) for values in product(*inputs)]
    for i, value in enumerate(flatten(results)):
        args[i].append(value)
    return args

def flatten(iterable: Matrix):
    result = []
    for item in iterable:
        if isinstance(item, Iterable):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result
```
```python
#test_m.py
import pytest
@pytest.mark.parametrize_matrix("x, y, result",
                                [1, 2, 3],
                                [4, 5, 6],

                                [[ 4,  5,  6],
                                 [ 8, 10, 12],
                                 [12, 15, 18],]
)
def test_multiplication(x, y, result):
    assert x * y == result
```

The ideal solution, which takes advantage of existing `pytest` code, would be:
```python
# test_m_ideal.py
import pytest
@pytest.mark.parametrize("x", [1, 2, 3])
@pytest.mark.parametrize("y", [4, 5, 6])
@pytest.mark.result_matrix("result", [
    [ 4,  5,  6],
    [ 8, 10, 12],
    [12, 15, 18],
])
def test_multiplication(x, y, result):
    assert x * y == result
```

But the problem is that I don't know how **properly** mutate existing tests cases, so that for example `pytest` doesn't give an error like "value for `y` is duplicated".

Either submitting "built-in" solution for the StackOverflow question, adding such built-in marker to `pytest` or adding a hook to `pytest` to allow that will be helpful.

- [ ] `pip list` of the virtual environment you are using
```
Python 3.6.5rc1
Package              Version  
-------------------- ---------
aenum                2.1.2    
argh                 0.26.2   
atomicwrites         1.2.1    
attrs                18.2.0   
bitarray             0.8.3    
bm                   0.1.0    
certifi              2018.8.24
chardet              3.0.4    
clang-5              5.0.post2
coverage             4.5.1    
decorator            4.3.0    
flake8               3.5.0    
flake8-builtins      1.1.1    
flake8-class-newline 1.6.0    
future               0.16.0   
hdlcontroller        0.4.0    
idna                 2.7      
inflection           0.3.1    
Jinja2               2.10     
jsonschema           2.6.0    
lxml                 4.2.5    
MarkupSafe           1.0      
marshmallow          2.15.6   
mccabe               0.6.1    
more-itertools       4.3.0    
munch                2.3.2    
pathtools            0.1.2    
pip                  18.0     
pkg-resources        0.0.0    
pluggy               0.7.1    
ply                  3.11     
prophy               2.0.2    
protobuf             3.6.1    
psutil               5.4.7    
py                   1.6.0    
pyasn1               0.4.4    
pycodestyle          2.3.1    
pyflakes             1.6.0    
pyserial             3.4      
pytest               3.8.1    
pytest-cov           2.6.0    
pytest-logger        0.4.0    
python4yahdlc        1.2.0    
PyYAML               3.13     
requests             2.19.1   
rp1                  2.63.2   
setuptools           40.4.3   
six                  1.11.0   
SQLAlchemy           1.2.12   
urllib3              1.23     
watchdog             0.9.0    
wheel                0.32.0
```
- [ ] pytest and operating system versions
ArchLinux, 4.12.13-1-ARCH

**Comment by Zac-HD** [comment]
If you can calculate the result from the inputs, you could use a list comprehension.  If not, I don't understand how listing the results separately from the inputs would make maintenance easier.

```python
import pytest
@pytest.mark.parametrize("x,y,result", [
	(x, y, x * y) 
    for x in [1, 2, 3]
    for y in [4, 5, 6]
])
def test_multiplication(x, y, result):
    assert x * y == result
```

I will second the suggestion from StackOverflow to use [Hypothesis](https://hypothesis.readthedocs.io/en/latest/) if the number of inputs is very large though - `parametrize` will report *all* failing inputs, while Hypothesis will only report the minimal input for each distinct error.

**Comment by WloHu** [comment]
The problem here is that you're duplicating `*` evaluation. It can be any operation instead multiplication, I've used it to simplify the problem.
Generating expected result values using code under test won't give you any fails. I want to pass hardcoded expected values.

**Comment by Zac-HD** [comment]
In that case, writing out the hard-coded values as a sequence of tuples already works 😄 

```python
HARD_CODED_CASES = [
    (1, 4, 4),
    (1, 5, 5),
    (1, 6, 6),
    (2, 4, 8),
    (2, 5, 10),
    (2, 6, 12),
    (3, 4, 12),
    (3, 5, 15),
    (3, 6, 18),
]
@pytest.mark.parametrize("x, y, result", HARD_CODED_CASES )
def test_multiplication(x, y, result):
    assert x * y == result
```

If your concern is minimal maintenance, a table of static data is much easier to keep up to date than code to mutate the test cases at runtime.  You can even load the data from a file, so it's entirely separate from your test code!

**Comment by RonnyPfannschmidt** [comment]
the correct way to declare such results is to declare them explicitly - as soon as you want to declare "any operation and its result" you are down to writing a function that generates it anyway

**Comment by WloHu** [comment]
@Zac-HD I know I can do it this way but as you can see all input values repeat multiple times and I want to avoid copy pasting them. Less duplicated code less maintenance but tradeoff is readability. For larger matrices it would be hard to match inputs with output value (at least I don't have idea how to make it well).

@RonnyPfannschmidt So it sounds like "Won't do" for such feature. Do you have any advice how can I make my hook reuse `parametrize` logic? The only idea I have is testcase objects mutation during collection which anti-API and volatile.

**Comment by WloHu** [comment]
My question wasn't precise enough. I'm using `pytest_generate_tests` to do that and I have 2 problems to make my hook correcly:

1. Single hook `parametrize_matrix` with input and output arguments.
`merge_arguments` and `flatten` functions doesn't handle e.g. `pytest.param` (and possibly some other situations) correctly like `metafunc.parametrize` does for multiple `pytest.mark.parametrize`. I stopped at this point because it would probably require to duplicate some functionality that `pytest` already has and dive deeper into source code.

2. Multiple `pytest.mark.parameterize` and single `result_matrix`.
At the point when I'm supposed to handle hook I would have to mutate existing testcases because calling `metafunc.parameterize` again will make another cartesian product from previous input values and given output values. This is also anti-API approach.
Additionally when I didn't use `metafunc.parameterize` test run ended with error saying that "fixture `result` doesn't exist".

It would be helpful to know what is the easiest way to either reuse `pytest`' logic in 1st case or in 2nd case mutate test cases w/o hacking.

**Comment by RonnyPfannschmidt** [comment]
@WloHu then its absolutely unclear what you want to actually archive to me, as far as i can tell you want to declare vectors, a result matrix, and collapse vectors and matrix into a linear collection of parameters

so you get an set of input and a result element and you want to serialize the resultso f that relation into one parameterset

so you would have exactly one call to `metafunc.parametrize`

the main reason why this mechanism as is cant make it into pytest itself because its absolute unclear how to be used and absolutely unclear how to make sense in a general setting

as far as i understood, practically you want to express a operation table like

```
* | 1 2 3
--+------
1 | 1 2 3
2 | 2 4 6
3 | 3 6 9
```

so a `pytest.mark.result_table("x y results", x=[1,2,3], y=[1,2,3] results=[[...], ...])` could be used to do the serializion to a table in some more nice manner

but some part has to do the combination of "headings" and results

**Comment by WloHu** [comment]
@RonnyPfannschmidt 

> cant make it into pytest itself because its absolute unclear how to be used and absolutely unclear how to make sense in a general setting

 I understand this and said 

> So it sounds like "Won't do" for such feature.

From that point I only tried to get a bit of advice what can be used to solve `pytest` related problems that my hook has.
Anyway, I will try to dig deeper into `pytest` and find out in my free time.

**Comment by WloHu** [comment]
#2171 Similar request.
