### ISSUE TITLE
Add timeout to testdir.run()

### ISSUE THREAD

**Issue by altendky** [pytest-dev/pytest#4073]
I would like to rewrite [this pytest-twisted test](https://github.com/pytest-dev/pytest-twisted/blob/14b16ca114e735d46d52cd36dc2f2306ed0ec636/testing/test_basic.py#L210-L261) but the new way would run indefinitely on failure.  It's already using [`testdir.run()`]() but that doesn't support a timeout.   There's `spawn_pytest()` and `spawn()` but they involve pexpect which doesn't seem right.  What's proper?  I can certainly provide a PR for adding a timeout to `testdir.run()` if that's the answer.

**Comment by nicoddemus** [comment]
Hi @altendky,

Looking at the code, I think it is OK to add this option to `runpytest_subprocess` and `run`. A PR is welcome! 👍

**Comment by altendky** [comment]
https://github.com/pytest-dev/pytest/pull/4078
