### ISSUE TITLE
Warnings during generating of allure report - RemovedInPytest4Warning

### ISSUE THREAD

**Issue by yshovkun-cartera** [pytest-dev/pytest#4080]
I updated my pytest to the latest version and started getting an errors during allure report generation.
However  as I can see, you fully support it with the latest version. 

pip list: 
package               Version
--------------------- ---------
atomicwrites          1.2.1
attrs                 18.2.0
certifi               2018.8.24
chardet               3.0.4
colorama              0.3.9
enum34                1.1.6
idna                  2.7
lxml                  4.2.5
more-itertools        4.3.0
namedlist             1.7
pip                   10.0.1
pluggy                0.7.1
py                    1.6.0
pytest                3.8.2
pytest-allure-adaptor 1.7.10
requests              2.19.1
setuptools            39.1.0
six                   1.11.0
urllib3               1.23

OS: Windows 10 Enterprise x64

Warning example:
============================== warnings summary ===============================
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:92: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  label_name = label_marker.name.split('.', 1)[-1]
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:93: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  for label_value in label_marker.args or ():
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:92: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  label_name = label_marker.name.split('.', 1)[-1]
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:93: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  for label_value in label_marker.args or ():
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:92: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  label_name = label_marker.name.split('.', 1)[-1]
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:93: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  for label_value in label_marker.args or ():
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:92: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  label_name = label_marker.name.split('.', 1)[-1]
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:93: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  for label_value in label_marker.args or ():
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:92: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  label_name = label_marker.name.split('.', 1)[-1]
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:93: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  for label_value in label_marker.args or ():
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:92: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  label_name = label_marker.name.split('.', 1)[-1]
C:\Virtual Env\cprw-api-tests\lib\site-packages\allure\utils.py:93: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  for label_value in label_marker.args or ():

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================== 1 passed, 12 warnings in 10.08 seconds ====================

**Comment by nicoddemus** [comment]
Could you please open an issue with `allure-python` @yshovkun-cartera? Thanks! 

Closing this as this is an upstream issue.
