### ISSUE TITLE
Test report losing colors

### ISSUE THREAD

**Issue by Victorious3** [pytest-dev/pytest#4084]
pytest version: 3.8.2
python: 3.7.0
OS: Windows 10
shell: cmd.exe + powershell

![image](https://user-images.githubusercontent.com/3749322/46550867-939e9400-c8d6-11e8-8b84-91ae7c468b2f.png)

The longer the tests run the more likely this is to happen. Otherwise it's entirely random. It also happens with cmder on Windows, and plain cmd without powershell.
It works fine under mintty.

I've also noticed that it doesn't pick up console width at all. Manually setting `$env:COLUMNS = xxx` in powershell fixes that. Would be nice if it could figure the width out on its own.

**Comment by asottile** [comment]
can confirm, here's a simple test I have:

![](https://i.fluffy.cc/4NJb5hJqFH9XTzqzphts6fp1qQCWcnXg.png)

**Comment by nicoddemus** [comment]
I believe this is a Python 3.6+ problem that has been discussed at length:

* https://github.com/pytest-dev/pytest/pull/2462
* https://github.com/python/cpython/pull/1927

I believe we can't do much more than was done at #2462 right now...

**Comment by Victorious3** [comment]
I did a few more testing and it does not seem to happen with the `-s` switch on. (Unless random chance is messing with me) The only difference in the output is the percentage display, so maybe something is going wrong when outputting that.

**Comment by nicoddemus** [comment]
> The only difference in the output is the percentage display

What do you mean? Does the only part that loses colors is the percentage display?

**Comment by Victorious3** [comment]
No, I mean it only loses color when it displays the percentage, on the line after that. It's probably not that though, but rather the capturing of stdout. I wouldn't know why though, colorama is still doing something or else I'd see the control sequences inside the output. I could try and see if I can get the color back after the test run by initializing colorama again.

**Comment by segevfiner** [comment]
Yeah, that's exactly it. I think this is a duplicate of https://github.com/pytest-dev/pytest/issues/2465. I created a PR to colorama: https://github.com/tartley/colorama/pull/131, which fixes this. Sadly it was never merged. colorama seems rather unmaintained for now.

You can test the PR, and even use it locally for now.

**Comment by Victorious3** [comment]
I see. Closing this one, then.

**Comment by nicoddemus** [comment]
> Sadly it was never merged. colorama seems rather unmaintained for now.

Hmm indeed that's sad. And it doesn't seem to exist an alternative either (at least I couldn't find one after a quick google search)
