### ISSUE TITLE
Pytest 'steals' focus in python3

### ISSUE THREAD

**Issue by max-sixty** [pytest-dev/pytest#4087]
Firstly - an obligatory thanks for creating such a beautiful package. That this behavior is annoying highlights how dependent I've become on the package.

I'm finding that running `pytest` in python3.7 causes the editor to 'steal' focus from whatever app is running. I use `pytest-watch` heavily, and this makes leaving that running in the background all-but-unusable (also relevant for `--looponfail`). While the behavior has the most impact on running tests in the background, it does happen even when running pytest alone (ref https://github.com/joeyespo/pytest-watch/issues/96).

Oddly, it doesn't happen in python2.7. I've checked the versions of both pytest and its plugins, and they all match.

Any ideas for what could be causing this? Or let me know if any additional info would be helpful

- [x] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [ ] Minimal example if possible

I'm running python 3.7.0 and python 2.7.15 on macOS.

`pip2 list`:

<details>

Package                            Version                          Location
---------------------------------- -------------------------------- --------------------------------------
alembic                            0.8.10
altair                             1.2.1
amqp                               2.2.2
apache-airflow                     1.10.0
apache-beam                        2.4.0
apipkg                             1.4
appnope                            0.1.0
argh                               0.26.2
arrow                              0.12.1
asn1crypto                         0.24.0
astroid                            1.6.1
asv                                0.2.1
atomicwrites                       1.1.5
attrs                              17.4.0
autopep8                           1.3.4
avro                               1.8.2
Babel                              2.5.3
backports-abc                      0.5
backports.functools-lru-cache      1.4
backports.shutil-get-terminal-size 1.0.0
backports.ssl-match-hostname       3.5.0.1
bcrypt                             3.1.4
billiard                           3.5.0.3
binaryornot                        0.4.4
bleach                             2.1.2
boto                               2.48.0
boto3                              1.7.38
botocore                           1.10.38
Bottleneck                         1.2.1
cached-property                    1.3.1
cachetools                         2.0.1
caniusepython3                     6.0.0
celery                             4.1.0
certifi                            2018.1.18
cffi                               1.11.5
chardet                            3.0.4
click                              6.7
colorama                           0.3.9
colorlover                         0.2.1
configparser                       3.5.0
cookiecutter                       1.6.0
coverage                           4.5.1
crcmod                             1.7
croniter                           0.3.20
cryptography                       2.1.4
cufflinks                          0.12.1
cvxopt                             1.2.0
cycler                             0.10.0
Cython                             0.27.3
decorator                          4.2.1
dill                               0.2.6
distlib                            0.2.7
docformatter                       0.8
docker                             3.3.0
docker-compose                     1.21.2
docker-pycreds                     0.2.3
dockerpty                          0.4.1
docopt                             0.6.2
docutils                           0.14
dogpile.cache                      0.6.4
entrypoints                        0.2.3
enum34                             1.1.6
execnet                            1.5.0
fancycompleter                     0.8
fasteners                          0.14.1
flake8                             3.5.0
flake8-isort                       2.3
flake8-polyfill                    1.0.2
Flask                              0.12.4
Flask-Admin                        1.4.1
Flask-AppBuilder                   1.11.1
Flask-Babel                        0.11.1
Flask-Cache                        0.13.1
Flask-Caching                      1.3.3
Flask-Login                        0.2.11
Flask-OpenID                       1.2.5
Flask-SQLAlchemy                   2.1
flask-swagger                      0.2.13
Flask-WTF                          0.14.2
flower                             0.9.2
funcsigs                           1.0.0
functools32                        3.2.3.post2
future                             0.16.0
futures                            3.2.0
gitdb2                             2.0.3
GitPython                          2.1.8
google-api-core                    1.2.1
google-api-python-client           1.6.5
google-apitools                    0.5.21
google-auth                        1.4.1
google-auth-oauthlib               0.2.0
google-cloud-bigquery              1.4.0
google-cloud-core                  0.28.1
google-gax                         0.15.16
google-resumable-media             0.3.1
googleapis-common-protos           1.5.3
grpc-google-iam-v1                 0.11.4
grpcio                             1.10.1
grpcio-tools                       1.10.0
gunicorn                           19.7.1
hdfs                               2.1.0
hdfs3                              0.3.0
html5lib                           1.0.1
httplib2                           0.9.2
hypothesis                         3.52.0
idna                               2.6
inflection                         0.3.1
ipaddress                          1.0.19
ipykernel                          4.8.2
ipython                            5.8.0
ipython-genutils                   0.2.0
ipywidgets                         7.1.1
iso8601                            0.1.12
isort                              4.3.4
itsdangerous                       0.24
jedi                               0.11.1
Jinja2                             2.8.1
jinja2-time                        0.2.0
jmespath                           0.9.3
json-rpc                           1.10.8
jsonschema                         2.6.0
jupyter                            1.0.0
jupyter-client                     5.2.2
jupyter-console                    5.2.0
jupyter-core                       4.4.0
jupyter-kernel-gateway             2.0.2
kombu                              4.1.0
lazy                               1.3
lazy-object-proxy                  1.3.1
line-profiler                      2.1.2
llvmlite                           0.21.0
lockfile                           0.12.2
lru-dict                           1.1.6
lxml                               3.8.0
mackup                             0.8.18
Mako                               1.0.7
Markdown                           2.6.11
MarkupSafe                         1.0
matplotlib                         2.1.2
mccabe                             0.6.1
memory-profiler                    0.51.0
mistune                            0.8.3
mock                               2.0.0
mockredispy                        2.9.3
monotonic                          1.4
more-itertools                     4.1.0
Mosek                              8.1.30
nbconvert                          5.3.1
nbformat                           4.4.0
ndg-httpsclient                    0.4.4
notebook                           5.4.1
numba                              0.36.2
numexpr                            2.6.4
numpy                              1.14.2
oauth2client                       3.0.0
oauthlib                           2.0.6
ordereddict                        1.1
packaging                          17.1
pandas                             0.22.0
pandas-gbq                         0.6.1+7.g8b7f8fd
pandocfilters                      1.4.2
paramiko                           2.4.0
parso                              0.1.1
pathlib                            1.0.1
pathlib2                           2.3.0
pathtools                          0.1.2
patsy                              0.5.0
pbr                                4.0.1
pdbpp                              0.9.2
pendulum                           1.4.4
pexpect                            4.4.0
pickleshare                        0.7.4
pip                                18.1
plotly                             2.3.0
pluggy                             0.7.1
ply                                3.8
poyo                               0.4.1
profilehooks                       1.10.0
prompt-toolkit                     1.0.15
protobuf                           3.5.2.post1
psutil                             4.4.2
ptyprocess                         0.5.2
py                                 1.5.3
pyasn1                             0.4.2
pyasn1-modules                     0.2.1
pycallgraph                        1.0.1
pycodestyle                        2.3.1
pycparser                          2.18
pydocstyle                         2.1.1
pyflakes                           1.6.0
Pygments                           2.2.0
pyinstrument                       2.0.1
pyinstrument-cext                  0.1.2
pylint                             1.8.2
pyls-isort                         0.1.1
PyNaCl                             1.2.1
pyodbc                             4.0.23
pyOpenSSL                          17.5.0
pyparsing                          2.2.0
pyrepl                             0.8.4
pysftp                             0.2.9
pyslack-real                       0.6.0
pytest                             3.8.2
pytest-forked                      0.2
pytest-pycharm                     0.5.0
pytest-regtest                     1.3.1
pytest-sugar                       0.9.1
pytest-testmon                     0.9.13
pytest-watch                       4.2.0
pytest-xdist                       1.23.2
python-daemon                      2.1.2
python-dateutil                    2.7.1
python-editor                      1.0.3
python-language-server             0.17.2
python-nvd3                        0.15.0
python-openid                      2.2.5
python-slugify                     1.2.6
pytz                               2018.3
pytzdata                           2018.5
PyVCF                              0.6.8
PyYAML                             3.12
pyzmq                              16.0.4
qgrid                              1.0.0
qtconsole                          4.3.1
Quandl                             3.3.0
redis                              2.10.6
requests                           2.18.4
requests-oauthlib                  0.8.0
rope                               0.10.7
rsa                                3.4.2
s3transfer                         0.1.13
scandir                            1.7
scikit-learn                       0.19.1
scipy                              1.0.0
seaborn                            0.8.1
Send2Trash                         1.4.2
setproctitle                       1.1.10
setuptools                         39.2.0
setuptools-scm                     2.1.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.11.0
sklearn                            0.0
slackclient                        1.2.1
smmap2                             2.0.3
snakeviz                           0.4.2
snowballstemmer                    1.2.1
SQLAlchemy                         1.1.18
statsmodels                        0.8.0
subprocess32                       3.2.7
tabulate                           0.7.7
tabview                            1.4.3
tenacity                           4.8.0
termcolor                          1.1.0
terminado                          0.8.1
testfixtures                       5.4.0
testpath                           0.3.1
text-unidecode                     1.2
texttable                          0.9.1
thrift                             0.11.0
toolz                              0.9.0
tornado                            4.5.3
tqdm                               4.23.3
traitlets                          4.3.2
typing                             3.6.4
tzlocal                            1.5.1
unicodecsv                         0.14.1
Unidecode                          1.0.22
unittest2pytest                    0.3
untokenize                         0.1.1
uritemplate                        3.0.0
urllib3                            1.22
vega                               0.4.4
vega-datasets                      0.4.1
vega3                              0.10.0
vine                               1.1.4
watchdog                           0.8.3
wcwidth                            0.1.7
webencodings                       0.5.1
websocket-client                   0.46.0
Werkzeug                           0.14.1
wheel                              0.31.1
whichcraft                         0.4.1
widgetsnbextension                 3.1.3
wmctrl                             0.3
wrapt                              1.10.11
WTForms                            2.1
xarray                             0.10.4
xlwt                               1.3.0
yapf                               0.20.2
zope.deprecation                   4.3.0

</details>

`pip3 list`:

<details>

Package                       Version                          Location
----------------------------- -------------------------------- --------------------------------------
adal                          1.1.0
alembic                       0.8.10
altair                        2.2.2
amqp                          2.3.2
apache-airflow                2.0.0.dev0+incubating
apipkg                        1.4
appdirs                       1.4.3
appnope                       0.1.0
argh                          0.26.2
arrow                         0.12.1
asn1crypto                    0.24.0
asv                           0.3
atomicwrites                  1.1.5
attrs                         18.1.0
autopep8                      1.4
Babel                         2.6.0
backcall                      0.1.0
backports.functools-lru-cache 1.5
bcrypt                        3.1.4
beautifulsoup4                4.6.0
billiard                      3.5.0.3
binaryornot                   0.4.4
black                         18.9b0
bleach                        2.1.4
boto                          2.49.0
Bottleneck                    1.2.1
bs4                           0.0.1
cached-property               1.4.3
cachetools                    2.1.0
celery                        4.2.1
certifi                       2018.4.16
cffi                          1.11.5
chardet                       3.0.4
cheroot                       6.3.2.post0
CherryPy                      16.0.2
click                         6.7
cloudpickle                   0.5.3
colorama                      0.3.9
colorlover                    0.2.1
configparser                  3.5.0
cookiecutter                  1.6.0
coverage                      4.5.1
crcmod                        1.7
croniter                      0.3.24
cryptography                  2.2.2
cufflinks                     0.14.4
cycler                        0.10.0
Cython                        0.28.5
dask                          0.18.1
data                          0.4
decorator                     4.3.0
defusedxml                    0.5.0
dill                          0.2.8.2
distlib                       0.2.7
docformatter                  1.0
docker                        3.4.1
docker-compose                1.22.0
docker-pycreds                0.3.0
dockerpty                     0.4.1
docopt                        0.6.2
docutils                      0.14
dogpile.cache                 0.6.7
entrypoints                   0.2.3
execnet                       1.5.0
fancycompleter                0.8
fasteners                     0.14.1
flake8                        3.5.0
flake8-isort                  2.5
Flask                         0.12.4
Flask-Admin                   1.4.1
Flask-AppBuilder              1.11.1
Flask-Babel                   0.11.1
Flask-Caching                 1.3.3
Flask-Login                   0.2.11
Flask-OpenID                  1.2.5
Flask-SQLAlchemy              2.1
flask-swagger                 0.2.13
Flask-WTF                     0.14.2
flower                        0.9.2
funcsigs                      1.0.0
future                        0.16.0
futures                       3.1.1
fuzzywuzzy                    0.17.0
git-up                        1.5.2
gitdb2                        2.0.3
GitPython                     2.1.10
google-api-core               1.2.1
google-api-python-client      1.7.4
google-apitools               0.5.23
google-auth                   1.5.1
google-auth-httplib2          0.0.3
google-auth-oauthlib          0.2.0
google-bigquery               0.14
google-cloud-bigquery         1.6.0
google-cloud-core             0.28.1
google-cloud-storage          1.13.0
google-gax                    0.15.16
google-resumable-media        0.3.1
googleapis-common-protos      1.5.3
grpc-google-iam-v1            0.11.4
grpcio                        1.13.0
gunicorn                      19.9.0
html5lib                      1.0.1
httplib2                      0.11.3
idna                          2.6
inflection                    0.3.1
ipaddress                     1.0.22
ipdb                          0.11
ipykernel                     4.8.2
ipython                       7.0.1
ipython-genutils              0.2.0
ipywidgets                    7.2.1
iso3166                       0.8
iso8601                       0.1.12
isort                         4.3.4
itsdangerous                  0.24
jedi                          0.13.1
Jinja2                        2.8.1
jinja2-time                   0.2.0
jsonschema                    2.6.0
jupyter                       1.0.0
jupyter-client                5.2.3
jupyter-console               5.2.0
jupyter-core                  4.4.0
jupyter-kernel-gateway        2.1.0
jupyterlab                    0.34.0rc2
jupyterlab-launcher           0.13.1
kiwisolver                    1.0.1
kombu                         4.2.1
kubernetes                    7.0.0
lazy                          1.3
llvmlite                      0.25.0
lockfile                      0.12.2
lru-dict                      1.1.6
lxml                          4.2.5
Mako                          1.0.7
Markdown                      2.6.11
MarkupSafe                    1.0
matplotlib                    3.0.0
mccabe                        0.6.1
memory-profiler               0.54.0
mistune                       0.8.3
mock                          2.0.0
mockredispy                   2.9.3
monotonic                     1.5
more-itertools                4.2.0
nbconvert                     5.3.1
nbformat                      4.4.0
networkx                      2.2
nose                          1.3.7
notebook                      5.7.0
numba                         0.40.0
numexpr                       2.6.8
numpy                         1.15.2
oauth2client                  3.0.0
oauthlib                      2.1.0
of                            1.0.1
ordereddict                   1.1
pandas                        0.23.4
pandas-datareader             0.7.0
pandas-gbq                    0.6.1+2.gd98c621
pandas-profiling              1.4.1
pandocfilters                 1.4.2
paramiko                      2.4.1
parso                         0.3.1
pathlib2                      2.3.2
pathtools                     0.1.2
patsy                         0.5.0
pbr                           4.0.4
pdbpp                         0.9.2
pendulum                      1.4.4
pexpect                       4.6.0
pickleshare                   0.7.4
Pillow                        5.2.0
pip                           18.1
plotly                        3.3.0
pluggy                        0.7.1
ply                           3.8
portend                       2.3
poyo                          0.4.1
profilehooks                  1.10.0
prometheus-client             0.3.1
prompt-toolkit                2.0.5
protobuf                      3.6.0
psutil                        5.4.7
ptyprocess                    0.6.0
py                            1.5.4
py3                           1.0.2
pyasn1                        0.4.3
pyasn1-modules                0.2.2
pycallgraph                   1.0.1
pycodestyle                   2.3.1
pycparser                     2.18
pydata                        1.0.0
pydocstyle                    2.1.1
pydot                         1.2.4
pyflakes                      1.6.0
Pygments                      2.2.0
pygraphviz                    1.5
pyinstrument                  2.2.1
pyinstrument-cext             0.2.0
PyJWT                         1.6.4
pymongo                       3.7.0
PyNaCl                        1.2.1
pyodbc                        4.0.23
pyparsing                     2.2.0
pysftp                        0.2.9
pyslack-real                  0.6.0
pytest                        3.8.2
pytest-forked                 0.2
pytest-pycharm                0.5.0
pytest-regtest                1.3.1
pytest-sugar                  0.9.1
pytest-testmon                0.9.13
pytest-watch                  4.2.0
pytest-xdist                  1.23.2
python-daemon                 2.1.2
python-dateutil               2.7.3
python-editor                 1.0.3
python-jsonrpc-server         0.0.2
python-language-server        0.21.2
python-Levenshtein            0.12.0
python-nvd3                   0.15.0
python-slugify                1.2.5
python3-openid                3.1.0
pytils                        0.3
pytz                          2018.5
pytzdata                      2018.5
PyWavelets                    0.5.2
PyYAML                        3.12
pyzmq                         17.1.2
qgrid                         1.1.1
qtconsole                     4.3.1
qualname                      0.1.0
Quandl                        3.4.2
redis                         2.10.6
requests                      2.18.4
requests-file                 1.4.3
requests-ftp                  0.3.1
requests-oauthlib             1.0.0
requirements                  0.1
retrying                      1.3.3
rope                          0.11.0
rsa                           3.4.2
scikit-image                  0.14.0
scikit-learn                  0.19.2
scipy                         1.1.0
seaborn                       0.9.0
Send2Trash                    1.5.0
setproctitle                  1.1.10
setuptools                    40.4.3
setuptools-scm                3.1.0
simplegeneric                 0.8.1
six                           1.11.0
sklearn                       0.0
slackclient                   1.3.0
smmap2                        2.0.3
snakebite                     2.11.0
snakeviz                      1.0.0
snowballstemmer               1.2.1
SQLAlchemy                    1.2.12
SQLAlchemy-Utc                0.10.0
statsmodels                   0.9.0
tabulate                      0.7.7
tabview                       1.4.3
tempora                       1.12
tenacity                      4.8.0
termcolor                     1.1.0
terminado                     0.8.1
testfixtures                  6.2.0
testpath                      0.3.1
texttable                     0.9.1
thrift                        0.11.0
toml                          0.9.4
tools                         0.1.9
toolz                         0.9.0
tornado                       5.1
tqdm                          4.26.0
traitlets                     4.3.2
typing                        3.6.4
tzlocal                       1.5.1
unicodecsv                    0.14.1
Unidecode                     1.0.22
unittest2pytest               0.3
untokenize                    0.1.1
uritemplate                   3.0.0
urllib3                       1.22
vega3                         0.13.0
vine                          1.1.4
viz                           0.0.5
watchdog                      0.8.3
wcwidth                       0.1.7
webencodings                  0.5.1
websocket-client              0.48.0
Werkzeug                      0.14.1
wheel                         0.32.0
whichcraft                    0.4.1
widgetsnbextension            3.2.1
wmctrl                        0.3
wrapt                         1.10.11
ws4py                         0.5.1
WTForms                       2.2.1
xarray                        0.10.9
xlrd                          1.1.0
xlwt                          1.3.0
xskillscore                   0.0.2
zope.deprecation              4.3.0

</details>

**Comment by nicoddemus** [comment]
Hi @max-sixty,

pytest iself is a command-line application, and has no concept of focus as is used by GUI applications. This seems like something to do with your window system, but it is strange why it only happens with Python 3.7...

**Comment by max-sixty** [comment]
Agree - it's unclear why it happen in pytest specifically. Are there any differences in how pytest handles forking processes between python versions? There are a couple of references around that; e.g. https://apple.stackexchange.com/questions/100069/when-terminal-forks-process-current-app-loses-focus

It's also possible (/ more likely?) it's how the different versions of python handle forking, and nothing to do with pytest, but I only observe it in pytest.

**Comment by nicoddemus** [comment]
pytest itself does not fork any processes, but that doesn't prevent tests from forking processes themselves of course.

**Comment by max-sixty** [comment]
OK. I'm fairly confident these tests don't do any forking themselves. (Specifically, I'm running https://github.com/pydata/xarray/blob/master/xarray/tests/test_variable.py)

**Comment by max-sixty** [comment]
Confirmed that this forks from inside the library; tested by uninstalling `scipy` and running. 

Thank you for engaging so quickly. Closing here.
