### ISSUE TITLE
Add a returncode argument to pytest.exit

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4098]
As discussed in https://github.com/pytest-dev/pytest/issues/3574#issuecomment-396893524, `pytest.exit()` could receive a `returncode` argument to cleanly exit pytest.

**Comment by BeyondEvil** [comment]
If my silly mind will start functioning again after my vacation, I'll take a stab at this...

Now, if I could only set a reminder... 🤔

**Comment by nicoddemus** [comment]
Thanks @BeyondEvil, sounds good! 😁

**Comment by Zac-HD** [comment]
Closed by #4145.

FYI @cacoze [this article](https://help.github.com/articles/closing-issues-using-keywords/) describes the keywords that GitHub recognises to automatically close issues.

**Comment by nicoddemus** [comment]
Awesome work @Zac-HD on triaging all those issues! 👍

**Comment by BeyondEvil** [comment]
Dammit, cacoze beat me to it.

Ah well, you snooze you loose, I suppose. 😊
