### ISSUE TITLE
match argument does not work in deprecate_call

### ISSUE THREAD

**Issue by massich** [pytest-dev/pytest#4102]
See:

```py
import warnings
import pytest

def test_deprecation(recwarn):
    with pytest.deprecated_call(match="is not here"):    
	    warnings.warn("deprecated", DeprecationWarning)
```

**Comment by asottile** [comment]
can confirm that this is the cause, however this doesn't appear to be documented anywhere.

A simple fix would be to change `deprecated_call` to be implemented via `pytest.warns` -- let me see if I can't do that easily enough :)

**Comment by asottile** [comment]
via #4104
