### ISSUE TITLE
`--trace` does not respect `--pdbcls`  [likely fixed]

### ISSUE THREAD

**Issue by boustrophedon** [pytest-dev/pytest#4111]
From what I can tell, the `--trace` option does not respect the value of `--pdbcls`. If I install pudb and then run `pytest --pdbcls=pudb.debugger:Debugger --pdb`, I am successfully dropped into pudb when a test fails.

However, when I run `pytest --pdbcls=pudb.debugger:Debugger --trace`, I am dropped into regular pdb upon failure.

**Comment by jeffreyrack** [comment]
The problematic line comes from debugging.py:

```
    pyfuncitem.obj = pdb.runcall
```

You see here that we're directly using the pdb.runcall function, rather than using the runcall function provided by the pdb_cls that is passed in through the command line.

This could be accessed via the pytestPDB object, so I think it would make sense to have this line look something like:
```
    pyfuncitem.obj = pytestPDB.runcall
```

And this would mean that pytestPDB.runcall would need to be implemented to properly call the runcall function of the pytestPDB._pdb_cls object.

**Comment by boustrophedon** [comment]
I wasn't sure what the right way to add tests similar to the ones at the bottom of `testing/test_pdb.py` was. I wrote the passthrough code just for the runcall method and tested it manually and it appears to work, and all the existing tests pass.

**Comment by jeffreyrack** [comment]
I haven't played with it myself, but I'd look at adding a function to the class defined in the custom_pdb_calls fixture, and then running pytest with the --trace option to ensure that the runcall function gets called in the custom PDB class.

For an example test that does something similar, I'd look at: `test_pdb_custom_cls` in test_pdb.py

It might also be worth looking at how `test_pdb_custom_cls_with_settrace` tests that pytest.set_trace() properly calls the set_trace() function in the custom pdb class.

**Comment by blueyed** [comment]
I think this is fixed since 92a2884b (accidentally), https://github.com/blueyed/pytest/commit/92a2884b09eb793a390460012e6e2859da87767a#diff-dc8ebd50544f186db81faac257019f99R172.

Not checked though, and could use a test then also maybe - at least in case reverting that line would not break any.

**Comment by boustrophedon** [comment]
`pytest --pdbcls=pudb.debugger:Debugger --trace` does indeed work for me now, thanks! I also checked that it worked with addopts in my pytest.ini.

**Comment by blueyed** [comment]
Great!
Added a test in https://github.com/pytest-dev/pytest/pull/5074.
