### ISSUE TITLE
--deselect does not work with tests inside classes

### ISSUE THREAD

**Issue by omnilinguist** [pytest-dev/pytest#4127]
FYI @uSpike @nicoddemus @RonnyPfannschmidt @blueyed @thisch 

In #3201, the test case only seems to test `--deselect`ions of the form `path/to/test_file.py::test_name`. I validated that this works, but `--deselect`ions of the form `path/to/test_file.py::TestClass::test_name` do not work. How challenging would this be to fix?

**Comment by blueyed** [comment]
A failing test would be a good start.
Looks like it is not mached in https://github.com/pytest-dev/pytest/pull/3201/files#diff-5b415004cf343fc3c36aebb8aad93882R221 then.

In this regard I've also noticed that sometimes (with failures?) you get `path/file.py::TestClass::()::test_name` (note the extra `()`) - but have never investigated.  It can be used with the extra `::()` then for running it, so maybe that is the case here already, i.e. you need the extra `::()` to deselect it.

btw: it would be nice if globs could be used here (i.e. not just `startswith`)

**Comment by omnilinguist** [comment]
oh wow...that `--deselect`ion (`path/file.py::TestClass::()::test_name`) actually worked! 😮 

I think that is an acceptable workaround for now, but depends on some fairly arcane tribal knowledge / black magic about the extra `::()`. I can backlog an item to investigate this, but I suspect someone who is much more familiar with pytest internals would be much faster at it.

**Comment by blueyed** [comment]
Cool.
I think / assumed the "::()" is not really intentional, or at least it looks like it to me.

**Comment by nicoddemus** [comment]
If we search for `"::()"` in the code base, we see at least three places that do a "parens normalization":

https://github.com/pytest-dev/pytest/blob/d46b6b2bc33babe76ceea91ab36b453b2731e4b4/src/_pytest/terminal.py#L678

I believe we should extract that to a function, change the duplicated places to use that function, including where @blueyed pointed out previously:

https://github.com/pytest-dev/pytest/blob/d46b6b2bc33babe76ceea91ab36b453b2731e4b4/src/_pytest/main.py#L295-L296

It is kind of hackish, but it is simple to do and should improve the current state of things.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus this is one of the really cringe-worthy structural problems of the collection tree

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt yep, I'm aware 😬

**Comment by blueyed** [comment]
It is coming via https://github.com/pytest-dev/pytest/blob/eb0c733a8494e0b4c12f407a49ac1c0d1be01d17/src/_pytest/terminal.py#L690.

And gets also removed/skipped here:
https://github.com/blueyed/pytest/blob/eb0c733a8494e0b4c12f407a49ac1c0d1be01d17/src/_pytest/python.py#L271-L272

If replacing/normalizing it, couldn't that be done in `Node` then, or a more central place?

But I wonder why the `Class` => `Instance` is necessary after all?

At least the following gets not collected anyway:
```python
class TestFoo():
    @classmethod
    def test_foo(cls):
        pass
```

I've given it a quick shot at https://github.com/pytest-dev/pytest/pull/4357.
