### ISSUE TITLE
python_classes: match class names on word boundaries

### ISSUE THREAD

**Issue by theY4Kman** [pytest-dev/pytest#4128]
The `python_classes` setting instructs pytest to include or ignore certain classes for test discovery based on their classname. I've been using some BDD/declarative-style test context names like `ForCurrentUser`, which I want tests to be discovered under. However, I also use mixin classes like `ForbidsAnonymousUsers` to include common tests in other test contexts.

To support my case, I've been using a custom plugin to allow dashes in `python_classes` to represent CamelCase word boundaries: https://gist.github.com/25861e8acd564fe3a0e4a9f45b54a316

I wondered if it might be useful to anyone else before I write up a PR.

**Comment by RonnyPfannschmidt** [comment]
@theY4Kman this sound slike something that should be explored in a external plugin first - just like pytest-bdd and similar toolkits do their specialties without forcing core pytest to adapt those structures

**Comment by RonnyPfannschmidt** [comment]
oh, and just fyi - the mechanism you used in your script is deprecated and will be removed

**Comment by theY4Kman** [comment]
Sounds good!

re: deprecation — Are you referring to using `Class` and family to customize collection, like the [Deprecations page warns of](https://docs.pytest.org/en/latest/deprecations.html?highlight=pytest_collect_make_item#internal-classes-accessed-through-node)? I'm not sure if it's a typo, or I'm not searching deep enough, or maybe it ain't released, yet, but that page suggests using the `pytest_collect_make_item`, which I can't find. I figure it might mean `pytest_pycollect_makeitem`.

Thanks for the heads-up, in any case!

**Comment by RonnyPfannschmidt** [comment]
@theY4Kman i meant using Class&co do customize it

**Comment by theY4Kman** [comment]
I finally packaged up the plugin: https://pypi.org/project/pytest-camel-collect/

---

I'm still kinda fuzzy on the proper way to have my custom PyCollector classes used. I thought I could use a hookwrapper on `pytest_pycollect_makeitem` to augment the regularly-scheduled return value with my base class — which did seem to work with `trylast=True`, but failed in a different environment? _(or I can't remember what happened there...)

Though, when the hookwrapper was working alright, `pytest_pycollect_makeitem` didn't seem to get passed any Modules — whose collection I wanted to augment to change how class names were filtered. I added a similar `pytest_pycollect_makemodule` hookwrapper to patch them Moddies, and collection seemed as expected.

But I noticed child context classes weren't being collected. For example:
```py
class TestMyStuff:
	def test_my_stuff(self):
		pass

    class TestMyStuff:
		def test_my_stuff_also(self):
			pass
```

My plugin was only collecting `test_my_stuff`, but not `test_my_stuff_also`. It seemed `pytest_pycollect_makeitem` was being passed Classes, but not Instances, which were apparently responsible for collection of inner test classes. 

I'm sure I missed something obvious along the way (or took so many left turns I thought I was right), but I couldn't find a way to achieve my desired results with something mostly purely hook-centric. I landed on a simple strategy: inject my base class into Modules with `pytest_pycollect_makemodule`, and override `_getcustomclass` in my `PyCollector` subclasses.

**Comment by RonnyPfannschmidt** [comment]
@theY4Kman _getcustomclass was removed in pytest 4.0 and the supporting code will be removed in 4.1

**Comment by theY4Kman** [comment]
That removal must not've made it to [4.0](https://github.com/pytest-dev/pytest/blob/4.0.2/src/_pytest/nodes.py#L129-L138).

Cheers for the heads-up! I'll find another way to hack me plugin together when the time comes :P

**Comment by RonnyPfannschmidt** [comment]
@theY4Kman the code paths that use it trigger an error in 4.0, its removed in 4.1

**Comment by theY4Kman** [comment]
To be clear, I'm not requesting anything from ya. It would be nice if my sooper-dooper important use case /s was tendered to, but I ain't demanding it. For a ginormous OSS project like pytest, not for a second would I think I could somehow squeeze dev effort out of ya. Same would apply for the smallest of OSS project. Plus, I know my way around a code or two; I'll be fine when things change — and I'm happy when they do, 'cause things have gotten nicer and nicer as time goes on.

I say that 'cause I'm not sure what makes ya so certain `_getcustomclass` isn't in 4.0.x. I built the thing with 4.0.2 installed; my red/green tests pass. Here's [a REPL with a basic example using the plugin](https://repl.it/repls/CreativeDisgustingLanserver). I see that it's [gone in the `features` branch](https://github.com/pytest-dev/pytest/blob/e63c7a13ffa8190e378e6d2a89d671b343610aee/src/_pytest/nodes.py#L58) — maybe something slipped past the packing/release process?

**Comment by RonnyPfannschmidt** [comment]
@theY4Kman in the 4.0.x series the code paths still exist, but having them interact triggers errors in different places (aka the interal api still exists, but the facade you where supposed to use it with fails already)

the 4.1.x series removes the codepaths
