### ISSUE TITLE
--pastebin: should pytest know how to post to bpaste?

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#4150]
I was profiling the slowest tests for pytest and the second slowest is:

```
2.08s call     testing/test_pastebin.py::TestPasteCapture::test_non_ascii_paste_text
```

looking into this, it appears pytest has a `--pastebin` option which posts directly to bpaste (!)

should pytest continue to have this option? do people use this?

**Comment by nicoddemus** [comment]
It is an internal plugin, it is hard to tell how many people use this.

I wouldn't remove just because of this, but we definitely should improve the test to not post to bpaste and mock it instead.

**Comment by tbradley-sans** [comment]
@asottile I certainly use --pastebin. It's useful, though it stopped working recently due to CERTIFICATE_VERIFY_FAILED.

**Comment by asottile** [comment]
@tbradley-sans worked fine for me: https://bpaste.net/show/84f2fe8c516c

Paste your full output / stacktrace? I imagine you're on macos and probably hitting https://stackoverflow.com/q/42098126/812183 ?

**Comment by tbradley-sans** [comment]
@asottile Oh, you know what? I totally forgot I had to install and switch to Python 3.6 earlier this week due to AWS SAM compatibility. And this is the first time I've used pytest since switching. So I bet your guess is right on the money. Thanks.

**Comment by Zac-HD** [comment]
Fixed by https://github.com/pytest-dev/pytest/commit/0db9dade653d9fbaf830cefaf305c25193837b15
