### ISSUE TITLE
[Proposal] Request to add support for CI/CD pipelines for Test reporting

### ISSUE THREAD

**Issue by nigurr** [pytest-dev/pytest#4154]
_Issue:_ 

Currently Azure DevOps and Circle CI/CD systems provide rich test experience.
In order to get this experience/track test reporting, users has to explicitly generate test reports (currently supported format JUnit) by 3rd party plugins and publish test results.

Most of the popular open source projects aren't using 3rd party reporting plugins.
To keep local development experience and CI/CD build experience similar, scripts to build/test are written to print test results to console (std_out).
To get richer test experience in CI/CD pipeline, customers has to modify their scripts and often need to add 3rd party plugins.
This is a steep learning and test reporting is one of the important data that should be easily available for open source github projects.

_Proposal for solution(s):_

**Generate test results file based on environment variables**:
     In this approach, test runners will generate test results file along with regular console output if an environment variable is set.
     CI/CD pipelines can set this variable to desired test output location where they can automatically publish test results by consuming test results file generated by test runners (pytest).
     This simple flag will make sure test runners are not going through any change in behavior in terms of execution or context they are running and users don't require go through any modification to their source/scripts.

Happy to listen to community feedback. Feel free to share other ideas if proposed solution is not feasible one.

**Comment by RonnyPfannschmidt** [comment]
@nigurr its relatively simple to just use either the `--junitxml` option directly, or to add a `PYTEST_ADDOPTS` env var to enable it

does that already solve your problem?

**Comment by nigurr** [comment]
@RonnyPfannschmidt yes, I am proposing this option `to add a PYTEST_ADDOPTS env var to enable it`

CI/CD pipelines can add environment variables to enable directly and runners can simply write to specified path.
With this approach neither user has to modify/change their existing code/scripts and test results will appear in CI/CD pipelines.

**Comment by RonnyPfannschmidt** [comment]
@nigurr great, i'll close this one as resolved then, should there be something missing please throw us a line
