### ISSUE TITLE
Suggestion: --passed-last

### ISSUE THREAD

**Issue by rinslow** [pytest-dev/pytest#4166]
--passed-last is very similiar to --failed-first however it runs all the tests that either failed or didn't run yet first, and then it re-runs all the tests that passed to make sure they pass again.

I think this would be useful because If a test passed once, most likely I didn't break it and I want to see the next test to fail without having to wait or filter out manually.

**Comment by RonnyPfannschmidt** [comment]
#4147 might be interesting for that scenario

**Comment by feuillemorte** [comment]
I'll take it

**Comment by nicoddemus** [comment]
@feuillemorte hold on a bit, I'm interested to know if the new `--sw` flag might suit @rinslow's needs.

**Comment by Zac-HD** [comment]
Closing because the `--sw` / `--stepwise` argument serves this use-case.
