### ISSUE TITLE
integrate twine check in the linting process after the warehouse validation got moved

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#4169]
@di metioned on irc that there is an effort to move parts of the warehouse validation into the`packaging` library in order to use it in `twine check`

https://github.com/pypa/warehouse/blob/8ac3770668c50f69f4e211d937a701d37e20155a/warehouse/forklift/legacy.py#L341-L343

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt is this still something we want to do?

**Comment by RonnyPfannschmidt** [comment]
Yes, we can just take it from setuptools_scm to adapt

**Comment by nicoddemus** [comment]
I see how it is done in `setuptools-scm`, interesting: https://github.com/pypa/setuptools_scm/blob/master/.github/workflows/python-tests.yml

So I think we have two options:

1. Just run `twine check dist/*` after creating the packages in the `deploy` step:

   https://github.com/pytest-dev/pytest/blob/9ccbf5b89906604dc76daee1fc07c1d26b6b5128/.github/workflows/main.yml#L194-L196

2. Split the current `deploy` job in two: `package`, which runs every time (like `linting` or every other normal build environment does, for example) and creates the packages, runs `twine check`, and uploads the generated packages; and `deploy`, which just downloads the previously generated packages and then deploys them to PyPI.

**Comment by RonnyPfannschmidt** [comment]
I would propose to add it to the deploy step, and creating a testpypi token for all of pytest-dev and doing release upload testing for every commit soon

**Comment by nicoddemus** [comment]
Cool. Do I understand correctly that this is something you plan to tackle, or are you just laying out the plans? (Just to make sure everybody's on the same page)

**Comment by RonnyPfannschmidt** [comment]
Primarily laying out plans, maybe tackle in a few months, we should list it as open for grabs/first contribution

**Comment by webknjaz** [comment]
FYI https://github.com/pytest-dev/pytest/blob/ff6d29717c96c64e108581ddc7ead862f8d2398a/.github/workflows/main.yml#L232 invokes `twine check` under the hood.

**Comment by RonnyPfannschmidt** [comment]
@webknjaz thanks, in that case it's a close 😁

**Comment by webknjaz** [comment]
FTR I usually prefer a separate linting job for this because having the check fail right when you cut a release is not very pleasant.

**Comment by RonnyPfannschmidt** [comment]
closing as we now use BAIP
