### ISSUE TITLE
egg install not install pytest.py file

### ISSUE THREAD

**Issue by ondratu** [pytest-dev/pytest#4177]
Hi, new version 3.9.1 not install pytest.py file when egg install from setuptools tests_require parameter is used.

I have this argument in setup.py setup function:
```python
tests_require=['pytest'],
```
Then when i run python3 setup.py test and no pytest is installed in system yet, then setuptools install all packages, and it's dependencies to .egg directory.  So:

```sh
~$ ls .eggs/pytest-3.9.1-py3.5.egg/
EGG-INFO  _pytest
~$ ls .eggs/pytest-3.8.2-py3.5.egg/
EGG-INFO  __pycache__  _pytest	pytest.py
```
Somewhere in my test setup class i import pytest, which not exist now. When pytest is installed via pip3, pytest.py exist in filesystem, for example at /usr/local/lib/python3.5/dist-packages/pytest.py.

Here is my pip3 list
```
Click (7.0)
extendparser (0.2.0)
Flask (1.0.2)
gevent (1.3.7)
greenlet (0.4.15)
itsdangerous (0.24)
Jinja2 (2.10)
Jinja2-template-info (0.1.1)
jsonschema (2.6.0)
lazy-object-proxy (1.3.1)
MarkupSafe (1.0)
openapi-core (0.6.0)
openapi-spec-validator (0.2.4)
pip (9.0.1)
prometheus-client (0.4.2)
PyYAML (3.13)
setuptools (33.1.1)
six (1.11.0)
uWSGI (2.0.17.1)
Werkzeug (0.14.1)
wheel (0.29.0)
```
I use that on updated debian stretch docker image with python3 3.5.3-1 package.

**Comment by ondratu** [comment]
cat pytest-3.9.1-py3.5.egg/EGG-INFO/top_level.txt
```
_pytest
e
p
s
t
y
```
cat pytest-3.8.2-py3.5.egg/EGG-INFO/top_level.txt
```
_pytest
pytest
```
I Have no record.txt files.

**Comment by RonnyPfannschmidt** [comment]
@ondratu thanks for that detail, i believe that might be a unexpected bug in setuptools, i believe we can elevate that by switching to find_packages in setup.cfg, i'll come up with a branch in a bit

 @jaraco is my initial idea about it being a setuptools bug correct?

**Comment by RonnyPfannschmidt** [comment]
on local testing i observed this to be a bug in setuptools 33 - its fixed already in a more modern version,
the quick workaround is to either install your test requirements, or to have a more modern setuptools, i will adapt the requirement soon

**Comment by RonnyPfannschmidt** [comment]
https://setuptools.readthedocs.io/en/latest/history.html#v34-4-0

so we either move py_modules back or go for a more recent version,
my current preference would be to go for a more recent version - perhaps as recent as 40.x

i'd like to hear other opinions/preferences as well

**Comment by ondratu** [comment]
Yes, updating setuptools solve my problem. Thank's a lot!
