### ISSUE TITLE
pytest 3.9.1 - tmpdir_factory not creating symlink to latest run

### ISSUE THREAD

**Issue by mulawamichal** [pytest-dev/pytest#4179]
hi,

on previous pytest (3.8.2 and earlier) when using a `tmpdir_factory` fixture it was creating subsequent  directories for each of runs in `pytest-of-$USER` and a symlink to most recent one like this:

```
foobar@foobar:~$ ll /tmp/pytest-of-foobar/
total 56
drwxr-xr-x  5 foobar foobar  4096 Oct 17 09:23 .
drwxrwxrwt  5 root   root   36864 Oct 17 09:23 ..
drwxr-xr-x 14 foobar foobar  4096 Oct 17 09:19 pytest-0
drwxr-xr-x  4 foobar foobar  4096 Oct 17 09:20 pytest-1
drwxr-xr-x  4 foobar foobar  4096 Oct 17 09:24 pytest-2
lrwxrwxrwx  1 foobar foobar    30 Oct 17 09:23 pytest-foobar -> /tmp/pytest-of-foobar/pytest-2
```

On latest pystest (3.9.1) the symlink is not getting created - which is a HUUUUUGE issue for me.

**Comment by RonnyPfannschmidt** [comment]
@pytest-dev/core i have to apologize - in my current setup i managed to accidentally push to master

**Comment by RonnyPfannschmidt** [comment]
i rectified the local situation for future use by setting up `git remote set-url upstream --push no_push`

**Comment by nicoddemus** [comment]
It happens, don't worry! Thanks for fixing this up so quickly! 👍

**Comment by dmitrytokarev** [comment]
@RonnyPfannschmidt when setting up protected branch include administrators then don't have to worry for any "local setup":
<img width="406" alt="screen shot 2018-10-17 at 12 42 00 pm" src="https://user-images.githubusercontent.com/7370035/47112063-147c5a80-d20a-11e8-90f6-24a3fe7a9506.png">

**Comment by nicoddemus** [comment]
@dmitrytokarev ahh good idea, just updated the configuration, thanks!

**Comment by asottile** [comment]
damn, ya got me -- now I can't https://github.com/pytest-dev/pytest/commit/ab8907f6f5b7a0d9df645651dbb34732b775b9cb

**Comment by nicoddemus** [comment]
😬
