### ISSUE TITLE
Pytest hold on test execution, continue on other tests in the job and resume on test

### ISSUE THREAD

**Issue by cauvery** [pytest-dev/pytest#4184]
I have a test scenario where test has some scheduling and so need to wait for the schedule to complete about 10 min and then when the schedule time completes, need to continue the test and verify few things.  

I can have a hard wait for that schedule period and have the test continue with verification.  
But this hard wait in single test is going to hold up the whole suite or entire job for that period.  Is there any way to handle this in pytest framework.  Or other alternative is to have this test alone in another job, but do not prefer that extra job if there is good alternative. 

Also tried mark pytest.mark.first.  But this does not help here as the test will hold for wait time either way.  

Need suggestions. Please let me know for any more questions.

Thanks in advance.
Cauvery.

Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by nicoddemus** [comment]
Hi @cauvery,

Currently pytest will always wait for all tests to finish first. This situation seems really unique, I would advise to go with your idea of using a separate job for that test alone.
