### ISSUE TITLE
local build succeeds, travis build fails

### ISSUE THREAD

**Issue by phuntimes** [pytest-dev/pytest#4187]
###  Include a detailed description of the bug or suggestion:

I use some imports from `_pytest.config`, `_pytest.config.argparse`, `_pytest.mark.structures` for type hints. With local virtualenv, all tests pass. On travis, `ModuleNotFoundError` raised for any import from `_pytest`. I'd really like to keep the type hints if I can.

###  `pip list` of the virtual environment you are using:

```
Package         Version   
--------------- ----------
apipkg          1.5       
atomicwrites    1.2.1     
attrs           18.2.0    
blueslip        0.1.0     
certifi         2018.10.15
chardet         3.0.4     
construct       2.9.45    
coverage        4.5.1     
coveralls       1.5.1     
docopt          0.6.2     
execnet         1.5.0     
idna            2.7       
more-itertools  4.3.0     
mypy            0.630     
mypy-extensions 0.4.1     
pep8            1.7.1     
pip             18.1      
pluggy          0.7.1     
py              1.6.0     
pyserial        3.4       
pytest          3.9.1     
pytest-cache    1.0       
pytest-cov      2.6.0     
pytest-mypy     0.3.2     
pytest-pep8     1.0.6     
requests        2.19.1    
setuptools      40.4.3    
six             1.11.0    
typed-ast       1.1.0     
urllib3         1.23 
```

###  pytest and operating system versions:

  - **local** virtualenv from pyenv 3.6.6, macOS
  - **travis** python 3.6, ubuntu trusty (i.e. default)

### Minimal example if possible:

```python
# conftest.py
from _pytest.config.argparsing import Parser

def pytest_addoption(parser: Parser):
    # add options...
```
raises `ModuleNotFoundError: No module named '_pytest.config.argparsing'; '_pytest.config' is not a package` on Travis but passes on local virtualenv.

**Comment by nicoddemus** [comment]
Which version of `pytest` is running on Travis? I'm guessing your local and Travis' versions are different.

**Comment by phuntimes** [comment]
I see in the Travis log:

```
Requirement already satisfied: pytest in /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages
```

looks like its using the pytest version in the cloned virtualenv (default for 3.6)

**Comment by nicoddemus** [comment]
> looks like its using the pytest version in the cloned virtualenv (default for 3.6)

Which pytest version? You can check with:

```console
$ pytest --version
```

Please note that pytest is not installed by default in virtualenv in general, but I believe Travis installs some pytest version by default.

**Comment by phuntimes** [comment]
I added to travis script:

```yaml
before_script:
  - pytest --version
```
log output:
```
pytest --version
This is pytest version 3.3.0, imported from /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest.py
setuptools registered plugins:
  pytest-pep8-1.0.6 at /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest_pep8.py
  pytest-mypy-0.3.2 at /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest_mypy.py
  pytest-cov-2.6.0 at /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest_cov/plugin.py
```

**Comment by phuntimes** [comment]
Great! Issue fixed.

**Comment by nicoddemus** [comment]
OK, I'm closing this then. 👍
