### ISSUE TITLE
Spinning "pytest.main(pytest_args)" via -OO Python executable option flag to the runner

### ISSUE THREAD

**Issue by ilayn** [pytest-dev/pytest#4189]
Over SciPy, we have noticed that one of our entries in the Travis CI matrix didn't respect the `-OO` invocation. However, we know, from a newer issue report, that it should have failed all along. Hence we started to dig a little deeper and found out that the tests are started without the `-OO` flags (maybe a child process or something).

By following the toolchain, it seems that we invoke the actual pytest via `import pytest` and then `pytest.main(pytest_args)` that is run in our testing script `runtests.py` and it starts by executing (see travis link below)

`python -u -OO runtests.py <other args>`

Later on `runtests.py` parses the the args and creates an instance of a pytest Tester and in that `pytest.main()` is called. Our suspicion is that there the flags are not passed on. 

Thus my question: is it possible to spin the pytest run with `-OO` flags to the test runner maybe to `main()`? Or I would appreciate pointers to the documentation if I missed something. 

Links: 

Travis CI invocation point and output: https://travis-ci.org/scipy/scipy/jobs/442766953#L1049
Runtest.py invocation point : https://github.com/scipy/scipy/blob/master/runtests.py#L270
PyTester object : https://github.com/scipy/scipy/blob/master/scipy/_lib/_testutils.py#L60

The version information about pytest and plugins can be found here https://travis-ci.org/scipy/scipy/jobs/442766953#L868

**Comment by nicoddemus** [comment]
> Thus my question: is it possible to spin the pytest run with -OO flags to the test runner maybe to main()? Or I would appreciate pointers to the documentation if I missed something.

Unless I'm missing something, `python -OO -m pytest` will start pytest with optimizations. But you have said that you are executing `python -OO runtests.py` which ultimately calls `pytest.main()` in the same process (I assume), so it should be running with optimizations enabled already...

**Comment by RonnyPfannschmidt** [comment]
in the code there is a subprocess call

**Comment by nicoddemus** [comment]
> indeed the complaints appear in the right places. Should I carry this issue to pytest-xdist? Or is there any other way to forward PYTHONOPTIMIZE=2 setting to the load scheduling workers?

Oh interesting. If you set `PYTHONOPTIMIZE=2` in your environment, does the subprocesses run with optimizations enabled?

**Comment by ilayn** [comment]
It seems so. If I place an `os.environ['PYTHONOPTIMIZE'] = '2'` just before the `pytest.main(args)` call I get 3 separate `WARNING: assertions not in test modules or plugins will be ignored because assert statements are not executed by the underlying Python interpreter (are you using python -O?)` warnings 
hence I think they start with that. 

Probably the existing `sys.flags.optimize` is not read by the workers but do they actually look for the env variable and not the flag?

**Comment by nicoddemus** [comment]
> Probably the existing sys.flags.optimize is not read by the workers but do they actually look for the env variable and not the flag?

Workers don't handle the optimization flag at all actually, when you set the environment variable the Python interpreter handles that automatically.

Handling the optimization flag should probably be done by `execnet` because when xdist takes over on the worker side the interpreter has already been initialized, so there's nothing xdist can do at that point to enable optimizations.

**Comment by ilayn** [comment]
I see. Then my remaining question is why the interpreter doesn't carry over the optimization state over to the workers and it has to be reset for them to register it. Because if I print the `sys.flags.optimize`  without setting the variable I see the value `2` but still they don't start optimized.

**Comment by nicoddemus** [comment]
> I see. Then my remaining question is why the interpreter doesn't carry over the optimization state over to the workers and it has to be reset for them to register it. 

Hmm that I wouldn't know. 😕

**Comment by ilayn** [comment]
No problem. Thank you for your kind help. I'll close this as it is kind of solved.
