### ISSUE TITLE
How to test session-scoped fixture clean-up when writing plugins?

### ISSUE THREAD

**Issue by butla** [pytest-dev/pytest#4193]
I'm trying to modify tests for [pytest-docker](https://github.com/AndreLouisCaron/pytest-docker). One thing that I'd like to add is testing that the session-scoped `docker_services` fixture (which spins up and later destroys a Docker Compose environment) gets rid of the Docker volume it creates.

All of the approaches I have in mind have problems:
1) use the [recommended black box testing](https://docs.pytest.org/en/latest/writing_plugins.html#testing-plugins) and create a small test that will use the fixture.
**The problem:** All of the names are generated randomly. I don't know ahead of time how the volume will be called, so I can't check if it's gone. I could count the volumes before the run and after the run, but that would be flaky if some other process on the machine is working with Docker in the background.
2) write a test using the fixture, do some assertions in it.
**The problem:** Any fixture or test I can create that references `docker_services` will have a smaller scope, so I can't run any test code *after* the fixture is cleaned.

Any thoughts on the subject? Is there something obvious that I'm missing?

**Comment by butla** [comment]
I'm gonna submit a PR to the docs about testing plugins if we get an elegant solution or if this thread :-)

**Comment by nicoddemus** [comment]
> I'm gonna submit a PR to the docs about testing plugins

Great, appreciate it! 😁

**Comment by butla** [comment]
So the approach I took [here] (https://github.com/AndreLouisCaron/pytest-docker/blob/master/tests/test_integration.py#L42) can be described like this:
- the outer test (the test testing the test fixture :) ) prepares a name for the file that will be used to pass data from the inner test
- the filename gets inserted into the string with inner test's Python code by string formatting
- inner tests happen, they write something to the file
- inner tests end, the outer test can retrieve whatever it needs from the file.

Any ideas for a more elegant aproach? If there aren't any, I'll submit that for the docs.

**Comment by nicoddemus** [comment]
I think that approach is fine @butla, I've used it myself on the past.
