### ISSUE TITLE
mark of two parameters - unexpected result

### ISSUE THREAD

**Issue by yoram-s** [pytest-dev/pytest#4211]
With the following example we desire to select only single combination of parameters when executing sanity:
```python
@pytest.mark.parametrize('foo', ['a', 'b', pytest.param('c', marks=pytest.mark.sanity)])
@pytest.mark.parametrize('bar', [1, 2, pytest.param(3, marks=pytest.mark.sanity)])
def test_things(foo, bar):
    assert foo in ['a', 'b', 'c']
    assert bar in [1, 2, 3]
```
```bash
pytest $TEST_FRAMEWORK --sim -m sanity --collect-only
======================== test session starts ============================
platform linux -- Python 3.6.0, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
plugins: xdist-1.22.2, pudb-0.6, forked-0.2
collected 1142 items / 1120 deselected
<Module 'tests/line_rate/test_line_rate.py'>
  <Function 'test_things[1-c]'>
  <Function 'test_things[2-c]'>
  <Function 'test_things[3-a]'>
  <Function 'test_things[3-b]'>
  <Function 'test_things[3-c]'>
```
It was expected that only `test_things[3-c]` will be selected when providing the `-m sanity`. However, multiple tests combination were selected.

**Comment by RonnyPfannschmidt** [comment]
all `3` and all `c` have the marker, so the result is as expected wrt pytest parameterize

note that `3-c` got the marker twice

if only a single combination has the marker, then you need to use a single parameterize

**Comment by RonnyPfannschmidt** [comment]
no

**Comment by asottile** [comment]
I made a terrible (?) thing that does what you want:

```python
import itertools

import pytest


def mark_intersection(params, intersect):
    names = [name for name, _ in params]
    values = [values for _, values in params]
    values = [
        pytest.param(*t, marks=intersect.get(t, ()))
        for t in itertools.product(*values)
    ]
    return pytest.mark.parametrize(names, values)


@mark_intersection(
    (
        ('foo', ('a', 'b', 'c')),
        ('bar', (1, 2, 3)),
    ),
    {
        ('c', 2): pytest.mark.sanity,
    },
)
def test_things(foo, bar):
    assert foo in ['a', 'b', 'c']
    assert bar in [1, 2, 3]
```

```console
$ pytest t.py  -m sanity -vv
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.9.1, py-1.7.0, pluggy-0.8.0 -- /tmp/t/venv/bin/python3
cachedir: .pytest_cache
rootdir: /tmp/t, inifile:
collected 9 items / 8 deselected                                               

t.py::test_things[c-2] PASSED                                            [100%]

==================== 1 passed, 8 deselected in 0.01 seconds ====================

$ pytest t.py -vv
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.9.1, py-1.7.0, pluggy-0.8.0 -- /tmp/t/venv/bin/python3
cachedir: .pytest_cache
rootdir: /tmp/t, inifile:
collected 9 items                                                              

t.py::test_things[a-1] PASSED                                            [ 11%]
t.py::test_things[a-2] PASSED                                            [ 22%]
t.py::test_things[a-3] PASSED                                            [ 33%]
t.py::test_things[b-1] PASSED                                            [ 44%]
t.py::test_things[b-2] PASSED                                            [ 55%]
t.py::test_things[b-3] PASSED                                            [ 66%]
t.py::test_things[c-1] PASSED                                            [ 77%]
t.py::test_things[c-2] PASSED                                            [ 88%]
t.py::test_things[c-3] PASSED                                            [100%]

=========================== 9 passed in 0.02 seconds ===========================
```

**Comment by EtgarIsraeli** [comment]
Hi,
It seems like a very complex way to achieve this, and will be more complex with more than 2 params, which is the many time the case..
Also, we have cases in which test depends on some (>2) Parametric fixtures - see example below.
How can be resolved ?


############## Parametric fixtures ##############
a_list = [1, 2, pytest.param(3, marks=pytest.mark.sanity)] 
@pytest.fixture(params=a_list=)
def a_modifier (request):
	return (request.param)
	
b_list = ['a', 'b', pytest.param('c', marks=pytest.mark.sanity)] 
@pytest.fixture(params=b_list)
def b_modifier (request):
	return (request.param)	
	
c_list = ['x', 'y', pytest.param('z', marks=pytest.mark.sanity)] 
@pytest.fixture(params=c_list)
def c_modifier (request):
	return (request.param)	
	
############## Test ##################
def my_test(a_modifier, b_modifier, c_modifier):
  print(a_modifier, b_modifier, c_modifier)

**Comment by RonnyPfannschmidt** [comment]
@EtgarIsraeli there is no simple solution - what you want to do here is something new and not supported by the underlying libraries/framework components - so its going to be hard

**Comment by EtgarIsraeli** [comment]
Is it something you can add relatively quickly ?
If not, can you guide us to a 'nice'/'not-to-complex' way you can think of in order to achieve that ?

**Comment by RonnyPfannschmidt** [comment]
no on both accounts

**Comment by asottile** [comment]
@EtgarIsraeli my example above generalizes to any number of parameters

**Comment by RonnyPfannschmidt** [comment]
@asottile your example doesn't generalize to different sources of parameters

**Comment by EtgarIsraeli** [comment]
@asottile will it work with parametric Fixtures as well ? (see my last example)
BTW it seems like a very complex way to achieve this.. [as you wrote: 'terrible (?) thing that does what you want' :)]

**Comment by asottile** [comment]
```python
def mark_intersection(params, intersect):
    names = [name for name, _ in params]  # not complicated, just decomposing the parameter
    values = [values for _, values in params]  # not complicated, just decomposing the parameter
    values = [  # the one clever line
        pytest.param(*t, marks=intersect.get(t, ()))
        for t in itertools.product(*values)
    ]
    return pytest.mark.parametrize(names, values)  # not complicated, just constructing output
```

**Comment by EtgarIsraeli** [comment]
Understood, but still does not work for 'fixture(..., params)' right ?

**Comment by asottile** [comment]
> nah it only works for actual `parametrize`
