### ISSUE TITLE
git: pre-commit: output diff on failure

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4230]
I am seeing the following when black would format something, but would appreciate the diff in the output already:

```
black....................................................................Failed
hookid: black                                                                  
Files were modified by this hook.
```

/cc @asottile

**Comment by asottile** [comment]
hmmm, I thought we already had `--show-diff-on-failure` set up

**Comment by asottile** [comment]
:thinking: https://github.com/pytest-dev/pytest/blob/b6fa4e248f16afb277ae229997417ed839931bed/tox.ini#L51

**Comment by blueyed** [comment]
I am not using this via tox here, but via "git commit".
But adding `--show-diff-on-failure` there might be what I've want maybe.

**Comment by blueyed** [comment]
Hmm:

```
black....................................................................Failed
hookid: black
Error: no such option: --show-diff-on-failure
```

**Comment by asottile** [comment]
heh, the original version of pre-commit did that and it was removed because it was a bad user experience (the important error messages would zoom off screen and require scrolling).  Plus most of the time you shouldn't/don't care about the diffs it applied: https://github.com/pre-commit/pre-commit/commit/7bb7f4a4838dbd5d52873187cc9b1b51b83cf0ba

**Comment by blueyed** [comment]
Yeah, it would need to become an option in the config file probably (https://pre-commit.com/#pre-commit-configyaml---top-level).

The current state is a bit bad though: you try to commit and only get a msg that "black would modify" files, but not even which file would be modified - just blocking you from committing.

**Comment by asottile** [comment]
yeah I'm probably not going to add an option to pre-commit to increase noise -- it's a core design principle to not do that :laughing: 

black writes the changes to disk, you can just run `git status` or `git diff` after.  I usually `git add -u && !!` myself (or if I'm curious, I'll `git diff` and then `git add -u` and then `^Rcommit`)

black has a verbose mode which will tell you what files it changed -- maybe that's what you want?

**Comment by blueyed** [comment]
> black has a verbose mode which will tell you what files it changed -- maybe that's what you want?

Maybe.. but I am just using it via the git-commit hook since recently, but it really is a bit annoying having quite some output for `git commit --amend` etc (and some seconds of delay through it also).

Knowing that `black` modified the files on disk is good, but also a bit scary - i.e. I would prefer if a git-commit would not change any local files.

**Comment by asottile** [comment]
`pre-commit` will never commit files on your behalf, it always gives you a chance to inspect the differences made.  Though it sounds to me like you're not even comfortable with the idea of fixers at all?  In that case `black` has a `--diff` mode which doesn't modify, but that's quite the pain -- then you have to install black and/or manually apply its suggestions (defeating the purpose of having black in the first place imo).

**Comment by blueyed** [comment]
Ok, thanks for your explanations - going to close this then.
