### ISSUE TITLE
Import reordering pre-commit hook

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#4233]
Let's introduce a hook for us that orders imports.  Inspired by a recent implicit conflict caused by an import reordering + an import removal. https://github.com/pytest-dev/pytest/pull/4028#issuecomment-432842271

There's basically two options here:

1. [`seed-isort-config`](https://github.com/asottile/seed-isort-config) + [`isort`](https://github.com/pre-commit/mirrors-isort)

there's some configuration that makes black happy that's necessary

2. [`reorder-python-imports`](https://github.com/asottile/reorder_python_imports)

no configuration necessary, the only options are compatible with `black`

**Comment by blueyed** [comment]
I am using and liking `isort` myself.

**Comment by nicoddemus** [comment]
I don't mind much either way, just one thought: isort depends looks on the current pythonpath to decide if an import is third-party or part of the project being formatted; this requires that it is executed on the proper environment (I understand `seed-isort-config` mitigates/eliminates this problem).

Never used `reorder-python-imports` myself.

What do you suggest @asottile?

**Comment by asottile** [comment]
tbh I'm biased ;) -- `reorder-python-imports` can be "too extreme" for some (one import per line, always), though its style choice is aimed at [eliminating merge conflicts as much as possible](https://github.com/asottile/reorder_python_imports#why-this-style).  `reorder-python-imports` is also usually going to be faster as well (`seed-isort-config` needs to read all the files every time, `isort` ~essentially _imports_ things).  `reorder-python-imports` + `seed-isort-config` use the same machinery under the hood which doesn't require things to be importable (though `r-p-i` doesn't need to look at every file all the time)

**Comment by nicoddemus** [comment]
I would vote for `reorder-python-imports` then, and unless someone has a strong preference I think the one opening the PR can decide 😁.

**Comment by blueyed** [comment]
Would be nice to have a matching isort config, so isort can be used to manually sort imports when editing files (in the same way that the hook expects it then) maybe.

**Comment by blueyed** [comment]
I use `:Isort` in Vim, so this already let's the computer do it.
However, I wasn't really aware that the automatic fix is only a `git add` away after all, and then it is only about being interrupted with `git commit` possibly.  I think that is OK for now.
