### ISSUE TITLE
Adjust stacklevel for compat warnings

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4236]
Follow up from https://github.com/pytest-dev/pytest/issues/4131#issuecomment-433015384.

Currently the warnings show this:

```
c:\projects\pytest\.tox\py36\lib\site-packages\_pytest\compat.py:321: RemovedInPytest4Warning: usage of Session.Class is deprecated, please use pytest.Class instead
360  return getattr(object, name, default)
361
```

We need to adjust the warnings stacklevel.

**Comment by pecey** [comment]
I can try and fix this. I would need some help though. If I understand correctly, we need to adjust the stack level for the warnings thrown my the warnings plugin itself.

**Comment by RonnyPfannschmidt** [comment]
@pecey unfortunately thats not how it works - the stacklevel is designated for direct usage, here a wrapper is using getattr - so adjusting the stacklevel for that breaks it

we do have a fix to remove the `safe_getattr` situation by not parsing compat properties as fixture in #4164

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt is right, the stacklevel is already properly set:

```python
def test(request):
    request.node.session.Class
```

```
test-foo.py::test
  C:\pytest\.tmp\test-foo.py:2: RemovedInPytest4Warning: usage of Session.Class is deprecated, please use pytest.Class instead
    request.node.session.Class
```

We only have to merge #4164 then. 👍
