### ISSUE TITLE
Display lru_cache cache_info in very verbose mode?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4249]
With the recent addition of `functools.lru_cache` it might make sense to display its `cache_info` with `-vvv` or some other flag, which would be helpful when investigating performance.

For this it might make sense to wrap it into a separate module, so that it is easier to handle all of them (currently just one, but two already with https://github.com/pytest-dev/pytest/pull/4247).

**Comment by nicoddemus** [comment]
Sounds good. The idea is to show `cache_info` for all `lru_cache`-decorated functions?

**Comment by blueyed** [comment]
Yeah.

**Comment by asottile** [comment]
Maybe instead of hooking into `-v` (I often spam `-vvvvv` since I can't remember how many it is and surely a few extra won't hurt -- and I don't think this info will be helpful in that case), we add a plugin that's something along the lines of `--show-lru-cache-info`?

**Comment by asottile** [comment]
@isidentical is looking into taking this one -- we're discussing some implementation details about this

what I think we're going to do for a first pass is:

- add a new plugin module to handle "internal pytest... stuff" for lack of a better name (maybe `debug`? `internal`? `meta`? idk, naming is hard)
- in this module, add an option like above
- add a reporting mechanism that uses `pkgutil` or some such to iterate through the `_pytest` namespace looking for globals with `lru_cache` attached

or something like that? thoughts?
