### ISSUE TITLE
Fixture Docs

### ISSUE THREAD

**Issue by Bernardoow** [pytest-dev/pytest#4254]
Can I change the address of link to lib in doc/fixtures.rst to pypi?

[Link](https://github.com/Bernardoow/pytest/commit/b0c0911ba30dc69581fcbc012776401c1107d9e3)

**Comment by nicoddemus** [comment]
Sure @Bernardoow, thanks!

(In the future, it might be simpler to just open a PR and ask there 😉)

**Comment by Bernardoow** [comment]
#4257
