### ISSUE TITLE
Mention that warning filter categories are not escaped

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4255]
We should at least mention in the docs that we don't regex-escape the module names for warning filtering, as mentioned in @nedbat's post in his blog: https://nedbatchelder.com/blog/201810/why_warnings_is_mysterious.html

> In my case, I was trying to suppress warnings reported while running tests with pytest. Pytest has its own setting for warnings filters, and it uses its own copy of the warnings.py code for reading them, so that the regexes are not escaped! This is very useful, but could also add to the mystery, since the pytest docs don’t mention the difference.

**Comment by nedbat** [comment]
Nice.  I wondered about putting something here about this, but I ran out of energy :)

**Comment by pecey** [comment]
I can add this to the docs. Is there any particular section on the [warnings](https://docs.python.org/3/library/warnings.html) page this should go into?

**Comment by pecey** [comment]
I can add this to the docs.
