### ISSUE TITLE
Make it easier to access test result information

### ISSUE THREAD

**Issue by cdvonbargen** [pytest-dev/pytest#4263]
It would be great if there was a built in way to make test result reports available in fixture finalizers. Ideally it would be great if a solution was easier than copying the example given here:
https://docs.pytest.org/en/latest/example/simple.html#making-test-result-information-available-in-fixtures

**Comment by d-b-w** [comment]
I would have found this useful when writing a version of the tmpdir fixture which reports the directory that it used

**Comment by Zac-HD** [comment]
Closing this issue because the proposal has had no updates for a long time, and there is a documented way to do this.
