### ISSUE TITLE
Harden isclass?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4266]
In https://github.com/pytest-dev/pytest-django/pull/668 we just learned that Django raises `ImproperlyConfigured` already when `isinstance` is called on `settings`.

I wonder if pytest's `isclass` should be hardened in this regard to return False.

But the real fix would probably be for Django to exclude `__class__` in the wrapped `__getattr__` (or whatever triggers this).

What do you think?

```
In [10]: from django.conf import settings as django_settings

In [11]: isinstance(django_settings, type)
---------------------------------------------------------------------------
ImproperlyConfigured                      Traceback (most recent call last)
<ipython-input-11-9824ac31307c> in <module>()
----> 1 isinstance(django_settings, type)

/usr/lib/python3.7/site-packages/django/utils/functional.py in inner(self, *args)
    211     def inner(self, *args):
    212         if self._wrapped is empty:
--> 213             self._setup()
    214         return func(self._wrapped, *args)
    215     return inner

/usr/lib/python3.7/site-packages/django/conf/__init__.py in _setup(self, name)
     40                 "You must either define the environment variable %s "
     41                 "or call settings.configure() before accessing settings."
---> 42                 % (desc, ENVIRONMENT_VARIABLE))
     43 
     44         self._wrapped = Settings(settings_module)

ImproperlyConfigured: Requested settings, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

```

**Comment by RonnyPfannschmidt** [comment]
im :-1: on this - its insanely tricky to do this right - django should get its act together

**Comment by blueyed** [comment]
> its insanely tricky to do this right

Isn't this just wrapping it with `try … except`?

**Comment by RonnyPfannschmidt** [comment]
@blueyed perhaps im misunderstanding a requirement of django then (i recall that its in a bad shape if its happening once)

in case this can be sorted out with a try/except and a testcase, i'm happy to merge such a pr

**Comment by blueyed** [comment]
Created https://code.djangoproject.com/ticket/29906 for Django.

The problem is that pytest might choke on this during collection, but it can be worked around (https://github.com/pytest-dev/pytest-django/pull/668/files#diff-b8f370066f4a8dcc417f6e09e1689a84R377).
pytest failure during collection: https://travis-ci.org/pytest-dev/pytest-django/jobs/448314459#L527

**Comment by RonnyPfannschmidt** [comment]
@charettes as far as i'm concerned - django settings are implemented sloppy if they fail basic python protocols/tests that aren't related to actual settings contents

**Comment by RonnyPfannschmidt** [comment]
https://github.com/django/django/blob/master/django/utils/functional.py#L305 - stuff like that is a pain

unfortunately python doesn't have a concept of "untouchable state of a object"

**Comment by blueyed** [comment]
@charettes 
> Trying to play with settings is not allowed until they are configured and setup.

pytest is checking if it is a class during collection, and the test that triggered this explicitly tests for Django not being configured (it is about pytest-django not being used if hypothesis import django.conf.settings).

So it is not really "playing with settings" (as `settings.DATABASES` would do).
