### ISSUE TITLE
doc recommends using a src layout

### ISSUE THREAD

**Issue by cykerway** [pytest-dev/pytest#4273]
I'm following this *non-src* layout as shown in [pytest][1] doc:

    setup.py
    mypkg/
        ...
    tests/
        __init__.py
        foo/
            __init__.py
            test_view.py
        bar/
            __init__.py
            test_view.py

The doc says:

>   Now pytest will load the modules as `tests.foo.test_view` and `tests.bar.test_view`, allowing you to have modules with the same name. But now this introduces a subtle problem: in order to load the test modules from the `tests` directory, pytest prepends the root of the repository to `sys.path`, which adds the side-effect that now `mypkg` is also importable. This is problematic if you are using a tool like tox to test your package in a virtual environment, because you want to test the installed version of your package, not the local code from the repository.

>   In this situation, it is **strongly** suggested to use a `src` layout where application root package resides in a sub-directory of your root...

But [tox][2] says it will sdist-package, install and test.

So this is what I don't understand:

>   ...because you want to test the installed version of your package, not the local code from the repository...

I think most of the time during development what we want to test **is** the local code from the repository. This is usually the development or nightly branch, not the stable branch that may be installed on our system.

And I did some experiments. I create a software package `mypkg`, installed its stable branch, and then modified some code in development branch to break the test. If `mypkg` is not put under `src` dir, then pytest will test *local code* because it can find `mypkg` package on the local path, and the test will break as expected. However, if `mypkg` is put under `src` dir, then pytest will instead test *installed code* because it can only find `mypkg` there, and the test won't break while it should.

So only the *non-src* layout is working as expected. It works as expected even with tox: tox will sdist and install the package in an isolated environment, which is not affected by `mypkg` in local path. So tox is indeed testing local code, not installed code, which is what we expect.

Given that *non-src* layout works correctly, why would the doc say it is *a subtle problem* and *strongly* recommend using a *src* layout?

  [1]: https://docs.pytest.org/en/latest/goodpractices.html#choosing-a-test-layout-import-rules
  [2]: https://tox.readthedocs.io/en/latest/#basic-example

**Comment by cykerway** [comment]
About *accidental testing of the worktree*: I think testing worktree is a good preliminary step to make sure the software is working as indeed, and I would test in isolated environments with different python versions if I want a more thorough answer. From the doc I have read, tox does that sdist-install thing automatically, so what being tested in isolated environments is a package *installed* from sdist. In this case, isn't it enough if we just make sure the software is packaged and installed correctly, regardless of whether it's inside `src` or not?

Furthermore, if possible I'd like to have an example of the *wreckage* by testing working tree. Even though I don't think testing working tree gives the final answer, knowing where are the caveats should also be helpful.

**Comment by RonnyPfannschmidt** [comment]
simple - if your set setup is "wrong" like for example having a `__init__.py` in the `testing` folder
then pytest would add your worktree to `sys.path` and in fact test against the worktree even if the installed package is supposed to be tested

the src layout is a protection against that structural issue

**Comment by cykerway** [comment]
From my post above you can see I do two kinds of tests: a *quick* test tests the working tree, hopefully to discover a problem quicker and earlier; a *thorough* test sdists and installs the package to a virtual env and tests it there.

For a quick test, testing the working tree is *intended*. Using a `src` layout only makes this more cumbersome. For a thorough test, the test will be done in an isolated env where only the package not the working tree is installed. So pytest, if working reasonably, won't add my working tree to `sys.path` because I'm testing in the env not in my working tree.

**Comment by cykerway** [comment]
I found some [link](https://github.com/pypa/python-packaging-user-guide/issues/320#issuecomment-389938850) that may be relevant to the *wreckage* you mentioned here. So yes the installed package may work differently from the working tree, but testing working tree is still helpful in discovering problems (and it's faster!). Logic is, testing working tree saying OK doesn't mean the software is OK, but testing working tree saying NOT_OK almost discovers a bug (and you don't need to install the package to discover that bug).

**Comment by RonnyPfannschmidt** [comment]
current due diligence is making an editable install in such a case

**Comment by cykerway** [comment]
How can an editable install of the development version coexist with an already installed stable version? When I was trying that the stable version was removed. Using a virtual env requires me to activate/deactive. Too many key strokes and I have to keep an eye on which env I'm using. IMHO this is more error-prone. I'd recommend working tree for quick test. But seeing that long post I think it's more like an opinion debate so feel free to close at any time if no one else joins.

**Comment by RonnyPfannschmidt** [comment]
@cykerway thats part of the domain of workflows - we try to guide towards practices for growing projects - and for example shadowing installed packages with the working tree has very negative if not downright broken effects to various kinds of package metadata users

for example pytest itself asks certain packages for files belonging to them via package metadata, this might differ from the random worktree vs the installed version

its basically technically impossible to avoid subtle bugs as soon as your project is more complex than a few files, as soon as you use more nuanced features of the python ecosystem, the installation is there to protect you from subtle things that are incredibly hard to figure out in some cases

as things progress in complexity the best practices we advocate are there to protect you and others working on your code from subtle really painful issues
