### ISSUE TITLE
cache dir is created even with "--cache-clear" option

### ISSUE THREAD

**Issue by omriben** [pytest-dev/pytest#4275]
I wish to avoid of all cache files creation.
In order to do this, I ran my tests with this command:
`pytest --cache-clear`

**This cache clear option won't help** - I still see 2 directories that created after each run:

- [ ] __pycache__
- [ ] .pytest_cache

How can I solve this issue?
10X!

**Comment by RonnyPfannschmidt** [comment]
the `--clear-cache` option just does a shutil.rmtree() on the `.pytest_cache` folder before recreating it

the `__pycache__` folder is from python itself and for caching the compiled bytecode

**Comment by omriben** [comment]
@RonnyPfannschmidt 
10X for the quick answer - is there a way to avoid creating `.pytest_cache` directory?

**Comment by RonnyPfannschmidt** [comment]
i beleive `-p no:cacheprovider` disables the related core plugins

**Comment by omriben** [comment]
Works now.
10X!
