### ISSUE TITLE
Add a CACHEDIR.TAG file to the cache directory

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4278]
Via https://github.com/pytest-dev/pytest/issues/1089#issuecomment-434571201.

**Comment by nicoddemus** [comment]
Spec seems to be defined here: http://www.brynosaurus.com/cachedir/spec.html, but appears to be offline/blocked as malware.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/borgbackup/borg/pull/4143/files

http://www.bford.info/cachedir/spec.html

**Comment by nicoddemus** [comment]
Cool, thanks for the link @RonnyPfannschmidt.

In summary (someone please correct me if I'm wrong), we just need to create a file with this exact contents in the cache directory:

```
Signature: 8a477f597d28d172789f06886806bc55
# This file is a cache directory tag created by pytest.
# For information about cache directory tags, see:
#	http://www.bford.info/cachedir/spec.html
```

**Comment by feuillemorte** [comment]
I'll take it

**Comment by feuillemorte** [comment]
PR merged, closing this task. Thanks!
