### ISSUE TITLE
pre-commit: rst: allow pytest directives in changelog entries

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4283]
Via: https://github.com/pytest-dev/pytest/pull/4271#issue-227093306

It is useful to link options etc in changelog entries, but linting fails on them.

**Comment by asottile** [comment]
rst-lint is quite inflexible, there isn't really anything that can be done here

**Comment by blueyed** [comment]
Well, not using it in the first place would be an option.
We're checking docs already for every PR in total, and should/could then instead check them with a generated CHANGELOG.rst then.

**Comment by asottile** [comment]
:man_shrugging: `rst-lint` has definitely saved me in changelogs before, I expect it to be even more helpful to those not familiar with the intricacies of rst

**Comment by nicoddemus** [comment]
👍 on keeping `rst-lint`: it also checks the changelog entries, while the generated changelog is only materialized on releases. It would make the release task much more frustating if it meant having to fix rst syntax problems in the CHANGELOG.

**Comment by blueyed** [comment]
> should/could then instead check them with a generated CHANGELOG.rst then.

**Comment by blueyed** [comment]
I would not sacrifice better documentation because of it.

(Also for linting rst in general I recommend using a linter / syntax highlighting in your editor already.)

**Comment by nicoddemus** [comment]
You mean generating the CHANGELOG during `docs` and checking that?

That would bring the advantage of using full rst syntax and directives (say `:ref:fixtures`)... it is an interesting idea indeed.

**Comment by blueyed** [comment]
Exactly.
