### ISSUE TITLE
Add a session scoped tmpdir

### ISSUE THREAD

**Issue by jsfehler** [pytest-dev/pytest#4288]
Currently, the pytest-splinter plugin implements a session scoped version of tmpdir. To avoid hacking around the fixture, a session scoped tmpdir directly in pytest would be helpful.

See: https://github.com/pytest-dev/pytest-splinter/issues/112

**Comment by RonnyPfannschmidt** [comment]
@jsfehler `tmpdir_factory` and `tmp_path_factory` sort that out as currently multi-scoped fixtures arent possible yet

**Comment by jsfehler** [comment]
Resolved, thanks.
