### ISSUE TITLE
Use same fixture twice: once as test-fixture and once as module 

### ISSUE THREAD

**Issue by EtgarIsraeli** [pytest-dev/pytest#4289]
Hi,

I have a complex fixture, that I want to use as a Test-fixture for some tests, and as a Module-fixture for others tests.
Any nice way to do that ? (inheritage/other..)

Thanks

**Comment by RonnyPfannschmidt** [comment]
the current suggestion is to factor out the inner code and declaring 2 fixtures

the support for multi-scoped fixtures cant be delivered in a timely manner

**Comment by EtgarIsraeli** [comment]
OK. Thanks
