### ISSUE TITLE
Access list of tests after marker filtering was applied

### ISSUE THREAD

**Issue by kalidasya** [pytest-dev/pytest#4291]
pytest_collection_modifyitems is a great way to modify tests (skip, etc) before running them, but it contains all collected item even when -m was used to include/exclude specific markers, which makes sense as it runs before anything.
My question is there a way to access a similar list of tests after the marker filtering was applied?
My goal is to add a specific marker for the last test in a group (also a marker).

**Comment by nicoddemus** [comment]
You can set the `trylast` option when declaring your `pytest_collection_modifyitems` hooks:

```python
@pytest.hookimpl(trylast=True)
def pytest_collection_modifyitems(items):
    ...
```

This will execute the hook as late as possible, after the `pytest_collection_modifyitems` hook of the plugins which filter items have been applied.

**Comment by kalidasya** [comment]
@nicoddemus why I never heard about this??? this is awesome, thank you very much!

**Comment by nicoddemus** [comment]
Cool, glad to help. I'm closing this then. 👍
