### ISSUE TITLE
Propagate marks from fixtures to tests

### ISSUE THREAD

**Issue by mariocj89** [pytest-dev/pytest#4296]
I'd love to see `pytest` forwarding the markers set on fixture to the tests where those are used.

I can see multiple use cases for this (which I've had :P):
- Skip a fixture altogether as there might be an unreliable resource you want to skip.
- Mark all tests that use network by the use of a fixture that sets up some kind of connection.

Example code:

```bash
$ cat pytest_mark.py
import pytest


@pytest.mark.skip
@pytest.fixture
def fixt():
    pass

def test_sample(fixt):
    pass
(3.7) mcorcherojim at PF11AY8S in ~/tmp
$ python3.7 -m pytest pytest_mark.py
======================================================= test session starts ========================================================
platform linux -- Python 3.7.0+, pytest-3.9.3, py-1.6.0, pluggy-0.7.1
rootdir: /home/mcorcherojim/tmp, inifile:
collected 1 item

pytest_mark.py .                                                                                                             [100%]

===================================================== 1 passed in 0.03 seconds =====================================================
```

You can see that the fixture is marked with skip but the test is still run. I'd really like this to be able to automagically mark my tests based on fixtures, which will allow to better organise them based on markers without having to repeat the markers in all the tests.
How is this useful? Let's say you have fixtures that set up the filesystem in same way for you or create fake processes, etc. You can mark all those and then filter the tests to run based on the marker.

Apologies if already reported, I have checked open & closed issues but could not find any referencing this behaviour. There might be a better way to do this, not a pytest expert.

I am happy to send a PR if you point me *generally* to where changes should be made, not familiar with pytest codebase.

**Comment by RonnyPfannschmidt** [comment]
this was explicitly ruled out before since only the trivial case would be do able and in any complex case it would be horribly wrong

i'll find the relevant issue later

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/issues/3664

**Comment by mariocj89** [comment]
👍 Thanks @RonnyPfannschmidt !  Totally missed that issue

**Comment by RonnyPfannschmidt** [comment]
@mariocj89 its next to impossible to find it from the conceptual perspective you asked for in this issue ^^
