### ISSUE TITLE
BUG: Pytest 3.10 doesn't parse minversion correctly

### ISSUE THREAD

**Issue by bashtage** [pytest-dev/pytest#4306]
Pytest 3.10 doesn't correctly parse minversion correctly.  I have 

```
[tool:pytest]
minversion = 3.6
```

in setup.cfg and see `ERROR: setup.cfg:16: requires pytest-3.6, actual pytest-3.10.0'`

Changing 3.6 to 3.06 fixes the problem, but this isn't consistent versioning.

Should correctly pass if if LooseVersion accepts the strings.

```
from distutils.version import LooseVersion
LooseVersion('3.10') > LooseVersion('3.6')

Out[3]: True
```

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [x] Minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
should use a pkg_ressources version
