### ISSUE TITLE
BUG: pytest v3.10.0 collects and runs all tests twice with "." in args (related to dupes)

### ISSUE THREAD

**Issue by animesharma** [pytest-dev/pytest#4310]
- ### On `pytest v3.9.3`:

```
============================= test session starts =============================
platform win32 -- Python 2.7.15, pytest-3.9.3, py-1.7.0, pluggy-0.8.0
rootdir: D:\project-name\tests, inifile: pytest.ini
plugins: xdist-1.24.0, metadata-1.7.0, html-1.19.0, forked-0.2, cov-2.6.0
collected 107 items
```

- ### On `pytest v3.10.0`:

```
============================= test session starts =============================
platform win32 -- Python 2.7.15, pytest-3.10.0, py-1.7.0, pluggy-0.8.0
rootdir:  D:\project-name\tests, inifile: pytest.ini
plugins: xdist-1.24.0, metadata-1.7.0, html-1.19.0, forked-0.2, cov-2.6.0
collected 214 items
```

- These are back to back runs with no code changes whatsoever in between.
- All tests are being collected and run twice on v3.10.0

**Comment by asottile** [comment]
I'm unable to reproduce this myself -- you'll probably need to provide some more information.

I've tried on both linux and windows (though only with python3.6 / python3.7).  The commandline and your configuration file will probably help here -- maybe even your repository if it is open source

**Comment by blueyed** [comment]
> By configuration file do you mean pytest.ini?

Yes.

Does it also happen when not specifying args, i.e. only running `pytest` (maybe with `testpaths` config)?
Are you using symlinks in the config?
Are your tests in separate `test_*.py` files, or all in `__init__.py`?

**Comment by blueyed** [comment]
Also consider trying to git-bisect it - you can use just `pytest --collect-only` for testing then.

**Comment by tfbirk** [comment]
@blueyed - I think I found the cause in our test environment. As you suggested, I looked at the pytest.ini file. We have this for our `testpaths`:
```
testpaths = unit functional integration .
```

The '.' is causing the doubling, so it's grabbing the tests in the subfolders twice. If I remove the '.', then we get closer to the expected number.

**Comment by blueyed** [comment]
This should get handled via https://github.com/blueyed/pytest/blob/cb57159e017747609e540c9be0f41e42ec6f9ef7/src/_pytest/main.py#L595-L602, and therefore likely regressed/changed due to e04182364.

**Comment by blueyed** [comment]
You are not using `keepduplicates = true`, do you?

**Comment by blueyed** [comment]
This duplicates `_collectfile` as with Session.
It appears to be quite messy in there..  e.g. I think the python plugin should not call `ihook.pytest_collect_file(path=path, parent=self)` itself (i.e. a file should be collected only once), and `_collectfile` is needed here, since the session plugin calls it when `root` gets set to a package..

**Comment by blueyed** [comment]
The patch above is not good in general, but might help in your case already.

> If I remove the '.', then we get closer to the expected number.

Does "closer" mean that it is still off?
Do you have a `__init__.py` in `.`?

**Comment by tfbirk** [comment]
Removing the `.` makes it exactly right, no duplicates. I wasn't sure at first, but now I am. I'm using pip to install pytest, so I'm not sure if I can patch. I don't think we need the `.` at all; there aren't any tests outside the subfolders. In the tests root folder, there is an empty `pytest.ini` and a `conftest.py` file. I don't remember why it was added in the first place, but it only started producing duplicates with pytest v3.10.0.

**Comment by blueyed** [comment]
Can you please try https://github.com/pytest-dev/pytest/pull/4319?
