### ISSUE TITLE
Custom format in the summary

### ISSUE THREAD

**Issue by datapythonista** [pytest-dev/pytest#4311]
It'd be very useful to be able to customize the output format of pytest summary. This would allow for example in azure-pipelines, to display the errors in the main dashboard, without having to enter the log (would save a decent amount of time, as the logs can be long and difficult to search, besides slow to load).

See what I mean in this screenshot:
![azure_errors](https://user-images.githubusercontent.com/10058240/47984588-f1d5b700-e0ce-11e8-9d53-a6c545ef139f.png)
 (or in the page directly: https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=2349&view=logs)

Ideally, this could work similar to `flake8`:
```
flake8 --format="##ERROR:[sourcepath=%(path)s;linenumber=%(row)s;code=%(code)s;]%(text)s" .
```

So, the current behavior:
```
$ pytest demo -rf
[...]
======================================================================= short test summary info ========================================================================
FAIL demo/tests/test_some_stuff.py::test_that_fails
================================================================== 1 failed, 5 passed in 0.18 seconds ==================================================================
```

Could be extended to work like:
```
$ pytest demo -rf --format="##ERROR:[sourcepath=%(path)s;linenumber=%(row)s;code=%(code)s;]%(text)s"
[...]
======================================================================= short test summary info ========================================================================
##ERROR:[sourcepath=demo/tests/test_some_stuff.py;linenumber=45;code=FAIL] assert 100 == 1000
================================================================== 1 failed, 5 passed in 0.18 seconds ==================================================================
```

Which would display the information in the azure dashboard, and I guess would be useful in other context, like parsing the input with `pytest ... | grep "^##ERROR" | cut -d";" ...` and automating tasks...

I think this should be doable in a simple way by creating a function that it's called when generating those lines (e.g. https://github.com/pytest-dev/pytest/blob/master/src/_pytest/skipping.py#L217)

Is there already a way to achieve what I want that I'm missing? If not, is this a feature you'd be happy to have in pytest? I'm happy to contribute a PR.

**Comment by blueyed** [comment]
See https://github.com/pytest-dev/pytest/issues/5047.

**Comment by gnikonorov** [comment]
@datapythonista - I am closing this issue as per @asottile's comment above. If you believe that my closing this issue is in error, please kindly reopen this issue
