### ISSUE TITLE
Missing `param` attribute on request if params are taken from an outer file

### ISSUE THREAD

**Issue by omriben** [pytest-dev/pytest#4318]
Hi,
Since all of my fixtures are being used in all over my project, I put them all in a single file `pytest_plugin.py`.  I recently added 2 new fixtures:

1. DATA_DRIVEN - fixture for loop runs
2. FILE_SETTER - fixture for configuring "params" argument for DATA_DRIVEN fixture

the problem - putting hard coded list for DATA_DRIVEN "params" **WORKS**, while getting it from an outer file **FAILS**.
I get `AttributeError: 'SubRequest' object has no attribute 'param'`

my questions:
- how do I solve it?
- is there a better way to configure another fixture's "params"?

-------

```python
# pytest_plugin.py
data_driven_params = None

@pytest.fixture
def FILE_SETTER():
    def set_file(path):
        global data_driven_params
        if data_driven_params = FileUtils.get_file_params(path)
        return data_driven_params
    return set_file

@pytest.fixture(params=data_driven_params)
def DATA_DRIVEN(request):
    param = request.param
    yield from handle_param(param)

def handle_param(param):
    yield param
```
```python
# test.py
def test_one(self, FILE_SETTER):
    FILE_SETTER('/tmp/data.json')

def test_data(self, DATA_DRIVEN):
    print(DATA_DRIVEN['name'])
    print(DATA_DRIVEN['age'])
```
```json
# /tmp/data.json
[
    {"name": "John", "last_name": "Doe", "age": 12345},
    {"name": "Avi", "Tal": "Doe", "age": 988776655}
]
```

**Comment by RonnyPfannschmidt** [comment]
its impossible to do that as you outlined- test collection happens before test execution - and in your example you configure test collection at test execution time

the proposed solution for cases like this is to use a mark to store the data and a own call to `pytest_generate_tests` to pass the parameters

**Comment by omriben** [comment]
@RonnyPfannschmidt 10X for the answer.
I've changed it and now trying to use `pytest_generate_tests`

now I have 2 fixtures:
1) DATA_DRIVEN: the fixture that my test use:
```
@pytest.fixture
def DATA_DRIVEN(request, GET_FILE_DATA):
    print('\nfile is ' + str(GET_FILE_DATA))
    yield from FileUtils.get_file_params(GET_FILE_DATA)
```

2) GET_FILE_DATA: the fixture that can be multiplied and used by DATA_DRIVEN fixture:
```
@pytest.fixture
def GET_FILE_DATA(file_data):
    yield file_data
```

Here, I enable multiple values for the second fixture (list of 2 files):
```
def pytest_addoption(parser):
    parser.addoption("--file_data", action="append", default=['/PATH1/data1.json', '/PATH2/data2.json'])
```

```
def pytest_generate_tests(metafunc):
    if 'file_data' in metafunc.fixturenames:
        metafunc.parametrize("file_data", metafunc.config.getoption('file_data'))
```
data1.json file:
```
[
	{"name": "NAME_1",  "age": 46},
	{"name": "NAME_2", "age": 34} .  # <-- this won't be printed
]
```
data2.json file:
```
[
	{"name": "TD2_name_1", "age": 12}, # <-- this won't be printed
	{"name": "TD2_name_2", "age": 22}
]
```
and this is my test:
```
def test_data(self, DATA_DRIVEN):
        print(DATA_DRIVEN['name'])
```

but this is my output - **2 of the 4 names aren't printed** (2 PASS & 2 **ERROR**):

> file is /Users/omri/Desktop/tmp/test_data.json
> name is: NAME_1
> PASSED
> payment_test.py::TestPayment::test_data[/Users/omri/Desktop/tmp/test_data.json] ERROR
> payment_test.py::TestPayment::test_data[/Users/omri/Desktop/tmp/test_data2.json] 
> 
> file is /Users/omri/Desktop/tmp/test_data2.json
> name is: TD2_name_1
> PASSED
> payment_test.py::TestPayment::test_data[/Users/omri/Desktop/tmp/test_data2.json] ERROR

and this is the errors log:
>  ERROR at teardown of TestPayment.test_data[/Users/omri/Desktop/tmp/test_data.json] 
> yield_fixture function has more than one 'yield':
> 
>     @pytest.fixture
>     def DATA_DRIVEN(request, GET_FILE_DATA):
>         print('\n\nfile is ' + str(GET_FILE_DATA))
>         yield from FileUtils.get_file_params(GET_FILE_DATA)
> /Users/omri/Desktop/ws/automation/automation_infra/pytest_plugin.py:136
>  ERROR at teardown of TestPayment.test_data[/Users/omri/Desktop/tmp/test_data2.json] 
> yield_fixture function has more than one 'yield':
> 
>     @pytest.fixture
>     def DATA_DRIVEN(request, GET_FILE_DATA):
>         print('\n\nfile is ' + str(GET_FILE_DATA))
>         yield from FileUtils.get_file_params(GET_FILE_DATA)
> /Users/omri/Desktop/ws/automation/automation_infra/pytest_plugin.py:136


**any ideas?**

**Comment by RonnyPfannschmidt** [comment]
your parametrization uses the **file name** instead of the **file content** for the declaration of the elements - which is the main reason for the lower number of tests

as for the selection of data thats being used in the test, without the code being provided i am entirely unaware what it does (my guess would be that it simply takes the last item of the file as data

**Comment by omriben** [comment]
@RonnyPfannschmidt 10X for the answer.
I get the Json type data with the "FileUtils.get_file_params()" method.
I decided to change it to only 1 file (I need to have the file path as parameter because test might have 8-9 parameters (name, age, number, gender...) and can't write them all in terminal.

```
def pytest_addoption(parser):
    parser.addoption("--file_data_driven", action="store", default='/PATH1/test_data.json')
```
data1.json file:
```
[
	{"name": "NAME_1",  "age": 46},
	{"name": "NAME_2", "age": 34} .  # <-- this won't be printed
]
```
here I get the list of dictionaries for the data driven test:
```
@staticmethod
    def get_file_params(path):
        with open(path) as f:
            data = json.load(f)
        return data
```

this is the fixture - now it reads the 1 file supplied by user in terminal, and should run on the list of dictionaries in the test: 
```
@pytest.fixture
def DATA_DRIVEN(request):
    file_name = request.config.getoption("--file_data_driven")
    for dictionary in FileUtils.get_file_params(file_name):
        yield dictionary
```

and this is the test:
```
    def test_data(self, DATA_DRIVEN):
        print('name is: ' + DATA_DRIVEN['name'])
```

but still, running gives only first row's name ("NAME_1").
**Is there a way to make fixture run multiple times without using "params" argument**

**Comment by omriben** [comment]
Tried pip install for pyrest-configure, pyrest, pyresttest and no such packages were found - its known in other name?

**Comment by RonnyPfannschmidt** [comment]
sorry that was a  typo on the mobile phone - the hook is `pytest_configure`

**Comment by omriben** [comment]
This package is also unknown by pip install, but I'll find some other solution
10X @RonnyPfannschmidt !
