### ISSUE TITLE
Documentation needed on usage context of `testdir.copy_example`

### ISSUE THREAD

**Issue by butla** [pytest-dev/pytest#4320]
As for the docs, the function is mentioned only [here](https://docs.pytest.org/en/latest/writing_plugins.html#testing-plugins), but it's a bit enigmatic. Why is it called an example? Does it just copy any file from the project's directory into the testdir?

**Comment by blueyed** [comment]
AFAIK, yes.
I suggest looking at the code, and where it gets used:
https://github.com/pytest-dev/pytest/blob/176d27440ce04d26d9d6a2dd590a5f2cb39f4fa2/src/_pytest/pytester.py#L660-L702

A PR to improve the docs would be appreciated, of course.
