### ISSUE TITLE
Can not ignore RemovedInPytest4Warning produced by allure-pytest

### ISSUE THREAD

**Issue by deepjia** [pytest-dev/pytest#4323]
platform darwin -- Python 3.7.0, pytest-3.10.0, py-1.7.0, pluggy-0.8.0
plugins: xdist-1.24.0, rerunfailures-4.2, forked-0.2, allure-pytest-2.5.3

Since pytest 3.9, i am not able to ignore RemovedInPytest4Warning produced by allure-pytest:

I start tests by:
```
PYTHONDONTWRITEBYTECODE=1 pytest case/test_type.py -W ignore:RemovedInPytest4Warning --alluredir=xml_report
```
I got lots of
```
RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
  Please use node.get_closest_marker(name) or node.iter_markers(name).
  Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
    yield (label_type, marker.args[0])
```
I was able to ignore them before pytest 3.9

**Comment by nicoddemus** [comment]
Closing as since 4.1 that feature has been removed, and the warning is no longer emitted.
