### ISSUE TITLE
[HELP] How to get option from pytest.ini  under custom section which is not under [pytest]

### ISSUE THREAD

**Issue by megachweng** [pytest-dev/pytest#4341]
```python
# content of pytest.ini
[pytest]
addopts = -v

[project]
version = 5
prefix = v5
```
```python
#content of test file
def test_option(request):
    version = request.config.getini('version')
    assert version == '5'
```

and will raise  `ValueError: unknown configuration value: 'version'`.
I know I can place version under `[pytest]` section, but threre should be a better way to manage it.

**Comment by RonnyPfannschmidt** [comment]
the first thing to note is - that this was never supported to begin with

you can still get the relevant object however - `request.config.inicfg.config` should be the root level config if i recall correctly - and its possible to go from there to your project section
