### ISSUE TITLE
Pytest's own tests fail with pytest-randomly

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4351]
Some tests are failing when installing pytest-randomly.

I've tried using `-p no:randomly` with the inner `runpytest`, but it appears that it has no (or not enough) effect - IIRC plugins can only be added there, but not removed.

Also this would not really be a general solution (i.e. when using another similar plugin with another name), so maybe a whitelist should be used always?!

**Comment by blueyed** [comment]
Also installing/using pytest-pdb is problematic, because its `pytest_configure` raises ValueError the second time it gets called to configure/extend `pdb.Pdb`.

The general problem here appears to be that pytester uses any outer plugins also for internal runs.

https://github.com/pytest-dev/pytest/pull/4518 should fix this.

**Comment by RonnyPfannschmidt** [comment]
@blueyed it should be noted that this fix breaks testing for plugins using pytester

**Comment by blueyed** [comment]
It is a sad state of affairs that you cannot pytest-randomly when working on things that have no clear tests defined in some corresponding test_* file, and you would like to test this quickly/randomly.
