### ISSUE TITLE
ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4355]
I've seen the following on full run of the test suite:

```
============== 1 failed, 2270 passed, 83 skipped, 13 xfailed in 271.31 seconds ==============
Exception ignored in: <_io.FileIO name='/dev/null' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>
Exception ignored in: <_io.FileIO name=13 mode='rb+' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name=13 mode='rb+' closefd=True>
Exception ignored in: <_io.FileIO name=15 mode='rb+' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name=15 mode='rb+' closefd=True>
Exception ignored in: <_io.FileIO name='/dev/null' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>
Exception ignored in: <_io.FileIO name=19 mode='rb+' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name=19 mode='rb+' closefd=True>
Exception ignored in: <_io.FileIO name=21 mode='rb+' closefd=True>
ResourceWarning: unclosed file <_io.FileIO name=21 mode='rb+' closefd=True>
```

Related to https://github.com/pytest-dev/pytest/issues/3879 in that it would be nice if those would cause CI to fail.

I have not investigated what triggered them.
This was on 8baeb90.

**Comment by asottile** [comment]
It's going to be hard to turn these into failures -- these are exceptions triggered as the interpreter is shutting down.  I think the best we can do is fix them and hope they don't come back.

From what I can tell, the only opening of `devnull` in the project is in [`FDCaptureBinary`](https://github.com/pytest-dev/pytest/blob/d4fdf793b55de24b7812b1b9ae65f7dbdfa0eb7d/src/_pytest/capture.py#L519).  I suspect ~something is making module-level references to an instance of these (which gets cleaned up at interpreter shutdown).

**Comment by RonnyPfannschmidt** [comment]
lets just do a gc.collect in session shutdown to see more information, perhaps even after each test (perhaps as part of the lsoff plugin)

**Comment by asottile** [comment]
A `gc.collect` isn't necessarily going to catch this.  It's likely module globals holding onto these :/

**Comment by blueyed** [comment]
Is it maybe coming from inner pytest runs?
Or would those show up with the particular tests then only?

**Comment by asottile** [comment]
mayyybe, but probably much less likely (unless they're complex second or third generation gc objects and the tests that leak them happen to be at the end).  I've really only seen the "Exception ignored ..." errors during module teardown though 🤷‍♂️

**Comment by blueyed** [comment]
=> https://github.com/pytest-dev/pytest/pull/5006
