### ISSUE TITLE
Use collect-only to print test description

### ISSUE THREAD

**Issue by yoram-s** [pytest-dev/pytest#4371]
Looking for means to print out the test documentation.
When using `--fixture` the print out provides the docstring description of the fixture.
We are looking for a way to printout the test cases description.

It is useful for reporting the test cases under different markers or for the whole tests suite

**Comment by jeffreyrack** [comment]
Any thoughts on what the ideal way to show the test descriptions would be while running tests?

Playing around with it, and most ways of showing it come up a little awkward, especially with multi-line docstrings:
```
example_description.py::test_b
This test has
a multi-line docstring.

example_description.py::test_b PASSED                                    [100%]
```

But it looks a bit awkward...I can't help but feel like there's gotta be a better way to display the test description while the tests are running.
