### ISSUE TITLE
unable to add cmd line option dynamically

### ISSUE THREAD

**Issue by revesansparole** [pytest-dev/pytest#4384]
I want to run pytest with coverage option only when the command is not launched inside pycharm. Previously I just added a hook in conftest.py and it was working well:
~~~~
def pytest_cmdline_preparse(args):
    if 'PYCHARM_HOSTED' not in os.environ:
        args.append("--cov=waloupkg")
~~~~
However the latest pytest calls this hook only after pytest-cov hooks have been already called and I'm unable to launch the cov pluggin as demonstrated below. In case 1) I do not get a coverage report while in case 2) I get one (not displayed here).

1) This is what happen when I do not specify '--cov' on the command line expecting my hook to do it for me:
~~~~
(toto) C:\Users\jchopard\Documents\eval\pkging\waloupkg
>pytest -s
cov: pytest_load_initial_conftests ['--maxfail=2', '-rf', '-s']
mine: pytest_cmdline_preparse
=============================================== test session starts ================================================
platform win32 -- Python 3.7.1, pytest-3.10.0, py-1.7.0, pluggy-0.8.0
rootdir: C:\Users\jchopard\Documents\eval\pkging\waloupkg, inifile: setup.cfg
plugins: cov-2.6.0
collected 1 item
~~~~
2) This is what happen when I explicitly specify '--cov' on the command line
~~~~
(toto) C:\Users\jchopard\Documents\eval\pkging\waloupkg
>pytest -s --cov
cov: pytest_load_initial_conftests ['--maxfail=2', '-rf', '-s', '--cov']
cov: __init__
cov: start
mine: pytest_cmdline_preparse
=============================================== test session starts ================================================
platform win32 -- Python 3.7.1, pytest-3.10.0, py-1.7.0, pluggy-0.8.0
rootdir: C:\Users\jchopard\Documents\eval\pkging\waloupkg, inifile: setup.cfg
plugins: cov-2.6.0
collected 1 item
~~~~

PS: I tried to use `pytest_load_initial_conftests`instead of `pytest_cmdline_preparse` but the hook was never called.

**Comment by revesansparole** [comment]
addendum: apparently the problem is not the order but the fact that `pytest_configure` does not exists anymore in pytest-cov. I tried to add it by hand but pytest is not calling it.

**Comment by blueyed** [comment]
Try setting `PYTEST_ADDOPTS` maybe dynamically instead.

**Comment by revesansparole** [comment]
@blueyed my understanding of the problem is that the --cov option need to be set before the calls to pytest-cov plugin initialisation. I don't see any entry point in the workflow of pytest that would allow me to do that. Am-I missing something?

**Comment by blueyed** [comment]
What I've meant is to set `PYTEST_ADDOPTS="--cov …"` dynamically (via a wrapper that you would use in pycharm).  Just some idea.

But in general it might sound like some kind of regression (either in pytest or pytest-cov), so it might be useful to know when this stopped working for you?  I would guess with pytest-cov 2.6 maybe.

**Comment by Zac-HD** [comment]
pytest-dev/pytest-cov#241
