### ISSUE TITLE
pytest overwrites .gitignore and README.md when run with --pdb

### ISSUE THREAD

**Issue by cdeil** [pytest-dev/pytest#4393]
There's an issue that was introduced in #3982 .

Running `pytest -v test.py --pdb` on a test that raises an exception will create or overwrite the `.gitignore` and `README.md` files in the current working directory.

At least I had one case where this happened, with `Python 2.7.15, pytest-3.10.1, py-1.7.0, pluggy-0.8.0` because for some reason there:
```
cachedir: .
```
See https://gist.github.com/cdeil/a90f0b5727a6187d06ecbf6be68af0ad

This writing of `.gitignore` and `README.md` was introduced in #4390, so cc @nicoddemus .

Can you reproduce the issue?

**Comment by blueyed** [comment]
The README.md should not be overwritten, but .gitignore might be:
https://github.com/blueyed/pytest/blob/ce0ed9cd22f40d9753efeb59e62c9bb2335877cb/src/_pytest/cacheprovider.py#L123-L131

**Comment by cdeil** [comment]
@blueyed - Indeed, `README.md` wasn't overwritten.

In my project there is only a `README.rst`. So pytest created a new `README.md` file.

**Comment by blueyed** [comment]
See https://github.com/pytest-dev/pytest/pull/4394 - however `cache_dir = .` is not really a good setting in  general AFAICT (except for finding corner cases.. ;))

**Comment by blueyed** [comment]
Ah, I've thought you configured it explicitly.
Check what `inifile` is set to (from the header).
Are you using tox by chance?

**Comment by blueyed** [comment]
I get `.pytest_cache`:
```
platform linux2 -- Python 2.7.15, pytest-4.0.0, py-1.7.0, pluggy-0.8.0 -- /tmp/gammapy/venv2/bin/python
cachedir: .pytest_cache
rootdir: /tmp/gammapy, inifile: setup.cfg
collecting ... 
Gammapy test data availability:
gammapy-extra ... no
Gammapy environment variables:
GAMMAPY_EXTRA = not set
collected 0 items / 1 errors                                                                
```

**Comment by blueyed** [comment]
Check the code around here:
https://github.com/pytest-dev/pytest/blob/9dec146edf5baf74a82b91fc85762c8676b604b8/src/_pytest/cacheprovider.py#L279-L282
