### ISSUE TITLE
Pytest dependency of markers fails with decorator  

### ISSUE THREAD

**Issue by omkarkhatavkar** [pytest-dev/pytest#4396]
**Issue Details** :  

I have a scenario where we do pre-upgrade tests after that we run the post-upgrade test. we collect the pre-upgrade the test based on decorator of report_if_failed. 

I have some markers as @post_upgrade, @pre_upgrade and @pytest.mark.depending(test='test_pre_upgrade') which is based on the test result of the @pre_upgrade test.

We have decorator of  @skip_if_bug_open('Bugzilla', 12121) which will skip the test if bug opened 
We have the @pytest.mark.depending(test='test_pre_upgrade') which will skip the test if the pre-upgrade test failed. 

Issue => depedncy of skip_if_bug_open is failed with  @pytest.mark.depending(test = 'test_pre_upgrade')
even if skip_if_bug_open is passed it still runs the @pytest.mark.depending(test = 'test_pre_upgrade'). We wanted to avoid @pytest.mark.depending(test = 'test_pre_upgrade') if     @skip_if_bug_open('bugzilla', 12121) is passed 
```
    @report_if_failed
    @pre_upgrade
    def test_pre_upgrade(self):
      assert 0;



    @pytest.mark.depending(test = 'test_pre_upgrade')
    @skip_if_bug_open('bugzilla', 12121)
    @post_upgrade
    def test_post_upgrade(self):



      def report_if_failed(func):
      ""
    "report test status in global_dict if it is failed. This will be helpful
    for skipping post_upgrade tests.
    "
    def wrapper( * args, ** kwargs):
      try:
      func( * args, ** kwargs)
    except Exception:
      status_dict = {
        args[0].__class__.__name__: {
          '{0}'.format(func.__name__): "failed"
        }
      }
    create_dict(status_dict)
    raise
    return wrapper



    # content of conftest.py
    def pytest_collection_modifyitems(session, config, items):
      for item in items:
      scenario_class_name = item.nodeid.split('::')[-2]
    scenario_entity = get_entity_data(scenario_class_name)
    for marker in item.own_markers:
      if 'depending' in marker.name and 'test' in marker.kwargs:
      depending_test = marker.kwargs.get('test')
    if scenario_entity.get(depending_test) == "failed":
      skip_test = pytest.mark.skip(reason = "As dependent pre-upgrade {1} got failed".format(item.name, depending_test))
    item.add_marker(skip_test)
        
```

**Comment by RonnyPfannschmidt** [comment]
without seeing the decorators we cant really figure what you did hide by accident from pytest

**Comment by omkarkhatavkar** [comment]
I think it no more valid issue, we can close this.
