### ISSUE TITLE
Test file not found during test collection

### ISSUE THREAD

**Issue by standage** [pytest-dev/pytest#4404]
Greetings, and thanks as always for your excellent work!

I recently upgraded to pytest 4.0 and I now get the following error when executing tests.

```
$ pytest --cov=kevlar kevlar/tests/*.py -m 'not long and not toolong'
Test session starts (platform: darwin, Python 3.6.7, pytest 4.0.1.dev1+g9dec146e, pytest-sugar 0.9.1)
rootdir: /Users/daniel.standage/Software/kevlar, inifile:
plugins: xdist-1.24.0, sugar-0.9.1, forked-0.2, cov-2.6.0
collecting ... 

Results (0.03s):
ERROR: not found: /Users/daniel.standage/Software/kevlar/kevlar/tests/test_alac.py
(no name '/Users/daniel.standage/Software/kevlar/kevlar/tests/test_alac.py' in any of ())
```

The file in question exists, and when I invoke the file directly with `pytest kevlar/test/test_alac.py` the test works fine. This behavior is the same for pytest 4.0.0 and for the latest Github master.

**Comment by blueyed** [comment]
Are symlinks and/or packages involved here?
Can you git-bisect it to a specific commit in pytest that broke it, please?

**Comment by standage** [comment]
Symlinks: no. Packages: yes. It's a package I'm developing [here](https://github.com/dib-lab/kevlar). I'll see if I can git-bisect the issue.

Sorry I've been unable to isolate a small test example. And installing it yourself is harder than it should be at the moment since it relies on an unreleased version of another github package. I usually do something like the following to set up a dev environment on a new machine.

```
$ cd kevlar/
$ pip install -U pip setuptools
$ pip install cython pysam networkx scipy pandas
$ pip install git+https://github.com/dib-lab/khmer.git  # better chance of success when cython is already installed
$ pip install -e .
```

Some weirdness:
- Things work fine when I invoke the test file directly: `pytest kevlar/tests/test_alac.py`
- Things work fine when I invoke all of the tests *except this one* with `pytest $(ls kevlar/tests/*.py | grep -v alac)`
- Things work fine when I invoke the test file in pairs with every other test file `for file in $(ls kevlar/tests/*.py | grep -v alac); do pytest $file kevlar/tests/test_alac.py`

**Comment by ipmb** [comment]
Seeing a similar issue on 4.0.0. `git bisect` reports:

```
3137c89cf1232d5c68802cdc187354b8d9909f31 is the first bad commit
commit 3137c89cf1232d5c68802cdc187354b8d9909f31
Author: Daniel Hahler <git@thequod.de>
Date:   Thu Nov 8 00:54:51 2018 +0100

    Fix/improve handling of chdir with no-args and testpaths

    Fixes https://github.com/pytest-dev/pytest/issues/4332.

:040000 040000 b838be74b2381e8099fdcfe8ee11b65072583236 e10eb4bba2c6061029ac829ad9cd4c3a32ca273c M	src
:040000 040000 4710f7fa341f181287e744bbf5c4175a4bc57835 f1feab1f0c834e3a89ca914a5df7b437dce731b7 M	testing
bisect run success
```

**Comment by standage** [comment]
Ok, here's a minimal example reproducing the bug: https://github.com/standage/pytest-issue-4404

Run `pytest bogusmodule/tests/*.py` to see the error message.

It looks like the `__init__.py` file in the `tests/` directory is the culprit. When it is included on the command line, the error message is printed. When it's not included, everything runs fine.

One could argue that the user shouldn't include `__init__.py` as one of the inputs. But even if that behavior is not supposed to be supported, the error message is pretty unclear.

**Comment by mdmintz** [comment]
@standage Can you check if this is still an issue on the latest version of ``pytest``?

**Comment by mdmintz** [comment]
@blueyed I expect this issue can be closed. It's from 2018 on pytest 4.0.0 - there have been significant changes from then to now on 7.0.0 with how test collection works.

**Comment by standage** [comment]
I'm happy to close this for now. I continue to use pytest extensively in a few projects, and this hasn't been an issued recently. Thanks!
