### ISSUE TITLE
testpaths + pyargs regression in 4.0.0

### ISSUE THREAD

**Issue by ipmb** [pytest-dev/pytest#4405]
I was using the following config to test specific modules, but it looks like they are now assumed to be relative paths instead of pyargs:

```ini
addopts = --pyargs
testpaths =
    module_one
    module_two
```

The exact error is:

```
ERROR: file or package not found: /path/to/cwd/module_one (missing __init__.py?)
```

Previously, `module_one` would be found on the `PYTHONPATH` instead of looking in the current working directory.

`git bisect` reports:

```
3137c89cf1232d5c68802cdc187354b8d9909f31 is the first bad commit
commit 3137c89cf1232d5c68802cdc187354b8d9909f31
Author: Daniel Hahler <git@thequod.de>
Date:   Thu Nov 8 00:54:51 2018 +0100

    Fix/improve handling of chdir with no-args and testpaths

    Fixes https://github.com/pytest-dev/pytest/issues/4332.

:040000 040000 b838be74b2381e8099fdcfe8ee11b65072583236 e10eb4bba2c6061029ac829ad9cd4c3a32ca273c M	src
:040000 040000 4710f7fa341f181287e744bbf5c4175a4bc57835 f1feab1f0c834e3a89ca914a5df7b437dce731b7 M	testing
bisect run success
```

**Comment by RonnyPfannschmidt** [comment]
interesting find and very unexpected combination

**Comment by ipmb** [comment]
Is there a more standard way to accomplish the same thing? I'm doing something like this in `conftest.py` to dynamically adjust the `testpaths` based on the environment:

```python
def pytest_configure(config):
    """Adds custom apps to testpaths"""
    # ...
    if condition_x:
            config.args.remove('module_two')
    if condition_y:
        config.args.append('module_three')
```

**Comment by RonnyPfannschmidt** [comment]
@ipmb its not quite clear what your actual use-case is - without a better understanding of the actual goal i cant even remotely approach giving a sound/sane suggestion

**Comment by ipmb** [comment]
When I run `pytest` I want it to test different modules in my project based on the current environment (defined via environment variables and/or a config file). I've defined a default set of modules in `setup.cfg` like so:

```ini
[tool:pytest]
addopts = --pyargs
# Additional paths are dynamically appended in conftest.py
testpaths =
    module_one
    module_two
```

At runtime, I use the `pytest_configure` function to inspect the current environment and adjust the `testpaths` accordingly as shown in my previous comment.

**Comment by RonnyPfannschmidt** [comment]
@ipmb and why are those picked based on env vars? thats a key point for suggesting a solution

**Comment by blueyed** [comment]
The use case is valid, and https://github.com/pytest-dev/pytest/pull/4411 should fix it.

**Comment by RonnyPfannschmidt** [comment]
@blueyed great job :+1:
