### ISSUE TITLE
pytest's own tests require hypothesis / make it optional?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4410]
Currently pytest's own tests with `pip install -e '.[testing]'` will fail with:

> ModuleNotFoundError: No module named 'hypothesis'

(testing/python/metafunc.py)

So either testing/python/metafunc.py should be skipped without hypothesis, or we should add it to the "testing" extras.

**Comment by RonnyPfannschmidt** [comment]
i believe adding to the testing extras is fine

**Comment by blueyed** [comment]
Ok.

btw: I've noticed that `testdir`s also will have hypothesis files in them if it is installed - expected?  (at least some minor overhead in general)

**Comment by blueyed** [comment]
I've seen `.hypothesis` dirs in testdirs, but that was likely only caused by running pytest itself then in the testdir manually (when debugging) - so nevermind that for now.

Turns out there wasn't a "testing" extra requirement yet even.

Should be fixed with https://github.com/pytest-dev/pytest/pull/4415.
