### ISSUE TITLE
Pytest set_trace() to enable using advanced options [skip option to debug in asyncio]

### ISSUE THREAD

**Issue by txomon** [pytest-dev/pytest#4416]
This feature is to enable `pytest.set_trace()` calls to use more advanced and less known features of pdb.

Right now, there is an assumption that `pdb.Pdb` doesn't take any extra arguments. Although it's not really publicized, or even written much about, when debugging asyncio, you get into the pain that the IOLoop doesn't let you follow your application flow easily.

Every await call will be lost in the depths of the eventloop logic, and it's difficult to find your way back to your program.

This feature would allow you to do something like the following:
```
import pytest; pytest.set_trace(skip=['asyncio.*', '_weakrefset.*', '_collections_abc.*', 'selectors.*', ])
```

Where all keyword arguments to set_trace would be passed to Pdb class instantiation.

**Comment by txomon** [comment]
For reference PDB usage with asyncio: https://bugs.python.org/issue32900

**Comment by asottile** [comment]
wow! I didn't know `pytest.set_trace` existed.  I like the sentiment of this issue, but not the suggested implementation -- `set_trace` should always follow the api of `Pdb.set_trace`.  *Fortunately* you can already do what you want with the standard library (and the suggested documentation of [`pdb`](https://docs.python.org/3/library/pdb.html#pdb.Pdb)

I tried it out myself:

```python
from django.utils.encoding import smart_text
import inspect



def test():
    import pdb; pdb.Pdb(skip=['django.*']).set_trace()
    x = smart_text('wat')
    print(x)
```

```console
$ pytest -s t.py
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-4.0.1.dev15+gcdbe2299, py-1.7.0, pluggy-0.8.0
rootdir: /tmp/pytest, inifile: tox.ini
collected 1 item                                                               

t.py > /tmp/pytest/t.py(9)test()
-> x = smart_text('wat')
(Pdb) s
> /tmp/pytest/t.py(10)test()
-> print(x)
(Pdb) print(x)
wat
(Pdb) c
wat
.

========================== 1 passed in 17.26 seconds ===========================
```

**Comment by blueyed** [comment]
`skip` is useful to pass into `set_trace` indeed.

As for compatibility: we have `set_break` there already (which should really be cleaned up anyway):
```
% pytest …
(Pdb) import pdb
(Pdb) inspect.getfullargspec(pdb.set_trace)
FullArgSpec(args=['cls'], varargs='args', varkw='kwargs', defaults=None, kwonlyargs=['set_break'], kwonlydefaults={'set_break': True}, annotations={})
```

And we do not support the `header` kwarg added in 3.7.

With pdb++ you can pass in kwargs (https://github.com/antocuni/pdb/blob/2d753414ea3c57881ecf64b9f47852656dcabeb1/pdb.py#L993-L1009), but it does not work with pytest then.

I think we should not call `Pdb.set_trace()`, but rather the original `pdb.set_trace` also.

I will create a PR.

**Comment by blueyed** [comment]
I highly recommend pdb++/pdbpp btw, but you should install it from Git for a lot of fixes/improvements: https://github.com/antocuni/pdb.

**Comment by blueyed** [comment]
Well, without pdbpp `set_trace` will create a new instance of Pdb, where we do not have control over.

I think it might actually be a feature request for Python to pass through (unhandled) kwargs into `Pdb()`, i.e. it would handle `header`, but forward `skip`.

As for `import pdb; pdb.Pdb(skip=['django.*']).set_trace()` - it is not that bad, but pytest should handle this (so that you do not need `-s`).

**Comment by txomon** [comment]
just in case, pytest is creating its own Pdb instance underneath, and subclassing etc. Therefore the proposal to send all kwargs to the constructor. if set_trace gets any argument in the future, it would still be supported, and we could just drop whatever keys in the pytest wrapper.

**Comment by blueyed** [comment]
Yes, pytest patches `pdb.set_trace()`, but then does not call the original, but the wrapped `pdb.Pdb`.
I think passing extra kwargs to `Pdb.__init__` makes sense (and is what pdb++ does also).

I do not think we should patch `pdb.Pdb` for `pdb.Pdb().set_trace()` to suspend output capturing etc. there.

I've given it a spin in https://github.com/pytest-dev/pytest/pull/4419.

**Comment by txomon** [comment]
@blueyed yes, it does, do you need any help with the code? I have seen there were some comments in the PR.

**Comment by blueyed** [comment]
@txomon 
Cool.
The discussion appears to be more about keeping the original signature etc (which is not the case currently already though anyway), but not about the code itself - if you can provide more insight / arguments over there it might help, yes.
