### ISSUE TITLE
passing the fixture around

### ISSUE THREAD

**Issue by Vic152** [pytest-dev/pytest#4422]
Hey Guys,
**Disclaimer :) It may be entirely impossible to what I am trying to achieve but I thought I would ask before giving up.**

Working Example:

conftest.py

```
@pytest.fixture()
def driver():

    options = webdriver.ChromeOptions()
    b = webdriver.Chrome('resources//chromedriver.exe', options=options)

    yield b
    b.close()
    b.quit()
```

```
test_login.py

@when('the user enters correct username <username> and password <password>')
def the_user_enters_correct_username_and_password(driver, username, password):

    HomePage().login_as(driver, username, password)
```

So here is my question: **Do I need to pass _driver_ to every single method that is going to need it?**

What I would like to do is to have Page Object model. I would write base_page class. In base_page class I would like to use **driver** fixture and use it in all other pages that would be subclass of base_page. In other words: to have class that can use fixture object and subclass that can inherit the same fixture object.

I want to use fixtures in classes/methods that are not test_ I suppose.

I spent some time (a week) looking around to see how can I avoid passing **driver** in every test method. People do many hacks including loading driver into a dictionary that is specified in conftest.py.

I tried:
https://github.com/ModusCreateOrg/python-automation-boilerplate/blob/1_pytest-bdd_initial_setup/tests_root/tests/conftest.py

This doesn't seem to do the trick.
https://dzone.com/articles/improve-your-selenium-webdriver-tests-with-pytest

All I want is to have base_page like this:

```
@pytest.mark.usefixtures("driver") -- or some other way I can pass driver
class BasePage(object):

    def wait_for_element_to_be_clickable(self, *locator):

        wait = WebDriverWait(self.driver, 10)
        if locator.__len__() == 2:
```

and subclass home_page like this:

```
class HomePage(BasePage):

     def login_as(self, username, password):

     self.wait_for_element_to_be_clickable(*HomePageLocators.touch_to_login).click()
```

at the moment I get error:

```
self = <pom.pages.home.HomePage object at 0x04741250>
locator = ('xpath', "//div[@class='cui-bar-click-area']")

    def wait_for_element_to_be_clickable(self, *locator):
    
>       wait = WebDriverWait(self.driver, 10)
E       AttributeError: 'HomePage' object has no attribute 'driver'

pom\base_page.py:13: AttributeError
```

My project setup would be something like this. I would keep POM separate from test modules. I use pytest-bdd too.

![image](https://user-images.githubusercontent.com/6089679/48718130-b1b81d80-ec12-11e8-8417-ec0ba45b3107.png)

**Comment by RonnyPfannschmidt** [comment]
see widgetastic or similar object implementations - typically the driver is a implementation detail that those objects manage and pass on

**Comment by Vic152** [comment]
Yup looked at that they still pass browser object to tests.

```
def test_basic_widgets(browser):
    class TestForm(View):
        h3 = Text('.//h3')
        input1 = TextInput(name='input1')
        input2 = Checkbox(id='input2')
        input3 = ColourInput(id='colourinput')
        fileinput = FileInput(id='fileinput')
```
I do not want my tests to be aware of the driver object. I want my base_page class to be aware and all the sub classes. I would like tests just to evaluate outputs/receive flag to indicate the state.

So for example:
```
test_login(username, password):
    logged_user = HomePage().login(username, password)
    assert logged_user == username
```
Or:
```
test_page_loaded():

    # PageA() is PageA(BasePage)
    # Only BasePage() knows about webdriver
    page_a_loaded = PageA().load()
    assert page_a_loaded is True
```
**What I am really asking is that if there is a way to do this with pytest fixtures**

**Comment by RonnyPfannschmidt** [comment]
you can just pass a page object into the test for example,
if you combine for example widgetastic and navmazing you can enter the test in a state where you get a widget representing a certain navigation state

in a sense the pytest fixture system does not at all care what the values are - you jsut have to pick the fixtures you want and use them (and if one of those fixtures is one of your page objects, then it will just work that way and not need a driver

however your examples look like they want to rely on global state, i'm generally for absolutely avoiding that

**Comment by Vic152** [comment]
I also think there is a similar issue mentioned here: https://github.com/pytest-dev/pytest/issues/3901#issuecomment-417358113

**Comment by Vic152** [comment]
Here is the solution. Use the `request` object to retrieve browser generated from fixture. No dirty hacks involved!
https://github.com/pytest-dev/pytest-html/issues/186#issuecomment-441208344

Okay so here is how you access webdriver from the report generation hook:
```
@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):

timestamp = datetime.now().strftime('%H-%M-%S')

pytest_html = item.config.pluginmanager.getplugin('html')
outcome = yield
report = outcome.get_result()
extra = getattr(report, 'extra', [])
if report.when == 'call':

    feature_request = item.funcargs['request']

    driver = feature_request.getfuncargvalue('browser')
    driver.save_screenshot('D:/report/scr'+timestamp+'.png')

    extra.append(pytest_html.extras.image('D:/report/scr'+timestamp+'.png'))

    # always add url to report
    extra.append(pytest_html.extras.url('http://www.example.com/'))
    xfail = hasattr(report, 'wasxfail')
    if (report.skipped and xfail) or (report.failed and not xfail):
        # only add additional html on failure
        extra.append(pytest_html.extras.image('D:/report/scr.png'))
        extra.append(pytest_html.extras.html('<div>Additional HTML</div>'))
    report.extra = extra`

```
This will give you an error:
```
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=61.0.3153.0)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.17134 x86_64)
```
But this can be easily fixed by checking if driver is present - this happens because driver closes before report is generated.

**I have to say that documentation for request object is very poor**
