### ISSUE TITLE
Question: is `place_as` a sane api to use ?

### ISSUE THREAD

**Issue by smarie** [pytest-dev/pytest#4429]
In [pytest-steps](https://github.com/smarie/python-pytest-steps) I use `decorator` to create function wrappers with additional arguments.

I found out recently that this was messing up the test ordering, because the source file and line number become "virtual" (and different from the wrapped function). 

I also saw that I could not let the `__wrapped__` field on the generated wrapper because then the change of signature (new arguments) would not be detected (pytest looks at the inner signature).

I finally found out a solution that seems to be "supported" (at least the code looks purposedly made for that): it is to set the `place_as` field.
https://github.com/pytest-dev/pytest/blob/d1c9c545716e6a0f2dcf64502f1b15681043bb32/src/_pytest/compat.py#L309

My question is then quite simple: can I use this safely or will it stop to be supported soon ?

**Comment by RonnyPfannschmidt** [comment]
the testcase which ensures this is called `test_allow_sane_sorting_for_decorators`

we are unlikely to remove this soon if at all

**Comment by smarie** [comment]
Perfect ! Thanks a lot @RonnyPfannschmidt , quick and precise answer as always.
I can close the ticket.
