### ISSUE TITLE
Examples on Pytest.org should be in color

### ISSUE THREAD

**Issue by goodside** [pytest-dev/pytest#4430]
I write all my tests in unittest (I like classes and disagree with some of pytest's design decisions, like #3834) but I always install pytest on every box I use. Why? _Colors_.

Anyone who's been forced to `python -m unittest` knows how illegible it is without the red/green headers and highlights. I go out of my way to keep compatibility with both unittest and pytest (e.g., no `self.subTest()`) just to get color output. New users install pytest for the `assert`, but they stay for the colors.

I'd suggest it's uniquely important that the giant, above-the-fold example output on the [pytest.org landing page](https://docs.pytest.org/en/latest/) not be in black-and-white. Colorizing other examples in the docs could also improve readability.

Sphinx has a contrib module for [parsing ANSI color codes](https://pythonhosted.org/sphinxcontrib-ansi/) from pytest output that should work.

**Comment by RonnyPfannschmidt** [comment]
the outputs are scm tracked atm - so having/storing the output currently is potentially problematic

we ought to take a look at a solution

**Comment by asottile** [comment]
I wonder if we could make a custom highlighter to ~mostly get this working nicely

**Comment by nicoddemus** [comment]
About the landing page, I agree that's probably a good idea to have that in color. A quick solution is to change that output in the landing page to a picture. What do you folks think?

**Comment by asottile** [comment]
I might hack on writing a pygments-pytest (pytest-pygments?) -- don't hold your breath though :laughing:

**Comment by nicoddemus** [comment]
> I might hack on writing a pygments-pytest (pytest-pygments?) -- don't hold your breath though

That would be an honorable endeavor, I don't doubt! 😁 

Meanwhile a picture in the landing page might fit the bill hehehe

**Comment by asottile** [comment]
ooh! this doesn't actually look that difficult to get ~something going -- it's going to inevitably drift from pytest but I figure it'll be better than nothing.  I'm inspired -- I might hack on this on stream tonight :laughing: 

Will probably use @chriskuehl's excellent [`pygments-ansi-color`](https://github.com/chriskuehl/pygments-ansi-color) as an example.  The rest of the docs for writing a lexer are [here](http://pygments.org/docs/lexerdevelopment/).  Might try and make one for `pre-commit` first since that'll be simpler

**Comment by asottile** [comment]
I mostly got it working! https://github.com/asottile/pygments-pytest (hard to tell from the README -- I'll make it more obvious soon!)

I need to polish up the README, write some tests, and handle a few edgecases and/or make pytest's output more consistent in a few cases

**Comment by RonnyPfannschmidt** [comment]
@asottile well done, it looks way better than my original approach from 2012 which failed

**Comment by RonnyPfannschmidt** [comment]
im also totally for making output more consistent

**Comment by Zac-HD** [comment]
Closed by #4456 🎉

**Comment by asottile** [comment]
This was one of the most fun things I've done in a while btw, thanks for the idea!
