### ISSUE TITLE
Can't filter rewrite warnings

### ISSUE THREAD

**Issue by shaicantor** [pytest-dev/pytest#4439]
Hi,

Part of my code imports the xdist plugin.
As a result I receive 
```
================================================ warnings summary ================================================
/path/to/my/ve/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:268: PytestWarning: Module already imported so cannot be rewritten: xdist
  self.config,
/path/to/my/ve/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:268: PytestWarning: Module already imported so cannot be rewritten: xdist
  self.config,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
I tried filtering with:

1. -p no:warnings -> no luck
2. --disable-pytest-warnings -> removes the warning but the summary is still yellow
3. @pytest.mark.filterwarnings -> no luck
4. native python warning.filterwarnings -> no luck

How can I filter this specific warning???

pytest version - 3.8.2

**Comment by nicoddemus** [comment]
Hi @shaicantor, thanks for writing up, looks like a bug.

**Comment by blueyed** [comment]
btw (maybe necessary here also): https://github.com/pytest-dev/pytest-cov/pull/228

**Comment by nicoddemus** [comment]
Closing in favor of https://github.com/pytest-dev/pytest/issues/6681 (which contains more details).
