### ISSUE TITLE
Update/add acceptance tests for "config warnings" stacklevel

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4445]
Follow up to: https://github.com/pytest-dev/pytest/pull/4440#issuecomment-441106932

**Comment by SaiHarshaK** [comment]
Hi, can i work on this issue? i'm a newbie so some help is appreciated.Could you please explain the issue in detail.

**Comment by blueyed** [comment]
@SaiHarshaK 
It is about writing tests for the fix(es) in #4440.

**Comment by davidfyu** [comment]
I would like to try working on this issue. Is there any update as to whether any acceptance tests have already been written for the fix(es) in #4440 at this time? Thanks!

**Comment by mandarvaze** [comment]
@davidfyu  @SaiHarshaK  Either of you working on this ?

**Comment by xibalba01** [comment]
I am also interested in working on this, but i don't really get what the fixes in #4440 are ?! Does it mean the introduction of the `stacklevel=somenumber` in `_issue_config_warning`? I need some clarification and help for starting :)

**Comment by xibalba01** [comment]
@nicoddemus Thanks for the explanation! Are there already some acceptance tests available that i could have a look at to know in which direction this should go?

**Comment by xibalba01** [comment]
@nicoddemus @RonnyPfannschmidt @blueyed  I am still trying to understand how this will work... A bit more details would be really nice :) In the end these specific warnings in mentioned in #4440 need to be triggered, right? But exactly this is where i am struggeling... How to trigger these warnings?

**Comment by blueyed** [comment]
@xibalba01 
They are hopefully covered with tests already (you could check the coverage report on codecov for the master branch to verify this).
Then just put an `assert 0, 1`, `assert 0, 2` etc in front of them (using different numbers for them), and run the whole test suite.  Then you should see what tests are executing the code, and could harden them then.

**Comment by blueyed** [comment]
@xibalba01 
Also take a look at https://github.com/pytest-dev/pytest/pull/5929 maybe, which is only a single one.

**Comment by xibalba01** [comment]
@blueyed Thanks, i will have look!

**Comment by xibalba01** [comment]
@blueyed in the end shall there be entirely new tests that are put in the acceptance_test.py module or shall the existing test that make use of _issue_capture_warning be enhanced to also check for a correct warning message?

**Comment by blueyed** [comment]
@xibalba01 
I'd enhance/harden the existing tests.

**Comment by blueyed** [comment]
@xibalba01 
Please post your findings here, i.e. the output of the short test summary with failed tests then, so it's easier to pick it up in the future again.

**Comment by xibalba01** [comment]
As @blueyed proposed, putting assert statements in the line just before `_issue_warning_captured` is called ([_pytest.assertion.rewrite.py](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/assertion/rewrite.py#L240), _pytest.config.\_\_init\_\_.py ([1](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L218), [2](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L584), [3](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L907)), [_pytest.resultlog.py](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/resultlog.py#L34), [_pytest.cacheprovider](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/resultlog.py#L34)) yields the following test failures when the whole test suite is run:

```
FAILED testing/acceptance_test.py::TestGeneralUsage::test_better_reporting_on_conftest_load_failure - Failed: nomatch: '*--version*'
FAILED testing/deprecated_test.py::test_resultlog_is_deprecated - Failed: nomatch: '*--result-log is deprecated and scheduled for removal in pytest 6.0*'
FAILED testing/deprecated_test.py::test_external_plugins_integrated[pytest_capturelog] - AssertionError: rewrite
FAILED testing/deprecated_test.py::test_external_plugins_integrated[pytest_catchlog] - AssertionError: rewrite
FAILED testing/deprecated_test.py::test_external_plugins_integrated[pytest_faulthandler] - AssertionError: rewrite
FAILED testing/test_assertrewrite.py::TestRewriteOnImport::test_rewrite_warning - Failed: remains unmatched: '*Module already imported*: _pytest'
FAILED testing/test_cacheprovider.py::TestNewAPI::test_cache_writefail_cachfile_silent - AssertionError: cacheprovider
FAILED testing/test_conftest.py::test_required_option_help - AssertionError: assert 'general:' in ''
FAILED testing/test_pluginmanager.py::TestPytestPluginManager::test_plugin_skip - assert 3 == <ExitCode.NO_TESTS_COLLECTED: 5>
FAILED testing/test_resultlog.py::TestWithFunctionIntegration::test_collection_report - assert not ['! c:\\users\\mo3klo4r\\documents\\code\\opensource\\python\\pytest\\src\\_pytest\\resultlog.py', ' Traceback (most r...nit__.py", line 720, in _do_configure',...
FAILED testing/test_resultlog.py::TestWithFunctionIntegration::test_log_test_outcomes - AssertionError: assert False
FAILED testing/test_resultlog.py::test_generic - Failed: nomatch: '. *:test_pass'
FAILED testing/test_resultlog.py::test_makedir_for_resultlog - Failed: nomatch: '. *:test_pass'
FAILED testing/test_resultlog.py::test_no_resultlog_on_slaves - AssertionError: resultlog
FAILED testing/test_resultlog.py::test_failure_issue380 - assert <ExitCode.INTERNAL_ERROR: 3> == 2
FAILED testing/python/fixtures.py::test_fixture_parametrization_nparray - AssertionError: assert {'error': 1, ...pped': 0, ...} == {'error': 0, ...pped': 0, ...}
```

Looking at some of the failed tests in more detail i am a bit puzzled about how to check for the captured warnings as the inner workings of pytest are somehow still very obscure, involved and magic to me. 
I have seen that the [test for _issue_warning_captured](https://github.com/pytest-dev/pytest/blob/master/testing/test_warnings.py#L238) itself uses a class that has the specific hook method (?) as a plugin in the testdir fixture for collecting the the captured warnings. But i have no idea how to test this in for example [testing/deprecated_test.py::test_external_plugins_integrated](https://github.com/pytest-dev/pytest/blob/master/testing/deprecated_test.py#L41)...

**Comment by xibalba01** [comment]
I have a question regarding a stacklevel of one `_issue_warning_captured` location in [_pytest.config.\_\_init\_\_.py](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L588). There it says `stacklevel=1` which points to the warnings module and not the import_module method where, from my point of view, the warning should point to... @nicoddemus @blueyed @RonnyPfannschmidt any insights on this?

**Comment by xibalba01** [comment]
Further on i am asking what is happening to the [warning in _prepareconfig](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L197) as it is set to `None` and never changed within that function. So the respective `_issue_warning_captured` is never reached. Also any insights from your side?

**Comment by blueyed** [comment]
> I have a question regarding a stacklevel of one `_issue_warning_captured` location in [_pytest.config.__init__.py](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L588). There it says `stacklevel=1` which points to the warnings module and not the import_module method where, from my point of view, the warning should point to...

Good find.
Running `testing/test_pluginmanager.py::TestPytestPluginManager::test_plugin_skip` shows:
```
(Pdb++) pp result.stdout.lines
['============================= test session starts ==============================',
 'platform linux -- Python 3.7.4, pytest-5.2.2.dev25+g914a9465a.d20191016, py-1.8.1.dev11+g34f716fe, pluggy-0.12.0',
 "hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('…/Vcs/pytest/.hypothesis/examples')",
 'rootdir: /tmp/pytest-of-user/pytest-436/test_plugin_skip0',
 'plugins: hypothesis-4.23.8, forked-1.0.2, xdist-1.29.0',
 'collected 0 items',
 '',
 '=============================== warnings summary ===============================',
 '…/Vcs/pytest/src/_pytest/warnings.py:147',
 '…/Vcs/pytest/src/_pytest/warnings.py:147',
 "  …/Vcs/pytest/src/_pytest/warnings.py:147: PytestConfigWarning: skipped plugin 'skipping1': hello",
 '    warnings.warn(warning, stacklevel=stacklevel)',
 '',
 '…/Vcs/pytest/src/_pytest/warnings.py:147',
 "  …/Vcs/pytest/src/_pytest/warnings.py:147: PytestConfigWarning: skipped plugin 'skipping2': hello",
 '    warnings.warn(warning, stacklevel=stacklevel)',
 '',
 '-- Docs: https://docs.pytest.org/en/latest/warnings.html',
 '============================= 3 warnings in 0.01s ==============================',
 '']
```
With `stacklevel=2`:
```
 '=============================== warnings summary ===============================',
 '…/Vcs/pytest/src/_pytest/config/__init__.py:588',
 '…/Vcs/pytest/src/_pytest/config/__init__.py:588',
 "  …/Vcs/pytest/src/_pytest/config/__init__.py:588: PytestConfigWarning: skipped plugin 'skipping1': hello",
 '    stacklevel=2,',
 '',
 '…/Vcs/pytest/src/_pytest/config/__init__.py:588',
 "  …/Vcs/pytest/src/_pytest/config/__init__.py:588: PytestConfigWarning: skipped plugin 'skipping2': hello",
 '    stacklevel=2,',
 '',
 '-- Docs: https://docs.pytest.org/en/latest/warnings.html',
 '============================= 3 warnings in 0.01s ==============================',
```

This is also a good example for a test that you can harden then: just use `fnmatch_lines` to match here additionally.
Note that the first warning is triggered twice (bug?):
```
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 207, in _prepareconfig',
 '    config = get_config(args, plugins)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 178, in get_config',
 '    pluginmanager.consider_preparse(args)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 506, in consider_preparse',
 '    self.consider_pluginarg(parg)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 531, in consider_pluginarg',
 '    self.import_plugin(arg, consider_entry_points=True)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 586, in import_plugin',
 '    __import__("traceback").print_stack(file=sys.stdout)',
```
and
```
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 221, in _prepareconfig',
 '    pluginmanager=pluginmanager, args=args',
 '  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 291, in __call__',
 '    return self._hookexec(self, self.get_hookimpls(), kwargs)',
 '  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec',
 '    return self._inner_hookexec(hook, methods, kwargs)',
 '  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>',
 '    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,',
 '  File "…/Vcs/pytest/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall',
 '    res = hook_impl.function(*args)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 740, in pytest_cmdline_parse',
 '    self.parse(args)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 947, in parse',
 '    self._preparse(args, addopts=addopts)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 890, in _preparse',
 '    self.pluginmanager.consider_preparse(args)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 506, in consider_preparse',
 '    self.consider_pluginarg(parg)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 531, in consider_pluginarg',
 '    self.import_plugin(arg, consider_entry_points=True)',
 '  File "…/Vcs/pytest/src/_pytest/config/__init__.py", line 586, in import_plugin',
```

```diff
 src/_pytest/config/__init__.py |  4 +++-
 testing/test_pluginmanager.py  | 10 +++++++++-
 2 files changed, 12 insertions(+), 2 deletions(-)

diff --git i/src/_pytest/config/__init__.py w/src/_pytest/config/__init__.py
index 39c8d2cdf..55b28ef28 100644
--- i/src/_pytest/config/__init__.py
+++ w/src/_pytest/config/__init__.py
@@ -582,10 +582,12 @@ def import_plugin(self, modname, consider_entry_points=False):
         except Skipped as e:
             from _pytest.warnings import _issue_warning_captured
 
+            print("=== WARN ===", modname, e.msg)
+            __import__("traceback").print_stack(file=sys.stdout)
             _issue_warning_captured(
                 PytestConfigWarning("skipped plugin {!r}: {}".format(modname, e.msg)),
                 self.hook,
-                stacklevel=1,
+                stacklevel=2,
             )
         else:
             mod = sys.modules[importspec]
diff --git i/testing/test_pluginmanager.py w/testing/test_pluginmanager.py
index 97f220ca5..ed687cab2 100644
--- i/testing/test_pluginmanager.py
+++ w/testing/test_pluginmanager.py
@@ -228,8 +228,16 @@ def test_plugin_skip(self, testdir, monkeypatch):
         monkeypatch.setenv("PYTEST_PLUGINS", "skipping2")
         result = testdir.runpytest("-rw", "-p", "skipping1", syspathinsert=True)
         assert result.ret == ExitCode.NO_TESTS_COLLECTED
+        __import__('pdb').set_trace()
         result.stdout.fnmatch_lines(
-            ["*skipped plugin*skipping1*hello*", "*skipped plugin*skipping2*hello*"]
+            [
+                "*skipped plugin*skipping1*hello*",
+                "*skipped plugin*skipping2*hello*",
+                '*= warnings summary =*',
+                "  *?_pytest?config?__init__.py:*: PytestConfigWarning: skipped plugin 'skipping1': hello",
+                "  *?_pytest?config?__init__.py:*: PytestConfigWarning: skipped plugin 'skipping2': hello",
+                '*= 3 warnings in *',
+             ]
         )
 
     def test_consider_env_plugin_instantiation(self, testdir, monkeypatch, pytestpm):
```

**Comment by blueyed** [comment]
> Further on i am asking what is happening to the [warning in _prepareconfig](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L197) as it is set to `None` and never changed within that function. So the respective `_issue_warning_captured` is never reached. Also any insights from your side?

Dead code.  https://codecov.io/gh/pytest-dev/pytest/src/master/src/_pytest/config/__init__.py#L216...219
Feel free to remove it I guess, but maybe check git-log/git-blame what happened there.

**Comment by xibalba01** [comment]
> Dead code. https://codecov.io/gh/pytest-dev/pytest/src/master/src/_pytest/config/__init__.py#L216...219
> Feel free to remove it I guess, but maybe check git-log/git-blame what happened there.

@blueyed @nicoddemus the code that could trigger setting `warning` to something different than `None` was removed with a7e4016. So i would also consider this dead code that could be removed...

**Comment by blueyed** [comment]
@xibalba01 
Yeah: https://github.com/pytest-dev/pytest/commit/a7e401656eca66fb1ecee7c5e55ea24598d87f45#diff-b80bb977f96695d5bfe21ddd2680c4efL181

Please consider creating a PR to remove it, otherwise let us know.  Thanks!
