### ISSUE TITLE
Get all fixture invocations at the end of collection phase

### ISSUE THREAD

**Issue by Sup3rGeo** [pytest-dev/pytest#4453]
Hi,

Pytest by the end of collection time has a list of all the test instances (parametrized test functions), available through the `items` parameter in `pytest_collection_modifyitems` hook.

Now, not only test functions can be parametrized and have many instances/invocations, but also fixtures.

Is there a way to, by the end of collection time and before the test run, have a list of all the fixtures "instances" generated?

I have a use case where some of our fixtures are somewhat expensive but they could be all created externally in parallel (the tests however cannot run in parallel, otherwise xdist would be an option). My idea would be to do this for all possible invocations of that fixture by the end of collection and later on, on execution, replace call the fixture function with an already cached value. This second part I have functional, but don't know how to go with the first part.

Thanks!

**Comment by nicoddemus** [comment]
Hi @Sup3rGeo!

We don't have an API for that, but if you don't mind access internal objects you can get all fixture definitions from the fixture manager:

```python
import pytest

@pytest.hookimpl(hookwrapper=True)
def pytest_collection(session):
    yield
    for x, d in session._fixturemanager._arg2fixturedefs.items():
        print(x, d)
``` 

Hope this helps!

**Comment by nicoddemus** [comment]
Oh I see. No, the fixture objects are evaluated on demand only, so we don't have access to the fixture results at collection time. This makes sense when you consider that we might not even execute all tests (plugins, `-k`, etc), so it would be a waste to compute all fixture values before hand.

**Comment by Sup3rGeo** [comment]
Well, but in collection time pytest knows that `test_one` will be executed also four times, right? And this behaviour is only coming from the fact that he uses the `fix` fixture. 

So I would suppose that in collection time pytest should know somehow that the fixture will have four invocations, propagating this to the tests. Or maybe I am missing something...

**Comment by nicoddemus** [comment]
You can perhaps inspect the list of test items, and see which fixture each one uses by accessing `item.fixturenames`?
