### ISSUE TITLE
pytest_make_parametrize_id and firstresult

### ISSUE THREAD

**Issue by floggle** [pytest-dev/pytest#4463]
This is either unclear docs or something buggy.

I'm trying to create parameterised tests with nice ids. The current id solutions all seem hard to maintain so I went with something simple:

```
@pytest.mark.parametrize("_, first, sec, expected", [
	(
		"add",
		2
		2
		4,
	),
])
def (_, first, sec, expected):
    assert first+sec == expected

```

The key being that the "_" attribute has the proposed id in it.

So I created this simple function in confttest.py:

```
def pytest_make_parametrize_id(argname, val, firstresult=True):
	if argname == '_':
		return repr(val)
```
Problem is that while it correctly gets the value of "_", it is also returning the values of all the other attributes too.
I would have expected that it not do that given I've set "firstresult=True".

The docs https://docs.pytest.org/en/latest/_modules/_pytest/hookspec.html say:
"Stops at first non-None result, see :ref:`firstresult`"

Although I cannot find ":ref`firstresult`" that it's referring to anywhere - that part could be clearer

pytest==3.7.1

**Comment by asottile** [comment]
`firstresult` is a setting for the [hook itself](https://github.com/pytest-dev/pytest/blob/d05b30ce11f68959d8c9ebebd8674bb84d91f02d/src/_pytest/hookspec.py#L299) it roughly means "call implementations of the hook until they return a non-None result" -- basically "find the first plugin that responds".

It doesn't mean that it won't call it for each argument.

Your signature also looks pretty different than the `(config, val, argname)` signature I'm seeing in the code -- I wonder if that's confusing your output as well?

`firstresult` is documented in [the pluggy docs](https://pluggy.readthedocs.io/en/latest/#first-result-only) though the docs are a little sparse and instead link to [these pytest docs](https://docs.pytest.org/en/latest/writing_plugins.html#firstresult-stop-at-first-non-none-result)

**Comment by RonnyPfannschmidt** [comment]
why not just write it as `pytest.param(2,2,4, id="add")`

**Comment by floggle** [comment]
@asottile - thanks. Ah well, guess I'll have to live with it, though it would be nice if there was a *good* way to set id's for things. Somewhere where the id is with the test and there's not lots of boilerplate making it all a confusing mess. Maybe a "reserved_word" parameter.

@RonnyPfannschmidt - unfortunately that is incredibly ugly and adds a huge amount of boiler-plate; it seems very unpythonic.
