### ISSUE TITLE
xfail cannot be tested with assert_outcomes

### ISSUE THREAD

**Issue by acerv** [pytest-dev/pytest#4467]
Hello,

the following code using pytester is not working after *3.7.4* version:
```
def test_marker_xfail(testdir):
    testdir.makepyfile("""
            import pytest
            @pytest.mark.xfail
            def test_teardown_failure():
                assert False
        """)
    rec = testdir.runpytest()
    rec.assert_outcomes()
```

Tested on both windows/linux.

Andrea

**Comment by blueyed** [comment]
Caused by 539a22c750e2232ca6f0664976a4940e65c48ef5, according to git-bisect.

/cc @wimglenn

**Comment by wimglenn** [comment]
Feature not a bug? Seems to be working as designed...

**Comment by blueyed** [comment]
Yes, looks like this to me also.

@acerv 
What is your actual use case?

**Comment by acerv** [comment]
I've reimplemented the junit plugin for a project and my unittests are failing due to changes in the pytester code. Every test (for each scenario) is also testing the results using `assert_outcomes`. If I remove it for xfail it passes, but is it the correct way? Why pytester isn't recognizing a result code anymore?

Before *3.7.4* version, all outcomes parameters were 0, but now what should I expect to see when `assert_outcomes` is called?

**Comment by RonnyPfannschmidt** [comment]
so basically we do have a "non-breaking" api change as we added support for more statuses to be checked

this api change however reveals tests that had historically been incorrect to begin with

the question is do we want to turn them into a warning for a while, or do we consider the deed done

based on the age `3.7.4` i'd say the pytest update reveals incorrect tests, please fix your tests

**Comment by acerv** [comment]
Ok thanks
