### ISSUE TITLE
Feature Request: rerun the slowest tests

### ISSUE THREAD

**Issue by matrixise** [pytest-dev/pytest#4471]
with pytest, we have the `--durations=XX` parameter, this one allows to show the slowest tests. One feature could be to run the slowest tests like the `--lf` parameter (rerun only the tests that failed).

Thank you

**Comment by blueyed** [comment]
What is your use case?
Why do you like to run the slowest tests?
And should they only be run first, or only the ones that matched the `--durations` "filter"?

**Comment by matrixise** [comment]
Use case ;-)

A lot of django tests and these ones are very slow, I would like to improve them but get the list, just one time and relaunch pytest only on these slow tests. 
Now, I could use a simple pattern on the logs and try to relaunch the tests from this log.

**Comment by blueyed** [comment]
I see.
Sounds very specific though, and it's not really clear how it should behave.

I suggest using markers, or something like the following, where you could only select tests using `transactional_db` or `db` fixtures etc (assuming you use pytest-django):

```python
@pytest.hookimpl(hookwrapper=True)
def pytest_collection_modifyitems(config, items):
    """Handle --split-tests."""

    yield

    only_using_fixture = config.getoption('--only-using-fixture')
    if only_using_fixture:
        new_items = []
        for item in items:
            if only_using_fixture in item.funcargnames:
                new_items.append(item)
        items[:] = new_items
```

**Comment by RonnyPfannschmidt** [comment]
@blueyed missing a pytest_deselected call, i believe we ought to make this automatic

**Comment by blueyed** [comment]
@RonnyPfannschmidt 
What do you mean?

**Comment by Zac-HD** [comment]
> A lot of django tests and these ones are very slow, I would like to improve them but get the list, just one time and relaunch pytest only on these slow tests. Now, I could use a simple pattern on the logs and try to relaunch the tests from this log.

For this use-case, I think you're strictly better off explicitly running known test ids (e.g. from the --durations=N` output) - if we had a `--rerun-slowest` flag, the tests you ran might change as you sped them up!
