### ISSUE TITLE
Empty string ignored for id renaming

### ISSUE THREAD

**Issue by floggle** [pytest-dev/pytest#4472]
I have this simple pytest_make_paramtrize_id function:

```

def pytest_make_parametrize_id(argname, val):
	if argname == '_':
		return name
	else:
  return ""
```

The problem is, when PyTest sees the "" returned by the `else`, it decides to ignore it and do its standard variable stuff.

This is because of line 1165 in this code:
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/python.py

it should be `if hook_id is not None`, otherwise you're intentionally ignoring the developer's explicit desire.

**Comment by RonnyPfannschmidt** [comment]
actually empty string is a completely invalid value at that point, and we should take more places into account to ensure that no empty string is used

some desires are wrong, keep those in check

**Comment by floggle** [comment]
Ok, in that case what's the correct method for having a value not be represented in the id? You can't send None of course, and apparently not "" either. Is there a mechanism for not representing a value that I've missed?

**Comment by RonnyPfannschmidt** [comment]
the problem is that the hook you try to use is for single elements of a parameterset, while a id is for a complete parameterset, joined by dashes if necessary
