### ISSUE TITLE
Hide Output but show custom feedback

### ISSUE THREAD

**Issue by WebDragonStudios** [pytest-dev/pytest#4473]
Hello,

I've looked through the documentation but can't find the correct parameter options to **ONLY** display the optional & additionally output from a failed test. Below is an example of an assertion I'm running:

```python
def test_add():
  sum = assertPYwithPyTest.add(10, 5)
  assert sum == 15, "Error in 'add' method. This is an example to add a note to a failed test"
```

The closest I got to removing the extra output was running the file like the following: 
`pytest -q --tb=line myFile.py.`

Is there anyway I can only display the custom feedback I want to show? Thank you.

**Comment by RonnyPfannschmidt** [comment]
the use-case behind this quite "specific" requirement is not clear, withoutb eing aware of that we will invoke the XY-Problem

so please elaborate on the intent

**Comment by WebDragonStudios** [comment]
I am creating custom feedback for students learning Python. The "usual"
terminal output for failed tests are displayed in an interactive, online
IDE. We simply want *only* the custom feedback to show, as per my OP. This
use-case for this is for beginners to not be overwhelmed with a large
amount of output, and to only focus on the "hints" we give for each failed
test.

**Comment by RonnyPfannschmidt** [comment]
@WebDragonStudios in that case - take pytest-sugar as an example - it disables the builtin terminalwriter plugin and does something completely different for output

it seems to me like that would be what would help your case - replacing the output system instead of argumentation gives you more control

**Comment by asottile** [comment]
@WebDragonStudios have you tried with more `-q`?  For example:

```
$ pytest -o console_output_style=classic -qq t.py --tb=line
F
=================================== FAILURES ===================================
/tmp/t/t.py:6: AssertionError: Error in 'add' method ...
```

`console_output_style=classic` will also remove the progress percentages
