### ISSUE TITLE
Common footgun `pytest.raises(Exception)`: should this be a warning?

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#4475]
Very frequently I've seem code that looks like:

```python
some_mock.side_effect = Exception
with pytest.raises(Exception):
    some_code()
```

And this silently passes because `some_code` raises `TypeError` / etc. and not the exception the user intended

Can pytest better guard against this?  Maybe a helpful warning (eventual error) when `raises(BaseException)` or `raises(Exception)` is used?

**Comment by blueyed** [comment]
Would be great.

(With non-custom exceptions (through mocks) I think also that `as exc` should be used and e.g. `exc.value.args` should be asserted/checked - but that is out of scope here)

**Comment by nicoddemus** [comment]
I agree, most likely `Exception` is not the user intended. I think a warning would be appropriate, although I wonder if we should provide a way to silence that warning when it makes sense... 🤔

**Comment by RonnyPfannschmidt** [comment]
i'm on the fence about this one because of the edges

**Comment by Tadaboody** [comment]
@RonnyPfannschmidt What edges for example?

**Comment by bluetech** [comment]
Unless this issue is truly prevalent out there, I'm -1. `pytest.raises(Exception)` is a legitimate thing to do, analogous to `except Exception`, and I'd be slightly annoyed if I have to do something extra for it to work. I think educating about too-broad `except` clauses is more of a language concern than a test framework concern.

**Comment by bluetech** [comment]
Some reasons you might want `pytest.raises(Exception)`:

- You know the consequences but just lazy to list all possibilities.
- You don't know exactly which exception is raised or don't want to lock it down, e.g. some 3rd party library which may change.
- You verify the exception some other way, e.g. `match`/exc info.

I would agree about it being a footgun if it were implicit, like a bare `except`. But in this case the user explicitly writes `Exception`. I don't think pytest should second-guess that.

**Comment by RonnyPfannschmidt** [comment]
By now I think this warrants a warning

**Comment by nicoddemus** [comment]
How about a warning *in the documentation*? This seems to be non-controversial and warns about the footgun.

I will implement this in #11578.

**Comment by nicoddemus** [comment]
I personally think adding a warning to the docs is a good balance between warning users and not bothering them for the legitimate cases, in which case #11578 can close this.

**Comment by RonnyPfannschmidt** [comment]
I'd much prefer having to opt in explicitly and getting a warning for bad usage

**Comment by nicoddemus** [comment]
I see.

Regardless I think adding the warning now is fine, as it serves to document the current behavior.

Would you like to open a new issue proposing how to handle `Exception` for `pytest.raises` @RonnyPfannschmidt ? We would need to discuss how that API will look like.

**Comment by nicoddemus** [comment]
(We might continue the proposal in this thread if you prefer too)

**Comment by RonnyPfannschmidt** [comment]
A while back I had a inspiring discussion with @asottile on matchers for better assertions

I believe the same concept can be used to have other matching behavior for the more specific matching

Once that is available we can Start to warn on using the base classes like a diaper

**Comment by bluetech** [comment]
flake8-pytest-style has a lint for this: https://github.com/m-burst/flake8-pytest-style/blob/master/docs/rules/PT011.md
I do think this is better as a lint than in pytest itself.

**Comment by bluetech** [comment]
I'm going to close this per the above comment.
