### ISSUE TITLE
Can't receive messaegs from ActiveMQ listener object in Pytest Test Case

### ISSUE THREAD

**Issue by AlperennK** [pytest-dev/pytest#4480]
Hello, 
Pytest 3.6.0

I want to implement some test cases to test an EventTransmitter. I 'm sending a message to our server and reading server's response from ActiveMQ topic. 
I have two classes for sending a message and reading messages on ActiveMQ topic. I know this classes work fine. Because it works smoothly if I run the test scenario as Python script. However when I implemented steps as a pytest Test Case. I couldn't get the test running becuase, Pytest doesn't initiate a topic Listener. Somehow, we don't get any message if we run the listener over Pytest.

Message Consumer Class:
```
import json
import time
import sys
import os
import stomp

user = os.getenv("ACTIVEMQ_USER") or "xxx"
password = os.getenv("ACTIVEMQ_PASSWORD") or "xxx"
host = os.getenv("ACTIVEMQ_HOST") or "xxxx"
port = os.getenv("ACTIVEMQ_PORT") or 61613
destination = sys.argv[1:2] or ["/topic/VirtualTopic.xx.events"]
destination = destination[0]

rcvd_msg=None

class MyListener(object):

  def __init__(self, conn):
    self.conn = conn
    self.count = 0
    self.start = time.time()
    self.msg_list=[]
    self.header_list=[]


  def on_error(self, headers, message):
    self.msg_list.append('received an error'+ message)
    print('received an error %s' % message)

#Check header also on message
  def on_message(self, headers, message):

    if('EventTimeStamp' in message):
        d_message=json.loads(message)

        self.msg_list.append(d_message)
        self.header_list.append(headers)

    if message == "SHUTDOWN":

      diff = time.time() - self.start
      print("Received %s in %f seconds" % (self.count, diff))
      conn.disconnect()
      sys.exit(0)


    else:
      if self.count==0:
        self.start = time.time()


      self.count += 1

      if self.count % 10 == 0:
         diff = time.time() - self.start
         #print("Received %s in %f seconds" % (self.count, diff))
         #print("Received %s messages." % self.count)


conn = stomp.Connection(host_and_ports = [(host, port)])
```

Here is the pytest test case: 

```
import messenger
import time
import amq_client as aq
import pytest

class Test_AMQ(object):
    def test_amq(self):
        lst=aq.MyListener(aq.conn)
        aq.conn.set_listener('', lst)
        aq.conn.start()
        aq.conn.connect(login=aq.user, passcode=aq.password)
        aq.conn.subscribe(destination=aq.destination, ack='auto', id=1234)
        print("Waiting for messages...")


        resp=messenger.Messenger().send_message()
        print(resp)
        lognum=resp[1].split("=")[1]

        time.sleep(15)
        actions = [x['ENTITY_ACTION'] for x in lst.header_list]
        accounts = [x['ACCOUNT'] for x in lst.header_list]
        print(actions)
        print(accounts)

        assert (lognum in accounts and 'NEW_ACCOUNT' in actions)

```
Result:
```
Waiting for messages...
['OK', 'LOGIN=701111332', 'end', '']
[]
[]
```

Without Pytest: 

```
import messenger
import time
import amq_client as aq



lst=aq.MyListener(aq.conn)
aq.conn.set_listener('', lst)
aq.conn.start()
aq.conn.connect(login=aq.user, passcode=aq.password)
aq.conn.subscribe(destination=aq.destination, ack='auto', id=1234)
print("Waiting for messages...")


resp=messenger.Messenger().send_message()
print(resp)
lognum=resp[1].split("=")[1]

time.sleep(15)

actions = [x['ENTITY_ACTION'] for x in lst.header_list]
accounts = [x['ACCOUNT'] for x in lst.header_list]

print('Actions : ', actions)
print('Accounts : ', accounts)

if(str(lognum) in accounts and 'NEW_ACCOUNT' in actions):
    print('Works')
else:
    print('Not Working')

```
Result: 
```
Waiting for messages...
['OK', 'LOGIN=701111333', 'end', '']
Actions :  ['NEW_ACCOUNT', 'ACCOUNT_GROUP_CHANGED']
Accounts :  ['701111333', '701111333']
Works
```

I need to run this listener over Pytest. I debugged and realized this listener is not being created when we run test case. 

Thank you.

Pytest Ver: 3.6.0

**Comment by RonnyPfannschmidt** [comment]
at first glance - all the magic global variables you have are likely interfering with something
as the current resource management looks its pretty much possible that any kind of timing issue could trigger it

all i can say is that pytest itself is completely unaware of those libraries 

i do wonder what happens if you invoke your actual testcase function from plain python

**Comment by AlperennK** [comment]
If I run from plain python, listener works and we can see new account message. By without Pytest, I meant plain python. Pytest aware of messenger library, but not aware of message consumer library. Messenger is sending new account message by socket library. ['OK', 'LOGIN=701111333', 'end', ''] we get this message as response, but server also generate message to ActiveMQ topic we don't get that message.

**Comment by AlperennK** [comment]
If I run from plain python, listener works and we can see new account message. By without Pytest, I meant plain python. Pytest aware of messenger library, but not aware of message consumer library. Messenger is sending new account message by socket library. ['OK', 'LOGIN=701111333', 'end', ''] we get this message as response, but server also generate message to ActiveMQ topic we don't get that message.

**Comment by RonnyPfannschmidt** [comment]
from my point of view the code posted is incomplete and full of patterns that could trigger any kind of random issue (including different execution) simply by having different timing

so off-hand there is practically nothing we can do for you other than telling you to sort out all those magical global variables
