### ISSUE TITLE
attrs 18.4.0 required, but only 18.2.0 available

### ISSUE THREAD

**Issue by caseyjlaw** [pytest-dev/pytest#4481]
Looks like the required attrs library version is higher than what is available:

https://github.com/pytest-dev/pytest/blob/d8e00c983ef4e0b663ce908c2db263416d2b6e2f/setup.py#L12

**Comment by asottile** [comment]
the linked code you've listed says _17_ -- looks like there's plenty of versions on pypi which satisfy that: https://pypi.org/simple/attrs/

**Comment by RonnyPfannschmidt** [comment]
closing as invalid
