### ISSUE TITLE
Running with --junitxml should report call times, not total times

### ISSUE THREAD

**Issue by aparamon** [pytest-dev/pytest#4483]
Currently, [--junitxml](https://docs.pytest.org/en/latest/usage.html#creating-junitxml-format-files) reports the total test time, including fixture set-ups and tear-downs:

````py
import pytest
import time

@pytest.fixture
def requisite():
    time.sleep(2)
    yield
    time.sleep(3)

def test_this(requisite):
    time.sleep(1)
````

````bat
>pytest test.py --durations 0 --junitxml result.xml
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: N:\pytest, inifile:
plugins: requests-mock-1.5.2, repeat-0.4.1, remotedata-0.3.0, ordering-0.5, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 1 item

test.py .                                                                [100%]

------------------ generated xml file: N:\pytest\result.xml -------------------
=========================== slowest test durations ============================
3.00s teardown test.py::test_this
2.00s setup    test.py::test_this
1.00s call     test.py::test_this
========================== 1 passed in 6.03 seconds ===========================
````

```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="0" tests="1" time="6.026">
  <testcase classname="test" file="test.py" line="9" name="test_this" time="6.002954006195068"></testcase>
</testsuite>
````

There should be an option to force --junitxml report call times, not total times.
Please additionally consider making it the default behavior.

**Comment by Zac-HD** [comment]
Unfortunately the JUnit XML spec ([e.g. here](https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_14.1.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html)) is pretty clear that the `time` field is for the actual time taken by executing the test, not time less setup.

**Comment by aparamon** [comment]
@Zac-HD I cannot completely agree that definition from your link or in
https://github.com/windyroad/JUnit-Schema/blob/49e95a79cc0bfba7961aaf779710a43a4d3f96bd/JUnit.xsd#L127-L130
is completely unambiguous :-)

And pragmatically, I see a great benefit in an option to write call times. Very often, I'm not interested in set-up and tear-down operations, but only in the actual code execution. JUnit XML export provides handy, readily-available interface for integration with e.g. Jenkins.

Would you object if I make a PR introducing something like `--junitxml-calltime`, with a clear note that it may violate JUnit XML schema?
