### ISSUE TITLE
Would like a way to customize --setup-show output to omit certain fixtures 

### ISSUE THREAD

**Issue by timblaktu** [pytest-dev/pytest#4484]
I would like to omit certain fixtures from those that are printed during a test run using --setup-show.

I always use --setup-show because I love the high-level textual picture it paints to stdout of what is going on in a live test run. 

I also like to have a detailed log file for the test run. I implemented a simple function-scoped, autouse fixture that will log entry/exit of each test method, regardless of scope, to provide some nice visua cues in our quite verbose logs. This is nice, but now my --setup-show output is "cluttered" with this new fixture's setup/teardown for each test function run. This is noise to me in this case.

I would propose something like this:

A new pytest.mark.nosetupshow be defined that, when used, causes pytest to suppress printing SETUP and TEARDOWN events for that fixture at test runtime.  The default behavior would not change, preserving --setup-show's educational value for most people.

I'm using:
platform linux2 -- Python 2.7.13, pytest-3.10.0, py-1.7.0, pluggy-0.8.0

**Comment by timblaktu** [comment]
Hi Ronny. I was trying to describe the use case as just a normal test developer who like the following feedback from pytest during test runs:

1. A High-level summary of real-time test activity which can be watched at stdout as a sort of "coarse progress bar" during test runs. This is provided by --setup-show option, which the user includes in addopts in their pytest.ini.
2. A detailed log of real-time test activity, which can be watched via log file created by standard python logging file target/handler. Nothing fancy here.

The test developer typically watches 1. and 2. during every test run for progress indication and feedback about interesting conditions. 1. is terse, 2. is very verbose.

When watching 2. it is desirable to have textual visual cues to indicate to the eyes and the brain where important epochs occur(red), epochs like entering/exiting each test function. To this end, I placed logger calls in my test functions to do this, but it is more appropriate to place this kind of functionality into a function-scoped, autouse fixture, so the test developer never has to write that code ever again (for that pytest project), and the new behavior (logging enter/exit of each test function) just automatically works.

BUT! After this fixture is implemented, the "--setup-show" stdout from pytest is now cluttered with the new SETUP/TEARDOWN lines corresponding to the new fixture. These are essentially noise to the test developer. He essentially wants to use pytest --setup-show stdout as a terse progress indicator.

At the core of this request is the implication that some fixtures are more important (or _interesting_) to a test developer than others. The test developer has created an entire test automation framework for his company based on pytest. This framework is composed of dozens of autouse fixtures like this, which by their very nature, implicitly _always on_, and therefore he wants to hide them from stdout.  

It seems a pretty standard use case to me, but perhaps there are other ways of achieving the same goal via other means. This is just the first, intuitive place my brain landed. I'm aware that I could roll my own "terse real-time test run summary" (1. above) using pytest hooks and plugins, but was hoping for a simpler solution. Pytest seems to me so far customizeable to the hilt, so I probably ASSumed this would be already possible, in a simpler way.

FWIW, our tests are quite complex, using several nested fixtures (some parametrized), so the setup-show output is quite informative except for the "administrative ones" like the example above which just wraps some log calls. I would think it common that people would want to turn off those uninteresting ones, but maybe people just aren't using setup-show like I am. Please enlighten me if you know a better way to "watch" your test progress.

**Comment by timblaktu** [comment]
FWIW, this is an example of one of the simple, mundane fixtures I have included in our framework, and would choose to "hide" from --setup-show if I had the choice/power:

```
@pytest.fixture(scope="function", autouse=True)
def test_func_log_wrapper(request):
    '''Wraps a test function/method to provide enter/exit logging.

    Requesting test function context (or containing class or module) must define
    a 'logger' attribute that is an instance of logging.Logger.
    '''
    if hasattr(request.function, "logger"):
        logger = request.function.logger
    elif hasattr(request.cls, "logger"):
        logger = request.cls.logger
    elif hasattr(request.module, "logger"):
        logger = request.module.logger
    else:
        print "test_func_log_wrapper: logger not defined at requesting scope or higher"
        return

    logger.info(80*"-")
    funcname = request.function.__name__
    include_test_docstr = False
    if include_test_docstr:
        logger.info("Enter test %s to %s", funcname, inspect.getdoc(request.function))
    else:
        logger.info("Enter test %s", funcname)
    yield
    logger.info("Exit test %s", funcname)
    logger.info(80*"-")
```

**Comment by Zac-HD** [comment]
I'm 👎 on this because I don't think the extra complexity is worth it, and I'm worried about misleading users who incorrectly believe that the output is complete.
