### ISSUE TITLE
get Pass/Fail value on XML output file for Pytest run

### ISSUE THREAD

**Issue by omriben** [pytest-dev/pytest#4494]
Hi,
I use the "--junitxml" to generate XML report after each run.
the problem - none of the "testcase" attributes is the most important key: **result** (that should be Pass or Fail).
```
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="3" tests="5" time="3.411">
    <testcase classname="temp_scripts.test.python_scripts.test_me.TestS3" 
        file="temp_scripts/test/python_scripts/test_me.py" 
        line="7" 
        name="test_1" 
        time="1.9083178043365479">
    </testcase>
<testcase classname="temp_scripts.test.python_scripts.test_me.TestS3" 
        file="temp_scripts/test/python_scripts/test_me.py" 
        line="14" 
        name="test_2" 
        time="1.5098254704165016">
    </testcase>
</testsuite>
```
I saw the "record_property" fixture but it's not enough because I don't want testers to:
1) call "record_property" fixture at every test function
2) write "record_property("result", 'Pass/Fail')" at every test end

Is there a way to collect all single test assertions with a "logic AND" to report Pass/Fail at the above XML?

Tried this with copy+paste:  [https://docs.pytest.org/en/latest/example/simple.html#making-test-result-information-available-in-fixtures](url)
but got an empty folder with no results.

10X!

**Comment by omriben** [comment]
I saw in here: [https://stackoverflow.com/questions/13364868/in-pytest-how-can-i-figure-out-if-a-test-failed-from-request/13375241](url)
with this optional solution:
```
@pytest.fixture(scope="module", autouse=True)
def failure_tracking_fixture(request):
    tests_failed_before_module = request.session.testsfailed
    yield
    tests_failed_during_module = request.session.testsfailed - tests_failed_before_module
```
Is there a way to write `tests_failed_during_module` to the XML output file? or maybe check if it's 0 and pass the test (and fail test if it's greater that 0)

**Comment by RonnyPfannschmidt** [comment]
junitxml has no concept of a "result" - everything without a failure is a success

**Comment by omriben** [comment]
I guess it's good enough
10X! @RonnyPfannschmidt
