### ISSUE TITLE
pytester configuration leaks in main pytest configuration

### ISSUE THREAD

**Issue by youtux** [pytest-dev/pytest#4495]
I discover this while debugging a failure in pytest-bdd (see https://github.com/pytest-dev/pytest-bdd/issues/276).
It seems that the ini configuration created by `testdir.makeini` function leaks in the main pytest configuration.
Here it is a test that reproduce the issue:
```
$ pytest test_bug.py::test_1 test_bug.py::test_2
```
```python
# test_bug.py
import pytest

pytest_plugins = "pytester"


def test_1(testdir):
    """Creating some configuration in the testdir. We set the `minversion` option, but it can be any option."""
    testdir.makeini(
        """
        [pytest]
        minversion=3.0.0
    """
    )

    testdir.makepyfile(
        """
        import pytest

        def test_expected_minversion():
            assert pytest.config.getini('minversion') == '3.0.0'
    """
    )

    result = testdir.runpytest()
    result.assert_outcomes(passed=1)


def test_2():
    """The configuration made in test_1 should not leak here."""
    assert pytest.config.getini('minversion') != '3.0.0'

```

This is the configuration I am using:
```
Package        Version
-------------- -------
atomicwrites   1.2.1
attrs          18.2.0
more-itertools 4.3.0
pip            18.1
pluggy         0.8.0
py             1.7.0
pytest         4.0.1
setuptools     40.6.2
six            1.11.0
wheel          0.32.3
```

Python 3.7.1 on Mac OS 10.14.1

- [x] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [x] Minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
its not so much leaking, but rather a rather massive/painful bug about pytests internal state

as pytest does in fact patch the object pytest.config, but never undoes the patch

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/blob/ecc5c84c1ec77ad43f0fe0cb34a097bb855c1423/src/_pytest/main.py#L170-L172

**Comment by RonnyPfannschmidt** [comment]
also ref #3050

**Comment by youtux** [comment]
It would be quite unfortunate if `pytest.config` is removed, since pytest-bdd requires it at tests import time (cannot just switch to request.config).

**Comment by RonnyPfannschmidt** [comment]
@youtux why would it need it that way?

**Comment by youtux** [comment]
Because pytest-bdd generates test items from `.feature` files at import time, but in order to parse the `.feature` files it needs to know where they are stored. This value is currently taken from the ini configuration of pytest.
Before https://github.com/pytest-dev/pytest-bdd/pull/255, pytest-bdd used to get this value by calling a fixture, but since fixture cannot be called directly anymore, we changed it to use the `pytest.config.getini()`.

**Comment by RonnyPfannschmidt** [comment]
all that happens past pytest-configure time, just configure your plugin at that time instead of getting the globals later

**Comment by asottile** [comment]
does this become "wontfix" given the resolution of #3050 (deprecating `pytest.config` global)?

**Comment by RonnyPfannschmidt** [comment]
@asottile we can debate on whether we want pytester to remember/reset the value

**Comment by RonnyPfannschmidt** [comment]
@sliwinski-milosz to fix pytest-bdd, the pytester plugin would have t fix the reference - note that pytest.config will go away with the next major release

**Comment by RonnyPfannschmidt** [comment]
@sliwinski-milosz for correctness you need pytest_configure and pytest_unconfigure paired

**Comment by sliwinski-milosz** [comment]
Ah ok. In our case unconfigure means bring previous values back.
To do that I need to be able to access the "previous" config. Can I get it from somewhere?
Would be great if it would be passed as an argument to `pytest_unconfigure` but as far as I can see it provides current config.

**Comment by RonnyPfannschmidt** [comment]
@sliwinski-milosz with the current layering of pytest, you have to track it yourself, its quite a pain,

**Comment by sliwinski-milosz** [comment]
Thanks! All clear now!

I have created pull request in which I use config stack. It seems that it works fine :)

**Comment by RonnyPfannschmidt** [comment]
@sliwinski-milosz great job

**Comment by RonnyPfannschmidt** [comment]
Closing as we removed the config global
