### ISSUE TITLE
pytest sets sys.gettrace() which confuses debug mode

### ISSUE THREAD

**Issue by nedo99** [pytest-dev/pytest#4499]
Hi,

I noticed that pytest sets `sys.gettrace()` variable when executed. I use `sys.gettrace()` to check if script started in debug mode, but when running with pytest it reports always that it is in debug mode since I pytest sets the trace.

Is there any other way to check if script is running in debug mode when using pytest?

Regards,
Nedim

**Comment by RonnyPfannschmidt** [comment]
pytest does not call set_trace - pdb does when entering the debug shell

the pdb integration of pytest triggers the codepath that does settrace

**Comment by nedo99** [comment]
The script was running with coverage report which was setting the trace and not the pytest. My bad.

Thank you!

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup
