### ISSUE TITLE
Info about selected and deselected tests in collecting phase

### ISSUE THREAD

**Issue by JerSefJeTu** [pytest-dev/pytest#4512]
Hello,
I am trying to implement my test explorer and i need to know:
How can i know in collecting phase which test is selected and which is not?

I am using `pytest_collection_modifyitems `hook and there i got all collected test but i need to get only selected tests.
Is it at all possible?

Thanks a lot!

**Comment by RonnyPfannschmidt** [comment]
before that hook is completely finished you can know for sure

i suspect this is a instance of the x-y problem

and i suspect the `pytest_runtestloop` might help you immensely
