### ISSUE TITLE
flake8 pre-commit-hook fails on Windows (Python 3.6.7 & 3.7.1)

### ISSUE THREAD

**Issue by fkohlgrueber** [pytest-dev/pytest#4513]
When running `pre-commit run --all-files` on Windows using the most recent Python versions (3.6.7, 3.7.1), the flake8 test fails. I've tracked the problem down to a regression error regarding `os.path.abspath` in these Python versions that will be fixed in the next minor release. For details, see this [issue](https://gitlab.com/pycqa/flake8/issues/478) in the flake8 bug tracker.

This issue will be solved with the upcoming releases, so there's nothing to do right now. I'm opening this issue primarily so that others can find the reason why their pre-commit hooks don't work. I hope that's ok.

cc @asottile

**Comment by asottile** [comment]
indeed :D -- here's the flake8 issue for this with the rest of the context: https://gitlab.com/pycqa/flake8/issues/478

**Comment by asottile** [comment]
If it's breaking in our CI, we can temporarily set `SKIP=flake8` for just appveyor

**Comment by fkohlgrueber** [comment]
Using python 3.7.2, the flake8 hook works as expected. Closing this issue.
