### ISSUE TITLE
Within Test_Func_1 of  A Module we cant call Test_Func_2 of B Module of another package

### ISSUE THREAD

**Issue by MaheshKok** [pytest-dev/pytest#4516]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by MaheshKok** [comment]
Hi Team,

I am using Latest Version of Pytest

Here is the requirement i came across


how can i make pytest add another modules test fun and run it after native modules test func

**Comment by asottile** [comment]
Can you provide what you've tried so far and what your desired behaviour is? you should be able to import code just as you would for any other python module

**Comment by MaheshKok** [comment]
Hi this is my complete Program

pkg :- A

#test_module_A.py

def test_A1():
    print('abc')

def test_A2():
    import B.test_module_B


pkg:- B
#test_module_B.py

def test_B1():
    print('def')
I am running test_module_A from pycharm using pytest

output

abc

However i would like the output to be

abc
def


Combinations which i tried so far...

1) inside A2 i imported the module and then explicitly called the func... it executed like normal func and pytest doesnt consider it as item... i.e pytest says collected 2 items when i run Module A ...instead i want pytest to consider test_B1() also its item and execute it ....


2) i imported the module B outside functions of module A and then ran the module A via Pytest... Now pytest considers it as 3 items but the problem is..it executes test_B1() before test_A1 and test_A2 ...I want pytest to execute test_B1 after its done with test_A1 and test_A2

i dont know how to proceed..... 

In real scenario Module_B is being imported dynamicaly among 100s of module based on some logic and logic is implemented in test_A2 ....hence its logical to run module B functions after test_A2.


Can anyone help me in this regards

**Comment by RonnyPfannschmidt** [comment]
an import only makes the name availiable, it looks like you want to call, its not clear what you actually want to do, please describe the use-case, not how you think it should be implemented

**Comment by MaheshKok** [comment]
Use case is

I have module A and it has one function for ex test_a1 and it applies some logic and on the basis of logic it calls one of many modules which resides in another package ...pytest after completing test_a1 it should execute the complete module which I want....how can I do these...

**Comment by asottile** [comment]
test discovery and execution are two separate stages -- it's too late for the execution of `test_a1` to influence what tests will be run after that.

**Comment by MaheshKok** [comment]
You are right....which test cases to be executed are decided in test discovery only .......but can't be there any other workaround for it.....

**Comment by asottile** [comment]
you can modify collected items _during discovery_ but not at any other time.  there's nothing to "work around" here -- that's the intentional design.  I still don't have a clear picture of your use case and what you're trying to solve, you've just suggested another way to _implement_ that.  Please help communicate _why_ you want to do what you're doing -- if it helps, list some specific technology that requires your setup :)

**Comment by MaheshKok** [comment]
I am working on automatiom framework ......and that framework was built in some other language and I am migrating it to Python for which I am taking help of Pytest for Structuring it and Allure for reporting.... Pytest provides one of the best error stacktrace and allure provides the best html report ...and old framework style is being tried to incorporate using Pytest and that's the use case which I described in above comments

**Comment by MaheshKok** [comment]
Please close this as i know the functionality i am trying to achieve is not as per design pattern ...Hence dropped the idea and instead used the design pattern to achieve my functionality...Thanks for the reply...your reply only made me go for the alternate approach and its awesome....

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup. i'm happy you reached a working solution
