### ISSUE TITLE
Allow injecting fixtures in teardown_module/function() 

### ISSUE THREAD

**Issue by majorgilles** [pytest-dev/pytest#4527]
- It would be useful to be able to inject fixtures in def teardown_module or similar functions.
Use case: some of my general integration test fixtures have common operations on tables associated with an injectable fixture. Sometimes it's necessary to use that code in fixtures. I have to make a separate plain function that is returned to the fixture.

e.g.

```
import delete_test_domain

@pytest.mark.integration
def test_execute_calls_remote_api(test_payload, fetch_domain_by_id):
    receiver = CreateDomainReceiver()
    command = CreateDomainCommand(receiver=receiver, body=test_payload)

    result = command.execute()
    pytest.some_id = result.id

    assert result.some_code == test_payload['some_code']

def teardown_module():
    if pytest.some_id:
        delete_test_domain(str(pytest.some_id))
```

- [ ] `pip list` of the virtual environment you are using
irrelevant
- [ ] pytest and operating system versions
pytest 4.0.0, osx Mojave

**Comment by RonnyPfannschmidt** [comment]
please show what you actually mean, i`m pretty sure there is some merit, but the example code you wrote in the description is not something sanely supportable
