### ISSUE TITLE
monkeypatch.delattr doesn't handle classmethod or staticmethod

### ISSUE THREAD

**Issue by chdsbd** [pytest-dev/pytest#4536]
The following example fails

```python
class SampleParent(object):
    @classmethod
    def hello(_cls):
        pass

class SampleChild(SampleParent):
    pass

monkeypatch = MonkeyPatch()
original = SampleChild.hello
monkeypatch.delattr(SampleParent, 'hello')
monkeypatch.undo()
assert original == SampleChild.hello
```

This issue was fixed for setattr via https://github.com/pytest-dev/pytest/issues/156

We need to make a similar check in delattr as seen here: https://github.com/pytest-dev/pytest/blob/9424d88843a06a290d2e9fe6b8e1523b3d8e39ee/src/_pytest/monkeypatch.py#L167

I'll put up a PR.

**Comment by nicoddemus** [comment]
Thanks for the report and the PR @chdsbd!
