### ISSUE TITLE
Feature request: refactor the pytest.raises interface

### ISSUE THREAD

**Issue by wimglenn** [pytest-dev/pytest#4538]
Interface for `pytest.raises` is a stumbling block.  Problems:

~1. The "message" kwarg violates principle of least surprise.  User probably expected: simple match on exception message (useful), but it's actually for providing custom failure message (not very useful). Recommend deprecation.~   `message` has now been deprecated.
~2. The "match" kwarg violates principle of least surprise.  It will catch substrings, for example. And it's annoying when the error message itself contains regex syntax that you'll need to escape. Could possibly be renamed to "regexp" or something?~   ...don't care / don't use it
~3. No easy way to achieve the most simple and basic use-case: assert exact match on an exception instance args with basic types such as strings and/or numbers.~   use the plugin instead: [pytest-raisin](https://github.com/wimglenn/pytest-raisin)

Here are some examples of problematic usage.

```
# looks right, but doesn't assert what it seems like it's asserting. trappy for beginners!
with pytest.raises(Exception, message="boom"):
    Exception("boom")

# whoops!
with pytest.raises(Exception, message="boom"):
    Exception("bang")

# whoops again! still not there yet..
with pytest.raises(Exception, match="boom"):
    Exception("kaboom")

# correct usage
with pytest.raises(Exception, match="^boom$"):
    Exception("kaboom")
```

What if the thing you want to match is not really a string?  Can encounter this frequently when testing the CLI parts of code (since `argparse` is gonna raise `SystemExit` with an integer return code).  Problems:

```
# passes, but not why you thought
with pytest.raises(SystemExit, match=0):
    sys.exit(0)

# passes??
with pytest.raises(SystemExit, match=0):
    sys.exit(1)

# crashes, but crashes too late (`TypeError` in re compile)
with pytest.raises(SystemExit, match=1):
    sys.exit(1)

# correct usage
with pytest.raises(SystemExit) as cm:
    sys.exit(0)
assert cm.value.args == (0,)

# another trap! d'oh!
with pytest.raises(SystemExit) as cm:
    sys.exit(0)
    assert cm.value.args == (0,)
```

I would like to propose using exception instances to overcome these stumbling blocks. 

Example usage:

```
with pytest.raises(SystemExit(2)):
    sys.exit(2)
```

[`testfixtures.ShouldRaise`](https://testfixtures.readthedocs.io/en/latest/exceptions.html#the-shouldraise-context-manager) is an example of this usage, and I'd love to have that interface in `pytest` directly. The comparison objects which make it work are non-trivial. A much easier to implement alternative, though less beautiful, might be just to support matching the args attribute as tuple. 

```
with pytest.raises(SomeError, exc_args=(2, "code two")):
    raise SomeError(2, "code two")
```

Admittedly it won't help people who put too much logic into their custom exception classes, but it should cover majority standard use-cases (where exceptions are dumb subclasses, just with a custom numeric error code or message).

What do you think?

**Comment by nicoddemus** [comment]
Hi @wimglenn,

You are absolutely right. In fact we had a long discussion about this in #3974.

I would like to avoid breaking things, even if `match` might be a little misleading as you comment.

We had some consensus with the proposal in https://github.com/pytest-dev/pytest/issues/3974#issuecomment-421204036 about the `message` parameter.

Your proposal then would be to add a new parameter. I particularly like the idea of passing the exception instance that should be matched exactly (`SystemExit(2)`).

**Comment by asottile** [comment]
one problem I see with passing exception instances into `raises` is few exception types properly implement `__eq__` and so you'd potentially enable another pitfall.  I'd rather lean towards fewer behaviours of raises and leave the assertion up to the user.

I think we should steer people more towards the context manager -- that said, I don't have any counters to this example other than linting 🤷‍♂️ (pytest knows the full ast of your tests, maybe it could warn on this behaviour during discovery)

```python
with pytest.raises(SystemExit) as cm:
    sys.exit(0)
    assert cm.value.args == (0,)
```

actually, now that I think about it -- any code coverage tool is going to expose this mistake so maybe it's less of a bad problem than I think.


I'm in favor of [deprecating and removing `message=](https://github.com/pytest-dev/pytest/issues/3974#issuecomment-421152319)

Should we consolidate this discussion into #3974 (duplicate)?

**Comment by nicoddemus** [comment]
> I'm in favor of deprecating and removing `message=

Too slow! 😁 https://github.com/pytest-dev/pytest/pull/4539

**Comment by wimglenn** [comment]
@asottile   To clarify, my suggestion was not be to rely on exception's `__eq__` (which in almost all cases will be identity-based) but for `pytest.raises` itself to do a more nuanced comparison of exception instances.

**Comment by asottile** [comment]
> @asottile To clarify, my suggestion was not be to rely on exception's `__eq__` (which in almost all cases will be identity-based) but for `pytest.raises` itself to do a more nuanced comparison of exception instances.

yes I understand that, implementing our own custom idea of "equality" seems like a place to write bugs and surprising behaviour.

**Comment by asottile** [comment]
Other than `message=` I don't find anything else you've posted "surprising".  Adding a custom non-equality "equality" check seems like a bad idea

**Comment by wimglenn** [comment]
Not even this one?

```
with pytest.raises(SystemExit, match=0):
    sys.exit(2)
```

Why `match=0` was treated the same as `match=None`?

> Adding a custom non-equality "equality" check seems like a bad idea

Yes, agreed.

**Comment by asottile** [comment]
Ooh missed that one. Seems like a micro bug needing an `is` somewhere

**Comment by asottile** [comment]
Here's a fix for that one: https://github.com/pytest-dev/pytest/pull/4540

**Comment by nicoddemus** [comment]
`message` is now deprecated as of #4539. 🎉 

I guess what's left here is to discuss if/how we can improve `pytest.raises` to also check for the exception's `args`, correct?

**Comment by wimglenn** [comment]
Correct.

Sensible options I see:
1. allow to pass exception instance, and equality compare args attributes. any more sophisticated comparison has to use cm.value instead 
2. allow to pass exception instance and allow user to provide a callable, takes two arguments, and compares exc.  optional - default callable just compares exc args.
3. do not allow to pass exception instances. add an "exc_args" keyword for pytest.raises to allow easier assertion on those.
4. do nothing.

**Comment by asottile** [comment]
my vote is for the simplest interface: 4 😆

**Comment by wimglenn** [comment]
4 is certainly simplest to code up. I could have it ready in a day or two.. 😉

my vote for 1.

**Comment by asottile** [comment]
1, 2, and 3 are all an "equality that is not `__eq__`" which to me is a double edged sword

**Comment by RonnyPfannschmidt** [comment]
its impossible to do it correct, its easy to check on the object - lets let others experiment with it for a while and keep it out of the core - if its truely needed, a good pattern will emerge and we can take a look at taking it in

**Comment by wimglenn** [comment]
Since there was not the support for this yet, I've added what interface I wanted in a plugin instead.

https://github.com/wimglenn/pytest-raisin

During implementation I noticed a few other weird buglets in the other usages of `pytest.raises`.

The code string version silently ignores match, message:

```
>>> pytest.raises(Exception, "2+'two'", match="cant put 2 and two together")
<ExceptionInfo TypeError tblen=2>
```

The code string version tries to unpack multiple args:

```
>>> pytest.raises(Exception, "2+'two'", "what")
ValueError: too many values to unpack (expected 1)
```

The passing a callable version is sharing the namespace for the callable args and also the args to `pytest.raises` itself in kwargs.  So there is no way to use the `match` there.  It's just bad design and impossible to handle the edge cases correctly.

```
>>> def func():
...     raise ValueError("wtf")
... 
>>> pytest.raises(Exception, func, match="yeah")
<ExceptionInfo TypeError tblen=1>
>>> pytest.raises(ValueError, func, match="nah")
TypeError: func() got an unexpected keyword argument 'match'
```

Without a convincing use-case, recommend deprecation of those legacy forms.  The context-manager is the one-obvious way to do it.

**Comment by asottile** [comment]
code string is already deprecated: https://github.com/pytest-dev/pytest/pull/4443

**Comment by wimglenn** [comment]
Ah, good!

**Comment by asottile** [comment]
oh no problem with the implementation that seems fine, just I've seen this backfire one too many times where someone assumes that's how it always works and then breaks some code elsewhere

**Comment by wimglenn** [comment]
Can close this now, [the plugin does the needfuls](https://github.com/wimglenn/pytest-raisin).

    pip install pytest-raisin
