### ISSUE TITLE
Change calling fixtures directly into an error instead of a warning

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4545]

**Comment by yousefcodes** [comment]
So why was this a problem that warrants an actual error?

**Comment by nicoddemus** [comment]
Hi @yousefcodes,

Please take a look at https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly, paraphrasing:

> This is a great source of confusion to new users, which will often call the fixture functions and request them from test functions interchangeably, which breaks the fixture resolution model.

Another problem is that we plan to introduce fixture objects at some point in the future, which will effectively make `@pytest.fixture`-decorated-functions no longer an actual function object.
