### ISSUE TITLE
Remove deprecated Node.get_marker

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4546]
@RonnyPfannschmidt are you OK with removing this directly or would you like to change this into an error or something?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus the return value practically errors already, there just is the edge-case that the non-return case didnt warn/error (its just in the docstring)

so i think killing it is ok

**Comment by RonnyPfannschmidt** [comment]
this is part of #891

**Comment by Themanwithoutaplan** [comment]
FWIW this change breaks a lot of CI stuff apparently without notice probably due to the way the deprecation was handled. Would be nice if the changelog contained a link on how to do it correctly as this would save a lot of us some time! :-)

**Comment by nicoddemus** [comment]
@Themanwithoutaplan definitely we should have handled that deprecation better, thanks for the feedback.

We did add this to the CHANGELOG:

> #4546: Remove Node.get_marker(name) the return value was not usable for more than a existence check.
> 
> Use Node.get_closest_marker(name) as a replacement.

You feel we should have pointed to https://docs.pytest.org/en/latest/mark.html#update-marker-code directly instead?

**Comment by RonnyPfannschmidt** [comment]
@Themanwithoutaplan basically whatever get_marker returned was in any case incomplete and fundamentally broken

**Comment by RonnyPfannschmidt** [comment]
but yes, the deprecation could have been handled much better

**Comment by nicoddemus** [comment]
@Themanwithoutaplan if you are interested on the rationale for the name change/mark revamp, please read this: https://docs.pytest.org/en/latest/mark.html#marker-revamp-and-iteration

We are happy to answer any questions you might have. 😁

**Comment by Themanwithoutaplan** [comment]
> @Themanwithoutaplan if you are interested on the rationale for the name change/mark revamp, please read this: https://docs.pytest.org/en/latest/mark.html#marker-revamp-and-iteration
> 
> We are happy to answer any questions you might have. 😁

Not really interested in a discussion to be honest, just want it work! :-D Thanks for updating the changelog with a note on how to fix it.
