### ISSUE TITLE
@pytest.fixture(scope='session', autouse=True) yields fixture function instead of data

### ISSUE THREAD

**Issue by foxale** [pytest-dev/pytest#4551]
pytest version: **4.0.1**
Pycharm version: **2018.3.2 RC**
pyspark version: **2.2.0**

```python
@pytest.fixture(scope='session', autouse=True)
def spark():
    spark = SparkSession.builder.getOrCreate()
    print(spark)
    yield spark
    spark.stop() 


class TestSelectAndClean(object):

    def test_spark(self):
        print(spark)
    
    def test_explicit_spark(self, spark):
        print(spark)
```

```python
Inside fixture: <pyspark.sql.session.SparkSession object at 0x0000018BFEA87128>
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
.Inside test: <function spark at 0x0000018BFE91A730>
.Inside explicit test: <pyspark.sql.session.SparkSession object at 0x0000018BFEA87128>
```

Is it supposed to be like that? I don't want a fixture returned, I want a spark object - just like in the explicit test.

**Comment by RonnyPfannschmidt** [comment]
this works as expected,

if you need a fixture, pass is as a argument

**Comment by RonnyPfannschmidt** [comment]
to elaborate, the test where you didnt add the argument, just looks up the fixture declaration at the python level

if you declared the fixture as

```
@fixture(name="spark",...)
def _hidden_name_spark(...):
   ...
```
or in a conftest, then you would see a python level name error

**Comment by nicoddemus** [comment]
It seems your question has been resolved so I'm closing this for now. Feel free to followup with further questions.
