### ISSUE TITLE
junit-xml: add option for disabling logs for passed tests

### ISSUE THREAD

**Issue by yoshi-lyosha** [pytest-dev/pytest#4559]
We have near 130k tests for some web-API, and in these tests we log a lot of http requests with its request/response headers, data, query and etc. We are logging it with logging module (`logging.getLogger('api_logger')`). There is a lot of logs, really. We are using Jenkins to run these tests and `--junit-xml` option for creating junit-xml style report.

So the problem is connected with  junit-xml creation. Junit-xml reporter captures not only failed tests (<1%) but passed tests too (>99%) and it can crash the Jenkins process and freeze the runner-server for a while.

There are some ways to disable logs for failed tests like:
- `--show-capture=no` Controls how captured stdout/stderr/log is shown on failed tests. Default is 'all',
- `--no-print-logs` disable printing caught logs on failed tests,

but no possibility to disable logs for passed test.

Right now we handle this with custom `pytest_runtest_logreport` that checks `if report.failed and report.when == 'call'`

So, maybe pytest needs an option for junit-xml that disables logs for passed tests and logs only failed, what do you think?

**Comment by blueyed** [comment]
Is there a use case for having logs for passed tests in the first place?
I can see that it might be useful for later introspection etc, but should be opt-in then maybe? (i.e. an option to enable it explicitly) - similar to how they are not displayed in the terminal for passed tests by default.

**Comment by nicoddemus** [comment]
Makes sense to me, so 👍.

**Comment by devhid** [comment]
Hi, was this ever implemented?

If so, how can I disable logs for passed tests?
