### ISSUE TITLE
Document `UsageError`

### ISSUE THREAD

**Issue by allanlewis** [pytest-dev/pytest#4560]
The exception `pytest.UsageError` is useful for validating that required options (specified in `pytest_addoption`) are set, or that other environmental factors are sane. However, it's currently undocumented: perhaps it should be added to the public API and therefore the published documentation?

**Comment by nicoddemus** [comment]
Indeed, thanks for the report @allanlewis.

**Comment by goodship1** [comment]
I will give it a ago

**Comment by justinwalker4179** [comment]
@goodship1 Any progress on this one, or can I pick it up?

**Comment by goodship1** [comment]
@justinwalker4179 sorry  totally  forgot about this. Yeh man pick it up

**Comment by Pulkit07** [comment]
Hi, is there any example of similar errors which are part of public API? I am trying to understand how the public API is denoted in the code.

**Comment by nicoddemus** [comment]
Hi @Pulkit07, thanks for the interest.

Sadly we don't have any exceptions documented in the docs. I believe a good place to put them is in https://docs.pytest.org/en/latest/reference.html, under a new "Exceptions" section.
