### ISSUE TITLE
jython hangs after collection

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest#4573]
Any ideas why could a jython run hang after/during collection phase, see https://dev.azure.com/pypa/virtualenv/_build/results?buildId=3314

**Comment by RonnyPfannschmidt** [comment]
@gaborbernat its possible that a object on jython behaves interesting and triggers some kind of unintended recursion while checking its details - can you replicate off-ci to enable edit/break debugging?

**Comment by RonnyPfannschmidt** [comment]
for more context, this happens directly after the collection of `test_activation.py` is finished but before the complete collection ends

**Comment by RonnyPfannschmidt** [comment]
sorry, i missunderstood the first log, as far as i can tell it happens while collecting `test_activation.py`

**Comment by gaborbernat** [comment]
Could be for some reason my subprocess calls that conditionally enable some tests in there hang, e.g. because waiting on some input.

**Comment by gaborbernat** [comment]
Sadly the issue manifests in CI only☹️
