### ISSUE TITLE
pytest passes tests with assertion errors.

### ISSUE THREAD

**Issue by AlfonsoSerra** [pytest-dev/pytest#4575]
pytest passes tests with assertion errors.
[piplist.txt](https://github.com/pytest-dev/pytest/files/2706255/piplist.txt)

One of my tests passes evaluating assert True == False.

video about the issue
https://drive.google.com/file/d/1QbjsqLuitR7kBWRe_ToLUFV3G73TiYYi/view?usp=sharing

**Comment by asottile** [comment]
Looks like classic test pollution, your `test_enabled` test above sets `T.enabled = False` which will carry over to your other test.  Be careful with global mutable state!

In the future, it would be better to post the code as text in the issue (a little easier to debug than watching a youtube video) and then I could have copy pasted it into an interpreter.

If you run `pytest -k language_switch` I think you'll see that the assertion is working fine (same if you switch the order of your two tests in your file)

**Comment by AlfonsoSerra** [comment]
Thanks, you are right. I should have restored the state when a test finishes. Learnt the lesson.

**Comment by asottile** [comment]
:tada: glad to help!
