### ISSUE TITLE
Doc Error in Parametrizing Fixtures (In the code there params are missing)

### ISSUE THREAD

**Issue by kappeler** [pytest-dev/pytest#4590]
For the description to be correct. There should be a param argument in the @pytest.fixture decorator.

![image](https://user-images.githubusercontent.com/3798533/50632893-95194000-0f49-11e9-8fb9-da8ec066d182.png)

**Comment by asottile** [comment]
it looks correct to me, but perhaps a little confusing -- it's using the `smtp_connection` fixture from above, which itself is `params`-ized: https://github.com/pytest-dev/pytest/blob/cf5a9aebb24f84a04bb21b56861017eb25553346/doc/en/fixture.rst#parametrizing-fixtures
