### ISSUE TITLE
package conftest still imported when package is added to collect_ignore

### ISSUE THREAD

**Issue by copperchin** [pytest-dev/pytest#4592]
I recently upgraded to pytest 4.0.2 (from 3.6.4) and am now seeing some changed behavior.

My top-level `conftest.py` would, under certain conditions, add a package name to the `collect_ignore` list.
This package also had a conftest.py, but with 3.6.4 the package's conftest would be ignored when the package was ignored.
Now with 4.0.2, the appropriate tests are ignored, but the conftest.py is no longer ignored.

I've attached a simple example to illustrate the behavior.
I'm running Python 2.7.6 (yes, I know, not by choice) on Windows 7.

[pytestbug.zip](https://github.com/pytest-dev/pytest/files/2725269/pytestbug.zip)

**Comment by pbasista** [comment]
I have noticed a similar behavior with tests that are supposed to be ignored because of the `--ignore` command line option.

From my experience, it is independent of Python version (i.e. it is reproducible with Python 2, as well as with Python 3) and it started with pytest 3.10.0. Earlier versions, up to and including pytest 3.9.3, would skip `conftest.py` files of the ignored test packages.

**Comment by pbasista** [comment]
Here is the result of git-bisecting:
```
e04182364338ed9cd2a63945204701c99e297f21 is the first new commit
commit e04182364338ed9cd2a63945204701c99e297f21
Author: Daniel Hahler <git@thequod.de>
Date:   Thu Oct 25 20:03:14 2018 +0200

    Move handling of duplicate files
    
    This removes the hack added in https://github.com/pytest-dev/pytest/pull/3802.
    
    Adjusts test:
    
    - it appears to not have been changed to 7 intentionally.
    - removes XXX comment, likely not relevant anymore since 6dac7743.

:040000 040000 2d9401be809bfa1366395d5c655377740b2add1c c1aeb5efcf9ac43aa42e7b9b417b687107d36efd M      src
:040000 040000 b64b2d5c7bf13611722b1993eaf710391c11b6ee 7e7bb008c016c21eb41384b58d84f16e5c550660 M      testing
```

**Comment by blueyed** [comment]
@pbasista 
Thanks!

@copperchin 
Is it the same commit that is causing your issue?

**Comment by blueyed** [comment]
I've git-bisected the original issue to 2b1410895e9ac30c4f08e9a701017cce65a9717b.

@pbasista 
So your issue is something (slightly) different, please file a new one (after looking for a better fitting one).

**Comment by blueyed** [comment]
https://github.com/pytest-dev/pytest/pull/4744 should fix this.

@pbasista 
Does it fix your issue also?

**Comment by pbasista** [comment]
I can confirm that `pytest-4.2.1.dev64+g67dd10de` does _not_ execute `conftest` modules of test packages that are explicitly ignored by the `--ignore` command line option.

The currently latest release version `pytest-4.2.0`, however, still executes them.
