### ISSUE TITLE
does not import from base directory

### ISSUE THREAD

**Issue by cyberfox1** [pytest-dev/pytest#4596]
I have a structure like:
/myproject/foo.py
/myproject/test/test_foo.py

And test_foo.py looks like:

    from foo import bar
    def test_foo_bar():
        assert "OK"

However when I run pytest from /myproject/ I get a ModuleNotFoundError on "foo".

Amazing such a basic thing does not work.

**Comment by asottile** [comment]
This is in line with how `sys.path` works in python.  If you'd like to have your thing on the path, either install it (using `pip install .` / `pip install -e .` + `setup.py`) or use `python -mpytest` (which sidesteps the issue by forcing `''` to be on the path)

**Comment by Tadaboody** [comment]
Another way (though less recommended IMO) is to manually add the project to the tests `sys.path` as detailed in [The Hitchhiker’s Guide to Python](https://docs.python-guide.org/writing/structure/#test-suite)

**Comment by asottile** [comment]
imo using `sys.path` or `PYTHONPATH` is almost always a bug

**Comment by Tadaboody** [comment]
Same here but it's also good to know of the options 🤷‍♀️

**Comment by Tadaboody** [comment]
@cyberfox1 Does this help you resolve the issue?

**Comment by RonnyPfannschmidt** [comment]
this is expected behavior ^^ without a `__init__.py` pytest doesn't add paths as one might want to test against installed modules instead of those in the work-tree

**Comment by cyberfox1** [comment]
> this is expected behavior ^^ without a `__init__.py` pytest doesn't add paths as one might want to test against installed modules instead of those in the work-tree

So those people can use PYTHONPATH. If I cd into a python module with a "tests" directory and run "pytest" I would expect it to just work. "Principle of least surprise".

**Comment by asottile** [comment]
I'd find it very surprising if things that weren't importable by python's module rules were suddenly importable -- I think the principle of least surprise is adhered to.

**Comment by RonnyPfannschmidt** [comment]
@cyberfox1 for me `Principle of least surprise` is - not adding random things you don't know about to `sys.path`
