### ISSUE TITLE
create a tee-stdio capture method that will print and capture at the python level

### ISSUE THREAD

**Issue by csm10495** [pytest-dev/pytest#4597]
Related to #4584 and #4593 

- [ ] Include a detailed description of the bug or suggestion

The desire is to have a capture mechanism by which output (stderr/stdout) can be saved to both console output (like -s) and junitxml output.

- [ ] `pip list` of the virtual environment you are using

> Package        Version
> -------------- ---------
> altgraph       0.16.1
> atomicwrites   1.2.1
> attrs          18.2.0
> colorama       0.4.1
> ctypesgen      0.post125
> dill           0.2.8.2
> dis3           0.1.2
> funcsigs       1.0.2
> future         0.16.0
> macholib       1.11
> more-itertools 5.0.0
> Pastebin       1.1.2
> pathlib2       2.3.3
> pefile         2018.8.8
> pip            18.1
> pluggy         0.8.0
> py             1.7.0
> pycparser      2.19
> PyInstaller    3.4
> pyreadline     2.1
> pytest         4.0.2
> pywin32-ctypes 0.2.0
> scandir        1.9.0
> setuptools     40.6.3
> six            1.12.0

- [ ] pytest and operating system versions
platform win32 -- Python 2.7.15, pytest-4.0.2, py-1.7.0, pluggy-0.8.0 -- C:\Python27\python.exe
Microsoft Windows [Version 10.0.17134.472]

- [ ] Minimal example if possible

Maybe a --capture=j_no for junit and no?

**Comment by csm10495** [comment]
Hey @RonnyPfannschmidt can you take a quick look at https://github.com/csm10495/pytest/commit/db153a29052ddf337f55eee17894344265f008d3

If this looks like its on the right track, I'd be happy to add some tests/docs and do a formal PR.

**Comment by RonnyPfannschmidt** [comment]
@csm10495 first glance it looks good, but i noted i probably have a typo and meant `tee-stdio`

**Comment by csm10495** [comment]
@RonnyPfannschmidt , haha, that does make a lot more sense.

**Comment by csm10495** [comment]
I think this can be closed now. Thanks all.
