### ISSUE TITLE
Pytest Failing with new Release (4.1.0)

### ISSUE THREAD

**Issue by chgad** [pytest-dev/pytest#4606]
Hello everybody,

I encounter that my Travis CI Build fails with the latest (2 hours old) Release of pytest 4.1.0.

The Error i get, for each Test, looks like this :
```
self = <pytest_cov.plugin.CovPlugin object at 0x2af7e0d326a0>
item = <Function test_model_existence>
    @compat.hookwrapper
    def pytest_runtest_call(self, item):
>       if (item.get_marker('no_cover')
                or 'no_cover' in getattr(item, 'fixturenames', ())):
E               AttributeError: 'Function' object has no attribute 'get_marker'
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/pytest_cov/plugin.py:289: AttributeError
```

My conftest.py consists only of these 4 fixtures:

```
import pytest
from api.models import User, Contract, Shift, Report


@pytest.fixture
def user_model_class():
    return User


@pytest.fixture
def contract_model_class():
    return Contract


@pytest.fixture
def shift_model_class():
    return Shift


@pytest.fixture
def report_model_class():
    return Report

```

Finally we run the following command in Travis `pipenv run pytest --cov=./`

I do not believe that the Tests i run with those fixtures are explicitly relevant for this Error so i only describe what i do with them: I basically call `hasattr()`, `isinstance()` or `issubclass()` and a few basic `assert A == B` calls.

I allready looked into the Changelog and the docs if something corresponding to this error has changed but couldn't find anything. From this point i could only speculate that the new Release breakes something with the pytest_cov Plugin (or visversa).

Any help on how to get this working is appreciated.

Thanks in advance.

**Comment by nicoddemus** [comment]
Hi @chgad thanks for the report! We are really sorry about this breakage.

We have removed `item.get_marker`, users should use `item.get_closest_marker` now (it's a long history, this was not an arbitrary change). Indeed I suspect pytest-cov might need to be updated.

cc @ionelmc

**Comment by ionelmc** [comment]
Ah yes, I'll make a quick release today or tomorrow.

**Comment by nicoddemus** [comment]
Cool, thanks for the quick response!

**Comment by blueyed** [comment]
Closing in favor of https://github.com/pytest-dev/pytest-cov/issues/252.

**Comment by chgad** [comment]
Thank you very much guys, especially for the quick response.
