### ISSUE TITLE
Problems when use latest version (4.1.0)

### ISSUE THREAD

**Issue by prsolucoes** [pytest-dev/pytest#4613]
Hi,

After update my tool to latest pytest, i start getting this error:

https://travis-ci.org/ezored/ezored/jobs/476372726

![image](https://user-images.githubusercontent.com/395096/50772277-61555780-1274-11e9-8ecb-e8d5e1c204a4.png)

Can anyone help me?

**Comment by RonnyPfannschmidt** [comment]
this indicates a broken test which changes to a temporary folder which is subsequently deleted

**Comment by RonnyPfannschmidt** [comment]
based on https://github.com/ezored/ezored/search?q=chdir&unscoped_q=chdir this seems to be entirely self inflicted as no cleanup seems to happen (at least based on the sample of examples i took a look at

**Comment by nicoddemus** [comment]
You say "latest version (2.6.1)", but the latest version is 4.1.0. Was that a typo?

**Comment by prsolucoes** [comment]
Sorry, pytest==4.1.0 and pytest-cov==2.6.1.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus he cant use that due to unittest usage

**Comment by nicoddemus** [comment]
Oh right. Then he will need the "autouse trick" or a custom implementation. I will post those later.

**Comment by prsolucoes** [comment]
If you have any solution, can you post here? It don't happen on old commits:

https://travis-ci.org/ezored/ezored/builds

Very strange.

**Comment by blueyed** [comment]
Just a sidenote: please take a little more time with reporting, i.e. provide tracebacks as text etc.

**Comment by nicoddemus** [comment]
Two solutions:

1. Use an `autouse` fixture to save `monkeypatch` in `self`, then use `self.monkeypatch` on tests:

   ```python
   class TestDependency(TestCase):
       @pytest.fixture(autouse=True)
       def get_monkeypatch(self, monkeypatch):
           self.monkeypatch = monkeypatch
   
       @tempdir()
       def test_dependency_list(self, d):
           self.monkeypatch.chdir(d.path)
   
           d.write(Constants.PROJECT_FILE, Constants.PROJECT_FILE_DATA.encode('utf-8'))
           ...
   ```

2. Implement your own "chdir-like-fixture" that makes use of `TestCase.addCleanup` to restore cwd to the original directory. This might be the simplest as you can simply do a quick find/replace for the `os.chdir` calls and add an import:

   ```python
   # in some utils module somewhere
   def change_cwd(testcase, path):
       old_dir = os.getcwd()
       
       def restore():
           os.chdir(old_dir)
       testcase.addCleanup(restore)
   
       os.chdir(path)
   
   
   # usage
   from .utils import change_cwd
   
   class TestDependency(TestCase):
   
       @tempdir()
       def test_dependency_list(self, d):
           change_cwd(self, d.path)
   
   ```

Hope this helps

**Comment by prsolucoes** [comment]
Hi,

I use the first solution and the problem was solved.

Green again:
https://github.com/ezored/ezored

Thanks.
