### ISSUE TITLE
Question: How to parametrize test cases based on a global?

### ISSUE THREAD

**Issue by Midnighter** [pytest-dev/pytest#4623]
My current strategy is:

1. Parse a dynamic object.
2. Initialize a pytest plugin with that object.
3. Populate the pytest namespace with attributes of that object.
4. Invoke `pytest.main` with the plugin.
5. Use values from the pytest namespace in order to parametrize test cases.
6. Success!

Now that `pytest_namespace` is deprecated, what is a good strategy to replace the existing one? I tried exposing the object as a fixture and using that in a `pytest_generate_tests` hook in order to parametrize tests in a specific module but the hook doesn't accept fixtures.

**Comment by RonnyPfannschmidt** [comment]
please show some code examples, there are plenty ways to do this
one is to put the values you need into a namespace you actually control

another way is to use a set of markers, that represent the plugin details, and let the generate_tests hook figure the actual values from the markers

**Comment by Midnighter** [comment]
Please re-open this issue.

I will try to give a minimized code example. It's a silly example but somewhat mirrors what I'm currently doing. Assuming two Python modules.

`run.py`

```python
import pytest


class Model:
    def __init__(self, content):
        self.content = content

    def get_a(self):
        return [l for l in self.content if l == "a"]

    def get_b(self):
        return [l for l in self.content if l == "b"]


class MyPlugin:

    def __init__(self, model):
        self.model = model

    def pytest_namespace(self):
        return {
            "foo": {
                "aa": self.model.get_a(),
                "bb": self.model.get_b()
            }
        }


def main():
    model = Model("avhfdaabdjfbbbbbbb")
    plugin = MyPlugin(model)
    pytest.main(["tests"], plugins=[plugin])


if __name__ == "__main__":
    main()
```

The actual content of `Model` is only known at runtime.

`tests/test_content.py`

```python
import pytest


AA = pytest.foo.aa
BB = pytest.foo.bb


@pytest.mark.parametrize("content", AA)
def test_aa(content):
    assert all(l == "a" for l in content)


@pytest.mark.parametrize("content", BB)
def test_bb(content):
    assert all(l == "b" for l in content)
```

**Comment by nicoddemus** [comment]
Thanks @Midnighter for the example. 👍

**Comment by RonnyPfannschmidt** [comment]
if you have a plugin already, don't use the namespace hook (its gone in modern pytest), instead declare a own marker to use,

and on top of that marker, just implement the `pytest_generate_tests` hook

that hook us also used to act on the `pytest.mark.parametrize`

**Comment by Midnighter** [comment]
I'm afraid that despite reading the docs on marks I don't see it yet. I understand that I can mark tests and separately I know how to use the hook to parametrize my tests based fixtures. I don't know how the hook can inspect marks nor how it will get access to the `Model` instance present in the `main` function above in order to parametrize the metafunc.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/blob/1a04e8903a9b2148ebfd5dda048e70b7ebf59f82/src/_pytest/python.py#L123-L132 is an example 

its the code turning `pytest.mark.parametrize` into that

**Comment by Midnighter** [comment]
So what I have now and works well is the following. Is that what you meant?

`run.py`

```python
import pytest


class Model:
    def __init__(self, content):
        self.content = content

    def get_a(self):
        return [l for l in self.content if l == "a"]

    def get_b(self):
        return [l for l in self.content if l == "b"]


class MyPlugin:

    def __init__(self, model):
        self.model = model

    def pytest_generate_tests(self, metafunc):
        if metafunc.definition.get_closest_marker("my_aa"):
            metafunc.parametrize("letter", self.model.get_a())
            return
        if metafunc.definition.get_closest_marker("my_bb"):
            metafunc.parametrize("letter", self.model.get_b())
            return


def main():
    model = Model("avhfdaabdjfbbbbbbb")
    plugin = MyPlugin(model)
    pytest.main(["tests"], plugins=[plugin])


if __name__ == "__main__":
    main()
```

`tests/test_content.py`

```python
import pytest


@pytest.mark.my_aa
def test_aa(letter):
    assert letter == "a"


@pytest.mark.my_bb
def test_bb(letter):
    assert letter == "b"
```

**Comment by RonnyPfannschmidt** [comment]
@Midnighter well done, that's a easy going and simple adaptation of my example

**Comment by Midnighter** [comment]
Thank you for your help and time :smiley:
