### ISSUE TITLE
How to know if a testcase is skipped in pytest_runtest_logreport() hook

### ISSUE THREAD

**Issue by raoyitao** [pytest-dev/pytest#4628]
I'm using Python 3.4 & PyTest 3.6.0 on Redhat 6.

I have a simple testcase:

    @pytest.mark.skip(reason="no way of currently testing this")
    def test_failure(self):
        assert False == True

when I run it, surely it will be skipped by PyTest.

I wrote a plugin object passed to PyTest and implemented pytest_runtest_logreport(self, report), in this hook, I found there are 'skipped' and 'outcome' attributes in report. If report.when == 'call', I expected that report.skip == True and report.outcome == 'skipped', however I got False and 'failed' respectively. Why this happened?

**Comment by RonnyPfannschmidt** [comment]
please show a minimal reproducer thats runnable (aka at least also the hook you implemented) so we can try locally without re-implementing what we think you have instead of having exactly what you have

**Comment by raoyitao** [comment]
Oh I'm sorry, as I tested it again, my pytest version is 2.8.7 and it has the problem. After updated to 3.6.0 it is solved. If a test item is marked skipped, then the setup report of the test item will have outcome 'skipped' and won't run the testcase, so the next time pytest_runtest_logreport() is called I can see report.call == 'teardown'.

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup, i'm delighted things work for you now :+1:
