### ISSUE TITLE
Pickle pytest running state?

### ISSUE THREAD

**Issue by csm10495** [pytest-dev/pytest#4634]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
Is there a way to save the current state of a pytest run to resume it later? I have a test that I would like to do a reboot during then resume (that test case) afterwards. I can pickle things that I need to save, but at the end it would be nice to get one test-result output file (and one junitxml). Is this possible?
- [ ] `pip list` of the virtual environment you are using
```
Package           Version
----------------- ----------
aiofiles          0.4.0
altgraph          0.16.1
appdirs           1.4.3
args              0.1.0
astor             0.7.1
atomicwrites      1.2.1
attrs             18.2.0
backgroundchanger 0.2.0
beautifulsoup4    4.7.0
bs4               0.0.1
certifi           2018.11.29
cffi              1.11.5
chardet           3.0.4
Click             7.0
clint             0.5.1
colorama          0.4.0
dicttoxml         1.7.4
dill              0.2.8.2
feedparser        5.2.1
Flask             1.0.2
funcparserlib     0.3.6
future            0.17.1
gevent            1.3.7
greenlet          0.4.15
gunicorn          19.9.0
humanize          0.5.1
hy                0.15.0
idna              2.8
iso8601           0.1.12
ItsDangerous      1.0.0
Jinja2            2.10
lxml              4.3.0
macholib          1.11
MarkupSafe        1.0
more-itertools    4.3.0
Pastebin          1.1.2
pefile            2018.8.8
Pillow            5.3.0
pip               18.1
pluggy            0.8.0
plumbum           1.6.7
printer           2.0.0
processor         0.10.0
psutil            5.4.8
py                1.7.0
pycparser         2.19
PyInstaller       3.4
pypiwin32         223
pyreadline        2.1
pyserial          3.4
pytest            4.0.2
pytz              2018.5
pywal             3.2.1
pywin32           223
pywin32-ctypes    0.2.0
PyYAML            3.13
requests          2.21.0
rply              0.7.6
rpyc              4.0.2
setuptools        39.0.1
six               1.11.0
soupsieve         1.6.2
Twiggy            0.4.7
twiggy-goodies    0.12.0
urllib3           1.24.1
vboxapi           1.0
Werkzeug          0.14.1
```
- [ ] pytest and operating system versions
4.0.2 / Win 10
- [ ] Minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
its absolutely unclear what you are asking for or what use-case you are planning to support

**Comment by csm10495** [comment]
Say I have a test that I am running. In order to complete the execution of the test, I need to reboot the entire computer. I'd like to have a way to save the pytest state (via pickle) to re-enter the test and complete the test case we are in and then move on to do remaining tests after. 

So say I have 3 tests: A, B, C that are run in that order. Say test B needs a reboot midway through.

So I'd want test A to run, Test B to partially run... reboot... then I re-enter the test (I can rekick pytest with some args or manually save some data if i knew what to save)... so after reboot Test B continues where it left off, then test C runs. I get final results for all 3 tests that ran.

If it's not currently possible, that's fine and we can close this. Just wanted to know if there was an existing way to do it.

**Comment by RonnyPfannschmidt** [comment]
its currently impossible and there is no plan to add support for something like that at all

the typical way to do acceptance tests with reboots necessary is to use vm's
