### ISSUE TITLE
Recommended "results dashboard" solutions ?

### ISSUE THREAD

**Issue by david-fliguer-ws** [pytest-dev/pytest#4640]
Hi,

Right now we get the results from our automated tests by email, where the email has an HTML attached to it that we generate using pytest-html plugin.

We are thinking about moving to some kind of "dashboard" where we could ideally:

- Have an history of our different runs
- Search easily runs
- Get some statistics
- See the results of the run in "live time"

Is important that it supports the different pytest results (skipped, xfailed,xpass) and also ideally running in parallel (We plan to do this using pytest-xdist)

Any recommendation about this ? I've heard about the following

- reportportal
- pytest-ochrus ? (I'm kind of doubting because I see that the project has 4 commits and last one is from 2018...)

Any help regarding this would be appreciated

Thanks and keep the good work !!!

David

**Comment by pfctdayelise** [comment]
Are you using a CI server? I feel like it's more common that the CI server would have the function (or plugin) to keep history of changes of test results.

**Comment by david-fliguer-ws** [comment]
Hi,

Yes we run our tests in Jenkins, but as far as I know Jenkins has a really basic plugin that stores the results in XML files and displays it on Jenkins itself (I've used a little bit and I didn't like it)

I am looking for a more powerful platform that also allows for searchs, maybe comparison between runs, etc...

**Comment by david-fliguer-ws** [comment]
Hi, can this be re-opened ? I am still looking for a good solution...

**Comment by pfctdayelise** [comment]
Hi David,

I think you are looking for something distinct enough that it is outside the scope of core pytest, and I would suggest outside the scope of pytest plugins as well. This product is probably called something like a "test report dashboard" or "test results management" tool.

Have you looked for different Jenkins plugins? Are you using the Test Results Analyzer plugin? https://wiki.jenkins.io/display/JENKINS/Test+Results+Analyzer+Plugin

If you want to use a different tool, the way to do it would likely be: have pytest create junitxml output (this is a defacto standard for test output), have your Jenkins job post this XML to whatever the server for your test report dashboard is.

A few tools I'm aware of: 

- https://www.qacube.com/qa-analytics
- https://www.tesults.com/
- https://www.perfecto.io/test-reporting-automation/
- http://www.inflectra.com/SpiraTest/ actually they did create a pytest plugin, pytest-spiratest
- http://allure.qatools.ru/ is open source, has a pytest plugin allure-pytest
- Report Portal you mentioned has a pytest plugin agent-python-pytest


The pytest team can't solve this problem for you, I'm sorry. But if you find a good solution I am sure we would be interested if you report back what you found.

**Comment by adamhasham** [comment]
@david-fliguer-ws interested to hear what you ended up using!
