### ISSUE TITLE
Why is pytest_sessionstart in conftest.py causing 'Fixtures are not meant to be called directly' error?

### ISSUE THREAD

**Issue by dcs3spp** [pytest-dev/pytest#4644]
Hi,

Can anyone explain why the *pytest_sessionstart* fixture in conftest.py is causing an error relating to Fixtures are not meant to be called directly?

I have searched the root directory and there are no further references to *pytest_sessionstart* so the fixture is not being called anywhere else within the project. 

I have installed the project source code from requirements.txt file using ```pip install -r requirements.txt```

The conftest.py file is listed below. If I uncomment the *pytest_sessionstart* fixture tests run!

I am using pytest 4.1.1 on OSX High Sierra 10.13.6.

```
import locale
import logging
import pytest

from pyramid_core.testing import FileServerFactory
from pyramid_core.testing.factories import TestEnvironment

def pytest_configure(config):
    TestEnvironment(config)

def pytest_addoption(parser):
    parser.addini("file.server.path", "file server")

@pytest.fixture(scope='session')
def docker_compose_files(pytestconfig):
    config = FileServerFactory.get_config(pytestconfig)
    return config.validated_files

@pytest.fixture(autouse=True, scope='session')
def pytest_sessionstart( ):
    locale.setlocale(locale.LC_TIME, '')
    logging.basicConfig(level=logging.INFO,
        format='%(asctime)s    %(levelname)s    %(module)s::%(funcName)s line %(lineno)s %(message)s',
        datefmt='%x:%X')

    logging.info('datetime locale set to {}'.format(locale.getlocale(category=locale.LC_TIME)))
    logging.info('logging configured')
```

**Comment by nicoddemus** [comment]
Hi @dcs3spp,

The code doesn't seem to be enough for us to understand the problem, can you also post the traceback please?

**Comment by RonnyPfannschmidt** [comment]
a pytest hook is **never** a fixture

so by marking the `pytest_sessionstart` hook as fixture instead of a `pytest.hookimpl()` you literally shoot your own foot

**Comment by nicoddemus** [comment]
Oh I completely missed the `@pytest.fixture(autouse=True, scope='session')` on `pytest_sessionstart` 😛

**Comment by nicoddemus** [comment]
@dcs3spp try to remove the `@pytest.fixture` declaration from `pytest_sessionstart`. If that does not work please post the full traceback.

**Comment by dcs3spp** [comment]
Oops, ok apologies....

Cheers @RonnyPfannschmidt and @nicoddemus. That got me up and running :)
