### ISSUE TITLE
pytest v3.2.3 gives internal RecursionError

### ISSUE THREAD

**Issue by tafify** [pytest-dev/pytest#4648]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [x] Minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
unfortunately without more information on what code, what system we cant make any sense of this one

if you cant repro we might have to even close this one as unverifiable result of your temporary system state

**Comment by tafify** [comment]
fair enough. @RonnyPfannschmidt what info can I provide about the code? the pytest function is huge and it is parametrized. The test runs on Ubuntu system 16.04 amd64. A small impersonation can be like so

```python
import asyncio
import re
import websockets
import aiohttp
import traceback
...
@pytest.mark.asyncio
@pytest.mark.parametrize('task', collect_all_tasks(), ids=get_task_name_as_id)
async def test_tasks(task):
...
```
websockets==3.2
aiohttp==2.1.0

The test runs several parametrized tasks then it failed with the callstack I provided in my previous comment.

Interesting, not a single line in the call stack refers to the test function or any external module (other than python traceback.py), which is why I think it is a pytest internal failure unrelated to what test it calls.

Thanks @RonnyPfannschmidt  for looking at it, let me know if there is specific info I can provide further to help the community, or else I'm fine with closing the ticket and avoid wasting time.

**Comment by RonnyPfannschmidt** [comment]
@tafify unforutnately with the current amount of provided information, there is nothing for us to act on

its worth noting, that pytest will consubme the complete collection of tasks before trying to run any of them - if that is something not fit with your expectations for execution that could be a possible cause

also im not fluent with the interaction with the asyncio eventloop, there may be usage patterns that trigger a chance for the issue you saw

**Comment by tafify** [comment]
Thanks @RonnyPfannschmidt, hopefully, next time I encounter this I'll have steps to repro the issue. I was hoping that the callstack can point to the faulty recursive calls. 
Closing the issue
