### ISSUE TITLE
tmp_path fixture provider is symlink Path on MacOS

### ISSUE THREAD

**Issue by AuHau** [pytest-dev/pytest#4653]
```
platform darwin (10.14) -- Python 3.6.5, pytest-3.10.1, py-1.7.0, pluggy-0.8.1 
```

The bug of #110 was reintroduced by refactoring to the usage of `pathlib.Path`.

On MacOS provided Path by `tmp_path` fixture is symlink and when `cd`ed into it, it changes into one prefixed by `/private`.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/commit/fc61bdd9073d86819eb54c8603384a10c626a9d4 had it "fixed" and https://github.com/pytest-dev/pytest/pull/4427 also broke it again

@nicoddemus do you recall the exact platform issue?

**Comment by RonnyPfannschmidt** [comment]
actually https://github.com/pytest-dev/pytest/pull/4427/commits/5f1d69207260297738ff4dd96687fe049d2963a3 is a bad test that i wrote missunderstanding the situation

i believe we need to use abspath on windows and resolve on any unix

**Comment by AuHau** [comment]
See the PR #4654.

Don't you think that `resolve()` will solve this for Windows? I unfortunately don't have way to test it.

**Comment by RonnyPfannschmidt** [comment]
@AuHau i recall resolve breaking on windows - @nicoddemus proposed just using abspath, and then i made a mistake with the osx tests
