### ISSUE TITLE
get capfd of run in fixture

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest#4663]
During https://github.com/tox-dev/tox/pull/1145#discussion_r249485580 it came up that pytest injects different instance for ``capfd`` on the fixture and on test function. Any way to get the call/run capfd inside a fixture? (use case: the fixture provides a helper function that automatically collects output during the run, and ideally would like to avoid the need for the user to pass it through from the call site). Thanks!

**Comment by nicoddemus** [comment]
Hi @gaborbernat!

I'm short on time so I didn't follow the discussion in tox-dev/tox#1145, but the short example below shows that you get the same `capfd` instance in fixtures and test functions:

```python
import pytest

@pytest.fixture
def fix(capfd):
    print('setup')
    yield
    print('teardown')
    assert 0, repr(capfd.readouterr().out)

def test_foo(fix, capfd):
    print('call')
``` 

This prints:

```
________________________ ERROR at teardown of test_foo ________________________

capfd = <_pytest.capture.CaptureFixture object at 0x044E4790>

    @pytest.fixture
    def fix(capfd):
        print('setup')
        yield
        print('teardown')
>       assert 0, repr(capfd.readouterr().out)
E       AssertionError: u'setup\ncall\nteardown\n'
E       assert 0

.tmp\test-foo.py:8: AssertionError
---------------------------- Captured stdout setup ----------------------------
setup
---------------------------- Captured stdout call -----------------------------
call
```

Also, I've made sure both `capfd` are the same instance by printing their `id()` (not shown here).

Can you please clarify what you mean, perhaps with a short example? Thanks! 🙇

**Comment by gaborbernat** [comment]
Indeed, this works as presented above with latest, maybe it was some bug in some older version. Anyway can no longer replicate, so thanks!
