### ISSUE TITLE
The short test summary info should use `pytest_report_teststatus` hook data

### ISSUE THREAD

**Issue by wimglenn** [pytest-dev/pytest#4667]
https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_report_teststatus 

```
@hookspec(firstresult=True)
def pytest_report_teststatus(report):
    """ return result-category, shortletter and verbose word for reporting.

    Stops at first non-None result, see :ref:`firstresult` """
```

Short test summary info that you get (e.g. with `pytest -rap`) should use the hook result.

Instead it uses data from a weird place - some hardcoded strings in a seemingly unrelated module [`_pytest/skipping.py`](https://github.com/pytest-dev/pytest/blob/4.1.1/src/_pytest/skipping.py#L289-L298).

**Comment by nicoddemus** [comment]
Hi @wimglenn,

Indeed, at first glance you are correct. `skipping.pytest_terminal_summary` should call `pytest_report_teststatus`, which can be implemented somewhere else to use that mapping.

**Comment by wimglenn** [comment]
Well, I had an attempt at it. Unfortunately, there is a weird decision to make - should the symbols in short test summary be matching the symbols in the test report (i.e. what the hook has otherwise returned), or should we override hook again, at the cost of being inconsistent, in order to get backwards compatibility there. Because in the report it's currently defaulting to `FAILED` but in the short test summary it was `FAIL`.  Similarly, in the report there's `xfail` and in the short test summary it's `XFAIL`.

**Comment by wimglenn** [comment]
Also https://github.com/pytest-dev/pytest/commit/9711e335d976b3030b667636a6666019c430b52c seems a violation of the hook spec - I think that should really be done differently.
