### ISSUE TITLE
Describing AssertionErrors raised from imported functions

### ISSUE THREAD

**Issue by bogdanpetrea** [pytest-dev/pytest#4671]
Assertion errors from imported functions are not described like the ones raised inside the test functions. Is this possible even?
Found a related [stackoverflow question](https://stackoverflow.com/questions/49033809/describing-failing-assert-statements-in-imported-functions-with-pytest) but it's not answered.

**Comment by nicoddemus** [comment]
It is possible, but you need to manually specify the modules that you want to see the assertions for using [pytest.register_assert_rewrite()](https://docs.pytest.org/en/latest/reference.html#pytest-register-assert-rewrite).

For example, if you have a package `mylib.testutils` which contains various helpers for testing, you can add this to your root `conftest.py` to obtain rich assertions from functions defined there:

```python
import pytest
pytest.register_assert_rewrite('mylib.testutils')
```

This declaration is recursive, so it will work for functions declared in `mylib.testutils` and `mylib.testutils.numutils` in case `testutils` is a package with other modules inside it.

**Comment by bogdanpetrea** [comment]
Thanks @nicoddemus, it worked.

**Comment by nicoddemus** [comment]
Glad it helped!

**Comment by nicoddemus** [comment]
Btw feel free to answer that SO question pointing to this issue to help others. 👍
