### ISSUE TITLE
[Feature Request]: Jumping to definition of fixture in VS Code

### ISSUE THREAD

**Issue by arizzubair** [pytest-dev/pytest#4685]
Is there any IDE which pytest supports fully, like code intellisense, jumping to definition etc. Pycharm works ok with pytest but it is far from ideal. 
Is there any plugin to jump to fixture definition in vs code?  
- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by nicoddemus** [comment]
FWIW I use PyCharm and I'm a happy camper!

@arizzubair if you find the answer to your question, please do come back and post it here so it can help others! 👍

**Comment by arizzubair** [comment]
I use pycharm with pytest plugin. It has fixture autocompletion and fixture definition.  It allows me to jump to fixture definition, which is important for my workflow. But the plugin does not support newer pycharm versions. I tried vscode but the pytest plugin there is poor. There is no option of jumping to the fixture definition. 

There should be a recommended IDE setup for pytest.

**Comment by nicoddemus** [comment]
What do you mean "with pytest plugin"? I ask because PyCharm has native pytest support.

**Comment by arizzubair** [comment]
I am talking about this plugin: https://plugins.jetbrains.com/plugin/10242-pytest

**Comment by nicoddemus** [comment]
Oh I didn't know that existed. I suggest to try to uninstall it and use the native support instead, and see if that works better for you.

**Comment by blueyed** [comment]
Sadly no docs apparently.
/me was just interested what it provides/does, but does not use PyCharm himself.

**Comment by nicoddemus** [comment]
From the top of my head: code completion for fixtures (so if you type `tmpdir.` it will show all `tmpdir` methods), "go to definition" for fixtures, run tests selecting them in a windows...
