### ISSUE TITLE
pytest shows Deprecation Warnings for functions inside virtualenv

### ISSUE THREAD

**Issue by tdbs** [pytest-dev/pytest#4695]
I have this directory:

- repository/
    - main/
    - venv/
    - tests/

running pytest (even with --ignore venv/) shows Deprecation Warnings for things not on my code, but on libraries in the virtual environment.

```
tests/test_worker.py::TestWorker::test_func
  /Users/username/repository/venv/lib/python3.7/site-packages/imported_lib/lib_file.py:33: DeprecationWarning: 'with await lock' is deprecated use 'async with lock' instead
    with await self.connected_lock:
  /Users/username/repository/venv/lib/python3.7/site-packages/imported_lib/lib_file.py:380: DeprecationWarning: 'with (yield from lock)' is deprecated use 'async with lock' instead
    with (yield from self._get_conn_lock):
```

I have no control over the calls the libs I use make, so these warnings are clutter for me.
Is there a way to not see them? I don't want to filter all Deprecation warnings otherwise my own deprecated uses will not show.

**Comment by nicoddemus** [comment]
Hi @tdbs, 

One way is to filter them individually in your `pytest.ini`:

```ini
[pytest]
filterwarnings =
    ignore:'with await lock' is deprecated use 'async with lock' instead
```

**Comment by tdbs** [comment]
Hi @nicoddemus but, this will filter out the same warning if it's in my code, the code base is big and not done by me, so i don't want to filter things that might actually **also** be in my code

**Comment by nicoddemus** [comment]
I see. `filterwarnings` receives the same parameter as `warnings.filterwarnings`:

```ini
[pytest]
filterwarnings = 
    ignore:'with await lock' is deprecated use 'async with lock' instead::imported_lib
    # or, if you want to ignore all warnings from 'imported_lib':
    ignore:::imported_lib
```

**Comment by tdbs** [comment]
thank you @nicoddemus that will work!
