### ISSUE TITLE
Release 4.2.0: xfail spelling change breaks test suite

### ISSUE THREAD

**Issue by hackebrot** [pytest-dev/pytest#4705]
Hi friends! 👋 

Upgrading to [pytest 4.2.0][4.2.0] caused failures in the [pytest-emoji testsuite][pytest-emoji], because ``pytest_report_teststatus`` now returns ``XFAIL`` instead of ``xfail`` for the verbose test report.

I'm raising this here as our [changelog][changelog] did not warn about this change (#4667, #4668). I welcome the change for the sake of consistency with other test outcomes, but I'm afraid this might cause some confusion for plugin maintainers.

How do you feel about updating the changelog to warn about this change? I'm happy to submit a pull request for that, if you think it makes sense. 🤔 

[4.2.0]: https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#pytest-420-2019-01-30
[pytest-emoji]: https://github.com/hackebrot/pytest-emoji/commit/2ff7d99ae2c9ce69c840236b1eac02c5fa6c7591
[changelog]: https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst

Here's a minimal testcase, which passes for 4.1.0 but fails for 4.2.0:

```python
import textwrap
import pytest


def test_emoji_disabled_by_default_verbose(testdir):
    testdir.makepyfile(
        textwrap.dedent(
            """
        # -*- coding: utf-8 -*-

        import pytest

        def test_passed():
            assert True

        def test_failed():
            assert False

        @pytest.mark.xfail
        def test_xfailed():
            assert False

        @pytest.mark.xfail
        def test_xpassed():
            assert True
        """
        )
    )

    result = testdir.runpytest("-v", "-o", "console_output_style=classic")

    result.stdout.fnmatch_lines(
        [
            "*::test_passed PASSED",
            "*::test_failed FAILED",
            "*::test_xfailed xfail",
            "*::test_xpassed XPASS",
        ]
    )

    assert result.ret == 1
```

**Comment by nicoddemus** [comment]
Howdy Raphael!

> How do you feel about updating the changelog to warn about this change? I'm happy to submit a pull request for that, if you think it makes sense.

Sounds good, indeed that slipped and we should make the change clearer in the CHANGELOG. It would be great if you could submit a PR. 👍 🙇

**Comment by hackebrot** [comment]
Which changelog category would be most fitting?

**Comment by nicoddemus** [comment]
I think "trivial" is OK?
