### ISSUE TITLE
Customizing FileHandler of LoggingPlugin from hook

### ISSUE THREAD

**Issue by mitzkia** [pytest-dev/pytest#4707]
Which hook is the best to customizing FileHandler of LoggingPlugin with the name of the testcase?
My goal is to create separate logfiles for each testcases (filename should contains name of the testcase).

Already tried:
- pytest_report_header(): I can overwrite FileHandler of LoggingPlugin, but the testcase information is not yet exist (I would need name of the testcase from: request.node.originalname)
- pytest_runtest_logstart(): I have got name of the testcase, but when I try to overwrite the FileHandler of LoggingPlugin it will take no effect.

**Comment by nicoddemus** [comment]
cc @thisch to get his take on this 👍

**Comment by RonnyPfannschmidt** [comment]
We dont have a way to customize this atm

**Comment by mitzkia** [comment]
@nicoddemus , @RonnyPfannschmidt Thanks for your answers. 
Is this goal goes against the current pytest architecture (is this a hard problem)? 
I hope somehow this goal can be achieved, if this could work we can switch totally to the native LoggingPlugin. 
Is there any workaround currently for this problem (just to start with something)?

**Comment by nicoddemus** [comment]
Hi @mitzkia,

> Is this goal goes against the current pytest architecture (is this a hard problem)?

Not really, we just have to figure out the best way to fit that requirement with how the native plugin works.

> Is there any workaround currently for this problem (just to start with something)?

Off hand I don't think there is, because the log file is taken directly from the command line.

Just to clarify, what you mean by "testcase" exactly? Name of the class which contains test methods?

**Comment by mitzkia** [comment]
Hi @nicoddemus 

Thanks for your question. My thought was to name the log-file as the test methods was named. As far as I know this information is exists in: request.node.originalname or in request.node.name.

In my case it would be the best if I could customize the filename parameter of the `logging.FileHandler()` call.

Just an example dir hierarchy from my side:
```
.
|-- conftest.py
|-- functional_tests
|-- pytest.ini
|-- reports
|-- src
```

In my case the reports dir contents is the following:
```
reports/2019-01-29-12-55-42-315311/test_acceptance/testcase_test_acceptance.log
```
- 2019-01-29-12-55-42-315311: directory, full date when the pytest run was executed (this parent directory would not change during the testruns)
- test_acceptance: directory, name of the test method, contains all of the session files which created during actual test run, and also contains the testlog file (this directory will be created when pytest switchs to another test method)
- testcase_test_acceptance.log: file, the actual testlog file, "tescase" is a simple prefix string, "test_acceptance" name of the test method (this file is created for each test method)

**Comment by thisch** [comment]
@mitzkia Thx for bringing this issue up. (The company I work for implemented a custom unittest based testrunner that has support for creating one log file per testcase. We also store the log files in a directory containing the timestamp of the time when the testrunner was started)

I think we can easily implement support for this use case in pytest, but maybe we should instead support this customization via hooks.

**Comment by thisch** [comment]
What do you think if we only add a ``set_log_filename`` method to the LoggingPlugin class? Then we could write a local hook that takes care of updating the log filename of each test.

```py
@pytest.hookimpl(tryfirst=True)
def pytest_runtest_call(item):
    config = item.config
    logging_plugin = config.pluginmanager.get_plugin("logging-plugin")

    full_fname = os.path.join(
        basedir,
        item._request.node.name + '.log'
    )
    logging_plugin.set_log_filename(full_fname)
```

**Comment by thisch** [comment]
@mitzkia I've just pushed the initial implementation to my pytest fork on github.

Please give it a try. 
If you want to contribute to pytest, which would be very welcome, feel free to take over this code and create a PR out of it.

**Comment by mitzkia** [comment]
Hi @thisch 

Thank you very much for your help, and for your suggestion. 
Then I will try to create a PR (of course I will mark you as a signer too).

Thanks

**Comment by mitzkia** [comment]
Related PR: #4752

**Comment by mitzkia** [comment]
@nicoddemus, @RonnyPfannschmidt, @thisch Thanks for your help again. 
The related PR is merged :).
