### ISSUE TITLE
pytest lacks option to emit cmdline passed to subprocess.Popen(cmdline) - totally idiotic

### ISSUE THREAD

**Issue by Smit-tay** [pytest-dev/pytest#4710]
If there is a way to do this, please excuse me, but I've spent a day trying to find it, so, clearly it's not obvious.

I am sorry to rant, but - there's just no excuse for this.

It ABSOLUTELY idiotic to inhibit the ability to emit the *exact* command that is about to be executed - as a matter of course.  How could a developer possibly be expected to figure out why a command is failing when he can't see the command that is being executed ?

This is possibly the most moronic active (as in, clearly intentional) decision I have ever come across in my career as a programmer.

If such functionality exists, why is it no obvious, clearly documented, or at least mentioned somewhere how to do it ?

**Comment by nicoddemus** [comment]
Hi, thanks for creating an issue, but this type of attitude and swearing is not welcomed. Feel free to open another issue.

**Comment by Smit-tay** [comment]
There's no swearing in this issue.

Just because you find the opinions expressed challenge your love of python does not mean they are even offensive.

This is a legitimate question, asked in a slightly provacative wording which none-the-less deserves to be addressed.
