### ISSUE TITLE
Can't emit command passed to subprocess.popen

### ISSUE THREAD

**Issue by Smit-tay** [pytest-dev/pytest#4711]
The title says it all, without the rant, which may be found here in closed issue. 4710

This is a fundamental requirement.  It's beyond comprehension that an obvious means of achieving this can't be found

**Comment by RonnyPfannschmidt** [comment]
its neither fundamental nor a required part of pytest

there is multiple libraries out there to support debugging sub-process invocations and in case of having local variables a natural solution to show local variables is `--showlocals`

a very common solution is debug logging/tracing which can be enabled not just for the test-running but also for other types of invocations

**Comment by Smit-tay** [comment]
Why would I require yet another library to emit the information known to the current library, pytest.

Pytest doesn't play well with pdb, as anyone who has ever tried will confirm.

If it's simply a matter of adding a command line switch, please provide an example.  I've tried every possible option I can find through various Google searches.

**Comment by RonnyPfannschmidt** [comment]
the thing is - it is not known to pytest - its somewhere in **your** call stack ^^

`pytest --showlocals ` will make pytest show local variables in stack traces by inspecting frames

**Comment by Smit-tay** [comment]
So, really, I'm trying to play nice....

I have no diea what you mean when you say "pytest --showlocals"

I have a suite of tests (4 python scripts) in a directory named "test".  The instructions for running the tests is:

python3.7 -m pytest test/ 

So, assuming I don't want to modify the test scripts contained in the test directory, your suggestion is that I should simply add --showlocals after pytest.

That results in this output:
[build]$ sudo python3.7 -m pytest --showlocals test/
....
test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse_drop_privileges] FAILED                       [ 31%]

======================================================= FAILURES =======================================================
_____________________________ test_hello[hello-options0-invoke_mount_fuse_drop_privileges] _____________________________
Traceback (most recent call last):
  File "/home/me/dev/FUSE/libfuse/build/test/test_examples.py", line 67, in test_hello
    wait_for_mount(mount_process, mnt_dir)
  File "/home/me/dev/FUSE/libfuse/build/test/util.py", line 42, in wait_for_mount
    pytest.fail('file system process terminated prematurely')
  File "/usr/local/lib/python3.7/site-packages/_pytest/outcomes.py", line 113, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: file system process terminated prematurely
------------------------------------------------- Captured stderr call -------------------------------------------------
/bin/sh: hello: command not found
=============================================== short test summary info ================================================
FAILED test/test_examples.py::test_hello[hello-options0-invoke_mount_fuse_drop_privileges]
========================================= 1 failed, 12 passed in 19.16 seconds =========================================
[build]$ 

So, doesn't help AT ALL, and is absolutely no different than the output without "--showlocals"

I've tried adding "-s" to the command line, but that gives a bunch of arguments separated by commas, and includes unclear quotation marks, and other spurious characters.  So, the exact command that is being attempted is unknown (so, totally un-clear.  THAT's Stupid)

So, how do I get pytest to show me what is being executed by the call to  subprocess.popen()

**Comment by RonnyPfannschmidt** [comment]
i'm no longer willing to spend my personal time on you

**Comment by Smit-tay** [comment]
Great.

Good response.

I get it.  Your time is voluntary.  You don't need the aggravation.  I apologize.

**Comment by Smit-tay** [comment]
So.  If you don't know the answer, or don't understand the question, just say.

But please don't adopt the holier than thou position, because nobody benefits from that.

**Comment by RonnyPfannschmidt** [comment]
i already provided all details needed to sort this out, and based on on your behaviour i'm not willing to break it down further
