### ISSUE TITLE
how to change pytest Generated parameters

### ISSUE THREAD

**Issue by lycaste** [pytest-dev/pytest#4712]
is there any possible change the test_zerodivision param when execute test_equals function

when test_equals is running test_zerodivision function param is a=1 b=0, but i want to change a or b value in this function

can i change TestClass.params then reload pytest_generate_tests or any other ways

i konw how to avoid this problem,but i just want know how change the value.

```
import pytest
def pytest_generate_tests(metafunc):
    # called once per each test function
    funcarglist = metafunc.cls.params[metafunc.function.__name__]
    argnames = sorted(funcarglist[0])
    metafunc.parametrize(argnames, [[funcargs[name] for name in argnames]
            for funcargs in funcarglist])

class TestClass(object):
    # a map specifying multiple argument sets for a test method
    params = {
        'test_equals': [dict(a=1, b=2), dict(a=3, b=3), ],
        'test_zerodivision': [dict(a=1, b=0), ],
    }

    def test_equals(self, a, b):

        assert a == b

    def test_zerodivision(self, a, b):
        with pytest.raises(ZeroDivisionError):
            a / b
```

**Comment by nicoddemus** [comment]
Hi @lycaste,

Unfortunately that is not possible; once collection is done, the parameters are fixed for that call. If you need to change them at runtime, I suggest to just change the parameters inside the test normally, without using pytest mechanisms (which is not supported anyway).

Closing for now, feel free to follow up with further questions. 👍
