### ISSUE TITLE
Tests failed with python3.8.0a1

### ISSUE THREAD

**Issue by matrixise** [pytest-dev/pytest#4716]
Hi,

I have tried to execute the tests with the new alpha release of Python 3.8

https://www.python.org/downloads/release/python-380a1/

And I get some errors, maybe it's an issue with pytest or with pytest but I have created an issue on the bug tracker of Python (https://bugs.python.org/issue35895)

[tox-pytest-38-stdout.log](https://github.com/pytest-dev/pytest/files/2828383/tox-pytest-38-stdout.log)

**Comment by RonnyPfannschmidt** [comment]
thanks for trying and getting us a early pointer about python 3.8 compatibility

At first glance it seems all to come down to minor differences in ast for the assertion rewriting which is a great starting point, it should be relatively straightforward to sort out the issues on time.

As of now i cant tell which of those are intended updates of the ast and which are python alpha issues that will go away themselves - the tracking issue here and over in the python tracker will be a great tool to stay on top of it.

:+1:

**Comment by RonnyPfannschmidt** [comment]
after taking a glance at the detail issues in the python tracker it seems that the ast provides various rock-solid extra metadata elements that will allow us to ensure MUCH more solid statement range finding,
a side effect seems to be some extra nodes we don't yet expect

**Comment by matrixise** [comment]
@RonnyPfannschmidt cool nice news.

**Comment by asottile** [comment]
Is there a stacktrace for this? I'm having trouble finding the failure mode and what triggers it -- can it be edited into the original message here and/or on the bpo issue?
