### ISSUE TITLE
FR: Full Object Support in Cache

### ISSUE THREAD

**Issue by jerodg** [pytest-dev/pytest#4717]
It would be awesome if the cache had better support for objects. i.e. dicts, classes, dataclasses, etc.

**Comment by RonnyPfannschmidt** [comment]
limiting it to json prevents a major set of headaches that complete serialization imposes (cycles, attack  vectors

so from my pov there needs to be a good proposal and a sane sheme that we can sanely move to

without that im -1 on it

**Comment by Zac-HD** [comment]
See #2899 - this is unlikely to be supported due to the security and maintenance headaches it would impose.

You can get around that by storing pickled objects as strings if you really want to; the headaches may still exist but then they're your problem not ours.
