### ISSUE TITLE
-k expression does not handle "1x and smoke"

### ISSUE THREAD

**Issue by Vic152** [pytest-dev/pytest#4729]
- [x] Include a detailed description of the bug or suggestion
When I try to run tests with `python -m pytest -k "1x and smoke"`
I get and error: `ERROR: Wrong expression passed to '-k': 1x and smoke`

However if they are passed separate it works just fine `python -m pytest -k "1x"`
- [x] pytest and operating system versions

pytest==4.0.2
websocket-client==0.54.0
parse==1.9.0
selenium==3.14.1
psutil
pywin32==224
pytest_bdd==3.0.1
pytest-html==1.19.0

Win 10 x64
- [x] Minimal example if possible
I use pytest-bdd and scenarios are tagged @smoke @1x

I realised that it works the other way around: `x1 and smoke` but this does not make sense for the tags.

**Comment by RonnyPfannschmidt** [comment]
complex keyword expressions must be valid python expressions, this is a long standing limitation

**Comment by Vic152** [comment]
Does it simply mean hat tags cannot start with a number if used in complex keyword?

**Comment by RonnyPfannschmidt** [comment]
yes - they currently absolutely have to be valid python identifiers

**Comment by Vic152** [comment]
Thank you!
