### ISSUE TITLE
pytest.mark.dependency depends not honored

### ISSUE THREAD

**Issue by jtmoon79** [pytest-dev/pytest#4737]
Using `@pytest.mark.dependency` does not honor the `depends` parameter.  The dependency check does not work.

Following the example from [readthedocs.io page *usage* section *naming-tests*](https://pytest-dependency.readthedocs.io/en/latest/usage.html#naming-tests), my file looks like

```Python
import pytest

class TestClassNamed(object):

    @pytest.mark.dependency(name="a")
    @pytest.mark.xfail(reason="deliberate fail")
    def test_a(self):
        assert False

    @pytest.mark.dependency(name="b", depends=["a"])
    def test_b(self):
        pass
```

Running this

```
PS > pytest .\test\ -v
===================== test session starts =====================
platform win32 -- Python 3.7.1, pytest-4.2.0, py-1.7.0, pluggy-0.8.1 -- c:\users\user1\.virtualenvs\project1-3kr5jz-l\scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\user1\Downloads\project1\test, inifile:

test/test_1.py::TestClassNamed::test_a XFAIL   [ 50%]
test/test_1.py::TestClassNamed::test_b PASSED  [100%]
```

I expected `TestClassNamed::test_b` to be `SKIPPED` because the `depends` on test named "`a`" which failed.  However, `TestClassNamed::test_b` was run and `PASSED` which I did not expect.

I tried this without the `@pytest.mark.xfail(reason="deliberate fail")` on `test_a`.  However, `TestClassNamed::test_b` still ran and `PASSED`.

### `pip list`

```
PS > pip list
Package        Version
-------------- -------
atomicwrites   1.3.0
attrs          18.2.0
colorama       0.4.1
more-itertools 5.0.0
musicbrainzngs 0.6
mutagen        1.42.0
pip            19.0.1
pluggy         0.8.1
py             1.7.0
pytest         4.2.0
setuptools     40.7.2
six            1.12.0
wheel          0.32.3
```

### pytest version

From the example output,

    platform win32 -- Python 3.7.1, pytest-4.2.0, py-1.7.0, pluggy-0.8.1

**Comment by nicoddemus** [comment]
Hi,

Thanks for writing up!

It seems you should post this issue on the [pytest-dependency issue tracker](https://github.com/RKrahl/pytest-dependency/issues). This repository is meant for issues on the pytest core, not on plugins.

I'm closing this now, but feel free to follow with further questions.

**Comment by jtmoon79** [comment]
Reported in [pytest-dependency #30](https://github.com/RKrahl/pytest-dependency/issues/30#issue-407494038).
