### ISSUE TITLE
pytest's assertion rewriting causes pytest-xdist to not being uninstalled completely

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4755]
`pip uninstall pytest-xdist` leaves files behind when pytest has created files via its assertion rewriting:

```
./.venv/lib/python3.7/site-packages/xdist
├── __pycache__
│   ├── dsession.cpython-37-PYTEST.pyc
│   ├── looponfail.cpython-37-PYTEST.pyc
│   ├── newhooks.cpython-37-PYTEST.pyc
│   ├── plugin.cpython-37-PYTEST.pyc
│   ├── remote.cpython-37-PYTEST.pyc
│   ├── report.cpython-37-PYTEST.pyc
│   ├── _version.cpython-37-PYTEST.pyc
│   └── workermanage.cpython-37-PYTEST.pyc
└── scheduler
    └── __pycache__
        ├── each.cpython-37-PYTEST.pyc
        ├── load.cpython-37-PYTEST.pyc
        ├── loadfile.cpython-37-PYTEST.pyc
        └── loadscope.cpython-37-PYTEST.pyc

3 directories, 12 files
```

pip 18.1 (python 3.7.2)

I've noticed this, because `pytest.importorskip` will not skip it then.

**Comment by nicoddemus** [comment]
Weird, at first glance I don't think this is anything related to xdist in particular, but for every pytest plugin. 🤔

**Comment by blueyed** [comment]
Yeah, likely.

**Comment by asottile** [comment]
maybe we should take #4730 and default to `.pytest_cache/pycache` (even on older python versions) -- since pytest controls the pyc loading anyway there's nothing binding us to the source directories

**Comment by blueyed** [comment]
@asottile 
Sounds like a good plan.
