### ISSUE TITLE
Default Behavior Of Warnings

### ISSUE THREAD

**Issue by mikedh** [pytest-dev/pytest#4758]
When one runs:
`pytests tests`

The warnings system prints every single one of the 5000+ `DepreciationWarnings` internal to one of my dependencies (`networkx`) to the terminal. This means that the output needed to resolve failures is buried behind this output, and sometimes means the actual failures aren't visible because they fell off the back of the terminal buffer (before I re- run with `pytest -p no:warnings tests`)

I propose that the *default* behavior of pytest warnings is changed to the behavior of: 
`pytest -W default tests`

Which prints only the *first* instance of any warning, and suppresses any duplicate warnings after. It provides all the benefits of the warnings system, but doesn't print thousands of identical warnings. It's already titled `default`, I'm not entirely clear as to why just running pytest doesn't exhibit this behavior already. 

System details:
- pytest version 3.8.1.dev25+g2803eb9f
- Python 3.6 from conda-forge on Ubuntu 18.04

**Comment by nicoddemus** [comment]
Hi @mikedh,

Indeed you are right, this is a problem. Fortunately this has been fixed in pytest 4.2, could you please give it a try? Thanks|

**Comment by mikedh** [comment]
Awesome, thanks for fixing this! Upgraded and observed the new behavior.
