### ISSUE TITLE
investigate replacing theinternal lsoff with pytest-openfiles

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#4771]
astropy created https://github.com/astropy/pytest-openfiles/ which uses psutil and seems more portable than what we have in place

we should investigate if this holds up in detail

**Comment by blueyed** [comment]
Gave it a quick spin: it is not wrapping as much as the lsof plugin does currently, and likely should not I guess (since it is about user tests, and not pytest internals).

**Comment by RonnyPfannschmidt** [comment]
well done - its nice to have a more detailed assessment of the state

from my pov the use-case is the  same - so im going to keep tabs on it, perhaps enhance it when i return to active

**Comment by webknjaz** [comment]
> investigate replacing theinternal lsoff with pytest-openfiles

@RonnyPfannschmidt this is no longer possible:

> This repository has been archived by the owner on Jun 5, 2024. It is now read-only. You can check out [its forks](https://github.com/astropy/pytest-openfiles/forks).

*(https://github.com/astropy/pytest-openfiles/#important-retirement-roadmap)*

**Comment by webknjaz** [comment]
@obestwalter this is a close candidate FYI ^

**Comment by obestwalter** [comment]
Closing due to the project in question was retired.
