### ISSUE TITLE
Should this project contain/support a GitHub Action for pytest?

### ISSUE THREAD

**Issue by cclauss** [pytest-dev/pytest#4797]
Should this project contain the code for a simple yet flexible GitHub Action that allows repo maintainers to quickly add automated pytest testing on all pull requests submitted to their repos?

Putting that code into this repo or another pytest-dev repo will focus development efforts on a single, community-supported GitHub Action for pytest instead of a multitude of homegrown solutions.

Currently you must be in the GitHub Action beta to be able to use Actions.

https://github.com/cclauss/GitHub-Action-for-pytest

**Comment by RonnyPfannschmidt** [comment]
first i want to thank you for bringing this opportunity up

based on context and tooling i believe we should have a a own repository with actions that can integrate pytest on different terms

for one - many projects use tox, for the other - just running pytest does simply not even remotely cut it for any project that has grown a bit in complexity and dependencies

nonetheless i see a great chance to add different types of workflows and pytest could be a good example for a more elaborate pipeline as well

the key requirement here is that we need to take a careful look at what we provide how,
as providing a weak integration that cant life up to growing projects in future is very certain to cost many people painful amounts of time

as such i believe we need to have a bigger discussion to figure a minimal viable setup that will allow people to grow things with joy

**Comment by cclauss** [comment]
Agreed.  Another important dimension to consider is the version of Python that pytest is run on.

**Comment by gnikonorov** [comment]
Hey @RonnyPfannschmidt - this sounds like it could be interesting. Did we want to revive this as a RFC/project or do you think this is stale and shouldn't be prioritized at the current moment

**Comment by lithammer** [comment]
I think what would be more interesting is to detect execution inside a GitHub Action and then use a special output formatter that prints errors their [annotation](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-error-message) format.

Supposedly you can detect this via the `GITHUB_ACTIONS` and `GITHUB_WORFLOW` environment variables. This is something that's supported by [ansible-lint](https://github.com/ansible-community/ansible-lint#cicd) today, so I guess one could take a look at how they're doing it.

**Comment by RonnyPfannschmidt** [comment]
as of now i don't see the discussion happening, closing this as not planned due to band-with
