### ISSUE TITLE
Make `assertrepr_compare` public.

### ISSUE THREAD

**Issue by brunns** [pytest-dev/pytest#4806]
The `assertrepr_compare` function, in `_pytest.assertion.util`, could be very useful in contexts outsides pytest's assertions. Might you consider exposing it as part of pytests public API so other packages can make use of it?

**Comment by Zac-HD** [comment]
Very unlikely sorry, as the details are tied to lots of pytest internals and we would then have to maintain it.

Instead, I suggest that interested projects copy-paste out the relevant code, which is after all under an MIT license!

**Comment by brunns** [comment]
OK, thanks!
