### ISSUE TITLE
Using logger from pytest_runtest_logreport()

### ISSUE THREAD

**Issue by mitzkia** [pytest-dev/pytest#4810]
Hi, 

I have a following files with contents: 
I would expect that log message from pytest_runtest_logreport() also appears in `log-file.txt`.
As far as I know pytest_runtest_logreport() runs after the setup, call and teardown methods.

conftest.py
```
import logging
logger = logging.getLogger(__name__)

def pytest_runtest_setup(item):
    logger.info("logger - from setup")

def pytest_runtest_call(item):
    logger.info("logger - from call")

def pytest_runtest_teardown(item):
    logger.info("logger - from teardown")

def pytest_runtest_logreport(report):
    logger.info("logger - from logreport")
```

test_example.py
```
def test_example():
    assert False
```

starter command
```
python3 -m pytest --log-level=debug --log-file=log-file.txt -lvs test_example.py
```

log-file.txt content:
```
conftest.py                  5 INFO     logger - from setup
conftest.py                  8 INFO     logger - from call
conftest.py                 11 INFO     logger - from teardown
```

Thanks for the help.

**Comment by mitzkia** [comment]
If pytest is not supported currently this method, could it be a relevant fix/update?

**Comment by nicoddemus** [comment]
Hi @mitzkia,

Indeed it is a bug. We should be catching logging calls around `pytest_runtest_logreport`, similar to what we do for `pytest_runtest_logfinish` (for example):

https://github.com/pytest-dev/pytest/blob/bf6dcd64dc7c93c3f79e703781a178b56273035a/src/_pytest/logging.py#L565-L568

**Comment by mitzkia** [comment]
Hi @nicoddemus, 

Thank you for the answer. 
I did not know yet how hard this issue, but I will start to resolve it.

**Comment by nicoddemus** [comment]
Oh a PR would certainly be appreciated!

**Comment by mitzkia** [comment]
At first glance this will easy :)

**Comment by mitzkia** [comment]
Something started working :)

**Comment by mitzkia** [comment]
I think the PR will work (just saw something which seems to be work)

**Comment by mitzkia** [comment]
Related PR #4812
