### ISSUE TITLE
pytest collects and runs tests that name starts with `tests_`

### ISSUE THREAD

**Issue by sliwinski-milosz** [pytest-dev/pytest#4818]
If that is expected behaviour then [test discovery documentation](https://docs.pytest.org/en/latest/goodpractices.html#conventions-for-python-test-discovery) needs to be updated as it doesn't say anything about that feature.

`test.py`
```
def tests_something():
    assert True
```
Above `tests_something` function got collected by pytest and it ran it.

Tested on `pytest==4.3.0`

**Comment by RonnyPfannschmidt** [comment]
its in the sublist of the itemized list in the first paragraph

**Comment by sliwinski-milosz** [comment]
Sorry, I still can't see it. Are you talking about below part?

```
From those files, collect test items:
    * `test_` prefixed test functions or methods outside of class
    * `test_` prefixed test functions or methods inside `Test` prefixed test classes (without an `__init__` method)
```

I can't find part that says that `tests_*` are going to be collected as test items.
I can see that it is mentioned about `test_*`.

**Comment by RonnyPfannschmidt** [comment]
indeed, thanks  for pointing out the detail i missed

https://github.com/pytest-dev/pytest/blob/master/src/_pytest/python.py#L100 defaults it to just `test*`

**Comment by sliwinski-milosz** [comment]
Do you think this needs to be fixed in code or it is better to simply update documentation?

**Comment by RonnyPfannschmidt** [comment]
a documentation update is needed, a code fix would practically constitute a hard  to detect breaking change

**Comment by asottile** [comment]
the reason it is `test*` is to allow old-school camelCase `testThatSomethingDoesSomething` iirc
