### ISSUE TITLE
How to properly stop a run or perform "validations" 

### ISSUE THREAD

**Issue by david-fliguer-ws** [pytest-dev/pytest#4821]
Hi,

Let's say that we have some code in our conftest that performs a general setup for the whole run, if something fails during that process then I don't want to run the tests, which is the recommended way to deal with this ?

Call to pytest.exit ? Raise an error ?

If you can give an example indicating which is the best way and where (If needed) use try/catch then it would be really helpful 

Thanks and keep up the good work,

David

**Comment by nicoddemus** [comment]
`pytest.exit()` or `raise pytest.Interrupted` are both good options. 👍 

I'm closing this for now, but feel free to follow up with further questions.
