### ISSUE TITLE
Very slow test setup in pytest 4.2.0+

### ISSUE THREAD

**Issue by okuta** [pytest-dev/pytest#4824]
Chainer and CuPy project use pytest.

I found a performance degradation in a particular version.

I run  `pytest --setuponly tests/chainer_tests > /dev/null` command.

| pytest version | user time[sec] |
----|---- 
| 4.1.1                |             120.88 |
| 4.2.0                |            1872.78|

I think that it is probably the influence of #4091 .

My environment
Python 2.7.13

**Comment by blueyed** [comment]
@okuta 
It would be helpful if you could git-bisect it.

**Comment by niboshi** [comment]
I did bisect and 0f918b1a9dd14a2d046d19be6ec239e8e2df4cb2 in #4091 is indeed the commit that introduced the degradation.

**Comment by blueyed** [comment]
Interesting.  btw: I suspect this change to also cause (more general, subtle) problems with pytest-django, which was handling those test setups itself before (https://github.com/pytest-dev/pytest-django/issues/710).

**Comment by toslunar** [comment]
I have a small example to reproduce the issue.  `N=10000 pytest --collect-only test_a.py | tail` shows ~10s with pytest 4.1.1 and ~200s with pytest 6.1.1 in my environment.

`test_a.py`
```python
import os
import sys
import unittest


def parameterize(*params):
    def f(cls):
        assert issubclass(cls, unittest.TestCase)
        module = sys.modules[cls.__module__]
        for i, param in enumerate(params):
            name = f"{cls.__name__}_param_{i}"
            setattr(module, name, type(name, (cls,), param))
        # Remove original base class
        return None
    return f


N = int(os.environ["N"])


@parameterize(*[{"x": n} for n in range(N)])
class TestA(unittest.TestCase):

    def test_x(self):
        assert self.x != 3

    def test_y(self):
        pass

    def test_z(self):
        pass
```

The `parameterize` decorator in the example sets class attributes:
```
% N=10 pytest test_a.py --tb=no | cat
============================= test session starts ==============================
platform darwin -- Python 3.9.0, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/tos/Documents/tmp/20201023
collected 30 items

test_a.py .........F....................                                 [100%]

=========================== short test summary info ============================
FAILED test_a.py::TestA_param_3::test_x - AssertionError: assert 3 != 3
========================= 1 failed, 29 passed in 0.12s =========================
```
```
% N=10000 pytest --collect-only test_a.py | tail
    <UnitTestCase TestA_param_9998>
      <TestCaseFunction test_x>
      <TestCaseFunction test_y>
      <TestCaseFunction test_z>
    <UnitTestCase TestA_param_9999>
      <TestCaseFunction test_x>
      <TestCaseFunction test_y>
      <TestCaseFunction test_z>

====================== no tests ran in 215.37s (0:03:35) =======================
```

**Comment by bluetech** [comment]
Thanks @toslunar, this is helpful. The profile of this shows some interesting things, which I am looking at.
