### ISSUE TITLE
[Question] Easiest method of correlating global data when using xdist?

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#4825]
Hi, is there any simple means of correlating global data when using xdist -n to run on multiple cpu's?

For example, my use case is I run many tests on multiprocess using xdist, however each test stores its results, at the end of the run I want access to a full dict of {'test_case_id': 'test_case_result'}.

As far as I can see, every session scoped fixture is running on every process and my result data is coupled to the process, now obviously this is how multi process works, I know this - however, is there a preferred solution or pattern I can apply to correlate all the data at the end?

I also have a use case where I want to get meta data from tests before running any of them and prepare something once before everything happens (again challenging on multi process, due to the forked memory clone)

Any advice in how to best manage this and keep the good parallelisation benefits?

**Comment by nicoddemus** [comment]
Hi @symonk,

When do you need access to the global dict? 

One way to communicate back to the master node is through files. You can make the master node create a temporary directory during `pytest_configure` and add it to `config.workerinput`. Then workers can access `config.workerinput` and write the required data to a filename, probably using `PYTEST_XDIST_WORKER` to generate a unique filename.

**Comment by symonk** [comment]
This is exactly what we went with in the end, using files to control process flow and waiting etc.  the config.workerinput seems interesting.  We also are going to write results on a per test to a shared file, and then handling API posting of such data as a post-testing stage, possibly even through jenkins.  Thanks!
