### ISSUE TITLE
Emit warnings on use of unknown marks

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#4826]
One of the most common problems I see, and help debug, is typos in `@pytest.mark.whatever` decorators.  Just recently we've had #4639 and #4814, and I've read three sets of unrelated docs in the last week that explicitly point out the spelling of `mark.parametrize` (not `parameterize`!).

The `--strict` argument helps, but is clearly insufficient by default.  On the other hand, it can't be an error until a major version bump.  

Happily, there is a standard middle ground: warnings!  I therefore propose to emit a warning every time an unknown name is used as an attribute of `pytest.mark`.  The message should include how to register the mark, why unregistered marks are problematic, and note that this warning may become an error in a future version of pytest.

Unless there are major objections to this plan, I'll try for an implementation over the weekend.

**Comment by blueyed** [comment]
@Zac-HD 
Sounds good, looking forward to a PR.

**Comment by RonnyPfannschmidt** [comment]
short opinion on this one, i believe we should migrate to warnings and deprecate `--strict`

if necessary i'm going to elaborate deeper when i'm back to active

**Comment by Zac-HD** [comment]
Here's a quick prototype: https://github.com/pytest-dev/pytest/compare/master...Zac-HD:warn-unknown-marks

Roughly what you had in mind?  Any feedback would be great!

**Comment by RonnyPfannschmidt** [comment]
@Zac-HD as  far as i can tell its broken due to adding more caching behaviour than warranted

**Comment by Zac-HD** [comment]
Ah, right - I had assumed that the config object was much more static that it really was.  Now fixed, I think, so another quick review would be great :smile:

**Comment by blueyed** [comment]
@Zac-HD 
A (draft) PR would be better, since you could comment on the code then.

As for deprecating `--strict`: I think it could be kepts still, and be used for other things in the future also.  It is not `--fail-on-unknown-marks` after all.

**Comment by Zac-HD** [comment]
Closed by #4935.

**Comment by 1313e** [comment]
In v4.5.0, this now emits warnings about 'unknown marks' that are perfectly valid and known.
For example, using the `pytest_pep8` plugin will emit that warning about `pytest.mark.pep8`, even though it is known and can be accessed perfectly fine.

**Comment by nicoddemus** [comment]
Hi @1313e, thanks for writing.

You mean `pytest_pep8` does register the `pep8` mark and pytest still complains about it being unknown? Then that's certainly a bug.

**Comment by 1313e** [comment]
> Hi @1313e, thanks for writing.
> 
> You mean `pytest_pep8` does register the `pep8` mark and pytest still complains about it being unknown? Then that's certainly a bug.

Correct.

**Comment by nicoddemus** [comment]
@1313e 

>> You mean pytest_pep8 does register the pep8 mark and pytest still complains about it being unknown? 

> Correct.

Took a quick look and that does not seem to be the case:

https://bitbucket.org/pytest-dev/pytest-pep8/src/44ddb3739f0f892fc0029d5d809496ec5ef24f28/pytest_pep8.py#lines-12:21

The `pep8` mark should be registered like shown [here](https://docs.pytest.org/en/latest/mark.html#registering-marks).

**Comment by Zac-HD** [comment]
> The pep8 mark should be registered like shown here.

Note that this is important to get the correct command-line help, as well as to avoid the new warning!

**Comment by 1313e** [comment]
That might be, but it still raises the warning.
So, apparently, it acts as if it is not registered, while it does work perfectly fine.

**Comment by RonnyPfannschmidt** [comment]
the point of the warning is to tell you there is something missing without actually breaking the world
so its not perfectly fine

**Comment by 1313e** [comment]
> the point of the warning is to tell you there is something missing without actually breaking the world
> so its not perfectly fine

Uhm, thanks for making my point I guess?

**Comment by blueyed** [comment]
@1313e 
The problem is that the mark is _not_ registered apparently, but only used.  This emits a warning, since it should get registered.

**Comment by nicoddemus** [comment]
@1313e 

Just to complement the other answers:

1. A plugin can *use* a mark (like `pytest-pep8` does) to drive some behavior;
1. A plugin *should* register the mark during their initialization; this shows the mark with `pytest --help` and lets pytest know the mark exists.
1. A user can *use* a mark in a test with the `@pytest.mark` decorator.

What is happening that `pytest-pep8` uses the mark (1), users can mark tests with that mark (3), but the mark itself is not *registered* by the plugin (2).

The warning is emitted because typos in marks are a common source of mistakes: if a user mistypes `ppe8`, then the plugin won't work as expected, leading to confusing and error reports. The new warning prevents that.

This causes a small pain now, but will prevent a lot of headaches in the future; plugins will now register their marks from the get-go, and mistypes will be immediately obvious. 

Reports about the unknown marks in the respective plugin bug trackers are welcome, so plugin authors can be made aware of the missing registration. 👍

**Comment by 1313e** [comment]
@nicoddemus Alright, but the mark itself does show up when executing `pytest --help`, so it still looks to me like it was registered properly.
Because of that, I am not sure whether I should report the 'warning' here or over at the repo for `pytest_pep8`.

**Comment by nicoddemus** [comment]
@1313e I see, thanks. I cannot reproduce this thought, I only see the builtin markers with `pytest-pep8` installed:

```
λ pip list
Package        Version
-------------- -------
apipkg         1.5
atomicwrites   1.3.0
attrs          19.1.0
colorama       0.4.1
execnet        1.6.0
more-itertools 7.0.0
pep8           1.7.1
pip            19.0.3
pluggy         0.11.0
py             1.8.0
pytest         4.5.0
pytest-cache   1.0
pytest-pep8    1.0.6
setuptools     40.8.0
six            1.12.0
wcwidth        0.1.7

λ pytest --markers
@pytest.mark.filterwarnings(warning): add a warning filter to the given test. see https://docs.pytest.org/en/latest/warnings.html#pytest-mark-filterwarnings

@pytest.mark.skip(reason=None): skip the given test function with an optional reason. Example: skip(reason="no way of currently testing this") skips the test.

@pytest.mark.skipif(condition): skip the given test function if eval(condition) results in a True value.  Evaluation happens within the module global context. Example: skipif('sys.platform == "win32"') skips the test if we are on the win32 platform. see https://docs.pytest.org/en/latest/skipping.html

@pytest.mark.xfail(condition, reason=None, run=True, raises=None, strict=False): mark the test function as an expected failure if eval(condition) has a True value. Optionally specify a reason for better reporting and run=False if you don't even want to execute the test function. If only specific exception(s) are expected, you can list them in raises, and if the test fails in other ways, it will be reported as a true failure. See https://docs.pytest.org/en/latest/skipping.html

@pytest.mark.parametrize(argnames, argvalues): call a test function multiple times passing in different arguments in turn. argvalues generally needs to be a list of values if argnames specifies only one name or a list of tuples of values if argnames specifies multiple names. Example: @parametrize('arg1', [1,2]) would lead to two calls of the decorated test function, one with arg1=1 and another with arg1=2.see https://docs.pytest.org/en/latest/parametrize.html for more info and examples.

@pytest.mark.usefixtures(fixturename1, fixturename2, ...): mark tests as needing all of the specified fixtures. see https://docs.pytest.org/en/latest/fixture.html#usefixtures

@pytest.mark.tryfirst: mark a hook implementation function such that the plugin machinery will try to call it first/as early as possible.

@pytest.mark.trylast: mark a hook implementation function such that the plugin machinery will try to call it last/as late as possible.
```

Can you post a reproducible example?

**Comment by 1313e** [comment]
Well, yeah, the markers show up when installed, but the error is emitted anyways.

**Comment by 1313e** [comment]
@nicoddemus Yeah, for me, it does not show up with `pytest --markers` either, but it does show up in the `pytest --help` list.
However, I also never use it as a marker, but rather as an optional argument when executing pytest.
I guess however that that simply adds the marker to every single test-function.

Alright, I guess I will have to open an issue about it at the `pytest_pep8` repo?

**Comment by nicoddemus** [comment]
> I guess however that that simply adds the marker to every single test-function.

Ahh it seems you are correct:

https://bitbucket.org/pytest-dev/pytest-pep8/src/44ddb3739f0f892fc0029d5d809496ec5ef24f28/pytest_pep8.py#lines-56

Well that explains everything now, thanks for the perseverance. 

> Alright, I guess I will have to open an issue about it at the pytest_pep8 repo?

Yes, please and thank you! 👍
