### ISSUE TITLE
Warn if a particular mark has already been applied to the test

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#4827]
Occasionally, I see people using `@pytest.mark.hypothesis` to distinguish tests using Hypothesis.  Apparently they've missed that the Hypothesis pytest plugin does this automatically!

On the surface this is a trivial inefficiency, but there's a latent problem here too: if users don't realise that they're doubling up on a particular mark, they probably don't know which tests have already had that mark applied.  When selecting tests by markers, they are therefore likely to include tests that they had intended to exclude.  This could even happen entirely automatically due to plugins, in which case it should be easier for someone to notice and end the name collision.

We probably don't need to make this an error, but a emitting a warning seems appropriate - it can be silenced, lived with, or made into an error as preferred by the end-user.

**Comment by RonnyPfannschmidt** [comment]
this is strongly dependent on the actual mark, for example `parameterize` must be used multiple times

as such the implementer of auto-marking should pick the behaviour

**Comment by nicoddemus** [comment]
> as such the implementer of auto-marking should pick the behaviour

Currently marks can be applied multiple times, and it is not clear how/if we could somehow configure each mark with the behavior to warn when double-marking.

I agree, I think this is the best solution: hypothesis itself could check if `@pytest.mark.hypothesis` has already been applied to a test function and issue an warning as appropriate.

Should we close this then?

**Comment by Zac-HD** [comment]
> I agree, I think this is the best solution: hypothesis itself could check if `@pytest.mark.hypothesis` has already been applied to a test function and issue an warning as appropriate.  Should we close this then?

Sounds good!
