### ISSUE TITLE
How to do only test discovery using API?

### ISSUE THREAD

**Issue by ericsnowcurrently** [pytest-dev/pytest#4850]
In the project I work on, we've been running `python3 -m pytest --collect-only ...` and then parsing the output into our own data structure.  However, that is somewhat fragile.  We'd rather use the public API to do the same thing, with the caveat that we still need to support user-supplied command-line arguments.  The main objective is to convert the collected tests into our custom data structure.

I tried doing this using `pytest.main()`, but it isn't clear what the plugin needs to implement (or even if that's the right way to go).  I also looked into using other parts of the API, but couldn't tell what to call, how to get the same command-line parsing support, or even if the API provides everything `pytest.main()` does.

So, what is the right way to do this?  Thanks!

**Comment by DonJayamanne** [comment]
How about:
```python
import pytest
class MyPlugin(object):
    def pytest_collection_modifyitems(sessino, config, items):
        print(items, "items from collected list")
    def pytest_collection_finish(self, session):
        print(list(session.items), "items from session")

pytest.main(["-v", "tests", "--collect-only"], plugins=[MyPlugin()])
```

**Comment by nicoddemus** [comment]
@ericsnowcurrently if you calling `pytest.main` is acceptable, @DonJayamanne's suggestion is on point: it will use the same hooks that pytest itself and plugins use. 👍

**Comment by ericsnowcurrently** [comment]
How do I keep it from printing anything out?

**Comment by nicoddemus** [comment]
Passing `-pno:terminal` so the terminal plugin doesn't load should do the trick.

**Comment by ericsnowcurrently** [comment]
Thanks!

**Comment by nicoddemus** [comment]
Great, closing now but feel free to follow with further questions.
