### ISSUE TITLE
AttributeError: module 'py' has no attribute 'path'

### ISSUE THREAD

**Issue by elcaiseri** [pytest-dev/pytest#4889]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [x] `pip list` of the virtual environment you are using
- [x] pytest and operating system versions
- [x] Minimal example if possible

**Comment by blueyed** [comment]
Please provide more information, not just click the checkboxes.

Please re-open then.
