### ISSUE TITLE
parser addoption does not have strict match for command line argument

### ISSUE THREAD

**Issue by balexander85** [pytest-dev/pytest#4891]
The parser.addoption does not do a strict match on the command line argument passed.

For the given example in documentation https://docs.pytest.org/en/latest/example/simple.html 
```
# content of conftest.py
import pytest


def pytest_addoption(parser):
    parser.addoption(
        "--cmdopt", action="store", default="type1", help="my option: type1 or type2"
    )


@pytest.fixture
def cmdopt(request):
    return request.config.getoption("--cmdopt")
```
If a user passes `--cmdop=type2` no error is raised and the command line arg (cmdop) is assumed as (cmdopt). It appears that the command line does a matching like `.startswith` because if I change arg to --cmd it works and if I use --cmdt I get expected error `error: unrecognized arguments: --cmdt=type2`

I created fresh virtualenv with pyenv (Python 3.6.1) and installed pytest here are my packages:
atomicwrites (1.3.0)
attrs (19.1.0)
more-itertools (6.0.0)
pip (9.0.1)
pluggy (0.9.0)
py (1.8.0)
pytest (4.3.0)
setuptools (28.8.0)
six (1.12.0)

**Comment by asottile** [comment]
Indeed, pytest options are prefix-matched (like most standard gnu tools)

```console
$ ls a*
'a b.py
$ ls --lit a*  # short for `ls --literal` / `ls -l`
a b.py'
```

**Comment by balexander85** [comment]
Ahh I did not know that.
