### ISSUE TITLE
Some plugin hooks missing from docs

### ISSUE THREAD

**Issue by altendky** [pytest-dev/pytest#4896]
The hooks listed below are not listed in the generated documentation.  I have low confidence I'm organizing them correctly but I'll submit a PR in case that eases discussion of where they do belong.

- `pytest_plugin_registered`
- `pytest_make_collect_report`
- `pytest_pycollect_makemodule`
- `pytest_collection_finish`
- `pytest_pyfunc_call`

**Comment by Tadaboody** [comment]
Is there still work tbd on this or was this closed by #4897?

**Comment by altendky** [comment]
@Tadaboody, thanks for the bump.
