### ISSUE TITLE
Fixtures won't work on first test call.

### ISSUE THREAD

**Issue by lvieirajr** [pytest-dev/pytest#4899]
I have the following fixture (on my `conftest.py` that lives on my top-level test folder):

```python
@fixture
def mock_app_exists():
    with mocker.patch(
        "authentication.serializers.app_validation.App.objects.filter",
        return_value=MagicMock(exists=(MagicMock(return_value=True))),
    ):
        yield
```
PS: This is the only fixture I have on my codebase.

One of the tests for example is:

```python
def test_when_valid_body_sent_returns_200(self, mocker, mock_app_exists):
    response = self.client.post(
		"/login/", 
		{"username": "test@example.com", "password": "123"}, 
		format="json"
	)
    assert response.status_code == 200
```

When I run my test suite, the first test to use the fixture always fails, because that path is not actually mocked, but the following tests all pass (even if I get another test to run first, that one will start failing and the other one will now pass). This also happens if I only run one test at a time, any test you chose that uses this fixture fails.

I'm running `pytest==4.1.1` with `pytest-mock==1.10.1`
This has been tested to happen both on my MAC OS and on circle-ci.

**Comment by nicoddemus** [comment]
Hi @lvieirajr,  

> the first test to use the fixture always fails, because that path is not actually mocked

I think we need more information, my guess is that the function is being called before the mock is being applied... can you provide more code with that?

**Comment by lvieirajr** [comment]
Hey @nicoddemus,
I don't know exactly what other piece of code I could provide here to give you more info. I tried debugging already and the fixture is called right before the test.

<img width="589" alt="Screen Shot 2019-03-09 at 8 56 47 AM" src="https://user-images.githubusercontent.com/283394/54074631-cfed6c00-4249-11e9-960c-4d48aefbe447.png">

In this screenshot you can see the execution order, "Before test" is right inside the mock and before the yield on the fixture, "After test" is after the yield and "Inside test" is where inside the test before the call is executed.

**Comment by nicoddemus** [comment]
As I suspected, the fixture is being called in the correct order than (otherwise pytest itself would be broken beyond recognition).

Not sure what else I can suggest to help you debug this, sorry. 😕

**Comment by nicoddemus** [comment]
Closing for now. Will be happy to reopen this if more information comes to light. 👍
