### ISSUE TITLE
Need infos : Thread & Pytest non python tests

### ISSUE THREAD

**Issue by FanatoniQ** [pytest-dev/pytest#4904]
# Goal

___This is not a bug, but a request for informations.___

I am using ___pytest 4.3___.
I am trying to use the python threading module, to have a thread running before collecting the test files with __pytest_collect_file__ (since my tests all recquire the thread to run).
My thread is a server (a class inheriting from threading.Thread) I want to test, I am therefore calling subprocess from within the thread.
I am using ___non python tests___ with json as shown [here](https://docs.pytest.org/en/latest/example/nonpython.html).

# Issue

I can't figure out how to correctly run the thread when pytest starts...
I tried autose Fixtures but it didn't do the trick with non python tests.
I also tried using pytest_sessionstart but it gave me this error : __Group Argument must be None for now__ as shown below :

![pytest_treads](https://user-images.githubusercontent.com/12274756/54090888-505eba80-4379-11e9-8aa1-bdd44becf8c1.PNG)

Could you please indicate how i should proceed.

Sincerly yours

**Comment by RonnyPfannschmidt** [comment]
you passed self to `super(MyClass, self).__init__` - which is wrong and not a pytest issue

**Comment by FanatoniQ** [comment]
Thanks for the quick answer !

Creating a subclass of threading.Thread for my thread or using :

```python3
thread = threading.Thread(target=(start_server), args=(conf_file,))
thread.daemon = True
thread.start()
```
inside pytest_sessionstart(session) does not do the trick.

The problem is not how the thread is created but how pytest and such a thread interacts with each others.
With non python tests, though a fixture marked as autoused I manage to have a thread but not with non python tests.

How can I achieve a daemon thread with non python test in pytest, is it even possible ?

**Comment by RonnyPfannschmidt** [comment]
i believe currently the only way to do it is to import internal  apis of pytest

@nicoddemus might know more details
