### ISSUE TITLE
Fixture naming convention

### ISSUE THREAD

**Issue by ikonst** [pytest-dev/pytest#4910]
Consider this test file:
```py
@pytest.fixture
def animal():
   return 'Cat'

def test_pet(animal):
    ...
```

This has two problems:
1. To a naive static analyzer it looks like the `animal` parameter shadows a global.
2. If you forget to request the fixture, the fixture's name confusingly still references a symbol, but that symbol is the fixture function itself:
    ```py
    def test_pet():
      assert animal == 'Cat'
    ```

One option is to explicitly name your fixtures like so:
```py
@pytest.fixture(name='animal')
def animal_fixture():
    return 'Cat'
```

If you find the `name` parameter to be tedious or non-DRY, you could implement (untested but you get the gist):
```py
def fancy_fixture(*args, **kwargs):
    def wrapper(f):
        name = f.__name__
        if name.endswith('_fixture'):
          name = name[:-len('_fixture)]
        kwargs.setdefault('name', name)
        return pytest.fixture(*args, **kwargs)(f)

    return wrapper
```

What if we added this behavior to built-in `pytest.fixture`?

**Comment by nicoddemus** [comment]
Hi @ikonst,

Thanks for the suggestion, but I particularly am not very found of the idea: seems to implicit. I have seen people complaining that the fixture being magically turned into a parameter of test functions "too magical", and adding this implicit behavior would add to the problem.

**Comment by ikonst** [comment]
Another option is to keep the fixtures in a paired file, i.e. `pet_tests.py` paired with `pet_fixtures.py`. I recall my proposal of introducing implicit loading of `fixtures/*` to be shot down, and I expect such a proposal will be shot down too, but perhaps it's doable with a plugin.

**Comment by nicoddemus** [comment]
Hi @ikonst,

Indeed both your proposals are doable as plugins. 

Your first suggestion should be simpler, as it is just a wrapper decorator around `pytest.fixture`:

```python
from fancy_fixture import fancy_fixture

@fancy_fixture(name='animal')
def animal_fixture():
    return 'Cat'
```

I'm not sure the second proposal is that useful though, you can already obtain the same effect using `conftests.py`... but it should be doable as a plugin, albeit it will be more complex because it will need to muck with the internals, as the fixture loading code is not well exposed I'm afraid.

**Comment by ikonst** [comment]
My previous interest in loading `fixtures/*` stemmed from root conftest.py files growing out of proportion. I suppose that for conftest.py files in subdirectories, this wouldn't be as bad.

Generally everything is doable but not everything is worth doing, especially when it comes to proposing new conventions. Opt-in plugins are a good way to test such things - let the public (dis)interest decide.

**Comment by nicoddemus** [comment]
> Generally everything is doable but not everything is worth doing, especially when it comes to proposing new conventions. Opt-in plugins are a good way to test such things

Agreed. 😁 

Want to keep this open in case someone picks it up, or can we close this?

**Comment by nicoddemus** [comment]
Thanks!
