### ISSUE TITLE
pytest.skip inside doctests does not work (UnexpectedException)

### ISSUE THREAD

**Issue by tkf** [pytest-dev/pytest#4911]
[`pytest.skip` docstring](https://docs.pytest.org/en/latest/reference.html#pytest-skip) says "This function should be called only during testing (setup, call or teardown)".  However, calling `pytest.skip` inside a doctest is counted as a failure:

```console
$ ls
env  test.txt

$ cat test.txt
>>> import pytest
>>> pytest.skip("Skip doctest")

$ env/bin/pytest
================== test session starts ==================
platform linux -- Python 3.7.0, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: /tmp/tmp.YVVwv7GVVo, inifile:
collected 1 item

test.txt F                                        [100%]

======================= FAILURES ========================
__________________ [doctest] test.txt ___________________
001 >>> import pytest
002 >>> pytest.skip("Skip doctest")
UNEXPECTED EXCEPTION: Skip doctest
Traceback (most recent call last):

  File "/usr/lib64/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest test.txt[1]>", line 1, in <module>

  File "/tmp/tmp.YVVwv7GVVo/env/lib/python3.7/site-packages/_pytest/outcomes.py", line 98, in skip
    raise Skipped(msg=msg, allow_module_level=allow_module_level)

Skipped: Skip doctest

/tmp/tmp.YVVwv7GVVo/test.txt:2: UnexpectedException
=============== 1 failed in 0.01 seconds ================
```

Would it be possible to make `pytest.skip` work inside doctests?

<details>
 <summary>System information:</summary>

```console
$ env/bin/pip list
Package        Version
-------------- -------
atomicwrites   1.3.0
attrs          19.1.0
more-itertools 6.0.0
pip            19.0.3
pluggy         0.9.0
py             1.8.0
pytest         4.3.0
setuptools     40.8.0
six            1.12.0
wheel          0.33.1

$ env/bin/pytest --version
This is pytest version 4.3.0, imported from /tmp/tmp.YVVwv7GVVo/env/lib/python3.7/site-packages/pytest.py

$ uname -a
Linux tkf-xps 4.14.61-1-lts #1 SMP Mon Aug 6 21:07:39 CEST 2018 x86_64 GNU/Linux

$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

</details>

**Comment by nicoddemus** [comment]
Hi @tkf,

To skip doctests you should use [the skip directive](https://docs.python.org/3/library/doctest.html#doctest.SKIP), so your tests don't explicitly depend on pytest. I'm not sure supporting `pytest.skip()` inside doctests is something we want given that we have a builtin alternative.

I'm closing this for now, but please feel free to follow up with further questions. 👍

**Comment by tkf** [comment]
Sorry, I should have mentioned the motivation clearly. I know `# doctest: +SKIP` but this only works if you statically know that some doctest should be skipped.  Sometimes it is impossible.  An example closer to the real use-case is something like this:

```rst
.. check if the following doctest should be run (and hide it in Sphinx)
   >>> import pytest
   >>> if should_skip():
   ...     pytest.skip("skipping the doctest below since it's not going to work.")

>>> some_doctest_code_here
```

I believe `SKIP` flag cannot be used for this purpose.  Is there a way to conditionally/dynamically skip doctest?  If not, could you re-open the issue?

**Comment by nicoddemus** [comment]
Hi @tkf,

Indeed there isn't. I'm don't think it would be too hard to implement `skip` in doctests.

**Comment by tkf** [comment]
@nicoddemus I appreciate that you reconsider this.  I made PR #4927 which seems to work as I expected.

**Comment by tkf** [comment]
#4927 implemented this issue
