### ISSUE TITLE
How does pytest accomplish terminal colors?

### ISSUE THREAD

**Issue by giampaolo** [pytest-dev/pytest#4940]
Hello. This is a help request rather than a bug so sorry in advance if this is not appropriate. 
I was looking into adding basic colors to unittest result/output, possibly without depending from external libs. I managed to do this on POSIX (bash at least) but still didn't on Windows (despite I found some working recipes I could use but, am not sure how reliable they are e.g. on Power Shell). Basically I was curious to know how pytest achieves colors and if there is a recommended way to do it. 

Thanks in advance.

**Comment by RonnyPfannschmidt** [comment]
colorama

**Comment by giampaolo** [comment]
Thanks.
