### ISSUE TITLE
Working with non python tests and pytest-repeat compatibility issue

### ISSUE THREAD

**Issue by davidemoro** [pytest-dev/pytest#4973]
If you implement a non python test following the example on official documentation (https://docs.pytest.org/en/latest/example/nonpython.html) you will get an error using the ``pytest-repeat``'s ``--count`` option:
```
request = <SubRequest '__pytest_repeat_step_number' for <YAMLItem test_single.yml>>

    @pytest.fixture(autouse=True)
    def __pytest_repeat_step_number(request):
        if request.config.option.count > 1:
            try:
                return request.param
            except AttributeError:
>               if issubclass(request.cls, TestCase):
E               TypeError: issubclass() arg 1 must be a class
```

for every past and present ``pytest``/``pytest-repeat`` version and every ``pytest-repeat`` version (at this time of writing ``pytest==4.3.1`` and ``pytest-repeat==0.8.0``). pytest-play users (https://github.com/pytest-dev/pytest-play/) are affected too since it is based on non python tests.

This error occurs with ``pytest.Item`` only, all is fine using a regular python based test based on ``pytest.Function`` instead.

``_compute_fixture_value`` in ``_pytest.fixtures.FixtureRequest`` generates a ``SubRequest`` with no ``param`` attribute basically because there is no ``callspec`` attribute (a ``_pytest.python.CallSpec2`` instance) on the ``pytest.Item`` instance.
In addition as far as I know a role in this scenario is played by ``_pytest.python.Metafunc`` that seems heavily specific to python based tests (see the ``FunctionDefinition`` assertion).

I'm wondering if it would be possible to define in pytest a generic technology independent abstraction layer that will unify the internal test lifecycle so that everything will works fine implementing a generic interface. I can imagine it might be challenging but there are also some benefits in terms of refactored internal api and fixtures management. Is there any future plan for that?

Alternatively is there a hook that doesn't involve ugly hacks on non python plugin side trying to emulate a callspec-like implementation making things compatible with the current engine?

Thanks in advance!

**Comment by nicoddemus** [comment]
Hi @davidemoro,

Thanks for writing.

You are correct in your assumptions, and I agree the internals are not ideal. The internal mechanisms have grown organically over the years, and are in a dire need of refactoring.

@RonnyPfannschmidt and I have been talking about rewriting the fixture and internal calls in a way that is simpler to understand and more extensible. We don't have any specs or detailed ideas in writing, this is just something that we plan to eventually tackle. @RonnyPfannschmidt is taking a couple of months to recharge his batteries, I suppose we will get to those discussions when he does. You are welcome to participate, as is anyone who's interested. 👍

**Comment by davidemoro** [comment]
Hi @nicoddemus,

thanks for the answer.

I was able to get non python tests working fine with pytest-repeat on a
private branch and I am going to share the workaround code in the next days!

During my pytest hacks I tried to figure out how to make life easier for a
framework user. Python based tests could be considered as a specialization
of non-python tests, so if you start designing an easier to use API for
non-python tests first (e.g., a generic base layer for metafunc, specs) I
guess you'll get a better experience for python based tests too as a
result. But I still have a too limited pytest internals knowledge, I'm just
sharing my first thoughts as a framework user or plugin developer.

**Comment by nicoddemus** [comment]
Great. You are absolutely correct on the approach of making a generic metafunc/specs layer and specialize that for Python tests. Looking forward to see what you came up with!

**Comment by davidemoro** [comment]
This is the workaround that let you make non python tests compatible with pytest-repeat emulating 
python based tests (I think this is the quickest way to do it at this time of writing): https://github.com/pytest-dev/pytest-play/pull/81/files

**Comment by Zac-HD** [comment]
Thanks so much @davidemoro for your write-up and pull request!

I'm going to close this issue now because I don't think we need any further action.

**Comment by davidemoro** [comment]
Thanks @Zac-HD!
