### ISSUE TITLE
stepwise: also remember last successful test for continuation

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#4992]
I think it would be useful if the stepwise plugin would also take into account successful tests.

A use case is running all tests, Ctrl-C'ing them (KeyboardInterrupt), but then wanting to continue from where they stopped.  For this `session.exitstatus = 2` (interrupted) could be used in `pytest_sessionfinish`.

**Comment by graingert** [comment]
@blueyed I think stepwise needs to remember all tests and their state, "passed", "failed", "pending"

This way it can handle:
* the failed test being renamed
* new tests added "in front" of the step-failing test
* xdist tests failing "in front" of the step-failing test, and the step failing test failing after a pending test

**Comment by graingert** [comment]
"--lf" and "--sw" should share the same database
