### ISSUE TITLE
pytest_runtest_teardown retrieve item status

### ISSUE THREAD

**Issue by AlexanderBerx** [pytest-dev/pytest#4997]
Hi, 

I've a question in regards to test teardowns. I've added the function "pytest_runtest_teardown" to my conftest.py  as referenced from [here](https://docs.pytest.org/en/latest/_modules/_pytest/hookspec.html#pytest_runtest_teardown). My question is, is there a way to retrieve from the item whether the test has failed or succeeded? The reason I'm asking is that I want to trigger a function every time a test fails.

My apologies if this was already posted/asked before but I couldn't find an anwser to it.

Thanks,
Alexander

**Comment by nicoddemus** [comment]
Hi @AlexanderBerx,

You are better off using [`pytest_runtest_logreport`](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_runtest_logreport) for that. You can detect if a test passed/failed by examining `report.when` and `report.outcome`.

**Comment by AlexanderBerx** [comment]
Hi @nicoddemus,

That does exactly what I'm looking for. Thanks a lot!

Cheers,
Alexander
