### ISSUE TITLE
Collection by mark

### ISSUE THREAD

**Issue by nadavishe** [pytest-dev/pytest#5001]
Hi,

I'm trying to run tests inside of main test folder with many sub-folders using -m key
I mark tests with different marks and i need to run only tests with selected mark
All is good, but the problem arise when some test (even marked by another mark) is can't be compiled or something wrong else, collection process report me about error inside this test, even i don't interesting in it
How can i prevent that?
Thanks

**Comment by blueyed** [comment]
Can you provide the/some output?
If I understand it correctly you are seeing a collection error?

**Comment by nadavishe** [comment]
C:\AT_Space\myTests>pytest -m Test1
============================= test session starts =============================
platform win32 -- Python 3.6.3, pytest-4.3.0, py-1.5.2, pluggy-0.8.1
metadata: {'Python': '3.6.3', 'Platform': 'Windows-7-6.1.7601-SP1', 'Packages': {'pytest': '4.3.0', 'py': '1.5.2', 'pluggy': '0.8.1'}, 'Plugins': {'metadata': '
1.5.1', 'ordering': '0.6', 'html': '1.19.0'}}
rootdir: C:\AT_Space\myTests, inifile:
plugins: metadata-1.5.1, ordering-0.6, html-1.19.0
collected 4 items / 1 errors / 2 deselected / 1 selected

=================================== ERRORS ====================================
__________ ERROR collecting FolderWithWrongTest/test_FolderWrong.py ___________
ImportError while importing test module 'C:\AT_Space\myTests\FolderWithWrongTest\test_FolderWrong.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
FolderWithWrongTest\test_FolderWrong.py:2: in <module>
    import blabla
E   ModuleNotFoundError: No module named 'blabla'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!
==================== 2 deselected, 1 error in 0.20 seconds ====================

**Comment by nadavishe** [comment]
Attached example of such scenario: there is folder where some file import not existing module

[myTests.zip](https://github.com/pytest-dev/pytest/files/3008051/myTests.zip)

**Comment by nadavishe** [comment]
I closed this issue by mistake, so i reopened it again

**Comment by blueyed** [comment]
I see.. there is no way to work around this AFAIK - and I am not sure if an option like `--ignore-collect-errors` makes sense; after all you might end up with missing tests (that would have the mark) etc.

**Comment by nadavishe** [comment]
No, i don't want option --ignore-collect-errors, because it will not warn about errors in tests
But, i need to test only marked tests, so why i need to know about errors in tests that are not marked with appropriate mark?

**Comment by blueyed** [comment]
pytest needs to collect all tests first to figure out which ones have the mark.

I suggest selecting tests by file name/paths additionally, e.g. if you know that marks are only in certain files anyway.

**Comment by nicoddemus** [comment]
@blueyed's solution is the simplest one.

Another solution (which might or might not work for your specific case) is to automatically attach marks on the tests, possibly using the `pytest_collection_modifyitems` hook to attach marks based on some criteria.

**Comment by nadavishe** [comment]
Hi, nicodemmus
How dynamic marking of tests will help me to prevent errors during collection?
I don't understand your solution

**Comment by nicoddemus** [comment]
Oh sorry, I missed the gist of the problem that it is collection errors you are having.

Then the only solution that comes to mind is using @blueyed's.

**Comment by Sup3rGeo** [comment]
@nadavishe You want pytest not to look into `test_FolderWrong.py` module, but he *should* do it because this file may contain a test inside marked `Test1`. 

How can it know beforehand that he shouldn't look into that file?

**Comment by nadavishe** [comment]
Pytest can know about it when it create the report, because it can compare the failed test with mark

**Comment by nicoddemus** [comment]
> Pytest can know about it when it create the report, because it can compare the failed test with mark

No it cannot, the collection *failed*, so it couldn't obtain a module object from the file, much less a test and mark.
