### ISSUE TITLE
Docker API Connection refused when running pytest

### ISSUE THREAD

**Issue by vkartik97** [pytest-dev/pytest#5021]
I am working on an application where I am using Docker to push and image:
```python
    .
    .
    .
    docker_client = docker.from_env()
    a = docker_client.containers.list()                 #Error on this line
```
I am getting 
```
<Result ConnectionError('Connection refused: GET http+docker://localhost/v1.35/containers/json?limit=-1&all=0&size=0&trunc_cmd=0',)>.exit_code
```
 when running 
```sh
$ py.test -s --cov . --cov-config .coveragerc
```
but is working perfectly when executing using `$ python file.py`

**Comment by nicoddemus** [comment]
Hi @vkartik97,

Not sure, nor pytest or pytest-cov try to access remote servers. Can you provide a reproducible example?

**Comment by vkartik97** [comment]
- Line causing error: 
   - (Debug statement)https://github.com/vkartik97/evalai-cli/blob/issue%23145-test/evalai/submissions.py#L53
   - https://github.com/vkartik97/evalai-cli/blob/issue%23145-test/evalai/submissions.py#L55
- Test Output: https://travis-ci.org/vkartik97/evalai-cli/jobs/513846459#L611

**Comment by RonnyPfannschmidt** [comment]
click does environment separation that you need to work around in a test call when using the test executor (i ran into this before, you explicitly need to pass over the env vars telling about docker)

**Comment by vkartik97** [comment]
@RonnyPfannschmidt 
How exactly should I achieve this?
Also, I figured out that responses is blocking all external api requests.

**Comment by RonnyPfannschmidt** [comment]
I font have anything like that abailiable
