### ISSUE TITLE
'pytest.config' global is deprecated

### ISSUE THREAD

**Issue by nadavishe** [pytest-dev/pytest#5030]
Hi,
I implemented some pytest hooks, where i used pytest.config global
However in new pytest version i have warning:
PytestDeprecationWarning: the `pytest.config` global is deprecated.  Please use `request.config` or `pytest_configure`
How i can obtain request.config in pytest hook, for example in hook:
pytest_runtestloop(session)

Thanks

**Comment by blueyed** [comment]
`session.config`.
See https://github.com/blueyed/pytest/blob/106427e0827a7a2829e726a39c8eaf7b71c7ebd5/src/_pytest/main.py#L420-L427

**Comment by blueyed** [comment]
Might be worth adding a note to the docs that it is usually available in other hooks also, but not not really sure.  https://github.com/blueyed/pytest/blame/106427e0827a7a2829e726a39c8eaf7b71c7ebd5/doc/en/deprecations.rst#L56-L63
