### ISSUE TITLE
cleanup: move terminal summary code to terminal plugin

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5067]
Code: https://github.com/pytest-dev/pytest/blob/13a9d876f74f17907ad04b13132cbd4aa4ad5842/src/_pytest/skipping.py#L188-L310

The "reportchars" option is owned by the terminal plugin, and therefore the processing should be done there also.  This avoids confusion in the code, and would probably also avoid going through a hook here.

**Comment by Zac-HD** [comment]
Fixed by #5069.
