### ISSUE TITLE
Improvements to last-failed plugin

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5073]
- [ ] `--show-lf` option to display a (short) summary of last failures (so that you can easily pick copy'n'paste them from there)
- [ ] `--lf-stash` / `--lf-pop`: stash (like git-stash) away (and pop) the current state.  Maybe `--lf-store` / `--lf-restore`, but in either case it would be useful to also provide/use names.  This could be something generic for cache entries (via their names), so more useful in general then.  See also #5033.  I tend to currently copy the cache dir/files manually, but that is a bit tedious.
- [ ] `--lf-readonly`: do not update cache, but only use it - easier option for the above (stashes/saving)

**Comment by jeffreyrack** [comment]
Is `--show-lf` essentially a `--collect-only --lf` with the main difference being that the output of `--show-lf` would be the node-ids so you can copy/paste which tests to run?

If so, would it make more sense to have `--collect-only` be able to provide the node-ids so you can copy/paste to run tests from there?
