### ISSUE TITLE
Making test result available in module fixture?

### ISSUE THREAD

**Issue by ckenna** [pytest-dev/pytest#5090]
This is not really an "issue" but I have seen others using GitHub issues as a sort of Q&A. Forgive me if this inappropriate. I can try some other way to get help.

The documentation at this anchor https://docs.pytest.org/en/latest/example/simple.html#making-test-result-information-available-in-fixtures is a great way to make the test results available to a fixture finalizer in **"function"** scope as the example points out.

However, I have a fixture that is _also_ used in **"module"** scope.  As such, I need a different approach that can support both. The issue with the given example code is that it will result in errors for fixtures with module scope.

For example, since `request.node` is a `Module` object and it is in `Module` scope, there is no `rep_setup` attribute (error below). I assume this is because the fixture with module scope's finalizer is only run after all tests have completed?

```
STDOUT: dump_instance_console_history_to_log_on_test_failure(request, ctx)
STDOUT: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
STDOUT: request = <SubRequest 'ctx' for <Function test_launch_instance_migration>>
STDOUT: ctx = <vmi.contexts.instance.InstanceContext object at 0x7f976be0eda0>
STDOUT: def dump_instance_console_history_to_log_on_test_failure(request: FixtureRequest, ctx: SingleInstanceContext):
STDOUT: >       if request.node.rep_setup.passed and (request.node.rep_call.failed or request.node.rep_call.skipped):
STDOUT: E       AttributeError: 'Module' object has no attribute 'rep_setup'
```

So one way to work around this is to modify the code in the example to try and account for both function and module scopes by recursively finding the module and setting a boolean indicating that a test failed, then modifying the fixture finalizer to look for this boolean, too.

That code looks like this:

```
@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item: pytest.Item, call):
    """
    This is derived from the documentation here:
    https://docs.pytest.org/en/latest/example/simple.html#making-test-result-information-available-in-fixtures
    """
    outcome = yield  # Get the outcome from running the phase of the call.
    # set a "report" attribute for each phase of a call with the result, which can be
    # "setup", "call", or "teardown"
    rep = outcome.get_result()
    setattr(item, "rep_" + rep.when, rep)

    # In the event of module scoped fixtures, also mark failure in module.
    module = item
    while module is not None and not isinstance(module, Module):
        module = module.parent
    if module is not None:
        if rep.when == 'call' and (rep.failed or rep.skipped):
            setattr(module, "module_test_failure", True)


def fixture_finalizer_failure_debugging(request: FixtureRequest, ctx: SingleInstanceContext):
    """
    Dump information to the log if test fails for instances managed by pytest fixtures.

    This assumes that the hook pytest_runtest_makereport also ran and set the "rep_*" objects.

    :param request: This is pytest's implicit FixtureRequest object that gives access to test context.
    :param ctx: This is the instance context the fixture is yielding to a test.

    """

    # Handle failure at the module scope level
    dump_information = isinstance(request.node, Module) and getattr(request.node, "module_test_failure", False)
    # Per the pytest example, the request.node is an "Item" because the scope is default function scope.
    dump_information |= isinstance(request.node, Item) \
        and request.node.rep_setup.passed \
        and (request.node.rep_call.failed or request.node.rep_call.skipped)

    if dump_information:
        # Code here dumps extra information on test failures...
```

So the question is: Is the above actually the best way to do this?

**Comment by nicoddemus** [comment]
Hi @ckenna,

Yes, it seems that is a good solution for your specific problem. Alternatively instead of just setting a boolean, you might consider using a list and adding the nodeid of the failed tests.

Closing this for now, feel free to follow up with further questions.

**Comment by smarie** [comment]
You might also have a look at the [pytest-harvest](https://smarie.github.io/python-pytest-harvest/) plugin, that provides several ways to retrieve the test results and even test-produced artifacts.

**Comment by konflic** [comment]
Would be nice if info about different types of scopes would be added to eexamples here https://docs.pytest.org/en/latest/example/simple.html#making-test-result-information-available-in-fixtures

Also, it indeed seems not OK that such an easy and needed functionality as obtaining the test result is not a part of default features.
