### ISSUE TITLE
nested pytest.mark.parametrize ignore mark=xfail or mark=skip

### ISSUE THREAD

**Issue by azrdev** [pytest-dev/pytest#5092]
Applying multiple `pytest.mark.parametrize` decorators to a test function (no fixtures involved) works fine, except for trying to `mark=pytest.mark.xfail()` some of the parameters:

~~~python
import pytest

@pytest.mark.parametrize('a', [
    pytest.param('a1'),
    pytest.param('a2', mark=pytest.mark.xfail()),
])
@pytest.mark.parametrize('b', [
    pytest.param('b1'),
    pytest.param('b2', mark=pytest.mark.skip()),
])
def test_foo(a, b):
    pass
~~~

Running `python3 -m pytest -vvv test.py` I'd expect only `a1-b1` to succeed, all other combinations to either fail (because no error + `xfail`) or be skipped. Instead I get 4 times "PASSED".

### `pip list` of the virtual environment you are using
~~~
Package    Version
---------- -------
pip        19.0.3 
setuptools 40.8.0 
~~~

### pytest and operating system versions
pytest 4.4.0
Python 3.7.3
archlinux rolling

**Comment by asottile** [comment]
This is a typo, you want `marks=...`

Probably also a bug that `pytest.param` allows arbitrary keyword arguments silently:

https://github.com/pytest-dev/pytest/blob/b3319a6074636eb651063bff7eec69ec289f1df5/src/_pytest/mark/structures.py#L62-L77

**Comment by azrdev** [comment]
> This is a typo, you want `marks=...`

indeed, sorry & thank you

> Probably also a bug that `pytest.param` allows arbitrary keyword arguments silently:

do you want to have that in a separate issue or keep this one?

**Comment by asottile** [comment]
this is probably fine
