### ISSUE TITLE
Mark validation: should keep track of marks to check without config

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5101]
I've just noticed that without a config (e.g. during loading of plugins), marks are not checked: https://github.com/pytest-dev/pytest/blob/19035f4b552c3164d4d7a10fbc6113b47232a99d/src/_pytest/mark/structures.py#L293

I think they could be remembered in a list to check later, e.g. on `pytest_configure`.

/cc @Zac-HD

**Comment by RonnyPfannschmidt** [comment]
it should be noted that the final result of that evaluation can only be solved after all marks have been registered

**Comment by blueyed** [comment]
That's my point.
Wouldn't that be the case in `pytest_configure`, or should a later hook be used?

This also means that validation would not have to been done when registering them already (where the config is read/iterated over always now), but only once for all marks.

**Comment by RonnyPfannschmidt** [comment]
practically speaking only after the end of a test run the data for validation is possibly complete (plugins can be registered at any time)

we should keep a list of unknown markers, and emmit warnigns at the end of the test session

we can probably wrap around plug-in registration to drop newly known ones from the list of unknown markers
