### ISSUE TITLE
docs: plugins page no longer exists

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#5105]
It seems that https://docs.pytest.org/en/latest/plugins_index/index.html page no longer exists but is listed in the main index at https://docs.pytest.org/en/latest/

List of plugins exists for older releases but not for the latest / main documentation.

**Comment by blueyed** [comment]
> but is listed in the main index at https://docs.pytest.org/en/latest/

Where?  I could not find it there.

**Comment by ssbarnea** [comment]
In fac is well hidden in left side panel, as "3rd party plugins" which points to  http://plugincompat.herokuapp.com/ --- which seems to be dynamic/slow to load.

I am sure that last week I got an error clicking that link. Now it seems to load, but very slow.

Still, I think that list of plugins should be part of the documentation, so we can use the search on them.

Now the listing is hosted on another site, which also has some uptime problems.

I really doubt that that list change so often that it would need this level of dynamic report. 

I would rather prefer to see this list saved inside the documentation and maybe having the job that tests them produce a PR for updating the documentation. This approach would enable search and also address the speed and flakiness issue.

**Comment by nicoddemus** [comment]
Yeah, that site is dynamic and uses Heroku's free tier, so it spins up a new VM if it has not seen activity in 10 minutes or so.

I worked on it when I started to contribute to pytest more, but I'm not sure it is that useful anymore. Perhaps making it static and auto-generated would be more useful overall?

**Comment by ssbarnea** [comment]
@nicoddemus Now even Travis has cron jobs which means that we could use travis cron to run job that does generate the report and if different that current one, it creates a PR to update the docs.

This would not require any extra hosting.

**Comment by mcsitter** [comment]
Is this an issue, which needs to be resolved? pytest-dev/plugincompat is still maintained and while the heroku dyno may sometimes have to spin up, it works. While not favourable sometimes links break. We could add a redirect file or entry for that if necessary.


An idea i had, which may not be worth pursuing:
To speed up the site, one could try the speed of a FaaS (function as a service). This could be serving the data via flask and grab the data from some db. I think the heroku database does not go down, so it could still be used and the data can be created periodically by the heroku dyno.

**Comment by ssbarnea** [comment]
With all due respect, I do find the urrent plugins page implementation close to not-usable. As in 2020, if a web page does not load in 5s we can easily consider it being offline.

We do not really need any server based hosting for it, in fact this can easily be a static website generated using a cron job hosted on either readhedocs (part of normal docs?) or using Amazon S3 (i am willing to pay the ~0.02$/month bucket coss to run it.

Lets avoid trying to overengineer anything. The "database" is nothing more than a small json that even a smart watch can process.

I propose making that page part of the documentation but load the plugins from a json file. Something like https://www.patternfly.org/v3/pattern-library/content-views/table-view/index.html#overview could be easy to implement and also address ability to filter the list of plugins based on their attributes, again without any server-side code.

**Comment by nicoddemus** [comment]
I'm in favor of implementing something simpler to replace the current pluginscompat page.

I implemented that initially more as a toy to learn Heroku, but of course in the end it proved useful so we at least added a link to the docs for it.

It definitely could be a static page, updated via a cron job of sorts.

However, we would need a champion to implement this transition, as I don't have the time to do that myself.

**Comment by mcsitter** [comment]
I can see myself tackling this, but i have no idea what i am getting myself into, really.

With some questions answered on what should be achieved, i might get a better idea.

1. Should the plugins site be more than just a list of pytest plugins? See 2 and 3

2. Should there be info about compatibility/ maintenance status? Should this be tested they way it is at the moment by installing/ testing or by checking metadata/requirements?

I assume this would be the most difficult part, especially with the testing of each plugin. On the other hand we have a lot of this logic written already, even if not perfect.

3. Should the Plugins have some kind of description? Have a look at [this](https://github.com/DmytroLitvinov/awesome-flake8-extensions) rather useful list of flake8-plugins to understand why i am asking this. Manual curation is not a goal, but it inspires.

This could be parsed from metadata or manually added. Could be a feature enhancement down the line. Just throwing it in!

4. Should this be part of the docs served by readthedocs (something in this repo) or an external ressource (maybe code living in pytest-dev/plugincompat )?

5. How the data is generated and turned into actual html will depend on the questions above. Feel free to state your architecture ideas.


My dream would be a single file in the docs which is updated or gets the plugin list (JSON) somewhere, but i don't know how feasible this us exactly with how much hassle the integration with sphinx might be. I imagine it could be solvable.

**Comment by nicoddemus** [comment]
My 2 cents:

1. The idea of testing integration with pytest IMHO proved not useful in practice: many plugins have external dependencies so it is hard to ensure a given plugin actually works in a generic way.

2. I think a list of plugins, with some short description, is already an useful idea by itself. We can also extract some interesting metadata automatically, like minimum pytest and Python versions supported, which could display along side each plugin.

3. I think serving this as a static site using GitHub pages is useful. A cron job could execute once a day to update the static site getting fresh information from PyPI, and push an update (if any).

I would be OK with experimenting with this in `plugincompat`, but I'm not sure if there's much code there that is worth sharing. Probably the best approach is for someone to try this into a new repository, under their own account: this gives them access to any resources (such as Travis) and the repository itself to setup things. Once this is working nicely, we can then move the repository to `pytest-dev` and change our docs to point to the new location.

Integrating with the official docs is interesting, but I believe secondary. However, this probably is even simpler because a job can just update a `.rst` file with the required information, and open a PR.

**Comment by mcsitter** [comment]
Thank you for the Feedback and support! I learned a lot from contributing here and the guidance helped immensely while being great fun.

After the weekend I will tackle this. Writing down roughly what the features should be will be the first thing to do along with exploring some code.

How should the conversation continue? I think i should open an issue on my repo and reference this issue. Than we can continue there.

**Comment by nicoddemus** [comment]
> How should the conversation continue? I think i should open an issue on my repo and reference this issue. Than we can continue there.

Sounds good!
