### ISSUE TITLE
Make exit statuses public API

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5125]
Currently they are defined in `_pytest.main`: https://github.com/blueyed/pytest/blob/526e64ec642bd34db7803d8c03b4b1b05350fc57/src/_pytest/main.py#L27-L33

It might make sense to move them to `Session`, which allows to use them more easily in hooks with a session also (e.g. `pytest_sessiofinish`).

Related: https://github.com/pytest-dev/pytest/issues/4901 - so it might make sense to use a class based on `int`, with a custom repr/str for example.

**Comment by RonnyPfannschmidt** [comment]
Enum

**Comment by Zac-HD** [comment]
[`enum.IntEnum`](https://docs.python.org/3/library/enum.html#enum.IntEnum) is definitely the way to go here 😄

**Comment by nicoddemus** [comment]
This is even easier now that we have dropped 2.7/3.4 from `master`. 😁
