### ISSUE TITLE
-k should work with header lines from failures

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5130]
Given `t.py`:
```
class Test:
    def test_fail(self):
        assert 0
```

It displays "Test.test_fail" in the header, but that cannot be used with "-k".

```
=================================== FAILURES ===================================
________________________________ Test.test_fail ________________________________

self = <test_nodeid_in_class.Test object at 0x7f2f37a3dd68>

    def test_fail(self):
>       assert 0
E       assert 0

testing/test_nodeid_in_class.py:3: AssertionError
=========================== short test summary info ============================
FAILED testing/test_nodeid_in_class.py::Test::test_fail
=========================== 1 failed in 0.04 seconds ===========================
```

Even `-k Test::test_fail` does not work..

It might make sense to explicitly include the full nodeid in https://github.com/blueyed/pytest/blob/ea79eb5c3ff96e5dad7719650784580cd31fa0ad/src/_pytest/mark/legacy.py#L28-L57, which would also kind of avoid getting the single name via the chain.

The headline uses `domain` from `location` there, which is the modpath (via https://github.com/blueyed/pytest/blob/ea79eb5c3ff96e5dad7719650784580cd31fa0ad/src/_pytest/python.py#L310).

**Comment by RonnyPfannschmidt** [comment]
thats currently as expected - `Test.test_fail` is not a keyword

**Comment by RonnyPfannschmidt** [comment]
to elaborate, the keywords `Test` and `test_fail` get registered from the respective node names

**Comment by blueyed** [comment]
Yeah.. but e.g. the full path appears to become a keyword also (which confused me with "-k fail" in a pytester testdir test case, where the outer test had also "fail" in its name, and hence the path).
Do you think it makes sense to explicitly add modpath/the location's "domain" (3rd arg) then also as a keyword?

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/blob/c3b7efc8186f290d5fc5939aba3497f5bd26ee13/src/_pytest/nodes.py#L352-L360 is responsible for the "full" fspath becoming a keyword

personally keyword/mark-expressions is something i want to see gone eventually, however a sensible replacement is not yet known

i'd prefer to avoid adding/removing elements to its behavior as any change in its structure is likely a completely breaking change
