### ISSUE TITLE
requests_mock plugin : No way of raising side_effect (requests.exceptions) 

### ISSUE THREAD

**Issue by jps-ob** [pytest-dev/pytest#5141]
I would like to test Connection/Timeout Exception for requests calls.

``
from unittest import mock

@mock.patch('requests.post', side_effect=requests.exceptions.ConnectTimeout)
def test_connection_error():
``

As stated [in docs here](https://requests-mock.readthedocs.io/en/latest/pytest.html)
> The fixture then provides the same interface as the **requests_mock.Mocker** letting you use requests-mock as you would expect.

requests-mock pytest plugin helps testing other failure scenarios, but not raising exception as side-effect. Hence  I would like to define custom Adapter for requests-mock as [documented here](https://requests-mock.readthedocs.io/en/latest/matching.html)

This is not possible with **requests-mock pytest plugin**  and without importing **requests-mock module** 

However this would create namespace class hence, we need something like this
`import requests_mock as req_mock_mod`

Is there any possibility of using plugin to raise Request.Exception  and/or define custom adapters ?

**Comment by jps-ob** [comment]
Also  the following (with requests_mock plugin fixture) doesn't raise mocked side effect
```
@mock.patch('requests.post', side_effect=requests.exceptions.ConnectTimeout)
def test_connection_error():
```

but passing requests_mock does trigger 
```
@mock.patch('requests.post', side_effect=requests.exceptions.ConnectTimeout)
def test_connection_error(requests_mock):
``` 

Is this expected or namespace corruption ?

**Comment by asottile** [comment]
This repo is the main pytest repository, if you have a bug for a specific plugin I'd suggest asking on their issue tracker :+1:

**Comment by jps-ob** [comment]
Apologies if this is not right forum.

As per [this page](https://requests-mock.readthedocs.io/en/latest/pytest.html), I thought it is maintained by PyTest. 

> pytest *has its own* method of registering and loading custom fixtures. requests-mock provides an external fixture registered with pytest such that it is usable simply by specifying it as a parameter. There is no need to import requests-mock it simply needs to be installed and specify the argument requests_mock.

If not, please suggest which forum I should addressing to

**Comment by jps-ob** [comment]
Never mind. I got [the right forum](https://github.com/jamielennox/requests-mock/issues/56). I will close this. Sorry for the confusion
