### ISSUE TITLE
如何控制生成的report报告页面元素

### ISSUE THREAD

**Issue by NarutoKobe** [pytest-dev/pytest#5142]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by NarutoKobe** [comment]
win10,platform win32 -- Python 3.7.0, pytest-3.7.2, py-1.8.0, pluggy-0.9.0
我想控制删选生成的页面元素,请问该修改哪里

**Comment by nicoddemus** [comment]
Hi @NarutoKobe,

There's not an actual issue described here, did you hit the 'submit' button too early perhaps?
