### ISSUE TITLE
pdb: might suspend output capture twice

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5146]
Fix makes sense only after https://github.com/pytest-dev/pytest/pull/5085.

This causes e.g. `terminal._tw.fullwidth` become 80 then (since stdout is not properly restored after resuming).

**Comment by eduzen** [comment]
Hi @blueyed , do you think is a good first issue to take? I would like to start helping here but Im not sure which issue is the best.

**Comment by blueyed** [comment]
Likely not a good first issue - but depends on your experience with pytest and its pdb wrapper after all.. ;)

Try looking at https://github.com/pytest-dev/pytest/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+easy%22.
