### ISSUE TITLE
pip 19.1 prevents pytest from being used in editable mode

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#5167]
pip 19.1 prevents pytest to use editable mode (https://github.com/pypa/pip/pull/6370) due to our `pyproject.toml` file.

This is a problem for us for two reasons:

1. `tox.ini` uses `usedevelop` in a `release` and `docs` environments. I think we can get away from using it in `docs`, not so sure about release.

2. We use editable mode ourselves.

I will open a PR shortly trying to address 1, but for 2 I don't know of any workaround other than downgrading pip manually.

cc @RonnyPfannschmidt

**Comment by gaborbernat** [comment]
https://github.com/pypa/pip/issues/6434 issue report and discussion, things should be better once pip 19.1.1 gets out (hopefully soon)

**Comment by bskinn** [comment]
For (2), try removing `-e .` (or `pip install -e .`, or whatever mechanism) for the pip-mediated editable install, and instead running `python setup.py develop` to achieve an editable install via `setuptools.

This has worked fine so far for both of my PEP517 projects.
