### ISSUE TITLE
pytest_configure silently ignored when using "yield"

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5170]
Have not really investigated, but when using `yield` accidentally in `pytest_configure`, it seemed to be silently ignored (running into a collection error later).

**Comment by nicoddemus** [comment]
What probably happens is that `pluggy` calls it, but it returns a `generator` object, which doesn't execute the actual block of code.

By "accidentally" you mean you meant to write a hookwrapper?

**Comment by blueyed** [comment]
> By "accidentally" you mean you meant to write a hookwrapper?

Yes.

**Comment by nicoddemus** [comment]
Probably we can open an issue on pluggy to warn/error when that happens, what do you think? I don't think hook calls are ever meant to be generators.

**Comment by blueyed** [comment]
Sounds good.

**Comment by nicoddemus** [comment]
Would you like to do it, or want me to do it? 😁 

Closing this then. 👍
