### ISSUE TITLE
"-p" with custom plugins and cwd != root

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5190]
When adding `-p tests.myplugin` to `addopts` it will not work when running the tests from another directory.

Using an entrypoint plugin has other problems: with editable installs it needs to be in the main package (since only this gets installed/linked AFAIK), which then for example does not allow you to use `__file__`-relative locations when the project is installed non-editable.  And it appears to be rather bad practise to have it with the main package in the first place.

Therefore I wonder if `-p` could a) just handle file locations (relative to `root`, e.g. `-p ./tests/myplugin.py`), or b) add the root to `sys.path` temporarily when importing it.

Also relevant for `PYTEST_PLUGINS` then.

**Comment by nicoddemus** [comment]
Passing tests in the command-line is the other way around: we accept file locations, but can use `--pyargs` to pass packages/modules instead. I like a), but given the above, perhaps we should then use another option in the same manner? `--plugin-path`? The advantage is that completely backward compatible and doesn't risk breaking things unexpectedly.
