### ISSUE TITLE
config: add support for explicit pytest_plugins

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5191]
Currently you cannot explicitly configure plugins to be used from the config, but have to use `addopts` for this.

It might be good to have a way to configure this explicitly, e.g. via a new `pytest_plugins` setting.

Not really sure about it, but it would certainly decouple it a bit, but also adds more parsing/handling.
It would be needed with e.g. https://github.com/pytest-dev/pytest/issues/5127, where you might disable `addopts` only for using pytest defaults, but the plugin is required for testing.

**Comment by nicoddemus** [comment]
You mean a specific option in `pytest.ini`? Definitely, I have thought about it in the past. I would suggest just calling it `plugins` though. 👍

**Comment by blueyed** [comment]
@RonnyPfannschmidt do you plan to do anything in this regard?  If so please just create a PR.  It's not an issue for myself (as OP).
