### ISSUE TITLE
Context manager for capsys

### ISSUE THREAD

**Issue by standage** [pytest-dev/pytest#5197]
I have a package with the following convenience function in `__init__.py`.

```python
from gzip import open as gzopen

def open(filename, mode):
    if mode not in ('r', 'w'):
        raise ValueError('invalid mode "{}"'.format(mode))
    if filename in ['-', None]:
        filehandle = sys.stdin if mode == 'r' else sys.stdout
        return filehandle
    openfunc = builtins.open
    if filename.endswith('.gz'):
        openfunc = gzopen
        mode += 't'
    return openfunc(filename, mode)
```

This allows me to use a single `open` function regardless if the file is compressed or not. If the file is unspecified, then it defaults to stdin or stdout, depending on the mode.

I have the following in several modules throughout my package's code.

```python
with mypackage.open(args.out, 'w') as fh:
    json.dump(data, fh)
```

This works fine...until I try to capture the terminal with `capsys`. It results in errors like `ValueError: I/O operation on closed file` and `AttributeError: __enter__`.

I was able to get both the package modules and the tests to work correctly by modifying the code as follows.

```python
fh = mypackage.open(args.out, 'w')
json.dump(data, fh)
if fh != sys.stdout:
    fh.close()
```

Eliminating this kind of messy boilerplate is exactly what context managers were created for. What is the suggested testing approach in this scenario? Is there any way I can invoke `capsys` while using the `with` syntax?

**Comment by nicoddemus** [comment]
Hi @standage,

Thanks for writing. I'm not sure I follow though, because closing `sys.stdout` seems to be problem:

```python
import sys

with sys.stdout as f:
    f.write('hello\n')

print('hey')
```

```
λ python foo.py
hello
Traceback (most recent call last):
  File "foo.py", line 6, in <module>
    print('hey')
ValueError: I/O operation on closed file.
```

Can you perhaps post a small reproducible example demonstrating your problem? Thanks!

**Comment by standage** [comment]
Hi @nicoddemus,

I've come up with a minimal example reproducing the behavior at https://github.com/standage/with-capsys-example. Let me know if anything is unclear.

**Comment by standage** [comment]
Sorry to consume your time. This was an issue with my handling of file handles.

You're right: my code was calling `close()` on the default `sys.stdout`, it just didn't have any consequences during runtime since it was the final operation before the programs terminate. But there are certainly scenarios where that might not be the case, and calling `close()` on `sys.stdout` is definitely problematic.

I ended up addressing the issue by making the `myopen` function a context manager itself. This allows me to yield sys.stdout/sys.stderr directly, and all other file handles within their own `with` block.

```python
@contextmanager
def myopen(filename, mode):
    if mode not in ('r', 'w'):
        raise ValueError('invalid mode "{}"'.format(mode))
    if filename in ['-', None]:
        filehandle = sys.stdin if mode == 'r' else sys.stdout
        yield filehandle
    else:
        openfunc = open
        if filename.endswith('.gz'):
            openfunc = gzopen
            mode += 't'
        with openfunc(filename, mode) as handle:
            yield handle
```

This produces the desired behavior both in a runtime and a testing context.
