### ISSUE TITLE
Subprocess vs. multi-process 

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest#5200]
Hi,

I have a usecase where I wrapped pytest in a docker and provided it an external Restful apis to communicate.

In order to provide some async responses, I wrapped pytest.main() with thread module - which I know it's unsafe.
I started reading about this topic, and found out that the way of building a safer runner is to use subprocess. however, I also saw that there is a module which is spwans a process with multiprocessing.

what is the correct and safer way to achieve my goal?

**Comment by nicoddemus** [comment]
Hi @Formartha,

> what is the correct and safer way to achieve my goal?

Can you describe this in more details? Your goal is not really clear to me from reading your message, I'm afraid.

**Comment by Formartha** [comment]
Hey @nicoddemus, thanks for helping out.

I'll try to rephrase my question, it might be easier than I described it at first place.
--
What is the best way to trigger pytest session from another python script.
e.g. - I have a main process which I would like to trigger session as per required.

Should I use subprocess(..) or multiprocessing.Process(..) and why? :)

**Comment by nicoddemus** [comment]
I suggest to try `pytest.main()` directly first, otherwise either `subprocess` or `multiprocessing` might be enough for your needs.

**Comment by Formartha** [comment]
thank you @nicoddemus.

I tried what you suggested, however I'm facing is the following issue:

I have a flask server that serves py.test main. meaning, I'm using restful API to pass down parameters to pytest.
The problem is that when I'm using pytest.main() in multiprocessing - the process hangs after collecting items.
I'm using the following impl.

Processing:
--------------
`        process = multiprocessing.Process(target=run_test, args=(test_args, test_uuid))
        process.daemon = True
        process.start()
        PytestSingleton.test_process = process.name`

Runner:
--------
`def run_test(inner_test_args, inner_test_uuid):
    """ inner dispatcher act as threading manager"""
    TestSingleton.test_uuid = inner_test_uuid

    importlib.reload(pytest)  # hack to reload pytest.
    pytest.main(
        [
            ProjectPaths.build_tests_path(),  # todo: parse test location from config file.
            "-k",
            inner_test_args["test_name"],
            "--config_entry",
            inner_test_args["config"],
            "--json-report"
        ]
    )
`

Running it from cmd is successful..

any ideas how to proceed understanding what's the issue?

**Comment by Formartha** [comment]
oh, and it runs inside docker. outside (my local PC) it works perfectly.

**Comment by nicoddemus** [comment]
(I fix your post formatting, please take a look [here](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) on how to properly format code in GitHub)

> any ideas how to proceed understanding what's the issue?

Given that this works when running outside the docker container, doesn't seem related to pytest. Not sure how to proceed here, sorry. 😕

**Comment by Formartha** [comment]
Hey, I'm back with information.
it turned out that a db access adapter was deadlocked due to the way we implemented it. this DB connector used in order to fetch down a config file that will feed the E2E tests we are creating.

till now, it seems like pytest works well in a multi-processed environment. 

just a quick question. How can I reload the entire pytest stack (including plugins) in each and every invocation to pytest.main() ?

**Comment by nicoddemus** [comment]
Hi @Formartha,

> just a quick question. How can I reload the entire pytest stack (including plugins) in each and every invocation to pytest.main() ?

Other than actual module reloading, pytest tries to properly tear everything down after main, although I suspect some plugins might not be doing things here and just leaving global state laying around.

If you are having a problem, please post specifics, in that way we will probably be able to help you better. 👍
