### ISSUE TITLE
Running pytest with pep8 shows an additional collected item

### ISSUE THREAD

**Issue by fbarbu15** [pytest-dev/pytest#5217]
- [ When running a pytest command that has --pep8 in setup.cfg an additional item is collected that comes from pep8. This messes up my reports.]

Here's an example: 

```
$ pytest --collect-only --html=report.html --self-contained-html tests\\test_main_window.py
============================= test session starts =============================
platform win32 -- Python 3.7.2, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: C:\WORK_DIR\cop_regression, inifile: setup.cfg
plugins: subtests-0.2.1, pep8-1.0.6, metadata-1.8.0, instafail-0.4.1, html-1.20.0, dependency-0.4.0
c:\work_dir\cop_regression\lib\site-packages\pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
C:\WORK_DIR\cop_regression
collected 2 items
<Pep8Item tests/test_main_window.py>
<Module tests/test_main_window.py>
  <UnitTestCase TestMainWindow>
    <TestCaseFunction test_02_new_contact_by_drop_down>`

```

<Pep8Item tests/test_main_window.py> is the unwanted item that keeps showing in the report.
Is there a way to ignore this? I tried with --deselect and --ignore-glob but it's either ignoring the real test as well or none of them. Thanks in advance.
 

- [$ pip list              
Package           Versio
----------------- ------
apipkg            1.5   
atomicwrites      1.3.0 
attrs             19.1.0
colorama          0.4.1 
comtypes          1.1.7 
entrypoints       0.3   
execnet           1.6.0 
mccabe            0.6.1 
more-itertools    7.0.0 
parameterized     0.7.0 
pep8              1.7.1 
Pillow            6.0.0 
pip               19.0.3
pluggy            0.9.0 
py                1.8.0 
PyAutoGUI         0.9.42
pycodestyle       2.5.0 
pyflakes          2.1.1 
PyGetWindow       0.0.4 
PyMsgBox          1.0.6 
pyodbc            4.0.26
PyRect            0.1.4 
PyScreeze         0.1.20
pytest            4.4.1 
pytest-cache      1.0   
pytest-dependency 0.4.0 
pytest-html       1.20.0
pytest-instafail  0.4.1 
pytest-logging    2015.1
pytest-metadata   1.8.0 
pytest-pep8       1.0.6 
pytest-subtests   0.2.1 
PyTweening        1.0.3 
pywin32           224   
pywinauto         0.6.6 
setuptools        41.0.0
six               1.12.0
wheel             0.33.1 ]

**Comment by nicoddemus** [comment]
> Is there a way to ignore this? I tried with --deselect and --ignore-glob but it's either ignoring the real test as well or none of them. Thanks in advance.

That's the "test item" generated by `pytest-pep8`, there's no way to prevent that from being collected AFAIK.

Alternatively you can use `pep8` directly from the command-line instead of the pytest plugin.

I'm closing this for now as I believe your question has been answered, but feel free to follow up with further questions.

**Comment by fbarbu15** [comment]
Thanks for the confirmation. Will use pep8 separately
