### ISSUE TITLE
Need a programmatic way to register markers

### ISSUE THREAD

**Issue by charris** [pytest-dev/pytest#5255]
The latest (4.5.0) pytest release raises a warning when non-registered markers are discovered in the discovery phase. That can be fixed by registering the markers in the `pytest.ini` file as long as that file is present and findable, however, that is not the case when testing NumPy installed from wheels or using `setup.py`, as the tests are run from the imported NumPy module. What would be helpful is if there were a way to register the marks from the pytest command line or possibly during the discovery phase. There may already be such a method, but I am unable to find it in the documentation.
 

- [ ] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
the common workaround 

https://github.com/pytest-dev/pytest/blob/6a43c8cd9405c68e223f4c6270bd1e1ac4bc8c5f/src/_pytest/skipping.py#L47-L70

**Comment by charris** [comment]
Yes, but where should it be done?

**Comment by RonnyPfannschmidt** [comment]
your personal `pytest_configure` hook

**Comment by charris** [comment]
Thanks, that seems to work. Not sure why I could not find that bit of documentation, I did search.

**Comment by RonnyPfannschmidt** [comment]
tbh, its hard to search for it - https://docs.pytest.org/en/latest/example/markers.html#custom-marker-and-command-line-option-to-control-test-runs

**Comment by nicoddemus** [comment]
Agreed, trying to improve the docs in #5265.

**Comment by rgommers** [comment]
This issue is popping up in many places, I've personally encountered it in NumPy, SciPy and PyWavelets. Many projects use at least a `slow` mark. Can that be added to the builtin marks somehow if you really want to keep this warning and turn it into an error? 

Also, `conftest.py` isn't a great name. `import scipy.conftest` really should not succeed, it looks like a public API.

@charris could you reopen this?

**Comment by nicoddemus** [comment]
Hi @rgommers,

> This issue is popping up in many places, I've personally encountered it in NumPy, SciPy and PyWavelets. 

What do you mean? Are you encountering this as a user or as a developer of those libraries?

**Comment by rgommers** [comment]
As a developer of those libraries mainly. But any user will see these if they run tests for NumPy, SciPy, PyWavelets or any other similar project if they install the latest pytest.

**Comment by nicoddemus** [comment]
Thanks @rgommers!

We probably want to leave the warning in place, because it was placed specifically because many users seemed to mistype the markers and get surprising results.

> But any user will see these if they run tests for NumPy, SciPy, PyWavelets or any other similar project if they install the latest pytest.

I see, but this is simple to solve in those projects, you just need to register your marks in your `pytest.ini` or `tox.ini` file:

```ini
[pytest]
markers =
    slow
```

And that's it. This works for any version of pytest since 2.something, so it should be safe. 👍

**Comment by rgommers** [comment]
There's a reason we were not shipping `pytest.ini`: to be able to switch between "develop" mode (raising errors on warnings to keep them from creeping in with new PRs) and "release" mode. IIRC this also had something to do with `pytest.ini` taking precedence over `conftest`, can't remember that detail exactly.

Now the mark registration in NumPy is moved to `conftest.py`, but that's an ugly name (as I said above, it looks like public API). Is there a way to configure that from a differently named Python file? Allowing `_conftest.py` would be an easy solution perhaps.

**Comment by nicoddemus** [comment]
> There's a reason we were not shipping pytest.ini

I see, thanks for the explanation.

> Now the mark registration in NumPy is moved to conftest.py, but that's an ugly name (as I said above, it looks like public API). Is there a way to configure that from a differently named Python file? Allowing _conftest.py would be an easy solution perhaps.

`conftest.py` is not really configurable, but one way to avoiding it is to use a [custom plugin instead](https://docs.pytest.org/en/latest/writing_plugins.html#making-your-plugin-installable-by-others): basically all it needs done is moving the `pytest_configure` hook to another file (say `numpy._pytest_plugin`) and register it into your `setup.py`:

  ```python
  setup(
      ...
      entry_points={"pytest11": ["numpy= numpy._pytest_plugin"]},
  )
  ``` 

`numpy._pytest_plugin` is also a place `numpy` can use in the future to provide fixtures and hooks for its pytest users.

**Comment by rgommers** [comment]
`setup.py` isn't installed, so I guess that this creates some global setuptools entry on wheel build/install? Or it doesn't work at all? I'd rather accept the public-API-like name for now. 

> `conftest.py` is not really configurable

I had guessed that was the case. Maybe you can consider this a feature request? Adding underscores to any `.py` file that is not part of the API is good practice, so allowing it would make sense I think.

**Comment by nicoddemus** [comment]
> setup.py isn't installed, so I guess that this creates some global setuptools entry on wheel build/install? Or it doesn't work at all? I'd rather accept the public-API-like name for now.

It is used to create entry points, a widely used mechanism introduced by setuptools. It works with any package generated by setuptools and also other tools, like `flit` and `poetry`, so I'm sure it will work for you.

> I had guessed that was the case. Maybe you can consider this a feature request? Adding underscores to any .py file that is not part of the API is good practice, so allowing it would make sense I think.

I guess it would make sense to support `_conftest.py` as well as `conftest.py` (non-configurable)(opened an issue: https://github.com/pytest-dev/pytest/issues/5280), but with the entry point option you can name the module anything (like I shown in my example), so you won't need a `conftest.py` file anymore. 

Also keep in mind that such support would only be able to come out in pytest 4.6 at earliest, so your pytest 4.5 users would still face the same problem. For that reason I think you should consider the setuptools option, it is a one-line change (beside the `pytest_configure` hook of course) that works and will continue to work for any pytest version.

**Comment by rgommers** [comment]
> I guess it would make sense to support _conftest.py as well as conftest.py(opened an issue: #5280), 

great, thank you!

> so I'm sure it will work for you.

sounds like our experiences with `setuptools` are nothing alike:) As one of the main maintainers of the numpy and scipy build systems, I see any new setuptools thing we use as a potential time sink and risk. So I'll live without it for pytest 4.5

**Comment by nicoddemus** [comment]
> As one of the main maintainers of the numpy and scipy build systems, I see any new setuptools thing we use as a potential time sink and risk. So I'll live without it for pytest 4.5

entry points are quite old and stable; it powers pytest's plugins and a lot of other systems. I suggest you give this at least a try, as there's no guarantee we will implement #5280 at all.

But thanks for raising the concern and the discussion!

Should we close this now?

**Comment by rgommers** [comment]
> Should we close this now?

yes, please do.
