### ISSUE TITLE
Invalid unicode in _pytest/terminal.py with Jython

### ISSUE THREAD

**Issue by fabioz** [pytest-dev/pytest#5256]
With: Jython 2.7.1 and pytest 4.5.0, I'm having the error below:

```
Traceback (most recent call last):
  File "C:\bin\jython2.7.1\Lib\runpy.py", line 161, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\bin\jython2.7.1\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\bin\jython2.7.1\Lib\site-packages\pytest.py", line 101, in <module>
    raise SystemExit(pytest.main())
  File "C:\bin\jython2.7.1\Lib\site-packages\_pytest\config\__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "C:\bin\jython2.7.1\Lib\site-packages\_pytest\config\__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "C:\bin\jython2.7.1\Lib\site-packages\_pytest\config\__init__.py", line 60, in main
    config = _prepareconfig(args, plugins)
  File "C:\bin\jython2.7.1\Lib\site-packages\_pytest\config\__init__.py", line 190, in _prepareconfig
    config = get_config(args)
  File "C:\bin\jython2.7.1\Lib\site-packages\_pytest\config\__init__.py", line 164, in get_config
    pluginmanager.import_plugin(spec)
  File "C:\bin\jython2.7.1\Lib\site-packages\_pytest\config\__init__.py", line 562, in import_plugin
    __import__(importspec)
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 2-8: illegal Unicode character
```

The error happens because `terminal._get_line_with_reprcrash_message` has the following unicode literal: `u"\uD83D"`.

I'm not sure about the proper fix... in that function `msg` seems to be doing a `msg.find("\n")` and later does `msg.rstrip(u"\uD83D")`, so, I'm not even sure if we're dealing with `unicode` or `bytes` there on Python 2 because it's mixed (my guess is bytes, but I'm not really sure).

If it's bytes, doing it an actual `str` literal instead of a `unicode` literal -- i.e.: remove the `u` -- does make Jython happy (would that be an appropriate solution?)

**Comment by blueyed** [comment]
> my guess is bytes, but I'm not really sure

How about printing its `repr()` - or using pdb there in the first place if it's local (i.e. not on CI).

**Comment by blueyed** [comment]
Heh.. appears to be for/with a debugger after all.. :) (https://github.com/fabioz/PyDev.Debugger)

**Comment by fabioz** [comment]
> > my guess is bytes, but I'm not really sure
> 
> How about printing its `repr()` - or using pdb there in the first place if it's local (i.e. not on CI).

The code doesn't really get to that point (the error is given on importing the module) and I wasn't really sure how to get to that point.

Anyways, great that you checked it... I'll try to change from unicode to bytes to see if that's enough.

**Comment by blueyed** [comment]
> the error is given on importing the module

You should still be able to use `import pdb; pdb.set_trace()` there (possibly with some `if` / `try / except` around it, and possibly with `-s` for pytest.

**Comment by nicoddemus** [comment]
Howdy @fabioz! 😁  

I'm guessing your Jython version was compiled with "narrow unicode" support, which might be why it thinks it is an invalid unicode character.

What does this output for you?

```python
>>> import sys
>>> print sys.maxunicode
```

(Taken from [this SO question](https://stackoverflow.com/questions/1446347/how-to-find-out-if-python-is-compiled-with-ucs-2-or-ucs-4))

~~If it outputs `65535` then it means you got a narrow unicode build. I think we can condition the code above to only try to strip it if `sys.maxunicode > 65535`, and~~ use `unichr` instead of the literal to avoid the import error:

I striked-out the comment above because this works on my system:

```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> unichr(55357)
u'\ud83d'
>>> import sys
>>> sys.maxunicode
65535
```

Anyway, can you try the snippet above?

**Comment by nicoddemus** [comment]
Installed Jython myself, it is very odd what's happening here:

```
Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_141
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.maxunicode
1114111
>>> unichr(55357)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: unichr() arg is a lone surrogate in range (0xD800, 0xDFFF) (Jython UTF-16 encoding)
>>> 0xDFFF
57343
```

So it seems Jython cannot represent a lone surrogate like CPython can:

```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> unichr(55357)
u'\ud83d'
```

I think a solution then is to use `unichr` and skip it if we get a `ValueError` like in Jython.

**Comment by nicoddemus** [comment]
Opened https://github.com/pytest-dev/pytest/pull/5271 with a fix. @fabioz can you test that version to make sure it works for you?

**Comment by fabioz** [comment]
Sorry about not answering sooner... I was actually thinking about this and I'm working in a similar issue in the pydev debugger -- linked above ;)

It seems that the pytest implementation only strips `U+D83D` -- shouldn't it be stripping all the ranges from `(0xD800, 0xDFFF)`?

I'm investigating the fix on the pydev debugger and will try to provide a fix for pytest once I'm done with that on the debugger side.

**Comment by fabioz** [comment]
I.e.: just to give an example, `u"😄"` starts with `u'\ud83d'` and `u"🌐"` starts with `u'\ud83c'`.

**Comment by nicoddemus** [comment]
Good point @fabioz, perhaps it should. Let us know your findings. 👍
