### ISSUE TITLE
Plugins can clobber node IDs, breaking other plugins.

### ISSUE THREAD

**Issue by ericsnowcurrently** [pytest-dev/pytest#5259]
I help maintain [a plugin](https://github.com/microsoft/vscode-python/blob/77a510c/pythonFiles/testing_tools/adapter/pytest.py#L73) that relies on the format of the pytest-provided node ID.  I've run into problems with other plugins that [change the node ID](https://github.com/tonybaloney/pytest-azurepipelines/blob/ce7600b/pytest_azurepipelines.py#L35).  So I'm looking for help on how to deal with this.

Specifically:

* is it okay for plugins to change node IDs?  I.E. should I expect this to happen legitimately?
* is there a way I can get the original node ID (while in `pytest_collection_modifyitems()`)?
* is there a better solution than hoping someone doesn't mess with the node IDs before my `pytest_collection_modifyitems()` gets called?
* can I ensure that my `pytest_collection_modifyitems()` is called first?
* is `pytest_collection_modifyitems()` the earliest place I have access to the list of discovered nodes?

**Comment by ericsnowcurrently** [comment]
FWIW, the azurepipelines plugin I cited above has good reasons for doing what it's doing, but AFAIK doesn't have a better way than changing the node IDs.  I don't want to distract from my original post, but do want to be clear that the clashing plugins here don't seem to have a clear way forward yet.  I'll leave it to @tonybaloney open a separate issue if he wants to. :)

**Comment by RonnyPfannschmidt** [comment]
Any plugin that changes a nodeid is wrong

**Comment by ericsnowcurrently** [comment]
That's what I figured.  Is there any way to guard against bad actors here?

**Comment by RonnyPfannschmidt** [comment]
Not off the bat, in future nodeid will be immutable

**Comment by ericsnowcurrently** [comment]
FWIW, `Node.nodeid` is already a property.  The azurepipelines plugin is actually modifying `Node._nodeid`.

**Comment by ericsnowcurrently** [comment]
FYI, I've opened https://github.com/tonybaloney/pytest-azurepipelines/issues/20, encouraging them to work with the pytest devs to get the functionality they need.

Otherwise, I don't think there's anything left to do here. :)
