### ISSUE TITLE
Confusing assertion rewriting message with byte strings

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5260]
The comparison with assertion rewriting for byte strings is confusing: 
```
    def test_b():
>       assert b"" == b"42"
E       AssertionError: assert b'' == b'42'
E         Right contains more items, first extra item: 52
E         Full diff:
E         - b''
E         + b'42'
E         ?   ++
```

52 is the ASCII ordinal of "4" here.

It became clear to me when using another example:

```
    def test_b():
>       assert b"" == b"1"
E       AssertionError: assert b'' == b'1'
E         Right contains more items, first extra item: 49
E         Full diff:
E         - b''
E         + b'1'
E         ?   +
```

Not sure what should/could be done here.

**Comment by asottile** [comment]
hmmm yes, this ~kinda makes sense as `bytes` objects are sequences of integers -- we should maybe just omit the "contains more items" messaging for bytes objects?

**Comment by blueyed** [comment]
Turns out that it was meant to handle bytes already, but only not for Python 3.
https://github.com/pytest-dev/pytest/pull/5267

**Comment by blueyed** [comment]
> ~kinda makes sense as `bytes` objects are sequences of integers

Yeah, but it was just confusing at first.
Strings are also a sequence of chars, but handled differently.

I've seen another issue recently where it was said that bytes are not decoded on purpose, but I think it is fine for when there are bytes on both sides?!
