### ISSUE TITLE
How to selectively enable a plugin?

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#5272]
I'm trying to use [pytest-black](https://pypi.org/project/pytest-black), but it only installs on Python 3 and I still have projects that depend on Python 2.

Using tox, I [attempted to configure the environment to exclude that plugin on Python 2](https://github.com/jaraco/skeleton/commit/4399038f2eab21f942a5462e0f5b1351e6203873), but when I do, I [still get failures](https://travis-ci.org/jaraco/pip-run/jobs/533076847) when the tests are not explicitly invoked with "py27" but still get Python 2.7.

Is there something I can do to cause pytest to run as if `--black` is indicated, but only when `pytest-black` is installed?

**Comment by blueyed** [comment]
OT: FWIW, I do not recommend using lint checkers together with pytest / tests.
It is better to have it separate for reporting on CI etc.. so I'd use just `black --diff`.

You can have it in the same tox testenv (use "ignore_errors" to keep going).

**Comment by jaraco** [comment]
> I'd use just `black --diff`.

I'm not sure I know how to do that.

> You can have it in the same tox testenv (use "ignore_errors" to keep going).

I don't want it to ignore errors except where expected (such as on Python 2). It should fail where black is available and fails the check.

The reason I'd like it to run as part of the test suite is because it's nice to have the tests run alongside the other tests - you can control selective tests with `-k` and other things. You can easily run it alongside other tests on various Python versions.

**Comment by jaraco** [comment]
I'm tempted to create a new package `pytest-black-multipy` that installs pytest-black (on supported versions) and on other versions supplies a `--black` option that has no effect.

**Comment by jaraco** [comment]
Is there a way to, using `conftest` for example, remove `--black` if it's known not to work?

**Comment by jaraco** [comment]
Or alternately, have it enabled in a config file such that it's only honored if the plugin is present?

**Comment by jaraco** [comment]
I suspect this conftest will suppress errors if `--black` is passed but `pytest-black` isn't present:

```
def pytest_addoption(parser):
    group = parser.getgroup("general")
    if any(
        op.dest == 'black'
        for op in group.options
    ):
        return

    group.addoption(
        "--black",
        action="store",
        dest="name",
        default=False,
        help="Suppress black on older Pythons",
    )
```

**Comment by jaraco** [comment]
I'm not confident I can build a package to implement that conftest ^ and be able to rely on it being called after pytest-black is (conditionally) initialized.

**Comment by jaraco** [comment]
Oh, I guess it could test for `import black` or `import pytest_black`.

**Comment by jaraco** [comment]
I've released the [pytest-black-multipy](https://pypi.org/project/pytest-black-multipy) project with support for Python 2.7+ (does nothing but ignore `--black` on Python 3.5 and earlier). I'm not sure if this is a good model in general, but it serves its purpose.

**Comment by blueyed** [comment]
> > I'd use just `black --diff`.
> 
> I'm not sure I know how to do that.

I've meant to run `black --diff` as a separate job in CI / via a checkqa tox testenv.

> > You can have it in the same tox testenv (use "ignore_errors" to keep going).
> 
> I don't want it to ignore errors except where expected (such as on Python 2). It should fail where black is available and fails the check.

`ignore_errors` with tox means to keep going - i.e. with multiple commands in a testenv.
I've mentioned this since you could then have it after e.g. `pytest`, and the tox env would run both, and fail (exit non-zero) if any of them failed.

> The reason I'd like it to run as part of the test suite is because it's nice to have the tests run alongside the other tests - you can control selective tests with -k and other things. You can easily run it alongside other tests on various Python versions.

But it will e.g. cause (all of) your test jobs fail in case of style issues, instead of having it clearly in a (single) checkqa job.

Anyway, not really related to your question(s)..
