### ISSUE TITLE
PyPy on Azure is timing out

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#5279]
(Follow up to https://github.com/pytest-dev/pytest/pull/5274)

Unfortunately both pypy2 and pypy3 are timing out the builds on Azure while running tests.

**Comment by blueyed** [comment]
Due to latest changes there?

**Comment by nicoddemus** [comment]
No idea, the output just gets stuck at some fixed %, at the last the two times I saw it.

**Comment by blueyed** [comment]
Would be interesting to know if it's the same test there then.
IIRC we had some changes to Azure with regard to PyPy - maybe those could/should be reverted then.
