### ISSUE TITLE
Support loading _conftest.py files as well as conftest.py

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#5280]
Some packages opt to include their test files in the package, so it has been raised the concern that `conftest.py` files are part of the public API and imported by users (https://github.com/pytest-dev/pytest/issues/5255#issuecomment-493218989).

How about we support `conftest.py` *and* `_conftest.py` (non-configurable)?

**Pros**

* Users with embedded tests can use `_conftest.py` files to avoid having `conftest` as part of their public API.
* Strongly suggests you should not import conftest files if they are named `_conftest.py`, which is a common misuse.

**Cons**

* Now there's two "standards" that users need to watch out for when contributing to a project.
* What to do if we have both `conftest.py` and `_conftest.py` in the same directory? Load both or raise an error?
* Don't know what are the repercussion of plugins and tools which currently deal with `conftest.py` files, if any? 

Thoughts?

**Comment by asottile** [comment]
👍 -- it always struck me as odd that it was `conftest.py` and not `_conftest.py` as for the Cons:

- (both "standards") -- yeah this is a bit unfortunate, maybe we can slowly deprecate the current name?
- (both there) if both are there it should error imo -- don't really want to get into ordering / overriding / etc. issues here
- hmm, none that I know of but that's a good point there's probably _something_

**Comment by graingert** [comment]
what about `conf-test.py`?

This makes it so you can't import it without a special mechanism

**Comment by RonnyPfannschmidt** [comment]
private tests folders can have the _ , public testsuites get public conftest, as well, as far as im concerned we shouldnt do anything

**Comment by nicoddemus** [comment]
Yeah I agree, it might bring more problems than it solves.

Closing this for now then.
