### ISSUE TITLE
short test summary: do not truncate messages on CI

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5283]
Currently extra messages for crashes in the short test summary get truncated to the terminal width (based on terminalwriter), but when running on CI there is not really a limit when it comes to e.g. the Travis logs - where the full message could be kept then.

This could be detected by looking at the "CI" environment variable, and/or by checking if stdout is a tty.

**Comment by nicoddemus** [comment]
Checking if stdout is a tty seems the best solution, as it would also work when redirecting the pytest output to a file. 👍

**Comment by blueyed** [comment]
Not sure if that works on e.g. Travis though: it might still simulate a tty there - what is often used to get colors also.  Gave it a shot in https://github.com/pytest-dev/pytest/pull/5284.

**Comment by blueyed** [comment]
Yeah, Travis still truncates it: https://travis-ci.org/pytest-dev/pytest/jobs/533880324#L576

**Comment by nicoddemus** [comment]
Yeah bummer, even on the raw logs this gets truncated

**Comment by blueyed** [comment]
> Yeah bummer, even on the raw logs this gets truncated

They are the same - they only have a special de-ansi mode there to strip escape codes AFAIK.

Should we use `$CI` as a method to detect this additionally?
But then again it could also be controlled by a new setting instead (to be used later in other places also).

**Comment by nicoddemus** [comment]
> Should we use $CI as a method to detect this additionally?
> But then again it could also be controlled by a new setting instead (to be used later in other places also).

I think so, this is the most common use case. If we in the future decide to have a new setting, we can make it the default to $CI if not defined explicitly.

**Comment by henryiii** [comment]
Was this fixed or is there a workaround? I don't see it in the issue, even though it is now closed. On GHA running with nox I still get things like this:

```
SKIPPED [1] tests/test_skbuild.py:178: Requires Windows
FAILED tests/test_cmakelists_not_in_top_level_dir.py::test_build - SystemExit...
FAILED tests/test_cmaker.py::test_get_python_library - AssertionError: assert...
FAILED tests/test_issue284_build_ext_inplace.py::test_build_ext_inplace_command
```

Many of the items are shorted so far I can't even see what failed, and the others still cut the interesting parts off (like what assertion failed). Just curious, thanks!

**Comment by nicoddemus** [comment]
Hasn't been fixed as far as I know @henryiii, will create a follow up. 👍

**Comment by nicoddemus** [comment]
Created: https://github.com/pytest-dev/pytest/issues/9920

**Comment by henryiii** [comment]
Nice, thanks!
