### ISSUE TITLE
pytest.main stop test run

### ISSUE THREAD

**Issue by nivpeter11** [pytest-dev/pytest#5290]
Python: 3.6
OS: MacOs 10.14

I wrap pytest.main with flask service.
I would like to stop the test run sometimes.
Is there a way to do it?

E.g.: 
def test():
   result = pytest.main(params, [self.test_plugins])

**Comment by asottile** [comment]
I would suggest running in a subprocess, that way you can terminate the subprocess via signals

you also get the added benefit of isolating the tests from your webapp -- tests often do some pretty nefarious things (global monkeyaptching, etc.) that could interfere with the internals of flask
