### ISSUE TITLE
assertion diff: do not mark "+" / "-"

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5291]
The leading `+` / `-` appears to be included when marking differing strings always, which is a bit confusing:

```
    def test():
>       assert "foo1" == "foo2"
E       AssertionError: assert 'foo1' == 'foo2'
E         - foo1
E         ?    ^
E         + foo2
E         ?    ^
```

It should look like this instead:
```
    def test():
>       assert "foo1" == "foo2"
E       AssertionError: assert 'foo1' == 'foo2'
E         - foo1
E              ^
E         + foo2
E              ^
```

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell thats intentional and a standard for contextual diff markers, i fail to see how this is confusing,
i consider the removal more problematic

**Comment by blueyed** [comment]
Well, it marks the diff markers itself as being different - not very useful, as this is expected, isn't it?

I do not say "-" / "+" should be removed, but only the "?" below them.

**Comment by RonnyPfannschmidt** [comment]
but the ? are the standard indicator for diff detail indicator lines !?

**Comment by blueyed** [comment]
Oh..  nevermind then.. :D
