### ISSUE TITLE
When other function uses fixture and storing values in list .The list going to empty when pass to parameterized method.But if it is normal test method.The list values as expected .Please help me how to resolve this issue.

### ISSUE THREAD

**Issue by nagarjunakappurapu** [pytest-dev/pytest#5292]
- [x] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by asottile** [comment]
could you elaborate?

**Comment by nagarjunakappurapu** [comment]
page_list=[]
def test_setup(cmdopt):
        base_url = 'original url'
        r = requests.get(base_url + 'sitemap.xml')
        sitemap_root = xmltodict.parse(r.text)
        # page_list = []
        for every_url in sitemap_root['urlset']['url']:
                if '/job/'not in every_url['loc']:
                        page_name = every_url['loc'].split('/')[-1]
                        page_list.append((page_name, every_url['loc']))

@pytest.mark.parametrize("pagename,url",page_list)
def test_eval(pagename, url):

Here the page_list is going to be empty

**Comment by asottile** [comment]
parametrization occurs at test discovery time, before any setup parts run.

If you want to parametrize based on that value you'll want to compute it at the module scope
