### ISSUE TITLE
web site code example doesn't have "import pytest"

### ISSUE THREAD

**Issue by oleg-yegorov** [pytest-dev/pytest#5293]
https://docs.pytest.org/en/latest/fixture.html#override-a-fixture-on-a-test-module-level
tests/conftest.py 
NameError: name 'pytest' is not defined

**Comment by asottile** [comment]
would you like to contribute a patch?  Should be an easy change to https://github.com/pytest-dev/pytest/blob/master/doc/en/fixture.rst#override-a-fixture-on-a-test-module-level

**Comment by oleg-yegorov** [comment]
https://github.com/pytest-dev/pytest/pull/5295
