### ISSUE TITLE
Add millisecond precision in logs

### ISSUE THREAD

**Issue by jurisbu** [pytest-dev/pytest#5296]
There does not seem to be a configurable way to specify that log date should contain millisecond precision.

As far as I can understand the issues is that in `logging.py` default date format is specified as `DEFAULT_LOG_DATE_FORMAT = "%H:%M:%S"` and consecutively it is passed down to Python's `logging.Formatter.formatTime()`. As per documentation https://docs.python.org/3/library/logging.html?#logging.Formatter.formatTime if only `datefmt` would be `None` then we could get millisecond precision in logs.

Unfortunately I have not found a way to pass `None` as `log_date_format` from pytest.ini or commandline options.

`pytest.ini` contents
```
[pytest]
log_format = %(asctime)s %(levelname)-10s [%(name)s] [%(filename)s:%(lineno)d %(funcName)s] %(message)s
```
`t.py`
```python
import logging

LOG = logging.getLogger(__name__)


def test_a():
    LOG.info("BEGIN")
    assert True
    LOG.info("END")
```
Running pytest
```
$ pytest t.py --log-cli-level=INFO
======================================= test session starts =======================================
platform linux -- Python 3.7.2, pytest-4.5.0, py-1.8.0, pluggy-0.11.0 -- /tmp/.venv/bin/python3.7
cachedir: .pytest_cache
rootdir: 
collected 1 item                                                                                  

t.py::test_a 
------------------------------------------ live log call ------------------------------------------
14:13:32 INFO       [t] [t.py:7 test_a] BEGIN
14:13:32 INFO       [t] [t.py:9 test_a] END
PASSED                                                                                      [100%]

==================================== 1 passed in 0.01 seconds =====================================
```

At the moment it seems to get milisecond precision one has to patch `logging.py` to have `DEFAULT_LOG_DATE_FORMAT = None`.

**Comment by thisch** [comment]
Does the msecs option do what you want?

```
 --log-cli-format='%(asctime)s.%(msecs)03d .....'
```

**Comment by jurisbu** [comment]
How did I miss `%(msecs)`? Shame on me! Just what I needed. Thanks @thisch!
Closing this issue!

**Comment by ranjan-osaro** [comment]
If you want to go with how pytest logs by default which is 6 digits and a `Z` at the end, then try this:
```
%(asctime)s.%(msecs)
```

**Comment by ut-adamc** [comment]
> If you want to go with how pytest logs by default which is 6 digits and a `Z` at the end, then try this:
> 
> ```
> %(asctime)s.%(msecs)
> ```

Doesn't work if you are also adding timezone.
