### ISSUE TITLE
Stack traces are lost for tests marked xfail

### ISSUE THREAD

**Issue by allanlewis** [pytest-dev/pytest#5298]
- [x] a detailed description of the bug or suggestion

If a test is marked `xfail`, the stack trace is not recorded anywhere. This makes it difficult to see exactly what the failure was.

- [x] output of `pip list` from the virtual environment you are using

```
Package        Version
-------------- -------
atomicwrites   1.3.0  
attrs          19.1.0 
more-itertools 7.0.0  
pip            19.1.1 
pluggy         0.11.0 
py             1.8.0  
pytest         4.5.0  
setuptools     41.0.1 
six            1.12.0 
wcwidth        0.1.7  
```

- [x] pytest and operating system versions

pytest 4.5.0
Python 3.7.3
Fedora 30

- [x] minimal example if possible

```py
import pytest

def test_fail():
    assert False

@pytest.mark.xfail(reason='foobar')
def test_xfail():
    assert False
```

I'd like to be able to see the stack trace suppressed by the `xfail`.

**Comment by blueyed** [comment]
Have you tried `-rA`?

**Comment by allanlewis** [comment]
> Have you tried `-rA`?

Thanks, but that gives me the xfail reason and not the stack trace.

**Comment by Zac-HD** [comment]
You can [tell pytest to ignore the xfail marker with `pytest --runxfail`](https://docs.pytest.org/en/latest/skipping.html#ignoring-xfail), and the traceback will then be shown as usual.

I don't think it's meaningful to have a traceback for a passing test, so we're unlikely to support anything else.
