### ISSUE TITLE
.github/FUNDING.yml file 

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#5302]
Hey @asottile and @blueyed,

I accidentally committed the [FUNDING.yml](https://github.com/pytest-dev/pytest/blob/master/.github/FUNDING.yml) file directly to `master`, instead of opening a PR like I wanted, while following the instructions from [here](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository): what happened is that I decided to hit "back" in the GH UI before clicking on the button that creates a PR, and that resetted the option to commit from "open a PR" to "commit directly to master" without me noticing.

I think the change is straightforward (0cacdadc978f4f5ec2b5da53dbaaf37401ff8a33), just wanted to let you know what happened and let it registered here that it was an accident. 👍

**Comment by asottile** [comment]
looks good -- thanks for the heads up!  mistakes happen 😆
