### ISSUE TITLE
pypy and pypy3 Exception warnings upon closing

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#5317]
We get a lot of ignored exceptions when the interpreter closes:

```
ResourceWarning: unclosed file <_io.FileIO fd=1114 mode='rb' closefd=True>
Exception ignored in: <_io.FileIO fd=1115 mode='rb' closefd=True>
```

At first glance it seems the capture plugin is not closing files properly.

**Comment by blueyed** [comment]
That are quite a lot - have you checked older logs?  I do not remember seeing that many, i.e. it might be a recent regression.

**Comment by nicoddemus** [comment]
>  have you checked older logs

I haven't... indeed I don't recall seeing so many

**Comment by blueyed** [comment]
Builds on master/features also started to fail: https://travis-ci.org/pytest-dev/pytest/branches

**Comment by blueyed** [comment]
https://travis-ci.org/pytest-dev/pytest/builds/537998957 (master-into-features PR) was OK, let's see how its merge comes out.

**Comment by blueyed** [comment]
As for the CI failures I suspect this is related to the lastest pluggy maybe?!  (at least some failures I've looked at are related to entrypoint-related tests).

**Comment by asottile** [comment]
yes, master failures are expected

releasing 4.6 or merging this will fix `master`: https://github.com/pytest-dev/pytest/pull/5325

**Comment by pierreglaser** [comment]
FYI, I am getting recent failures on `loky` using `pypy` with `pytest >= 4.6`. The root cause seems to be unclosed file descriptors, so it seems related to this issue.

**Comment by asottile** [comment]
I found the root cause of this by the way: 

- issue: https://bitbucket.org/pypy/pypy/issues/3021/ioopen-directory-leaks-a-file-descriptor
- PR: https://bitbucket.org/pypy/pypy/pull-requests/647/fix-leak-of-file-descriptor-with-_iofileio/diff

the same thing is affecting pre-commit's CI as well :S

**Comment by blueyed** [comment]
Awesome.

Can we remove pypy3 until there is some progress / fix in this regard?
Nobody is paying attention to real failures there anyway, and it slows down CI in general, especially now with it being run last due to allowed-failures.

**Comment by nicoddemus** [comment]
> Can we remove pypy3 until there is some progress / fix in this regard?

I agree. We should test it again when a new `pypy3` release comes out.
