### ISSUE TITLE
Return non-zero exit code on unflitered warnings

### ISSUE THREAD

**Issue by aklajnert** [pytest-dev/pytest#5320]
In my pytest configuration I have some warnings filtered out, since they are coming from a third-party libraries. It would be useful to fail tests in case if any warning that is not filtered out will show up.

The `-Werror` option is not useful, as it fails for the filtered warnings.

**Comment by blueyed** [comment]
> The -Werror option is not useful, as it fails for the filtered warnings.

Are you using `python -Werror`, or `python -m pytest -Werror`?

In the latter case your use case might work, if it would happen after the filtering maybe?
Have you tried `python -m pytest -W filtererd -W warnings -W error`?

(just trying to help / get more details, I agree that an option to fail on warnings in general might make sense, and could be added in the `--strict-*` family of options maybe)

**Comment by aklajnert** [comment]
There isn't actually much difference. The `pytest -Werr` crashesh with a slightly nicer error. Besides it's all the same.

Here is a sample code to test it:

```python
import platform


def test_warning():
    assert platform.linux_distribution()

```

`pytest.ini`:

```ini
[pytest]
filterwarnings = ignore::DeprecationWarning
```

The tests will pass with no warnings if you just invoke pytest.   

If you use `python -Werr -m pytest` it seems like it doesn't even run pytest, as it doesn't display the standard information that pytest does (like the platform, versions etc.).   

Running `pytest -Werr` fails test suite even if all warnings are filtered.

I'm not sure if understand how the `python -m pytest -W filtererd -W warnings -W error` example should work. I assume I should adjust it to my example as `python -m pytest -W ignore::DeprecationWarning -W error`. If that's right, then it produces the same output as `pytest -W error`.

**Comment by nicoddemus** [comment]
Hi @aklajnert,

Try using this:

```ini
[pytest]
filterwarnings = 
    error
    ignore::DeprecationWarning
```

This will ignore any deprecation warnings, but will cause an error in all others.

**Comment by aklajnert** [comment]
Hi @nicoddemus,

It works! It is even explicitly said in the documentation and I have missed that. Thank you, I'll close the issue as it is exactly what I needed.
