### ISSUE TITLE
Use capfd in module/session scope

### ISSUE THREAD

**Issue by SHxKM** [pytest-dev/pytest#5321]
I understand the concept of scopes. What I want to do is to call a module-scop fixture and return the `capfd` for other tests.

 I am testing a profiler so I have to use `time.sleep()` in my code. For some instances, I'd like to run the function only once in a fixture, and only return its stdout to test in separate `pytest` tests. This way I can refer to the `stdout` and test portions of it without having to invoke the function and sleeping 2 seconds (or whatever the sleep time is) each time.

```
@profile(2)
def slow_add_self(num):
    time.sleep(2)
    return num + num


@pytest.fixture(scope="module")
def slow_add_console_output(capfd):
    slow_add_self(2)
    out, _ = capfd.readouterr()
    return out


def test_prints(capfd, slow_add_console_output):
    out = slow_add_console_output
    assert "slow_add_self" in out
    assert "seconds" in out

```

The code above throws an error: 

>  You tried to access the 'function' scoped fixture 'capfd' with a 'module' scoped request object

Is there any way around this?

**Comment by SHxKM** [comment]
OK, I thought I managed to solve this by using this:

```
pytest.fixture(scope="module")
def slow_add_arg2_invocation():
    f = io.StringIO()

    with redirect_stdout(f):

        @profile(2)
        def slow_add_self(num):
            """
            slow_add_self is a really nice function. this docstring here is for testing purposes.
            """
            time.sleep(1)
            return num + num

        d = slow_add_self(2)
    stdout = f.getvalue()
```

But I'm worried about side-effects, should I be?

**Comment by Zac-HD** [comment]
Closing this issue as inactive 😕 

I think your workaround is a decent one.
