### ISSUE TITLE
testing a decorator code (coverage) that prints to console

### ISSUE THREAD

**Issue by SHxKM** [pytest-dev/pytest#5324]
So I have a decorator `@profile`, puesdo-code:

    def profile(nums: int = 1, show_args: bool = False, show_kwargs: bool = False):
    
        def middle(func):
            # middle code
    
            pre_message = f"profiling {func.__name__}"
    
            print(pre_message) # how do I test this?
            # more middle code
            def wrapper(*args, **kwargs):
                # wrapper code
                 
    
            return wrapper
    
        return middle

I'm using `pytest` for testing and I can't get coverage to report that the line `print(pre_message)` (for example) is covered. Actually, while my tests do fail and succeed based on `profile`'s (so tests are proper as far as I'm concerned), everything inside of it is reported as uncovered by pytest.

I have tried the following: 

testing with `unittest` mock:

    @unittest.mock.patch("sys.stdout", new_callable=io.StringIO)
    def test_decorator(mock_stdout):
        decorated = profile()
        d = decorated(default_engine)
        assert "profiling" in mock_stdout.getvalue()
        assert callable(decorated)

Tests pass but the print statement is still reported as untested.

    def test_decorator(capfd):
        decorated = profile()
        d = decorated(default_engine)
        out, _ = capfd.readouterr()
        assert "profiling" in out
        assert callable(decorated)

Same. Test pass and fail according to the expected output but coverage reports the lines as uncovered.

I've also tried decorating the `def`s with `@` inside the `test_func`s themselves, and while I get the same test behaviour, coverage is still near 0% for my `profile` code.

In fact, everything in `middle` is reported as untested though I am covering functionality there.

What gives? there must be something I'm missing.

**Comment by blueyed** [comment]
Sounds like the code is executed before the test is run - on import time (when the original function gets decorated).

There are ways to force eager coverage, but your best bet might be to import it from the test function / file / fixture instead.

**Comment by SHxKM** [comment]
> Sounds like the code is executed before the test is run - on import time (when the original function gets decorated).

That's interesting. As said, I'm able to run the tests properly, and they will fail if I change the implementation without updating tests, but I'm unable to get the coverage report to report the lines getting covered.

> There are ways to force eager coverage, but your best bet might be to import it from the test function / file / fixture instead.

Can you please elaborate? I'm pretty new to decorators and too experienced with pytest/pytest-cov.

**Comment by blueyed** [comment]
A decorator wraps a function, and will therefore run when the function is defined - and coverage tracing typically only starts after your tests/code are/is imported.
How do you track coverage?  Try using pytest-cov, which has ways to get early coverage (search for "eager" in its docs, if it does not work out-of-the-box).
Also try putting a `__import__("traceback").print_stack()` or `__import__("pdb").set_trace()` with the uncovered code to see where it gets run from.

**Comment by Zac-HD** [comment]
Closing this as - I hope! - the question has been answered :smile:
