### ISSUE TITLE
Tests in 3.10.1+ takes forever and some are failing

### ISSUE THREAD

**Issue by mxschmitt** [pytest-dev/pytest#5329]
Hi,

We are trying to update our test suite from pytest 3.6.4 to the latest version. But on pytest 4.5 the tests are taking forever and some are failing.

So I tried version by versions to find the cause which version will cause this issue and saw, that in version 3.10.0 everything is working fine. But once I upgrade to version 3.10.1 the tests are extremely slow and some are failing.

<details>
<summary>PIP list</summary>

Package                          Version   
-------------------------------- ----------
adal                             1.2.1     
aiodns                           2.0.0     
aiohttp                          3.5.4     
amqp                             2.4.1     
aniso8601                        3.0.2     
appnope                          0.1.0     
argon2-cffi                      19.1.0    
asn1crypto                       0.24.0    
aspy.yaml                        1.2.0     
async-timeout                    3.0.1     
atomicwrites                     1.3.0     
attrs                            18.2.0    
autopep8                         1.4.4     
awesome-slugify                  1.6.5     
azure                            2.0.0     
azure-batch                      3.0.0     
azure-common                     1.1.21    
azure-datalake-store             0.0.45    
azure-graphrbac                  0.30.0    
azure-keyvault                   0.3.7     
azure-mgmt                       1.0.0     
azure-mgmt-authorization         0.30.0    
azure-mgmt-batch                 4.0.0     
azure-mgmt-cdn                   0.30.3    
azure-mgmt-cognitiveservices     1.0.0     
azure-mgmt-compute               1.0.0     
azure-mgmt-containerregistry     0.2.1     
azure-mgmt-datalake-analytics    0.1.6     
azure-mgmt-datalake-nspkg        3.0.1     
azure-mgmt-datalake-store        0.1.6     
azure-mgmt-devtestlabs           2.0.0     
azure-mgmt-dns                   1.0.1     
azure-mgmt-documentdb            0.1.3     
azure-mgmt-iothub                0.2.2     
azure-mgmt-keyvault              0.31.0    
azure-mgmt-logic                 2.1.0     
azure-mgmt-monitor               0.2.1     
azure-mgmt-network               1.0.0     
azure-mgmt-nspkg                 3.0.2     
azure-mgmt-rdbms                 0.1.0     
azure-mgmt-redis                 4.1.1     
azure-mgmt-resource              1.1.0     
azure-mgmt-scheduler             1.1.3     
azure-mgmt-sql                   0.5.3     
azure-mgmt-storage               1.0.0     
azure-mgmt-trafficmanager        0.30.0    
azure-mgmt-web                   0.32.0    
azure-nspkg                      3.0.2     
azure-servicebus                 0.21.1    
azure-servicefabric              5.6.130   
azure-servicemanagement-legacy   0.20.6    
azure-storage                    0.36.0    
Babel                            2.6.0     
backcall                         0.1.0     
bcrypt                           3.1.6     
billiard                         3.6.0.0   
boltons                          19.1.0    
boto3                            1.9.123   
botocore                         1.12.136  
cached-property                  1.5.1     
celery                           4.3.0     
certifi                          2018.11.29
cffi                             1.12.2    
cfgv                             1.5.0     
chardet                          3.0.4     
cli-helpers                      1.1.0     
Click                            7.0       
codecov                          2.0.15    
configobj                        5.0.6     
coreapi                          2.3.3     
coreschema                       0.0.4     
coverage                         4.5.2     
cryptography                     2.5       
decorator                        4.3.2     
defusedxml                       0.5.0     
diff-match-patch                 20181111  
dj-database-url                  0.5.0     
Django                           2.2.1     
django-admin-tools               0.8.1     
django-allauth                   0.39.1    
django-appconf                   1.0.2     
django-braces                    1.13.0    
django-cities                    0.5.0.6   
django-cors-headers              2.5.2     
django-coverage-plugin           1.6.0     
django-crispy-forms              1.7.2     
django-csp                       3.5       
django-environ                   0.4.5     
django-extensions                2.1.7     
django-filter                    2.1.0     
django-imagekit                  4.0.2     
django-import-export             1.2.0     
django-js-asset                  1.2.2     
django-middleware-global-request 0.1.1     
django-model-utils               3.1.2     
django-mptt                      0.9.1     
django-phonenumber-field         2.0.0     
django-phonenumbers              1.0.1     
django-redis                     4.10.0    
django-redis-sessions-fork       0.7.0     
django-rest-auth                 0.9.5     
django-reversion                 3.0.3     
django-s3-storage                0.12.4    
django-test-plus                 1.1.1     
djangorestframework              3.9.4     
djangorestframework-gis          0.14      
djangorestframework-recursive    0.1.2     
docutils                         0.14      
drf-extensions                   0.5.0     
drf-yasg                         1.15.0    
entrypoints                      0.3       
et-xmlfile                       1.0.1     
fabric                           2.4.0     
factory-boy                      2.11.1    
Faker                            1.0.2     
flake8                           3.6.0     
flake8-blind-except              0.1.1     
flake8-commas                    2.0.0     
flake8-comprehensions            2.1.0     
flake8-debugger                  3.1.0     
flake8-docstrings                1.3.0     
flake8-mutable                   1.2.0     
flake8-polyfill                  1.0.2     
flake8-print                     3.1.0     
flake8-quotes                    1.0.0     
flake8-tuple                     0.2.14    
future                           0.17.1    
graphene                         2.1.3     
graphene-django                  2.2.0     
graphql-core                     2.1       
graphql-relay                    0.4.5     
hiredis                          1.0.0     
html5lib                         1.0.1     
humanize                         0.5.1     
identify                         1.4.0     
idna                             2.8       
importlib-metadata               0.15      
inflection                       0.3.1     
invoke                           1.2.0     
ipdb                             0.11      
ipython                          7.3.0     
ipython-genutils                 0.2.0     
isodate                          0.6.0     
isort                            4.3.20    
itypes                           1.1.0     
jdcal                            1.4       
jedi                             0.13.3    
jet-django                       0.5.9     
Jinja2                           2.10      
jmespath                         0.9.4     
keyring                          19.0.2    
kombu                            4.5.0     
lxml                             4.3.3     
MarkupSafe                       1.1.1     
maxminddb                        1.4.1     
maxminddb-geolite2               2018.703  
mccabe                           0.6.1     
mime                             0.1.0     
more-itertools                   6.0.0     
msrest                           0.6.6     
msrestazure                      0.4.34    
multidict                        4.5.2     
nodeenv                          1.3.3     
numpy                            1.16.2    
oauthlib                         3.0.1     
odfpy                            1.4.0     
openpyxl                         2.6.0     
packaging                        19.0      
paramiko                         2.4.2     
parso                            0.3.4     
pep8                             1.7.1     
pep8-naming                      0.8.2     
pexpect                          4.6.0     
pgcli                            2.0.2     
pgspecial                        1.11.5    
phonenumbers                     8.10.6    
phonenumberslite                 8.10.6    
pickleshare                      0.7.5     
pilkit                           2.0       
Pillow                           5.3.0     
pip                              18.1      
pip-tools                        3.5.0     
pip-upgrade                      0.0.6     
pipdeptree                       0.13.2    
pluggy                           0.12.0    
pre-commit                       1.12.0    
promise                          2.2.1     
prompt-toolkit                   2.0.9     
psycopg2                         2.7.7     
psycopg2-binary                  2.7.6.1   
ptvsd                            4.2.4     
ptyprocess                       0.6.0     
py                               1.8.0     
pyasn1                           0.4.5     
pycares                          3.0.0     
pycodestyle                      2.4.0     
pycountry                        18.12.8   
pycparser                        2.19      
pycrypto                         2.6.1     
pydevd                           1.6.1     
pydocstyle                       3.0.0     
pyflakes                         2.0.0     
Pygments                         2.3.0     
PyJWT                            1.7.1     
PyNaCl                           1.3.0     
pyparsing                        2.3.1     
PyPDF2                           1.26.0    
pytest                           3.10.0    
pytest-cov                       2.7.1     
pytest-cov-threshold             0.1.0     
pytest-django                    3.4.8     
pytest-sugar                     0.9.2     
python-dateutil                  2.8.0     
python-http-client               3.1.0     
python-magic                     0.4.15    
python3-openid                   3.1.0     
pytz                             2018.7    
PyYAML                           3.13      
raven                            6.9.0     
redis                            3.2.1     
regex                            2019.2.21 
reportlab                        3.5.13    
requests                         2.21.0    
requests-file                    1.4.3     
requests-oauthlib                1.2.0     
responses                        0.10.6    
reverse-geocoder                 1.5.1     
ruamel.yaml                      0.15.89   
Rx                               1.6.1     
s3transfer                       0.2.0     
scipy                            1.2.1     
sendgrid                         3.6.5     
sendgrid-django                  4.2.0     
setproctitle                     1.1.10    
setuptools                       40.6.2    
simplegeneric                    0.8.1     
singledispatch                   3.4.0.3   
six                              1.12.0    
slackclient                      2.0.1     
snowballstemmer                  1.2.1     
sqlparse                         0.2.4     
swapper                          1.1.0     
tablib                           0.12.1    
tabulate                         0.8.3     
termcolor                        1.1.0     
terminaltables                   3.1.0     
text-unidecode                   1.2       
tldextract                       2.2.1     
toml                             0.10.0    
tqdm                             4.31.1    
traitlets                        4.3.2     
unicodecsv                       0.14.1    
Unidecode                        0.4.21    
uritemplate                      3.0.0     
urllib3                          1.24.1    
uWSGI                            2.0.17.1  
vine                             1.3.0     
virtualenv                       16.4.3    
wcwidth                          0.1.7     
webencodings                     0.5.1     
websocket-client                 0.54.0    
Werkzeug                         0.14.1    
wheel                            0.33.4    
xhtml2pdf                        0.2.3     
xlrd                             1.1.0     
xlwt                             1.3.0     
yarl                             1.3.0     
zipp                             0.5.1  

</details>

I would appreciate any help.

Thanks in advance

Max

**Comment by RonnyPfannschmidt** [comment]
there have been a number of commits that could have caused this in between https://github.com/pytest-dev/pytest/compare/3.10.0...3.10.1

if you could pinpoint the exact commit/merge which broke the world for you and/or provide more details, it would really help us figure what triggers the issue

atm we know nothing about your test-suite and lack any information to figure the issue

**Comment by mxschmitt** [comment]
@RonnyPfannschmidt 
it's hard to say, I will continue testing with specific commits later. But the main issue, why it takes so long, is that the incorrect amount of tests will be collected.
There are 2329 items collected but it should only be 361 collected (before upgrading pytest)
=> over six times more, very weird

**Comment by mxschmitt** [comment]
@RonnyPfannschmidt I'm so sorry. I found out, that in the codebase was the `--keep-duplicates` flag set...

**Comment by RonnyPfannschmidt** [comment]
thanks for the feedback
i'm glad its just a easily missed configuration issue and not a bug in pytest
happy testing
