### ISSUE TITLE
ResourceWarning during collection

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5342]
Using pypy3 I see this reliably (`tox -e pypy3 -- -m 'not slow'`):
```
collecting ... Exception ignored in: <_io.FileIO fd=3 mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.FileIO fd=3 mode='rb' closefd=True>
collected 2422 items / 1675 deselected / 747 selected
```

```
Python 3.6.1 (784b254d669919c872a505b807db8462b6140973, May 09 2019, 13:17:30)
[PyPy 7.1.1-beta0 with GCC 8.3.0]
```

Not on master, and only with `usedevelop = true`.

**Comment by asottile** [comment]
Is this with coverage? I'm seeing similar things in pre-commit: https://github.com/nedbat/coveragepy/issues/807

**Comment by blueyed** [comment]
No, that was not with coverage (just `-e pypy3`, not `-e pypy3-coverage`).

**Comment by blueyed** [comment]
The interesting part about https://github.com/nedbat/coveragepy/issues/807 is also that you're able to catch the ResourceWarnings there, isn't it?

**Comment by blueyed** [comment]
Closing as likely to be a duplicate of https://github.com/pytest-dev/pytest/issues/5317.
