### ISSUE TITLE
doctest fail because it doesn't like any ~/.pdbrc.py

### ISSUE THREAD

**Issue by pawciobiel** [pytest-dev/pytest#5345]
- [*] a detailed description of the bug or suggestion
Pytest doctest failes because it can not import empty or any ~/.pdbrc.py

Doctest:
```
>>> exist_fn = lambda fn: fn in ('file.txt', 'file_1.txt')
```

pytest.ini
```
[pytest]
norecursedirs=dist build .tox .eggs scripts
#addopts=--doctest-modules --flake8 --cov
addopts=--doctest-modules
doctest_optionflags=ALLOW_UNICODE ELLIPSIS
filterwarnings=
	ignore:Possible nested set::pycodestyle:113
	ignore:Using or importing the ABCs::flake8:410
	# workaround for https://sourceforge.net/p/docutils/bugs/348/
	ignore:'U' mode is deprecated::docutils.io
	# workaround for https://gitlab.com/pycqa/flake8/issues/275
	ignore:You passed a bytestring as `filenames`.::flake8
	ignore:::newrelic.console:71
	ignore:::cherrypy._cpchecker:105
	ignore:Using or importing the ABCs::newrelic.packages.requests
```

empty ~/.pdbrc.py

Error output: 
```
____________________________ [doctest] x.lib.storage.unique_name ____________________________
...
106 
107     >>> exist_fn = lambda fn: fn in ('file.txt', 'file_1.txt')
Expected nothing
Got:
    ** error when importing ~/.pdbrc.py: 'Config' **

x/lib/storage.py:107: DocTestFailure
```

- [*] output of `pip list` from the virtual environment you are using
```
pdbpp==0.9.3
pytest==4.3.0
pytest-cov==2.6.1
pytest-cover==3.0.0
pytest-coverage==0.0
pytest-flake8==1.0.4
```

- [*] pytest and operating system versions
pytest==4.3.0
ubuntu bionic 18.04 AMD64
Python 2.7.14

- [*] minimal example if possible
Doctest:
```
>>> exist_fn = lambda fn: fn in ('file.txt', 'file_1.txt')
```

**Comment by blueyed** [comment]
1. you should upgraded pdb++ :)
2. you should try latest pytest

Works for me using:
```python
class Foo:
    """
    >>> print(1)
    1
    """
```
And `pytest --doctest-modules t-doctest.py`.

Any extra output from ~/.pdbrc.py though will show up, and cause a test failure.

How does your `~/.pdbrc.py` look like?

With later pdb++ you can use `PDBPP_HIJACK_PDB=0` in the environment (might required pdbpp master).

**Comment by blueyed** [comment]
One more question: do you see this with regular tests also, e.g. with a failing one, and using `--pdb`?

**Comment by pawciobiel** [comment]
Updated pytest and pdbpp but unfortunately the result is the same.
pytest-4.5.0, pdbpp-0.10.0

`~/.pdbrc.py` file is just an empty file.
I tried adding 
```from pprint import pprint```
to it but the error is the same.
It also fails with `--doctest-modules` as well as with `--pdb`.

The code is this:
```
def unique_name(candidates, exists): 
    """
    Given a series of candidate names and a function that checks for
    existence, return the first name that doesn't exist.              

    >>> exist_fn = lambda fn: fn in ('file.txt', 'file_1.txt')
    >>> unique_name(numbered_files('some file.txt'), exist_fn)
    'some file.txt' 
    >>> unique_name(numbered_files('file.txt'), exist_fn)
    'file_2.txt'
    >>> candidates = numbered_files('file.txt', format='{name} ({num}){ext}')
    >>> unique_name(candidates, exist_fn)
    'file (1).txt'
    """
    return next(six.moves.filterfalse(exists, candidates)) 
    
```

The output 
```
____________________________ [doctest] x.lib.storage.unique_name ____________________________

107     >>> exist_fn = lambda fn: fn in ('file.txt', 'file_1.txt')
Expected nothing
Got:
    ** error when importing ~/.pdbrc.py: 'Config' **

x/lib/storage.py:107: DocTestFailure
```

**Comment by blueyed** [comment]
I see.

It is an issue with pdbpp (or rather fancycompleter), which expects a `Config` class in `~/.pdbrc.py` (https://github.com/pdbpp/fancycompleter/blob/35e892813fa0b5d071bb6dcc6d960bcdc14bb75e/fancycompleter.py#L202).

So as a workaround either add actual config therein, or not have the file in the first place I guess?! :)

Created https://github.com/pdbpp/fancycompleter/issues/12 to track this.

**Comment by blueyed** [comment]
> I don't see this with regular tests, only doc test, it doesn't matter if I use --pdb or not,

Not true, is it?

Given `t-fail.py`:
```python
def test_fail(): assert 0
```
```
% pytest --pdb t-fail
==================================== test session starts ====================================
platform linux -- Python 3.7.3, pytest-4.5.1.dev117+gd6ce2e585.d20190530, py-1.8.0, pluggy-0.11.0
…
collected 1 item                                                                            

t-fail.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>   def test_fail(): assert 0
E   assert 0

t-fail.py:1: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>
** error when importing ~/.pdbrc.py: 'Config' **
[11] > /home/user/Vcs/pytest/t-fail.py(1)test_fail()
-> def test_fail(): assert 0
   6 frames hidden (try 'help hidden_frames')
(Pdb++) 
```

**Comment by blueyed** [comment]
Fixed in fancycompleter (master), also printing to stderr in case of real errors now, which does not cause doctest failures then..

**Comment by pawciobiel** [comment]
thank you! :-)

**Comment by blueyed** [comment]
You're welcome!  Happy to see a pdb++ user.. :)
