### ISSUE TITLE
Accessing builtins attr fails non-deteminstically

### ISSUE THREAD

**Issue by scopatz** [pytest-dev/pytest#5348]
This was originally reported by @carmenbianca on https://github.com/xonsh/xonsh/issues/3070 but is something that we have noticed for a while.  Basically, pytest is super unstable when it comes to attribute access of the `builtins` module.  For example, we frequently see the following error:

```
    def load_builtins(execer=None, ctx=None):
        """Loads the xonsh builtins into the Python builtins. Sets the
        BUILTINS_LOADED variable to True.
        """
        global BUILTINS_LOADED
        if not hasattr(builtins, "__xonsh__"):
            builtins.__xonsh__ = XonshSession(execer=execer, ctx=ctx)
        builtins.__xonsh__.load(execer=execer, ctx=ctx)
>       builtins.__xonsh__.link_builtins(execer=execer)
E       AttributeError: module 'builtins' has no attribute '__xonsh__'
```

This is strange because it is failing to access `builtins.__xonsh__` on a line after we have ensured that `__xonsh__` is there AND accessed it on the previous line.  There must be some side effect in pytest that is improperly removing this builtin. Note that we do a lot of work [in the conftest.py](https://github.com/xonsh/xonsh/blob/master/tests/conftest.py#L36) to makes sure that the `__xonsh__` object is there.

This happens on pytest 4.5.0 and across Windows, Mac, and Linux at least. The original bug report comes from redhat.  

Happy to help with further debugging.

**Comment by scopatz** [comment]
You can also see this issue in the fixure in [this build log](https://dev.azure.com/xonsh/xonsh/_build/results?buildId=738&view=logs&jobId=d4c41d73-cbb1-5e00-d063-646f265db4d9&taskId=a00e5170-e0a0-5d4d-cbed-6c8fd2918c0d&lineStart=132&lineEnd=133&colStart=1&colEnd=1). 

```
=================================== ERRORS ====================================
____________________ ERROR at setup of test_xonsh_failback ____________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x0000025D941FAA58>
xonsh_events = <xonsh.events.EventManager object at 0x0000025D8C777198>

    @pytest.fixture
    def xonsh_builtins(monkeypatch, xonsh_events):
        """Mock out most of the builtins xonsh attributes."""
        old_builtins = set(dir(builtins))
        execer = getattr(getattr(builtins, "__xonsh__", None), "execer", None)
        session = XonshSession(execer=execer, ctx={})
        ensure_attached_session(monkeypatch, session)
        builtins.__xonsh__.env = DummyEnv()
        if ON_WINDOWS:
            builtins.__xonsh__.env["PATHEXT"] = [".EXE", ".BAT", ".CMD"]
        builtins.__xonsh__.shell = DummyShell()
        builtins.__xonsh__.help = lambda x: x
        builtins.__xonsh__.glob = glob.glob
        builtins.__xonsh__.exit = False
        builtins.__xonsh__.superhelp = lambda x: x
        builtins.__xonsh__.pathsearch = pathsearch
        builtins.__xonsh__.globsearch = globsearch
        builtins.__xonsh__.regexsearch = regexsearch
        builtins.__xonsh__.regexpath = lambda x: []
        builtins.__xonsh__.expand_path = lambda x: x
        builtins.__xonsh__.subproc_captured = sp
        builtins.__xonsh__.subproc_uncaptured = sp
        builtins.__xonsh__.stdout_uncaptured = None
        builtins.__xonsh__.stderr_uncaptured = None
        builtins.__xonsh__.ensure_list_of_strs = ensure_list_of_strs
        builtins.__xonsh__.commands_cache = DummyCommandsCache()
        builtins.__xonsh__.all_jobs = {}
        builtins.__xonsh__.list_of_strs_or_callables = list_of_strs_or_callables
        builtins.__xonsh__.list_of_list_of_strs_outer_product = (
            list_of_list_of_strs_outer_product
        )
>       builtins.__xonsh__.history = DummyHistory()
E       AttributeError: module 'builtins' has no attribute '__xonsh__'

tests\conftest.py:135: AttributeError
```

**Comment by scopatz** [comment]
Pinging this

**Comment by nicoddemus** [comment]
Hi @scopatz,

This is really strange. The only places I can see `builtins` being explicitly referenced in pytest are as follows:

Just some traback generation code:

https://github.com/pytest-dev/pytest/blob/240828d91245bd39d058f9d29ad5f2360e95368d/src/_pytest/_code/code.py#L639-L640

Hacks to show shorter tracebacks:

https://github.com/pytest-dev/pytest/blob/240828d91245bd39d058f9d29ad5f2360e95368d/src/_pytest/main.py#L351-L354

https://github.com/pytest-dev/pytest/blob/240828d91245bd39d058f9d29ad5f2360e95368d/src/_pytest/outcomes.py#L34-L47

Assertion rewriter making an alias to ensure we access the true `builtins` when needed:

https://github.com/pytest-dev/pytest/blob/240828d91245bd39d058f9d29ad5f2360e95368d/src/_pytest/assertion/rewrite.py#L601-L604

https://github.com/pytest-dev/pytest/blob/240828d91245bd39d058f9d29ad5f2360e95368d/src/_pytest/assertion/rewrite.py#L687-L689

--- 

Do you have different results with `--assert=plain`?

**Comment by scopatz** [comment]
Ok, [here is a build](https://circleci.com/gh/xonsh/xonsh/6078?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) with the same issue using `--assert=plain` on xonsh/xonsh#3173 which shows the same problem

**Comment by jnoortheen** [comment]
I think this is no longer the case. Please reopen if needed.
