### ISSUE TITLE
When we execute 100 test cases under the folder, can we support real-time report generation?

### ISSUE THREAD

**Issue by imhoule** [pytest-dev/pytest#5369]
- [ ] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by asottile** [comment]
I'm not sure what you mean, could you please clarify?  Does `-v` satisfy your usecase?

**Comment by nicoddemus** [comment]
Perhaps [`pytest-instafail`](https://pypi.org/project/pytest-instafail/)?

> pytest-instafail is a plugin for py.test that shows failures and errors instantly instead of waiting until the end of test session.

**Comment by imhoule** [comment]
When we execute multiple use cases in a folder, we can generate test reports through pytest-html, but we need to wait until the use cases are executed. Is it possible to obtain the current running status in real time and generate real-time test reports during the execution of use cases?

**Comment by nicoddemus** [comment]
If you want to see it in a file, you can use the `--resultlog` option. It is somewhat deprecated because we want to provide a different alternative but which fits the same requirements, but you are welcome to try it out to see how it works out for you.
