### ISSUE TITLE
Capsys scope mismatch

### ISSUE THREAD

**Issue by LEscobar-Driver** [pytest-dev/pytest#5414]
Within my root conftest.py file I have a session scoped fixture which outputs text to console with certain statistics about all the tests. 

Currently I am passing the -s flag to ensure this text prints but that produces a lot of system wide garbage output. 

I am attempting to use **with capsys.disabled():** to ensure my statistics print to console but that produces as ScopeMismatch error. 

How can I ensure that my output is printed into console????

**pytest version**
4.5.0

**os**
MacOS Mojave v 10.14.5

**Comment by nicoddemus** [comment]
Hi @LEscobar-Driver,

Unfortunately this not currently possible as `capsys` is function-scoped. 

You can try to use [`contextlib.redirect_stdout`](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout) in your session-scoped fixture to suppress its output.

**Comment by LEscobar-Driver** [comment]
> Unfortunately this not currently possible as capsys is function-scoped.

dang, that really sucks. Is there going to be a re-write of **capsys** to introduce this feature? 

So if I want to print something to console without using the **-s** flag, I have to use `contextlib.redirect_stdout` ? Are there any alternatives that have been found to essentially duplicate `capsys` in methods that are not function scoped?

**Comment by nicoddemus** [comment]
> dang, that really sucks. Is there going to be a re-write of capsys to introduce this feature?

No plans, and given that `capture` is quite complicated already, I'm afraid this will happen any time soon (or at all).

> So if I want to print something to console without using the -s flag, I have to use contextlib.redirect_stdout ?

No, that's actually meant to suppress output.

If you have test statistics to show, you can perhaps implement [`pytest_report_header`](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_report_header) or [`pytest_terminal_summary`](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_terminal_summary).

**Comment by LEscobar-Driver** [comment]
Thanks for the feedback, `pytest_terminal_summary` will work well for my purposes.
