### ISSUE TITLE
sys.prefix is lowercased when running under pytest on Windows

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [pytest-dev/pytest#5417]
### To reproduce

1. Create the following file (let's name it `my_test.py`):
```python
import sys
print(sys.prefix)
```

2. Run `pytest -s -v`

### Expected result

It should print, among other things, "C:\Python3.7" (because that's where I have Python installed).

### Actual result

It prints it in lower case, "c:\python3.7".

```
=========================================================== test session starts ===========================================================
platform win32 -- Python 3.7.3, pytest-4.5.0, py-1.8.0, pluggy-0.12.0 -- c:\python37\python.exe
cachedir: .pytest_cache
rootdir: C:\temp
plugins: cov-2.7.1
collecting ... c:\python37
collected 0 items

====================================================== no tests ran in 0.05 seconds =======================================================

```

It works as expected when I run this script without `pytest`:
```
> python my_test.py
C:\Python3.7
```

**Comment by nicoddemus** [comment]
Strange, I cannot reproduce this... 🤔 

```
λ pytest .tmp\test-foo.py -q -s
D:\Miniconda3
```

**Comment by Vlad-Shcherbina** [comment]
Thank you!

I looked at it closer and it seems all scripts installed to `C:\Python37\Scripts` by pip have shebang `#!c:\python37\python.exe`. This includes `pytest.exe`.

No idea why, but in any case, `pytest` is not to blame.

I was able to get the expected behavior by running `python -m pytest` instead of `pytest`.

**Comment by nicoddemus** [comment]
Great, thanks for the follow up!
