### ISSUE TITLE
id parameter in pytest.params 

### ISSUE THREAD

**Issue by Joeycho** [pytest-dev/pytest#5426]
Versions :
pytest version: 4.5.0
OS version : 4.13.0-43-generic #48~16.04.1-Ubuntu

Hello, there! I am on my way to learn how to use pytest, and here is my question!

Sample code:
```python
import pytest

@pytest.mark.parametrize("test_input,expected", [
    ("3+5", 8),("6*8", 43),pytest.param("4*5", 20, marks=pytest.mark.xfail),
    pytest.param("6*9", 42, marks=pytest.mark.xfail),
])

def test_eval(test_input, expected):
    assert eval(test_input) == expected
```

I used the above code to understand what are the marks in pytest, and get used to with 'parametrize'. I regard 'parametrize' is special testing way in pytest. So, I want to be used to it.
Back to the code, [1] how can I use 'id parameter' in pytest.params? I think in the above code, except explicit marks parameters, all are values. [1]How can I use 'id parameter' with the above sample code?

Another question is about 'xfail'. So, this only can result in 'xfail(expected fail(actual fail, but categorized as 'xfail'' or 'Fail(when it success, unexpected success)'. That's how I can understand 'xfail' now.  

[2]In the result from pytest, simply, 'pass', 'fail', 'xfail', 'error', are these four signs from pytest? Can we have 'xpass' or customized test result sign in pytest?

In the pytest, I checked 'skip', 'skipif', 'xfail', and 'parametrize' as built-in marks. However, since I am more curious about the test result, it would be great to know the answer of [2] question.

**Comment by asottile** [comment]
the `id` parameter allows you to customize the test name, taking from your example:

```python
import pytest

@pytest.mark.parametrize("test_input,expected", [
    ("3+5", 8),("6*8", 43),pytest.param("4*5", 20, marks=pytest.mark.xfail),
    pytest.param("6*9", 42, marks=pytest.mark.xfail, id='life and the universe'),
])

def test_eval(test_input, expected):
    assert eval(test_input) == expected
```

```console
$ pytest -vv t.py
...
t.py::test_eval[life and the universe] XFAIL                             [100%]
...
```

notice how the test id changed

As for your second question, these are the states:
- PASS
- FAIL
- ERROR
- SKIP
- XFAIL
- XPASS (passed but expected failure)

I believe XPASS is the one you're interested about?

Notice that your test currently has an  xpass result as well:

```console
$ pytest -vv t.py
...
t.py::test_eval[4*5-20] XPASS                                            [ 75%]
...
```

**Comment by Joeycho** [comment]
@asottile 

Hi! Yes, I was quite interested in XPASS as well. Since I could not see XPASS state without '-vv' flag.

Probably '-vv' flag shows more in detail.

Thanks for your clear answer! It helped me a lot to understand :)

**Comment by asottile** [comment]
cheers! thanks for the issue 🎉
