### ISSUE TITLE
Higher level directory on sys.path causing double import of module

### ISSUE THREAD

**Issue by phoolish-philomath** [pytest-dev/pytest#5431]
Directory structure looks like:
```
project/
└── foo/
     ├── pytest.ini
     ├── __init__.py/
     ├── libs/
     |      ├── __init__.py
     |      ├── baz.py
     |      └── bam.py
     └── tests/
            ├── __init__.py
            └── test_foo.py
```
```python
# test_bar.py:
from ..libs.baz import Baz
from ..libs.bam import Bam

Bam.startup()
Baz.doSomethingWithBam()
```
```python
# baz.py:
from .bam import Bam

class Baz:
     def doSomethingWithBam():
           # needs Bam to be started up
           ...
```
When I print `sys.path` from `test_bar`, `sys.path[0]` is the path to the parent directory of project and and `sys.path[1]` is the path to project. When I print `sys.modules`, I see 2 copies of `bam.py`, one from `sys.path[0]` and one from `sys.path[1]`.

The problem is that I need a single instance of `Bam` to be shared across all the code but `test_bar` is using one instance of `Bam` and `baz.py` is using the other.

According to https://docs.pytest.org/en/latest/pythonpath.html#pythonpath, pytest is behaving as expected by adding the parent of project to `sys.path`. However, this is breaking my tests and I would like to know if there's something I can do to avoid it.

Thanks!

**System: Ubuntu 18.04.1, Python 3.7, pytest 4.4.1**

<details><summary>`pip freeze` output</summary>

aioredis              1.2.0   
apipkg                1.5     
arrow                 0.13.1  
asn1crypto            0.24.0  
async-timeout         3.0.1   
atomicwrites          1.3.0   
attrs                 19.1.0  
certifi               2019.3.9
cffi                  1.12.3  
chardet               3.0.4   
cryptography          2.6.1   
execnet               1.6.0   
hiredis               1.0.0   
idna                  2.8     
linecache2            1.0.0   
loggly-python-handler 1.0.0   
more-itertools        7.0.0   
mypy                  0.701   
mypy-extensions       0.4.1   
pip                   19.0.3  
pluggy                0.9.0   
psutil                5.4.8   
py                    1.8.0   
pycparser             2.19    
pydash                4.7.3   
pytest                4.4.1   
pytest-asyncio        0.10.0  
pytest-cache          1.0     
pytest-timeout        1.3.3   
pytest-xprocess       0.12.1  
python-dateutil       2.8.0   
requests              2.21.0  
requests-futures      0.9.7   
ruamel.yaml           0.15.91 
setuptools            40.8.0  
six                   1.12.0  
traceback2            1.4.0   
typed-ast             1.3.4   
unittest2             1.1.0   
urllib3               1.24.2  
wheel                 0.33.1  

</details>

**Comment by RonnyPfannschmidt** [comment]
its  not clear how exactly you run pytest and if there is an editable install

based on the folder structure there should only be one module, os this seems to be a bug

**Comment by phoolish-philomath** [comment]
Thanks for the response. 
I am running pytest from project/
```
python -m pytest foo/tests/test_foo.py
```
I'm not totally sure what an editable install is but I don't have a setup.py for project, if that helps to know.

There is actually an extra directory "layer" in my project structure. I wasn't sure if it mattered but I'll include a more accurate directory structure here:
```
project/
├── foo/
     ├── foo_1/
     ├── foo_2/
          ├── __init__.py
          ├── libs/
                 ├── __init__.py
                 ├── baz.py
                 ├── bam.py
          ├── tests/
                 ├── __init__.py
                 └─ integration_tests
                       ├── __init__.py
                       └─ test_foo_1.py
     ├── pytest.ini
     └─ __init__.py/
  
```

**Comment by RonnyPfannschmidt** [comment]
as a starting point, use `py.test` instead of `python -m pytest` - i suspect that this could already sort out the `sys.path` issue

**Comment by phoolish-philomath** [comment]
I tried running (from project):
```
py.test foo/foo_2/tests/integration_tests/test_foo_2.py::test_foo_2_basic
```
This only works if I get rid of `__init__.py` from project/. With `__init__.py`, I get the error:
```
ERROR: not found: <path to project>/foo/foo_2/tests/integration_tests/test_foo_2.py::test_foo_2_basic
(no name '<path to project>/foo/foo_2/tests/integration_tests/test_foo_2.py::test_foo_2_basic' in any of [<Module test_foo_2.py>])
```

When I run
```
python -m pytest foo/foo_2/tests/integration_tests/test_foo_2.py::test_foo_2_basic
```
it works if I remove __init__.py from project/ but breaks because of the issue I originally reported if I keep __init__.py
