### ISSUE TITLE
Allow using unittest asserts with pytest without TestCase

### ISSUE THREAD

**Issue by pakal** [pytest-dev/pytest#5443]
The stdlib unittests are full of useful test utilities to perform tests on sets, dict (see https://github.com/pytest-dev/pytest/issues/2376), etc. And other frameworks add their own layer on top of that, like Django adding assertXXXX to test templates and responses.

How about mixing the best of both worlds ? These assertXXXX are, for a reason I can't get, real methods and not classmethods (whereas they visibly never used the instance attributes), but I don't think this could be changed in stdlib, although I don't think there would be risks of regressions regarding custom user code.

So why not expose somewhere a utility to easily call these assertXXXX (from basic TestCase or any other subclass) from the outside, like simple utilities ? Thus we can used both fixtures and these extended assertXXXX. Has it already been attempted ?

**Comment by RonnyPfannschmidt** [comment]
that should be placed in a different lib,

for pytest we eventually want higher level assertion helpers

**Comment by pakal** [comment]
Ok I've just been pointed to this related discussion on python bugtracker - https://bugs.python.org/issue19645

**Comment by asottile** [comment]
I don't think pytest should magically provide assertion methods -- if you want the `unittest` ones, mix in `unittest.TestCase`

that said, I do think there would be value in providing more assertion helpers.  when yelp deprecated testify (another python test framework) we really wanted to keep the assertions and provide them in a separate library but it never really happened: [testify/assertions.py](https://github.com/Yelp/Testify/blob/master/testify/assertions.py)

**Comment by blueyed** [comment]
Just for reference: related discussion/PR from pytest-django: https://github.com/pytest-dev/pytest-django/issues/97 / https://github.com/pytest-dev/pytest-django/pull/709.

**Comment by nicoddemus** [comment]
Closing this as "duplicate" of https://github.com/pytest-dev/pytest/issues/2376, feel free to continue the discussion over there.
