### ISSUE TITLE
Fixture with parameters, explicit "tuple list" (like test functions) leads to useless setups/teardown

### ISSUE THREAD

**Issue by smarie** [pytest-dev/pytest#5457]
If we have two parameters 'A' spanning (0, 1) and 'B' spanning (8, 9), it is currently relatively easy to skip some combinations of AxB if they are used in a test function:

```python
A0, A1 = 'a0', 'a1'
B0, B1 = 'b0', 'b1'

@pytest.mark.parametrize("A, B", [(A0, B0), (A0, B1), (A1, B1)])
def test_paramtuple(A, B):
    pass
```

In the example above the (A1, B1) combination is not run:

```
test_tmp.py::test_paramtuple[a0-b0] 
test_tmp.py::test_paramtuple[a0-b1] 
test_tmp.py::test_paramtuple[a1-b1] 
```

Now if I want to do this with fixtures, I do not find a way to do it so that there is no unnecessary teardown of A:

```python
import pytest

A0, A1 = 'a0', 'a1'
B0, B1 = 'b0', 'b1'

@pytest.fixture(params=[(A0, B0),
                        (A0, B1),
                        (A1, B1)])
def AB(request):
    return request.param

# --- A
@pytest.fixture
def A_value(AB):
    return AB[0]

@pytest.fixture
def A(A_value):
    print("setting up A for value %s" % A_value)
    yield
    print("tearing down A")

# ---- B
@pytest.fixture
def B_value(AB):
    return AB[1]

@pytest.fixture
def B(B_value):
    yield

# --------- test
def test_dummy(A, B):
    pass
```

yields:

```
test_tmp.py::test_dummy[AB0] setting up A for value a0
PASSED tearing down A

test_tmp.py::test_dummy[AB1] setting up A for value a0
PASSED tearing down A

test_tmp.py::test_dummy[AB2] setting up A for value a1
PASSED tearing down A
```

I think that I understand why: since fixture `AB` is torn down (it actually changes parameter), all fixtures depending on it are also torn down. So A is torn down, even if its input does not change.

Is there a way as of today to do this right ? 

Note: I also tried indirect parametrization:

```python
@pytest.fixture(scope='module')
def A(request):
    print("setting up A for value %s" % request.param)
    yield

@pytest.fixture(scope='module')
def B(request):
    yield

@pytest.mark.parametrize('A, B', [(A0, B0), (A0, B1), (A1, B1)], indirect=True, scope='module')
def test_dummy(A, B):
    pass
```

Note2: this directly relates to https://stackoverflow.com/questions/46909275/parametrizing-tests-depending-of-also-parametrized-values-in-pytest/56602597#56602597

**Comment by Zac-HD** [comment]
Closing this issue as an inactive question.

**Comment by smarie** [comment]
Thanks @Zac-HD 

I would not call it "inactive" but rather "waiting for an answer" :)

Does it need rephrasing in your opinion ?

**Comment by Zac-HD** [comment]
I actually think it's a great question, and well-phrased :slightly_smiling_face:

I've only closed it because we have a standing policy of closing issues which are questions if they have not had any activity after a few weeks - if it hasn't been answered yet it probably won't be, and we have way too many open issues already.  Unfortunately I don't know of a way to do this myself :confused:

**Comment by smarie** [comment]
I see. Too bad there is no "third option" for this kind of case that can potentially influence future features. 

But I agree that keeping the issues backlog clean and reasonably small is a must-have, otherwise things get out of control. Thanks for doing it !
