### ISSUE TITLE
Provide a reporting hook for assert evaluation

### ISSUE THREAD

**Issue by mfalesni** [pytest-dev/pytest#5464]
Since pytest provides `pytest_assertrepr_compare` hook, I was wondering whether it would also be possible to provide a hook that would be called for each assert evaluation, be it successful or not. In current testing system I am working, built on top of UnitTest2, our assert methods do have logging of what they are asserting. Now, if I want to do the same with the pytest magic assert rewrites, I can't AFAIK.

My proposal would be so it would have similar signature as `pytest_assertrepr_compare`:

```python
def pytest_assert_evaluated(config, op, left, right, message, success):
    log = logger.info if success else logger.error
    log('Assert: ...', {'some': 'params'})
```
I can't think of any side-effects that this hook could provide, I think that just firing and forgetting would probably be its only use case. It could also condense op, left and right into a single string argument ...

Thanks guys (and gals) for your time reading this one! :smile:

**Comment by nicoddemus** [comment]
Hi @mfalesni,

Thanks for writing.

I know it is not exactly what you asked for, but perhaps https://github.com/pytest-dev/pytest/pull/3479 can work out for you, together with the existing hook?

**Comment by mfalesni** [comment]
Well, that could possibly work for the purpose, since assert will fail and display itself. I hope this gets in then, thanks for pointing me to it :)

**Comment by nicoddemus** [comment]
Thanks for the follow up! I'm closing this then as a "kind of duplicate". 😁
