### ISSUE TITLE
Hostname and timestamp properties in generated JUnit XML reports

### ISSUE THREAD

**Issue by anaskhan96** [pytest-dev/pytest#5471]
Pytest enables generating JUnit XML reports of the tests.

However, there are some properties missing, specifically `hostname` and `timestamp` from the `testsuite` XML element. Is there an option to include them?

Example of a pytest XML report:
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="2" name="check" skipped="0" tests="4" time="0.049">
	<testcase classname="test_sample.TestClass" file="test_sample.py" line="3" name="test_addOne_normal" time="0.001"></testcase>
	<testcase classname="test_sample.TestClass" file="test_sample.py" line="6" name="test_addOne_edge" time="0.001"></testcase>
</testsuite>
```

Example of a junit XML report:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="location.GeoLocationTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2019-04-22T10:32:27" hostname="Anass-MacBook-Pro.local" time="0.048">
  <properties/>
  <testcase name="testIoException()" classname="location.GeoLocationTest" time="0.044"/>
  <testcase name="testJsonDeserialization()" classname="location.GeoLocationTest" time="0.003"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

**Comment by samueljsb** [comment]
Fixed by #5692

**Comment by anaskhan96** [comment]
@samueljsb thanks!

**Comment by KellyWalker** [comment]
Can the fix for this be back-ported to a 4.6 patch release?

@nicoddemus did something similar for #5594 

See my request in that ticket for details on my request:
https://github.com/pytest-dev/pytest/pull/5550#issuecomment-558797460

**Comment by nicoddemus** [comment]
Thanks @KellyWalker for the ping. 

Opened: https://github.com/pytest-dev/pytest/pull/6332

**Comment by nicoddemus** [comment]
Done! It will be available on the next 4.6.X release. 👍

**Comment by KellyWalker** [comment]
Most excellent!

**Comment by symbiont-eli-wang** [comment]
Can we add timestamp to each test case?

**Comment by nicoddemus** [comment]
> Can we add timestamp to each test case?

You mean each `TestCase` subclass? Hmmm it is not trivial to do it, I think.

**Comment by KellyWalker** [comment]
> Done! It will be available on the next 4.6.X release. 👍

@nicoddemus do you have an estimate when that release will be made?

**Comment by nicoddemus** [comment]
Hi @KellyWalker,

We can make it anytime actually, personally I will only have time to tackle this next week after the holidays, but if there's urgency other maintainers might step in.

**Comment by KellyWalker** [comment]
Thanks for the quick response. Next week is fine, though if someone were available sooner that would be even better. I don’t know how/who to ask, so if you have a chance, great. If not, we can wait a bit.

**Comment by nicoddemus** [comment]
@asottile perhaps can tackle a new 4.6 release?

**Comment by asottile** [comment]
yep!  I'll do that handle that tomorrow :)

**Comment by nicoddemus** [comment]
Awesome, thanks!

**Comment by asottile** [comment]
4.6.8 has been released -- thanks again!

**Comment by KellyWalker** [comment]
Thanks! You guys are awesome.
