### ISSUE TITLE
 recursive dependency involving fixture 'X' detected with Pillow

### ISSUE THREAD

**Issue by Vic152** [pytest-dev/pytest#5480]
- [x] a detailed description of the bug or suggestion
I have recursive dependency involving fixture 'X' detected error. However this only happens in a specific python env.
- [x] output of `pip list` from the virtual environment you are using
I have Two envs
**First:**
Package           Version
----------------- -----------
aio.app           0.1.8
aio.config        0.1.2
aio.core          0.1.0
aio.http.server   0.1.4
aio.signals       0.1.3
aiohttp           2.2.5
apipkg            1.5
astroid           1.6.5
async-timeout     1.2.1
atomicwrites      1.2.1
attrs             19.1.0
Automat           0.6.0
bottle            0.12.16
certifi           2017.7.27.1
chardet           3.0.4
colorama          0.3.9
conan             1.2.1
constantly        15.1.0
coverage          4.4.1
cx-Freeze         5.0.2
cycler            0.10.0
deprecation       2.0.6
distribute        0.7.3
distro            1.1.0
docutils          0.14
execnet           1.5.0
extras            1.0.0
fasteners         0.14.1
fixtures          3.0.0
future            0.16.0
glob2             0.6
grpcio            1.18.0
grpcio-tools      1.18.0
hyperlink         17.3.0
idna              2.6
imutils           0.5.2
incremental       17.5.0
isort             4.3.4
Jinja2            2.8.1
kiwisolver        1.0.1
lazy-object-proxy 1.3.1
linecache2        1.0.0
lockfile          0.12.2
Mako              1.0.7
MarkupSafe        1.0
matplotlib        3.0.2
mccabe            0.6.1
mock              1.3.0
monotonic         1.5
more-itertools    4.3.0
multidict         3.1.3
node-semver       0.2.0
nose              1.3.7
numpy             1.13.1
olefile           0.44
opencv-python     3.3.0.9
packaging         19.0
parse             1.9.0
parse-type        0.4.2
patch             1.16
pathlib2          2.3.2
pbr               3.1.1
Pillow            5.4.1
pip               19.0.3
pluggy            0.8.0
pluginbase        0.7
protobuf          3.6.1
psutil            5.3.1
py                1.8.0
Pygments          2.3.1
PyJWT             1.7.1
pylint            1.8.4
pyModbusTCP       0.1.7
pyparsing         2.3.1
pyserial          3.4
pytest            4.0.2
pytest-bdd        3.0.1
pytest-cov        2.6.0
pytest-forked     0.2
pytest-html       1.19.0
pytest-metadata   1.7.0
pytest-xdist      1.23.2
python-daemon     2.1.2
python-dateutil   2.8.0
python-mimeparse  1.6.0
pywin32           224
PyYAML            3.12
requests          2.21.0
selenium          3.14.1
setuptools        28.8.0
six               1.11.0
testtools         2.3.0
traceback2        1.4.0
unittest2         1.1.0
urllib3           1.24
websocket-client  0.54.0
win32core         221.36
win32gui          221.6
wrapt             1.11.1
yarl              0.12.0
zope.dottedname   4.2
zope.interface    4.4.2

**Second:**
Package            Version
------------------ ----------
astroid            1.6.6
atomicwrites       1.3.0
attrs              19.1.0
bottle             0.12.16
certifi            2019.6.16
chardet            3.0.4
colorama           0.3.9
conan              1.2.1
deprecation        2.0.6
distro             1.1.0
fasteners          0.15
future             0.16.0
glob2              0.7
idna               2.8
importlib-metadata 0.18
isort              4.3.20
lazy-object-proxy  1.4.1
Mako               1.0.12
MarkupSafe         1.1.1
mccabe             0.6.1
monotonic          1.5
more-itertools     7.0.0
node-semver        0.2.0
numpy              1.16.4
opencv-python      3.3.0.9
packaging          19.0
parse              1.9.0
parse-type         0.4.2
patch              1.16
pathlib2           2.3.3
Pillow             5.4.1
pip                19.1.1
pipenv             2018.11.26
pluggy             0.12.0
pluginbase         0.7
psutil             5.6.3
py                 1.8.0
Pygments           2.4.2
PyJWT              1.7.1
pylint             1.8.4
pyModbusTCP        0.1.8
pyparsing          2.4.0
pytest             4.0.2
pytest-bdd         3.0.1
pytest-html        1.19.0
pytest-metadata    1.8.0
pywin32            224
PyYAML             3.12
requests           2.22.0
selenium           3.14.1
setuptools         41.0.1
six                1.11.0
urllib3            1.25.3
virtualenv         16.6.1
virtualenv-clone   0.5.3
websocket-client   0.54.0
wrapt              1.11.2
zipp               0.5.1
- [x] pytest and operating system versions
Win 10, gitlab runner in a container on headless windows. pytest 4.0.1 with plugins as per lists above. Python 3.5.4
- [x] minimal example if possible
When I do this:
```
from PIL import ImageGrab

@pytest.fixture(name='browser', scope='function')
def browser(chromium):
    img = ImageGrab.grab()
    img.save('output/img.png')
    yield chromium.driver
```
It works in the First env but not Second. I tried to have it in different modules etc. It seems whatever I do in env with more pip imports it works and the other "cleaner" env does not. I do not think this might be pytest issue, however someone might have come across similar problem and could point me in the right direction.

**Comment by nicoddemus** [comment]
Hi @Vic152,

Could you post the exact error message you are getting, which test module, and test function?

Also is that reproducible with a minimal example? Failing that, can you provide instructions on how to reproduce using perhaps a public repository?

**Comment by Vic152** [comment]
Sure I will try to give you best info I can.

**Error**
```
file C:\gitlab\builds\....\bdd\ui_step_definitions\test_stats_chart_steps.py, line 53
  @scenario('stats_chart.feature', 'Testing 3')
  def test_testing_3():
E       recursive dependency involving fixture 'browser' detected
>       available fixtures:  ...
....
>       use 'pytest --fixtures [testpath]' for help on them.
```

Minimal example would be very complex. It would involve pytest-bdd workflow and it may not reproduce the issue. I have a feeling that there is something about ENV that is running in the machine that is failing. I was hoping that this would be sufficient to identify the issue.

It is interesting that in one env this works just fine and not in the another. It fails when I try to use Pillow - PIL in the fixture. There must be something missing from the second set of packages that contributes to this problem.

**Comment by Zac-HD** [comment]
Without a reproducible (even if not minimal) example there not much we can do 😕

**Comment by Vic152** [comment]
Agreed. I logged it for the reference in case someone else comes across similar issue. Thanks!

**Comment by powellrb** [comment]
> in case someone else comes across similar issue.

Thanks, I **am** seeing something similar, also with pytest-bdd, and in my case it is even harder to reproduce as it seems to sometimes work and then sometimes not (mostly it works).

In my case, the fixture that is being complained about has already been instantiated; `--setup-show` output displays it, and it is listed in the available fixtures in the error output. Given that I'm thinking that it is a lookup error meaning that it is trying to be re-instantiated?

I'm not really expecting any response here, just paying forward the 'logging for reference'.

**Comment by Vic152** [comment]
This is a timing or similar issue. We fixed it. @powellrb are you using any pytest _private methods or pytest objects? Like `_arg2fixturedefs` or `request` or `fixture_request`, `fixture_request.getfixturevalue`

We fixed it in 2 ways:

1. Use dependency injection through fixtures primarily. 
2. If you are using private methods and pytest objects, handle exceptions gracefully.

```python
return request.getfixturevalue(fixture_name)
            try:
                return request.getfixturevalue(fixture_name)
            except Exception:
                return None
```

**Comment by powellrb** [comment]
Thanks, that's helpful. We are using `fixture_request.getfixturevalue` and I wondered if it was a contributor and experimented with changing it - that seemed to move the problem to other fixtures though rather than solve things completely. I'll try adding exception handling as you suggest.
