### ISSUE TITLE
Add support for dictionary `argvalues` for `parametrize`

### ISSUE THREAD

**Issue by kevinjfoley** [pytest-dev/pytest#5487]
I'd like to be able to pass a dictionary to `pytest.mark.parametrize` as `argvalues` with the keys as `ids` and the values as `argvalues`

For example:
```
import pytest


@pytest.mark.parametrize(["a", "b"], {"test 1": (1, 2), "test 2": (3, 4)})
def test_foo(a, b):

    assert a + 1 == b

# instead of
@pytest.mark.parametrize(["a", "b"], [(1, 2), (3, 4)], ids=["test 1", "test 2"])
def test_foo(a, b):

    assert a + 1 == b

```

would generate two tests named "test 1" and "test 2".

Before trying to add this feature I wanted to make sure there's no foreseen issues with a making change like this.

**Comment by asottile** [comment]
I'm -1

You can already do this which satisfies the same thing without creating more edge cases:

```python
@pytest.mark.parametrize(["a", "b"], (pytest.param(1, 2, id='test 1'), pytest.param(3, 4, id='test 2')))
```

**Comment by kevinjfoley** [comment]
I completely missed that in the guide, using `pytest.param` does what I'm looking for.

**Comment by blueyed** [comment]
I think using `pytest.param` is not really straight-forward, and less readable in general:

Currently:

```python
@pytest.mark.parametrize(
    ["a", "b"], (
        pytest.param(1, 2, id='test 1'),
        pytest.param(3, 4, id='test 2'),
    )
)
```

New:

```python
@pytest.mark.parametrize(
    ["a", "b"], {
        'test 1': (1, 2),
        'test 2': (3, 4),
    }
)
```

A workaround is of course to use a dict in the first place, and then use that,
but it would be better to not have this redirection also:

```python
@pytest.mark.parametrize("a,b", t.values(), ids=list(t.keys())
```

It feels pretty natural to use a dict here, since the ID is supposed to be unique.
