### ISSUE TITLE
Respect PYTHONBREAKPOINT for `--pdb`

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest#5498]
TL;DR I want this to drop me into pudb's interface:
```
PYTHONBREAKPOINT=pudb.set_trace pytest --pdb
```

Any reason you didn't do this? Or it's just because nobody suggested it?

**Comment by asottile** [comment]
pytest's `--pdb` / `--trace` / etc. mechanism monkeypatches the `pdb` module and nothing else.

You'll notice for instance that this doesn't work:

```python
def test():
    import pudb; pu.db
```

```console
$ pytest t.py

(I don't know, it broke my terminal)































================================ 1 failed in 0.18 seconds =================================
(venv) asottile@asottile-MacBookPro:/tmp/t
$ 
```

**Comment by webknjaz** [comment]
You're forgetting about `-s`. And it's `import pudb; pudb.set_trace()`

**Comment by asottile** [comment]
for `pdb` you don't need `-s` (because pytest monkeypatches it) -- also `pu.db` is a shorthand to save some typing (one of the unique things of using `pudb`) ;)

**Comment by webknjaz** [comment]
Oh

**Comment by webknjaz** [comment]
But in your example there's no `--pdb` or `--trace`. That is why I mentioned `-s` (which works for me when I use custom debuggers

**Comment by asottile** [comment]
Ah mostly because they all work by the same mechanism. `--pdbcls` is the option that controls all of those behaviors

**Comment by DahlitzFlorian** [comment]
I would like to work on this issue, so we can close the issue. While researching for `pudb` (didn't know it before), I stumbled across a section in their documentation explaining how to use `pudb` together with pytest. The example uses the `--pdbcls` option @asottile described.

I suppose even though there is a way to invoke custom debuggers, we should add support for `PYHTONBREAKPOINT`. Correct me if I'm wrong. If this is the case, I would like to work on supporting it.

https://documen.tician.de/pudb/starting.html#usage-with-pytest

**Comment by DahlitzFlorian** [comment]
Another question arose: What happens if `PYTHONBREAKPOINT` is set to let's say `pudb.set_trace`? Do we want to _only_ use `pudb`'s `set_trace()` function or use the whole debugger `pudb.debugger:Debugger` instead of `pdb.Pdb`?

**Comment by webknjaz** [comment]
I think there's no generic way of deriving `--pdbcls` out of `PYTHONBREAKPOINT` so I'd say only `set_trace()` matters.

**Comment by asottile** [comment]
agreed, I don't think this is possible which is unfortunate but makes sense given the history of pytest's pdb coupling

**Comment by webknjaz** [comment]
Shouldn't set_trace still work?

**Comment by asottile** [comment]
I don't think so, it only works for pdb because of pdbcls

**Comment by webknjaz** [comment]
@asottile what if pytest declared another setuptools entrypoint for third-party debugger libs that would be used to configure pdbcls based on what's in `PYTHONBREAKPOINT`? Or maybe some hook for pytest plugins to register such things?

**Comment by asottile** [comment]
at that point you might as well just use `--pdbcls` since it wouldn't reduce the amount of configuration / settings needed, only would make pytest more complex for not really any benefit afaict

**Comment by webknjaz** [comment]
Why? The idea is that end-users wouldn't need to configure pytest: it would be able to figure out pdbcls automatically. Only the debugger lib maintainers would need to make a small hook.
