### ISSUE TITLE
Remove fallback from inspect wrapper

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#5513]
Now that the master branch only has to be compatible with Python 3.5+, we can simplify the following code because `inspect.unwrap` was added in 3.4:

https://github.com/pytest-dev/pytest/blob/cf27af734e0b3689944061721c54af0e7d24dd08/src/_pytest/doctest.py#L367-L370

So we can just use `real_unwrap = inspect.unwrap`, and unconditionally run the `else:` block.  This is a good issue for a first-time contributor!

**Comment by AmirElkess** [comment]
I apologize if any mistake happened, as it's my first contribution to open-source community.

I made this change, which passed the tests, then pushed it. 
According to the contribution guide, the next step is to create a new changelog entry, and I am unsure of the type of this issue. 

Can you please check if my push request is correct, and tell me what type is this issue?
Thanks.

**Comment by nicoddemus** [comment]
Hi @AmirElkess,

Thanks for the contribution in https://github.com/pytest-dev/pytest/pull/5518. I will comment about your questions in there. 👍

**Comment by nicoddemus** [comment]
Fixed by #5518
