### ISSUE TITLE
YML files are not YAML files

### ISSUE THREAD

**Issue by AvdN** [pytest-dev/pytest#5533]
https://docs.pytest.org/en/latest/example/nonpython.html has a description of using YAML files.

However there is repeated reference to .yml files. YML (https://fdik.org/yml/) is a different format that is almost as old as YAML.

The [recommended file extension](http://yaml.org/faq.html) for *YAML* files has been  `.yaml` since 2006 (https://web.archive.org/web/20060924190202/http://yaml.org/faq.html)

Please use the appropriate extension for YAML files and change the option `--run-yml` to `--run-yaml`, because `pytest` is not using YML files at all.

**Comment by asottile** [comment]
this seems pedantic at best 🤷‍♂ -- I can't find any reference to the `.yml` file extension referring to YML files, however I can find many many references to them containing YAML

In fact on github there are 39 million results for `filename:*.yml` yet only 6 million results for `filename:*.yaml`

**Comment by nicoddemus** [comment]
Yeah TBH I never thought there was a difference... for example `conda` uses `meta.yaml` for build recipes, and `environment.yml` for environment files, and both are in the YAML format. 

I always thought both `.yml` and `.yaml` were valid extensions for YAML files.

Having said that I would be happy to merge a PR updating the docs to use only `.yaml`. 👍
