### ISSUE TITLE
setup.py test is going to be deprecated

### ISSUE THREAD

**Issue by jamesmyatt** [pytest-dev/pytest#5534]
There are plans to deprecate `setup.py test` (https://github.com/pypa/setuptools/issues/1684). Is it worth updating the section in "Good Integration Practices" to discourage using the setuptools integration (https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner)?

**Comment by nicoddemus** [comment]
Definitely, thanks for bringing this to attention.

We might even consider removing that section altogether I think, only keeping the `pytest-runner` section.

**Comment by nicoddemus** [comment]
@jaraco what do you think?

**Comment by graingert** [comment]
setting setup_requires in 'setup.py' is not good practice, it should be moved to `pyproject.toml` if used at all

**Comment by graingert** [comment]
https://github.com/pytest-dev/pytest/issues/3814

**Comment by jaraco** [comment]
I agree we should discourage use of `setup_requires` and `tests_require` in favor of extras or requirements.txt or pyproject.toml.

> We might even consider removing that section altogether I think, only keeping the pytest-runner section.

Yes, I'm in favor of removing the section altogether. I don't see any value in keeping a reference to pytest-runner. Instead, I recommend giving users guidance on how best to _orchestrate_ (create environments, declare and install dependencies, etc) their tests (e.g. with `tox`).

**Comment by jamesmyatt** [comment]
I'd be tempted to include a recommendation to not integrate with setuptools, rather than just have the section disappear. Otherwise people won't understand why it's gone.

**Comment by nicoddemus** [comment]
@jamesmyatt that's a good suggestion. Would you like to open a short PR with that? I suppose this can be done even directly from the GH interface. 👍

**Comment by nicoddemus** [comment]
Closed by #5546
