### ISSUE TITLE
Use standard library importlib.metadata on Python 3.8

### ISSUE THREAD

**Issue by hroncok** [pytest-dev/pytest#5537]
Once we update Python in Fedora to 3.8, we'd like our pytest package to use `importlib.metadata` from the standard library. Would you accept a PR that makes the dependency on external `importlib_metadata` optional (only use it on Python < 3.8)?

**Comment by nicoddemus** [comment]
I defer the final decision to @asottile, but it seems reasonable to me! 👍

**Comment by asottile** [comment]
yep, was planning to do this once most of the CI providers were on 3.8b1+ -- I think now that travis (and I believe circle?) are there we should do this

**Comment by hroncok** [comment]
OK. I'll start with pluggy https://github.com/pytest-dev/pluggy/issues/222

**Comment by hroncok** [comment]
working on this now
