### ISSUE TITLE
item.getparent(pytest.Class) returning NoneType

### ISSUE THREAD

**Issue by vsfba1-iscteiul** [pytest-dev/pytest#5543]
Hi everyone, this is my first time reporting a bug here so I hope this is the right place for this. I searched on google and couldn't find anything related to my problem.

So, I've been redesigning my Pytest/ Selenium test suite to work locally or on Selenium Grid (right now, just commenting out the remote driver or the chrome driver, depending on what I intend to do). This was working until yesterday but today, when running my tests locally (haven't been able to run them on the grid yet, for different reasons), I'm having an issue on my fixture, namely on this part of the code:

```
driver = webdriver.Chrome()

session = request.node

for item in session.items:
            cls = item.getparent(pytest.Class)
>           setattr(cls.obj, "driver", driver)
E           AttributeError: 'NoneType' object has no attribute 'obj'
```

This is the output of pip list for my virtual environment. I did switch my virtual environment yesterday and am thinking it could be related, but I'm not sure what could be different, since I installed from my requirements.txt. I'm using Python 3.7 on Manjaro Linux, and Pytest v5.0. 

```
Package                    Version   
-------------------------- ----------
atomicwrites               1.3.0     
attrs                      19.1.0    
certifi                    2019.6.16 
chardet                    3.0.4     
future                     0.17.1    
idna                       2.8       
importlib-metadata         0.18      
jedi                       0.14.0    
more-itertools             7.1.0     
packaging                  19.0      
parso                      0.5.0     
pip                        19.1.1    
pipenv                     2018.11.26
pluggy                     0.12.0    
py                         1.8.0     
pymssql                    2.1.4     
pyparsing                  2.4.0     
pytest                     5.0.0     
pytest-base-url            1.4.1     
pytest-html                1.21.1    
pytest-metadata            1.8.0     
pytest-parallel            0.0.9     
pytest-selenium            1.16.0    
pytest-variables           1.7.1     
python-jsonrpc-server      0.2.0     
python-language-server     0.27.0    
requests                   2.22.0    
requests-file              1.4.3     
selenium                   3.141.0   
selenium-chrome-screenshot 0.0.1     
selenium-requests-html     1.0       
setuptools                 41.0.1    
six                        1.12.0    
tldextract                 2.2.1     
urllib3                    1.25.3    
virtualenv                 16.6.1    
virtualenv-clone           0.5.3     
Wand                       0.5.4     
wcwidth                    0.1.7     
zipp                       0.5.1     
```

**Comment by RonnyPfannschmidt** [comment]
without more details on the collection structure this looks like a user error

also if the code you posted is in a fixture, i intensely advise to change structure, its not something i'd expect to see on any kind of fixture

**Comment by vandakiara** [comment]
> without more details on the collection structure this looks like a user error
> 
> also if the code you posted is in a fixture, i intensely advise to change structure, its not something i'd expect to see on any kind of fixture

Than you for your reply. Could you help me understand what you mean by collection structure? As for the code being inside a fixture, is there a problem? I'm a beginner in test automation and I found many places advising this kind of structure for the fixture. What is the problem?

**Comment by RonnyPfannschmidt** [comment]
collection structure is bascially the output if `pytest --collect-only`

it would show the actual items


a session scoped fixture that then iterates through all items of the session and modifies them is pretty much missuse of the concept - i cant think of any good reason to do it that way

its so severe that as a beginner you should under no circumstances do it and as a senior engineer you better have a really good reason and put it into a comment

**Comment by vandakiara** [comment]
Here's the collection structure:
```
platform linux -- Python 3.7.3, pytest-5.0.0, py-1.8.0, pluggy-0.12.0
sensitiveurl: .*
rootdir: /home/vandabarata/PycharmProjects/vpp-qa-automation-tests, inifile: pytest.ini
plugins: parallel-0.0.9, base-url-1.4.1, variables-1.7.1, html-1.21.1, selenium-1.16.0, metadata-1.8.0
collected 8 items                                                                                                                                                                        
<Package /home/vandabarata/PycharmProjects/vpp-qa-automation-tests/test_suites>
  <Module test_login_registration.py>
    <Class TestLoginAndRegistration>
        <Function test_login_wrong_user>
        <Function test_registration>
        <Function test_log_off>
  <Module test_quickpick.py>
    <Class TestQuickPickButtons>
        <Function test_start_session_and_place_random_bet>
    <Class TestSessionExpiration>
        <Function test_session_after_30min>
  <Module test_sanity.py>
    <Function test_bms_logic_health>
    <Function test_db_health>
    <Function test_bms_wallet_health>
```

I structured the project trying to follow a Page Object Model (POM) so I am also using the for loop above for setting the pages as class attributes, so I can use them freely in my tests. This was the only way I found for doing this. My current code is as such:
   ```
    # initializes the pages and page functions
    # that will be needed to use for the tests
    main_page = PageFunctions(driver)
    login_page = LoginPage(driver)
    registration_page = RegistrationPage(driver)

    for item in session.items:
        cls = item.getparent(pytest.Class)
        setattr(cls.obj, "driver", driver)
        setattr(cls.obj, "page", main_page)
        setattr(cls.obj, "login", login_page)
        setattr(cls.obj, "registration", registration_page)
```

Is the problem that the fixture is session scoped? I admit I had a really hard time finding information about fixtures and scopes, so I'm still not sure what I'm doing wrong here. Thank you once again for taking time to reply and help me.

**Comment by RonnyPfannschmidt** [comment]
ok, the first error is that not all of your tests are in a class, the getparent call however expects classes

the second error is the patching of objects into all items from session scope,
those should be fixtures you pass in as argument
so driver, page, login, registration would all be fixtures you receive instead  of objects you patch  in

**Comment by vandakiara** [comment]
Thank you so much, the issue was indeed not having all the tests inside of classes. Having classes for all my test functions solved my problem. I don't quite understand what you mean by passing the pages and driver as fixtures passed in as arguments. Could you show me an example with 2 or 3 of them so I can improve then? Thank you once more :)

**Comment by RonnyPfannschmidt** [comment]
```
@fixture 
def driver():
  return webdriver.Chrome()


@fixture 
def main_pag(driver):
  return PageFunctions(driver)


def test_something(main_page):
  main_page.magic()
```

**Comment by Zac-HD** [comment]
Issue solved 😄
