### ISSUE TITLE
Provide an implementation of UnitTest.assertCountEqual

### ISSUE THREAD

**Issue by software-opal** [pytest-dev/pytest#5548]
Currently if I want to test that two lists contain the same elements, ignoring their order, I need to use a set(only on hashable types) or use a `UnitTest` subclass(which means I loose some functionality).

It would be good to provide some guidance on how to do within PyTest.

I'm thinking it would look something like this:

```python
import pytest

def my_reverse(list):
  return reversed(list)

def test_reverse_keeps_items():
  my_list = ['a', {'key': 'value'}, object()]
  # I'm just spitballing the name; I don't know what would be a good name for it.
  assert my_list == pytest.unordered(reversed(my_list))
  # or
  pytest.assert_count_equal(my_list, my_reverse(my_list))
```

If this isn't a good idea it would be nice to add a note in the docs on how to do it so that people can easily discover it.

**Comment by asottile** [comment]
I don't think pytest should grow an assertion library, you can already get essentially this by using sets or counters (and with better assertion messages usually)

**Comment by RonnyPfannschmidt** [comment]
pytest should grow assertion helpers, something like the "unordered" or a "sorted" object would be helpfull in many ways

but this should be started outside of pytest and experimented wtith for a few years  before bringing it into core

**Comment by Zac-HD** [comment]
Closing this issue, as it's suitable to be demonstrated in a plugin before further discussion in Pytest.

**Comment by utapyngo** [comment]
Has anyone started working on a plugin for this?

**Comment by RonnyPfannschmidt** [comment]
im unaware, if  anyone is  please link

**Comment by utapyngo** [comment]
Here is a related SO question: https://stackoverflow.com/questions/41605889/does-pytest-have-an-assertitemsequal-assertcountequal-equivalent

**Comment by blueyed** [comment]
For reference: https://github.com/pytest-dev/pytest-django/pull/709 (using Django's helpers).

**Comment by utapyngo** [comment]
> Closing this issue, as it's suitable to be demonstrated in a plugin before further discussion in Pytest.

Is a plugin able to inject a function into the `pytest` namespace? I want to use it as `pytest.unordered()`, the same way as `pytest.approx()`.

**Comment by RonnyPfannschmidt** [comment]
intentionally no longer

**Comment by utapyngo** [comment]
What hook the plugin should use then?
Should it by a pytest- plugin at all? It seems that a simple package exporting one function is enough.

**Comment by RonnyPfannschmidt** [comment]
@utapyngo well, it needs assertrepr hooks for explaining whats different/not different

**Comment by utapyngo** [comment]
Docs for reference: http://doc.pytest.org/en/latest/assert.html#defining-your-own-explanation-for-failed-assertions

**Comment by utapyngo** [comment]
Could someone please review [pytest-unordered](https://github.com/utapyngo/pytest-unordered)?

**Comment by utapyngo** [comment]
@RonnyPfannschmidt, could you please review [pytest-unordered](https://github.com/utapyngo/pytest-unordered)?

@software-opal, will this work for you?
```python

from pytest_unordered import unordered

def test_reverse_keeps_items():
    my_list = ['a', {'key': 'value'}, object()]
    assert my_list == unordered(list(reversed(my_list)))
```
