### ISSUE TITLE
pytest: error: unrecognized arguments: --doctest-module

### ISSUE THREAD

**Issue by charlax** [pytest-dev/pytest#5554]
- [X] a detailed description of the bug or suggestion
- [X] output of `pip list` from the virtual environment you are using
- [X] pytest and operating system versions
- [X] minimal example if possible

Using:

* pytest version 5.0.0...
* setuptools registered plugins:
  * doubles-1.5.3
  * pytest-factoryboy-2.0.3
  * pytest-cov-2.7.1
  * pytest-osxnotify-0.1.7
  * pytest-flask-0.15.0

Since v5.0.0, I'm getting `unrecognized arguments: --doctest-module`.

```
% pytest
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --doctest-module
  inifile: .../api/setup.cfg
  rootdir: .../api
```

`pytest` section of my `setup.cfg`:

```
[tool:pytest]
addopts = --tb=native --no-cov-on-fail --doctest-module --ignore=migrations/env.py --ignore=migrations/
filterwarnings =
    ignore::DeprecationWarning
```

The [v5 changelog](https://docs.pytest.org/en/latest/changelog.html#pytest-5-0-0-2019-06-28) does mention something about `--doctest-module` but it does not offer any explanation why my case would fail... Also, I'm still following the setup recommended in https://docs.pytest.org/en/latest/doctest.html

**Comment by nicoddemus** [comment]
Hi @charlax,

The option is named `--doctest-modules` (plural). This used to work prior 5.0 because `ArgumentParser` contains a feature that accepts "partial options", that's why `--doctest-module` used to work.

This is mentioned in more details on the CHANGELOG:

> #1149: Pytest no longer accepts prefixes of command-line arguments, for example typing pytest --doctest-mod inplace of --doctest-modules. This was previously allowed where the ArgumentParser thought it was unambiguous, but this could be incorrect due to delayed parsing of options for plugins. See for example issues #1149, #3413, and #4009.

I'm closing for now, feel free to follow up with other questions. 👍

**Comment by charlax** [comment]
🤦‍♂ 

Oh nice catch! Thanks!
