### ISSUE TITLE
Exception args converted to string by assert but by raise exception

### ISSUE THREAD

**Issue by Miksus** [pytest-dev/pytest#5562]
Hi,

Pytest converts AssertionError's args to strings when using assert but not when the exception is raised. 

For example, in native Python I can do the following:
```python
try:
    assert 0, 123
except Exception as error:
    error_arg = error.args[0]
    print(type(error_arg))
```
this prints out ofc `<class 'int'>`.

But when I make a similar failing pytest's test:
```python
def test_fail_with_assert():
    assert 0, 123
```
and interact with the exception with a function in conftest.py (https://stackoverflow.com/a/28201810):
```python
def pytest_exception_interact(node, call, report):
    error = call.excinfo.value
    error_arg = error.args[0]
    print(type(error_arg))
```
this prints out `<class 'str'>` (when run with pytest, also prints the fail report ofc). The argument itself is turned to `'123\nassert 0'`. I also used debugger to check if there would have been any attribute that holds the original args.

However, if I raise the exception instead of using assert, it works as I expected:
```python
def test_fail_with_raise():
    err = AssertionError(123)
    raise err
```
this prints out `<class 'int'>` (by having the previous function in conftest.py). 

So why does pytest convert AssertionException args when used in assert but not when used with raise? I think the arguments should not be converted at all as this would allow one to pass more information from tests to reports. Alternatively, there could be another attribute that stores the original exception and its args as is.

<details>
  <summary>Example case</summary>
One is testing a function that returns a pandas dataframe and would like test the output does not have duplicate rows, negative values etc. If there are any, he/she would like to manually inspect the problematic entries in Excel, thus the erroneous subset of a dataframe of a failed test should be saved on disk. The most straightforward way to accomplish this, I think, is to pass the dataframe with the exception and save it then using perhaps _pytest_exception_interact_. This keeps the tests themselves short, easy to read and write. Raising AssertionError (or any other exception) could do the job but the feedback is more limited and more code need to be written per test. The obvious way would be to pass it with assert but at the moment it is not possible.

Would be awesome if he/she could do a test like:

```python
def test_duplicates(df: pandas.DataFrame):
    "Test whether dataframe for duplicate rows"
    df_duplicated = df[df.duplicated(keep=False)]
    duplicated = df_duplicated.to_dict('records')
    assert [] == duplicated, df_duplicated
```

and have in conftest.py:
```python
def pytest_exception_interact(node, call, report):
    "Save data to disk passed with exception"
    if report.failed:
        error = call.excinfo.value
        error_arg = error.args[0]
        if hasattr(error_arg, "to_excel"):
            error_arg.to_excel(f"{report.head_line}_failed_data.xlsx")
```
</details>

<details>
  <summary>Environment description</summary>

Python version: Python 3.7.3
OS: Windows 10.0.17134

`pip list`

|Package            | Version |
|------------------ | --------- |
|atomicwrites      |  1.3.0 |
|attrs              | 19.1.0 |
|certifi            | 2019.6.16 |
|colorama           | 0.4.1 |
|importlib-metadata | 0.17 |
|more-itertools    | 7.0.0|
|packaging         | 19.0|
|pip               | 19.1.1|
|pluggy            | 0.12.0|
|py                | 1.8.0|
|pyparsing         | 2.4.0|
|pytest            | 5.0.0|
|setuptools        | 41.0.1|
|six               | 1.12.0|
|wcwidth           | 0.1.7|
|wheel             | 0.33.4|
|wincertstore      | 0.2|
|zipp              | 0.5.1|
</details>

Am I missing something?

**Comment by asottile** [comment]
Definitely looks like a bug, thanks for the report!

**Comment by asottile** [comment]
Here's a much simpler reproduction:

```python
def test():
    with pytest.raises(AssertionError) as excinfo:
        assert 0, 123
    assert type(excinfo.value.args[0]) is int
```

**Comment by asottile** [comment]
Actually, this looks intentional -- this is assertion rewriting mechanism doing its thing (it works by replacing the message of the assertionerror with the useful information)

For instance:

```
$ pytest t.py
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.0.2.dev3+g2180d9ef6, py-1.8.0, pluggy-0.12.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/asottile/workspace/pytest/.hypothesis/examples')
rootdir: /home/asottile/workspace/pytest, inifile: tox.ini
plugins: hypothesis-4.26.3
collected 1 item                                                               

t.py F                                                                   [100%]

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        with pytest.raises(AssertionError) as excinfo:
            assert 0, 123
>       assert excinfo.value.args[0] == 123
E       AssertionError: assert '123\nassert 0' == 123

t.py:7: AssertionError
=========================== short test summary info ============================
FAILED t.py::test - AssertionError: assert '123\nassert 0' == 123
=========================== 1 failed in 0.10 seconds ===========================
```

**Comment by asottile** [comment]
given that, I believe this to be invalid -- thanks for the issue!  if there's something I missed feel free to comment back and we can reopen it
