### ISSUE TITLE
Create a plugin for Nunit3

### ISSUE THREAD

**Issue by tonybaloney** [pytest-dev/pytest#5572]
This is not a bug.

I find the junit XML formatter quite limiting. Especially with 3rd party test loggers and reporting tools (like Microsoft DevOps).

The other common format I've been looking into is Nunit3.

Nunit3 is MIT licensed and the schema is well documented.

I've started on a plugin, based on the junit XML pattern (but with changes) and in a way that abstracts the node-reporter from the Nunit XML structure so that this could be used for other formats. 

This is a work-in-progress, but when completed, I'd like to relocate the project to pytest-dev (if it's wanted!) https://github.com/tonybaloney/pytest-nunit

CC @asottile

**Comment by thisch** [comment]
> Especially with 3rd party test loggers
What kind of logging related problems do you have with pytests' junit formatter?

**Comment by nicoddemus** [comment]
> This is a work-in-progress, but when completed, I'd like to relocate the project to pytest-dev (if it's wanted!) 

Definitely! 👍

**Comment by tonybaloney** [comment]
See https://github.com/pytest-dev/pytest-nunit/issues/17 for complete beta
