### ISSUE TITLE
In pytest 5.0.0 scope='session' does not work with monkeypatch, but it did in 3.0.0 and the docs are unclear.

### ISSUE THREAD

**Issue by spearsem** [pytest-dev/pytest#5574]
If your try to create a session-scoped fixture using `monkeypatch` in pytest 5.0.0, like in a conftest.py file to patch an environment variable consumed by some other module at module import time, you get an error stating that `monkeypatch` is a function-scoped fixture and and cannot be used for a session.

However, in the docs for pytest 3.0.0, there is [an explicit section of the docs recommending how to use `monkeypatch` as a session-scoped fixture](https://docs.pytest.org/en/3.0.0/monkeypatch.html#example-setting-an-environment-variable-for-the-test-session).

Since this same use case is not addressed at all in [the docs for v 5.0.0](https://docs.pytest.org/en/5.0.0/monkeypatch.html), it means the 3.0.0 docs still show up highly in search engines when looking for this type of use case of monkeypatch.

It would probably be good to explicitly call out this functionality in both the 3.0.0 docs and 5.0.0 docs (and any intermediate docs versions too), with a special box indicating that this is not supported with newer pytest versions.

If possible, providing an example for how to solve the same type of problem using `monkeypatch` in v 5.0.0 would be great. Note that none of the existing examples explain how it could be solved, since they all focus on function-scoped monkeypatching. For example, [there is an example](https://docs.pytest.org/en/5.0.0/monkeypatch.html#example-setting-an-environment-variable-for-the-test-session) about deleting the `requests` attribute from the `requests` module, but this does not address what happens if side-effectful behavior happens _at import time_ based on a variable that needs to be patched.

However, many times you will work with a Python module that sets up a module-level variable one time upon first import (like a logging setting or a path to a special data set to use depending on the environment).

How do we use `monkeypatch` in v 5.0.0 to solve that case and ensure the patching happens _before_ a module is imported by a test and is cleaned up after that test session ends?

I added a toy example [in this comment](https://github.com/pytest-dev/pytest/issues/2229#issuecomment-509246709) on an old related issue.

- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
in pytest 3.0 there was a experimental feature for multi scoped fixtures,
we did later learn that the tech debt in the fixture system made the implementation do incorrect/bad things, and we had to take it out as it broke in too many/surprising ways,

unfortunately it doesn't seem to be in the change-log - @nicoddemus any idea what happened to the historic record?

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/pull/1811

**Comment by spearsem** [comment]
It doesn't appear to be a previous 'experimental' feature, but rather it was a primary intended use case and had a [dedicated section of documentation](https://docs.pytest.org/en/3.0.0/monkeypatch.html#example-setting-an-environment-variable-for-the-test-session). If it was actually experimental, it might be good to retroactively add that tag to the documentation block, because it reads in 3.0.0 like a fully supported, first-class feature. Amending changelogs probably won't be enough to help people understand when searching online to find why it went away when upgrading or something.

**Comment by RonnyPfannschmidt** [comment]
I did indeed misstemember some details, it got pulled right before the release and i believe there where oversights in the docs that have since been fixed, i wonder how to correctly mark those as deprecated/broken

**Comment by nicoddemus** [comment]
>  it got pulled right before the release and i believe there where oversights in the docs that have since been fixed

Exactly what happened: before the release we noticed the broken behavior in @The-Compiler's test suite. Hmm in retrospect, the problem might be more related to https://github.com/pytest-dev/pytest/issues/4871 than the actual caching mechanism.
  
> i wonder how to correctly mark those as deprecated/broken

If everyone agrees, we can just take those docs down. 👍

**Comment by RonnyPfannschmidt** [comment]
Take down is fine

**Comment by nicoddemus** [comment]
Done! Closing this for now then, thanks everyone. 👍
