### ISSUE TITLE
pytest xdist is unable to capture logs

### ISSUE THREAD

**Issue by GitBharath** [pytest-dev/pytest#5586]
Using python3.6, pytest==4.6.3, pytest-xdist==1.28.0

Unable to get the logs when I use `-n` flag (pytest-xdist). I have to explicitly provide `import logging` and set the loggers in each of my test case files to see at which line it failed.

pytest.ini
-----------
    [pytest]
    addopts = -v -s -p no:warnings -n auto
    log_cli=true
    log_level=NOTSET
    log_format = %(asctime)s %(levelname)s (%(threadName)-10s) %(filename)s:%(lineno)d %(message)s
    log_date_format = %Y-%m-%d %H:%M:%S
    filterwarnings =
        ignore::UserWarning

My command line execution goes like this in general ...

    pytest test_testcase.py --env ENV1 --env ENV2 --env ENV3

I expected different subprocesses to be executed for different ENVs and logs to be captured for each ENVs accordingly

Here is the output ...

    (venv) [tivo@localhost tests]$ pytest test_tc74080_validate_pgd_process.py --env usqe1 --env usqe2 --env micqe3
    ===================================================================== test session starts     ======================================================================
    platform linux -- Python 3.6.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 -- /home/tivo/workspace/ServicePortal/autotestscripts/CAT/scripts/ServerQE/SBrat/venv/bin/python3.6
    cachedir: .pytest_cache
    rootdir: /home/tivo/workspace/ServicePortal/autotestscripts/CAT/scripts/ServerQE/SBrat,         inifile: pytest.ini
    plugins: forked-1.0.2, rerunfailures-7.0, xdist-1.28.0
    [gw0] linux Python 3.6.3 cwd: /home/tivo/workspace/ServicePortal/autotestscripts/CAT/scripts/ServerQE/SBrat/python3/tests
    [gw1] linux Python 3.6.3 cwd: /home/tivo/workspace/ServicePortal/autotestscripts/CAT/scripts/ServerQE/SBrat/python3/tests
    [gw0] Python 3.6.3 (default, Jun 25 2019, 18:53:50)  -- [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
    [gw1] Python 3.6.3 (default, Jun 25 2019, 18:53:50)  -- [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
    gw0 ok / gw1 ok
    gw0 [3] / gw1 [3]
    scheduling tests via LoadScheduling

    test_tc74080_validate_pgd_process.py::TestPGDProcess::test_tc74080_verify_pgd_processing_with_tivodate[usqe1] 
    test_tc74080_validate_pgd_process.py::TestPGDProcess::test_tc74080_verify_pgd_processing_with_tivodate[usqe2] 
    [gw0] PASSED     test_tc74080_validate_pgd_process.py::TestPGDProcess::test_tc74080_verify_pgd_processing_with_tivodate[usqe1] 
    test_tc74080_validate_pgd_process.py::TestPGDProcess::test_tc74080_verify_pgd_processing_with_tivodate[micqe3] 
    [gw1] PASSED     test_tc74080_validate_pgd_process.py::TestPGDProcess::test_tc74080_verify_pgd_processing_with_tivodate[usqe2] 
    [gw0] PASSED     test_tc74080_validate_pgd_process.py::TestPGDProcess::test_tc74080_verify_pgd_processing_with_tivodate[micqe3] 

    =================================================================== 3 passed in 8.22 seconds     ===================================================================

Expected Result:
---------------------
1. When it initiated with `-n auto` from `pytest.ini` file, I was expecting 3 different subprocess to activate for each ENVs like this below ...

        gw0 [3] / gw1 [3] / gw2[3]

but getting this ...

    gw0 [3] / gw1 [3]

In order to get what I want, I must keep changing in the command line for `-n3` for 3 ENVs, `-n4` for 4 ENVs.

2. I want to capture logs for each ENVs separately either in xml or txt format.

3. Logs must be captured for each test cases without having the `import logging`.

I don't have a clue how to get these above; please give me a clue of how to get what I wanted.

**Comment by nicoddemus** [comment]
Hi @GitBharath,

Unfortunately this is not currently possible in current xdist's design. Please see https://github.com/pytest-dev/pytest-xdist/issues/402 for more details.

I'm closing this now, feel free to post questions to the issue linked above. 👍
