### ISSUE TITLE
pytest fails with implicit namespaces

### ISSUE THREAD

**Issue by aatkinson** [pytest-dev/pytest#5590]
Pytest doesn't seem to work with implicit namespaces in your source, as defined by [PEP 420](https://www.python.org/dev/peps/pep-0420/). This still occurs as of pytest 5.0.1 installed in a Python 3 environment.

Note this is for the __source__ package being tested, and I've encountered the issue with tests __outside__ of the source package (__init__.py files are required for tests as noted in the [best practices document](https://docs.pytest.org/en/latest/goodpractices.html).

E.g.

```
mypkg/
    foo/
        baz.py
    bar/
        baz.py
tests/
```

will yield errors like

```
./../../.local/lib/python3.6/site-packages/py/_path/local.py:721: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   py._path.local.LocalPath.ImportMismatchError: ('baz', '/home/vsts/work/1/s/mkpkg/foo/baz.py', local('/home/vsts/work/1/s/mkpkg/bar/mkpkg.py'))
```

This issue has appeared in #774.

**Comment by asottile** [comment]
I cannot reproduce, did you `cp -r` the `foo` and `bar` directories?

```console
$ find mypkg/ tests -name '*.py' | xargs tail -n999
==> mypkg/bar/baz.py <==

==> mypkg/foo/baz.py <==

==> tests/test_foo.py <==
import mypkg.foo.baz
import mypkg.bar.baz


def test(): pass

$ python -m pytest tests
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /tmp/x
collected 1 item                                                               

tests/test_foo.py .                                                      [100%]

=========================== 1 passed in 0.01 seconds ===========================
```

**Comment by Zac-HD** [comment]
Closing as inactive; I can't reproduce it either (and #774 was test files, not code files).
