### ISSUE TITLE
`$bF` symbol for command line argument gives `pytest: error: argument --someparam: expected one argumen`

### ISSUE THREAD

**Issue by vhryhorchuk-amplify** [pytest-dev/pytest#5596]
Hello!
I run into issue with combination `$bF` for command line param.
```
pytest -v -s tests --password $bF
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --password: expected one argument
```
My conftests.py looks like this:
```
def pytest_addoption(parser):
    parser.addoption(
        """--password""", type=str, action="store"
    )

@pytest.fixture(scope="session")
def environment_config(request):
    auth_pass = request.config.getoption("--password")
    print(auth_pass)
```
The same issue happens with
` pytest -v -s tests/ --password Qwerty$bF!`
Output:
`Qwerty`
It seems, pytest somehow ignores `$bF`

```
pip list
pytest                4.1.1     
pytest-forked         1.0.1     
pytest-xdist          1.26.0   
```
```
python -V
3.6.8
```
Worth to mention, the problem has been resolved by taking `$bF!` to the single quotes `'$bF!'`.

**Comment by Zac-HD** [comment]
> Worth to mention, the problem has been resolved by taking `$bF!` to the single quotes `'$bF!'`.

Sounds like an issue quoting `$` in your shell.  Thanks for providing such a detailed report - that makes diagnosis much easier and saves all our time :smile:
