### ISSUE TITLE
pytest ignores config files in --rootdir

### ISSUE THREAD

**Issue by cr** [pytest-dev/pytest#5610]
## a detailed description of the bug or suggestion
`pytest --rootdir=$DIR` ignores pytest config files in rootdir. It also doesn't descent into rootdir to look for tests, unless rootdir is a descendant of $CWD. Config seems to be only taken from $CWD up and tests only collected from $CWD down, so I am wondering, what `--rootdir` is actually supposed to be used for.

## output of `pip list` from the virtual environment you are using
```
appnope            0.1.0     
atomicwrites       1.3.0     
attrs              19.1.0    
backcall           0.1.0     
certifi            2019.6.16 
chardet            3.0.4     
coloredlogs        10.0      
coverage           4.5.3     
cycler             0.10.0    
decorator          4.4.0     
glob2              0.7       
humanfriendly      4.18      
idna               2.8       
importlib-metadata 0.18      
ipython            7.6.1     
ipython-genutils   0.2.0     
jedi               0.14.0    
kiwisolver         1.1.0     
Mako               1.0.13    
MarkupSafe         1.1.1     
matplotlib         3.1.1     
more-itertools     7.1.0     
mozdep             0.0.0a3   /Users/cr/Documents/src/mozilla-depends/utils
networkx           2.3       
numpy              1.16.4    
packaging          19.0      
parse              1.12.0    
parse-type         0.4.2     
parso              0.5.0     
pexpect            4.7.0     
pickleshare        0.7.5     
pip                19.1.1    
pluggy             0.12.0    
prompt-toolkit     2.0.9     
ptyprocess         0.6.0     
py                 1.8.0     
pycodestyle        2.5.0     
Pygments           2.4.2     
pygraphviz         1.5       
pyparsing          2.4.0     
pytest             5.0.1     
pytest-bdd         3.1.1     
pytest-codestyle   1.4.0     
pytest-runner      5.1       
python-dateutil    2.8.0     
PyYAML             5.1.1     
requests           2.22.0    
semantic-version   2.6.0     
setuptools         41.0.1    
six                1.12.0    
toml               0.10.0    
traitlets          4.3.2     
urllib3            1.25.3    
wcwidth            0.1.7     
wheel              0.33.4    
zipp               0.5.2   
```

## pytest and operating system versions
Pytest 5.0.1 on Mac OS 10.13.6

## minimal example if possible
Take your favorite project that uses pytest. Assuming it's in $TOPDIR/$DIR, run `cd $TOPDIR ; pytest --rootdir=$DIR`, and pytest config files in $DIR are being ignored. Only config files in current working directory (or above?) are loaded. If you cd into a completely unrelated directory and specify an absolute rootdir, not even the tests are discovered.

This may be a (somewhat unexpected) expected behavior, but if this is the case, I can't find where it is documented.

**Comment by Zac-HD** [comment]
Closing this because it hasn't been answered in several months open 😕

**Comment by nicoddemus** [comment]
(Missed this one)

> Config seems to be only taken from $CWD up and tests only collected from $CWD down, so I am wondering, what --rootdir is actually supposed to be used for.

At the moment `rootdir` only serves for two things:

1. The directory where `.pytest_cache` is created.
2. The root where nodeids are generated: `<root>/testing/test_foo.py` will result in the `testing.test_foo` node id.

Also from [the docs](https://docs.pytest.org/en/latest/customize.html#initialization-determining-rootdir-and-inifile):

> Important to emphasize that rootdir is NOT used to modify sys.path/PYTHONPATH or influence how modules are imported. See pytest import mechanisms and sys.path/PYTHONPATH for more details.
