### ISSUE TITLE
Parametrized tests. Param combination which produce warning.

### ISSUE THREAD

**Issue by BeforeFlight** [pytest-dev/pytest#5622]
- [X] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [X] pytest and operating system versions
- [ ] minimal example if possible

While testing with parametrized params in some tests the code may produce warning. So the problem is that all warnings across all params combinations are collected in in the end of the output without any marks on which params combination the warning arose:
```
======================================================================================= warnings summary =======================================================================================
pandas/core/dtypes/missing.py:433
pandas/core/dtypes/missing.py:433
pandas/core/dtypes/missing.py:433
pandas/core/dtypes/missing.py:433
pandas/core/dtypes/missing.py:433
pandas/core/dtypes/missing.py:433
pandas/core/dtypes/missing.py:433
pandas/core/dtypes/missing.py:433
  /home/beforeflight/github/pandas-BeforeFlight/pandas/core/dtypes/missing.py:433: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
    ensure_object(left.ravel()), ensure_object(right.ravel())
```
Which makes debugging more complicated.

pytest 4.6.4
OS Ubuntu 19.04

**Comment by Zac-HD** [comment]
I suggest turning warnings into errors, e.g. using the `-Werror` command-line argument, which makes it easy to see which tests or code-under-test is causing the warning.

**Comment by BeforeFlight** [comment]
Have already fixed those warnings so have no some to try your suggestion, but believe it works.

Anyway for me as a _user_ logic should be quite simple: warning/error raised -> warning/error printed. Any other is simply workaround and should be considered only as temporary.

But of course I'm not stated here anything - just share my experience as a _user_. So this might be freely closed if _devs_ see no issue here at all.
