### ISSUE TITLE
tox recreates environment even if recreate = false set in configuration

### ISSUE THREAD

**Issue by PJCampi** [pytest-dev/pytest#5635]
Hi guys,

First off thank you very much for the great work on the package!

I have always assumed that `recreate = false` implied that a tox environment would not be recreated if it exists already. It was thus a bit confusing to see my existing environment recreated sometimes nonetheless. For example it happens if I run Tox from the command line, and subsequently in Pycharm via _Tox_ configuration (same configuration).

After some debugging, I discovered that I need to run tox with the python executable that initially created my environment in order to avoid recreating it. The environment path appears to be defined in the _.tox-config1_ file.
In my example above, Pycharm automatically activates the executable called _pythonX.X_ in its command line tool, while it uses the executable called _python_ when you run it via a _Tox_ configuration.

What's the rationale behind ensuring that the same executable is used to prevent recreating an environment?
Additionally, I was wondering if it was possible to add a line or two in the documentation of the `recreate` config field to explain that `false` does not mean that the environment will not be recreated (for example if tox is called from another python)?

I use tox 3.12.1

Thank you,

PJ

**Comment by The-Compiler** [comment]
Please report this in the tox issue tracker: https://github.com/tox-dev/tox/issues
