### ISSUE TITLE
easier pattern for linter-friendly local fixtures

### ISSUE THREAD

**Issue by belm0** [pytest-dev/pytest#5645]
#1444 added a linter-friendly way to deal with locally defined fixtures, but it's rather cumbersome.

I'd like to see the fixture decorator ignore any leading underscore of the wrapped function.  Then usage would be:

```
@pytest.fixture
def _my_fixture():
    ...

def test_foo(my_fixture):
    ...
```

**Comment by RonnyPfannschmidt** [comment]
I'm against adding a implicit name mangling system

**Comment by belm0** [comment]
I can appreciate the aversion to implicitness-- however the fixture scheme is already rather implicit itself.   I mean, define a function and then functions with an *argument* of the same name invoke it as a (stateful) factory...?

Prefixing local functions with underbar is the right thing to do anyway.  The small renaming doesn't seem like a stretch.

**Comment by blueyed** [comment]
@belm0 
What linter is this about?
Maybe it should be made aware of pytest fixtures then maybe?

**Comment by Zac-HD** [comment]
Looks like we have a consensus against.

I'd recommend using standard context managers instead of fixtures, which linters should understand much better.
