### ISSUE TITLE
Pytest Fixture: How to send a parameter into the fixture from the test file?

### ISSUE THREAD

**Issue by mojidadashi** [pytest-dev/pytest#5663]
<!--
I have bunch of fixtures in my Conftest file which I need to run them when I run the test file. All of the fixtures are like setups that we need to do before we get into the tests. 

One of the fixtures that I have  I need to send the parameter name from the test file:
@pytest.fixture(scope="class", params='PORTFOLIO_NAME')
def change_portfolio(request):
    request.cls.topnav.get_profile(request.cls.profile.PROFILE_FINAL_LOADED_ELEMENT)
    request.cls.profile.change_portfolio(request.param)
    assert request.cls.PORTFOLIO_NAME in request.cls.profile.get_row_one_value(column="1")
    request.cls.profile.take_screen_shot("02_check_search")
    request.cls.profile.click_row_one_portfolio()
    request.cls.profile.take_screen_shot("03_change_group")

and in the test file I call it like below:
@pytest.mark.usefixtures("parser", "driver", "setup_classes", "login", "reset_user")
@pytest.mark.parametrize("change_portfolio", [PORTFOLIO_NAME])
class TestProfile:

Portfolio name is a variable that will be defined in the test file, so in the  begining of the testfile I have: 
PORTFOLIO_NAME = "new portfolio"

When I run the test file I get:

test_profile.py:None (test_profile.py)
In test_add_portfolio: function uses no argument 'change_portfolio'
collected 0 items / 1 errors

Note: test_add_portfolio is one of the tests I have in the test file which does not need the portfolio name.

Please help me to know how can I send this parameter name into the "change_portfolio" fixture.
<img width="743" alt="1" src="https://user-images.githubusercontent.com/53317169/61907392-35cd4e00-aee2-11e9-9e76-cacbd1ed4324.png">
<img width="672" alt="2" src="https://user-images.githubusercontent.com/53317169/61907394-3665e480-aee2-11e9-832f-737c445d710c.png">

**Comment by asottile** [comment]
could you elaborate on what you're trying to do? it's unclear from just the title and no example

**Comment by bgroJr** [comment]
To pass a parameter into a fixture, you need to apply the [@pytest.mark.parametrize](http://docs.pytest.org/en/latest/reference.html#pytest-mark-parametrize) decorator to the test function with the **indirect** argument, to do something called *indirect parametrization*. Here's a simple example: 

```python
import pytest

@pytest.fixture
def upper_case_name(request):
    return request.param.upper()

@pytest.mark.parametrize(
    argnames="upper_case_name",
    argvalues=["john"],
    indirect=["upper_case_name"]
)
def test_name_is_upper_case(upper_case_name):
    assert upper_case_name == "JOHN"
```

In this example, there is a `@pytest.fixture` function that takes the [request](http://docs.pytest.org/en/latest/reference.html#request) object as an argument. The fixture accesses `request.param` to get the parameter value. On the test function, there is the `@pytest.mark.parametrize` decorator. The decorator accepts the fixture name (as a string), some parameter values for the fixture (a list), and a list of fixture names (the indirect argument). 

When the `@pytest.mark.parametrize` decorator has an indirect argument, the fixture given as the `indirect` argument will receive the parameter value given in the second argument (argvalues) in the `request` object, passed to the fixture. 

Using this combination of a `@pytest.fixture`, the `request` object, and the `@pytest.mark.parametrize` decorator, you can pass parameter values to a fixture to generate the values needed for a test. 

For reference, here are some links to other examples of people using a similar technique: 
* [StackOverflow: How to parametrize a pytest fixture](https://stackoverflow.com/questions/42228895/how-to-parametrize-a-pytest-fixture)
* [Obey the Testing Goat](obeythetestinggoat.com/a-pytest-pattern-using-parametrize-to-customise-nested-fixtures.html)
* [mark.parametrize with indirect](http://hackebrot.github.io/pytest-tricks/mark_parametrize_with_indirect/)
