### ISSUE TITLE
Missing TestDir.copy_example method in API reference doc

### ISSUE THREAD

**Issue by AntoineD** [pytest-dev/pytest#5669]
See [API reference](https://docs.pytest.org/en/latest/reference.html#testdir) and [code](https://github.com/pytest-dev/pytest/blob/61dcb84f0dd71d8a46c5b1db3bbe563bd731adb3/src/_pytest/pytester.py#L632).

**Comment by asottile** [comment]
Looks like it needs a docstring -- I believe the api is experimental which is why it maybe wasn't documented (note that it currently always raises a warning when called)

Should be pretty easy to add a quick docstring though 👍

**Comment by AntoineD** [comment]
This method appears in the doc for [writing plugins](https://docs.pytest.org/en/latest/writing_plugins.html?highlight=copy_example#testing-plugins), is it really experimental?

**Comment by RonnyPfannschmidt** [comment]
yes, it was introduced and hasn't seen iteration/refinement yet

**Comment by martbln** [comment]
Fixed #5719
