### ISSUE TITLE
Is there a way to run collected tests from a previous session

### ISSUE THREAD

**Issue by nadavishe** [pytest-dev/pytest#5670]
Hello,
I need to accelerate running of tests
One of the places I'd like to save time-is the collection time
Because in my scenario it will always same collection - is there a way to prevent collection again and again, and just to say to pytest to run collected items from the previous run

Thank you, Nadav

**Comment by RonnyPfannschmidt** [comment]
collection cannot be stored/retrieved atm, however the number of files that are checked can be altered

right now its not clear what your exact use-case is, also its not clear what your collection time is and if/why it is high

**Comment by blueyed** [comment]
Check out https://github.com/tarpas/pytest-testmon and/or https://github.com/pytest-dev/pytest-incremental.

**Comment by nadavishe** [comment]
> Check out https://github.com/tarpas/pytest-testmon and/or https://github.com/pytest-dev/pytest-incremental.
Thank you blueyed, this is exactly what i search
