### ISSUE TITLE
RFE: Register markers via command line

### ISSUE THREAD

**Issue by hroncok** [pytest-dev/pytest#5678]
Hello, in Fedora, we have been hit by the combination of this:

 - project uses `pytest-cov` and decorates some tests with `@pytest.mark.no_cover`
 - we don't need/want to use `pytest-cov`
 - pytest warns about unknown marker
 - something is turning warnings into errors

This results in:

```
+ /usr/bin/python3 -m pytest
error: Bad exit status from /var/tmp/rpm-tmp.pPDDgv (%check)
============================= test session starts ==============================
platform linux -- Python 3.8.0b3, pytest-4.6.4, py-1.8.0, pluggy-0.12.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/builddir/build/BUILD/python-dateutil-2.8.0/.hypothesis/examples')
rootdir: /builddir/build/BUILD/python-dateutil-2.8.0, inifile: setup.cfg
plugins: hypothesis-4.23.8
collected 1043 items / 6 errors / 1037 selected
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 206, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 91, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 82, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 259, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 497, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 91, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/manager.py", line 82, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/builddir/build/BUILD/python-dateutil-2.8.0/dateutil/test/conftest.py", line 20, in pytest_collection_modifyitems
INTERNALERROR>     item.add_marker(pytest.mark.no_cover)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/mark/structures.py", line 330, in __getattr__
INTERNALERROR>     warnings.warn(
INTERNALERROR> _pytest.warning_types.PytestUnknownMarkWarning: Unknown pytest.mark.no_cover - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
```

See https://bugzilla.redhat.com/show_bug.cgi?id=1734775

As a workaround, we can register the marker, however creating a config file (or amending one) is required.

I kindly request one of the following features:

 * ability to register marks via command line (e.g. `--register-mark no_cover`)
 * ability to disable unregistered marks warnings via command line (e.g. `--relaxed-marks`)

(I would submit a PR.)

**Comment by The-Compiler** [comment]
You can set any config file option via `-o`, so you can already do `-o markers=no_cover` to register it. You can also ignore the warning via the `-W` commandline option: `-W ignore::_pytest.warning_types.PytestUnknownMarkWarning`

**Comment by hroncok** [comment]
I suppose the `-W` option might be overwritten by the thing that changes it to error. The `-o markers=no_cover` sounds good enough. Thanks. Will test it.

**Comment by hroncok** [comment]
`-o markers=no_cover` seem to override all already registered markers.

**Comment by hroncok** [comment]
The `-W ignore::pytest.PytestUnknownMarkWarning` workaround works (in this case).

**Comment by RonnyPfannschmidt** [comment]
Why not register the marker in your pytest configfile? That should be the way if you use markers registered in optional dep

I'm.-1on registration of marks on the cli

**Comment by hroncok** [comment]
We'd like to have an easy way of doing it without patching the project we are testing. That said, I'd take no as an answer, it's just an RFE.

**Comment by nicoddemus** [comment]
> We'd like to have an easy way of doing it without patching the project we are testing.

Just to be clear, it's a 3rd party project being tested?

**Comment by RonnyPfannschmidt** [comment]
In that case a plugin is the best place for it

**Comment by hroncok** [comment]
> Just to be clear, it's a 3rd party project being tested?

Yes, as a distribution, we are building packages with 3rd party projects. During the build, we are running the tests to verify everything works. We don't really care about coverage and we like to avoid depending on extra stuff, such as a coverage plugin (or a custom plugin suggested by Ronny).

Obviously, in this case, we should probably send a PR to the project being tested, that makes the dependency on the coverage plugin optional. But as a more general solution, I thought it would be nice to have this option (registering marks via command line).

**Comment by nicoddemus** [comment]
Yeah in this case I suggest just ignoring the warning.

Registering marks in the command-line is probably not a good idea because we have plans to make marks (optionally) more than just objects created by pytest.mark, but also to allow class-based objects.

Glad you have found a workaround though.

@RonnyPfannschmidt please close this as "wontfix" then. 👍

**Comment by RonnyPfannschmidt** [comment]
closing as wont fix, didn't  we have a label for that

**Comment by hroncok** [comment]
Thank you all, especially @The-Compiler for the workarounds.
