### ISSUE TITLE
Mark parametrized tests

### ISSUE THREAD

**Issue by acerv** [pytest-dev/pytest#5679]
Hello everyone,

I'm actually generating parametrized tests using `pytest_generate_tests` hook as explained in the documentation. Is there a way to apply a marker to parametrized tests once they are added to the pytest queue?

Suppose I already added a marker called `mymarker` inside an external plugin. Please use this example just as a reference:

    def pytest_generate_tests(metafunc):
        if "stringinput" in metafunc.fixturenames:
            metafunc.parametrize("stringinput", "HELLO!")

            # here I would like to apply mymarker to all parametrized functions

    def test_valid_string(stringinput):
        print stringinput

Setup:
- Platform: Windows & Linux
- pytest version: 4.6.3

Thank you in advice,
Andrea

**Comment by RonnyPfannschmidt** [comment]
i vaugely recall that `metafunc` has a `applymarker` method, that should do, also you can  use `pytest.param` to annotate the parameters

**Comment by acerv** [comment]
Do you have a working example? Because I tried `applymarker` inside the hook without success

**Comment by RonnyPfannschmidt** [comment]
@acerv oif the  mark added in applymarker does not transfer to the test then its a bug

can you give a more elabrate example of waht you try to do?

**Comment by acerv** [comment]
I've seen the code in deep and applymarker works well. I was generating a report file with a custom plugin that was not storing marker informations during tests execution. Now it's working, after fixing the plugin generating the report file.

Thank you!

**Comment by RonnyPfannschmidt** [comment]
thanks for the followup, i'll close this one then as solved
