### ISSUE TITLE
testdir.getitems not parsing test when `import pytest` present

### ISSUE THREAD

**Issue by joelberkeley-pio** [pytest-dev/pytest#5683]
I am writing a test for a pytest plugin. For this, I want to have tests with and without `@pytest.mark.slow`. In the following I have not used the decorator anywhere. If and only if I include `import pytest` in the string to parse as a test, the `testdir.getitem` fails as shown below. If I use `testdir.getitems` instead, I just get an empty list.

I have
`pytest_plugins = ["pytester"]`
in my conftest.py

This passes
```
def test_this(testdir):
    testdir.getitem(
        "def test_func():   "
        "    pass           "
    )
```
while this fails
```
def test_this(testdir):
    testdir.getitem(
        "import pytest      "
        "def test_func():   "
        "    pass           "
    )
```
with

> AssertionError: 'test_func' item not found in module:
> E         import pytest      def test_func():       pass           
> E         items: []
> E       assert 0

```
$ pip list
atomicwrites       1.3.0   
attrs              19.1.0  
certifi            2019.3.9
chardet            3.0.4   
idna               2.8     
importlib-metadata 0.19    
mock               2.0.0   
more-itertools     7.2.0   
numpy              1.17.0  
packaging          19.0    
pandas             0.24.2  
pathlib2           2.3.4   
pbr                5.1.3   
pip                19.0.2  
pluggy             0.12.0  
py                 1.8.0   
pyparsing          2.4.1.1 
pytest             5.0.1   
python-dateutil    2.8.0   
pytz               2019.1  
setuptools         40.8.0  
six                1.12.0  
urllib3            1.24.3  
wcwidth            0.1.7   
wheel              0.32.3  
zipp               0.5.2
```

OS Ubuntu 16.04
pytest version 5.0.1

**Comment by nicoddemus** [comment]
Hi @joelberkeley-pio,

You are missing newlines on the strings:

```python
        "import pytest      \n"
        "def test_func():   \n"
        "    pass           \n"
```

Without the newlines, the string is actually:

```python
"import pytest    def test_func():   pass"
```

Which is not valid.

Your first example works because:

```python
        "def test_func():   "
        "    pass           "
```

Is:

```python
"def test_func():   pass"
```

Which is valid Python. 😁 


Closing for now, feel free to follow with further questions.
