### ISSUE TITLE
disallow absolute and non-normalized paths for mktemp

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#5686]
followup to #4202

this is an potential issue and attack vector, absolute paths are no tmpdir and escaping paths aren't either,
just normalizing would also break the world

so we should only ever accept normalized relative paths for it

**Comment by gftea** [comment]
Hi,

Can I try to work on this. I am new, but this seems not a difficult job.

**Comment by nicoddemus** [comment]
Great @gftea, feel free to open a PR (even if incomplete) and we can discuss it from there. 👍
