### ISSUE TITLE
[Question]is it intentional that all conftests get loaded under this scenario?

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#5688]
Here is an example tree (excuse the cache dirs):

```python
C:.
├───.idea
│       misc.xml
│       modules.xml
│       pycharmer.iml
│       workspace.xml
│
└───tests
    │   conftest.py
    │
    ├───interface
    │   ├───interface
    │   │   │   conftest.py
    │   │   │   test_intf.py
    │   │   │
    │   │   └───__pycache__
    │   │           conftest.cpython-37-pytest-5.0.1.pyc
    │   │           test_intf.cpython-37-pytest-5.0.1.pyc
    │   │
    │   └───system
    │       │   conftest.py
    │       │   test_sys.py
    │       │
    │       └───__pycache__
    │               conftest.cpython-37-pytest-5.0.1.pyc
    │               test_sys.cpython-37-pytest-5.0.1.pyc
    │
    ├───production
    │   │   conftest.py
    │   │   test_prod.py
    │   │
    │   ├───.pytest_cache
    │   │   │   .gitignore
    │   │   │   CACHEDIR.TAG
    │   │   │   README.md
    │   │   │
    │   │   └───v
    │   │       └───cache
    │   │               nodeids
    │   │               stepwise
    │   │
    │   └───__pycache__
    │           conftest.cpython-37-pytest-5.0.1.pyc
    │           test_prod.cpython-37-pytest-5.0.1.pyc
    │
    └───__pycache__
            conftest.cpython-37-pytest-5.0.1.pyc

```

Production file:
```python
import pytest


class TestProduction:

    @pytest.mark.prod
    def test_production(self):
        assert 1 == 1
```

System file:
```python
import pytest


class TestSystem:

    @pytest.mark.system
    def test_system(self):
        assert 1 == 1
```

Integration file:

```python
import pytest


class TestIntegration:

    @pytest.mark.integration
    def test_integration(self):
        assert 1 == 1
```

is it intentional that when executing the following:

`pytest -m prod` that all 3 conftest files get loaded here? I thought the ones not in root/prod (e.g interface/system would NOT be loaded in that scenario, guess i am misunderstanding?)

```python
rootdir: C:\Users\sy\PycharmProjects\pycharmer
collecting ... prod conftest
PLUGIN registered: <module 'conftest' from 'C:\\Users\\sy\\PycharmProjects\\pycharmer\\tests\\production\\conftest.py'>
interface conf
PLUGIN registered: <module 'conftest' from 'C:\\Users\\sy\\PycharmProjects\\pycharmer\\tests\\interface\\interface\\conftest.py'>
sys conf
PLUGIN registered: <module 'conftest' from 'C:\\Users\\sy\\PycharmProjects\\pycharmer\\tests\\interface\\system\\conftest.py'>
collected 3 items / 2 deselected / 1 selected              
```

How do autouse fixtures work in this regard? since all 3 are collected with an autouse function scoped fixture apply to EVERY test? lets say i had the following in production folders conftest.py:

```python
@pytest.fixture(scope='function', autouse=True)
def do_fixture(request):
    print('AUTO USE ON')
```

Will this execute on EVERY test then? how do you have only autouse fixtures apply to tests in their own directory respectively, e.g the above fixture would only apply to the tests in the 'production directory'? Just trying to gain an understanding on how this stuff works

I'm reading about fixtures, it states that 'plugins' should be careful with autouse fixtures, what makes a conftest.py file considered a 'plugin' ?

**Comment by nicoddemus** [comment]
Hi @symonk,

> pytest -m prod that all 3 conftest files get loaded here?

`-m` is a *selector*, meaning that it will select some tests based on their marker, after *all* tests are collected. That's why all conftests are loaded. You most likely are seeing all your tests collected in the "collected XX" message in your terminal, I assume.

>  since all 3 are collected with an autouse function scoped fixture apply to EVERY test?

Depends where the fixture is located. An autouse fixture declared in a `conftest.py` file will be applied to all tests at or below the directory the `conftest.py` file is located.

> Will this execute on EVERY test then? how do you have only autouse fixtures apply to tests in their own directory respectively, e.g the above fixture would only apply to the tests in the 'production directory'? Just trying to gain an understanding on how this stuff works

I think I have answered that above, let me know if it is still not clear.

> I'm reading about fixtures, it states that 'plugins' should be careful with autouse fixtures, what makes a conftest.py file considered a 'plugin' ?

`conftest.py` files are called a "local" plugin, in the sense that their fixtures are visible and hooks are called only for tests at or below where the `conftest.py` are located (beware some hooks don't work on `conftest.py`, those are documented as such).

Hope this clarifies things a bit.

**Comment by symonk** [comment]
ok I have an example in work where the layout above with a @autouse function fixture is applying to ALL tests collected by -m, ones that do not reside in the directory of the conftest that contains it.  I read on the docs about autouse functions within plugins can apply fixtures globally (so care is advised) could you elaborate on that? I think I may be falling fowl on this, but i don't know exactly what i've done in the conftest to make it happen.  I thought maybe defining a pytest_configure (or any other hook impl) would cause this.  I am experiencing this:

```
lastly, and please use that with care: if you define an autouse fixture in a plugin, it will be invoked for all tests in all projects where the plugin is installed. This can be useful if a fixture only anyway works in the presence of certain settings e. g. in the ini-file. Such a global fixture should always quickly determine if it should do any work and avoid otherwise expensive imports or computation.
```

but from a fixture inside the conftest, so im very confused! what criteria in a 'conftest.py' could cause the above behaviour ^? 

Thank you @nicoddemus

**Comment by symonk** [comment]
so i collect on my marker, here we see:

```python
<Module tests/product/api/v1/billing_endpoint/test_billing_get.py>
  <Class TestBillingEndpointGet>
```

Now, lets have a look at some of the fixtures:
Very important to see that these fixtures
```
---------------------------------------------------------------------------------- fixtures defined from tests_product_interface_conftest ----------------------------------------------------------------------------------
test_clean_up
    lib/conftests/tests_product_interface_conftest.py:133: no docstring available
manage_test_lifecycle
    lib/conftests/tests_product_interface_conftest.py:38: no docstring available
prepare_settings_and_entities
    lib/conftests/tests_product_interface_conftest.py:48: no docstring available
inject_mailflow_data
    lib/conftests/tests_product_interface_conftest.py:89: no docstring available
```

Lets look at one of the above fixtures:
```python
@pytest.fixture(scope='function', autouse=True)
def test_clean_up(request):
    request.addfinalizer(lambda: __delete_entities(request))
```
Now lets run a test that sites in a directory which is not even in the same folder as the conftest.py containing the above fixtures...

```     SETUP    F inject_mailflow_data2019-08-03T00:32:52  00:00.003518  [    INFO]  report_helper.py:35  **************************** Starting test: test_billing_response_code_for_admin ****************************

        SETUP    F manage_test_lifecycle
        SETUP    F test_clean_up
        SETUP    F destroy_test_data
```

these tests collected by the marker live here:

tests/product/api

the conftest with the above fixture lives here:

tests/product/system/conftest.py

these fixtures should **not** be executing, what on earth have I done wrong?

n.b my /tests dir is a symlink

**Comment by nicoddemus** [comment]
Hmm indeed it is strange. Can you produce a minimal example that I can execute, so I can see what's going on? Probably the exact same tree you have, but without the actual code is enough.

**Comment by symonk** [comment]
@nicoddemus I think its caused by my entire /tests dir being a symlink? if you see my contests they live in /lib

--lib
---conftests
----3x conftest files
--tests(symlinked in from outside)
--...

Would this be problematic?

**Comment by symonk** [comment]
will recreate a minimal repeatable example in the morning, its 2am and ive been working from since 6am, gotta take a break :D

**Comment by nicoddemus** [comment]
A simple test is to not make `tests` a symlink, copy them over and see if this changes things.

> will recreate a minimal repeatable example in the morning, its 2am and ive been working from since 6am, gotta take a break :D

Sure, take a well deserved rest!

**Comment by symonk** [comment]
Yep so I think i tried that and it works, unfortunately its not possible for me to change the setup in work, can I make pytest fit my needs with hooks at all? the symlink must remain :(

**Comment by nicoddemus** [comment]
> can I make pytest fit my needs with hooks at all?

We would have analyse that with more diligence, I'm afraid I can't confirm that outright.

**Comment by symonk** [comment]
ok I will reproduce a small example tomorrow and we can have a look :) thanks for your time and have a good night

**Comment by symonk** [comment]
sorry been a busy week, will get back onto this now!
