### ISSUE TITLE
import pytest:TypeError: __call__() got an unexpected keyword argument 'warn_on_impl'

### ISSUE THREAD

**Issue by jade-li1115** [pytest-dev/pytest#5695]
i dont know what i did makes my pytest couldnt work now:(((
![image](https://user-images.githubusercontent.com/53292092/62432360-d3861000-b761-11e9-8fb1-ce18269e71aa.png)

**Comment by asottile** [comment]
it appears you have an incompatible version of `pluggy` -- try `C:\Python27\python.exe -m pip install --upgrade pluggy` perhaps

**Comment by jade-li1115** [comment]
thank you,it works:)) but i didnt change my pluggy,before i could use it ,its weird

**Comment by jade-li1115** [comment]
> it appears you have an incompatible version of `pluggy` -- try `C:\Python27\python.exe -m pip install --upgrade pluggy` perhaps

thank you,it works:)) but i didnt change my pluggy,before i could use it ,its weird

**Comment by asottile** [comment]
not sure, maybe you `pip install`d something else which caused a downgrade?

**Comment by nicoddemus** [comment]
Glad it worked, I think we can close this now?

**Comment by asottile** [comment]
Yep, I think so
