### ISSUE TITLE
Introduction of code of conduct for pytest

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#5709]
I figure we're a large enough organization that runs a decent amount of public relations through github issues / PRs that it would make sense that we set up some clear guidelines on contributions and conduct.  I've never worked with a CoC before but I think it would be good to formalize a set of guidelines that ensure that we as individual contributors are producing high quality external and internal interactions.

As I don't know the first thing about the _right_ thing to do for a CoC I'm opening this as more of a RFC / open ended discussion where we can choose the right approach here.  My main goals are that we end at a place where we can all have positive interactions with individuals and foster a positive community (much like we're hopefully already doing!).

A few examples we might be able to follow here:

- [pypa CoC](https://www.pypa.io/en/latest/code-of-conduct/)
- [psf CoC](https://www.python.org/psf/codeofconduct/)

**Comment by The-Compiler** [comment]
Big :+1: - we've already had a discussion on a mailinglist a while ago and I volunteered to take care of things, then got distracted by studies and exams... My bad! :worried: 

Relevant mails:

https://mail.python.org/pipermail/pytest-dev/2018-July/004549.html
https://mail.python.org/pipermail/pytest-dev/2018-July/004550.html
https://mail.python.org/pipermail/pytest-dev/2018-July/004551.html
https://mail.python.org/pipermail/pytest-dev/2018-July/004552.html
https://mail.python.org/pipermail/pytest-dev/2018-July/004554.html
https://mail.python.org/pipermail/pytest-dev/2018-July/004556.html
https://mail.python.org/pipermail/pytest-dev/2018-July/004557.html
https://mail.python.org/pipermail/pytest-dev/2018-August/004562.html
https://mail.python.org/pipermail/pytest-dev/2018-August/004563.html
https://mail.python.org/pipermail/pytest-dev/2018-August/004564.html
https://mail.python.org/pipermail/pytest-dev/2018-August/004565.html

If someone wants to pick up things that'd be great - another (last) exam is coming up, so the earliest I could pick this up is in September.

cc @davehunt

**Comment by RonnyPfannschmidt** [comment]
i'd like to note that @The-Compiler also already did set up  coc@pytest.org as an alias

and Brianna, @nicoddemus, @The-Compiler and  me are receiving messages for it

also based on current information i'm happy to adopt the contributor covenant in a recent version even if i disagree with various behaviors of its creators

it will be critical to build a awareness of the spirit we want to bring across by adding the letters of a CoC, and then to make sure we keep the spirit in mind when interpreting the letters when enforcement is necessary

**Comment by The-Compiler** [comment]
Oh, I totally forgot about having that set up already :laughing: I opened a PR to get the ball rolling: #5711 

And now I'm back to my exams (I'll take a look at emails though!) :man_student:

**Comment by asottile** [comment]
via #5711
