### ISSUE TITLE
pytest is not collecting custom tests via directory

### ISSUE THREAD

**Issue by acerv** [pytest-dev/pytest#5710]
Hello everyone,
It looks like pytest is not collecting custom tests giving tests folder only (it collects python tests only by default).

conftest.py file is the following

        import pytest

        class MyItem(pytest.Item):
            nodeid = 'foo'
            def runtest(self):
                pass

        def pytest_collect_file(path, parent):
            if path.ext == ".yaml" and path.basename.startswith("test"):
                return MyItem("foo", parent)

Inside `tests` directory place an empty Yaml file called `test_mytest.yaml`.

When runnning pytest with `pytest tests/` command, no tests are found:

    ============================= test session starts =============================
    platform win32 -- Python 2.7.15, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
    rootdir: c:\userdata, inifile: pytest.ini
    plugins: marvin-2.4.0
    collected 0 items                                                              
    ======================== no tests ran in 0.04 seconds =========================

Is it a bug? According with documentation for custom tests, the example should work.

Thanks,
Andrea

**Comment by RonnyPfannschmidt** [comment]
my understanding is that you need to return a collector there
you you would need a collector for the file and then a test item as well

**Comment by acerv** [comment]
I took the Yaml custom tests file example and tried to execute `pytest -v` as explained in the documentation, without having the same result. Is documentation outdated?

Could you please example where I should return a collector? Is there an example showing how to do it?

**Comment by RonnyPfannschmidt** [comment]
http://doc.pytest.org/en/latest/example/nonpython.html has YamlFile and YamlItem to sort this out

**Comment by acerv** [comment]
I just tried to copy paste the conftest.py and `pytest tests/` command is still not collecting items. Try to believe :)

**Comment by RonnyPfannschmidt** [comment]
next we would need is a debug trace of pytest to figure why its not acting on the conftest

**Comment by acerv** [comment]
I'm sorry, but it looks like I was doing something wrong with an another plugin that was ignoring all extensions beside ".py". This issue can be rejected. Thank you anyway

**Comment by The-Compiler** [comment]
No worries - thanks for the follow-up!
