### ISSUE TITLE
Undocumented method of fixture parametrization

### ISSUE THREAD

**Issue by harius** [pytest-dev/pytest#5712]
This test passes:
```python
import pytest


@pytest.fixture
def fixture(argument):
    return argument


@pytest.mark.parametrize("argument", ["foo", "bar"])
def test_with_argument(argument, fixture):
    assert argument == fixture


@pytest.mark.parametrize("argument", ["baz"])
def test_without_argument(fixture):
    assert "baz" == fixture
```

I failed to find any documentation on this argument passing technique.
Is it a supported and known feature or just a by-product of `pytest.mark.parametrize` implementation details?

My setup:
```bash
$ pip list | grep pytest
pytest                             3.8.0                                           
pytest-socket                      0.3.1
```

**Comment by harius** [comment]
It looks almost like [overriding a fixture with a parameter](https://docs.pytest.org/en/latest/fixture.html#override-a-fixture-with-direct-test-parametrization), except that in my nothing is overridden (there is no fixture named "argument")

**Comment by RonnyPfannschmidt** [comment]
i believe its exactly that and we should elevate it to a actual feature

**Comment by erheron** [comment]
Hi! Is there still a need to work on this issue?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus in that case we probably need to make the indirect a required argument there

as  for fixtures, we will need to include a mechanism to distinguish between declared with params, declared as must be configured with params, declared as not having params (to enable better failing)

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt just to be clear:

```python
@pytest.mark.parametrize("argument", ["baz"], indirect=True)
def test_without_argument(fixture):
    assert "baz" == fixture
```

(`indirect=["argument"]` would also be valid)

I agree, if `indirect` not given we should raise an explicit error requiring `indirect=True` or `indirect=["argument"]`.

Updated the labels to reflect that.

**Comment by erheron** [comment]
Hi! Could someone take a look at this commit on my fork of pytest?
I'm aware of fact this is far away from production-ready code, but just to check if the direction is right. 
https://github.com/erheron/pytest/commit/89086a13f7f6faafd24da236b2a6e88468c3f17f

**Comment by blueyed** [comment]
JFI: a PR is being worked on at https://github.com/pytest-dev/pytest/pull/6330  (for email notifications)

**Comment by nicoddemus** [comment]
Unfortunately we had to revert this in https://github.com/pytest-dev/pytest/pull/6914 because it caused a number of regressions; people do rely on this, unfortunately.
