### ISSUE TITLE
Use autouse fixtures via conftest.py for custom tests

### ISSUE THREAD

**Issue by acerv** [pytest-dev/pytest#5715]
Hello everyone,

I'm trying to execute custom Yaml tests using pytest, but it looks like that any autouse fixture inside conftest.py is ignored for Yaml tests.

Is there a way to support them?

Thanks,
Andrea

**Comment by acerv** [comment]
Here's an example:

conftest.y

    # content of conftest.py
    import pytest
    import logging


    def pytest_collect_file(parent, path):
        if path.ext == ".yaml" and path.basename.startswith("test"):
            return YamlFile(path, parent)


    class YamlFile(pytest.File):
        def collect(self):
            import yaml  # we need a yaml parser, e.g. PyYAML

            raw = yaml.safe_load(self.fspath.open())
            for name, spec in sorted(raw.items()):
                yield YamlItem(name, self, spec)


    class YamlItem(pytest.Item):
        def __init__(self, name, parent, spec):
            super(YamlItem, self).__init__(name, parent)
            self.spec = spec
            self.logger = logging.getLogger("yaml.test")

        def runtest(self):
            self.logger.info("running test with spec=%s", self.spec)


    # this fixture never works
    @pytest.fixture(scope="session", autouse=True)
    def _crash():
        assert False


test_mytest.yaml

    ok:
        sub1: sub1

    hello:
        world: world
        some: other
        

After executing, I would expect to see an assert during test setup, but nothing hapens:

    (venv) C:\userdata\workspaces\app_tools\testtttt>pytest
    ============================= test session starts =============================
    platform win32 -- Python 2.7.15, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
    rootdir: C:\userdata, inifile: pytest.ini
    collected 2 items                                                              

    test_mytest.yaml ..                                                      [100%]

    ========================== 2 passed in 0.05 seconds ===========================

**Comment by Zac-HD** [comment]
Closing this issue as an inactive question.
