### ISSUE TITLE
test function or fixture use request and parametrized at the same time

### ISSUE THREAD

**Issue by Candidate48** [pytest-dev/pytest#5720]
I want use different http host to run the test function (api test)  without changing the code.
then I use [Pass different values to a test function, depending on command line options](http://www.pytest.org/en/latest/example/simple.html#pass-different-values-to-a-test-function-depending-on-command-line-options) . 
```
def test_temp(self, request):
    print("run_host  is  " + request.config.getoption("--test_env"))
```
my test function or pytest fixture use input function arguments `request` can get the command line options value .but the test function `test_temp` need parametrized by `@pytest.mark.parametrize` , and the parametrized decorator take up the function arguments.

then i try fixture parametrize way .to get the test data and request,but get Error `has no attribute 'config'`
```
    @pytest.fixture(scope='module', params=[0, 1, 2])
    def uid(request):
        data = []
        data.append(request.config.getoption("--test_env"))
        data.append(request.param)
        return data

    def test_tt1(self, uid):
        print(uid[0])
        print(uid[1])
```
what can i do ?

or other way modify the run environment using the command line

**Comment by The-Compiler** [comment]
> but the test function `test_temp` need parametrized by `@pytest.mark.parametrize` , and the parametrized decorator take up the function arguments.

You can freely mix fixtures (like `request`) and parametrization - the parametrize decorator only cares about the arguments you list in it.

This should work fine:

```python
import pytest

@pytest.mark.parametrize('uid', [0, 1, 2])
def test_temp(request, uid):
    print("run_host is " + request.config.getoption("--test_env"))
    print("uid is " + uid)
```

**Comment by Candidate48** [comment]
> > but the test function `test_temp` need parametrized by `@pytest.mark.parametrize` , and the parametrized decorator take up the function arguments.
> 
> You can freely mix fixtures (like `request`) and parametrization - the parametrize decorator only cares about the arguments you list in it.
> 
> This should work fine:
> 
> ```python
> import pytest
> 
> @pytest.mark.parametrize('uid', [0, 1, 2])
> def test_temp(request, uid):
>     print("run_host is " + request.config.getoption("--test_env"))
>     print("uid is " + uid)
> ```

Thanks for your help!
