### ISSUE TITLE
Problem mit Approx

### ISSUE THREAD

**Issue by DuckNrOne** [pytest-dev/pytest#5737]
Hey guy,

I have a little problem with the function *approx*. I use it alot in a project, but in one situation it looks like the code by this [guy](https://github.com/pytest-dev/pytest/issues/2003). 

Here is the spesific [file](https://github.com/DuckNrOne/symfit/blob/PytestApprox/tests/test_constrained_py.py#L853), the line of code at 853:
`assert constr_value[0] == pytest.approx(0, 1e-5)`

The error:
```
E           assert -1.758637679927233e-11 == 0 ± 1.0e-12
E            +  where 0 ± 1.0e-12 = <function approx at 0x000001BB36AF9400>(0, 1e-11)
E            +    where <function approx at 0x000001BB36AF9400> = pytest.approx
```
I'm using the pytest version 4.3.1 from Anaconda3 and win 10 and these are [my packages](https://github.com/pytest-dev/pytest/files/3498815/pipList.txt).

**Comment by The-Compiler** [comment]
I don't follow. You expect a value to be 0 ± 1.0e-12 but it is -1.758637679927233e-11 which is far smaller (i.e. [further away from 0](https://www.wolframalpha.com/input/?i=-1.758637679927233e-11,+-1.0e-12)).

**Comment by DuckNrOne** [comment]
I know and i don't want it. I expected a value 0 ± 1e-5 (see code [line](https://github.com/DuckNrOne/symfit/blob/PytestApprox/tests/test_constrained_py.py#L853)), but pytest ignores my decision and uses 1e-12

**Comment by kalekundert** [comment]
I think the problem is that you specified a relative tolerance instead of an absolute tolerance, and anything relative to 0 is still 0.  Try this instead:
```
assert constr_value[0] == pytest.approx(0, abs=1e-5)
```
The logic behind all of this is explained here: https://docs.pytest.org/en/latest/reference.html#pytest-approx

**Comment by DuckNrOne** [comment]
Great! Now it works like expected. Thanks for your quick help. 👍
