### ISSUE TITLE
Migrate docstrings to NumPy style or Google style

### ISSUE THREAD

**Issue by timhoffm** [pytest-dev/pytest#5753]
Is there an interest in migrating docstring from plain reStructuredText to [NumPy- or Google-style docstrings](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html?highlight=numpy)? They are simpler to write and more readable as plain text.

I would be willing to contribute here.

**Comment by asottile** [comment]
I'm -1, the automatic sphinx doc generation is fine with what we have and the churn seems not worth it -- plus iirc there isn't a great way to cross reference

**Comment by timhoffm** [comment]
This is not about placating sphinx. It‘s about making raw docstings easier to read and write. Also, I don‘t see how these affect cross-referencing. But I‘m not going to push this if there is no appreciation for the proposed change.

**Comment by blueyed** [comment]
AFAICS we have no consistent way for docstrings - they seem to also be ad-hoc often.

It would be great to at least have a recommended (canonical) way for them.

**Comment by timhoffm** [comment]
By now, we do have quite detailed rules how to write docstrings:
https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings

They are not yet in place everywhere because there's quite a lot of documentation. But we're continuously replacing old stuff (ideally improving the content of the docstring as we go along as well). Help is always welcome :smile:.

**Comment by blueyed** [comment]
@timhoffm 
I was talking about pytest, where such rules are not in place.

**Comment by nicoddemus** [comment]
> It would be great to at least have a recommended (canonical) way for them.

Agreed. I always wrote sphinx-style when using them.

Should we add this convention somewhere?

**Comment by timhoffm** [comment]
@blueyed Sorry I was not paying attention to the repo 🐑.
