### ISSUE TITLE
Checking NoneType by comparison with approx

### ISSUE THREAD

**Issue by DuckNrOne** [pytest-dev/pytest#5771]
Hey
Either it's an issue or a feature request :D 
I have the following situation: I want to use the approx feature to compare two results form a function. These two methods may return *None*. In this case, I have to use such ugly code:
'''
tempResult = functionA()
if tempResult is not None:
    assert tempResult == pytest.approx(functionB())
'''
How can I compare returned values with the premise that they can be *None* using approx?

Grüße

**Comment by nicoddemus** [comment]
Hi @DuckNrOne,

Thanks for writing!

IMO `pytest.approx` should not allow `None` as this can hide errors and misuses. I suggest to be explicit about it, or use an auxiliary function if this patterns appear a lot in your test suite:

```python
def check_approx_or_none(a, b):
    if a is not None and b is not None:
         assert a == pytest.approx(b)

def test_foo():
    check_approx_or_none(functionA(), functionB())
```

Closing for now, feel free to follow with further questions. 👍

**Comment by DuckNrOne** [comment]
I got you, but if both functions return None, there are equal. Wouldn't that be a nice feature? I was converting unittests in pytest and unittest compares or checks for Nonetype.

**Comment by The-Compiler** [comment]
Hmm, looks like Python's unittest [considers](https://github.com/python/cpython/blob/v3.7.4/Lib/unittest/case.py#L874-L879) anything almostEqual when it's equal.

Not sure if I'd consider that a good idea though...

**Comment by nicoddemus** [comment]
`pytest.approx` is meant to compare floating numbers... definitely feels error prone to allow `None`. Also considering this seems like an edge-case rather than a common feature, further suggests this probably will bring more problems than solve them IMHO.

**Comment by RonnyPfannschmidt** [comment]
something like an almost_equal helper would be in the domain of assertion helper functions, we sstill have to flesh out the api/non-api for those

assert almost_equal(a, b) certainly would be a ncie api, ,,but that's for a different issue
