### ISSUE TITLE
Move makefile from testdir to tmpdir?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5774]
The `makefile` method is useful to create several files in a temporary directory, but is currently provided via `testdir`.

It would be useful to have it with `tmpdir` already.

Of course backward compatibility should be kept, but might make room for improving/fixing its API (if there's anything to be fixed there).

What do you think?

Code ref: https://github.com/pytest-dev/pytest/blob/daff9066c/src/_pytest/pytester.py#L564-L583

**Comment by nicoddemus** [comment]
The problem that I see is that we plan to eventually replace `tmpdir` by `tmp_path`, or at the very least keep them paired feature-wise.

**Comment by RonnyPfannschmidt** [comment]
IMHO fundamentaly a no go - `py.path` is to be removed and dead, `pathlib` is never going to be nicely convenient

**Comment by blueyed** [comment]
The functionally could be provided with new APIs, regardless of tmpdir/tmp_path/py.path/pathlib?!

For reference, tox has `create_files`: https://github.com/tox-dev/tox/blob/041f867a4befbb262ca4121dbb90a6604c4097e1/src/tox/_pytestplugin.py#L474-L480

**Comment by nicoddemus** [comment]
I thought you meant adding it as a method (as it is currently) instead of a free function. We have thought about having free functions such as `fnmatch_lines`-like as part of the API.

**Comment by blueyed** [comment]
It would be a method.
But both tmpdir / tmp_path could have it (maybe only tmp_path then), no?

**Comment by nicoddemus** [comment]
> It would be a method.

Not sure I'm a big fan of subclassing `pathlib.Path` or monkeypatching it to inject a method.

To make conversation easier, can you provide an example usage of a concrete proposal?

**Comment by RonnyPfannschmidt** [comment]
@blueyed a free standing function is fine, in that case any path-alike would be supported (it should just cast to the pytest Path and be done with it

**Comment by RonnyPfannschmidt** [comment]
closing as tmpdir is deprecated
