### ISSUE TITLE
Correctness issues with @pytest.mark.parametrize()

### ISSUE THREAD

**Issue by yingw787** [pytest-dev/pytest#5777]
Major correctness issue found with @pytest.mark.parametrize, where parametrized fixtures are not taken into account when stub methods assert False. Doesn't seem to matter what the params are in the fixture, if the stub returns False the parametrized test returns True.

This was tested with Pytest 3.8.0 and Python 3.6.6 on Ubuntu 16.04 (x86_64), and Pytest 5.1.1 and Python 3.7.1 on macOS 10.12.6 (x86_64).

```
import pytest

# generate_column_properties() #
@pytest.mark.parametrize('params', (
    [
        # User-specified input overrides the entire Spark dataframe schema in a
        # valid manner.
        {
            'a': 0
        }
    ]
))
def test_generate_column_properties_works(params):
    return False
```

`python -m pytest test.py`

**Comment by The-Compiler** [comment]
I don't understand what the issue is. The test in your example passes, and I'd expect it to. Usually, you wouldn't return any value from a test.

**Comment by yingw787** [comment]
@The-Compiler @RonnyPfannschmidt Yes, you are correct. I retried with `assert` and the tests fail/succeed according to inputs properly. My apologies for not reading the documentation thoroughly.
