### ISSUE TITLE
Support for zipapp-based python standalone application

### ISSUE THREAD

**Issue by RyanSiu1995** [pytest-dev/pytest#5780]
Since python 3.5, developers can release their application through zipapp. It provides a great functionality in standalone application delivery.
But how can we ensure the packaged app is well-tested with pytest? Right before the packaging, we can use pytest scan through the whole repo. After the package, there is no way to test through the packaged application. There may be some issues during the packaging.
In order to facilitate the delivery of the standalone application, the support for zipapp from pytest is necessary.
I have two proposals for this issue.
1. Support zipapp scanning, e.g. `pytest myapplication.pyz`
This approach assumes the test cases are packaged along with the source code. If pytest detects the file format as pyz, it will decompress the zip file and scan through the directory. A quick and brute force solution in the support of zipapp-based application.
2. Add `--zipapp=app.pyz` as a support flag
This solution assumes the test cases are not packaged along with the source code. In my past experience in the development, test cases are not necessary for runtime. They, in general, are not included in the built binary. Based on this assumption, the developer can package a test-free standalone application with the following file structure
```
| - app.pyz
| - src/
| - tests/
    | - test_a.py
    | - test_b.py
```
Then, the developers can invoke a command like this `pytest --zipapp=app.pyz tests/`. Pytest will then create a virtualenv with the zipapp for running those tests.

Please let me know if there is a function like this. I will delete the issue afterward.
Thank you!

**Comment by asottile** [comment]
I'm pretty sure this already works, take for instance the `virtualenv` zipapp:

```bash
git clone git@github.com:pypa/virtualenv
cd virtualenv
python3 tasks/make_zipapp.py
cp *.pyz ..
rm -rf virtualenv
```

```python
import os.path

import virtualenv


def test():
    assert not os.path.exists(virtualenv.__file__)
```

```console
$ PYTHONPATH=virtualenv.pyz pytest test.py 
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.1.1, py-1.8.0, pluggy-0.12.0
rootdir: /tmp/x
collected 1 item                                                               

test.py .                                                                [100%]

============================== 1 passed in 0.05s ===============================
```

**Comment by RyanSiu1995** [comment]
@asottile Thanks a lot! It makes a lot of sense to me now!
