### ISSUE TITLE
UNC path in additional argument causes tox failure 

### ISSUE THREAD

**Issue by cyrilschmidt** [pytest-dev/pytest#5793]
**Problem description:** when tox is passed a UNC path as additional argument, it fails with the error message like

> ValueError: path is on mount '\\\\172.18.180.162\\Share1', start on mount 'C:'

The full stack trace and tox.ini are attached (note: tox.ini is renamed to tox.ini.txt)

**How to reproduce:**
`tox -e test-posargs -- \\172.18.180.162\Share1`

**Additional observations:**
1. Tox works if the additional argument is not a UNC path, e.g. `tox -e test-posargs -- C:\`
2. Tox works if the UNC path points to a nonexistent share, e.g. `tox -e test-posargs -- \\172.18.180.162\NoShare`
3. If I move the commands in the default section `[testenv]`, it works.
4. Positional arguments are not even referred to in tox.ini.
5. The `args_are_paths` option should prevent tox from meddling with the arguments, but it does not.

**Environment:**
OS; Windows Server 2012 R2 Datacenter

> C:\>pip list
> Package         Version
> --------------- -------
> filelock        3.0.10
> numpy           1.16.2
> pandas          0.24.2
> pip             19.0.3
> pluggy          0.9.0
> py              1.8.0
> python-dateutil 2.8.0
> pytz            2019.1
> scipy           1.2.1
> setuptools      40.8.0
> six             1.12.0
> toml            0.10.0
> tox             3.8.1
> virtualenv      16.4.3
> xmljson         0.2.0
[stacktrace.txt](https://github.com/pytest-dev/pytest/files/3546833/stacktrace.txt)
[tox.ini.txt](https://github.com/pytest-dev/pytest/files/3546839/tox.ini.txt)

**Comment by The-Compiler** [comment]
This should probably be opened at https://github.com/tox-dev/tox/issues instead? Also, please make sure you include the full stracktrace you get.

**Comment by cyrilschmidt** [comment]
My bad, I am moving it to tox-dev issue #1410.
