### ISSUE TITLE
parametrized pytest - how to run concurrently

### ISSUE THREAD

**Issue by artis3n** [pytest-dev/pytest#5799]
Hey,

I have a parametrize snippet looking like:

```python
scenarios: List[Tuple[str, Dict[str, str]]] = load_scenarios()

for scenario in scenarios:
    idlist.append(scenario[0])
    items = scenario[1].items()
    argnames = [item[0] for item in items]
    argvalues.append([item[1] for item in items])
metafunc.parametrize(argnames, argvalues, ids=idlist, scope='class')
```

This collects 263 total tests. I am going to add a few other tests and the total collected with scenarios will ballon to ~780. Don't ask. Each indidivual test takes about 1-2.5s. Based on this parametrize collection, `pytest-parallel` and `xdist` are not gonna work, at least not so far as I've tried testing. How might I actually get these concurrent?

Also - each of the 263 tests spawns a `Popen`.

**Comment by asottile** [comment]
can you elaborate on why `xdist` won't work for this?

**Comment by nicoddemus** [comment]
Besides @asottile's question, the short answer is that pytest does not support any kind of test concurrency out of the box.

**Comment by artis3n** [comment]
> can you elaborate on why `xdist` won't work for this?

I think that I just need to configure my `conftest.py` differently and `xdist` is what I need. Let me modify my question.
I currently have an expensive setup fixture:

```python
@pytest.fixture(autouse=True, scope='session')
def all_prep(dependency_dir, global_dependency_dir) -> None:
    """
    Runs all pre- and post-test session setup and teardown.
    """
    # Setup
    stuff = setup(dependency_dir, global_dependency_dir)  # takes in two other fixtures I've defined
    setup_another_thing(global_dependency_dir)

    try:
        yield  # Return execution to parent pytest method, run test suite, then move to the 'finally' block
    finally:
        # Teardown
        teardown(stuff)
```

In the `setup` method, in this example, is a bunch of network calls to download test dependencies that get cached into the `global_dependency_dir`. Right now I'm getting an EOFError trying to unzip one of those and I'm betting it's a locking situation with the xdist nodes.

Is there a way to ensure certain setup is only run by the first worker and the rest wait for that to complete? They could wait until a boolean is true, I suppose. Is `master` always available, or are the worker names always `gwX`, e.g. the first worker would be `gw1` / `gw0`?


Something like:
```python
@pytest.fixture(autouse=True, scope='session')
def all_prep(dependency_dir, global_dependency_dir) -> None:
    """
    Runs all pre- and post-test session setup and teardown.
    """
    this_worker = os.environ['PYTEST_XDIST_WORKER']
    pytest.setup_completed = False
    if this_worker == 'gw0':
        # Setup
        stuff = setup(dependency_dir, global_dependency_dir)  # takes in two other fixtures I've defined
        setup_another_thing(global_dependency_dir)
        pytest.setup_completed = True

        try:
            yield  # Return execution to parent pytest method, run test suite, then move to the 'finally' block
        finally:
            # Teardown
            teardown(stuff)

    else:
        while not pytest.setup_completed:
            sleep(2)
        yield  # Execute tests
```

When i try this example above, my tests run successfully, but at the same pace as before so I'm guessing only the one worker node that ran setup runs and the others stay blocked forever at the while loop.

**Comment by asottile** [comment]
yeah they'll be in separate processes so they won't share the same python globals -- you'll need to communicate using a pipe or a file or something -- like perhaps write a file to disk in a well known location and the workers can watch for that?

**Comment by artis3n** [comment]
> yeah they'll be in separate processes so they won't share the same python globals -- you'll need to communicate using a pipe or a file or something -- like perhaps write a file to disk in a well known location and the workers can watch for that?

The if this_worker == 'gw0':` should work to define which worker acts and which wait for a file to exist, correct? Is the first worker `gw0` or `gw1`?

**Comment by asottile** [comment]
yeah, my point was that mutating `pytest.setup_completed` will not be reflected in other processes

**Comment by artis3n** [comment]
> yeah, my point was that mutating `pytest.setup_completed` will not be reflected in other processes

But wait, are they 0-indexed or not, which describes the first worker?

**Comment by asottile** [comment]
I don't know, I don't use or work on xdist -- but you can probably poke around in their source (or print them all and see what happens)

**Comment by artis3n** [comment]
Ah, my bad. Thanks

**Comment by nicoddemus** [comment]
Yeah `gw0` is the first worker. You can probably make `gw0` write to a file somewhere, and all other workers wait for some "done" signal before proceeding. Alternatively, you can also try a file lock for example.

**Comment by artis3n** [comment]
Hmm...the other workers seem to not be invoked at all, although I see the processes existing with `ps aux | grep python`.

I now have:
```python
    this_worker = os.environ['PYTEST_XDIST_WORKER']
    nonce = uuid.uuid4().hex
    setup_complete_file = dependency_dir / f'setup_complete-{nonce}' . # This is a pathlib.Path

    # Only one worker should run the setup. The rest will block until it is complete.
    if this_worker == 'gw0':
        # Setup
        server = setup_server(dependency_dir, global_dependency_dir)
        setup_otherthing(global_dependency_dir)
        complete_setup(setup_complete_file)
        print(f'worker {this_worker} has completed setup')

        try:
            yield  # Return execution to parent pytest method, run test suite, then move to the 'finally' block
        finally:
            # Teardown
            teardown_vault(vault_server)

    else:
        wait_for_setup_to_complete(setup_complete_file)
        yield  # Worker returns execution to parent to run test suite
```

```python
def complete_setup(complete: Path):
    with complete.open(mode='w') as file:
        file.write('setup complete')


def wait_for_setup_to_complete(complete: Path):
    # Block until setup has been completed
    print(f'worker {os.environ["PYTEST_XDIST_WORKER"]} starting to sleep')
    while not complete.exists():
        sleep(1)
    print(f'worker {os.environ["PYTEST_XDIST_WORKER"]} no longer sleeping')
```

Notably, `worker <gwX> starting to sleep` never gets logged. I only see `worker gw0 has completed setup` get logged when intentionally failing tests with `assert 0`.

I'm invoking pytest with: `pytest -n 5 -q library/test/`
There is no `pytest.ini`

I'm realizing that that nonce will be different for every worker so that is not going to work, but I should still see that log before the worker starts to block and I am not..

**Comment by artis3n** [comment]
Ok, got it working after removing the nonce. Full snippets for future people that come to this issue:

```python
@pytest.fixture(autouse=True, scope='session')
def all_prep(dependency_dir, global_dependency_dir) -> None:
    """
    Runs all pre- and post-test setup and teardown.
    :param dependency_dir: Path to the dependency directory for this test session
    :param global_dependency_dir: Path to the inter-session dependency directory
    :return: None
    """
    this_worker = os.environ['PYTEST_XDIST_WORKER']
    setup_complete_file = dependency_dir / 'setup_complete'  # pathlib.Path

    # Only one worker should run the setup. The rest will block until it is complete.
    if this_worker == 'gw0':
        # Setup
        server = setup_server(dependency_dir, global_dependency_dir)
        setup_other_stuff(global_dependency_dir)
        complete_setup(setup_complete_file)

        try:
            yield  # Return execution to parent pytest method, run test suite, then move to the 'finally' block
        finally:
            # Teardown
            teardown_server(server)
            setup_complete_file.unlink()  # Delete the setup_complete file

    else:
        wait_for_setup_to_complete(setup_complete_file)
        yield  # Worker returns execution to parent to run test suite


def complete_setup(complete: Path):
    complete.touch()


def wait_for_setup_to_complete(complete: Path):
    # Block until setup has been completed
    while not complete.exists():
        sleep(2)
```
