### ISSUE TITLE
tmpdir path too long on macOS

### ISSUE THREAD

**Issue by adamjstewart** [pytest-dev/pytest#5802]
I have a unit test that runs `gpg`. First we set `GNUPGHOME` to the temporary directory that pytest creates, then we run it using our own keys. However, `gpg` fails with the following error:
```
gpg: keybox '/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-5/test_buildcache0/gpg/pubring.kbx' created
gpg: can't connect to the agent: File name too long
gpg: agent_genkey failed: No agent running
gpg: key generation failed: No agent running
```
According to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847206, `gpg` cannot handle long paths. Is there any way to shorten `/private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-5/test_buildcache0/gpg/pubring.kbx`?

platform darwin -- Python 3.7.3, pytest-3.2.5, py-1.4.34, pluggy-0.4.0

Possibly related to #291

**Comment by adamjstewart** [comment]
Hmm, didn't realize I was using such an ancient version of pytest. It looks like 3.2.5 is the last version that supports Python 2.6. I assume this bug has been fixed in newer versions of pytest, so I'll close this unless I find a way to reproduce it.

**Comment by adamjstewart** [comment]
Hmm, but #291 was claimed to be fixed long before pytest 3.2.5. Reopening...

**Comment by RonnyPfannschmidt** [comment]
indeed, thats a different issue (full path vs path component)

as a workaround you can probably use `--basetemp` and manage the creation/destruction/naming of the tmpdir (pytest will reset the content of the given directory)

**Comment by nicoddemus** [comment]
Closing this for now, seems like using `--basetemp` is a good workaround. Feel free to chip in if we should re-open.

**Comment by The-Compiler** [comment]
FWIW I have this in my testsuite for a similar issue:

```python
@pytest.fixture()
def short_tmpdir():
    with tempfile.TemporaryDirectory() as tdir:
        yield py.path.local(tdir)
```

**Comment by yihuang** [comment]
> FWIW I have this in my testsuite for a similar issue:
> 
> ```python
> @pytest.fixture()
> def short_tmpdir():
>     with tempfile.TemporaryDirectory() as tdir:
>         yield py.path.local(tdir)
> ```

this solution will cleanup dir automatically after test, not good for development.
seems `--basetemp` is the only solution, the only thing is you can't configure it in ini, have to pass it in every run.

**Comment by koffie** [comment]
could it at least be made easier to use this workaround and make basetmp something that is configurable in the pytest config file so that I don;t need to remember it passing it as an option every single time?

**Comment by The-Compiler** [comment]
You can configure any command line option in the config via `addopts`.

**Comment by yihuang** [comment]
Another solution is just set `TMPDIR=/tmp` in current profile.

**Comment by koffie** [comment]
@The-Compiler 

Thanks, that works.

For some reason I was expecting:
to work

    [tool:pytest]
    basetemp = /tmp/pytest


but luckily

    [tool:pytest]
    addopts = --basetemp=/tmp/pytest

does exactly what I want

**Comment by RonnyPfannschmidt** [comment]
@koffie please note that the basepmp option deletes the target folder

**Comment by koffie** [comment]
@RonnyPfannschmidt thanks for the heads up. That is why I created a specific folder for pyrest tests and used `--basetemp=/tmp/pytest` so that my other temporary files keep existing (at least temporarily). And also why I did not do `--basetemp=/tmp`. Or are you implying that there is also a way of achieving the same result without deleting the target folder?

**Comment by RonnyPfannschmidt** [comment]
@koffie current there isn't, but people miss the delete sometimes
