### ISSUE TITLE
"Option already added", using tox (w. usedevelop) and anaconda on Windows

### ISSUE THREAD

**Issue by KennethNielsen** [pytest-dev/pytest#5813]
Hallo pytest devs and thanks for an awesome tool.

Short summary: I'm using tox to run pytest in the default Anaconda environment under Windows. To ensure proper testing my source is located in a non-importable directory ("src") and I use the appropriate setup.py settings and `usedevelop` in tox. In pytest I add a custom option, to disable certain tests if the flag is not present. When I run the tests with pytest directly, it works, but when I run it with tox I get the following error:

```
____________________________________________ ERROR collecting test session ____________________________________________
.tox\py36\lib\site-packages\_pytest\config\__init__.py:436: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('C:\\git\\olefn\\tests\\conftest.py')

During handling of the above exception, another exception occurred:
.tox\py36\lib\site-packages\py\_path\common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
.tox\py36\lib\site-packages\py\_path\common.py:418: in gen
    dirs = self.optsort([p for p in entries
.tox\py36\lib\site-packages\py\_path\common.py:419: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
.tox\py36\lib\site-packages\_pytest\main.py:606: in _recurse
    ihook = self.gethookproxy(dirpath)
.tox\py36\lib\site-packages\_pytest\main.py:424: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
.tox\py36\lib\site-packages\_pytest\config\__init__.py:420: in _getconftestmodules
    mod = self._importconftest(conftestpath.realpath())
.tox\py36\lib\site-packages\_pytest\config\__init__.py:461: in _importconftest
    self.consider_conftest(mod)
.tox\py36\lib\site-packages\_pytest\config\__init__.py:514: in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
.tox\py36\lib\site-packages\_pytest\config\__init__.py:323: in register
    ret = super().register(plugin, name)
.tox\py36\lib\site-packages\pluggy\manager.py:121: in register
    hook._maybe_apply_history(hookimpl)
.tox\py36\lib\site-packages\pluggy\hooks.py:336: in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
.tox\py36\lib\site-packages\pluggy\manager.py:87: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox\py36\lib\site-packages\pluggy\manager.py:81: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
tests\conftest.py:25: in pytest_addoption
    "activate equipment tests. The value `MS` activates the mass spectrometer "
.tox\py36\lib\site-packages\_pytest\config\argparsing.py:73: in addoption
    self._anonymous.addoption(*opts, **attrs)
.tox\py36\lib\site-packages\_pytest\config\argparsing.py:304: in addoption
    raise ValueError("option names %s already added" % conflict)
E   ValueError: option names {'--equipment', '-E'} already added
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 1 error in 0.17s ===================================================
ERROR: InvocationError for command 'c:\git\olefn\.tox\py36\Scripts\pytest.EXE' --disable-pytest-warnings (exited with code 2)
```

So it seems that the `conftest.py` somehow gets executed twice. To further corroborate that, if I augment my `conftest.py` in the following way, to prevent adding the option again, then everything is fine:
```python
"""pytest configuration file"""

import sys
import os

import pytest

# Add helpers to path
sys.path.append(os.path.join(os.path.dirname(__file__), "helpers"))


def pytest_addoption(parser):
    """Adds commandline option to pytest"""
    # FIXME Ugly hack to prevent option already added exception, remove when possibly
    for opt in parser._anonymous.options:
        if opt.dest == "equipment":
            return

    parser.addoption(
        "-E",
        "--equipment",
        action="store",
        default="NONE",
        help=(
            "activate equipment tests. The value `MS` activates the mass spectrometer "
            "tests and the value `all` activates all equipment tests."
        ),
    )


def pytest_configure(config):
    """Configures pytest"""
    os.environ["equipment"] = config.getoption("-E")
```

Quite obviously the bug could be both in tox, in pytest and somehow in the way that anaconda makes environments. I will report it both here and in tox (https://github.com/tox-dev/tox/issues/1413).

For posterity here are tox.ini:
```ini
# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = py36,py37,pylint,mypy
skip_missing_interpreters=true
usedevelop=True
# project_module_dir={toxinidir}/src/olefn

[testenv]
deps =
    -rrequirements.txt
    -rrequirements-dev.txt
commands = pytest --disable-pytest-warnings

[testenv:pylint]
commands = pylint --rcfile={toxinidir}/tools/pylint.rc {toxinidir}/src/olefn

[testenv:mypy]
description = type check ourselves
basepython = python3.6
commands = mypy --no-strict-optional --strict {toxinidir}/src/olefn
```

and setup.cfg
```ini
[tool:pytest]
norecursedirs=tests/helpers tools

[mypy]
```

General info. I'm on Windows 10 Pro (64 bit). pytest-5.1.1 and tox 3.13.2. It is a little difficult for me to create a recipe for reproducing, since it involves an anaconda installation. But if someone is willing to install anaconda, I will on demand create a test project that could be cloned to reproduce.

Let me know if you need any other information.

Ouput of `pip list` attached: 
[piplist.txt](https://github.com/pytest-dev/pytest/files/3565150/piplist.txt)

**Comment by blueyed** [comment]
Please add `__import__("traceback").print_stack()` to the top of the conftest.py file, and post the tracebacks here then.

**Comment by KennethNielsen** [comment]
Hi @blueyed 

Here is the output from the run with print_stack: 
[output.txt](https://github.com/pytest-dev/pytest/files/3566456/output.txt)

**Comment by blueyed** [comment]
First call via:
```
  File "c:\git\olefn\.tox\py36\lib\site-packages\_pytest\config\__init__.py", line 77, in main
    return config.hook.pytest_cmdline_main(config=config)
```

Second:
```
  File "c:\git\olefn\.tox\py36\lib\site-packages\_pytest\config\__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
```

**Comment by blueyed** [comment]
@KennethNielsen 
Can we paste the contents of it here, so it's available for later?

**Comment by KennethNielsen** [comment]
> First call via:
> 
> ```
>   File "c:\git\olefn\.tox\py36\lib\site-packages\_pytest\config\__init__.py", line 77, in main
>     return config.hook.pytest_cmdline_main(config=config)
> ```
> 
> Second:
> 
> ```
>   File "c:\git\olefn\.tox\py36\lib\site-packages\_pytest\config\__init__.py", line 58, in main
>     config = _prepareconfig(args, plugins)
> ```
> 
> But it reports the error before the second one already, so not sure what's going on there.

Yeah. I think it is pretty weird as well. As I mentioned, tox normal runs ok, and tox also ran ok before I added the `usedevelop` option to that, so best bet is that it is doing something bad. But I can't figure out what.

> Can we paste the contents of it here, so it's available for later?

Sure. I have edited the post. I though these attached files were the standard way of doing it. If you want the pip list pasted as well, just let me know.

**Comment by blueyed** [comment]
You might want to print the traceback also / instead from `pytest_addoption`, of course, too.
And then use `file=sys.stdout` with `print()` there, and `pytest -s …` to ensure it's not displayed only after other output.
Of course trying to debug it with `pdb.set_trace()` might be superior, of course.

**Comment by KennethNielsen** [comment]
@blueyed I tried to insert the print traceback directly in the addoption function. But since cleaning the repository I find it difficult to reproduce the problem. Maybe something caught in a cache somewhere. I will close this for now, to see if it reappears. Sorry about the noise.
