### ISSUE TITLE
Test location string in test failures uses dot-notation not pytest's "::" notation 

### ISSUE THREAD

**Issue by belugame** [pytest-dev/pytest#5816]
When I have a failing test the failure is reported as:

```
============= FAILURES ============
________ SomeTestCase.test_foo ____

self = <some.long.path.subfolder.tests.test_bar.SomeTestCase testMethod=test_foo>

    def test_foo(self):
>       foo
E       NameError: global name 'foo' is not defined

some/long/path/subfolder/tests/test_bar.py:258: NameError
```

Lets say this happened in the CI system and I want to rerun it on my local machine. It would be convenient if I could simply copy one of the test locations. For running test_foo I need a command like:

pytest some/long/path/subfolder/tests/test_bar.py::SomeTestCase::test_foo

But the report is using a different format, which seems illogical to me. It would make it easier to copy/paste a test if the string inside `self = <...>` would have the same format as the pytest executable expects in the CLI.

e.g.

`self = <some/long/path/subfolder/tests/test_bar.py::SomeTestCase::test_foo>
`

**Comment by asottile** [comment]
that `<...>` is the repr from `unittest.TestCase` and not part of pytest

**Comment by belugame** [comment]
Hm, I see :-/
There is no way to call pytest with a test name in that dot-notation either, right?

**Comment by asottile** [comment]
iirc, passing `-rf` will include the failing test ids in the output

**Comment by nicoddemus** [comment]
Perhaps we can print the full node id at the bottom?

```
________ SomeTestCase.test_foo ____

self = <some.long.path.subfolder.tests.test_bar.SomeTestCase testMethod=test_foo>

    def test_foo(self):
>       foo
E       NameError: global name 'foo' is not defined


some/long/path/subfolder/tests/test_bar.py:258: NameError

some/long/path/subfolder/tests/test_bar.py::SomeTestCase::test_foo 
```

Or would that be confusing? Seems very useful to be able to just copy/paste the last line and run it, I recall @blueyed brought this up as well, but wanted to support running `some/long/path/subfolder/tests/test_bar.py:258` directly in the command-line instead.

**Comment by belugame** [comment]
I came up with a solution that would have helped me by adding this in a base testcase class:

```
def __repr__(self):
    return "{}.py::{}".format(self.__module__.replace(".", "/"), 
                              "::".join([self.__class__.__name__, self.__name__]))
```
But @asottile's hint is better. By adding `-rfE` to my command I get the failing tests as summary in the :: notation at the end of the output.

Thank you guys, for me the issue is solved :)

**Comment by blueyed** [comment]
Just for info: I find it useful to use `-ra` always.

**Comment by blueyed** [comment]
See also https://github.com/pytest-dev/pytest/issues/5130.
