### ISSUE TITLE
Run argparse before parameterized

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest#5829]
Hi,
I have a use case where I store some config file which I parse and set as an object which the tests are using. in one of the configurations, I'm using an endpoint that exposes all the location of files which I download and manipulate.

In the tests, I'm setting down this location as a parameter which creates multiple tests with the same test script, but different test data (derived by the downloaded file from the endpoint directory).

The problem is that parameterized fixture starts before the argparse is. as a result, I end up with inability to access the constructed object I expect to have.

How can overtake come that?

**Comment by RonnyPfannschmidt** [comment]
its not quite clear what argparse you mean and what you actually do,

can you perhaps create a minimal example and/or link the code

else we cant even hope to make suggestions

**Comment by Formartha** [comment]
Hi @RonnyPfannschmidt, I'll try to add some examples here.

I have a test that looks like the following:

`
@pytest.mark.parametrize("model", FileSystem.get_file_list_from_url(orion_nfs_config.file_loc())
def test_print_model(model):
      print model
`

The conftest.py builds the object named orion_nfs_config.file_loc with passing down arguments.
an example should be like:

`
@pytest.fixture(scope="session", autouse=True)
def parse_args(request):
    file_loc = request.get("file_loc")
    set_orion_nfs_config(conf**)
    return orion_nfs_config
`

The location is an external server which holds files, which, the test, in it's turn, grabs all the models from the server and basically do something with it (in my example, it's just prints them).

The problem is that parameterized happens before argparse is initiated.

thanks again,
-M

**Comment by RonnyPfannschmidt** [comment]
as far  as i can tell you need to do the setup at pytest_configure  time, a fixture is tool ate as ithappens after collection of tests

**Comment by Formartha** [comment]
@RonnyPfannschmidt - Perfect! it worked. this thread is closed :)

Cheers!

**Comment by RonnyPfannschmidt** [comment]
thanks for the follow-up, im glad i could help
