### ISSUE TITLE
`pytest.skip()` fails when running using unittest

### ISSUE THREAD

**Issue by leofang** [pytest-dev/pytest#5832]
- [x] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [x] minimal example if possible

Not sure if I missed any previous discussion. Is this made on purpose that `purest.skip()` would fail if `unittest` is used as the test runner?
```python
import pytest
import unittest


class ATest(unittest.TestCase):
    def test_function(self):
        if True:
            pytest.skip("unsupported")
```
```shell
leofang@Leos-MacBook-Pro:~$ python -m unittest -v test_pytest.py 
test_function (test_pytest.ATest) ... ERROR

======================================================================
ERROR: test_function (test_pytest.ATest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/leofang/test_pytest.py", line 8, in test_function
    pytest.skip("unsupported")
  File "/Users/leofang/miniconda3/envs/qutip-env/lib/python3.6/site-packages/_pytest/outcomes.py", line 96, in skip
    raise Skipped(msg=msg, allow_module_level=allow_module_level)
Skipped: unsupported

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```
Is there a way I can mark it "passed" in `unittest`? Thanks!

**Comment by RonnyPfannschmidt** [comment]
off hand i'm not aware of a way to make unittest support pytest utilities

if you want unittest compatibility, you need to use unittest utilities

**Comment by leofang** [comment]
OK thank you. I was under the (wrong) impression that pytest's functionalities are compatible with unittest as the runner.
