### ISSUE TITLE
Issue on Windows with uppercase folders with versions >= 5.1.0 and conftest

### ISSUE THREAD

**Issue by jfthuong** [pytest-dev/pytest#5837]
Hi,

Related to issue #2761, I have an issue in Windows with folders containing uppercase and *conftest.py*.

I have the following organization

```
E:/Prototypes/Toto/
  -> __init__.py
  -> conftest.py
  -> tests/
       -> test.py
```

See following files in zip: [Toto.zip](https://github.com/pytest-dev/pytest/files/3599312/Toto.zip)

When running `pytest` 5.1.2 (Python 3.7.1), I have the following error:

```python
ImportError while loading conftest 'e:\prototypes\toto\conftest.py'.
ModuleNotFoundError: No module named 'toto'
```

This works fine with `pytest` 5.0.1:
```python
platform win32 -- Python 3.7.1, pytest-5.0.1, py-1.8.0, pluggy-0.13.0
rootdir: E:\Prototypes\Toto
plugins: cov-2.6.1, forked-1.0.2, html-1.22.0, instafail-0.4.1, metadata-1.8.0, xdist-1.26.1
collected 2 items

tests\test_case.py .F
```

This is my list of installed modules:
[pip_list.txt](https://github.com/pytest-dev/pytest/files/3599323/pip_list.txt)

**Comment by asottile** [comment]
I believe this is a duplciate of #5819
