### ISSUE TITLE
Issues finding PyTest fixtures when calling tests in upper level directory

### ISSUE THREAD

**Issue by MarkABrezovecEaton** [pytest-dev/pytest#5858]
I am using PyTest 3.6.8.

My question/issue is essentially a copy of my StackOverflow request which hasn't garnered a lot of attention.  Linked below, but reposting here.

https://stackoverflow.com/questions/57913677/issues-finding-pytest-fixtures-when-calling-tests-in-upper-level-directory

---

I have a PyTest based test project which utilizes base-classes with fixtures. This "core" project is functioning as expected.

I would also like to have other "side" test projects in a different folder structure utilize these base-classes and fixtures. The use-case is that we have one core development project and many other projects which utilize this core project. We want "core" tests available to everyone, but we don't want the other project-specific tests cluttering the core.

Here is a skeleton tree structure:

    directory/
    ├── core/
    |   ├── conftest.py
    |   └── folder1/
    |       └── base_class.py
    |       └── conftest.py
    |       └── tests/
    |           └── test_core.py
    ├── ancillary/
    |   └── test_ancillary.py

Here are the contents of the python files:

    # contests of core.conftest.py
    import pytest
    
    @pytest.fixture(scope='session')
    def base_true_fixture():
        return True
    
    @pytest.fixture(scope='session')
    def base_false_fixture():
        return False
    
    --
    
    # contents of core.folder1.conftest.py
    import pytest
    
    @pytest.fixture(scope='session')
    def true_fixture(base_true_fixture):
        return base_true_fixture
    
    @pytest.fixture(scope='session')
    def false_fixture(base_false_fixture):
        return base_false_fixture
    
    --
    
    # contents of core.folder1.base_class.py
    import pytest
    
    
    class base:
        true = None
        false = None
    
        @pytest.fixture(scope='class', autouse=True)
        def base_setup(self, request, true_fixture, false_fixture):
            request.cls.true = true_fixture
            request.cls.false = false_fixture
            yield
    
    --
    
    # contents of contents of core.folder1.tests.test_core.py
    from folder1.base_class import base
    import pytest
    
    
    class TestCore(base):
        @pytest.fixture(scope='class', autouse=True)
        def console_setup(self, request, base_setup):
            # Required to ensure other autouse fixtures are instantiated.
            yield
    
        def test_class_pass(self):
            assert self.true, "Passes-{}".format(self.true)
    
        def test_class_fail(self):
            assert self.false, "Fails-{}".format(self.false)

As mentioned above, this 'core' part works perfectly fine when I execute pytest from the 'core' directory.

The complication comes in when I try to use my base-class with test_ancillary.py. Here are its contents:

    from folder1.base_class import base
    import pytest
    
    
    class TestAncillary(base):
        @pytest.fixture(scope='class', autouse=True)
        def console_setup(self, request, base_setup):
            # Required to ensure other autouse fixtures are instantiated.
            yield
    
        def test_class_pass(self):
            assert self.true, "Passes-{}".format(self.true)
    
        def test_class_fail(self):
            assert self.false, "Fails-{}".format(self.false)

In my original setup I was running PyTest directly from the 'core/' directory and pointing it at ancillary/:

    python3 -m pytest -vv -n=1 ancillary/ 
    
    ...
    [gw0] linux -- Python 3.6.8 /usr/bin/python3
    file /home/me/adopter_project_layer/ancillary/test_ancillary.py, line 18
          def test_class_pass(self):
    file /home/me/adopter_project_layer/core_module/folder1/base_class.py, line 8
          @pytest.fixture(scope='class', autouse=True)
          def base_setup(self, request, true_fixture, false_fixture):
    E       fixture 'true_fixture' not found
    >       available fixtures: __pytest_repeat_step_number, base_setup, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, console_setup, doctest_namespace, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id
    >       use 'pytest --fixtures [testpath]' for help on them.

    /home/me/adopter_project_layer/core_module/folder1/base_class.py:8
    ...

So it cannot find my fixtures (**"fixture 'true_fixture' not found"**).

Right now I am just trying to get the 'ancillary' tests to run with this base class. What is the best way to do that?

I would also like users to be able to execute tests in 'core' and in 'ancillary' at the same time. I am trying to find a solution which will provide this.

The closest match I found to my question was here: pytest fixtures in a separate directory

I tried this solution with directly executing out of the 'directory', but I still received the same issue with not being able to find fixtures. That said, I am not convinced that I did it correctly.

Any ideas? I am not even too sure which should be my executing directory in this case. My main restraint is that 'core/' should definitely still stand alone.

**Comment by Zac-HD** [comment]
> I am using PyTest 3.6.8

Does this still happen on the current version of Pytest?

**Comment by MarkABrezovecEaton** [comment]
> > I am using PyTest 3.6.8
> 
> Does this still happen on the current version of Pytest?

Zac, thanks for the response.  I made a bit of a typo - my Python is 3.6.8 and my PyTest is 5.1.1.

--

I actually got a bit further on this yesterday to the point where I think I am past my original problem.  During my original investigation I had tried various combinations of updating the sys.path and adding items to my pytest_plugins.  I had some issues with these combinations in terms of the base conftest.py being found twice - once for 'ancillary' and once for 'core'.  I originally abandoned this approach, but I realized that instead of referencing the 'core' conftest in my ancillary 'conftest' pytest_plugins I could just import a common module from core between the two conftest files.

Final fixes (based on my memory):

``
# Contents of ancillary/conftest.py

import pytest
import os
import sys

full_path = os.path.dirname(os.getcwd()) + '/core_module/'
assert os.path.isdir(full_path), "NOT A DIRECTORY:  {}".format(full_path)

sys.path.insert(0, full_path)

pytest_plugins = [
    'fixtures_base.base_bool_fixtures',
    "folder1.conftest",
]

--

# Contents of core/conftest.py

pytest_plugins = [
    'fixtures_base.base_bool_fixtures',
]

``
