### ISSUE TITLE
Custom comments on test results

### ISSUE THREAD

**Issue by eparubrub-view** [pytest-dev/pytest#5860]
Hello,

I am not reporting a bug, I would like to ask about the functionality. I would like to know how pytest adds comments to the test results. Right now I am using the pytest-testrail to report my pytest test results to testrail but right now the comments produce tracebacks for failures and nothing for passing test cases. Is there a way that I could add environment variables to the comments of the test case results?

For more on this issue: https://github.com/allankp/pytest-testrail/issues/45

Thank you!

**Comment by Zac-HD** [comment]
Maybe https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_runtest_makereport ?  Sorry I can't help more.
