### ISSUE TITLE
Wildcard filename does not work on Windows?

### ISSUE THREAD

**Issue by fukatani** [pytest-dev/pytest#5870]
Our directory configurations.

online-judge-tools/
　├ tests/
    │   ├ command_download.py (test file)
　│　└ other many test scripts
　└ setup.py

And we tried, 
```
cd online-judge-tools/
pytest tests/*.py
```

In appveyor-Python 3.6-x64 envirionment, 
pytest failed with 
```
ERROR: file not found: tests\*.py
Command exited with code 4
```
Full report is here ( https://ci.appveyor.com/project/kmyk/online-judge-tools/builds/27575940/job/i3409cunpxeauq6r ).

In linux, we confirmed that the tests were passed.
https://travis-ci.org/kmyk/online-judge-tools/jobs/587992080 works well.

Thanks!

**Comment by asottile** [comment]
cmd.exe does not expand `*` like posix shells do -- a workaround would be to invoke bash explicitly on Windows `bash -c 'pytest tests/*.py'` or just drop the wildcard entirely and let pytest so the discovery `pytest tests`

**Comment by fukatani** [comment]
Ah, I got it.
Many thanks for your kind answer!

**Comment by asottile** [comment]
cheers! thanks for the issue
