### ISSUE TITLE
Fast fail option -x can be influenced by a bug in a plugin

### ISSUE THREAD

**Issue by 1605200517** [pytest-dev/pytest#5879]
A bug in a plugin can replace `maxfail` variable with an instance of a custom class instead of integer.

How to reproduce: 

* install latest pytest 5.1.3 and the plugin pytest-parallel 
* create a test with a successful test and a failing test 
* run test: `pytest -xs --workers auto test.py`
* Exception will occur like in https://github.com/browsertron/pytest-parallel/issues/40
```

File "/home/user/.virtualenvs/apache-cs-extensions/lib/python3.6/site-packages/_pytest/main.py", line 412, in pytest_runtest_logreport
if maxfail and self.testsfTypeError: '>=' not supported between instances of 'SafeNumber' and 'int'ailed >= maxfail:
TypeError: '>=' not supported between instances of 'SafeNumber' and 'int'#
```
It looks like somehow the maxfail variable got replaced by a `SafeNumber` instance instead of being an `int`.

Maybe this is also related to changes planned in #4702.

**Comment by RonnyPfannschmidt** [comment]
its a structural issue with pytest-parallel, its badly implemented and breaks things, 
pytest isnt in the game of defending against that kind of neglect
