### ISSUE TITLE
Lower case attributes capitalized in docs

### ISSUE THREAD

**Issue by altendky** [pytest-dev/pytest#5883]
Shouldn't `Ret`/`Outlines`/`Errlines`/`Stdout`/`Stderr`/`Duration` be lower case?  `Testdir` is similarly broken.  Not sure how many more.

https://docs.pytest.org/en/5.1.3/reference.html#_pytest.pytester.RunResult
![image](https://user-images.githubusercontent.com/543719/65738977-c0ccef00-e0b1-11e9-8d57-2162dc66b9e9.png)

https://docs.pytest.org/en/5.1.3/_modules/_pytest/pytester.html#RunResult
![image](https://user-images.githubusercontent.com/543719/65739005-d5a98280-e0b1-11e9-8ddd-1a33cd573525.png)

https://github.com/pytest-dev/pytest/blob/1a9f4a51cb2a3c3b1d8e3bd5189552a24a85f5f4/src/_pytest/pytester.py#L349-L363

**Comment by asottile** [comment]
#5887 should fix this, silly sphinx :)

**Comment by altendky** [comment]
@asottile, thanks.  I didn't dig around for more, did you?  I think they were just the first two I looked at and then I reported it and moved on.  If not, I can poke around.

**Comment by asottile** [comment]
I found a few more in that particular file but didn't really see any others at a glance -- but I didn't look very thoroughly to be honest :) (and it wasn't easy to grep for)
