### ISSUE TITLE
i cant run pytest

### ISSUE THREAD

**Issue by jade-li1115** [pytest-dev/pytest#5888]
![image](https://user-images.githubusercontent.com/53292092/65827215-779fb980-e2c2-11e9-8026-931ed50292f5.png)

hi ,i cant run this use pytest,it seems doesnt reconize pytest

**Comment by jade-li1115** [comment]
this is normal,it shold like this :
![image](https://user-images.githubusercontent.com/53292092/65827613-7f605d80-e2c4-11e9-8518-fe785ee89a4c.png)

**Comment by RonnyPfannschmidt** [comment]
This looks like a problem with your ide or environmental, nothing related to pytest itself
