### ISSUE TITLE
junitxml: Testcases have multiple results

### ISSUE THREAD

**Issue by alcalda** [pytest-dev/pytest#5891]
Related to [junit xml "tests" number seems wrong if only teardown fails](https://github.com/pytest-dev/pytest/issues/3850)?

Having a Data-Driven-Test function `test_comp`, which is parametrized. This test function uses other fixtures `compb`, e.g. extraction of files to a target directory.
In the teardown portion of these fixtures the extracted files shall be deleted again.

When some of the Data-Driven parameters are skipped, it is expected that the particular generated testcase have Result Skipped. pytest do this well.

Due to latency it may happen, that some other process still claim the files, which shall be deleted during the above described teardown portion of the fixture `compb`. It will throw a PermissionError exception

AND 

additionally add a second pytest Result: Error, which is tagged to the testcase (which is expected to be Skipped).

So, the testcase has two Results, which is violation of Junit Format.

Versions:
Windows 10
pytest 5.2.0

Pipfile
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
pytest = "==5.2.0"
pytest-html = "*"
junitparser = "*"

[requires]
python_version = "3.7"
```

Example Code
```
import pytest
import logging
logger = logging.getLogger(__name__)


@pytest.fixture(scope="package", name="compb")
def fixture_comp(request):
    logger.debug(f"Fixture {request.fixturename} started from {request.fspath.strpath}")
    yield None
    logger.debug(f"Fixture {request.fixturename} finished from {request.fspath.strpath}")
    raise PermissionError


@pytest.mark.parametrize("param1", [
    1,
    2,
    pytest.param(3, marks=pytest.mark.skip)
])
def test_comp(compb, param1):
    assert True
```

conftest.py
```
from junitparser import JUnitXml, TestSuite, TestCase, Properties, Attr, Skipped, Failure, Error, JUnitXmlError
import logging
logger = logging.getLogger(__name__)


def pytest_sessionfinish(session, exitstatus):
    if session.config.pluginmanager.hasplugin("junitxml"):
        junitxml = getattr(session.config, "_xml", None)

    # Convert the JunitXml Report
    if junitxml:
        testsuites = JUnitXml.fromfile(junitxml.logfile)
        for ts in testsuites:
            for tc in ts.iterchildren(TestCase):
                logger.info(tc.result)
```

**Comment by JAMMFam** [comment]
Testing

**Comment by The-Compiler** [comment]
A simpler example:

```python
import pytest

@pytest.fixture(scope="module")
def compb():
    yield
    raise PermissionError

def test_comp_1(compb):
    assert True

@pytest.mark.skip
def test_comp_2(compb):
    assert True
```

results in:

```xml
<testsuites>
<testsuite errors="1" failures="0" hostname="hooch" name="pytest" skipped="1" tests="3" time="0.025" timestamp="2020-02-05T10:52:33.843536">
<testcase classname="test_x" file="test_x.py" line="7" name="test_comp_1" time="0.000"/>
<testcase classname="test_x" file="test_x.py" line="10" name="test_comp_2" time="0.000">
<skipped message="unconditional skip" type="pytest.skip">test_x.py:11: unconditional skip</skipped>
<error message="test teardown failure">
@pytest.fixture(scope="module") def compb(): yield > raise PermissionError E PermissionError test_x.py:6: PermissionError
</error>
</testcase>
</testsuite>
</testsuites>
```

**Comment by nicoddemus** [comment]
Thanks @The-Compiler for posting a smaller example and including the resulting XML. 

Just to clarify, is the problem the fact that we have both `<skipped>` and `<error>` tags for a `<testcase>`?

```xml
<testcase classname="test_x" file="test_x.py" line="10" name="test_comp_2" time="0.000">
<skipped message="unconditional skip" type="pytest.skip">test_x.py:11: unconditional skip</skipped>
<error message="test teardown failure">
@pytest.fixture(scope="module") def compb(): yield > raise PermissionError E PermissionError test_x.py:6: PermissionError
</error>
</testcase>
```

@alcalda can you confirm? And if so, what should the produced XML output look like?

**Comment by nicoddemus** [comment]
Actually the schema permits any number of children `skipped`, `error`, `failure`, etc, elements for a `testcase`:

https://github.com/jenkinsci/xunit-plugin/blob/ce58c5eb1db91d0d181935889a20cc42d2697b03/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd#L85-L105

So it seems the produced junit xml is actually valid.

@alcalda which tool are you using to parse this XML that is producing an error?

**Comment by The-Compiler** [comment]
I just talked to @alcalda again (he's in a pytest company training I'm giving currently) - It looks like `junitparser` has an issue with it. With the `conftest.py` above:

```
  File "/home/florian/tmp/5891/orig/conftest.py", line 8, in pytest_sessionfinish
    if session.config.pluginmanager.hasplugin("junitxml"):
  File "/home/florian/tmp/5891/.venv/lib/python3.8/site-packages/junitparser/junitparser.py", line 631, in result
    raise JUnitXmlError("Only one result allowed per test case.")
junitparser.junitparser.JUnitXmlError: Only one result allowed per test case.
```

So this looks like a junitparser rather than a pytest bug then, if the schema allows this to happen!

**Comment by gruberma** [comment]
Since [version 2](https://junitparser.readthedocs.io/en/latest/#note-on-version-2), `junitparser` now supports test cases having multiple <Failure> or <Error> tags.

**Comment by nkr0** [comment]
I am really confused what the correct spec (or interpretation of spec) is for JUnit XML. As commented above, [this schema is from Jenkins xUnit plugin](https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd).
```xml
    <xs:element name="testcase">
...
                <xs:choice minOccurs="0" maxOccurs="unbounded">
...
                    <xs:element ref="error"/>
                    <xs:element ref="failure"/>
                    <xs:element ref="rerunFailure" minOccurs="0" maxOccurs="unbounded"/>
...
```
In practice, Jenkins xUnit plugin shows only 1 `error` from a `testcase` with multiple `error` elements. This is the same behavior of [Azure DevOps PublishTestResults@2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2). But that is perhaps using [an older JUnit schema](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd).

So what does the schema snippet above mean:
1) Can you have multiple `error` elements in a `testcase`? Unlike `rerunFailure`, `error` does not have `minOccurs="0" maxOccurs="unbounded"`.
2) Or can you only have 1 `error` element in a `testcase`. But you can also have a `failure` element and multiple `rerunFailure` elements all at the same time if you want. So `choice` and `rerunFailure` are `unbounded`. But `error` and and `failure` are? Unspecified?

[Jenkins xUnit plugin page](https://plugins.jenkins.io/xunit/) states "JUnit (supported schema are [Ant junit](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) and [Maven Surefire](http://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd))"

Ant JUnit links to the same JUnit schema that Azure DevOps links to. But Maven Surefire links to a different schema. In this schema, some elements in `testcase` are `unbounded` and others (`error` is one of them) are not.
```xml
<xs:element name="testcase" minOccurs="0" maxOccurs="unbounded">
...
<xs:element name="failure" nillable="true" minOccurs="0" maxOccurs="unbounded">
...
<xs:element name="rerunFailure" minOccurs="0" maxOccurs="unbounded">
...
<xs:element name="skipped" nillable="true" minOccurs="0" maxOccurs="1">
...
<xs:element name="error" nillable="true" minOccurs="0" maxOccurs="1">
```

Any help in understanding is appreciated.
