### ISSUE TITLE
Python Code Testing

### ISSUE THREAD

**Issue by JAMMFam** [pytest-dev/pytest#5893]
- [ ] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by The-Compiler** [comment]
Hey @JAMMFam and welcome to GitHub! This repository is about a real project ([pytest](https://www.pytest.org/)) - please use a personal repository for testing things, as this repository is watched by >160 people who'll get an email for every change :wink:
