### ISSUE TITLE
Suggestion: add flag to run only new tests

### ISSUE THREAD

**Issue by m-burst** [pytest-dev/pytest#5907]
Hi there,

I thought it might be useful to add a flag allowing to run only new tests.
The use case would be when actively writing new tests, and it seems like the only solution now is to specify keywords to run only new tests.
The implementation of the feature could probably use the cache machinery which is used by `--lastfailed`.

What do you think?

**Comment by RonnyPfannschmidt** [comment]
lastfailed is a pretty bad location to gather that data
i'd prefer to see added tests and changed tests based on workdir state or feautre branch to master/base branch difference

**Comment by blueyed** [comment]
There is `--new-first` at least already.
We should keep in mind though that `--lf` by itself is buggy already..
