### ISSUE TITLE
Include helper to mock/trigger ImportErrors?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#5915]
Example code: https://github.com/Vimjas/covimerage/pull/82/files#diff-484462fced51d1a06b1d93b4a44dd535R48-R65

Maybe something more for pytest itself, or its / this documentation?

**Comment by nicoddemus** [comment]
Want to tackle this yourself @blueyed?

Obviously this should not be a new fixture, but a method of `monkeypatch` (users can use `context()` to use this feature in a context if they need to.

**Comment by The-Compiler** [comment]
Also see the previous discussion at #945 - FWIW I still think this would be a good fit for the builtin `monkeypatch` fixture, not a plugin.

**Comment by nicoddemus** [comment]
Yep. I liked `monkeypatch.importerror(names, err=ImportError)` as in the link posted, with `names` possibly being a single string for convenience.

**Comment by nicoddemus** [comment]
It should be cumulative too, so these should be equivalent:

```python
monkeypatch.importerror(('myapp.core', 'myapp.lib'))

monkeypatch.importerror('myapp.core')
monkeypatch.importerror('myapp.lib')
```

**Comment by blueyed** [comment]
What do you think about a more unique name (for greps)? I've used `mock_importerror` for now in https://github.com/blueyed/pytest/pull/119 (WIP).
Need to revisit https://github.com/pytest-dev/pytest/issues/945, but am not sure how useful "returning another object" is.
Maybe it could just handle/take a callable (instead of an exception) that gets called then, and could do whatever it wants?

**Comment by blueyed** [comment]
Just a heads up: I'm going with https://github.com/blueyed/pytest/pull/119 likely soon (since I need/want it), and will not adjust it afterwards anymore necessarily - in case you want to provide feedback.
