### ISSUE TITLE
Running pytest.main() from another folder that where tests are found

### ISSUE THREAD

**Issue by nadavchernin** [pytest-dev/pytest#5919]
I'm try to create python GUI application that will run pytest tests. My main GUI application will have some conftest files with fixtures and hooks The application will need to run tests in selected folder.

To test this concept, i try to run now pytest from the python with pytest.main("a/b/tests_folder") when my main python script found in different folder from the tests folder.

The issue now is how to use both conftests of my main application and of tests folder

Nadav

**Comment by RonnyPfannschmidt** [comment]
your application should provide a subprocess with a actual pytest plugin in order to sort this out correctly

this plugin can even be passed to pytest.main as an actual problem

a conftest is always a folder local plugin, so its never suitable for the outlined use-case

**Comment by nicoddemus** [comment]
>  My main GUI application will have some conftest files with fixtures and hooks The application will need to run tests in selected folder.

So you can implement hooks to display test progress, reporting, etc, correct? In this case you should write a plugin like @RonnyPfannschmidt mentioned, and pass it over to `pytest.main()` probably need to change the `cwd` as well, as users probably expect that your application is executing from that directory (that's dependent on your application of course). 

Be aware thought that in this way your fixtures will be exposed to the test suite you are running, which I'm not sure it is a good idea.
