### ISSUE TITLE
Help with plugin assertion rewriting

### ISSUE THREAD

**Issue by JBKahn** [pytest-dev/pytest#5931]
Hey, I was looking at the [pytest-clarity package](https://github.com/darrenburns/pytest-clarity) and it does something really nice, imo, which is it turns this:

![pytest](https://raw.githubusercontent.com/darrenburns/pytest-clarity/master/without-clarity.png)

into:

![pytest](https://raw.githubusercontent.com/darrenburns/pytest-clarity/master/pytest-clarity.png)

The downside is that the rewriting results in a loss of functionality:

```python
a = [1, 2, 3]
b = [1, 2]

def test_a():
    assert len(a) == len(b)
```

Goes from
```
    def test_a():
>       assert len(a) == len(b)
E       assert 3 == 2
E        +  where 3 = len([1, 2, 3])
E        +  and   2 = len([1, 2])
```

to

```
    def test_a():
>       assert len(a) == len(b)
E       assert left == right failed.
E         Showing split diff:
E
E         left:  3
E         right: 2
```

I've been digging through the source and I can't quite find the right part to use to do this. It stems from use of `pytest_assertrepr_compare` but I can't find anything in pytest I can use to construct that `3 = len([1, 2, 3])`. I'm looking for some pointers if anyone can help put me on the right track. I was barking down  the `AssertionRewriter` which I think is what I'm looking for but I can't quite put my finger on how to modify these assertions in way that still utilizes that code.

**Comment by blueyed** [comment]
Should we also close this as duplicate?  (#5932)

**Comment by blueyed** [comment]
Might be good to get feedback in https://github.com/pytest-dev/pytest/pull/5933 how the new method / alternatives would be useful for the plugin, since the plugin would benefit here from having the original explanation (or a way to say where it should be inserted (via special placeholder)).

**Comment by JBKahn** [comment]
I'll take a look tomorrow myself

**Comment by JBKahn** [comment]
Thanks for getting back so quickly!
