### ISSUE TITLE
help - documentation improvement - grouping test by class - how to share values

### ISSUE THREAD

**Issue by andreabisello** [pytest-dev/pytest#5942]
Following this example
https://docs.pytest.org/en/latest/getting-started.html#group-multiple-tests-in-a-class
i would like to make a test workflow.
the second test needs result obtained from the first test.
i'm not able to share these information.

i'm using python 3.7.4 and pytest-5.2.1

as you can see,

even if i set a parameter to the class, this parameter look like already evaluated when the second test start.

```
import pytest
@pytest.mark.incremental
class TestUserHandling:
    id = "1"
    def test_login(self):
        print("id value --> " + self.id)
        self.id = "2"
        print("id value --> " + self.id)
        pass

    def test_modification(self):
        assert self.id == "2", "self id value is " + self.id

```

first test returns

```
b__test_step.py::TestUserHandling::test_login PASSED
id value --> 1
id value --> 2
```

second test returns

```
AssertionError: self id value is 1
1 != 2
```

second test needs data from the first test to make the job.

how can i obtain this behaviour?

thanks.

**Comment by andreabisello** [comment]
> each method gets a new instance, the workflow you propose is currently not supported at all

Understand.

So if my test workflow is 

* try to make login. you should obtain a token
* try to validate this token. the token should to be valid

i cannot cover this behaviour because i cannot pass the token obtained from the first test using the login api to the second test that need the token for the validateToken api.

this isn't a normal flow ? i'm doing something out of standard?

thanks for your feedback.

**Comment by andreabisello** [comment]
> the general standard is that each test is separate and independent of each other test
> 
> however the work flow that you implement is something thats recently picking up as more and more end2end and system testing happens,
> where one tests a work-flow composed of multiple steps, which people like to put into methods of some sort
> 
> currently pytest has no good answer to this, but startig points in plugins like [pytest-subtests](https://pypi.org/project/pytest-subtests/)

i totally agree with you,
due i'm creating e2e tests.

every test need to be independent,
but some test needs some pre-requisite.

i don't like to mock pre requisite, and login token cannot be mocked.

i will take a look to pytest-subtests.

what do you think about a documentation improvement ? i can make a pull request for synthetically describe this situation.

**Comment by RonnyPfannschmidt** [comment]
currently the setups im involved in do workflws&co by just setting up the dependencies for each test in fixtures, even if its expensive in some ways, and then use caching7scopes to sort out the cost

**Comment by RonnyPfannschmidt** [comment]
thanks for the follow-up
