### ISSUE TITLE
Can I see warnings as I would without pytest?

### ISSUE THREAD

**Issue by dan-stromberg** [pytest-dev/pytest#5956]
Hi.  Thanks for looking at this issue.

- [x] a detailed description of the bug or suggestion
I want to run a single test with warnings not disabled or redirected or anything else.  I just want them to appear as they would normally, so I can figure out which statement in the test is generating the warning.  Yes, the test is probably bigger than it should be.

- [x] output of `pip list` from the virtual environment you are using
I would need to check with management before posting that much detail, but here are the pytest-related ones:
$ python3 -m pip freeze | grep pytest
below cmd output started 2019 Mon Oct 14 01:09:34 PM PDT
pytest==4.6.5
pytest-forked==1.0.2
pytest-pudb==0.7.0
pytest-repeat==0.8.0
pytest-xdist==1.29.0
unittest2pytest==0.4

I'm using both Python 3.6 and Python 2.7, BTW.

- [x] pytest and operating system versions
See above, and Linux Mint 19.1

- [ ] minimal example if possible
I'm not sure one is useful in this case.

**Comment by blueyed** [comment]
One possibility would be to use `pdb` (e.g. via `pytest --trace`) and `break warnings.warn`.
Otherwise try `-s` and `--disable-warnings`.

**Comment by dan-stromberg** [comment]
pdb gave the default behaviour.
-s gave the default behaviour.
--disable-warnings suppressed the warnings.
-s --disable-warnings suppressed the warnings.

I'm taking this to Freenode.

Thanks!

**Comment by dan-stromberg** [comment]
ronny on Freenode quickly responded that I could:
python3 -Walways -m pytest -p no:warnings -s test_clustering_api.py::TestClusteringApi::test_get_active_clusters

I report it here for web searches.

Thanks.

**Comment by The-Compiler** [comment]
FWIW I like `-Werror` for tracking down warnings - then you get a stacktrace.

**Comment by blueyed** [comment]
> pdb gave the default behaviour.

What I've meant is that you would then stop/break where the warning get emitted.
Did you forgot to set the breakpoint?

Anyway, closing as answered then.

I second `-Werror`, but often it stops then already for DeprecationWarnings etc that you have to ignore then first.
