### ISSUE TITLE
how to use fixture chain?

### ISSUE THREAD

**Issue by bglmmz** [pytest-dev/pytest#5970]
I defined a session fixture in conftest.py,  and the fixture returns a global env, 

```
@pytest.fixture(scope="session", autouse=True)
def global_test_env(request):
    ...
    global_env = create_env_impl()
    yield global_env 
    ....
```

Now I difined another module fixture in xxx.py，and this fixture want to retrieve the global_env  created in session fixture. How to approach this? Like below?

```
@pytest.fixture(scope='module',autouse=True)
def custom_env(global_test_env):
    #retrieve the global_env like this?
    global_env = global_test_env

    do something else...
    my_env = create_my_evn()
    yield my_env    
    ....

```

**Comment by The-Compiler** [comment]
That looks good, yup!

**Comment by bglmmz** [comment]
the stackoverflow has a same quetion:

[https://stackoverflow.com/questions/56402600/pytest-calling-a-fixture-from-another-fixture](url)

**Comment by Zac-HD** [comment]
Answered on StackOverflow 😄 

FYI you can have [syntax highlighting for code blocks on Github](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).
