### ISSUE TITLE
How to register custom mark in my library?

### ISSUE THREAD

**Issue by ddidier** [pytest-dev/pytest#5972]
Hi,
I'm developing a small library with custom marks and I see a lot of `PytestUnknownMarkWarning` when testing it and using it. I know that this is the intended behavior and that the marks should be declared in the importing project (in `pytest.ini` and `conftest.py`), but is there a way to declare them in the library itself, so that the library users have no need to do so?
Thanks

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest-forked/blob/dd42fd1861201536f985be7075f8cd869e17179c/src/pytest_forked/__init__.py#L32-L36 has an example of a recent addition in a plugin

this can also be done in `pytest_configure`
