### ISSUE TITLE
Easier access to what marks are active would rock 🤘

### ISSUE THREAD

**Issue by carsongee** [pytest-dev/pytest#5987]
As a plugin writer, I would like to select/deselect tests more dynamically based on what marks are active.  Specifically, I wanted to dynamically add marks to a subset of tests in `parametrize` marked test using the `pytest_generate_tests` hook, e.g. pick a random one to run in the current session because a mark is present. 

Unfortunately, I had to go digging into the internal APIs to use the mark and keyword option sets from config and combine it as is done in https://github.com/pytest-dev/pytest/blob/master/src/_pytest/mark/__init__.py#L98. Perhaps  making the parsing separable methods is enough, but I think the ideal situation is to have a `config.marks` or `config.active_marks` available early enough that both `_pytest/mark` and plugin hooks can read them before selection/deselection occurs.

**Comment by RonnyPfannschmidt** [comment]
please show an example of your use-ase, its not clear what you mean

pseudo-code/mockup is sufficient

**Comment by carsongee** [comment]
No problem, the test would be something like:
```python
@pytest.mark.parameterized_run_all_at_night_otherwise_first('apple', ['red delicious', 'granny smith'])
def test_apples(...)
    ...
```
and `pytest_generate_tests` for that mark would choose which parameters have which mark depending on what marks are active, something along the lines of:
```python
if 'nightly' in metafunc.config.marks:
    # mark all tests with nightly so they all run
else:
   # generate first one only
```

**Comment by RonnyPfannschmidt** [comment]
pytest has no concept of active marks at all

a starting point would be a plugin to demo the behaviour

**Comment by Zac-HD** [comment]
Closing as unclear / stale; happy to re-open if we have a demonstration.
