### ISSUE TITLE
latest version(19.3.0) of dependency attrs is breaking pytest (4.2.0)

### ISSUE THREAD

**Issue by sandipsutariya** [pytest-dev/pytest#5988]
We are still using v.4.2.0 of PyTest. From last two days, tests started failing giving error from attrs library. Looks like the latest version 19.3.0 of 'attrs' is creating problem with this. Considering PyTest has dependency attrs >=17.4.0, it always install the latest attrs and that is causing problem

**Comment by The-Compiler** [comment]
This has already been fixed in pytest 4.6.6 and 5.2.1.

**Comment by RonnyPfannschmidt** [comment]
note, if unable to update pytest, pin your attrs dependency
