### ISSUE TITLE
Plurality mismatch in warnings

### ISSUE THREAD

**Issue by MarcoGorelli** [pytest-dev/pytest#5989]
- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

Admittedly this is a very minor issue.

If I write a file `pytest_example.py` as

```
import warnings

warnings.warn("one warning")
```
and then run
```
pytest pytest_example.py
```
from the command line, the output reads
> 1 warnings in 0.02s

I believe this should read "1 warning in 0.02s".

Would a PR to address this be welcome?

<details>

```
$ pip list
Package            Version
------------------ -------
atomicwrites       1.3.0  
attrs              19.3.0 
importlib-metadata 0.23   
more-itertools     7.2.0  
packaging          19.2   
pip                19.0.3 
pluggy             0.13.0 
py                 1.8.0  
pyparsing          2.4.2  
pytest             5.2.1  
setuptools         40.8.0 
six                1.12.0 
wcwidth            0.1.7  
zipp               0.6.0  

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

</details>

**Comment by The-Compiler** [comment]
Similarly this:

```python
import pytest

@pytest.fixture
def fix():
    raise Exception

def test_foo(fix):
    pass

def test_bar(fix):
    pass
```

displays "2 error in ...s".

Those messages are generated via `build_summary_stats_line` in `terminal.py` - but I'm not sure what the best way would be to handle this, as e.g. plugins can insert their own outcomes there as well.

**Comment by nicoddemus** [comment]
I think fixing our core messages is OK, so IMHO a PR would be welcome @MarcoGorelli!

**Comment by blueyed** [comment]
Fixed in https://github.com/pytest-dev/pytest/pull/5990 (features).
