### ISSUE TITLE
How to skip value from generator in `pytest.mark.parametrize`?

### ISSUE THREAD

**Issue by heckad** [pytest-dev/pytest#6012]
I have a generator wich return tuple of `exchange_name, exchange_class, info, credentials`. For some test, I need in all of this but in another test don't. How to skip some values? I tried 
`@pytest.mark.parametrize('_, exchange_class, _, credentials')` but it does not work.

**Comment by Zac-HD** [comment]
```python
@pytest.mark.parametrize('exchange_class, (c for _, c, _ in credentials))
```

should do the trick - remember that you've got all of Python available!

**Comment by heckad** [comment]
It's not useful when six or more parameters and need skip 2. Maybe add `_` as the empty mark in `parametrize`. It will be a good feature.
