### ISSUE TITLE
ci: remove WIP status bot

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6024]
I do not like that it displays PR statuses as "pending", which is the same as when CI is running still - this does not allow for seeing if CI has finished for a PR.

Given that it is triggered via `[WIP]` in the subject, I'd rather still use that indicator by itself.
IIRC it was added when some WIP-PR was merged accidentally, but that can be avoided by just paying attention to the subject and any previous comments then.
Also in my case I prefer to merge my PRs after approval myself, and would not merge PRs from other contributors (that can merge theirs themselves), so accidentally merging a WIP-PR shouldn't be an issue there in the first place.

So I'd like to ask for removal of the CI status.

**Comment by The-Compiler** [comment]
Also note that GitHub has native support for [Draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) nowadays.

**Comment by nicoddemus** [comment]
Given that most people have replied with 👍 to the issue, I've removed it, although I personally don't have a problem with it myself.

It would be nice if we started to use Draft pull requests then.
