### ISSUE TITLE
Passing parameter to fixture from test parametrization

### ISSUE THREAD

**Issue by yamoussouk** [pytest-dev/pytest#6037]
Hello everyone,

I have a scenario where on a test a parametrize decorator is placed. Using the parameter during the test is easy, but passing the parameter or something to a fixture is hard to me. I've read the doc, many github threads, but I could not find the solution to my problem.

````
def some_data_provider():
   return [('name','23'), ('gender','male')]

TestClass:
@pytest.fixture()
def some_fixture(request):
   yield
   self.__restore(request.param)
@pytest.mark.parametrize('some_fixture', [data[0]], indirect=True)
@pytest.mark.parametrize('data', some_data_provider())
def test_some_test(self, data):
   assert data[0] == 0
````

So when a test runs I want the fixture to restore a very specific data passed by the test, or the decorator itself, whatever. Is it possible? Thank you guys!

**Comment by Zac-HD** [comment]
I don't think this is possible, sorry.  Might be related to #3678?
