### ISSUE TITLE
Exit code 5 when the test is passed, and exit code 2

### ISSUE THREAD

**Issue by PierreMarchand20** [pytest-dev/pytest#6049]
- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions: 5.2.1 on macOS
- [x] minimal example if possible: see [here](https://github.com/PierreMarchand20/htool/tree/python)

I have a very simple library [here](https://github.com/PierreMarchand20/htool/tree/python) and I am trying to setup a test for the python interface. When I do `pytest` in the root of my repo or in `python_tests`, I got a exit code 5, which means that it did not find my test (which is weird from what I understood of the documentation). But if I break my test, then it finds it.

![image](https://user-images.githubusercontent.com/15056323/67415637-46629280-f5bd-11e9-9ec5-f7226fa136a9.png)

![image](https://user-images.githubusercontent.com/15056323/67415715-6b570580-f5bd-11e9-8419-b49643741854.png)

So it finds when it breaks but not when it works fine. If it is a bug, it seems to be not very consistent.

`pip list`
 pip3 list
Package            Version  
------------------ ---------
astroid            2.3.1    
atomicwrites       1.3.0    
attrs              19.3.0   
certifi            2019.9.11
chardet            3.0.4    
cycler             0.10.0   
Cython             0.29.13  
enopy              0.10.0   
gmsh-api           0.1.5    
Htool              1.0      
idna               2.8      
importlib-metadata 0.23     
isort              4.3.21   
kiwisolver         1.1.0    
lazy-object-proxy  1.4.2    
matplotlib         3.1.1    
mccabe             0.6.1    
more-itertools     7.2.0    
mpi4py             3.0.2    
numpy              1.17.2   
packaging          19.2     
pandas             0.25.1   
pip                19.1.1   
pluggy             0.13.0   
py                 1.8.0    
pylint             2.4.2    
pyparsing          2.4.2    
pytest             5.2.1    
python-dateutil    2.8.0    
pytz               2019.3   
requests           2.22.0   
scipy              1.3.1    
setuptools         41.0.1   
six                1.12.0   
TBB                0.1      
typed-ast          1.4.0    
urllib3            1.25.6   
wcwidth            0.1.7    
wheel              0.33.4   
wrapt              1.11.2   
zipp               0.6.0

**Comment by The-Compiler** [comment]
It's hard to tell from your cropped screenshots, but I think what happens is this:

- At the top, collection finished but no test was found -> exit status 5
- At the bottom, there was an error during collection (the output should say so?) -> exit status 2

In other words, even at the bottom, no test was found - but there was some exception during the collection phase.

Does that make sense?

**Comment by PierreMarchand20** [comment]
Well the output is a little bit large, so it was just to give you an idea of the problem and try by yourself. 

But no, because in the second case, I see the output of my code and the assert is explained as expected: (top of the second output)
![image](https://user-images.githubusercontent.com/15056323/67416751-4cf20980-f5bf-11e9-8c9f-55146708775c.png)

**Comment by PierreMarchand20** [comment]
Ok I got it, the function needs to called `test`something. I thought an assert would be enough
