### ISSUE TITLE
Make it possible to call hooks in pytest_addoption

### ISSUE THREAD

**Issue by joshuastorck** [pytest-dev/pytest#6061]
**Suggestion**

Make it possible to call hooks in pytest_addoption by passing the pluginmanager as an argument. 

I have a  plugin that is used across a number of projects. That plugin has a command line option that is added in pytest_addoption, but the default values for those options will change based on the project/conftest.py that's using them (think: configuration file). While I could use the parser's **extra_info** field to inject the default values, that seems like a hack and not the field's intended use. Instead, it would seem to make more sense to have the conftest.py plugin in each project implement a hook or hooks that return the default values. That way there is a nicely defined contract between the plugin and the conftest.py that depends on it. Unfortunately, the pytest_addoption hook does not make the pluginmanager available as an argument. The plugin can cheat by storing a reference to the pluginmanager in pytest_addhooks, which works like this but feels like a hack:

In the plugin file, myplugin.py:

```python
import hooks

global thepluginmanager

def pytest_addhooks(pluginmanager):
    global thepluginmanager
    pluginmanager.add_hookspecs(hooks)
    thepluginmanager = pluginmanager

def pytest_addoption(parser):
    global thepluginmanager
    parser.addoption("--some-option", help="Some option, defaults to %(default)s",
                     default=thepluginmanager.hook.pytest_myplugin_default_value()[0])
```
In the conftest.py file:

```python
pytest_plugins = ["myplugin"]

def pytest_myplugin_default_value():
    return 1
```
In the hooks.py file:

```python
def pytest_myplugin_default_value():
    """
    Returns the default value for the command line option
    """
```

One possible solution would be to modify the signature to:

```python
def pytest_addoption(parser, pluginmanager)
```
It appears the pluggy can handle this in a backwards compatible fashion, though I could imagine there is a deprecation policy in this project that requires defining a newly named function. Alternatively, add a new hook and call them both:

```python
def pytest_addoption_with_plugins(parser, pluginmanager)
```

**pytest Version: 3.7.4**

**Comment by RonnyPfannschmidt** [comment]
Why not just use a ini option for the per project default and warn in pytest configure if that's not set

**Comment by joshuastorck** [comment]
I don’t want to repeat the help documentation in each project and want the
—help to display the default value.

**Comment by RonnyPfannschmidt** [comment]
in that case, how about a helper function in the main project, and then each project can just call `helper(parser)`

this has the added benefit of failing early if someone sets it up multiple times by accident

**Comment by joshuastorck** [comment]
I tried that but it requires importing the plugin in conftest.py, which
emits the warning about assertion rewriting. I can put a sibling module
next to the plugin module with the helper function, though I would prefer
to keep the code in one place for readability and maintainability.

Is there a danger in making the pluginmanager available to addoption? Or is
adding a new hook not desirable?

I could imagine there are a lot of ways this could be useful beyond default
values. For example, your contest.py could signal to the plugin whether or
not it needed certain features and the plugin could conditionally add
command line arguments.

I would be happy to put together a PR for the feature if folks are open to
adding the new hook.

**Comment by nicoddemus** [comment]
Unless @RonnyPfannschmidt has strong motives otherwise, I think it is fine to add `pluginmanager` as parameter to `pytest_addoption`, we already pass the plugin manager to `pytest_addhooks` and `pytest_cmdline_parse`, so I don't see any harm.

**Comment by RonnyPfannschmidt** [comment]
ok, lets add it as a experimental hook

**Comment by nicoddemus** [comment]
I actually meant just adding `pluginmanager` parameter to `pytest_addoption`, not adding a new hook.

**Comment by blueyed** [comment]
What about passing config?

**Comment by joshuastorck** [comment]
I’m happy to make the PR. What’s the process  for making it experimental?

**Comment by joshuastorck** [comment]
I think when pytest_addoption is called config is not fully initialized,
that’s why I recommended passing the pluginmanager instead.

**Comment by blueyed** [comment]
> What’s the process  for making it experimental?

You can use a draft PR, but feel free to have it tested already to see failing tests etc.

**Comment by blueyed** [comment]
I guess you could try passing `config=self` - then the pluginmanager is also available from there then: https://github.com/pytest-dev/pytest/blob/fea57bf3c3a12ba7dc7bc8135a8f41c5a9fd4981/src/_pytest/config/__init__.py#L698-L707

**Comment by joshuastorck** [comment]
I don't think config should be passed at that point, as it's in a half-initialized state. Note how _configured is set to False. Most of the methods would be useless/wrong (e.g., getoption). Perhaps an argument could be made for including InvocationParams as a parameter.

**Comment by RonnyPfannschmidt** [comment]
at that point config is entirely incomplete, so no passing it please
