### ISSUE TITLE
Output INTERNALERROR to stderr?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6091]
It appears to be good practice outputting errors to stderr instead of stdout.

**Comment by RonnyPfannschmidt** [comment]
sounds like a good idea, lets cross-check if not using stderr has a historic reason or if it was just an artefact of getting something else done and creating it

**Comment by blueyed** [comment]
stderr gets used here: https://github.com/pytest-dev/pytest/blob/2edb960a107e7f7204c8094011d59708fefd671a/src/_pytest/config/__init__.py#L764-L776, but not here: https://github.com/pytest-dev/pytest/blob/2edb960a107e7f7204c8094011d59708fefd671a/src/_pytest/terminal.py#L418-L421

**Comment by blueyed** [comment]
So it's likely due to the TerminalWriter not having the concept of stderr.

**Comment by blueyed** [comment]
Out of scope given TerminalWriter's limitation for now I think.
