### ISSUE TITLE
Support Python3.8 PYTHONPYCACHEPREFIX (parallel filesystem cache for .pyc)

### ISSUE THREAD

**Issue by inyeollee** [pytest-dev/pytest#6095]
Pytest saves .pyc files to "__pycache__" subdirectory of the Python module, regardless of Python3.8 PYTHONPYCACHEPREFIX setting. Please add parallel filesystem support for .pyc.

Here are test setup:
$uname -sv
Darwin Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64
$ python3 --version
Python 3.8.0
$ pytest --version
This is pytest version 5.2.2, imported from /Users/inyeol/util/lib/python3.8/site-packages/pytest.py
$ echo $PYTHONPYCACHEPREFIX
/Users/inyeol/.pycache

**Comment by blueyed** [comment]
See https://github.com/pytest-dev/pytest/pull/5864, i.e. it is in the features branch already.
