### ISSUE TITLE
terminal: indicate current outcome/status with color of percentage indicator

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6097]
It would be nice to use different colors for the "[XXX%]" indicator, according to if there are failed tests already especially.
Basically it could have the color that would be used with the final (new) multi-colored line's main color.

**Comment by MarcoGorelli** [comment]
This would be a nice feature! I'd be happy to work on it if nobody else has taken it on

**Comment by blueyed** [comment]
Fixed in features.

As a follow-up I think this would be nice:

- [ ] bold for when the status / number of errors changed in the current line
- [ ] a count for new (and updated totals) in/from the current line, maybe only with a new "console_output_style" option, but it seems to be useful with both existing modes (percent and counts)

**Comment by nicoddemus** [comment]
Closing this for now, given that the original issue has been fixed.
