### ISSUE TITLE
ERROR: InvocationError for command 'C:\src\techweb\AutomatedTests\api\tmp\py37\Scripts\python' 'C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pycharm\pytestrunner.py'

### ISSUE THREAD

**Issue by AlainBouchard** [pytest-dev/pytest#6105]
- [ ] a detailed description of the bug or suggestion
Since I've updated to pytest 5.0.1 to 5.2.0 then my PyCharm + Tox + Pytest setup doesn't work anymore.  It works again when I downgrade to 5.0.1.

note: I am having the same issue with 5.1.0, so 5.2.0 probably didn't introduce the bug.

Console output + Stack Trace:
Testing started at 3:38 PM ...
C:\Users\alainb\PycharmProjects\techweb\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pycharm\_jb_tox_runner.py" --recreate --
py37 recreate: C:\src\techweb\AutomatedTests\api\tmp\py37
py37 installdeps: -rrequirements-tox.txt
WARNING: Discarding $PYTHONPATH from environment, to override specify PYTHONPATH in 'passenv' in your configuration.
py37 installed: aiosmtpd==1.2,alabaster==0.7.12,atomicwrites==1.3.0,atpublic==1.0,attrs==19.3.0,Babel==2.7.0,bottle==0.12.17,certifi==2019.9.11,cffi==1.13.1,chardet==3.0.4,colorama==0.4.1,coverage==4.5.4,cryptography==2.8,decorator==4.4.0,docutils==0.15.2,entrypoints==0.3,Faker==2.0.2,filelock==3.0.12,flake8==3.7.8,hub-aqa-framework==1.12,idna==2.8,imagesize==1.1.0,importlib-metadata==0.23,Jinja2==2.10.3,jwcrypto==0.6.0,MarkupSafe==1.1.1,mccabe==0.6.1,mock==3.0.5,more-itertools==7.2.0,packaging==19.2,pluggy==0.13.0,pockets==0.9,psutil==5.6.3,py==1.8.0,pycodestyle==2.5.0,pycparser==2.19,pyflakes==2.1.1,Pygments==2.4.2,PyJWT==1.7.1,pyodbc==4.0.27,pyparsing==2.4.2,pytest==5.2.0,pytest-cov==2.7.1,python-dateutil==2.8.0,pytz==2019.3,requests==2.22.0,six==1.12.0,snowballstemmer==2.0.0,Sphinx==2.2.0,sphinxcontrib-applehelp==1.0.1,sphinxcontrib-devhelp==1.0.1,sphinxcontrib-htmlhelp==1.0.2,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-napoleon==0.7,sphinxcontrib-qthelp==1.0.2,sphinxcontrib-serializinghtml==1.1.3,teamcity-messages==1.25,text-unidecode==1.3,toml==0.10.0,tox==3.14.0,urllib3==1.25.6,virtualenv==16.7.7,wcwidth==0.1.7,zipp==0.6.0
py37 run-test-pre: PYTHONHASHSEED='579'
py37 run-test: commands[0] | flake8 src/ tests/
py37 run-test: commands[1] | 'C:\src\techweb\AutomatedTests\api\tmp\py37\Scripts\python' 'C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pycharm\pytestrunner.py' -p pytest_teamcity -p no:cacheprovider --cov-config .coveragerc --cov-report term-missing --cov=src/dgw --cov=src/techweb --cov=src/pms --cov=src/ams src src/framework tests/dgw tests/techweb tests/pms tests/ams
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pycharm\pytestrunner.py", line 60, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pycharm\pytestrunner.py", line 34, in main
    pluginmanager=_pluginmanager, args=args)
  File "C:\src\techweb\AutomatedTests\api\tmp\py37\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\src\techweb\AutomatedTests\api\tmp\py37\lib\site-packages\pluggy\manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\src\techweb\AutomatedTests\api\tmp\py37\lib\site-packages\pluggy\manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "C:\src\techweb\AutomatedTests\api\tmp\py37\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\src\techweb\AutomatedTests\api\tmp\py37\lib\site-packages\_pytest\helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "C:\src\techweb\AutomatedTests\api\tmp\py37\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\src\techweb\AutomatedTests\api\tmp\py37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\src\techweb\AutomatedTests\api\tmp\py37\lib\site-packages\_pytest\config\__init__.py", line 736, in pytest_cmdline_parse
    self.parse(args)
  File "C:\src\techweb\AutomatedTests\api\tmp\py37\lib\site-packages\_pytest\config\__init__.py", line 939, in parse
    assert self.invocation_params.args == args
AssertionError
ERROR: InvocationError for command 'C:\src\techweb\AutomatedTests\api\tmp\py37\Scripts\python' 'C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\helpers\pycharm\pytestrunner.py' -p pytest_teamcity -p no:cacheprovider --cov-config .coveragerc --cov-report term-missing --cov=src/dgw --cov=src/techweb --cov=src/pms --cov=src/ams src src/framework tests/dgw tests/techweb tests/pms tests/ams (exited with code 1)

commands failed
___________________________________ summary ___________________________________
ERROR:   py37: commands failed

Process finished with exit code 0

- [ ] output of `pip list` from the virtual environment you are using
aiosmtpd==1.2,alabaster==0.7.12,atomicwrites==1.3.0,atpublic==1.0,attrs==19.3.0,Babel==2.7.0,bottle==0.12.17,certifi==2019.9.11,cffi==1.13.1,chardet==3.0.4,colorama==0.4.1,coverage==4.5.4,cryptography==2.8,decorator==4.4.0,docutils==0.15.2,entrypoints==0.3,Faker==2.0.2,filelock==3.0.12,flake8==3.7.8,hub-aqa-framework==1.12,idna==2.8,imagesize==1.1.0,importlib-metadata==0.23,Jinja2==2.10.3,jwcrypto==0.6.0,MarkupSafe==1.1.1,mccabe==0.6.1,mock==3.0.5,more-itertools==7.2.0,packaging==19.2,pluggy==0.13.0,pockets==0.9,psutil==5.6.3,py==1.8.0,pycodestyle==2.5.0,pycparser==2.19,pyflakes==2.1.1,Pygments==2.4.2,PyJWT==1.7.1,pyodbc==4.0.27,pyparsing==2.4.2,pytest==5.2.0,pytest-cov==2.7.1,python-dateutil==2.8.0,pytz==2019.3,requests==2.22.0,six==1.12.0,snowballstemmer==2.0.0,Sphinx==2.2.0,sphinxcontrib-applehelp==1.0.1,sphinxcontrib-devhelp==1.0.1,sphinxcontrib-htmlhelp==1.0.2,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-napoleon==0.7,sphinxcontrib-qthelp==1.0.2,sphinxcontrib-serializinghtml==1.1.3,teamcity-messages==1.25,text-unidecode==1.3,toml==0.10.0,tox==3.14.0,urllib3==1.25.6,virtualenv==16.7.7,wcwidth==0.1.7,zipp==0.6.0
- [ ] pytest and operating system versions
pytest==5.2.0
Microsoft Windows [Version 10.0.17763.652]

PyCharm 2019.2.3 (Community Edition):
Build #PC-192.6817.19, built on September 25, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4

- [ ] minimal example if possible

**Comment by The-Compiler** [comment]
This is a PyCharm bug which is fixed in 2019.3, see https://youtrack.jetbrains.com/issue/PY-37571

**Comment by AlainBouchard** [comment]
@The-Compiler thanks, validated - it's working with 2019.3 EAP version:
PyCharm 2019.3 EAP (Community Edition)
Build #PC-193.4778.18, built on October 23, 2019
