### ISSUE TITLE
recursive dependency involving fixture 'httpbin' detected

### ISSUE THREAD

**Issue by jayvdb** [pytest-dev/pytest#6110]
python requests [`conftest.py`](https://github.com/psf/requests/blob/15a3869/tests/conftest.py#L18) for many years has had

```
import pytest
from requests.compat import urljoin


def prepare_url(value):
    # Issue #1483: Make sure the URL always has a trailing slash
    httpbin_url = value.url.rstrip('/') + '/'

    def inner(*suffix):
        return urljoin(httpbin_url, '/'.join(suffix))

    return inner


@pytest.fixture
def httpbin(httpbin):
    return prepare_url(httpbin)


@pytest.fixture
def httpbin_secure(httpbin_secure):
    return prepare_url(httpbin_secure)
```

This recently started triggering
`recursive dependency involving fixture 'httpbin' detected`
which is one of two problems causing their pytest to be pinned to an old version.

That is not recursive, but I can see why it might have been broken by pytest 5. 
It is quite easy to fix the requests tests to use new names for their custom fixtures, and most people would appreciate the added clarity.

If this is very intentionally no longer supported, it would be useful to adjust the error message
> redefinition of fixture 'httpbin' detected

If this style of redefinition is deemed still desirable/permissible, does the fix only involve improving the detection logic to avoid this false positive?  Or is the problem deeper?

**Comment by jayvdb** [comment]
I havent been able to reproduce this in a VM, so it might be a local problem.  I am currently suspecting it might be that pytest-httpbin isnt loading properly for me, which might explain why it is being detected as circular.  Sifti9ng through a few semi-related env problems atm, and will update when isolated.  I have got requests working with pytest 5, give or take a few tests, with a few changes to their test suite at https://github.com/psf/requests/pull/5251

**Comment by RonnyPfannschmidt** [comment]
without more context on where "httpbin" is from, this is clearly self-recursive for both fixtures

**Comment by RonnyPfannschmidt** [comment]
i started reading a bit more code, seems like i need to actually clone and run tests myself to understand whats up

**Comment by RonnyPfannschmidt** [comment]
yikes, instead of tox its using easy_install to install test_dependencies, thats just fundamentally wrong

**Comment by RonnyPfannschmidt** [comment]
running the tests  now in a own virtualenv

**Comment by RonnyPfannschmidt** [comment]
i cant replicate the error locally using the branch you posted in the pr

**Comment by jayvdb** [comment]
I did say above I cant replicated it in a VM :P
I'm still working on slightly adjacent problems in order to better isolate it.

**Comment by jayvdb** [comment]
After the other pytest5 problems were fixed, I found the problem was my `httpbin` wasnt loading correctly (due to binary package markupsafe), causing pytest-httpbin to also break, and thus `httpbin` fixture didnt exist, which is why it was being reported as a recursive fixture dependency.  I guess there isnt much that pytest can do to help here.
