### ISSUE TITLE
a test silent ignore

### ISSUE THREAD

**Issue by andry81** [pytest-dev/pytest#6113]
- [ ] a detailed description of the bug or suggestion
If conditionally or unconditionally create a test with already existed file name, then it would be ignored to run and the first one would be run instead. Which means that a test can be silently ignored.

- [ ] output of `pip list` from the virtual environment you are using
<details>

```
Package             Version
------------------- -------
atomicwrites        1.3.0
attrs               19.2.0
cmdix               0.2.0
colorama            0.4.1
conditional         1.3
importlib-metadata  0.23
importlib-resources 1.0.2
more-itertools      7.2.0
packaging           19.2
pip                 19.3.1
pluggy              0.13.0
plumbum             1.6.7
prompt-toolkit      2.0.10
py                  1.8.0
pyparsing           2.4.2
pytest              5.2.2
PyYAML              5.1.2
setuptools          40.8.0
six                 1.12.0
wcwidth             0.1.7
win-unicode-console 0.5
xonsh               0.9.12
zipp                0.6.0
```

</details>

- [ ] pytest and operating system versions
`windows 7 x64`
`platform win32 -- Python 3.7.3, pytest-5.2.2, py-1.8.0, pluggy-0.13.0`

- [ ] minimal example if possible
create 2 tests:
```
<root>/01_test/test_main.py
<root>/02_test/test_main.xsh
```
the second would be ignored

**Comment by The-Compiler** [comment]
I can't reproduce this (on Linux though) - I get an import file mismatch error as I'd expect.

```
$ mkdir 01_test
$ mkdir 02_test
$ cat > 01_test/test_main.py
def test_things():
    pass
$ cp 01_test/test_main.py 02_test/test_main.py
$ pytest
```

gives me:

```
________________________ ERROR collecting 02_test/test_main.py ________________________
import file mismatch:
imported module 'test_main' has this __file__ attribute:
  /home/florian/tmp/6113/01_test/test_main.py
which is not the same as the test file we want to collect:
  /home/florian/tmp/6113/02_test/test_main.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```

**Comment by andry81** [comment]
> I can't reproduce

Ye, this seems somehow connected to different extensions of test files.

Try additionally to print from each test:
> 01_test\test_main.py
```
def test_me():
  print(1)
```
> 02_test\test_main.xsh
```
def test_me():
  print(2)
```
```
02_test\test_main.xsh 1
.
01_test\test_main.py 1
.
```

**Comment by The-Compiler** [comment]
pytest only collects `*.py` files by default - what are you doing to make it collect `*.xsh` files exactly?

**Comment by andry81** [comment]
Nothing, just run pytest.
`.xsh` is registered extension of the `xonsh` module. May be it is connected to that.

**Comment by The-Compiler** [comment]
Hmm, weird. If you don't have any plugins related to that (which you don't seem to have, according to your output) and you don't have a `pytest.ini` which changes the `python_files` setting away from its default `test_*.py`, I don't see why such files should be collected at all.

**Comment by andry81** [comment]
I have an empty `pytest.ini`, just to move `.pytest_cache` directory 1 level up in the directory tree.

**Comment by The-Compiler** [comment]
Ah, looks like the xonsh module automatically installs a [pytest plugin](https://github.com/xonsh/xonsh/blob/master/xonsh/pytest_plugin.py) to pick `test_*.xsh` up. So both this and #6114 might actually be bugs in that plugin rather than pytest - but I'm not sure.

**Comment by andry81** [comment]
Why it should be in there? I don't see how that related to the xonsh.

**Comment by The-Compiler** [comment]
Why wouldn't it be in there, seeing that you can only reproduce this issue with that plugin?

I've taken a closer look now - the plugin does some `sys.path` patching and then does `mod = importlib.import_module(self.fspath.purebasename)`, in other words, it imports the `test_main` module. Since that module (the `.py` one) was already imported previously, it gets the existing one (that's a Python mechanism).

Instead of using `importlib`, it should probably do something similar than pytest [does](
https://github.com/pytest-dev/pytest/blob/5.2.2/src/_pytest/python.py#L497), where it detects such collisions.
