### ISSUE TITLE
can not order tests by a test directory path

### ISSUE THREAD

**Issue by andry81** [pytest-dev/pytest#6114]
- [ ] a detailed description of the bug or suggestion
I want to collect and run tests ordered by a directory path just like in a convenient testing system. Currently tests run chaotically.

- [ ] output of `pip list` from the virtual environment you are using
<details>

```
Package             Version
------------------- -------
atomicwrites        1.3.0
attrs               19.2.0
cmdix               0.2.0
colorama            0.4.1
conditional         1.3
importlib-metadata  0.23
importlib-resources 1.0.2
more-itertools      7.2.0
packaging           19.2
pip                 19.3.1
pluggy              0.13.0
plumbum             1.6.7
prompt-toolkit      2.0.10
py                  1.8.0
pyparsing           2.4.2
pytest              5.2.2
PyYAML              5.1.2
setuptools          40.8.0
six                 1.12.0
wcwidth             0.1.7
win-unicode-console 0.5
xonsh               0.9.12
zipp                0.6.0
```

</details>

- [ ] pytest and operating system versions
`Windows 7 x64`
`platform win32 -- Python 3.7.3, pytest-5.2.2, py-1.8.0, pluggy-0.13.0`

- [ ] minimal example if possible
create hierarchical set of tests with different file extension:
```
<root>/01_group_a/01_test_bbb/test_main_01.py
<root>/01_group_a/02_test_xxx/test_main_02.xsh
<root>/01_group_a/03_test_ddd/test_main_03.py
<root>/01_group_a/04_test_ccc/test_main_04.xsh
<root>/01_group_a/04_test_yyy/test_main_05.py
etc..
```

**Comment by The-Compiler** [comment]
Looks like the `xonsh` plugin you're using [reorders](https://github.com/xonsh/xonsh/blob/0.9.13/xonsh/pytest_plugin.py#L17) the tests.
