### ISSUE TITLE
question: is there a way to properly check if a marker is active in conftest

### ISSUE THREAD

**Issue by NNRepos** [pytest-dev/pytest#6115]
Sometimes I need to check if a certain marker is active (from -m or whatever):

```
#I'm conftest.py
def pytest_configure(config):
markers = config.ForgotSyntax.markers
if "network" in markers and "not network" not in markers:
  subprocess.Popen....
```

Is there some simple way to evaluate the markers expression and tell if something is active instead of in... and not in... and... etc. ? e.g.
```
if config.is_active_marker("network"):
   subprocess.Popen...
```

Thanks!

**Comment by RonnyPfannschmidt** [comment]
there is no concept of "active marker"

**Comment by blueyed** [comment]
`get_closest_marker`?
Ref: https://github.com/pytest-dev/pytest/blob/73f63ca9adfc20160034d8094e66aa6713769da5/src/_pytest/nodes.py#L224-L231
(search the docs probably)

**Comment by NNRepos** [comment]
@RonnyPfannschmidt 
> there is no concept of "active marker"

by active I mean, after the markers string has been evaluated, what markers are evaluated as 'True'. Markers can be used with 'and' and 'or', which makes it a bit complicated to know which ones pytest is going to use. The tests are somehow filtered, so there should be some way to see if a marker will be 'active', in the sense that tests using that marker only would be run.

@blueyed 
> `get_closest_marker`?

it looks like this gives me any marker that can be used, not a marker that is used right now by the running pytest.

**Comment by RonnyPfannschmidt** [comment]
@NNRepos marker expressions are evaluated as python expressons against a python dict, there is no concept of "active" there in the sense you outlined earlier

**Comment by blueyed** [comment]
@NNRepos 
Maybe it helps to describe your use case.
`get_closest_marker` allows to see in the context of an item (and related hooks) if (and which) marker is used with that item.

**Comment by NNRepos** [comment]
> @NNRepos marker expressions are evaluated as python expressons against a python dict, there is no concept of "active" there in the sense you outlined earlier

what do you mean by that? Could you reference me to a place in the code where that happens? thanks

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/mark/evaluate.py

**Comment by RonnyPfannschmidt** [comment]
practically it means that its axiomatically impossible to have a concept of a "active mark" from mark eexpressions, as a mark expression does boolean logic, one could perhaps imply one from simple common mark expressions, but its certainly impossible for complex cases (one can have xor relationships)

**Comment by RonnyPfannschmidt** [comment]
oh, and https://github.com/pytest-dev/pytest/blob/master/src/_pytest/mark/__init__.py#L125

**Comment by NNRepos** [comment]
Thanks @RonnyPfannschmidt, this is what I was looking for:
```
#inside src/_pytest/mark/legacy.py
def matchmark(colitem, markexpr):
    """Tries to match on any marker names, attached to the given colitem."""
    try:
        return eval(markexpr, {}, MarkMapping.from_item(colitem))
```

Is there a way to use this function in my conftest.py? I don't think importing _pytest is an option

**Comment by RonnyPfannschmidt** [comment]
@NNRepos its not exposed, whats your actual use-case ? own mark expressions?

**Comment by NNRepos** [comment]
> @NNRepos its not exposed, whats your actual use-case ? own mark expressions?

I'm simply trying to understand what *single* marks will be selected ("active", evaluated as True by matchmark) before starting all tests. For example, if I'm running tests that need to connect to the network over specific routes, I will run a script that changes the routing rules (firewall?) before starting all tests. I only want to run that script once, so I call it from pytest_configure, and not before every test.

**Comment by RonnyPfannschmidt** [comment]
@NNRepos i would strongly suggest to use a session scoped fixture for that kind of setup (unless there is a reason thats preventing such a situation)

**Comment by NNRepos** [comment]
@RonnyPfannschmidt I'm not sure I understood what you said, but perhaps a possible thing preventing it would be running the same setup multiple times with different markers? That's the reason I check them. Also, I don't fully understand what fixtures are.

**Comment by RonnyPfannschmidt** [comment]
@NNRepos a session scope fixture is a fixture that runs once per setup, so they tend to be a good place to set up a resource that one will use for many tests

**Comment by NNRepos** [comment]
@RonnyPfannschmidt I see. I still don't think they answer my needs. I'll try to describe them again:
let's say I run a bash file which looks like this:
```
#!...
pytest tests -m "funny and heavy"
pytest tests -m "funny and light"
```
And I want something to run whenever I run heavy tests. 2 possible solutions would be:
1.
```
#!...
heavy_program --enable
pytest tests -m "funny and heavy"
heavy_program --disable
pytest tests -m "funny and light"
```

2.
```
#I'm conftest.py
parser.addoption("--heavy", action="store")
```
and
```
#!...
pytest tests -m "funny and heavy" --heavy
pytest tests -m "funny and light"
```

However, I think it would make more sense to check for markers:
```
#I'm conftest.py
def pytest_configure(config):
    if matchmark("heavy", config...markers):
        run_heavy_program()
```

Although it looks like matchmark expects an item and not a string. I guess the best solution would be to use eval() and MarkMapping themselves.

**Comment by RonnyPfannschmidt** [comment]
i believe something like this could work
```python
@pytest.fixture(scope="session")
def heavy():
    with heavy_enabled():
       yield



def pytest_item_collected(item): # from memory, please cross-check
    if item.get_closest_marker("heavy") is not None:
        item.applymarker(pytest.mark.usefixtures("heavy"))

```
i typed it from memory and didnt test, so crosschecking the api is a must

**Comment by NNRepos** [comment]
> i believe something like this could work
> 
> ```python
> @pytest.fixture(scope="session")
> def heavy():
>     with heavy_enabled():
>        yield
> 
> 
> 
> def pytest_item_collected(item): # from memory, please cross-check
>     if item.get_closest_marker("heavy") is not None:
>         item.applymarker(pytest.mark.usefixtures("heavy"))
> ```
> 
> i typed it from memory and didnt test, so crosschecking the api is a must

Thanks, could you explain what it does?
I can tell this is a conftest file, and that the item_collected hook runs every time an item is collected. However, I don't understand how would I use something like "heavy_enabled()" without adding another opt when calling pytest.
It looks a little like the 2nd solution I've proposed on my last comment, except it has to run for every item.
Also, does `get_closest_marker` use the `matchmark` method?

**Comment by RonnyPfannschmidt** [comment]
@NNRepos this code simly makes all "heavy" tests use the "heavy fixture

the heavy fixture is executed exactly once per pytest process

**Comment by NNRepos** [comment]
Hi Ronnie, I tried what you said (using pytest_itemcollected and item.add_marker, since applymarker is a fixture function and not an item function). the get_closest_marker part worked, but the fixture was not activated. I still think there should be some function that does this automatically, perhaps by generating an Item with given markers and evaluating whether it's going to run or not. Or maybe I'll just add another --opt. Thanks either way

**Comment by Zac-HD** [comment]
You could also use an environment variable?

```bash
#!...
HEAVY=1 pytest tests -m "funny and heavy"
pytest tests -m "funny and light"
```

```python
#I'm conftest.py
def pytest_configure(config):
    if "HEAVY" in os.environ:
        run_heavy_program()
```

**Comment by ncoghlan** [comment]
> > i typed (_the hook name_) from memory and didnt test, so crosschecking the api is a must

I have a similar requirement to the OP (ensuring an expensive resource is available only if at least one test case that needs that resource is selected for execution), and the cross-checked hook name is [`pytest_itemcollected`](https://docs.pytest.org/en/stable/reference/reference.html#pytest.hookspec.pytest_itemcollected) (only the first underscore, not the second)

```python
def pytest_itemcollected(item): # Amended to match the documented hook name
    if item.get_closest_marker("heavy") is not None:
        item.applymarker(pytest.mark.usefixtures("heavy"))
```
