### ISSUE TITLE
config: ini: should allow for `default=None` - currently returns `[]` then

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6117]
Will create a PR, but can use this then for a changelog.

**Comment by RonnyPfannschmidt** [comment]
You can also use the pr ID for the change log

**Comment by blueyed** [comment]
..which is not known upfront typically.

**Comment by RonnyPfannschmidt** [comment]
I fail to see how that is a problem with git

**Comment by blueyed** [comment]
I usually force-push later, yes, if that's what you mean - but here I was certain to have a PR without failing tests, and did not want to trigger CI (I cannot cancel Azure).
Anyway...

I'd be more interested on your opinion with regard to API changes, since `default=None` (the current default) gets you an empty list.  I could also use `default=unset` explicitly for my use case - that would prevent API changes.

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell its intentional and was added about a decade ago that way
so changing it would be a major breaking change

i haven't investigated the deeper details of this one, and i don't think i can in near future as it will require a proper history lesson spanning about 12-14 years of pytest config evolution

**Comment by blueyed** [comment]
I think it is just an oversight: for getoption it was done in https://github.com/pytest-dev/pytest/commit/0365e5c3a0cf62cdf9328131ea05f7557f969d9e.

**Comment by RonnyPfannschmidt** [comment]
hmm, im inclined to agree, im notsure how to best assess impact,

**Comment by blueyed** [comment]
Will consider it with https://github.com/pytest-dev/pytest/pull/5968 again (code ref: https://github.com/pytest-dev/pytest/pull/6118/files#diff-b80bb977f96695d5bfe21ddd2680c4efR993).
AFAICS it should handle different type better anyway, and this could keep the old behavior then maybe, checking if "default" is passed as an arg or not etc.

**Comment by blueyed** [comment]
Found something that changed in this regard: with https://github.com/pytest-dev/pytest/pull/4521/files#diff-b80bb977f96695d5bfe21ddd2680c4efR357 I was using `default=notset` myself (likely since `None` did not work), which then resulted in an empty list with https://github.com/pytest-dev/pytest/pull/6118.
Since others might have used the same workaround I think we should check if it was provided in kwargs actually to see if it should be considered to have been set/given, or not.
