### ISSUE TITLE
How to access captured stdout during collection?

### ISSUE THREAD

**Issue by finefoot** [pytest-dev/pytest#6123]
```python
print("example") # Exemplary stdout
# I want to access the captured stdout at this point
1/0 # Exemplary error during collection
```

Will result in:

```
$ python3 -m pytest test.py 
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /home/user/Documents
collected 0 items / 1 errors                                                   

==================================== ERRORS ====================================
___________________________ ERROR collecting test.py ___________________________
test.py:2: in <module>
    1/0
E   ZeroDivisionError: division by zero
------------------------------- Captured stdout --------------------------------
example
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.07 seconds ============================
```

Inside a test function, there is `capsys`, but how can I access the captured stdout in this case? It has to be stored in some object, right?

**Comment by RonnyPfannschmidt** [comment]
please outline the actual use-case you need this for

**Comment by finefoot** [comment]
Hey, thanks for getting back to me :) In my case, during collection, stdout is filled with a lot of useless (in parts even sensitive) information which I want to filter (I don't want to disable stdout capture completely) before attempting a step which might result in an error and therefore printing the captured stdout.

**Comment by MarcoGorelli** [comment]
Not sure I've understood the question. You want to attempt a step, and print the stdout if there's an error?

If you have a function like the one you've defined
```
def print_something():
    print("example")  # Exemplary stdout
    # I want to access the captured stdout at this point
    1 / 0  # Exemplary error during collection
```
then you can access the stdout ('example') in your test function as follows:
```
def test_print_something(capsys):
    try:
        print_something()
    except ZeroDivisionError:
        stdout, stderr = capsys.readouterr()
    assert stdout == "example"
```

**Comment by finefoot** [comment]
Thanks for the reply :) Yes, that's exactly how I would do it, if I wanted to access the captured output from a test function. In my case, however, the stdout in question is being produced (and the error happens) during collection.

**Comment by Zac-HD** [comment]
> In my case, however, the stdout in question is being produced (and the error happens) during collection.

I think the only useful advice we can give is "try not to do that".  If it's setup logic, can you move it inside the test or use a decorator factory?

**Comment by finefoot** [comment]
Hmm, can I modify `terminalreporter` from a `pytest_terminal_summary` hook? :thinking:

**Comment by finefoot** [comment]
>  If it's setup logic, can you move it inside the test or use a decorator factory?

@Zac-HD Oh, sorry, I didn't answer this. The error might happen during an `import` statement, for example. So I'd have to put `import` into each test function.

Regarding decorator factory: I'm not sure what you mean. See [my previous comment](https://github.com/pytest-dev/pytest/issues/6123#issuecomment-557961858):

> Hmm, can I modify `terminalreporter` from a `pytest_terminal_summary` hook? :thinking:

**Comment by Zac-HD** [comment]
`@pytest.mark.xfail` - decorator.  `@pytest.mark.parametrize(...)` - decorator factory; you get the decorator by calling a function.  (most people call these "decorators" too, but sometimes it's useful to distinguish)

**Comment by finefoot** [comment]
Thank you for the reply. :) I'm sorry for my badly worded question. I'm aware of the distinction between decorator and decorator factory. What I don't know is how I could use it to help in my situation?

The only thing in relation to output of captured stdout I could find is the `pytest_terminal_summary` hook.
