### ISSUE TITLE
pytest.mark.filterwarnings ignore applies to all subsequent tests on Py2

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#6126]
https://travis-ci.org/graingert/pyt-warnings/builds/605948138

here's the example code:
https://github.com/graingert/pyt-warnings/blob/6f5bcdc4cdc957ae6ce1deb1c69692acd50726e9/tests/test_foo.py#L1-L21

**Comment by graingert** [comment]
I suspect this is a py2 bug/misfeature that won't be going away. If we can't work around it in pytest we should document how to.

Using https://github.com/graingert/pyt-warnings/pull/1 appears to do the right thing (except now I get a warnings summary)

**Comment by graingert** [comment]
@RonnyPfannschmidt I think warnings in pytest may need an overhaul, I currently use "filterwarnings = error" in my `pytest.ini`

I think a better approach would be to use `filterwarnings = always` in pytest.ini and then have an option fail tests that log to recwarn and an associated "pytest.mark.xwarns" mark

**Comment by RonnyPfannschmidt** [comment]
@graingert the issue you linked is a python2 only issue fixed in https://github.com/python/cpython/blob/master/Lib/warnings.py#L341

however in https://github.com/python/cpython/blob/2.7/Lib/warnings.py its not fixed

**Comment by graingert** [comment]
@RonnyPfannschmidt My warn_explicit is overridden by c code https://github.com/python/cpython/blob/master/Lib/warnings.py#L523

**Comment by graingert** [comment]
> https://bugs.python.org/issue4180

**Comment by graingert** [comment]
@RonnyPfannschmidt adding this fixture appears to work around this issue

```
import pytest

import sys

@pytest.fixture(autouse=True)
def _clear_warning_registry():
    for module in sys.modules.values():
        try:
            del module.__warningregistry__
        except AttributeError:
            pass
```

**Comment by RonnyPfannschmidt** [comment]
@graingert i believe this could make a addition to the warning catching utilities in pytest on the python 2.7 branch (perhaps tightly integrated with the test contexts we already have in use

**Comment by asottile** [comment]
`recwarn` at least already [tries to handle this](https://github.com/pytest-dev/pytest/blob/3edf417969299af80c72dfa02dcfcf22a8fb6391/src/_pytest/recwarn.py#L175-L185) but I agree that fixing this for `filterwarnings` would probably be too much of a change to backport

it might be possible to use `recwarn` + warnings filters directly as an alternate documented workaround

**Comment by graingert** [comment]
> but I agree that fixing this for filterwarnings would probably be too much of a change to backport

You wouldn't have to backport it - the problem only applies for `pytest~=4.0`

**Comment by asottile** [comment]
> > but I agree that fixing this for filterwarnings would probably be too much of a change to backport
> 
> You wouldn't have to backport it - the problem only applies for `pytest~=4.0`

that's precisely what I mean -- 4.x is feature frozen

**Comment by graingert** [comment]
Imho this is a bug, and I'm enabling and warnings as errors with filterwarnings to focus specific tests in order to aid with porting a codebase to Py3

**Comment by asottile** [comment]
I disagree, backporting the warning filter behaviour of python3 to python2 seems quite out of scope for maintenance-only branches

**Comment by RonnyPfannschmidt** [comment]
@graingert i think a 3rd  party package should hijack the warnings module and add registry resets 
im happy to add such a dependency to the python2 only branch, but im certainly not willing to create it myself, i suspect the core devs hold a similar position
