### ISSUE TITLE
overhaul approach to warnings

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#6128]
I think warnings in pytest may need an overhaul, I currently use `filterwarnings = error` in my `pytest.ini`

This doesn't work for me either because I have a large legacy code base with many structures like:

```python
def do_action1(opt):
    if opt == 1:
        warnings.warn("opt 1 is deprecated", Action1Warning)
    ...

def act():
    try:
        do_action1(1)
    except Exception:
        logger.exception("the bad thing happened")
        return
    do_action2()
```

I'd like to be able to remove any call to "do_action1" in existing tests and new code, and enabling `filterwarnings = error` causes `act()` to behave 'strangely' rather than emit a warning and fail the test because of that warning.

Also adding a single test to the code with "pytest.mark.filterwarnings" means new tests do not fail due to https://github.com/pytest-dev/pytest/issues/6126

I think a better approach would be to use `filterwarnings = always` in pytest.ini and then have an option fail tests that log to recwarn and an associated `pytest.mark.xwarns` mark

**Comment by asottile** [comment]
I don't think we should rework warnings as you're describing -- the current approach is consistent with the python `warnings` module

I'd argue that the `except Exception:` code is the bug (too-broad `except`)

that said, you can still have that and do exactly what you're suggesting, for example here's what `pre-commit` does: https://github.com/pre-commit/pre-commit/blob/0fd4a2ea38df4f276e43397e21ecb3fcbc96d122/tests/conftest.py#L26-L41

**Comment by graingert** [comment]
@asottile perhaps that fixture would do well in a built-in plugin along with a xwarns mark

**Comment by asottile** [comment]
:man_shrugging: I think the `filterwarnings = error` approach is better, I just haven't gotten around to changing that code since pytest changed how warnings

**Comment by Zac-HD** [comment]
I'm with @asottile in preferring the current behaviour; consistency with the wider ecosystem is a virtue `pytest` could use more of.  In particular I'd be very, very cautious about messing with warnings since test-time is the only place that users are likely to see e.g. DeprecationWarning!
