### ISSUE TITLE
tmp_path_factory not mentioned in changelog

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#6135]
When was it added? Maybe consider updating the changelog and/or documentation so someone using this feature might know what is the minimum version required to include it.

**Comment by The-Compiler** [comment]
It was added when `tmp_path` was added in 3.9.0 (which is mentioned in the changelog). The documentation for `tmp_path_factory` used to mention that, but given that it's more than two major releases ago, it was removed in 9c5da9c0d15ccf7ab9f3a8fbd6540e4a56ea789f.

**Comment by Zac-HD** [comment]
Let's just add a changelog entry then, so you can grep for it there if the date is important to you.

Tagged as "easy" because I think this would be a good first PR for a new contributor :smile:

**Comment by TH3CHARLie** [comment]
@Zac-HD I'd like to take it

**Comment by Zac-HD** [comment]
Go for it! Happy to review if you tag me in the PR 😁

**Comment by jaraco** [comment]
Thanks!
