### ISSUE TITLE
logging output in junitxml

### ISSUE THREAD

**Issue by kown7** [pytest-dev/pytest#6139]
This is the inverse of #2648.

To better evaluate the CI (Jenkins) results, it would be great to have the collected logging information available in the `results.xml`.

```python
    @pytest.mark.parametrize("count", range(5))
    def test_logging_to_xml(count):
        """Write report to XML -> warnings should be there too"""
        logging.info("This is just information")
        logging.warning("Something went sideways %i", count)
       assert False
```

I'd would like to see the captured log lines

```
INFO     root:tests_helper.py:52 This is just information
WARNING  root:tests_helper.py:53 Something went sideways 4
```

in my `results.xml` file.

**Comment by thisch** [comment]
There is already an ini variable that does what you want. It is called `junit-logging`.

You can pass it to pytest as an arg via e.g. `-o junit_logging=system-out`.

**Comment by kown7** [comment]
Thank you!

**Comment by abbas-tari** [comment]
Unfortunately this does not include logs within the JUnit xml report! Any alternative solutions?
