### ISSUE TITLE
Selecting multiple markers to run

### ISSUE THREAD

**Issue by larkolab** [pytest-dev/pytest#6142]
Hello,
Is there a way to give a list of markers to select the tests to be run ?

Something like:
`python -m pytest -vv -s tests/ -m "foo1 and foo2"`
or
`python -m pytest -vv -s tests/ -m "not foo1 and not foo2"`

Thanks and regards,
Michael

**Comment by Zac-HD** [comment]
`-m "foo1 or foo2 or foo3"` should work :smile:

**Comment by super6602** [comment]
does it support more complicated cases?
like "(a or b) and c"

**Comment by The-Compiler** [comment]
@super6602 Try it and see? But yes, it does.

**Comment by santkumar333** [comment]
Thanks all , It works
