### ISSUE TITLE
Symlinks break conftest.py imports in the doctest plugin

### ISSUE THREAD

**Issue by sitaktif** [pytest-dev/pytest#6146]
The `conftest.py` import logic in the doctest plugin doesn't handle some layouts that contain multiple levels of symlinks (such as when used with bazel).

When the doctest plugin is disabled, `pytest` runs fine but when I enable doctests with `--doctest-modules` I get the following error:

```
____________________ ERROR collecting test/rtm/conftest.py _____________________
../pypi__pytest__4_6_4/_pytest/config/__init__.py:440: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('/private/var/tmp/_bazel_sitatkif/715d015e3d448dfcaced93a8d1b1a5f5/execroot/__main__/bazel-out/darwin-fastbuild/bin/test/test.runfiles/__main__/test/rtm/conftest.py')

During handling of the above exception, another exception occurred:
../pypi__pytest__4_6_4/_pytest/runner.py:226: in from_call
    result = func()
../pypi__pytest__4_6_4/_pytest/runner.py:253: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
../pypi__pytest__4_6_4/_pytest/doctest.py:421: in collect
    module = self.config.pluginmanager._importconftest(self.fspath)
../pypi__pytest__4_6_4/_pytest/config/__init__.py:471: in _importconftest
    assert mod not in mods
E   AssertionError
```

Upon investigation, this is due to the fact that the mods dict contains the `realpath` of my `conftest.py` but the doctest plugin is trying to load it again using a symlinked path.

I noticed that core `pytest` uses the realpath to load the project's conftest.py module(s):

https://github.com/pytest-dev/pytest/blob/d3549df5b94137453b832345a9b8074f518731b0/src/_pytest/config/__init__.py#L424

...while the doctest plugin does not resolve the realpath:

https://github.com/pytest-dev/pytest/blob/d3549df5b94137453b832345a9b8074f518731b0/src/_pytest/doctest.py#L421

Changing the doctest line above with the code below solves the problem for me:

```python
module = self.config.pluginmanager._importconftest(self.fspath.realpath())
```

(note: the code on the master branch changed a bit but the behavior is the same. See https://github.com/pytest-dev/pytest/blob/85288b53218d4e0037dce9c34bd37f86fa9e212d/src/_pytest/config/__init__.py#L424-L432 for core and https://github.com/pytest-dev/pytest/blob/85288b53218d4e0037dce9c34bd37f86fa9e212d/src/_pytest/doctest.py#L414 for doctest).

**Comment by sitaktif** [comment]
I would open a PR but I'd first need to go through a long and tedious legal approval procress - given how short the change is I'm hoping that someone is happy to pick it up <3

**Comment by blueyed** [comment]
JFI: code in this regard changed in b48f51eb0.

**Comment by sitaktif** [comment]
@blueyed good catch, it seems that we should be calling `.realpath().resolve()` then.

**Comment by sitaktif** [comment]
Thanks I confirm that the issue is fixed.

**Comment by blueyed** [comment]
@sitaktif 
That's odd then - https://github.com/pytest-dev/pytest/pull/6155 was not merged yet, and I've only closed this accidentally.  Leaving it closed for now.
/cc @JonathanGrant

**Comment by sitaktif** [comment]
@blueyed that's my bad: when I opened the ticket I was using an older version of pytest (4.6.4) - which btw explains [this comment](https://github.com/pytest-dev/pytest/issues/6146#issuecomment-551960609) of yours. Version 5.1.2 happens to be working, at least for my use case (not sure whether that's *thanks* to b48f51e or not).

So in the end I think this issue should be closed.
