### ISSUE TITLE
pytest.raises documention doesn't state upfront that 'match' is keyword only

### ISSUE THREAD

**Issue by brettcannon** [pytest-dev/pytest#6158]
Reading http://pytest.org/en/latest/reference.html#pytest-raises I thought the 'match' argument supporting positional specificity due to it being listed as `[, match]` in the parameter list and the argument specification not saying anything about it. But if you read a bit farther down you notice that it's mentioned it's keyword-only.

My suspicion is there's no way to change the syntax of that parameter list to use `*,` to make it clearer that `match` is positional-only? Otherwise I'm happy to write a PR to state that in its parameter documentation.

**Comment by Zac-HD** [comment]
https://github.com/pytest-dev/pytest/blob/master/doc/en/reference.rst#pytest-raises

Looks like the signature is specified in our docs file, so it should be pretty easy to fix!

**Comment by NNRepos** [comment]
@Zac-HD, do you think changing `[, match]` to `, [match]` is clear enough? If so, where can it be changed? Could you type the path to the directory from which http://pytest.org/en/latest/reference.html#pytest-raises is edited? Thanks

**Comment by Zac-HD** [comment]
@NNRepos - I think `[, *, match]` would be clearer, using Python 3's syntax for keyword-only arguments.  The file is `doc/en/reference.rst`.  Hope that helps :smile:

**Comment by brettcannon** [comment]
@Zac-HD created #6173 to implement your suggestion.
