### ISSUE TITLE
monkeypatch.delenv: unset with value=None

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6162]
This would make it more usable in parametrized tests.
It would call `monkeypatch.delenv(…, raising=False)` then.

ref: https://github.com/blueyed/pytest/commit/e2bd8cec4d9c6de3dc90c296ee948bd95c9099d1#diff-1f034a0f101912ca729b09e39a3973bb

**Comment by RonnyPfannschmidt** [comment]
this convenience would also hide programming errors i believe

 i'd rather have a explicit name for set or delete so the operational contract is clear

my peeve here is about naming/semantics, the actual combined functionality should be exposed using a new name

**Comment by blueyed** [comment]
What about a new kwarg `unset_for_none`, defaulting to `None`, and which would get passed through as `raising` then if non-None?
(I'd rather not have a new method just for this (`delorunsetenv` ?).

**Comment by RonnyPfannschmidt** [comment]
a well named kwarg would work too
my personal preference would be a well named method that  encapsulates the new behaviour in its name (following SOLID and detaching the responsiblities)

**Comment by erheron** [comment]
Hi! I would like to work on this. I will try to implement using new method as @RonnyPfannschmidt  was suggesting. Do You have any thoughts which might be useful for me?

**Comment by RonnyPfannschmidt** [comment]
@erheron i don't have any beginning thoughts on that one.

I believe for the particular use-case a test-frist approach could be a fun exercise
first writing down the invocations/calls one wants to work , then making sure they do.

before you start i'd like another of the maintainers to chime in on the implementation form as i'm not under the impression that the communication between me and @blueyed has reached a conclusion

perhaps @nicoddemus can chime in.

I believe once you have a rough implementation we can take a look at the details and guide towards a successfully pr.
