### ISSUE TITLE
PytestAssertRewriteWarning: asserting the value None, please use "assert is None"

### ISSUE THREAD

**Issue by KrishnaKantPrajapat** [pytest-dev/pytest#6203]
Here is the minimal demo that is working fine on local machine but showing warning while submitting for a handson
```
<body>
  <video width="320" height="200" controls preload="none" poster="https://cdn12.picryl.com/photo/2016/12/31/lego-stones-plastic-education-8b9a7d-1024.jpg">
    <source src="video.mp4" type="video/mp4">
</video>

<video width="320" height="200" controls preload="none" poster="https://cdn12.picryl.com/photo/2016/12/31/lego-stones-plastic-education-8b9a7d-1024.jpg">
    <source src="video.mp4" type="video/mp4">
</video>

<video width="320" height="200" controls preload="none" poster="https://cdn12.picryl.com/photo/2016/12/31/lego-stones-plastic-education-8b9a7d-1024.jpg">
    <source src="video.mp4" type="video/mp4">
</video>

</body>
```
And here is the warning message
```
test/test_webpage.py::TestWebpage::test_indexpage

  /projects/challenge/test/test_webpage.py:28: PytestAssertRewriteWarning: asserting the value None, please use "assert is None"

    assert self._index.find('video', {'controls': '', 'preload': ''})

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
For below tests
```
assert self._index.find('video', {'autoplay': ''})
        assert self._index.find('video', {'controls': '', 'preload': ''})
        assert self._index.find('video', {'poster': 'https://cdn12.picryl.com/photo/2016/12/31/lego-stones-plastic-education-8b9a7d-1024.jpg'})
```

**Comment by bluetech** [comment]
The warning is intentional. It suggests to you to change your assertions as follows:

```py
assert self._index.find('video', {'autoplay': ''}) is not None
assert self._index.find('video', {'controls': '', 'preload': ''}) is not None
assert self._index.find('video', {'poster': 'https://cdn12.picryl.com/photo/2016/12/31/lego-stones-plastic-education-8b9a7d-1024.jpg'}) is not None
```

You can see issue #3191 for the rationale for the warning. Let us know if this isn't clear enough.

**Comment by Vaish-09** [comment]
@bluetech Still after giving autoplay="autoplay" in my video tag, I get the below error:
test/test_webpage.py::TestWebpage::test_indexpage

  /projects/challenge/test/test_webpage.py:27: PytestAssertRewriteWarning: asserting the value None, please use "assert is None"

    assert self._index.find('video', {'autoplay': ''})

Can you please help me out?

**Comment by bluetech** [comment]
Change it to the following:

```py
assert self._index.find('video', {'autoplay': ''}) is not None
```

**Comment by nagulapatigirireddy** [comment]
Hi , I am having same issue. Please help with what changes to be made for below code?

`<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="favicon.png" type="image/png">
    <title>Destiny</title>
    <link href="mystyle.css" rel="stylesheet" type="text/css">
  </head>
  <body>
    <video width="320" height="200" autoplay loop controls preload="none"
      poster="https://cdn12.picryl.com/photo/2016/12/31/lego-stones-plastic-education-8b9a7d-1024.jpg">
      <source src="video.mp4" type="video/mp4" />
    </video>
    <video width="320" height="200" autoplay loop controls preload="none"
      poster="https://cdn12.picryl.com/photo/2016/12/31/lego-stones-plastic-education-8b9a7d-1024.jpg">
      <source src="video.mp4" type="video/mp4" />
    </video>
    <video width="320" height="200" autoplay loop controls preload="none"
      poster="https://cdn12.picryl.com/photo/2016/12/31/lego-stones-plastic-education-8b9a7d-1024.jpg">
      <source src="video.mp4" type="video/mp4" />
    </video>
  </body>
</html>`

**Comment by nicoddemus** [comment]
@nagulapatigirireddy,

You did not post any code, but the change is simple. It means you have this:

```python
assert <expr>
``` 

You just need to change it to:

```python
assert <expr> is not None
```
