### ISSUE TITLE
testdir: use existing monkeypatch fixture?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6213]
Do you want this?
https://github.com/blueyed/pytest/commit/b23b0df80e8c100c7a9084002052e4029f407485#diff-1284161c2c98c8aedd66545ff79a8af6R497

Needs to be decided for https://github.com/pytest-dev/pytest/pull/6164.

**Comment by nicoddemus** [comment]
I'm fine with that change, except perhaps it should receive `monkeypatch` by argument (like done for `request` and `tmpdir_factory`) instead of using `getfixturevalue`.

**Comment by blueyed** [comment]
Fixed.
