### ISSUE TITLE
Get the execution result of pytest

### ISSUE THREAD

**Issue by hanchenxu** [pytest-dev/pytest#6217]
How can I get the execution results of pytest each time? I need to use the execution results for continuous integration (not Jenkins).

**Comment by hanchenxu** [comment]
Hi @nicoddemus ,

Thanks for your reply.

In my project, the test results currently running with pytest are all independent.

I want to get the execution result of pytest and store it in my MySQL database.

My web page can query the data in the database, and display the results of ten consecutive execution of my test case.

**Comment by The-Compiler** [comment]
Like @nicoddemus mentioned, you could use the XUnit XML file. Other options:

- [pytest-json](https://github.com/mattcl/pytest-json)
- [pytest-html](https://github.com/pytest-dev/pytest-html/) (if you're going to display it on a website anyways)
- [pytest-reportlog](https://github.com/pytest-dev/pytest-reportlog) (JSON as well)
- Writing your own custom [reporting plugin](https://docs.pytest.org/en/latest/writing_plugins.html)

I'm closing this now as I think this answers your question, but let us know if you need more help!
