### ISSUE TITLE
Cannot use existing logging setups with pytest?

### ISSUE THREAD

**Issue by markmelvin** [pytest-dev/pytest#6229]
Hi There,

I am trying to use an existing system with pytest that configures various levels of logging, including some logging.FileHandlers.  I simply cannot figure out what pytest is doing to logging behind the scenes.  It seems that any logging I have configured is blown away entirely, including the FileHandlers so nothing is ever logged (except into pytest's console).

I'm currently configuring Python logging with logging.config.dictConfig(mydict) before running pytest with pytest.main().  Since I have multi-layered logging that uses Python's logging subsystem to create logfiles as part of a run, is there any hope of getting this working with pytest?

Thanks,
Mark

**Comment by The-Compiler** [comment]
Does something about that change if you run pytest with `-p no:logging`?

**Comment by RonnyPfannschmidt** [comment]
i had a similar case at work and we would disable pytest logging integration until we integrated the application logging with the pytest logging

**Comment by markmelvin** [comment]
> Does something about that change if you run pytest with `-p no:logging`?

This appears to have no effect.

**Comment by The-Compiler** [comment]
Then I'm not sure what's going on. With that option, I don't think pytest touches logging in any way at all. Are you sure your logging initialization is in fact run correctly?

**Comment by markmelvin** [comment]
I'm fairly certain. I can run an identical test without pytest and everything works fine. I'll triple-check and try to come up with an example.

**Comment by Zac-HD** [comment]
Closing this for now - please feel free to reopen if we can find a reproducing example!
