### ISSUE TITLE
Suggestion: reset sys.last_traceback using `del` rather than setting to `None`

### ISSUE THREAD

**Issue by mdickinson** [pytest-dev/pytest#6255]
PR #3384 introduced code that resets `sys.last_traceback` and friends by assigning `None` to them: https://github.com/pytest-dev/pytest/blob/7e10c8191d0a6b8e2a0047947ededc232d02cd06/src/_pytest/runner.py#L124

The normal CPython behaviour here is that once the exception has been cleared, the attributes are `del`eted rather than set to `None`. Could I suggest updating this line of code to delete the attributes?

For context: the `None`s caused test failures in another project when we attempted to switch from `unittest discover` to `pytest` as our test runner; we had a test for some complex code that was messing with various `sys` attributes including the `sys.last_*` attributes, and the test verified that those attributes were unchanged by the code under test.

**Comment by nicoddemus** [comment]
Hi @mdickinson,

Definitely sounds reasonable, thanks.

**Comment by nicoddemus** [comment]
@mdickinson would you like to open a PR? Should be a simple change and there's already a test in place which just needs to be updated, `test_store_except_info_on_error`.

**Comment by mdickinson** [comment]
@nicoddemus Done! #6256

**Comment by RonnyPfannschmidt** [comment]
i just checked the python docs, and as far as i can tell we would be more in line with the setup python expects if this is implemented
