### ISSUE TITLE
Old pattern of checking exception text restored in pytest 5.3?

### ISSUE THREAD

**Issue by standage** [pytest-dev/pytest#6260]
Back in the day I used to check for text in my exceptions using the following pattern.

```python
with pytest.raises(ValueError) as ve:
    do_something_incredibly_stupid(like_really_stupid)
assert 'Expected text' in str(ve)
```

When pytest 5.0 came out, I updating the tests for some of my projects to use the new `match` pattern.

```python
with pytest.raises(ValueError, match=r'Expected text'):
    do_something_incredibly_stupid(like_really_stupid)
```

Today I revisited some old tests that hadn't been updated to the new pattern. The tests fail on pytest 5.2.4, but they pass on pytest 5.3.0 (Python 3.5). Has support for the old pattern been intentionally restored? Can/should I rely on this support, or should I continue updating my tests to the new pattern?

- [x] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by nicoddemus** [comment]
Hi @standage,

The old behavior is still not supported, probably your tests are matching by accident:

```python
import pytest

def test():

    with pytest.raises(ValueError) as ve:
        raise ValueError('Expected text here')
    assert 'Expected text' in str(ve)
    assert 0, str(ve)

``` 

```
_______________________________ test ________________________________

    def test():

        with pytest.raises(ValueError) as ve:
            raise ValueError('Expected text here')
        assert 'Expected text' in str(ve)
>       assert 0, str(ve)
E       AssertionError: <ExceptionInfo ValueError('Expected text here',) tblen=1>
E       assert 0

.tmp\test_exc.py:8: AssertionError
========================= 1 failed in 0.06s =========================
```

So `str(e)` previously would be `"Expected text here"`, but in 5.2 we changed it to be `"<ExceptionInfo ValueError('Expected text here',) tblen=1>"` to avoid confusion. But using `in` still matches the new representation. 😁

**Comment by standage** [comment]
Good catch. Thanks!
