### ISSUE TITLE
pytest output format

### ISSUE THREAD

**Issue by nicola-lunghi** [pytest-dev/pytest#6262]
Hi,
there's a way to have pytest output with a custom output format?

I need a test output like

PASS: testname
FAIL: testname

with no progress bar/point/etc etc
to be parsed by our build system

 Thanks
Nick

**Comment by nicola-lunghi** [comment]
currently for python unit test we run

python3 -m test -v | sed -u \
-e '/\.\.\. ok/ s/^/PASS: /g' \
-e '/\.\.\. [ERROR|FAIL]/ s/^/FAIL: /g' \
-e '/\.\.\. skipped/ s/^/SKIP: /g' \
-e 's/ \.\.\. ok//g' \
-e 's/ \.\.\. ERROR//g' \
-e 's/ \.\.\. FAIL//g' \
-e 's/ \.\.\. skipped//g'

**Comment by RonnyPfannschmidt** [comment]
pytest-tap is a external plugin that supports a mode of operation like that, you can probably replicate its approach

**Comment by nicoddemus** [comment]
Complementing @RonnyPfannschmidt's answer, you can also try `pytest-reportlog` and translate its results into the output you need (should be trivial).

Alternatively take a look at the [pytest-reportlog source](https://github.com/pytest-dev/pytest-reportlog/blob/master/src/pytest_reportlog/plugin.py) and replicate it into your own `conftest.py` file.

Closing for now, feel free to follow up with further questions.
