### ISSUE TITLE
Avoid truncation when it makes the output longer

### ISSUE THREAD

**Issue by douglasbagnall** [pytest-dev/pytest#6267]
Pytest version 3.10.1, also seen on Ubuntu 19.04:

With `-v`, when the output of a failure is close to the truncation limit, verbosity is *increased*, and the extra words are not useful. In short, this:

```
$ py.test-3 -v | wc
     60     269    3287
$ py.test-3 -vv | wc
     59     272    3292
```
In addition the  truncation message is misleading in the number of truncated lines. With `-v`:

```
E       assert b'<!DOCTYPE H...cation.</p>\n' == b'{}'
E         At index 0 diff: 60 != 123
E         Left contains more items, first extra item: 68
E         Full diff:
E         + b'{}'
E         - (b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Inter'
E         -  b'nal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server en'
E         -  b'countered an internal error and was unable to complete your request.  Either'...
E         
E         ...Full output truncated (2 lines hidden), use '-vv' to show
```

With `-vv`:

```
E       assert b'<!DOCTYPE H...cation.</p>\n' == b'{}'
E         At index 0 diff: 60 != 123
E         Left contains more items, first extra item: 68
E         Full diff:
E         + b'{}'
E         - (b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Inter'
E         -  b'nal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server en'
E         -  b'countered an internal error and was unable to complete your request.  Either'
E         -  b' the server is overloaded or there is an error in the application.</p>\n')
```

That looks *one* extra line to me, not two. Possibly lines are counted by splitting on `\n`, and the message has a terminating `\n`, technically leaving an empty line at the end -- but this empty line is not shown in the `-vv` output.

it would be better for pytest to print the one line of error, rather than the two lines making an inaccurate claim about the truncation.

**Comment by douglasbagnall** [comment]
I'm thinking of something like this, though I haven't checked its effects on tests:

```
 src/_pytest/assertion/truncate.py | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/src/_pytest/assertion/truncate.py b/src/_pytest/assertion/truncate.py
index d97b05b44..47620e15c 100644
--- a/src/_pytest/assertion/truncate.py
+++ b/src/_pytest/assertion/truncate.py
@@ -48,8 +48,12 @@ def _truncate_explanation(input_lines, max_lines=None, max_chars=None):
         max_chars = DEFAULT_MAX_CHARS
 
     # Check if truncation required
+    #
+    # If the truncated string plus the truncation explanation is
+    # longer than the original, we might as well show the original.
+
     input_char_count = len("".join(input_lines))
-    if len(input_lines) <= max_lines and input_char_count <= max_chars:
+    if len(input_lines) <= max_lines + 3 and input_char_count <= max_chars:
         return input_lines
 
     # Truncate first to max_lines, and then truncate to max_chars if max_chars
```

**Comment by erheron** [comment]
@douglasbagnall, the problem isn't in '\n' at the end, rather in line 65 in https://github.com/pytest-dev/pytest/blob/622995a50130824da120e81f31a048ac38966d06/src/_pytest/assertion/truncate.py#L63-L70
So in your particular case if it's written "2 lines hidden" it really does mean "1 line hidden + last line was [maybe] truncated". Not sure why it's done that way. Maybe @RonnyPfannschmidt  can tell?
I'm going to do something similar to what You've suggesting, though.

**Comment by blueyed** [comment]
Just remembered this issue when being confused about a test having a different outcome when changing an explanation on top.  (https://github.com/pytest-dev/pytest/pull/6702)
Those should maybe not get counted in the first place.

I also think it should be line based only maybe, and/or have an increased max length, and/or rather truncate lines exceeding the "max line length" (80, but multiplied currently): it is not useful to have the last line becoming different (with regard to its end) when one of the previous lines was changed.  Code: https://github.com/blueyed/pytest/blob/0e153a0da560715a1db0f8def40772234ee57f3d/src/_pytest/assertion/truncate.py#L9-L10

**Comment by jedie** [comment]
> 
> https://github.com/pytest-dev/pytest/blob/0e153a0da560715a1db0f8def40772234ee57f3d/src/_pytest/assertion/truncate.py#L9-L10

Question: Is it possible to change these default in `pytest.ini` ?!?
