### ISSUE TITLE
Modified `sys.path` leaks into unrelated tests when using Python 3.8

### ISSUE THREAD

**Issue by aivarannamaa** [pytest-dev/pytest#6273]
Deep in the structure of my project there is [a resource file](https://github.com/thonny/thonny/blob/master/thonny/plugins/micropython/api_stubs/lcd160cr_test.py) (with *.py extension), which looks like a test file.

`pytest <name of the main project directory>` picks it up as test file and adds its directory to `sys.path`, but this caused no harm with Python 3.7

When running pytest with Python 3.8, this directory seems to remain in `sys.path` for (some?) other unrelated test(s) as well and this breaks the build.

I tested it with pytest 4.6.6, 4.6.5, 4.5.0 and 5.3.0 on Windows 10 and current Fedora Rawhide.

Here is the original discussion leading to this discovery: https://github.com/davidhalter/parso/issues/88

**Comment by asottile** [comment]
my guess at this (haven't had a chance to debug) is that python3.7 imported `hashlib` earlier than in python3.8 (as a side-effect of some other module -- they're always trying to optimize the minimal-modules game in cpython) and so you only see the effects of `sys.path` (but it's happening in both?)

**Comment by asottile** [comment]
yep -- this is just a matter of deferred imports, nothing really do with pytest I'm afraid:

```
=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
>       assert not sys.path
E       AssertionError: assert not ['/tmp/thonny', '/tmp/thonny/thonny/plugins/micropython/api_stubs', '/tmp/thonny/venv37/bin', '/tmp/thonny/venv37/lib/python37.zip', '/tmp/thonny/venv37/lib/python3.7', '/tmp/thonny/venv37/lib/python3.7/lib-dynload', ...]
E        +  where ['/tmp/thonny', '/tmp/thonny/thonny/plugins/micropython/api_stubs', '/tmp/thonny/venv37/bin', '/tmp/thonny/venv37/lib/python37.zip', '/tmp/thonny/venv37/lib/python3.7', '/tmp/thonny/venv37/lib/python3.7/lib-dynload', ...] = sys.path

thonny/test/test_sys_path.py:5: AssertionError
```

```
=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
>       assert not sys.path
E       AssertionError: assert not ['/tmp/thonny', '/tmp/thonny/thonny/plugins/micropython/api_stubs', '/tmp/thonny/venv38/bin', '/tmp/thonny/venv38/lib/python38.zip', '/tmp/thonny/venv38/lib/python3.8', '/tmp/thonny/venv38/lib/python3.8/lib-dynload', ...]
E        +  where ['/tmp/thonny', '/tmp/thonny/thonny/plugins/micropython/api_stubs', '/tmp/thonny/venv38/bin', '/tmp/thonny/venv38/lib/python38.zip', '/tmp/thonny/venv38/lib/python3.8', '/tmp/thonny/venv38/lib/python3.8/lib-dynload', ...] = sys.path

thonny/test/test_sys_path.py:5: AssertionError

```
