### ISSUE TITLE
@pytest.mark.focus

### ISSUE THREAD

**Issue by m4js7er** [pytest-dev/pytest#6276]
pytest vresion 5.3.0

I would like to have a feature where I can say "run only this test" from the source file without needing to open any other file or modify any command-line script.

A possible solution is to have a unique marker, e.g. `@pytest.mark.focus` that would allow me to achieve a similar effect to `-m MARKEXPR`, but with two changes:
- when no test is marked with it, then run all tests,
- don't need to specify it on the command line.

There are multiple use-cases where it would be beneficial:
- My specific use-case:
In my local development, when writing python code, I have a script running on my command line that watches file changes, and whenever a file is modified, the script automatically re-runs pytest. Having `@pytest.mark.focus` allows me to very quickly focus on a specific test: add decorator + hit save button. I don't have to look for `.sh` file, modify it...
- Another use case:
When the `pytest` command is wrapped in another script/tool, and it is not possible or hard to pass command-line options to `pytest`.

Possible implementation (by @godlygeek):
```python
import pytest

def pytest_collection_modifyitems(items):
    '''If any items are marked 'focus', run only those items.

    This hook is run automatically by pytest.
    '''
    # Find items with the 'focus' mark
    focused = [item for item in items if item.get_closest_marker("focus")]
    # If any have it, replace the full list of collected items with only them
    if focused:
        items[:] = focused

def pytest_configure(config):
    config.addinivalue_line(
        "markers", "focus: If any tests have this mark, run only those"
    )
```

Alternative implementation: add a command line option `--run-all-if-none-marked`, but with a better name.

I believe this feature seems simple and useful enough to be added to `pytest` directly and not to be a plugin.

**Comment by The-Compiler** [comment]
FWIW there's already the [pytest-only plugin](https://github.com/theY4Kman/pytest-only) which does that.

**Comment by m4js7er** [comment]
Oh, cool haven't seen that before.
I wonder if it was possible to merge it into core `pytest`?

**Comment by nicoddemus** [comment]
Perhaps, but installing the plugin seems simple enough?

**Comment by RonnyPfannschmidt** [comment]
@m4js7er the plugin was created as a response of not wanting to try this concept in core yet, its definitively going to be considered for inclusion at some point

**Comment by m4js7er** [comment]
@RonnyPfannschmidt thank you for clarification. I looked for this kind of information, before creating this ticket, but I have missed it.
Do you think it is worth to try this concept in core now? The [pytest-only plugin](https://github.com/theY4Kman/pytest-only) looks mature to me.

I will use the plugin for now and wait for it to be added to the core.
