### ISSUE TITLE
Expose _pytest.fixtures.FixtureLookupError

### ISSUE THREAD

**Issue by earonesty** [pytest-dev/pytest#6280]
I have a testing infrastructure that gets imported into other repos that implement a well-defined interface (`from parent.tests import *`).

Those repos can optionally define fixtures that may or not be available to the tests.   If not available, default fixtures are used, and/or tests are disabled.

Currently everything works fine, however I have to use the protected `_pytest.fixtures.FixtureLookupError` to catch exceptions while looking for optionally defined fixtures.

For me, ideally `pytest.FixtureLookupError` would be a top level, supported, feature.

**Comment by RonnyPfannschmidt** [comment]
@earonesty its a good idea, would you like to implement the pr?

**Comment by bluetech** [comment]
Fixed by #6285.
