### ISSUE TITLE
enhance pytest.xfail documentation

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#6289]
> Just out of curiosity: Why do I get to pytest.xfail() and pytest.fail() progammatically? 

`pytest.fail()` and `pytest.skip()` and `pytest.xfail()` are there for situations where you don't want to check for a condition at *module level*, which is when the condition is evaluated for marks. 

Consider:

```python
import slow_module_to_import
@pytest.mark.xfail(slow_module_to_import.very_slow_function(), reason="...")
def test_foo():
    ...
```

Vs:

```python
def test_foo():
    import slow_module_to_import
    if slow_module_to_import.very_slow_function():
        pytest.xfail(reason="...")
```

Performance is not the only reason too, sometimes your condition needs to access things which are not available at module import time (access a database, read a config file, etc.)

> Will that be deprecated in the future in favour of marking?

No plans at all.

_Originally posted by @nicoddemus in https://github.com/pytest-dev/pytest/issues/6288#issuecomment-559765982_

**Comment by graingert** [comment]
I think we should include the:

```python
def test_foo():
    import slow_module_to_import
    if slow_module_to_import.very_slow_function():
        pytest.xfail(reason="...")
```

example in the pytest.xfail reference material

**Comment by shankarj67** [comment]
Can I work on this issue?

**Comment by nicoddemus** [comment]
Sure, thanks!
