### ISSUE TITLE
Feature request: equivalent error formatting for operators.eq and ==

### ISSUE THREAD

**Issue by ivirshup** [pytest-dev/pytest#6291]
I will sometimes use `operators.eq` in my assertions for composability (e.g. `assert comp(val1, val2)`) or when comparing the results of long expressions. I would like it if the formatted error pytest showed me on failing tests was as nice as if I'd used `==`. That is, I would like the following two assertions to show equivalent errors:

```python
from operators import eq

assert a == b
assert eq(a, b)
```

Would this be possible?

**Comment by RonnyPfannschmidt** [comment]
it sounds  technically possible, however the implementation will be quite an adventure, as one would have to trace the objects used and pick belonging operators for function calls to those

**Comment by asottile** [comment]
I'm not sure this is possible in all cases without solving a halting problem

**Comment by asottile** [comment]
ugh shift+enter sends too quickly, let me elaborate

with `==` we know with certainty this is an equality operator so we can produce special parsing around it

with a name however it _could_ come from anywhere so it can't be determined statically what the name is (sure in the example it's pretty easy to see as a human that it _probably_ is (stdlib)operator.eq

but even in that case you could have:
- monkeypatched the `operator` module
- shadowed the `operator` module
- assigned `eq` elsewhere in the file
- etc.

and these are all hard problems to solve statically

**Comment by nicoddemus** [comment]
Thanks everyone for the posts.

I think we can conclude that this can't be easily implemented so we better close this. 😁

**Comment by RonnyPfannschmidt** [comment]
@asottile i don't think we have to account for elaborate breakage for the operator module - the idea would be to allow running operator equivalent calls in a way that would match  them to assertrepr compare hooks

**Comment by ivirshup** [comment]
I agree with @RonnyPfannschmidt here, I don't think cases around monkey patching should be considered since those also apply to `==`. I could override  `__eq__` to mean addition as easily as I could monkey patch `operator.eq`. As for knowing if `eq` has been defined elsewhere in the file, could the generated code just include a `func is operator.eq` check?

**Comment by asottile** [comment]
the assertion rewriting works at code parse time -- can't really know that `func is operator.eq` at that time

**Comment by ivirshup** [comment]
I was thinking the rewritten code could have a check like:

```python
if func is operator.eq:
    # The rewrite
else:
    # The original code
```
