### ISSUE TITLE
Confusing behavior with capsys and print partials

### ISSUE THREAD

**Issue by bhrutledge** [pytest-dev/pytest#6299]
I put up a repository with a description and tests of this behavior, including output from a failing test run: https://github.com/bhrutledge/capsys-print-partials.

In a function that can write to standard out or a file, I thought it would be elegant/clever to override `print` like so:

```python
def write_hello(file=sys.stdout):
    print = partial(builtins.print, file=file)

    print("Hello")


with open("hello.txt", "w") as file:
    write_hello(file)
```

This works as hoped. However, that broke my existing tests that use the `capsys` fixture:

```python
def test_write_hello(capsys):
    import hello

    captured = capsys.readouterr()
    assert captured.out == "Hello\n"
```

The captured output is empty at the time of the assertion. However, the report from pytest still shows a `Captured stdout call` with the expected content.

I'm using pytest 5.3.1 with Python 3.7.4 on macOS 10.15.1. Output from `pip list`:

```
Package            Version
------------------ -------
attrs              19.3.0 
importlib-metadata 1.0.0  
more-itertools     8.0.0  
packaging          19.2   
pip                19.1.1 
pluggy             0.13.1 
py                 1.8.0  
pyparsing          2.4.5  
pytest             5.3.1  
setuptools         41.0.1 
six                1.13.0 
wcwidth            0.1.7  
wheel              0.33.4 
zipp               0.6.0  
```

**Comment by Zac-HD** [comment]
This is just a matter of *when* the default value of your `file` argument is evaluated.  The following idiom will delay it until the actual call, allowing the `capsys` fixture to work:

````python
def write_hello(file=None):
    print = partial(builtins.print, file=sys.stdout if file is None else file)
    print("Hello")

**Comment by bhrutledge** [comment]
Thanks, @Zac-HD! That does the trick.

In the process of trying it out, I realized that my initial `write_hello` example wasn't written properly, resulting in a spurious failure. I've updated the issue description and example repo to be closer to what I *was* doing in my project.

**Comment by bhrutledge** [comment]
@Zac-HD If you're game (and it's totally cool if you're not), I don't why changing the `file` evaluation solved my `capsys` issue. Again, my initial code worked as expected; it was only `capsys` that wasn't working.

**Comment by Zac-HD** [comment]
It's because `capsys` works by changing *which file handle is `sys.stdout`*, while the default value of that `file` argument is "the file handle that was `sys.stdout` at the time that the function was defined".

Basically the same reason that you should never have a mutable default argument!

**Comment by bhrutledge** [comment]
Aha! Thank for you the explanation. I didn't think of `sys.stdout` as mutable, but I can how it is.
