### ISSUE TITLE
filterwarnings breaks grpc on py3

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#6314]
- [ ] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

This issue was briefly raised in grpc but then closed and locked https://github.com/grpc/grpc/issues/19745

**Comment by graingert** [comment]
@Alipipe do you still have your minimal repeatable example?

**Comment by Zac-HD** [comment]
```ini
[pytest]
filterwarnings =
    error
    ignore::UserWarning
```

This is going to be a problem regardless, because a warning is checked against each filter entry *in order* and the first match is applied.  So in this case everything will be `error`, including `UserWarning` which I presume was intended to be `ignore`d.  Perhaps we could add a warning for useless-filterwarnings-entry?

**Comment by graingert** [comment]
we could only repeat this on `pytest==5.0.1` when upgrading to `pytest==5.3.1` the issue is no longer apparent /cc @funkyhat

**Comment by graingert** [comment]
> ```ini
> [pytest]
> filterwarnings =
>     error
>     ignore::UserWarning
> ```
> 
> This is going to be a problem regardless, because a warning is checked against each filter entry _in order_ and the first match is applied. So in this case everything will be `error`, including `UserWarning` which I presume was intended to be `ignore`d. Perhaps we could add a warning for useless-filterwarnings-entry?

we had the problem with just:

```ini
[pytest]
filterwarnings =
    error
```

**Comment by graingert** [comment]
@lidizheng can you add a link to this issue on https://github.com/grpc/grpc/issues/19745 please? It's currently locked

**Comment by lidizheng** [comment]
@graingert Link added, thanks for fixing this behavior :)

**Comment by graingert** [comment]
> @graingert Link added, thanks for fixing this behavior :)

I don't know what actually fixed it :p

**Comment by graingert** [comment]
closing this issue as upgrading to `~=5.3` from `==5.0.1`fixed the issue for @funkyHat
