### ISSUE TITLE
Force a specific test to always run regardless of "-k"

### ISSUE THREAD

**Issue by yoelai** [pytest-dev/pytest#6317]
Hi,

I am trying to add a test to my pytest suite that will verify the python version that is used to run the test and fail and stop testing if the version is lower than 3.8. I'd like to get pytest to always run this test, regardless of any "-k" filtering done on the command line.

For reference, this is the actual test:

```python
@pytest.mark.tryfirst
def test_python_version():
    version = sys.version_info
    if version.major < 3:
        logging.error("python2 is not supported")
        pytest.exit("Stopped testing")
    elif version.minor < 8:
        logging.warning("Use python 3.8 or higher for best results")
```

I'm a bit new to pytest, but I couldn't find any marker that provides this functionality. Regardless of the specific aforementioned use case, it seems to me to be a pretty useful thing to have implemented, IMHO.

Asked this question in SO, with no responses: https://stackoverflow.com/questions/59094496/force-pytest-to-always-run-a-specific-test-regardless-of-k

Thanks.

**Comment by The-Compiler** [comment]
You could e.g. use an [autouse fixture](https://docs.pytest.org/en/latest/fixture.html#autouse-fixtures-xunit-setup-on-steroids) (with session scope), or something like the [pytest_configure hook](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_configure).

**Comment by yoelai** [comment]
> You could e.g. use an [autouse fixture](https://docs.pytest.org/en/latest/fixture.html#autouse-fixtures-xunit-setup-on-steroids) (with session scope), or something like the [pytest_configure hook](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_configure).

What if I want this python version check to appear as a failed test in the output pytest logs?

**Comment by nicoddemus** [comment]
> regardless of any "-k" filtering done on the command line.

Strange, why would you like to bypass the filtering for a specific test?

Can you perhaps describe your use case in more detail? We might be able to provide a better solution then.

**Comment by yoelai** [comment]
> > regardless of any "-k" filtering done on the command line.
> 
> Strange, why would you like to bypass the filtering for a specific test?
> 
> Can you perhaps describe your use case in more detail? We might be able to provide a better solution then.

As I mentioned earlier, one use case I am currently trying to get implemented is a python version test. I am building a test environment and I'd like to ensure it is running on python 3 and stop testing if it is running on python 2.
I am trying to get this done as an actual pytest test, so that it shows up as a failed test or a successful test as the first result of the test run in all the logs I am generating.
Naturally, this test must run first every time pytest is invoked, regardless of any filtering done on the command line.

I can do this in a fixture with autouse, true, or in pytest_configure, as mentioned by @The-Compiler , but it just seems to me to be more elegant to have this be an actual test. Feel free to correct me if I am maybe misguided here, or if it does not seem like a very useful feature, in which case I'd still like to explore how to do this myself.

**Comment by nicoddemus** [comment]
I see thanks.

> Feel free to correct me if I am maybe misguided here

I'm not sure about misguided, but I think it should be enough to have this failing the entire test session during `pytest_configure`, not the responsibility of a single test.

**Comment by Zac-HD** [comment]
Closing this issue because I think the question has been answered: the consensus is to use a hook or fixure rather than a test for such code.
