### ISSUE TITLE
Parametrize fails resolve argument ids for classes with no __name__

### ISSUE THREAD

**Issue by volcan01010** [pytest-dev/pytest#6321]
### Summary

Pytest crashes when attempting to parameterize tests if the parameterized values include classes for which `__name__` attribute is not present.

### Example

A minimal example to recreate is:

```python
import pytest


class MyClass(dict):
    a = "hello"

    def __getattr__(self, item):
        return self[item]


@pytest.mark.parametrize('custom_class', [MyClass(), MyClass()])
def test_my_class(custom_class):
    assert custom_class.a == "hello"
```

This gives the following output:

```
==================================================== test session starts =====================================================
platform linux -- Python 3.7.3, pytest-5.3.1, py-1.8.0, pluggy-0.13.0 -- /home/jostev/.virtualenvs/etlhelper/bin/python
cachedir: .pytest_cache
rootdir: /home/jostev/github/etlhelper, inifile: pytest.ini
plugins: cov-2.7.1
collected 0 items / 1 error                                                                                                  

=========================================================== ERRORS ===========================================================
________________________________________ ERROR collecting test/unit/broken_pytest.py _________________________________________
test/unit/broken_pytest.py:8: in __getattr__
    return self[item]
E   KeyError: '__name__'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================== 1 error in 0.18s ======================================================
```

My version information is included above.  This behaviour was not present in `pytest-4.3.1`.

### Potential fix

The error occurs when parametrize is creating an id for the class:
https://github.com/pytest-dev/pytest/blob/1c0ab3c2a32f7932378a1c37106d082784cb4700/src/_pytest/python.py#L1169

Replacing this line with

```python
    elif hasattr(val, "__name__"):
        if isinstance(val.__name__, str):
```

should be a fix.  With this update, pytest would only try to access `val.__name__` if it exists.

### Postscript

If you are wondering how I ended up with a class with no `__name__`, this is how:  https://amir.rachum.com/blog/2016/10/05/python-dynamic-attributes/

**Comment by The-Compiler** [comment]
This is a bug in your code - `__getattr__` is supposed to raise `AttributeError` (not `KeyError`) when an attribute doesn't exist.

Your potential fix is equivalent to the existing code - if the left-hand side of an `and` is false, the right-hand side never gets executed. It's the `hasattr` itself which raises an exception, which you can see by doing:

```python
 c = MyClass()
print(hasattr(c, 'bla'))
```

**Comment by volcan01010** [comment]
Ah, OK.  Thanks.  I'll update my class to throw the correct exception.
