### ISSUE TITLE
Dynamically generate fixtures (again)

### ISSUE THREAD

**Issue by Seeefo** [pytest-dev/pytest#6322]
Suggestion/Question:

I am trying to generate dynamic fixtures based on another class that does dependency injection similar to pytest. The dependencies are represented as a dict, which I am hoping to just generate identically named fixtures to make those accessible in test code without having a lot of boilerplate code. I found https://github.com/pytest-dev/pytest/issues/2424#issuecomment-376012022 and this works fine for any of the test functions I write, but doesn't work if another _fixture_ has a dependency on one of these "autogenerated" fixtures.

Any advice on how I can expand the above link to support both test cases and fixtures?

**Comment by Zac-HD** [comment]
Closing this as inactive - maybe try StackOverflow?  Sorry we couldn't help :confused:

**Comment by Seeefo** [comment]
Sorry, forgot to come back and update this. I figured it out:

```
@pytest.fixture(autouse=True, scope="session")
def inject_service_fixtures(request):
    try:
        service = request.getfixturevalue("service")
    except FixtureLookupError:
        logger.exception(
            "Service fixture not defined!"
        )
    else:
        our_fixtures = {}
        for name in service.registrations():
            func = partial(getattr, service, name)
            func.__name__ = name
            f = FixtureDef(request._fixturemanager, "", name, func, "function", None)
            our_fixtures[name] = [f]
        request._fixturemanager._arg2fixturedefs.update(our_fixtures)
```

"service" is the name of our dependency injection object and also has to be a fixture (at session scope).  Not ideal I guess, hate to really dig into the internals there, but its definitely been helpful so far.
