### ISSUE TITLE
Allow pytest.raises to accept sequence of str/Pattern for match argument

### ISSUE THREAD

**Issue by stevecj** [pytest-dev/pytest#6331]
Since it is complicated to write a regular expression that matches a combination of character sequences in arbitrary order, it would be nice to be able to pass a sequence of values to the `match` argument and have the assertion pass only if all of the expressions match.

```python
with pytest.raises(AttributeError, match=(r'leading|first', r'dash')):
    my_function('-badvalue')
```

**Comment by stevecj** [comment]
I know this can be roughly accomplished by using the `match` method of `ExceptionInfo`, BTW. It would be nice to have this as a shortcut though.

**Comment by Zac-HD** [comment]
I can see that this would be a useful feature, but I'm concerned that many people would interpret it as *any* match, not *all* matches - the former would match `isinstance` and many other common functions.

**Comment by asottile** [comment]
imo there should be one obvious way to do it, having both apis seems not great (when `.match(...)` already does what you're looking for)
