### ISSUE TITLE
Using '-r Ff' will output failed tests twice

### ISSUE THREAD

**Issue by Matlino** [pytest-dev/pytest#6334]
This is related to #5110 . -r F option is not documented but will create same output to short summary info as -r f. Problem is when user use both of them:

```
def test_1():
    assert False
```

pytest -r Fe
```
======================================================================= short test summary info ========================================================================
FAILED test_a.py::test_1 - assert False
FAILED test_a.py::test_1 - assert False
```

I teste on 5.3.1, master and also features.

**Comment by nicoddemus** [comment]
Thanks @Matlino, will be released in 5.4. 👍
