### ISSUE TITLE
how can I properly tell pytest to exit with a specific exit code?

### ISSUE THREAD

**Issue by NNRepos** [pytest-dev/pytest#6344]
question:
Hi,
I'm using python2 and TeamCity (CI framework).
TeamCity expects an exit code of 1 upon failure.
If I try sending sys.exit(1) from conftest.py, pytest catches it and generates an exit code of 0.
I've heard of the "pytest-custom-exit-code" plugin, but there's no documentation whatsoever and I don't know if it fits me in any way.

TL;DR
how do I make pytest exit with exit code 1 with a single command?
and, could we perhaps change the documentation to make this more obvious?
Thanks

**Comment by nicoddemus** [comment]
Hi @NNRepos,

Try [pytest.exit()](https://docs.pytest.org/en/latest/reference.html#pytest-exit). 

I don't think we need to change the docs though, a search for `exit` in the reference page quickly shows this. 

Closing this for now, but feel free to follow up with more questions.

**Comment by NNRepos** [comment]
@nicoddemus, couldn't find it in the docs, but it works, so thank you.

**Comment by NNRepos** [comment]
@nicoddemus Hi again, for some reason pytest.exit("", returncode=X) always gives errorcode 1. Am I using it wrong?

**Comment by nicoddemus** [comment]
Hi @NNRepos,

Weird, it works for me:

```python
import pytest

def test_exit():
    pytest.exit('hello', returncode=10)
```

```
λ pytest .tmp\test_exit.py -q

no tests ran in 0.15s
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: hello !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

λ echo %errorlevel%
10
```
