### ISSUE TITLE
#5990 breaks pytester

### ISSUE THREAD

**Issue by aragilar** [pytest-dev/pytest#6352]
It looks like #5990 broke pytester, by changing "error" to "errors". 

MWE follows (use `pytest -p pytester test_fail.py` to run the code below)

```python
CODE = """
    import pytest

    @pytest.fixture
    def bad_fixture():
        raise Exception("bad")

    def test_error1(bad_fixture):
        pass

    def test_error2(bad_fixture):
        pass
"""

def test_failfail(testdir):
    testdir.makepyfile(CODE)
    result = testdir.runpytest()
    result.assert_outcomes(error=2)
```

**Comment by Zac-HD** [comment]
Hmm, not quite sure *when* it broke, but changing 

https://github.com/pytest-dev/pytest/blob/8be9684ab23220cc85abb06e06414961667340b3/src/_pytest/pytester.py#L459

to 

```python
        "error": d.get("error", 0) + d.get("errors", 0), 
```

should fix it :smile:

**Comment by nicoddemus** [comment]
Yep, anybody up for a quick PR? 😁

**Comment by mulatinho** [comment]
I would like to be more involved with pytest, here's a PR :)
