### ISSUE TITLE
Idea: Define scope of factory fixtures based on passed-in args.

### ISSUE THREAD

**Issue by alexkost819** [pytest-dev/pytest#6354]
I discovered dynamic scoping for fixtures recently and am curious about it. One thing I'm trying to play around with is defining the scope of the output of a factory fixture. Is it possible to define the scope of a factory fixture dynamically based on args passed in to the factory fixture? e.g.

```python
@pytest.fixture(scope=arg_scope)
def factory_fixture(other_fixture):
    def _get_fixture(arg_scope):
        return f"I am in {arg_scope} scope!"
    return _get_fixture

@pytest.fixture
def function_scope(factory_fixture):
    return factory_fixture("function")

@pytest.fixture(scope="session")
def failing_function_scope(factory_fixture):
    return factory_fixture("function")  # expect ScopeMismatchError
```

The reason I ask is I have a factory fixture that is currently function scoped but I want to use in higher-scoped items. I get `ScopeMismatchError` though as the higher-scoped fixtures don't know when to tear down (understandably). My current resolution has been copy/pasting the old fixture with a different scope. Dynamic scoping seems really useful, but I don't know how to pass a function down to the original fixture (located in my `conftest.py`) and I cannot use additional command line arguments (so I can't define a function within `conftest.py`).

Open to all feedback and suggestions. Thank you!

**Comment by RonnyPfannschmidt** [comment]
we planned to introduce this in pytest 3.0 as invocation scope (meaning a fixture would be made for each scope its used in

unfortunately it turned out to be horrendously error-prone with the current internals and we haven't gotten around a actual re-factoring, I'll add issue references later unless someone is quicker than me about that

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/issues/1681

**Comment by alexkost819** [comment]
Thanks @RonnyPfannschmidt for the prompt responses. I'm comfortable closing this issue as #1681 captures the desire and my question has been answered. If you feel otherwise re-open. Thank you again.

**Comment by RonnyPfannschmidt** [comment]
Thanks for the follow up
