### ISSUE TITLE
include a is_subset assert method

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#6367]
I think it is common to want to assert that a nested dictonary is a subset of another one and it would be very useful to add such an assert function to pytest itself. 

One good example is at https://stackoverflow.com/a/57675231/99834

**Comment by asottile** [comment]
pytest doesn't currently house any assertion functions -- this would be better done in some assertion library or plugin

**Comment by ssbarnea** [comment]
@asottile I was afraid that this may be the case. Now the big question is if there is another **existing** library or plugin which could host this assertion. I do really want to avoid creating another project for it.

**Comment by nicoddemus** [comment]
While @asottile is correct, I do wonder if we should perhaps have an official assertion library/plugin, as it solves practical problems. Immediately comes to mind how often I use `fnmatch_lines` even though it is private.

But before we introduce assertions, I would like to see a possible list of "assertion helpers" that should be included, so we can take a look at the landscape and decide if this should be indeed a separate library (perhaps under pytest-dev directly) or introduced into pytest itself (I tend for the former, as it doesn't depend on the internals and might have a different release cycle than the core).

This has been brought up before: https://github.com/pytest-dev/pytest/issues/2376

**Comment by nicoddemus** [comment]
@ssbarnea I'm closing this now, let's continue this in #2376
