### ISSUE TITLE
Also rewrite assertions in test modules ("helpers")

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6377]
Pytest does not appear to rewrite assert statements in `tests/utils.py`, although it is is used/imported from `tests/test_foo.py`.

**Comment by The-Compiler** [comment]
That seems like expected behavior to me, see https://docs.pytest.org/en/latest/writing_plugins.html#assertion-rewriting

**Comment by blueyed** [comment]
@The-Compiler 
Thanks for the link to docs (which do not mention that this is based on `python_files` though).

Note that this issue was meant to enhance the "expected"/documented behavior however.
I've given a new setting ("assert_rewrite_fnpatterns") a try in https://github.com/blueyed/pytest/pull/145, but could also imagine to do this based on some automation (e.g. whitelist/rewrite the top-level package(s)/module(s) where tests are collected from).
