### ISSUE TITLE
parametrizing a fixture. why this snippet works?

### ISSUE THREAD

**Issue by andreabisello** [pytest-dev/pytest#6389]
Some time ago,
i was searching for parametrizing a fixture.
because i used a fixture that generate a content.
but because there are different type of content, to avoid code repetition, 
i wanted to pass a parameter, in order to choose the type of content.

i found a snippet, and it works, but i don't know why.

so if i have the fixture

```
@fixture
get_content():
```

and a test using the fixture

```
test_do_something(get_content)
```

i can parametrize the "get_content" fixture passing a parameter to the test

```
@pytest.mark.parametrize('get_content', ['red'], indirect=True)
def test_do_something_on_red_content(get_content)
#here i got a red content
```

why this works? i'm not able to find the answer reading this documentation  https://docs.pytest.org/en/latest/fixture.html#fixture-parametrize

can someone help me?

thanks.

**Comment by erheron** [comment]
Looks like [overriding a fixture](https://docs.pytest.org/en/latest/fixture.html#override-a-fixture-with-direct-test-parametrization), istn't it the case?

**Comment by andreabisello** [comment]
@erheron  yes.
sorry.
