### ISSUE TITLE
monkeypatch dont works with curio enabled context

### ISSUE THREAD

**Issue by yunfan** [pytest-dev/pytest#6395]
# libraries

<details>

<summary>`pip list` output</summary>

```
[jyf@jyf: patch_failed] pip list
Package            Version
------------------ -------
attrs              19.3.0 
coverage           5.0.1  
curio              0.9    
importlib-metadata 1.3.0  
more-itertools     8.0.2  
packaging          19.2   
pip                19.3.1 
pluggy             0.13.1 
py                 1.8.1  
pyparsing          2.4.6  
pytest             5.3.2  
pytest-cov         2.8.1  
pytest-curio       0.1.0  
setuptools         40.8.0 
six                1.13.0 
wcwidth            0.1.8  
zipp               0.6.0
```
</details>

# my code sample

## app.py

```python
import time
import traceback

errorSleep = 5

def fetchValidTask(a, b):
    return b


def taskMonitor():
    while True:
        try:
            ret = fetchValidTask(123)
            if ret is None:
                continue
            print(f"ret = {ret}")

        except Exception:
            traceback.print_exc()
            time.sleep(errorSleep)
            continue

```

## test_app.py

```python
import pytest
import curio

import app

testWaiting = 5

def testTaskMonitorA(kernel, monkeypatch):
    async def testit():
        monkeypatch.setattr(app, "errorSleep", 1)
        monkeypatch.setattr(app, "fetchValidTask", lambda *args: None)

        async with curio.ignore_after(testWaiting):
            await curio.run_in_thread(
                app.taskMonitor
            )

    kernel.run(testit, shutdown=True)
```

## pytest.ini

```ini
[pytest]
addopts = -sx --disable-warnings --cov=./ --cov-report=html
```

# bug description

the `monkeypatch.setattr` method failed to work when working together with `curio` (which itself had already use pytest for testing)

in the above code, i have a function which will run infinitly, so i use styles like 

```python
async with curio.ignore_after(5):   # timeout after 5 seconds and not raise exception
    await curio.run_in_thread(target_function, *args)
```

and it works as except, will exit the target_fucntion after 5 seconds even if its a infinite one
the problem is that `monkeypatch.setattr` failed for setting the other function it invoked
which in this case is `fetchValidTask`, you could see that from the failed log 

```
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/jyf/pytest_samples/patch_failed, inifile: pytest.ini
plugins: cov-2.8.1, curio-0.1.0
collected 1 item

test_app.py .

----------- coverage: platform linux, python 3.7.3-final-0 -----------
Coverage HTML written to dir htmlcov


============================== 1 passed in 5.13s ===============================
Traceback (most recent call last):
  File "/home/jyf/pytest_samples/patch_failed/app.py", line 16, in taskMonitor
    ret = fetchValidTask(123)
TypeError: fetchValidTask() missing 1 required positional argument: 'b'
```

**Comment by Zac-HD** [comment]
I think the problem is that here:

```python
def fetchValidTask(a, b):
    return b


def taskMonitor():
    while True:
        try:
            ret = fetchValidTask(123)
		...
```

you access `fetchValidTask` directly by name, not by looking up an attribute of the module.

**Comment by yunfan** [comment]
@Zac-HD  the problem is when i use some hacking to mock the `True` with some other callable object which will return `True` for a while and then return `False`, this made the target function's loop finite, and wont need to use a curio based solution, under this case, monkeypatch works

**Comment by Zac-HD** [comment]
I'm pretty sure this is a usage problem, not a bug in pytest.  Happy to reopen if you can provide a reproducible example with just pytest 🙂

**Comment by RonnyPfannschmidt** [comment]
@yunfan the problem seems to be that the thread keeps running, and after the monkeypatch is undone after test teardown, things go really bad

so the problem aint monkeypatch, but the still running thread, please murder your threads ^^

**Comment by RonnyPfannschmidt** [comment]
extra detail, based on the  docs of https://curio.readthedocs.io/en/latest/reference.html#curio.workers.run_in_thread - this is strictly a user error

**Comment by yunfan** [comment]
@RonnyPfannschmidt  thanks, so what do you recommend to test such logic ? suppose i need to use curio still

**Comment by RonnyPfannschmidt** [comment]
@yunfan you need  to ensure you end your threads gracefully within the test

typically this would be a good option to ensure you generally can do graceful and  controlled shut-down of all parts

**Comment by nicoddemus** [comment]
In summary:

```python
kernel.run(testit, shutdown=True)
```

This line should be changed somehow (I don't know curio enough) to ensure that after `run` returns, every background thread has been finished.

Btw you might want to try https://pypi.org/project/pytest-curio 👍

**Comment by yunfan** [comment]
@RonnyPfannschmidt thanks very much for you patient and the helpful links , also thanks to you  @nicoddemus
