### ISSUE TITLE
Incorrect changelog link from docs homepage

### ISSUE THREAD

**Issue by mplough** [pytest-dev/pytest#6397]
On https://docs.pytest.org/en/latest/index.html, the Changelog is erroneously linked:

> Consult the [Changelog](https://docs.python.org/3/whatsnew/changelog.html#changelog) page for fixes and enhancements of each version.

It links to the Python language changelog (https://docs.python.org/3/whatsnew/changelog.html#changelog) rather than the Pytest changelog (https://docs.pytest.org/en/latest/changelog.html).

I'm not sure why; the `rst` source says the following and there is a changelog page.

```rst
Changelog
---------

Consult the :ref:`Changelog <changelog>` page for fixes and enhancements of each version.
```

Is there an issue with the doc generation process?

**Comment by nicoddemus** [comment]
Thanks @mplough for the report, appreciate it!
