### ISSUE TITLE
proposal - generate tests from openapi?

### ISSUE THREAD

**Issue by andreabisello** [pytest-dev/pytest#6414]
I was thinking about generation of tests starting from a openapi specification.
Sure, not E2E tests,
but maybe a basic implementation of a series of unit test tests tailored around the openapi specification can be useful and the creation of the test files with test definitions can be automatized following the openapi specification.
what do you think?

**Comment by nicoddemus** [comment]
Hi @andreabisello that sounds like a great idea! 

But it is probably better implemented as a plugin, because it would not demand any changes in the core after all. 👍

**Comment by andreabisello** [comment]
@nicoddemus  thanks,
i thinks a cli should be good.
my approach can be

* read the openapi specification , e.g. https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml
* fisically create a string containing tests looping through methods parameters input values return values status codes etc
* save the string inside a test_file.py 

i opened this issue as a brainstorming, because i think its strange there are not projects like the one i'm thinking about. There should be something wrong.

**Comment by Zac-HD** [comment]
> i think its strange there are not projects like the one i'm thinking about.

Creating a set of basic / template tests is feasible, but automatically updating when the schema changes is *really, really hard*.  And without updates it's just not that useful - at the start your schema is small enough that you don't really need the tool, and later it's very difficult to adopt the tool.

But also https://github.com/kiwicom/schemathesis exists :smile:

**Comment by andreabisello** [comment]
@Zac-HD I didn't know schematesis , it looks like a good project, but i'm searching for something different , something that generate the boilerplate of a test suite, not an test executer. Maybe the test search strategy can be the same.

**Comment by nicoddemus** [comment]
A search brought me to https://github.com/pyopenapi/pyswagger, which says will support OpenAPI 3.0 soon. Might be worth taking a deeper look.

**Comment by RonnyPfannschmidt** [comment]
unfortunately it says that since a while and the openapi-codegen for python is not feature  complete either

**Comment by Zac-HD** [comment]
Closing this issue because we think the proposed feature - while really cool - does not fit in core `pytest`.

**Comment by andreabisello** [comment]
yes,
thanks.
