### ISSUE TITLE
Add python_classes_ignore option config file

### ISSUE THREAD

**Issue by natter1** [pytest-dev/pytest#6418]
In some cases classes may have a name starting or ending with test, that ar not meant to be a test (e.g. class Testament). When writing tests for such a class the output becomes clutterd with PytestCollectionWarning. It would be nice to have a way to exclude certain classes via config file. Something like python_classes_ignore  as the opposite of python_classes. Or have I missed a better way to achieve this?

For an example see also:
https://stackoverflow.com/questions/58624641/

**Comment by Zac-HD** [comment]
Keeping classes-to-ignore out of collected test files is probably the only solution, sorry.

**Comment by RonnyPfannschmidt** [comment]
i roughly recall that the `__test__` attribute can be used as indication, but im not sure - someone would have to validate

**Comment by nicoddemus** [comment]
@natter1 

As @RonnyPfannschmidt said, you can set a `__test__` attribute on classes that pytest should ignore:

```python
class Testament:
    __test__ = False
```
