### ISSUE TITLE
warn when logging fails

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest#6433]
```python
def func():
    logging.error("%s" , "a", "b")

def test_func():
    func()
```

Now an expectation will be thrown and written on the output... but no warning is thrown... so the test run can't be marked as failed. 🤔

**Comment by RonnyPfannschmidt** [comment]
this is the logging default behaviour

```pycon
>>> import logging
>>> logging.error("%s" , "a", "b")
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
Message: '%s'
Arguments: ('a', 'b')
>>> 
```

so we need  a more out of band handling for logging errors

**Comment by CarycaKatarzyna** [comment]
As far as I can see the ``logging.error`` is not shown if test is passed. But if test fails ``Captured stderr call`` is printed and looks like default behaviour presented by @RonnyPfannschmidt. How exactly should the expected result look like?

**Comment by RonnyPfannschmidt** [comment]
This is the expected result for wrong calls to logging

It should how alway fail the test
