### ISSUE TITLE
Add testing/__init__.py ?

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6452]
https://github.com/pytest-dev/pytest/issues/6451 reminded me of having `testing/__init__.py`, which is required for specific mypy config (`[mypy-testing.*]`) - mypy requires this to be a module.

Should we add this?
We do not have specific mypy config for tests yet, but this would allow to use `check_untyped_defs = True` there then.

/cc @bluetech

**Comment by nicoddemus** [comment]
I'm not against adding `testing/__init__.py` at all, but it would probably better to do this until we have an actual reason to do so (that's if I understand your original message correctly in the first place).

**Comment by bluetech** [comment]
If there is a problem with adding actual `testing/__init__.py`, can always use `testing/__init__.pyi` (note the i at the end) to please mypy but not affect anything else.

**Comment by blueyed** [comment]
@bluetech that makes sense, thanks!
