### ISSUE TITLE
5.3.3 breaks `lazy_fixture` pattern

### ISSUE THREAD

**Issue by trendelkampschroer** [pytest-dev/pytest#6513]
First of all thanks a lot for the creation of pytest and all the work that is going into it! 

This is the problem I have observed:

`pytest-5.3.3` breaks usage of `lazy_fixture` parametrisation that was working with `pytest-5.3.2`

pytest: 5.3.3 (conda-forge)
pytest-lazy-fixture: 0.6.2
os: macos catalina
python: 3.6.7

```python

import pytest
from pytest_lazyfixture import lazy_fixture


@pytest.fixture
def foo():
    return "foo"

@pytest.fixture
def bar():
    return "bar"

@pytest.fixture(params=[
    lazy_fixture("foo"),
    lazy_fixture("bar")
])
def myfixture(request):
    return request.param

def test_foo_bar(myfixture):
    assert myfixture in ["foo", "bar"]

```

This fails with the following error

```

  @pytest.fixture(params=[
      lazy_fixture("foo"),
      lazy_fixture("bar")
  ])
  def myfixture(request):
E       recursive dependency involving fixture 'foo' detected

```

**Comment by trendelkampschroer** [comment]
Thx for the quick reply.

**Comment by SalmonMode** [comment]
@blueyed thanks for the CC. I've never used `lazy_fixture` before, so I'll have to dig into it a bit, but this issue is separate from the one found in https://github.com/pytest-dev/pytest/issues/6492

**Comment by blueyed** [comment]
@SalmonMode yeah, thought so myself.  I think you/we should go through all the issues being closed off as duplicates maybe too quickly - #6492 appears to be a meta issue for everything this has caused a regression of some kind.

**Comment by nicoddemus** [comment]
Another idea is to list all issues in #6492 itself for book keeping (I mean in the first post, in a separate section).

**Comment by nicoddemus** [comment]
This is working as of `pytest-7.4.1` and `lazy-fixture-0.6.3`:

```
λ pytest foo.py
======================== test session starts ========================
platform win32 -- Python 3.10.10, pytest-7.4.1, pluggy-1.3.0
rootdir: e:\Temp\venvs
plugins: lazy-fixture-0.6.3
collected 2 items

foo.py ..                                                      [100%]

========================= 2 passed in 0.02s =========================
```
