### ISSUE TITLE
ci: use cache with pre-commit (linting)

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6528]
Ref: https://github.com/actions/cache/blob/master/examples.md#simple-example

Might not be trivial with our setup (matrix).  Might make sense to move "linting" to a simple job.

**Comment by hugovk** [comment]
Here's an example lint job with pre-commit (and pip) caching:

https://github.com/hugovk/pypistats/blob/master/.github/workflows/lint.yml

**Comment by nicoddemus** [comment]
But is it necessary? I think linting currently finishes before most of other jobs.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pre-commit/action has nice docs around it

**Comment by blueyed** [comment]
@RonnyPfannschmidt the problem there is that we're not using `jobs` - otherwise this would have been a PR instead of an issue.. ;)

**Comment by RonnyPfannschmidt** [comment]
@blueyed i'm under the assumption that it should be fine to put that bit into new workflow file, did i miss anything

**Comment by nicoddemus** [comment]
IIUC, currently we execute pre-commit via `tox -e linting`, which has the nice property of being convenient to use locally as well.

Using `pre-commit/action` would use something different on CI, which is a small disadvantage.

**Comment by asottile** [comment]
we can still use all of the parts of the README of `pre-commit/action` without the actual action itself -- the interesting / clever bits are in the cache step (the action itself is pretty dumb tbh)

**Comment by asottile** [comment]
the other nice bit about GA is you can add another workflow file (don't need to make `main` super complicated) -- this might be a good idea already for the deploy steps at the bottom

**Comment by nicoddemus** [comment]
> the other nice bit about GA is you can add another workflow file (don't need to make main super complicated) -- this might be a good idea already for the deploy steps at the bottom

Interesting. Currently the `deploy` job depends on the `build` job succeeding:

https://github.com/pytest-dev/pytest/blob/1cd4bafda75a8bfc4d7ed54c36962ce496f65784/.github/workflows/main.yml#L161-L162

Do you know off-hand if that's possible to accomplish with separate workflow files?

**Comment by asottile** [comment]
oh hmmm yeah I don't think that works cross file :thinking:

**Comment by asottile** [comment]
via #7304
