### ISSUE TITLE
Support access to autouse/pytestmark/etc. fixtures

### ISSUE THREAD

**Issue by kpinc** [pytest-dev/pytest#6565]
I would like to see pytestmark etc. fixtures be made available to tests.

The use case is:

You have a production database or other "important stuff" that you don't want tests to ever touch, so you write a fixture for your integration tests that ensures this.  Using pytestmark, etc. is a good way to ensure that the fixture is always applied and you don't accidentally write a new test that touches your untouchables.

But the tests occasionally need access to the fixture.  An example would be a test that looks for a log message when the database can't be accessed, as might be setup by a mock database connector.  The test would want to access the mock_db_connector fixture and do:

   mock_db_connector.side_effect = mydb.exceptions.ConnectionFailedError()

This would cause the connection to the database to fail, which is the condition the integration test is looking for.

**Comment by RonnyPfannschmidt** [comment]
its not clear what you are asking for, please provide a larger pseudo code example

**Comment by blueyed** [comment]
@kpinc I understood it as if you want to get the fixture/mark from within a test? (when it is not used as an arg directly)  That would be possible then.

**Comment by kpinc** [comment]
On Sat, 25 Jan 2020 09:26:22 +0000 (UTC)
Daniel Hahler <notifications@github.com> wrote:

> @kpinc I understood it as if you want to get the fixture/mark from
> within a test? (when it is not used as an arg directly) 

Yes.  That is exactly what I am asking for.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by nicoddemus** [comment]
@kpinc here's how:

```python
@pytest.mark.my_mark(x=1)
def test_foo(request):
    tmpdir = request.getfixturevalue('tmpdir')
    my_mark = request.node.get_closest_mark('my_mark')
    assert my_mark.kwargs['x'] == 1
```

You can see the API in [reference](https://docs.pytest.org/en/latest/reference.html).

**Comment by kpinc** [comment]
On Thu, 30 Jan 2020 14:43:13 -0800
Bruno Oliveira <notifications@github.com> wrote:

> @kpinc here's how:
> 
> ```python
> @pytest.mark.my_mark(x=1)
> def test_foo(request):
>     tmpdir = request.getfixturevalue('tmpdir')
>     my_mark = request.node.get_closest_mark('my_mark')
>     assert my_mark.kwargs['x'] == 1
> ```

Just what I want.  Thanks for the explanation.

Please consider the attached documentation patch: fixture_v1.patch

It adds a list of available fixtures to the start of the
chapter on fixtures.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by blueyed** [comment]
@kpinc 

> Please consider the attached documentation patch: fixture_v1.patch

It did not get here.  Please post it on Github as a comment.

**Comment by kpinc** [comment]
diff --git a/doc/en/fixture.rst b/doc/en/fixture.rst
    index b54a12731..d80fe9e67 100644
    --- a/doc/en/fixture.rst
    +++ b/doc/en/fixture.rst
    @@ -34,6 +34,76 @@ both styles, moving incrementally from classic to new style, as you
     prefer.  You can also start out from existing :ref:`unittest.TestCase
     style <unittest.TestCase>` or :ref:`nose based <nosestyle>` projects.
     
    +The built-in pytest :ref:`fixtures <fixtures-api>` are, in order of
    +introduction:
    +
    +   :ref:`record_property-api`
    +       Add extra properties to the test
    +
    +   :ref:`record_testsuite_property-api`
    +       Add extra properties to the test suite
    +
    +   :ref:`pytest.fixture-api`
    +       Function decorator; the decorated function becomes a new
    +       fixture
    +
    +   :ref:`request-api`
    +       Provide information on the executing test function
    +
    +   :ref:`monkeypatch-api`
    +       Temporarily modify classes, functions, dictionaries,
    +       ``os.environ``, and other objects
    +
    +   :ref:`tmp_path-api`
    +       Provide a :class:`pathlib.Path` object to a temporary directory
    +       which is unique to each test function
    +
    +   :ref:`tmp_path_factory-api`
    +        Make session-scoped temporary directories and return
    +        :class:`pathlib.Path` objects
    +
    +   :ref:`tmpdir-api`
    +        Provide a :class:`py.path.local` object to a temporary
    +        directory which is unique to each test function;
    +        replaced by :doc:`tmp_path <tmpdir>`
    +
    +        .. _`py.path.local`: https://py.readthedocs.io/en/latest/path.html
    +
    +   :ref:`tmpdir_factory-api`
    +        Make session-scoped temporary directories and return
    +        :class:`py.path.local` objects;
    +        replaced by :ref:`tmp_path_factory <tmp_path_factory example>`
    +
    +   :ref:`capsys-api`
    +        Capture writes to ``sys.stdout`` and ``sys.stderr``
    +
    +   :ref:`capsysbinary-api`
    +        Capture writes to ``sys.stdout`` and ``sys.stderr``
    +
    +   :ref:`capfd-api`
    +        Capture writes to file descriptors ``1`` and ``2``
    +
    +   :ref:`capfdbinary-api`
    +        Capture writes to file descriptors ``1`` and ``2``
    +
    +   :ref:`recwarn-api`
    +        Record warnings emitted by test functions
    +
    +   :ref:`doctest_namespace-api`
    +        Provide a dict injected into the docstests namespace
    +
    +   :ref:`cache-api`
    +        Store and retrieve values across pytest runs
    +
    +   :ref:`testdir`
    +        Provide a temporary test directory to aid in running, and
    +        testing, pytest
    +
    +   :ref:`pytestconfig-api`
    +        Access to configuration values, pluginmanager and plugin hooks
    +
    +   :ref:`caplog-api`
    +        Access, and control, logging
     
     .. _`funcargs`:
     .. _`funcarg mechanism`:
    diff --git a/doc/en/reference.rst b/doc/en/reference.rst
    index 50e32d660..619450f8b 100644
    --- a/doc/en/reference.rst
    +++ b/doc/en/reference.rst
    @@ -243,6 +243,8 @@ Will create and attach a :class:`Mark <_pytest.mark.structures.Mark>` object to
         mark.kwargs == {"method": "thread"}
     
     
    +.. _`fixtures-api`:
    +
     Fixtures
     --------
     
    @@ -273,6 +275,8 @@ Example of a fixture requiring another fixture:
     For more details, consult the full :ref:`fixtures docs <fixture>`.
     
     
    +.. _`pytest.fixture-api`:
    +
     @pytest.fixture
     ~~~~~~~~~~~~~~~
     
    @@ -301,6 +305,8 @@ Under the hood, the cache plugin uses the simple
     .. automethod:: Cache.makedir
     
     
    +.. _`capsys-api`:
    +
     capsys
     ~~~~~~
     
    @@ -326,6 +332,8 @@ capsys
         :members:
     
     
    +.. _`capsysbinary-api`:
    +
     capsysbinary
     ~~~~~~~~~~~~
     
    @@ -346,6 +354,8 @@ capsysbinary
                 assert captured.out == b"hello\n"
     
     
    +.. _`capfd-api`:
    +
     capfd
     ~~~~~~
     
    @@ -366,6 +376,8 @@ capfd
                 assert captured.out == "hello\n"
     
     
    +.. _`capfdbinary-api`:
    +
     capfdbinary
     ~~~~~~~~~~~~
     
    @@ -386,6 +398,8 @@ capfdbinary
                 assert captured.out == b"hello\n"
     
     
    +.. _`doctest_namespace-api`:
    +
     doctest_namespace
     ~~~~~~~~~~~~~~~~~
     
    @@ -404,6 +418,8 @@ doctest_namespace
         For more details: :ref:`doctest_namespace`.
     
     
    +.. _`request-api`:
    +
     request
     ~~~~~~~
     
    @@ -415,12 +431,16 @@ The ``request`` fixture is a special fixture providing information of the reques
         :members:
     
     
    +.. _`pytestconfig-api`:
    +
     pytestconfig
     ~~~~~~~~~~~~
     
     .. autofunction:: _pytest.fixtures.pytestconfig()
     
     
    +.. _`record_property-api`:
    +
     record_property
     ~~~~~~~~~~~~~~~~~~~
     
    @@ -429,6 +449,8 @@ record_property
     .. autofunction:: _pytest.junitxml.record_property()
     
     
    +.. _`record_testsuite_property-api`:
    +
     record_testsuite_property
     ~~~~~~~~~~~~~~~~~~~~~~~~~
     
    @@ -436,6 +458,9 @@ record_testsuite_property
     
     .. autofunction:: _pytest.junitxml.record_testsuite_property()
     
    +
    +.. _`caplog-api`:
    +
     caplog
     ~~~~~~
     
    @@ -450,6 +475,8 @@ caplog
         :members:
     
     
    +.. _`monkeypatch-api`:
    +
     monkeypatch
     ~~~~~~~~~~~
     
    @@ -465,6 +492,7 @@ monkeypatch
     .. autoclass:: _pytest.monkeypatch.MonkeyPatch
         :members:
     
    +
     .. _testdir:
     
     testdir
    @@ -493,6 +521,8 @@ To use it, include in your top-most ``conftest.py`` file:
         :members:
     
     
    +.. _`recwarn-api`:
    +
     recwarn
     ~~~~~~~
     
    @@ -516,6 +546,8 @@ Each recorded warning is an instance of :class:`warnings.WarningMessage`.
         differently; see :ref:`ensuring_function_triggers`.
     
     
    +.. _`tmp_path-api`:
    +
     tmp_path
     ~~~~~~~~
     
    @@ -527,6 +559,8 @@ tmp_path
         :no-auto-options:
     
     
    +.. _`tmp_path_factory-api`:
    +
     tmp_path_factory
     ~~~~~~~~~~~~~~~~
     
    @@ -542,6 +576,8 @@ tmp_path_factory
     .. automethod:: TempPathFactory.getbasetemp
     
     
    +.. _`tmpdir-api`:
    +
     tmpdir
     ~~~~~~
     
    @@ -553,6 +589,8 @@ tmpdir
         :no-auto-options:
     
     
    +.. _`tmpdir_factory-api`:
    +
     tmpdir_factory
     ~~~~~~~~~~~~~~

**Comment by kpinc** [comment]
Pasting a patch into a github comment was painful.

**Comment by blueyed** [comment]
> Pasting a patch into a github comment was painful.

Why?  To get the formatting right?  (I've edited it)
Thanks anyway!

**Comment by kpinc** [comment]
On Fri, 31 Jan 2020 01:07:28 -0800
Daniel Hahler <notifications@github.com> wrote:

> > Pasting a patch into a github comment was painful.  
> 
> Why?  To get the formatting right? 

Yes.  It has to be markdown, you can't just paste the
patch.

> (I've edited it)

Thanks.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by nicoddemus** [comment]
Thanks @kpinc,

The idea is good, but unfortunately listing the fixtures like is bound to be forgotten and we might forgot to update it when new fixtures are added.

I will try to think of a solution and open a follow up later.

Thanks!

**Comment by kpinc** [comment]
On Fri, 31 Jan 2020 15:21:27 -0800
Bruno Oliveira <notifications@github.com> wrote:

> Thanks @kpinc,
> 
> The idea is good, but unfortunately listing the fixtures like is
> bound to be forgotten and we might forgot to update it when new
> fixtures are added.

Understood.  Perhaps there is some way to automate the listing.

It would be very nice to have a place to go to get an
overview of available fixtures with one-line summaries.

I feel like I missed out on pytest features.  I only
want to really read those parts of the tutorial that
are of immediate interest.  And don't want to go
to the API docs unless I feel the need for a complete
understanding.  That leaves reading the overviews
to discover what exists.  (Especially as a pytest
beginner.)

If it were up to me I'd put in the list of fixtures
and wait for somebody to point out a problem when
something is forgotten and left off the list.

Good luck with a solution moving forward.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by blueyed** [comment]
Just for reference / as an idea: pytest-django has a custom "fixture" cross ref.
https://github.com/pytest-dev/pytest-django/blob/f72557965302b3974969769b00f3e33aa3da7aae/docs/_ext/pytestdocs.py
https://github.com/pytest-dev/pytest-django/blame/f72557965302b3974969769b00f3e33aa3da7aae/docs/helpers.rst#L191
Still similar to this here (needs to be added with fixtures manually).

**Comment by blueyed** [comment]
@nicoddemus 
Have you came up with anything?
AFAICS the patch is good by itself, and we need to update docs anyway for new fixtures currently.

**Comment by nicoddemus** [comment]
> Have you came up with anything?

Sorry nothing that wouldn't require us to manually update it anytime a new fixture is introduced; but as you comment, we already have to update the docs manually anyway, we just need to remember to do it in another place (no big deal).

**Comment by blueyed** [comment]
Ok.. :confused: 

Anyway, I think we should take @kpinc's patch then for now.
I can put that into a PR if you'd rather like not do it yourself, @kpinc.

**Comment by kpinc** [comment]
On Fri, 07 Feb 2020 23:03:32 -0800
Daniel Hahler <notifications@github.com> wrote:

> Anyway, I think we should take @kpinc's patch then for now.
> I can put that into a PR if you'd rather like not do it yourself,
> @kpinc.

Created pull request: 
Add list of fixtures to start of fixture chapter #6696

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by kpinc** [comment]
On Sat, 8 Feb 2020 12:59:34 -0600
"Karl O. Pinc" <kop@karlpinc.com> wrote:

> On Fri, 07 Feb 2020 23:03:32 -0800
> Daniel Hahler <notifications@github.com> wrote:
> 
> > Anyway, I think we should take @kpinc's patch then for now.
> > I can put that into a PR if you'd rather like not do it yourself,
> > @kpinc.  
> 
> Created pull request: 
> Add list of fixtures to start of fixture chapter #6696

It failed travis, which might mean there's a problem
with master.  I just rebased against master.

I'll let you guys figure it out.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein
