### ISSUE TITLE
access `config` object in hook `pytest_runtest_logstart` and `pytest_runtest_logfinish`

### ISSUE THREAD

**Issue by toolsh** [pytest-dev/pytest#6581]
- [X] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [X] pytest and operating system versions
 version = '5.3.4'
- [ ] minimal example if possible

**Background** 

-  pytest.config global has been [removed since version 5.0](https://docs.pytest.org/en/latest/deprecations.html#pytest-config-global).
- Instead use `request.config` (via the `request fixture`) or if you are a plugin author use the `pytest_configure(config)` hook. Many hooks can also access the `config` object indirectly, through `session.config` or `item.config` for example. 

**Issue**

- How to acess the `config` object in hook [`pytest_runtest_logstart(nodeid, location)`](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_runtest_logstart) and [`pytest_runtest_logfinish(nodeid, location)`](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_runtest_logfinish)? The two hooks has no `request` or `item` or `session` input parameter.
- Given the fact that hooks `pytest_runtest_logstart` and `pytest_runtest_logfinish` are called by [`pytest_runtest_protocol`](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/runner.py#L82) only, a **hacking** way to acess `config` object would be moving codes into `pytest_runtest_protocol` from the two hooks. This is abuse of hooks because it makes the two hooks useless.  Is there a way that to access `config` object **directly** in the two hooks?

```python
def pytest_runtest_protocol(item, nextitem):
    item.ihook.pytest_runtest_logstart(nodeid=item.nodeid, location=item.location)
    runtestprotocol(item, nextitem=nextitem)
    item.ihook.pytest_runtest_logfinish(nodeid=item.nodeid, location=item.location)
    return True
```

**Comment by nicoddemus** [comment]
@toolsh,

A common way to workaround this is by installing a "subplugin":

```python
# conftest.py
def pytest_configure(config):
    config.pluginmanager.register(MyPlugin())


class MyPlugin:

    def pytest_configure(self, config):
        self.config = config

    def pytest_runtest_logstart(self, nodeid, location):
        ...  # access self.config

    def pytest_runtest_logfinish(self, nodeid, location):
        ...  # access self.config
``` 

(Similar approach to access `session`).

Adding new parameters to hooks is usually trivial, but unfortunately adding the `config` parameter to those two hooks in particular are a bit problematic because we need to also update `pytest-xdist`, which calls the hooks directly.

**Comment by Zac-HD** [comment]
Closing this as the question seems to have been answered 😄
