### ISSUE TITLE
Pytest skipping all the tests when using venv shown skipped for appium automation code

### ISSUE THREAD

**Issue by Mani-Hipbar** [pytest-dev/pytest#6584]
(pytest) mani@HBPL-DES-006:~/Documents/Automation$ pytest -rx
============================================================ test session starts =============================================================
platform linux -- Python 3.6.9, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
rootdir: /home/mani/Documents/Automation
plugins: appium-0.1, variables-1.9.0
collected 3 items                                                                                                                            

test_calc.py s                                                                                                                         [ 33%]
test_home.py ss

**Comment by The-Compiler** [comment]
What does `-rs` say?

**Comment by Mani-Hipbar** [comment]
HI i am new to development.
 what do u mean by -rs?

**Comment by Mani-Hipbar** [comment]
SKIPPED [2] /home/mani/Documents/Appium/env/pytest/lib/python3.6/site-packages/pytest_appium/plugin.py:8: no variables file

**Comment by Mani-Hipbar** [comment]
its skipping the whole progaram

**Comment by The-Compiler** [comment]
Looks like you use a `pytest-appium` plugins which skips those tests with a "no variables file" message. You'll need to check appium's documentation or reach out to its developers, as this is happening there and not in pytest's core.

**Comment by Mani-Hipbar** [comment]
Thanks for ur replay, but when i tried to run normal assert function also showing skipped. 

platform linux -- Python 3.6.9, pytest-5.3.4, py-1.8.1, pluggy-0.13.1 -- /home/mani/Documents/Appium/env/pytest/bin/python3
cachedir: .pytest_cache
rootdir: /home/mani/Documents/Automation
plugins: appium-0.1, variables-1.9.0
collected 1 item                                                                                                                             

test_calc.py::test_al SKIPPED                                                                                                          [100%]

============================================================= 1 skipped in 0.01s =============================================================
teste_calc.py
def test_al():
    x = 5
    y = 5
    assert x == y

**Comment by The-Compiler** [comment]
That's because that plugin just skips all tests ([source](https://github.com/hanzhichao/pytest-appium/blob/master/pytest_appium/plugin.py)) if it's installed but pytest-variables isn't configured accordingly. You might want to open a bug there, or uninstall the plugin.
