### ISSUE TITLE
How to sanitize-out ANSI escapes from captured output

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#6586]
In order to improve output asserts and display of potential errors I need a generic way to sanitize captured output.

Please, keep in mind that the purpose of this is not to disable the ANSI support in the executed command but to assure that when asserts fail, they can be read by humans.
![screenshot](https://sbarnea.com/ss/Screen-Shot-2020-01-27-15-24-28.73.png)

* Is there something I can do to enable implicit sanitization?
* How can I improve the assert error report to make it easier to read? Combining newlines like this makes it very difficult to read.

I should add that I know how to strip ANSI part, the question if there is a way to make this implicit as part of assert. Maybe a custom assert that does this?

**Comment by The-Compiler** [comment]
You're running `str()` on a bytes object, which gives you a string like that. Instead, you might want to properly decode it via something like `e.value.stdout.decode('utf-8')` (or if that's the `subprocess` module, pass the `encoding` argument to `subprocess`

**Comment by ssbarnea** [comment]
I am more worried about how to improve pytest display of multiline string assert failures in pytest. The problem is still valid even without ANSI escapes.

**Comment by The-Compiler** [comment]
That's not pytest - your string has the literal characters `\`, `n` in it:

```python
>>> str(b'foo\nbar')
"b'foo\\nbar'"
```
