### ISSUE TITLE
[release] should not check (all) links

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6612]
`tox -e release -- …` triggers the link checking, which is very slow.

This should only be done on demand I think.

**Comment by nicoddemus** [comment]
I was a bit concerned about this as well, but after making the release a few times I don't really seem to notice (takes less than 3 minutes or so).

**Comment by The-Compiler** [comment]
FWIW we've already had this discussion in https://github.com/pytest-dev/pytest/issues/1722.

If only doing it on demand, I bet nobody will ever do it :wink: Like @nicoddemus said, if it's not a problem when releasing in practice, I don't see why it should be removed.
