### ISSUE TITLE
Comment shows incorrect choices.

### ISSUE THREAD

**Issue by BhanuPrakashN** [pytest-dev/pytest#6617]
https://github.com/pytest-dev/pytest/blob/8e1d59a8ddba34495bf3f2d0cd3d2f17e9dbc8af/src/_pytest/junitxml.py#L413

**Comment by Zac-HD** [comment]
Fixing the comment would be a good first contribution.

If you want to go further, you could un-comment the `choices` argument so the ini values are actually validated!  It looks like they were commented out when the feature was first added, but IMO we should have this validation enabled.
