### ISSUE TITLE
ci: release/deploy: do not run the whole test suite

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6619]
There should be only some basic check (a single job), or rather none - given that it was tested before already (before pushing the tag).

Therefore I think it would be best to have a separate "deploy" workflow for this (on GHA).

**Comment by nicoddemus** [comment]
Would be sufficient to just create a new `deploy.yml` file, with the deploy job and proper triggers (tags matching `x.y.z`)?

**Comment by blueyed** [comment]
Yes, I think so.

**Comment by nicoddemus** [comment]
Just found a good example of this, for reference:

https://github.com/cli/cli/tree/master/.github/workflows
https://github.com/cli/cli/actions

**Comment by hugovk** [comment]
Good find! This looks like the pertinent part:

```yml
on:
  push:
    tags:
      - "v*"
```

This may be enough for pytest:

```yml
on:
  push:
    tags:
      - "*"
```
