### ISSUE TITLE
[FeatureRequest] Enable having comments in the expected output inside the docsting

### ISSUE THREAD

**Issue by MomIsBestFriend** [pytest-dev/pytest#6628]
I am having trouble in having a comment next to my expected output, inside the docstring (I don't have very good English, hopefully my examples will cover that).

I am trying to document a function, and give some examples about it.

The function may have an unexpected output, so I am trying to give an example.

What I am trying to do is (from the original [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.searchsorted.html)) :

```python
def searchsorted():
    """
    >>> x = pd.Series([2, 1, 3])

    >>> x.searchsorted(1)
    0  # wrong result, correct would be 1
    """
```

It would be really nice if I could skip this specific example, or if the expected output will not be included along side with the comment.

The error I am getting right now is:

```
Expected:
    0  # wrong result, correct would be 1
Got:
    0
```

I am really sorry if you already have that option (and I would like to know about it), I looked everywhere and couldn't find anything.

P.S
You guys are amazing, your product is the only reason I write tests :laughing: (Thank you)

__Enviroment details__:

<details>

INSTALLED VERSIONS
------------------
python           : 3.8.1.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.13.a-1-hardened
machine          : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pytest           : 5.3.5
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0
Cython           : 0.29.14
hypothesis       : 5.4.0
sphinx           : 2.3.1
blosc            : 1.8.3
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.0
IPython          : 7.11.1
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.1
fastparquet      : 0.3.2
gcsfs            : None
lxml.etree       : 4.5.0
matplotlib       : 3.1.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.1
pandas_gbq       : None
pyarrow          : None
pytables         : None
pytest           : 5.3.5
pyxlsb           : None
s3fs             : 0.4.0
scipy            : 1.4.1
sqlalchemy       : 1.3.13
tables           : 3.6.1
tabulate         : 0.8.6
xarray           : 0.14.1
xlrd             : 1.2.0
xlwt             : 1.3.0
xlsxwriter       : 1.2.7
numba            : 0.48.0

</details>

**Comment by blueyed** [comment]
You can put the comment with the line above, e.g.:
```
"""
>>> 'real'  # should be 'expected'
'expected'
"""
```

Looks like this then:
```
==================== FAILURES ====================
____________ [doctest] t.test_doctest ____________
001
002 >>> 'real'  # should be 'expected'
Expected:
    'expected'
Got:
    'real'
```

In general though this looks like you want to have something like "xfail" for this also / additionally?

**Comment by blueyed** [comment]
You can skip it using `>>> import pytest; pytest.skip("skip")` (see https://github.com/blueyed/pytest/blob/c23e74ba7b388c80c3494c87f548c3058855e74b/doc/en/doctest.rst#skipping-tests-dynamically).

**Comment by blueyed** [comment]
Better:
```python
"""
>>> 'real'  # doctest: +SKIP
'expected'
"""
```
See https://docs.python.org/3/library/doctest.html?highlight=doctest#doctest.SKIP.

Closing as answered, feel free to followup regardless, of course.

**Comment by MomIsBestFriend** [comment]
@blueyed Thank you so much!!!
