### ISSUE TITLE
approx-like behavior for dataclasses

### ISSUE THREAD

**Issue by MatanRubin** [pytest-dev/pytest#6632]
Is there a way to get approx-like behavior on dataclasses?
My use-case is this - I have a dataclass with some int fields, some string fields, and some float fields.
Comparing the two dataclasses for equality works well, except for the float fields, which may be slightly different due to precision errors.
I would like to be able to compare dataclass instances such that int fields, string fields, etc. are tested for equality, but float fields are tested using approx.

Code example:

```
@dataclass
class Foo:
    bar: int
    baz: float

a = Foo(1, 3.0)
b = Foo(1, 3.00000001)

pytest.approx(a, b)  # should return True
```

Is there a way to do this?

**Comment by d1618033** [comment]
I think you might not be using pytest.approx correctly. from the [docs](https://docs.pytest.org/en/latest/reference.html#pytest-approx) it seems you should be using it on the value you want to compare to, e.g:

```python
def test_compare_floats():
    a = Foo(1, 3.00000001)
    b = Foo(1, pytest.approx(3.0, abs=1e-3))
    assert a == b
```

**Comment by michaelyaakoby** [comment]
I think the above answer is good only if you create the dataclass instance in the test's code.
If the dataclass's instance is created by the system-under-tests, than I think you cannot easily wrap a value with `pytest.approx()`.

In this case, you can write your own recursive comparison that usess ``approx()`` to compare numbers. 

Something like this:
```python
from dataclasses import dataclass
from typing import Any

import pytest


@dataclass
class Foo:
    bar: int
    baz: float


@dataclass
class Bar:
    foo: Foo
    bar: str


def approx(o1: Any, o2: Any) -> None:
    assert type(o1) == type(o2)

    o1_keys = [v for v in dir(o1) if not v.startswith('__')]
    o2_keys = [v for v in dir(o2) if not v.startswith('__')]

    assert sorted(o1_keys) == sorted(o2_keys)

    for k in o1_keys:
        v1 = getattr(o1, k)
        v2 = getattr(o2, k)
        if isinstance(v1, int) or isinstance(v1, float):
            assert v1 == pytest.approx(v2)
            continue

        if isinstance(v1, bool) or isinstance(v1, str):
            assert v1 == v2
            continue

        approx(v1, v2)


def test_different_foo() -> None:
    approx(
        Foo(1, 3.0),
        Foo(1, 30.00000001)
    )


def test_same_foo() -> None:
    approx(
        Foo(1, 3.0),
        Foo(1, 3.00000001)
    )


def test_different_bar() -> None:
    approx(
        Bar(Foo(1, 3.0), "bla"),
        Bar(Foo(1, 30.00000001), "bla")
    )


def test_same_bar() -> None:
    approx(
        Bar(Foo(1, 3.0), "bla"),
        Bar(Foo(1, 3.00000001), "bla")
    )

```

**Comment by MatanRubin** [comment]
Thanks @michaelyaakoby , this worked great!
I think this is a great feature to have in pytest, you should open a PR with this method.

**Comment by johnthagen** [comment]
I was able to use [`DeepDiff`](https://github.com/seperman/deepdiff) `significant_digits` to perform nested comparisons of `dataclass`es with `float` values

- https://zepworks.com/deepdiff/current/numbers.html#significant-digits

```py
    a: MyDataclass = function_under_test()
    diff = DeepDiff(
        a,
        MyDataclass(
            value=0.1,
        ),
        significant_digits=3,
    )
    assert len(diff) == 0
```
