### ISSUE TITLE
How can i repeat a test module in pytest?

### ISSUE THREAD

**Issue by kvenkat88** [pytest-dev/pytest#6641]
I would like to repeat a test module N times.
The order is very important.

```python
import pytest

@pytest.mark.usefixtures("class_setup_teardown")
class TestStressRobot:
    def test_1(self):
        print "\nstressing part 1..."
        assert True

    def test_2(self):
        print "\nstressing part 2..."
        assert True

    def test_3(self):
        print "\nstressing part 3..."
        assert True
```

When I run `py.test --repeat=2`, the output is:

```
test_stress.pyTestStressRobot.test_1[0] ✓
test_stress.pyTestStressRobot.test_1[1] ✓
test_stress.pyTestStressRobot.test_2[0] ✓
test_stress.pyTestStressRobot.test_2[1] ✓
test_stress.pyTestStressRobot.test_3[0] ✓
test_stress.pyTestStressRobot.test_3[1] ✓
```

I don't want it to be repeated per test, but per test module.

Is it possible to have something like that?

```
test_stress.pyTestStressRobot.test_1[0] ✓
test_stress.pyTestStressRobot.test_2[0] ✓
test_stress.pyTestStressRobot.test_3[0] ✓
test_stress.pyTestStressRobot.test_1[1] ✓
test_stress.pyTestStressRobot.test_2[1] ✓
test_stress.pyTestStressRobot.test_3[1] ✓
```

Could you please let me know how to do? Awaiting your reply.

**Comment by iwanb** [comment]
See https://github.com/pytest-dev/pytest-repeat

You can use --count=10 --repeat-scope=module

I think you can also just put your test module X times on the command line.

**Comment by nicoddemus** [comment]
Thanks @iwanb,

I will close this for now, but please don't hesitate to come back if you have further questions @kvenkat88!

**Comment by kvenkat88** [comment]
@iwanb  @nicoddemus Thanks for your reply. Sure i will come back to you if i have any questions
