### ISSUE TITLE
How to use fixtures/relevant logic in pytest.mark.parametrize()?

### ISSUE THREAD

**Issue by kvenkat88** [pytest-dev/pytest#6647]
I have a fixture called like below

```python
@pytest.fixture(scope='session')  # Fixture to get configuration items from command line
def request_get_config_brand_value(request):
    brand = request.config.getoption("--brand")
    print(brand)
    return DataReader().fetch_clinic_details(brand)['apptmt_types']
```

Below fixture would return output like `['Med','Den','Cardio']`

How to use the above fixture returned output in the `pytest.mark.parametrize()`?

**Comment by Zac-HD** [comment]
Closing this issue as an inactive question.  We recommend using the [`pytest` tag on stackoverflow](https://stackoverflow.com/questions/tagged/pytest).
