### ISSUE TITLE
-m disables autouse fixtures for custom Items

### ISSUE THREAD

**Issue by dmtucker** [pytest-dev/pytest#6650]
``` python
# conftest.py

import pytest


@pytest.fixture(scope='session', autouse=True)
def thing():
    raise Exception('thing ran!')

def pytest_collect_file(path, parent):
    return FooItem(path, parent)

class FooItem(pytest.Item, pytest.File):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_marker('foo')

    def runtest(self):
        raise Exception(str(self.fspath) + ' ran!')
```
``` python
# test_foo.py

def test_whatever():
    pass
```

If I run `test_foo.py`, I get a failure (from the injected `FooItem`) and an error (from the exception in the `thing` fixture, which ran because it is `autouse=True`).
```
$ venv/bin/pytest test_foo.py
...
==================== 1 failed, 1 warning, 1 error in 0.15s =====================
```

However, if I just want to run the `FooItem` (which has its own marker, `'foo'`), the `autouse` fixture is skipped:
```
$ venv/bin/pytest -m foo test_foo.py
...
================== 1 failed, 1 deselected, 1 warning in 0.17s ==================
```
- Note that the results show a failure from the `FooItem`, not an error from the `thing` fixture.

Here's my venv's `pip list`:
```
Package            Version
------------------ -------
attrs              19.3.0 
importlib-metadata 1.5.0  
more-itertools     8.2.0  
packaging          20.1   
pip                19.2.3 
pluggy             0.13.1 
py                 1.8.1  
pyparsing          2.4.6  
pytest             5.3.5  
setuptools         41.2.0 
six                1.14.0 
wcwidth            0.1.8  
zipp               2.1.0  
```
I'm on macOS 10.13.6.

**Comment by dmtucker** [comment]
This is very similar to #5715.

**Comment by RonnyPfannschmidt** [comment]
fixtures are currently not implemented at the level of `Item`. but at the level of specific `Item` subclasses

this in turn means, that `FooItem` won't get fixtures

**Comment by dmtucker** [comment]
@RonnyPfannschmidt Would it be reasonable for me to inherit from one of those specific subclasses instead of `Item` directly?

For context, I'm working on adding `pytest-xdist` support to `pytest-mypy`... It needs to run `mypy` once, then the collected `MypyItem`s need to see if their associated file has errors in the output. Currently, [the run is done in `pytest_runtestloop`](https://github.com/dbader/pytest-mypy/blob/ed2f5cc84b408f0802b6dcf5b9331866347ec0fd/src/pytest_mypy.py#L48) which is problematic because [`pytest-xdist` re-implements that](https://github.com/pytest-dev/pytest-xdist/blob/6fd5b56491ac30b47e31a98dd79f16e1e85ecf41/OVERVIEW.md#L40). (Even if it didn't, as is that would result in multiple `mypy` runs...)

The strategy I've been working with is described [in the "Making session-scoped fixtures execute only once" section of the `pytest-xdist` README](https://github.com/pytest-dev/pytest-xdist/blob/6fd5b56491ac30b47e31a98dd79f16e1e85ecf41/README.rst#L125-L142); however, that won't work if only the `MypyItem`s are run (e.g. with `pytest -m mypy` or if no fixture-supporting tests are found). Also, I can't access `tmp_path_factory` or `worker_id` from a hook (#5012).

Any tips or ideas you have would be much appreciated!

**Comment by RonnyPfannschmidt** [comment]
sub-classing python items could be a way  to work around current limitations

my personal opinion is that code analysis like flake8, mypy & co doesn't belong into test execution

**Comment by dmtucker** [comment]
👌

FWIW, I was able to get something working (https://github.com/dbader/pytest-mypy/pull/73) by combining that xdist recipe (but not in a fixture) with this one: https://hackebrot.github.io/pytest-tricks/shared_directory_xdist/
