### ISSUE TITLE
Document way to customize abbreviation (elipsis) on AssertionError

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#6682]
I keep getting errors that I cannot debug because the printed `AssertionError` is censored so much that makes impossible to see what was the difference.

Adding `-vvvv` did not help at all changing the way exceptions are rendered.

> >           assert l in out
> E           AssertionError: assert 'instance         docker         ansible             default          false      false' in 'Instance Name    Driver Name    Provisioner Name    Scenario Name    Created    Converged\n---------------  ---------...i-node       false      false\ninstance-2       docker         ansible             multi-node       false      false\n'
> 

I did try to research the subject a lot online but I was not able to find any solution that would allow me to disable or customize when abbreviation happens, to make the limit upwards.

I raised this to PyTest because I am looking for a solution that can enable this at the entire test-suite and not on a specific file with tests, being able to do it globally is key for big projects.

Some resources I found:
* https://stackoverflow.com/questions/50608443/how-do-i-get-pycharm-to-show-entire-error-diffs-from-pytest -- I was not able to find a way to hack DEFAULT_MAX_CHARS 
* https://stackoverflow.com/questions/38000993/how-can-i-get-my-assertions-in-pytest-to-stop-being-abbreviated-with-ellipsis

**Comment by blueyed** [comment]
Try `env CI=true …`.
(It is an annoying thing, I know - there are some issues/ideas in that regard open already)
Related: https://github.com/blueyed/pytest/pull/63

**Comment by ssbarnea** [comment]
One year later and I am facing again the same issue, a bug caused by an incomplete feature, one that cannot be disabled, the truncation.

Can we please do something about it? For some projects this is testing PITA as the comparisons are almost always bigger than the limit and the user is left clueless to face the `what is behind those ellipses?` questions.

**Comment by nicoddemus** [comment]
Indeed this is frustrating, thanks @ssbarnea for bringing it to light again.

I've opened #9391 as an attempt to fix this, feedback welcome.

**Comment by ssbarnea** [comment]
I think it was #8391

**Comment by nicoddemus** [comment]
Oops yes, fixed my comment.

**Comment by ssbarnea** [comment]
@nicoddemus I think that we need to reopen this issue because current behavior is still not ok. I found multiple similar unanswered question online such https://stackoverflow.com/questions/38000993/how-can-i-get-my-assertions-in-pytest-to-stop-being-abbreviated-with-ellipsis 

IMHO, I think that we need to make these values configurable regardless of the verbosity level, especially as we know that changing general verbosity level has other side effects.

My opinion is that most people would want to run in minimal verbosity level (especially) on ci but have verbose errors for failed tests.

If I run in verbose by default displaying the console log in the browser can be problematic, true for github actions and also most CI/CD system I know (none behaves nice with very long console logs).

**Comment by bluetech** [comment]
@ssbarnea Check out https://docs.pytest.org/en/stable/reference/reference.html#confval-verbosity_assertions, added in pytest 8.

**Comment by ssbarnea** [comment]
@bluetech That issue seems to never want to be go away... :p --- I tried, still same output with ellipses, in fact even calling `pytest -vvvv` does ellipsis....

```toml
[tool.pytest.ini_options]
verbosity_assertions = 4
verbosity_test_cases = 4
```

Output:
```
>       assert len(results) == len(expected), results
E       AssertionError: [[no-tabs] (Most files should not contain tabs.) matched examples/playbooks/rule-no-tabs.yml:10 Task/Handler: Foo, [no...hould not contain tabs.) matched examples/playbooks/rule-no-tabs.yml:37 Task/Handler: Should not trigger no-tabs rules]
E       assert 3 == 2
E        +  where 3 = len([[no-tabs] (Most files should not contain tabs.) matched examples/playbooks/rule-no-tabs.yml:10 Task/Handler: Foo, [no-tabs] (Most files should not contain tabs.) matched examples/playbooks/rule-no-tabs.yml:13 Task/Handler: Key has a tab, [no-tabs] (Most files should not contain tabs.) matched examples/playbooks/rule-no-tabs.yml:37 Task/Handler: Should not trigger no-tabs rules])
E        +  and   2 = len((13, 'Most files should not contain tabs.'))
```

**Comment by nicoddemus** [comment]
Sorry folks, seems we dropped the ball on this on. Opened #12662 with a proposed fix.

**Comment by ncoghlan** [comment]
Thanks @nicoddemus!

I agree that combined with the previous reference to https://docs.pytest.org/en/stable/reference/reference.html#confval-verbosity_assertions that change should cover both this issue and #12307
