### ISSUE TITLE
[Question] Any way to force internally loaded plugins to run last?

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#6683]
Hi, when loading internal plugins through the pytest_plugins=[] in a conftest.py, is there anyway to set an explicit plugin should be run **last** explicitly?  

We have 15+ internal plugin(s) and we now need one of them to be guaranteed last to execute, is this possible?

**Comment by RonnyPfannschmidt** [comment]
typically order is enforced primarily by the hook markers and secondary by the  loading/declaration order
van you outline a example of what you mean in more detail?

**Comment by symonk** [comment]
Hi @RonnyPfannschmidt thanks

Lets say we have the following:

```
plugin_one.py
plugin_two.py
plugin_three.py
`

every one of these plugins has something like the following:

```
@pytest.mark.trylast
def pytest_configure(config):
    pass
```

conftest.py then loads:

```
pytest_plugins = ['plugin_one', 'plugin_two', 'plugin_three']
```

Along comes plugin_four and we have to guarantee that its pytest_configure will be explicitly last, 4/4 to execute - how do we achieve that with internal plugins?

**Comment by Zac-HD** [comment]
Closing this issue as an inactive question.  We recommend using the [`pytest` tag on stackoverflow](https://stackoverflow.com/questions/tagged/pytest).
