### ISSUE TITLE
[Question] Is it possible to deregister a plugin inside pytest_configure based on logic?

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#6688]
Hi, we have a lot of internally loaded plugins loaded through a conftest.py `pytest_plugins=['']`

Lets say we want to do some logic on a run, and if A or B is true, we want to completely disable one or multiple of these plugins; how do we achieve that?

example plugin:

```python
@pytest.mark.tryfirst
def pytest_configure(config):
    if 10 != 11:
        # completely disable or deregister this plugin for the rest of the run
        # no hooks should be running, pytest_unconfigure shouldn't even be running?
```

I have tried everything I can think of with no avail, could someone who knows the pytest core better advise me on how this works?  -p can't play a part here because we will only know at runtime which plugins we don't want to be running

**Comment by nicoddemus** [comment]
Hi @symonk,

Did you try to unregister said plugin? You can use `config.pluginmanager.unregister("myplugin")` for that.

**Comment by symonk** [comment]
@nicoddemus it doesnt seem to work in our internal plugins; can you give an example of 1) Where to put such code (in which hook of the internal plugin) and B) an of disabling one?

Thanks!

**Comment by RonnyPfannschmidt** [comment]
i would generally suggest to have a plugin object that's either registered  or not based on logic (like the lastfailed plugin inside pytest core,deregistring another plugin on logic can be icky

is there a larger surrounding use-case (and perhaps no direct control over the plugin you want out)

**Comment by symonk** [comment]
no but we have about 20+ internalyl loaded plugins for doing various things across our test stack in our automation framework that we wrote ourselves, we are doing a lot of early returning in configure/unconfigure based on logic, but im wondering how we can just tell the run 'hey - dont load this internal plugin whatsoever if XYZ is true'

**Comment by symonk** [comment]
Oh i see @RonnyPfannschmidt a similar example here:

`https://github.com/pytest-dev/pytest/blob/master/src/_pytest/stepwise.py` we can actually create an object and pass it in directly? we didnt know that!

**Comment by blueyed** [comment]
@symonk 
Yes, that basically only creates and registers the real plugin when necessary.
See also the debugging plugin: https://github.com/blueyed/pytest/blob/974be8e6b323d4982b3b9a4da45b9babbb9f44bf/src/_pytest/debugging.py#L60-L73

**Comment by blueyed** [comment]
Closing as answered.
