### ISSUE TITLE
howto check for misused boolean

### ISSUE THREAD

**Issue by ReimarBauer** [pytest-dev/pytest#6693]
Hi there,

I have some old code and I want to show by a test where always 1,0 is used as boolean.
Probably this is still a lot used and maybe someone had already an idea how to make the
inspection of the methods and show that as failure.

Thx for helping
Reimar

**Comment by bluetech** [comment]
Hi @ReimarBauer, could you provide an example of what you'd like to achieve? Like an example of a test and what you would want it to display/do.

**Comment by ReimarBauer** [comment]
We are not that bad with usage of integer as boolean, but I don't want to do this sometimes again, so the idea is to backup the changes by a test. 

For example if I use Display(visible=0, size=(1280, 1024)) and it is meaned by its definition as boolean https://github.com/ponty/PyVirtualDisplay/blob/master/pyvirtualdisplay/display.py#L22
I want to know how I can get a test finding this. Is this even possible?

for reference
https://bitbucket.org/wxmetvis/mss/issues/525/refactor-correct-usage-of-boolean-and

**Comment by RonnyPfannschmidt** [comment]
@ReimarBauer at first glance i would say that mypy might be the perfect tool to find that kind of misuse globally
