### ISSUE TITLE
How to test raises with cause?

### ISSUE THREAD

**Issue by alegonz** [pytest-dev/pytest#6694]
Hello, 

Thank you for the great testing library :)

This is more of a question than a bug/suggestion. I'd like to know if there is a way to test that a piece of code raises an exception with some specific cause (i.e. it did `raise foo from bar`)?

Perhaps something like?
```python
with pytest.raises(RuntimeError, cause=TypeError):
    ...
```

I couldn't find a way to do this so I concocted my own function shown below, but it feels hacky, and I was wondering if there exists a more proper/official/recommended way of doing this.

```python
from _pytest.python_api import RaisesContext
from pytest import fail

class RaisesWithCause(RaisesContext):
    def __init__(self, expected_exception, expected_cause, message, match_expr=None):
        super().__init__(expected_exception, message, match_expr)
        self.expected_cause = expected_cause

    def __exit__(self, exc_type, exc_val, exc_tb):
        if super().__exit__(exc_type, exc_val, exc_tb):
            if exc_val.__cause__ is None:
                fail(self.message)
            if isinstance(exc_val.__cause__, self.expected_cause):
                return True
        return False


def raises_with_cause(expected_exception, expected_cause):
    message = "DID NOT RAISE {} WITH CAUSE {}".format(
        expected_exception, expected_cause
    )
    return RaisesWithCause(expected_exception, expected_cause, message)

def test_foo():
    with raises_with_cause(RuntimeError, TypeError):
        ...
```

**Comment by bluetech** [comment]
The way to do this now is:

```py
with pytest.raises(RuntimeError, cause=TypeError) as excinfo:
   ...
assert isinstance(excinfo.value.__cause__, TypeError)
```

Adding a `cause` shortcut might be nice. However, there are several three different cases for such an argument:

1. Check that there is no cause.
1. Check the direct cause only.
1. Check the cause anywhere in the chain.

And there is also the distinction between explicit cause and cause with `__suppress_context__ = False`  etc. This makes me prefer checking the exception object directly, since it doesn't require checking what the argument does exactly.

**Comment by alegonz** [comment]
Thank you, @bluetech .

I believe you meant this, right? (without the `cause` argument)

```python
with pytest.raises(RuntimeError) as excinfo:
    ...
    assert isinstance(excinfo.value.__cause__, TypeError)
```

I had forgotten to consider the case of more than two chained exceptions, and wasn't aware of the `__suppress_context__` attribute. In my case I don't need to consider such cases so what you suggested is enough.

**Comment by bluetech** [comment]
> I believe you meant this, right?

Right :)

**Comment by suhasdotcom** [comment]
Hi Team and @bluetech,
I searched the internet for a better/recommended way to handle `from` clause when checking for chained exceptions but couldn't find one, so I incorporated @alegonz's suggestion into my tests:
> Thank you, @bluetech .
> 
> I believe you meant this, right? (without the `cause` argument)
> 
> ```python
> with pytest.raises(RuntimeError) as excinfo:
>     ...
>     assert isinstance(excinfo.value.__cause__, TypeError)
> ```
> 
> I had forgotten to consider the case of more than two chained exceptions, and wasn't aware of the `__suppress_context__` attribute. In my case I don't need to consider such cases so what you suggested is enough.

I think this can be done in some way which does look recommended, like so,
```python
with pytest.raises(TheBaseException):
    with pytest.raises(TheNextExceptionWithCause):
        with pytest.raises(LastExceptionWithCause):
            # some code that raises exceptions in such fashion:
            # raise LastExceptionWithCause from TheNextExceptionWithCause from TheBaseException
```
Here I am assuming that `pytest.raises` will raise an exception if the exception has a `__cause__ `defined.

But again, this is just my suggestion. 

Do we have a new recommended way to check chained-exceptions in pytest now?
