### ISSUE TITLE
Pass the value from the test to the called fixture

### ISSUE THREAD

**Issue by AyushiRautela** [pytest-dev/pytest#6695]
- [ ] a detailed description of the bug or suggestion

test creates an id at the run time which is to be passed to the called fixture for the cleanup.  an example can be found below

- [ ] output of `pip list` from the virtual environment you are using : 

```
Package                  Version
------------------------ ----------
allure-pytest            2.8.6
allure-python-commons    2.8.6
appdirs                  1.4.3
atomicwrites             1.3.0
attrs                    19.3.0
beautifulsoup4           4.8.2
build                    1.0.2
cached-property          1.5.1
cachetools               4.0.0
cefpython3               66.0
certifi                  2019.11.28
chardet                  3.0.4
colorama                 0.4.3
comtypes                 1.1.7
defusedxml               0.6.0
discovery                0.0.4
geoip2                   3.0.0
google-api-python-client 1.7.11
google-auth              1.10.0
google-auth-httplib2     0.0.3
google-auth-oauthlib     0.4.1
httplib2                 0.15.0
idna                     2.8
isodate                  0.6.0
jsonpath                 0.82
jsonpickle               1.2
lxml                     4.4.2
maxminddb                1.5.2
more-itertools           8.0.2
oauthlib                 3.1.0
packaging                19.2
pip                      20.0.2
pluggy                   0.13.1
pretend                  1.0.9
py                       1.8.1
pyasn1                   0.4.8
pyasn1-modules           0.2.7
PyHamcrest               1.9.0
pyparsing                2.4.6
pytest                   5.3.2
pytz                     2019.3
pywin32                  227
pywinauto                0.6.7
requests                 2.22.0
requests-oauthlib        1.3.0
requests-toolbelt        0.9.1
rsa                      4.0
selenium                 3.141.0
setuptools               41.2.0
six                      1.13.0
soupsieve                1.9.5
uritemplate              3.0.1
urllib3                  1.25.7
wcwidth                  0.1.7
webservice               0.3
xmltodict                0.12.0
zeep                     3.4.0
```

- [ ] pytest and operating system versions: platform win32 -- Python 3.8.0, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
- [ ] minimal example if possible:

```py
@pytest.fixture()
def api_setup_cleanup():
    login_results = get_apilogin_results
    yield login_results

# please share the inputs on how do I get the value of the id generated by the below test here in teardown?

@pytest.mark.tags("smoke")
def test_this(api_setup_cleanup):
    login_result = api_setup_cleanup

    # below id gets generated at the run time
    id = api_call_response
```

**Comment by viralmutant** [comment]
I think with `yield` in fixture, you should be able to just `send` values back to it like with python `generators`

While there might me more elegant solutions to it :), the following is one way this could work

```
@pytest.fixture
def api_setup_cleanup():
    login_results = [1,2,3]    # Just a sample input
    cleanup_list = None
    def _inner():
        nonlocal cleanup_list
        cleanup_list = yield login_results
    yield _inner
    #Add cleanup code here
    print(cleanup_list)

@pytest.mark.tags("smoke")
def test_this(api_setup_cleanup):
    inner = api_setup_cleanup()
    login_result = next(inner)

    # Work with the values from fixture
    print(login_result)

    # below id gets generated at the run time
    # id = api_call_response
    id = [7,8,9]    # This is just a sample output

    # Call the cleanup within try...except and pass StopIteration error
    try:
        inner.send(id)
    except StopIteration:
        pass
```

**Comment by RonnyPfannschmidt** [comment]
A common solution is to either have the fixture yield a callable that handles creation and cleanup registration

Or an object that provides test run integrated crud +cleanup

**Comment by viralmutant** [comment]
> A common solution is to either have the fixture yield a callable that handles creation and cleanup registration

I didn't understand this. Isn't the handling of creation/cleanup generally the job of a fixture ? Should it yield another callable ?

**Comment by RonnyPfannschmidt** [comment]
When the fixture is in charge of cleanup, but not creation, the common way to solve is to have the fixture value be a registration function or a object that manages resources and is torn down at fixture teardown

**Comment by AyushiRautela** [comment]
> ```python
> nonlocal cleanup_list
> ```

Thank you so much for the solution. Providing the code snippet helped a lot. Thanks again for taking out time for the same.
Now I am able to pass in the value from test to fixture but after the fixture gets the value from test it starts the cleanup. I require the cleanup/teardown to be executed only after the test execution is completed or after an exception occurs. Please do let me know of any inputs here, if possible. Below is what I tried.

Fixture:
@pytest.fixture()
def api_setup_cleanup():
    login_results = get_apilogin_results
    cleanup_data = []
    def _cleanup():
        nonlocal cleanup_data
        cleanup_data = yield login_results
    yield _cleanup
# Please share your inputs on how to handle execution of the below statements only after the test execution is completed or after an exception is thrown
    if len(cleanup_data) != 0:
        id1 = cleanup_data[0]
        id2 = cleanup_data[1]  

Test:

def test_thisapi_setup_cleanup
    inner = api_setup_cleanup
    login_result = next(inner())
    print(login_result)
    id = ['7', '8']
    try:
        c = inner()
        next(c)
        c.send(id)
    except StopIteration:
        pass

**Comment by AyushiRautela** [comment]
> > ```python
> > nonlocal cleanup_list
> > ```
> 
> Thank you so much for the solution. Providing the code snippet helped a lot. Thanks again for taking out time for the same.
> Now I am able to pass in the value from test to fixture but after the fixture gets the value from test it starts the cleanup. I require the cleanup/teardown to be executed only after the test execution is completed or after an exception occurs. Please do let me know of any inputs here, if possible. Below is what I tried.
> 
> Fixture:
> @pytest.fixture()
> def api_setup_cleanup():
> login_results = get_apilogin_results
> cleanup_data = []
> def _cleanup():
> nonlocal cleanup_data
> cleanup_data = yield login_results
> yield _cleanup
> 
> # Please share your inputs on how to handle execution of the below statements only after the test execution is completed or after an exception is thrown
> ```
> if len(cleanup_data) != 0:
>     id1 = cleanup_data[0]
>     id2 = cleanup_data[1]  
> ```
> 
> Test:
> 
> def test_thisapi_setup_cleanup
> inner = api_setup_cleanup
> login_result = next(inner())
> print(login_result)
> id = ['7', '8']
> try:
> c = inner()
> next(c)
> c.send(id)
> except StopIteration:
> pass

**Comment by viralmutant** [comment]
> Please share your inputs on how to handle execution of the below statements only after the test execution is completed or after an exception is thrown

I had already warned that my earlier approach was not elegant and a bit hacky :)

Now that the experts have spoken, here is another approach based on the advice

```python
class Data():
    '''
    This is the class to store inputs generated by fixtures
    And the results generated by test for cleanup
    '''
    def __init__(self, login_results):
        self.login_results = login_results
        self.cleanup_list = []

    def teardown(self):
        if self.cleanup_list:
            print("Cleaning up: ", self.cleanup_list)
            self.cleanup_list.clear()

@pytest.fixture
def api_setup_cleanup(request):
    login_results = [1,2,3]    # Just a sample input
    testdata = Data(login_results)
    request.addfinalizer(testdata.teardown)
    return testdata

@pytest.mark.tags("smoke")
def test_this(api_setup_cleanup):
    # Work with the values from fixture
    print(api_setup_cleanup.login_results)

    # below id gets generated at the run time
    # id = api_call_response
    id = [7,8,9]    # This is just a sample output
    api_setup_cleanup.cleanup_list = id
    assert 0         # Advertise that even if the test fails, cleanup resumes with values
```
Just make sure that your tests stores the values to be cleaned up before any possible error is raised

**Comment by RonnyPfannschmidt** [comment]
that first draft is closer in direction and while technically correct, i would still suggest to give it a few iterations and the api's op uses to ensure its "beautiful" in terms of the underlying api and ensures correct usage is easy and incorrect usage is hard/impossible

**Comment by AyushiRautela** [comment]
Thank you so much everyone for your valuable inputs. Special thanks to @viralmutant for providing the code snippet. It helped a lot.
This is exactly what was required. It works, I am closing the issue.
