### ISSUE TITLE
Is "-s" visible as a fixture?

### ISSUE THREAD

**Issue by jsn1993** [pytest-dev/pytest#6718]
Hi all,

I wonder if I can enable/disable my own printing facilities based on whether the "-s" option is passed to pytest command line, as muting the printing still doesn't get rid of the overheads of printing (in my case very high ...). Is "-s" observable through some fixture or hacks? Or is it possble
to know the exact command line that invoked the test, so that I can search for "-s" on my own?

```python
def test(print_on):
  if print_on: print(xxx)
```

This is what I found in pytest source code. 
```python
    group._addoption(
        "-s",
        action="store_const",
        const="no",
        dest="capture",
        help="shortcut for --capture=no.",
    )
```

Thanks,
Shunning

**Comment by nicoddemus** [comment]
Hi @jsn1993,

Try using `pytestconfig`

```python
def test(pytestconfig):
  if pytestconfig.getoption("capture") != "no": print(xxx)
```

**Comment by jsn1993** [comment]
> Hi @jsn1993,
> 
> Try using `pytestconfig`
> 
> ```python
> def test(pytestconfig):
>   if pytestconfig.getoption("capture") != "no": print(xxx)
> ```

Thanks for the quick answer. It seems like the -s option won't change for a single Python execution, so is it possible to do it without fixture?

```python
def test():
  if pytestxxx.getoption("capture") != "no": print(xxx)
```

**Comment by nicoddemus** [comment]
> won't change for a single Python execution

What you mean, you are not running this with `pytest`?

**Comment by jsn1993** [comment]
Sorry I mean I prefer not to add fixture to every test function. Instead I wonder if it’s possible to get it without the fixture.

**Comment by nicoddemus** [comment]
Oh I see, no currently there's no "global" access to pytest properties (we deliberately removed that support because it brought many initialization issues).

**Comment by jsn1993** [comment]
ok!

**Comment by jsn1993** [comment]
Thanks guys!
