### ISSUE TITLE
Transition open PRs from the features branch to master

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#6719]
As part of #6571, we want to delete the `features` branch, but there are some open PRs against it. This is the list: https://github.com/pytest-dev/pytest/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3Afeatures

I've asked all of the submitters to rebase on `master`. Once the list becomes empty, we can do the deletion.

**Comment by nicoddemus** [comment]
Thanks, I like how you took the time to write a short message to each PR. 👍

**Comment by nicoddemus** [comment]
Btw we might consider just changing the target of the PRs ourselves, that's what I did in https://github.com/pytest-dev/pytest/pull/6410 and didn't have any repercussions there.

**Comment by bluetech** [comment]
I thought I'd give the authors a chance to do it themselves, but after some time we can switch it ourselves. ATM there are 4 PRs left.

**Comment by nicoddemus** [comment]
Sounds good, should we give ourselves a "deadline"? How about Monday?

**Comment by bluetech** [comment]
Fine by me!

**Comment by bluetech** [comment]
@nicoddemus Oops, I remembered Sunday but you said Monday. Anyway, I've changed the remaning PRs manually and the list is clear now.

**Comment by nicoddemus** [comment]
No problem, all good then. 👍

**Comment by nicoddemus** [comment]
Just deleted `features` (was 4209ad6fcacb679d953f3dd6be96f330139006f0).
