### ISSUE TITLE
saving captured stdout to tempfile

### ISSUE THREAD

**Issue by cielavenir** [pytest-dev/pytest#6720]
I have tests with large amount of stdout. My tests fail rarely, but when failed I need to get the full log. It can be modeled like this:

```py
# --count=1000 (pytest-repeat)
def test_largeamountoutput(__pytest_repeat_step_number):
    for i in range(10000):
        print('%04d:'%i + '1234567890'*100)
    if __pytest_repeat_step_number==0:
        # I need to get the full log of this case
        assert False
```

Currently pytests holds all stdout in memory, so it can easily cause out of memory.
Is it possible to save stdout into tempfile and read them back at the end of pytest session?

**Comment by blueyed** [comment]
Use `--capture=fd` ?  (it uses real files)

**Comment by cielavenir** [comment]
After capture is done using real file for each test case, the output is gathered into memory. Please try my test script.

**Comment by blueyed** [comment]
Please provide the options you are using at least.
Have you tried `--capture=fd`?  Have you tried `-s` (`--capture=no) - in general, and/or redirecting that into a file?

**Comment by cielavenir** [comment]
`--capture=fd` is default, right? (and I have already stated `--count=1000` above)

anyway,

```
pytest --count=1000 test_largeamountoutput.py # huge memory consumption
pytest --capture=fd --count=1000 test_largeamountoutput.py # huge memory consumption
pytest --capture=no --count=1000 test_largeamountoutput.py # no memory issue
```

However, when I need to analyze the failure, I'd like to get the formatted output. `--capture=no` will disable it.

**Comment by cielavenir** [comment]
sorry I forgot to write environment:

Debian 9
Python 2.7.13 (pytest 3.10.1 / 4.6.9)
Python 3.6.1 (pytest 3.10.1 / 5.3.5)

Reproducible on all these 4 pytest patterns.

**Comment by cielavenir** [comment]
I suppose this `rep.sections.append(("Captured stdout", out))` causes out (stdout as string) to memory named rep.
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/capture.py#L236

**Comment by blueyed** [comment]
Good guess, but that should only affect output of collection.
Likely more here: https://github.com/pytest-dev/pytest/blob/d18c75baa3a461fdc4e7a7513c852dbf4d5b38d0/src/_pytest/capture.py#L222

A quick idea might be to not collect it in the first place if it is not going to be displayed anyway (i.e. for non-failures).

**Comment by Zac-HD** [comment]
(Probably worth noting that we only support Pytest 5 now; we may accept PRs for 4.6 for a few more months by 3.x is totally unsupported)

**Comment by cielavenir** [comment]
@blueyed I found that https://github.com/cielavenir/pytest/commit/ece7cc76b1d7bbb27d2bd43a22255e4b175971cf worked for my usage.

... I knew some of pytest-devs don't like this way.
