### ISSUE TITLE
Separate terminal verbosity from diff verbosity

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#6723]
Currently `-v` controls both terminal verbosity (how to display test session progress in the terminal) and diff verbosity (how verbose is our diffs when assertions fail).

I've often wanted to increase diff verbosity while also keeping terminal verbosity at the normal level, but this is not possible today.

## Proposal

Introduce a *new* option that controls only *diff* verbosity (for discussion here `-dv`, but please let's bikeshed on this).

For backward compatibility reasons, `-v` keeps controlling both terminal verbosity *and* diff verbosity, but `-dv` can be used to increase diff verbosity independently. 

* `-v`: when used, increase both terminal verbosity and diff verbosity.
* `-dv`: when used, increase diff verbosity only (we also need the equivalent of `-q` for diff verbosity).

With `-dv` in place, we might even consider changing to a higher level of diff verbosity in the future by default, but that remains to be seen.

Related: #6292, #5192

**Comment by blueyed** [comment]
I have `assert_truncate_level` already (https://github.com/blueyed/pytest/pull/63), but it only affects the truncation of lines (which is related to diffs / what you want, but yet another knob in this regard).

I'm planning to have something like `assert_verbosity_level` that would be added/substracted from `verbosity` for all of the assertion rewriting (including truncating lines - I will likely remove `assert_truncate_level` then, or keep it (based on `assert_verbosity_level` then)).

This could also default to "auto", which means that it would be 2 for running on CI.


> Related: #6292, #5192

https://github.com/pytest-dev/pytest/issues/5192 is a bug, not really related to having the option / control for it.
https://github.com/pytest-dev/pytest/issues/3962 is related however.

**Comment by bluetech** [comment]
I almost always use `-v`/`-vv` just the get the full diff, and in these cases I always prefer not to increase the terminal verbosity. So :+1: from me.

---

Will the `diff is truncated, to see full diff pass -v` message be changed to the new flag?

---

How does the parsing of `-dv` work? Is `-d` a flag that just modifies what `-v` does? I think this doesn't compose very well, e.g. if I have `pytest -dv long_test_name`, and I want terminal verbosity, I expect to be able to just quickly jump to the end of the line and append `-v`, but it wouldn't work. So I prefer to just have `-d` and `-dd` as standalone flags.

> With -dv in place, we might even consider changing to a higher level of diff verbosity in the future by default, but that remains to be seen.

In that case there will also need to be a flag to decrease the default verbosity, so should consider it in the bikesheding.

**Comment by strokirk** [comment]
Adding this as a config option (rather than a CLI-flag) as a first step would work well for me, since I almost always want the highest level of verbosity for tests.

**Comment by iliakur** [comment]
Is there still interest in this? I use `-v` almost exclusively for diffs and find the extra terminal output rather distracting, so I'm quite motivated to tackle this.

I'm a bit strapped for time, however, and I'm not very experienced with the codebase so will likely need guidance.

**Comment by nicoddemus** [comment]
@iliakur thanks for volunteering! Yes definitely there's still interest in this.

Beside the original post, we also need to consider the remarks in https://github.com/pytest-dev/pytest/issues/6723#issuecomment-585688033.

> I'm a bit strapped for time, however, and I'm not very experienced with the codebase so will likely need guidance.

Sure, we are glad to provide it. To get you started, you can see that `-v` is declared here:

https://github.com/pytest-dev/pytest/blob/ced125ad153bb3e24710ad478b8986147f9b1a5d/src/_pytest/terminal.py#L114-L123

And is used like this throughout the codebase:

https://github.com/pytest-dev/pytest/blob/ced125ad153bb3e24710ad478b8986147f9b1a5d/src/_pytest/terminal.py#L773-L775

So we need to review everywhere the option is used and adapt it for the new flags (which we still need to decide precisely).

**Comment by iliakur** [comment]
@nicoddemus should this be closed as implemented by #11387?

**Comment by nicoddemus** [comment]
Sure, thanks for the ping!
