### ISSUE TITLE
Bug - Error for calling fixtures directly but I am doing it the instructed way

### ISSUE THREAD

**Issue by suityou01** [pytest-dev/pytest#6731]
I have a small project, with this structure

    dir_a/
        target.py
    test/
        conftest.py
        test.py
    venv/

I am running pytest 5.3.5 on Python version 3.6.9 on Ubuntu 18.04

In conftest.py I have a shared function that sets up a db connection using sql alchemy. The target is passed in an engine object via the constructor.

conftest.py

    #!/usr/bin/env python

    """ Shared test functions, such as db_engine that creates a db_engine from sqlalchemy for the 
    target tests"""

    import pytest

    @pytest.fixture(scope="module")
    def db_engine():
        """Create a SqlAlchemy DB Engine for use in test fixtures"""
        from sqlalchemy import create_engine
        import os
        from dotenv import load_dotenv
        
        print("db_engine called")
        load_dotenv()
        db_url = os.getenv("sqlalchemy_test_db_url")
        
        """Create alchemy DBEngine"""
        return create_engine(db_url,
                                encoding='latin1', echo=True)

And my test.py looks like this

    import pytest
    from dirA import Target

    class TestTarget:
   
    def test_creates(self, db_engine):   #NB Not calling the fixture directly
         """Demonstrate it is possible to create an instance of the target"""
         t = Target(db_engine)
        assert t is not None
        assert type(t) == type(Target)

As you can see, I am not calling the fixture directly, it is an argument for my test fixture.

Yet I get the following error

> Fixture "db_engine" called directly. Fixtures are not meant to be called directly,
> but are created automatically when test functions request them as parameters.
> See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
> https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update  your code.

**Comment by RonnyPfannschmidt** [comment]
please show the actual traceback, with the redacted version its not obvious that anything is wrong

**Comment by blueyed** [comment]
Try it with `--fulltrace` - I think there is not much there otherwise (https://github.com/blueyed/pytest/blob/15cea2ece435c63f69884b4e1b46ea22d3fa5ac2/src/_pytest/fixtures.py#L983-L992)

**Comment by blueyed** [comment]
Note: indentation looks at least a bit off - sp make sure that the example reflects what you really have also.

```python
class TestTarget:

def test_creates(self, db_engine):   #NB Not calling the fixture directly
     """Demonstrate it is possible to create an instance of the target"""
     t = Target(db_engine)
    assert t is not None
    assert type(t) == type(Target)
```

**Comment by suityou01** [comment]
Thanks for the feedback. I have created a github that demonstrates the problem. I have pasted the output into the conftest.py as python multiline comments.

I have also included my virtual environment folder so you can see everything.

https://github.com/suityou01/pytestbug

**Comment by The-Compiler** [comment]
You're trying to use/call the fixture in a hook (`pytest_runtest_setup`). However, fixtures are "attached" to a test, while hooks in general are not - so you cannot use fixtures in hooks.

You might want to use a normal helper function, call that in the hook, and also have a separate fixture function which calls the helper.

**Comment by Zac-HD** [comment]
Closing this because as far as I can tell The-Compiler solved it above.
