### ISSUE TITLE
singledispatch decorator for test functions

### ISSUE THREAD

**Issue by alexcoca** [pytest-dev/pytest#6738]
Hi,

This is a suggestion about a functionality that would be nice to have in pytest. In Python 3, we can overload functions by using the `functools.singledispatch` decorator. It would be nice if something along the lines of 

```python
@pytest.mark.parametrize('x', (1, [2, 3, 4]))
@functools.singledispatch
def test_foo(x):

    raise NotImplementedError

@test_foo.register(int)
def _(x):
    assert isinstance(x, int)
@test_foo.register(list)
def _(x):
    assert isinstance(x, list)
```

I don't know if this is possible given the way fixtures work but it would simplify and make the testing code more maintainable. Currently this attempt fails with: 

```python
Traceback (most recent call last):
  File "/home/alex/anaconda3/envs/alibi/lib/python3.7/functools.py", line 837, in wrapper
    raise TypeError(f'{funcname} requires at least '
TypeError: test_foo requires at least 1 positional argument
```

This suggests that the fixtures aren't treated in the same as positional arguments and that to `functools` the test function appears not to have any arguments.

**Comment by asottile** [comment]
- my 2c: you're making your tests way too complicated if you need singledispatch to handle them
- workaround: call a function which itself uses singledispatch

**Comment by Zac-HD** [comment]
Along with \@asottile's objections, this sounds like a maintainence nightmare to me.  Fixtures are *already* complicated enough to cause a lot of problems (and ~20% of our open issues), and this would add another dimension of cases that everything would need to deal with (parametrize, fixtures, first- and third-party plugins, etc).

So IMO "call a function which uses `singledispatch`" resolves the issue.
