### ISSUE TITLE
Possible null pointer dereference in fixtures.py

### ISSUE THREAD

**Issue by huornlmj** [pytest-dev/pytest#6766]
https://github.com/pytest-dev/pytest/blob/7c09d88b72b3dd404167f537953582f2f24e1cc1/src/_pytest/fixtures.py#L910

Null-checking `self.cached_result` suggests that it may be null, but it has already been dereferenced on all paths leading to the check (at line 898).  (CWE-476: NULL Pointer Dereference)

**Comment by RonnyPfannschmidt** [comment]
a per https://github.com/pytest-dev/pytest/blob/7c09d88b72b3dd404167f537953582f2f24e1cc1/src/_pytest/fixtures.py#L864-L886 this asserts a invariant about a None value

there is no null pointer involved

what tool reports the "null" pointer

**Comment by huornlmj** [comment]
Coverity

**Comment by The-Compiler** [comment]
Coverity is wrong then :wink: - I'm a bit surprised it doesn't understand the code properly.

It's pretty clear this block isn't even entered when it is `None`:

https://github.com/pytest-dev/pytest/blob/7c09d88b72b3dd404167f537953582f2f24e1cc1/src/_pytest/fixtures.py#L897-L898

The assert checks that calling `self.finish(...)` set the value to `None`:

https://github.com/pytest-dev/pytest/blob/7c09d88b72b3dd404167f537953582f2f24e1cc1/src/_pytest/fixtures.py#L909-L910
