### ISSUE TITLE
How to execute (non-setup) part of the test only once

### ISSUE THREAD

**Issue by s-barannikov** [pytest-dev/pytest#6769]
Hi,

Let's assume I want to write a test for a compiler. The test is considered successful if:
1) the compiler is able to generate executable, and
2) the executable produces correct result for given input.

The test could look like this:

```python
@pytest.mark.parametrize('input,ref_output',
[
  (input_1, ref_output_1),
  (input_2, ref_output_2)
])
def test_1(input, ref_output):
  executable = compiler.compile(test_program_1) # Check (1)
  assert executable.run(input) == ref_output # Check (2)
```

I would like to avoid calling `compiler.compile` for each pair of `input, ref_output`, because the generated `executable` is always the same for same `test_program`, and generating the executable is a very time consuming operation.

What I could think of is to pull the compilation step into a module fixture, like this:

```python
@pytest.fixture(scope='module')
def executable_1():
  return compiler.compile(test_program_1) # Check (1)

@pytest.mark.parametrize('input,ref_output',
[
  (input_1, ref_output_1),
  (input_2, ref_output_2)
])
def test_1(executable_1, input, ref_output):
  assert executable_1.run(input) == ref_output # Check (2)
```

This works, but I think this is not are fixtures for. They should not do testing, and `compiler.compile()` is part of the test.

Also, there are multiple (N) `test_program`s, each of them has its own set of input / reference output data. Going this way, I would have to write N identical fixtures along with N test functions, and it is very easy to make a mistake when copy&pasting them with slight adjustments.

Is there a better / proper way to do this with pytest?

**Comment by Zac-HD** [comment]
I'd use [`functools.lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache) on the `compile` step - if you don't want to put that in your code, it could be a test-level constant:

```python
_caching_compiler = functools.lru_cache(maxsize=1)(compiler.compile)

@pytest.mark.parametrize('input,ref_output', ...)
def test_1(input, ref_output):
  executable = _caching_compiler(test_program_1) # Check (1)
  assert executable.run(input) == ref_output # Check (2)
```

Personally though I'd probably decorate the compile function with a small LRU cache - size 1 has a fairly small memory overhead, and makes repeated calls close to free; or stick with the default size of 128 and it will usually memorize all the frequent calls.

**Comment by s-barannikov** [comment]
I also considered caching the result of the compilation step, but was wondering if there is some pytestish way to achieve the same result. Thanks for clarifying it (and for the quick response).
