### ISSUE TITLE
how to fetch the "test_" method status in teardown(after each test method)

### ISSUE THREAD

**Issue by ravikiransandri** [pytest-dev/pytest#6780]
Hi,
I am trying to fetch the test method result post execution of each test method. For this I am using hook to do that but I am not able to fetch the results as per pytest test results i.e.,(xpass, xfail, fail, etc) But from the below code i am able to fetch the test result from report object but for the case where i am making test xfail i am able to fetch output as "skipped" but pytest is showing it as xfail.

Could you please help me out in fetching pytest test method output after each test execution. i.e., as xfail, xpass, pass, fail, error, etc

**Environment details:**
platform win32(Windows 10) -- Python 3.7.3, pytest-5.3.1, 

**conftest.py**

```python
import pytest
import os.path

@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    # execute all other hooks to obtain the report object
    outcome = yield
    print(f"{outcome}")
    rep = outcome.get_result()
    print(f"\n{rep}")
    if rep.when == "call":
        print(f'{rep.outcome}')
```

**test_file.py**

```python
import pytest
def test_fail1(tmpdir):
    assert False

def test_fail2():
    assert True

def test_fail3():
    pytest.xfail("Intenional")

def test_fail4():
    1/0
```

**Console Output:**
```
pytest test_file.py -s -v
.......
collected 4 items                                                                

testresults.py::test_fail1 <pluggy.callers._Result object at 0x000001A0E8A24860>

<TestReport 'testresults.py::test_fail1' when='setup' outcome='passed'>
<pluggy.callers._Result object at 0x000001A0E8F7E588>

<TestReport 'testresults.py::test_fail1' when='call' outcome='failed'>
failed
FAILED<pluggy.callers._Result object at 0x000001A0E8F7E438>

<TestReport 'testresults.py::test_fail1' when='teardown' outcome='passed'>

testresults.py::test_fail2 <pluggy.callers._Result object at 0x000001A0E8F7E438>

<TestReport 'testresults.py::test_fail2' when='setup' outcome='passed'>
<pluggy.callers._Result object at 0x000001A0E8F7E438>

<TestReport 'testresults.py::test_fail2' when='call' outcome='passed'>
passed
PASSED<pluggy.callers._Result object at 0x000001A0E8F7E438>

<TestReport 'testresults.py::test_fail2' when='teardown' outcome='passed'>

testresults.py::test_fail3 <pluggy.callers._Result object at 0x000001A0E8F7E588>

<TestReport 'testresults.py::test_fail3' when='setup' outcome='passed'>
<pluggy.callers._Result object at 0x000001A0E8F856D8>

<TestReport 'testresults.py::test_fail3' when='call' outcome='skipped'>
**skipped**
**XFAIL**<pluggy.callers._Result object at 0x000001A0E8F85BA8>

<TestReport 'testresults.py::test_fail3' when='teardown' outcome='passed'>

testresults.py::test_fail4 <pluggy.callers._Result object at 0x000001A0E8F85A58>

<TestReport 'testresults.py::test_fail4' when='setup' outcome='passed'>
<pluggy.callers._Result object at 0x000001A0E8F859B0>

<TestReport 'testresults.py::test_fail4' when='call' outcome='failed'>
**failed**
**FAILED**<pluggy.callers._Result object at 0x000001A0E8F7E668>

<TestReport 'testresults.py::test_fail4' when='teardown' outcome='passed'>


=================================== FAILURES ====================================
__________________________________ test_fail1 ___________________________________

tmpdir = local('C:\\Users\\Ravi\\AppData\\Local\\Temp\\pytest-of-Ravi\\pytest-60\\
test_fail10')

    def test_fail1(tmpdir):
>       assert False
E       assert False

testresults.py:3: AssertionError
__________________________________ test_fail4 ___________________________________

    def test_fail4():
>       1/0
E       ZeroDivisionError: division by zero

testresults.py:12: ZeroDivisionError
==================== 2 failed, 1 passed, 1 xfailed in 0.31s =====================
```

**Comment by surevs** [comment]
👍

**Comment by aklajnert** [comment]
Did you try this page? https://docs.pytest.org/en/latest/example/simple.html#making-test-result-information-available-in-fixtures

**Comment by ravikiransandri** [comment]
Hi @aklajnert ,
I have even tried mentioned above, I am facing a problem here is when i make the test case xfail using pytest.fail. with above code i see testcase as skipped but actually it is xfail as per pytest output

**Comment by RonnyPfannschmidt** [comment]
that one is a race condition, the outcome comes in as failed, and the rebranding to xfailed happens after the orposed plugin is triggered in your code

**Comment by aklajnert** [comment]
Sorry, I got confused. I did some digging in the code and I think that there might be a bug. 

In [this line](https://github.com/pytest-dev/pytest/blob/6a7df7f03165a3b802be07c835286dbcb6acc351/src/_pytest/skipping.py#L138) you can see that the `rep.outcome` is set to `skipped` on `xfail`. You can rely on the fact that the `rep.wasxfail` will be set to the `xfail` reason (`reason: Intentional` in your case). But that isn't happening when you reach the `xfail` state by triggering it manually.

**Comment by RonnyPfannschmidt** [comment]
i can understand that confusion, the xfail outcome is "normalized" to the extra attribute + passed or skipped or failed
i dont recall why it is done like that, it may be time to rethink outcomes and their indication

**Comment by aklajnert** [comment]
The `xfail` can be determined by a small workaround actually:
```python
xfail = rep.outcome == 'skipped' and hasattr(rep, 'wasxfail')
```

Maybe that will be useful.

**Comment by ravikiransandri** [comment]
Thanks for the observation and workarounds. Could you please fix the issue if it is a bug. Could we have this value easily accessible in teardown methods.

**Comment by Zac-HD** [comment]
Closing as answered by https://github.com/pytest-dev/pytest/issues/6780#issuecomment-590780774 above.
