### ISSUE TITLE
how to make `pytest.testdir` detect my new plugin

### ISSUE THREAD

**Issue by markshao** [pytest-dev/pytest#6811]
My Environment
- Description:	Ubuntu 18.04.3 LTS
- Python = 3.6.9
- Pytest Version = 5.3.5

I'm writing a new plugin , but fail to test using `pytester.testdir`  the file tree looks like this

> 

- testing
-- conftest.py
-- test_plugin.py
- visualizer
-- __init__.py
-- plugin.py

my test code looks like this 

```python
def test_webp_life_cycle(_testdir):
    _testdir.makepyfile(r"""
    import pytest

    def test_webp():
        assert True
    """)

    ret = _testdir.runpytest_subprocess("--visualizer")
    from pprint import pprint
    pprint(ret.outlines)
```

And the output as following

```python-traceback
.running: /home/markshao/code/pytest-visualizer/.env/bin/python -mpytest --basetemp=/tmp/pytest-of-markshao/pytest-21/test_webp_life_cycle0/runpytest-0 --visualizer
     in: /tmp/pytest-of-markshao/pytest-21/test_webp_life_cycle0
[]
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --visualizer
  inifile: None
  rootdir: /tmp/pytest-of-markshao/pytest-21/test_webp_life_cycle
```

Looks like the the inner pytest process doesn't load my plugin, I have the add_option inside plugin.py.

I don't know how to make the testdir fixture auto load my new plugin . I have investigated the **pytest-xdist** source code , it has done nothings on testdir but all works fine , could anyone help me ?

- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by Zac-HD** [comment]
(FYI I've fixed your code blocks; [see here for details](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks))

Is your plugin installed, and is the entry point configured?  Try importing it to check.

**Comment by markshao** [comment]
T

> (FYI I've fixed your code blocks; [see here for details](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks))
> 
> Is your plugin installed, and is the entry point configured? Try importing it to check.
@markshao

**Comment by markshao** [comment]
@Zac-HD thanks a lot.

the plugin not installed, it's under development , I run the test case inside the plugin code repo.

**Comment by markshao** [comment]
I try to reproduce the problem on `pytest-xdist` , but I'm confused.

Just clone the project and jjust install the requirement dependencies.  All the test cases passed without exception.  Looks like the `testdir` could detect the plugin at runtime .

**Comment by Zac-HD** [comment]
Depends on repo layout etc.; if you consistently install your plugin you should be fine.   See https://hynek.me/articles/testing-packaging/ for more details.

**Comment by markshao** [comment]
Find out the reason , it's my problem .  I forget when I use `pip install -e .` to install the dependency of `pytest-xdist` ,it will install the current package as the entry point inside the site-packages.

Retry it in my plugin , problem solved . Whateve thanks a lot again
