### ISSUE TITLE
Call pytest_collection_modifyitems in groups by args

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6827]
I think it would be good to call `pytest_collection_modifyitems` with groups of items by provided args.

That would solve the problem of not running `test_foo.py` tests first with `pytest test_foo.py test_bar.py`.

Given that this is a behavior change it could either be a new hook, or the hook would get passed a `final` argument, and would be called for each arg (including testpaths etc) with `final=False`, and with `final=True` in the end.

**Comment by RonnyPfannschmidt** [comment]
Please elaborate the use,, case, it doesn't make sense to me

We'd need a new hook for the machinery

**Comment by CarycaKatarzyna** [comment]
When I call ``pytest test_foo.py test_bar.py``, then `` test_foo`` is run first. Could you explain the purpose of this issue?

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of extra information
