### ISSUE TITLE
Feature Request: Specify named test functions, classes, or class.methods in a suite file to run

### ISSUE THREAD

**Issue by joshuatbadger** [pytest-dev/pytest#6862]
In a hypothetical test directory, I have some 300 tests, split among test classes and functions. In the command line calling the tests, I'd LOVE to specify a test suite file that has one test per line and only collect those tests for running.

Example contents of a test suite file:
`TestFoo` <- test class containing 7 tests
`TestBar.test_bar` <- single test method in test class
`test_baz` <- single function in a module

This file would collect 9 tests total.

The test names specified would have to match tests that would normally be picked up by Pytest's normal collection methods (matching whatever customizations made in the pytest.ini file, etc).

Additionally, perhaps a warning if a specified test(s) had the correct naming scheme, but failed to find a matching test?

**Comment by RonnyPfannschmidt** [comment]
currently this can be approximated by putting the test nodeids into the  file, then executing `xargs pytest < nodelist.txt`

the file would look roughly like
```
test_foo.py::TestFoo
test_bar.py::TestBar::test_bar
test_baz.py::test_baz
```

**Comment by joshuatbadger** [comment]
Oh, interesting. I missed that in the documentation. Where does it show
that?

**Comment by joshuatbadger** [comment]
Sorry, that was a dumb question. I realized after replying that xargs is
not a pytest flag, but its own utility. Wouldn't that simply run the pytest
multiple times, each with its own report? And wouldn't it be limited to
Unix-like systems? Meaning Windows is out?

That would make things like class-level fixtures behave like
function-level, too, right?

This seems like a poor approximation long-term, though I can certainly use
it in the interim.

**Comment by RonnyPfannschmidt** [comment]
@joshuatbadger the invocation i posted  would run it exactly  once

you you could also jsut invoke `pytest.main`  from python or create a simple selection/deselection/collection plugin that reconfigures the args to include the lines of a determined files

**Comment by joshbadgervstg** [comment]
Switching over to my work account, this is no longer a feature request, as I've come up with a simple system. However, now the reporting is incorrect.

```
# conftest.py
def pytest_collection_modifyitems(session, config, items):
    """
    Modify test collection to only include specified tests. Will run tests in order specified in the suite file,
    or leave the items list as-is without modifying order.
    Args:
        session: pytest session object, passed automatically
        config: pytest config object, passed automatically
        items: pytest items objects, passed automatically
    """
    if suite_fp := config.getoption('--suite-file', None):
        specified_tests = suite_info(suite_fp)
        unsorted_items = [
            item
            for item in items
            if item.location[-1] in specified_tests
            or item.location[-1].split('.')[0] in specified_tests
        ]
        items[:] = sort_test_order(specified_tests, unsorted_items)
        print(f'For now, ignore the next line reporting the number of tests collected. We will run {len(items)} tests')
```

This gets the tests I specify and only executes the tests I've asked for. HOWEVER, as you can see in the last line of that function, it also reports incorrectly. Running with a suite file specifying a single test class to run, I get the following output (this output used `--collect-only` to illustrate, but the result is otherwise the same when running the tests for real):

```
...
collecting ... For now, ignore the next line reporting the number of tests collected. We will run 2 tests
collected 98 items
<Package /Users/joshuabadger/Python_Projects/mobile_automation/automation/tests/apps/hea>
  <Module test_hea_basic_functionality.py>
    <Class TestHEABasicFunctionality>
        <Function test_login_gatekeeping>
        <Function test_login_no_sites>
============================ no tests ran in 0.20s =============================

Process finished with exit code 0

```

It correctly lists the module, class, and tests that my suite file has specified, but it still claims it collected 98 tests. What hook can I use to modify that so that it correctly reports `collected 2 items`?

**Comment by joshbadgervstg** [comment]
I ask because I'm building the tests for the framework I'm building itself and want to test the test selection as part of CI/CD, but running `testdir.inline_genitems('--suite-file', 'suite_file.suite')` still returns all tests collected, even if the displayed report reports similarly as above.

```
=================================== FAILURES ===================================
_ TestSuiteFileCollection.test_suite_file[classes_and_tests0-TestClassA\nTestClassB.test_method_b_2\nTestClassC.test_method_c_3\nTestClassC.test_method_c_2-6] _

self = <framework_tests.test_suite_file_collection.TestSuiteFileCollection object at 0x104a063d0>
testdir = <Testdir local('/private/var/folders/r6/zx_vsg6d0_18jg915m_08n240000gr/T/pytest-of-joshuabadger/pytest-60/test_suite_file0')>
default_timestamp = '2020_03_26_15_19_32'
classes_and_tests = {'A': 3, 'B': 2, 'C': 5}
suite_file_contents = 'TestClassA\nTestClassB.test_method_b_2\nTestClassC.test_method_c_3\nTestClassC.test_method_c_2'
expected_test_total = 6

    @pytest.mark.parametrize('classes_and_tests,suite_file_contents,expected_test_total', [
        ({'A': 3, 'B': 2, 'C': 5},
         'TestClassA\n'
         'TestClassB.test_method_b_2\n'
         'TestClassC.test_method_c_3\n'
         'TestClassC.test_method_c_2',
         6)
    ])
    def test_suite_file(self, testdir, default_timestamp, classes_and_tests, suite_file_contents, expected_test_total):
        """Verify the correct date gets attached to the record title based on the timestamp given"""
        # Build the test file to run
    
        test_file = self.build_test_classes_and_methods(classes_and_tests)
    
        testdir.makepyfile(
            test_file=test_file
        )
    
        # Create the suite file
        testdir.makefile('.suite', suite_file=suite_file_contents)
    
        # Build out the conftest.py file
        testdir.makeconftest(COLLECTION_CONF_FILE + build_pytest_flags('suite-file'))
    
        # Run the test
        results, hook_recorder = testdir.inline_genitems('--timestamp', default_timestamp,
                                                         '--suite-file', 'suite_file.suite')
    
        # Confirm all tests passed
        print(results)
>       assert len(results) == expected_test_total
E       assert 10 == 6
E         +10
E         -6

/Users/joshuabadger/Python_Projects/mobile_automation/framework_tests/test_suite_file_collection.py:88: AssertionError
=========================== short test summary info ============================
FAILED framework_tests/test_suite_file_collection.py::TestSuiteFileCollection::test_suite_file[classes_and_tests0-TestClassA\nTestClassB.test_method_b_2\nTestClassC.test_method_c_3\nTestClassC.test_method_c_2-6]
============================== 1 failed in 0.12s ===============================

Process finished with exit code 1
```
