### ISSUE TITLE
cleanup after test failure

### ISSUE THREAD

**Issue by stefanseefeld** [pytest-dev/pytest#6864]
My test code instantiates classes which require exclusive access to some resources (a socket at a given address, notably).
I regularly get into situations failing tests wouldn't properly clean up local objects, so subsequent tests fail simply because they can't instantiate the above class ("cannot bind server address
" and similar errors).
While I understand that Python doesn't give any guarantee of when / where objects are cleaned up, I wonder whether there are any techniques / idioms I could use to avoid such spurious failures.

**Comment by RonnyPfannschmidt** [comment]
The common way is to have a cleanup registry for the things you create in tests

**Comment by stefanseefeld** [comment]
Can you elaborate (or give an example) ?
Consider this (much simplified) code:
```
def test_device():
    tracker = Tracker()
    assert tracker.process()

def test_simulator():
    tracker = Tracker()
    ...
```
Please note that `Tracker` allocates some resources that prevents two concurrent Tracker objects to co-exist. Normally the above tests pass, but sometimes the first fails. And if it does, I get an error also running the second test, because the `tracker` object from the first test wasn't properly destroyed.
What can I do to forcefully clean up all the resources associated with a given test ?

**Comment by The-Compiler** [comment]
You'd normally use a pytest [fixture](https://docs.pytest.org/en/latest/fixture.html) to move your setup/teardown code out of your tests, also making your tests simpler/shorter in the process.

For your example, it could look something like this:

```python
@pytest.fixture
def tracker():
    tracker = Tracker()
    yield tracker
    tracker.cleanup()

def test_device(tracker):
    assert tracker.process()

def test_simulator(tracker):
    # ...
```

If `test_device` and `test_simulator` do the same thing essentially, you could also use a parametrized fixture to provide all of your tests with both a `SimulatedTracker` and a `DeviceTracker` object, so all tests would then run twice, once against the simulation and once against a real device.

**Comment by stefanseefeld** [comment]
OK, so moving the `Tracker` construction into a fixture might give me more control over its cleanup. But what if I really do want to construct the tracker in the test body, i.e. if the construction isn't part of the setup, but part of the test ?

**Comment by Zac-HD** [comment]
Then I'd use a context manager, like

```python
with Tracker() as t:
    ...
```

**Comment by stefanseefeld** [comment]
`Tracker` is a class from elsewhere that I want to test. Changing it to better control resources is out of scope. The more I think about it the more I wonder whether this couldn't considered a bug in pytest.

Consider this simplified example to highlight the essence of the issue:
```
class Singleton:
    busy = False
    def __init__(self):
        assert Singleton.busy == False  # only one instance allowed !
        Singleton.busy = True

    def __del__(self):
        Singleton.busy = False


def test_one():
    s = Singleton()
    assert False

def test_two():
    s = Singleton()
```

Two very simple tests allocate a resource, which may only be allocated once. Normally (i.e. without the `assert False` at the end of `test_one`, all goes well, as the resources are cleaned up properly after each test is run. But when `test_one` fails (as in the above sample code), it also fails to clean up its resources, and consequently `test_two` also fails (though the text itself, when run in isolation, passes !).

Shouldn't pytest make sure that tests are maximally decoupled from each other, i.e. that all resources are properly cleaned up between individual tests ? Is there any reason for the current behaviour ? Is this something that could be fixed ?
(I agree there are a few workarounds, including using explicit context managers, or moving resource allocation out of the test body into fixtures. They are all quite cumbersome and intrusive, as they may even alter the nature of the test. It would be better to have a built-in mechanism to achieve this, without having to add noise to the code.)
Don't you agree ?
