### ISSUE TITLE
test

### ISSUE THREAD

**Issue by ihsinme** [pytest-dev/pytest#6879]
- [ ] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by The-Compiler** [comment]
Hey @ihsinme! This repository is about a real project ([pytest](https://www.pytest.org/)) - please use a personal repository for testing things, as this repository is watched by >180 people who'll get a notification for every change :wink:
