### ISSUE TITLE
Commit 2e48c32dead052 broke the link to the cache fixture in the fixture list

### ISSUE THREAD

**Issue by kpinc** [pytest-dev/pytest#6883]
Hi,

The link to the cache fixture is broken in the list of fixtures at the top of:
https://docs.pytest.org/en/latest/fixture.html

I believe commit 2e48c32dead052 broke it.

Regards,
Karl

**Comment by dannysepler** [comment]
leaving https://github.com/pytest-dev/pytest/pull/6929 to address this

**Comment by bluetech** [comment]
Oops, seems like it didn't fix the issue. Now the link is hyperlinked but it doesn't reach the anchor: https://docs.pytest.org/en/latest/reference.html#std:fixture-cache

**Comment by dannysepler** [comment]
oops! sorry to hear that! i'd love to fix it for real :) but just for my own clarity, when i go to https://docs.pytest.org/en/latest/fixture.html and then click on the "cache" link it does take me to https://docs.pytest.org/en/latest/reference.html#std:fixture-cache -- is there a part of this bug i'm missing?

**Comment by bluetech** [comment]
You are right! I don't know why it didn't work for me before, but it works now.

**Comment by dannysepler** [comment]
woo hoo! you know, a similar thing happened to me. i wonder if our browsers saved a bit of html from the old version or something? anyway thanks for checking!

**Comment by blueyed** [comment]
Well, please review https://github.com/dannysepler/pytest/commit/2e48c32dead05221e7ad511e90bae183aff8d43c#diff-e4d471283fbb89846eea8d749ea2671e.

IIRC you've broken that one again now.
IIRC^2 the fixture is not called "cache" in the first place.
