### ISSUE TITLE
[Question/Guidance] Plugin development for run-once tasks when xdist is loaded?

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#6886]
Hi, I know its asked a lot but what is the 'official' / best practice for plugin development once xdist gets involved, could someone outline an approach where all slaves will not carry out the work also?

is it simply have only master register the plugin within pytest configure? slaves _would_ run the configure but not have the plugin as part of their run?

I am writing a pytest-infrastructure plugin for validating a stack/environment prior to test execution, but i only want to run it before all tests, once on the master node when xdist is involved.

1. What is the best practice to check if xdist is running?
2. What is the standard practice to prevent xdist slaves running the hooks etc

**Comment by symonk** [comment]
@nicoddemus any suggestions? :)

**Comment by RonnyPfannschmidt** [comment]
conditional enabling of plugins in generally done by adding them in a pytest configure,
if you always need the plugin anyway, but dont want it on workers, the best is to check for the xdist workerinput

also sorry for the delays, daycares are shut down ^^

**Comment by symonk** [comment]
no problem at all @RonnyPfannschmidt thanks for the response, firstly I hope you and your family are doing well at the current time.  So its just as easy as checking if its a slave; do not register the plugin? I like it thanks :)
