### ISSUE TITLE
schedule regular link-check

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#6894]
in #6892 we noted broken/outdated links
in order to get ahead of  that we should auto-trigger link-checking on a regular slow schedule

**Comment by The-Compiler** [comment]
I opened #12474 with a few more details. Maybe with improvements in the Sphinx link checker we could also discuss doing it for every PR or release. Taking the freedom to close this one instead of the other one as it has more context.
