### ISSUE TITLE
Ability to disable pygments highlighting even if pygments is installed

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#6906]
the [docstring mentions a `code_highlight` setting](https://github.com/pytest-dev/pytest/blob/93aa988e0152392c233acac1e24bf6db8a2772c7/src/_pytest/_io/__init__.py#L29) but it seems it was not implemented

I'd like to be able to disable the syntax highlighting for a couple reasons:
- the colors can be distracting
- I'd like to be able to disable them for the tests in [pygments-pytest](https://github.com/asottile/pygments-pytest) (currently failing)

**Comment by asottile** [comment]
`--color=no` disables this, but disables all colors so it doesn't quite do what I want

**Comment by gdhameeja** [comment]
I'd like to work on this. Since I'm kinda new to pytest, some guidance would be helpful.

**Comment by nicoddemus** [comment]
Hi @gdhameeja,

Thanks for taking interest in contributing to this!

The relevant code is here:

https://github.com/pytest-dev/pytest/blob/master/src/_pytest/_io/__init__.py

I think the correct approach would be to:

1. Add a new property to this class, say `code_highlight` which defaults to `True`.
1. Use the `code_highlight` property in the `_highlight` method accordingly.
1. Add a new `code_highlight` (what do you think @asottile?) configuration option here: 
   https://github.com/pytest-dev/pytest/blob/c26bbdfaf027d031e694227a2e3414108d17f1a8/src/_pytest/terminal.py#L77

1. Configure `tw.code_highlight` accordingly to the config option. 
  https://github.com/pytest-dev/pytest/blob/c26bbdfaf027d031e694227a2e3414108d17f1a8/src/_pytest/config/__init__.py#L1204
1. Add a test that ensures the option is respected:
   https://github.com/pytest-dev/pytest/blob/c26bbdfaf027d031e694227a2e3414108d17f1a8/testing/test_terminal.py#L2100 
   This class contains tests using color highlighting for tracebacks, you just need a new test which sets the `code_highlight` option to `False` and ensure the tracebacks doesn't have color (but only the tracebacks, other colors should still show up).

1. I think at this point it also makes sense to make `Pygments` a normal dependency? Either way we should still use a try/except in `io.__init__.py` so we fail if that dependency is not present.

1. Add docs for the new option at the bottom of this file in alphabetical order with the other options: https://github.com/pytest-dev/pytest/blob/master/doc/en/reference.rst

I think that's pretty much it. If I forget something no worries, we can discuss this over the PR. 👍

**Comment by asottile** [comment]
sounds good to me 👍

**Comment by gdhameeja** [comment]
Great, I shall take this up and try to finish it off.
@nicoddemus Thanks for the detailed explanation.

**Comment by gdhameeja** [comment]
> I think at this point it also makes sense to make Pygments a normal dependency? Either way we should still use a try/except in io.__init__.py so we fail if that dependency is not present.
I don't understand this part. We still seem to have the pygments imports in try/except in `io.__init__.py`.

**Comment by nicoddemus** [comment]
Just to make it an official dependency by adding it to this list:

https://github.com/pytest-dev/pytest/blob/ded30238f7d27861ee09ae5af945b3bee66779da/setup.py#L5-L16

Currently the user has to install `Pygments` manually to see colored tracebacks.

**Comment by bluetech** [comment]
Issue #6906 wants to allow to configure the pygments style. I'd think the two issues (turn on/off and configuring style) should probably be considered together.

**Comment by nicoddemus** [comment]
> be considered together.

You mean in the same PR, or in the same option?

**Comment by bluetech** [comment]
If the proposal to configure the style is accepted, it *might* make sense to use the same option. I mostly just wanted to bring it to attention before it's too late to consider (maybe it will affect the design).

**Comment by nicoddemus** [comment]
Makes, sense, but I think they should be two separate options, see https://github.com/pytest-dev/pytest/pull/6934#issuecomment-605508367.
