### ISSUE TITLE
Improve error message from bot

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#6911]
We probably need to improve that message... `python scripts/release.py failed` is not very helpful.

_Originally posted by @nicoddemus in https://github.com/pytest-dev/pytest/issues/6892#issuecomment-598272355_

**Comment by gdhameeja** [comment]
I can take this up. But I see we're already printing out the exception, any suggestions how we can make this more helpful?

**Comment by nicoddemus** [comment]
Thanks!

We probably need to catch all the output from the intermediate commands to add to the current message.

**Comment by gdhameeja** [comment]
Apologies. Just to clarify:
I'm assuming, by intermediate commands you mean:
```
        check_call(["git", "config", "user.name", "pytest bot"])
        check_call(["git", "config", "user.email", "pytestbot@gmail.com"])

        check_call(["git", "checkout", "-b", release_branch, f"origin/{base_branch}"])
        check_call([sys.executable, "scripts/release.py", version])
        check_call(["git", "push", oauth_url, f"HEAD:{release_branch}", "--force"])
```
In case you are referring to the above for checks, the subprocess docs say we should be using `run()` to capture the stderr output.
https://docs.python.org/3/library/subprocess.html#subprocess.check_call
Should we do that and capture the stderr output and add the same to the message?
Or am I completely misunderstanding what you mean by checks here?

**Comment by nicoddemus** [comment]
> Or am I completely misunderstanding what you mean by checks here?

No you got it correctly. 👍 

No problem changing this to use `subprocess.run()`, I used `check_call` as convenience, but definitely should have been using `subprocess.run()` from the start.

Btw, we should only post the error output of the command that failed, for example:

```python
        check_call(["git", "config", "user.name", "pytest bot"])
        check_call(["git", "config", "user.email", "pytestbot@gmail.com"])
        check_call(["git", "checkout", "-b", release_branch, f"origin/{base_branch}"])
```

If the `checkout` command fails, we should only post the output from that command, not the cumulative output from the previous two `config` commands too.
