### ISSUE TITLE
Suggestion: error output improvement

### ISSUE THREAD

**Issue by darrenburns** [pytest-dev/pytest#6921]
Hi 👋 I'm really enjoying the new improvements around test output/syntax highlighting as that's always been an area I felt has had room for improvement.

I was wondering what your thoughts were about adding a little bit of colour to the diff "error" output (i.e. the red lines that begin with the letter `E`)? I think it really helps draw your eyes to the information you care about after doing some experimenting with it in my own project. I'll just post some pictures to express my suggestion rather than trying to explain it:

This is the current output:
![Screenshot 2020-03-13 at 19 31 28](https://user-images.githubusercontent.com/5740731/76653954-bb7d3700-6561-11ea-88d4-54c219b5c98b.png)

My suggestion (I'm only suggesting the colours, not that we swap the ordering -- ignore that difference 😄):
![Screenshot 2020-03-13 at 19 51 38](https://user-images.githubusercontent.com/5740731/76654950-1748bf80-6564-11ea-93fd-39d3e0f1f0a6.png)

This could be disabled via a command line flag or config option.

Interested in hearing what the community thinks! :)

**Comment by nicoddemus** [comment]
Hi @darrenburns! 👋 

Oh definitely, adding syntax highlight to tracebacks is just the first step we plan to add. Coloring diffs is definitely something we have in mind, surely inspired by `pytest-clarity` and `ward`. 👍 

I believe right now we have to think how to properly integrate arbitrary coloring to text in our terminal writer. @blueyed has mentioned an idea of integrating with the Pygments streaming protocol, that's one idea.

**Comment by bluetech** [comment]
This is done in pytest 8.0 -- can test with pytest 8.0.0rc1 until the final release.
