### ISSUE TITLE
How to address DeprecationWarning with Node.from_parent

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#6928]
In jaraco/pytest-checkdocs#3, I started observing a warning in my projects.

```
.tox/python/lib/python3.8/site-packages/pytest_checkdocs.py:12
  /Users/jaraco/code/main/jaraco.util/.tox/python/lib/python3.8/site-packages/pytest_checkdocs.py:12: PytestDeprecationWarning: direct construction of CheckdocsItem has been deprecated, please use CheckdocsItem.from_parent
    return CheckdocsItem(path, parent) if path.basename == 'setup.py' else None
```

I see similar warnings in pytest-flake8 and pytest-black.

```
.tox/python/lib/python3.8/site-packages/pytest_flake8.py:65
  /Users/jaraco/code/main/pytest-checkdocs/.tox/python/lib/python3.8/site-packages/pytest_flake8.py:65: PytestDeprecationWarning: direct construction of Flake8Item has been deprecated, please use Flake8Item.from_parent
    return Flake8Item(

.tox/python/lib/python3.8/site-packages/pytest_black.py:26
  /Users/jaraco/code/main/pytest-checkdocs/.tox/python/lib/python3.8/site-packages/pytest_black.py:26: PytestDeprecationWarning: direct construction of BlackItem has been deprecated, please use BlackItem.from_parent
    return BlackItem(path, parent)
```

I've attempted to port this code to the new recommended format, but I haven't been able to figure out the syntax.

I tried this patch:

```diff
diff --git a/pytest_checkdocs.py b/pytest_checkdocs.py
index 970cf26..9db4a0a 100644
--- a/pytest_checkdocs.py
+++ b/pytest_checkdocs.py
@@ -9,7 +9,11 @@ from more_itertools import first
 
 def pytest_collect_file(path, parent):
     """Filter files down to which ones should be checked."""
-    return CheckdocsItem(path, parent) if path.basename == 'setup.py' else None
+    return (
+        CheckdocsItem.from_parent(parent, name=path)
+        if path.basename == 'setup.py'
+        else None
+    )
 
 
 class CheckdocsItem(pytest.Item, pytest.File):
```

But that gives me an error:

```
_____________________________________________________________________ ERROR collecting test session ______________________________________________________________________
.tox/python/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
.tox/python/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox/python/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
pytest_checkdocs.py:13: in pytest_collect_file
    CheckdocsItem.from_parent(parent, name=path)
E   TypeError: from_parent() got an unexpected keyword argument 'name'
```

I don't understand how from_parent could have an unexpected keyword argument when it accepts all keyword arguments.

What is the proper way to implement a hook in `pytest_collect_file` to construct a Node/Item?

**Comment by RonnyPfannschmidt** [comment]
https://github.com/jaraco/pytest-checkdocs/blob/bc936baa301417b42be7c9d008f2c31006f15000/pytest_checkdocs.py#L15 has a structural error by inheriting from both file and item,

the structurally correct solution is to have a `File` that collects a `Item`

**Comment by RonnyPfannschmidt** [comment]
@jaraco i just noted my error, as the ctor is inherited the way you have it, you just need to pass `fspath=path`

**Comment by jaraco** [comment]
> pytest-checkdocs has a [structural error](https://github.com/jaraco/pytest-checkdocs/blob/bc936baa301417b42be7c9d008f2c31006f15000/pytest_checkdocs.py#L15) by inheriting from both file and item

ugh. I'm not sure where I got that pattern from - probably from pytest-flake8.

**Comment by jaraco** [comment]
In [this branch](https://github.com/jaraco/pytest-checkdocs/tree/feature/node-from-parent), I've pushed a new commit trying to use just `nodes.Item`, but that doesn't work. I then tried as you say constructing an item from within a file, but that fails because I don't know what value to supply to the item's Name, something the code didn't have to supply before.

Can you provide or link to an example of how one can extend pytest to add tests to existing files already collected? In this case, I wish to add a single Item for the `setup.py` file.

**Comment by Zac-HD** [comment]
@jaraco @RonnyPfannschmidt - any updates on this?

**Comment by jaraco** [comment]
No updates. I'm still stuck where I was before. Looks like there have since been some commits in other projects. I'll try to derive inspiration from them.

**Comment by jaraco** [comment]
In [this new branch](https://github.com/jaraco/pytest-checkdocs/tree/feature/node-from-parent-redux), I have a new fix that seems to be working. I drew most of the inspiration from pytest-flake8. It's a rather awkward fix (jaraco/pytest-checkdocs@5deec2a13beae75543d7f16bc62ea95b78c05cd1), but not nearly as awkward as the one in pytest-pylint. I'm really not confident in the solution, but it seems to be working so ¯\_(ツ)_/¯.

**Comment by jaraco** [comment]
I should also mention where pytest-black worked around the issue: shopkeep/pytest-black#43

**Comment by Zac-HD** [comment]
If it's working, I guess that's something :man_shrugging:
