### ISSUE TITLE
Suggestion: Automatic grouping of assert statements

### ISSUE THREAD

**Issue by henzef** [pytest-dev/pytest#6933]
It would be useful if pytest would automatically group successive assertions and print a report detailing all assertions that failed instead of just the first, e.g.

    msg = get_msg_from_database()
    assert msg.title == "Some entry"
    assert msg.payload == b"data"
    assert msg.timestamp < time.time()

Let's say the title and the timestamp do not match. Currently pytest would report the title mismatch and exit. However during debugging, it might be valuable to know that the timestamp is also wrong.

Since pytest is already rewriting all assertions, maybe it would be possible to combine successive assert statements and provide a detailed report?

**Comment by laurentbristiel** [comment]
Hi. Did you check the [pytest-assume plugin](https://github.com/astraw38/pytest-assume)? It  "allows multiple failures per test" so it should solve your problem, no?

**Comment by Zac-HD** [comment]
Unfortunately this isn't feasible to add to the core pytest library, but the plugin should help :smile:

**Comment by RonnyPfannschmidt** [comment]
there are some ideas to allow controll over assert statements but thats not going to manifest anytime soon
