### ISSUE TITLE
tmpdir_factory and absolute paths that coincide with tmpdir_factory fails

### ISSUE THREAD

**Issue by zerothi** [pytest-dev/pytest#6937]
Prior to #5686 (I think) one could provide absolute paths to `tmpdir_factory`. I understand the security issues this brings. However, I had a `conftest.py` implementation which used `tmpdir_factory.getbasetemp()` and it self created full paths with the base being `getbasetemp()`.

I think in such cases `pytest` should not fail since the directory is valid and could easily be checked against.

I.e. the directory/file passed should be resolved and if it is prefixed with `getbasetemp` then all is good, else fails.

I am only now encountering these problems in Travis, pytest version 5.4.1 (not on my local box, since I haven't updated pytest, I am still on 5.0.1).

See [here](https://travis-ci.org/github/zerothi/sisl/jobs/663854528?utm_medium=notification&utm_source=email) for the output which creates the fails.

See [here](https://github.com/zerothi/sisl/blob/987edeff2242792e7a4aa9d66a868fa621fb99d3/sisl/conftest.py#L34) for the implementation which itself collects the directories and files that are created.

If anymore information is required, feel free to contact me.

**Comment by Zac-HD** [comment]
Hmm.  Validating that a path is safe just makes me nervous - is there a workaround you could try like calculating the relative paths you want?

**Comment by zerothi** [comment]
Thanks!
I have now made a work-around, but it has some quirks. I'll see if I can simplify it out...
