### ISSUE TITLE
3.1.2: PYTEST_ADDOPTS fails to work for getini

### ISSUE THREAD

**Issue by suederat** [pytest-dev/pytest#6946]
- [ ] a detailed description of the bug or suggestion
PYTEST_ADDOPTS fails to be accepted through getini, so --override-ini only works in cli.I use PYTEST_ADDOPTS in make-target for running pytest, so hit this issue. 

- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
pytest 3.1.2
docker running alpine 3.8

- [ ] minimal example if possible
[pytest]
log_file_scope=module

pytest data_plane/tests -o log_file_scope=session 
(Pdb++) item.config.getoption('override_ini')
[['log_file_scope=session']]
(Pdb++) item.config.getini('log_file_scope')
'session'

export PYTEST_ADDOPTS='data_plane/tests  -o log_file_scope=session'
pytest
(Pdb++) item.config.getoption('override_ini')
[['log_file_scope=session']]
(Pdb++) item.config.getini('log_file_scope')
'module'

**Comment by Zac-HD** [comment]
`pytest` <= 5 is no longer supported.
