### ISSUE TITLE
Conditional xfail

### ISSUE THREAD

**Issue by timhoffm** [pytest-dev/pytest#6952]
I'd like to see something like `pytest.mark.xfailif(condition)`

### Use-case:
Our lib is built on multiple operating systems. Currently one test fails on OSX due to issues outside of the library. If it would fail always, I could add `@pytest.mark.xfail()`, but it's only happening on OSX. Alternatively, I could `@pytest.mark.skipif()`. But the advantage of `xflail` is that it would notify me when the external issue is solved and I can reactivate the test. With `skipif` I would not know when the test starts working again and probably forget it.

Alternatively, is there an existing pattern I could use to get a conditional xfail.

**Comment by The-Compiler** [comment]
`@pytest.mark.xfail` already [does take](https://docs.pytest.org/en/latest/reference.html#pytest.mark.xfail) a condition as a first argument. This probably could be documented better on the [skip/xfail page](https://docs.pytest.org/en/latest/skipping.html#xfail-mark-test-functions-as-expected-to-fail), though?

**Comment by timhoffm** [comment]
Thanks, yes I was looking only at that page. You may close this or leave it open as a reminder to update the docs.
