### ISSUE TITLE
JunitXml test results for single test in test module

### ISSUE THREAD

**Issue by TerekhovaKate** [pytest-dev/pytest#6955]
Is it documented anywhere how i can get junitxml test result for each test while test module still running. Im using --junitxml,   but if test suite contains 20 long running tests,  xml result file not generated.

code example 

FILE = __name__.split('.')[-1:][0]
SS_FILE_NAME_FORMAT = '/tmp/{}_%s.png'.format(FILE)

@pytest.mark.usefixtures("qtest_modules") - custom record_xml_attribute 
@pytest.mark.usefixtures("skip_if")
@pytest.mark.platform('i', '')
class TestAdFW():

    @pytest.fixture(autouse=True)
    def setup(self, app_function): # app_function = pytest args to configure run
        with ProxySetup(app_function, file=FILE):
            yield

    def test_1(self, driver, app_function, db, ocr, asset,
                               assert_playback, record_property, common):

        assert_expectations()
          .............
      fin() - push results to management system

    def test_2(self, driver, app_function, db, ocr, asset,
                               assert_playback, record_property, common):

        assert_expectations()
        .............
       fin() - push results to management system
if junitxml cannot support  it, maybe you can suggest some hooks to get stdout with pytest error code  for single test case. or example if  to modify junitxml.py  https://docs.pytest.org/en/3.7.2/_modules/_pytest/junitxml.html
Thanks  so much 

- [*] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [*] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
It's currently not supportable,
There are some ideas to enable it, but that requires a rewrite and some sketchy XML writing hacks

**Comment by TerekhovaKate** [comment]
How hard would be implementations for your ideas?  May you to share code example to play, debug and troubleshoot. I was trying with call logXML object as a fixture,  had no luck so far, 
@pytest.fixture()
def _configure():
    xml = LogXML(logfile ="tets.xml", prefix=None)
    yield xml

this code able to take results as a bool for test, but stdout are blocked with flag pytest --capture=
@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    # execute all other hooks to obtain the report object
    outcome = yield
    rep = outcome.get_result() 
thanks

**Comment by RonnyPfannschmidt** [comment]
A correct implementation would prepare a overwritable xml header, and append more xml while repeatedly overwriting the initial stats line

It's a quite daring way and I don't want to work on the details of correctness /corruption prevention anytime soon

**Comment by TerekhovaKate** [comment]
Thanks. Will look fo different solution in my side.
