### ISSUE TITLE
can someone kindly suggest me how to configure pytest in order to make "print" visibile in pytest-html report?

### ISSUE THREAD

**Issue by andreabisello** [pytest-dev/pytest#6960]
i need to store in pytest-html report some "print" output containing some test result informations.

i'm not sure this question should to be asked in this repository or in the pytest-html repository.

i read

- https://docs.pytest.org/en/latest/reference.html#confval-log_level
- https://docs.pytest.org/en/latest/logging.html
- https://docs.pytest.org/en/latest/warnings.html
- https://pypi.org/project/pytest-html/

but still not able to store "print" inside some kind of report, as for example pytest-html

i'm using pytest 5.4.1, python 3.8 on updated windows 10, pytest-html 2.1.1 , allure pytest 2.8.12

this is my simple test

```
@pytest.mark.printable
def test_print_something():
    print("foo bar foo bar")

```

this is the command line i'm executing

pytest -s -m printable

this is the result

> 
> C:\src\qa-lsd-webservices>pytest -s -m printable
> ================================================= test session starts =================================================
> platform win32 -- Python 3.8.0, pytest-5.4.1, py-1.8.0, pluggy-0.13.0 -- c:\users\andreabisello\appdata\local\programs\python\python38-32\python.exe
> cachedir: .pytest_cache
> metadata: {'Python': '3.8.0', 'Platform': 'Windows-10-10.0.18362-SP0', 'Packages': {'pytest': '5.4.1', 'py': '1.8.0', 'pluggy': '0.13.0'}, 'Plugins': {'allure-pytest': '2.8.12', 'flaky': '3.6.1', 'clarity': '0.2.0a1', 'forked': '1.1.3', 'html': '2.1.1', 'metadata': '1.8.0', 'print': '0.1.3', 'rerunfailures': '8.0', 'testconfig': '0.2.0', 'timeout': '1.3.4', 'xdist': '1.31.0'}, 'JAVA_HOME': 'C:\\Program Files\\Java\\jre1.8.0_241'}
> Suite di test dei webservices
> rootdir: C:\src\qa-lsd-webservices, inifile: pytest.ini
> plugins: allure-pytest-2.8.12, flaky-3.6.1, clarity-0.2.0a1, forked-1.1.3, html-2.1.1, metadata-1.8.0, print-0.1.3, rerunfailures-8.0, testconfig-0.2.0, timeout-1.3.4, xdist-1.31.0
> collecting 0 items                                                                                                     
> collected 317 items / 316 deselected / 1 selected
> 
> test_hub.py::test_print_something foo bar foo bar
> PASSED
> 
> 

has you can see, "foor bar foor bar" is the result of the print inside the test.
i would like to store in the pytest-html file.

but this is the content of the pytest-html .html file

![image](https://user-images.githubusercontent.com/2149815/77307340-565fd900-6cf9-11ea-8f3d-927bdb30ffe0.png)

there is no log captured.
i also tried with pytest-allure and pytest-print

sorry if i'm in the wrong place.

thanks for any advice.

**Comment by bluetech** [comment]
Hi,

`-s` means that output capturing is disabled (just goes to the terminal). What happens if you remove it?

**Comment by andreabisello** [comment]
oh!

i put -s to see the output of the print in the command prompt,
but removing,
i see the print log in the pytest-html file.

thanks
