### ISSUE TITLE
``--last-failed`` is broken for parametrized and class tests since 5.4

### ISSUE THREAD

**Issue by throwable-one** [pytest-dev/pytest#6968]
```python
import pytest

class TestPyTest:
    def test_good(self):
        pass

    def test_bad(self):
        assert False

@pytest.mark.parametrize("good", [True, False])
def test_moderate(good):
    assert good
```

``pytest==5.3.5``
First run (``pytest test_foo.py``):  2 failed, 2 passed 
``pytest --last-failed test_foo.py``:  2 failed, 2 deselected 

``pytest==5.4.1``
First run (``pytest test_foo.py``):  2 failed, 2 passed 
``pytest --last-failed test_foo.py``:  **1 failed**

It only reruns parametrized test, but not ``TestPyTest.test_bad``

**Comment by blueyed** [comment]
Just for reference: I think this is fixed in my forked, but due to to multiple commits etc no trivial to backport:  https://github.com/blueyed/pytest/blob/fbe8c77d41202ce98e55701ccf31b7352e8d8d38/src/_pytest/cacheprovider.py

I.e. feel free to pick it from there.

**Comment by nicoddemus** [comment]
@blueyed can you please do the port yourself?

**Comment by blueyed** [comment]
@nicoddemus sure.  Just let me know maybe 1 day ahead when you plan to make 5.4.2, and this was not done yet.

**Comment by blueyed** [comment]
https://github.com/pytest-dev/pytest/pull/6991
