### ISSUE TITLE
PyTest uses a different class object to the code

### ISSUE THREAD

**Issue by PsychicSmurf** [pytest-dev/pytest#6975]
PyTest: 5.4.1
Python: 3.7.3
Windows 10 (fully patched)

In my application, I have a helper class (to manage time) made up of class methods which use a single class-level variable to manage state.

If I call a method on this class from within a test function (which modifies the class-level variable) the change is not seen by the code-under-test which appears to have its own copy of the class, separate to the one used by PyTest.

This means I cannot use this class to manipulate time under test conditions!

Surely PyTest should only have a single class definition created that is common to both PyTest and the code-under-test?

Class Module:
`"""This class overrides the system datetime function for this application.
   This will allow for unit tests to control the time and accurately, and reliably, test functionality."""
from datetime import datetime
import random

class DateTimeStamp():
    _custom_time = 0

    @classmethod
    def getCurrentTimeStamp(cls):
        """Returns the current time, or the overridden time if set"""
        return cls._custom_time if cls._custom_time else datetime.now()

    @classmethod
    def clear_override(cls):
        """Clears any previous override allowing the code to access real time again"""
        cls._custom_time = 0

    @classmethod
    def override(cls, years, months, days, hours=0, minutes=0, seconds=0, millis=0):
        """Allows the date and time to be manually set, and fixed, to allow testing"""
        cls._custom_time = datetime(years, months, days, hours, minutes, seconds, millis, tzinfo=None)
`

Test case:
```
def test_generate_log_entry(logger):
    """This test ensures that the line of text is generated correctly with the given input"""
    # First, let's stop time!
    DateTimeStamp.override(1968, 4, 15, 11, 23, 45, 4567)
    log_time, log_entry = logger._generate_log_entry("this is a test")
    assert log_entry == "11:23:45.004567, this is a test"
```

Code under test:

```
class Logger():
    def _generate_log_entry(self, log_text):
        # Get the current time and date
        log_time = DateTimeStamp.getCurrentTimeStamp()
        print("Logger ID    ", DateTimeStamp.id)
        # Create the line to text to be logged
        log_entry = self._getLogTimeAsString(log_time) + ", " + log_text
        return log_time, log_entry

    def _getLogTimeAsString(self, log_time):
        """Uses the current time to create a log timestamp"""
        return log_time.strftime("%H:%M:%S.%f")
```

pip list output:
```
[11:54:40] PS C:\Git\TM470(venv) > pip list 
Package            Version   
------------------ ----------
astroid            2.3.3
atomicwrites       1.3.0
attrs              19.3.0
autopep8           1.5
certifi            2019.11.28
chardet            3.0.4
colorama           0.4.3
graphviz           0.13.2
idna               2.9
importlib-metadata 1.6.0     
isort              4.3.21
lazy-object-proxy  1.4.3
mccabe             0.6.1
mock               4.0.2
more-itertools     8.2.0
numpy              1.18.2
packaging          20.3
pandas             1.0.3
pip                20.0.2    
pluggy             0.13.1
py                 1.8.1
pycodestyle        2.5.0
pylint             2.4.4
pyparsing          2.4.6
PyQt5              5.14.1
PyQt5-sip          12.7.1
pytest             5.4.1
python-dateutil    2.8.1
pytz               2019.3    
requests           2.23.0
setuptools         46.1.3
six                1.14.0
typed-ast          1.4.1
Unidecode          1.1.1
urllib3            1.25.8
wcwidth            0.1.9
wheel              0.34.2
wrapt              1.11.2
zipp               3.1.0
```

**Comment by RonnyPfannschmidt** [comment]
pytest simply uses python an does not create duplicate classes, without more context its not clear what is happening

**Comment by PsychicSmurf** [comment]
I'm not sure how to offer more context here, is there anything, in particular, you think I've missed?

I did add another class variable to my helper class, set to a random number, and then printed this number out from the test function, and the function-under-test. The numbers were different meaning that each had a different copy of the class.

**Comment by RonnyPfannschmidt** [comment]
@PsychicSmurf without seeing the actual code usage i cant tell, what you posted here looks like it should work exactly as expected, is it possible that there are multiple locations for the class to be in (import path missmatch), for that you could compare the __module__ and the files the code objects reside in

**Comment by PsychicSmurf** [comment]
Thank you.

Whilst there was only one source file, my test functions (the test modules are stored in a separate directory to the source files) accessed the file using a slightly longer path.

I have now made ensured that the import statements use the same full prefix and the test now passes!
