### ISSUE TITLE
Ignore directories in config file

### ISSUE THREAD

**Issue by domoritz** [pytest-dev/pytest#6990]
I would like to ignore a directory `data` but keep `src/data/` via the config file (`pytest.ini`). Unfortunately, pytest only allows setting the ignore on the cli but not via the config file.

I think it would be good to support `ignore` in the config file. 

cc @ldegreef

**Comment by blueyed** [comment]
You can use command line options via `addopts`.
The most flexible however is using `collect_ignore_glob` (a list of globs) in a `conftest.py` file.

Closing as answered question, feel free to follow up of course.
