### ISSUE TITLE
Shell Bindings Disabled After Reclaiming File Descriptors with `-s` CLI Argument?

### ISSUE THREAD

**Issue by her** [pytest-dev/pytest#6995]
Hi, 

- [x] a detailed description of the bug or suggestion

I noticed that after passing the `-s` argument https://docs.pytest.org/en/2.8.7/capture.html and using IPython debugger that `bash` key bindings are disabled or overridden by pytest? so `C-a` `C-e` etc. no longer work, also colors are disabled? 

Has anyone experienced this? How did you work around this?

- [ ] output of `pip list` from the virtual environment you are using
I can't provide this
- [x] pytest and operating system versions
18.04.1-Ubuntu  platform linux -- Python 3.6.8, pytest-3.6.0, py-1.8.0, pluggy-0.6.0
- [x] minimal example if possible

**Comment by blueyed** [comment]
Do you mean they are disabled within IPython then?  (which would not be bash then)
Please provide steps to reproduce it.
Also: does it work when not using `-s`?
Are you using `ipdb`, or how do you invoke the debugger?

**Comment by her** [comment]
Hi @blueyed, thank you for the reply. I think the problem was maybe the version of pytest I'm using. After updating to a newer version things seem to work fine. 

I'm going to close this issue.
