### ISSUE TITLE
bugfix backports

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#7001]
- [x] #6992 by #7066
- [x] #6927 for #6924 by #7068 
- [x] #6986 by #7067

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i hope to get to those either today or tomorrow morning

**Comment by nicoddemus** [comment]
Awesome, thanks!

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i finally had a moment to run trough it, happy easter

**Comment by nicoddemus** [comment]
Thanks!
