### ISSUE TITLE
Remaining tests fail when assertion fails

### ISSUE THREAD

**Issue by gsilvapt** [pytest-dev/pytest#7004]
Hi!

I have a Django application that has many tests and we moved onto pytest recently. 
Everything was fine until we needed to reset a virtual environment and we realized all remaining tests were failing with `TransactionManagementError` after one assertion failed. Previously, it would just point one failing test, the one with a failing assertion. All others would run without any transaction errors.

To test this, I fresh installed our env, without pin-pointing `pytest`'s version and it installs version 5.4.1.
Then I modified a working test so that it fails, and got many failing tests, one with the assertion and all others with `TransactionManagementError`.
Than ran `pip install pytest=5.3.5.` manually, ran the suite again, and only one test was failing - the one with the wrong assertion.   

**I can't show code, nor the tests, nor the environment because this is still a closed-source application and I don't want to get into legal issues, but thought it might be important to talk with you guys about this as this seems like a bug introduced in the march's releases.**

Environment that I am allowed to share:
pytest 5.3.5 - which works
pytest 5.4.1 - which doesn't work
pytest-django 3.8.0
MacOS Mojave 10.14.6
Python 3.7.5
Django 2.1.15

- [X] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [X] pytest and operating system versions
- [ ] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
I suspect this is related to the know bug /regression about not running unit test teardown, i can't crosslink while on mobile

**Comment by gsilvapt** [comment]
Maybe this? I couldn't find official release to see for known bugs: https://github.com/pytest-dev/pytest/issues/6752
