### ISSUE TITLE
Test description for verbose runs

### ISSUE THREAD

**Issue by Sup3rGeo** [pytest-dev/pytest#7005]
Hello!

#4371 implemented printing the description when running with `collect-only`, but I thought the description would be also useful for normal test runs so I wanted to also have it when running tests in verbose mode.

In fact this was quite easy to do after a bit of research ([I posted my solution in a stackoverflow question about it](https://stackoverflow.com/a/61002385/3444175)), but was wondering if it would be useful to have it into pytest itself?

Thanks!

**Comment by Zac-HD** [comment]
Given that this is pretty easy to solve with a downstream plugin, I'm closing this per https://github.com/pytest-dev/pytest/issues/12465#issuecomment-2175596712
