### ISSUE TITLE
Is it possible to decorate a fixture that takes another fixture as an argument?

### ISSUE THREAD

**Issue by ajhynes7** [pytest-dev/pytest#7007]
I want to log the results of several pytest fixtures.

I can write a simple decorator to log the result of a function, and it works on a fixture that has no arguments. But it fails on a fixture that takes another fixture as an argument.

Here's a simple example:

```
import logging
import pytest


logger = logging.getLogger(__name__)
logger.setLevel("DEBUG")


def log_result(func):
    def wrapper(*args, **kwargs):

        result = func(*args, **kwargs)
        logger.debug(result)

        return result

    return wrapper


@pytest.fixture
@log_result
def foo():
    return "foo"


@pytest.fixture
@log_result
def bar(foo):
    return foo + "bar"


def test_foo(foo):
    pass


def test_bar(bar):
    pass
```

The first test passes and the value of the `foo` fixture is logged. But the second test fails with 

```
TypeError: bar() missing 1 required positional argument: 'foo'
```

So I really have two questions:

1. Is there some way to write a decorator for a fixture that takes another fixture as an argument?
2. If not, is there another way to log the result of a fixture?

I know it'd be simple enough to assign the fixture return value to a variable, log the variable, then return it, but I'm curious if there's another way so I can reduce noise in the fixture body.

**Comment by RonnyPfannschmidt** [comment]
a function wrapper must transport the signature 

typically this is done by decorating the wrapper using `functools.wraps` from the stdlib,
which sets up the attribute/signature of the wrapped function on the wrapper

**Comment by ajhynes7** [comment]
Nice, that was a simpler simpler solution than I expected. I added `functools.wraps` and the two tests passed. Thank you!
