### ISSUE TITLE
Class Inheriting another Class is not able to call its own teardown_class()

### ISSUE THREAD

**Issue by harishkumar3091** [pytest-dev/pytest#7013]
**Description:**

- Lets say a class A() has setup_class(), test_cases and its own teardown_class()
- I want to use the same test variables inside the above class and also the triggers into new class. 
- So, I inherit them as class B(A) which has its own setup_class, test_cases & teardown_class()
- Now, from class B() - I hit a certain condition where I need to call its teardown_class() skipping all the consecutive test cases.
- From Python point of view - When i hit the break point and do dir(class B) - I see the container variables, values etc. 
- But when i invoke - class B().teardown_class() - it just continues moving ahead not performing any operation. 
- Pytest Version - 3.0.7

**Sample Code:** 

Class A():

def setup_class(self):
    pass

def test_one(self):
    pass

def teardown_class(self):
    pass

class B(A):

def setup_class(self):
    B().teardown_class   --------> Not Invokable

def test_one(self):
    pass

def teardown_class(self):
    pass

**Comment by Zac-HD** [comment]
> Pytest Version - 3.0.7

Pytest 3 is way way out of support - unless this is replicated on pytest 5 we won't try to fix it.

**Comment by The-Compiler** [comment]
> B().teardown_class --------> Not Invokable

FWIW this doesn't make much sense - you're constructing a new instance of the test class, and then access the `teardown_class` method on it, but you don't call it. But even if you did: Calling teardown methods by hand is probably not a good idea.
