### ISSUE TITLE
Replace usage of py.path.local().make_numbered_dir

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#7018]
There are two places where `make_numbered_dir` is used from pylib, although there is also `_pytest.pathlib.make_numbered_dir`:

`testdir.runpytest_subprocess`:
https://github.com/pytest-dev/pytest/blob/e01dcbf3235188c64d8aa3b9cdc014efbc29e15d/src/_pytest/pytester.py#L1242-L1244

In a test - likely to prepare it for use via `runpytest_subprocess`:
https://github.com/pytest-dev/pytest/blob/e01dcbf3235188c64d8aa3b9cdc014efbc29e15d/testing/test_assertrewrite.py#L835-L837

Ref: https://github.com/pytest-dev/pytest/issues/3810

**Comment by RonnyPfannschmidt** [comment]
Good find, believe they can be replaced with the internal helper
