### ISSUE TITLE
Question: how to modify the exit code of the run session ?

### ISSUE THREAD

**Issue by h-rueda** [pytest-dev/pytest#7031]
Hi,

How can I modifiy the exit code of the pytest run session ?

I am interested in :

- Determine the number of xfailed, xpasses and skipped tests
- returning 1 if there are xfailed or skipped tests 
- not returnning 1 if there is any xpassed test

**Comment by SalmonMode** [comment]
Typically, it wouldn't be about modifying how an already established executable determines its exit codes, but rather parsing the results of the executable and adding your own logic on top of that to provide your own exit code.

It would sort of be like asking `grep` to exit with `0` if no results were found (which would normally be a `1`). If you are expecting grep to return no results, then you would check for that directly, and then handle it accordingly.

To do what you're asking with pytest, an easy way would be to have a wrapper script call pytest, have pytest pump out an junit xml report, which are super easy to parse, and have the wrapping script analyze the report and provide its own exit code according to the logic you want.

**Comment by symonk** [comment]
Hi @h-rueda I'm not aware of a way to customize it, ultimately:

```python
-> pytest_cmdline_main()
   -> wrap_session()
        -> # some preset logic here, USAGE_ERROR, INTERNAL_ERROR... etc
```

Here is a little more info:

```python
    #: tests passed
    OK = 0
    #: tests failed
    TESTS_FAILED = 1
    #: pytest was interrupted
    INTERRUPTED = 2
    #: an internal error got in the way
    INTERNAL_ERROR = 3
    #: pytest was misused
    USAGE_ERROR = 4
    #: pytest couldn't find tests
    NO_TESTS_COLLECTED = 5
```

 will try to pass up the session exit code through wrap_session etc.  Its maybe something a custom plugin could modify somehow, but thats a guess, I would need to have a look through some code.

**Comment by bluetech** [comment]
`pytest_cmdline_main()` is a hook you can wrap with a `@pytest.hookimpl(hookwrapper=True)`, see [here](https://docs.pytest.org/en/latest/writing_plugins.html#hookwrapper-executing-around-other-hooks). The return value of the hook is the exit code. Note however that according to the documentation of this specific hook, "This hook will not be called for ``conftest.py`` files, only for setuptools plugins.".
