### ISSUE TITLE
pytest.mark.xfail - run parameter not working as expected

### ISSUE THREAD

**Issue by h-rueda** [pytest-dev/pytest#7032]
I have this test : 

```
@pytest.mark.xfail(run=True)
def test_1() :
   print("Hello world")
   assert 1 == 0, "assert failed"
```
When I execute it with the -rA flags (pytext -rA), I don't get the print function output

My environment : 
`platform linux -- Python 3.6.9, pytest-5.4.0, py-1.8.1, pluggy-0.13.1`

**Comment by RonnyPfannschmidt** [comment]
this is working "as expected", th explicit run parameter just means whether or not to run the test to begin with (there is a option to not even run xfailing tests)

however xfailing tests are not considered a "failure" so they don't get reporting, if you want the output, for now you have to take off the xfail mark

**Comment by h-rueda** [comment]
OK, thank you.
This issue can be closed
