### ISSUE TITLE
Adding "passed" status into junitxml logs

### ISSUE THREAD

**Issue by nvoloshchuk19** [pytest-dev/pytest#7045]
![image](https://user-images.githubusercontent.com/51717986/78811321-5850ba00-79d2-11ea-8c02-2c7487470821.png)
Is it possible to add "passed" status of tests in the report?

**Comment by nvoloshchuk19** [comment]
`numtests = (
            self.stats["passed"]
            + self.stats["failure"]
            + self.stats["skipped"]
            + self.stats["error"]
            - self.cnt_double_fail_tests
        )`
As I see, we have "passed" status, but how I can log it into report?

**Comment by RonnyPfannschmidt** [comment]
passed is **not** part of the spec, so the junitxml plugin shouldnt simply add it
see https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd#L116-L130

**Comment by nvoloshchuk-amplify** [comment]
@RonnyPfannschmidt one more question. I have a problem with passed tests, they are not displaying at the graphic report(only errors and failures), can lack of passed status be the cause?

**Comment by nvoloshchuk19** [comment]
@RonnyPfannschmidt one more question. I have a problem with passed tests, they are not displaying at the graphic report(only errors and failures), can lack of passed status be the cause?

**Comment by RonnyPfannschmidt** [comment]
That depends on the reporting too you use, personally I do not use junitxml
