### ISSUE TITLE
Mapping expected outputs for parameterized fixtures.

### ISSUE THREAD

**Issue by pkaleta** [pytest-dev/pytest#7054]
Let's assume I have the following two functions I want to test:

```
def mult(text, n):
    return text * n

def add(text, n):
    return "{}_{}".format(text, n)
```

I want to use one parametrized fixture to generate test inputs for both functions. Here's one way to do that:

```
class TestFoo(object):
    @pytest.fixture(
        params=[
            ("a", 3),
            ("b", 2),
        ],
        scope="function",
        ids=[
            "testa",
            "testb",
        ],
    )
    def myfixture(self, request):
        return request.param

    def test_mult(self, myfixture):
        if myfixture == ("a", 3):
            assert mult(*myfixture) == "aaa"
        elif myfixture == ("b", 2):
            assert mult(*myfixture) == "bb"
        else:
            raise ValueError("wrong arg")

    def test_add(self, myfixture):
        if myfixture == ("a", 3):
            assert add(*myfixture) == "a_3"
        elif myfixture == ("b", 2):
            assert add(*myfixture) == "b_2"
        else:
            raise ValueError("wrong arg")
```

This works fine, but one problem is that in each test function, I have to explicitly check which parameters are passed to the function under test and based on that pick the expected return value. This code has to be repeated in every test function as well. Is there a better (more concise) way to do this?

**Comment by RonnyPfannschmidt** [comment]
a common solution is to create a mapping of inputs to outputs and use those for lookup

something like 
```python
EXPECTED_ADD_RESULTS = {
  ("a",3): "a_3",
   ...
}
```

**Comment by pkaleta** [comment]
Gotcha, I've used that as well. Just wanted to make sure there's no functionality provided by pytest to support this use case.

I could imagine having a kind of mapping between fixture name/id and additional data that is passed to the test function. Using example from above that would be:

```
@pytes.mark.parametrize(extra={"testa": "aaa", "testb": "bb"})
def test_mult(extra):
    assert mult(*myfixture) == extra

@pytes.mark.parametrize(extra={"testa": "a_3", "testb": "b_2"})
def test_add(myfixture, extra): 
    assert add(*myfixture) == extra
```

**Comment by RonnyPfannschmidt** [comment]
"covariant" parameterization is largely unexplored and so far no elegant general solution emerged

**Comment by pkaleta** [comment]
Thanks @RonnyPfannschmidt
