### ISSUE TITLE
pytest_generate_tests doesn't have a way to check whether the test will be collected

### ISSUE THREAD

**Issue by kappa10j** [pytest-dev/pytest#7065]
I've created a `pytest_generate_tests` function to dynamically generate parameters from an input file.  That's working fine but all the tests are generated on every run even if I run 1 out of 100 tests.  Is there anyway to check if the test will be collected?

The code below will end up reading in all the data files even when a test won't be running.  I planned to have a folder call `input_data` containing a data file for each module.

I'll usually run tests by calling `pytest -k "value"`

```python
class InputData:

    folder_data = {}

    @staticmethod
    def get_data(filename):
        if not filename in InputData.folder_data:
            InputData.folder_data[filename] = json.load(filename)
        return InputData.folder_data[filename]

@pytest.hookspec
def pytest_generate_tests(metafunc):
    if 'data' in metafunc.fixturenames:
        test_name = metafunc.definition.name
        dirname = metafunc.definition.fspath.dirname
        module_name = metafunc.definition.fspath.purebasename
        metafunc.parametrize('data', InputData.get_data('filepath'), indirect=True)
```

thanks for the help

**Comment by Zac-HD** [comment]
As I understand it, you're asking about a performance optimisation we you can avoid generating certain tests based on the selection criteria?

While this is not strictly impossible, I'd avoid it - there's a real risk that bugs will lead to silently missing tests.  If there really is a lot of performance overhead, I'd first try selecting by module (file) as well as `-k`, and if that wasn't enough I'd try deferring the expensive part of test generation to when the test function was run.

**Comment by kappa10j** [comment]
Or how could I check to see that the test would be collected according to
the arguments passed in?  In this case, by the -k argument.

So instead of only checking, if 'data' in metafunc.fixturenames
I could also check, 'if the current test will be collected....'

**Comment by RonnyPfannschmidt** [comment]
its still not clear what you are asking about, pytest-generate-tests can not know whichtest get plucked away by `-k` as **deselection** happens after collecting all tests

**Comment by kappa10j** [comment]
I hadn’t understood the difference between selection and deselection.  Now I do.  So I’m able to select only the tests I want by specifying the test class.   Now I know you stated “pytest-generate-tests can not know whichtest get plucked away by -k as deselection happens after collecting all tests,” but is it possible to check in generate tests if a test is a candidate for deselection?  Perhaps by calling the function that performs the deselection on the collection being created in pytest-generate-tests as it’s checking each test? From: Ronny PfannschmidtSent: Friday, April 10, 2020 2:05 AMTo: pytest-dev/pytestCc: kappa10j; AuthorSubject: Re: [pytest-dev/pytest] pytest_generate_tests doesn't have a way to check whether the test will be collected (#7065) its still not clear what you are asking about, pytest-generate-tests can not know whichtest get plucked away by -k as deselection happens after collecting all tests—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by RonnyPfannschmidt** [comment]
right now that functionality is not exposed as public api
