### ISSUE TITLE
Doctest does not register formatted strings

### ISSUE THREAD

**Issue by saattrupdan** [pytest-dev/pytest#7084]
Pytest currently ignores docstrings of the form `f'foo{bar}'` (and also `'foo{}'.format(bar)`).

Minimal example:
```python
def fstring_test():
    f''' 
    >>> fstring_test()
    1
    '''
    return 1

def format_test():
    ''' 
    >>> format_test()
    1
    '''.format()
    return 1
```

```
> pytest --doctest-modules
============================== test session starts ==============================
platform linux -- Python 3.7.4, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: <root>, inifile: pytest.ini
collected 0 items
```

Removing the formatting makes the doctest detectable again. I'm running Ubuntu 18.04.4 LTS. Here's my `pip list`:
```
Package            Version
------------------ -------
attrs              19.3.0 
importlib-metadata 1.6.0  
more-itertools     8.2.0  
packaging          20.3   
pip                20.0.2 
pluggy             0.13.1 
py                 1.8.1  
pyparsing          2.4.7  
pytest             5.4.1  
setuptools         46.1.3 
six                1.14.0 
wcwidth            0.1.9  
zipp               3.1.0 
```

**Comment by bluetech** [comment]
Hi @saattrupdan, this is actually up to Python itself. pytest uses the `__doc__` attribute which Python fills with the docstring. But with `f`/`format` it isn't filled, so pytest doesn't see it. I guess in an usual situation like this, you can just set it directly, `fstring_test.__doc__ = f"my docstring"`, I think that should work with pytest but I didn't verify.

**Comment by saattrupdan** [comment]
Hi @bluetech and thanks for the quick answer. It does indeed work if I directly set `__doc__`, thanks!
