### ISSUE TITLE
File and Line attributes are not Junit compliant for Jenkins

### ISSUE THREAD

**Issue by alkuzad** [pytest-dev/pytest#7096]
In https://github.com/pytest-dev/pytest/pull/809 file and line attributes were added, which are not complaint to junit standard schemas:

In 2015 they were ok for Jenkins:

But now they are not:
https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd

Junit ...

**Comment by markshao** [comment]
looks like we should re-org the xml-report structure according to [https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd](url)

currently the pytest may only support one testsuite inside the xml-report , according to the new spec, we shild split the testsuite with unique file , testcases under the same suites comes from the same file.

**Comment by markshao** [comment]
According to the latest xunit-spec , we may need to refacter the structure of testsuite and testcase.

currently the pytest only support one testsuite , cause some duplicated attrs in the testcase tag like file .

maybe we should group by the testsuite with same file according to the new spec , for example 
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
<testsuite errors="0" failures="4" file="test_assert.py" hostname="MacBook-Pro-4.local" name="pytest" skipped="2" tests="17" time="16.211" timestamp="2020-04-19T23:03:49.548476">
    <testcase classname="test_assert" name="test_array_assert" time="0.002">
      <failure message="assert [1, 2, 3, 4, 5] == [1, 3, 3, 4, 5]
  At index 1 diff: 2 != 3
  Use -v to get the full diff">def test_array_assert():
        source = [1,2,3,4,5]
        target = [1,3,3,4,5]
&gt;       assert source == target
E       assert [1, 2, 3, 4, 5] == [1, 3, 3, 4, 5]
E         At index 1 diff: 2 != 3
E         Use -v to get the full diff

niutest/test_assert.py:6: AssertionError</failure>
    </testcase>
  </testsuite>
<testsuite errors="0" failures="4" file="test_fixtures.py" hostname="MacBook-Pro-4.local" name="pytest" skipped="2" tests="17" time="16.211" timestamp="2020-04-19T23:03:49.548476">
    <testcase classname="test_fixtures.TestFixtureLogic" name="test_fix2" time="0.003"></testcase>
    <testcase classname="test_fixtures.TestFixtureLogic" name="test_singleton" time="0.000">
      <skipped message="test skip" type="pytest.skip">test_fixtures.py:31: test skip</skipped>
    </testcase>
  </testsuite>
<testsuites>
```

there some stats failure I'm still working on .

**Comment by petr-balogh** [comment]
+1, we started using some tool and it's also complaining about those values :(

**Comment by petr-balogh** [comment]
```python
import xml.etree.ElementTree as ET

def remove_attributes(xml_file, element_name, attributes_to_remove):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    for elem in root.findall('.//{}'.format(element_name)):
        for attribute in attributes_to_remove:
            if attribute in elem.attrib:
                del elem.attrib[attribute]

    tree.write(xml_file)

# Example usage:
xml_file_path = 'path/to/xml/report.xml'
element_name_to_modify = 'testcase'
attributes_to_remove = ['file', 'line']

remove_attributes(xml_file_path, element_name_to_modify, attributes_to_remove)
```

This should make the trick as a W/A for removing those from existing report.

**Comment by RonnyPfannschmidt** [comment]
closing as solved - use the junit2 family which is the default

https://docs.pytest.org/en/7.2.x/reference/reference.html#confval-junit_family

i suspect the testsuite us using the property recording features that also cant be supported with modern junit
