### ISSUE TITLE
Confusing log for teardown

### ISSUE THREAD

**Issue by szha** [pytest-dev/pytest#7101]
# Description
For test files where the last test is skipped, if module level teardown incurs exception, the exception would still be attributed to the skipped test.

# Example

1. Save the following snippet as test.py
```
import pytest

def teardown_module():
    print('executed teardown')
    raise RuntimeError()

def test_test():
    print('executed test')
    pass

@pytest.mark.skip(reason='something')
def test_skipped():
    print('executed skipped')
    pass
```
2. run `pytest -v test.py`

3. output
```
% pytest -v test.py
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.7.7, pytest-5.4.1, py-1.8.0, pluggy-0.13.1 -- /usr/local/opt/python/bin/python3.7
cachedir: xx
rootdir: xx
plugins: env-0.6.2, xdist-1.31.0, forked-1.1.3, cov-2.8.1
collected 2 items

test.py::test_test PASSED                                                                                                                         [ 50%]
test.py::test_skipped SKIPPED                                                                                                                     [100%]
test.py::test_skipped ERROR                                                                                                                       [100%]

=========================================================================== ERRORS ===========================================================================
_____________________________________________________________ ERROR at teardown of test_skipped ______________________________________________________________

    def teardown_module():
        print('executed teardown')
>       raise RuntimeError()
E       RuntimeError

test.py:5: RuntimeError
------------------------------------------------------------------ Captured stdout teardown ------------------------------------------------------------------
executed teardown
================================================================== short test summary info ===================================================================
ERROR test.py::test_skipped - RuntimeError
=========================================================== 1 passed, 1 skipped, 1 error in 0.21s ============================================================
```

# Env

OSX w/ pytest 5.4.1

**Comment by bluetech** [comment]
(The skipping is inconsequential here -- the error in `teardown_module` is "attached" to which ever test runs last.)

**Comment by Zac-HD** [comment]
`ERROR at teardown of test_skipped` seems like it's functioning as intended to me.

@szha, what do you think *should* be happening here?

**Comment by szha** [comment]
If a test is skipped then users won’t expect that test to err. Since the error is in module teardown, it makes more sense to me to either have an additional entry just for the status for the module or to have the error message attached to the last run test, not including the skipped ones.

**Comment by Zac-HD** [comment]
I think this is working as intended - while it might be unintuitive, changing where we report teardown errors depending on skipped status (which can be decided within the test, and potentially nondeterministically!) is likely to cause worse problems.

**Comment by RonnyPfannschmidt** [comment]
there is a plan to split up the layers of setup/teardown to own reports, which wil lfix that issue, its indeed a pain that we merge setup/teardown reports of different scope into the function setup/teardown

**Comment by RonnyPfannschmidt** [comment]
setting this as duplicate of #895
