### ISSUE TITLE
Question: is it possible to write doctests for async functions?

### ISSUE THREAD

**Issue by oakkitten** [pytest-dev/pytest#7102]
Suppose I have a simple function like this:

    async def hello_world():
        """
        Will great the world with a friendly hello.

        >>> await hello_world()
        'hello world'
        """
        return "hello world"

It would test fine were it not for the fact that one can't use `await` in a regular function. Is there perhaps a way to run this test inside `asyncio` or `trio`, or perhaps some simple non-io aware event loop?

**Comment by Zac-HD** [comment]
You can use the usual `trio.run(...)` or `asyncio.run(...)` functions, but top-level `await` is not supported in doctests or the Python repl.

`pytest-trio` or `pytest-asyncio` might be interested in extending the [recent asyncio repl](https://bugs.python.org/issue37028) work to doctest though, so I guess you could propose a new feature?  It's a tricky one though :confused:
