### ISSUE TITLE
Add option to log exception in --log-file

### ISSUE THREAD

**Issue by d3nzil** [pytest-dev/pytest#7104]
Currently when using --log-file parameter there is no way, as far as I could find, to make pytest log exceptions that happen in the test.
So when having example test like (in file test.py):
```
def test_exc():
    print(1/0)
```
And running pytest like:
`pytest --log-file=test.log test.py`

Then the test.log file ends up being empty.
But it would be nice to have way to enable logging of the exception into the log file as this would enable to check steps leading to the exception and the exception in one place.
I know I can get the exceptions logged into file using --resultlog, but that is different file and makes it difficult to match together. And logging into console is problematic when using pytest-xdist as log lines are not in order.

**Comment by Zac-HD** [comment]
Closing this because it's been inactive for more than two weeks - https://stackoverflow.com/questions/tagged/pytest might be able to help?

**Comment by RonnyPfannschmidt** [comment]
An answer is that pytest does not log exceptions from tests to a logger
