### ISSUE TITLE
async tests are prone to human errors

### ISSUE THREAD

**Issue by uriva** [pytest-dev/pytest#7105]
Hi, currently pytest doens't handle async ootb, and plugins are needed. However these plugin require file/function based annotations, which are easy to miss. I suggest raising some exception upon a test function which is async, but not marked as such.

For more detail: https://github.com/pytest-dev/pytest-asyncio/issues/144

**Comment by kerizane** [comment]
Can you provide a minimal example of a test you would expect to fail?

For example, using pytest-asyncio==0.10.0 and pytest==5.3.1
```
import asyncio
import pytest

async def test_example():
    await asyncio.sleep(0, loop=event_loop)
```

E       pytest.PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
E       You need to install a suitable plugin for your async framework, for example:
E         - pytest-asyncio
E         - pytest-trio
E         - pytest-tornasync

Looks fine to me?

**Comment by uriva** [comment]
Must be new or something. Didn't notice it.
Anyway it's great thanks.

**Comment by uriva** [comment]
Does this trigger even if you have the plugin installed?

**Comment by nicoddemus** [comment]
It should trigger the warning only if no plugin handles the `async def` test function. Let us know if that's not the case. 👍
