### ISSUE TITLE
Working towards getting vscode to always be able to collect tests

### ISSUE THREAD

**Issue by mahmoudajawad** [pytest-dev/pytest#7106]
In many cases, attempting tests discovery in vscode results in pytest reporting import errors. Many cases are reported in the wild and solutions like adding `conftest.py`, `pytest.ini`, or `__init__.py` somewhere resolves the issue. For me, however, it never did whatever I attempted. I'm using pytest without vscode integration, however I'm really feeling I should do something about this.

This issue from vscode reports some aspect of the issue:
https://github.com/microsoft/vscode-python/issues/10469

For some reason, running pytest programmatically from within vscode python extension results in pytest failing to import test modules. No matter what I did it always fails. I tried manipulating the extension directly at:
`https://github.com/microsoft/vscode-python/blob/649156a09ccdc51c0d20f7cd44540f1918f9347b/pythonFiles/testing_tools/adapter/pytest/_discovery.py`
where I edited `pytestargs` variable with much of options just to get pytest to recognise the correct structure of the package when run from within vscode, but always failed. This is definitely not a bug in pytest, but an attempt to find a middle land between vscode and pytest to make sure everyone benefits from it.

I'm going to reference my comment on vscode for the sake of project structure reference:
https://github.com/microsoft/vscode-python/issues/10469#issuecomment-616388984

```
Python: 3.8.1
pytest: 5.4.1
OS: Debian Buster, Windows 10
```

**Comment by Zac-HD** [comment]
Hi @mahmoudajawad - thanks for taking the time to write this up.

As far as I can tell, this problem is entirely on the VS Code end.  As they are responsible for the integration (and unlike Pytest have paid staff!), there's nothing for us to do here.
