### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by zaufi** [pytest-dev/pytest#7114]
I'm trying to test my plugin w/ various Python versions and the latest `pytest` works on Python 3.8 [only](https://travis-ci.org/github/zaufi/pytest-matcher/jobs/678653647#L191). Python [3.7](https://travis-ci.org/github/zaufi/pytest-matcher/jobs/678653646#L206) and [3.6](https://travis-ci.org/github/zaufi/pytest-matcher/jobs/678653645#L206) failed with the $subj message.

The problem gone if I install `importlib_metadata` package "manually".

**Comment by bluetech** [comment]
The `importlib_metadata` is a dependency of pytest for Python < 3.8:

https://github.com/pytest-dev/pytest/blob/7d5f5a878598aaa7f3e100ef6a97bcd13c1b408d/setup.py#L14

pytest is expected to be installed through `pip` or another program which takes care to install such dependencies. If you are using another installation method, take a look at list from the link above and make sure all of the dependencies are satisfied.

**Comment by zaufi** [comment]
I use [`pipenv`](https://travis-ci.org/github/zaufi/pytest-matcher/jobs/678653646#L183) which is supposed to be a sane install method...

**Comment by DjMoren** [comment]
For people suffering this with pipenv, search into your .lock file if ther's an importlib-metadata entrance... If you don't find it, then regenerate your .lock file again and it will be there and this will be fixed.

**Comment by zaufi** [comment]
Yeah, somehow the problem is gone %)
Case closed.

**Comment by michauds** [comment]
To piggyback on this issue, if using pipenv to manage project requirements, make sure the following stanza is present in the Pipfile: 

```
[version]
python_version = "3.6"
```

My file was missing this. Once added, and a `pipenv lock` later and importlib-metadata was in the lockfile.

Hope it helps.

**Comment by cglacet** [comment]
Also got this error with tox + poetry, right after manually changing `tool.poetry.dependencies.python` from 3.8 to 3.7. Running `tox` right after that triggered the same error. 

Got it fixed by updating my lock file:

```bash
$ poetry lock
$ tox
```
