### ISSUE TITLE
Probable error in doctest doc https://docs.pytest.org/en/4.4.1/doctest.html

### ISSUE THREAD

**Issue by ArtyomKaltovich** [pytest-dev/pytest#7116]
Hello.

I've tried to follow the documentation here https://docs.pytest.org/en/4.4.1/doctest.html

But pytest doesn't collect any tests from rst. It is because the param args:

    $ pytest --doctest-glob='*.rst'

Which should be 

    $ pytest --doctest-glob=*.rst

At least for windows.

Thank you.

**Comment by bluetech** [comment]
I guess Windows interprets this as a literal `'*.rst'`, unlike UNIX shells which remove the quotes.

I think the reason the example uses quotes was as a way to escape the `*` character such that it is not interpeted as a glob by the *shell*. So to be strictly correct the form you suggest shouldn't be used.

Do any of the following work on Windows?

```
$ pytest --doctest-glob '*.rst'
$ pytest '--doctest-glob=*.rst'
```

**Comment by ArtyomKaltovich** [comment]
Hello @bluetech.

Unfortunately, neither works.

I guess the two command (for UNIX and Windows) should be specified separately.

**Comment by asottile** [comment]
`--doctest-glob "*.rst"` should work for both

**Comment by ArtyomKaltovich** [comment]
Hello @asottile thank you for your suggestion.

@nicoddemus Actually the probles is with ' quote, " works fine)

I will do PR.

**Comment by ArtyomKaltovich** [comment]
Sorry for reopening, missclick

THe PR was created, please review. https://github.com/pytest-dev/pytest/pull/7131
