### ISSUE TITLE
pytest --version less verbose by default

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#7128]
Currently `pytest --version` shows something like:

```
$ pytest --version 
This is pytest version 5.4.2, imported from d:\projects\pytest\src\pytest\__init__.py
setuptools registered plugins:
  hypothesis-4.36.0 at d:\projects\pytest\.env36\lib\site-packages\hypothesis\extra\pytestplugin.py
  pytest-forked-1.1.1 at d:\projects\pytest\.env36\lib\site-packages\pytest_forked\__init__.py
  pytest-xdist-1.31.0 at d:\projects\pytest\.env36\lib\site-packages\xdist\plugin.py
  pytest-xdist-1.31.0 at d:\projects\pytest\.env36\lib\site-packages\xdist\looponfail.py
```

We should follow other tools (black, pre-commit, Python), where `--version` shows only the tool version, while `--version --version` shows more information.

```
$ pytest --version
pytest 5.4.2

$ pytest --version --version
This is pytest version 5.4.2, imported from d:\projects\pytest\src\pytest\__init__.py
setuptools registered plugins:
  hypothesis-4.36.0 at d:\projects\pytest\.env36\lib\site-packages\hypothesis\extra\pytestplugin.py
  pytest-forked-1.1.1 at d:\projects\pytest\.env36\lib\site-packages\pytest_forked\__init__.py
  pytest-xdist-1.31.0 at d:\projects\pytest\.env36\lib\site-packages\xdist\plugin.py
  pytest-xdist-1.31.0 at d:\projects\pytest\.env36\lib\site-packages\xdist\looponfail.py
```

(From https://github.com/pytest-dev/pytest/issues/3692#issuecomment-620670986)

**Comment by RonnyPfannschmidt** [comment]
How about using verbosity as indicator

**Comment by debugduck** [comment]
Hi, I'm new but I was wondering if I could look into this?

**Comment by nicoddemus** [comment]
> How about using verbosity as indicator

That was my initial suggestion, but others pointed out that `--version --version` is used by black, pre-commit and even Python itself, so we decided to follow suit.

**Comment by nicoddemus** [comment]
Hi @debugduck,

> Hi, I'm new but I was wondering if I could look into this?

Sure! The related code is here:

https://github.com/pytest-dev/pytest/blob/dd49812dae02c0d8d731fb52b63a975638364f46/src/_pytest/helpconfig.py#L118-L127

You will need to update the definition of the `--version` command-line flag to support being passed multiple times, then you check in `showversion` if it has passed more than once, and adjust the message accordingly.

Feel free to open an incomplete PR if you have questions, we can discuss over there then. 👍

**Comment by debugduck** [comment]
Thank you so much! I’ll work on it.
