### ISSUE TITLE
Ability to choose syntax highlighting style by configuration

### ISSUE THREAD

**Issue by azmeuk** [pytest-dev/pytest#7132]
This issue is somewhat related to #6906.
Syntax highlighting is a great feature that I have been waiting for a long time. Thank you for that!
However, the pygment style that is used by default does not really match my terminal color configuration. Colors have poor contrast, and in the end, I cannot really benefit from syntax highlighting.

I would love to be able to choose the pygments theme from CLI options, or in a configuration file.

Another idea would be to configure the pygments theme with environment variables. This is because, pytest configuration generally depends on the project you are testing, and the configuration file is shipped in the project repository. However colors configuration will be dependent on the developper setup and should probably better remain unversioned. Environment variables allows that.

![terminal](https://user-images.githubusercontent.com/60163/80571413-e1b94200-89fc-11ea-90d0-3c82cac503ce.png)

What do you think?

**Comment by bluetech** [comment]
IIUC, pygments colors are defined by [Styles](https://pygments.org/docs/styles/). There are some builtin styles

```
default emacs friendly colorful autumn murphy manni monokai perldoc pastie borland trac native fruity bw vim vs tango rrt xcode igor paraiso-light paraiso-dark lovelace algol algol_nu arduino rainbow_dash abap solarized-dark solarized-light sas stata stata-light stata-dark inkpot
```

and custom styles can be added as described [here](https://pygments.org/docs/plugins/).

So if we want to make this configurable, and agree to "lock in" to pygments, we'd want a cli argument/ini which selects the pygments style by name.

PR #6934 (still open at time of writing) proposes a `--code-highlight=yes/no` options. It'll probably be wise to consider the two issues together -- I'll refer that issue to here.

**Comment by symonk** [comment]
something to note, as far as I can tell current TerminalFormatter() does not support style=, I toyed around with some others, should be simple enough to bolt on a --pygments-style type arg to terminal_writer and pass it through to highlight (will require a new Formatter tho)

**Comment by symonk** [comment]
Right now we do logic based on 'if' you have pygments or not, from what I can tell its not a core dependency - @bluetech where do we make a collective decision about this stuff? as typically this would require us locking it in as a dependency to gracefully achieve - sure we could say --pygments-style=colorful and only if you have it installed but thats kinda weird

**Comment by bluetech** [comment]
> something to note, as far as I can tell current TerminalFormatter() does not support style=,

Looks like there is a `TerminalFormatter` which doesn't support `style=`, but there is also a [`TerminalTrueColorFormatter`](https://pygments.org/docs/formatters/?highlight=terminalformatter#TerminalTrueColorFormatter) which does support it. I haven't checked the difference, maybe @nicoddemus knows more?

> sure we could say --pygments-style=colorful and only if you have it installed but thats kinda weird

As long as pygments is not a required dep it sounds fine to me to add an argument but ignore it if not installed.

Possibly after #6934 is merged it will be `--code-highlight=<style>`.

**Comment by nicoddemus** [comment]
IMHO I don't think we should double-down on `pygments` just yet, because we might decide to use something else in the future (for example I have my eyes on [rich](https://pypi.org/project/rich/)).

**Comment by GergelyKalmar** [comment]
An elegant and future-proof solution would be to do it similarly to how ``isort`` does it: with an install extra (see https://github.com/PyCQA/isort/blob/develop/isort/format.py#L108, it is quite nicely done!). Allowing the user to ``pip install pytest[color]`` would be very nice. This could install Pygments for now but this could be just as easily replaced with any other tool in the future if there's something more suitable. I would advocate for a more generic flag so that there is no need to deprecate it when the underlying tool is changed.

**Comment by michjnich** [comment]
I'd like to argue for this being more important than a lot of people might think it is. 

As a colourblind person, I really need the ability to customise colours. As it stands, I have issues seeing some of the output - specifically red text on a black terminal. I'm by far from alone in this, and the red on black is a common problem amongst those of us (~12% of the population) that are colourblind. 

Right now, I kind of need to turn the colour off when running pytest so I can actually read the errors, but I do find colourisation extremely useful, and would like to be able to use it.

**Comment by The-Compiler** [comment]
@michjnich Could you clarify (maybe with a screenshot) what output you're talking about exactly? This issue is specifically about code syntax highlighting, while it seems to me you're talking about the output colors in general?

**Comment by michjnich** [comment]
I am, yes. Perhaps I'm wrong about this, but my understanding is that the output colours are hardcoded - they certainly don't seem to respond to changes in terminal setup (I'm using WSL2 btw). The error messages come out in red, which is very difficult to see in a black terminal

Maybe I've conflated 2 things here, but would the "fix" for this issue potentially allow changing the output text colour?

**Comment by The-Compiler** [comment]
No, a fix for this issue - at least from how I understand it - would only allow picking a Pygments theme for customizing the syntax highlighting colors. This is unrelated to pytest's own output coloring (i.e., outside of syntax highlighting).

See #6984 though, which seems to be what you describe.

**Comment by michjnich** [comment]
You're right, #6984 seems more appropriate, though I do note that refers back here as well, and also mentions pygments ...
