### ISSUE TITLE
pytest.config has removed, but how can I push cmdline value to testclass

### ISSUE THREAD

**Issue by wdq347** [pytest-dev/pytest#7137]
### problem

when upgrade to 5.0 version, pytest.config has removed,  I canot push cmdline value to testclass

My test arch only uses one testclass with only one testcase which is extended by parametrize testcase yml file, but I want use cmdline value for testcase yml file.

my code is following

conftest.py file
```
import pytest
def pytest_addoption(parser):
    parser.addoption("--bed", action="store", default="__testbed.yml",
                     help="testbed file")
```
testxx.py file
```
class TestTotal():
    bed_file = pytest.config.getoption("--bed")
    casedir = bed.casedir

    @pytest.mark.parametrize("serial, desc, ops, expect, resetops, judgetype", yml_read.ptest_read_yml(casedir, template))
    def test_cases(self, serial, desc, ops, expect, resetops, judgetype):
        .........................................
```
### trying
I try request.config, buf failed for ```bed``` will be used before testcase and  fixture is useless

I try pytest_generate_tests to set cls var ```bed_file```, also failed for cls var cannot be seen in TestTotal  and only be seen in test function

I only hope varaibles to hold cmdline argument

who can help me, thanks very much!

**Comment by jstoja** [comment]
Hello @wdq347,

`pytest.config` was deprecated in version 4 and has been removed in version 5.
You can use [`pytest.request`](https://docs.pytest.org/en/latest/reference.html#request) to achieve the similar (same) result.

If you need more information about why it was deprecated and examples with pytest.request, please look at the original issue #3050 .

If you don't have any other question, you can close this ticket :)

**Comment by wdq347** [comment]
Thanks @jstoja

using pytest_generate_tests  and metafunc.parametrize will solve this probelm

conftest.py file

```
import os
import pytest
import yml_read

def pytest_addoption(parser):
    parser.addoption("--bed", action="store", default="__testbed.yml",
                     help="testbed file")

def pytest_generate_tests(metafunc):
    bed_file = metafunc.config.getoption("--bed")
...................
    metafunc.parametrize("serial, desc, ops, expect, resetops, judgetype", yml_read.ptest_read_yml(bed_file))
```
