### ISSUE TITLE
documentation: Parametrize - apply indirect on particular arguments

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [pytest-dev/pytest#7138]
https://docs.pytest.org/en/latest/example/parametrize.html#apply-indirect-on-particular-arguments
Runtime example below the description of indirect parametrization uses ` --collect-only` flag which results in
`========================== no tests ran in 0.12s ===========================
`
I believe it should show the actual test result if it suppose to be a meaningful presentation of indirect parametrization.

**Comment by jstoja** [comment]
The command shows:
```
collected 1 item
<Module test_indirect_list.py>
  <Function test_indirect[a-b]>
```

Do you mean that you think it should show something like:
```
collected 1 item
<Module test_indirect_list.py>
  <Function test_indirect[aaa-b]>
```

?

**Comment by pwilczynskiclearcode** [comment]
I mean, that captions says `The result of this test will be successful:` but the command using `--collect-only` doesn't actually run the `test_indirect` test with its assertions. So I would remove the `--collect-only` flag and show the test output. It would be a better example for users not familiar yet with indirect parametrization.

**Comment by Zac-HD** [comment]
Sounds good to me - so long as we add `-v` so the names of the tests are still printed.

Would you like to open a PR?

**Comment by pwilczynskiclearcode** [comment]
https://github.com/pytest-dev/pytest/pull/7209/files
