### ISSUE TITLE
Purpose of ConfTestImportFailure; prevents --pdb

### ISSUE THREAD

**Issue by chaoflow** [pytest-dev/pytest#7150]
Using latest master exceptions during import of conftest files are [caught and turned into](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/config/__init__.py#L511) ``ConftestImportFailure(conftestpath, sys.exc_info())``.

Removing the try/except I can debug the original exception using ``pytest --pdb``, which is not possible if the try/except in place.

What is the purpose for this / would it be an option to drop the try/except?

**Comment by Zac-HD** [comment]
Hmm... does `--pdb` work if we explicitly track the source of the error?  i.e.

```python
            except Exception as err:
                raise ConftestImportFailure(conftestpath, sys.exc_info()) from err
```

**Comment by asottile** [comment]
[`pdb.post_mortem`](https://docs.python.org/3/library/pdb.html#pdb.post_mortem) takes a `traceback=` parameter (which I believe `ConftestImportFailure` retains a reference to) -- perhaps that could be used to fix this?

**Comment by DahlitzFlorian** [comment]
Hi everyone! I would like to work on this one and already had a look at the corresponding file as well as related ones. However, I do not really know where to start and I'm not able to reproduce the issue. I really appreciate any guidance. Thanks in advance!

**Comment by asottile** [comment]
iirc `ConftestImportFailure` is only raised for *nested* conftests (which would be nice to clean up at the same time as well) -- I think if you have a structure like:

```
tests/
    one_test.py
    ns/
        conftest.py
        two_test.py
```

and then an import error / type error / etc. in `conftest.py` then it should reproduce?

**Comment by DahlitzFlorian** [comment]
Thanks @asottile, I was able to reproduce it. Furthermore, I fixed the issue. I'm now adding a changelog file and submit a PR.

**Comment by chaoflow** [comment]
@DahlitzFlorian @asottile Thank you very much for working on and solving this!

For completeness, I saw the hidden exception in a simpler setup:
```
pkg/
  tests/
    conftest.py <- raising exception on import
    test_foo.py
```

As a follow-up: When running only test_foo.py the NameError is and was not hidden, but also cannot be caught using `--pdb` whereas exceptions on import in test_foo.py are being caught be `--pdb`. Shall I open a new issue for that?

**Comment by asottile** [comment]
@chaoflow I believe that's equivalent to #6956

**Comment by DahlitzFlorian** [comment]
I guess after merging #7244 this can be closed now.

**Comment by asottile** [comment]
indeed, thanks for the fixes!
