### ISSUE TITLE
testdir.makepyfile overwrites the one file when making multiple files without specifying a name - could we improve on this?

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#7154]
While working on some plugin development, I was banging my head on the following:

```python
    capabilities = testdir.makepyfile(
        """
        capabilities = {}
        capabilities['a'] = 1
        capabilities['b'] = 2
        capabilities['c'] = 3
        """
        )

    test_file = testdir.makepyfile(
        """
        def test_browser_capabilities_py_file(py_desired_caps):
            pass
        """
    )
```
Using the test name as the file name here is kinda confusing in the instance where you are writing multiple files, as you only end up with one, whereas the user would expect 2 here.  The name= arg was not well documented at least, could we improve on this?

fixed:

```python
def test_desired_caps_get_loaded_into_browser(testdir):
    capabilities = testdir.makepyfile(custom=
        """
        capabilities = {}
        capabilities['a'] = 1
        capabilities['b'] = 2
        capabilities['c'] = 3
        """
        )

    test_file = testdir.makepyfile(
        """
        def test_browser_capabilities_py_file(py_desired_caps):
            pass
        """
    )
    result = testdir.runpytest("--browser-capabilities", capabilities, '--acquire-binary')
    assert result.ret == ExitCode.OK
```

Docs:

```python
makepyfile(*args, **kwargs)[source]
Shortcut for .makefile() with a .py extension.
```

Trivial I know, just an observation

**Comment by nicoddemus** [comment]
Hi @symonk,

Thanks for taking the time to write an issue, we appreciate it.

Sorry you waste time on that, it happens to the best of us. 😁  

Although at first your suggestion seems reasonable, sometimes we do want to overwrite the previous file, for example in a test where we write a file, run pytest, then update the file and run pytest again.

I guess we could raise an error if the user tries to overwrite a previous file, and a `force=True` parameter to overwrite the error, but TBH I'm not sure this error is common enough for us to introduce a breaking change like that.

I definitely agree to warn about this pitfall in the docs for `makefile` though.
