### ISSUE TITLE
Halting pytest.main() when invoked via multiprocessing

### ISSUE THREAD

**Issue by ptrivedi2610** [pytest-dev/pytest#7165]
Hi,

I currently am facing issue to stop execution of pytest from below scenario
1. 'ProcessM' is my main process
2. 'ProcessS' is created using multiprocessing module.
3. ProcessS has some python code. On top of that, its  has a call to pytest.main()
4. When I call ProcessS.terminate(), from ProcessM, I want pytest to halt as well.

How to achieve this ?
I tried using pytest.exit() from ProcessS, sys.exit() from ProcessS etc. but does not work

**Comment by bluetech** [comment]
Hi @ptrivedi2610,

When you say it doesn't work, what does it mean exactly? Nothing happens?

Also, please specify the details requested in the [issue template](https://github.com/pytest-dev/pytest/blob/master/.github/ISSUE_TEMPLATE.md), it will help us understand the issue better.

**Comment by ptrivedi2610** [comment]
@bluetech 
That is slight difficult. Lets make this a bit simpler
Lets say I am calling pytest.main() from my script ScriptP.py

Is there a way to programatically stop pytest session from ScriptP.py, such that ScriptP.py need not to be stopped ?

**Comment by nicoddemus** [comment]
On way to accomplish that is setting `session.shouldstop` to a string, which will make pytest display that string and stop the test run.

You can do that via the `pytest_sessionstart` hook, something like this:


```python
class StopPlugin:

    def pytest_sessionstart(self, session):
        self.session = session

    def stop(self):
        self.session.shouldstop = "stopped by parent process"


stop_plugin = StopPlugin()
pytest.main(argv, plugins=[stop_plugin])
```

Then you need to somehow make the parent process communicate with the child process and call `stop_plugin.stop()`.

**Comment by ptrivedi2610** [comment]
@nicoddemus Thanks a lot for the quick help.
I noticed it doesn't immediately halt the session. The test still move further for sometime and then the session is halted.

Is there a way to fix this  ? I need immediate halting of pytest

**Comment by RonnyPfannschmidt** [comment]
For a direct halt, termination of the process is required

**Comment by ptrivedi2610** [comment]
@RonnyPfannschmidt Yes, but then when calling process.terminate(), I am loosing all the teardowns. I want a behavior similar to SIGINT

The issue is that standard Python has issues with os.kill(). Please refer https://bugs.python.org/issue23948

Thus I have to manually code some workaround that would programatically halt pytest, but after passing through all teardowns

**Comment by RonnyPfannschmidt** [comment]
based on your information there doesnt seem to be a way to make what you ask for work on windows

**Comment by nicoddemus** [comment]
> Thus I have to manually code some workaround that would programatically halt pytest, but after passing through all teardowns

pytest will check `session.shouldstop` after each test, I think that's the only way to ask pytest to stop running in a controlled manner. There's no way to just interrupt the current test mid-way, as pytest doesn't use threads to run tests.

Unfortunately I don't think it is possible to accomplish what you want, I'm afraid.

I'm closing this for now because I think we have exhausted all our options, but feel free to post further questions and we can reopen this if there are more suggestions to try out. :+1:

**Comment by ptrivedi2610** [comment]
@nicoddemus 
Sure, thanks a lot for all the conceptual explanations and help :)
