### ISSUE TITLE
Output of unittest setup incorrectly assigned to call phase

### ISSUE THREAD

**Issue by StefRe** [pytest-dev/pytest#7173]
With this example:
```python
import unittest
class FixturesTest(unittest.TestCase):
    def setUp(self):
        print('In setUp()')
    def test(self):
        print('In test()')
        self.assertTrue(False)
```
I get the following:

```
============================= test session starts =============================
platform win32 -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
PyQt5 5.12.3 -- Qt runtime 5.12.7 -- Qt compiled 5.12.7
rootdir: C:\test
plugins: cov-2.8.1, forked-1.1.3, qt-3.3.0, xdist-1.31.0
collected 1 item

test_fixtures.py F                                                       [100%]

================================== FAILURES ===================================
______________________________ FixturesTest.test ______________________________

self = <test_fixtures.FixturesTest testMethod=test>

    def test(self):
        print('In test()')
>       self.assertTrue(False)
E       AssertionError: False is not true

test_fixtures.py:20: AssertionError
---------------------------- Captured stdout call -----------------------------
In setUp()
In test()
=========================== short test summary info ===========================
FAILED test_fixtures.py::FixturesTest::test - AssertionError: False is not true
============================== 1 failed in 0.16s ==============================
```

i.e. output from setUp() is assigned to the call phase. Expected result is:

```
...
---------------------------- Captured stdout setup ----------------------------
In setUp()
---------------------------- Captured stdout call -----------------------------
In test() 
...
```
  <br>
  
PS: Output from `setUpClass` or `setUpModule` is correctly assigned to the setup phase.

**Comment by nicoddemus** [comment]
Unfortunately I'm afraid there's not much we can do here:

pytest will try to execute the `TestCase` test during its `call` step, by delegating the actual execution to the `TestCase.run` method. `TestCase.run` takes care of all the steps required by the `unittest` framework, such as calling `setUp`, `setUpClass`, `tearDown`, cleanup functions, etc. This is all implemented inside the `run` method in a single block of code: https://github.com/python/cpython/blob/441416c9a06f11f28e17d56c915ea6116c0c9ea7/Lib/unittest/case.py#L558-L625.

If `TestCase.run` was implemented in terms of smaller pieces (say, `TestCase.run_setup`, `TestCase.run_test`, `TestCase.run_teardown`, etc) then we would be able to call each piece at the appropriate times on pytest's side, but that's not the case.

I'm closing this for now, feel free to follow up with further questions. 👍

**Comment by StefRe** [comment]
Thanks for the very quick response. In the end it's just a petty issue, so no worries.
