### ISSUE TITLE
Contributing guide vs. development guide

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#7202]
We have two documents that serve a similar purpose:

- https://docs.pytest.org/en/latest/contributing.html (source: https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst)
- https://docs.pytest.org/en/latest/development_guide.html (source: https://github.com/pytest-dev/pytest/blob/master/doc/en/development_guide.rst)

The development guide includes some of its own content, and also embeds https://github.com/pytest-dev/pytest/blob/master/RELEASING.rst.

The development guide's own content seems mostly outdated or redundant with the CONTRIBUTING.

My proposal to fix this is:

- Add a new releasing section to the docs, embedding RELEASING.rst. Or just remove it -- I'm not sure that anyone doing pytest releases will need to read the instructions on the rendered docs..?
- Change the development guide to only link to the contributing and releasing guides, mostly to avoid breaking the URL.

**Comment by Zac-HD** [comment]
Sounds good to me.

Let's keep the releasing docs though, even if everyone currently responsible knows what to do they're still useful as inspiration to other projects or aspiring pytest contributors :slightly_smiling_face:
