### ISSUE TITLE
pytest_collection_modifyitems in subdir conftest recieves all tests

### ISSUE THREAD

**Issue by thejcannon** [pytest-dev/pytest#7212]
Given the following test setup:
```
tests
| - a
    | - __init__.py
    | - conftest.py
    | - test_foo.py  
| - __init__.py
| - test_bar.py
```

```python
# a/conftest.py
def pytest_collection_modifyitems(items):
    for item in items:
        print(item.name)
```

```python
# a/test_foo.py
def test_foo():
    pass
```

```python
# test_bar.py
def test_bar():
    pass
```

Based on the docs, I wouldn't expect to see "test_bar" be printed, but I do.

---
Debug:
```
Package            Version
------------------ -------
atomicwrites       1.4.0
attrs              19.3.0
colorama           0.4.3
importlib-metadata 1.6.0
more-itertools     8.2.0
packaging          20.3
pip                10.0.1
pluggy             0.13.1
py                 1.8.1
pyparsing          2.4.7
pytest             5.4.2
setuptools         39.0.1
six                1.14.0
wcwidth            0.1.9
zipp               3.1.0
```

**Comment by RonnyPfannschmidt** [comment]
The exposed behaviour is correct, please link the misleading docs

**Comment by thejcannon** [comment]
[conftest.py: local per-directory plugins](https://docs.pytest.org/en/latest/writing_plugins.html#conftest-py-local-per-directory-plugins):

>Local conftest.py plugins contain directory-specific hook implementations.

Makes me believe all the hooks in a `conftest.py` will be directory-specific.

I also can't find anything that tells me _which_ hooks in a subdir `conftest.py` receive all tests and which recieve the scoped down version, which furthers my assumption they _all_ operate on just the tests in the subdir. 

Perhaps a note similar to "pytest_report_header"'s second note would suffice?

>Note
This function should be implemented only in plugins or conftest.py files situated at the tests root directory due to how pytest discovers plugins during startup.

**Comment by bluetech** [comment]
@thejcannon I think at the moment any change to the behavior here would be a breaking change, so cannot be done for a while. So your suggestion to add a note to the docs sounds good to me. Would you like to submit a PR for this?

**Comment by nimeshvashistha** [comment]
Hi, can i take this issue?

**Comment by The-Compiler** [comment]
@nimeshvashistha Since @thejcannon didn't answer for a couple of weeks it seems fine to take this - as discussed, only the doc addition without any behavior/code changes for now. Thanks!

**Comment by nimeshvashistha** [comment]
> @nimeshvashistha Since @thejcannon didn't answer for a couple of weeks it seems fine to take this - as discussed, only the doc addition without any behavior/code changes for now. Thanks!

alright, thanks!

**Comment by thejcannon** [comment]
@The-Compiler @nimeshvashistha My bad 😅 September has been a _very_ busy month.

 Put me on the PR when it's ready. I haven't had much runtime with the Python documentation ecosystem and would love a reason to get familiar 😄
