### ISSUE TITLE
Get rootdir in nose tests

### ISSUE THREAD

**Issue by axys16** [pytest-dev/pytest#7216]
Hi,
It is possible to get the rootdir in nose tests (outside the test class and inside the setUp() ) ?

**Comment by RonnyPfannschmidt** [comment]
There is no official support for that

Use fixtures

**Comment by nicoddemus** [comment]
I can think of an ugly ugly hack, which might work (untested):

```python
import pytest

rootdir = None

@pytest.fixture(autouse=True, scope="session")
def grab_pytestconfig(pytestconfig):
    global rootdir
    rootdir = pytestconfig.rootdir
```

But I concur with @RonnyPfannschmidt, if possible convert at least part of the suite to a proper fixture.

Hope this helps!

**Comment by axys16** [comment]
Thanks, this helps :)

I'm using nosetests to do functional tests through a little framework that I did ( https://github.com/AffilaeTech/niav ).
I use it to test a javascript API.
Do you think fixtures can be used in this particular case ?

**Comment by RonnyPfannschmidt** [comment]
fixtues and parameterization will never be deeply integrated into unit-test support,
they only have a very basic integration for auto-use fixtures to aid migration to pytest
