### ISSUE TITLE
Test Discovery - Skip Test if Failure

### ISSUE THREAD

**Issue by scott-wilson** [pytest-dev/pytest#7218]
Hello!

Example tests:

`tests/test_failure.py`
```python
this is a syntax error

def test_failure():
    pass
```

`tests/test_succeed.py`
```python
# this is not a syntax error

def test_succeed():
    pass
```

If I were to use PyTest to discover the tests (specifically, discovering in Visual Studio Code's Python plugin), then it'll fail discovering all of the tests. Instead, I would like to be able to skip discovering that file (or up until where the error happened) and move onto the next file.

Is there a way to do this currently, or would this have to be implemented?

**Comment by RonnyPfannschmidt** [comment]
There is a option to still run tests on collection errors

**Comment by asottile** [comment]
in particular `--continue-on-collection-errors`

**Comment by symonk** [comment]
@scott-wilson as outlined previously:

```
  --continue-on-collection-errors
                        Force test execution even if collection errors occur.
```

Does this answer your question sufficiently? :)

**Comment by scott-wilson** [comment]
Partially. I found that https://pypi.org/project/pytest-custom-exit-code/
--suppress-tests-exit-code did the trick. Thanks!
