### ISSUE TITLE
add cli option for junit_suite_name

### ISSUE THREAD

**Issue by mulawamichal** [pytest-dev/pytest#7225]
hi,
it would be useful to have a explicit `--junit-suite-name=foo` cli option available, instead of having to use workarounds with overriding an ini value using `-o junit_suite_name=foo`.

**Comment by nicoddemus** [comment]
Hi @mulawamichal, 

We added `-o` exactly to allow having duplicated commanda line options and ini options.

Why do you feel is that a workaround?

**Comment by mulawamichal** [comment]
my understanding was, that intention of a ini file is some general common config persistent for all tests. But I can imagine, that there are multiple independent test-suites in one test project. So it would be nice to be able to pass such per-testsuite options in elegant way - using a dedicated cli arg

**Comment by nicoddemus** [comment]
I understand your point, but we have decided to avoid having duplicated ini and command-line options, because they generate maintenance/docs overhead without much gain.

So I suggest to go ahead and use `-o` as if it was a command-line argument. 👍 

But thanks for the suggestion anyway, we appreciate it!

**Comment by stefan894** [comment]
"-o junit_suite_name=foo" seems no to longer work

**Comment by stefan894** [comment]
> "-o junit_suite_name=foo" seems no to longer work

sry. false alarm, issue was on my side, I was starting pytest inside a python application and had issue with the string replacement...

In case others are struggling with the same issue, this is the code that works on my side (python 3.10.12/linux/pytest 9.0.2):

```
import sys
import pytest

timestr = "tb6_testresults/log_setup" + ".xml"
ini_file = 'pytest_tb6.ini'
test_suite="junit_suite_name=foo"

if __name__ == "__main__":
    sys.exit(pytest.main(["-m setup", f'-c{ini_file}', f'--junitxml=./{timestr}', "-x", "-s", f'-o{test_suite}']))
```
