### ISSUE TITLE
monkeypatch-style `chdir`

### ISSUE THREAD

**Issue by jtratner** [pytest-dev/pytest#7228]
First - thank you so much for pytest - amazing tool and I love it!

The `tmp_path` and `tmpdir` fixtures are excellent, but can easily lead to changing current directory for all tests without realizing it (which can be confusing in error output).

It'd be useful to have a monkeypatch-style helper to change the directory built-in to pytest, equivalent to the `chdir` fixture below.

```
import pytest
import contextlib
from pathlib import Path
import os

ORIGINAL_DIR = Path.cwd()

@pytest.fixture
def chdir():
    original_path = Path.cwd()

    def do_chdir(path):
        curdir = Path.cwd()
        os.chdir(path)
    try:
        yield do_chdir
    finally:
        os.chdir(original_path)

def test_original_path():
    assert Path.cwd() == ORIGINAL_DIR


def test_something(tmpdir, chdir):
    assert Path.cwd() == ORIGINAL_DIR
    mypath = tmpdir.join("whatever")
    mypath.mkdir()
    chdir(mypath)
    assert Path.cwd() == mypath

```

The best-est implementation would make `tmpdir.chdir()` _automatically_ restore working environment after test completed, but I could see that being complicated.

- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
<details><summary>pip list</summary>
<pre>
Package            Version
------------------ -------
attrs              19.3.0 
importlib-metadata 1.6.0  
more-itertools     8.3.0  
packaging          20.3   
pip                18.1   
pluggy             0.13.1 
py                 1.8.1  
pyparsing          2.4.7  
pytest             5.4.2  
setuptools         40.6.2 
six                1.14.0 
wcwidth            0.1.9  
zipp               3.1.0  
</pre>
</details>

- [x] pytest and operating system versions - pytest 5.4.2 + OSX 
- [x] minimal example if possible

**Comment by jtratner** [comment]
(happy to contribute a pull request if this is an acceptable item - might need some help figuring out how to enforce test ordering tho :) )

**Comment by nicoddemus** [comment]
Hi @jtratner,

There's already [`monkeypatch.chdir`](https://docs.pytest.org/en/latest/reference.html#_pytest.monkeypatch.monkeypatch) which does exactly that. 😁

**Comment by jtratner** [comment]
oof 😅 slightly embarrassing haha  (I swear I searched for it! haha) - lemme put up a PR to update the docs to call this out with tmpdir/tmp_path examples

**Comment by nicoddemus** [comment]
Hehehe no worries, thanks!
