### ISSUE TITLE
Add an EqualsTester helper class

### ISSUE THREAD

**Issue by Strilanc** [pytest-dev/pytest#7230]
It would be great if pytest provided a utility similar to [Guava's EqualsTester](https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/testing/EqualsTester.java).

There are a lot of ways to incorrectly implement equality in python (e.g. returning False instead of NotImplemented for an unrecognized type, accidentally making `__ne__` inconsistent with `__eq__`, violating the `a==b implies hash(a) == hash(b)` invariant, etc). EqualsTester verifies all of these properties while providing an interface that's more convenient than a series of `a == b != c` assertions.

Basically, usage would look like this:

```
eq = pytest.EqualsTester()
eq.add_equivalence_group(1, 1.0, fractions.Fraction(1, 1))
eq.add_equivalence_group(2)
```

and every time you call `add_equivalence_group` the equals tester checks that 1) all members of the group are equal to all other members and 2) no members from different groups are equal. Also it can check things like "If I give you an unrecognized object, `__eq__` should return NotImplemented.

We have an implementation of this concept in Cirq ( https://github.com/quantumlib/Cirq/blob/master/cirq/testing/equals_tester.py ), but it really belongs in a testing library instead of a quantum computing library.
```

**Comment by Zac-HD** [comment]
This does sound like a useful feature, but it's also for a very specific use-case and I don't think it would fit well in `pytest`.

Hopefully other contributors might be able to suggest a package where it would fit well; if not this might be the start of a new one!

**Comment by RonnyPfannschmidt** [comment]
just as for the general topic of assertion helpers, this should start in a new package, so a good api can emerge over time before binding it into a test runner

**Comment by Zac-HD** [comment]
Closing as out-of-scope for `pytest`; we wish you all the best though :slightly_smiling_face:
