### ISSUE TITLE
Contradiction in breaking change versioning policy

### ISSUE THREAD

**Issue by gsnedders** [pytest-dev/pytest#7241]
https://docs.pytest.org/en/latest/changelog.html documents that "Backward incompatible (breaking) changes will only be introduced in major versions with advance notice in the Deprecations section of releases", yet pytest 5.4.0 contains documented breaking changes.

What is the policy for breaking changes and what versions can contain them, and can we update the documentation to match actual practice here?

**Comment by symonk** [comment]
Hi @gsnedders this does indeed seem like we should revisit (or update the documentation to reflect what the current policy is - that im not sure of):

```
pytest 5.4.0 (2020-03-12)
Breaking Changes
#6316: Matching of -k EXPRESSION to test names is now case-insensitive.

#6443: Plugins specified with -p are now loaded after internal plugins, which results in their hooks being called before the internal ones.

This makes the -p behavior consistent with PYTEST_PLUGINS.

#6637: Removed the long-deprecated pytest_itemstart hook.

This hook has been marked as deprecated and not been even called by pytest for over 10 years now.

#6673: Reversed / fix meaning of “+/-” in error diffs. “-” means that sth. expected is missing in the result and “+” means that there are unexpected extras in the result.

#6737: The cached_result attribute of FixtureDef is now set to None when the result is unavailable, instead of being deleted.

If your plugin performs checks like hasattr(fixturedef, 'cached_result'), for example in a pytest_fixture_post_finalizer hook implementation, replace it with fixturedef.cached_result is not None. If you del the attribute, set it to None instead.
```

According to this:

```
Versions follow Semantic Versioning (<major>.<minor>.<patch>).

Backward incompatible (breaking) changes will only be introduced in major versions with advance notice in the Deprecations section of releases.
```

This would imply such changes should be existing in 6.X.X

**Comment by Zac-HD** [comment]
I think we should actually update *practice* to match our documentation and policy - if we release such breaking changes in a minor version in future, IMO we should revert them and wait until the next major release.
