### ISSUE TITLE
tox -e docs not supported out of the box on windows platform

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#7251]
When building docs, we use 'sh' which fails from the pycharm terminal on windows for example.  Will investigate if tox can have a platform agnostic command for towncrier that will work for everybody.

```
[testenv:docs]
basepython = python3
usedevelop = True
deps =
    -r{toxinidir}/doc/en/requirements.txt
    towncrier
whitelist_externals = sh
commands =
    sh -c 'towncrier --draft > doc/en/_changelog_towncrier_draft.rst'
    # the '-t changelog_towncrier_draft' tags makes sphinx include the draft
    # changelog in the docs; this does not happen on ReadTheDocs because it uses
    # the standard sphinx command so the 'changelog_towncrier_draft' is never set there
    sphinx-build -W --keep-going -b html doc/en doc/en/_build/html -t changelog_towncrier_draft {posargs:}
```

**Comment by symonk** [comment]
@nicoddemus how does someone get the ability to assign 'labels' on issue(s) on the project here at pytest?

**Comment by RonnyPfannschmidt** [comment]
@symonk we would either need a wrapper script around towncrier, or a towncrier feature addition to write the draft to a file

**Comment by symonk** [comment]
on my radar for this week

**Comment by mcsitter** [comment]
One can get around this limitation by using windows subsystem for linux. This worked for me!

In the meanwhile an note could be added to the [write documentation](https://docs.pytest.org/en/latest/contributing.html#write-documentation) section stating the incompatibility with windows and linking to the installation guide of the [microsoft documentation](https://docs.microsoft.com/en-us/windows/wsl/install-win10). I would offer to open a pull request for that.
