### ISSUE TITLE
Please remove the dependency on 'py'

### ISSUE THREAD

**Issue by mgorny** [pytest-dev/pytest#7259]
Since 'py' isn't really receiving any attention, and distributions end up carrying growing pile of patches just to keep it working, I think it'd be reasonable for pytest to stop requiring it. Just to be clear, right now we need to patch tests to work with pytest-4+, we hackaround breakages in python3.8 and python3.9 is around the corner with yet another set of problems.

**Comment by RonnyPfannschmidt** [comment]
We are working on it, it's still going to take years

**Comment by bluetech** [comment]
In master, we are down to depending on only two parts of py: `py.path.local` and `py.iniconfig` (and one instance of `py.error.Error` which I can remove). Migrating from `py.path.local` would require a big effort, but `py.iniconfig` can be imported quite easily. WDYT @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
Ini config is already externalized, no need to copy into pytest

**Comment by kerizane** [comment]
Is the plan documented anyway? Any preferences or guidelines?

**Comment by RonnyPfannschmidt** [comment]
the plan is not documented anywhere, in detail yet, we created https://github.com/pytest-dev/pytest/projects/4 to de-tangle and track it

**Comment by Zac-HD** [comment]
Personally I'd be happy to have a hard-cutover to `pathlib` in pytest 6.0

It's a significant change and may be a breaking one for some users and plugins, but I think likely to cause *less* churn in dependencies than trying to invent a compatibility layer.  I estimate that almost no end-users will be directly affected, and only a small fraction of plugins - and importantly that it will be easier on pytest maintainers to help plugins migrate than to have an upstream compat layer.

**Comment by nicoddemus** [comment]
> It's a significant change and may be a breaking one for some users and plugins

Oh no it would break the world: `tmpdir` (a *very* used fixture) is a `py.path.local` object.

**Comment by Zac-HD** [comment]
Ah.  Yes, that would do it :man_facepalming:

**Comment by RonnyPfannschmidt** [comment]
Personally i will reject a compatibility layer beyond casting some objects to local paths and leaving behind the legacy properties which do

Support for py.path.local will then be constrained to the python versions where pylib works and pylib will turn into a optional dependency that's declared dead

**Comment by bluetech** [comment]
> In master, we are down to depending on only two parts of py: py.path.local and py.iniconfig

For some reason, one slipped my mind: `py.xml` used in the junitxml plugin.

**Comment by nicoddemus** [comment]
Oh right. That will be a simple, but arduous refactoring.

**Comment by kerizane** [comment]
https://github.com/pytest-dev/pytest/issues/4970

**Comment by gnikonorov** [comment]
Question. What is the reason for py’s existence? Were the features it added just not available in standard python at the time or was it optimized for pytest?

**Comment by nicoddemus** [comment]
The first one: it dates before/around Python 3.0 was released, so it contained a bunch of utilities that worked in both Python 2 and Python 3.0 at the time, plus general utilities such as xml manipulation, file first-class objects, I/O, and including `py.test`, which was the early stages of pytest. `pytest` was in fact born by extracting `py.test` from `py`.

Since then, there are better alternatives for all of which is implemented there, that's why we have no interest in adding new features to it, or even maintaining it if possible.

**Comment by gnikonorov** [comment]
Thank you for the explanation @nicoddemus

**Comment by bluetech** [comment]
As mentioned in [this comment](https://github.com/pytest-dev/pytest/pull/8251#issuecomment-796852908), I have looked more closely at what remains to be done before we can deprecate py.path. Of course, before we can deprecate, there must be replacements for everything which takes or returns a `py.path`. After all of our recent PRs, I created a branch which removes all py.path functionality for which there exist replacements (i.e. can be readily deprecated), here: https://github.com/bluetech/pytest/commits/rm-py. That branch passes all tests and lints which ensures I don't miss anything.

There are only two remaining py.path usages which cannot be easily handled:

### pathlist

The `pathlist` ini type (as in `parser.addini("mypaths", "my ini option", type="pathlist")`). This type takes a line list and returns the values as a list of paths relative to the ini file. This type is not documented anywhere that I can see.

It is not possible to fix a return type, so this would either need to be removed, replaced or broken without deprecation.

<details>
<summary>Plugins which use this</summary>

```py
pytest-pythonpath/pytest_pythonpath.py
9-    # py.test has an issue where the cwd is not in the PYTHONPATH. Fix it here.
10-    if os.getcwd() not in sys.path:
11-        sys.path.insert(0, os.getcwd())
12:    parser.addini("python_paths", type="pathlist", help="space seperated directory paths to add to PYTHONPATH via sys.path.insert(0, path)",
13-                  default=[])
14:    parser.addini("site_dirs", type="pathlist", help="space seperated directory paths to add to PYTHONPATH via site.addsitedir(path)",
15-                  default=[])
16-
17-

pytest-cloud/pytest_cloud/plugin.py
174-    parser.addini(
175-        "cloud_develop_eggs",
176-        "list of python package paths to install in develop mode on the remote side",
177:        type="pathlist",
178-    )
179-
180-

pytest-srcpaths/pytest_srcpaths.py
7-
8-def pytest_addoption(parser):
9-    parser.addini("srcpaths",
10:                  type="pathlist",
11-                  help="Add paths to sys.path")
12-
13-

pytest-xdist/src/xdist/plugin.py
142-    parser.addini(
143-        "rsyncdirs",
144-        "list of (relative) paths to be rsynced for remote distributed testing.",
145:        type="pathlist",
146-    )
147-    parser.addini(
148-        "rsyncignore",
149-        "list of (relative) glob-style paths to be ignored for rsyncing.",
150:        type="pathlist",
151-    )
152-    parser.addini(
153-        "looponfailroots",
154:        type="pathlist",
155-        help="directories to check for changes",
156-        default=[py.path.local()],
157-    )

pytest-postgresql/src/pytest_postgresql/plugin.py
100-
101-    parser.addini(
102-        name='postgresql_load',
103:        type='pathlist',
104-        help=_help_load,
105-        default=None
106-    )
```
</details>

### reportinfo

This is a method that needs to be implemented by custom `Item`s. One of its return values is a `py.path`.

Most plugins *implement* the method, which is normally called by pytest, but some plugins do *call* it. So the `py.path` is in both a covariant and contravariant position.

If we only care about the plugin-implements case, then we can change the contract to "returns path-like object" instead of "returns py.path". If we also care about the plugin-calls case, then we need to come up with another solution.

<details>
<summary>Plugins which use this</summary>

```py
pytest-isort/pytest_isort.py
184:    def reportinfo(self):

pytest-pycodestyle/src/pytest_pycodestyle.py
85:    def reportinfo(self):

pytest-pycodestyle/tests/test_pytest_pycodestyle.py
118:    def test_reportinfo(self):

pytest-ghostinspector/pytest_gi/plugin.py
241:    def reportinfo(self):

pytest-qml/src/pytestqml/nodes.py
130:    def reportinfo(self):

pytest-alembic/src/pytest_alembic/plugin/plugin.py
105:    def reportinfo(self):

pytest-codestyle/tests/test_pytest_pycodestyle.py
118:    def test_reportinfo(self):

pytest-codestyle/src/pytest_pycodestyle.py
85:    def reportinfo(self):

pytest-check-links/pytest_check_links/plugin.py
223:    def reportinfo(self):

pytest-gherkin/pytest_gherkin/gherkin.py
174:    def reportinfo(self):

pytest_oot/pytest_oot/oot_plugin.py
223:    def reportinfo(self):

pytest-flake8/pytest_flake8.py
141:    def reportinfo(self):

pytest-eradicate/pytest_eradicate.py
84:    def reportinfo(self):

pytest-asptest/asptest/classes.py
171:    def reportinfo(self):

pytest-freeze-reqs/freeze_reqs/pytest_freeze_reqs.py
99:    def reportinfo(self):

pytest-mypy-plugins/pytest_mypy_plugins/item.py
352:    def reportinfo(self) -> Tuple[Union[py.path.local, str], Optional[int], str]:

pytest-jasmine/pytest_jasmine.py
157:    def reportinfo(self):

pytest-notebook/pytest_notebook/plugin.py
306:    def reportinfo(self):

pytest-checkipdb/pytest_checkipdb.py
47:    def reportinfo(self):

pytest-pydocstyle/tests/test_pytest_pydocstyle.py
131:    def test_reportinfo(self):

pytest-pydocstyle/src/pytest_pydocstyle.py
104:    def reportinfo(self):

python-pytest-cases/pytest_cases/case_parametrizer_new.py
827:#             fspath, lineno, _ = item.reportinfo()

pytest-bandit/pytest_bandit/controller.py
95:    def reportinfo(self):

pytest-mypy/src/pytest_mypy.py
176:    def reportinfo(self):

pytest-translations/pytest_translations/po_spelling.py
123:    def reportinfo(self):

pytest-translations/pytest_translations/mo_files.py
85:    def reportinfo(self):

pytest-translations/pytest_translations/po_files.py
83:    def reportinfo(self):
101:    def reportinfo(self):
119:    def reportinfo(self):

pytest-black/pytest_black.py
89:    def reportinfo(self):

agent-python-pytest/pytest_reportportal/service.py
717:            return test_item.reportinfo()[2]

pytest-mccabe/pytest_mccabe.py
92:    def reportinfo(self):

pytest-requests/pytest_python_requests.py
418:    def reportinfo(self):

pytest-reqs/pytest_reqs.py
160:    def reportinfo(self):

pytest-dash/pytest_dash/behaviors.py
85:    def reportinfo(self):

pytest-docstyle/src/pytest_pydocstyle.py
104:    def reportinfo(self):

pytest-docstyle/tests/test_pytest_pydocstyle.py
131:    def test_reportinfo(self):

pytest-yapf3/src/pytest_yapf3/__init__.py
147:    def reportinfo(self):

pytest-pylint/pytest_pylint/plugin.py
391:    def reportinfo(self):

pytest-molecule/pytest_molecule/__init__.py
233:    def reportinfo(self):

pytest-contexts/pytest_contexts.py
31:    def reportinfo(self):
64:    def reportinfo(self):

dbt-adapter-tests/pytest_dbt_adapter/spec_file.py
689:    def reportinfo(self):

pytest-mypy-testing/src/pytest_mypy_testing/plugin.py
74:    def reportinfo(self) -> Tuple[str, Optional[int], str]:

allure-pytest/allure/pytest_plugin.py
115:            description = item.reportinfo()[2]

pytest-cpp/src/pytest_cpp/plugin.py
155:    def reportinfo(self):

pytest-flakes/pytest_flakes.py
102:    def reportinfo(self):

pytest-cram/pytest_cram/__init__.py
83:    def reportinfo(self):
```
</details>

**Comment by RonnyPfannschmidt** [comment]
i wonder if we can revise  the concept of the reportinfo while ridding us of py.path

i'd also like to rid pytest of the copy of pylibs exceptioninfo to bring in better features for tracebacks on async, twisted and frameworks in general

**Comment by bluetech** [comment]
As for `pathlist` (see comment https://github.com/pytest-dev/pytest/issues/7259#issuecomment-803460109 above), I think we can add a `paths` INI type (`parser.addini("mypaths", "my ini option", type="paths")`) to replace `pathlist`. This would of course return a list of `Path`s instead of `py.path`s. Then we could deprecate `pathlist`.

Another alternative is to just deprecate `pathlist` without replacement, it's not used *that* much and not really hard to implement oneself.

I think I will submit a PR to add `paths` unless someone has other preferences.

> i wonder if we can revise the concept of the reportinfo while ridding us of py.path

Right, for `reportinfo` there doesn't seem to be simple solutions. This ^ would need some design work.

**Comment by bluetech** [comment]
OK, here is my suggestion:

### For 6.3.0 (next minor release)

- Add a single `PendingDeprecationWarning` type for `py.path`. Go over all `py.path` usages and add it. Message for each case would be different and indicate the suggested replacement. It would be possible to ignore the entire class based on the type, or specific cases based on the message.
- Add a section to the deprecation docs with a rationale, the deprecation timeline and listing all of the deprecated `py.path` usages and their replacements (single central place to link to), along with the version from which the replacement is available.
- Add a note to the release notes indicating the deprecation has began and linking to the doc.

One hitch here is `reportinfo` which has no replacement but I suggest we punt it for now -- better than nothing. Of course it won't be marked deprecated until there is a replacement.

### For 7.0.0 (next major release)

Change the `PendingDeprecationWarning` to a `DeprecationWarning`.

### For 8.0.0

Remove. I estimate this would be 2-3 years from now.

---

If this sounds OK, I can do the work for the 6.3.0 release.

The idea here is just to give ample time to transition.

Does anyone have alternative ideas on how we could reduce the pain here? The audiences are:

- Users: presumably we want them to just pin or require a new pytest version and convert all `tmpdir` to `tmp_path` etc. and be done with it. Can we ease these migrations?

- Plugins 1: they often would want to support older versions which don't have full pathlib support. Should we just rely on the long deprecation period + dropping support for older versions, or can we offer some way to do it without dropping compat?

- Plugins 2: some probably have their own APIs which expose `py.path`. Can we aid them in migrating to pathlib?

I know @RonnyPfannschmidt has ideas around `legacy_path` etc. but I don't think I've seen the exact idea/plan.

**Comment by RonnyPfannschmidt** [comment]
@bluetech the basic idea of legacy_path is that we can turn the pylib dependency optional at some point while leaving the deprecated calls in - a legacy_path would eventually act "like" a `py.path.local` but only pylib  is installed

so in  sense we would pass around "py.path.local" tokens that only turn into a `py.path.local` when actually used

exposing legacy_path would also help them to migrate

 beleive the basic idea should be to help everyone migrate off `py.path.local` as soon as possible and investigate how other plugins can have that easy (maybe by providing some extra collection classes in a compat package)

**Comment by The-Compiler** [comment]
FWIW I'm strongly opposed to adding more to the 6.3.0 backlog unless absolutely required. We haven't had a feature release in more than half a year, and adding more stuff rather than finishing what we've started (mostly #8435 at this point?) is only going to make things worse.

**Comment by RonnyPfannschmidt** [comment]
Thanks for the check, I'll aim at finishing that by the end of the week and let's push the rest to 6.4/7

**Comment by The-Compiler** [comment]
> Unfortunately this will be a huge huge pain. There are very large suites out there that make extensive use of `tmpdir`, and porting to `tmp_path` is a trivial but manually intensive labor.

We could try to write a tool in the spirit of [unittest2pytest](https://github.com/pytest-dev/unittest2pytest) or [hypothesis codemod](https://hypothesis.readthedocs.io/en/latest/extras.html#codemods) to automate this to the extent that's possible. [LibCST](https://libcst.readthedocs.io/en/latest/) seems like an excellent base for something like this, but I have no real experience with it.

For reference, here's hypothesis' implementation: [codemods.py](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/codemods.py)

**Comment by bluetech** [comment]
I like the plugin idea, didn't think of that! If we can pull it off it would solve a lot of problems nicely. So here's some discussion points on this approach.

## Scope of plugin

(There might be some items I'm missing below)

### Fixtures

I think including the fixtures is pretty obvious - I believe these are

- `tmpdir`
- `tmpdir_factory`
- `testdir` 

All should be straightforward.

### Hooks

These are less straightforward. We would need some mechanism which allows the plugin to modify an existing hook by adding an argument + converting it to another argument. With enough hackery this is probably doable? Doesn't have to be pretty...

- `pytest_ignore_collect`
- `pytest_collect_file`
- `pytest_pycollect_makemodule`
- `pytest_report_header`
- `pytest_report_collectionfinish`

### APIs

Some APIs can probably be done by monkeypatching, if we want to go this route.

- `cache.makedir()`
- `Config.invocation_dir`
- `Config.rootdir`
- `Config.inifile`
- `Session.startdir`
- `request.fspath`
- `Node.fspath`
- `TerminalReporter.startdir`

### Plugin APIs

There are some APIs which plugins use like `Node` constructors etc. which take py.path. I'm not very optimistic about being able to handle these in the compat plugin -- would need the normal deprecation route.

## Rollout of plugin

A gradual rollout might be something like

- Minor release: Implement as a *built-in* plugin. Can disable with `-p no:legacypath`. Add `PendingDeprecationWarning`, doc etc as discussed in previous comment.
- Major release: Change pending deprecation to full deprecation
- Major+1 release: Remove internal plugin, move to an external plugin that anyone who doesn't want to migrate can install (no deprecation warnings, except the entire plugin itself being deprecated).

**Comment by bluetech** [comment]
> We could try to write a tool in the spirit of unittest2pytest or hypothesis codemod to automate this to the extent that's possible. LibCST seems like an excellent base for something like this, but I have no real experience with it.

That would be great to have. Even if it only tries to handle `tmpdir` and `tmpdir_factory` it would help a lot of projects probably. Here are some of the conversions that pytest itself did for its own testsuite:

- #8357
- #8209
- #8174

**Comment by RonnyPfannschmidt** [comment]
if we contain py.path in a plugin thats part of pytest, im pretty sure we can just add a proxy object to it as well

we already havea hook handler for converting, imho we should be fine if we introduce the proxy

a key reason for introducing legacy_path/LEGACY_PATH inside of pytest is that it allows to swap in a proxy that will defer functionality so we no longer need pylib installed without an api

we already have a example of the hook fixup in the codebase (just no clean idea on how to upstream it

**Comment by nicoddemus** [comment]
From https://github.com/pytest-dev/pytest/issues/7259#issuecomment-846598389:

> Hooks
These are less straightforward. We would need some mechanism which allows the plugin to modify an existing hook by adding an argument + converting it to another argument.

Reading this again, I realized that unfortunately doesn't seem a plugin should be able to change existing hooks like that (even with very deep black magic), but I'm not sure it is really necessary: a large test suite might contain a few plugins which implement those hooks, and seems manageable to update those by hand. In this case I think we can move ahead with deprecating/removing the `py.path` arguments.

> APIs
Some APIs can probably be done by monkeypatching

Same here. We should probably be able to slowly deprecate/remove those. If not, monkeypatching might be a solution indeed.

**Comment by RonnyPfannschmidt** [comment]
Again, I already implemented the switch for core hooks,

We need to upstream the mechanism to pluggy

**Comment by nicoddemus** [comment]
> Again, I already implemented the switch for core hooks,

You mean #8463, correct? Yes, but that's implemented in the core, as a stop gap measure so we can deprecate legacy path arguments in favor of pathlib ones. I was mentioning that we don't need this "legacy path" plugin to implement that workaround, as by the time the plugin is released the arguments legacy path arguments should have been removed.

Or do you mean to upstream to pluggy a similar mechanism that allows plugins to modify/fix hooks (like you did in #8463), even for hooks they don't own?

**Comment by RonnyPfannschmidt** [comment]
closing as completed as we removed the py dependency when the CVE did hit

**Comment by The-Compiler** [comment]
Didn't we have some further plans around this? I thought at some point we wanted to get rid of our `py` shim, possibly deprecating and then removing things in your `legacypath` built-in plugin, no?

**Comment by bluetech** [comment]
The proposed deprecation plan was here: https://github.com/pytest-dev/pytest/issues/7259#issuecomment-843872291

It should be mostly straightforward code-wise to deprecate and move to external plugin for those who still want it. At least after 8.1 removes various related already-deprecated functionality like the `path` parameters in hooks.

But for me at least the main reason for doing so was to remove the `py` dependency, and since we already did this then it's starting to look less appealing to put people through the deprecation pain (as @nicoddemus said, the py.path stuff is used *a lot* so this *will* be painful).

**Comment by RonnyPfannschmidt** [comment]
We have to put local path to a rest, it's a White elephant

**Comment by nicoddemus** [comment]
The pain in this case is for users that still use `tmpdir` in their code bases to add `pytest-tmpdir` to their dependencies... I think it is worthy tradeoff, as it has the big benefit of *plain pytest installations* no longer having `tmpdir`, which might point inexperienced users in the wrong direction.

One point to consider is the absolute ton of content out there that expects `tmpdir` to be builtin, and will be out-dated.

**Comment by RonnyPfannschmidt** [comment]
It's important to put into perspective that pyllib was a good idea in 2005, we are now close to 2025, its not been aging well
