### ISSUE TITLE
[documentation] document fixture caching

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#7269]
Hi team, after searching a bit I couldn't find anything insightful to highlight fixture caching, but from reading a few open issues it seems that fixtures do infact cache values? I was unable to find documentation around that in the docs

**Comment by RonnyPfannschmidt** [comment]
That example is python string constant interning, nothing pytest does

**Comment by symonk** [comment]
@RonnyPfannschmidt  derp!, but fixtures do cache values? Ive been reading some open issue(s) relating to what sounds like fixture caching, first thing i tried to find was docs relating to it but was unable to find anything

**Comment by RonnyPfannschmidt** [comment]
Fixtures are not cached, but rather scope/parameter bound

A precursors of today's scope bound fixtures used a cache to manage scopes / parameters
