### ISSUE TITLE
Add a list of builtin markers to doc 

### ISSUE THREAD

**Issue by xinbinhuang** [pytest-dev/pytest#7270]
Hi team,

Thanks for the great work!

I am using more and more pytest recently, so I have gone through the docs back and forth a lot.
I think it will be great to add a subsection that includes a list of builtin markers along with documentation and usage on this page https://docs.pytest.org/en/latest/mark.html .

I can create a PR if you guys agree. 

Best
Bin

- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

**Comment by Zac-HD** [comment]
That would be great - thanks Bin!

Ideally this would come with a test so that our build if new marks are added (or removed) without updating the docs :smile:

**Comment by xinbinhuang** [comment]
> Ideally this would come with a test so that our build if new marks are added (or removed) without updating the docs 😄

hmm, do you have similar tests already implemented that I can refer to or any suggestions on how may achieve this? I am thinking pre-commit hook may do the trick

**Comment by nicoddemus** [comment]
I think we can postpone that other bit, the doc update is already a good improvement IMHO. 😁 

Thanks a lot @xinbinhuang!
