### ISSUE TITLE
Question How to run cloned code under debugger ? 

### ISSUE THREAD

**Issue by Izison** [pytest-dev/pytest#7276]
Hi,  I am trying to  customize PyTest.  I have cloned git repo. 
Now when I run <repo>/src/pytest/__main__.py file under debugger in PyCharm it compalins about missing NameError: name 'version' is not defined.
I suspect that this version is generated as part  of release procedure. 

Any help How I can continue ? 
And guide-lines how to run PyTest source code under debugger ? 

P:S I am studying how pytest code works because I use as part of the job setup and in the future I have plans to join project as developer or QA engineer.

**Comment by asottile** [comment]
hello!  you'll want to first install pytest in some way, I'd suggest a virtual environment

for example:

```bash
virtualenv venv
. venv/bin/activate
venv/bin/pip install -e .
```

`version` is set up by `setuptools-scm` as part of installation


the [contributing guidelines](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst) have some instructions on how to get set up with a development environment -- you may also find those helpful!

**Comment by Izison** [comment]
Thank you, very much.
![image](https://user-images.githubusercontent.com/32955881/83397839-92e93880-a3fe-11ea-83b7-3a9a291d4af3.png)
