### ISSUE TITLE
import marks arguments from external file

### ISSUE THREAD

**Issue by RomanLeca** [pytest-dev/pytest#7278]
Hello!

If there already is a solution for the below issue, please point me in the right direction. I wan't able to identify anything related.

**Problem:**
I have large sets of parameters for complex e2e tests (yes, we're trying everything pytest has to offer), which don't fit nicely in the test file because of readability.

To solve this, I am working on a solution that allows parametrizing tests from a csv, including markers and test IDs, both optional. So far, I have managed to make it work for markers, but only partially. I'm currently stuck at passing the optional parameters (e.g. reason). 

Code:
```
def split_markers(csv_markers=None):
    """Handle none, one or more markers, split by '+' sign in a csv cell"""
    if csv_markers:
        markers = csv_markers.split('+')
        marker_list = []
        for each_marker in markers:
            marker_list.append(getattr(pytest.mark, each_marker))
        return marker_list

def form_line_content(lst=None):
    """Break down csv contents and return them in pytest.param(...) format"""
    test_id, *test_data, markers = lst
    test_markers = []
    if markers:
        test_markers = split_markers(markers)
    return pytest.param(test_data, marks=test_markers, id=test_id)

def load_csv(py_file, csv_filename, skip_headers=True):
    """Process a csv file with the following structure: test_id, *params, marks"""
    csv_path = Path(py_file).parent / csv_filename
    # read csv
    with open(csv_path, 'r', encoding='utf-8') as csv_file:
        rows = reader(csv_file)
        if skip_headers:
            next(rows)  # Skips first row
        for row in rows:
            yield form_line_content(row)

csv_file = load_csv(__file__, 'marks.csv')

@pytest.mark.parametrize('test_data', csv_file)
def test_markers_csv(test_data):
    val1, val2 = test_data
    assert val1 == val2
```
###### *.csv file contents:
```
test_id,value1,value2,marks
passing_test,1,1,
onemarker,2,1,regression
two_markers,1,1,second+third
skipping,4,1,skip
skipping_with_reason,4,1,skip(reason="expected to skip")
```
I am currently trying to avoid using an extra column for marker optional arguments, because handling reasons for 2+ markers on the same line would be tricky. Still, I can't "force" get_attr to pick up argument list, as well :)
 
The --strict-markers option is enabled in pytest.ini, which conditions the following error for the last line at collection time:
**'skip(reason="expected to skip")' not found in `markers` configuration option**

If there is a smarter way of handling marks that I accidentally ignored, I'm glad to try that :)

Thank you!

pip list:
---------------------- ----------
aiohttp                3.6.2
allpairspy             2.5.0
apipkg                 1.5
async-timeout          3.0.1
atomicwrites           1.3.0
attrs                  19.3.0
bcrypt                 3.1.7
certifi                2019.11.28
cffi                   1.14.0
chardet                3.0.4
colorama               0.4.3
cryptography           2.8
decorator              4.4.2
dnspython              1.16.0
execnet                1.7.1
Faker                  4.0.2
idna                   2.9
idna-ssl               1.1.0
importlib-metadata     1.5.2
jsonpath-rw            1.4.0
more-itertools         8.2.0
multidict              4.7.5
mysql-connector-python 8.0.19
packaging              20.3
paramiko               2.7.1
pip                    18.1
pluggy                 0.13.1
ply                    3.11
protobuf               3.6.1
py                     1.8.1
pycparser              2.20
PyNaCl                 1.3.0
pyparsing              2.4.6
pyperclip              1.7.0
pytest                 5.4.1
pytest-forked          1.1.3
pytest-html            2.1.1
pytest-metadata        1.8.0
pytest-rerunfailures   9.0
pytest-xdist           1.31.0
python-dateutil        2.8.1
PyYAML                 5.3.1
requests               2.23.0
selenium               3.141.0
setuptools             40.6.2
six                    1.14.0
text-unidecode         1.3
typing-extensions      3.7.4.1
urllib3                1.25.8
wcwidth                0.1.9
yarl                   1.4.2
zipp                   3.1.0

**Comment by asottile** [comment]
you could maybe build some sort of mapping like

```json
{"skip": {"reason": "because!"}}
```

(I'm using json since structured data is going to be a lot easier than writing a hand-made parser)

and then

```python
test_fn = ...
for k, v in reasons_dct.items():
    marker_fn = getattr(pytest.mark, k)
    marker = marker_fn(**v)
    test_fn = marker(test_fn)
```

**Comment by Zac-HD** [comment]
Closing this because the question has been inactive for at least two weeks.

**Comment by RomanLeca** [comment]
Thank you, Anthony!
I will definitely try this.

Kind regards!
Roman
