### ISSUE TITLE
Ignoring result

### ISSUE THREAD

**Issue by xeor** [pytest-dev/pytest#7279]
I want to implement a `pytest.ignore()` that will behave as `pytest.skip()`, but without any visuals. ie, no yellow `S`, or `xx skipped` in the ui.

Using pytest with testinfra I end up with a ton of tests that I don't want to show in the UI because of parameterize. I asked at https://stackoverflow.com/questions/62079737/pytest-ignore-test-not-just-skip, and have looked around but can not find any indication that this is possible.

I can submit a pr on this, but I want to see if it will get accepted first, and/or if there are any deep reason why this can not be implemented.

**Comment by RonnyPfannschmidt** [comment]
Im -1 on that one

**Comment by DahlitzFlorian** [comment]
I do not see a benefit in creating such a feature. Without a clear purpose and benefits for all pytest users, I suggest to create a pytest plugin. This way, people who need this feature can install the plugin. But as it seems to be an edge case, I wouldn't include it in pytest core.

**Comment by xeor** [comment]
Thanks for the kind rejection :) This is an edge case, and would also probably be missused.
But poking around, I really don't see any good way of making this into a plugin. Using `pytest_collection_modifyitems` and filter them out would be a good way. But I can't find any way to access information about a run.

Do you mind pointing me in the correct direction before closing this issue?

**Comment by DahlitzFlorian** [comment]
To be honest, I did not write a pytest plugin on my own yet. I suggest to have a look at [this](https://docs.pytest.org/en/latest/writing_plugins.html#writing-your-own-plugin) part of the documentation, which covers writing your own plugins. It also contains a link to a list of external plugins, which can be used as a starting point. Maybe someone else can point you in a more appropriate direction, sorry for that.

**Comment by asottile** [comment]
I think that silently ignoring failures is not a good idea and we should not implement this as a feature

that said, you can already build something that works like that today if you want

something like

```python
class SilentlyFail(Exception):
    pass

def allow_silent_failures(func):
    @functools.wraps(func)
    def allow_silent_failures_inner(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except SilentlyFail:
            pass
    return allow_silent_failures_inner

def silently_fail(*args):
        raise SilentlyFail(*args)

@allow_silent_failures
def test_my_thing():
        if True:
            silently_fail()
```

(apologies for typos, this code is untested-just-typed-into-github-comment-box and might need some small tweaks)

**Comment by xeor** [comment]
Thanks for the code @asottile , however, I'm not sure how this should work? Did you forget about some part of the code? The only thing it does is to ignore an exception. I'm getting the same result by just using `return` inside my function instead of `silently_fail`.

The goal is to not count the run as a test.. I don't want the green dots, nor a count against (x passed in ...).

Eg

```py
@pytest.mark.parametrize('test', ([1,2,3,4,5,6,7,8]))
def test_my_thing(test):
    if test % 2:
        silently_fail()  # some magic here to let pytest pretend this runnever happened
```

I want to return

```
test_infratest.py ....

=== 4 passed in 0.07s ===
```

not

```
test_infratest.py ........

=== 8 passed in 0.07s ===
```

**Comment by asottile** [comment]
I'd suggest just filtering your parametrize up front then:

```python
cases = [1,2,3,4,5,6,7,8]

@pytest.mark.parametrize('test', [case for case in cases if case % 2 == 0])
def test_my_thing(test):
    ...
```

**Comment by xeor** [comment]
@asottile yes.. That is what I want to do. However, I am using [testinfra](https://testinfra.readthedocs.io/en/latest/), so I have tests like:

```
def test_my_thing(host):
    ...
```

I found no way to skip some host inside the test. And I don't want to filter all the hosts before, there is a lot of them.. Still any options?

**Comment by h-vetinari** [comment]
There's some prior discussion on this in #3730

**Comment by asottile** [comment]
ah thanks, yes that's an exact duplicate -- let's continue the discussion there
