### ISSUE TITLE
Add option to not install dependencies (offline install/reproducible)

### ISSUE THREAD

**Issue by FFY00** [pytest-dev/pytest#7281]
Hi,

Right now we use https://github.com/pytest-dev/pytest-runner to run tests when building packages in Arch Linux. We do this because we have a requirement to not pull anything from outside the build environment. We make sure all dependencies are met and all sources that go into the build environment get their checksum/signature verified. The most obvious benefits of this are reproducibility and control over the sources.

As `pytest-runner` is deprecated, and not PEP517 compatible, would it be possible to add an option to `pytest` to achieve such behavior? It could be called something like `--ofline`.

Would this fit the scope? If not, where would this fit instead? Are there any alternatives?

Cheers,
Filipe

**Comment by RonnyPfannschmidt** [comment]
Out of scope,for pytest

**Comment by FFY00** [comment]
Could you elaborate a bit? Why is it out of scope?

This option would just not install dependencies, which seems pretty reasonable.

Where should this be provided if not on pytest?

**Comment by Zac-HD** [comment]
`pip install --no-deps pytest`

https://pip.pypa.io/en/stable/reference/pip_install/#install-no-deps

**Comment by bluetech** [comment]
@FFY00 I think we *may* be misunderstanding your request. Can you explain what you mean by "install dependencies", or provide an example of a package that is causing you issues?

**Comment by FFY00** [comment]
@bluetech nevermind, there was a misunderstanding from my part on how some components behave. Sorry to bother :)
