### ISSUE TITLE
switch from py.iniconfig to iniconfig

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#7291]
As part of removing pylib

See also #7259

**Comment by bluetech** [comment]
My preference is to copy over the implementation to pytest, instead of depending on the `iniconfig` package. This is because:

- It is an internal dependency AFAIK.
- It is small (~100 lines).
- Python dependency management is still... lacking.
- By having it in tree we can adapt and adjust it freely without backward compat concerns or cross-project synchronization overhead.

**Comment by RonnyPfannschmidt** [comment]
Personally I'm strictly opposed to own internal copies of libraries /structural components,

As pypa/pip#988 is going to be resolved in a reasonable time frame I'm actually working on taking specific logic components out of pytest and to foster more sharing among test runners

**Comment by bluetech** [comment]
My experience with npm-style micro dependencies is very negative. At work, our gigantic Django-based server has 50 transitive dependencies (include dev dependencies). The JS frontend has about 3000. I hope Python doesn't go that way.

**Comment by RonnyPfannschmidt** [comment]
i'm happy to go with some type of automated vendoring apporach, i'm not going to keep custimized internal copies of things that should be external and shared

i agree that npm is a extreme

i also believe that a good choice in granularity + vendoring tooling could make things transitively better

**Comment by nicoddemus** [comment]
Given the discussion should we go ahead with https://github.com/pytest-dev/pytest/pull/7292? I think so, because even if we decide to vendor it later, part of the work is done already.

**Comment by bluetech** [comment]
My preference is that integrate iniconfig into pytest, and allow changes like a regular module, i.e. not vendor or depend on it. I'd like to be able to make it conform to our code style, linters, add type annotations, fix bugs, refactor and add new features directly, etc. Also, according to [this](https://pypistats.org/packages/iniconfig) the package isn't used much by other projects, and is maintained by Ronny, so it will essentially be "owned" by pytest anyway...

But just to be clear, if both @nicoddemus and @RonnyPfannschmidt think it's a good idea then I'm perfectly fine with that (the PR itself looks good), I'm just trying to advocate my position :)

**Comment by RonnyPfannschmidt** [comment]
It's used by tox via pylib, and based on the experience with py.code integration I am severely opposed to integration of any other lib, i rather want to focus on extraction of more functional components rather than having hidden internal apis

**Comment by The-Compiler** [comment]
I'm a bit late to the party, but is there a good reason that pytest really needs a hand-rolled ini-parser rather than `configparser` in the Python stdlib? Didn't notice this before the 6.0 release, but that additional dependency probably caused quite a bit of additional work across various Linux distributions packaging pytest.

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler i vaugely recall that back when holger and me experimented with debugging/configuration/parsing/behaviors of various config parsers (for both pytest and tox) there where shortcomings in default behaviors and debugging, so we created a own variant 

i would take a while before i can get at digging up the exact technical details from that time, i imagine the situation is a bit different now, but im not sure if we can easily replace the parsers yet

**Comment by sk-** [comment]
@RonnyPfannschmidt would be nice if you could dig up the technical reasons for having a custom parser. Specially given since then many python versions reached their EOL.
