### ISSUE TITLE
(internal) should we clean up the python 2 only issues now that core support has ended?

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#7296]
this would cut down a bit on our backlog and would give us more room to focus on open issues.

I'm proposing the following:

- close those tagged with [platform: python 2 only]
- leave a comment to the effect of "core support has ended for python 2, however community patches are still accepted for this issue (even though this issue is closed) <<link to the 2.7 / 3.4 support document>>

@nicoddemus @bluetech @RonnyPfannschmidt  thoughts?

**Comment by RonnyPfannschmidt** [comment]
I enthusiastically approve

**Comment by bluetech** [comment]
Looking at the list of issues https://github.com/pytest-dev/pytest/issues?q=is%3Aopen+is%3Aissue+label%3A%22platform%3A+python+2+only%22

Looks fine to me to close them.

**Comment by symonk** [comment]
+1, sounds good!

**Comment by nicoddemus** [comment]
Sure! 👍

**Comment by asottile** [comment]
alright, I'll handle this then!

**Comment by nicoddemus** [comment]
Cool thanks @asottile!

**Comment by asottile** [comment]
this has been done -- this is the messaging I used:

> hello, first off thank you for the issue!
> 
> python 2.x support has ended for pytest core.
> 
> we've decided in #7296 to close the python-2-specific issues to free up some space in our backlog.  however, in accordance to our [python 2.7 and 3.4 support](https://docs.pytest.org/en/latest/py27-py34-deprecation.html) community patches *will still be accepted* to the `4.6` series to fix bugs for python 2.  (so if this issue is important to you and you have a patch to fix it, feel free to make a PR targeting the 4.6.x branch despite this ticket being closed).
