### ISSUE TITLE
pytest~=4.6: `UnboundLocalError: local variable 'letter' referenced before assignment`

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest#7310]
While implementing a test for https://github.com/pytest-dev/pytest-forked/issues/33 I've hit this:
```python
INTERNALERROR>   File "~/src/github/pytest-dev/pytest-forked/.tox/py27-pytest46/lib/python2.7/site-packages/_pytest/terminal.py", line 190, in pytest_report_teststatus
INTERNALERROR>     return report.outcome, letter, report.outcome.upper()
INTERNALERROR> UnboundLocalError: local variable 'letter' referenced before assignment
```

Looking at the repo, it seems to have been fixed on master by @nicoddemus as a part of https://github.com/pytest-dev/pytest/pull/6337. But it still persists in the `4.6.x` branch.

The fix should be trivial: just add a fallback variable value before if-blocks. No need to backport that whole PR (unless somebody thinks that it should be done, of course).

Ref: https://github.com/pytest-dev/pytest/pull/7311.

**Comment by RonnyPfannschmidt** [comment]
based on the content, i'd just backport the full pr

**Comment by webknjaz** [comment]
@RonnyPfannschmidt here's an alternative per your suggestion: https://github.com/pytest-dev/pytest/pull/7314.

**Comment by asottile** [comment]
via #7314
