### ISSUE TITLE
Autouse Session Scoped Fixture ScopeMismatch

### ISSUE THREAD

**Issue by ImXron** [pytest-dev/pytest#7320]
Hey guys,

Just wanted to get some clarification to see if this is expected behavior. I want to override a session scoped fixture that's in my conftest, with a function scoped fixture in my test file (same name).

[Repl with code ready to run](https://repl.it/join/eupujtlu-imxron)

#### Error:
```
ScopeMismatch: You tried to access the 'function' scoped fixture 'ssh' with a 'session' scoped request object, involved factories
conftest.py:24: def autouse_fixture(config, power_supply, ssh)
test_my_test.py:3: def ssh(config)
ERROR test_my_test.py:test_my_test
```

Looks like it's trying to use the ssh fixture in my test file instead of the one in my conftest? Works fine when not using an autouse fixture in that example. Also works if I rename the function scoped fixture something other than ```ssh```.

#### env:
```
platform linux -- Python 3.7.5rc1, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
```

#### conftest.py
```python
import pytest


@pytest.fixture(scope="session")
def config():
    print("config session fixture.")


@pytest.fixture(scope="session")
def power_supply(config):
    print("power supply fixture.")


# I want to override this fixture in the test file.
@pytest.fixture(scope="session")
def ssh(power_supply):
    print("ssh session fixture.")


@pytest.fixture(scope="session", autouse=True)
def autouse_fixture(config, power_supply, ssh):
    print("autouse session fixture.")
```

#### test_my_test.py
```python
import pytest

# Overriding the fixture from the conftest file.
@pytest.fixture
def ssh(config):
    print("ssh function scoped fixture.")


def test_my_test(ssh):
    print("test")
```

Thanks!

**Comment by RonnyPfannschmidt** [comment]
thats currently not resolvable, unless yu can make the test level fixture also session scoped, it currently cant work

this is a limitation of the fixture system, and  at first glance it seems its one that shouldnt change

**Comment by ImXron** [comment]
@RonnyPfannschmidt thanks for the clarification. I'll work around this with either a new name or a session fixture.

Seems like Pytest should support this, considering how it already respects scope and overriding?

But if this is some weird edge case that no one runs into, no worries.

**Comment by RonnyPfannschmidt** [comment]
its structurally impossible to support as of now, since lookup is name based and you override a session scoped name with a function scoped name, then all users of that name are required function scope as well

**Comment by ImXron** [comment]
Ahh I see. Thanks for the context.

Closing.
