### ISSUE TITLE
Pytest Entry Point for Registering a Cleanup function when tests throw uncaught exception

### ISSUE THREAD

**Issue by szegel** [pytest-dev/pytest#7325]
Hello All,

I am trying to write Pytests to automate testing in a complicated Lab environment.  It is critical that the cleanup code ALWAYS get called, even if a test throws an uncaught exception.  I would like to be able to register my cleanup function with Pytest, and have it get run no-matter what happens.

Goal main.py:

```
print("Starting Pytest")
try:
    Run All My Tests
except e:
   call_my_registered_cleanup_function()
   throw(e)
```

**Comment by graingert** [comment]
how about:

```python
@pytest.fixture(scope="session", autouse=True):
def _cleanup():
    print("Starting Pytest"
    yield
    call_my_registered_cleanup_function()
```

**Comment by szegel** [comment]
I'll give it a try and get back to you.  My concern is I have seen my tests fail immediately, without gracefully closing Pytest.  I will try to re-create my concern with a simple example.

**Comment by graingert** [comment]
Does your suite fail to collect? `--collect-only`

**Comment by szegel** [comment]
So I think this solution will work for me.  If I mash cntrl-c, I get "Exception occurred while handling another exception", but I can easily write my own SIGINT exception handler to make sure that doesn't happen. Thanks for the fast reply!

**Comment by szegel** [comment]
I think the issues I have seen with pytest not closing properly is when our python to C++ bindings core dump, which is not Pytest's fault.

**Comment by szegel** [comment]
Thank You!
