### ISSUE TITLE
The link in the latest version docs points to an non existing URL

### ISSUE THREAD

**Issue by tzickel** [pytest-dev/pytest#7331]
https://docs.pytest.org/en/latest/reference.html

A notice on top says "This is the development version. The latest stable version is Version 5.4.3" with a link that does not work:

https://docs.pytest.org/en/latest/5.4.3/reference.html

**Comment by symonk** [comment]
@tzickel thank you for raising this

**Comment by nicoddemus** [comment]
Thanks @tzickel!

That banner is added by readthedocs automatically. I did spend some time in reading through the options and on Google, but couldn't really figure out why the link is wrong. 🤔 

Any help here is appreciated.

**Comment by stsewd** [comment]
@nicoddemus that banner isn't the one that rtd injects, that banner comes from the flask theme https://github.com/pallets/pallets-sphinx-themes/blob/b0c6c41849b4e15cbf62cc1d95c05ef2b3e155c8/src/pallets_sphinx_themes/themes/pocoo/layout.html#L24-L29

**Comment by nicoddemus** [comment]
Ahh that great @stsewd thank you!

Do you have a suggestion on how to fix it?

**Comment by stsewd** [comment]
Sorry, no. I can see the link is being generated wrong here https://github.com/pallets/pallets-sphinx-themes/blob/b0c6c41849b4e15cbf62cc1d95c05ef2b3e155c8/src/pallets_sphinx_themes/versions.py#L135
