### ISSUE TITLE
'pytest -v' shows full path on Windows when pytest.ini is on substituted drive

### ISSUE THREAD

**Issue by thorstenkampe** [pytest-dev/pytest#7333]
- [x] a detailed description of the bug or suggestion
- [x] platform win32 -- Python 3.8.3, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
- [x] minimal example if possible

The subject says it all: pytest on Windows shows full path of the test file in verbose mode when there is a `pytest.ini` in the current directory and the directory is on a substituted drive:
```
> pwd
Path
----
F:\cygwin\home\thorsten\python\modules

> pytest -v
platform win32 -- Python 3.8.3, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- f:\scoop\apps\python\current\python.exe
cachedir: .pytest_cache
rootdir: C:\data\flash drive\cygwin\home\thorsten\python\modules
collected 32 items

test_toolbox.py::test_assert_installed PASSED
test_toolbox.py::Test_get_version::test_1 PASSED
test_toolbox.py::Test_get_version::test_2 PASSED
```
```
> touch pytest.ini
> pytest -v
platform win32 -- Python 3.8.3, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- f:\scoop\apps\python\current\python.exe
cachedir: .pytest_cache
rootdir: F:\cygwin\home\thorsten\python\modules, inifile: pytest.ini
collected 32 items

F:\cygwin\home\thorsten\python\modules\test_toolbox.py::test_assert_installed PASSED
F:\cygwin\home\thorsten\python\modules\test_toolbox.py::Test_get_version::test_1 PASSED
F:\cygwin\home\thorsten\python\modules\test_toolbox.py::Test_get_version::test_2 PASSED
```
```

**Comment by thorstenkampe** [comment]
One more observation: creating an empty `pytest.ini` changes the `rootdir` log line from `rootdir: C:\data\flash drive\cygwin\home\thorsten\python\modules` to `rootdir: F:\cygwin\home\thorsten\python\modules`. This reflect the fact that `F:` is a substituted drive:
```
> subst
F:\: => C:\data\flash drive
```
Changing the subject acccordingly.

**Comment by Zac-HD** [comment]
What do you think it *should* display?

**Comment by thorstenkampe** [comment]
@Zac-HD pytest should display just the file name (as it does on Linux and if the the test file is not on a substituted drive). For me it looks like the current path is incorrectly determined. I'm in `F:\cygwin\home\thorsten\python\modules` - not in `C:\data\flash drive\cygwin\home\thorsten\python\modules` (the latter is "mounted"/substituted to the former)

**Comment by nicoddemus** [comment]
Thanks @thorstenkampe!

This will be fixed by https://github.com/pytest-dev/pytest/pull/6523. 👍
