### ISSUE TITLE
[RFC]: Add documentation for proper way to close issues fixed by PRs

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest#7334]
Hi all,

I went through all the documentation ( I think ) and couldn't find guidance on the best way to close issues which have been fixed by a PR. I think we should have this documented somewhere for the benefit of both contributors and issue raisers. Can we come up with a set of rules we should follow for this and document it somewhere?

My apologies if I missed this in the docs.

For example: should they be closed on issue merge, on version release, what about if the original requestor is unresponsive, etc.

**Comment by nicoddemus** [comment]
Hi @gnikonorov,

You mean old issues that have been fixed already by a PR, but haven't been closed by oversight?

I that case we just usually close with a message like "Fixed by #XXXX".

I agree this can be documented though. I suggest we add a new section below the one being introduced in https://github.com/pytest-dev/pytest/pull/7332.

**Comment by gnikonorov** [comment]
Hi @nicoddemus

I mean, let's say an issue is fixed by a PR that will go out in the next minor version ( which in this example is a month away ). Should we close the issue immediately on PR merge, or when the minor version is released to users.

And I guess more generally, for all cases ( bug fixes, major release, minor releases, unresponsive issue raisers, etc )

**Comment by nicoddemus** [comment]
Ahhh OK!

We usually just close it immediately after merging... we usually don't leave a note saying when the change from an issue will be released, unless someone asks.

**Comment by gnikonorov** [comment]
Thanks for clarifying, @nicoddemus!

I'll add a section to `CONTRIBUTING.rst`

**Comment by gnikonorov** [comment]
Will add after https://github.com/pytest-dev/pytest/pull/7332 is merged

**Comment by symonk** [comment]
can't we use a commit message to auto close it?

I always thought a commit like so:

```
git commit -m "Fix issue 2567; closes #2567" 
```

would automatically close such issue when the commit makes its way back to master.  I think there are pros and cons of that feature however.

**Comment by gnikonorov** [comment]
@symonk - I can see that leading to a lot of ‘please rebase your branch’ type comments. Is there any way we can put it into the PR template instead?

**Comment by nicoddemus** [comment]
Putting it into the PR template would be good, although I would encourage contributors to also add a reference to the issue number to the commits: this helps when browsing history/git blame.

**Comment by gnikonorov** [comment]
Does anyone know if there’s a way we can automate the check for that instead of manually looking?

**Comment by nicoddemus** [comment]
Not that I'm aware of.

**Comment by gnikonorov** [comment]
It’s easy enough to do as a pre-commit check with a regex, but I can’t find a widely accepted solution for GitHub, just some home grown solutions

**Comment by gnikonorov** [comment]
I take that back...we can just perform the same check server side as well in a hook. Thoughts @nicoddemus and @symonk? We can make a rule such that the pr pipeline fails if all commit messages in the PR don’t match the format proposed in https://github.com/pytest-dev/pytest/issues/7334#issuecomment-640584184.

But, I’m not sure if we’d need it twice. Perhaps all we’d need to do is add it to pre-commit and not bother with the server side check assuming that someone rebasing and then force pushing wouldn’t bypass pre-commit

**Comment by nicoddemus** [comment]
> We can make a rule such that the pr pipeline fails if all commit messages in the PR don’t match the format proposed in #7334 (comment).

I appreciate the willingness to automate/make this easier for us, but TBH I'm -1 on the idea, it seems like too much bureaucracy. Many times a commit is not about closing an issue specifically, but applying code reviews suggestions, fixing linting, and many others reasons not directly tied to closing/fixing an issue. Adding a check here seems overkill to me.

I would propose just to update the PR template instead, for example an extra check with something like this:

```markdown
[ ] - If this fixes an issue, add a line `Fix #XYZW` to the PR description and/or commits (where `XYZW` is the issue number). See [github docs](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) for more information.
```

I believe this will be enough to nudge contributors to do the right thing.

**Comment by gnikonorov** [comment]
Sure @nicoddemus. Sorry I thought we require an issue for every PR

**Comment by nicoddemus** [comment]
> Sorry I thought we require an issue for every PR

Oh no need to be sorry of course! 

Usually PRs have an issue associated, but a few do not. 👍

**Comment by gnikonorov** [comment]
In that case I’ll just add a check to the template and update the docs accordingly

**Comment by nicoddemus** [comment]
Sounds good, thanks!
