### ISSUE TITLE
inaccurate documentation

### ISSUE THREAD

**Issue by shilobar** [pytest-dev/pytest#7336]
In https://docs.pytest.org/en/5.4.3/reference.html, under "log_file", it says: "Sets a file name relative to the pytest.ini file"

Instead, the log file is created relative to the directory where pytest was invoked.

I ran `pytest _test.py` in a subdirectory, with a `pytest.ini` a few directories above it, with the following config:

```
[pytest]
python_files = _test*.py
testpaths = lib
log_cli = True
log_cli_level = DEBUG
log_file = pytest-logs.txt
log_file_level = DEBUG
```

A `pytest-logs.txt` was created in the directory where I ran pytest.

I'm running:
pytest 5.4.3
macOs 10.15.4

**Comment by shilobar** [comment]
Btw, I'm not sure if this is a documentation issue or a bug.

**Comment by codeslash21** [comment]
Hii, I can see that this issue is not closed. Can I take this issue?

**Comment by The-Compiler** [comment]
@codeslash21 @symonk already opened #7350 for this (see the link above your comment).

**Comment by reynaldipriandika** [comment]
hay everybody, I know that I'm really new to contribute in open source project, so please help me with all your kindness. Can you tell me how I can contribute for this issue ?. Thanks a lot

**Comment by symonk** [comment]
Feel free to take this, using my PR as a starting point 😀 I’m working on some other issues at the moment

**Comment by frnsimoes** [comment]
Hey, everyone. Is it ok if I try this out? Thanks!
