### ISSUE TITLE
Allow users to specify version information for the `required_plugins` INI key

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest#7346]
Building off of https://github.com/pytest-dev/pytest/issues/7305, we should allow users to specify the required versions of the plugins they would like to make required. This should be implemented as defined in [PEP 440](https://www.python.org/dev/peps/pep-0440/#version-specifiers), and should be optional after each plugin name in the list of required plugins.

For example:
```ini
[pytest]
required_plugins = pugin1===1.0.0 plugin2<=5.6.1 plugin3 plugin4~=3.2.1
```

**Comment by gnikonorov** [comment]
Thoughts @nicoddemus and @RonnyPfannschmidt?

**Comment by nicoddemus** [comment]
Yep the description is accurate, thanks. We should use [packaging](https://pypi.org/project/packaging/) to match the versions.

**Comment by gnikonorov** [comment]
Thanks for suggesting packaging @nicoddemus, I’ll use it
