### ISSUE TITLE
pass list in command line args and use in fixture

### ISSUE THREAD

**Issue by vbpatel73** [pytest-dev/pytest#7347]
I want to pass list of browsers in command line and use this list in fixture to run all tests on all browsers.
 I need to pass firefox and chrome as list from command line and use here in this fixture
@pytest.fixture(scope="session", autouse=True, params=["firefox","chrome"])

**Comment by vbpatel73** [comment]
is there any other option as i do not know how to create plugin

**Comment by gnikonorov** [comment]
@vbpatel73 take a look at this and see if it solves your problem: https://stackoverflow.com/questions/40880259/how-to-pass-arguments-in-pytest-by-command-line

**Comment by SalmonMode** [comment]
A simpler solution is to use the `pytest_collection_modifyitems` to mark the tests according to the browser referenced in their `nodeid`, then you can just do `pytest -m firefox` or `pytest -m "chrome or firefox"`.

**Comment by gnikonorov** [comment]
@vbpatel73 do the above 2 solutions answer your question?

**Comment by RonnyPfannschmidt** [comment]
Btw, a pytest.param("browsername",marks=pytest.mark.browsername) should work if I recall correctly

**Comment by gnikonorov** [comment]
@vbpatel73 - any of the 3 above solutions should work to fix your issue. I am closing this issue as it has been 2 weeks of inactivity. If you find that this issue persists, please kindly re-open.

Thank you,
Gleb
