### ISSUE TITLE
Audit sets/dicts of `py.path.local`s

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#7357]
`py.path.local` has a footgun flaw: `__eq__` on Windows is case-insensitive, but `__hash__` returns the hash of the `strpath` directly, meaning `a == b` does not imply `hash(a) == hash(b)`. So things like this are possible:

```py
import sys, py
assert sys.platform == "win32"

a = py.path.local("/some/path")
b = py.path.local("/some/PATH")
assert a == b  # Passes
assert a in {b}  # Fails
assert a in {b: 'b'}  # Fails
```

This probably causes some subtle bugs in pytest, which uses several dicts & sets of `py.path.local`s. Since `py` is frozen, it's not possible to fix there.

I haven't checked it yet, but wanted to make a note for later.

**Comment by nicoddemus** [comment]
Oh my!

`py` is not really frozen, it is in a "maintenance mode but only for critical bugs", and this qualifies as a critical bug IMHO.

Just to leave this option here in case it was not clear it was an option.

**Comment by bluetech** [comment]
OK, fixing at the source is definitely best. Sent a PR to py: https://github.com/pytest-dev/py/pull/243

If it gets merged and released, we should probably bump the `py` requirement in pytest to resolve this issue.

**Comment by nicoddemus** [comment]
`1.8.2` was just released with your fix, thanks!

**Comment by bluetech** [comment]
Thanks for doing the release @nicoddemus. I sent #7372 to bump the requirement.
