### ISSUE TITLE
Adding a pytest plugin is causing user pkg_resources calls to raise NotImplementedError

### ISSUE THREAD

**Issue by omry** [pytest-dev/pytest#7375]
It appears that registering an empty pytest plugin with my is somehow interacting with pkg_resources.

This breaks the package config discovery in Hydra (using pkg_resources), failing most of the tests.

- [x] output of `pip list` from the virtual environment you are using
see requirements.txt in minimal example.

- [x] pytest and operating system versions
Ubuntu 18.04
pytest 5.4.3

- [x] minimal example if possible
attached
[pytest_plugin.tar.gz](https://github.com/pytest-dev/pytest/files/4783274/pytest_plugin.tar.gz)

**Comment by omry** [comment]
1. extract minimal example.
2. observe that pytest passes.
3. install project: `pip install -e .`
4. observe thet pytest fails:
http://paste.ubuntu.com/p/3fyKNkwdpJ/

**Comment by asottile** [comment]
Use importlib.resources instead when working with a pytest plugin, or register your importer manually

**Comment by omry** [comment]
I have a PR attempting to use importlib_resources but it's blocked due to missing functionality in importlib_resources for now.

Can you give more details about your suggestion for registering your importer manually?

an example in the minimal repro would be great.

**Comment by asottile** [comment]
you'd utilize these apis, I'm sorry but I don't have free time right now to write the code for you https://setuptools.readthedocs.io/en/latest/pkg_resources.html#supporting-custom-importers

**Comment by omry** [comment]
I think pytest plugin registration should not be breaking applications using pkg_resource.

If the recommended workaround is to use specific APIs in pkg_resource I think it's reasonable for pytest to provide an example.

I can definitely take a look myself, but you seem to suggest it for a reason. can you at least say what pytest is doing that is breaking pkg_resource?

**Comment by asottile** [comment]
I know this is minor but it's `pkg_resources` not `pkg_resource`

`pkg_resources` (for whatever reason) does not support new-style importers (PEP 451+) through the resource apis -- this is fine though as those apis are deprecated for `importlib.resources`

you can manually re-enable the pkg_resources apis using the functions above -- they're explicitly avoided in pytest because it adds 300-400ms to startup for ~nothing

**Comment by omry** [comment]
> I know this is minor but it's pkg_resources not pkg_resource

Thanks.
autocompletion related brain fart, corrected.

> pkg_resources (for whatever reason) does not support new-style importers (PEP 451+) through the resource apis -- this is fine though as those apis are deprecated for importlib.resources

Happy to switch to it if and when it supports importing resources from the global module.
see [this](https://gitlab.com/python-devs/importlib_resources/-/issues/103).

> you can manually re-enable the pkg_resources apis using the functions above -- they're explicitly avoided in pytest because it adds 300-400ms to startup for ~nothing

If pytest is being slowed down by pkg_resources it should use importlib-resources instead.
I don't understand why it should fiddle with pkg_resources loaders.
I think I am still missing some context here.

You also say I can "re-enable the pkg_resources apis". is pytest disabling it for apps?
looking at the APIs, it sounds like they are about registering new types of loaders which is certainly not what I want to do.

**Comment by asottile** [comment]
oh I see what you're missing.  the way pytest assertions work is there is an import hook which rewrites `assert` statements.  this import hook is implemented as a PEP 451 loader which `pkg_resources`'s resource apis do not understand

pytest is not disabling it, it is just not registering the loaders directly to the pkg_resources apis (because doing so would incur the overhead of pkg_resources).  you can however (if you need to use pkg_resources-type-resources inside a pytest loader) manually re-enable those using the apis listed above

or you can turn off assertion rewriting with `--assert=plain`

~generally this hasn't been a problem, either packages adapted for PEP 451 style loaders (for example [flask](https://github.com/pallets/flask/commit/a5ecdfa7a57bf6bcba7391fc6d356e3f7de33e57)), or stopped storing package resources in non-package directories (tests)

**Comment by omry** [comment]
Ah, it's starting to make more sense. Thanks for explaining.

Hydra is allowing the user to compose a configuration from config files anywhere.
I created an example test to show Hydra users how to compose configs inside tests.

Here is the [example test](https://github.com/facebookresearch/hydra/blob/master/examples/advanced/hydra_app_example/tests/test_hydra_app.py
). It works well until I try to enable a pytest plugin.

Hydra itself is also using this mechanism to load its own configs. This is actually where I see the breakage when I try to enable a pytest plugin.

The reason I want to provide a plugin is to have a standard fixture users can use to initialize Hydra (instead asking them copy-pasting my try: finally blocks or write their own fixture)

Any insights as to why this works until I register a plugin? (even if that plugin is empty)?

Makes me wonder if a workaround might be to separate the plugin to a different pip package?

**Comment by asottile** [comment]
plugins get all of their source assertion rewritten when under test, a separate package would probably work, yes

**Comment by omry** [comment]
A preliminary test in the minimal repro in the issue shows that it does work.
will spend more confirming it (and put something useful in my empty plugin to be 100% sure it's working).

In the mean time, a question:

> plugins get all of their source assertion rewritten when under test

Is this intentional that it's not limited the the plugin module mentioned in the entry point?
`entry_points={"pytest11": ["name_of_plugin = my_pytest_plugin.pytest_plugin"]}`

`my_pytest_plugin.pytest_plugin` above.

**Comment by asottile** [comment]
yeah it's always been that way -- iirc this is because an importer/loader applies to the top level package and doesn't allow for differentiation in sub-packages

**Comment by omry** [comment]
Ok.
I suspect that at this point changing this behavior is out of the question even if it is technically possible.

I will complete my testing with a separate plugin later, and with some luck importlib_resources will support resources in the global module which will allow me to completely sidestep the whole problem.

**Comment by omry** [comment]
Okay, switching the plugin to a different package solved my issue.

Thanks for your help.
