### ISSUE TITLE
Enable auto-build documentation during PRs

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#7376]
ReadTheDocs has just launched the ability of building docs for PRs:

https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html

I've enabled it for us to see how it works, using this issue mostly to communicate/get feedback (it is only a matter of ticking a checkbox, so we can easily undo it).

**Comment by gnikonorov** [comment]
This is awesome, thanks @nicoddemus !

**Comment by bluetech** [comment]
This sounds very useful for docs PR, like @SalmonMode's PR #7381.

The link mentions a PR status, but I don't see it in the PR above. How does one reach the docs built for a specific PR?

**Comment by nicoddemus** [comment]
Yeah I didn't see any status either. I guess one possible reason is that it will only push status for PRs based on branches in the main repository, instead of forks? 🤔

**Comment by SalmonMode** [comment]
Hmm that would be an odd restriction, but I could see how it might be limited in that way. Are there any branches in the main repo with PRs where this is working?

**Comment by SalmonMode** [comment]
Looks like it should work. They said we might need to check if it has the proper permissions and webhooks https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html#troubleshooting

**Comment by nicoddemus** [comment]
Thanks @SalmonMode.

I can see that the webhook is set properly in `pytest-dev/pytest` (see at the bottom):

![image](https://user-images.githubusercontent.com/1085180/85043253-87b63c80-b162-11ea-913f-3688ab1f2f29.png)

I've also re-synced it in readthedocs to make sure.

However I don't see the ReadTheDocs application as a "GitHub Apps" in the organization:

![image](https://user-images.githubusercontent.com/1085180/85043440-bb916200-b162-11ea-9fb9-065a9404fb2c.png)

But I see a "Read the Docs Community" in "Third-party access":

![image](https://user-images.githubusercontent.com/1085180/85043671-feebd080-b162-11ea-99c9-d85ae30d302d.png)


Also I can't find the "Read the Docs" application in the [Market place](https://github.com/marketplace) to somehow add it to the organization.

(This third-party/github app business is very confusing)

If somebody has any other pointers I would appreciate. 👍

**Comment by bluetech** [comment]
It's working now! Example: https://pytest--7388.org.readthedocs.build/en/7388/

**Comment by nicoddemus** [comment]
Cool! Just FTR, did anybody change anything else than what I mentioned here?

Closing then. 👍
