### ISSUE TITLE
How to test a custom collection filter?

### ISSUE THREAD

**Issue by joshuatbadger** [pytest-dev/pytest#7377]
I was able to build something for work (referenced in #6862 ), and then COVID-19 caused a layoff. I liked the system I was able to come up with, so I'm in the process of rebuilding (from scratch) that system to hopefully submit as a plugin one day.

However, I cannot figure out how to test whether the filters are working correctly short of manual testing.

In the current iteration, I filter the test items using `pytest_collection_modifyitems`. When I try to build out some automated tests to validate that I'm correctly filtering the tests, however, it appears that `testdir.inline_genitems` and `testdir.genitems` both return all items gathered before `pytest_collection_modifyitems` is run.

I have a feeling I could approximate this by putting print/log statements unique to each test and then use caplog to validate that only those tests ran, but that somehow doesn't feel like the appropriate way to do this. Is there a better way to test `pytest_collection_modifyitems`? Or should I try to figure out writing a custom `Collector` subclass?

**Comment by Zac-HD** [comment]
[`testdir.getitems`](https://docs.pytest.org/en/stable/reference.html#_pytest.pytester.Testdir.getitems), maybe?

Otherwise, `--collect-only` is probably still nicer than custom prints or logging :confused:

**Comment by RonnyPfannschmidt** [comment]
you might want to use pytests pytester plugin (needs to be manually enabled) which supplements a testdir fixture that enables creating pytest folders and to run tests against them, see the pytest testsuite for examples)

**Comment by joshuatbadger** [comment]
So I've done just that, have enabled `pytester`, and used the `testdir` fixture, trying both `inline_genitems` and just `genitems`. Neither of them will run the check on the generated test items after my custom `pytest_collection_modifyitems` hook, only before.

Perhaps I should try a different approach and try to write a custom `SuiteCollector` that subclasses off of `FSCollector`? But if I did that how would I trigger pytest to use `SuiteCollector` instead?

I love pytest, but man some of this is hard to wrap my head around... :P

**Comment by SalmonMode** [comment]
> I love pytest, but man some of this is hard to wrap my head around

I personally find it easier to structure my tests so that I'm never defining tests I don't intend to run, and use the `pytest_collection_modifyitems` just to add marks. Then I can use file structure, marks, and/or test name matching (-k) to filter for the tests I want to run (or filter the tests out that I don't want to run).

This requires the structuring of my tests and fixtures to be a bit more spread out, but it reduces complexity significantly, and reduces headaches.

**Comment by iwanb** [comment]
I usually test plugins by asserting the plugin behaviour within dummy sample tests.

E.g.:
```
def test_should_run():
    assert True

def test_should_not_run():
    # If it would mistakenly run, it will fail
    assert False
```

Then you do `testdir.assertOutcomes(passed=1, failed=0)`

You can also add a conftest.py with a `pytest_collection_modifyitems` hook wrapper to test your conditions after the hook has executed.

It'd be probably cleaner to have utilities to create dummy test sessions/items/etc and run the hooks on them as kind of unit tests, but AFAIK it's not easy to do.

**Comment by joshuatbadger** [comment]
This is a fantastic idea. I will try this out. Thank you!

**Comment by symonk** [comment]
@joshuatbadger try using pytester and the testdir fixture to invoke by test and assert against the stdout when running with --collect-only for example

**Comment by Zac-HD** [comment]
Closing this as the question seems to be answered or at least inactive.  I hope we helped!
