### ISSUE TITLE
`PyCollector.istestfunction` breaks on objects with custom `__bool__` method

### ISSUE THREAD

**Issue by ymost** [pytest-dev/pytest#7378]
Code from [this line](https://github.com/pytest-dev/pytest/blob/db00612b84b5f0313a42ccc59b14d1302a55d0c3/src/_pytest/python.py#L365) in `PyCollector.istestfunction`:

    return (
        safe_getattr(obj, "__call__", False)
        and fixtures.getfixturemarker(obj) is None
    )

Relevant use case: the object returned by `obj.__call__` has a custom `__bool__` method which either:

1. Returns `False` - causing `False` to erroneously be returned by `istestfunction`.
2. Raises an exception - causing an unwarranted exception to be raised from `istestfunction`.

Suggested fix:

    return (
        safe_getattr(obj, "__call__", None) is not None
        and fixtures.getfixturemarker(obj) is None
    )

**Comment by RonnyPfannschmidt** [comment]
i beleive we shoud check for `__call__` on the type of the object

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by RonnyPfannschmidt** [comment]
i think we can actually turn this into a check for callable again now that its back
