### ISSUE TITLE
Package scope fixture: experimental status?

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#7389]
Just noticed that `package` scope is still marked as experimental:

https://docs.pytest.org/en/stable/fixture.html#package-scope-experimental

Should we remove that warning and mark it as official for 6.0?

**Comment by symonk** [comment]
should we evaluate the open issue(s) around package scope (i noted 1-2+) and perhaps try resolve them pre-6.0 to move this from 'experimental' ?

**Comment by nicoddemus** [comment]
Good idea, can you link them here please? 😁

**Comment by symonk** [comment]
Heres what I could find:

https://github.com/pytest-dev/pytest/issues/7256
https://github.com/pytest-dev/pytest/issues/4684

**Comment by RonnyPfannschmidt** [comment]
im under the impression that it will take until 7 or 8 to resolve the underlying collection tree details to get this behave consistent

**Comment by nicoddemus** [comment]
I agree. But should we remove the experimental status or not? The question we need to answer is if we understand that removing Package scope at this point is a possibility in the future; if it is, we should keep the experimental status, otherwise we might as well remove it even if it still contains issues.

**Comment by RonnyPfannschmidt** [comment]
Good perspective, i agree with that, it stays

**Comment by nicoddemus** [comment]
> it stays

By "it" you mean the experimental status or the feature? 😁 (Sorry I want to be sure what you mean and don't leave open for interpretation).

Also would like to hear from @asottile and @bluetech. 👍

**Comment by asottile** [comment]
I think package scope is helpful and that we should continue to support it going forward.  it will probably make refactoring the collection tree a little bit more difficult (so maybe we should mark some of the behaviours provisional? maybe not and just run with it?) but I think the idea of a package scoped fixture seems good to me 👍

**Comment by RonnyPfannschmidt** [comment]
The feature stays

**Comment by s0undt3ch** [comment]
Thank You for keeping it.
Salt's test suite depends heavily on subprocesses which run some daemons.
Historically we started the daemons at the start of the test suite and stopped them at the end.
These daemons are not required for unit tests not functional tests, so the package scope, when properly working, solves this issue for us.
