### ISSUE TITLE
Exclude specific plugins from xunit2 output

### ISSUE THREAD

**Issue by wkoot** [pytest-dev/pytest#7413]
- [x] a detailed description of the bug or suggestion
It would be nice if specific plugins' output could be omitted from xunit2 report, for instance via include/exclude params in pytest.ini.
In this particular case I'm filtering out `testcase`s with `name="PYTEST"`, because it's reporting source files as test (and mostly skips when unchanged).

- [x] output of `pip list` from the virtual environment you are using
```
Django==2.2.12
pylint==2.5.0
pytest==5.4.1
pytest-cov==2.8.1
pytest-django==3.9.0
pytest-pylint==0.16.1
```

- [x] pytest and operating system versions
For pytest, see versions above from pip
Windows 10 with Python 3.6.7 & 3.7.4
Ubuntu 18.04 (on WSL) with Python 3.6.7 & 3.7.7

- [x] minimal example if possible
Useless testcase output is providing incompatible class name and reports source files as testcases
```
    <testcase classname="manage../c/path/to/repo/source/manage.py" name="PYLINT" time="0.001">
      <skipped message="file(s) previously passed pylint checks" type="pytest.skip">
        ~/.virtualenvs/app367/lib/python3.6/site-packages/pytest_pylint/plugin.py:319: file(s) previously passed pylint checks
      </skipped>
    </testcase>
    <testcase classname="app.admin./c/path/to/repo/source/app/admin.py" name="PYLINT" time="0.007"></testcase>
```

**Comment by nicoddemus** [comment]
Hi @wkoot,

`pytest-flakes` creates actual test items to run lint checks, and from pytest's perspective, those are test items which should be included in the report, as any other item. I don't think pytest can do anything about that here, because many plugins create test items which users want in the junitxml report (just as an example, `pytest-cpp` does that, and I'm sure many others).

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i believe the intent is to skip the pylint plugin from the junit report

**Comment by wkoot** [comment]
Thanks for the replies, indeed in my case it is particularly meant for pylint because it's reporting linted source files as test cases.

An option combo like `--ignore` and `--ignore-glob` for the testcase/class name could do the trick in this case, because all pylint cases are named "PYLINT".
For instance something as `--ignore-testname=PYLINT` or similarly via pytest.ini would offer the option.

NB: I'm currently filtering the cases with `xmlstarlet`:
```
xmlstarlet ed --inline --delete \"testsuites/testsuite/testcase[@name='PYLINT']\" xunit-result.xml
```
Of course, this does not change the `testsuite` reported count for tests and skipped tests.
Luckily, the Jenkins JUnit plugin seems to ignore that and simply count the testcases :^)

**Comment by nicoddemus** [comment]
Sorry if I was not clear, I understood the use case, I was wondering what the option would look like.

> An option combo like --ignore and --ignore-glob for the testcase/class name could do the trick in this case, because all pylint cases are named "PYLINT".

For example something like this?

```ini
[pytest]
junit_ignore_casename_glob = PYLINT
```

**Comment by RonnyPfannschmidt** [comment]
Personally im - 1 on the feature, i consider unit testing and lining necessarily distinct

For a ci pipeline i would personally just run the linter in a separate job

**Comment by wkoot** [comment]
@RonnyPfannschmidt I'm inclined to agree with you, but that would suggest not having pytest-pylint at all?

The settings for unittest / coverage (pytest-cov) / linter (pytest-pylint) all go in pytest.ini.
I can't run pytest for different use cases (tests/coverage, linting) from a single pytest.ini file (they inherit addopts anyway).
In my pipeline I import the pytest output in Sonar with SonarPython, which has deprecated running pylint itself.

**Comment by Zac-HD** [comment]
Closing this as stale, and because running pylint separately (rather than `pytest-pylint`) seems like a good solution to me too.
