### ISSUE TITLE
proxy pass using hostname 

### ISSUE THREAD

**Issue by teamdts** [pytest-dev/pytest#7420]
pytest in i am passing argument like
`pipenv run pytest . -m 'basic' --browser=chrome --proxy=172.19.0.2:8090
`
so 
`
--proxy=IP_ADDRESS:PORT
`
is only allowing to use ip address.

i using docker so in proxy we want to pass hostname instead of ip.
because we don't know ip address .
so my expectation is it will accept hostname also. 
`--proxy=HOSTNAME:PORT
`

Thanks

**Comment by RonnyPfannschmidt** [comment]
Pytest core is completely unaware of that argument, please ask in the belonging plugins

**Comment by symonk** [comment]
Hi @teamdts i assume its pytest-selenium; please raise the issue over here:  https://github.com/pytest-dev/pytest-selenium/issues

**Comment by teamdts** [comment]
ok thanks @RonnyPfannschmidt @symonk
