### ISSUE TITLE
Clarify (more) that marks are only effective in tests

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#7422]
Marks are only effective for tests, but there was confusion in https://github.com/pytest-dev/pytest/issues/6908#issuecomment-638365232 about being possible to add marks to hooks. 

We have this note in the [introduction for marks](https://docs.pytest.org/en/stable/mark.html):

![image](https://user-images.githubusercontent.com/1085180/85888782-a2229280-b7c0-11ea-9c8a-dd0f056b4dda.png)

Any hints on how to update the docs for that to be clearer?

_Originally posted by @nicoddemus in https://github.com/pytest-dev/pytest/issues/6908#issuecomment-650326532_

**Comment by KGB33** [comment]
It seems like the problem is that the `usefixture` mark doesn't load fixtures during hooks. 

What if we were to change the Warning on [pytest.mark.usefixtures](https://docs.pytest.org/en/latest/reference.html?highlight=usefixtures#id29) 

from:
 > This mark has no effect when applied to a fixture function.

to something like
> This mark only works when applied directly to a test function or class.

**Comment by nicoddemus** [comment]
> usefixture mark doesn't load fixtures during hooks

Indeed, a mark only attaches a metadata to a test function; the mark is then often queried by hooks/fixtures/tests to do something. `usefixtures` is queried only during test setup to see which other fixtures should be applied to that test item, so it might work on some hooks (notably it works on `pytest_collect_modifyitems` for example) but not on others.

Your rephrasing for `pytest.mark.usefixtures` is good, but we might consider adding a more extensive explanation like the one above. What do you think?

**Comment by KGB33** [comment]
What about adding the following between, "Mark a test function as using the given fixture names." and the warning. 

> When using `usefixtures` in hooks, it can only load fixtures when applied to a **test** before test setup. 
> To modify fixtures after test setup, append the fixture name to `item.fixturenames`.
