### ISSUE TITLE
move  _issue_warning_captured from _pytest.warning

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest#7426]
We should move `_issue_warning_captured` from `_pytest.warning` to `_pytest.config` since right now every caller lazily imports it due to cycles. Since every caller has access to `config`, it would make sense to move the function there.

This builds off of https://github.com/pytest-dev/pytest/pull/7396#issuecomment-650561884

Also, we should evaluate if we are happy with the stack levels currently in use. Please see https://github.com/pytest-dev/pytest/pull/7396#issuecomment-650710719 for a detailed breakdown of the stack levels. It may be possible improve what we show to users as part of this

**Comment by RonnyPfannschmidt** [comment]
I do wonder if a focus on generally splitting plugins into exposed utilities and implementation parts would help

**Comment by gnikonorov** [comment]
That sounds like it would be beneficial in its own right
How large of a change would that be?

**Comment by RonnyPfannschmidt** [comment]
I never did a survey to figure, but I
It sound more like a milestone /project than a single change

**Comment by gnikonorov** [comment]
I'm +1 on the idea, the distinction would definitely be beneficial IMO

Do we want to make it a milestone? Not sure how the process works, do we need more buy-in

**Comment by RonnyPfannschmidt** [comment]
At first no idea size and scope are still unknown

**Comment by nicoddemus** [comment]
Fixed by #7700
