### ISSUE TITLE
 RFE: allow to selectively disable loggers from command-line

### ISSUE THREAD

**Issue by ankostis** [pytest-dev/pytest#7431]
A common debugging strategy is to study the logs.
But sometimes the program issues excessive logging messages, 
necessitating the selective disabling of babbler loggers.

This SO captures the crux & solution of this Request For Enhancement:
https://stackoverflow.com/a/57002853/548792

Although the proposed SO solution of a new ``--disable-log`` option works perfectly fine, 
it is annoying to have to patch every new project,
plus, it does not support auto-completion e.g. on bash.

- Would it make sense to include such capability into core code?

In any case, I'm suggesting the new option to be called ``--logger-disabled``,
to fit with the existing option names starting with  ``--log-...``.

**Comment by RonnyPfannschmidt** [comment]
i believe this could play into #7417

**Comment by symonk** [comment]
Back after some time out :)

What do we think about a --suppress-logger= appendable parsearg option here, which takes a list of logger names (convert to set to avoid duplicates) and doing the following:

 - add NullHandler() to the logger to avoid warnings from last resort writing to stderr
 - mark propagate = False to avoid events being passed to ancestor handlers

Let me know, thanks :) its where I'm thinking to 'start' with this

**Comment by ankostis** [comment]
As i suggested in the opening-post, i would choose an option name starting from `--log-...`, to fit with existing options related to the logging subsystem (e.g. in the `--help` message).

**Comment by ankostis** [comment]
Additionally, i would allow a separate option for each logger suppressed, to specify as value whether it should propagate=false/true.

**Comment by dluiscosta** [comment]
@symonk, are you still working on this and on #7417?

I've been looking through the issues labeled with `status: easy` in hopes of making a first contribution. This issue stood out to me since I've had problems with excessive logs during tests myself. Also, a possible solution doesn't seem to involve any subjects I'm too unfamiliar with.

**Comment by itxasos23** [comment]
Hey everone!
I'd like to tackle this as part of Hacktoberfest.
I see @symonk already had an ongoing PR (https://github.com/pytest-dev/pytest/pull/7873) that they closed.

I'm going to take it from there if it's ok.

**Comment by ankostis** [comment]
Please, be my guest.

**Comment by lovetheguitar** [comment]
@nicoddemus 7.2 is released now, but somehow this change is not part of it, contrary to your [comment in #7873](https://github.com/pytest-dev/pytest/pull/10371#discussion_r1003822838)?

Please let me know when this is planned to be released, or what is missing so @itxasos23 or myself could finish this. 😸 
Thanks!

**Comment by chanhosuh** [comment]
it's confusing as `--log-disable` is mentioned in the [docs](https://github.com/pytest-dev/pytest/blob/main/doc/en/how-to/logging.rst) but isn't actually available.

**Comment by lovetheguitar** [comment]
> it's confusing as `--log-disable` is mentioned in the [docs](https://github.com/pytest-dev/pytest/blob/main/doc/en/how-to/logging.rst) but isn't actually available.

@chanhosuh It was finally included in the [7.3.0](https://github.com/pytest-dev/pytest/releases/tag/7.3.0) release. 🥳
