### ISSUE TITLE
Slightly confusing text in getting-started.rst

### ISSUE THREAD

**Issue by rswarbrick** [pytest-dev/pytest#7441]
The Getting Started document gives instructions for how to assert that a certain exception is raised (line 88). After that example, there's the following

```rst
Execute the test function with “quiet” reporting mode:

.. code-block:: pytest

    $ pytest -q test_sysexit.py
    .                                                                    [100%]
    1 passed in 0.12s
```

Delving with `git annotate`, I think that this used to say something like "Hey, let's try running in quiet mode this time". The text that's in the document now doesn't look quite like that. In fact, I thought that it was supposed to be a header (and cloned the repo to make a PR "fixing" the formatting).

I think that this example should probably be split into a separate item ("Run less verbosely" or something). Alternatively, the text could be expanded to make it clearer that we're showing off an unrelated feature, but I think this document is probably better if it's possible to "dip in" by section title (rather than having to read it end-to-end to find all the features it describes).

**Comment by bluetech** [comment]
I suspect `-q` is used here just to keep the output brief. So what do you think about the following?

```
Execute the test function:

    $ pytest -q test_sysexit.py
    .                                                                    [100%]
    1 passed in 0.12s

The ``-q/--quiet`` flag keeps the output brief in this example.
```

**Comment by rswarbrick** [comment]
Ah, good point. Sounds good to me.

**Comment by mdebi** [comment]
Hi. This is my first time attempting a PR in this project. Please review and let me know if any update is needed. Thank you.
