### ISSUE TITLE
How to execute an action after all parameterized tests has finished?

### ISSUE THREAD

**Issue by mciepluc** [pytest-dev/pytest#7445]
Hi,

Is it possible to run a function specific for one type of test, after all parameterized runs of this test have ended?
It can be done using pytest_sessionfinish(), but that means that I need to put all the code specific for particular tests in this function, which is not nice. Is there another way?

**Comment by RonnyPfannschmidt** [comment]
The easiest way would be a session scop fixture that is linked to these tests only, the issue would be that it runs at the test session end instead of the last test belonging to the set

**Comment by mciepluc** [comment]
@RonnyPfannschmidt 

Thanks. I have missed the part that the code after ```yield``` in the session-scoped fixture will be executed after all tests have finished. Now it is clear.
