### ISSUE TITLE
Autocomplete object code methods from object in fixture.

### ISSUE THREAD

**Issue by akozyreva** [pytest-dev/pytest#7446]
Hi everyone!
I have a question, according work of fixture.
For example, I have the following fixture in conftest.py:
```
from lib import Car
@pytest.fixture(scope="module")
def car():
    car = Car()
    yield car
    car.stop()

```
and the test (test_car.py)
```
def test_car(car):
     car.dirve();
     car.stop();
     car.drive();
....
```
The point is, that car object has bunch of methods and I want to have autocomplete of these methods (for example, when I type `car.d ` in editorI want to have a hint from IDE, `drive()`, but IDE refers to fixture from conftest.py). Is there any way to fix it?

**Comment by nicoddemus** [comment]
FWIW PyCharm automatically knows about pytest fixtures so that works automatically, but you can use type-hints in your test to help your particular editor:

```python
def test_car(car: Car):
     car.drive();
     car.stop();
     car.drive();
```

**Comment by akozyreva** [comment]
@nicoddemus thanks a lot for your answer! Works for me perfect now! Was this feature somewhere documented?

**Comment by asottile** [comment]
@akozyreva this isn't really a feature of pytest, but of python itself! [PEP 3107](https://www.python.org/dev/peps/pep-3107/),  [PEP 484](https://www.python.org/dev/peps/pep-0484/)
