### ISSUE TITLE
Cannot initiate abstract base test class

### ISSUE THREAD

**Issue by urishalit** [pytest-dev/pytest#7450]
Hi,
I am using pytest version 4.6.9. With pypy 2.7 on Mac. But this issue replicates on our unix based Jenkins machine as well. On my machine it happens both in PyCharm and in the terminal.

The problem I am having is when creating an abstract test class it tries to initiate the base class ignoring it being abstract. As follows:

```
class Base(TestCase):
    __meta__ = ABCMeta
    def test_something(self):
         x = self.get_x()
         ...
         self.assert....

    @abstractmethod
     def get_x(self):
         pass

class TestX(Base):
       def get_x(self):
             return ...
```

In the example above pytest  tries to run tests both for `Base` & `TestX`- Base fails as it gets an error: `Cannot initiate abstract class...` - From debugging it seems the collector collects all functions that start with `test_` and tries to initiate them. When creating an abstract class with only `setUp` for instance it doesn't try to initiate it.

There is a workaround for this that I found, adding to `Base`: `__test__ = False` and to each deriving class `__test__ = True` - but this is quite ugly.

If interested: The usage for this is creating a base class for some interface, and then creating a test class for each implementation of said interface.

**Comment by nicoddemus** [comment]
Hi @urishalit,

Indeed pytest doesn't try to verify if a class is abstract or not.

What happens if you execute this with plain unittest?

Also, which Python version and OS are you using locally? I can't reproduce this on my computer using 4.6.9 and Python 3.7.

**Comment by urishalit** [comment]
Locally I am using Mac OS 10.14.6 and Python:

```
Python 2.7.13 (ab0b9caf307db6592905a80b8faffd69b39005b8, Sep 30 2018, 13:54:57)
[PyPy 6.0.0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

This reproduces in unitest and nosetests as well....

**Comment by nicoddemus** [comment]
If we reproduce the `unittest` behavior, then I don't think this is a bug. Weird that I cannot reproduce it on Windows though... 🤔

**Comment by Zac-HD** [comment]
Yeah, if this is also the behaviour of `unittest` I don't consider it a bug (or at least not a *pytest* bug...)
