### ISSUE TITLE
tmp_path fixture fails when run as root

### ISSUE THREAD

**Issue by amitbeka** [pytest-dev/pytest#7451]
Hi there,

I'm trying to use `tmp_path` fixture under a docker container in our own Gitlab deployment, so I don't know all the details of the system.

When trying to create the `tmp_path` fixture, it somehow picks up the name `/root` as the current user, and tries to create "/tmp/pytest-of-/root" and fails.

A minimum example is:

```
def test_path(tmp_path):
    assert tmp_path

```

This is the full output:

```
$ export PYTHON_PROJECTS=smurf
$ pytest $PYTHON_PROJECTS
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
rootdir: /builds/elevate/smurf
collected 1 item
smurf/tests/test_paths.py E                                              [100%]
==================================== ERRORS ====================================
_________________________ ERROR at setup of test_path __________________________
self = PosixPath('/tmp/pytest-of-/root'), mode = 511, parents = False
exist_ok = True
    def mkdir(self, mode=0o777, parents=False, exist_ok=False):
        """
        Create a new directory at this given path.
        """
        if self._closed:
            self._raise_closed()
        try:
>           self._accessor.mkdir(self, mode)
E           FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-/root'
/usr/local/lib/python3.8/pathlib.py:1279: FileNotFoundError
=========================== short test summary info ============================
ERROR smurf/tests/test_paths.py::test_path - FileNotFoundError: [Errno 2] No ...
=============================== 1 error in 0.33s ===============================
```

I don't know why "/root" is the username here, but I think it would be better to make `tmp_path` more resilient to weird cases like this.

Thanks,
Amit

**Comment by bluetech** [comment]
pytest uses `getpass.getuser()` to get the user name. What is the output of this command on the container?

```sh
python -c 'import getpass; print(getpass.getuser())'
```

The code of `getpass.getuser()` is

```py
    for name in ('LOGNAME', 'USER', 'LNAME', 'USERNAME'):
        user = os.environ.get(name)
        if user:
            return user

    # If this fails, the exception will "explain" why
    import pwd
    return pwd.getpwuid(os.getuid())[0]
```

So check these environment variables and `pwd.getpwuid(os.getuid())[0]` as well if you can.

**Comment by amitbeka** [comment]
Thanks for the quick reply!


My output of `getuser()` is actually "/root", which is also what is set as my USER env var (I don't have LOGNAME).



I can set the USER var for the process and it will fix it, but I wonder maybe it's worth asserting/fixing in pytest too.









---- On Mon, 06 Jul 2020 10:21:56 +0300 Ran Benita <notifications@github.com> wrote ----





pytest uses getpass.getuser() to get the user name. What is the output of this command on the container?

python -c 'import getpass; print(getpass.getuser())'


The code of getpass.getuser() is

    for name in ('LOGNAME', 'USER', 'LNAME', 'USERNAME'):
        user = os.environ.get(name)
        if user:
            return user

    # If this fails, the exception will "explain" why
    import pwd
    return pwd.getpwuid(os.getuid())[0]


So check these environment variables and pwd.getpwuid(os.getuid())[0] as well if you can.

**Comment by bluetech** [comment]
I suggest checking why the container sets `USER` to `/root` instead of the expected `root`, as that may cause other issues for you in the future.

We can maybe escape the username for a file name, but it's not so straightforward due to windows/unix differences.

Overall unless it happens more often, I think pytest shouldn't try to workaround a system misconfiguration.

**Comment by amitbeka** [comment]
Found the copy-paste bug somewhere. The user is indeed root (as evident from running `id`) but the env var is wrong.
Closing, thanks!
