### ISSUE TITLE
Overriding @parameterize with no action at collect phase

### ISSUE THREAD

**Issue by mciepluc** [pytest-dev/pytest#7456]
Hi,

I am overriding the ```@parameterize``` decorator, so I can add some pre-parameterization functionality:

```Python

def my_parameterize(pre_parameterize):
    def _decorator(test_function):     
        pre_parameterize()
        ...
        return pytest.mark.parametrize('foo', foo)(test_function)
    return _decorator

@my_parameterize(pre_parameterize_)
def test(foo):
    ...

```

It works OK, but even if I run only one single test, ```pre_parameterize``` is called for all the tests (guess it is because it is called at the collect phase). Is it possible to avoid it?

**Comment by RonnyPfannschmidt** [comment]
without more context, all i can say that this is a python question not a pytest question

**Comment by asottile** [comment]
@mciepluc to discover tests, the module must be imported -- the decorator is run at import time so I believe it is unavoidable

**Comment by mciepluc** [comment]
Thanks, that is what I expected. The decorator that is not calling ```parametrize``` can be done quite easily, by adding one more function layer in the example that I provided, but in that case simply no test will be discovered as it is not called again anymore...
