### ISSUE TITLE
How can I activate log_cli dynamically?

### ISSUE THREAD

**Issue by chbndrhnns** [pytest-dev/pytest#7457]
I am trying to activate `log_cli` for a single test where I am interested in seeing the output during the run. However, it seems to me like it is not possible to set this option at runtime using the `request` fixture. 

Am I maybe missing something?
Is it possible?

**Comment by Zac-HD** [comment]
Hi @chbndrhnns - unfortunately nobody has answered here and I don't know, but maybe you could ask on StackOverflow?
