### ISSUE TITLE
--lf skips tests in classes since 5.4.x

### ISSUE THREAD

**Issue by fschulze** [pytest-dev/pytest#7461]
In devpi we have many tests in classes. When using --lf those tests are skipped. This happens in ``LFPluginCollWrapper.pytest_make_collect_report`` in the ``elif isinstance(collector, Module):`` branch. The ``filtered_result`` list comprehension removes the tests in classes. The nodeid from ``res.result`` is for example ``test_devpi_server/test_replica.py::TestChangelog`` and the nodeid in ``self.lfplugin.lastfailed`` is ``test_devpi_server/test_replica.py::TestChangelog::test_get_since[False]``. Because of the mismatch the test is filtered out.

I'm not sure how to fix this, but my guess is that either the tests for these nodes need to be generated first, before the filtering takes place, or these nodes need to be included in ``filtered_result`` for further processing.

This is with pytest 5.4.3. This seems to be a regression in 5.4.x, pytest 5.3.5 works correctly.

**Comment by blueyed** [comment]
Please try master (d530d7012).

**Comment by fschulze** [comment]
That seems to fix it. I had something weird on first try, but couldn't reproduce. Might have been caused by old cache data.

So I guess this ticket can be closed with the next release.

**Comment by Zac-HD** [comment]
Glad to hear it's been fixed - the release should be soon(ish)!
