### ISSUE TITLE
Support NO_COLOR to disable colored output

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#7464]
`NO_COLOR` is a [community standard environement](https://no-color.org/ ) variable.

The general behavior is:
* A command line application emits colour when attached to a TTY, but no colour otherwise e.g. when attached to a pipe.
* `NO_COLOR` stops the application from emitting colour even when attached to a TTY
* My extension to the standard is to add `FORCE_COLOR` which forces the application to emit colour escape sequences even when not outputting to a TTY e.g. if we want to pipe into a log file with colour.

_Originally posted by @jhol in https://github.com/pytest-dev/pytest/issues/7443#issuecomment-655520755_

**Comment by nicoddemus** [comment]
`PY_COLOR` is also pytest specific, so I think if it happens that both are set, we should give preference over `PY_COLOR` over `NO_COLOR`.

**Comment by asottile** [comment]
fwiw, I think `NO_COLOR` is ~slightly flawed in that `NO_COLOR=` (empty environment variable) is treated as `NO_COLOR=1`.  this diverges from standard expected posix behaviour where an empty environment variable should be treated as absent

**Comment by hugovk** [comment]
Please see PR https://github.com/pytest-dev/pytest/pull/7466.

**Comment by hugovk** [comment]
I've created a PR to add pytest to https://no-color.org:

* https://github.com/jcs/no_color/pull/90
