### ISSUE TITLE
flag to cleanup generated tmp_path objects

### ISSUE THREAD

**Issue by kjaymiller** [pytest-dev/pytest#7465]
When using the tmp_path factory, the path remains until:

- The system is restarted
- The number of tmp_path objects is greater than the limit (currently 3) 
- a basepath is given (This will just overwrite the existing basepath, but will not provide any cleanup).

I propose a flag that cleans up `tmp_path` objects on completion of the test.

Usage would look like

`python -m pytest --autocleanup`

This would execute the following steps:

1. create a list of each `tmp_path` object created. 
2. execute code
3. iterate through the list deleting each tmp_path that was created (if it still exists)

**Comment by symonk** [comment]
IIRC tmp_path is a function scoped fixture, we could just tear them down if a new flag exists post-yielding.  Thoughts on something like that @nicoddemus - if we feel some merit in the idea of providing this, please assign it to me.

**Comment by RonnyPfannschmidt** [comment]
May we know the surrounding use case that makes the current auto cleanup misfit?

The folders intentionally stay around to do post mortem analysis

**Comment by kjaymiller** [comment]
Any type of image manipulation and processing could result in having to test the performance metrics of large amounts of hi-res files.

I do understand that this would be an edge case. Perhaps it should be handled by the end-user. 

I do wonder about those testing on smaller systems (raspberry pi and other devices of this type).

**Comment by asottile** [comment]
if full cleanup is needed you could always write your own wrapper fixture

```python
@pytest.fixture
def my_tmp_path(tmp_path):
    yield tmp_path
    # do your cleanup here
```

**Comment by nicoddemus** [comment]
@asottile's suggestion is on point, and in fact you might even overwrite the builtin fixture into your root `conftest.py`:

```python
@pytest.fixture
def tmp_path(tmp_path):
    yield tmp_path
    shutil.rmtree(tmp_path)
```

I'm closing because I believe this should be enough to fix OP's problem without changing anything in pytest.
