### ISSUE TITLE
--log-file should create subdirectories

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#7467]
If you provide a path with a subdirectory, which does not exist, it crashes with.
For example execute `pytest --log-file=subtest/test.log` produces something like this:
`INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/test/subtest/test.log' `

Maybe someone want to add something like this
```
dirname = os.path.dirname(os.path.abspath(logfile))
if not os.path.isdir(dirname):
    os.makedirs(dirname)
```
However, there is the possibility to say that someone is not supposed to pass a directory path there.

_Originally posted by @Hardy7cc in https://github.com/pytest-dev/pytest/pull/7350#issuecomment-655750453_

**Comment by nicoddemus** [comment]
I agree, `--junitxml` works the same way. 👍

**Comment by symonk** [comment]
Sorry ive been busy the past little while, I am doing some work in and around --log-file so I'm happy to build in support here also

**Comment by nicoddemus** [comment]
Thanks @symonk, and no need to be sorry, we all are busy at times!

Feel free to tackle this in #7350 if you like then. 👍

**Comment by Hardy7cc** [comment]
@nicoddemus Thanks for creating this new issue.
@symonk Thanks to take this up into your work around --log-file. I'm looking forward to see it ready, but take your time. I had this comment on my list for some days, so it does not hurry.
