### ISSUE TITLE
pytest 6: pylint shows not-callable error for builtin pytest marks

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#7473]
With the current versions of pylint (2.5.3) and the underlying astroid (2.4.2), running pylint against a simple pytest 6.0.0rc1 test:

```python3
import pytest

@pytest.mark.parametrize('a', [1, 2])
def test_a(a):
    pass
```

results in:

```
************* Module test_pylint
test_pylint.py:3:1: E1102: pytest.mark.parametrize is not callable (not-callable)
```

which isn't the case with pytest 5.4.3. I was able to bisect this to b3fb5a2d47743a09c551555da22da27ce9e73f41 (#7379, "Type annotate pytest.mark.* builtin marks" by @bluetech).

Note that to my knowledge, pylint doesn't know about type annotations and relies on its inference only. Thus, I suppose it either only sees `parametrize = None`, or it sees `_ParametrizeMarkDecorator.__call__` raising `NotImplementedError`. Not sure what, though. Maybe @PCManticore can explain what exactly is going on there?

Not sure how to best make this work in a way that pylint understands it (or, alternatively, fix it in pylint?) though.

**Comment by bluetech** [comment]
Thanks for testing @The-Compiler! I do think ideally this will be fixed in pylint but it's understandable that it gets confused by this, so I posted a fix in #7476.
