### ISSUE TITLE
Question: Ability to skip teardown execution and stop tests

### ISSUE THREAD

**Issue by serjb9** [pytest-dev/pytest#7493]
Hello, 

This a classic situation when we have a codebase and we want to approach or have the functionality that other product/plugin has but we can't with current functionality. 

So I was wondering, is there a functionality that can skip the current test teardown (and fixture teardown) and kinda stop execution of the whole session in PyTest or is there an any possible approach for this?

Comparing to the RobotFramework, it was useful to have **skip_teardown_on_exit** to stop the session, keep the environment is in the current state and collect results.

I know that PyTest guarantees execution of all teardown methods/fixtures, nonetheless some kinda workaround would be great in my situation without dramatically refactoring of current teardown methods in tests and modifying fixtures teardown.

Is it possible or better to not to do that?
Thanks.

**Comment by nicoddemus** [comment]
Hi @serjb9,

> So I was wondering, is there a functionality that can skip the current test teardown (and fixture teardown) and kinda stop execution of the whole session in PyTest or is there an any possible approach for this?

I'm afraid not at the moment; at first glance the `pytest_runtest_teardown` could be used for that, but it is not really a `firstresult` hook (btw @RonnyPfannschmidt shouldn't it be? as it stands one cannot override the current behavior, just add to it).

Can't think of a workaround either at the moment, but others might suggest something.
