### ISSUE TITLE
Question: How to use the "doctest+fixture" feature in a non-test file?

### ISSUE THREAD

**Issue by pandichef** [pytest-dev/pytest#7497]
I want to use the doctest+fixtures feature of pytest as documented [here](https://docs.pytest.org/en/stable/doctest.html#using-fixtures).

Unfortunately, `pytest --doctest-modules` doesn't seem to find fixtures in the file unless the file name is prefixed with `test_`.  I realize I can set `python_files = *.py` in `setup.cfg`, but this would presumably slow down the test runner in general.

Is there a better solution to this?

**Comment by nicoddemus** [comment]
Hi @pandichef,

Strange, it should work. Where are your functions defined? And your `*.py` files?

**Comment by pandichef** [comment]
@nicoddemus I was defining the fixture function in the same file as the doctest... but I think you answered elsewhere that it should be done in a conftest.py file.  `python_files = *.py` is always an option.

**Comment by nicoddemus** [comment]
Ahh indeed, because the normal python files are not scanned for fixtures.

**Comment by nicoddemus** [comment]
Opened #7501 improving the docs a bit, thanks!
