### ISSUE TITLE
Question. Is it possible to get 1 "unified" test result for parametrized test?

### ISSUE THREAD

**Issue by DenKos363** [pytest-dev/pytest#7498]
Hello guys.

I searched everywhere but didn't find an answer, so would ask you for help here.

I have manual "Test case" in Jira, and automated test in pytest.
With help of hooks, after running automated test, it will send to Jira test result status, like, "pass" or "fail", so the manual test case will get correct status.

Automated test is using parametrization with about 300-1600 test combinations, and "default" hook will change Jira status after EACH parameter, and in the end Jira test will get "last" parametrized result.

My idea is to "collect" each parameter "result" in fixture, and "summ" them, returning "unified" status, and AFTER that - use API for sending this status into Jira. I found this in https://github.com/pytest-dev/pytest/issues/230#issuecomment-402580536

Am I right or there is another way to solve this?

Thank you in advance and will be appreciated for any help and suggestions

**Comment by nicoddemus** [comment]
Hi @DenKos363,

The suggestion in https://github.com/pytest-dev/pytest/issues/230#issuecomment-402580536 is how I would implement it if I wanted to stay inside pytest.

But you might consider simpler to postprocess pytest results instead: run pytest normally with `--junitxml=tests.xml`, then process the generated `tests.xml` file to aggregate the tests results and post that to Jira.

**Comment by DenKos363** [comment]
Hi @nicoddemus I also thought about working with report AFTER running the tests, but wanted to be sure, that there is no easier way to do so right away after test finishing.
Thank you for suggestion!!!

**Comment by nicoddemus** [comment]
OK @DenKos363, glad it was helpful!
