### ISSUE TITLE
Use new GH actions manual triggers for preparing releases

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#7507]
As seen in: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch

It should be simple to adapt our current script to use this new mechanism instead.

**Comment by pradyunsg** [comment]
Please @-mention me in the PR, I'd like to copy ideas into pip's release process.

**Comment by nicoddemus** [comment]
So we can now go to the Actions tab and manually trigger a release using the prepare release pr workflow. 👍

Here's the PR that was created: https://github.com/pytest-dev/pytest/pull/8156
