### ISSUE TITLE
Tests on Windows started failing since WSL was made available on GitHub Actions

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#7518]
See e.g. https://github.com/pytest-dev/pytest/pull/7516/checks?check_run_id=889498913#step:7:172 from #7516. 

That smells like a change in the GitHub Actions environments, as the error message reads (with a couple of NUL-bytes in between):

```
running: bash C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-0\popen-gw0\test_argcomplete0\test_argcomplete --fu
     in: C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-0\popen-gw0\test_argcomplete0
Windows Subsystem for Linux has no installed distributions.


Distributions can be installed by visiting the Microsoft Store:


https://aka.ms/wslstore
```

Probably due to this: https://github.com/actions/virtual-environments/pull/1081. 
Not sure what to do here. Should we just skip that test on Windows? Or perhaps if on Windows and on GitHub Actions?

**Comment by bluetech** [comment]
From the log it looks like `bash` is in PATH in Windows, but is not actually bash, but some wrapper script which fails...

Maybe in addition to the `which` we can also skip if `bash --version` fails, or some other safe check to verify this is actually bash.

**Comment by The-Compiler** [comment]
Yeah, I suppose something like running `bash --version` and checking that the output starts with `GNU bash` would be better. I won't have time to submit a PR right now I'm afraid, so feel free to go ahead if you have the time.
