### ISSUE TITLE
Show namedtuple field name in assertion error message

### ISSUE THREAD

**Issue by tekumara** [pytest-dev/pytest#7527]
```python
from typing import NamedTuple

class Cart(NamedTuple):
    num_items: int
    total_cost: float

def test_cart():
    assert Cart(1, 10) == Cart(1, 20)
```

pytest failure message:
```
    def test_cart():
>       assert Cart(1, 10) == Cart(1, 20)
E       assert Cart(num_item...total_cost=10) == Cart(num_item...total_cost=20)
E         At index 1 diff: 10 != 20
E         Use -v to get the full diff
```

It would nice if the field name was shown in the assertion failure message, rather than an index, eg:
```
    def test_cart():
>       assert Cart(1, 10) == Cart(1, 20)
E       assert Cart(num_item...total_cost=10) == Cart(num_item...total_cost=20)
E         At index 1 (total_cost) diff: 10 != 20
E         Use -v to get the full diff
```

Python 3.6.10
Pytest 5.4.3

**Comment by asottile** [comment]
I believe this is pytest noticing this is a `tuple` and comparing it as a sequence -- there can probably be some special casing if it looks like a namedtuple (isinstance of `tuple`, has `_fields`, etc. -- it's actually difficult to know exactly whether something is a namedtuple) and special case the assertion messaging (similar to what is done for attrs classes, etc.)

**Comment by symonk** [comment]
@asottile it is indeed hard to determine! (surprisingly actually - tho namedtuple appears to be a factory function, rather than a class).  instance checking on tuple / hasattr _fields seems like one of the _best_ ways to go, but even that has no absolute guarantee (e.g custom class with such attr etc).

**Comment by RonnyPfannschmidt** [comment]
i believe tuple sub classes with `_fields` can be reasonably considered similar to attrs/dataclasses

**Comment by tirkarthi** [comment]
Detecting a namedtuple was raised to CPython. Checking for tuple subclass and `_fields` attribute is the suggested way. See : https://bugs.python.org/issue7796

I have implemented this feature with https://github.com/tirkarthi/pytest/commit/726450b2bdba2d7bf1955b8963207f9d808055a1

**Comment by The-Compiler** [comment]
@tirkarthi Looks great from a quick look! :+1: Do you want to open a pull request?

**Comment by graingert** [comment]
a less elegant approach, but with lower chance of false positives:

```python
_NT_REPR_CODE = collections.namedtuple("a", "").__repr__.__code__

def isnamedtuple(v):
    for c in type(v).__mro__:
        try:
            c_repr_code = c.__repr__.__code__
        except AttributeError:
            continue
        if c_repr_code is _NT_REPR_CODE:
            return True
    return False
```

FWIW, I like the "._fields" approach but I think it should fallback to regular tuple comparison if the attributes are not exhausted
