### ISSUE TITLE
Deprecate `--strict` 

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#7530]
I don't see the point in removing it in a release just to reintroduce it again, that just makes things more confusing for everyone.

_Originally posted by @The-Compiler in https://github.com/pytest-dev/pytest/issues/7503#issuecomment-662524793_

**Comment by graingert** [comment]
@nicoddemus why don't we do this in `6.1`?

**Comment by nicoddemus** [comment]
6.1 is the version where we effectively remove the deprecated features. I would rather not introduce another possible breakage point in 6.1, hence delay this until 6.2.

**Comment by graingert** [comment]
Ok that makes sense
