### ISSUE TITLE
Quesiton on best way to duplicate a `nodes.py` `Item` object

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest#7543]
Hi everyone,

I want to be able to create a duplicate of an `Item` object ( defined AFAIK in `nodes.py` ). When I try to deep-copy it, I get the following error:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/gnikonorov/pytest-dynamicrerun/.venv/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/gnikonorov/pytest-dynamicrerun/.venv/lib/python3.7/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
...
INTERNALERROR>   File "/usr/lib/python3.7/copy.py", line 169, in deepcopy
INTERNALERROR>     rv = reductor(4)
INTERNALERROR> TypeError: can't pickle module objects
```
I am trying to create a duplicate so that I can rerun a set of tests after all tests have run ( in this case I am rerunning all failed tests ). If I just save it on the `session` object, It looks like it's status is duplicated. So, let's we had a test named `test_false` that just asserted False, and it ran twice. Let's say after the first run I changed its status to `skipped` via `report.outcome`, and left it as `failed` on the second run. I would expected to see `1 failed, 1 skipped`, but instead I see `2 failed, 2 skipped` ( presumably because I'm sharing the same item ).

What is the best way to create a duplicate of the object to achieve my goal above?

**Comment by RonnyPfannschmidt** [comment]
Currently there is no good way to duplicate nodes, its horrendously error prone and should be avoided

Can you outlined the actual use case in more detail (as it sounds similar to rerunfailures)

**Comment by gnikonorov** [comment]
Sure @RonnyPfannschmidt. It is similar but there are 2 key differences.

I am trying to rerun failed tests on a dynamic interval ( so you could say if error x occurs, rerun the failing test at the start of the hour ). This is different from rerun failures which attempts to rerun after a predefined time interval ( y seconds ).

I want to defer rerunning tests instead of immediately attempting to rerun which is also different from rerun failures since it attempts to rerun an error immediately upon encountering it. So the idea is:

- Collect and run all tests
- Dynamically wait until it's safe to rerun again
- Rerun only the failed tests

Hopefully that clears it up

**Comment by RonnyPfannschmidt** [comment]
that sounds like a combination of lastfailed and a custom delay - is there any reason for not just starting a new pytest run with `--lastfailed` at/after the controlled interval,

in any case, i would strongly suggest to use the builtin lastfailed plugin and to manage the scheduling at pytest execution instead of having pytest fail

**Comment by gnikonorov** [comment]
Thanks @RonnyPfannschmidt let me try that. Closing for now
