### ISSUE TITLE
Better document -k partial matching and what 'keyword' means

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#7546]
_Originally posted by @asottile in https://github.com/pytest-dev/pytest/issues/7539#issuecomment-664050187_

I think at least this should be documented and improved to avoid underscored names (this would solve this particular issue, but I think would be a reasonable baseline expectation)

The relevant docs are here: https://docs.pytest.org/en/latest/example/markers.html#using-k-expr-to-select-tests-based-on-their-name

**Comment by ikedaosushi** [comment]
I'll take it!

**Comment by ikedaosushi** [comment]
I'll take it.

**Comment by Swaleha-12** [comment]
Can I take this one?

**Comment by asottile** [comment]
@Swaleha-12 it looks like #7610 is already started
