### ISSUE TITLE
Return value for `--last-failed-no-failures none`

### ISSUE THREAD

**Issue by dimaqq** [pytest-dev/pytest#7562]
More of a question / maybe behaviour change request:

```command
> rm -rf .pytest_cache/
> pytest --last-failed --last-failed-no-failures none && echo OK || echo FAIL
...
run-last-failure: no previously failed tests, deselecting all items.
=== test session starts ===
...
=== 1915 deselected, 12 warnings in 1.69s ===
FAIL
```

Should `pytest` return `0`, truthy to shell when no tests are ran as a result of `--last-failed-no-failures none` ?

**Comment by Zac-HD** [comment]
See #2393 - failing (exit code 5) when no tests are run is the intended behaviour, to avoid 'missed alarms' where tests should fail but were not collected.  We considered adding an option to disable this, but concluded that the complexity was better left to the invoking user or script - pytest has a lot of options already!

**Comment by bsipocz** [comment]
I run into this very same issue, and now wonder what's the purpose of `--last-failed-no-failures none` if it will trigger the failing status in all the cases?
