### ISSUE TITLE
pytest.raises not working with suppressing context manager

### ISSUE THREAD

**Issue by Pilen** [pytest-dev/pytest#7579]
I have found a weird edge case regarding context managers and expected exceptions.

```python
#file: pytest_example.py
import pytest
from typing import Any

class ExitException(Exception):
    pass

class Foo():
    def __enter__(self) -> "Foo":
        return self
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool:
        print("Is ExitException:", exc_type == ExitException)
        return True
        # return None

class UnrelatedException(Exception):
    pass

def test_foo() -> None:
    with Foo() as foo:
        with pytest.raises(UnrelatedException) as exc_info:
            raise ExitException()
            # pass
    print("exc_info:", vars(exc_info))
```

In the above snippet I create a contextmanager that expects to be exited by raising an `ExitException` that will then be suppressed.
In test_foo I use the contextmanager as intended, but I have thrown in a `pytest.raises` for an entire unrelated exception.

```
$ python -m pytest -s pytest_example.py
=================================== test session starts ====================================
platform linux -- Python 3.8.2, pytest-6.0.0, py-1.9.0, pluggy-0.13.1
rootdir: /vagrant
collected 1 item

pytest_example.py Is ExitException: True
exc_info: {'_excinfo': None, '_striptext': '', '_traceback': None}
.

==================================== 1 passed in 0.01s =====================================
```
Pytest seem to be happy no matter happens inside the raises block. I would expect pytest to check the exception before the context manager handles it.
I can replace the `raise ExitException()` with `pass` and pytest still doesn't complain.

If `Foo.__exit__` returns a false value, pytest works as expected.

I did this in a venv with only pytest installed
```
$ python -m pip list
Package        Version
-------------- -------
attrs          19.3.0
iniconfig      1.0.0
more-itertools 8.4.0
packaging      20.4
pip            20.0.2
pkg-resources  0.0.0
pluggy         0.13.1
py             1.9.0
pyparsing      2.4.7
pytest         6.0.0
setuptools     44.0.0
six            1.15.0
toml           0.10.1
```

```
$ python3 --version
Python 3.8.2
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```
```
$ uname -a
Linux ubuntu-focal 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bluetech** [comment]
I think what's going on is this (haven't verified): `pytest.raises` fails using an `assert`. When the `assert` fails, it raises an `AssertionError` exception. This then reaches your context manager, which suppresses it (because of the unconditional `return True`).

**Comment by asottile** [comment]
yep, nothing that can be done here -- the failure mode of `raises` is raising an exception, so if you ignore that exception then you're out of luck!

**Comment by Pilen** [comment]
@asottile 
Hmm I see, it is definitely simpler to build pytest.raises by just propagating the exception.
It means that you should ensure no code interferes with the exception then, I am not sure that I particularly like that.

If the code looks like
``` python
import pytest

class ExitException(Exception):
    pass
class UnrelatedException(Exception):
    pass


def test_foo() -> None:
    try:
        with pytest.raises(UnrelatedException):
            raise ExitException()
    except:
        pass
```

It is clear that we have done something in the test*ing* code that catches the exception from pytest.raises, that I am actively ignoring it.\
But in my original case or in this following case:

```python
import pytest

class ExitException(Exception):
    pass
class UnrelatedException(Exception):
    pass

def caller(callback):
    try:
        callback()
    except:
        pass

def test_bar() -> None:
    def inner():
        with pytest.raises(UnrelatedException):
            raise ExitException()
    caller(inner)
```

I think it is rather problematic that the test*ed* code can interfere with the test*ing* code in this way. Ignoring what pytest.raises did was not the intention.

But I see how it would probably be hard to change pytest to handle that the "right" way, if it is even possible.\
I might make my own helper functionality that will make some kind of note that the raises failed, this can then be checked at the end of the test.\
Unfortunately that would mean the error could not point at the correct place in the code.

I do however think that the this "pitfall" should be documented clearly in both https://docs.pytest.org/en/stable/reference.html and https://docs.pytest.org/en/stable/assert.html#assertions-about-expected-exceptions

**Comment by nicoddemus** [comment]
> But I see how it would probably be hard to change pytest to handle that the "right" way, if it is even possible.

I'm not sure it is possible: pytest calls the functions and checks for assertion errors to evaluate if the test passed or not; if any code along the way prevents the exception from happening, there's not anything pytest can do.

**Comment by asottile** [comment]
@Pilen I'm not sure what's surprising to you here, if you could elaborate that would be helpful.  failed assertions raise exceptions and if your tests are bad and catch those exceptions then you're going to silently ignore them.  perhaps when writing tests you should ensure they fail first and then pass when you implement the code? (mini-TDDish) this would help you avoid writing tests which do nothing or pass for the wrong reason

**Comment by RonnyPfannschmidt** [comment]
Bringing back 4 years old closed issue isn't quite nice
