### ISSUE TITLE
Inconsistent `self` instances for class scoped fixtures

### ISSUE THREAD

**Issue by vkomarov-r7** [pytest-dev/pytest#7580]
- [x] a detailed description of the bug or suggestion
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

Hello,

It appears that it's possible to have class fixtures assign to the `self` value for later use in subsequent tests (usually for setup purposes). While I'm aware that rewriting them to use fixtures for setup more extensively is the ultimate goal, I don't have the time to do so. Ultimately I ended up with something like this, that seems to fail when the scope is set to `class` instead of `function`. I've observed that the `self` instance seems to get reset when it gets to the test case. This is surprising, as I would expect the `self` instance to be the same across the entire test run, including the init in `class_set_me_up`.

```python
import pytest

class TestSomething:
   @pytest.fixture(scope='class', autouse=True)
   def class_set_me_up(self):
       self.some_attr = "foo"

   def test_foo(self):
       assert self.some_attr == "foo"   # Fails with an AttributeError, not able to find `some_attr`. Expected the attribute to exist on the class.
```

## Env Info
`pip list`: Can repro with the above example with just `pytest` (and deps) installed.
pytest == 7.0.0 (version doesn't seem to matter)
OSX 10.15.6

**Comment by The-Compiler** [comment]
This is intended and what unittest.py does as well. Also see #6890 as well as the [relevant docs](https://docs.pytest.org/en/stable/getting-started.html#group-multiple-tests-in-a-class).
