### ISSUE TITLE
Mypy checking fails with --disallow-untyped-decorators

### ISSUE THREAD

**Issue by squaresmile** [pytest-dev/pytest#7589]
It looks like the `@pytest.mark.parametrize` decorator can't pass mypy with `--disallow-untyped-decorators`. mypy works without the flag.

Following [my comment](https://github.com/pytest-dev/pytest/issues/3342#issuecomment-666497058), I made this [reproduction repo](https://github.com/squaresmile/pytest-mypy-test). I can reproduce this with pytest 6.0.1 and Python 3.6.9 on Linux or Python 3.8.5 on Windows.

```
> mypy test_mypy.py
test_mypy.py:7: note: Revealed type is 'def (query: builtins.str, result: builtins.str)'
> mypy --disallow-untyped-decorators test_mypy.py
test_mypy.py:3: error: Untyped decorator makes function "test_raw" untyped
test_mypy.py:7: note: Revealed type is 'def (query: builtins.str, result: builtins.str)'
```

```
> pip list
Package            Version
------------------ -------
attrs              19.3.0
importlib-metadata 1.7.0
iniconfig          1.0.0
more-itertools     8.4.0
mypy               0.782
mypy-extensions    0.4.3
packaging          20.4
pip                20.1.1
pluggy             0.13.1
py                 1.9.0
pyparsing          2.4.7
pytest             6.0.1
setuptools         49.2.0
six                1.15.0
toml               0.10.1
typed-ast          1.4.1
typing-extensions  3.7.4.2
wheel              0.34.2
zipp               3.1.0
```

**Comment by bluetech** [comment]
This is a mypy bug. I proposed a fix here: https://github.com/python/mypy/pull/9232.

I'm afraid there isn't a simple workaround for this in pytest. Hopefully the mypy fix will be merged and released, but until then I suggest turning off `disallow-untyped-decorators` (at least in your test modules) are adding `type: ignore` comments.
