### ISSUE TITLE
[Question] Applying marks dynamically from parametrize with args?

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#7594]
This is a bit of a small edge case, something we use in work:

```python
@pytest.mark.example(variable=10)
def test_something():
    # we do some magic here that is bolted into the test class based on the value of variable
    ...
```

Is it at all possible to parametrize the above scenario to apply this example marker with a range of value(s) per iteration?  

Expected outcome:

Generate this test 4 times, where variable = [10, 9, 8,7] for example.

We use the marker along with arguments to do some logic upfront for all test(s). I have looked at the parametrized with pytest.param but I don't think it supports arg/kwargs for the marker ?

a pytest_generate_tests hook may be the way to go? I'm curious if a solution already exists (it is trivial if the marker to be applied per iteration is non args such as @pytest.mark.xfail etc

`note: we dont care about the injected value from parametrized, we just need the test generated with a particular mark on it with X arg values`

**Comment by iwanb** [comment]
See this in the doc:
https://docs.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions

```python
# content of test_expectation.py
import pytest


@pytest.mark.parametrize(
    "test_input,expected",
    [("3+5", 8), ("2+4", 6), pytest.param("6*9", 42, marks=pytest.mark.xfail)],
)
def test_eval(test_input, expected):
    assert eval(test_input) == expected
```

Replacing `pytest.mark.xfail` by `pytest.mark.example(variable=10)`. AFAIK it should work the same from the `pytest_generate_tests` hook.

**Comment by The-Compiler** [comment]
@iwanb I don't think this answers the question @symonk was asking. As far as I understood, the goal was to run the test multiple times with different values passed to the *marker*.

**Comment by iwanb** [comment]
Isn't this what this does? (The input can be ignored.)

```python
@pytest.mark.parametrize(
    "input",
    [
        pytest.param(1, marks=pytest.mark.example(variable=1)),
        pytest.param(2, marks=pytest.mark.example(variable=2)),
        pytest.param(3, marks=pytest.mark.example(variable=3)),
        pytest.param(4, marks=pytest.mark.example(variable=4)),
    ],
)
```

**Comment by The-Compiler** [comment]
Ah, right - I suppose that works, even if a bit unorthodox.
