### ISSUE TITLE
Cannot set log capture format

### ISSUE THREAD

**Issue by tekumara** [pytest-dev/pytest#7617]
In pytest 5.4.3 it was possible to configure log capture to format logs the same way as our application, like this:
```python
def configure_log_capture_format():
    """Configure pytest's log capture handler to use the right formatter"""
    our_formatter = logging.root.handlers[0].formatter
    if not our_formatter:
        raise Exception("no formatter")
    pytest_handler = logging.root.handlers[-1]
    pytest_handler.setFormatter(our_formatter)
```

In pytest 6.0.1 the above no longer has an effect.

**Comment by The-Compiler** [comment]
Do you have a complete, runnable example I could use to bisect this?

**Comment by tekumara** [comment]
Thanks @The-Compiler for your response... I've been digging into this a little.

Here what`logging.root.handlers` contains in pytest 5.4.3:
```
 [<FiniteQueueHandler (NOTSET)>, <LogCaptureHandler (NOTSET)>]
```

And in pytest 6.0.1:
```
[<FiniteQueueHandler (NOTSET)>,
 <_LiveLoggingNullHandler (NOTSET)>,
 <_FileHandler /dev/null (NOTSET)>,
 <LogCaptureHandler (NOTSET)>,
 <LogCaptureHandler (NOTSET)>]
```

Looks like the solution is to select the second to last log handler, rather than the last, eg:

```python
    pytest_handler = logging.root.handlers[-2]
```

**Comment by The-Compiler** [comment]
Closing this then, as I don't think there's any guarantee about which log handlers pytest uses internally.
