### ISSUE TITLE
caplog fixture is not setting the requested level per logger

### ISSUE THREAD

**Issue by Colin-b** [pytest-dev/pytest#7618]
Hi,

Since pytest 6.0.1 (running on Windows 7 with Python 3.8.2 64 bits) , it seems that caplog fixture is not handling set_level properly anymore.

I wrote a quick sample to reproduce the issue I am facing, when setting levels on loggers, it seems that only the last one is taken into account without even looking at the related logger.

As you can see in the following sample (working with pytest 5.4.3), failing since pytest 6.

```python
import logging

logger1 = logging.getLogger("first_logger.test_module.test_submodule")
logger2 = logging.getLogger("second_logger.test_second_module.test_second_submodule")


def test_caplog(caplog):
    caplog.set_level(logging.DEBUG, logger="first_logger")
    caplog.set_level(logging.INFO, logger="second_logger")

    logger1.debug("This is a debug statement")
    logger2.debug("This is a second debug statement")

    logger1.info("This is an info statement")
    logger2.info("This is a second info statement")

    assert caplog.messages == [
        "This is a debug statement",  # This statement is not captured since pytest 6
        "This is an info statement",
        "This is a second info statement"
    ]

```

**Comment by bluetech** [comment]
Since fcbaab8b0b89abc622dbfb7982cf9bd8c91ef301, `set_level` also affects the level of the log capturing handler. I think we might want to reconsider that, but this is already discussed in #7162, so I'll close this as a duplicate.

A workaround for your specific issue for now is to swap the order of the two `set_level` lines; the last call affects the rest of the test.

**Comment by Colin-b** [comment]
Thanks, @bluetech I confirm it works by changing the order of the calls. 

I don't know how many people will encounter the same issue but you might want to add this change in the `Breaking Changes` section of the 6.0.0 changelog to avoid issues to popup or people simply sticking to pytest 5
