### ISSUE TITLE
PytestConfigWarning about unknown keys can't be suppressed

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#7620]
@The-Compiler With pytest.PytestConfigWarning the INTERNALERROR is gone but I still get the warnings. I have even tried to ignore all PytestConfigWarning but with no success. 

```ini
filterwarnings =
    ignore::pytest.PytestConfigWarning
```

This means, filterwarnings does nothing in my case. How can I suppress these warnings?

```
============================== warnings summary ===============================
venv\lib\site-packages\_pytest\config\__init__.py:1148
  venv\lib\site-packages\_pytest\config\__init__.py:1148: PytestConfigWarning: Unknown config ini key: flake8-ignore
  
    self._warn_or_fail_if_strict("Unknown config ini key: {}\n".format(key))

venv\lib\site-packages\_pytest\config\__init__.py:1148
  venv\lib\site-packages\_pytest\config\__init__.py:1148: PytestConfigWarning: Unknown config ini key: flake8-max-line-length

_Originally posted by @marincandenza in https://github.com/pytest-dev/pytest/issues/7612#issuecomment-668993473_

**Comment by The-Compiler** [comment]
I can reproduce with:

```ini
[pytest]
doesnotexist = 42
filterwarnings = ignore::pytest.PytestConfigWarning
```

I'm guessing the warning gets emitted before pytest's warning filtering is initialized, which is a bit unfortunate...

**Comment by nicoddemus** [comment]
Yeah a bit, what happens is:

We want to issue warnings during the configure stage. Unfortunately at that stage, it might happen that the `warnings` plugin has not even been configured yet, so warnings issued using `warnings.warn` would not be captured at all.

The workaround devised at the time was to call `_issue_warning_captured`, which calls `warnings.warn` but also manually triggers `pytest_warning_recorded`. That's the reason why we can still show it in the terminal.

Perhaps a way to fix the general case is to special case warnings, by installing the filters early as possible, even before the `warnings` plugin is initialized. This would require some refactoring though.

**Comment by nicoddemus** [comment]
Actually for this specific warning it seems it is possible, see #7649.
