### ISSUE TITLE
How to Run the Tests of Django Third-Party apps Using Pytest

### ISSUE THREAD

**Issue by 7xMind** [pytest-dev/pytest#7636]
How can I run the tests of third party apps? With the default Django test runner, it would be as trivial as issuing: `./manage.py <name_of_the_installed_app>`

But this seems not to be the case with pytest. If I install a third-party app and put it inside the istalled_app, how can I run the app's tests using pytest? 

If I install my desired app using pip, and I add it to the list of installed apps, and I issue the command: pytest <name_of_the_app> I get the error: `ERROR: file not found: <name_of_the_app>`

I am using Django 2.2.7, Python 3.6, pytest-django-3.9.0

**Comment by bluetech** [comment]
Can you give a particular example of a 3rd-party app which allows you to run tests in this way?
