### ISSUE TITLE
consume and ignore pytest 6 config options in pytest 4

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#7653]
I want to use `--config-strict` in a py2/py3 universal python project, but the flag is mis-handled in pytest v4

also pytest v4 should detect the bare minimum of pyproject.toml config options, to be able to let the operator know that they need to upgrade, eg:

```
[tool.pytest.ini_options]
minversion = "6.0"
```

should cause pytest 4 to fail

- [ ] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by graingert** [comment]
otherwise I can try and backport the features completely

**Comment by graingert** [comment]
the `pytest --strict-config` option can be added in a plugin

https://docs.pytest.org/en/latest/writing_plugins.html#using-hooks-in-pytest-addoption

minversion is harder to do:
```
[tool.pytest.ini_options]
minversion = "6.0"
```

**Comment by nicoddemus** [comment]
As per our policy pytest 4 should not receive any new features, unless for exceptional cases where something is completely broken, so backporting the features completely is out of question, I think.

However some minimal/minor feature that enhances interoperability between pytest 4 and current versions could be considered. What exactly would you propose?

**Comment by graingert** [comment]
@nicoddemus I've created https://pypi.org/project/pytest-forward-compatibility/ and I think it solves the first part of the problem for me
