### ISSUE TITLE
Injecting a Session-level Item

### ISSUE THREAD

**Issue by dmtucker** [pytest-dev/pytest#7655]
I am working on [an issue with a plugin](https://github.com/dbader/pytest-mypy/issues/85) which seems to be caused by an `Item` that is [injected in `pytest_collection_modifyitems`](https://github.com/dbader/pytest-mypy/blob/573667535d1f6f731d76fd87f1360b9de85f7aa7/src/pytest_mypy.py#L113-L130) because its `parent=session`.
1. This obviously suggests `parent=session` is not supported in this context. Could anyone confirm/explain that for me?
   It seemed appropriate because the injected `MypyStatusItem` applies to the whole run more than any particular `MypyFileItem`.
2. Is this kind of [injection](https://github.com/dbader/pytest-mypy/blob/573667535d1f6f731d76fd87f1360b9de85f7aa7/tests/test_pytest_mypy.py#L262-L291) (or [removal](https://github.com/dbader/pytest-mypy/blob/573667535d1f6f731d76fd87f1360b9de85f7aa7/tests/test_pytest_mypy.py#L217-L246)) of `Item`s in `pytest_collection_modifyitems` even supported?

**Comment by dmtucker** [comment]
I will take a stab at answering my own question based on what I've learned tinkering with this over the past couple months.
1. The hierarchy seems to be `session` -> `File` -> `Item` (not `session` -> `Item`).
   In the case of `pytest-mypy`, the `File` (`MypyFile`) yields an `MypyFileItem` triggering the need for a `MypyStatusItem`, so really, the `MypyStatusItem` is a "product" of the `MypyFile`. (It just so happens that only one is needed as opposed to one per `MypyFile` or `MypyFileItem`).
2. Removal? Yes.
   Injection? Eh, maybe, but it's wonky because it's essentially implementing collection at the end of collection. Not having an obvious `parent` to attach is basically evidence of abuse. Cloning an `Item` or synthesizing one based on (or perhaps as a child of) another might make sense, but overall, `File`s should probably be the test creators/"injectors".

**Comment by tucked** [comment]
> 2. Removal? Yes.

Also consider calling `config.hook.pytest_deselected`:
https://github.com/pytest-dev/pytest/blob/63d2f7f7f8ec8b09c4289f18a94178c520d93bff/src/_pytest/main.py#L419-L421

**Comment by Zac-HD** [comment]
Closing because I don't think there's any action for the Pytest project to take here 😕
