### ISSUE TITLE
XML file is empty when assertions are placed in other thread than main. 

### ISSUE THREAD

**Issue by deepanshu-yadav** [pytest-dev/pytest#7657]
# XML file is not getting updated on when the assertion fails in a thread. 

- Pytest Version - 5.2.1
- Environment- Ubuntu 18.04 

Hi, I have written a script which checks whether an assertion is true every 10 seconds and fails after a minute (deliberately). 
The script is as follows : 

```
import datetime
import time
from threading import Thread, Condition
DURATION = 1 # 1 minute
START_TIME = 0

class Monitoring(Thread):
    def __init__(self):
        super(Monitoring, self).__init__()

    def run(self):
        global DURATION
        while True:
            if (datetime.datetime.now() - START_TIME).seconds <= DURATION*60:
                assert 1+2 == 3, "No"
                time.sleep(10)
            else:
                assert 1+3 == 5, "oh no"
                break

def test_thread():
    global START_TIME
    START_TIME = datetime.datetime.now()
    Monitoring().start()
```

Store this script under the name **test_for_thread.py** . 
Also execute this script like this  

```
python3  -m pytest --junit-xml=error_report.xml test_for_thread.py
```

Here is what i get 

```
- generated xml file: /home/deepanshu/notebooks/error_report.xml -
============================== 1 passed in 0.01s ===============================
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/deepanshu/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/deepanshu/foglamp_workspace/csv_plugins/notebooks/test_for_thread.py", line 18, in run
    assert 1+3 == 5, "oh no"
AssertionError: oh no
assert (1 + 3) == 5
```

I wanted the **error_report.xml**  should should have information about the failure. The file is created but there is nothing in there. I suspect the pytest exits , but the thread keeps on running. Is there any way to make sure the failure information to get reflected in the xml file or may be to force the pytest to not exit . 

Any help appreciated. 
Thanks in advance.

**Comment by RonnyPfannschmidt** [comment]
This use case is not supported, with python as is, its rather hard to do, it's something a plugin should explore

**Comment by Zac-HD** [comment]
I agree, this is out of scope for pytest.

**Comment by deepanshu-yadav** [comment]
Ok thanks for you feedback. @RonnyPfannschmidt @Zac-HD . Yes should close this.

**Comment by bjoluc** [comment]
> This use case is not supported, with python as is, its rather hard to do, it's something a plugin should explore

I built one last year: [pytest-reraise](https://github.com/bjoluc/pytest-reraise) should be exactly what you were looking for @deepanshu-yadav :slightly_smiling_face:
