### ISSUE TITLE
Parameterize on a session level

### ISSUE THREAD

**Issue by rng4life** [pytest-dev/pytest#7659]
I have a question for someone more experienced with the pytest framework, it's not really an issue but I'm going to throw it here as it may be a feature idea. 

I'll give a short example of my use case so the question's clear. 
I'm testing some application code I have against a vm that I have setup as a session level fixture for dynamic creation and cleanup of the vm. I want to run all of my tests with the vm in a particular state, then I want to change the state of the vm and run all of the tests again. 
In visual form: 
(setup vm) [state 1]: test1, test2 ... test100, [toggle to state 2] test1, test2, ... test100 (teardown vm)

Is this within the scope of the existing framework/plugins?

**Comment by Zac-HD** [comment]
Sounds like a case for `pytest-xdist` to me!

**Comment by rng4life** [comment]
Interesting, I didn't see this capability the xdist documentation but I will look at it again, thanks for the comment and proper label :)

**Comment by RonnyPfannschmidt** [comment]
Session scope +prams already solves this, xdist does not seem related

**Comment by The-Compiler** [comment]
To elaborate on what @RonnyPfannschmidt said: You can [parametrize fixtures](https://docs.pytest.org/en/stable/fixture.html#parametrizing-fixtures) which then runs all tests twice. I think by default they'd run "interleaved" though, so you might need to reorder them in `pytest_modifyitems`.

**Comment by RonnyPfannschmidt** [comment]
Session scope parameters trigger reordering to minimise setup / teardown of scoped fixtures

**Comment by rng4life** [comment]
So a session scoped param would run all tests once for param[0], then run all of them again for param[1]? Or would I need to modify the collection to attain that order?

**Comment by nicoddemus** [comment]
> So a session scoped param would run all tests once for param[0], then run all of them again for param[1]?

Yes, pytest will reorder the tests for you automatically:

```python
import pytest

@pytest.fixture(scope="session", params=[1, 2, 3, 4])
def ses():
    pass

def test_foo(ses):
    pass

def test_bar(ses):
    pass
```

```
======================== test session starts ========================
collected 8 items

.tmp/test_foo_ses.py::test_foo[1] PASSED                       [ 12%]
.tmp/test_foo_ses.py::test_bar[1] PASSED                       [ 25%]
.tmp/test_foo_ses.py::test_foo[2] PASSED                       [ 37%]
.tmp/test_foo_ses.py::test_bar[2] PASSED                       [ 50%]
.tmp/test_foo_ses.py::test_foo[3] PASSED                       [ 62%]
.tmp/test_foo_ses.py::test_bar[3] PASSED                       [ 75%]
.tmp/test_foo_ses.py::test_foo[4] PASSED                       [ 87%]
.tmp/test_foo_ses.py::test_bar[4] PASSED                       [100%]

========================= 8 passed in 0.05s =========================
```

**Comment by rng4life** [comment]
Yep, that's working superbly.
I would still like to randomize the test order within the scope of the params which pytest-random-order doesn't seem to pay attention to and it scrambles my session scoped stateful tests but I assume that I'll have to do some custom ordering or extend the functionality of that plugin to handle that.

You rock, thanks for the help so far
