### ISSUE TITLE
Timestamp in Pytest JUnit XML test report doesn't have time zone infomation

### ISSUE THREAD

**Issue by jih-dk** [pytest-dev/pytest#7662]
- [x] a detailed description of the bug or suggestion
Last year,  pytest add <timestamp> attribute to the JUnit test report.   In the test report I can see the timestamp like 
`timestamp="2020-08-17T10:14:39.548365"`

It looks like pytest just takes the system time from OS, and save it to test report.  
Unfortunately,  this timestamp doesn't have any timezone infomation,  Our CI system will treat this timestamp as a UTC time, even the timestamp is actually from another time zone.  

- [x] pytest and operating system versions
pytest 5.2.1,  I have seen the issue in both Linux and Windows

Is it possible to add timezone information to the timestamp attribute,  or always use UTC time in timestamp?

**Comment by Zac-HD** [comment]
I think it would be appropriate to always use UTC, and to include the timezone (i.e. utc) in the xml file.

https://blog.ganssle.io/articles/2019/11/utcnow.html has some good advice on the topic.

**Comment by graingert** [comment]
Local time with zone and UTC offset is probably the most useful. It's just
whether or not JUnit supports it

**Comment by nicoddemus** [comment]
Currently the `timestamp` attribute is defined only as a `xsd:string`:

https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd#L123

```
<xs:attribute name="timestamp" type="xs:string" />
```

So I think it is reasonable to write local time + UTC offset as @graingert mentioned.

**Comment by nicoddemus** [comment]
@jinxudb would you like to give that a try? Should be a simple patch (change that line + test + a changelog).

**Comment by graingert** [comment]
https://github.com/junit-team/junit5/issues/373 looks like it's sort of implementation defined, so would be a good idea to test it on a real Jenkins box

**Comment by graingert** [comment]
@nicoddemus https://github.com/junit-team/junit5/blob/58bb81bfee73c5154b0a223ba68f7677bb98376d/junit-platform-reporting/src/main/java/org/junit/platform/reporting/legacy/xml/XmlReportWriter.java#L119

**Comment by nicoddemus** [comment]
Thanks @graingert. 👍 

From the docs at https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html, that format does not include the time zone, but of course it doesn't mean that a Jenkins box cannot read time zone information if it is present.

**Comment by graingert** [comment]
@nicoddemus we should also make sure that we store the timestamp of when the test started, not finished. This way a consumer can determine the end time of a test from `testsuite.timestamp + dt.timedelta(seconds=testsuite.time)`

**Comment by graingert** [comment]
@nicoddemus I think we should only land this if Junit5 also lands the same change

**Comment by graingert** [comment]
getTimestamp is an undocumented String getter: https://javadoc.jenkins.io/plugin/junit/hudson/tasks/junit/SuiteResult.html#getTimestamp--

**Comment by joseph-sentry** [comment]
Any update on this issue? I think that having some timezone information in the timestamp makes sense.

It looks like the JUnit plugin for Jenkins does support datetimes with timezone information as shown in [this sample file](https://github.com/jenkinsci/junit-plugin/blob/63bd1315bfcddb63bf670270b31cf67ac4c09076/src/test/resources/hudson/tasks/junit/junit-report-testsuite-various-timestamps.xml#L2) that's a part of their tests. This [test](https://github.com/jenkinsci/junit-plugin/blob/63bd1315bfcddb63bf670270b31cf67ac4c09076/src/test/java/hudson/tasks/junit/TestResultTest.java#L331) here shows that the suites included in the sample junit xml file should be parsed correctly. 

So I think as long as the timestamp generated by the junitxml plugin matches one of the valid ones shown in the sample file then it should be compatible with Jenkins.
