### ISSUE TITLE
Can I collect `Items` without running `pytest.main()`?

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#7665]
I'm currently working on a fuzzing mode for Hypothesis, and would really like to have a smooth integration with existing test suites.  The basic idea is for `fuzz <user args here>` to pick up each test that would be collected by `pytest --collect-only -m hypothesis <user args here>` and then do some longer-running magic with them.

Hacking around via the CLI to get test ids *kinda* works, but is (a) aesthetically displeasing, and (b) incorrect with respect to plugins - including Hypothesis' own pytest plugin - which modify collected items.  My best attempt so far, which doesn't work at all, was:

```python
config = _prepareconfig(args=None, plugins=None)
try:
    session = Session.from_config(config)
    config._do_configure()
    config.hook.pytest_collection(session=session)
    items = session.perform_collect()  # sadly always empty
finally:
    config._ensure_unconfigure()
```

(asking here rather than stackoverflow because it's a rather niche question about internals)

**Comment by bluetech** [comment]
- Missing `pytest_sessionstart`/`pytest_sessionfinish`
- Calling collection twice (the `pytest_collection` hook just calls `perform_collect`)
- Relying on `sys.argv`

So:

```py
import pytest
from _pytest.config import _prepareconfig

config = _prepareconfig(args=[], plugins=None)
try:
    session = pytest.Session.from_config(config)
    config._do_configure()
    config.hook.pytest_sessionstart(session=session)
    config.hook.pytest_collection(session=session)
finally:
    config.hook.pytest_sessionfinish(session=session, exitstatus=session.exitstatus)
    config._ensure_unconfigure()

print(session.items)
```

If you want a bit more isolation you can also try replacing `_prepareconfig` with `get_config`.

**Comment by Zac-HD** [comment]
You're a legend, that works perfectly.  Thanks!
