### ISSUE TITLE
Include code that runs in runpytest_subprocess in coverage

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#7679]
In #7651 we had some code which is only covered by a subprocess test and is somewhat hard to cover inprocess.

It *seems* that the code running in the subprocess is not covered. @nicoddemus mentioned that some coverage configuration is needed to get this to work: https://coverage.readthedocs.io/en/stable/subprocess.html

**Comment by asottile** [comment]
one way I've done this before is via `coverage-enable-subprocess`

essentially:
1. install `coverage-enable-subprocess` under test
2. https://github.com/asottile/setuptools-golang/blob/a6eaed0801255d4b2b7fb9e964126bce2747a0a9/tox.ini#L6
3. https://github.com/asottile/setuptools-golang/blob/a6eaed0801255d4b2b7fb9e964126bce2747a0a9/.coveragerc#L5

**Comment by antonblr** [comment]
Closing via #8188 - lines which have been shown as [uncovered](https://codecov.io/gh/pytest-dev/pytest/compare/d426a79a90351dff0492fbd40404b1256b24f91f...0d5a65091d45e04662837ace13dd88dba954ea8a/diff) in #7651 are covered now.
