### ISSUE TITLE
Add --log-cli option

### ISSUE THREAD

**Issue by GergelyKalmar** [pytest-dev/pytest#7680]
It is a bit tiresome to use ``-o log_cli=true`` to enable live logging – I've found that this is one of the options I use most often while TDD-ing. Adding this option to the config file is not really nice either because if one accidentally commits it then the automated tests are going to start doing live logging too, which is most likely not what one wants.

Would it be therefore possible to add a ``--log-cli`` option to pytest? Having a shorter flag like ``-g`` as well would be even more awesome (unfortunately ``-l`` is already used by a flag I rarely if ever need).

Thank you!

**Comment by symonk** [comment]
Hi @GergelyKalmar, the following should exhibit the same behaviour on its own:
```
--log-cli-level=LEVEL
```

I will add an explicit CLI option for it, makes sense to me to have it slightly more shorthand

**Comment by GergelyKalmar** [comment]
Makes sense! In the meantime I ended up creating a small plugin that adds a ``--live`` option, which in turn enables both ``-s`` and ``log_cli`` at the same time. This way I pretty much see the same behavior as I would if I were just running a program outside of a test suite. It even sets ``-n`` to ``0`` with ``pytest-xdist`` to make sure things don't run in parallel in live mode, which is nice.

**Comment by symonk** [comment]
@nicoddemus / @bluetech / @RonnyPfannschmidt how what is the process of where we decide something is viable and should be added? I want to avoid spending time doing pieces of work only to realise at PR time its not a viable option for the pytest core.

**Comment by nicoddemus** [comment]
@symonk there's no formal process I'm afraid, often what we do is to ask specifically for buy in from some people.

Personally on this I'm -0.5, because `-o log_cli=true` and `--log-cli` are not that far apart IMHO, but again I don't really use logging much so I wouldn't mind adding this if people who use logging a lot find the difference a game changer for them (note that `-o log_cli=1` also works).

**Comment by Zac-HD** [comment]
Closing this per https://github.com/pytest-dev/pytest/issues/12465#issuecomment-2175596712
