### ISSUE TITLE
issue with pytest mark 

### ISSUE THREAD

**Issue by arautela-conga** [pytest-dev/pytest#7684]
- [ ] a detailed description of the bug or suggestion
Hi, I am using pytest-tags annotated as below in the script. Upon execution I see that the correct number of items are getting collected but I do not see the results of all scripts in the allure report. I just wanted to get your inputs if this is an allure issue or pytest. Any inputs will be highly appreciated. Thank you in advance

@pytest.mark.tags("smoke")

command used to execute script: pytest -s -v --tags smoke tests
(my automated suite is under folder tests of the root directory)

- [ ] output of `pip list` from the virtual environment you are using

Package                  Version
------------------------ ----------
allure-pytest            2.8.12
allure-python-commons    2.8.12
appdirs                  1.4.3
atomicwrites             1.3.0
attrs                    19.3.0
cached-property          1.5.1
cachetools               4.0.0
certifi                  2019.11.28
chardet                  3.0.4
client                   0.0.1
colorama                 0.4.3
comtypes                 1.1.7
DateTime                 4.3
defusedxml               0.6.0
delayed-assert           0.3.2
future                   0.18.2
google-api-core          1.16.0
google-api-python-client 1.8.0
google-auth              1.11.3
google-auth-httplib2     0.0.3
googleapis-common-protos 1.51.0
httplib2                 0.17.0
idna                     2.9
isodate                  0.6.0
jsonpath                 0.82
lxml                     4.5.0
more-itertools           8.2.0
packaging                20.3
pip                      20.1.1
pluggy                   0.13.1
properties               0.6.1
property                 2.2
protobuf                 3.11.3
py                       1.8.1
pyad                     0.5.15
pyasn1                   0.4.8
pyasn1-modules           0.2.8
PyHamcrest               2.0.2
pyparsing                2.4.6
pytest                   5.4.1
pytest-json              0.4.0
pytest-ordering          0.6
pytest-tags              1.7.2
pytz                     2019.3
pywin32                  227
pywinauto                0.6.8
requests                 2.23.0
requests-toolbelt        0.9.1
rsa                      4.0
selenium                 3.141.0
setuptools               40.8.0
six                      1.14.0
uritemplate              3.0.1
urllib3                  1.25.8
wcwidth                  0.1.9
zeep                     3.4.0
zope.interface           5.1.0

- [ ] pytest and operating system versions
pytest                   5.4.1
 operating system version : Windows10 Enterprise version 1809

- [ ] minimal example if possible

Let say if 20 scripts are annotated as smoke. Upon execution, I see pytest collects all 20 out of the entire automated suite. But in the allure report I see results of only 10  scripts

**Comment by Zac-HD** [comment]
If the expected number of tests are collected, the problem is probably in the plugin.

**Comment by RonnyPfannschmidt** [comment]
this is a issue of https://github.com/Projectplace/pytest-tags

**Comment by arautela-conga** [comment]
@RonnyPfannschmidt  Thank you for the reply. So is this a known issue of https://github.com/Projectplace/pytest-tags. Do you suggest any workaround for the same

**Comment by arautela-conga** [comment]
> If the expected number of tests are collected, the problem is probably in the plugin.

Thank you Zac

**Comment by RonnyPfannschmidt** [comment]
@arautela-conga im not aware of a workaround, i wasn't even aware of the plugin, as people typically just use marks directly for that use case

**Comment by arautela-conga** [comment]
> @arautela-conga im not aware of a workaround, i wasn't even aware of the plugin, as people typically just use marks directly for that use case

No issues. Thanks again. Appreciate it :)
