### ISSUE TITLE
"plugin discovery order" incorrectly documented

### ISSUE THREAD

**Issue by mcow** [pytest-dev/pytest#7691]
[Documentation of "plugin discovery order"](https://docs.pytest.org/en/latest/writing_plugins.html#plugin-discovery-order-at-tool-startup) states that setuptools-entry-point plugins are loaded before plugins specified with `-p` on the command line. This is incorrect, the command line plugins are loaded "early" (as is documented elsewhere).

I would argue that a late-loading command-line option would be useful, but that's a different issue.

**Comment by graingert** [comment]
Could probably do with being an `<ol>`  rather than an `<ul>` in the docs

**Comment by RonnyPfannschmidt** [comment]
I recall a Bugfix wrt disabling setuptools plugins correctly, im on mobile atm and can't effectively search it

**Comment by nicoddemus** [comment]
Indeed `-p` are early loaded:

https://github.com/pytest-dev/pytest/blob/634cde9506eb1f48dec3ec77974ee8dc952207c6/src/_pytest/config/__init__.py#L1163-L1168
