### ISSUE TITLE
Summary when using collection only is confusing

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#7701]
A this moment the summary line is the same regarless if you effectively executed any tests or if you just did a discovery with commands like `pytest --collect-only` or `pytest-collect-only -k foo`.

The expectation is to see in the summary how many tests were collected and how many tests were deselected.

The collected/deselected/selected is printed early but not part of the summary and if you have more than ~40-60 tests selected, you will need to scroll a lot to spot that information.

The proposal here is to include this information in the summary line, which is clearly easier to read.

# Current output
```
# pytest --collect-only
==== no tests ran in 1.66s ====
# pytest --collect-only -k filter
==== 544 deselected in 1.67s ====
```

# Expected output

```
# pytest --collect-only
==== 123 selected, no tests ran in 1.66s ====
# pytest --collect-only -k filter
==== 123 selected, 544 deselected in 1.67s ====
```

# Details

Some feedback regarding the formatting of the summary when run in collection mode would be appreciated.

Example of how visible is the summary line versus the "collected" line, the one that usually gets lost in the terminal output. (`pco` is my alias for `pytest --collect-only`)
![](https://sbarnea.com/ss/Screen-Shot-2020-08-29-18-00-25.65.png)

**Comment by DahlitzFlorian** [comment]
@ssbarnea I'm totally with you and will have a look how to manage it properly.

**Comment by DahlitzFlorian** [comment]
@symonk feel free to take it!

**Comment by caramelomartins** [comment]
Hey,

I took a look into this and I believe I found where it needs changing, if possible. In `build_summary_stats_line` (https://github.com/pytest-dev/pytest/blob/master/src/_pytest/terminal.py#L1167) seems to be where the summary line is built before being printed out.

It essentially iterates a list of known types (https://github.com/pytest-dev/pytest/blob/master/src/_pytest/terminal.py#L58):

```
KNOWN_TYPES = (
    "failed",
    "passed",
    "skipped",
    "deselected",
    "xfailed",
    "xpassed",
    "warnings",
    "error",
)
``` 
As you can see, `selected` doesn't exist here but `deselected` exists. I believe there are no elements of total collection in the stats structure that is passed around in the code but we can probably infer the `collected` items by adding all the types that are not `deselected`.

Would this make sense?

**Comment by caramelomartins** [comment]
I ended up finding a way, by using `self._numcollected` and opened PR https://github.com/pytest-dev/pytest/pull/7875 with a potential fix for this issue.

**Comment by nicoddemus** [comment]
Hi @ssbarnea,

I've taken @caramelomartins' #7875 for a spin, and executing `pytest --co` in pytest itself we get:

```
$ pytest --co
=== 3005 selected, no tests ran in 3.81s ===

$ pytest --co -k integra
=== 30 selected, 2975 deselected, no tests ran in 1.65s ===
``` 

Which is in line with what you asked originally, but wouldn't be better to say *collected* instead of *selected*?

```
$ pytest --co
=== 3005 collected, no tests ran in 3.81s ===

$ pytest --co -k integra
=== 30 collected, 2975 deselected, no tests ran in 1.65s ===
``` 

We might even drop the phrase "no tests run", given that we explicitly say "collected" on the status message.

Thoughts?

**Comment by ssbarnea** [comment]
Super! I will look at it when i reach the big screen.

**Comment by caramelomartins** [comment]
I'm fine with removing the "no tests run" section, I understand how it is confusing. I really liked the compressed format of `=== 10/50 tests found (40 deselected) in 1.23s ===`, it seems to convey all the necessary information.

@nicoddemus do you like any of these options? I can reflect theses changes in the PR.

**Comment by nicoddemus** [comment]
Hey sorry for the delay.

> I really liked the compressed format of === 10/50 tests found (40 deselected) in 1.23s ===, it seems to convey all the necessary information.

I also like it, however I suspect `Testdir` might cause problems, it uses that string to parse the number of passes, failed, etc. 

So I would say go for the compact format, but if things get hairy, I suggest falling back to the more traditional format I posted.

**Comment by caramelomartins** [comment]
> Hey sorry for the delay.
> 
> > I really liked the compressed format of === 10/50 tests found (40 deselected) in 1.23s ===, it seems to convey all the necessary information.
> 
> I also like it, however I suspect `Testdir` might cause problems, it uses that string to parse the number of passes, failed, etc. 
> 
> So I would say go for the compact format, but if things get hairy, I suggest falling back to the more traditional format I posted.

No need to apologize. We are all busy. 😉

Okay, I'll update the PR accordingly and will let you know once it is updated with the new outputs. 👌

**Comment by caramelomartins** [comment]
I've implemented what was discussed in #7875 but I have a few corner cases that I thought would be interesting to discuss. While implementing this I came across the following questions:

- What happens if we collect 0 tests? It is outputting `0/0 tests found (0 deselected)` which is a bit weird. I would say that maybe `no tests collected` would be a more interesting option.
-  What happens if we deselected 0 tests? Currently, it echos `10/10 tests (0 deselected)` - adding `0 deselected` seems a bit redundant.
- What happens if there's an error? Currently there's no output about that, it just outputs `0/0 tests found (0 deselected)`. Should we do `X error(s)` instead?

Let me know what you think about these corner cases because I believe they would greatly improve the experience of using `pytest` if handled.

**Comment by caramelomartins** [comment]
> I've implemented what was discussed in #7875 but I have a few corner cases that I thought would be interesting to discuss. While implementing this I came across the following questions:
> 
>     * What happens if we collect 0 tests? It is outputting `0/0 tests found (0 deselected)` which is a bit weird. I would say that maybe `no tests collected` would be a more interesting option.
> 
>     * What happens if we deselected 0 tests? Currently, it echos `10/10 tests (0 deselected)` - adding `0 deselected` seems a bit redundant.
> 
>     * What happens if there's an error? Currently there's no output about that, it just outputs `0/0 tests found (0 deselected)`. Should we do `X error(s)` instead?
> 
> 
> Let me know what you think about these corner cases because I believe they would greatly improve the experience of using `pytest` if handled.

@nicoddemus and @ssbarnea, any thoughts on this?

**Comment by nicoddemus** [comment]
Hi @caramelomartins,

Thanks for the ping!

I agree with all your suggestions!

Initially I thought `RunResult.parseoutcomes` could be a problem, because it works by parsing the summary line, but I noticed it doesn't parse anything with `--collect-only` today:

```python
    def test_foo(pytester):
        pytester.makepyfile("""
            def test_foo():
                pass
            def test_bar():
                pass
        """)
        r = pytester.runpytest("--collect-only")
        assert r.parseoutcomes() == {}
```

So we are free to tweak that message at will. 👍 

Thanks again for the patience here on pursuing this.

**Comment by caramelomartins** [comment]
> I agree with all your suggestions!

Okay, I will update the PR accordingly with those suggestions.

> Thanks again for the patience here on pursuing this.

It is all fine. As a long time user of `pytest` I am happy to be able to contribute with something more substantial than documentation typos. 😉

**Comment by caramelomartins** [comment]
@nicoddemus I have updated PR #7875 and I believe it is ready for a proper review. :+1:
