### ISSUE TITLE
provide a way to ignore values from testing without using a reserved identifier

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#7726]
currently you can set `__test__ = False` on a test to have it not be collected.

https://docs.python.org/3/reference/lexical_analysis.html#reserved-classes-of-identifiers

> System-defined names, informally known as “dunder” names. These names are defined by the interpreter and its implementation (including the standard library). Current system names are discussed in the Special method names section and elsewhere. More will likely be defined in future versions of Python. **Any use of `__*__` names, in any context, that does not follow explicitly documented use, is subject to breakage without warning.**

I don't think pytest should be encouraging use of these names, except for nose compatibility

**Comment by graingert** [comment]
this could be done with a WeakSet:

```python
from typing import TypeVar
from collections.abc import Hashable

_NOT_TESTS = weakref.WeakSet()

_T = TypeVar("_T")

def not_a_test(v: _T) -> _T:
    try:
        _NOT_TESTS.add(v)
        return v
    except TypeError: # not weakrefable
        pass

    v.__test__ = False
    return v

@pytest.not_a_test
class TestFoo:
    return v
```

**Comment by graingert** [comment]
annoyingly WeakSet only supports hashable members, we'd have to roll our own identity-based WeakSet. But most classes and functions are already hashable.

**Comment by graingert** [comment]
someone might want to use `@not_a_test` outside a test file - without pytest installed, so we could provide a pypi package that pytest depends on, this would allow other frameworks to agree on objects that are not tests.

Otherwise we could try and get `__test__` reserved for this purpose in CPython

**Comment by asottile** [comment]
I think this is incredibly unlikely to conflict and doing work here would be unnecessarily tedious so I'm 👎 

`__test__` has been in use for decades

**Comment by The-Compiler** [comment]
Agreed - we need to keep `__test__` for nose compatibility anyways, so I'd rather just document that instead of adding another way to do the same thing.

On the other hand, Python [does already use `__test__` at module level for doctest](https://docs.python.org/3/library/doctest.html?highlight=__test__#which-docstrings-are-examined), so I wonder how (un)likely it really is for Python to start using it for other purposes on class-level as well.

**Comment by graingert** [comment]
not_a_test could be done in a collect plugin, so could be considered out of scope

**Comment by nicoddemus** [comment]
I'm also 👎 given the reasons stated above by @asottile and @The-Compiler. 

As @graingert comments, this also this can be done by a plugin if someone really wants this, so let's close it. 👍
