### ISSUE TITLE
document strict-config and other command line flags

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#7728]
I was recently asked to explain why I was adding `--strict-config` to a pytest ini, "as it appears to be undocumented"

currently command line flags are only documented in the changelog and https://docs.pytest.org/en/stable/_modules/_pytest/main.html

I think we should automatically add the output of `pytest --help` to the docs, eg here:
https://docs.pytest.org/en/stable/usage.html#getting-help-on-version-option-names-environment-variables

**Comment by Zac-HD** [comment]
Sounds good to me.  I've used [`sphinxcontrib-programoutput`](https://pypi.org/project/sphinxcontrib-programoutput/) for this before, if nobody has a better idea?

**Comment by The-Compiler** [comment]
If we just want the raw output: We already do use `regendoc` all over the docs, so without a good reason I don't think we should add yet another way to generate command output in the documentation.
