### ISSUE TITLE
Modular / recursive configuration with multiple pytest.ini in subfolders

### ISSUE THREAD

**Issue by waszil** [pytest-dev/pytest#7732]
Hi, i have been searching around about this, but could not find any info. My question is, is it possible somehow to use multiple pytest.ini files in subfolders? What I would like to achieve is that I have a package with several subfolders/subpackages that may contain python files that may contain test functions. These files may not have the `test_*.py` naming convention, so in these subfolders I create a pytest.ini file with a `python_files = my_file_pattern*.py` entry. Now, if I invoke pytest on the root level folder of my package, these pytest.ini files in the subfolders are not considered as I can tell. Is there any way to achieve something like this? Also, I could use this to specify different `filterwarnings` entries in different subfolders.
Thanks for any hints.

**Comment by graingert** [comment]
You can use https://docs.pytest.org/en/stable/reference.html#globalvar-collect_ignore_glob in a `conftest.py`

**Comment by waszil** [comment]
How would that help? I need the opposite, I don't want to ignore some files, I would like to additionally collect some. Meanwhile I have played around with `addinivalue_line('python_files', ...` in the `def pytest_configure` hook in conftest.py, but no luck.

**Comment by waszil** [comment]
Thanks. So I guess I would be better off by reorganizing the project and extracting all tests to a separate tests folder. However I still see this as a possible feature, because in our case it is a quite big codebase, and in this case it would be better to have the tests next to the actual modules, or even inside them.
