### ISSUE TITLE
logging only supports percent-style msg-formatting

### ISSUE THREAD

**Issue by htgoebel** [pytest-dev/pytest#7735]
pytest does not support str-formatting or string-templete formatting style of log messages. This is an issue if a program uses one of these formatting styles for logging.

Background:

Recent version of Python std-module `logging` implemented different formatting, esp. the "new" str-formatting style using `{}`.   This str-formatting style das the benefit of a smaller impact, since some more evaluation of logged elements (e.g. attribute access) could be postponed until the message is actually formatted. Also users get used to this style, thus we will see more str-formatted logging in the near future.

Example:
``` python
# script.py
import logging
logging.basicConfig(style="{")
logging.warning("holla: {} people found", 42)
```
``` python
# tests.py
def test1():
    import script
```
Run:
```
$ pytest test.py
… passes …
$ pytest test.py --log-cli-level=DEBUG
…
---------------------------------- live log call -----------------------------------
--- Logging error ---
Message: 'holla: {} people found'
Arguments: (42,)
```

pytest-5.0.1, pytest-6.0.1

**Comment by aklajnert** [comment]
Interesting, according to the [docs](https://docs.python.org/3/library/logging.html#logging.basicConfig), this was added in Python 3.2 but it doesn't seem to work. I've tested multiple interpreter versions, and I get a following error in every one of them:  

```python
Python 3.9.0rc1 (default, Sep  1 2020, 18:36:07)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(style="{")
>>> logging.warning("holla: {} people found", 42)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 659, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
Message: 'holla: {} people found'
Arguments: (42,)
```

I've never heard of this possibility before, am I missing some magic I need to perform before I try to use it?

**Comment by The-Compiler** [comment]
Running your `script.py` outside of pytest does not work either, as @aklajnert mentions. The `style` argument does not work like you think it does - it specifies how the `format` format string to `logging.basicConfig` (or a `logging.Formatter`) is handled, *not* how individual messages are logged. See [Using particular formatting styles throughout your application](https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles) in the Python docs for details:

> In Python 3.2, the Formatter gained a style keyword parameter which, while defaulting to % for backward compatibility, allowed the specification of { or $ to support the formatting approaches supported by str.format() and string.Template. **Note that this governs the formatting of logging messages for final output to logs, and is completely orthogonal to how an individual logging message is constructed.**

(emphasis mine)

Thus, I don't think there's anything for pytest to do here.
