### ISSUE TITLE
Can't update test case in running session

### ISSUE THREAD

**Issue by CerSU** [pytest-dev/pytest#7755]
I have run pytest.main() withThread triged by other thread, I find the test case can't update when I have changed the test case. I have used cache-clear , no effected.  maybe clear pytest session ?

class Tthread(Qthread):
   ....
     def run(self): 
           opt.append('--collect-only')
           pytest.main(opt,plugins=[self.plugin])

run = Thread()
run.start()  ---> output test case list  (mark 1)

time.sleep(20)  --> modified the test case before time out

run.start  --> output test case same as mark 1

- [x] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by RonnyPfannschmidt** [comment]
pytest uses normal python imports/modules (and wont relead already loaded ones) so if you run pytest twice in the same process, you will see such loading artifacts

in general the suggestion is, that if you have a permanent UI, pytest should be repeatedly run in subprocesses that communicate via ipc (for example the looponfail plugin does that)

**Comment by CerSU** [comment]
Good idea, Thanks!
