### ISSUE TITLE
Python -  initialize global variables in  "def __init__(self)" when using pytest

### ISSUE THREAD

**Issue by kartiktumu** [pytest-dev/pytest#7759]
In class, I declared a global variable "status" Later I used that variable in the first function "test_1", and assigned the value status=None

In the second function "test_481" I changed the value to that variable status=TRUE

Now again my focus came to the first function then I am still seeing status value as NONE, I am expecting value True here (how to do this?)

Please give a detail explanation (as I am still learning stage) with sample code.

class Test_Selenium():

 
    def __init__(self):
        self.status1 = None  # starting value

    def test_1(self):
        #Selenium driver logic
        
        if self.status1 == None:  # can also use if not self.status1:
            return self.test_481()
        elif self.status1 == True:
             print("User is asked for new authentication")

    def test_481(self):
        ##some logic##
        
        logic = True

        if (logic):  # must be true to set status1
            print("User authenticated - Passed")
            self.status1 = True
            #self.driver.quit()
            return self.test_1()  # recheck status

1. How to initialize global variables in  "def __init__(self)" when using pytest? Currently, I am seeing error as Process finished with exit code 5

Empty suite

**Comment by symonk** [comment]
IIRC each test gets its own instance of the class, status1 is also not a global.  I would highly recommend against this test dependence and calling tests from other tests, instead inject the data you need from a fixture and keep the tests independent, these can be written as two standalone test functions, there is no need to even use a class if you do not want/need too.

**Comment by gnikonorov** [comment]
> IIRC each test gets its own instance of the class, status1 is also not a global.  I would highly recommend against this test dependence and calling tests from other tests, instead inject the data you need from a fixture and keep the tests independent, these can be written as two standalone test functions, there is no need to even use a class if you do not want/need too.

+1 to this answer. It would be cleaner to use a fixture to setup and tear down data, and ideally tests should never depend on one another.

You can read up on fixtures [here](https://docs.pytest.org/en/stable/fixture.html)
