### ISSUE TITLE
parametrize with dict argvalues seems broken

### ISSUE THREAD

**Issue by viralmutant** [pytest-dev/pytest#7795]
Working with pytest version 4.5.0, there seems to be some inconsistency with dict argvalues in parameterize

    @pytest.mark.parametrize('ifgroup', [{'b': '2'}])
    def test_1(ifgroup):
        print(ifgroup)`

While this prints `{'b': '2'}`

If I make 'ifgroup' as a list, only the key 'b' is printed

    @pytest.mark.parametrize(['ifgroup'], [{'b': '2'}])
    def test_1(ifgroup):
        print(ifgroup)`

Referring to this [documentation ](https://docs.pytest.org/en/stable/reference.html#pytest.python.Metafunc.parametrize), I would expect both to behave alike

**Comment by viralmutant** [comment]
Maybe this issue is with single argname only ?

Observed something similar with tuple argvalue too, while the following works:
    @pytest.mark.parametrize('ifgroup', [('b', 2)])

If I were to enclose the `ifgroup` within list, I have to modify argvalue as:
    @pytest.mark.parametrize(['ifgroup'], [(('b', 2),)])

Similary, to pass dict argvalue to single arname as list:
    @pytest.mark.parametrize('ifgroup', [({'b': 2},)]

**Comment by asottile** [comment]
yeah parametrize has two different type-shapes

one of them is:

```
(str, Iterable[values for that arg])
```

the other is

```
(Iterable[str], Iterable[Tuple[of, the args]])
```

___

as for the docs, there's [this page](https://docs.pytest.org/en/stable/parametrize.html) which has one example using the first shape and [this page](https://docs.pytest.org/en/stable/example/parametrize.html#paramexamples) with multiple examples

**Comment by asottile** [comment]
note that your second form the `__iter__` of the `dict` is called giving you `('b',)` as your args tuple

**Comment by viralmutant** [comment]
> yeah parametrize has two different type-shapes
> 
> one of them is:
> 
> ```
> (str, Iterable[values for that arg])
> ```
> 
> the other is
> 
> ```
> (Iterable[str], Iterable[Tuple[of, the args]])
> ```

So basically mixing the two is wrong:
```
(Iterable[str], Iterable[values for that arg])
```
That wasn't clear from the API documentation

**Comment by asottile** [comment]
yeah the type annotation is very tricky for that one because you can also do `'comma,separated,string'` it seems -- if I were designing the api from scratch I wouldn't have allowed stringy lists but it's too late to break that backward compatibility now

A better way would be to represent it via overloads, but there's just no way to represent a type for a string with commas in it

**Comment by viralmutant** [comment]
Now that I have clarity on this, I'll close the bug.
Thanks
