### ISSUE TITLE
Pytest fails reimporting hypothesis.

### ISSUE THREAD

**Issue by charris** [pytest-dev/pytest#7810]
The NumPy CI tests fail if pytest is bumped from 6.0.2 to 6.1.0. The error message is
```
pytest.PytestAssertRewriteWarning: Module already imported so cannot be rewritten: hypothesis
```
See https://travis-ci.org/github/numpy/numpy/jobs/730868650 for an example. Note that NumPy fails on warnings. I also see this warning when running tests locally where it is ignored.

- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by asottile** [comment]
seems due to this line (the comment is incorrect here as the assertion rewriting happens at test time not at import time): https://github.com/numpy/numpy/blob/33e1dbee8d9e11a3e96efaae822ff6f3c44e3cef/numpy/_pytesttester.py#L143-L144

the warning is correct

**Comment by charris** [comment]
Any suggestions as to how we can avoid the warning? We could suppress it, but I'd rather get rid of it.

**Comment by asottile** [comment]
I don't know anything about configuring hypothesis but perhaps you can move that to your root `conftest.py`?

**Comment by Zac-HD** [comment]
Closing this as we're doing exactly that in https://github.com/numpy/numpy/pull/17776.
