### ISSUE TITLE
Pytest module scoped fixture with parameters and autouse does not work as intended

### ISSUE THREAD

**Issue by dillonm197** [pytest-dev/pytest#7812]
platform darwin -- Python 3.8.2, pytest-6.0.2, py-1.9.0, pluggy-0.13.1

I have a test file as follows:
```
import pytest


@pytest.fixture(scope='module', params=[True, False], autouse=True)
def a(request):
    a = request.param
    print(f'{a=}')
    return a


@pytest.fixture(scope='module')
def b():
    b = 1
    print(f'{b=}')
    return b


@pytest.fixture(scope='module')
def c():
    c = 1
    print(f'{c=}')
    return c


def test_a(b, c):
    assert b
    assert c
```

I expect that since the fixture `a` has `autouse` enabled and has parameters defined, that it causes all other fixtures that are referenced after it to get executed again without having to explicity reference it in each fixture definition.

**Expected Output:**
```
b=1
c=1
PASSED                                           [ 50%]
test_a.py::test_a[False] a=False
b=1
c=1
PASSED                                          [100%]
```

**Actual Output:**
```
test_a.py::test_a[True] a=True
b=1
c=1
PASSED                                           [ 50%]
test_a.py::test_a[False] a=False
PASSED                                          [100%]
```

**Comment by asottile** [comment]
I'm not sure why you expect fixture `a` to affect `b` or `c` -- could you point to documentation which indicates that?

there's nothing linking those fixtures at all so I expect them to be completely independent

**Comment by dillonm197** [comment]
If you use **function** scoped fixtures, `b` and `c` both get refreshed when switching parameters in `a`. When using `module` scope, the only fixture that is refreshed is `a` when the parameters switch.
```
import pytest


@pytest.fixture()
def b():
    b = 1
    print(f'{b=}')
    return b


@pytest.fixture(params=[True, False], autouse=True)
def a(request):
    a = request.param
    print(f'{a=}')
    return request.param


@pytest.fixture()
def c():
    c = 1
    print(f'{c=}')
    return c


def test_a(b, c):
    assert b
    assert c
```
Output:
```
test_a.py::test_a[True] a=True
b=1
c=1
PASSED                                           [ 50%]
test_a.py::test_a[False] a=False
b=1
c=1
PASSED                                          [100%]
```

**Comment by asottile** [comment]
function scoped fixtures are run once per function, since there are two invocations of the function you see two sets of fixtures
