### ISSUE TITLE
Plugin lookup in testdir-based test should be simpler

### ISSUE THREAD

**Issue by mcow** [pytest-dev/pytest#7825]
I have developed a plugin. The plugin gets initialized from command line options. I want to write a unit test to prove this. I am using the "pytester" `testdir` fixture for my test, and following [the documented example](https://docs.pytest.org/en/latest/writing_plugins.html#testing-plugins) as best I can.

My problem is that the test function in the temporary test directory is no longer able to locate the plugin in its source directory, in [the way](https://docs.pytest.org/en/stable/goodpractices.html#tests-outside-application-code) that tests in the project directory (parallel to the package) do. (Important to know: the package has not been "installed" in any way, not even editable.)

I would really like `testdir` to be smart about where the test originated and perform module lookup for import in the same way as tests within the project folder.

Also possibly important: we are currently using pytest 5.4.3 because of "an incompatibility" -- I don't know the exact details of this, but an in-house plugin that we are required to use does not work under current pytest.  I don't even know if there's a bug about that, but I can find details.

**Comment by mcow** [comment]
Attaching a code file that represents the problem, it doesn't run because I don't have time to put together a full working-but-not-working package for you.
[testdir-issue.zip](https://github.com/pytest-dev/pytest/files/5307226/testdir-issue.zip)

**Comment by mcow** [comment]
I'm willing to use workarounds. I've been trying to get `testdir.syspathinsert()` but I haven't had any luck giving it a string it likes.

**Comment by mcow** [comment]
Related: issue #2126

**Comment by mcow** [comment]
Following that issue's opening comment, I re-implemented using `inline_run()` and passing in an already-imported plugin name, as well as passing the command-line arguments in the call instead of creating the temporary conftest.py with fixtures to fudge that part. The test passes, and it's overall cleaner, so I'm happy enough with that; but the issue I reported is still an issue.

Two other things:

- documentation for testdir is really bad and it should be reorganized and made clear. (There is no online documentation for HookRecorder.)

- Also, `HookRecorder.assertoutcome()` vs `RunResult.assert_outcomes()`. How about aligning those? (How about deriving HookRecorder *from* RunResult instead of re-implenting?)

**Comment by asottile** [comment]
Is your plugin provided by a package? could you install that package? (perhaps with `pip install -e .`)
