### ISSUE TITLE
pytest 6.1.0 Sphinx build fails on Debian

### ISSUE THREAD

**Issue by Trophime** [pytest-dev/pytest#7827]
[sphinx-err-a0r2jt1j.log](https://github.com/pytest-dev/pytest/files/5314488/sphinx-err-a0r2jt1j.log)

- [x] a detailed description of the bug or problem you are having

Trying to update pytest package on Debian/Testing with python 3.8, I run into a problem while running the tests.
See the attached log file.

- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

**Comment by The-Compiler** [comment]
What are you running there exactly? That's not the testsuite, but Sphinx (the documentation generation) based on the output.

**Comment by Trophime** [comment]
I've read the log too quickly.
Indeed:
```
PYTHONPATH=/build/pytest-6.1.0/src \
	SPHINXBUILD=/usr/share/sphinx/scripts/python3/sphinx-build \
	/usr/bin/make -C doc/en man html
make[2]: Entering directory '/build/pytest-6.1.0/doc/en'
Running Sphinx v3.2.1
making output directory... done
loading intersphinx inventory from https://pluggy.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://pluggy.readthedocs.io/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='pluggy.readthedocs.io', port=443): Max retries exceeded with url: /en/latest/objects.inv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe83016ef10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.python.org/3/objects.inv' not fetchable due to <class 'requests.exceptions.ConnectionError'>: HTTPSConnectionPool(host='docs.python.org', port=443): Max retries exceeded with url: /3/objects.inv (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe83018e1f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
...
```

**Comment by Trophime** [comment]
Actually, it fails when trying to build the package as it is *forbidden* to download stuff when building the package.
A similar patch was applied in the previous version.
I will try to update the patch to account for the new value of `intersphinx_mapping` in doc/en/conf.py.

I think you can close this issue as it is debian related.
Best

**Comment by The-Compiler** [comment]
Alright, closing this then - thanks for the follow-up!
