### ISSUE TITLE
Update the default value of junit_family in docs

### ISSUE THREAD

**Issue by bluefish6** [pytest-dev/pytest#7858]
Hi, according to changelog, [this change](https://github.com/pytest-dev/pytest/pull/7660/commits/6ecbd008c417795a8a11563428d1706c4b4230f2) and [deprecation docs](https://docs.pytest.org/en/stable/deprecations.html#id10), the default junit_family config value is xunit2 (since pytest 6). However the [documentation](https://docs.pytest.org/en/latest/reference.html#confval-junit_family) still says that xunit1 is the default. 
Could you please update [the default version indication in docs](https://docs.pytest.org/en/latest/reference.html#confval-junit_family)?

**Comment by nicoddemus** [comment]
Thanks for catch that, indeed we missed it. 👍
