### ISSUE TITLE
Use `collections.Counter` instead of a `dict` in `terminal.py`

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#7868]
Consider the following code defining `counts`, and the similar [`counts_by_filename`](https://github.com/pytest-dev/pytest/blob/95917f8833bc71229c3ac4fb73cbf5ca5818201b/src/_pytest/terminal.py#L925-L928) below:

https://github.com/pytest-dev/pytest/blob/95917f8833bc71229c3ac4fb73cbf5ca5818201b/src/_pytest/terminal.py#L757-L760

This is a classic case for [`collections.Counter`](https://docs.python.org/3/library/collections.html#collections.Counter), and would make a great first pull request!

Example solution initialising the `Counter` from an iterable:

```python
counts = Counter(... for item in items)  # you fill in the ... part
```

**Comment by tanvimehta** [comment]
Hello! I'm new to the open source community. Is this something I can pick up and work on?

**Comment by Zac-HD** [comment]
Absolutely!  @-mention me from the PR and I'll be happy to review it for you  :smiley:

**Comment by tanvimehta** [comment]
Great! Will do. Thanks!
