### ISSUE TITLE
docs: Explain how to register multiple custom markers

### ISSUE THREAD

**Issue by lobsterkatie** [pytest-dev/pytest#7880]
In the [docs on registering markers](https://docs.pytest.org/en/latest/example/markers.html#registering-markers), it explains how to register a single custom marker but not how to register multiple custom markers.

It would be great if there were a sentence like, "To register multiple custom markers, put each one on its own line in your `pytest.ini` file," with or without an example.

**Comment by gutsytechster** [comment]
I'd like to resolve this issue. Can I take it up?
