### ISSUE TITLE
assert helper to compare list contents, ignoring order

### ISSUE THREAD

**Issue by soxofaan** [pytest-dev/pytest#7899]
I created this small pytest assert helper to compare lists/tuples ignoring item order:
https://gist.github.com/soxofaan/8e6512f765f0f0df697311c2561be57e

It's roughly `assert sorted(actual) == sorted(expected)`, but with some added benefits:

- container type (list vs tuple) is also checked
- inspired by `pytest.approx`, to make it more explicit what the intention of the comparison is. You only have to use it in the `expected` object, you can leave the `actual` object as is. It also works inside nested structures, e.g. 
    ```
    assert {"foo": [1, 2, 3]} == {"foo": IgnoreOrder([3, 2, 1])}
    ```

Would it be worthwhile to create a PR for this?

**Comment by nicoddemus** [comment]
I like the idea; often one goes and uses a `sorted()` call, but that's not ideal as it doesn't check the container type. Also using it inside nested structures is a plus.

Now to name shedding. 😁 

What should we call it? `pytest.anyorder`? 

What others think?

**Comment by nicoddemus** [comment]
Ahh indeed, we discussed this before and `pytest-unordered` was created because of that, although I'm not sure `pytest-unordered` also checks the types of the sequences being compared...

**Comment by soxofaan** [comment]
thanks for the reference

closing this one
