### ISSUE TITLE
a

### ISSUE THREAD

**Issue by travel2surf** [pytest-dev/pytest#7927]

**Comment by graingert** [comment]
@travel2surf why not try out our discussion forum? https://github.com/pytest-dev/pytest/discussions?discussions_q=category%3AGeneral

**Comment by The-Compiler** [comment]
Hey @travel2surf and welcome to GitHub! This repository is about a real project ([pytest](https://www.pytest.org/)) - please use a personal repository for testing things, as this repository is watched by ~200 people who'll get a notification for every change :wink:

@graingert The discussion forum isn't the right place for this either.
