### ISSUE TITLE
Multiple calls to the `pytest.main` API gives you the same results

### ISSUE THREAD

**Issue by joeyespo** [pytest-dev/pytest#793]
I'm using `pytest.main` in [a plugin](https://github.com/joeyespo/pytest-watch). It runs tests and uses Watchdog to listen for file changes. When a file changes, it runs `pytest.main` again.

Pytest seems to be using a cached version of the tests instead of re-running them with new results.

**Comment by hpk42** [comment]
pytest makes not attempt to unload the test and packaging modules which were imported during the test run.  It could probably do that, maybe there is a plugin already doing this.  But i usually consider it better for isolation to run tests in a subprocess which is what "pytest-xdist" is doing in its "loop-on-failure" mode.

**Comment by joeyespo** [comment]
Ok. Thank you, @hpk42 !
