### ISSUE TITLE
pytest - addopts - environment variables

### ISSUE THREAD

**Issue by nmt1** [pytest-dev/pytest#7932]
# description
I don't understand how I can change the addopts in  pytest.
I am not sure what is the approach, and can't find a clear/strict way within the pytest documentation. 

# content of pytest.ini
[pytest]
addopts = --strict

# content of conftest.py
exitfirst = os.getenv("env_exitfirst", "false")  # typically controlled via Jenkins

if exitfirst == "true":
**write --exitfirst to addopts?**

**Comment by symonk** [comment]
HI @nmt1 why not just specify the -x | --exit-first flag in the pytest.ini directly via addopts = --strict -x.  I would also like to point you to the --max-fail flag as thats possibly something of interest to you also (if you are in and around `exitfirst` behaviour.

Now if you must use the env vars via jenkins, this is available:

```
export PYTEST_ADDOPTS="-x"
```
