### ISSUE TITLE
testing: migrate pytest's own tests from the testdir fixture to the pytester fixture

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#7942]
pytest has many tests for testing itself, under the `testing/` directory in this repo. Many of the tests invoke `pytest` and check its output and outcomes. pytest provides a fixture called `pytester` which aids in this, you can find its documentation [here](https://docs.pytest.org/en/latest/reference.html#pytester).

The `pytester` itself is new in pytest 6.2 (unreleased yet when this is written), but its functionality is also provided by an older plugin called [`testdir`](https://docs.pytest.org/en/latest/reference.html#testdir). The two fixtures have almost the same API, the only difference is that `testdir` takes and returns `py.path.local` objects, while `pytester` is based on `pathlib.Path`, which we are trying to transition to.

Almost all of pytest's test are currently written using `testdir`. This issue is about migrating to use `pytester` instead. The instructions for converting are:

- Pick a file under `testing/` which uses `testdir`.
- Go over each test which uses `tesdir` and change it to `pytester`. Beyond just replacing the name, some adjustments *might* be needed for using `pathlib` Paths instead of `py.path.local` paths.
- Bonus points: add a type annotation for the `pytester` argument.

Example:

Before:

```py
def test_rootdir_wrong_option_arg(testdir):
    result = testdir.runpytest("--rootdir=wrong_dir")
    result.stderr.fnmatch_lines(
        ["*Directory *wrong_dir* not found. Check your '--rootdir' option.*"]
    )
```

After:

```py
# At this import at the top of the file.
from _pytest.pytester import Pytester

def test_rootdir_wrong_option_arg(pytester: Pytester) -> None:
    result = pytester.runpytest("--rootdir=wrong_dir")
    result.stderr.fnmatch_lines(
        ["*Directory *wrong_dir* not found. Check your '--rootdir' option.*"]
    )
```

**Comment by symonk** [comment]
Thanks @bluetech I will start with `testing/test_mark.py`

**Comment by nicoddemus** [comment]
> Should this be branched off somewhere else than master for 6.2? or be destined for somewhere else? (I assume master is ok for both).

Yes `master` is fine. 👍

**Comment by symonk** [comment]
`test_stepwise` next on the hit list, i've been refactoring the plugin so I want to follow up and port that over

**Comment by cmecklenborg** [comment]
I'm working on `test_setuponly` now, then will go back and try to finish `test_assertrewrite`

**Comment by pillemer** [comment]
Hi, I'd love to help here. I'm new to contributing so let me know if I should be doing anything differently.
I can do test_runner_xunit.py, if that's ok?

**Comment by symonk** [comment]
Thanks @pillemer & @cmecklenborg! (I had a skim of your branch @pillemer and it looks good for a PR) Welcome to the project!

**Comment by duthades** [comment]
I would like to contribute. I am working on ```testing/test_collection.py```.

**Comment by duthades** [comment]
Hi, I would like to contribute. I am working on ```testing/test_session.py```.

**Comment by itsmegarvi** [comment]
hi , I am a newbie , first time contributing . I would like to contribute to test_setupplan.py

**Comment by JosiasAurel** [comment]
Hi, I am new to contributions and will like to contribute to ```testing/test_faulthandler.py```

**Comment by JosiasAurel** [comment]
Here is [my PR](https://github.com/pytest-dev/pytest/pull/8019).

**Comment by locknic** [comment]
I am new to contributions and would like to contribute to `testing/acceptance_test.py`

**Comment by bot2x** [comment]
Hello people. Starting my journey of contributing to open source project here. I would like to contribute by working on test_warnings.py

**Comment by bluetech** [comment]
@bot2x Let us know if you need any help!

**Comment by bot2x** [comment]
> @bot2x Let us know if you need any help!

Thank you for being so welcoming. I made the necessary changes and have created a pull request - [https://github.com/pytest-dev/pytest/pull/8104#issue-533166082](here). I was not sure how else to reference it here.

**Comment by antonblr** [comment]
👋🏻  I would like to update`test_capture.py` and, perhaps `test_config.py`

**Comment by nicoddemus** [comment]
@antonblr please go ahead! I would suggest to start with the smallest one and open a PR with that. 👍

**Comment by bluetech** [comment]
I'm happy to say this issue is complete.

Thanks to all who contributed: @antonblr @bluetech @bot2x @cmecklenborg @crricks @duthades @itsmegarvi @JosiasAurel @locknic @nicoddemus @pillemer @proggga @symonk

It is very useful as a part of the effort the clean up the legacy `py.path` from pytest.

Hope to see you more in the future!
