### ISSUE TITLE
Docs typo

### ISSUE THREAD

**Issue by memee** [pytest-dev/pytest#795]
Hi,

If you look at the https://pytest.org/latest/goodpractises.html heading and the title (or https://github.com/pytest-dev/pytest/search?utf8=%E2%9C%93&q=practises), 
you see "Good integration **practises**"
IMHO it should be written **practice** for noun and **practise** for verb.
So "Good integration **practices**" would be better, I think.

**Comment by nicoddemus** [comment]
Would you care to open a PR? :smile:

**Comment by hpk42** [comment]
i fixed it already.
