### ISSUE TITLE
Failure when trying to call __repr__ because __iter__ is called?

### ISSUE THREAD

**Issue by Holt59** [pytest-dev/pytest#7966]
## 1. Problem

The following code 

```python
class A:
    def __iter__(self):
        raise ValueError()

    def __eq__(self, o: object) -> bool:
        return self is o


def test_a():
    assert A() == A()
```

...will throw:

```
    def test_a():
>       assert A() == A()
E       assert <tests.test_p...0019C132F1490> == <tests.test_p...0019C132F12B0>
E         (pytest_assertion plugin: representation of details failed: XXX\test_pp.py:3: ValueError.
E          Probably an object has a faulty __repr__.)
```

...because `__iter__` is called in order to `repr()` the object?

Is there a way to avoid `__iter__` being called when a test fails?

**Comment by RonnyPfannschmidt** [comment]
part of the assertion representation logic does try various things to tell more about the object

the isiterable helper unfortunately calls `__iter__` instead of just verifying its existence

it only checks for type-error, which doesn't account for broken implementations of iter

**Comment by RonnyPfannschmidt** [comment]
we should decide whether we want to uphold the invariant that iter calls should only raise type errors, or whether we need to do something better

in any case the error needs to be better

**Comment by Holt59** [comment]
Thanks, I actually did not think that there was some conventions about the type of exceptions being raised by special methods... 

I'm working on a custom interpreter for a different language, so I simply had a different `MyTypeError`. Making a kind of hybrid error inheriting both type errors actually fix the issue.

**Comment by RonnyPfannschmidt** [comment]
CC @nicoddemus after reviewing i beleive we shoudl add 2 additional failure modes

a) types that wrap data but dont proviede `__iter__` should diff a mu
ltiline repr
b) types that fail `__iter__` should be considered differently

```

In [1]: 
   ...: 
   ...: class A:
   ...:     def __iter__(self):
   ...:         raise ValueError()
   ...: 
   ...:     def __eq__(self, o: object) -> bool:
   ...:         return self is o
   ...: 

In [2]: 

In [2]: a = A()

In [9]: pprint.pformat(a)
Out[9]: '<__main__.A object at 0x7fab6fda9d30>'

In [10]: from _pytest.assertion.util import _pformat_dispatch

In [11]: _pformat_dispatch(a)
Out[11]: '<__main__.A object at 0x7fab6fda9d30>'

In [12]: 
```

i believe a better error should be triggered

**Comment by nicoddemus** [comment]
I agree with b), however I don't understand what you mean with a)... why use a multiline repr for types that _don't_ have a `__iter__` method?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i have some helper pbjects around that just wrap around other sutff

also openapi types dont necessarily iterate but have a nested multiline repr

**Comment by nicoddemus** [comment]
Hmm wait, I might be missing something, what do you mean by "multiline repr"? 🤔

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus any type where repr is either multiline on its own or by using something some `pprint.pformat`

**Comment by nicoddemus** [comment]
You mean calling `__repr__().split()` and see if there are more than one line, and treat that accordingly? I see.

**Comment by RonnyPfannschmidt** [comment]
Just use diff on it

**Comment by AIGeneratedUsername** [comment]
Hi, guys.

When a test fails, Pytest fails to print `repr()` for objects in a list. Example output:
```python
sample_users = [<[KeyError('is_adult') raised in repr()] SampleUser object at 0x7fa9fad23a00>, <[KeyError('is_adult') raised in repr()] SampleUser object at 0x7fa9fad23be0>]
```

My `SampleUser` is a 'pydantic' class, and `SampleUser.is_adult` is a class property. I do not know why Pytest fails to call `repr()`, because I can `repr()` manually in my code and all works fine.

Is it related to this issue, or I need to create a new one?
