### ISSUE TITLE
Changelog missing entries for 4.6.10/4.6.11

### ISSUE THREAD

**Issue by Hawk777** [pytest-dev/pytest#7967]
Go [here](https://docs.pytest.org/en/stable/changelog.html). The changelog does not show entries for 4.6.10 or 4.6.11. Pop up the version selector. If you choose `4.6.x` they are available, but none of the other major/minor pairs have a `.x` form, and if you choose `5.0.0`, then everything 4.6.4 and above disappears.

**Comment by nicoddemus** [comment]
Hi @Hawk777,

That's expected unfortunately due to the fact that `4.6.x` is frozen in practice and no longer part of the normal line of development.

Any suggestions on how we can increase visibility for that however? Perhaps a small note at the top of the current CHANGELOG along the lines of:

```
Note: looking for the changelog of the 4.6.x series? Please visit [this link].
``` 

?

**Comment by Hawk777** [comment]
Oh, I find it quite confusing, I thought the changelog in the master branch, or whatever is shown on the main website (without choosing a version), would contain all versions ever released. I’ve also seen some projects where each major has its own changelog, so there would be one file for all the 3.x, one for all the 4.x, one for all the 5.x, and so on. Maybe the note would help, yeah, it just seems weird that *some* of the 4.x would show up in the “main” changelog (from master branch I guess?) but not all of them.

**Comment by nicoddemus** [comment]
You are absolutely right it is weird. 😁 

Let's see if others have better suggestions.

**Comment by Hawk777** [comment]
Is it impractical to just add everything to the changelog file in the master branch?

**Comment by nicoddemus** [comment]
> Is it impractical to just add everything to the changelog file in the master branch?

Hmmm no, that's definitely possible. Let's do this manually and try to port the CHANGELOG entries for the next 4.6 releases then.
