### ISSUE TITLE
Using dict to provide ids for pytest.mark.parametrize

### ISSUE THREAD

**Issue by pepoluan** [pytest-dev/pytest#7977]
[As it is right now](https://docs.pytest.org/en/stable/example/parametrize.html#different-options-for-test-ids), to provide non-default test IDs when using `pytest.mark.parametrize`, one must use the `ids` keyword arg.

However, a thought occurred to me: What if we supply a `dict` to parametrize's argvalues, and from that dict, use the keys as the don-default test IDs?

For example, rather than:

```python
    @pytest.mark.parametrize(
        "command", [
            "RCPT",
            "RCPT <anne@example.com>",
            "RCPT TO:",
            "RCPT TO: <bart@example.com> SIZE=1000",
        ],
        ids=["noarg", "noto", "noaddr", "params"]
    )
```

we can supply it more succinctly like so:

```python
    @pytest.mark.parametrize(
        "command", {
            "noarg": "RCPT",
            "noto": "RCPT <anne@example.com>",
            "noaddr": "RCPT TO:",
            "params": "RCPT TO: <bart@example.com> SIZE=1000",
        }
    )
```

Users who absolutely need ordering can still use the first one, or use `OrderedDict` (or standard dict in Python>=3.7, where dict ordering became a language feature.)

**Comment by The-Compiler** [comment]
There isn't really an agreement on what dicts in parametrize should mean - see #7568 and related discussions.

Note that you can already use `pytest.param`:

```python
    @pytest.mark.parametrize(
        "command", [
            pytest.param("RCPT", id="noarg),
            pytest.param("RCPT <anne@example.com>", id="noto"),
            pytest.param("RCPT TO:", id="noattr),
            pytest.param("RCPT TO: <bart@example.com> SIZE=1000", id="params"),
        ],
    )
```

**Comment by seandstewart** [comment]
Popping in here to say I wrote a plugin which solves for this limitation as well after submitting my own issue (#10528): https://github.com/seandstewart/pytest-parametrize-suite

```python

@pytest.mark.suite(
    case1=dict(arg1=1, arg2=2),
    case2=dict(arg1=1, arg2=2),
)
def test_valid_suite(arg1, arg2):
    # Given
    expected_result = arg1
    # When
    result = arg2 - arg1
    # Then
    assert result == expected_result


@pytest.mark.suite(
    case1=dict(arg1="cross1"),
    case2=dict(arg1="cross2"),
)
@pytest.mark.suite(
    case3=dict(arg2="product1"),
    case4=dict(arg2="product2"),
)
def test_suite_matrix(arg1, arg2):
    # Given
    combination = arg1 + arg2
    # When
    possible_combinations.remove(combination)
    # Then
    assert combination not in possible_combinations


possible_combinations = {
    "cross1product1",
    "cross1product2",
    "cross2product1",
    "cross2product2",
}

```

Essentially, the top-level keyword argument is your test ID. Then you pass in a mapping of `{argname->argvalue, ...}`. 

The plugin does the work of validating that the structure of all the mappings for a given marker are the same structure, then translates it into the standard parametrize input and passes it on to metafunc.parametrize. 

All-in-all, it's fairly simple and naive, but it results in parametrized tests which are extremely easy to read, reason about, and maintain while providing a clean test output.

I don't say all this to advertise for myself. Rather, I think this interface is an improvement over the standard interface and would love to see a version of it accepted into pytest core. Until then, I have my plugin to bridge the gap.
