### ISSUE TITLE
Mocking __new__ breaks subsequent object creation

### ISSUE THREAD

**Issue by ymyke** [pytest-dev/pytest#8009]
Potential pytest bug (see also Comments section).

# Problem description

My goal is to patch a class' `__new__` method in order to control the exact object it creates in a test case. See the code below.

Each of the two tests `test_1` and `test_2` work as expected when run individually. When they are both run consecutively, however, `test_2` fails with:

`TypeError: object.__new__() takes exactly one argument (the type to instantiate)`

# Code

```python
import pytest


# The class to test:
class A:
    def __init__(self, x):
        self.x = x


def test_1(mocker):
    """First test patches the new method."""
    # Create object:
    a = A(x=3)
    # Make sure new method always returns this object:
    mocker.patch.object(A, "__new__", return_value=a)
    # Switch off the initializer (so it doesn't overwrite values in the pre-made object):
    mocker.patch.object(A, "__init__", return_value=None)
    # Do the test:
    res = A(x=1)
    assert res.x == 3


def test_2():
    """Second test uses the class as intended."""
    A(2)  # <- Fails (when run right after test_1)
```

# Comments

I'm not sure if this is really a pytest issue, since the problem also occurs even if I store away the original `__new__` method pointer and restore it at the end of `test_1`. Either way, I'd appreciate any help in finding out what is going on.

# Environment

* pytest             5.3.5
* pytest-mock        3.2.0
* pytest-socket      0.3.5
* pytest-sugar       0.9.4
* Python 3.7.5
* Windows 10

**Comment by RonnyPfannschmidt** [comment]
At first glance it looks like misuse of mocking, nothing pytest can do here

**Comment by ymyke** [comment]
Why is that a misuse? Any idea how I can achieve my goal in "legal" ways?

**Comment by ymyke** [comment]
BTW, it works if I change the class definition to this:

```python
class A(object):
    def __new__(cls, *_, **__):
        return super(A, cls).__new__(cls)

    def __init__(self, x):
        self.x = x
```

**Comment by RonnyPfannschmidt** [comment]
To figure the correct way I'd have to experiment, i would suggest to Patch `__call__` however
