### ISSUE TITLE
Doctest collection only returns single test for __init__.py

### ISSUE THREAD

**Issue by gatesn** [pytest-dev/pytest#8016]
`pytest --doctest-modules __init__.py` will only collect a single doctest because of this:

https://github.com/pytest-dev/pytest/blob/e986d84466dfa98dbbc55cc1bf5fcb99075f4ac3/src/_pytest/main.py#L768-L781

Introduced a while back by @kchmck here: https://github.com/pytest-dev/pytest/commit/5ac4eff09b8514a5b46bdff464605a60051abc83

See failing tests: https://github.com/pytest-dev/pytest/pull/8015

**Comment by spagh-eddie** [comment]
@gatesn can you please explain why and/or give a workaround?

**Comment by gatesn** [comment]
I think your expectation is right.

The bug in this issue was that if you had multiple doctests in the same __init__.py then only one of them would get picked up.

Perhaps the fix has introduced another issue whereby running against the init file now discovers tests in the entire package? Which I agree seems wrong.

**Comment by spagh-eddie** [comment]
Ah, thank you for the explanation. I thought that this explicitly intended to discover tests in the entire package! I will create a separate MRE since these are intended for different things.
