### ISSUE TITLE
Indirect parameterization doesn't get passed to fixture from an imported module

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pytest#8030]
### Description

I have a fixture that gets indirectly parameterized using `pytest.mark.parameterize()`.

When I import that fixture into another test module, and try parameterizing it from there, it doesn't work.

I have read through the docs in detail, and see nothing about this.

Take a look at the code sample below.  Am I doing something wrong, or is this not currently supported by pytest?

### Minimal Repro

`houses_fixture`:

```python
import pytest

class Config:
    """This is a configuration object."""

    def __init__(self, a: int, b: int):
        self._a = a
        self._b = b

@pytest.fixture
def config(a: int, b: int) -> Config:
    return Config(a, b)

class Bar:
    def __init__(self, config: Config):
        """This does some other behavior."""
        self.config = config

@pytest.fixture
def bar(config: Config) -> Bar:
    return Bar(config)

@pytest.mark.parametrize("a, b", [(1, 2)])
class TestBar:
    def test_bar(self, bar: Bar) -> None:
        """This runs fine."""
```

`imports_fixture`:

```python
import pytest

from .houses_fixture import bar, Bar

@pytest.mark.parametrize("a, b", [(1, 2)])
def test_something(bar: Bar) -> Bar:
    _ = 0
```

The output when running pytest on `imports_fixture`:

```none
In test_something: function uses no argument 'a'
```

It seems like the `imports_fixture` is not able to discern that an arg of `bar` needs to be parameterized.

If I comment out the parameterization line in `imports_fixture` and re-run, it outputs:

```none
test setup failed
file imports_fixture.py
  def test_something(bar: Bar) -> Bar:
file houses_fixture.py
  @pytest.fixture
  def bar(config: Config) -> Bar:
E       fixture 'config' not found
>       available fixtures: bar, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, spam, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

Next, I also import `config` into `imports_fixture`, even though it shouldn't need to be done.

```python
from .houses_fixture import bar, Bar, config
```

The new output:

```none
file imports_fixture.py, line 7
  def test_something(bar: Bar) -> Bar:
file houses_fixture.py, line 23
  @pytest.fixture
  def bar(config: Config) -> Bar:
file houses_fixture.py, line 12
  @pytest.fixture
  def config(a: int, b: int) -> Config:
E       fixture 'a' not found
>       available fixtures: bar, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, class_mocker, config, doctest_namespace, mocker, module_mocker, monkeypatch, package_mocker, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, session_mocker, spam, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

And at last we confirm that the parameterization doesn't make it to `config`.

### Versions

```
Python==3.8.6
pytest==6.1.1
```

**Comment by nicoddemus** [comment]
Hi @jamesbraza,

Sorry for the delay.

The example seems incomplete, I don't see a `parameterize_same_args` module. 

Regardless it is not recommended to import fixtures into other modules, put them in a `conftest.py` file instead: importing a fixture makes pytest thinks the fixture is defined in that module, which can cause problems when trying to match fixture definition location against test location.

**Comment by jamesbraza** [comment]
Ah sorry about that @nicoddemus, I had been playing around with a lot of stuff when making the minimal repro. I edited the original post, the `parameterize_same_args` was supposed to be `houses_fixture`.

---

### Updated Minimal Repro

I didn't know about the `conftest.py` stuff (thanks for the tip), so I decided to give it a whirl:

`conftest.py`:

```python
import pytest

from .houses_fixture import Config, Bar

@pytest.fixture
def config(a: int, b: int) -> Config:
    return Config(a, b)

@pytest.fixture
def bar(config: Config) -> Bar:
    return Bar(config)

```

`houses_fixture`:

```python
import pytest

class Config:
    """This is a configuration object."""

    def __init__(self, a: int, b: int):
        self._a = a
        self._b = b

class Bar:
    def __init__(self, config: Config):
        """This does some other behavior."""
        self.config = config

@pytest.mark.parametrize("a, b", [(1, 2)])
class TestBar:
    def test_bar(self, bar: Bar) -> None:
        """This runs fine."""

```

Aside: I'm impressed the `houses_fixture` pytest succeeds, it seems `conftest.py` can somehow dodge circular imports - nice!

`imports_fixture`:

```python
import pytest

from .houses_fixture import Bar

@pytest.mark.parametrize("a, b", [(1, 2)])
def test_something(bar: Bar) -> Bar:
    _ = 0

```

And now the test passes as intended.

---

### Thoughts

I see now that this suggestion is indirectly documented here: [`conftest.py`: sharing fixture functions](https://docs.pytest.org/en/6.1.1/fixture.html#conftest-py-sharing-fixture-functions)

@nicoddemus do you think there's an opportunity for better docs here?  If not, we can close this issue, and thank you again for answering.

**Comment by nicoddemus** [comment]
> @nicoddemus do you think there's an opportunity for better docs here?

I'm not sure, do you have any suggestions that would have made your life easier in the first place?

> If not, we can close this issue, and thank you again for answering.

Sure thing, glad I could help. 👍
