### ISSUE TITLE
pytest -s should not start the replay of std streams on the test name line

### ISSUE THREAD

**Issue by stas00** [pytest-dev/pytest#8047]
Please observe:
```
pytest -s test.py
================================================================ test session starts ================================================================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /mnt/nvme1/code/huggingface/transformers-master
plugins: hydra-core-1.0.3, cov-2.10.1, flake8-1.0.6, forked-1.3.0, xdist-2.1.0, instafail-0.4.2, ipynb-1.1.1.dev0
collected 1 item

test.py foo
bar
```

why does `-s` not start its std streams replay on a new line? For a while now it starts on the same line as the test name?
```
cat test.py
def test_noise():
    print("foo")
    print("bar")
```

The problem is that because of this behavior the first logged by the test entry often appears hidden, since it gets appended to the line with the test name.

Ideally the output should be:

```
test.py 
foo
bar
```

It still happens if I remove all of the pytest extensions, so it's a core issue.

Thank you!

**Comment by RonnyPfannschmidt** [comment]
The practical issue is that the terminalwriter is not integrated /aware of the general io

But for verbose test output we could change it a bit

**Comment by The-Compiler** [comment]
> why does `-s` not start its std streams replay on a new line?

Note that it doesn't *replay* anything - it just doesn't capture output at all. There's no way for pytest to know whether some output from the test will follow or not.

Like @RonnyPfannschmidt said, with `-v` there's the possibility for pytest to just output a newline after every test name if `-s` is enabled - but that'll then lead to rather ugly output when the test doesn't actually print anything, because the "PASSED" can't be on the same line as the test name anymore...

**Comment by stas00** [comment]
Thank you for clarifying how it works.

Since I generally use `-sv` that would definitely improve things - and I totally hear you that it'd improve things with something being logged, but make it worse for non-output tests. So that wouldn't be a good change.

This is perhaps a long shot but perhaps it could capture and replay the std streams? and then it could be aware of the output. Here it'd capture in the sense of `tee(1)` rather than pytest's capture mechanism. 

The only other thing I can think of is messing around with terminal and updating the test line with the test outcome by navigating back to the same line and updating it rather than straight `print`- like tqdm does.

**Comment by RonnyPfannschmidt** [comment]
Unfortunately that kinda replay is full of incredible tricky edge cases,
Personally I dare not to go that direction

Perhaps this is something for a library

**Comment by stas00** [comment]
Understood. 

Thank you for your feedback. 

It was useful to understand why it behaves in that way and the limitations around it.

**Comment by The-Compiler** [comment]
The whole point of `-s` is disabling the output capturing so that no capturing interferes with tricky edge cases. Perhaps you might want to use [live logging](https://docs.pytest.org/en/stable/logging.html#live-logs) instead, though I haven't used it myself so far.

**Comment by stas00** [comment]
I checked it out - thank you - I see this is specific for logging, so this won't work with normal std streams.
