### ISSUE TITLE
pytest result is not err msg, reulst is abort, don't know problem

### ISSUE THREAD

**Issue by bmh8993** [pytest-dev/pytest#8049]
- [x] a detailed description of the bug or problem you are having
run pytest, result abort msg
```python
@pytest.fixture
def access_db(db):
    pass

@pytest.fixture
def menu(access_db):
    for _ in range(10):
       mixer.blend(Menu)

    return Menu.objects.all()


@pytest.fixture
def admin(access_db):
    return mixer.blend(Admin, is_superuser=True, is_deleted=False)


def test_create_menu(menu):
    assert Menu.objects.count() == 10
```
<img width="714" alt="screenshot 2020-11-19 16 11 08" src="https://user-images.githubusercontent.com/45564139/99633188-d6556300-2a81-11eb-9142-0704c560d212.png">

```python
@pytest.fixture
def access_db(db):
    pass

@pytest.fixture
def menu(access_db):
    for _ in range(10):
       mixer.blend(Menu)

    return Menu.objects.all()


@pytest.fixture
def admin(access_db):
    return mixer.blend(Admin, is_superuser=True, is_deleted=False)


def test_create_menu(menu):
    admin = mixer.blend(Admin, is_superuser=True, is_deleted=False)
    assert Menu.objects.count() == 10
```
<img width="717" alt="screenshot 2020-11-19 16 12 21" src="https://user-images.githubusercontent.com/45564139/99633306-01d84d80-2a82-11eb-8567-0ba8eb778c6a.png">

The only thing that has changed is the new definition of the admin.

- [x] output of `pip list` from the virtual environment you are using
Package                       Version
----------------------------- -------------------
alabaster                     0.7.12
apiclient                     1.0.4
appdirs                       1.4.4
appnope                       0.1.0
attrs                         20.3.0
Babel                         2.9.0
backcall                      0.2.0
black                         19.10b0
cachetools                    4.1.0
certifi                       2020.6.20
cfgv                          3.2.0
chardet                       3.0.4
click                         7.1.2
coreapi                       2.3.3
coreschema                    0.0.4
coverage                      5.3
decorator                     4.4.2
distlib                       0.3.1
Django                        2.2
django-cors-headers           3.2.1
django-debug-toolbar          2.2
django-extensions             2.2.9
django-request-logging        0.7.2
djangorestframework           3.11.0
djangorestframework-jwt       1.11.0
docutils                      0.16
drf-yasg                      1.17.1
drf-yasg-examples             0.1.1
entrypoints                   0.3
Faker                         0.9.1
filelock                      3.0.12
flake8                        3.7.9
flex                          6.14.1
google-api-python-client      1.8.0
google-auth-httplib2          0.0.3
googleapis-common-protos      1.51.0
httplib2                      0.17.1
identify                      1.5.9
idna                          2.9
imagesize                     1.2.0
importlib-metadata            2.0.0
inflection                    0.5.1
ipdb                          0.13.4
ipython                       7.13.0
ipython-genutils              0.2.0
itypes                        1.2.0
jedi                          0.17.2
Jinja2                        2.11.2
jsonpointer                   2.0
MarkupSafe                    1.1.1
mccabe                        0.6.1
mixer                         6.1.3
mock                          4.0.2
mock-django                   0.6.10
more-itertools                8.6.0
nodeenv                       1.5.0
oauth2client                  4.1.3
packaging                     20.4
parso                         0.7.1
pathspec                      0.8.1
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           20.2.4
pluggy                        0.13.1
pre-commit                    2.2.0
prompt-toolkit                3.0.8
psycopg2-binary               2.8.5
ptyprocess                    0.6.0
py                            1.9.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.5.0
pyflakes                      2.1.1
Pygments                      2.7.2
PyJWT                         1.7.1
pyparsing                     2.4.7
pytest                        5.4.3
pytest-cov                    2.10.1
pytest-django                 3.10.0
python-dateutil               2.8.1
python-jsonrpc-server         0.4.0
python-language-server        0.36.1
pytz                          2020.4
PyYAML                        5.3.1
regex                         2020.11.13
requests                      2.23.0
rfc3987                       1.3.8
rsa                           4.0
ruamel.yaml                   0.16.12
ruamel.yaml.clib              0.2.2
setuptools                    50.3.1.post20201107
six                           1.15.0
snowballstemmer               2.0.0
Sphinx                        3.1.1
sphinx-rtd-theme              0.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
sqlparse                      0.4.1
strict-rfc3339                0.7
text-unidecode                1.2
toml                          0.10.2
traitlets                     5.0.5
typed-ast                     1.4.1
ujson                         4.0.1
uritemplate                   3.0.1
urllib3                       1.25.9
validate-email                1.3
virtualenv                    20.1.0
wcwidth                       0.2.5
wheel                         0.35.1
zipp                          3.4.0
- [x] pytest and operating system versions
python==3.7.9
pytest==5.4.3
- [x] minimal example if possible

**Comment by asottile** [comment]
`abort` is a C level failure -- you're also not showing us all the code, what is `Menu` or `mixer` or anything?  could you try debugging this in `gdb` (`gdb python` and then `run -m pytest tests`) and getting a backtrace (`bt`)?

**Comment by bmh8993** [comment]
> `abort` is a C level failure -- you're also not showing us all the code, what is `Menu` or `mixer` or anything? could you try debugging this in `gdb` (`gdb python` and then `run -m pytest tests`) and getting a backtrace (`bt`)?

Oh, my mistake
```python
import pytest

from rest_framework import status
from rest_framework_jwt.settings import api_settings
from django.urls import reverse
from mixer.backend.django import mixer

from admins.models import Admin
from menu.models import Menu
from menu.api.serializers import MenuSerializer
```
@asottile

**Comment by The-Compiler** [comment]
With a bit of luck, running with `-s` (disabling pytest's output capturing) will give you some sort of error message before the abort.

**Comment by bmh8993** [comment]
oh thx! I resolved this problem!
I guess, User Model that django provide can't use mixer pkg.
raise `recursionerror maximum recursion depth exceeded while calling a python object`
so, I use factory-boy for User Model.
