### ISSUE TITLE
pytest.mark.parametrize fails with pyright (when using strict type checking mode)

### ISSUE THREAD

**Issue by renzhentaxi** [pytest-dev/pytest#8053]
This is very similar to the mypy issue #7589. 
It appears that pyright is not able to recognize the type for pytest.mark.parametrize at all

  3:2 - error: Type of "parametrize" is unknown (**reportUnknownMemberType**)
  3:2 - error: Untyped function decorator obscures type of function; ignoring decorator (**reportUntypedFunctionDecorator**)

setup:
os: linux
python 3.8.5,
pytest 6.1.2
pyright 1.1.86

piplist:
```
➜  test pip list
Package           Version
----------------- -------
astroid           2.4.2
attrs             20.1.0
iniconfig         1.0.1
isort             5.4.2
lazy-object-proxy 1.4.3
mccabe            0.6.1
more-itertools    8.4.0
packaging         20.4
pip               20.2.4
pluggy            0.13.1
py                1.9.0
pylint            2.6.0
pyparsing         2.4.7
pytest            6.1.2
setuptools        47.1.0
six               1.15.0
toml              0.10.1
wrapt             1.12.1
```
pyrightconfig.json:
```json
{
	"typeCheckingMode": "strict",
	"reportUnusedVariable": "information"
}

```
code:
```python
import pytest

@pytest.mark.parametrize("param", ["dog", "cat"])
def test_sample(param: str):
    assert False
```
I will create an issue on pyright's repo as well

**Comment by asottile** [comment]
`parametrize` is typed, I'd suggest you re-raise this with the pyright people: https://github.com/pytest-dev/pytest/blob/afd53ede6f3c950df3bfc9e81afdd45e09ef6d2b/src/_pytest/mark/structures.py#L422-L437

**Comment by symonk** [comment]
Response from pyright:

```
This is a problem with the pytest package. It claims to be typed (i.e. it contains a "py.typed" file), but it includes some variables that are not annotated. The parametrize variable is one such example. As such, pyright is treating it as an "unknown" type.
```

https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md would be a starting point to resolving this potentially

**Comment by bluetech** [comment]
I replied in the pyright issue.

**Comment by bluetech** [comment]
So in pytest 6.2 we've changed the typing of `pytest.mark.parametrize` a bit (from variable assignment to variable annotation) which should resolve this issue for pyright, so I'll close this issue, but we can reopen it if it actually doesn't.
