### ISSUE TITLE
Pytest doesn't accept the python logging

### ISSUE THREAD

**Issue by h-rueda** [pytest-dev/pytest#8083]
Pytest doesn't take into account the Python logging commands.

For example, Pytest doesn't execute the following:

`import logging`
`logging.basicConfig(filename='example.log', level=logging.DEBUG)`
`logging.debug('This message should go to the log file')`

**Comment by prakhargurunani** [comment]
@h-rueda You can directly use Python's default `logging` module to log to a file, but before that, you will have to setup [Live logs](https://docs.pytest.org/en/stable/logging.html#live-logs) and make necessary configuration in `tox.ini` to make `logging.debug` work.

**Comment by nicoddemus** [comment]
Just to complement @prakhargurunani's response, Live logs are optional, but you do need to tell pytest which logs should be captured using `--log-level` or `log_level`. 

Closing for now, but if you are still having problems @h-rueda please post a follow up showing some more code and what what you expected to see so we can help out in more detail. 👍

**Comment by h-rueda** [comment]
@nicoddemus Thank you for the tip. The right switch is `--log-level`.

I am still having issues with the logging, though.

Here is my code:
```
fmt = '%(levelname)s - %(filename)s - %(funcName)s - %(lineno)s - %(message)s'
logging.basicConfig(filename='app.log', filemode='w', format=fmt, level=logging.DEBUG)
	
def test_f() :
	logging.debug('This will get logged')
```

The result I am having:

1. The logs are send to stdout instead of app.log file
2. The log format (**fmt** variable) is not taken into account

Putting the first two lines of code inside **test_f** didn't change anything.

Any tips ? :)

**Comment by h-rueda** [comment]
Thank you @nicoddemus 

It worked out well with this options
`--log-level=DEBUG --log-file="app.log" --log-file-format="%(filename)s %(funcName)s:%(lineno)s - %(message)s"` 

I do have 2 questions:

1. Is there a way to put those options in a fixture instead of putting them as line command options ?
2. The logs are send to both the stdout and the **app.log** file. Is there a way to send the logs to the file only ?

Thanks in advance
