### ISSUE TITLE
Pytest unable to execute files with same name in different folders

### ISSUE THREAD

**Issue by h-rueda** [pytest-dev/pytest#8084]
Hello,

Pytest has a conflict when there are two files with the same name in different folders.
I have the following folders and files:

parent
parent / folder1
parent / folder1 / my_test.py
parent / folder2
parent / folder2 / my_test.py

I have two different `my_test.py` files in two different folders.

When I execute Pytest from `parent` , I get:

`imported module 'my_test.py' has this __file__ attribute:`
`/parent/folder1/my_test.py`
`which is not the same as the test file we want to collect:`
`/parent/folder2/my_test.py`
`HINT: remove __pycache__/ .pyc files`

I suppose this is due to the way how Pytets manages the rootdir ?
[https://docs.pytest.org/en/stable/pythonpath.html](https://docs.pytest.org/en/stable/pythonpath.html)

**Comment by h-rueda** [comment]
I realized that including `__init__.py` files in both `folder1` and `folder2` solves this issue.

**Comment by The-Compiler** [comment]
Also see the ["Good Integration Practices" docs](https://docs.pytest.org/en/stable/goodpractices.html#tests-outside-application-code) explaining why this happens at what you can do about it.
