### ISSUE TITLE
Bug: Targeted tests imports uninvolved files during collection

### ISSUE THREAD

**Issue by lmeyerov** [pytest-dev/pytest#8093]
When running a command like `python -m pytest test/some/file.py -k test_something`, we expected only `pytest test/some/file.py` to have its imports get run. While the collector indeed only selects tests from `file.py`, the collection / startup process appears to collect files that aren't `file.py`,  runs Python's `import` on them, and then deselects them. 

The excess imports are surprising in a few ways:

* semantics: python imports can have side-effects, which makes debugging bugs harder when the execess imports occur
* slow python test imports: Importing all pytest files can be heavy
* slow python test dependency imports: pytest files likely import the files they're testing, so add the weight of the full app

Working around via lazy loaders is difficult. For projects with many tests/files or running in containers with virtualized IO, the problem gets exacerbated.

The excess imports seems like a bug based on the CLI interface -- running imports is semantic, not just performance. However, changing that can be a vastly breaking change, so I can imagine doing some sort of flag to avoid breaking existing code..

## Reproduction

```bash
find .
#test/
#  some/
#    - test_file.py
#  slow_if_python_imports_each/
#      - test_file2.py
#      ...
#      - test_file100.py

cat test/some/test_file.py
#def test_something():
#    pass

cat test/slow_if_python_imports_each/test_file2.py
#print('I should not be imported')

python -m pytest test/some/test_file.py -k test_something
# I should not be imported
```

The expectation is `"'I should not be imported"` does not get printed

**Comment by The-Compiler** [comment]
I can't reproduce:

```console
$ find test/ -type f
test/slow_if_python_imports_each/test_file2.py
test/some/test_file.py

$ cat test/slow_if_python_imports_each/test_file2.py
print('not imported')

$ cat test/some/test_file.py
def test_something():
    pass

$ python -m pytest test/some/test_file.py -k test_something 
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/florian/proj/pytest, configfile: pyproject.toml
collected 1 item                                                               

test/some/test_file.py .                                                 [100%]

============================== 1 passed in 0.01s ===============================
```

**Comment by lmeyerov** [comment]
@The-Compiler  Hmm, will reexamine reproduction, thanks. Scenario was carved from a hairy env, apologies.

**Comment by lmeyerov** [comment]
@The-Compiler We indeed worked on extracting further to an issue on our side:

a test with `import x.y.z` would pull in `x.a.b` when  file `x/__init__.py`  had `import .a.b` 

So safe to close
