### ISSUE TITLE
Pytest does not show path name in verbose output for Pathlib objects

### ISSUE THREAD

**Issue by thorstenkampe** [pytest-dev/pytest#8118]
- [x] a detailed description of the bug or problem you are having
- [x] pytest and operating system versions: pytest 6.1.2 on Windows 10
- [x] minimal example if possible

Not one hundred percent sure if a bug report or a feature request: Pytest shows "file1" in verbose output when the parameter is a pathlib object.

* actual output: `file1`
* expected output: `test2.txt` (`str(file1)`)

Below output demonstrates the desired output (`test1.txt`) and the faulty one (`file1` instead of `test2.txt`)

``` python
import pathlib
import pytest

filelist = ['test1.txt', pathlib.Path('test2.txt')]

@pytest.mark.parametrize('file', filelist)
def test_runscript(file):
    assert True
```

```
> pytest -v -p no:sugar .\test_path.py
================================================================= test session starts =================================================================
platform win32 -- Python 3.9.1, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- F:\scoop\apps\miniconda3\current\envs\main\python.exe
cachedir: .pytest_cache
rootdir: F:\cygwin\home\thorsten\bin\source, configfile: pytest.ini
collected 2 items

test_path.py::test_runscript[test1.txt] PASSED  # GOOD!                                                                                                 [ 50%]
test_path.py::test_runscript[file1] PASSED      # BAD!                                                                                                  [100%]
                             ~~~~~

================================================================== 2 passed in 0.03s ==================================================================

**Comment by RonnyPfannschmidt** [comment]
Good catch, this is also a nice first issue

**Comment by nicoddemus** [comment]
Hmmm but should it? Using full paths for example wouldn't make the node id too long/unwieldy?

**Comment by RonnyPfannschmidt** [comment]
Full path as Id does the same

We can't guess how to correctly shorten, but we can make most cases look better

For pathological cases people can use the callable or explicit ids

**Comment by nicoddemus** [comment]
> Full path as Id does the same

Sure, but that's just a string as far as pytest is concerned... however full paths are probably not that common anyway in parametrization. Btw I was just wondering, not opposing the idea. 😁

**Comment by RonnyPfannschmidt** [comment]
As paths may be relative, i believe it's fine

**Comment by matthewhughes934** [comment]
Hi, I'm interested in tackling this as a first (non-docs related) issue. After a quick browse of the code: would this just require adding handling for `pathlib.Path` objects when building ids for parametrization args?

**Comment by RonnyPfannschmidt** [comment]
Correct

**Comment by matthewhughes934** [comment]
> Correct

Thanks I gave this a shot with #8176

**Comment by bluetech** [comment]
We've decided not to change this, see discussion in #8176. The alternative is to use a string for the parameter, or to set an explicit id using `pytest.param`.
