### ISSUE TITLE
PytestConfigWarning: Unknown config option: expected_results_path

### ISSUE THREAD

**Issue by abhayp505** [pytest-dev/pytest#8140]
Hi,

I am getting a warning while running pytest please find the details below.
The Test is executed and running fine but following warning is thrown

```
env/lib/python3.7/site-packages/_pytest/config/__init__.py:1230:
 PytestConfigWarning: Unknown config option: expected_results_path
  
 self._warn_or_fail_if_strict("Unknown config option: {}\n".format(key))
```

Python version:- Python 3.7.3

Please find the configuration details:

```console
(env) bash-3.2$ pip freeze
attrs==20.3.0
certifi==2020.12.5
chardet==3.0.4
flaky==3.7.0
idna==2.10
importlib-metadata==3.1.1
iniconfig==1.1.1
jsonschema==3.2.0
nose==1.3.7
nose-testconfig==0.10
packaging==20.7
parameterized==0.7.4
pluggy==0.13.1
psycopg2-binary==2.8.6
py==1.9.0
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.1.2
requests==2.25.0
selenium==3.141.0
six==1.15.0
toml==0.10.2
urllib3==1.26.2
zipp==3.4.0
```

**Comment by nicoddemus** [comment]
Hi, 

You seem to have an `expected_results_path` option declared in your configuration file that is not being used by any plugin, hence the warning.

**Comment by AaronStiff** [comment]
I seem to be having the same issue. Is the solution to modify the `expected_results_path` options, and if so, could you explain where to find this?

**Comment by RonnyPfannschmidt** [comment]
@AaronStiff in your case it seems to  be that the pytest-doctestplus plugin is missing

**Comment by AaronStiff** [comment]
Hm. Okay, so I just installed `pytest-docstringplus` using `pip`, but I'm still getting that warning. Perhaps there's something with `pytest-doctestplus` I have to configure?

**Comment by RonnyPfannschmidt** [comment]
im unaware of more details - i don't use doctestplus

**Comment by AaronStiff** [comment]
No problem. It's not obtrusive, and I can work around it with `--disable-warnings`

**Comment by zwl1995-54** [comment]
解决了吗
