### ISSUE TITLE
passing functions to indirect parametrization instead of string

### ISSUE THREAD

**Issue by Vert53** [pytest-dev/pytest#8146]
#### What's the problem this feature will solve?
Currently when parametrizing a test indirectly through fixtures, the name of the fixture that the parameters will be passed to is specified as a string. For example:
```
@pytest.mark.parametrize(
    "my_fixture",
    [
        ("param", 2),
    ],
    indirect=True)
class TestFoo:
    pass

```
This approach is problematic because IDE's can't find usages of fixtures when these are passed as strings.
Also IDE's can't notice if the fixture's name is passed incorrectly.

#### Describe the solution you'd like
I propose to allow the parametrize method to receive function objects who's name can be retrieved internally in parametrize with the .____name____ attribute of functions. Example:
```
@pytest.mark.parametrize(
    my_fixture,  # this time the function itself is passed
    [
        ("param", 2),
    ],
    indirect=True)
class TestFoo:
    pass

```

Waiting for feedback so I could perhaps implement this feature.

Thanks,
Vert

**Comment by RonnyPfannschmidt** [comment]
currently fixture declarations are not symbolic and location-bound, as such its at least a breaking change, if not a major refactoring to properly introduce this

that being said, i'd like the fixture system to move to that direction, its just not clear to what changes/breakages are required to go there

**Comment by Vert53** [comment]
I am not fully aware of all the details but my understanding is that if my fixture is in a different file (say conftest.py) I can import the fixture and then pass it like in my last comment. This is mostly syntactic and good for static code checks and code navigation.
Shouldn't break the current method of passing strings.

**Comment by RonnyPfannschmidt** [comment]
Importing fixtures means there are multiple definitions for the fixture at each import site, this creates trouble for scopes

**Comment by Zac-HD** [comment]
Closing this per https://github.com/pytest-dev/pytest/issues/12465#issuecomment-2175596712
