### ISSUE TITLE
Is slash `/` a reliable character to indicate a fixture union alternative test id in pytest-cases

### ISSUE THREAD

**Issue by smarie** [pytest-dev/pytest#8157]
Dear pytest maintainers, in [`pytest-cases`](https://smarie.github.io/python-pytest-cases/) as you know I extend the "cross-product" parametrization engine of pytest so that it becomes a tree of independent cross-products, each path in the tree being a combination of fixture alternatives and having its own fixture closure. (see [more detailed explanation here](https://smarie.github.io/python-pytest-cases/unions_theory/))

I recently was challenged by users to simplify the generated test ids. I think that I found a [reasonably elegant solution](https://github.com/smarie/python-pytest-cases/issues/154#issuecomment-743322696). It relies on a special character indicating that a given parameterset is a fixture alternative. For now I use special character `/`, as I find it intuitive to indicate that this goes into a sub-branch of the fixture closure tree. 

However I just noticed that this character is transformed by `pytest` into a backslash `\` for display. Is this the only side-effect or is there any other I should know about ?

Thanks a lot for your feedback !

**Comment by RonnyPfannschmidt** [comment]
Off hand I'd think it's just path display bug, i intend to turn test ids into a more complex object soonish

**Comment by smarie** [comment]
Thanks @RonnyPfannschmidt . Ok, then I'll release version 2.8.0 with this character, and if this becomes a forbidden character let me know! Of course if the display can be fixed in the future that can be even better, but this is non-blocking for me. The only side-effet of current behaviour for users of `pytest-harvest` or similar plugin is that they see `/` in the fixture collecting the test results, but see `\` in the console display and IDE (PyCharm, etc.). Not a big deal I guess.

**Comment by Zac-HD** [comment]
Closing as answered 👍
