### ISSUE TITLE
Inspecting the signature for determining fixtures should not follow wrapped functions

### ISSUE THREAD

**Issue by plammens** [pytest-dev/pytest#8164]
In Python >= 3.5, test functions decorated with something that uses `functools.wraps` will be used with the original signature instead of the decorated signature, which shouldn't be the case. This can make pytest think some of the arguments appearing in the original signature are fixture requests while they are not because they're just used by the decorator.

## Minimal example

```python
import functools
import pytest


def decorator(f):
    @functools.wraps(f)
    def decorated(a, b):
        return f(a, b, a + b)

    return decorated


@pytest.fixture
def a():
    return 1


@pytest.fixture
def b():
    return 2


@decorator
def test_foo(a, b, a_plus_b):
    assert a + b == a_plus_b
```

(Note: this isn't a sensible use of a decorator in this scenario, it's just to show an example.)

**Expected:** the (decorated) `test_foo` function is invoked with `a=1` and `b=2`, and the test passes.

**Actual:**
```none
test setup failed
file ...
  def test_foo(a, b, a_plus_b):
E       fixture 'a_plus_b' not found
>       available fixtures: a, b, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, extra, fixture_store, include_metadata_in_junit_xml, metadata, module_results_dct, module_results_df, module_results_df_steps_pivoted, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, results_bag, session_results_dct, session_results_df, session_results_df_steps_pivoted, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

----------------------------------

## Cause

In `getfuncargnames`, the call to `inspect.signature` should pass `follow_wrapped=False` to avoid getting the signature from the wrapped function instead of the wrapper (which might have a different signature):

https://github.com/pytest-dev/pytest/blob/f61d4ed9d587575fd20ee5ece1674ddc3088ee2a/src/_pytest/compat.py#L143

should be `parameters = signature(function, follow_wrapped=False).parameters`.

**Comment by plammens** [comment]
Ah, I see this conflicts with #217 and the tests added in dba2a8bc. However, those tests seem to be testing for something broader than being able to use `unittest.mock.patch`, indeed they're testing the exact opposite of what I am requesting in this issue? As stated in #217 this is an issue with `patch` not showing the appropriate signature, not an issue with wrapping test functions. Can these two things be reconciled? Maybe we can do as I proposed above but add a special case for `patch`?

For now users should do `del decorated.__wrapped__` in the decorator if they want a decorator as shown above to work with pytest.

**Comment by RonnyPfannschmidt** [comment]
the decorator should assign a fixed signature if it changes the signature

**Comment by RonnyPfannschmidt** [comment]
https://www.python.org/dev/peps/pep-0362/#visualizing-callable-objects-signature has a example of a signature fixing decorator
