### ISSUE TITLE
CI builds are failing with "IS_WINDOWS is not defined" error

### ISSUE THREAD

**Issue by antonblr** [pytest-dev/pytest#8170]
e.g. see https://github.com/pytest-dev/pytest/runs/1571751504
```
Run actions/setup-python@v2
  with:
    python-version: pypy3
    token: ***
Error: IS_WINDOWS is not defined
```

This is a known issue with the latest `setup-python` release - https://github.com/actions/setup-python/issues/171

A temporary  workaround would be to pin GH action version to the latest stable (`v2.1.4`).  I'll open a PR, but let's keep this issue open until `actions/setup-python` is fixed to revert the change.

**Comment by hugovk** [comment]
Looks like the fix has been released now, want to retry?

**Comment by asottile** [comment]
via #8171 / #8172
