### ISSUE TITLE
[infra] enable pre-commit.ci?

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#8186]
(internal issue)

I've been working on this for the last ~6 months or so and I think it's usable enough for pytest: https://pre-commit.ci

I wanted to make sure we had a discussion first before flipping it on though :)

Basically it will get us:
- a freed up CI worker
- autofixing of PRs (especially useful for the many drive-by PRs we get that don't set up the linting and/or commits that are made from the github UI)
- periodic autoupdate of the pre-commit configuration
- ~20 lines of github actions configuration _removed_
- much faster linting runs (a cold test run I just did was 1:40 vs 2:53 on github actions -- with everything cached it's ~1:10 and will only get faster as I make some planned improvements)

To enable, we'd just add the pytest repo to the pre-commit.ci app installation (it appears it's already installed on [pytest-randomly](https://results.pre-commit.ci/repo/github/55790864))

**Comment by nicoddemus** [comment]
Sure, sounds great, 👍 from me. 😁

**Comment by symonk** [comment]
@asottile  sounds good :) been watching the streams a lot & the tool seems to be coming along nicely!

**Comment by bluetech** [comment]
Seems like it's active now, and indeed faster than the github actions `linting` job. Is the next step to remove `linting` from the github actions?

**Comment by asottile** [comment]
yep!  assuming we're happy with it

**Comment by RonnyPfannschmidt** [comment]
Should we award a reasonable amount of the tidelift/open collective money towards precommit.ci i feel its warranted as its not marketing infra like github actions and @asottile is proving a great value add there

**Comment by RonnyPfannschmidt** [comment]
My assumption being that the time of the aws infra is pennies anyway and utterly swift well working infra deserves a sweet margin to begin with

**Comment by nicoddemus** [comment]
> Should we award a reasonable amount of the tidelift/open collective money towards precommit.ci i feel its warranted as its not marketing infra like github actions and @asottile is proving a great value add there

👍 from me. @asottile let us know once you have pricing setup.

**Comment by symonk** [comment]
@asottile can we close this one out? seems to be implemented! :)

**Comment by asottile** [comment]
this part isn't completed yet: https://github.com/pytest-dev/pytest/issues/8186#issuecomment-751352830

**Comment by nicoddemus** [comment]
👍 from me to remove the linting job from there now. Seems to be working perfectly, both here and everywhere else I turned it on. 😁

**Comment by bluetech** [comment]
In preparation, I changed `master`'s required check from `linting` to `pre-commit.ci - pr`, hopefully that's the right one.
