### ISSUE TITLE
Allow to disable automatic replacement of the nodes

### ISSUE THREAD

**Issue by bubenkoff** [pytest-dev/pytest#819]
Most of the time tests fail with the reason, and it's not required to automatically try to rerun them if test node failed

**Comment by nicoddemus** [comment]
Could you please provide an example of a situation where you would like to disable slave recovery? I have some cases in mind, but would love to hear yours.

Also, would you like to see this as a command line option? A mark?

**Comment by bubenkoff** [comment]
it looks like in some cases automatic slave recovery leads to infinite retries (that's what i've see in my case), so i wanted to disable that completely for debugging

**Comment by bubenkoff** [comment]
probably it's related to node ids being set via xspec, but slave recovery asks for new ids

**Comment by nicoddemus** [comment]
A command line option then?

**Comment by bubenkoff** [comment]
yes, would work

**Comment by nicoddemus** [comment]
Opened a [PR](https://bitbucket.org/pytest-dev/pytest-xdist/pull-request/20) on xdist for this option.
