### ISSUE TITLE
Do command-line parsing before executing metadata fixture

### ISSUE THREAD

**Issue by harmin-parra** [pytest-dev/pytest#8198]
Context:

My pytest project has these particularities:
- Reads command-line options via **pytest_addoption** fixture as input data for some tests
- Modifies the metadata output of **pytest-html** report via **pytest_metadata** fixture

Actual behavior:
After conducting some tests, I realized that the metadata fixture is executing before the parsing the command-line options.

Desired behavior:
Being able to read command-line options values when executing the metadata fixture.

I am aware of the possibility of passing optional metadata via the `--metadata` option, but I would like very much to avoid having to provide the same option twice/separately  (for both the metadata and my tests).

Platform:
python = 3.6.9
pytest = 6.1.2
pytest-metadata = 1.10.0
pytest-html = 2.1.1

**Comment by symonk** [comment]
Hi @h-rueda can you please share a recreatable example? `pytest_addoption` is a hookspec / implementation of plugins (registered at various points in time depending on external, core/builtin etc etc).  I had a look at the pytest-metadata project and it defines this `pytest_metadata` hook which I (think) you are referring too, (yes it also exposes a `metadata` fixture). 

The plugin(s) custom hook is in fact invoking the pluggy machinery for `pytest_metadata` as part of its own `pytest_configure` hook invocation. (Such plugin is attempting to influence pluggy invocation order via `tryfirst=True`.

**Comment by h-rueda** [comment]
**conftest.py** file

```
import pytest

def pytest_addoption(parser):
	parser.addoption("--proxy", action="store", default="false")

@pytest.fixture()
def proxy(request):
	return request.config.getoption("--proxy")

@pytest.mark.optionalhook
def pytest_metadata(metadata):
	print("I wish I could read the --proxy option and do some stuff here according to its value")

	print("Then add a custom metadata related to the --proxy option value")
	metadata['Proxy'] = "metadata related to the --proxy option value"
```

**my_test.py** file

```
def test_sample(proxy):
	if proxy == "true" :
		print("test with proxy = true")
	else :
		print("test with proxy = false")
```

Run the test like this
`pytest my_test.py --html=report.html --proxy=true`

**Comment by RonnyPfannschmidt** [comment]
as per https://github.com/pytest-dev/pytest-metadata/blob/master/pytest_metadata/plugin.py - the metadata plugin hooks into the pytest_configrue hook and commandline data
the only way i see to sort it is to create a plugin object that fills the metadata in via the pytest_metadata hook

**Comment by harmin-parra** [comment]
I found the solution. I have got the idea by reading the source code of the `pytest-html `plugin

It has to be done with the `pytest_configure` hook.

Here is a sample code. But I don't understand the `except` block and the **stash** attribute of **config**

I have to say that the internal API documentation of **pytest** and **pytest-html** is not very complete, and writing plugins can be a painful task, because of this lack of documentation and examples.

Sorry for the complain, but I am really spending a lot of time and effort examining and understanding the source code of other projects because I don't find enough documentation for `pytest` and `pytest-html` internal workings.


```
@pytest.hookimpl(trylast=True)
def pytest_configure(config):
    my_option = config.getoption("my_option")
    metadata = config.pluginmanager.getplugin("metadata")
    if metadata:
        try:
            metadata = config._metadata
        except AttributeError:
            from pytest_metadata.plugin import metadata_key
            metadata = config.stash[metadata_key]
        metadata["my_option"] = config.getoption("my_option")
```

**Comment by The-Compiler** [comment]
@harmin-parra A stash is just a way to store some data, and is documented here: [API Reference — pytest documentation](https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.Stash), with some additional explanations here: [Writing hook functions — pytest documentation](https://docs.pytest.org/en/7.4.x/how-to/writing_hook_functions.html#storing-data-on-items-across-hook-functions).

The `pytest-metadata` project [seems to have some examples](https://github.com/pytest-dev/pytest-metadata#accessing-metadata) on how to access the metadata. I don't see why you would need that try/except at all.

Can you elaborate what's missing?

**Comment by harmin-parra** [comment]
If I use the example mentioned in `pytest-metadata` project (https://github.com/pytest-dev/pytest-metadata#accessing-metadata), the metadata block disappears in the HTML report

```
def pytest_configure(config):
  metadata = config.pluginmanager.getplugin("metadata")
  if metadata:
      from pytest_metadata.plugin import metadata_key
      config.stash[metadata_key]['foo'] = 'bar'
```
![Screenshot from 2023-08-05 22-35-01](https://github.com/pytest-dev/pytest/assets/16239820/d80a7890-8f63-4bf3-a094-c7f3a53c6bf2)

**Comment by The-Compiler** [comment]
Are you sure you're using pytest-metadata v3.0.0? See https://github.com/pytest-dev/pytest-metadata/commit/4194258e3665a66c3ab0bebeb2bbcfc2c7d8fc8c where this was changed. The reason for the try/except in pytest-html to continue working with older pytest-metadata versions.

**Comment by harmin-parra** [comment]
I am using the latest version of pytest-metadata

```
sudo pip3 list | grep pytest
pytest                 7.0.0               
pytest-html            3.2.0               
pytest-metadata        3.0.0 
```

**Comment by harmin-parra** [comment]
This is a pytest-metadata issue
https://github.com/pytest-dev/pytest-metadata/issues/76
