### ISSUE TITLE
testing: migrate pytest's own tests from the tmpdir fixture to the tmp_path fixture

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#8204]
The [`tmpdir` fixture](https://docs.pytest.org/en/stable/tmpdir.html#the-tmpdir-fixture) gives the test its own temporary directory. The type of the `tmpdir` is [`py.path.local`](https://py.readthedocs.io/en/latest/path.html) from the `py` library. Pytest is aiming to eventually deprecate and remove the usage of `py.path.local`, and therefore offers an alternative fixture [`tmp_path`](https://docs.pytest.org/en/stable/tmpdir.html#the-tmp-path-fixture) which has the type `pathlib.Path` from the standard library.

Before pytest can deprecate the `py.path.local` usage and related fixtures, it really ought to stop using them in its own test suite! This issue is about doing this. Luckily there aren't too many of those, the files which use `tmpdir` are (along with the number of occurrences):

```
$ rg tmpdir --count-matches -- testing/
testing/test_pathlib.py:1
testing/python/collect.py:1
testing/python/integration.py:1
testing/python/fixtures.py:24
testing/test_monkeypatch.py:4
testing/test_tmpdir.py:32
testing/test_conftest.py:8
testing/test_collection.py:24
testing/test_argcomplete.py:3
testing/test_cacheprovider.py:1
testing/example_scripts/tmpdir/tmpdir_fixture.py:3
testing/code/test_source.py:3
testing/code/test_excinfo.py:3
```

The process is:

1. Clone the latest pytest from github.
1. Pick a file or files (or all of them) from the above list.
2. Search for `tmpdir` in the file.
2. Unless the test intentionally wants a `py.path.local`, convert the `tmpdir` to `tmp_path` and `tmpdir_factory` to `tmp_path_factory` and fixup the test accordingly. The aim is to reduce the usage of `py.path` types.
3. Run the tests with `tox -e linting && tox -e py -- testing/THE_FILE_HERE.py`.
4. Submit a PR.

Optional: If the test function does not have type annotations, add them -- see #7942 for a previous example.

**Comment by sousajf1** [comment]
hello. can I work on this issue?

**Comment by bluetech** [comment]
@sousajf1 Sure!

**Comment by sousajf1** [comment]
Analysis:
**testing/test_pathlib.py:1 :**  from _pytest.tmpdir import TempPathFactory
**testing/python/collect.py:**  inside a pytester.makepyfile 
**testing/python/integration.py:1**  same
**testing/python/fixtures.py:24**  these seem tests to check the fixture itself 
**testing/test_monkeypatch.py:4**   variable naming 
**testing/test_tmpdir.py:32** test the module itself so these makepyfile must make sense to test the fixture
**testing/test_conftest.py:8**  just variable naming again
**testing/test_collection.py:24**  actually those are pytester.path
**testing/test_argcomplete.py:3**  _**FIXED**_
**testing/test_cacheprovider.py:1**  just the module import 
**testing/example_scripts/tmpdir/tmpdir_fixture.py:3**  test to the tmpdir fixture
**testing/code/test_source.py:3**  Source(tmpdir.join("a.py").pyimport().A) --> how to handle this pyimport() call?
**testing/code/test_excinfo.py:3**  _**FIXED**_

**Comment by bluetech** [comment]
@sousajf1

> how to handle this pyimport() call?

I think if you replace the `tmpdir.join("a.py").pyimport()` with

```py
mod: Any = import_path(tmp_path / "a.py")
```

where `import_path` is imported as

```py
from _pytest.pathlib import import_path
```

then it should work.

**Comment by sousajf1** [comment]
@bluetech ty. I'll check it :)

**Comment by RJ722** [comment]
Now that #8357 has been merged, can we close this issue?

**Comment by bluetech** [comment]
Yes, thanks to all who helped!
