### ISSUE TITLE
Let pytest.makefile support writing bytes

### ISSUE THREAD

**Issue by xuhdev** [pytest-dev/pytest#8215]
#### What's the problem this feature will solve?
`pytest.makefile` doesn't support writing bytes like `pytester.makefile(ext='.bin', my_file=b'binary content')`.

#### Describe the solution you'd like

The following piece of code should produce `test_a.bin` with the binary content written to it:

```python
pytest_plugins = ('pytester',)


def test_a(pytester):
    "Test pytester.makefile."

    pytester.makefile(ext='.bin', my_file=b'binary content')
```

#### Alternative Solutions

Alternative would be take the return value of `makefile` and use `write_bytes`.

**Comment by sousajf1** [comment]
should we add a pytester.makebin ?

**Comment by RonnyPfannschmidt** [comment]
The ext is not a good choice

If bytes input, use write_bytes, else use write_text

**Comment by asottile** [comment]
I would prefer a separate `makefile_binary` api instead of a union if possible

**Comment by sousajf1** [comment]
I'm not sure if this is what was intended.

**Comment by RonnyPfannschmidt** [comment]
@sousajf1 not at all

**Comment by nicoddemus** [comment]
> I would prefer a separate makefile_binary api instead of a union if possible

I think I understand the sentiment here, often having separate `Path.write_text` and `Path.write_bytes` methods have caught a bug for me, where I was expecting `str` and got `bytes`. If `Path` had just a `write` method which would write a binary or text file based on the argument type, the issue might go unnoticed.

I suspect the need to write a binary file by hand doesn't come up that often (not in my experience anyway) when using `pytester`, and it seems we are having trouble coming up with a good API, so in the end perhaps using `p = pytester.makefile(...); p.write_bytes()` is not that bad after all?

**Comment by asottile** [comment]
I think I've used `pytester.testdir.join('foo.bin').write_binary(b'...')` before -- maybe we just need to document the right code here?

**Comment by pauliyobo** [comment]
Perhapps checking if the content to write is a string or bytes and then use write_text or write_bytes could work?
In addition, although this seems  not necessary, a strict flag could be added which defaults to false, which would raise a warning, or an exception if the user tried to write bytes on a file that ends with an extension that usually  doesn't contain binary content?

**Comment by asottile** [comment]
> Perhapps checking if the content to write is a string or bytes and then use write_text or write_bytes could work?
> In addition, although this seems not necessary, a strict flag could be added which defaults to false, which would raise a warning, or an exception if the user tried to write bytes on a file that ends with an extension that usually doesn't contain binary content?

- taking str or bytes is not a good api
- keeping a mapping of "probably binary" / "probably text" file extensions is not going to be maintainable in any way.  there's also extensions which conventionally contain both (for example, apple's `.plist` is either a binary format or an xml format)

I don't think either of those suggestions should be implemented

**Comment by pauliyobo** [comment]
@asottile makes sense. I understand the mapping unmaintainability on the long run.
As for str or bytes, do you believe it's not a good API because it may confuse the users on what to provide?  I am genuinely curious,  and I apologize if this is not the place to ask.

**Comment by asottile** [comment]
strings and bytes are separate types and should be treated separately -- bugs / bad apis related to implicit conversion between the two in python 2 was most of the reason for making python 3

**Comment by xuhdev** [comment]
If you don't think it's a good idea to accept bytes,  could you perhaps at least make it clear in the doc about what a user is supposed to do? Or, perhaps add a `make_bin_file` function?

**Comment by asottile** [comment]
yeah, like I said I think this is as simple as documenting what I said above here: https://github.com/pytest-dev/pytest/issues/8215#issuecomment-754277218

just needs a documentation pull request
