### ISSUE TITLE
`--version` writes to stderr

### ISSUE THREAD

**Issue by K3UL** [pytest-dev/pytest#8246]
Hello,
When calling `pytest --version`, Pytest writes the version to stderr, which should be stdout I think. This is a problem to create automation tooling around it.

Example : 
```python
import subprocess
res = subprocess.run(["pytest", "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
res

> CompletedProcess(args=['pytest', '--version'], returncode=0, stdout=b'', stderr=b'pytest 6.1.2\r\n')
```

Context : 
```
Pytest  6.1.2
Python  3.9.0
Windows 10 20H2
```

**Comment by nicoddemus** [comment]
Hi @K3UL, 

Indeed, seems correct and at least `python -V` works the same way. Thanks!
