### ISSUE TITLE
Faulthandler not enabled when pytest run under Python Dev Mode (-X dev)

### ISSUE THREAD

**Issue by thomascobb** [pytest-dev/pytest#8258]
# Description
I use [Python Dev Mode](https://docs.python.org/3/library/devmode.html#devmode) as a handy shortcut for enabling faulthandler, enabling debug mode of asyncio, logging resource leaks, and other goodies. Unfortunately, pytest's faulthandler plugin doesn't install itself if something else has already enabled the faulthandler. This means the output of the faulthandler is swallowed unless pytest is run with `-s`

# Minimal example
Here is a file with 2 tests, one which fails with an asyncio error when run under dev mode, and another which occasionally seg faults. I would like to see the asyncio error when it doesn't segfault, and the stack trace when it does.
```python
import ctypes
import asyncio
import threading
import time

def test_wrong_thread():
    loop = asyncio.get_event_loop()
    t = threading.Thread(target=loop.run_forever)
    t.setDaemon(True)
    t.start()
    loop.call_soon(print)

def test_segfault():
    if time.time() % 1 < 0.3:
        ctypes.string_at(0)
```
Running
```
$ python -X dev -m pytest
```
Gives the error from asyncio:
```
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```
But when it segfaults the stack trace is swallowed unless run with `-s`
# Suggestion
Either unconditionally enabling faulthandler in the plugin (regardless of whether it was already enabled) or adding an option to do so would fix this, I am happy to provide a PR if this is a valid solution.
This naive solution fixes things for my example:
```diff
--- faulthandler.py	2021-01-20 09:42:57.611168438 +0000
+++ faulthandler_patch.py	2021-01-20 09:43:30.767501381 +0000
@@ -25,7 +25,7 @@
 def pytest_configure(config: Config) -> None:
     import faulthandler
 
-    if not faulthandler.is_enabled():
+    if True:
         # faulthhandler is not enabled, so install plugin that does the actual work
         # of enabling faulthandler before each test executes.
         config.pluginmanager.register(FaultHandlerHooks(), "faulthandler-hooks")
```

# Environment
```
$ pip list
Package       Version
------------- ----------
appdirs       1.4.3
attrs         20.3.0
CacheControl  0.12.6
certifi       2019.11.28
chardet       3.0.4
colorama      0.4.3
contextlib2   0.6.0
distlib       0.3.0
distro        1.4.0
html5lib      1.0.1
idna          2.8
iniconfig     1.1.1
ipaddr        2.2.0
lockfile      0.12.2
msgpack       0.6.2
packaging     20.8
pep517        0.8.2
pip           20.0.2
pkg-resources 0.0.0
pluggy        0.13.1
progress      1.5
py            1.10.0
pyparsing     2.4.7
pytest        6.2.1
pytoml        0.1.21
requests      2.22.0
retrying      1.3.3
setuptools    44.0.0
six           1.14.0
toml          0.10.2
urllib3       1.25.8
webencodings  0.5.1
wheel         0.34.2
```

**Comment by The-Compiler** [comment]
Also see #6575 - looks like the disabling [wasn't part of the original pytest-faulthandler](https://github.com/pytest-dev/pytest-faulthandler/blob/ef5cd4cbecb5bc67366e6b06e386579777752b80/pytest_faulthandler.py) but [added in #5441 by @nicoddemus](https://github.com/pytest-dev/pytest/pull/5441/files) - not sure why exactly to be honest! :slightly_smiling_face:

**Comment by nicoddemus** [comment]
> not sure why exactly to be honest! 🙂

Hmm I think was to only mess with `faulthandler` if it is not enabled yet, to avoid interfering with it, but seems that's the wrong call.

As mentioned:

https://github.com/pytest-dev/pytest/blob/eef2d1a8e268ef727eec8f1c38119ee76cdaebc2/src/_pytest/faulthandler.py#L28-L31

This will not install the hooks at all if faulthandler is already enabled. 

Here's one of the hooks:

https://github.com/pytest-dev/pytest/blob/eef2d1a8e268ef727eec8f1c38119ee76cdaebc2/src/_pytest/faulthandler.py#L50-L55

The hook does two things: 1) dup stderr so we can dump the traceback in case of exceptions, and 2) enable `faulthandler`.

I think the fix should be to always install the hooks, but pass on a `enable_faulthandler` flag, which if `True` will handle 2), but 1) will always be handled. We can then pass `enable_faulthandler=not faulthandler.is_enabled()` when installing the plugin, meaning that the plugin will enable/disable the faulthandler if it is not enabled yet, but if it is enabled it won't try to enable/disable it between tests. It will however always dup stderr and call `dump_traceback_later`/`cancel_dump_traceback_later`.

**Comment by nicoddemus** [comment]
Opened https://github.com/pytest-dev/pytest/pull/8260: the approach is slightly different than what I described above, it turns out it is simpler than that.
