### ISSUE TITLE
__package__ not set correctly at module import time

### ISSUE THREAD

**Issue by Arkadiy-bb** [pytest-dev/pytest#8261]
According to the spec [here](https://docs.python.org/3/reference/import.html#__package__), `__package__` must be string at all times.

This simple test reveals that `__package__` is set correctly when the test is executed, but is set to `None` when the module is being imported:
```
top_level_package = __package__

def  test_package():
    assert top_level_package == __package__
```

This is worse for any module I have in my testing directory. If I need to load a resource in my module, `pkgutil.get_data(__package__, "filename")` fails at the top level.

I worked around this limitation by loading my resources in session-level fixtures. Still, it would be nice to set `__package__` properly.

**Comment by asottile** [comment]
please provide more information:

```python
x = __package__

def test():
    assert type(x) is str
```

```console
$ pytest t.py 
============================= test session starts ==============================
platform linux -- Python 3.7.9, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /tmp/z
collected 1 item                                                               

t.py .                                                                   [100%]

============================== 1 passed in 0.00s ===============================
```

**Comment by asottile** [comment]
this must be from pytest 4.x, it's been set properly since pytest 5
