### ISSUE TITLE
Wrong test instance set is collected when having multiple parametrize with individual marks.

### ISSUE THREAD

**Issue by ljubanka** [pytest-dev/pytest#8262]
Version: pytest 6.1.1

From [documentation]( https://docs.pytest.org/en/stable/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions) we have the next behavior for multiple parameterized arguments, for example:
```
@pytest.mark.parametrize("x", [0, 1])
@pytest.mark.parametrize("y", [2, 3])
def test_foo(x, y):
    pass
```

This will run the test with the arguments set to x=0/y=2, x=1/y=2, x=0/y=3, and x=1/y=3 exhausting parameters in the order of the decorators. So there are 4 tests collected. Here we have equal number of values (two values) for every parameter. 

In the next case with non-equal number of values of parameters:
```
@pytest.mark.parametrize("x", [0, 1])
@pytest.mark.parametrize("y", [2, 3, 4])
def test_foo(x, y):
    pass
```
6 tests will be collected within the next set: x=0/y=2, x=1/y=2, x=0/y=3, x=1/y=3, x=0/y=4 , x=1/y=4 exhausting all combinations too. Here we have two values for "x" parameter and three values for "y" parameter.
In the next case where I want to mark individual test instance (taken from the [question here](https://stackoverflow.com/questions/24698359/mark-inputs-in-pytest-parametrize)):
```
@pytest.mark.parametrize("x", [pytest.param(0, marks=pytest.mark.suiteA), 1,])
@pytest.mark.parametrize("y", [pytest.param(2, marks=pytest.mark.suiteA), 3, 4])
def test_foo(x, y):
    pass
```
I expect that only one test will be collected in case of running pytest with "-m suiteA": the combination of values "x=0/y=2", but four tests are collected instead:
x=0/y=2
x=1/y=2
x=0/y=3
x=0/y=4

**Comment by RonnyPfannschmidt** [comment]
this is behaviour as expected, as the cross product has one run of y with the mark of x=0 and one run of x with the mark of y=2
