### ISSUE TITLE
main() -o parsing

### ISSUE THREAD

**Issue by samfok** [pytest-dev/pytest#8266]
`pytest.main()` accepts args as a list of str. However, it's not explicit in the [documentation](https://docs.pytest.org/en/stable/usage.html#calling-pytest-from-python-code) how the ini option arguments `-o <ini option>` must be passed in. They must be passed in as two separate list entries instead of one, and passing in ini option arguments in the same str as `-o` fails silently by ignoring it altogether. I would expect it to fail with an error if an argument is passed in incorrectly (as it would if, say, we passed in `-o` with nothing following).

For example, for the command line 
`pytest -o python_functions=foo`
the programmatic equivalent is
`pytest.main(['-o', 'python_functions=foo'])` where `-o` and its argument are two list entries
and not 
`pytest.main(['-o python_functions=foo'])` where they are a single entry.
In the single entry case, the `-o` option is silently ignored.

For the example test file
``` python
import logging
import pytest

LOGGER = logging.getLogger(__name__)

def test_green_eggs():
    LOGGER.warning('warning green_eggs')

def test_ham():
    LOGGER.warning('warning ham')

if __name__ == '__main__':
    # "-o python_functions" works
    pytest.main(args=['-s', '-o', 'python_functions=test_green_eggs', __file__])
    # "-o python_functions" silently ignored
    pytest.main(args=['-s', '-o python_functions=test_green_eggs', __file__])

    # "-o log_cli" works
    pytest.main(args=['-s', '-o', 'log_cli=True', __file__])
    # "-o log_cli" silently ignored
    pytest.main(args=['-s', '-o log_cli=True', __file__])
```

we  call `pytest.main` with two different `-o` options in separate-entry and single-entry format. The output  is

```
$ python test_o.py
==================================== test session starts =====================================
platform darwin -- Python 3.7.6, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir:
plugins: typeguard-2.9.1, cov-2.10.1, timeout-1.4.2
collected 1 item

test_o.py .

===================================== 1 passed in 0.01s ======================================
==================================== test session starts =====================================
platform darwin -- Python 3.7.6, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir:
plugins: typeguard-2.9.1, cov-2.10.1, timeout-1.4.2
collected 2 items

test_o.py ..

===================================== 2 passed in 0.01s ======================================
==================================== test session starts =====================================
platform darwin -- Python 3.7.6, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir:
plugins: typeguard-2.9.1, cov-2.10.1, timeout-1.4.2
collected 2 items

test_o.py::test_green_eggs
--------------------------------------- live log call ----------------------------------------
WARNING  test_o:test_o.py:7 warning green_eggs
PASSED
test_o.py::test_ham
--------------------------------------- live log call ----------------------------------------
WARNING  test_o:test_o.py:10 warning ham
PASSED

===================================== 2 passed in 0.01s ======================================
==================================== test session starts =====================================
platform darwin -- Python 3.7.6, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir:
plugins: typeguard-2.9.1, cov-2.10.1, timeout-1.4.2
collected 2 items

test_o.py ..

===================================== 2 passed in 0.01s ======================================
```

For `-o python_functions=test_green_eggs`, the first run correctly matched only one test while the second run did not.
For `-o log_cli=True`, the first run correctly output the logging information while the second run did not.

**Comment by asottile** [comment]
this isn't specific to `-o` or even pytest, that's just how arguments work.  when you send commands on your shell they are delimited by spacing / quoting.  For example `echo 'foo bar' baz "womp womp"` => `['echo', 'foo bar', 'baz', 'womp womp']`

the documentation already includes an example of this with `["-x", "mytestdir"]`

> In the single entry case, the -o option is silently ignored.

technically it's not ignored, it set `' python_functions'` to `'foo'` -- though there's no such option (the same as running `pytest '-o python_functions=foo'`)
