### ISSUE TITLE
PyTest not getting the response when testing a Django endpoint firing a celery shared task asynchronously 

### ISSUE THREAD

**Issue by tawanda14** [pytest-dev/pytest#8288]
<h1> The Issue</h1>

<p> I have a Django application running in Docker and I am trying to implement unit tests using pytest but I am facing an issue when testing an endpoint that fires celery task, the test is not getting the response from the endpoint, I am hitting the endpoint using API client </p>
<br>

<h2>The Code</h2>

<h4>The fixture</h4>

<p>@pytest.fixture <br>
        def client(): <br>
            return APIClient() <br> </p>

<h4>The Test  Class and Function </h4>

<p>
  @pytest.mark.django_db
class TestSendfit:
    
    async def test_sendfit_post(self, client):
        
    
        
        sendfit_data = {
            
            "name": "Test Name",
            "age": 1000,
            "gender": "male",
            "email": "test@gmail.com",
            "country": "ZW",
            "preferences": ["hiit", "yoga"]
            
        }

        response = client.post(SENDFIT_URL, data=sendfit_data)
              
        assert response.status_code == status.HTTP_201_CREATED
</p>
<img width="1280" alt="Screenshot 2021-01-28 at 08 50 35" src="https://user-images.githubusercontent.com/69671390/106101021-f53d3900-6145-11eb-8730-aeb4a6c28fd7.png">
<img width="1280" alt="Screenshot 2021-01-28 at 08 50 41" src="https://user-images.githubusercontent.com/69671390/106101027-fa01ed00-6145-11eb-85e2-4850ab1c651f.png">

I hope you can assist
<img width="1280" alt="Screenshot 2021-01-28 at 08 49 17" src="https://user-images.githubusercontent.com/69671390/106100937-cfb02f80-6145-11eb-8a16-406ec629ed1a.png">
<img width="1280" alt="Screenshot 2021-01-28 at 08 49 32" src="https://user-images.githubusercontent.com/69671390/106100949-d3dc4d00-6145-11eb-9d71-8b24f7dd8a4c.png">
<img width="1280" alt="Screenshot 2021-01-28 at 08 49 39" src="https://user-images.githubusercontent.com/69671390/106101010-f1111b80-6145-11eb-9c35-2117a45eb1ad.png">

**Comment by bluetech** [comment]
It is hard to say what is the problem. I suggest attaching a debugger and seeing what happens when the test is executed.

**Comment by Zac-HD** [comment]
Closing as inactive.
