### ISSUE TITLE
deprecate resultlog

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#830]
the format is incomplete and tricky to parse,
i propose deprecating it in 2.8 and scheduling full removal for when pypy uses something more modern

a more complete replacement will be proposed at a later point in time

**Comment by nicoddemus** [comment]
Hmm I have never used it... could you explain the motivation for the plugin to exist in the first place and what pypy has to do with it?

I kind of agree about it being difficult to parse... perhaps it would be better to produce the contents in something easier to parse, like JSON perhaps?

Thanks!

**Comment by RonnyPfannschmidt** [comment]
resultog is basically the first variant of semi-structured output of test results for later consumption

it was created years before json was as well known as today

pypy uses it for its execution result analysis

these days a format like subunit or a general stream of json objects (one per line) seems far more helpful

such a format could also be used for more detailed pytest debugging, (since trace items could be part of sucha stream without creating unwanted intersection)

**Comment by nicoddemus** [comment]
I see, thanks for the explanation! :smile:

**Comment by nicoddemus** [comment]
Should this be updated to `2.9` now that `2.8` is out already?

**Comment by The-Compiler** [comment]
Should we do this for 3.0 as it's backwards-incompatible but probably relatively straightforward?

**Comment by RonnyPfannschmidt** [comment]
yes please

**Comment by nicoddemus** [comment]
Fixed in #1812

**Comment by Feuermurmel** [comment]
This question may be relevant for others finding their way to this issue:

What should I use in place of `--resultlog` in py.test >= 4.0?

**Comment by RonnyPfannschmidt** [comment]
one idea is to serialize reports to the json-lines format and writing them to a file

we did not spec anything out, and we cant remove resultlog before something is in place

**Comment by The-Compiler** [comment]
What about the (already existing) JUnit XML, or TAP (for which [pytest-tap](https://pypi.python.org/pypi/pytest-tap/) + [tappy](https://pypi.python.org/pypi/tap.py) exists already)

**Comment by Feuermurmel** [comment]
@The-Compiler [JUnit XML](http://doc.pytest.org/en/latest/usage.html#creating-junitxml-format-files) seems OK, I hope I'll find all information I need in there. Didn't know about TAP, seems useful!

**Comment by nicoddemus** [comment]
We decided to deprecate it mostly because it was a custom, rarely used format.

Let us know if JUnit or TAP fits your needs, it is also useful for others looking for the same information. :grin:

**Comment by emin63** [comment]
I'm a big fan of py.test. It would be really nice to have a simple, machine readable output as this would make it easier to integrate automated testing into larger projects.

I've been going through various alternatives and all seem to have issues:

  - resultlog (this ticket) : deprecated and not easy to parse
  - junitxml : output format not documented, says it doesn't work with xdist, xml can be a pain to parse
  - pytest-json : almost exactly what I want (simple json output) but breaks reading setup.cfg for config
  - pytest-tap : seems buggy (running with --tap-outdir makes it skip all tests; running without --tap-outdir does not let you control location of output file).

I will probably use pytest-json as it seems pretty good and I guess I can live with not reading setup.cfg. It would be nice if there was a simple way to do this built into py.test or a pointer to the right place in the code to look for implementing it.

Advice appreciated.

Thanks.

**Comment by nicoddemus** [comment]
Hi @emin63,

> junitxml : output format not documented, says it doesn't work with xdist

Where does it say it doesn't work with `xdist`? Because at work we use `xdist` with `junitxml` without any issues.

> pytest-json : almost exactly what I want (simple json output) but breaks reading setup.cfg for config

I would recommend this solution as well, could you please post a bug in the `pytest-json` issue tracker so this can be brought to attention?

**Comment by emin63** [comment]
Thanks for the quick answer. I responded at https://github.com/pytest-dev/pytest/issues/2306#issuecomment-286291230 and will continue discussion there to not hijack this thread.

Thanks.
