### ISSUE TITLE
some codes are not executed.

### ISSUE THREAD

**Issue by sh3llsh0ck** [pytest-dev/pytest#832]
Hello,

its my first time to use py.test and I don't know what title should be for this issue , but here's my explanation:

In saltstack i am trying to make something like linter to look for some standards in my salt states. which will be used in jenkins as a script.

so i am trying to use py.test for this instead of using a normal python script.

I have the following `conftest.py`:

```python
def pytest_report_header(config):
    return ["project: SaltStack Formula Convention Checker","author: Mostafa Hussein"]

def pytest_addoption(parser):
    parser.addoption("--saltformula", action="append", default=[],
        help="use this option to test saltstack formula against some conventions. NOTE: you have to pass the formula same as you pass it in saltstack while using a state.sls function. EXAMPLE: --salt-formula='coreutils-viewer-formula'")

def pytest_generate_tests(metafunc):
    if 'saltformula' in metafunc.fixturenames:
        metafunc.parametrize("saltformula",
                             metafunc.config.option.saltformula)

```

and this is my `test_salt.py` script:

```python
import salt.client
import json

caller = salt.client.Caller()

def test_GeneratedJSON(saltformula):
    state_data = caller.sminion.functions['state.show_sls'](saltformula)
    json_data = dict(json.loads(json.dumps(state_data)).items())
    assert type(json_data) == dict
```
and when i run `py.test -v --saltformula='coreutils-viewer-formula' test_salt.py`

I noticed that the following line is never executed `state_data = caller.sminion.functions['state.show_sls'](saltformula)` so my test is failing , also i tried to create a separate function the test the returned value but still cannot get this line to be executed `state_data = caller.sminion.functions['state.show_sls'](saltformula)` however it works in any other python script that doesn't have a test.

is there something specific i should do to make it work ?

thanks

**Comment by nicoddemus** [comment]
I have tried to reproduce if there was any problem, but pytest seems to execute the tests as expected (I've changed the test a bit to ensure it was being called):

```python
import json

def test_GeneratedJSON(saltformula):
    assert saltformula is None
    state_data = caller.sminion.functions['state.show_sls'](saltformula)
    json_data = dict(json.loads(json.dumps(state_data)).items())
    assert type(json_data) == dict
```

```
$ py.test --saltformula=2 --saltformula=4
================================== FAILURES ===================================
____________________________ test_GeneratedJSON[2] ____________________________

saltformula = '2'

    def test_GeneratedJSON(saltformula):
>       assert saltformula is None
E       assert '2' is None

test_salt.py:5: AssertionError
____________________________ test_GeneratedJSON[4] ____________________________

saltformula = '4'

    def test_GeneratedJSON(saltformula):
>       assert saltformula is None
E       assert '4' is None

test_salt.py:5: AssertionError
========================== 2 failed in 0.03 seconds ===========================
```

To me it looks OK. What do you mean by *the following line is never executed* exactly?

**Comment by sh3llsh0ck** [comment]
I have revised the code and its working now it was my bad, i have another question:

can i get a returned value from a PASSED test so i can use it in another test instead of writing my whole code as a one function ?

```python
def test_GeneratedJSON(saltformula):
    state_data = caller.sminion.functions['state.show_sls'](saltformula)
    json_data = dict(json.loads(json.dumps(state_data)).items())
    assert type(json_data) == dict
```
so when json_data passed the test it should passed as a parameter to the following test:

```python
def test_delete_keys(json_data):
    for key in json_data.keys():
        del json_data[key]["__env__"]
        del json_data[key]["__sls__"]
    #some assertions
```

I haven't tried it yet but i am asking for making sure if its possible or not

**Comment by nicoddemus** [comment]
IIUC, you want to automatically chains some tests and share data between them, something like:

```
saltformula = 'foo' -> test_generated_json("foo") -> test_delete_keys("saltformula for foo")
saltformula = 'bar' -> test_generated_json("bar") -> test_delete_keys("saltformula for bar")
```

There's no direct support for tests to call other tests with some data. I suggest just calling a function after the other:

```python
def test_GeneratedJSON(saltformula):
    state_data = caller.sminion.functions['state.show_sls'](saltformula)
    json_data = dict(json.loads(json.dumps(state_data)).items())
    assert type(json_data) == dict
    check_delete_keys(json_data)

def check_delete_keys(json_data):
    for key in json_data.keys():
        del json_data[key]["__env__"]
        del json_data[key]["__sls__"]
    # some assertions
```

If you start coding a bunch of functions like this, you might want to move them to a fixture object instead; keep in mind that you can use `assert` statements anywhere, not only from within `test_` functions. :wink:

**Comment by sh3llsh0ck** [comment]
thanks for the help ! I will read about fixtures after having a working version of my script in order to make it as enhancements. i will close this issue for now. thanks again!

**Comment by sh3llsh0ck** [comment]
I noticed that `--maxfail` seems to calculate the fail tests during the run time, is there a way to call it as an object inside the script ? so if the first function failed the maxfail object will force interrupt the test session ?

**Comment by nicoddemus** [comment]
I'm not sure I understand what you are trying to accomplish... could you explain in more detail please?

If you test function fails (IOW, any assertion fails) then `maxfail` will automatically interrupt the test session. Or perhaps you mean that you want to stop the test suite even if `--maxfail` was not passed in the command line? In this case you can call `pytest.exit(msg)` from within the test function.

**Comment by RonnyPfannschmidt** [comment]
@sh3llsh0ck a side-note, using issues for unrelated questions/support requests easily creates confusion for contributors and others alike

i'd appreciate if you'd try to use a different means for to bring such requests/questions forth

**Comment by nicoddemus** [comment]
@sh3llsh0ck any more comments on this?
