### ISSUE TITLE
Session fixture is being activated second time

### ISSUE THREAD

**Issue by dina809** [pytest-dev/pytest#8328]
Hi

we have a session fixture that receives parameters. 
when running 2 tests using this fixture, it is being activated also for the second test. 

how can we make it to run 1 time only (despite the fact it has parameters)? 

using pytest 5.4.2 (python 3.7.4)

**Comment by RonnyPfannschmidt** [comment]
your setup is not clear, in general when it gets parameters, it gets enabled for every parameter

if you need a intermediate fixture, its necessary to have a fixture without parameters to do the heavy lifting and a parameter using fixture to do the little bits

**Comment by Formartha** [comment]
@RonnyPfannschmidt - So you are saying that fixutre in session scope shouldn't get parameters? and if it does, than it becomes a function scope fixture?

Thanks.

**Comment by RonnyPfannschmidt** [comment]
no, im saying at the session scope the fixture is set up for each parameter,, si its activated once for each parameter

parameters also exist at session scope and dont force function scope

**Comment by dina809** [comment]
@RonnyPfannschmidt - thanks for the help, but still need to clarify something.
session scope fixtures supposed to be executed once per session (fixture without parameters)
if i have session fixture with parameters then it will be activated per each parameter. is it correct to assume that if the fixture is called twice (from 2 diff functions) with SAME parameter it will be activated only one time?

i tried this example and the fixture activated each call. so not sure what is the difference between function scope fixture and session scope fixture with parameters

here is the example: 

@pytest.fixture(scope="session")
def prepare_dict(request):
    """ dict for example """
    print("parameter is {}".format(request.param["name"]))


@pytest.mark.parametrize('prepare_dict', [{"name": "dina"}], indirect=True)
def test_example(prepare_dict):
    print("Test1 done\n")

@pytest.mark.parametrize('prepare_dict', [{"name": "mor"}], indirect=True)
def test_example_2(prepare_dict):
    print("Test2 done\n")

@pytest.mark.parametrize('prepare_dict', [{"name": "dina"}], indirect=True)
def test_example_3(prepare_dict):
    print("Test3 done\n")


**output**
parameter is dina
Test1 done
parameter is mor
Test2 done
parameter is dina
Test3 done

**Comment by RonnyPfannschmidt** [comment]
Oh, you are hitting a bug there, the Parametrize turns the scope to function

Please set scope to session there as well, i believe more recent pytest handles this Better

**Comment by dina809** [comment]
@RonnyPfannschmidt  - I'v upgraded pytest to 6.2.2 and added scope parameter to the parameterize so it is looking like this:

@pytest.fixture(scope="session")
def prepare_dict(request):
    """ dict for example """
    print("parameter is {}".format(request.param["name"]))


@pytest.mark.parametrize('prepare_dict', [{"name": "dina"}], indirect=True, scope="session")
def test_example(prepare_dict):
    print("Test1 done\n")

@pytest.mark.parametrize('prepare_dict', [{"name": "mor"}], indirect=True, scope="session")
def test_example_2(prepare_dict):
    print("Test2 done\n")


@pytest.mark.parametrize('prepare_dict', [{"name": "dina"}], indirect=True, scope="session")
def test_example_3(prepare_dict):
    print("Test3 done\n")

but still it is activated 3 times.. 
using python 3.7.4

**Comment by dina809** [comment]
@RonnyPfannschmidt  - Hi Ronny, any updates on this? should i convert this issue to a bug?
thanks.

**Comment by RonnyPfannschmidt** [comment]
thanks for the ping, this went under, i'll test this today

**Comment by dina809** [comment]
@RonnyPfannschmidt  - ok, thanks! waiting for an update :)

**Comment by RonnyPfannschmidt** [comment]
ok, i understood the issue

i adopted the test script a bit to experiment with different parameter passing

```python
import pytest


@pytest.fixture(scope="session")
def prepare_dict(request):
    """ dict for example """
    print("\nparameter is {}".format(request.param))

dina = {"name": "dina"}
mor = {"name": "mor"}

def deco(name):
    return pytest.mark.parametrize('prepare_dict', [name["name"]], indirect=True, scope="session", ids=lambda x:x["name"] if isinstance(x, dict) else x)


@deco(dina)
def test_example(prepare_dict):
    print("Test1 done\n")

@deco(mor)
def test_example_2(prepare_dict):
    print("Test2 done\n")


@deco(dina)
def test_example_3(prepare_dict):
    print("Test3 done\n")
```

as far as i gathered pytest does not consider them the same identity in any case and thus does not reorder tests to avoid setup/teardown

this  could also be a edge case bug in the test reordering

**Comment by Formartha** [comment]
Thanks @RonnyPfannschmidt,
Both me and Dina are trying to understand what shall we do next? as in, how to workaround this issue? any ideas?
I'm thinking that all the fixtures are kept in memory, thus a singleton might help to determine if a fixture ran or not.

I'm not sure if there are other options (maybe register a attribute on request object might help), but we'll appreciate your guidence.

Thanks,
Mor

**Comment by BorjaEst** [comment]
Same issue here I think:

See this example:
```py
import pytest


@pytest.fixture(scope="session")
def param1(request):
    print("session param1 is {}".format(request.param))


@pytest.fixture(scope="session")
def param2(request):
    print("session param2 is {}".format(request.param))


@pytest.mark.parametrize('param1', [1, 2], indirect=True)
def test_example_1(param1):
    print("Test1 done\n")


@pytest.mark.parametrize('param1', [1, 2], indirect=True)
@pytest.mark.parametrize('param2', [1, 2], indirect=True)
def test_example_2(param1, param2):
    print("Test2 done\n")
```

Provides the following output
```sh 
$ pytest -s
========================= test session starts =========================
platform linux -- Python 3.8.3, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/.../Temp/test
collected 6 items                                                                                                                                                                                                           

test_example.py session param1 is 1 # <---- SEE HERE, first execution as "session"
Test1 done

.session param2 is 1
Test2 done

.session param1 is 2
Test2 done

.Test1 done

.session param2 is 2
Test2 done

.session param1 is 1 # <---- SEE HERE, second execution as "session"
Test2 done

.

========================== 6 passed in 0.01s ==========================
```

As I defined the fixture as "session" I do not expect to have the fisture running a second time with the same parameter...

**Comment by RonnyPfannschmidt** [comment]
Different issue, fixture variants with different parameters currently cannot coexist, so multiple setups for one have to happen

**Comment by dina809** [comment]
@RonnyPfannschmidt  - Hi Ronny, so should we change this issue to a bug?

**Comment by RonnyPfannschmidt** [comment]
That's not clear to me, I'd like to get the opinion of @nicoddemus

**Comment by dina809** [comment]
Hi @nicoddemus 
can you please assist?

Thanks.

**Comment by nicoddemus** [comment]
Sorry missed this.

> as far as i gathered pytest does not consider them the same identity in any case and thus does not reorder tests to avoid setup/teardown

Did you remember why they are not considered the same identity in this case @RonnyPfannschmidt ?

**Comment by RonnyPfannschmidt** [comment]
Unfortunately absolutely no idea

**Comment by nicoddemus** [comment]
Reduced the example further:

```python
import pytest

@pytest.fixture(scope="session")
def prepare(request):
    print("\nprepare setup with {!r}".format(request.param))

@pytest.mark.parametrize('prepare', ["dina"], indirect=True, scope="session")
def test_1(prepare):
    print("Test1 done\n")

@pytest.mark.parametrize('prepare', ["mor"], indirect=True, scope="session")
def test_2(prepare):
    print("Test2 done\n")

@pytest.mark.parametrize('prepare', ["dina"], indirect=True, scope="session")
def test_3(prepare):
    print("Test3 done\n")
```

I get this output:

```
λ pytest .tmp\test_fix_session.py -sq

prepare setup with 'dina'
Test1 done

.
prepare setup with 'mor'
Test2 done

.
prepare setup with 'dina'
Test3 done

.
3 passed in 0.02s
```

We would expect it to reorder the tests to `[test_1, test_3, test_2]` so the fixture would execute only twice, instead of 3 times as it is doing now, so definitely looks like a bug (unless I'm missing something).

If this looks right, I suggest we open a new issue with this final example/description, so one doesn't need to read the whole thread to get to the central point of the problem. What do you folks think?

**Comment by RonnyPfannschmidt** [comment]
Go ahead

**Comment by nicoddemus** [comment]
Done, closing this then in favor of https://github.com/pytest-dev/pytest/issues/8914.
