### ISSUE TITLE
Improve pytest.approx error messages readability

### ISSUE THREAD

**Issue by tarcisiofischer** [pytest-dev/pytest#8335]
Hey all. I think that as important as getting `PASSED` on our tests, it is important to get useful messages when the tests `FAIL`. That being said...

#### What's the problem this feature will solve?
While comparing numerical data with `pytest.approx`, I find the messages a bit hard to read when we are comparing big enough numpy arrays. Example:

```python
def test_bla():
    import numpy as np
    a = np.linspace(0, 100, 20)
    b = np.linspace(0, 100, 20)
    a[10] += 0.5
    assert a == pytest.approx(b)
```

The error message:   
```
>       assert a == pytest.approx(b)
E       assert array([  0.        ,   5.26315789,  10.52631579,  15.78947368,\n        21.05263158,  26.31578947,  31.57894737,  36.84210526,\n        42.10526316,  47.36842105,  53.13157895,  57.89473684,\n        63.15789474,  68.42105263,  73.68421053,  78.94736842,\n        84.21052632,  89.47368421,  94.73684211, 100.        ]) == approx([0.0 ± 1.0e-12, 5.2631578947368425 ± 5.3e-06, 10.526315789473685 ± 1.1e-05, 15.789473684210527 ± 1.6e-05, 21.05263157894737 ± 2.1e-05, 26.315789473684212 ± 2.6e-05, 31.578947368421055 ± 3.2e-05, 36.8421052631579 ± 3.7e-05, 42.10526315789474 ± 4.2e-05, 47.36842105263158 ± 4.7e-05, 52.631578947368425 ± 5.3e-05, 57.89473684210527 ± 5.8e-05, 63.15789473684211 ± 6.3e-05, 68.42105263157896 ± 6.8e-05, 73.6842105263158 ± 7.4e-05, 78.94736842105263 ± 7.9e-05, 84.21052631578948 ± 8.4e-05, 89.47368421052633 ± 8.9e-05, 94.73684210526316 ± 9.5e-05, 100.0 ± 1.0e-04])
```

This is the main example I want to solve, although I've implemented a solution for other cases.

#### Describe the solution you'd like
Would be nice to have something like this:
```
>       assert a == pytest.approx(b)
E       assert comparison failed for 1 values:
E         Index | Obtained           | Expected                    
E         (10,) | 53.131578947368425 | 52.631578947368425 ± 5.3e-05
```

#### ~Alternative~ Solutions
I haven't tried any workaround. But I implemented a solution, using `pytest_assertrepr_compare`. It is in this gist: https://gist.github.com/tarcisiofischer/cab56a5eb65aaa03bdbb4d206f1d49f0

Examples:
```
>       assert [1, 2, 3, 4] == pytest.approx([1, 3, 3, 5])
E       assert comparison failed for 2 values:
E         Index | Obtained | Expected   
E         1     | 2        | 3 ± 3.0e-06
E         3     | 4        | 5 ± 5.0e-06
```

```
>       assert 1.0 == pytest.approx(2.0)
E       assert comparison failed
E         Obtained: 1.0
E         Expected: 2.0 ± 2.0e-06
```

```
>       assert {'a': 1, 'b': 3} == pytest.approx({'a': 1.7, 'b': 3})
E       assert comparison failed for 1 values:
E         Index | Obtained | Expected     
E         a     | 1        | 1.7 ± 1.7e-06
```

A big one (sorry for the dump)
```
>       assert np.array([
            [
                [1.1987311, 12412342.3],
                [3.214143244, 1423412423415.677]
            ], [
                [1, 2],
                [3, 219371297321973]
            ]
        ]) == pytest.approx(
            np.array([
                [
                    [1.12313, 12412342.3],
                    [3.214143244, 534523542345.677]
                ], [
                    [1, 2],
                    [3, 7]
                ]
            ])
        )
E       assert comparison failed for 3 values:
E         Index     | Obtained          | Expected                  
E         (0, 0, 0) | 1.1987311         | 1.12313 ± 1.1e-06         
E         (0, 1, 1) | 1423412423415.677 | 534523542345.677 ± 5.3e+05
E         (1, 1, 1) | 219371297321973.0 | 7.0 ± 7.0e-06
```

#### Additional context
Just to mention, I didn't find any similar issue, so I'm starting a new one. The following issue has similar title, but it is completely different: https://github.com/pytest-dev/pytest/issues/6985

Please, let me know if you guys like my proposal, and feel free to suggest improvements - I'll be happy to hear ideas.
Also, feel free to disagree and close this proposal, so I will just move my code to my project's `conftest.py` ;)

**Comment by kalekundert** [comment]
Seems good to me.  Feel free to make a PR.  I didn't look at the code in great detail, but I have to believe it would be easier to modify the `__repr__()` methods for the various `Approx*` classes than to work things out after the fact like that.

**Comment by tarcisiofischer** [comment]
I tried this approach, but the problem is that while at `__repr__()` I do not have information about the lhs data of the comparison... In `pytest_assertrepr_compare` I have both sides at hand, so I can "pretty print" the two side by side. (Please correct me if I'm wrong)

**Comment by Zac-HD** [comment]
When testing numpy arrays, I'd recommend using [the `numpy.testing` support package](https://numpy.org/doc/stable/reference/routines.testing.html) instead of `pytest.approx`.

**Comment by tarcisiofischer** [comment]
Hey @Zac-HD . I liked your suggestion.

Do you think we should deprecate `pytest.approx` for ndarrays, and keep only the list implementation (So that pytest deals only with the builtin types: `float`, `map` and `list`)?

I ask because I don't know why we'd need one implementation for ndarrays here and other in the numpy package... 
Trying with `numpy.testing` gives me this result:

```
>       assert np.testing.assert_allclose(a, b)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       Mismatched elements: 1 / 20 (5%)
E       Max absolute difference: 0.5
E       Max relative difference: 0.0095
E        x: array([  0.      ,   5.263158,  10.526316,  15.789474,  21.052632,
E               26.315789,  31.578947,  36.842105,  42.105263,  47.368421,
E               53.131579,  57.894737,  63.157895,  68.421053,  73.684211,
E               78.947368,  84.210526,  89.473684,  94.736842, 100.      ])
E        y: array([  0.      ,   5.263158,  10.526316,  15.789474,  21.052632,
E               26.315789,  31.578947,  36.842105,  42.105263,  47.368421,
E               52.631579,  57.894737,  63.157895,  68.421053,  73.684211,
E               78.947368,  84.210526,  89.473684,  94.736842, 100.      ])
```

Which is better than today's `pytest.approx` message. Anyhow, I could also open up an issue there suggesting the same idea, and see where it goes from there.

What you guys thing?

**Comment by nicoddemus** [comment]
Hi @tarcisiofischer! 

I definitely like your suggestion, and it aligns nicely with how we show the diff on failure for other containers like `list` and `dict`.

> Do you think we should deprecate pytest.approx for ndarrays, and keep only the list implementation (So that pytest deals only with the builtin types: float, map and list)?

I'm not sure, but that's another issue I think.

> Which is better than today's pytest.approx message. But still, would be nice to tell which ones are different instead of throwing the whole array at me hehehe... 

Yeah I agree, and I definitely like the output you shown:

```
>       assert [1, 2, 3, 4] == pytest.approx([1, 3, 3, 5])
E       assert comparison failed for 2 values:
E         Index | Obtained | Expected   
E         1     | 2        | 3 ± 3.0e-06
E         3     | 4        | 5 ± 5.0e-06
```

We can also take some ideas from `numpy.testing`, and also include the number of mismatched elements max absolute/relative difference in there.

Another point is that we should honor the `verbose` option, how about:

* normal verbosity (no `-v` flag): we show the improved diff above, but limit it to show only 10 elements.
* verbose (`-v`): improved diff, but show all diffing elements.
* extra verbose (`-vv`): dump the two full arrays, similar like what we have today, however we might want to also include the number of differing elements, and max absolute/relative difference.

**Comment by tarcisiofischer** [comment]
sgtm. Will take a time now to try implementing on my machine before proceeding to a PR.
Thank you!

**Comment by kalekundert** [comment]
Regarding `__repr__()` again, it makes sense that you need to access both sides of the comparison.  That said, it still would probably be better to delegate the actual formatting code to a method in the `Approx*` classes, e.g. `ApproxBase.repr_compare()` or something.  That would keep more of the code in the same place, and make it easier to add new `Approx*` subclasses in the future.

**Comment by tarcisiofischer** [comment]
Hey guys @kalekundert @nicoddemus 

I managed to make a first version of this (commit is [in my fork here](https://github.com/tarcisiofischer/pytest/commit/015d8af0c0435afe5a37d8999a2d6ad015790b6d))

But I'm having trouble finding out how to implement it "inside" pytest: My original implementation relies on `pytest_assertrepr_compare`, which is something that goes on the `conftest.py` file. Today, I've added the code in the `testing` module, just to be able to run some tests. I need help moving this to the appropriate place now. Where should my `pytest_assertrepr_compare` be?

Thanks in advance.

**Comment by nicoddemus** [comment]
I think it is OK to define it in the same place `approx` is defined, in [python_api.py](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/python_api.py). 👍

**Comment by tarcisiofischer** [comment]
@nicoddemus Placing `pytest_assertrepr_compare` on `python_api.py` doesn't seem to get "collected" by the mechanism... Should it work outside `conftest.py`? [That's how I tried](https://github.com/tarcisiofischer/pytest/commit/139c93fad5cfc0dce8fe5f27e846c7bfee80879e), but running with `tox -e py36 -- testing/python/approx.py` yields the "old" error messages, so my tests fails:

```
E       AssertionError: assert 'assert 2.0 =...= approx(1.0)' == 'assert compa...1.0 ± 1.0e-06'
E         + assert 2.0 == 1.0 ± 1.0e-06
E         +  +  where 1.0 ± 1.0e-06 = approx(1.0)
E         - assert comparison failed
E         -   Obtained: 2.0
E         -   Expected: 1.0 ± 1.0e-06
```

**Comment by nicoddemus** [comment]
Argh sorry, my bad, `python_api` is not one of the [default plutins](https://github.com/pytest-dev/pytest/blob/bfbf733a3ed2f58a71570aa6e950444f3c5b0ea1/src/_pytest/config/__init__.py#L226-L259) which are installed automatically.

I suggest to place that hook in `python.py` then, we can discuss a better location over the code in the PR if needed.
