### ISSUE TITLE
Recommend `np.testing` module instead of `pytest.approx` with Numpy arrays

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#8337]
Via https://github.com/pytest-dev/pytest/issues/8335#issuecomment-777359893, this issue proposes that we should deprecate `pytest.approx()` for `numpy.ndarray`s in favor of the `numpy.testing` module.  That module is custom-built with lots of useful assertion helpers for Numpy, while `pytest.approx()` only incidentally copes with multi-dimensional arrays and the risk of treating arrays as truthy booleans in assertions.

I particularly like this because we can very easily [check if something is an array without importing Numpy](https://twitter.com/jakevdp/status/1130983439862181888), and teaching people about the `numpy.testing` module is likely to lead to better tests 🙂

**Comment by nicoddemus** [comment]
Definitely 👍 on at least recommending `numpy.testing` on our docs.

About deprecating, we might consider just calling some `numpy.testing` functions internally when using `approx` with numpy arrays, to avoid breaking users?

**Comment by kalekundert** [comment]
Strongly disagree on deprecating `approx()` in favor of `numpy.testing` for arrays:
- The `approx()` syntax is much more consistent with the pytest style of writing tests.
- There's less for users to learn if the `approx()` syntax works for both built-in and numpy types.
- `numpy.testing` has very little functionality that `approx()` doesn't.  It does have the ability to compare arrays in terms of ULPs, which `approx()` does not, but that's a pretty niche feature.
- Multi-dimensional arrays are supported by `approx()`; is there something specific that doesn't work?  I'm also not sure what you mean by "the risk treating arrays as truthy booleans".
- I can't see any benefit to re-implementing `approx()` to use `numpy.testing` under the hood.  We would just lose control over the way that errors are reported, and introduce subtle differences in the semantics of the tolerances depending on which types are being compared.

I'm not opposed to mentioning `numpy.testing` in the docs—which already mention `numpy.isclose()` and `numpy.allclose()`—but actually deprecating `approx()` for numpy comparisons would be a clear step backwards.

**Comment by tarcisiofischer** [comment]
Ok, now that #8335 is closed, I'll take a look at this.
I don't have any strong feelings about this, only that, today, I prefer to use `approx` because it is what I was already using hehe :P 

Current proposal for close this issue is just mention `numpy.testing` on the docs. Seems enough @Zac-HD ?
