### ISSUE TITLE
pytest_generate_tests can't override fixture parameters?

### ISSUE THREAD

**Issue by lawrence-danna-apple** [pytest-dev/pytest#8338]
This is supposed to work right?

```python
import pytest

@pytest.fixture(params=[10,20])
def foo(request):
    return request.param

def test_foo(foo):
    assert foo % 10 == 0

def pytest_generate_tests(metafunc):
    metafunc.parametrize('foo', [100,200,300])
```

What I get is: 

```python
e/lib/python3.8/site-packages/_pytest/fixtures.py:1581: in pytest_generate_tests
    metafunc.parametrize(
e/lib/python3.8/site-packages/_pytest/python.py:1100: in parametrize
    newcallspec.setmulti2(
e/lib/python3.8/site-packages/_pytest/python.py:932: in setmulti2
    self._checkargnotcontained(arg)
e/lib/python3.8/site-packages/_pytest/python.py:909: in _checkargnotcontained
    raise ValueError(f"duplicate {arg!r}")
E   ValueError: duplicate 'foo'
```

environment:

```
(e) dispater.local:~/Desktop$ pip list
Package    Version
---------- -------
attrs      20.3.0
iniconfig  1.1.1
packaging  20.9
pip        20.3.3
pluggy     0.13.1
py         1.10.0
pyparsing  2.4.7
pytest     6.2.2
setuptools 51.1.0
toml       0.10.2
wheel      0.36.2
WARNING: You are using pip version 20.3.3; however, version 21.0.1 is available.
```

**Comment by bluetech** [comment]
> This is supposed to work right?

I'm not sure, it seems to me that this scenario is mean often an unintentional error than something that is intended to work.

I assume that what you mean for it to do is to add the `100, 200, 300` params in addition to the `10,20` params?

May I ask what is the use case for this? Specifically, why not use just `fixture(param)` or just `pytest_generate_tests`?

**Comment by lawrence-danna-apple** [comment]
> May I ask what is the use case for this? Specifically, why not use just fixture(param) or just pytest_generate_tests?

I've got a bunch of tests that use the fixture.  Most of them use the default parameters but some need different parameters.

I found I could use `pytest.mark.parametrize(...,indirect=True)` to set the parameters on on the weird tests instead of `pytest_generate_tests`

**Comment by RonnyPfannschmidt** [comment]
I wonder if this is about the hook order

The Parametrize mark is implemented using that hook

**Comment by rjboczar** [comment]
Does this break anything unexpected?
```
def pytest_generate_tests(metafunc):
    mark = metafunc.definition.get_closest_marker("parametrize")
    mark.args[1] = [100,200,300]
```

**Comment by RonnyPfannschmidt** [comment]
This would utterly mess up class scope Parametrize markers

It's also happy go lucky on which parameter names it hits

Wouldn't recommend

**Comment by rjboczar** [comment]
Gotcha; I tried this out to force a specific fixture to always be `indirect = True` in parametrize calls. It worked, but I bet with a more complicated setup something would break. I poked through the code a bit and there were definitely some scoping things you'd also have to fix manually.

**Comment by Zac-HD** [comment]
Closing this because there's no clear action to take 🤷
