### ISSUE TITLE
Insure failing if a required parameter is missing

### ISSUE THREAD

**Issue by sh3llsh0ck** [pytest-dev/pytest#835]
In the documentation there is the following example about how to add a custom option:

```python
# content of conftest.py

def pytest_addoption(parser):
    parser.addoption("--stringinput", action="append", default=[],
        help="list of stringinputs to pass to test functions")

def pytest_generate_tests(metafunc):
    if 'stringinput' in metafunc.fixturenames:
        metafunc.parametrize("stringinput",
                             metafunc.config.option.stringinput)
```

```python
# content of test_strings.py

def test_valid_string(stringinput):
    assert stringinput.isalpha()
```
as the documentation says : 
If you don’t specify a stringinput it will be skipped because metafunc.parametrize() will be called with an empty parameter listlist:

```
$ py.test -q -rs test_strings.py
s
========================= short test summary info ==========================
SKIP [1] /tmp/sandbox/pytest/.tox/regen/lib/python3.4/site-packages/_pytest/python.py:1185: got empty parameter set, function test_valid_string at /tmp/doc-exec-109/test_strings.py:1
1 skipped in 0.01 seconds
```
what if i want it to fail instead of skip (so it will be fail if i didn't pass a required parameter), how to accomplish this ?

**Comment by nicoddemus** [comment]
I can suggest two options:

1. Check that parameters were passed in the command line within the `pytest_generate_tests` call. This will make the collection of the modules that use that fixture to fail:

  ```python
  def pytest_generate_tests(metafunc):
      if 'stringinput' in metafunc.fixturenames:
          assert metafunc.config.option.stringinput, 'no stringinput given'
          metafunc.parametrize("stringinput",
                               metafunc.config.option.stringinput) 
  ```
  ```
    =================================== ERRORS ====================================
    ______________________ ERROR collecting test_strings.py _______________________
    X:\pytest\.env34\lib\site-packages\pluggy-0.3.0-py3.4.egg\pluggy.py:724: in __call__
        return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
    X:\pytest\.env34\lib\site-packages\pluggy-0.3.0-py3.4.egg\pluggy.py:338: in _hookexec
        return self._inner_hookexec(hook, methods, kwargs)
    X:\pytest\.env34\lib\site-packages\pluggy-0.3.0-py3.4.egg\pluggy.py:333: in <lambda>
        _MultiCall(methods, kwargs, hook.spec_opts).execute()
    X:\pytest\.env34\lib\site-packages\pluggy-0.3.0-py3.4.egg\pluggy.py:595: in execute
        return _wrapped_call(hook_impl.function(*args), self.execute)
    X:\pytest\.env34\lib\site-packages\pluggy-0.3.0-py3.4.egg\pluggy.py:249: in _wrapped_call
        wrap_controller.send(call_outcome)
    x:\pytest\_pytest\python.py:254: in pytest_pycollect_makeitem
        res = list(collector._genfunctions(name, obj))
    x:\pytest\_pytest\python.py:396: in _genfunctions
        self.ihook.pytest_generate_tests(metafunc=metafunc)
    X:\pytest\.env34\lib\site-packages\pluggy-0.3.0-py3.4.egg\pluggy.py:724: in __call__
        return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
    X:\pytest\.env34\lib\site-packages\pluggy-0.3.0-py3.4.egg\pluggy.py:338: in _hookexec
        return self._inner_hookexec(hook, methods, kwargs)
    X:\pytest\.env34\lib\site-packages\pluggy-0.3.0-py3.4.egg\pluggy.py:333: in <lambda>
        _MultiCall(methods, kwargs, hook.spec_opts).execute()
    X:\pytest\.env34\lib\site-packages\pluggy-0.3.0-py3.4.egg\pluggy.py:596: in execute
        res = hook_impl.function(*args)
    conftest.py:9: in pytest_generate_tests
        assert metafunc.config.option.stringinput, 'no stringinput given'
    E   AssertionError: no stringinput given
    =========================== 1 error in 0.04 seconds ===========================
  ```

2. Another option is to explicitly parametrize your tests with a special value (say `None`), and make them fail if they encounter it:

  ```python 
  def pytest_generate_tests(metafunc):
      if 'stringinput' in metafunc.fixturenames:
          metafunc.parametrize("stringinput",
                               metafunc.config.option.stringinput or [None]) 
  # test_strings.py
  def test_valid_string(stringinput):
      assert stringinput is not None, 'stringinput not given'
      assert stringinput.isalpha()  
  ```

  ```
    ================================== FAILURES ===================================
    ___________________________ test_valid_string[None] ___________________________

    stringinput = None

        def test_valid_string(stringinput):
    >       assert stringinput is not None, 'stringinput not given'
    E       AssertionError: stringinput not given
    E       assert None is not None

    test_strings.py:2: AssertionError
    ========================== 1 failed in 0.02 seconds ===========================         
  ```

Which one to use depends on your specific use case: in the first option won't run any test from the modules which use that fixture, while the second one would run the entire test suite as usual but only the tests which use the fixture would fail.

Hope that helps!

**Comment by sh3llsh0ck** [comment]
Thanks ! , I will go with first option to avoid running the tests at all.

I have another question about customized parameters, It seems its not allowed to use hyphens in the command line option and keep the parameter name as it is.

for example if i want to make the option called `--string-input` and make the parameter called `stringinput` or `string_input`. i tried to accomplish this put its failing, any explanation ?

Also is there a way to customize the builtin report header, I don't mean adding a new header, i mean hiding a builtin header like `rootdir` for example.

**Comment by nicoddemus** [comment]
> for example if i want to make the option called --string-input and make the parameter called stringinput or string_input. i tried to accomplish this put its failing, any explanation?

You can use the `dest` parameter:

```python
def pytest_addoption(parser):
    parser.addoption("--stringinput", dest="my_variable_name", ...)
``` 

> Also is there a way to customize the builtin report header, I don't mean adding a new header, i mean hiding a builtin header like rootdir for example.

Currently it's not possible to hide headers, only add new lines to it.

Cheers

**Comment by sh3llsh0ck** [comment]
Thanks , I think documentation needs more details about the options available for `parser.addoption` , as nothing there about `dest` , and also i don't know the need of `action` and its value depends on what ? , or maybe i cannot reach the page where it explaining the usage of `parser.addoption`

**Comment by nicoddemus** [comment]
Agree, PR for the docs are always appreciated. :smile:

Could you close this then?

**Comment by sh3llsh0ck** [comment]
Okay I will close it.

Could you tell me the usage of `action` parameter in `parser.addoption` ? do i need to use it ? currently i set it value to append as it was in the documentation but i don't know the importance of it or why its set to append

**Comment by nicoddemus** [comment]
Sure, It follows the same options as the standard [argparse](https://docs.python.org/2/library/argparse.html) module.
