### ISSUE TITLE
[appearance][Dark Mode] Logo in the org should have a transparent background

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest#8356]
This is a sequel to #8158. I was browsing the org and noticed that the white square of a logo on the pytest-dev org page. Also, it appears to be lowres (maybe that's because I use 200% zoom these days but having better quality should help with this too.

The treatment should be the same as in the original issue. Org logos can be PNG (as proven by @cherrypy).

**Comment by webknjaz** [comment]
Oh, and the bounding box of the logo sorta crops parts of the letters in the corners so it may be a good idea to add some space around it.

**Comment by webknjaz** [comment]
![pytest-dev-org-logo-dark](https://user-images.githubusercontent.com/578543/108601452-efc9bc00-739c-11eb-9ed1-c5302f4918d1.png)

**Comment by webknjaz** [comment]
@nicoddemus this should be easily fixable by requires somebody with org owner access level ^

**Comment by The-Compiler** [comment]
Done!

![image](https://user-images.githubusercontent.com/625793/185758850-17070cdf-3d84-46f0-bb4c-e80dbedd2673.png)

**Comment by webknjaz** [comment]
Brilliant! That's so much nicer :)
I see some scaling artifacts but pretty sure you can't fix that...
@The-Compiler did you use a PNG version of the logo or a JPG? The former is supposed to be smoother IIUC.

**Comment by The-Compiler** [comment]
I uploaded a 300dpi png (based [on the SVG](https://github.com/pytest-dev/design/blob/master/pytest_logo/pytest_logo_curves.svg)). So yeah, don't think there's much we can do about that, other than perhaps trying to upload a less insane resolution? But doubt it'd help.

**Comment by webknjaz** [comment]
It injects this
```html
<img itemprop="image" class="avatar flex-shrink-0 mb-3 mr-3 mb-md-0 mr-md-4" src="https://avatars.githubusercontent.com/u/8897583?s=200&amp;v=4" alt="@pytest-dev" width="100" height="100">
```

So maybe if you manually scale it down to 200x200px before uploading, it'd skip rescaling.

**Comment by The-Compiler** [comment]
Given that the size is in the URL, I'm guessing they use different URLs with different scaling in other contexts perhaps. The [docs for users](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/personalizing-your-profile) actually say:

> For the best quality rendering, we recommend keeping the image at about 500 by 500 pixels.

So that's what I did now. Also made it a tiny bit bigger, I think (hard to judge, because GitHub's UI actually makes you cut it to a circle, even if it's later displayed as a square...).

**Comment by webknjaz** [comment]
Well, I don't see any difference but maybe it's just cached. Let's hope this does the trick.
