### ISSUE TITLE
Wrong color formatting output with FAILED test.

### ISSUE THREAD

**Issue by SebFernandez** [pytest-dev/pytest#8371]
**Context**
I'm using Pytest to test a Flask webapp, when I execute my tests there is one of them that FAILS at the middel of the sequence, so the format of the following text will be red instead of green when they PASS.

**Steps to reproduce**: 
1. Create a set of tests.
2. Place one test that will **fail** in order to be executed at the middle of the test execution.

**Expected behavior**
Wheter the test fails the color will be red and if it's a pass, the color will be green.

**Screenshots**
[Here's a screenshot of the issue](https://imgur.com/oqGbbme.png)
[VS Code detailed information](https://imgur.com/FKBo6Yl.png)

**Environment:**
 - OS: Xubuntu 20.10
 - Python Version 3.8.6
 - Pytest version 6.2.2
 - Flask version 1.1.2

**Additional context**
I'm using a Terminal hosted by VS Code (v1.53.2)

PS: I would love to contribute as it's my first ever issue reported but I can't figure out at the source code where is this coded.

**Comment by The-Compiler** [comment]
This is intended, so that it's clear that something failed in the past even with longer outputs.
