### ISSUE TITLE
file attribute is wrong in `junitxml` output when using decorator over test function

### ISSUE THREAD

**Issue by zigomir** [pytest-dev/pytest#8386]
- [x] a detailed description of the bug or problem you are having

I expect `pytest` to print actual file path into `file` attribute of `junitxml` output instead of one of the decorator function being used.

Similarly, when you run `pytest` with `-vv` you can see decorator function like so

```
test_repro.py::test_reproduction <- mock_decorator.py PASSED 
```

which is fine, but not for `junitxml` results.

- [x] output of `pip list` from the virtual environment you are using

```
pip list
Package    Version
---------- -------
attrs      20.3.0
iniconfig  1.1.1
packaging  20.9
pip        21.0.1
pluggy     0.13.1
py         1.10.0
pyparsing  2.4.7
pytest     6.2.2
setuptools 53.0.0
toml       0.10.2
wheel      0.36.2
```

- [x] pytest and operating system versions

```sh
pytest --version
pytest 6.2.2
uname -a
Linux 57667840718d 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux
```

- [x] minimal example if possible

See https://github.com/zigomir/pytest_junitxml

**Comment by RonnyPfannschmidt** [comment]
user error - the decorator does not indicate the returned function is a wrapper and what is wrapped

use `functools.wraps` to add that metadata
