### ISSUE TITLE
pytest --version should also display information about installed plugins

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#8393]
At this moment `pytest --version` does only output one line with its current version, missing to mention other essential informations which do affect its execution: installed plugins and python version.

Based on other tools that support plugins I dare to suggest extending the display to something similar with tox output:

```shell
$ tox --version
3.21.3 imported from /Users/ssbarnea/.pyenv/versions/3.8.6/lib/python3.8/site-packages/tox/__init__.py
registered plugins:
    tox-envreport-0.2.1 at /Users/ssbarnea/.pyenv/versions/3.8.6/lib/python3.8/site-packages/tox_envreport/plugin.py
    tox-ansible-1.0.5.dev1 at /Users/ssbarnea/c/a/tox-ansible/src/tox_ansible/hooks.py
```

I do not have a strong opinion regarding if those paths should be printed, but plugins and their versions are essential. 

Also it would be wise to assure that the first line still starts with `pytest <version>`, so it would be unlikely to break parsing of version, if anyone did this. I mention this because recently Ansible managed to break even this, by adding some other bit between tool name and the version... :p

**Comment by The-Compiler** [comment]
It already does this with `--version --version` - see #7169 and #7128. Given that the change was introduced because some people felt `--version` was too verbose (and there's precedence for repeating the argument for more verbose version info in other tools), I don't see a reason to go back.

**Comment by ssbarnea** [comment]
Ooops, I kinda deserve a RTFM on that..... It is the first time when I see that --version is used like that, maybe I would have seen more logic on enabling it via `-v` instead of repeating it. Anyway sorry for creating a false bug report and thanks!

**Comment by nicoddemus** [comment]
>  maybe I would have seen more logic on enabling it via -v instead of repeating it

That was the original idea, but other tools (including Python) follow the same approach: https://github.com/pytest-dev/pytest/issues/3692#issuecomment-620670986

**Comment by ssbarnea** [comment]
I did not see this documented on https://clig.dev/ but it would not be a bad idea to make a pull-request to improve it and to mention that displaying version twice could display more information. That guide is very useful for anyone writing CLI tools.
