### ISSUE TITLE
Truncation threshold at different verbosity levels

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#8403]
Currently pytest _always_ truncates any output string when displaying assertion errors to 240 characters (it is hardcoded in `saferepr`). This is often a problem, specially in CI (#6682).

https://github.com/pytest-dev/pytest/pull/8391 changes how verbosity affects truncation of assertion output, like this:

<table>
<tr>
	<td>Verbosity
	<td>Max chars
<tr>
	<td>0
	<td>240
<tr>
	<td>1
	<td>240
<tr>
	<td>2
	<td>240
<tr>
	<td>3
	<td>2400
<tr>
	<td>4+
	<td>No limit
</table>

The intent here was to keep the normal `-v` and `-vv` (the more common verbosity levels) unchanged, however I have been thinking that perhaps it makes more sense to increase the threshold starting right with `-v`, like this:

<table>
<tr>
	<td>Verbosity
	<td>Max chars
<tr>
	<td>0
	<td>240
<tr>
	<td>1
	<td>2400
<tr>
	<td>2+
	<td>No limit
</table>

Thoughts?

The logic is that one who is increasing verbosity already expects more output anyway, so it makes sense to increase the threshold limit as well.

cc @ssbarnea

**Comment by RonnyPfannschmidt** [comment]
I agree

**Comment by ssbarnea** [comment]
To me this will likely be an acceptable approach as I could assure that we run with `-v` in CI, which gives a long enough limit  for most cases. I do see this proposal as much more practical.

Out of curiosity, could you recommend me a way to rewrite the [current test](https://github.com/ansible-community/ansible-lint/blob/483005eb871f6bc0e3f398d32fe788797a749e43/test/test_prerun.py#L17) that is causing this issue in a way that would allow user to see the full error when it fails?

The common issue is that I run an external command and endup with a `subprocess.CompletedProcess` object which I inspect, usually checking that specific strings are present or absent in it.

When the test fails I want to display the entire stdout/stderr from the CompletedProcess on the console, as without it, the user will likely be clueless about what caused the unexpected failure. 

I am willing to do anything to workaround the current limitation, especially as I am very curious which flakey errors are causing these on CI.

**Comment by nicoddemus** [comment]
> Out of curiosity, could you recommend me a way to rewrite the current test that is causing this issue in a way that would allow user to see the full error when it fails?

Only that linked line fails? 

Either way, as a workaround I would pass the full stderr/stdout as the assertion message:

```python
    assert "Running ansible-galaxy role install" in result.stderr, result.stderr
    assert "Running ansible-galaxy collection install" not in result.stderr, result.stderr
    assert result.returncode == 0, result.stderr
```

**Comment by nicoddemus** [comment]
Worth noting, the assertion only rewrites assertions in the form `assert <expr>`, assertions in the form `assert <expr>, msg` are left untouched.
