### ISSUE TITLE
Readability of API documentation with type annotations

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#8405]
Hey folks,

Recently [on twitter](https://twitter.com/nedbat/status/1367801775189860353) a thread about type annotations in documentation gained traction, using pytest as an example:

![image](https://user-images.githubusercontent.com/1085180/110146121-f30b7180-7db8-11eb-8927-4e25ecf6bff9.png)

I'm opening this to see if we can improve the situation.

**Comment by davidism** [comment]
Not sure if you're using the Sphinx autodoc extension, but if you are you can add `autodoc_typehints = "description"` to get the hints next to the parameter/return descriptions instead of in the signature.

**Comment by nicoddemus** [comment]
Thanks for the suggestion! Opened https://github.com/pytest-dev/pytest/pull/8407 with this change, let's see what others think.

**Comment by Tinche** [comment]
Tangential: optional[union] doesn't make sense anyway, just add None to the union. That's what happens in runtime anyway iirc

**Comment by bluetech** [comment]
The `_pytest.code.code.ExceptionInfo` would hopefully become just `ExceptionInfo` once we sort out its typing.

We can change the `_E` to `E` or `Exc`; I suppose legibility is more important here than the privacy designation.

Other than that it looks good to me for an API reference. Maybe some syntax highlighting would help, but that's up to Sphinx.

**Comment by bluetech** [comment]
> Tangential: optional[union] doesn't make sense anyway, just add None to the union. That's what happens in runtime anyway iirc

I myself at least prefer to use `Optional` when the `None` is just some dummy default/disable value, and `Union[..., None]` when the `None` is an actual "legitimate" value (e.g. `JsonPrimitive = Union[str, float, bool, None]`). Although the new `|` syntax will make this moot.

Speaking of `|`, it would also make this a little clearer display wise. Maybe Sphinx can swap `Union` with `|` already somehow.
