### ISSUE TITLE
Wrapping mark decorator works at individual test level but not class level

### ISSUE THREAD

**Issue by antesaj** [pytest-dev/pytest#8406]
`pytest 6.1.2`

I've created a decorator that wraps the `pytest.mark` decorator like so:

```
def set_resources(*args):
    def wrapper(func):
        @pytest.mark.resources(*args)
        def inner(*args, **kwargs):
            func(*args, **kwargs)
        return inner
    return wrapper
```
Where `resources` is a custom marker used to pass metadata to tests.

I then use the decorator just as I would use `pytest.mark.resources()`, like

```
@set_resources('a', 'b', 'c')
def test_something():
   ...
```

This successfully inherits the behavior of `pytest.mark` when placed on individual tests, however when used at the class level, pytest loses its ability to discover tests completely. 

I'm not sure if wrapping `pytest` decorators like this is even supported or if I'm merely doing it wrong, but I am not receiving any indication of errors. PyTest discovery simply discovers and sets the mark when I use the wrapper on individual cases, and fails to discover any tests at all when using it on the class level.

**Comment by RonnyPfannschmidt** [comment]
This is a user error, classes need different decoration

Based on the example just return the mark decorator and it will work

**Comment by antesaj** [comment]
Thanks @RonnyPfannschmidt - I didn't realize you could extend a decorator simply by returning it.
