### ISSUE TITLE
Adding finalizers directly, setup code raise exception,but teardown code not run

### ISSUE THREAD

**Issue by wessonlan** [pytest-dev/pytest#8408]
I read pytest doc about fixture-Adding finalizers directly:
We have to be careful though, because pytest will run that finalizer once it’s been added, even if that fixture raises an exception after adding the finalizer. 

I try setup code raise exception,but teardown code still not run

**Comment by RonnyPfannschmidt** [comment]
Please add enough information /code examples so that we can actually figure what you mean

As is we have to close this as not actionable.

**Comment by wessonlan** [comment]
```
# content of conftest.py

@pytest.fixture()
def init_data_allot_task(request):
    query_sql = """
    SELECT id FROM `sm_purchase_allot` WHERE `status`!=5 ORDER BY add_time desc limit 100
    """
    db = DB()
    data = db.fetch_one(query_sql)
    db.close()

    def demo_finalizer():
        print("running finalizer code...")
    request.addfinalizer(demo_finalizer)
    return data
```
```
# content of test-test_allot_task_detail.py
...
def test_allot_detail(init_data_allot_task):
    """

    """
    payload = {
          "allotId": init_data_allot_task[0]
        }
    r = requests.post(QA_URL + API_URL, json=payload, headers=HEADER)
    result = r.json()

    assert result["result"] == "ok"
    assert result["errmsg"] == "success"
    assert len(result["row"]["taskListOfPage"]["resultData"]) > 0


if __name__ == "__main__":
    pytest.main(["-s", "test_allot_task_detail.py"])
```
I try the code ` db = DB()` in the fixture raise mysql error what time out, then I thought `demo_finalizer`function will run，but I have no see `"running finalizer code..."`，

so I don't know what this sentence in the official document means:`We have to be careful though, because pytest will run that finalizer once it’s been added, even if that fixture raises an exception after adding the finalizer.`

can you help me? thanks

**Comment by mrbean-bremen** [comment]
In your fixture, the exception occurs _before_ you add the finalizer, so it actually never gets added. As you quote the documentation:
> even if that fixture raises an exception ***after*** adding the finalizer

**Comment by wessonlan** [comment]
> In your fixture, the exception occurs _before_ you add the finalizer, so it actually never gets added. As you quote the documentation:
> 
> > even if that fixture raises an exception _**after**_ adding the finalizer

thanks,I  see

**Comment by mrbean-bremen** [comment]
Closing as answered.
