### ISSUE TITLE
Update website links

### ISSUE THREAD

**Issue by xmo-odoo** [pytest-dev/pytest#841]
On http://pytest.org/latest/ both the Issue Tracker and code links (*pytest @ bitbucket*) link to bitbucket, which then redirects to github. Would be nice to update the site and link directly to github since the project has apparently moved here.

**Comment by xmo-odoo** [comment]
Mmmm it looks like [the sidebar links were updated a long time ago in the source](https://github.com/pytest-dev/pytest/blob/master/doc/en/_templates/links.html) is it possible that whatever builds pytest.org wasn't udpated and is still pulling from bitbucket?

**Comment by nicoddemus** [comment]
Yep, we need to push the new docs to the site. Thanks for bringing this up!

**Comment by nicoddemus** [comment]
Just uploaded the docs for 2.7.2, thanks again.
