### ISSUE TITLE
pytest.mark.skip/skipif is not working when pytest bdd decorators are added at function level

### ISSUE THREAD

**Issue by aniket02k** [pytest-dev/pytest#8423]
Hi,
I am trying to skip test case execution using pytest.mark.skipif() decorator. But its not working when I am using this marker with pytestbdd markers. Is there any solution available to resolve this issue?

Below is the sample code which I am trying to execute.

```import pytest
from pytest_bdd import (
    given,
    scenarios,
    then,
    when,
    parsers
)
a=5
scenarios('./a.feature')
@pytest.mark.skipif(a==5,reason='matched')
@given(parsers.parse('a is declared'))
def test_ios():
    assert 'not executed'
```

**Test case is passing in any condition**
m_test.py::test_verify_markers PASSED                                                                                           [100%]

Thanks In Advance.

**Comment by mrbean-bremen** [comment]
It should actually skip `test_ios` as is - maybe it has to do with the loaded feature. Does it behave the same if you don't load the feature (e.g. comment out the `scenarios` line)?

**Comment by aniket02k** [comment]
> Does it behave the same if you don't load the feature (e.g. comment out the `scenarios` line)?

Yes its working as expected after commenting `scenarios` line

**Comment by aniket02k** [comment]
Hi @mrbean-bremen,
I tried setting variable after loading the scenarios from feature file. Still getting the same results.

Below is the updated code
```
import pytest
from pytest_bdd import (
    given,
    scenarios,
    then,
    when,
    parsers
)
scenarios('./a.feature')
a=5
@given(parsers.parse('a is declared'))
@pytest.mark.skipif(a==5,reason='matched')
def test_ios():
    assert True

```

**Comment by mrbean-bremen** [comment]
If I try this with some dummy scenario, it works fine for me (e.g. the test is skipped), so it shall have to do with your concrete scenario. It would help if you could provide a minimal reproducible example, including the feature file and the feature implementation.

**Comment by aniket02k** [comment]
Hi @mrbean-bremen,
Below is my feature file:
```
Feature: Check pytest markers

       Scenario: verify markers
           Given a is declared
```

and content of a_test.py

```
import pytest
from pytest_bdd import (
    given,
    scenarios,
    then,
    when,
    parsers
)
scenarios('./a.feature')
a=5
@given(parsers.parse('a is declared'))
@pytest.mark.skipif(a==5,reason='matched')
def test_ios():
    assert True
```

**Comment by aniket02k** [comment]
I wanted to skip the execution of test case based on some condition. Is there any alternative for `pytest.mark.skipif` available? any pointers on alternative ways to skip the test case in pytest-bdd please suggest.

**Comment by mrbean-bremen** [comment]
Hm, works fine for me. Here is the output with your feature (this is under Windows, but that should not matter):
```

(Py37_new) c:\...\skip_with_scenario>pytest -v
SESSIONSTART
================================================= test session starts =================================================
platform win32 -- Python 3.7.1, pytest-6.2.2, py-1.9.0, pluggy-0.13.1 -- c:\dev\venv\py37_new\scripts\python.exe
cachedir: .pytest_cache
rootdir: c:\dev\questions, configfile: pytest.ini
plugins: bdd-4.0.2, dependency-0.5.1, forked-1.3.0, mock-3.2.0, xdist-2.2.1, order-1.0.0.dev0
collected 2 items

test_bdd_scen.py::test_ios SKIPPED (matched)                                                                     [ 50%]
test_bdd_scen.py::test_verify_markers PASSED                                                                     [100%]

============================================ 1 passed, 1 skipped in 0.08s =============================================
```
As you can see, I use pytest-bdd 4.0.2 with pytest 6.2.2 under Python 3.7. 
What versions and environment are you using?

**Comment by aniket02k** [comment]
I am using below versions
`Python 3.6.8`, `pytest-6.2.2`, `bdd-4.0.2`

**Comment by mrbean-bremen** [comment]
As @RonnyPfannschmidt already wrote, this is very likely not a pytest issue. You can try to raise an issue with pytest-bdd - without being able to reproduce the issue it is difficult to help you.

**Comment by The-Compiler** [comment]
Works fine for me as well. I suppose reporting it to pytest-bdd won't get anywhere either as long as there's no reproducer for this...

@aniket02k Could you please show the full pytest output with that reproducer?

**Comment by aniket02k** [comment]
Hi @mrbean-bremen @The-Compiler @RonnyPfannschmidt,
Have used pytest-bdd's approach for skipping the test case and it worked as expecetd.

Below is the sample code:
```
def pytest_bdd_apply_tag(tag, function):
    if tag == 'todo':
        marker = pytest.mark.skip(reason="Not implemented yet")
        marker(function)
        return True
    else:
        # Fall back to pytest-bdd's default behavior
        return None
 ```

**Comment by nicoddemus** [comment]
If you have access to the test item/node, you could use [Node.add_marker](https://docs.pytest.org/en/stable/reference.html#pytest.nodes.Node.add_marker) as well (in fact it might be preferable as that's the public API to apply markers to items).
