### ISSUE TITLE
Make backward-compatibility magic optional

### ISSUE THREAD

**Issue by nedbat** [pytest-dev/pytest#8424]
I had some trouble with getting my large test suite to work properly with pytest. A debugging session revealed that I was using method names that pytest identified as "unittest" names, and then also as "nosetest" names.  Pytest treated the methods specially as a result.  Better for me would be if that helpful magic could be disabled, so that I get just-plain pytest.

My suggestion is to have options `--legacy=unittest` and `--legacy=nosetest`, and have to opt-in to that behavior.  This would be a breaking change, so making it opt-out instead of opt-in is also a reasonable path.

**Comment by RonnyPfannschmidt** [comment]
i believe we can leave unittest as is, and we should phase out nosetest as soon to be opt in

reason being that unittest needs explicit inheritance, while nose messes in the same space as pytest

i propose to turn nosetest into a opt-out first, and migrate it to a opt-in with warnings for nose methods, eventually dropping nose support alltogether

**Comment by nedbat** [comment]
I had problems with naming a method "setUp", even without the unittest inheritance.  Was that the nose magic kicking in?

**Comment by bluetech** [comment]
The opt out for nose is `-p no:nose`.

**Comment by bluetech** [comment]
Closing as opt-out is possible as described above, and will track deprecation in #6973.
