### ISSUE TITLE
xprocess log prints empty tuple

### ISSUE THREAD

**Issue by cr3** [pytest-dev/pytest#843]
The log attribute of an XProcess instance is an instance of this class:

```
            class Log:
                def debug(self, msg, *args):
                    if args:
                        print (msg % args)
                    else:
                        print (args)
```

The problem with the `debug` method is that when `args` evaluates to false, ie when the message is only called with `msg`, then an empty tuple is printed. Most of the code calls the `debug` method with both arguments except in the `_checkpattern` private method which ends up printing `()` for each log line.

**Comment by nicoddemus** [comment]
Thanks for the report!

Could you open a PR in `pytest-xprocess` itself with this change?

**Comment by RonnyPfannschmidt** [comment]
thanks for the work,.depending on time it might be until after EP that holger can merge it
