### ISSUE TITLE
add more docs on the fspath deprecation

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#8445]
provide more help for testing and general code handling it

_Originally posted by @RonnyPfannschmidt in https://github.com/pytest-dev/pytest/discussions/8418#discussioncomment-452556_

**Comment by h-vetinari** [comment]
Since #8037 has gone in, this should probably be remilestoned to 7.0? CC @The-Compiler 

PS. The GH UI looks mighty confusing with renamed milestones:

![pytest_7 0](https://user-images.githubusercontent.com/33685575/123796106-0f419a00-d8e5-11eb-8c67-08802add6079.png)

**Comment by nicoddemus** [comment]
Fixed, thanks!

**Comment by nicoddemus** [comment]
Ahh no sorry, this is correct, it should be removed from 7.0 but will be released in a future version.

**Comment by h-vetinari** [comment]
> 
> 
> Ahh no sorry, it should be removed from 7.0 but will be released in a future version.

How so? It's already released, no? Quoting from #8418 (which is what this issues was about)



> > > > hl037: From here: ~https://docs.pytest.org/en/latest/reference.html#request~ [fixed [link](https://docs.pytest.org/en/latest/reference/reference.html#pytest.FixtureRequest.fspath)]
> > > > I can see request.fspath will be deprecated. I can't find information about this decision and I was wondering what could I use instead to get the current test path ?
> > > 
> > > @RonnyPfannschmidt: Good catch, the path alias needs to be added there, `request.node.path` will do meanwhile
> >
> > @nicoddemus: we have a short notice here: https://docs.pytest.org/en/latest/deprecations.html#node-fspath-in-favor-of-pathlib-and-node-path
> >
> > However I wonder if we should expand that? We only mention some kind of reasoning briefly:
> > 
> > > As pytest tries to move off py.path.local we ported most of the node internals to pathlib.
> >
> > Should we expand/create a new section with the rationale and future plans?
>
> @RonnyPfannschmidt: we should

**Comment by The-Compiler** [comment]
Yeah, it sounds like this should be in 7.0. The fspath deprecation is in 7.0, so I suppose we should also have proper deprecation docs there. Let's add it for now and then look at it in detail later before the final release.
