### ISSUE TITLE
Add support to skip testcase by its name or string match in name

### ISSUE THREAD

**Issue by vipkum2** [pytest-dev/pytest#8452]
#### What's the problem this feature will solve?
Currently as I am aware we need to add the pytest skip fixture(@pytest.mark.skip/skip-if) before the test case.

Many times we need to skip the testcase with reasons like failure, functionality, depends on other, to do the same each time we need to modify the script, then add it to git(version control), review it , push it, after this we can execute the same in mainline.

#### Describe the solution you'd like
There should be an option like --skip then provide test name string to skip the one and all(depends test case string match)
like: --skip "test01, test02" , it could be list or string.

#### Alternative Solutions
we only have workaround to mark each test first, then skip.
@pytest.mark.skip/skip-if

**Comment by The-Compiler** [comment]
From `pytest --help` (emphasis mine):

>  -k EXPRESSION         only run tests which match the given substring expression. An expression is a python evaluatable expression where all names are substring-matched against test names and their parent classes. Example: -k
>                        'test_method or test_other' matches all test functions and classes whose name contains 'test_method' or 'test_other', **while -k 'not test_method' matches those that don't contain 'test_method' in their names**. -k
>                        'not test_method and not test_other' will eliminate the matches. Additionally keywords are matched to classes and functions containing extra names in their 'extra_keyword_matches' set, as well as functions which
>                        have names assigned directly to them. The matching is case-insensitive.

**Comment by vipkum2** [comment]
Yes we have -k , to run the matching cases, but we don't have anything to skip with test name. like - 
`def test01_dosum
def test02_dosum
def test03_dosum`
So if I give -k dosum it will run all 3. but what should I give command line param to skip the case test02_dosum.
I think we need to edit the file, then need to @pytest.mark.skip, then we can skip the same.
But We should also have something to provide in command line.

**Comment by The-Compiler** [comment]
Did you see the part in bold?

**Comment by vipkum2** [comment]
So it is like if I give -k 'not test02' , then it will execute test01 and test03. right ?
if it is right. So I have got my answer .

Thanks a lot @The-Compiler  !!!!
