### ISSUE TITLE
--ignore option doesn't work

### ISSUE THREAD

**Issue by olgert** [pytest-dev/pytest#846]
I'm using Python 3.4.3 and pytest 2.7.2.
Running `py.test --collect-only --ignore=path/to/file.py` collects tests for me that should be ignored.

**Comment by The-Compiler** [comment]
How can this be reproduced? Seems to work fine here:

```
$ cat test_foo.py
def test_foo():
    pass

$ py.test --collect-only
platform linux -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.2
collected 1 items 
<Module 'test_foo.py'>
  <Function 'test_foo'>

$ py.test --collect-only --ignore=test_foo.py
collected 0 items 
```

(I removed some lines from the output for brevity)

**Comment by olgert** [comment]
Hmm, this basic case works for me in freshly created virtualenv, but does not in my projects' virtualenv. It looks like some of installed packages make an influence on that.

**Comment by The-Compiler** [comment]
i haven't looked at the implementation of `--ignore`, but that sounds odd. Can you show `pip freeze` in the affected virtualenv?

Random guess: Maybe you're running the `pytest` binary which comes with logilab-common which in turn comes with pylint? You'd notice by the lack of colors, for example. If that's the case, try `python -m py.test` instead.

**Comment by olgert** [comment]
Looks like I found that package `pytest-gitignore==1.2` which overrides original `pytest_ignore_collect(path, config)`. I'm not yet familiar with pytest's plugin model, but is it possible to inherit default behavior in overridden `pytest_ignore_collect(path, config)`? Or even better, just to own ignore handler into pipeline? This plugin is quite useful, though.

**Comment by nicoddemus** [comment]
You can inherit the default behavior by using the new `hookwrapper` mechanism, for example:

```python
@pytest.mark.hookwrapper
def pytest_ignore_collect(path, config):
    outcome = yield
    if not output.get_result():
        # not ignored by the default hook
        if git_ignore_check_path(path):
            outcome.force_result(True)
```

But this will have to be implemented in [pytest-gitignore](https://github.com/tgs/pytest-gitignore), so I suggest creating an issue or opening a PR there. :smile:

Closing this as I think there's not much more to do here.

**Comment by tgs** [comment]
@nicoddemus - thank you for the example code!

**Comment by nicoddemus** [comment]
:+1: :smile:
