### ISSUE TITLE
Redirect old doc pages to new locations

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#8471]
As part of the docs restructuring #8443 some pages are moved, so the old URLs now return 404. Some of these pages have a lot of incoming links so I think it's important to keep them working.

First we need to create a list of pages we want to keep working (TODO).

Then we need to implement the redirects. I think there are two ways to go about that:

1. HTTP redirects - requires server configuration. Looks like ReadTheDocs [can do it](https://docs.readthedocs.io/en/stable/user-defined-redirects.html).
2. HTML redirects - requires placeholder pages with `<meta refresh>`. Can use a [sphinx plugin](https://pypi.org/project/sphinx-reredirects/) to do it or implement one ourselves. 

I think server redirects are easier and more recommended. I can add them unless someone objects (I would need permissions for RTD though).

**Comment by nicoddemus** [comment]
> I think server redirects are easier and more recommended. 

But perhaps HTML redirects are easier to maintain, because anybody who contributes documentation can write the redirect directive?

**Comment by jsoref** [comment]
So, there are only [~2000 places in GitHub](https://github.com/search?q=%22docs.pytest.org%2Fen%2Flatest%2Fwarnings.html%22&type=code) that link to https://docs.pytest.org/en/latest/warnings.html 

One of the places that links to this page is https://docs.pytest.org/en/stable/warnings.html:
![direct link from stable](https://user-images.githubusercontent.com/2119212/113609287-900c3500-9619-11eb-911d-f963da568be9.png)

Perhaps it would be a good idea for the website not to directly link to a page that doesn't exist.

In case you're wondering, this is what the page looks like today:
![ad for Digital Ocean](https://user-images.githubusercontent.com/2119212/113609426-bd58e300-9619-11eb-9186-c8b47061d19c.png)

**Comment by jsoref** [comment]
For more fun, one might reasonably expect that clicking on the cute little box at the bottom right of https://docs.pytest.org/en/latest/warnings.html#pytest-mark-filterwarnings
![image](https://user-images.githubusercontent.com/2119212/113613490-50484c00-961f-11eb-9bb1-218eecad3244.png)
would take one to the right page, e.g. https://docs.pytest.org/en/stable/warnings.html#pytest-mark-filterwarnings, but one would be wrong. Go Directly to https://docs.pytest.org/en/stable/404.html do not collect 💰 200.

**Comment by The-Compiler** [comment]
I went ahead and added a RTD redirect from `/en/latest/warnings.html` -> `/en/latest/how-to/capture-warnings.html`, so at least that one works correctly. There's probably more, and I have no idea how to handle this for multiple versions (there's a "page redirect", but doing that redirect for the old versions would be wrong...).

**Comment by nicoddemus** [comment]
> so at least that one works correctly.

That's great! We now know how to point that out during review when docs get moved around.

**Comment by rahul-kumi** [comment]
I managed to analyse the _**getindex.html**_ of both the [`latest`](https://docs.pytest.org/en/latest/genindex.html)  and [`stable`](https://docs.pytest.org/en/stable/genindex.html)  versions of the documentation, hope the below information helps in identifying the links that need fixing.
- List of items that were present only in `latest` but not in `stable` version of the index:
```
(Node property)
(RunResult attribute)
(Session property)
(TempPathFactory method)
(Testdir.Session property)
CallInfo (class in pytest)
ExceptionInfo (class in pytest)
Mark (class in pytest)
MarkDecorator (class in pytest)
MarkGenerator (class in pytest)
Metafunc (class in pytest)
duration (CallInfo attribute)
excinfo (CallInfo attribute)
from_call() (CallInfo class method)
getbasetemp() (TempdirFactory method)
mkdir() (Cache method)
mktemp() (TempdirFactory method)
path (Node attribute)
result() (CallInfo property)
sections (CollectReport attribute)
stardir() (Pytester.Session property)
start (CallInfo attribute)
startpath() (Pytester.Session property)
stop (CallInfo attribute)
tmp_path_factory
when (CallInfo attribute)
```
- List of items that were present only in `stable` but not in `latest` version of the index:
```
(Testdir attribute)
CLOSE_STDIN (Pytester attribute)
CallInfo (class in _pytest.runner)
ExceptionInfo (class in _pytest._code)
Mark (class in _pytest.mark.structures)
MarkDecorator (class in _pytest.mark)
MarkGenerator (class in _pytest.mark)
Metafunc (class in _pytest.python)
_pytest.tmpdir.tmp_path_factory
duration (RunResult attribute)
fspath (Node attribute)
mkdir() (Pytester method)
sections (TestReport attribute)
when (TestReport attribute)
```
- List of items that had a different path in `latest` than in the `stable` version of the index:
```
{
    "module (Metafunc attribute)": {
        "latest_path": "reference/reference.html#pytest.Metafunc.module",
        "stable_path": "reference.html#pytest.python.Metafunc.module"
    },
    "combined_with() (Mark method)": {
        "latest_path": "reference/reference.html#pytest.Mark.combined_with",
        "stable_path": "reference.html#pytest.mark.structures.Mark.combined_with"
    },
    "name() (MarkDecorator property)": {
        "latest_path": "reference/reference.html#pytest.MarkDecorator.name",
        "stable_path": "reference.html#pytest.mark.MarkDecorator.name"
    },
    "kwargs() (MarkDecorator property)": {
        "latest_path": "reference/reference.html#pytest.MarkDecorator.kwargs",
        "stable_path": "reference.html#pytest.mark.MarkDecorator.kwargs"
    },
    "config (Metafunc attribute)": {
        "latest_path": "reference/reference.html#pytest.Metafunc.config",
        "stable_path": "reference.html#pytest.python.Metafunc.config"
    },
    "(Mark attribute)": {
        "latest_path": "reference/reference.html#pytest.Mark.args",
        "stable_path": "reference.html#pytest.mark.structures.Mark.args"
    },
    "parametrize() (Metafunc method)": {
        "latest_path": "reference/reference.html#pytest.Metafunc.parametrize",
        "stable_path": "reference.html#pytest.python.Metafunc.parametrize"
    },
    "match() (ExceptionInfo method)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.match",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.match"
    },
    "from_current() (ExceptionInfo class method)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.from_current",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.from_current"
    },
    "typename() (ExceptionInfo property)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.typename",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.typename"
    },
    "kwargs (Mark attribute)": {
        "latest_path": "reference/reference.html#pytest.Mark.kwargs",
        "stable_path": "reference.html#pytest.mark.structures.Mark.kwargs"
    },
    "fixturenames (Metafunc attribute)": {
        "latest_path": "reference/reference.html#pytest.Metafunc.fixturenames",
        "stable_path": "reference.html#pytest.python.Metafunc.fixturenames"
    },
    "exconly() (ExceptionInfo method)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.exconly",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.exconly"
    },
    "for_later() (ExceptionInfo class method)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.for_later",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.for_later"
    },
    "fill_unfilled() (ExceptionInfo method)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.fill_unfilled",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.fill_unfilled"
    },
    "value() (ExceptionInfo property)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.value",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.value"
    },
    "definition (Metafunc attribute)": {
        "latest_path": "reference/reference.html#pytest.Metafunc.definition",
        "stable_path": "reference.html#pytest.python.Metafunc.definition"
    },
    "type() (ExceptionInfo property)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.type",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.type"
    },
    "tb() (ExceptionInfo property)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.tb",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.tb"
    },
    "function (Metafunc attribute)": {
        "latest_path": "reference/reference.html#pytest.Metafunc.function",
        "stable_path": "reference.html#pytest.python.Metafunc.function"
    },
    "from_exc_info() (ExceptionInfo class method)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.from_exc_info",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.from_exc_info"
    },
    "args() (MarkDecorator property)": {
        "latest_path": "reference/reference.html#pytest.MarkDecorator.args",
        "stable_path": "reference.html#pytest.mark.MarkDecorator.args"
    },
    "with_args() (MarkDecorator method)": {
        "latest_path": "reference/reference.html#pytest.MarkDecorator.with_args",
        "stable_path": "reference.html#pytest.mark.MarkDecorator.with_args"
    },
    "(TestReport attribute)": {
        "latest_path": "reference/reference.html#pytest.reports.TestReport.when",
        "stable_path": "reference.html#pytest.reports.TestReport.user_properties"
    },
    "cls (Metafunc attribute)": {
        "latest_path": "reference/reference.html#pytest.Metafunc.cls",
        "stable_path": "reference.html#pytest.python.Metafunc.cls"
    },
    "errisinstance() (ExceptionInfo method)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.errisinstance",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.errisinstance"
    },
    "name (Mark attribute)": {
        "latest_path": "reference/reference.html#pytest.Mark.name",
        "stable_path": "reference.html#pytest.mark.structures.Mark.name"
    },
    "(Pytester method)": {
        "latest_path": "reference/reference.html#pytest.Pytester.mkdir",
        "stable_path": "reference.html#pytest.Pytester.chdir"
    },
    "traceback() (ExceptionInfo property)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.traceback",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.traceback"
    },
    "getrepr() (ExceptionInfo method)": {
        "latest_path": "reference/reference.html#pytest.ExceptionInfo.getrepr",
        "stable_path": "reference.html#pytest._code.ExceptionInfo.getrepr"
    }
}
```
PS: The analysis took into account the `\reference` prefix to the paths included in the `latest` version when comparing with the `stable` version.

**Comment by The-Compiler** [comment]
Thanks @rahul-kumi! However, your analysis only covers different classes/functions on the `reference.html` page - I think it's okay if those links break, as the actual objects themselves changed between versions too.

The much more critical thing are moved *pages*, such as with the earlier `warnings.html` example.

**Comment by The-Compiler** [comment]
Like also mentioned earlier, I suppose it's not always that easy, as one page (in the old docs) typically got split into three (in the new docs). For example, should the old [fixture docs](https://docs.pytest.org/en/6.2.x/fixture.html) now redirect to:

- [The fixtures how-to](https://docs.pytest.org/en/latest/how-to/fixtures.html)
- [The fixtures explanation](https://docs.pytest.org/en/latest/explanation/fixtures.html)
- [The fixtures reference](https://docs.pytest.org/en/latest/reference/fixtures.html)

It's tricky, and I wish we'd have given this more consideration when restructuring those docs...

I'm wondering if we should just reintroduce a `doc/fixtures.rst` "fixtures overview" or "fixtures topic" page which is a small stub linking to the other three? That way:

- We wouldn't have go through the churn of fixing all links
- We wouldn't need to decide where to redirect to (in case one page got split into three)
- Instead of multiple "see also" boxes, we could just redirect to a single overview page from the three sub-pages
- Yet any old links will continue to work properly, even when switching between versions, without any redirects or other hacks

What do others think? @evildmp @bluetech

cc @DrGFreeman who offered to help with #8831 - what I'd propose here is to introduce those "stub" pages for 7.0 instead of having to change all links (especially because there are many external links to the old locations which are out of our control, and with the 7.0 release, even links going to `/stable/` will break).

**Comment by jsoref** [comment]
@The-Compiler: If a page was split, then yes, having a see-also page in its place that just links to the split items is a good strategy.

If your goal is to eventually cause the page to be really eligible for deletion, you might do is something like:

`doc/fixtures.rst` (define as a 301 redirect (?) => `doc/fixtures.split.rst` or even `doc/fixtures.split.6.rst` or `doc/split/6/fixtures.rst` to record when the split happened)
-- I think that pages that land as redirects might be penalized from search indexes. https://www.searchenginejournal.com/301-redirect-pagerank/275503/ talks decaying page rank (note that search algorithm behavior is not static, and I've never worked for/on a search engine).

Have neither page listed in your index.

Later, you could check visit counts to see if the page has sufficiently fallen off page rank that you could remove it entirely.

**Comment by nicoddemus** [comment]
I like the stub approach, and I suppose it could even stay around "forever" given how much those links exist over the web. 👍

**Comment by The-Compiler** [comment]
Okay I think I got redirects for everything set up via RTD:


| old (stable) | new (latest) | redirect (latest with old path) | notes |
| -- | -- | -- | -- |
| [/flaky.html](https://docs.pytest.org/en/stable/flaky.html) | [/explanation/flaky.html](https://docs.pytest.org/en/latest/explanation/flaky.html) | [redirect](https://docs.pytest.org/en/latest/flaky.html) |  |
| [/goodpractices.html](https://docs.pytest.org/en/stable/goodpractices.html) | [/explanation/goodpractices.html](https://docs.pytest.org/en/latest/explanation/goodpractices.html) | [redirect](https://docs.pytest.org/en/latest/goodpractices.html) |  |
| [/pythonpath.html](https://docs.pytest.org/en/stable/pythonpath.html) | [/explanation/pythonpath.html](https://docs.pytest.org/en/latest/explanation/pythonpath.html) | [redirect](https://docs.pytest.org/en/latest/pythonpath.html) |  |
| [/assert.html](https://docs.pytest.org/en/stable/assert.html) | [/how-to/assert.html](https://docs.pytest.org/en/latest/how-to/assert.html) | [redirect](https://docs.pytest.org/en/latest/assert.html) |  |
| [/bash-completion.html](https://docs.pytest.org/en/stable/bash-completion.html) | [/how-to/bash-completion.html](https://docs.pytest.org/en/latest/how-to/bash-completion.html) | [redirect](https://docs.pytest.org/en/latest/bash-completion.html) |  |
| [/cache.html](https://docs.pytest.org/en/stable/cache.html) | [/how-to/cache.html](https://docs.pytest.org/en/latest/how-to/cache.html) | [redirect](https://docs.pytest.org/en/latest/cache.html) |  |
| [/capture.html](https://docs.pytest.org/en/stable/capture.html) | [/how-to/capture-stdout-stderr.html](https://docs.pytest.org/en/latest/how-to/capture-stdout-stderr.html) | [redirect](https://docs.pytest.org/en/latest/capture.html) |  |
| [/warnings.html](https://docs.pytest.org/en/stable/warnings.html) | [/how-to/capture-warnings.html](https://docs.pytest.org/en/latest/how-to/capture-warnings.html) | [redirect](https://docs.pytest.org/en/latest/warnings.html) |  |
| [/doctest.html](https://docs.pytest.org/en/stable/doctest.html) | [/how-to/doctest.html](https://docs.pytest.org/en/latest/how-to/doctest.html) | [redirect](https://docs.pytest.org/en/latest/doctest.html) |  |
| [/existingtestsuite.html](https://docs.pytest.org/en/stable/existingtestsuite.html) | [/how-to/existingtestsuite.html](https://docs.pytest.org/en/latest/how-to/existingtestsuite.html) | [redirect](https://docs.pytest.org/en/latest/existingtestsuite.html) |  |
| [/logging.html](https://docs.pytest.org/en/stable/logging.html) | [/how-to/logging.html](https://docs.pytest.org/en/latest/how-to/logging.html) | [redirect](https://docs.pytest.org/en/latest/logging.html) |  |
| [/mark.html](https://docs.pytest.org/en/stable/mark.html) | [/how-to/mark.html](https://docs.pytest.org/en/latest/how-to/mark.html) | [redirect](https://docs.pytest.org/en/latest/mark.html) |  |
| [/monkeypatch.html](https://docs.pytest.org/en/stable/monkeypatch.html) | [/how-to/monkeypatch.html](https://docs.pytest.org/en/latest/how-to/monkeypatch.html) | [redirect](https://docs.pytest.org/en/latest/monkeypatch.html) |  |
| [/nose.html](https://docs.pytest.org/en/stable/nose.html) | [/how-to/nose.html](https://docs.pytest.org/en/latest/how-to/nose.html) | [redirect](https://docs.pytest.org/en/latest/nose.html) |  |
| [/parametrize.html](https://docs.pytest.org/en/stable/parametrize.html) | [/how-to/parametrize.html](https://docs.pytest.org/en/latest/how-to/parametrize.html) | [redirect](https://docs.pytest.org/en/latest/parametrize.html) |  |
| [/plugins.html](https://docs.pytest.org/en/stable/plugins.html) | [/how-to/plugins.html](https://docs.pytest.org/en/latest/how-to/plugins.html) | [redirect](https://docs.pytest.org/en/latest/plugins.html) |  |
| [/skipping.html](https://docs.pytest.org/en/stable/skipping.html) | [/how-to/skipping.html](https://docs.pytest.org/en/latest/how-to/skipping.html) | [redirect](https://docs.pytest.org/en/latest/skipping.html) |  |
| [/tmpdir.html](https://docs.pytest.org/en/stable/tmpdir.html) | [/how-to/tmpdir.html](https://docs.pytest.org/en/latest/how-to/tmpdir.html) | [redirect](https://docs.pytest.org/en/latest/tmpdir.html) |  |
| [/unittest.html](https://docs.pytest.org/en/stable/unittest.html) | [/how-to/unittest.html](https://docs.pytest.org/en/latest/how-to/unittest.html) | [redirect](https://docs.pytest.org/en/latest/unittest.html) |  |
| [/writing_plugins.html](https://docs.pytest.org/en/stable/writing_plugins.html) | [/how-to/writing_plugins.html](https://docs.pytest.org/en/latest/how-to/writing_plugins.html) | [redirect](https://docs.pytest.org/en/latest/writing_plugins.html) |  |
| [/xunit_setup.html](https://docs.pytest.org/en/stable/xunit_setup.html) | [/how-to/xunit_setup.html](https://docs.pytest.org/en/latest/how-to/xunit_setup.html) | [redirect](https://docs.pytest.org/en/latest/xunit_setup.html) |  |
| [/customize.html](https://docs.pytest.org/en/stable/customize.html) | [/reference/customize.html](https://docs.pytest.org/en/latest/reference/customize.html) | [redirect](https://docs.pytest.org/en/latest/customize.html) |  |
| [/reference.html](https://docs.pytest.org/en/stable/reference.html) | [/reference/reference.html](https://docs.pytest.org/en/latest/reference/reference.html) | [redirect](https://docs.pytest.org/en/latest/reference.html) |  |

Had some trouble getting some of those to work, but I'll test with a fresh browser instance after submitting this comment.

**Comment by DrGFreeman** [comment]
Great! I'll get working on the new stubs and adding "see also" sections to the new pages that were split.

**Comment by DrGFreeman** [comment]
@The-Compiler, I started working on the stubs pages but I realized that they need to be referenced by a table of content somewhere otherwise a warning is issued on build and with the `-W` option in the `sphinx-build` command the build fails.

The new [explanation/fixtures.html](https://docs.pytest.org/en/latest/explanation/fixtures.html) and [how-to/usage.html](https://docs.pytest.org/en/latest/how-to/usage.html) pages both already include "See also" sections with links to the other relevant pages at the top so I think that additional stub pages would not provide much additional value and would add unnecessary clutter the table of content and more links to click for the users encountering a link in a warning message or elsewhere.

Instead of new stub pages, I believe we could just have redirects to those pages:
`fixture.html` -> `explanation/fixtures.html`
`usage.html` -> `how-to/usage.html`

Let me know what you think.

**Comment by The-Compiler** [comment]
You can use [`:orphan:`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html#metadata) at the top of the file to suppress that warning.

The main thing I was worried about is someone getting a link to the old `fixture.html`, but whatever topic was linked to isn't there - with the stub pages we would make that explicit and the user knows to check those three pages, but with the redirects it's a bit more subtle. But maybe you're right, and the redirects are enough - so I'd propose I'll add them in RTD, we'll close this issue, and then we'll see how it goes.

I'll also open a PR to change all links in the source to the new locations despite the redirects. I hope it's okay if I take over there - given that we now have a list, this should be easy to automate.

**Comment by The-Compiler** [comment]
I added redirects for the two remaining pages:

| old (stable) | new (latest) | redirect (latest with old path) | notes |
| -- | -- | -- | -- |
| [/fixture.html](https://docs.pytest.org/en/stable/fixture.html) | [/explanation/fixtures.html](https://docs.pytest.org/en/latest/explanation/fixtures.html) | [redirect](https://docs.pytest.org/en/latest/fixture.html) |  |
| [/usage.html](https://docs.pytest.org/en/stable/usage.html) | [/how-to/usage.html](https://docs.pytest.org/en/latest/how-to/usage.html) | [redirect](https://docs.pytest.org/en/latest/usage.html) |  |

so this should be all done now!

**Comment by The-Compiler** [comment]
TIL that you can add reverse redirects too, as page redirects will only trigger if no matching page was found in the docs. After a lot of clicking in RTD's webinterface I now added another 25 reverse redirects, so that e.g. switching between 7.0.0 (latest) and pre-7 (stable) works fine now!
