### ISSUE TITLE
collections importing DeprecationWarning

### ISSUE THREAD

**Issue by adventurerka** [pytest-dev/pytest#8483]
Hi!

I use pyparsing - 2.4.7 and  have two warnings in my tests:

pyparsing.py:696: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    collections.MutableMapping.register(ParseResults)

pyparsing.py:2273: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    elif isinstance( exprs, collections.Sequence ):

**Comment by RonnyPfannschmidt** [comment]
according to https://github.com/pyparsing/pyparsing/blob/pyparsing_2.4.7/pyparsing.py#L688-L699 and https://github.com/pyparsing/pyparsing/blob/pyparsing_2.4.7/pyparsing.py#L1206-L1211

your setup is broken - the lines just don't match up, please fix it
