### ISSUE TITLE
test_classes filter for unittest.TestCase

### ISSUE THREAD

**Issue by vallsv** [pytest-dev/pytest#8488]
Hi,

I spend some time to figure out that the ini option to filter classes `test_classes` is not working for `unitest.TestCase` classes.

Taking some times in the source code, it looks like the `unitest.TestCase` are not collected the same way other classes, 

Do you think it is a good idea to implement it, and do you think it is easy?

Is there another way to filter this classes? For now i skip them, but i would prefer not to see them as skipped.

Thanks a lot.

# Env

```
# Name                    Version                   Build  Channel
pytest                    6.2.2            py38h578d9bd_0    conda-forge
```

# Example

```
import unittest

class _Test:
    def test(self):
        pass

class _Abstract(unittest.TestCase):
    def test(self):
        pass

class TestForReal(_Abstract):
    def test(self):
        pass
```

# Toml

```
[tool.pytest.ini_options]
python_classes = ["Test"]
```

# Setup plan
```
test_v3.py 
      SETUP    C unittest_setUpClass_fixture__Abstract
        test_v3.py::_Abstract::test (fixtures used: request, unittest_setUpClass_fixture__Abstract)
      TEARDOWN C unittest_setUpClass_fixture__Abstract
      SETUP    C unittest_setUpClass_fixture_TestForReal
        test_v3.py::TestForReal::test (fixtures used: request, unittest_setUpClass_fixture_TestForReal)
      TEARDOWN C unittest_setUpClass_fixture_TestForReal
```
Notice that `_Test` was filtered but `_Abstract` was not.

**Comment by vallsv** [comment]
Just found in the code that i can use `__test__`, but for abstract class tests it's not very convenient, cause i have to patch specialized classes too.

```
class _Abstract(unittest.TestCase):
    __test__ = False
    def test(self):
        pass

class TestForReal(_Abstract):
    __test__ = True
    def test(self):
        pass
```

**Comment by nicoddemus** [comment]
Hi @vallsv thanks for writing.

> Do you think it is a good idea to implement it, and do you think it is easy?

We mimic how `unittest` itself collects classes, which is to collect any class which subclasses `unittest.TestCase`. I don't think we should deviate from that at all, TBH. Also honoring `python_classes` for `unittest.TestCase` would be a breaking change.

I'm closing this for now then, feel free to follow up with further questions.

**Comment by vallsv** [comment]
I see. It makes sens.
