### ISSUE TITLE
The finalizers for a test do not run in the same order they are registered

### ISSUE THREAD

**Issue by chilversc** [pytest-dev/pytest#8489]
### Steps to reproduce

```python
import pytest


@pytest.fixture
def first(request):
    def factory():
        print("SETUP instance")
        request.addfinalizer(lambda: print("TEARDOWN instance"))

    print("SETUP first")
    yield factory
    print("TEARDOWN first")


@pytest.fixture
def second(request):
    print("SETUP second")
    yield 1
    print("TEARDOWN second")


def test_order(request, first, second):
    print("SETUP test")
    request.addfinalizer(lambda: print("TEARDOWN test"))
    first()
```

### Expected Result

```
SETUP (1) first
SETUP (2) second
SETUP (3) test
SETUP (4) instance
TEARDOWN (4) instance
TEARDOWN (3) test
TEARDOWN (2) second
TEARDOWN (1) first
```

### Actual Result

```
SETUP (1) first
SETUP (2) second
SETUP (3) test
SETUP (4) instance
TEARDOWN (3) test
TEARDOWN (2) second
TEARDOWN (4) instance
TEARDOWN (1) first
```

### Background

I was creating a couple of fixtures that act as factories for test data that is too awkward to use as simple fixtures (too many variations / special cases).

These factories deal with an underlying database where there can be foreing keys between the records being created. This creates an unavoidable hidden dependency.

Because of the nature of these test (integration), a transaction cannot be used (the test spans multiple transactions). As such the factories register finalizers to delete the records when the test completes.

### Environment

* ubuntu 20.04
* python 3.9.2
* tox 3.23.0
* pytest f28421cc7068b13ba63c1f60cc21f898cccea36c (current main at time of reporting)

**Comment by RonnyPfannschmidt** [comment]
At first glance i think this is working exactly as intended

Finalizers run in reverse order, fixture teardown is a Finalizer

**Comment by RonnyPfannschmidt** [comment]
For more context the order reversal is req AS each new element may be building on a prior one

If the order is not reversed, teardowns would run in the wrong topology

**Comment by chilversc** [comment]
Sorry, copy/paste error. I transposed expected/actual.

**Comment by chilversc** [comment]
I've updated the description.

Also, while debugging it seems what is happening is each fixture gets its own request object with its own list of finalizers. So when the factory is called from the test, the finalizer is registered with the finalizers for the first fixture, instead of the test.

I can't see any nice way in the current system though to work-around that beyond having to pass request into every method.

E.g. this would work, but makes everything a lot more awkward and adding a finalizer to a factory later would require updating every call site:

```py
def factory(request, *args):
    ...
    request.addfinalizer(...)

def test_foo(request):
    item = factory(request, ...)
```

**Comment by chilversc** [comment]
I added some numbers to the test to make it easier to read the actual/expected.

**Comment by RonnyPfannschmidt** [comment]
thanks, i identified the bug, fixture request will use node.addfinalizer, a subrequest will not

this is a structural bug, it ma not be simple to fix it 

cc @nicoddemus

**Comment by bluetech** [comment]
IMO there is no bug here. The line

```py
request.addfinalizer(lambda: print("TEARDOWN instance"))
```

adds a finalizer to `first`, so it runs when `first` is finalized (i.e. along with the `TEARDOWN first` line).

The `SETUP instance` and `TEARDOWN instance` here are *not* a setup/teardown pair in pytest's eyes.
