### ISSUE TITLE
Numeric objects are restored

### ISSUE THREAD

**Issue by ThinkDone** [pytest-dev/pytest#8507]
class Test:

    @classmethod
    def setup_class(cls):
        cls.x = [0]
        cls.y = 0

    def setup_method(self, method):
        self.x[0] += 1
        self.y += 1

    def test_1(self):
        assert self.x[0] == 1
        assert self.y == 1

    def test_2(self):
        assert self.x[0] == 2
        assert self.y == 2

---------------------------------
    def test_2(self):
        assert self.x[0] == 2
\>      assert self.y == 2
E       assert 1 == 2

**Comment by The-Compiler** [comment]
Every test gets a new instance of the class - this is intended, and consistent with what e.g. unittest.py does as well:

```python
import unittest


class TestNumbers(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.x = [0]
        cls.y = 0

    def setUp(self):
        self.x[0] += 1
        self.y += 1

    def test_1(self):
        self.assertEqual(self.x[0], 1)
        self.assertEqual(self.y, 1)

    def test_2(self):
        self.assertEqual(self.x[0], 2)
        self.assertEqual(self.y, 2)
```

```
$ python3 -m unittest x.py
.F
======================================================================
FAIL: test_2 (x.TestNumbers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/florian/tmp/x.py", line 21, in test_2
    self.assertEqual(self.y, 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (failures=1)
```

Also see: https://docs.pytest.org/en/stable/getting-started.html#group-multiple-tests-in-a-class

**Comment by ThinkDone** [comment]
Thanks, should the two 0xdeadbeef addresses in the outlined at the end of the group-multiple-tests-in-a-class chapter be different?

**Comment by nicoddemus** [comment]
@ThinkDone you are right, we should at least add a note there and point to the relevant issue: https://github.com/pytest-dev/regendoc/issues/12. 👍 

Would you like to contribute a PR with that?

**Comment by The-Compiler** [comment]
Also see #7646 FWIW.
