### ISSUE TITLE
Fixture : scope "session" not working as expected

### ISSUE THREAD

**Issue by h-rueda** [pytest-dev/pytest#8525]
I have a function with the following decorator
**@pytest.fixture(scope = "session")**

The setup fixture is used in 2 different pytest **.py** files

Execute all tests from the command line

Actual result
The setup fixture is executed twice

Expected result
The setup fixture is executed once

Pytest version : 6.2.2

**Comment by RonnyPfannschmidt** [comment]
Without code we have no idea what you do

Do you use a contest or import?
