### ISSUE TITLE
ModuleNotFound error when a package with scripts installed in 'bin' is imported in conftest.py

### ISSUE THREAD

**Issue by lhupfeldt** [pytest-dev/pytest#8549]
Importing  'gherkin' (from gherkin-official) in conftest.py results in the following error:
```
[xxx@mb ttt]$ pytest 
sys.path: ['/home/xxx/src/ttt', '/home/xxx/.local/bin', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/home/xxx/.local/lib/python3.9/site-packages', '/home/xxx/src/jenkinsflow', '/usr/local/lib64/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/usr/lib64/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
ImportError while loading conftest '/home/xxx/src/ttt/conftest.py'.
conftest.py:5: in <module>
    import gherkin
../../.local/bin/gherkin.py:15: in <module>
    from gherkin.stream.gherkin_events import GherkinEvents
E   ModuleNotFoundError: No module named 'gherkin.stream'; 'gherkin' is not a package
```

A simple run of python works fine.
```
[xxx@mb ttt]$ python conftest.py
sys.path: ['/home/xxx/src/ttt', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/home/xxx/.local/lib/python3.9/site-packages', '/home/xxx/src/jenkinsflow', '/usr/local/lib64/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/usr/lib64/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
```

`conftest.py`:
```python
import sys

print("sys.path:", sys.path)

import gherkin
```

I don't know why pytest has 'bin' directory in sys.path.

The error is caused by a change to the installation of the imported package which now puts a `gherkin.py` in 'bin'.
```
ls .local/bin/gherkin*
.local/bin/gherkin  .local/bin/gherkin.py
```

Earlier there was only `gherkin`,  but no `gherkin.py` in 'bin' dir.

Pytest 6.2.3 and 5.3.5 tested.
Python version 3.9.2
gherkin-official 18.1.0
pip 21.0.1

**Comment by lhupfeldt** [comment]
The workaround is to use `python -m pytest` instead of `pytest`

**Comment by asottile** [comment]
this is unfortunately just how python works.  when you run a script it puts that directory onto `sys.path`

```console
$ echo $'#!/usr/bin/env python\nimport gherkin.stream' > venv/bin/wat
$ chmod +x venv/bin/wat
$ venv/bin/wat
Traceback (most recent call last):
  File "venv/bin/wat", line 2, in <module>
    import gherkin.stream
  File "/tmp/y/venv/bin/gherkin.py", line 15, in <module>
    from gherkin.stream.gherkin_events import GherkinEvents
ModuleNotFoundError: No module named 'gherkin.stream'; 'gherkin' is not a package
```

the `gherkin-official` package should stop placing `gherkin.py` inside the script dir and clobbering their own module namespace -- please report this to them

**Comment by lhupfeldt** [comment]
I have reported it there.
But I think it is a double error. The pytest script wrapper (generated by distutils?) should probably make sure the bin directory is removed from sys.path.

**Comment by asottile** [comment]
then report it to setuptools?  though I don't think that'll change since it'd break a basic expectation about how scripts and sys.path work

**Comment by lhupfeldt** [comment]
I don't think many people creating packages expect the bin dir to be in `sys.path`. `gherkin-official` is the first I've see to put both a script wrapper without extension and the same with the `.py` extension in `bin`. This quite different from directly excuting a python script which has not been installed.

**Comment by asottile** [comment]
yeah, like I said: gherkin is doing this wrong and should fix their self-inflicted mess
