### ISSUE TITLE
Warn when passing a string as a `plugins` of pytest.main

### ISSUE THREAD

**Issue by xmo-odoo** [pytest-dev/pytest#855]
This is definitely a case of user stupidity/laziness (in this case mine), but at one point to load a plugin without having to import it in the local scope I tried:

    pytest.main(args, plugins=['my.module.plugin'])

which didn't work, but also didn't output any warning or anything, so the tests ran but those which needed  said plugin (and the fixtures it provides) failed in various interesting manners.

It's really not a big deal, but it would still be neat if pytest errored or at least warned when a plugin is passed as a string.

**Comment by nicoddemus** [comment]
Thanks for the report! :smile:

I agree that it should provide a friendlier message.

**Comment by xmo-odoo** [comment]
@nicoddemus this issue can be closed since #860 was merged no?

**Comment by nicoddemus** [comment]
Yes, thanks for the reminder! :smile:
