### ISSUE TITLE
Fully retire 4.6.x?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#8558]
We still have 4.6.x listed as an active version on RTD, and the [Python 2.7 and 3.4 support](https://docs.pytest.org/en/stable/py27-py34-deprecation.html) page says:

> The core team will be happy to accept those patches, and make new 4.6.X releases **until mid-2020** (but consider that date as a ballpark, after that date the team might still decide to make new releases for critical bugs).

It's probably time to fully retire it, i.e. adjust that page (or perhaps remove it entirely, it's probably not relevant anymore nowadays) and mark the version as inactive on RTD?

The last commit in 4.6.x was #8054 in November 2020, the last release was 4.6.11 in June 2020.

**Comment by nicoddemus** [comment]
> It's probably time to fully retire it, i.e. adjust that page (or perhaps remove it entirely, it's probably not relevant anymore nowadays) and mark the version as inactive on RTD?

Probably we should just update it, so old links still find it and it presents the present status. We should however remove it from left table of contents of the main page.

**Comment by timhoffm** [comment]
Closed by #9957 / #9967.
