### ISSUE TITLE
`--color yes` does not color some output

### ISSUE THREAD

**Issue by barneygale** [pytest-dev/pytest#856]
Specifying `--color yes` on the command line fails to enable colors in some circumstances.

This affects `--fixtures` and `--markers` and possibly other parts of pytest.

This can be worked around by setting the `PY_COLORS` environment variable to `1`.

Reproduction steps:

1. In an empty directory, run: ``py.test --color yes --fixtures | cat``
2. Observe that the names of fixtures are not coloured green

**Comment by The-Compiler** [comment]
This seems to be because `pytest` uses various `TerminalWriter`s:

```
_pytest/genscript.py
73:        tw = py.io.TerminalWriter()

_pytest/helpconfig.py
65:    tw = py.io.TerminalWriter()

_pytest/pastebin.py
82:            tw = py.io.TerminalWriter(stringio=True)

_pytest/terminal.py
103:        self._tw = self.writer = py.io.TerminalWriter(file)

_pytest/python.py
965:    tw = py.io.TerminalWriter()

_pytest/config.py
38:            tw = py.io.TerminalWriter(sys.stderr)

_pytest/mark.py
48:        tw = py.io.TerminalWriter()

_pytest/pdb.py
42:            tw = py.io.TerminalWriter()
```

But only the one in `terminal.py` handles that option:

```python
        if self.config.option.color == 'yes':
            self._tw.hasmarkup = True
        if self.config.option.color == 'no':
            self._tw.hasmarkup = False
```

I don't really know what a clean way to fix this would be, though.

**Comment by nicoddemus** [comment]
I think a good solution would be to add a method to the config object:

```python
def create_terminal_writer(self):
    tw = py.io.TerminalWriter()
    if self.option.color == 'yes':
        tw.hasmarkup = True
    if self.config.option.color == 'no':
        tw.hasmarkup = False
    return tw
```

And everyone uses this method instead of creating a `TerminalWriter` manually.
