### ISSUE TITLE
Add an option to pause and continue the timer.

### ISSUE THREAD

**Issue by freaker2k7** [pytest-dev/pytest#8568]
I'm the author of the question from https://stackoverflow.com/questions/67090593/how-to-pause-pytest-timer
After I understood there is no way to do so I decided not to wait and add this option myself.
As Linus Torvalds nicely said: "The new way to complain is to pull a request" :)

I'm adding the ability to use pytest.StopTimer() & pytest.StartTimer() just as the ability that Golang has (as described in my question on stackoverflow).

This ability adds the option to measure the exact time your program runs without counting the bootstrap time, mostly for parametrized tests.

The answer for my question on stackoverflow gives solution to only single step tests, but there's no option to do so, after a thorough research, for parametrized tests neither for specific parts of a test itself.

I'm opening this issue to get an issue-id to complete the PR.

**Comment by RonnyPfannschmidt** [comment]
closing as out of scope for core as noted in the mr
