### ISSUE TITLE
miss count during pytest session is finished.

### ISSUE THREAD

**Issue by k3v8ns** [pytest-dev/pytest#8569]
summary : 
{'passed': 11, 'skipped': 5, 'failed': 5, 'total': 21, 'collected': 21}

Results (5.27s):
      32 passed
       5 failed
         - xxxx/raw/test_aaa.py:26 test_1e111[1]
         - xxxx/raw/test_aaa.py:26 test_1e111[2]
         - xxxx/raw/test_aaa.py:26 test_1e111[3]
         - xxxx/raw/test_aaa.py:26 test_1e111[4]
         - xxxx/raw/test_aaa.py:26 test_1e111[5]
       5 skipped

**Comment by The-Compiler** [comment]
You will really need to be a bit more verbose if you expect any useful answer - where is that output coming from (it doesn't look like pytest core from a quick glance)? How can this be reproduced?

**Comment by k3v8ns** [comment]
i write  a  pytest cases  for my own project . when the  test is  finished.  the passed results always miss count.

the  collector can find 21 cases to run . the result summaries is right. but  terminal print is not corrected.

**Comment by k3v8ns** [comment]
plugins: play-2.3.1, json-report-1.2.4, pypom-navigation-2.0.3, level-0.1.3, sugar-0.9.4, variables-1.9.0, html-3.1.1, xdist-2.2.1, metadata-1.11.0, dependency-0.5.1, splinter-3.3.1, timeout-1.4.2, forked-1.3.0
timeout: 14400.0s
timeout method: signal
timeout func_only: False

**Comment by k3v8ns** [comment]
Test session starts (platform: darwin, Python 3.9.4, pytest 6.2.3, pytest-sugar 0.9.4)

**Comment by nicoddemus** [comment]
Hi @k3v8ns,

That's unfortunately too little information to help you. Could you provide a reproducible example which shows your problem?
