### ISSUE TITLE
Broken links in faq

### ISSUE THREAD

**Issue by kbd** [pytest-dev/pytest#857]
In https://pytest.org/latest/faq.html, the following paragraph has broken links:

> Is using pytest fixtures versus xUnit setup a style question?
>
> For simple applications and for people experienced with **nose** or unittest-style test setup using xUnit style setup probably feels natural. For larger test suites, parametrized testing or setup of complex test resources using **funcargs** may feel more natural. 

I bolded the words that are broken links.

**Comment by nicoddemus** [comment]
Thanks! :smile:
