### ISSUE TITLE
A line break after Pytest's logs on console

### ISSUE THREAD

**Issue by ValaJeyhani** [pytest-dev/pytest#8574]
#### What's the problem this feature will solve?

Improving readability of console messages. Currently the Pytest's messages are followed by application log messages on the same line. For example:
```
[INFO] ...
[INFO] ...
PASSED[INFO]...
[INFO] ...
```

I think it would be beneficial to add a line break after Pytest's console logs.

**Comment by asottile** [comment]
Could you provide more information?  what code have you written which produces that output?

**Comment by ValaJeyhani** [comment]
Sure. Basically, I was hopping to be able to see the application logs in their own lines. Here is an example that can reproduce the problem:
`pytest.ini`:
```
[pytest]
testpaths =
    test_layer
python_files =
    test_*.py
```
`conftest.py`:
```
import logging

def pytest_configure(config):
    FORMAT = "[%(levelname)5s] " \
             + "%(asctime)s.%(msecs)03d " \
             + "{%(filename)s} " \
             + "%(message)s"
    logging.basicConfig(level=logging.INFO, format=FORMAT, datefmt="%H:%M:%S")
```
`test_example.py`:
```
import logging

log = logging.getLogger(__name__)

class TestExample():
    @classmethod
    def teardown_class(cls):
        log.info("Teardown")

    def test_1(self):
        log.info("info1")
        log.warning("warn1")
        log.error("error1")
        assert True

    def test_2(self):
        log.info("info2")
        log.warning("warn2")
        log.error("error2")
        assert True
```

And the output is:
```
=========================================================== test session starts ===========================================================
platform linux -- Python 3.7.3, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- <...>
<...>
plugins: dependency-0.5.1
collected 2 items

test_layer/test_example.py::TestExample::test_1 [ INFO] 16:10:44.572 {test_example.py} info1
[WARNING] 16:10:44.572 {test_example.py} warn1
[ERROR] 16:10:44.572 {test_example.py} error1
PASSED
test_layer/test_example.py::TestExample::test_2 [ INFO] 16:10:44.575 {test_example.py} info2
[WARNING] 16:10:44.576 {test_example.py} warn2
[ERROR] 16:10:44.576 {test_example.py} error2
PASSED[ INFO] 16:10:44.577 {test_example.py} Teardown
```

Two problems:
1. The first INFO logs follow the pytest message that specifies the test name (e.g. `test_layer/test_example.py::TestExample::test_1`) 
2. The INFO log in teardown follows `PASSED` message

**Comment by asottile** [comment]
ah so you're seeing interleaved output -- that's to be expected as pytest produces output as part of running

there isn't really a way to fix this without breaking pytest's output -- but you could put some extra `print()`s in there if you want

**Comment by ValaJeyhani** [comment]
Thanks for your confirmation.

**Comment by thisch** [comment]
@ValaJeyhani  FYI in your example in https://github.com/pytest-dev/pytest/issues/8574#issuecomment-828750810 you don't need a conftest.py file, because you can specify the logging options (`log_date_format`, `log_format` and  `log_level`) in `pytest.ini`.

**Comment by cbensimon** [comment]
Would have been great if something could be done
Running `pytest -v` produces this on most of the projects

**Comment by qnu** [comment]
@ValaJeyhani you can have a `print()` in your TestCase's `setup()`
