### ISSUE TITLE
expand node.fspath docs and add request.path as alternative to request.fspath

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#8576]
followup to https://github.com/pytest-dev/pytest/discussions/8418

we should make the future plans better known

**Comment by rahul-kumi** [comment]
Will the suggestion to use `request.path` go in the below section?
https://docs.pytest.org/en/latest/deprecations.html#node-fspath-in-favor-of-pathlib-and-node-path

**Comment by bluetech** [comment]
`request.path` exists now, and `fspath` is entirely gone outside of the legacypath plugin, so this is completed.
