### ISSUE TITLE
`pytest tests` from docs does not work as expected

### ISSUE THREAD

**Issue by burk** [pytest-dev/pytest#8578]
Hello,

I wanted to try out pytest on my unittest test suite. I tried to run `pytest tests` from this doc page: https://docs.pytest.org/en/stable/unittest.html but it seems that just looks for a folder named tests, which it doesn't find. Is that expected? Does the doc assume that I have all my tests in a `tests/` folder?

If I try running just `pytest` it starts collecting tests, but also tries to collect classes starting with `Test` which are not sub-classes of `TestCase`. Is it possible to avoid this? The docs suggests only subclasses of `TestCase` will be collected.

```
(python) > pytest tests  
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.8.6, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /xyz
collected 0 items                                                                                                                                                                                         

========================================================================================== no tests ran in 0.01s ==========================================================================================
ERROR: file or directory not found: tests
```

Error when just running `pytest` suggesting it tried to instantiate a non-TestCase class:
`TestX - TypeError: Can't instantiate abstract class TestX with abstract methods y, z`

**Comment by The-Compiler** [comment]
> but it seems that just looks for a folder named tests, which it doesn't find. Is that expected? Does the doc assume that I have all my tests in a `tests/` folder?

It does indeed - that's a quite common project layout.

> If I try running just `pytest` it starts collecting tests, but also tries to collect classes starting with `Test` which are not sub-classes of `TestCase`. Is it possible to avoid this? The docs suggests only subclasses of `TestCase` will be collected.

Does it? Where? See [this section of the docs](https://docs.pytest.org/en/stable/goodpractices.html#conventions-for-python-test-discovery) which explains this in more detail. Also see [Changing naming conventions](https://docs.pytest.org/en/stable/example/pythoncollection.html#changing-naming-conventions) if you want to avoid that.

**Comment by burk** [comment]
> Does it? Where? See [this section of the docs](https://docs.pytest.org/en/stable/goodpractices.html#conventions-for-python-test-discovery) which explains this in more detail. Also see [Changing naming conventions](https://docs.pytest.org/en/stable/example/pythoncollection.html#changing-naming-conventions) if you want to avoid that.

Well it doesn't suggest _only_ TestCase subclasses will be collected, so maybe that's just me optimistically reading the docs to fit my use-case:

> pytest will automatically collect unittest.TestCase subclasses and their test methods in test_*.py or *_test.py files.

(from the page I linked above)

I understand it's uncommon to have non-test-classes start with Test, so I'll look into changing those. Thanks for the clarification! And sorry for not reading the docs more thoroughly.
