### ISSUE TITLE
teardown exception reports both test pass and error

### ISSUE THREAD

**Issue by okken** [pytest-dev/pytest#8582]
- [ x] a detailed description of the bug or problem you are having

A fixture that asserts during teardown has the test show up as both pass and error.
Also, the numbers aren't right. The error test is showing up in both the passed count and the error count.

- [ x] output of `pip list` from the virtual environment you are using

$ pip list
Package    Version
---------- -------
attrs      20.3.0
iniconfig  1.1.1
packaging  20.9
pip        21.0.1
pluggy     0.13.1
py         1.10.0
pyparsing  2.4.7
pytest     6.2.3
setuptools 46.4.0
toml       0.10.2
wheel      0.34.2

- [x ] pytest and operating system versions

MacOS Big Sur 11.2.3
Python 3.9.1
pytest 6.2.3

- [ x] minimal example if possible

test_count.py:
```python
import pytest

@pytest.fixture()
def foo():
    yield
    assert False

def test_one():
    pass

def test_two(foo):
    pass

def test_three():
    pass
```

When run:
```
$ pytest -v --tb=no test_count.py
========================= test session starts ==========================
collected 3 items                                                      

test_count.py::test_one PASSED                                   [ 33%]
test_count.py::test_two PASSED                                   [ 66%]
test_count.py::test_two ERROR                                    [ 66%]
test_count.py::test_three PASSED                                 [100%]

======================= short test summary info ========================
ERROR test_count.py::test_two - assert False
====================== 3 passed, 1 error in 0.01s ======================
```

I would have expected test_two ERROR.
It's the PASSED that confuses me.
Also, it should say 2 passed, 1 error

**Comment by asottile** [comment]
so what happens here is the test body of `test_two` succeeds (marking it as `PASSED`) -- and then some time after that the fixture is torn down which errors (leading to an `ERROR` result).  this is (at least) ~roughly consistent with other test frameworks I've worked with (testify's `setup_teardown` gives pass+fail for failing teardowns, unittest gives pass+error for failing `tearDownClass`)

**Comment by rahul-kumi** [comment]
Shouldn't the expected behaviour be to fail stating: `ERROR at teardown of test2`
Is the `assert False` causing this behaviour?
