### ISSUE TITLE
approx() documentation page incorrectly compares with unittest as of 3.2

### ISSUE THREAD

**Issue by Pentracchiano** [pytest-dev/pytest#8587]
Hello!
While navigating on the docs, I found that the `approx()` documentation, while comparing its usage to the analogous function in `unittest`, says:

> unittest.TestCase.assertAlmostEqual(a, b): True if a and b are within an absolute tolerance of 1e-7. No relative tolerance is considered and the absolute tolerance cannot be changed, so this function is not appropriate for very large or very small numbers.

This statement is not true as of unittest version 3.2, as:

> Changed in version 3.2: [...] Added the delta keyword argument.

which lets a user choose the desired level of tolerance.

I am not a `pytest` user (yet), so I don't know what I could change that statement to, just pointing that out to someone who does.

**Comment by Zac-HD** [comment]
(docs for [pytest.approx()](https://docs.pytest.org/en/stable/reference.html#pytest-approx) and [assertAlmostEqual](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual))

Even now, `delta` only allows you to set a different absolute tolerance (not relative tolerance).  I'd therefore just delete the words "`and the absolute tolerance cannot be changed`" from our docs.  Would you like to open a pull request with this change?
