### ISSUE TITLE
Verbosity and --fixtures / --fixtures-per-test

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#8606]
Something that's usually interesting to know when checking what fixtures exist in a project is where exactly they are defined. In other words, imagine I'm looking at a test, and I want to know where those fixtures are coming from.

Intuitively, I'd run with `--fixtures-per-test`, which shows me the fixture names and docstrings, but I still don't know where they come from. I was today years old when I learned that adding `--verbose` will show that information.

I think there's nothing particularly verbose about it, though! It's just one line, which will usually fit on the same line as the fixture name anyways! However, something that's *very* verbose (sometimes) are the docstrings...

What about:

- Always showing the path to the fixtures
- Only showing the first line of the docstrings unless `--verbose` is given?

**Comment by nicoddemus** [comment]
Definitely 👍 

I don't use that option often, but using it now your proposal makes total sense (specially showing the first line of the docstring... I really don't need the full docs each time `monkeypatch` shows up 😁).

**Comment by symonk** [comment]
I like the idea 👍

**Comment by The-Compiler** [comment]
Fixed via #8626 - thanks @rahul-kumi!
