### ISSUE TITLE
Improving grammar in documentation Fixtures:Sharing Test Data

### ISSUE THREAD

**Issue by alshapton** [pytest-dev/pytest#8625]
"Sharing test data
If you want to make test data from files available to your tests, a good way to do this is by loading these data in a fixture for use by your tests. This makes use of the automatic caching mechanisms of pytest.

Another good approach is by adding the data files in the tests folder. There are also community plugins available to help managing this aspect of testing, e.g. pytest-datadir and pytest-datafiles."

SHOULD be:

"Sharing test data
If you want to make test data from files available to your tests, a good way to do this is by loading these data in a fixture for use by your tests. This makes use of the automatic caching mechanisms of pytest.

Another good approach is by adding the data files in the tests folder. There are also community plugins available to help **manage** this aspect of testing, e.g. pytest-datadir and pytest-datafiles."

**Comment by The-Compiler** [comment]
Well spotted, indeed! :+1:  @alshapton, would you like to open a pull request for this change? You can even do so [right from GitHub's web interface](https://github.com/pytest-dev/pytest/edit/main/doc/en/explanation/fixtures.rst).

**Comment by alshapton** [comment]
Done - waiting for PR to be reviewed and approved !

Thanks for letting me be part of your community - first contribution to OS
software !!!

Andrew
