### ISSUE TITLE
Please backport Python 3.10 fixes to 6.2.x

### ISSUE THREAD

**Issue by mgorny** [pytest-dev/pytest#8638]
Unless I'm mistaken, the 6.2.4 release seems to be entirely fine with Python 3.10, except for a bunch of test failures. The failures seem to be specifically related to tests themselves, and I've been able to get them to pass by cherry-picking the following commits:

913cffa45f9230087f589140604ec1eb5f199a83 f1570dc038585c8e5746f9bfdeb76321cd8be722 710446420c0bb98f0761724ec865a894820bb610 382599287f4cab914bd7502887072e7f325cdb09

Given that these commits do not affect anything but tests, could you please consider backporting them to 6.2.x branch?

**Comment by nicoddemus** [comment]
I wouldn't mind it being backported, would you like to open a PR with that?

**Comment by mgorny** [comment]
I could try doing that later today. Right now I'm a bit busy testing Python 3.10 for Gentoo.

**Comment by nicoddemus** [comment]
Closed by https://github.com/pytest-dev/pytest/pull/8639.
