### ISSUE TITLE
Add timestamp prefix before test output

### ISSUE THREAD

**Issue by mbkroese** [pytest-dev/pytest#8640]
#### What's the problem this feature will solve?
While the tests are running it is not clear how long a single test has been running.
By adding timestamps before the name of the test printed to the terminal we can infer how long it has been running

#### Describe the solution you'd like
Currently the output looks like this:

```
pytest -v
tests/my/path/to/test_func.py [PASSED [ 57%]
```

I would to be able set it to this:

```
pytest -v
2021-01-01 12:00:00 - tests/my/path/to/test_func.py [PASSED [ 57%]
```

But any date(time) format could be supported

Real world example:
We start the tests, they have been running for 1h. Has it been stuck for long on the last test that it is currently running?

#### Alternative Solutions
I could not find other plugins or CLI options to change this

**Comment by nicoddemus** [comment]
For Jenkins, there's https://plugins.jenkins.io/timestamper, which does exactly what you need.

This probably should be in a plugin, so I'm 👎 on adding this to the core.

**Comment by nicoddemus** [comment]
Hi @mbkroese,

Hmm indeed, it doesn't seem to be a clean way currently to extend that output to include timestamps. Subclassing `TerminalReporter` and overriding `_locationline` seems to be the only way currently to accomplish this.

**Comment by mbkroese** [comment]
In case anybody is interested, here is a plugin: https://github.com/mbkroese/pytest-timestamper

**Comment by nicoddemus** [comment]
Awesome, thanks for sharing!
