### ISSUE TITLE
pytest.warns(None) does not fail if warnings are raised.

### ISSUE THREAD

**Issue by Jasha10** [pytest-dev/pytest#8644]
I expect that `pytest.warns(None)` is an assertion that no warnings are raised.

```python
import warnings
import pytest

def test_no_warning():
    with pytest.warns(None):
        warnings.warn("Look out!")
```

Running pytest on the above does not fail. I would expect a failure, something like "a warning was raised where no warning was expected".

```
$ pip list
Package    Version
---------- -------------------
attrs      21.2.0
certifi    2020.12.5
iniconfig  1.1.1
packaging  20.9
pip        21.0.1
pluggy     0.13.1
py         1.10.0
pyparsing  2.4.7
pytest     6.2.4
setuptools 52.0.0.post20210125
toml       0.10.2
wheel      0.36.2
$ python --version
Python 3.9.4
```

OS: Ubuntu 18.04

**Comment by Zac-HD** [comment]
[See the docs](https://docs.pytest.org/en/doc-warnings/recwarn.html#recording-warnings):

> To record with `pytest.warns` without asserting anything about the warnings, pass `None` as the expected warning type

[This StackOverflow question](https://stackoverflow.com/questions/45671803/how-to-use-pytest-to-assert-no-warning-is-raised) shows how to assert that no warning was raised.

**Comment by Jasha10** [comment]
Awesome, thanks! Your answer to that SO question looks good :)
