### ISSUE TITLE
Reducing user confusion from `pytest.warns(None)`

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#8645]
`with pytest.warns(None):` has the same effect as `with pytest.warns(Warning):`, but is [often](https://github.com/pytest-dev/pytest/issues/8644) [confused](https://stackoverflow.com/questions/45671803/how-to-use-pytest-to-assert-no-warning-is-raised) with the meaning "does not emit any warning". I think we should therefore:

- change the docs to show `with pytest.warns()` (no arguments) as the catch-anything default
- change the default argument from `None` to `Warning`
- emit a deprecation warning if passed `None`, and treat it as `Warning` (for now)

*I'm saving this one for the [Mentored Sprints](https://www.mentored-sprints.dev/) - experienced contributors please wait a week or so :smiley:*

**Comment by olgarithms** [comment]
I would like to work on this :)

**Comment by Zac-HD** [comment]
Closed by #8677 🎉
