### ISSUE TITLE
pytest.raises() ignores unwanted exceptions

### ISSUE THREAD

**Issue by tweakimp** [pytest-dev/pytest#8675]
`pytest.raises()` ignores unwanted exceptions if they happen after an expected one.

```python
import pytest

with pytest.raises(ZeroDivisionError):
    1 / 0  # raises ZeroDivisionError
    1 + ""  # raises TypeError
```
This code runs with no error, although `1 + ""` raises a `TypeError` which is ignored by pytest.

```python
import pytest

with pytest.raises(ZeroDivisionError):
    1 + ""  # raises TypeError
    1 / 0  # raises ZeroDivisionError
```
If we swap the lines, the `TypeError` is raised correctly.
`TypeError: unsupported operand type(s) for +: 'int' and 'str'`

Do we expect `pytest.raises()` to assert that **only** the provided error (`ZeroDivisionError` in this case) is raised?
If no, I  would suggest to add an argument to the function that allows to restrict the function to only allow the provided error.

<details>
<summary>Environment</summary>
Windows 10 64bit  

Python 3.8.2   
pytest 6.2.4
</details>

**Comment by The-Compiler** [comment]
This is how exceptions work in Python (and also many other languages) - there's nothing pytest could do to change that. As soon as an exception happens, the control flow jumps out of the current block of code (in this case, to the `__exit__` of the `pytest.raises` context manager), and the rest won't run at all.

Compare:

```python
try:
    1 / 0  # raises ZeroDivisionError
    1 + ""  # raises TypeError
except ZeroDevisionError:
    pass
```

which will never run the second line of code either.

Also see the [note in the docs](https://docs.pytest.org/en/6.2.x/reference.html#pytest-raises) which explains essentially the same scenario.

**Comment by tweakimp** [comment]
Thank you for your fast answer.
Very unsatisfiying to see that there is no way to assert that the rest of the code is working as intended.

There must be a better way! *hits the table*

**Comment by The-Compiler** [comment]
That seems like an entirely different issue, but with your test, not with pytest.

That `TestModel(integer=2)` line raises a single `ValidationError` exception, as you can see when you remove the `pytest.raises`:

```
E   pydantic.error_wrappers.ValidationError: 2 validation errors for TestModel
E   string
E     field required (type=value_error.missing)
E   integer
E     ensure this value is greater than or equal to 3 (type=value_error.number.not_ge; limit_value=3)
```

If you want to make sure it only contains one error, you will need to check the exception object more carefully - perhaps using something like:

```python
    with pytest.raises(ValidationError) as excinfo:
        TestModel(integer=2)
    errors = excinfo.value.errors()
    assert len(errors) == 1
    assert errors[0]['msg'] == "ensure this value is greater than or equal to 3"
```

(note I know nothing about pydantic, though)

**Comment by tweakimp** [comment]
Funny, I had exactly the same code already, but it looked a bit hacky :)

Thanks anyways.
