### ISSUE TITLE
pytest plugins loading order

### ISSUE THREAD

**Issue by RobertasMurnikovas** [pytest-dev/pytest#8688]
I have `pytest-django` `pytest-dotenv` installed on my machine. Somehow pytest cannot load `pytest-dotenv` first and because of that, I cannot set the `DATABASE_URL` and pytest just uses defaults from django settings and fails to run tests because it tries to run tests with `sqlite3` not `posgre`. I've found this issue https://github.com/pytest-dev/pytest/issues/4718, but for me `-p` part still doesn't seem to work. so everytime i open a new terminal session screen, I need to manually export things in order for pytest to run. Could someone tell me why I cannot set my `pytest` plugin order?

**Comment by RonnyPfannschmidt** [comment]
for entrypoint based plug-ins the order is currently undefined

**Comment by nicoddemus** [comment]
To add to @RonnyPfannschmidt's answer, the order is the same as the one returned by `setuptools` entry points, which in undefined as far as we know.

**Comment by Zac-HD** [comment]
The only way I know to control plugin loading order is to explicitly load them in your `conftest.py` ([see here](https://hypothesis.readthedocs.io/en/latest/strategies.html#interaction-with-pytest-cov)).
