### ISSUE TITLE
Pytest (interrupting callback) versus unittest (not interrupting callback) in connection with pika

### ISSUE THREAD

**Issue by mwberlindeu** [pytest-dev/pytest#8710]
We intend to test (not mocked) callbacks and streams that are based on pika (https://pika.readthedocs.io/en/stable/index.html).

However it seems that such callbacks / streams are broken when trying to run them in pytest.

We have set up identical tests with unittest (https://docs.python.org/3/library/unittest.html). Using unittest the tests work. Streams and callbacks are not interrupted.

We are now facing a tricky decision.
1. We refactor our existing pytest test cases to unittest.
2. We use two test packages - pytest for tests not involving callbacks/streams and unittest for tests involving callbacks / streams.
3. We wait until testing callbacks / streams (using pika) also work in pytest if we can get some reasonable assurance that the issue is acknowledged, can be reproduced and a fix for pytest is within reach.

It will be very much appreciated to receive some feedback for decision option 3.

**Some details excerpts on the error messages**

FAILED SystemTests\  ...  - pika.exceptions.StreamLostError: Stream connection lost: IndexError...
FAILED SystemTests\  ...  - pika.exceptions.ConnectionWrongStateError: BlockingConnect...

C:\ProgramData\Anaconda3\ ... \pika\adapters\blocking_connection.py:2571: in queue_bind
    self._flush_output(bind_ok_result.is_ready)
C:\ProgramData\Anaconda3\ ... \pika\adapters\blocking_connection.py:1336: in _flush_output
    self._connection._flush_output(lambda: self.is_closed, *waiters)

self = <BlockingConnection impl=<SelectConnection CLOSED transport=None params=<ConnectionParameters host=ectp-wqa-002 port=5672 virtual_host=/ ssl=False>>>
waiters = (<function BlockingChannel._flush_output.<locals>.<lambda> at 0x000001DD1197FDC8>, <bound method _CallbackResult.is_ready of <pika.adapters.blocking_connection._CallbackResult object at 0x000001DD13789D48>>)
is_done = <function BlockingConnection._flush_output.<locals>.<lambda> at 0x000001DD1197FB88>

   def _flush_output(self, *waiters):
        """ Flush output and process input while waiting for any of the given
        callbacks to return true. The wait is aborted upon connection-close.
        Otherwise, processing continues until the output is flushed AND at least
        one of the callbacks returns true. If there are no callbacks, then
        processing ends when all output is flushed.

        :param waiters: sequence of zero or more callables taking no args and
                        returning true when it's time to stop processing.
                        Their results are OR'ed together.
        :raises: exceptions passed by impl if opening of connection fails or
            connection closes.
        """
        if self.is_closed:
            raise exceptions.ConnectionWrongStateError()

        # Conditions for terminating the processing loop:
        #   connection closed
        #         OR
        #   empty outbound buffer and no waiters
        #         OR
        #   empty outbound buffer and any waiter is ready
        is_done = (lambda:
                   self._closed_result.ready or
                   ((not self._impl._transport or
                     self._impl._get_write_buffer_size() == 0) and
                    (not waiters or any(ready() for ready in waiters))))

        # Process I/O until our completion condition is satisfied
        while not is_done():
            self._impl.ioloop.poll()
            self._impl.ioloop.process_timeouts()

        if self._closed_result.ready:
            try:
                if not isinstance(self._closed_result.value.error,
                                  exceptions.ConnectionClosedByClient):
                    LOGGER.error('Unexpected connection close detected: %r',
                                 self._closed_result.value.error)
>                   raise self._closed_result.value.error
E                   pika.exceptions.StreamLostError: Stream connection lost: IndexError('pop from an empty deque')

ERROR    pika.adapters.utils.io_services_utils:io_services_utils.py:1107 _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=1820, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.0.0.19', 54620), raddr=('10.0.0.14', 5672)>; Caller's stack:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\ ... \pika\adapters\utils\io_services_utils.py", line 1097, in _on_socket_writable
    self._produce()
  File "C:\ProgramData\Anaconda3\ ... \pika\adapters\utils\io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\ ... \pika\adapters\utils\io_services_utils.py", line 1097, in _on_socket_writable
    self._produce()
  File "C:\ProgramData\Anaconda3\ ... \pika\adapters\utils\io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
ERROR    pika.adapters.base_connection:base_connection.py:429 connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
ERROR    pika.adapters.blocking_connection:blocking_connection.py:521 Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
ERROR    pika.adapters.blocking_connection:blocking_connection.py:521 Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)

**Excerpt from pip list / pytest version**
pytest                             6.2.3
pytest-dependency         0.5.1
pytest-ordering              0.6
pika                               1.1.0

**Operating system versions**
Win 10 Enterprise - Version 10.0.19043 Build 19043

**Comment by mwberlindeu** [comment]
Which pieces of code do you need?

**Comment by asottile** [comment]
enough to reproduce the problem -- I can't see your screen or type on your keyboard

**Comment by mwberlindeu** [comment]
Hm, that is tricky as the code base is large, and I cannot share everything. I have shared some pieces of code that contain the to be tested callback. Does this help in understanding / reproducing the problem?


import pika
import confuse

class ServiceClient:

    def __init__(self, args=None):

        self.event_channel = self.event_connection.channel()
	self.config = confuse.Configuration("ServiceClient", __name__)
        if (args):
            self.config.set_args({"StartArgs": args})
	rabbitUser = self.config["RabbitMQ"]["User"].get()
        rabbitPassword = self.config["RabbitMQ"]["Password"].get()
        host = self.config["RabbitMQ"]["Host"].get()
       if len(rabbitUser) > 0:
            cred = pika.credentials.PlainCredentials(rabbitUser, rabbitPassword)
            params = pika.ConnectionParameters(host=host, credentials=cred)
        else:
            params = pika.ConnectionParameters(host=host)
        self.response_connection = pika.BlockingConnection(params)
        self.response_channel = self.response_connection.channel()
        self.event_connection = pika.BlockingConnection(params)
        self.event_channel = self.event_connection.channel()

    def init_exchange_subscription(self, exchange, topic):
        if self.event_channel.exchange_declare(exchange, "topic", passive=True):
            self.event_channel.queue_bind(queue=self.eventRouting, exchange=exchange, routing_key=topic)
            return True
        else:
            return False

    def register_callback(self, exchange_name, topic, callback):
        self._register_callback_internal(exchange_name, topic, callback)

    def _register_callback_internal(self, exchange, topic, callback):
        exch = exchange
        if not exch.startswith('Exchange_'):
            exch = f'Exchange_{exch}'
        if self.init_exchange_subscription(exch, topic):
            callbackMap = self.eventCallbacks.setdefault(exch, dict())
            callbackList = callbackMap.setdefault(topic, list())
            callbackList.append(callback)
            self.logger.info("[x] registered event callback at topic %s.", topic)
        else:
            raise Exception("Unable to register callback. See logs for more details.")

**Comment by asottile** [comment]
nope, I need to have something I can run and shows your problem -- this is some useful reading on the subject: https://stackoverflow.com/help/minimal-reproducible-example

note also when formatting code on github you should use code fence blocks:

```markdown
    ```python
    print('hello hello world')
    ```
```

**Comment by mwberlindeu** [comment]
Thanks for the reply. In order to provide some reproducible code you would have to recreate the complete stack we use which I cannot provide the code for. Maybe some other user may someday have a simiar issue who can provide the code. Please close the ticket if you cannot reproduce the issue. We will switch ti unittest.
