### ISSUE TITLE
Integrate pytest-instafail functionality into the core

### ISSUE THREAD

**Issue by staticdev** [pytest-dev/pytest#8720]
#### What's the problem this feature will solve?
When you have hours of tests to run (for example thousands of integration tests) you can be able to see the logs during execution and start fixing errors.

Actually, I found a 2015 question on [StackOverflow](https://stackoverflow.com/questions/30994622/pytest-report-summary-to-display-error-information/49091203) about that but no solution there worked. I tried using flags `-v`, `-rA`, `-v --tb=no` and also `--tb=line`.

#### Describe the solution you'd like
Have a flag to show failed test's errors while executing the tests (instead of standard after all tests were executed).

#### Alternative Solutions
Some of the existing flags such as `-v`, `-rA`, `-v --tb=no` and also `--tb=line` have this behavior.

**Comment by Zac-HD** [comment]
I think you want https://pypi.org/project/pytest-instafail/ ?

**Comment by staticdev** [comment]
@Zac-HD looks like so. But without having to install something just to change how is the output. Since pytest already has many options for that built-in.

**Comment by nicoddemus** [comment]
Hi @staticdev,

> But without having to install something just to change how is the output

I personally think that's OK: pytest has a flexible plugin architecture for this very reason, for people to be able to implement extra functionality without adding maintenance overhead to the core. After all, this should be a simple `pip install` away.

Having said that, in the past we did integrate extra functionality that was implemented as a plugin into the core, so I'm renaming the title of the issue to reflect that more clearly, and changing this to a proposal. 👍

**Comment by Zac-HD** [comment]
Closing as per https://github.com/pytest-dev/pytest/issues/12465#issuecomment-2175596712.

**Comment by danielhollas** [comment]
Hi 👋 

I would like to kindly request for this issue to be re-opened. It was closed in a mass issue-closing event without discussion. We believe this functionality is common enough to be in core, and hopefully not too much extra code to maintain. In fact, given that `pytest-instafail` is under the `pytest-dev` organization, one might argue that maintaining it in core might be in the end less work?

For context, we've been looking for this functionality and were disappointed by our options. 
The last commit to `pytest-instafail` is 3 years old, and last tested versions are Python 3.11 and pytest 6!

`pytest-sugar` offers the same functionality, but adds other stuff that makes it a large plugin (800 lines). 

Thanks for your consideration.

**Comment by The-Compiler** [comment]
For what it's worth, pytest-instafail works perfectly fine with modern Python and pytest versions. Other than adding those to CI (which I see you are working on in https://github.com/pytest-dev/pytest-instafail/pull/33), there is really nothing to be done there. I don't understand how that ends up in you being "disappointed by [y]our options", the plugin is perfectly fine to use.

That being said, personally I'd be interested in having this as part of the core, as this is probably my number one favorite pytest plugin which I install in all longer-running testsuites. Reopening for now for some discussion.

**Comment by danielhollas** [comment]
@The-Compiler thanks for a swift reply and reopening the issue! 🫶 Great to hear that the plugin works for modern versions. 

> I don't understand how that ends up in you being "disappointed by [y]our options", the plugin is perfectly fine to use.

I apologize for the unnecessary "flair" in my wording there. I guess the "disappointment" feeling came from the manner this issue was closed. Thanks for reopening it!

**Comment by nicoddemus** [comment]
I agree it could be merged into the core, seems like really small and a nice addition to have.

I'm 👍 if somebody wants to work on it.
