### ISSUE TITLE
Better API for assertion failure reprs

### ISSUE THREAD

**Issue by ikonst** [pytest-dev/pytest#8740]
PyCharm injects a [pytest plugin](https://github.com/JetBrains/teamcity-messages) to enable the IDE to intercept comparison assertion failures and provide an integrated diff UI for them. Currently it does a bunch of messy things that fail in complex cases:
- implements `pytest_assertrepr_compare` to encode the assertion failure in a more resilient way
- overrides `config.option.verbose = 2` to avoid truncation
- picks up the results in `pytest_runtest_logreport`
- hackily undoes `_pytest.assertion.util.format_explanation`

It'll be nice to have a way for plugins to stash assertion failures in a more structured way so they could be "picked up" in `pytest_runtest_logreport` cleanly and then serialized in whatever way the IDE prefers to get them.

Currently:
- `pytest_assertrepr_compare` gets `config` but not `item` so there's no way to stash structured results on the `item`
- `pytest_assertrepr_compare` return value is a `Optional[List[str]]` (no complex data structure)

Open to other ideas of course.

**Comment by RonnyPfannschmidt** [comment]
I just started to use pycharm and im happy to collaborate

Im also preparing a pep to get annotated assertions into python core

**Comment by ikonst** [comment]
I've considered a few options:
- raising an exception from `pytest_assertrepr_compare`, but the `TestReport` doesn't contain any reference to the original exception (rather just "repr"s of it)
- changing `pytest_assertrepr_compare` hook to pass `item` (I understand that won't break existing hooks) and then stashing it on the item -- would you use `user_properties`?

**Comment by RonnyPfannschmidt** [comment]
i think i'd prefer to go for a new type of return value instead (compatible with the list api, but able to provide more detail)

**Comment by ikonst** [comment]
@RonnyPfannschmidt how the result will be made available to `pytest_runtest_logreport`?

**Comment by ikonst** [comment]
@RonnyPfannschmidt ping :)

**Comment by RonnyPfannschmidt** [comment]
@ikonst a plugin object will have to manage passover from being returnd fro mthe hook and being passed to the report

**Comment by nicoddemus** [comment]
Yeah I think help plugins to gather better information for custom failure representations would be awesome! I'm a long time PyCharm user and usually I'm pretty unhappy on how PyCharm formats certain failures (so much that I have go and run a test in the terminal to understand what's going on).

Having said that I'm also happy to collaborate to achieve this!

> changing pytest_assertrepr_compare hook to pass item (I understand that won't break existing hooks) and then stashing it on the item -- would you use user_properties?

Indeed and that I think we should do right away, as to me it is a no-brainer and makes sense regardless of what other steps we take in the future to improve the status quo. Do you agree @RonnyPfannschmidt?

**Comment by RonnyPfannschmidt** [comment]
As far as I understood the invocation point of the hook has no direct access to the session /item, as such I am opposed to funneling it in

A wrapper plugin that tracks it sound like a good idea

**Comment by nicoddemus** [comment]
What do you mean? Here's the calling point:

https://github.com/pytest-dev/pytest/blob/c94766a580d10449536c75fbbdb4d9e9f3ba2082/src/_pytest/assertion/__init__.py#L141-L143

We have direct access to `item` at that point.

**Comment by nicoddemus** [comment]
@ikonst would you like to contribute that?

**Comment by ikonst** [comment]
PyCharm's plugin should remain compatible with older versions of pytest. While hooks allow pytest to evolve while remaining compatible, is there a path for plugins to evolve while remaining compatible?

I tried assigning a default to the parameter, e.g.
```python
def pytest_assertrepr_compare(op, left,  right, item=None):
    ...
```
but the default arg ends up in the (unused) `HookImpl.kwargname` such that
```python
hook_impl.argnames == ('op', 'left', 'right')
hook_impl.kwargnames == ('item')
```
Curiously enough, actual kw-only args are lost, i.e. `foobar` in the following example goes nowhere:
```python
def pytest_assertrepr_compare(op, left,  right, *, foobar):
    ...
```

tbh, looking at the mechanics of how `item` becomes available for `pytest_assertrepr_compare`, through the `util._reprcompare` global variable, it might be easiest to assume there's one test at a time and stash the `item` in the plugin during a `pytest_runtest_protocol` hook.

**Comment by RonnyPfannschmidt** [comment]
in that case you pretty much have to implement the initial proposed solution and /or have different hook declarations for older and newer pytest

**Comment by ikonst** [comment]
The disadvantage with raising an exception, though, is that it doesn't allow the default hook to take place.

**Comment by ikonst** [comment]
Also, just realized that `Item.user_properties` have a specific meaning of items that end up in the report, which is not needed here and might be disruptive.

**Comment by ikonst** [comment]
There's `Node._store` but it's for internal use only (`StoreKey` is available through `_pytest.store`).

**Comment by nicoddemus** [comment]
We plan to eventually make `Node._store` available to users, but we don't have a clear roadmap for that yet.

You might as well just create your own attribute, `Node._pycharm_data` or something, plugins have been doing that for years to attach data to `Node` and `Config`.
