### ISSUE TITLE
codecov.io uploads extremely unstable

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#8743]
not sure what to do about this, but 3-5 runs fail on this per build and it easily has the potential to hide real issues with the testsuite

**Comment by RonnyPfannschmidt** [comment]
Let's make Coverage artifacts upload something we do in a own job and disable codecov upload for now

**Comment by nicoddemus** [comment]
@hynek just published a how to: https://hynek.me/til/ditch-codecov-python/

**Comment by bluetech** [comment]
Maybe #11921 improves things, though it's been alright lately, so I'll close this as I think there's nothing to do here really.
