### ISSUE TITLE
docs about TestClassDemoInstance is wrong

### ISSUE THREAD

**Issue by haihit** [pytest-dev/pytest#8745]
Something to be aware of when grouping tests inside classes is that each test has a unique instance of the class.
but the example TestClassDemoInstance show the same object ID
self = <test_class_demo.TestClassDemoInstance object at 0xdeadbeef>
self = <test_class_demo.TestClassDemoInstance object at 0xdeadbeef>
it should be different

**Comment by RonnyPfannschmidt** [comment]
indeed, thats a known issue from regendoc (trying to make the addresses in docs stable)

**Comment by nicoddemus** [comment]
Thanks @haihit, 

Duplicate of https://github.com/pytest-dev/pytest/issues/7646.
