### ISSUE TITLE
[RFE]: add possibility to report which one extension is reporting exact error or warning

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest#8757]
In case when some error or warnimg is printed it would be good to have some details about which one pytest extension exact error or warning has been reported.

**Comment by Zac-HD** [comment]
I think you can get this from `python -Werror -m pytest` and the traceback?

Closing per https://github.com/pytest-dev/pytest/issues/12465#issuecomment-2175596712 since I don't think we need to do anything.
