### ISSUE TITLE
Find useless filterwarnings ignores

### ISSUE THREAD

**Issue by kasium** [pytest-dev/pytest#8768]
#### What's the problem this feature will solve?

1. The filterwarnings list can contain a few entries in larger projects with a lot of dependecies. It's hard to find out if an ignore is still needed
2. Projects using `pytest.mark.filterwarnings` cannot find out if the filterwarnings filters something or not

#### Describe the solution you'd like
1. A mode which checks if all ignores sill capture at least one warning. This could be implemented with a CLI flag
2. A strict flag for `pytest.mark.filterwarnings`  which will raise an error if no warning was captured

#### Alternative Solutions
The only approach known to me is to remove the ignore or decorator and then to test of the tests don't have any warning /error

**Comment by nicoddemus** [comment]
Thanks @kasium!

This is interesting and something I wished to have on occasion already.

Implementation-wise I'm not sure it is doable however, as we use [catch_warnings](https://docs.python.org/3/library/warnings.html#warnings.catch_warnings) to capture the warnings, and there's no indication from that function which filters matched or not.

**Comment by kasium** [comment]
@nicoddemus thanks for the comment

I'm not quite sure, but I guess in both cases, the warnings filter shouldn't be given to python's warning module. So, you first capture all warnings with catch_warnings. Then on exit/function return, you check if the warning emitted (as provided by catch_warnings) matching any filter.
I'm not sure, if python provides a way to check if a filter filters a warning message, but this could be a feature request to them.

I'm not sure if I forgot something or if there are further things to consider.

**Comment by nicoddemus** [comment]
> Then on exit/function return, you check if the warning emitted (as provided by catch_warnings) matching any filter.

Sounds reasonable, but then we have to replicate the filtering logic. Also I'm sure this might bring its host of own problems.

> I'm not sure, if python provides a way to check if a filter filters a warning message, but this could be a feature request to them.

It is possible I guess.

**Comment by kasium** [comment]
Fair point.

Another idea would be, that python offers a function which returns the filtered warnings incl. the filter rule which was applied.
What do you think?

**Comment by nicoddemus** [comment]
> Another idea would be, that python offers a function which returns the filtered warnings incl. the filter rule which was applied.
What do you think?

That would make it trivial for pytest to find out if any warnings were not found, definitely.

**Comment by kasium** [comment]
I created a thread on python-ideas (currently waiting for moderation)

**Comment by asottile** [comment]
I'm not sure this would be useful in the general case as many warnings are version-specific

**Comment by kasium** [comment]
@asottile I agree with the version-specific part, but what I have seen in projects is the following:
* a warning occurs in library xyz in version 1.2
* The library is updated to version 1.3 where the warning is fixed
* The committer just forgot to remove the filtered warning

Some time later we wonder why there is an filter. To find out we need first to remove it, run the whole test base and then see.
An more automatic approach would help here a lot, so that the "forgot" just can't occur

In addition, let's image that the same warning happens in multiple libraries. Then a code editor might ignore it w/o specifying the module at all. Then it's even harder to remove the warning later.

IMHO, this request makes sense. @asottile feel free to comment to the python-idea as well. I'm happy to get any sort of feedback, even if the idea is declined at the end

**Comment by asottile** [comment]
the common case for warnings I've seen is based on *python* versions -- for example from pytest's warnings [this only displays in python3.10](https://github.com/pytest-dev/pytest/blob/ced125ad153bb3e24710ad478b8986147f9b1a5d/pyproject.toml#L29-L30) -- an "unused warning filter" would not be useful here because it would error incorrectly in python<3.10

**Comment by kasium** [comment]
@asottile thanks a lot for this limitation. That's definitive valid and should be considered. But what's about projects building on top of a specific python version? The idea would still work for them, or do you don't see a use case there?

**Comment by asottile** [comment]
I'm not sure the complexity is worth it, it's pretty easy to comment out the setting, see all the warnings, and prune as needed

**Comment by kasium** [comment]
I see the potential for automatic checks, but yes, it can be checked by hand w/o bis issues

**Comment by kasium** [comment]
Hi all,

the python idea got no answers yet and also the feedback from asottile is quite valid.
Therefore if @nicoddemus agrees, I would suggest to drop that issue.

**Comment by nicoddemus** [comment]
Sure, thanks everyone for participating. 👍
