### ISSUE TITLE
Invoke tests with a .xml file

### ISSUE THREAD

**Issue by gchungsy** [pytest-dev/pytest#8770]
#### What's the problem this feature will solve?

Currently, we can mark test functions with attribute and run tests by marker expressions: pytest -m smoke
However, different testers may have different opinions of what test function should be marked with @smoke
And sometimes commented-out markers get checked in by accident (human error).

#### Describe the solution you'd like

It would be great if we could invoke tests with a .xml file, similar to what is available in this test framework: https://testng.org/doc/documentation-main.html#testng-xml

This way each person can create their own XML and run a different set of tests (without modifying code)

#### Alternative Solutions

Not aware of any plugin that would solve this problem

**Comment by nicoddemus** [comment]
Hi @gchungsy,

The suggestion would be to implement a plugin which does that. It could receive a XML file as argument, and then filter out tests which shouldn't be executed by implementing the [pytest_collection_modifyitems](pytest_collection_modifyitems). Should be straightforward to implement.

**Comment by gchungsy** [comment]
Hi @nicoddemus,

I made some progress. Thanks for the suggestion.
