### ISSUE TITLE
Can pytest give warnings or other messages when using @pytest.mark.importorskip

### ISSUE THREAD

**Issue by AllentDan** [pytest-dev/pytest#8776]
Hi, thanks for the amazing work.

It seems to me that importorskip functions share the same effects like "try import sth except" and it should be used inside unit tests. Not sure if it is right.

But I tried @pytest.mark.importorskip outside the unit tests. It gives me no warning or error messages. Is @pytest.importorskip the right usage of this function? 

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
------------------ ------------------- ------------------------------------------------------------
addict             2.4.0
appdirs            1.4.4
asynctest          0.13.0
attrs              21.2.0
certifi            2021.5.30
cfgv               3.3.0
chardet            4.0.0
codecov            2.1.11
coverage           5.5
cycler             0.10.0
Cython             0.29.23
decorator          4.4.2
distlib            0.3.2
filelock           3.0.12
flake8             3.9.2
graphsurgeon       0.4.5
identify           2.2.10
idna               2.10
imageio            2.9.0
imgaug             0.4.0
importlib-metadata 4.5.0
iniconfig          1.1.1
isort              5.8.0
kiwisolver         1.3.1
kwarray            0.5.19
lanms-proper       1.0.1
llvmlite           0.36.0
lmdb               1.2.1
matplotlib         3.4.2
mccabe             0.6.1
mmcv-full          1.3.5               open-mmlab/mmcv
mmdet              2.11.0              mmdetection-2.11.0
mmpycocotools      12.0.3
networkx           2.5.1
nodeenv            1.6.0
numba              0.53.1
numpy              1.20.3
onnx               1.9.0
onnx-graphsurgeon  0.2.6
onnxruntime-gpu    1.7.0
opencv-python      4.5.2.52
ordered-set        4.0.2
packaging          20.9
Pillow             8.2.0
pip                21.1.1
pluggy             0.13.1
Polygon3           3.0.9.1
pre-commit         2.13.0
protobuf           3.17.2
py                 1.10.0
pyclipper          1.2.1
pycodestyle        2.7.0
pyflakes           2.3.1
pyparsing          2.4.7
pytest             6.2.4
pytest-cov         2.12.1
pytest-runner      5.3.1
python-dateutil    2.8.1
PyWavelets         1.1.1
PyYAML             5.4.1
rapidfuzz          1.4.1
requests           2.25.1
scikit-image       0.18.1
scipy              1.6.3
setuptools         52.0.0.post20210125
Shapely            1.7.1
six                1.16.0
tensorrt           7.2.1.6
terminaltables     3.1.0
tifffile           2021.4.8
toml               0.10.2
torch              1.8.1+cu111
torchaudio         0.8.1
torchvision        0.9.1+cu111
typing-extensions  3.10.0.0
ubelt              0.9.5
urllib3            1.26.5
virtualenv         20.4.7
wheel              0.36.2
xdoctest           0.15.4
yapf               0.31.0
zipp               3.4.1
- [x] pytest and operating system versions:
pytest: '6.2.4'
system: ubuntu 18.04
- [x] minimal example if possible:
Just like description above.

**Comment by RonnyPfannschmidt** [comment]
its not clear what you are doing, please show a code example and a error

note that https://docs.pytest.org/en/6.2.x/reference.html#pytest-importorskip is a function, not a mark

**Comment by AllentDan** [comment]
Hi, @RonnyPfannschmidt. Just suggest that using it invalid like pytest.mark.importorskip be warned or not allowed to excute.

**Comment by RonnyPfannschmidt** [comment]
@AllentDan there should be a warning about mark usage already as its now a known mark

**Comment by nicoddemus** [comment]
Indeed, `@pytest.mark.importorskip` should already be showing as a warning:

```python
import pytest

@pytest.mark.importorskip("numpy")
def test_foo(): pass
```

```
λ pytest .tmp\test_importor.py --no-header
======================== test session starts ========================
collected 1 item

.tmp\test_importor.py .                                        [100%]

========================= warnings summary ==========================
.tmp\test_importor.py:3
  e:\projects\pytest\.tmp\test_importor.py:3: PytestUnknownMarkWarning: Unknown pytest.mark.importorskip - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.importorskip("numpy")

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================== 1 passed, 1 warning in 0.01s ====================
```

Closing this for now. 👍
