### ISSUE TITLE
Wrong link on warning message for custom mark

### ISSUE THREAD

**Issue by bsypniewski** [pytest-dev/pytest#8787]
When I try to use custome marker ex. "@pytest.mark.webtest" after test finishes i get warning:
"PytestUnknownMarkWarning: Unknown pytest.mark.uploadtenantcontent - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html"

But this link: https://docs.pytest.org/en/latest/mark.html does not exists, i get 404 
i think correct link should be: https://docs.pytest.org/en/6.2.x/mark.html
or maybe: https://docs.pytest.org/en/6.2.x/example/markers.html

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

pytest: 6.2.4
OS: MacOS Catalina

pip list:
attrs           20.3.0
boto3           1.17.82
botocore        1.20.82
iniconfig       1.1.1
jmespath        0.10.0
mstest          0.1.0
packaging       20.9
pip             21.0.1
pluggy          0.13.1
py              1.10.0
pyparsing       2.4.7
pytest          6.2.4
pytest-mock     3.6.1
python-dateutil 2.8.1
s3transfer      0.4.2
setuptools      54.1.2
six             1.16.0
urllib3         1.26.5
wheel           0.36.2

**Comment by DrGFreeman** [comment]
I believe the correct link should be https://docs.pytest.org/en/latest/how-to/mark.html which is similar to https://docs.pytest.org/en/6.2.x/mark.html but not version specific.

I can submit a PR with the link change.

**Comment by The-Compiler** [comment]
Additionally to @DrGFreeman's PR, I've now also added a redirect on readthedocs so that (as soon as caching catches up I'm guessing) https://docs.pytest.org/en/latest/mark.html should work as well.

**Comment by The-Compiler** [comment]
Wait, @bsypniewski, are you sure you're running 6.2.4? There, the link already [points to](https://github.com/pytest-dev/pytest/commit/93d2ccbfb7b99755e8f4a2a3947c466949ee3c46#diff-d4864cafea74aab49680c53ef12e29653bcf4b72b85f8eac7e003f5c04514d0e) https://docs.pytest.org/en/stable/mark.html which is correct.

**Comment by The-Compiler** [comment]
See https://github.com/pytest-dev/pytest/issues/8471#issuecomment-871416094 for a possible alternative solution to all this...

**Comment by jsoref** [comment]
@bsypniewski / @The-Compiler : can you fix the title to `Wrong link`? 😉

**Comment by bsypniewski** [comment]
> Wait, @bsypniewski, are you sure you're running 6.2.4? There, the link [already points](https://github.com/pytest-dev/pytest/commit/93d2ccbfb7b99755e8f4a2a3947c466949ee3c46#diff-d4864cafea74aab49680c53ef12e29653bcf4b72b85f8eac7e003f5c04514d0e) to https://docs.pytest.org/en/stable/mark.html which is correct.

yes. you can see it on pip freeze output

**Comment by The-Compiler** [comment]
What I'm saying is that your `pip list` output probably doesn't correspond to what you're actually running. Like you can see above, the link is different in the version listed in your `pip list`.

How exactly do you run pytest? If it's via `pytest`, what do `which pytest` and `which pip` say?

**Comment by The-Compiler** [comment]
Closing this now, since (as shown above) the doc links in 6.2.4 point to the correct location - also, there's a redirect in place now (#8471), so the `/latest/` link will work too.
