### ISSUE TITLE
Add note about exit code in example code for pytest.main()

### ISSUE THREAD

**Issue by ingomueller-net** [pytest-dev/pytest#8790]
I have just noticed that I have been calling `pytest.main()` for years in several projects and ignored the exit code. This is obviously really bad for unit tests; the only reason I have not noticed is that I have used the `python -m pytest` invocation method in CI -- until today.

The problem, in my opinion, is that the one [example in the documentation](https://docs.pytest.org/en/6.2.x/usage.html#calling-pytest-from-python-code) ignores the exit code as well. It does mention that the function returns the exit code but giving an example where that code is used would be more explicit. For example:

```python
if __name__ == '__main__':
    sys.exit(pytest.main(sys.argv))

```

**Comment by RonnyPfannschmidt** [comment]
@ingomueller-net thanks for the note, would you like to create a pr adding a a note you would find helpful ?

**Comment by nicoddemus** [comment]
We should also update the examples to make that explicit:

```
```

**Comment by Srip** [comment]
@RonnyPfannschmidt , Can I pick this up and submit a PR?

**Comment by nicoddemus** [comment]
@Srip please go ahead. 👍

**Comment by Srip** [comment]
Submitted a PR with requested changes: https://github.com/pytest-dev/pytest/pull/8800 
Please provide feedback if any changes required
