### ISSUE TITLE
6.2.4: pytest with multiple -k works not as expected

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest#8809]
Looks like if pytest is used with multiple -k like `pytest -k "not uni1" -k "not unit2"` only last `unit2` is deselected.

**Comment by The-Compiler** [comment]
See #7229. However, if we'd join the two expressions with `or` (which, IMHO, would be the most sensible thing to do), that still wouldn't work as you'd expect with `not unit1 or not unit2`. I don't really see a way out of that.
