### ISSUE TITLE
Figure out how to fix changelog title

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#8817]
Strange, this should be:

```suggestion
pytest 7.0.0rc1 (2021-06-28)
============================

```

No idea, seems like a town crier problem? 🤔

_Originally posted by @nicoddemus in https://github.com/pytest-dev/pytest/pull/8814#discussion_r660066152_

**Comment by The-Compiler** [comment]
If all else fails, we could always patch this manually in the release PR. But let's take a quick look if we can figure out where this comes from and fix this there.

**Comment by RonnyPfannschmidt** [comment]
i recall having the same issue in xdist and before in prance - i suspect its a towncrier bug

**Comment by symonk** [comment]
I think this is a towncrier problem @The-Compiler , I noticed it when trying to setup TC on another project recently, will investigate this tomorrow!

**Comment by The-Compiler** [comment]
Yay, thanks! Note I'll be mostly afk for the next 3 weeks.
