### ISSUE TITLE
Investigate long regendoc output in cache.rst

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#8818]
Hmmm with the documentation moved we are getting cache data from other runs. @RonnyPfannschmidt can we use "regendoc wipe" to fix this?

_Originally posted by @nicoddemus in https://github.com/pytest-dev/pytest/pull/8814#discussion_r660068177_

**Comment by The-Compiler** [comment]
I have no idea on this one - @nicoddemus @RonnyPfannschmidt could one of you take a look at what's wrong there?

**Comment by RonnyPfannschmidt** [comment]
Slotted for the evening

**Comment by RonnyPfannschmidt** [comment]
so much for that evening, fetching the details now

**Comment by RonnyPfannschmidt** [comment]
discovered a bug in bestrelpath

when it goes up to the root, then it will return a relative path that is longer than the rest

**Comment by RonnyPfannschmidt** [comment]
@bluetech i believe the issue could have gotten introduced while changing our commonpath usage to the stdlib, creating a test+fix now

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler i made the fixture output better by fixing the bestrelpath for root == commonpath on posix,

additionally im introducing a PYTHON_SITE meta env var for better handling

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler i  discovered that for some reason the python  prefix is used as pytest cache dire

**Comment by RonnyPfannschmidt** [comment]
it seems this first cropped up in 2019 and was back then incorrectly resolved by adding a `rm -rf`

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler @nicoddemus i refactored regendoc a little and it now no longer path escapes, and we get unique addresses,

im preparing the commit now, hopefully release on the weekend

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/regendoc/pull/13
