### ISSUE TITLE
Changelog rewording for 7.0

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#8824]
See the comments in https://github.com/pytest-dev/pytest/pull/8814/files#diff-e02b5aa2806cf9086c18c4d38b880df457d9313bf02ba108d58e67336abbab66 - those should be fixed in the individual `changelog/*.rst` files.

Ignore the first comment about the title, that's tracked in #8817.

**Comment by ericluoliu** [comment]
Working on this

**Comment by ericluoliu** [comment]
Made the pull request
I noticed a comment on 8411.trivial.rst to perhaps drop the contents of the file but I wasn't sure what needed to be done so I just left it as is for now.
