### ISSUE TITLE
Update all links after doc restructuring

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#8831]
Similarly to what 93d2ccbfb7b99755e8f4a2a3947c466949ee3c46 did, we'll have to update all links in the source code to point to the correct `stable/` locations for when 7.0.0 is released (and/or add redirects in RTD's backend).

Otherwise, as I understand it, once the release is out, all the `stable/` links which currently work (due to `stable` pointing to `6.2.x`, before the restructuring) will break :cry:

**Comment by DrGFreeman** [comment]
@The-Compiler, can I help with this?

Do you know which PR(s) restructured the docs? That would speed-up finding the new link values.

**Comment by The-Compiler** [comment]
See the [PRs by @evildmp](https://github.com/pytest-dev/pytest/pulls?q=is%3Apr+author%3Aevildmp+is%3Aclosed) on this - I think it was mostly #8433, but probably others as well.

Having a list of how the documentation moved certainly would be a good starting point, then we could also add redirects to fix existing links (see #8471).

However, I suppose it's not always that easy, as one page (in the old docs) typically got split into three (in the new docs). For example, should the old [fixture docs](https://docs.pytest.org/en/6.2.x/fixture.html) now redirect to:

- [The fixtures how-to](https://docs.pytest.org/en/latest/how-to/fixtures.html)
- [The fixtures explanation](https://docs.pytest.org/en/latest/explanation/fixtures.html)
- [The fixtures reference](https://docs.pytest.org/en/latest/reference/fixtures.html)

It's tricky, and I wish we'd have given this more consideration when restructuring those docs...

I'm also wondering if changing all those links is really the right approach, or we should go for a different solution. I'll post over in #8471 about that one. Let's try to get to a consensus there, and then maybe you can help with that, if that works for you?

**Comment by DrGFreeman** [comment]
> Let's try to get to a consensus there, and then maybe you can help with that, if that works for you?

Sure!
