### ISSUE TITLE
7.0 and test_deprecation_warning_as_error

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#8833]
https://github.com/pytest-dev/pytest/blob/9cdb7223b5f465d6511e2da1885ad37701eb8d02/testing/test_warnings.py#L520-L529

what's the plan there for 7.0? @nicoddemus?

**Comment by nicoddemus** [comment]
I will take a look into this together with https://github.com/pytest-dev/pytest/issues/7363. 👍

**Comment by nicoddemus** [comment]
Will be handled appropriately in #7363 (see #8837 also).
