### ISSUE TITLE
6.2.4: misleading message about missing `subdirectory.module`

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest#8845]
Preamblem:
I'm building rpm packages with python module and on building them I'm using typical template like below
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with $PYTHONPATH pointing to setearch and sitelib inside </install/prefix>

Problem:
pytest prints misleading message about missing `subdirectory.module` if in `</install/prefix/>[setearch|sitelib]/subdirectory/` there is no `__init__.py`

Workaround:
- after "setup.py build" create empty `__init__.py` (`> build/lib/subdirectory/__init__.py)
- "setup.py install --root </install/prefix>"
- "pytest" with $PYTHONPATH pointing to setearch and sitelib inside </install/prefix>
- package everything without `</install/prefix/>[setearch|sitelib]/subdirectory/{*.py,__pycache__}`

Exact case is here of such module https://github.com/sphinx-contrib/sphinxcontrib-towncrier/issues/50

- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
Linux x86_64, pytest 6.2.4, python 3.8.11
- [x] minimal example if possible

**Comment by Zac-HD** [comment]
Based on the linked issue, it looks like this is a problem with your install process rather than Pytest.

**Comment by kloczek** [comment]
> Based on the linked issue, it looks like this is a problem with your install process rather than Pytest.

Could you please tell a bit more about what is wrong wit that process?

**Comment by kloczek** [comment]
I've checked https://docs.pytest.org/en/stable/usage.html#calling-pytest-through-python-m-pytest and was not able to find any hints about what could be wrong with my methodology :/

Please could you please tell how should I perform testing in case with which I have issue?

I found another module `sphinxcontrib-serializinghtml` with which I have simillar issue but in this case that hack with create empty `build/lib/sphinxcontrib/__init__.py` does not work and pytest fails because it cannot find `sphinxcontrib.serializinghtml`.
