### ISSUE TITLE
Pytest warning on readline

### ISSUE THREAD

**Issue by stefaneidelloth** [pytest-dev/pytest#8847]
If I use pytest-6.2.4, pytest-cov 2.12.1 and python 3.9.4 on Windows 10

with following commands:

`pytest --cov src --cov-fail-under=98 --cov-report=term-missing`

or simply

`pytest`

I get a warning: 

..\..\app\winpython\python-3.9.4.amd64\lib\site-packages\pyreadline\py3k_compat.py:8
  c:\python_env\app\winpython\python-3.9.4.amd64\lib\site-packages\pyreadline\py3k_compat.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3
, and in 3.10 it will stop working
    return isinstance(x, collections.Callable)

-- Docs: https://docs.pytest.org/en/stable/warnings.html

=> Could please replace pyreadline or somehow hide the warning?

Related: 
https://github.com/pytest-dev/pytest/issues/8733
https://github.com/pyreadline/pyreadline/pull/68

**Comment by The-Compiler** [comment]
Like you point out, the warning is coming from pyreadline. pytest doesn't use pyreadline, all it does is `import readline` for #1281.

**Comment by nicoddemus** [comment]
@The-Compiler is right, but I think we should drop that workaround given `pyreadline` is no longer maintained, and the workaround was introduced in 2015 by #1281.

**Comment by The-Compiler** [comment]
Not sure about this. As evident by this issue people still seem to have `pyreadline` installed, and depending on how obscure the behavior with pyreadline and `--pdb` is, I'd rather have them see a deprecation warning (making them realize they should probably uninstall `pyreadline`) than having behavior which is probably much harder to track down.

**Comment by nicoddemus** [comment]
OK, let's discuss this over the PR then: https://github.com/pytest-dev/pytest/pull/8848 👍

**Comment by RonnyPfannschmidt** [comment]
We can ask packaging if pyreadline is installed and/or guard the import with a warning recorder + trigger a pytest specific pytest warning

**Comment by The-Compiler** [comment]
The workaround is there specifically for pyreadline from what I understood.

**Comment by bluetech** [comment]
I briefly tried to understand what the original workaround was about. IIUC, when pyreadline is imported, it attaches to stdin/out/err, and [bugs out](https://github.com/pytest-dev/pytest/pull/1281) if they're redirected. But I'm pretty sure that the debugging plugin suspends the capturing before calling `Pdb(...)` which imports readline. So I wonder why the workaround is even needed? I don't have a Windows machine, and pyreadline has some "keysyms" error on Linux, so can't try it myself.
