### ISSUE TITLE
Unable to add a new file under src

### ISSUE THREAD

**Issue by Mrodent** [pytest-dev/pytest#8853]
- [ ] a detailed description of the bug or problem you are having
I just tried to add a new file under py_lib\src (NB OS is W10)... and pytest is completely unable to "see" this, despite numerous efforts on my part (see [SO question](https://stackoverflow.com/q/68238966/595305)).

NB actual name of project "py_lib".

- [ ] output of `pip list` from the virtual environment you are using

Package      Version Location
------------ ------- -------------------------------------------------------------
atomicwrites 1.4.0
attrs        21.2.0
colorama     0.4.4
iniconfig    1.1.1
packaging    20.9
pip          21.1.3
pluggy       0.13.1
py           1.10.0
py-lib       0.1.0   d:\my documents\software projects\eclipseworkspace\py_lib\src
pyparsing    2.4.7
pytest       6.2.4
setuptools   57.0.0
toml         0.10.2
wheel        0.36.2

- [ ] pytest and operating system versions
6.2.4.  OS: W10 10.0.19042

- [ ] minimal example if possible
N/A

**Comment by The-Compiler** [comment]
I doubt this is a pytest issue. Do you see the same issue if you run `python test_misc_utils.py`?

**Comment by Mrodent** [comment]
Thanks.  `python test_misc_utils.py` (i.e. just run my_proj/tests/unit/test_misc_utils.py) would, in itself, not of course as standard include files under my_proj/src/utils in the list of python source dirs.  

But I can import these files fine when I run e.g. from the directory my_proj: `> python src/utils` ... as there is a file my_proj/src/utils/__main__.py, this runs, and successfully imports the problem files under .../utils: variables in them can be accessed, etc., no problem.

You may be right about it not being a pytest issue. But I'm completely stumped. I'm wondering just how pytest does this business of adding the production files location (my_proj/src) to its python source dirs prior to running the tests...?

**Comment by The-Compiler** [comment]
It sounds like you probably want to import `my_proj.utils.new_file`, not just `utils.new_file` (that'd be from a project called `utils` after all)?

**Comment by Mrodent** [comment]
No, that's not the issue: other files in the same utils directory import fine, and src is a Python directory. As I say, it's my_proj/src/utils...

**Comment by asottile** [comment]
I think you're using a non-editable install and so it is not appearing until you reinstall your library under test

but I agree, this is not a pytest issue

**Comment by Mrodent** [comment]
Starting a new project from scratch, using a minimal implementation, and putting together the most bare-bones implementations of setup.py, I realised what the problem is: the suggested structure (in the book) for the src files involves a module src/tasks, under which is an `__init__.py`. 

This explicitly imports the variables for export (classes, etc.) from that "tasks" package. Not surprisingly, only things in there can in fact be imported from the "tests" branch.

Thus it would appear that 
`from tasks import Task`
in my test file can only access variables explicitly prepared for export from the "tasks" module because they've been included in `__init__.py`.  This may not be the whole story. But it obviously is about what setup.py does.  At the moment mine looks like this:

```
from setuptools import setup
setup(
    name='py_lib2',
    py_modules=['py_lib2']
)

```
... I presume this means only `__init__.py` files in packages under py_lib2/src are available for looking for variables to import. As I say, this may not be the whole story...
