### ISSUE TITLE
MarkInfo class is misused for collection of MarkInfo objects

### ISSUE THREAD

**Issue by JanBednarik** [pytest-dev/pytest#886]
`MarkInfo` class ( https://github.com/pytest-dev/pytest/blob/master/_pytest/mark.py#L286 ) is used for two purposes:
- store MarkInfo (args and kwargs) of one object
- iterable collection of MarkInfo objects (list of args and kwargs)

This unclear usage leads to nasty bugs like #751 and makes requests like #759 too hard to implement. `MarkInfo` should be refactored into two classes one for each purpose.

**Comment by chmeldax** [comment]
@JanBednarik Well, did you start working on it or what is the progress of this "enhacement"? I just wonder if I should somehow reopen #759 :)

**Comment by JanBednarik** [comment]
@chmeldax I started working on it, but looks like deeper issue.

@RonnyPfannschmidt Should I work on this? Or you will deal with this in issue #891 ?

**Comment by RonnyPfannschmidt** [comment]
@JanBednarik for easing #891 some toolings to delcare/use and merge collections of marks seem handy - more communication needed, are you by chance on irc, or is another medium better

**Comment by RonnyPfannschmidt** [comment]
the underlying refactorings are done, the other facade will get a new api
