### ISSUE TITLE
logged errors should fail test

### ISSUE THREAD

**Issue by Akuli** [pytest-dev/pytest#8887]
#### What's the problem this feature will solve?

I often catch and log errors with e.g. `logger.exception("Foobar failed")`. When running tests, they get silently ignored, and I see the errors for the first time in production.

#### Describe the solution you'd like

```python
def test_should_fail(check_nothing_logged):
    logging.error("Lol")

def test_should_succeed(check_nothing_logged, caplog):
    logging.error("Lol")
    assert caplog.record_tuples == [("root", logging.ERROR, "Lol")]
```

In other words, if a test logs an error (`logging.ERROR` or `logging.CRITICAL`):
- If the test uses the `caplog` fixture, do nothing new, as the test expects to get something logged.
- If the test doesn't use the `caplog` fixture, any error logging causes it to fail.

#### Alternative Solutions

I already have a fixture that implements this. The question is whether this should be the default behavior.

```python
@pytest.fixture(scope="function", autouse=True)
def check_nothing_logged(request):
    if "caplog" in request.fixturenames:
        # Test uses caplog fixture, expects to get logging errors
        yield
    else:
        # Fail test if it logs an error
        def emit(record: logging.LogRecord):
            raise RuntimeError(f"test logged error: {record}")

        handler = logging.Handler()
        handler.setLevel(logging.ERROR)
        handler.emit = emit
        logging.getLogger().addHandler(handler)
        yield
        logging.getLogger().removeHandler(handler)
```

**Comment by nicoddemus** [comment]
Hi @Akuli,

Thanks for writing.

> I already have a fixture that implements this. The question is whether this should be the default behavior.

I don't think so, as that would break many many test suites. Not sure logging.exception should really be cause of a failure, given that the expected usage is that errors are reported through exceptions.

However I certainly see that the fixture implementation can be added to [pytest-tricks](https://hackebrot.github.io/pytest-tricks/). 👍

**Comment by Akuli** [comment]
Apparently someone else has had this problem before, and couldn't come up with what I made: https://stackoverflow.com/q/59742264

**Comment by nicoddemus** [comment]
Yeah, that's why I mentioned that posting it somewhere that is visible by the community would be interesting. 👍

**Comment by symonk** [comment]
-1 from me, I don't really see why logging an error should be a test failure.

**Comment by Akuli** [comment]
"Real world" example of why this would have been useful: My project has logging code that suppresses a specific error coming from a library. I updated the library and tests passed. When actually running the program, the error I suppressed was no longer being suppressed correctly.

If you have logging errors that shouldn't be test failures, I think you should use `caplog` to explicitly check that you get the errors you expect, and you have to do that with my fixture (or if you really need to, `def test_foo(caplog):` but don't actually use `caplog`). I think explicit checking is much better than completely hiding the errors.

Even if logging an error doesn't fail a test, I would really like to see the error printed. Is suppressing errors really a feature and not a bug?

**Comment by nicoddemus** [comment]
> Is suppressing errors really a feature and not a bug?

It depends by what you mean by "errors"... in Python it is generally accepted that exceptions are used to communicate errors, logging not so much. Also please realize that this change would break many test suites, so just from that point of view this wouldn't be an option.

Closing this for now, but feel free to follow up with future comments. 👍

**Comment by nicoddemus** [comment]
Oh it is worth mentioning: you could publish your fixture as a plugin, so any user which desires that behavior can get that for free just by installing the plugin. We highly encourage you to do that, pytest is designed to be flexible to accommodate all types of alternative workflows/requirements.
