### ISSUE TITLE
test_pdb_collection_failure_is_shown() hangs in PyCharm 4.5

### ISSUE THREAD

**Issue by omarkohl** [pytest-dev/pytest#889]
I tried running the py.test tests in PyCharm and **test_pdb_collection_failure_is_shown()** from the **test_pdb.py** module simply hangs and stops execution.

PyCharm disables output capturing (probably because they want to capture it themselves).

It can be easily reproduced _without_ PyCharm:

``` bash
py.test -s testing/test_pdb.py
```

Then one can type 'c' (continue in pdb)  - even though no output is shown regarding pdb - and the test run finishes.

Following is the default command executed by PyCharm to run the test:

``` bash
python3 /opt/pycharm-community-4.5.2/helpers/pycharm/pytestrunner.py -p pytest_teamcity testing/test_pdb.py --capture=sys
```

To verify that the problem is as described **TWO** things need to be done:
1. Remove the `--capture=sys` from the command (or replace with `--capture=fd`)
2. Comment out line 25 in **pytestrunner.py** `args.append("-s") if "-s" not in args else None`

This issue was originally reported/discussed on the [mailing list](https://mail.python.org/pipermail/pytest-dev/2015-July/003080.html).

Other info (probably not relevant):
- Issue found on **master** (commit ae28e4ba0fe9771d4dfd4ec268252db869f58469)
- OS: Ubuntu 15.04
- Java version Oracle JRE 1.8.0_25
- PyCharm 4.5.2
- Python version 3.4.3

**Comment by Cephlin** [comment]
Bump.

Has anyone else experienced this or fixed this?

It's hanging for me too and it's driving me nuts.

**Comment by RonnyPfannschmidt** [comment]
im not aware of a core dev using pycharm - and as far as i can tell the pycharm integration breaks things there

**Comment by nicoddemus** [comment]
Actually, I use PyCharm. 😁 

But I recall someone fixing running `testing/test_pdb.py` with `-s` recently. Which pytest version does this happen?

**Comment by Cephlin** [comment]
Bump.

Has anyone else experienced this or fixed this?

It's hanging for me too and it's driving me nuts.

**Comment by Cephlin** [comment]
I'll give it a go and report back.

**Comment by nicoddemus** [comment]
Closing for now; we will be happy to re-open this once we get more information.
