### ISSUE TITLE
rename tmpdir.rst to tmp_path.rst

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#8897]
but also with a permanent 308 redirect from tmpdir to tmp_path so the link juice is conserved

currently the tmp_path docs are hosted at: https://docs.pytest.org/en/6.2.x/tmpdir.html#the-tmp-path-fixture

but really it would be better to use https://docs.pytest.org/en/6.2.x/tmp_path.html#the-tmp-path-fixture

**Comment by graingert** [comment]
I'd make a PR for this, but I don't know how to configure the redirect

**Comment by nicoddemus** [comment]
The redirect is configured in the RTD interface, we can do that after the PR gets merged. 👍
