### ISSUE TITLE
Change docs files from .txt to .rst

### ISSUE THREAD

**Issue by pfctdayelise** [pytest-dev/pytest#890]
This will mean that the contents are previewed on Github. It's much nicer to look at and also makes editing in the Github web interface quite easy. We have this already for CONTRIBUTING, README and HOWTORELEASE at the top level but in the docs/en dir. See e.g. https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst

**Comment by markhovskiy** [comment]
Hi and thanks for that amazing talk on EP15 :)

I would like to help with `doc/en`.

Looks like it's (mainly) quite a manual work, though content of these files is already kind of reStructured. So is it about renaming extensions of all the files + minor corrections + proof reading?

Could it mean also testing the docs (if all examples are still valid)?

Any priorities here? Should it be one giant complete PR if not?

**Comment by pfctdayelise** [comment]
Hi @markhovskiy, great! :)

I think it only needs to rename the files (git mv), as the contents are already RST as you noticed. Then there will be some scripts which are looking for .txt files and should be changed to look for .rst. 

The code examples inside the docs should be fine as they don't need to be changed. Step 8 in https://github.com/pytest-dev/pytest/blob/master/HOWTORELEASE.rst has the info about how to build the docs. So build them locally and browse around a bit to make sure things still seem to be working correctly, is my suggestion.

**Comment by Akasurde** [comment]
@oleksmarkh , @pfctdayelise - I would love to work on this.

**Comment by oleksmarkh** [comment]
@pfctdayelise , sorry for not creating a PR yet. Planning to finally do it till 04.08 evening.
@Akasurde , we could even do it together, if you want - for instance, I can help with testing all those files built. If not, just ignore me and post your PR straight away :)

**Comment by Akasurde** [comment]
@pfctdayelise Let us do it together then

**Comment by pfctdayelise** [comment]
@Akasurde I think you meant to address @oleksmarkh, since you two are keen I won't get involved, but I will review it when there is a PR :)

**Comment by Akasurde** [comment]
@oleksmarkh can you please check PR #912 ?

**Comment by oleksmarkh** [comment]
@Akasurde , it fails. Perhaps, because either/both [/Makefile](https://github.com/pytest-dev/pytest/blob/master/Makefile) and/or [/doc/en/Makefile](https://github.com/pytest-dev/pytest/blob/master/doc/en/Makefile) aren't updated.

Are docs compiled for you? I don't know what steps are executed on `continuous-integration/appveyor`, means I don't know why your PR fails.

**Comment by Akasurde** [comment]
I have made some changes in PR #912 , build is passing for me.

**Comment by oleksmarkh** [comment]
@Akasurde , I've tested https://github.com/pytest-dev/pytest/pull/915, looks good. Thanks for taking it :)

**Comment by nicoddemus** [comment]
Just merged it, thanks everyone! :smile:
