### ISSUE TITLE
Feature request: unittest.mock's patch decorator applied during pytest fixture execution

### ISSUE THREAD

**Issue by jamesbraza** [pytest-dev/pytest#8901]
Before I would like to begin, I would like to say I am a fan of pytest, making fixtures, and monkey patching.

I have noticed today that `pytest.fixture` doesn't seem to allow `patch`ing (from `unittest.mock`) to take place before the fixture has either `return`ed or `yield`ed.

To give an understanding of what I mean, please see the below sample code:
- `test_patched_without_fixture` doesn't use `pytest.fixture`, and the `patch`ing is a success by the time the SUT (software under test, `Foo` in this sample) is instantiated
- `test_patched_with_fixture` uses `pytest.fixture`, and we can observe the `patch` doesn't take place during the SUT's instantiation

```python
from unittest.mock import patch
import pytest

class Foo:
    def __init__(self):
        self.bar_ref_during_init = self.bar

    def bar(self) -> None:
        """Some method to patch."""

@pytest.fixture
def foo_fixture() -> Foo:
    return Foo()

@patch(f"{__name__}.Foo.bar")
def test_patched_without_fixture(patched_bar):
    """
    Without a fixture, patching takes place before Foo.__init__, as expected.

    NOTE: this test passes
    """
    foo = Foo()
    assert foo.bar is patched_bar
    assert foo.bar_ref_during_init is patched_bar

@patch(f"{__name__}.Foo.bar")
def test_patched_with_fixture(patched_bar, foo_fixture):
    """With a fixture, patching hasn't taken place before Foo.__init__."""
    assert foo_fixture.bar is patched_bar
    assert foo_fixture.bar_ref_during_init is patched_bar  # Fails here
    # Why?  Because the patch hasn't taken effect while the fixture is executing
```

I am not sure if this behavior is intentional or not, so I will assume it is.  **My feature request: enable the `patch`ing to somehow take place before fixtures are run, when using `patch` as a decorator.**

There is a halfway workaround, and that's to use context management on the `patch` within the fixture.  See the below:

```python
@pytest.fixture
def foo_fixture_yield() -> Iterator[Foo]:
    patched_in = MagicMock(return_value="this can't be changed")
    with patch(f"{__name__}.Foo.bar", patched_in):
        yield Foo()
```

However, this has a major drawback: if `foo_fixture` is a factory fixture, the "prelude" (part before the `yield`) only gets executed once --> all "factory made" fixtures will share the same `patched_in` object (as if it's a singleton, not desirable)

I may also have a misunderstanding here, so please let me know.  I have done a search through the Issues, and I don't see one like this already in existence.

<details>
<summary>Versions</summary>

macOS Catalina, version 10.15.7

```
Python==3.8.8
pytest==6.2.4
```

</details>

**Comment by RonnyPfannschmidt** [comment]
That feature request has to be declined

The decorator will run at call time

Pytest will not change that

Use the context managers of mock and/or the monkeypatch fixtures to handle patching in fixtures

**Comment by nicoddemus** [comment]
> The decorator will run at call time

Just to complement @RonnyPfannschmidt's answer, the patching only occurs when `test_patched_with_fixture` gets called, but by then pytest has already inspected `test_patched_with_fixture` arguments and instantiated `foo_fixture` (which was not patched then).

The solution is to use one of `mock`'s context manager, `monkeypatch` or [`mocker`](https://github.com/pytest-dev/pytest-mock), inside the fixture itself.

**Comment by jamesbraza** [comment]
Thank you both for the speedy response!

To root cause this issue took quite a bit of time, so being able to understand and then move forward quickly is a huge help :)
