### ISSUE TITLE
pytest._pathlib.import_path should pass absolute paths on Python>=3.8 <3.10

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#8918]
In https://bugs.python.org/issue44070, `spec_from_file_location()` has changed its behaviour so that the responsibility of passing absolute paths is on the caller between 3.8 and 3.10

So something like this is needed:

```python
    if (3, 8) <= sys.version_info[:2] < (3, 10) and not os.path.isabs(fn):
        # module.__spec__.__file__ is supposed to be absolute in py3.8+
        # importlib.util.spec_from_file_location does this automatically from
        # 3.10+
        # This was backported to 3.8 and 3.9, but then reverted in 3.8.11 and
        # 3.9.6
        # See https://twistedmatrix.com/trac/ticket/10230
        # and https://bugs.python.org/issue44070
        fn = os.path.join(os.getcwd(), fn)
```
https://github.com/pytest-dev/pytest/blob/d200598de9588fe6d7a68bddc3e638afce80f153/src/_pytest/pathlib.py#L500

**Comment by sgaist** [comment]
Hi,

I would like to take care of this one for Hacktoberfest.

**Comment by nicoddemus** [comment]
In the end we verified this is not needed, see: https://github.com/pytest-dev/pytest/pull/9140#issuecomment-980014177

Thanks @graingert!
