### ISSUE TITLE
Dead link in README for 'assert statements'

### ISSUE THREAD

**Issue by greyblue9** [pytest-dev/pytest#8926]
Title says it all; the link (which is part of the first item in a series of bullet points) points to:
[https://docs.pytest.org/en/stable/how-to/assert.html](https://docs.pytest.org/en/stable/how-to/assert.html) 

... but the destination reports "Page Not Found"

**Comment by RonnyPfannschmidt** [comment]
unless i'm mistaken, we want it to point to https://docs.pytest.org/en/stable/assert.html now

**Comment by RonnyPfannschmidt** [comment]
we should also add a redirect i believe

**Comment by nicoddemus** [comment]
> we should also add a redirect i believe

It is the other way around: the redirect is already in place for the new URL: `/assert.html -> /how-to/assert.html`. However we can't add a redirect in the other direction too, I believe.

**Comment by The-Compiler** [comment]
> It is the other way around: the redirect is already in place for the new URL: `/assert.html -> /how-to/assert.html`. However we can't add a redirect in the other direction too, I believe.

Turns out we can, as redirects only trigger if there is a 404. Thus, I added all the reverse redirects now!
