### ISSUE TITLE
MonkeyPatch doesn't affect file if imported differently somewhere else

### ISSUE THREAD

**Issue by boanergies** [pytest-dev/pytest#8931]
- [X] a detailed description of the bug or problem you are having
- [X] output of `pip list` from the virtual environment you are using
- [X] pytest and operating system versions
- [X] minimal example if possible

So essentially I have a pydantic settings file I'm monkeypatching to test when a certain environment variable isn't set. Specifically I'm monkeypatching to make sure the environment variable is never set and a class attribute in the pydantic settings class is set to `None` to not have the pydantic settings class to look for a .env file as explained [here](b0lvonlb_2ZKGHdhVhkQhkWdQhYe6jEyVwdxArsuK) when using python-dotenv in development.

The test file imports the settings file essentially in this manner
`from src.config import DatabaseSettings`

The actual file working with the DatabaseSettings imports it this way
`from config import DatabaseSettings`

I'm setting the attribute as below
`monkeypatch.setattr(DatabaseSettings.Config, "env_file", None)`

For some reason though during the test `env_file` does not come up None in the file I'm testing. If though I change the import in that file being tested to be
`from src.config import DatabaseSettings`
Suddenly it gets the monkeypatched value for "env_file"

My tests directory is a sub package in the src directory due to how I'm deploying my code currently (long story). I run `python -m pytest` within the src directory. 'src' is a package and so is the 'tests' directory.

It looks like this
```
src/
src/__init__.py
src/config.py
src/database.py
src/tests/__init__.py
src/tests/test_database.py
```

Pip list:
Package            Version
------------------ ---------
aiofiles           0.7.0
appdirs            1.4.4
astroid            2.5.6
attrs              21.2.0
black              21.5b1
certifi            2021.5.30
charset-normalizer 2.0.3
click              8.0.1
deta               1.0.0
fastapi            0.67.0
flake8             3.9.2
h11                0.12.0
idna               3.2
iniconfig          1.1.1
isort              5.8.0
Jinja2             3.0.1
lazy-object-proxy  1.6.0
MarkupSafe         2.0.1
mccabe             0.6.1
mypy               0.812
mypy-extensions    0.4.3
packaging          20.9
pathspec           0.8.1
pip                21.1.3
pluggy             0.13.1
py                 1.10.0
pycodestyle        2.7.0
pydantic           1.8.2
pyflakes           2.3.1
pylint             2.8.2
pyparsing          2.4.7
pytest             6.2.4
python-dotenv      0.17.1
regex              2021.4.4
requests           2.26.0
setuptools         57.4.0
starlette          0.14.2
toml               0.10.2
typed-ast          1.4.3
typing-extensions  3.10.0.0
urllib3            1.26.6
uvicorn            0.13.4
wheel              0.36.2
wrapt              1.12.1

Linux, Ubuntu, WSL

**Comment by nicoddemus** [comment]
Hi,

Can you pring `DatabaseSettings` right after importing it, both in your test file and your actual file? For example:

```python
from src.config import DatabaseSettings
print(DatabaseSettings)
print(DatabaseSettings.__module__)
```

My guess is that, due to your configuration, you are getting *two* separate modules imported, and hence, two different classes (which happen to have the same name).

**Comment by boanergies** [comment]
From the database file, or the file being tested
<class 'config.DatabaseSettings'>
config

From the test file
<class 'meal_planning.config.DatabaseSettings'>
meal_planning.config
meal_planning being the 'src' directory

It is definitely the same file

**Comment by nicoddemus** [comment]
You can see however that you have to different classes `<class 'config.DatabaseSettings'>` and `<class 'meal_planning.config.DatabaseSettings'>`.

In Python, if you execute `import foo` in a file and `import src.foo` in another, you effectively end up with two different modules, even if in the underlying file system they both come from the same file.

So this is not really a pytest issue, but just how the Python import machinery works.

**Comment by boanergies** [comment]
Can you post a link to docs explaining this so I can understand what your talking about in the future?

**Comment by boanergies** [comment]
Just in case others run into this issue as well like I did. This is not a problem with `monkeypatch` in pytest but has to do with how python imports files.
when you do the following imports for the same files
```Python
from src.config import Settings
from config import Settings
```

Though you may think your importing the same file, python apparently caches them as individual imports according to the path of import.

This is confirmed when you look at `sys.modules` and print out values as shown below:
```Python
print(sys.modules["config"])
print(sys.modules["src.config"])
```

So in essence if you monkeypatch the Settings imported just from `config` then you won't be changing the Settings imported from `src.config`
