### ISSUE TITLE
tmpdir_factory does not remove the old symlink named pytest-$user

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#894]
pre tmpdir-factory we created a tmp folder  named `pytest-$user` linking to the current numbered dir

now py.test fails to create the tmpdir due to trying to create that name as a folder

to fix it we need to use a different name, since just using that name will break older py.test from different virtualenvs

i propose using the folder name `pytest-of-$user`

**Comment by The-Compiler** [comment]
Could this be the same issue as [my comment](https://github.com/pytest-dev/pytest/pull/851#issuecomment-124856548) on #851?

**Comment by RonnyPfannschmidt** [comment]
actually yes
