### ISSUE TITLE
Abridged assertions still cannot be disabled by using -vv (ellipses)

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#8940]
It seems that the abridging feature proves to be quite hard to neuter, even after #8391. While running with `pytest==6.2.4`, i can still see how assertions are abridged and I fail to see what was the real error causing them, even when running with `-vv` mode.

[![](https://sbarnea.com/ss/Screen-Shot-2021-07-24-10-32-48.18.png)](https://github.com/ansible-community/ansible-compat/pull/30/checks?check_run_id=3149951962)

`result` is a CompletedProcess, one with multi-ling stdout.stderr and is essential to display it in full in order to get an idea about what went wrong.

Note that even tried `-vvv` and `-vvvv` without any visible outcome. Did I miss something?

**Comment by nicoddemus** [comment]
#8403 has not been released yet, it will be released in `7.0.0`. Our 7.0.0 is long overdue, unfortunately.

**Comment by ssbarnea** [comment]
Sorry, my mistake that i missed to spot that. I only looked at date of last release, date of merge and assumed it was released.

I may prove useful to assign 7.0 milestone to those merged to master to make it more clear when they are expected to ship. I could do this but i need triage permissions.

**Comment by nicoddemus** [comment]
> I could do this but i need triage permissions.

Strange, you are already a member of pytest-dev, you should have those permissions already.

**Comment by ssbarnea** [comment]
The only projects where I can add/remove labels/milestones/assignees are those where I am core, like https://github.com/pytest-dev/pytest-testinfra -- i checked few others and I do not see any edit options. It may worth investigating as I suspect that is the same for others.

**Comment by nicoddemus** [comment]
Ahh added you to the Contributors team, that should do it.
