### ISSUE TITLE
DOC: pytest.mark.parametrize on class definition should be documented

### ISSUE THREAD

**Issue by pllim** [pytest-dev/pytest#8947]
#### What's the problem this feature will solve?

Using `pytest.mark.parametrize` on class definition should be documented. It is mentioned in https://stackoverflow.com/questions/17434031/parametrizing-test-classes-in-pytest/ (the second answer) and it works, but I cannot find it hinted at https://github.com/pytest-dev/pytest/blob/main/doc/en/example/parametrize.rst . All the existing example involving classes are way too complicated for the particular usage I am looking for.

```python
import pytest


@pytest.mark.parametrize('x', [1, 2])
class TestMe:
    def test_1(self, x):
        print(f'test 1: {x}')

    def test_2(self, x):
        print(f'test 2: {x}')
```

gives me correctly:

```
test 1: 1
test 1: 2
test 2: 1
test 2: 2
```

But since it is not documented, is it only working by accident? Or it is actually supported?

#### Describe the solution you'd like

Document it if it is actually a supported usage.

#### Alternative Solutions

Disallow it if it is not actually a supported usage.

#### Additional context

astropy/astropy#11972

cc @WilliamJamieson

**Comment by The-Compiler** [comment]
This isn't specific to parametrize and documented here: https://docs.pytest.org/en/6.2.x/example/markers.html#marking-whole-classes-or-modules

**Comment by pllim** [comment]
Thanks for the quick response! Interesting... completely missed it. Well, feel free to close though I still think some cross-referencing would benefit users.

**Comment by RonnyPfannschmidt** [comment]
We should have examples for class /module levels so people can go by concrete examples,

Beginners can't as easily generalise some details as very well versed users

**Comment by eamanu** [comment]
HI I'm interest to work in this issue.

**Comment by nicoddemus** [comment]
@eamanu thanks! The idea would be to add two examples of using `@pytest.mark.parametrize` for classes and modules to https://github.com/pytest-dev/pytest/blob/main/doc/en/how-to/parametrize.rst.

**Comment by eamanu** [comment]
@nicoddemus I'm just create the PR :) thanks!
