### ISSUE TITLE
pytest.skip: Rename "msg" to "reason" for consistency with pytest.mark.skip/xfail?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#8948]
The [signature of `pytest.skip` is](https://docs.pytest.org/en/latest/reference/reference.html#pytest-skip):

```python
skip(msg[, allow_module_level=False])
```

but the [signature of `pytest.xfail` is](https://docs.pytest.org/en/latest/reference/reference.html#pytest-xfail):

```python
xfail(reason='')
```

Marks ([pytest.mark.skip](https://docs.pytest.org/en/latest/reference/reference.html#pytest-mark-skip), [pytest.mark.skipif](https://docs.pytest.org/en/latest/reference/reference.html#pytest-mark-skipif) and [pytest.mark.xfail](https://docs.pytest.org/en/latest/reference/reference.html#pytest-mark-xfail)) use `reason` too:

```python
pytest.mark.skipif(condition, *, reason=None)
pytest.mark.xfail(condition=None, *, reason=None, raises=None, run=True, strict=False)¶
pytest.mark.skipif(condition, *, reason=None)¶
```

Note that `pytest.fail` [uses `msg`](https://docs.pytest.org/en/latest/reference/reference.html#pytest.fail):

```python
fail(msg='', pytrace=True)
```

but at least from an user perspective, `skip` is probably closer to `xfail` and `mark.skip` / `mark.skipif` / `mark.xfail`.

Should we rename the `msg` argument for `pytest.skip` to `reason` for consistency (with a deprecation for the old name), or isn't that worth the trouble?

*Thanks to Francesco Casalegno for reporting this in the pytest training I gave at Europython 2021 today!*

**Comment by RonnyPfannschmidt** [comment]
lovely find, should do

**Comment by nicoddemus** [comment]
Agreed. Also should not affect many users as I suspect almost everyone just writes `pytest.skip("some message")` rather than `pytest.skip(msg="some message")`, so they shouldn't be affected.

**Comment by symonk** [comment]
👍 agree to unify, however I am one of the ones who uses `reason=` 😄

**Comment by The-Compiler** [comment]
A very quick look at https://grep.app/search?q=pytest.skip%28msg%3D shows some common projects affected by this, so I think we definitely need a proper deprecation.

**Comment by Zac-HD** [comment]
I'd be inclined to move to `pytest.fail(reason=...)` as well, while we're at it.

And IMO we should probably organise some PRs to help downstream OSS projects make the transition (by deleting `msg=`, since the positional arg will work on either side of the transition).

**Comment by nicoddemus** [comment]
> I'd be inclined to move to pytest.fail(reason=...) as well, while we're at it.

Makes sense, better to do a "all 'msg' arguments changed to 'reason'" in one swoop, rather than leave an outlier there.

**Comment by The-Compiler** [comment]
Some (naive) code searches:

- `pytest.fail(msg=`: [15 on grep.app](https://grep.app/search?q=pytest.fail%28msg%3D), [128 on Sourcegraph](https://sourcegraph.com/search?q=context:global+pytest.fail%28msg%3D&patternType=literal), [7 on Debian Code Search](https://codesearch.debian.net/search?q=pytest.fail%28msg%3D&literal=1)
- `pytest.skip(msg=`: [45 on grep.app](https://grep.app/search?q=pytest.skip%28msg%3D), [112 on Sourcegraph](https://sourcegraph.com/search?q=context:global+pytest.skip%28msg%3D&patternType=literal), [9 on Debian Code Search](https://codesearch.debian.net/search?q=pytest.skip%28msg%3D&literal=1)

Positional usage:

- `pytest.fail`: [1121 on grep.app](https://grep.app/search?q=pytest%5C.fail%5C%28%5B%22%27%5D&regexp=true), [7.3k on Sourcegraph](https://sourcegraph.com/search?q=context:global+pytest%5C.fail%5C%28%5B%22%27%5D+count:8000&patternType=regexp), [767 on Debian Code Search](https://codesearch.debian.net/search?q=pytest%5C.fail%5C%28%5B%27%22%5D&literal=0)
- `pytest.skip`: [3700 on grep.app](https://grep.app/search?q=pytest%5C.skip%5C%28%5B%22%27%5D&regexp=true), [25k on Sourcegraph](https://sourcegraph.com/search?q=context:global+pytest%5C.skip%5C%28%5B%22%27%5D+count:30000&patternType=regexp), [2612 on Debian Code Search](https://codesearch.debian.net/search?q=pytest%5C.skip%5C%28%5B%27%22%5D&literal=0)

**Comment by nicoddemus** [comment]
Thanks for the results @The-Compiler.

In case it wasn't clear, I definitely agree we should add `reason` and deprecate `msg`, not replace (and break calls) right away.

**Comment by symonk** [comment]
Thanks all, I will carve out some time tonight after work to attempt to unify `reason=` across the board in places, I have made a start.  After I have a few PRs i will look at initially creating follow up PRs to move plugins inside `pytest-dev/` using `msg=` explicitly to use `reason=` or pass w/o keyword.

**Comment by symonk** [comment]
should `exit(msg=` also be deprecated?, I'm not sure if that _fits_ into this as elegantly, is msg more appropriate for it's use case?
