### ISSUE TITLE
make `--debug` more configurable via `--debug-file` or `--debug-append`

### ISSUE THREAD

**Issue by symonk** [pytest-dev/pytest#8954]
Hi, it is probably common (enough) that when using `xdist` people are running pytest multiple time(s), I think @nicoddemus even mentioned he does this, we do in work similar like:

```python
# multiple jenkins stages & pytest invocations are involved in one 'CI run'
pytest -m parallel and not isolated --debug
pytest -m isolated --debug
```

By default `--debug` opens the `pytestdebug.log` file with `w` which means collecting artifacts later to assist with debugging when using a CI system like jenkins for example is often problematic as you will only receive the isolated runs debug logs here

I propose one of the following:

- `--debug-file=debug1.log` (I think keeping the same root dir here but allowing unique names could be beneficial)
- `--debug-append` which _appends_ (`a`) to the file if it already exists

Thoughts? I will PR if you think its got any merit

**Comment by nicoddemus** [comment]
Hi @symonk,

I like the idea and suggestions, with one small change: perhaps we can change `--debug` to accept an optional filename, defaulting to `pytestdebug.log`? That would be just an additional command-line flag then, rather than two new ones.
