### ISSUE TITLE
The setup_module() function is not called in a special case.

### ISSUE THREAD

**Issue by h2cw2l** [pytest-dev/pytest#8966]
- [ ] a detailed description of the bug or problem you are having
Thank you very much, I just want to ask a question.  Any reply will be appreciated.

I want to init the param in @pytest.mark.parametrize() by the setup_xxx() function, but it runs failed.
How can I realized this ?
① setup_module() is not called and run failed
![图片](https://user-images.githubusercontent.com/58133919/127766522-5e8871ad-b8a4-4bd5-a12e-ac50130fd79e.png)
result:
![图片](https://user-images.githubusercontent.com/58133919/127766679-89518da0-b5a2-4f70-a5f3-603f572195a1.png)

  ②  setup_module() is called and run pass
  ![图片](https://user-images.githubusercontent.com/58133919/127766485-44405943-3c9b-4360-b957-993e56f45ed6.png)
result:
![图片](https://user-images.githubusercontent.com/58133919/127766687-aa31cb9b-d40d-46f9-b5de-4d8eac35862b.png)

- [ ] output of `pip list` from the virtual environment you are using
[root@bogon test]# pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
attrs (21.2.0)
bcc (0.14.0)
blivet (3.2.2)
Brlapi (0.6.7)
cffi (1.11.5)
chardet (3.0.4)
chrome-gnome-shell (0.0.0)
configobj (5.0.6)
coverage (4.5.1)
cryptography (2.3)
cupshelpers (1.0)
dasbus (1.2)
dbus-python (1.2.4)
decorator (4.2.1)
ethtool (0.14)
gpg (1.13.1)
idna (2.5)
importlib-metadata (4.6.1)
iniconfig (1.1.1)
iniparse (0.4)
initial-setup (0.3.81.6)
isc (2.0)
langtable (0.0.51)
meson (0.58.1)
netaddr (0.7.19)
netifaces (0.10.6)
nftables (0.1)
ntplib (0.3.3)
ordered-set (2.0.2)
packaging (21.0)
pciutils (2.3.6)
perf (0.1)
pid (2.1.1)
pip (9.0.3)
pluggy (0.13.1)
ply (3.9)
productmd (1.11)
pwquality (1.4.0)
py (1.10.0)
pycairo (1.16.3)
pycparser (2.14)
pycups (1.9.72)
pycurl (7.43.0.2)
pydbus (0.6.0)
pyelftools (0.27)
pygobject (3.28.3)
pyinotify (0.9.6)
pykickstart (3.16.11)
pyOpenSSL (18.0.0)
pyparsing (2.4.7)
pyparted (3.11.0)
PySocks (1.6.8)
pytest (6.2.4)
python-dateutil (2.6.1)
python-dmidecode (3.12.2)
python-linux-procfs (0.6.2)
python-meh (0.47.2)
pytz (2017.2)
pyudev (0.21.0)
pyxdg (0.25)
PyYAML (3.12)
requests (2.20.0)
requests-file (1.4.3)
requests-ftp (0.3.1)
rhnlib (2.8.6)
rpm (4.14.3)
schedutils (0.6)
selinux (2.9)
sepolicy (1.1)
setools (4.3.0)
setroubleshoot (1.1)
setuptools (39.2.0)
simpleline (1.1.1)
six (1.11.0)
slip (0.6.4)
slip.dbus (0.6.4)
sos (3.9)
SSSDConfig (2.3.0)
subscription-manager (1.27.16)
syspurpose (1.27.16)
systemd-python (234)
toml (0.10.2)
typing-extensions (3.10.0.0)
urllib3 (1.24.2)
zipp (3.5.0)
[root@bogon test]#
- [ ] pytest and operating system versions
![图片](https://user-images.githubusercontent.com/58133919/127766651-08528ee5-919c-4cad-8304-f64923a466cc.png)

- [ ] minimal example if possible

**Comment by symonk** [comment]
at a glance `parametrize` is likely evaluated at interpretation time, long before the `setup_module()` runs, which is why your list is empty, example two passes in a `[1,1]` and that is why it works, as `setup_module()` is called, but later than you think?

note: I am not familiar with `setup_module()`

**Comment by h2cw2l** [comment]
> 
> 
> at a glance `parametrize` is likely evaluated at interpretation time (decorator), long before the `setup_module()` runs, which is why your list is empty, example two passes in a `[1,1]` and that is why it works (pytest is happy with `[1,1]` but ofcourse, not with `[]`, as `setup_module()` is called, but later than you think.
> 
> note: I am not familiar with `setup_module()`

Thanks for your reply.

Is there any way can init the param before the test run,
so the param  can be dynamically inited and I don't need to assign it sunch as [1, 1].
I think this is significant.

**Comment by Zac-HD** [comment]
I think a (function-scoped) parametrized fixture would solve this for you, since they can get the list of params just before running the test.
