### ISSUE TITLE
Allow setting configuration options in `conftest.py`

### ISSUE THREAD

**Issue by Kodiologist** [pytest-dev/pytest#8981]
The page https://docs.pytest.org/en/6.2.x/customize.html describes the various forms of configuration files pytest supports. Not mentioned is `conftest.py`, nor how options of this kind, such as `addopts`, can be set in `conftest.py`, which would be desirable so that one could put all of one's pytest configuration in one place.

**Comment by asottile** [comment]
*code* in conftest.py is not *configuration* but it can set options, I'm not sure mentioning it in the place about configuration files is quite correct

**Comment by Kodiologist** [comment]
`conftest.py` is not documented as a thing unto itself elsewhere, only mentioned in passing while documenting e.g. plugins. This seems like an obvious place to put it to me, although I'm not that familiar with the documentation, so that doesn't mean much.

**Comment by RonnyPfannschmidt** [comment]
Structurally only initial conftests can do it

We need to document this better

**Comment by Kodiologist** [comment]
It looks like you set configuration options in `conftest.py` using the `pytest_configure` hook. I translated this `setup.cfg`:

```ini
[tool:pytest]
# Be sure to include Hy test functions with mangled names.
python_functions=test_* hyx_test_*
filterwarnings =
    once::DeprecationWarning
    once::PendingDeprecationWarning
    ignore::SyntaxWarning
    ignore::pytest.PytestReturnNotNoneWarning
```

into this hook:

```python
def pytest_configure(config):
    config.getini('python_functions').extend([
        'test_*',
        'hyx_test_*'])
    config.getini('filterwarnings').extend([
        'once::DeprecationWarning',
        'once::PendingDeprecationWarning',
        'ignore::SyntaxWarning',
        'ignore::pytest.PytestReturnNotNoneWarning'])
```

If this is a bad idea for some reason, let me know. I don't want to use `setup.cfg` in the same project, so any potential conflicts between these two ways of setting the same options aren't an issue.

**Comment by RonnyPfannschmidt** [comment]
@Kodiologist the examples you posted are extremely fragile,work only by luck and will certainly break if the order of things changes

**Comment by Kodiologist** [comment]
Good to know.

**Comment by RonnyPfannschmidt** [comment]
Note that you can use other configuration files like pypropject.toml or pytest.ini/tox.ini

**Comment by RonnyPfannschmidt** [comment]
Closing this as not planned, contests are plugins, not configuration files

**Comment by Kodiologist** [comment]
Do you think it's worth editing https://docs.pytest.org/en/7.4.x/reference/customize.html to point out that `conftest.py` also exists and that, despite its name, it's not considered a configuration file?

**Comment by RonnyPfannschmidt** [comment]
Based on behavior of people it would likely have the opposite effect
