### ISSUE TITLE
Warn when a test doesn't assert anything

### ISSUE THREAD

**Issue by djmattyg007** [pytest-dev/pytest#9005]
#### What's the problem this feature will solve?

Every now then someone writes a test that doesn't behave exactly you're expecting. Instead of asserting something, your test winds up doing nothing useful at all and doesn't run any assert statements.

As it stands right now, pytest will just tell me that a test like this passed successfully. I would prefer it if pytest was proactive in warning me that the test didn't actually do anything, so that I can fix the test.

#### Describe the solution you'd like

Pytest should have a separate count for these tests that do not assert anything. PHPUnit calls them "risky" or "useless" tests, and I think this is a good name for them:

https://phpunit.readthedocs.io/en/9.5/risky-tests.html

Ideally it would be on by default, because I can't imagine why you wouldn't want to be notified that your tests aren't behaving as expected. However, I appreciate that this could create a BC nightmare. Therefore it might be necessary to make it so that these warnings are only displayed if a flag is passed or a specific configuration option is set (eg. `notify-useless-tests`).

#### Alternative Solutions

I first enquired about whether or not such a feature already existed in the discussions forum:

https://github.com/pytest-dev/pytest/discussions/9004

And was informed of a feature (that is, at the time of writing, not in a released version of pytest) named "assertion pass hooks". I could supposedly combine this with some other logic to introduce a hacky way of checking for this myself. However, I have no idea how I could possibly integrate this cleanly into the general output provided by pytest in my terminal.

Using a linter was also suggested. I believe this is a non-solution, because it would require the linter to be aware of every single way in which an assertion could be made. On the other hand, pytest is already natively aware of when an `assert` statement is used regardless of where it appears in python code.

**Comment by nicoddemus** [comment]
> And was informed of a feature (that is, at the time of writing, not in a released version of pytest) named "assertion pass hooks". 

It was released in 5.0.

As discussed in #9004, this can be implemented through a plugin, and I don't think this should be integrated into the core before a plugin is published and there is enough demand from users to integrate this functionality into the core.

Thanks for the suggestion.
