### ISSUE TITLE
Make explicit which fixtures a test use

### ISSUE THREAD

**Issue by taliaga** [pytest-dev/pytest#901]
Hi everyone,

Sometimes in big projects with multiple fixtures (many of which with *autouse*) I feel it gets tricky to track which fixtures will be used for the test I am about to write and consequently know what will happen behind the scenes. Therefore, I thought it'd be interesting to have a way (a command, maybe?) to show all the fixtures a test will be using (even via autouse declarations).

Has anybody felt the same about it? Would that be worth implementing?

**Comment by taliaga** [comment]
Note: I couldn't find the "issue kind" the pytest/CONTRIBUTING.rst refers to for suggestions. Neither was I able to add labels to this issue.

**Comment by nicoddemus** [comment]
Thanks for the report! :smile: 

It seems to be a GitHub limitation the fact that issue submitter can't add labels.

**Comment by pfctdayelise** [comment]
Seems like a good idea for a plugin :)

**Comment by nicoddemus** [comment]
Hmmm... forgot about [pytest-fixture-tools](https://github.com/pytest-dev/pytest-fixture-tools). Certainly this functionality could be implemented there, I think. @bubenkoff, what do you think?

**Comment by bubenkoff** [comment]
I agree, a good place

**Comment by nicoddemus** [comment]
@taliaga, could you move this issue to [pytest-fixture-tools](https://github.com/pytest-dev/pytest-fixture-tools) please? I'm closing this here then. :smile:
