### ISSUE TITLE
Delayed step execution and test result without holding testing.

### ISSUE THREAD

**Issue by govindasharma1986** [pytest-dev/pytest#9012]
_(I am a non technical QA so please ignore my technical ignorance)_
#### What's the problem this feature will solve?

I would be running E2E tests using selenium and then checking few things in DB. Some checks would be immediate while **some _checks_ would be delayed for some known duration.**

These checks are delayed because the API under test create a job which execute after 20min to insert/update something in DB table.

API is tightly coupled with frontend cookies so cannot separately test this functionality through API unit/integration testing.

These tests are compliance related so cannot ignore them. For now manually testing them once a week. It is real pain ...

Let's say if, I have 35 such tests and each automation test needs to wait for 20 mins then the total duration of test execution is very high.

Lets consider a scenario: 
I have few test files in which there are 5 tests. At the end of each test method there are 4 assertions. The last 2 assertion needs me to verify something in a DB table after 'x' mins. For each test method, the waiting duration for each last 2 assertion could be varying (>=15min) and this would be known beforehand. 

Now I have tried,
1. time.sleep(duration)
    1. This just holds up entire testing.

2. Even concurrent/parallel execution does not help because when they reach last 2 assertion statements in each test method then they all have to wait for a duration and it just halts testing for given time.

3. Thought of using RabbitMQ with Celery and scheduling those assertions but by the time these assertions would be executed, pytest would have assigned all tests a status: (Pass/Fail). So if test1 was marked as Pass and after 10 mins after assertion executes and it Fails then I would not be able to update status of test1 in pytest.

#### Describe the solution you'd like

I have few things in mind: 
1. Support for delayed execution of a statement in test method. Such statements should be the last few statements in a test method.
2. Test results should wait for completion of execution of delayed statement.
3. The result of such tests or test method would be updated after delayed assertions are over.
4. The delays should be of two types,
    1. Simultaneously starting timer for each assertions. If duration for assertion2 is more than assertion1 then option should be to wait for assertion1 to complete (sequential execution) or execute assertion2 before assertion1(nonconsecutive execution)
    2. Timer for assertion2 should start after timer for assertion1 is over i.e. executed.
5. When running parallel tests, then the process should not wait for these test methods. After scheduling these delayed statements, it should start with next test method. (It is always understood that such delayed statements would be the last few statements of test method)

These checks are delayed because the API under test creates a job which execute after 20min to insert/update something in DB table.

API is tightly coupled with frontend cookies so cannot separately test this functionality through API unit/integration testing.

These tests are compliance related so cannot ignore them. For now manually testing them once a week. It is real real real pain ...

Let's say if, I have 35 such tests and each automation test needs to wait for 20 mins then the total duration of test execution is very high.

#### Alternative Solutions

Now I have tried,
1. time.sleep(duration)
    1. This just holds up entire testing.

2. Even concurrent/parallel execution does not help because when they reach last 2 assertion statements in each test method then they all have to wait for a duration and it just halts testing for given time.

3. Thought of using RabbitMQ with Celery and scheduling those assertions but by the time these assertions would be executed, pytest would have assigned all tests a status: (Pass/Fail). So if test1 was marked as Pass and after 10 mins after assertion executes and it Fails then I would not be able to update status of test1 in pytest.

#### Additional context

Is it doable?
I would really appreciate if you could consider it 👍

**Comment by RonnyPfannschmidt** [comment]
A common solution is to use something like wait_for/tenancy to wait for the conditions in combination with xdist for getting parallel test execution

Currently pytest doesn't support running "async" tests concurrently in the same process

**Comment by govindasharma1986** [comment]
@RonnyPfannschmidt 
I have a kind request.

Can u pls describe a pseudocode or an article/doc reference where something similar is implemented?

**Comment by RonnyPfannschmidt** [comment]
https://pypi.org/project/wait-for/
https://pypi.org/project/retrying/

are some lbiraries for patters to wait for something to hold true
the common solution is to wait for the system too have the data one did sent to it
