### ISSUE TITLE
always show full diff in ci

### ISSUE THREAD

**Issue by davidszotten** [pytest-dev/pytest#9023]
Hi,

would you accept a patch to extend #1314 (Always show full comparison output if on CI) to add similar behaviour to the [diff output for iterables](https://github.com/pytest-dev/pytest/blob/16077f2a65a1e02560ba123cfc7afd0f25fbb34e/src/_pytest/assertion/util.py#L290)?

**Comment by nicoddemus** [comment]
I think so, the rationale is the same. Would love a patch in that direction. 👍
