### ISSUE TITLE
Issues with pytest for Bigquery Dataframe

### ISSUE THREAD

**Issue by paudelsubodh** [pytest-dev/pytest#9026]
Locally, I can get dataframe.

However, 
while testing using pytest

```python
bq=bigquery.Client(project='xyz')
query_string="SELECT *FROM <table_name>"
df = bq.query(str(query_string)).result().to_dataframe()
assert df
```

It will through an error 

```python
    @final
    def __nonzero__(self):
        raise ValueError(
>           f"The truth value of a {type(self).__name__} is ambiguous. "
            "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
        )
E       ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

/opt/conda/lib/python3.7/site-packages/pandas/core/indexes/base.py:2574: ValueError
```

How we can hide this error message or it is some bug with pytest?

**Comment by RonnyPfannschmidt** [comment]
The error precisely tells how to handle the results data in a non ambiguous way

**Comment by paudelsubodh** [comment]
> The error precisely tells how to handle the results data in a non ambiguous way

Do you mean it is an issues with query_string= return f""" SELECT *FROM <table_name>""" or what should I change to avoid such ambiguous index error.

**Comment by RonnyPfannschmidt** [comment]
the value error on the assert of `df` telly you to use one of the listed methods instead

**Comment by nicoddemus** [comment]
Dataframes can't be used in a boolean context, like `assert` or `if`. You will get the same error if you write `if df:` for example.

You should use `assert df.any()`, `assert df.bool()`, whatever you want to test.

Closing for now, feel free to follow up with further questions.
