### ISSUE TITLE
Parametrized tests don't display unicode in ids correctly.

### ISSUE THREAD

**Issue by solarmist** [pytest-dev/pytest#9037]
```python
@pytest.mark.parametrize(
    "string1", [
        pytest.param("test1", id="unicode in id い")
])
def test_unicode_in_param_id(string1:str) -> None:
    assert string1 == "test1"

```

running it with `pytest -v test.py` gives me

```
platform darwin -- Python 3.9.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /usr/local/opt/python@3.9/bin/python3.9
cachedir: .pytest_cache
rootdir: /Users/solarmist/repos/pytest
collected 1 item

test.py::test_unicode_in_param_id[unicode in id \u3044] PASSED                                                                                                                                                                                         [100%]
```

I expected the [] to show `unicode in id い`

`pip list`

```Package    Version
---------- -------
pip        21.2.4
setuptools 57.4.0
wheel      0.36.2```

This is on a macOS 11.4.

**Comment by brandonchinn178** [comment]
> Also I put the option in my `pyproject.toml` file as
> 
> ```
> [tool.pytest]
> disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
> ```
> 
> [...]
> 
> but was unable to get any of those variations to display unescaped unicode.

So I found that if you're explicitly doing `pytest.param(..., id="...")`, it'll always escape, regardless of configuration:
https://github.com/pytest-dev/pytest/blob/245a8c23dd0ffeb03710f0fbabd1f5e6a56611ab/src/_pytest/mark/structures.py#L95

As opposed to when the parameter itself is a string:
https://github.com/pytest-dev/pytest/blob/245a8c23dd0ffeb03710f0fbabd1f5e6a56611ab/src/_pytest/python.py#L1050

So perhaps it's a bug in that pytest should use the same logic with both explicit `id="..."` and implicit ids. But personally, I would suggest that **explicitly set ids should not be escaped**. I would also accept the solution of _add a `escape=False` argument to `pytest.param` to turn off escaping_, if pytest devs want to avoid breaking backwards compat.

I also want to echo other sentiments that this shouldn't be hidden in a flag, unicode should be the default everywhere, and OSes that have issues with pytest showing unicode should be updated (or perhaps a flag to enable unicode escaping in pytest).

**Comment by RonnyPfannschmidt** [comment]
My first comment still applies ...

**Comment by ALLinLLM** [comment]
@solarmist I meet this problem today, and this is my workaround, wish it can help u as well: 
change this line in __init__ in the `Node` class in file: <your_python_path>/site-packages/_pytest/main.py:
 `self.name: str = name.encode("utf-8").decode("unicode_escape")` 

and it works for me with Ubuntu 20.04 python3.10, pytest 7.4.0
![image](https://github.com/pytest-dev/pytest/assets/15920086/8a960555-a73a-4abe-b785-7cd7eac594b7)

after change, the source code `_pytest/main.py` like this:
``` python
class Node(metaclass=NodeMeta):
    """Base class for Collector and Item, the components of the test
    collection tree.

    Collector subclasses have children; Items are leaf nodes.
    """

    # Implemented in the legacypath plugin.
    #: A ``LEGACY_PATH`` copy of the :attr:`path` attribute. Intended for usage
    #: for methods not migrated to ``pathlib.Path`` yet, such as
    #: :meth:`Item.reportinfo`. Will be deprecated in a future release, prefer
    #: using :attr:`path` instead.
    fspath: LEGACY_PATH

    # Use __slots__ to make attribute access faster.
    # Note that __dict__ is still available.
    __slots__ = (
        "name",
        "parent",
        "config",
        "session",
        "path",
        "_nodeid",
        "_store",
        "__dict__",
    )

    def __init__(
        self,
        name: str,
        parent: "Optional[Node]" = None,
        config: Optional[Config] = None,
        session: "Optional[Session]" = None,
        fspath: Optional[LEGACY_PATH] = None,
        path: Optional[Path] = None,
        nodeid: Optional[str] = None,
    ) -> None:
        #: A unique name within the scope of the parent node.
        self.name: str = name.encode("utf-8").decode("unicode_escape")
```

**Comment by RonnyPfannschmidt** [comment]
Since we no longer support python 2 we ought to revisit that mr

**Comment by riZZZhik** [comment]
```toml
[tool.pytest.ini_options]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
```

Fixed issue for me with russian parameters in `@pytest.mark.parametrize`
