### ISSUE TITLE
pluggy 1.0.0 is incompatible with pytest

### ISSUE THREAD

**Issue by HilitOreny** [pytest-dev/pytest#9044]
I upgraded my pluggy version to 1.0.0.
Pip notified me that pluggy 1.0.0 is incompatible with pytest. Pytest 6.2.4 requires pluggy<1.0.0a1,>=0.12.
See the error message in the screenshot below:
![pytest pluggy dependancy problem](https://user-images.githubusercontent.com/69712717/131106013-6b0758be-ae9b-47df-83d8-6e287ca14759.jpg)

I use a Windows 10 Home 64-bit laptop.
My python version is 3.9.6.
I did not use any virtual environment. I simply opened the Command Prompt and run "pip list --outdated".
Here is a full list of all my packages and their versions using pip list:
astroid           2.7.2
atomicwrites      1.4.0
attrs             21.2.0
colorama          0.4.4
et-xmlfile        1.1.0
iniconfig         1.1.1
isort             5.9.3
jdcal             1.4.1
lazy-object-proxy 1.6.0
mccabe            0.6.1
numpy             1.21.2
openpyxl          3.0.7
packaging         21.0
pandas            1.3.2
pip               21.2.4
platformdirs      2.2.0
pluggy            1.0.0
py                1.10.0
pylint            2.10.2
pymongo           3.12.0
pyparsing         2.4.7
PySimpleValidate  0.2.12
pytest            6.2.4
python-dateutil   2.8.2
pytz              2021.1
setuptools        57.4.0
six               1.16.0
stdiomask         0.0.6
toml              0.10.2
wheel             0.37.0
wrapt             1.12.1

**Comment by hemna** [comment]
I'm using pip-compile to update my packages and pytest's use of the old pluggy is preventing me from a release.

```
ERROR: Cannot install pluggy==0.13.1 and pluggy==1.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pluggy==1.0.0
    The user requested pluggy==0.13.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by nicoddemus** [comment]
We will release `6.2.5` today which will loose the package requirement.

**Comment by nicoddemus** [comment]
`6.2.5` has been released, thanks for everyone who reported the problem. 👍
