### ISSUE TITLE
New pytest -k syntax does not seem to work for me after --

### ISSUE THREAD

**Issue by Ark-kun** [pytest-dev/pytest#9052]
I use an internal system that ultimately calls pytest `pytest.main(args=args)`:

`args` array always starts with `"--"` and ends with a test file path. I can only control what's in the middle.

When I'm using the deprecated test-exclusion syntax `["-k-azure"]` everything works (azure tests are excluded).
However when I use the suggested new syntax `["-k", "azure"]` it does not seem to do anything - all tests are executed.

Could there be any issue with the parsing of the new `-k` syntax after `--`?

P.S. Sorry, I'm new to pytest and learning it just to set up a minimal standalone repro would take some time.

- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions; Linux; Python 3.7.10, pytest-6.2.3
- [ ] minimal example if possible

**Comment by Ark-kun** [comment]
Getting errors with `["-k", "not azure"]`:
```
ERROR: Wrong expression passed to '-k': not: at column 4: expected not OR left parenthesis OR identifier; got end of input
```

`["-k", "not (azure)"]`
```
ERROR: file or directory not found: (azure)
```

It's as if the arguments are just concatenated to the command-line using spaces. But we're passing the args in the list form, not as a single string...

**Comment by bluetech** [comment]
It is more likely that instead of passing `["-k", "not azure"]` to pytest you are actually passing `["-k", "not", "azure"]`. Please recheck exactly what is passed to pytest.

**Comment by tamird** [comment]
This is still an issue.
```
poetry run pytest tests/my_test.py -vv -k "hello world"
===================================================================================================================================================== no tests ran in 0.10s ======================================================================================================================================================
ERROR: Wrong expression passed to '-k': hello world: at column 7: expected end of input; got identifier
```

You can see that pytest correct sees the value of `-k` as `"hello world"` rather than `["hello", "world"]`.

**Comment by RonnyPfannschmidt** [comment]
@tamird its expected to use a operator there

**Comment by The-Compiler** [comment]
`and` or `or` - I don't see how your example is connected to this issue, and it's working as expected.

**Comment by tamird** [comment]
Operators seem to be optional, an expression without an operator should just substring match.

```
  -k EXPRESSION         Only run tests which match the given substring expression. An expression is a Python evaluatable expression where all names are substring-matched against test names and their parent classes. Example: -k 'test_method or
                        test_other' matches all test functions and classes whose name contains 'test_method' or 'test_other', while -k 'not test_method' matches those that don't contain 'test_method' in their names. -k 'not test_method and not
                        test_other' will eliminate the matches. Additionally keywords are matched to classes and functions containing extra names in their 'extra_keyword_matches' set, as well as functions which have names assigned directly to them.
                        The matching is case-insensitive.
```

**Comment by The-Compiler** [comment]
Yes, and and as the error told you, `hello world` is not a valid Python-like expression... I'm still not sure why you expect this to work, or what you'd expect it to even do.

**Comment by tamird** [comment]
I'd like to be able to pass an expression that contains spaces. It's not possible to express `"hello world" and "good day"` today, as far as I can tell.

**Comment by The-Compiler** [comment]
That's correct, but seems entirely unrelated to this issue. Please open a feature request, and consider explaining a bit more about what problem this solves, i.e. *why* you're wanting to do that.

**Comment by smarie** [comment]
Thanks @The-Compiler 
I have had the same problem as @tamird for years : parametrized test identifiers are usually created from the parameters of a test, through either some direct string representation or customization of `ids` in `pytest.mark.parametrize`. In some situations the id associated with a parameter will contain a space. This is currently accepted by `pytest`. However the filtering mechanism with '-k' does not work as expected (as shared by @tamird ) in this situation. It could help to 

- either be more strict (refusing identifiers containing spaces) 
- or to make sure the keyword-based filtering feature works in this situation.

I hope this clarifies a bit ! Thanks for the support !

**Comment by RonnyPfannschmidt** [comment]
keyword matching is mostly a leftover from earlier days from before marks


keywords where the precursor of marks, and pretty much limited to a syntax like

```python
# python 2.3 test code with pytest 
def test_messy():
   pass

test_messy.integration = True
```

these days keywords match subsets of names, and markers 
the situation around spaces was always a bit strange - i recall was an accidental short for an and expressions


with massive issues around certain kinds of matching/missmatches in one of the reakign releases we eventually made sure its using the much more constrainte synxtax to prevent a lot oft the other user errors

im not sure if theres a sensible way to get space suppot in there

im not fond of escaping or shell quoting a identifier

**Comment by smarie** [comment]
Thanks ! If I'm not mistaken, markers would be hard to use in order to slice through a list of parameters. For example a parameter is "dataset_id" and its values are a few thousands of identifiers as string "D1", "D2", etc. "-k" works well here to select only a few parameter values. But it fails when spaces are present.

**Comment by RonnyPfannschmidt** [comment]
For such a use case id currently recommend creating a own cli arg for selection

**Comment by smarie** [comment]
Thanks @RonnyPfannschmidt . I need to dig into the docs more, as it does not seem obvious to me how to relate a new cli option with a filtering done on a parameter defined in a test. You probably mean leveraging the modifyitems hook then. This is not very elegant as this is not "baked in" (as the '-k' cli is). But it most probably can work with custom code in a hook
