### ISSUE TITLE
Based on parameter run tests

### ISSUE THREAD

**Issue by ManishIBM** [pytest-dev/pytest#9058]
#### What's the problem this feature will solve?
In pytest based on parameters, I need not to include/exclude to run a test. We can achieve it by using skip but in the report, it reduces the pass percentage. Skip appears like the test is skipped on this run but expected to run. But in many case, we know that the test will not be called in certain cases.

Example: Suppose I am writing test of different controls on pages (pages are passed by pytest parameter). I wrote tests like test_lable, test_link, test_button etc. 
On some page all controls are not present, in that case I am able to skip but I think those tests should not be generated. Or those tests should not be in scope. In report it reduces the passed percentage which is misleading.

#### Describe the solution you'd like
There should be a way to enable/disable a test case dynamically

**Comment by nicoddemus** [comment]
Hi @ManishIBM, 

> There should be a way to enable/disable a test case dynamically

There is, you can write a custom [`pytest_collection_modifyitems`](https://docs.pytest.org/en/stable/reference.html) hook, where you can remove tests from the list using any criteria you need.

**Comment by ManishIBM** [comment]
> Hi @ManishIBM,
> 
> > There should be a way to enable/disable a test case dynamically
> 
> There is, you can write a custom [`pytest_collection_modifyitems`](https://docs.pytest.org/en/stable/reference.html) hook, where you can remove tests from the list using any criteria you need.

Thanks @nicoddemus I am trying the approach

**Comment by nicoddemus** [comment]
Cool, closing for now then, feel free to follow up with further questions though.

**Comment by ManishIBM** [comment]
> > Hi @ManishIBM,
> > > There should be a way to enable/disable a test case dynamically
> > 
> > 
> > There is, you can write a custom [`pytest_collection_modifyitems`](https://docs.pytest.org/en/stable/reference.html) hook, where you can remove tests from the list using any criteria you need.
> 
> Thanks @nicoddemus I am trying the approach

when I used the hook, I am able to deselect required tests and got message like:
**collected 33 items / 10 deselected / 23 selected**

when the execution completed, the 10 deselected are showing again as skipped like:
 
<img width="223" alt="image" src="https://user-images.githubusercontent.com/38526728/131361276-b0da5d3b-ea3e-4f67-a681-ed40a380bf7e.png">
Above output can be achieved by on skipping the test using pytest.skip. I am looking at a way by which I don't get the skipped status for the deselected tests and will not appear in report as well.

**Comment by nicoddemus** [comment]
Can you post the code for the hook?

**Comment by ManishIBM** [comment]
def pytest_collection_modifyitems(items, config):
    disabled_tcs = get_disable_tests_list()
    deselect_tcs = []
    selected_tcs = []
    for tc_item in items:
        res = check_and_disable_test(tc_item, disabled_tcs)    ----> The function is to check whether the TC should run or not
        if res is not None:
            deselect_tcs.append(tc_item)    ----> Exclude the TC
        else:
            selected_tcs.append(tc_item)  ----> Include the TC

    config.hook.pytest_deselected(items=deselect_tcs)
    items = selected_tcs

**Comment by ManishIBM** [comment]
> def pytest_collection_modifyitems(items, config):
> disabled_tcs = get_disable_tests_list()
> deselect_tcs = []
> selected_tcs = []
> for tc_item in items:
> res = check_and_disable_test(tc_item, disabled_tcs) ----> The function is to check whether the TC should run or not
> if res is not None:
> deselect_tcs.append(tc_item) ----> Exclude the TC
> else:
> selected_tcs.append(tc_item) ----> Include the TC
> 
> ```
> config.hook.pytest_deselected(items=deselect_tcs)
> items = selected_tcs
> ```

seems my fault...it should be like items[:] = selected_tcs
