### ISSUE TITLE
when grpc with stream returned in pytest fixture, the tests are not able to run

### ISSUE THREAD

**Issue by NickYin0125** [pytest-dev/pytest#9071]
```python
@pytest.fixture
def grpc_session():
    return PricingHelper.connect_to_pricing()

@pytest.fixture
def market_data(grpc_session):
    return PricingHelper.get_market_data(grpc_session)
```

as you see above, the `get_market_data()` method will receive stream data from grpc server, however when I try to use the `market_data` fixture, pytest will block in this fixture and won't start the test.

**Comment by nicoddemus** [comment]
Hi @NickYin0125,

That's strange, pytest just calls the fixture functions and hands the result of the call to functions/other fixtures. 

Can you use that code in a simple snippet instead? 

For example, what does the python script below prints?

```python
# missing imports of course
grpc_session = PricingHelper.connect_to_pricing()
print(PricingHelper.get_market_data(grpc_session))
```
