### ISSUE TITLE
ref count leakage of fixture objects

### ISSUE THREAD

**Issue by stefanseefeld** [pytest-dev/pytest#9083]
I'm writing tests involving C++ objects that need to be constructed during test setup and destructed during test teardown. Unfortunately the destruction during teardown doesn't work reliably, so I have tried to synthesize a minimal (pure Python) test case that replicates the issue. The following test case should be pretty clear: I'm constructing an object `a` during setup, pass it down into the test, then delete it during teardown. In between I'm printing its ref-count:
```python
import pytest
import sys

class A:
    def __init__(self): print('A.__init__')
    def __del__(self): print('A.__del__')

@pytest.fixture
def a():
    a = A()
    print(f'in setup: a ref count={sys.getrefcount(a)}')
    yield a
    print(f'in teardown: a ref count={sys.getrefcount(a)}')
    del a
    print('done!')
    
def test_1(a):
    print(f'in test: a ref count={sys.getrefcount(a)}')
```
And here is the actual output when I run this with `pytest -vs`:
```
========================= test session starts ==========================
platform linux -- Python 3.8.10, pytest-4.6.9, py-1.8.1, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/stefan/tsi/pytest-bug
plugins: forked-1.3.0, asyncio-0.10.0
collected 1 item

test_ref_count.py::test_1 A.__init__
in setup: a ref count=2
in test: a ref count=7
PASSEDin teardown: a ref count=4
done!
A.__del__
```
Note that `a` 's destructor is only called *after* teardown, rather than *during* teardown. (The effect for me is that in a case with many tests, multiple `a` objects will co-exist, which my code doesn't support !)

What seems rather intriguing is that during setup I get a ref count of `2`, while during teardown I get a ref count of '4'. Where do the extra ref counts come from ? Are they responsible for the belated cleanup ?

Any suggestions for how I can fix my test setup such that the first `a` will be destroyed prior to the `a` of the following test will be constructed ?

(I have been trying to work around this problem by using the `pytest-forked` plugin, but that opens an entirely new can of worms, e.g. https://github.com/pytest-dev/pytest-forked/issues/55)

**Comment by RonnyPfannschmidt** [comment]
There is no leak, but there are some references that are cleaned up later as part of the fixture system

This is yet another example why relying on the gc is the incorrect way to do resource management

Unlike c++ python does not have RAII

**Comment by RonnyPfannschmidt** [comment]
@stefanseefeld without more context, the only suggestion i can make is to detach your resource cleanup from your reference lifecycles (in python this is done with context managers instead of RAII)

i hope that pytest eventually can solve this better (but currently have to bookkeep fixture references in a number of places to ensure things don't break down

a possible crude hack to work around it would be to return a `weakref.proxy` so nobody bu the fixture has actual references

does this reasonably solve your issue?
