### ISSUE TITLE
Error parsing test ID in command-line.

### ISSUE THREAD

**Issue by stefanseefeld** [pytest-dev/pytest#9087]
As part of my test suite I have a parametrized test, which I can invoke as
```
pytest  python/tests/tmini/test_scenarios.py::test_scenario[replace_battery]
```

I'm now trying to run this test repeatedly, so I installed the `pytest-repeat` addon. Adding the `--count=5` option, I suddenly get this error:

```
pytest --count=100 python/tests/tmini/test_scenarios.py::test_scenario[replace_battery]
========================================================================= test session starts =========================================================================
platform linux -- Python 3.8.5, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/user/srcdir
plugins: forked-1.3.0, repeat-0.9.1, timeout-1.4.2
collected 0 items                                                                                                                                                     

======================================================================== no tests ran in 0.16s ========================================================================
ERROR: not found: /home/user/srcdir/python/tests/tmini/test_scenarios.py::test_scenario[replace_battery]
(no name '/home/user/srcdir/python/tests/tmini/test_scenarios.py::test_scenario[replace_battery]' in any of [<Module python/tests/tmini/test_scenarios.py>])
```
which suggests something is wrong with the way the command-line arguments are processed. Given the generic nature of the error I assume this is a `pytest` bug, rather than a `pytest-repeat` bug. Let me know if I should report that elsewhere.

**Comment by nicoddemus** [comment]
Isn't your shell escaping it? Try:

```
pytest 'python/tests/tmini/test_scenarios.py::test_scenario[replace_battery]'
```

**Comment by stefanseefeld** [comment]
Why would my shell treat this differently depending on the presence of the `--count=...` argument ?
The quoting didn't change anything.

**Comment by stefanseefeld** [comment]
I don't quite understand how the "python/tests/tmini/test_scenarios.py::test_scenario[replace_battery]" argument is mapped to a test ID during the `pytest` initialization, but somehow this process is perturbed (and broken) by the presence of the `--count` argument.
I'd appreciate any suggestion on how to debug this further.

**Comment by nicoddemus** [comment]
Things to try:

1. Remove `--count=100`.
2. Move `--count=100` to the end.

Also please show the output of `pytest --collect-only`.

**Comment by stefanseefeld** [comment]
* removing `--count=100`: as I already reported, that works fine, just as expected.
*  moving `--count=100` to the end: I observe the same (erroneous) behaviour as having it before the test ID argument.
* output of `pytest --collect-only`:
  * with `--count=100` I get the same error as before
  * without `--count=100` I get the expected
     ```
        <Module python/tests/tmini/test_scenarios.py>
          <Function test_scenario[replace_battery]>
    ```

**Comment by nicoddemus** [comment]
What's the output you get with `pytest --count=100 python/tests/tmini/test_scenarios.py --co`?

Also try `pytest --count=100 python/tests/tmini/test_scenarios.py -k replace_battery`

**Comment by stefanseefeld** [comment]
First question: I get output starting with:
```
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/user/srcdir
plugins: forked-1.3.0, repeat-0.9.1, timeout-1.4.2
collected 3900 items

<Module python/tests/tmini/test_scenarios.py>
  <Function test_scenario[fail-1-100]>
  <Function test_scenario[fail-2-100]>
  <Function test_scenario[fail-3-100]>
   ...
```
(and a very long list of functions)

Second question:
That invocation works, i.e. my test is executed correctly.

**Comment by nicoddemus** [comment]
That explains it then, `pytest-repeat` does its work by parametrizing your test with `count`, which changes the id of the test:

https://github.com/pytest-dev/pytest-repeat/blob/a57dcde99966d515010435ffc4613f576d3f579f/pytest_repeat.py#L66-L73

I suggest to use `-k` then, which doesn't depend on the exact id, being a fuzzy match.

**Comment by stefanseefeld** [comment]
Oh, that's a rather surprising (but clear, in hindsight) explanation. It might be useful to explain these test ID changes clearly, but that's an entirely separate issue...

Thanks for helping me understand the issue !
