### ISSUE TITLE
Pylance check error:"Final" not allowed in this context

### ISSUE THREAD

**Issue by markshao** [pytest-dev/pytest#9095]
working on vscode (mac os BigSure) withremote mode (connnect to the linux vm)
- vm os: Debian 9.13
- vm python: python 3.8.7 installed via pyenv
- visual studio code: v 1.60.0

got error of type lint for the reason :"Final" not allowed in this context, check the file 
- compat.py
```python
NOTSET: "Final" = NotSetType.token  # noqa: E305
```

- pytester.py
```python
    CLOSE_STDIN: "Final" = NOTSET
```

do anyone has the same trouble like me ?

Looks like dont have any image , everything works fine on command line , and can ignore it through adding comment "# type: ignore"

**Comment by bluetech** [comment]
This might be a problem in pytest, but it looks like a proper application of `Final` to me and I can't think why it wouldn't be allowed. So I suggest reporting this to pylance/pyright and see what they think.
