### ISSUE TITLE
Add convenience method getRecordsForLogger to LogCaptureFixture

### ISSUE THREAD

**Issue by kasium** [pytest-dev/pytest#9110]
#### What's the problem this feature will solve?
In many tests I'm only interested to see the log records of one logger. So I have quite often
```python
[record for record in caplog.records if record.name == logger_name]
```

#### Describe the solution you'd like
It would be great to have a convenience method at LogCaptureFixture like `getRecordsForLogger`.
As an alternative, a method similar to setLevel which only captures the logs of a particular logger.

```python
def test(caplog):
  caplog.setLogger("myLogger")
  # test
  assert caplog.records[0]
```

#### Alternative Solutions
Code it yourself

#### Additional context
I'm very happy to give a PR a try 😄

**Comment by kasium** [comment]
PR is closed, so this request was declined

**Comment by nicoddemus** [comment]
Thanks @kasium, forgot to close the issue. 👍
