### ISSUE TITLE
Py.test hangs while diffing `bytes` objects when assertion fails

### ISSUE THREAD

**Issue by demberto** [pytest-dev/pytest#9124]
My test:
```Python
def test_equality():
      # original and new are bytes object
      assert original == new
```

`py.test` worked correctly when the assertions were true, however instead of failing, it gets stuck on some infinite loop probably because CPU usage is quite high and sustained until I quit it manually.

When I exit out, a `KeyboardInterrupt` from `difflib.py` is emitted, which likely indicates that pytest is stuck on diffing, my bytes objects are about ~100kb size in minimum, I don't need the diff, how do I disable it?

**Comment by Zac-HD** [comment]
See also #7206, #8404, and #8998 - this is (unfortunately) a known issue, and we're waiting for someone to implement the heuristic proposed in https://github.com/pytest-dev/pytest/issues/8998#issuecomment-900389987.

**Comment by demberto** [comment]
I didn't even use the `-v` flag with py.test, still its diffing
