### ISSUE TITLE
Abort immediately upon syntax error in conftest (or at least on autoused fixtures)

### ISSUE THREAD

**Issue by ChanceNCounter** [pytest-dev/pytest#9135]
I accidentally ran a macro on conftest and broke a fixture. When I ran pytest, I noticed and aborted in 1.44 seconds. During that time, pytest scanned and failed 52 tests. 1.44 seconds of pytest execution was followed by almost 2 minutes of console spam over SSH.

There is absolutely no reason pytest should've continued after the first failure. The fixture fires on every test. Every test was always going to fail. I got the same 29 lines of traceback and feedback 52 times in a row on a remote connection.

I am quite annoyed.

**Comment by RonnyPfannschmidt** [comment]
pytest can hardly know if a fixture is broken once or all the time,

as no context/output is included, your request is simply not actionable

the `-x` and `--maxfail $n`cli options provide control over this and i highly recommend using them when sssh and many tests  are involved

also syntax error doesn't make any sense, a syntax error would end test collection

feel free to reopen if you have actionable information

**Comment by ChanceNCounter** [comment]
I will produce more information in a few hours. I do not, however, appreciate the attitude.

**Comment by ChanceNCounter** [comment]
Okay. Here goes.

1) Put a syntax error in any module.  
2) Import it inside a fixture. Don't worry about why, because I am SO FAR BEYOND not in the mood to argue with you. You need to understand that you guys work on a tool with which hundreds of thousands of developers are professionally stuck whether we like it or not.  
3) Run your test suite.

> also syntax error doesn't make any sense, a syntax error would end test collection

No kidding.

**Comment by ChanceNCounter** [comment]
Oh, and outsiders don't have the "reopen" button. Does this project set out to upset users?
