### ISSUE TITLE
Make it clear in the documentation that fixtures are not suitable for managing resource lifecycles

### ISSUE THREAD

**Issue by gsmethells** [pytest-dev/pytest#9141]
#### What's the problem this feature will solve?
Partitioned off of https://github.com/pytest-dev/pytest/issues/5243

Proposal: Make it clear in the pytest documentation that users are responsible for resource lifecycle management. 

Currently, [there are misleading examples](https://docs.pytest.org/en/latest/how-to/fixtures.html#parametrizing-fixtures) such as:

```
@pytest.fixture(scope="module", params=["smtp.gmail.com", "mail.python.org"])
def smtp_connection(request):
    smtp_connection = smtplib.SMTP(request.param, 587, timeout=5)
    yield smtp_connection
    print("finalizing {}".format(smtp_connection))
    smtp_connection.close()
```

that suggest otherwise. The above fixture from the documentation is highly suggestive that pytest believes fixtures are appropriate to use for resource management; however, [pytest is only a test runner and not a resource manager](https://github.com/pytest-dev/pytest/issues/5243#issuecomment-931629005) according to @asottile

#### Describe the solution you'd like
A documentation change that makes it clear that pytest fixtures are not fit for the purpose of handling resource lifecycles in all cases (user beware). There are likely other places in the documentation that require review concerning this point.

Also, it would be useful to all users to document common ways a user can handle resource lifecycles, especially for external resources that could be leaked, that are known to work smoothly with pytest's framework.

#### Alternative Solutions
None

#### Additional context
Identified during discussions in:

- https://github.com/pytest-dev/pytest/issues/5243

**Comment by nicoddemus** [comment]
Hi @gsmethells,

Not sure I agree, "not suitable for managing resource lifecycles" is a bit strong worded. For example even if we handled `SIGTERM` as commented in #5243, a crash in the process would still leave dangling resources.

I'm OK with adding a note that `SIGTERM` is not handled thought.

**Comment by gsmethells** [comment]
`SIGSEGV` would be a pretty dire case that is beyond any software to handle and is also a bit strongly worded rebuke to the proposal. 

`Fixtures have no built-in failsafe regarding resource leaks.` 

That is the essence of the necessary change to the documentation. How loud or quiet it may be desired to be, users should have fair warning that fixtures cannot handle:

- `SIGINT`
- `SIGTERM`
- `SIGQUIT`

However, it is a fact that:

1. `SIGTERM` is in common use by CI runners like GitLab, Jenkins, et al when they cancel a CI job
2. [pytest is only  a test runner and not a resource manager](https://github.com/pytest-dev/pytest/issues/5243#issuecomment-931629005) according to @asottile 

Therefore, it is a fair assessment, given both those facts, that "fixtures are not [fit for the purpose](https://en.wiktionary.org/wiki/fit_for_purpose) of resource lifecycle management."

`SIGSEGV` goes without saying and does not belong in the discussion.

**Comment by asottile** [comment]
_@gsmethells I recommend you take a step back and consider how you're communicating -- we understand you're passionate about this issue but you don't need to use inflammatory language to get your point across.  please be nice -- there are humans on the other side of the cable_

as is standard in python, SIGINT *is handled* (via raising `KeyboardInterrupt`) which calls finalizers / teardowns / etc. -- you'll recall my recommendation from the original thread was to [transform SIGTERM into SIGINT to extend that behaviour if you want it](https://github.com/pytest-dev/pytest/issues/5243#issuecomment-491522595)

**Comment by gsmethells** [comment]
@asottile understood

**Comment by gsmethells** [comment]
I seek to help other users than myself. I believe the best place for it, in this case, is in the documentation given the stances I learned by spending my time on these threads instead of helping doctors with their patients and our software.

The suggested solution would need further refinement to suss out issues for more complicated test suite codebases. It doesn't work for us. That can be figured out in #9142 at some point.

Until then, I hope you will agree that the current documentation is not definitive concerning where the responsibility of resource lifecycle management rests and how best to go about it. I lay it out as I do in a proof format more for the formality of my thoughts than any intention to be unkind and I am sorry if it was taken otherwise. If it is any consolation, I spent a good part of my waking hours being useful regarding the Sept 30th [Let's Encrypt's snafu](https://www.zdnet.com/article/fortinet-shopify-others-report-issues-after-root-ca-certificate-from-lets-encrypt-expires/) for hundreds of clinics in every state of the U.S. (some of the largest in the country) and I'm pretty spent, but that's no excuse.

**Comment by nicoddemus** [comment]
> Until then, I hope you will agree that the current documentation is not definitive concerning where the responsibility of resource lifecycle management rests and how best to go about it.

I agree, how about something like:

```
pytest does not do any special processing for `SIGTERM` and `SIGQUIT` signals (`SIGINT` is handled naturally by the Python runtime via `KeyboardInterrupt`), so fixtures that manage external resources which are important
to be cleared when the Python process is terminated by those signals might leak resources.

If fixtures in your suite need special care regarding termination in those scenarios, consider using the pytest-XXX plugin.
```

My intent here is explicitly warn about the signals not handled by pytest, and provide an alternative when handling those signals is important.

**Comment by nicoddemus** [comment]
@asottile out of curiosity, what drawbacks you see in making pytest handle `SIGTERM` to stop executing and execute teardown (like we do with `KeyboardInterrupt`)? I think having the drawbacks explicitly helps explaining to users *why* pytest doesn't handle them. 

(I'm wondering about concrete points, not necessarily about the definition/terminology of "resource manager" vs "test runner")

**Comment by asottile** [comment]
signal handlers are global and if pytest starts adding them that will interfere with execution of current code in a surprising way (I know specifically of at least one private project that breaks due to testing signal handlers directly)

**Comment by nicoddemus** [comment]
Ahh makes sense, thanks!

**Comment by gsmethells** [comment]
@nicoddemus I'm good with the above blurb. Thanks for taking the time to write it up.

**Comment by gsmethells** [comment]
@asottile thanks for taking the time to explain why signal handlers do not belong in pytest core.

**Comment by nicoddemus** [comment]
PR open: https://github.com/pytest-dev/pytest/pull/9150
