### ISSUE TITLE
Documentation for caplog `set_level()` should make it clearer it's a threshold

### ISSUE THREAD

**Issue by MetRonnie** [pytest-dev/pytest#9146]
#### What's the problem this feature will solve?

The [documentation for `caplog.set_level()`](https://docs.pytest.org/en/stable/reference.html#pytest.LogCaptureFixture.set_level) says
> Set the level of a logger for the duration of a test.

This does not make it clear that it's setting the _threshold_ level for capturing logging.

#### Describe the solution you'd like

The Python logging documentation makes this clear for `logging.setLevel()`:
> Sets the threshold for this logger to level. Logging messages which are less severe than level will be ignored; ...

`caplog.set_level()` ought to do the same.

#### Additional context

The only reason I know it's a threshold is because I tried running `pytest -rA` with different levels set in caplog and the output contained messages at that level and above

**Comment by nicoddemus** [comment]
Thanks @MetRonnie for the detailed report.

Would you like to contribute that change?

**Comment by MetRonnie** [comment]
Happy to, is it just a case of updating https://github.com/pytest-dev/pytest/blob/main/doc/en/reference/fixtures.rst?

**Comment by Vijay-Arora** [comment]
Hey @nicoddemus and @MetRonnie, I am new to contributing to open source and I'm looking for a good first issue. Could you please kindly guide me if I can pick up this or any issue which you think might be useful for me to start with?
Thanks in advance!

**Comment by nicoddemus** [comment]
Thanks @MetRonnie and @Vijay-Arora.

Just need to update the docstring at:

https://github.com/pytest-dev/pytest/blob/f65dfc39f36c6a4289e8af852e49869c1cb2be78/src/_pytest/logging.py#L449-L458

**Comment by Vijay-Arora** [comment]
Hey @nicoddemus and @MetRonnie, I did it! As it's my first time, let me know in case any change is required.

**Comment by Vijay-Arora** [comment]
Also @nicoddemus, I first forked it and then contributed; I was wondering if we can directly open a PR without forking and creating our own branch in this repository itself? Is that allowed?

**Comment by nicoddemus** [comment]
>  I was wondering if we can directly open a PR without forking and creating our own branch in this repository itself? Is that allowed?

Only for project contributors (as there are security concerns to let anyone commit to the repository).

**Comment by nicoddemus** [comment]
Also I don't see a PR? You might have just pushed that branch to a fork, but you need to open a Pull Request. Consult GitHub's help for more information. 👍

**Comment by Vijay-Arora** [comment]
Oh okay. Thanks for the quick response, @nicoddemus!

**Comment by Vijay-Arora** [comment]
> Also I don't see a PR? You might have just pushed that branch to a fork, but you need to open a Pull Request. Consult GitHub's help for more information. 👍

Hmm, okay, thanks for the heads up! Will update here as soon as I see how to make that work.

**Comment by Vijay-Arora** [comment]
Hey @nicoddemus, I added a PR; it's visible now but i think i missed some of the points. Could you take a look at it and give me some feedback on it?

**Comment by kushagrabhushan** [comment]
Hello @Vijay-Arora @nicoddemus @MetRonnie! I am also just getting started with open-source and wanted to start contributing. I just had a question whether this issue is currently open or has it been closed?

**Comment by MetRonnie** [comment]
@kushagrabhushan This is still open but there is already a pull request #9149 to close it (you can see this in the "Linked pull requests" section in the sidebar at the top)

**Comment by Vijay-Arora** [comment]
@kushagrabhushan, I'm actively working on it, I'll be picking this up from where I left this on Friday.

**Comment by DaveParr** [comment]
Is this still needing action and able to be acted on? 

I'm looking to get invoolved in hacktoberfest 2022, and this issue is now a year old. FWIW I understand from the users persepective how pytest works and how the caplog process can be utilised in tests.

**Comment by tuhinmallick** [comment]
Is this issue still open, if yes i would like to work on it
