### ISSUE TITLE
These should be synonomous: __init__(self) & setup_class()

### ISSUE THREAD

**Issue by ghostsquad** [pytest-dev/pytest#918]
see issue #410
@nicoddemus :+1: 

an exception should be thrown if BOTH are provided.

**Comment by The-Compiler** [comment]
IMHO, `setup_class` is mainly there for nose compatibility, and (possibly autouse) fixtures should be used when writing "pytest-style" tests - so I don't see the point of this.

**Comment by nicoddemus** [comment]
@ghostsquad, I'm not sure I understand what you mean... are you sure you are referring to the correct issue? Also the subject of this issue is "These should be synonomous: __init__(self) and setup_class()" but in the body of the issue you say that an exception should be thrown if both are provided...?

**Comment by The-Compiler** [comment]
@nicoddemus - in #410 you said:

> So I'm closing this issue. If people would like to discuss if having an `__init__` without parameters should be collected, I think a new issue should be opened.

@ghostsquad is saying writing

```python

class Test:

    def __init__(self):
        do_some_setup()

    def test_foo(self):        
        pass
```

should be equivalent to writing

```python
class Test:

    def setup_class(self):
        do_some_setup()

    def test_foo(self):        
        pass
```

But if an user would define both `__init__` and `setup_class`, an exception would be raised as it's ambigious.

As said, my take on it is that there shouldn't be *another different* way of doing init/teardown - fixtures are the only pytest way to do it, and everything else is there for nose/unittest compatibility, should only be used for those cases, and shouldn't have new features (or ways to do things) added. But I'd like to hear other opinions before closing this.

**Comment by nicoddemus** [comment]
I see, thanks @The-Compiler! :smile:

I agree with you, we already have pytest-style (fixtures), all the other styles are for compatibility only.

**Comment by ghostsquad** [comment]
it seems the pytest favors modules over classes in terms of using the `addfinalizer`. With pytest fixtures, it seems that it also favors explicit "dependency injection" over something like this (C#):

```C#
public class testingStuff : IDisposable {
    // set value when instance is initialized
    private string bar = "initial value"

    //or setting the value in the constructor
    public testingStuff() {
         this.bar = "initial value from ctor"
    }

    [Fact]
    public void testFoo() {
       // use this.bar for something
    }

    public void Dispose() {
       // close file handles, or other resources here
    }
}
```

With that said, I guess what this comes down to, is how can pytest act more like [x|n|j]unit style classes?

The wrong way to reference a value:
```Python
mod_var = "initial module value"

def test_foo() {
   global mod_var;
   #do something with mod_var
}
```

The dependency injection way
```Python
@pytest.fixture(scope="function")
def before(request):
    # create resource
    thing1 = "thing1"

    def after():
        print('\nhulk smash ' + thing1)

    request.addfinalizer(after)

    return thing1

def test_foo(before):
    myValue = before
    # do something with resource created in "before" fixture
```

If you have more than 1 object that needs to be reference between tests, you must use a tuple, or dictionary, which I suppose is... ok??

Thoughts?

**Comment by RonnyPfannschmidt** [comment]
@ghostsquad setup_class and __init__ can never be synoyms, setup_class is outside of instanciation

**Comment by The-Compiler** [comment]
> If you have more than 1 object that needs to be reference between tests, you must use a tuple, or dictionary, which I suppose is... ok??

If they're closely related (say, you need the file object and a filename from a fixture*), the usual thing I've seen people do is to use a namedtuple:

```python
@pytest.yield_fixture
def testfile():
    fileret_tpl = collections.namedtuple('fileret_tpl', 'filename, file')
    filename = 'blah'
    with open(filename, 'r') as f:
        yield fileret_tpl(filename, f)

def test_foo(testfile):
    assert testfile.filename == 'blah'
```

If they're unrelated, they probably should be two separate fixtures.

`*` I know this is a made-up example, since a file object usually has a `filename` attribute

**Comment by ghostsquad** [comment]
@The-Compiler that works for me. I'll close this issue.
