### ISSUE TITLE
Codecov bash uploader is deprecated

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#9202]
The Codecov bash uploader that the CI is using is deprecated and will stop working on Feb 1, 2022, with brownouts before then.

https://about.codecov.io/blog/introducing-codecovs-new-uploader/

We should update to their new uploader.

The relevant file is https://github.com/pytest-dev/pytest/blob/5fc7b21391c959bb5a54174d9084ad55131b8fdb/scripts/upload-coverage.sh

Called in CI from here: https://github.com/pytest-dev/pytest/blob/5fc7b21391c959bb5a54174d9084ad55131b8fdb/.github/workflows/main.yml#L168-L172

Note: the `scripts/upload-coverage.sh` script itself can stay in bash; just the codecov file it downloads should be changed to the new one.

**Comment by bluetech** [comment]
Correct me if I'm wrong, but I don't think it will make the `upload-coverage.sh` redundant, since still need to do the `python -m coverage xml` step. So maybe it's not worth it...

**Comment by mPandaRed** [comment]
Is this `upload-coverage.sh` file only being used in the GitHub action? If so, it looks like there is a pre-built Action created for Codecov V2:
https://github.com/marketplace/actions/codecov
