### ISSUE TITLE
Incorrectly dropping brackets on display of assertions

### ISSUE THREAD

**Issue by DRMacIver** [pytest-dev/pytest#925]
If I have the following test:

```python
def test_ternary_display():
    assert (False == False) == False
```

then this will correctly fail, but will display as:

```
    def test_ternary_display():
>       assert (False == False) == False
E       assert False == False == False

display.py:2: AssertionError
```

This is wrong. The brackets are required because "False == False == False" evaluates to True. In Python this is the same as "(False == False) and (False == False)" due to [the rules about chaining operators](https://docs.python.org/2/reference/expressions.html#not-in).

**Comment by The-Compiler** [comment]
While looking at this in IRC, I also found a case where it's not wrong, but pytest adds/changes brackets:

```
>       assert (False == False) and False
E       assert (False == False and False)
```

**Comment by RedBeardCode** [comment]
What would be a suspected output for the case.
assert  False==(False == False)==True
?

**Comment by RedBeardCode** [comment]
I started to implement a solution and it works for the first given case, but to make it really general it is more work.
