### ISSUE TITLE
pytest captures warnings which are already captured in tested code

### ISSUE THREAD

**Issue by trendelkampschroer** [pytest-dev/pytest#9259]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

Pytest captures warnings when testing a calling function that already captures warnings from the called function.

Minimal example:

```python
import pytest
import warnings
pytestmark = pytest.mark.filterwarnings("error")

def f():
    warnings.warn("I am warning you")

def g():
    with warnings.catch_warnings(record=True):
        f()

def test_g():
    g()
```

Pytest fails because of `UserWarning` issued by function `f`, although the calling function `g` is catching all warnings when calling `f`. I'd expected the test to pass, as the warning from `f` was already handled by `g`.

Output of `pip list`

```
Package            Version
------------------ --------
attrs              21.2.0
importlib-metadata 4.8.1
iniconfig          1.1.1
packaging          21.2
pip                21.3.1
pluggy             1.0.0
py                 1.10.0
pyparsing          2.4.7
pytest             6.2.5
setuptools         57.0.0
toml               0.10.2
typing-extensions  3.10.0.2
warnings-capture   0.0.0
wheel              0.36.2
zipp               3.6.0

```

Pytest and operating system versions:

* pytest 6.2.5
* macOS BigSur 11.6

I'd be glad for any suggestions/help in understanding whether this is desired behaviour or a bug.

**Comment by Kojoley** [comment]
`warnings.catch_warnings` does not reset the filters, but it will revert any changes to filters on `__exit__`ing `with` block, so you can achieve what you want like that:
```python
    with warnings.catch_warnings(record=True):
        warnings.simplefilter("always")
        f()
```

**Comment by trendelkampschroer** [comment]
@Kojoley : Thanks a lot for clarifying this.
