### ISSUE TITLE
`pytest.Instance` is not documented in the API Reference

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#9265]
The `Instance` collector type is part of the public API and is passed to some hooks, e.g. `pytest_pycollect_makeitem`, so we should explain what it is (it is not very obvious!).

**Comment by bluetech** [comment]
Looking at `Instance`, I'm think we might want to get rid of it instead of publicizing it more. I'll post a proposal for this after #9273 is merged.

**Comment by RonnyPfannschmidt** [comment]
@bluetech i want to remove instance for more than 5 years now ^^ and at the same time introduce FunctionDefinition more directly

**Comment by bluetech** [comment]
This is made irrelevant by #9277.
