### ISSUE TITLE
Document that pytest.warns affects default DeprecationWarning processing

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#9291]
As discussed in https://github.com/pytest-dev/pytest/issues/9288#issuecomment-965102239, using `pytest.warns` will by design also capture `DeprecationWarning`s which would by default be captured by pytest.

We should add a note about that in `pytest.warns` and the section about DeprecationWarnings handling.

**Comment by fddemora** [comment]
Hi is this issue still open? I noticed there is a commit to close the issue.

**Comment by toclarity** [comment]
Hi @nicoddemus, from @clarityai-eng we'd like to contribute with this PR to make the documentation clearer on how  `pytest.warn` is affecting other posible raised warnings.

We hope you find it useful, let us know if it fits your requirements.

**Comment by toclarity** [comment]
Hi! We have updated the MR, please take a look at it whenever you can. Thanks! :)
