### ISSUE TITLE
New hook to customize @pytest.mark.parametrize test ids

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#930]
Currently `@pytest.mark.parametrize` can customize the generated ids for its parameters by passing a list of strings or a function.

It would be nice for plugins to be able to customize those ids for some specific types (#923), or even supplied by the user on a `conftest` file to generate readable parameter ids even for project-specific objects.

I propose to add a new hook along the lines of:

```python
def pytest_make_parametrize_id(config, val):
    """Return a user-friendly string representation of the given ``val`` that will be used 
    by @pytest.mark.parametrize calls. Return None if the hook doesn't know about ``val``.
    """
```

**Comment by RonnyPfannschmidt** [comment]
closing since #1535 is merged
