### ISSUE TITLE
Running the case where nodeid contains :: from command line will cause an error

### ISSUE THREAD

**Issue by Simon-Chenzw** [pytest-dev/pytest#9302]
### description

when the nodeid of a parametrized test case contained `::` , running the test case through the command line will cause error

pytest: latest version (6.2.5) 

```python
# run: pytest test_foo.py::test_bar[::]
import pytest
@pytest.mark.parametrize("a", [":", "::"])
def test_bar(a):
    assert 1 == 1
```

### bug location

wrong line: [src/_pytest/main.py#L878](https://github.com/pytest-dev/pytest/blob/17b38259fde89caaf44a4e578d9f62d001a894c9/src/_pytest/main.py#L878) `strpath, *parts = str(arg).split("::")`

nodeid will be like this: `test_foo.py::test_bar[*****]` , any string will in the square brackets. 
So it probably shouldn't simply be split with `::` , or `::` shouldn't appear in brackets.

### my solution

Not tested, just for suggestion
```
strpath, *parts = str(arg).split("::", 1)
if parts:
    if "[" in parts[0]:
        pre, suf = parts[0].split("[", 1)
        parts = list(pre.split("::"))
        parts[-1] += "[" + suf
    else:
        parts = list(parts[0].split("::"))
print(strpath, parts)
```

**Comment by bluetech** [comment]
We likely need a less ad-hoc solution for this, which would involve mapping all of the places which need to "parse" (psuedo-)nodeids, as `resolve_collection_argument` does. We probably have existing issues for that...

In the meantime, a workaround would be to avoid `::` in the nodeid by assigning some other IDs to the params:

```py
import pytest
@pytest.mark.parametrize("a", [pytest.param(":", id="colon"), pytest.param("::", id="double-colon")])
def test_bar(a):
    assert 1 == 1
```
