### ISSUE TITLE
Add keyword-only parameter to `@pytest.mark.parametrize` to unify `argvalues` and `ids`

### ISSUE THREAD

**Issue by mattkram** [pytest-dev/pytest#9314]
#### What's the problem this feature will solve?

The `ids` parameter for `@pytest.mark.parametrize` is a fantastic way to make the test output a bit more readable for parametrized tests. However, this iterable must be kept in sync with the `argvalues` iterable, which requires care to ensure the association between an `id` and its associated `argvalue` is correct. Additionally, it can be challenging to comment out specific parametrizations during development.

#### Describe the solution you'd like

I would like to propose the ability to pass in a keyword-only argument (`id_map` below, alternately `as_dict` or other suggestions welcome) to unify these two arguments and allow the user to pass in a mapping of `id` to `argvalue` for the different test parametrizations. Under the hood, this is just a simple manipulation using `dict.items()` to unpack the `ids` and `argvalues` iterables from the dictionary.

Here is the example of usage:
```python
import pytest

@pytest.mark.parametrize(
    ["value", "power", "expected"],
    id_map={
        "squared": (2, 2, 4), 
        "cubed": (2, 3, 8), 
        "to_the_fourth": (3, 4, 81)
    },
)
def test_pow(value, power, expected):
    assert value ** power == expected

```

The example above is implemented successfully with an import-time monkey-patch. I would like to help develop and merge this into the main branch if others find it interesting. Preliminary internal company feedback has been positive and I was encouraged to submit as a proposed upstream contribution.

Here is the monkey-patch:

```python

def _monkey_patch_parametrize():
    """Monkeypatch parametrize to add `id_map` argument."""
    _orig_parametrize = pytest.mark.parametrize

    def _new_parametrize(*args, id_map=None, **kwargs):
        def wrapped(f):
            if id_map is not None:
                kwargs["ids"] = id_map.keys()
                kwargs["argvalues"] = id_map.values()
            return _orig_parametrize(*args, **kwargs)(f)

        return wrapped

    setattr(pytest.mark, "parametrize", _new_parametrize)


_monkey_patch_parametrize()
```

#### Alternative Solutions

I haven't been able to find anything similar on PyPI, and I think this is useful enough to be in core `pytest`.

**Comment by kalekundert** [comment]
I agree that `parametrize()` doesn't have the most user-friendly API, but I think that this specific issue is already handled by `pytest.param()`:

```
import pytest

@pytest.mark.parametrize(
    ['value', 'power', 'expected'], [
        pytest.param(2, 2, 4, id='squared'),
        pytest.param(2, 3, 8, id='cubed'),
        pytest.param(3, 4, 81, id='to_the_fourth'),
    ],
)
def test_pow(value, power, expected):
    assert value ** power == expected
```

**Comment by mattkram** [comment]
> I agree that `parametrize()` doesn't have the most user-friendly API, but I think that this specific issue is already handled by `pytest.param()`:
> 
> ```
> import pytest
> 
> @pytest.mark.parametrize(
>     ['value', 'power', 'expected'], [
>         pytest.param(2, 2, 4, id='squared'),
>         pytest.param(2, 3, 8, id='cubed'),
>         pytest.param(3, 4, 81, id='to_the_fourth'),
>     ],
> )
> def test_pow(value, power, expected):
>     assert value ** power == expected
> ```

Wow, thanks @kalekundert! I agree that is a nice way to meet the same objective. Would the maintainers be amenable to me contributing a few small documentation additions to cover this case more explicitly in the [API docs](https://docs.pytest.org/en/6.2.x/reference.html?highlight=pytest%20param#pytest-param) and [User Guide](https://docs.pytest.org/en/6.2.x/parametrize.html)?

**Comment by kalekundert** [comment]
Glad I could help!  I'm not one of the core maintainers, but I'm pretty sure that documentation improvements are always welcome.  I'm going to close this issue, but feel free to reopen it if you want to keep discussing this.
