### ISSUE TITLE
Remove gateway lines from xdist failure output

### ISSUE THREAD

**Issue by GergelyKalmar** [pytest-dev/pytest#9316]
#### What's the problem this feature will solve?
Currently the failure section of the output of a pytest run with xdist enabled looks similar to this:
```
=== FAILURES ===
___ [pylint] file1.py ___
[gw1] linux -- Python 3.8.10 .../bin/python3.8
W: 31, 1: TODO: ... (fixme)
W: 32, 1: TODO: ... (fixme)
___ [pylint] file2.py ___
[gw4] linux -- Python 3.8.10...bin/python3.8
W: 47, 1: TODO: ... (fixme)
...
=== 3 failed, 69 passed, 131 skipped in 27.71s ===
```

Note that the lines starting with `[gwX]` do not provide any additional (useful) information in this case (the platform and Python version information is shown at the beginning of the session already).

#### Describe the solution you'd like
It would be great if these lines could be shown only when there is a benefit in doing so. Alternatively, making it possible to hide this via configuration or some pytest hook would be also acceptable (e.g. to make it possible to override it with a plugin).

#### Alternative Solutions
This behavior seems to be hardcoded at https://github.com/pytest-dev/pytest/blob/9d17cebe64878f695fbd7596fcfb643f53a56830/src/_pytest/terminal.py#L570 at the moment.

#### Additional context
The issue was originally raised in the pytest-xdist plugin (https://github.com/pytest-dev/pytest-xdist/issues/718), however, it seems that the issue is specific to pytest itself.

**Comment by nicoddemus** [comment]
Hi @GergelyKalmar,

Thanks for writing! 

> Note that the lines starting with [gwX] do not provide any additional (useful) information in this case (the platform and Python version information is shown at the beginning of the session already).

Actually the `[gwX]` itself is useful, as often knowing which worker run a test can be useful. But I agree the platform and Python version are superfluous.

Can you elaborate why that line is such a problem however?

**Comment by GergelyKalmar** [comment]
Well it is not a gigantic problem for sure, but if I have a few small errors but in many files, this can add quite a lot of lines to the overall failure output. These lines make the output less compact, so I see fewer errors on the screen than I could and I need to scroll more too. It is a bit of an inconvenience.

I see what you mean with the worker numbers, however, I don't remember any occasion where I actually needed that information, so I would definitely prefer the default output to be the same as when running pytest without xdist with the possibility to add this information when really needed (perhaps displaying it in verbose mode or when the environments are not the same would be the best).

**Comment by nicoddemus** [comment]
Hmm I see, thanks.

I'm not sure we should change the defaults, as I'm sure people rely on it. I'm also -1 on adding a new configuration value just for that, as while it might seem at first just a new option, it bears documentation, maintenance, etc, which adds to the long term maintenance.

Let's see what others have to say however.

**Comment by GergelyKalmar** [comment]
I would agree. Of course, because it is Python, I can always just patch the terminal writer or do some other wild patching, however, it would perhaps be nicer to have a more direct way of controlling this. I'm not very familiar with this part, but if there's a way to make patching/controlling this easier, that would also help (and wouldn't need changes to defaults or perhaps the introduction of a new configuration value).

**Comment by GergelyKalmar** [comment]
It turns out that the lines in question are actually coming from https://github.com/pytest-dev/pytest/blob/main/src/_pytest/reports.py#L44, so it is pretty easy to remove these lines like this:

```python
def pytest_configure(config):
    config.pluginmanager.get_plugin('reports').getworkerinfoline = lambda *_args, **_kwargs: ''
```

Now the only challenge is that we still get an unnecessary newline from https://github.com/pytest-dev/pytest/blob/main/src/_pytest/reports.py#L79, however, I think this could be easily solved by moving the newline to the `getworkerinfoline` function and using `out.write` instead of `out.line` in `toterminal`. This way we would have the possibility to control the entire info line in a very elegant manner. Any thoughts on this?

**Comment by GergelyKalmar** [comment]
@nicoddemus It turns out there is a simple solution which makes it possible to hide these lines from the failure output. The only change we are making is that we are only displaying workerinfo when it is not empty, which is arguably a useful patch in any case (in PR https://github.com/pytest-dev/pytest/pull/9357). This is mostly a backwards-compatible change, the only case anyone would be impacted is if they explicitly set the getworkerinfoline to empty (as in the example above), in which case the output will become simply more consistent with the non-xdist version.

If someone could review, merge and eventually release this little patch, that would be greatly appreciated!
