### ISSUE TITLE
Ability to rename how conftest.py are called

### ISSUE THREAD

**Issue by Steinthor** [pytest-dev/pytest#9325]
I've been making some tests with pytest, and would love two things:

1) not needing a conftest.py, i.e. be able to define everything in a single .py file.  Example of things needing a conftest.py: additional input arguments

2) if you need a configuration file, be able to name it whatever you want.

**Comment by nicoddemus** [comment]
Hi @Steinthor,

Thanks for writing.

Particularly I'm -1 on being able to customize how `conftest.py` are named: forcing them to have that name brings consistency across test suites, so when coming to a new project it is valuable to look at a `conftest.py` file and immediately know what it means. Being able to customize the name makes that no longer true necessarily, as a project might decide to call it `testsuiteconfig.py` for example.

That's my opinion, but let's see if others think differently.

**Comment by The-Compiler** [comment]
Taking the freedom to close this, as we seem to have a consensus that this doesn't seem like a good idea. Thanks for the suggestion though, @Steinthor!
