### ISSUE TITLE
Incorrect calculation of passed tests

### ISSUE THREAD

**Issue by Cabpacob** [pytest-dev/pytest#9331]
Tests are calculated incorrectly when the decorator passes an argument to the test. 

`test.py` contains:
```python
def decorator(argument):
    def wrapper(function):
        return function(argument=argument)
    return wrapper


@decorator(argument=10)
def test_function(argument):
    pass
```

`pytest test.py` ouput:
```
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: {path}, inifile:
plugins: xonsh-0.6.0
collected 0 items                                                              

========================= no tests ran in 0.00 seconds =========================
```

Actually, the test has been run, but was not counted in the total amount.

I'm on a 64-bit Ubuntu 18.04.6 LTS

**Comment by RonnyPfannschmidt** [comment]
User error

At first glance there are 2 issues

1. You don't have a decorator, you have a invoker
2. No functools.wraps usage

So you replace the function with its return value and pytest rightly finds no test, as in place of the test function there is a return value, likely none
