### ISSUE TITLE
Where would I start to work with the trepanning debugger? 

### ISSUE THREAD

**Issue by rocky** [pytest-dev/pytest#936]
I'd like to be able to use [trepan](https://pypi.python.org/pypi/trepan/0.5.0) with pytest. 

I looked at https://github.com/pytest-dev/pytest/blob/master/_pytest/pdb.py but I am lost here.

**Comment by RonnyPfannschmidt** [comment]
the important bits are probably in the set_trace method of the pytestPDB classt,

bascially if you want to interact with the stdio, you need to disable the captureing for the current test first

**Comment by nicoddemus** [comment]
@rocky feel free to ask more questions here, but could you close this when you're done? Thanks! :smile:

**Comment by rocky** [comment]
I will ask more questions later, basically along the lines of getting more
information, such as what that class does and what which methods are
required.

I looked at trying to add feature or wishlist label, and but dind't see
that I could do that.

**Comment by nicoddemus** [comment]
Yeah, for some reason issue reporters can't assign labels apparently. :frowning:

**Comment by rocky** [comment]
@nicoddemus Thanks for the help. I have now an internal plugin version that supports trepan via option `--trepan`. See https://github.com/rocky/pytest/commit/a076dee8661e79a9b694ef5fcf09b81fd14b00f4 

I guess the only thing remaining is to turn this into an external plugin. I'll look at the other external plugins for guidance, but if there's any additional help or tips anyone can offer that would be appreciated. 

In the commit cited above, I have added docstrings to some of the functions which I find helpful. If others find them helpful, they could be added into `_pytest/pdb.py`, making the trivial substitution of "trepan" to "pdb" . 

Finally, I'll put in a slight plug for trepan in the context of doing this work. I think the setup needed to call trepan is not as ugly as it is for pdb. To be fair, some of the less ugliness is because some of the complexity has been shifted from the setup code into the debugger where I think it more appropriately belongs.  But that's okay, because a project like trepan can more easily and quickly improve the api and put out a release. (I will be putting out a release soon to support pytest as soon as I get the external plugin thing worked out.)

Some specifics. In trepan you don't call *set_trace()*, but rather *debug()*.  To support pytest, or pytest-like setups, I have just added a *level* parameter to that which allows the caller of *debug()* to ignore newest or top-level setup frames.

**Comment by nicoddemus** [comment]
That looks nice! I didn't know about trepan, will certainly take a closer look! :smile: 

To make that into an external plugin, please take a look at [this section] in the docs, it's pretty simple! Feel free to ask any questions here.

Cheers
:beers:

**Comment by rocky** [comment]
> To make that into an external plugin, please take a look at [this section] in the docs,
@nicoddemus  [this section] link typo

**Comment by nicoddemus** [comment]
Ops! :sweat_smile: Fixed, thanks!

**Comment by rocky** [comment]
> it's pretty simple!

Yes, it was simple. https://github.com/rocky/pytest-trepan 

Gotta run now but I will clean it up test it and add tests later. And when I'm done I'll close this. 

Thanks again for the pointer and help.

**Comment by rocky** [comment]
I think I can take things from here. At some point, I'd probably like move https://github.com/rocky/pytest-trepan into the pytest-dev space.

**Comment by nicoddemus** [comment]
Nice! :sunglasses:
