### ISSUE TITLE
Norton Quarentines pytest.exe

### ISSUE THREAD

**Issue by Linn111** [pytest-dev/pytest#9364]
PIP install of pytest is quarantined by Norton 360.  This is probably a false positive, but I would like to know for sure.  Norton should also be notified.  Details below:  pyflake8.exe has the same issue in case there is a connection.

Norton Version:
22.21.10.40
Serial Number:
7HJM4FT6MBMC
End Point ID:
{FA2AAAC0-D5E9-40EF-80DF-3BA6D0A2D48D}
Current SKU:
21403754
Media SKU:
21376863

Edition	Windows 10 Pro
Version	21H2
Installed on	‎11/‎11/‎2021
OS build	19044.1387
Experience	Windows Feature Experience Pack 120.2212.3920.0

------------------------------------------------------
------------------------------------------------------

Filename: py.test.exe
Threat name: SONAR.PSDownloader!g1Full Path: Not Available
____________________________
____________________________

On computers as of 
12/2/2021 at 5:34:48 AM

Last Used 
12/2/2021 at 5:34:48 AM

Startup Item 
No

Launched 
Yes

SONAR Protection monitors for suspicious program activity on your computer.

===============================
===============================

Filename: pytest.exe
Threat name: SONAR.PSDownloader!g1Full Path: Not Available
____________________________
____________________________

On computers as of 
12/2/2021 at 5:34:48 AM

Last Used 
12/2/2021 at 5:34:48 AM

Startup Item 
No

Launched 
Yes

SONAR Protection monitors for suspicious program activity on your computer.
____________________________

pytest.exe Threat name: SONAR.PSDownloader!g1
Locate

Very Few Users
Fewer than 5 users in the Norton Community have used this file.

Very New
This file was released less than 1 week  ago.

High
This file risk is high.
____________________________

Source: External Media

Source File:
python.exe

File Created:
pytest.exe
____________________________

File Actions

File: c:\Users\John\AppData\Roaming\Python\Python39\Scripts\ pytest.exe Threat Removed
____________________________

System Settings Actions

Event: Process start (Performed by c:\users\john\appdata\roaming\python\python39\scripts\pytest.exe, PID:19508) No action taken
Event: Process start: c:\users\john\appdata\roaming\python\python39\scripts\ pytest.exe, PID:19508 (Performed by c:\users\john\appdata\roaming\python\python39\scripts\pytest.exe, PID:19508) No action taken
____________________________

File Thumbprint - SHA:
Not available
File Thumbprint - MD5:
Not available

------------------------------------------------------
------------------------------------------------------

Filename: py.test.exe
Threat name: SONAR.PSDownloader!g1Full Path: Not Available
____________________________
____________________________

On computers as of 
12/2/2021 at 5:34:48 AM

Last Used 
12/2/2021 at 5:34:48 AM

Startup Item 
No

Launched 
Yes

SONAR Protection monitors for suspicious program activity on your computer.
____________________________

py.test.exe Threat name: SONAR.PSDownloader!g1
Locate

Very Few Users
Fewer than 5 users in the Norton Community have used this file.

Very New
This file was released less than 1 week  ago.

High
This file risk is high.
____________________________

Source: External Media

Source File:
python.exe

File Created:
py.test.exe

____________________________

File Actions

File: c:\Users\John\AppData\Roaming\Python\Python39\Scripts\ py.test.exe Threat Removed
____________________________

System Settings Actions

Event: Process start (Performed by c:\users\john\appdata\roaming\python\python39\scripts\py.test.exe, PID:8672) No action taken
Event: Process start: c:\users\john\appdata\roaming\python\python39\scripts\ py.test.exe, PID:8672 (Performed by c:\users\john\appdata\roaming\python\python39\scripts\py.test.exe, PID:8672) No action taken
____________________________

File Thumbprint - SHA:
Not available
File Thumbprint - MD5:
Not available

____________________________
____________________________

**Comment by RonnyPfannschmidt** [comment]
This is a false positive of the virus scanner, pytest is not involved with the exe, it comes from the installer aka pip

**Comment by Linn111** [comment]
Ronny,

 

As I expected.  Thanks for confirming.

 

  _____
