### ISSUE TITLE
Specify Py.test base directory per test?

### ISSUE THREAD

**Issue by alanhdu** [pytest-dev/pytest#940]
We have a bunch of modules with a public-facing API, and some internal code that's only run to update some data and ML models. Each module has a `tests` directory for the internal code, and the entire repo has a `tests` directory for the API. In other words, we have a couple of basically independent tests that need to be run with different base directories.

More concretely, the repository structure looks like:
```
├── module
│   ├── __init__.py                -- Note: does not import module/src/stuff.py
│   ├── src
│   │   └── stuff.py               -- Update some ML models
│   └── tests
│       └── test_unit.py           -- test module/src/stuff.py
└── tests
    ├── test_integration.py    
    └── test_unit.py               -- test module/__init__.py
```

We'd like `py.test` to run `tests/test_*` in the root directory, and `module/src/tests` from the `module` directory. In other words, we'd like to be able to do `from src import stuff` in the `module/tests/test_unit.py` directory, but `import module` from the `tests/` directory.

We've thought of a couple of ways to do this:
1. Hack the Python path via `sys.path` in `module/src/tests/*`  (seems kind of janky, and won't worker if we want to use use local data files)
2. Edit our CI script to make multiple calls to `py.test`   (not the end of the world, but it'd be nice not to)
3. Rewrite `module/src/tests/*` to run from the root directory (annoying for developers)

Is there a recommended way of doing this?

**Comment by alanhdu** [comment]
PS. Sorry if any of this is unclear. It's a little complicated to explain, and I'd be happy to post any clarifications.

cc @arielist

**Comment by RonnyPfannschmidt** [comment]
for in module test folders, it is suggested to use a __init__.py in the tests folder

the src folder and its context is indeed confusing, more details might be necessary to understand

you could have something that setup up a extra pythonpath element, however the mental picture i have of your setup is still rather fuzzy and incomplete

it might be sensible to use something like a develop install

how is the module used in production?

**Comment by alanhdu** [comment]
By init.py, do you mean an `__init__.py`? I thought I read somewhere that it was discouraged to put `__init__.py` in the tests folder.

Sorry about the confusion. Essentially, we use the src folder to fit some ML models. Currently, we're dumping out the appropriate constants and copy-and-pasting them where we need them. So the src directory's never actually called in production: we use it for development and when deploying new models.

We're not using a setup.py or anything right now. In production, we just use `from module import whatever`, from the top-level directory.

**Comment by RonnyPfannschmidt** [comment]
The suggested setup is tests detached from source without a init file, so tests can be fun against installed/different versions of a lib

Since you neither install, nor separate, having those are not files makes various details more reliable for your setup

Since your setup is kinda unique, you will have to figure a own way to deal with the rest of the import paths

My understanding is that you only need it for tests, so hooking it into a contest might be helpful

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of feedback
