### ISSUE TITLE
FR: Revert pytest.warns(None) changes

### ISSUE THREAD

**Issue by bashtage** [pytest-dev/pytest#9402]
#### What's the problem this feature will solve?

I need to dynamically catch warnings where whether the warning is issued or not depends on information that is only available at runtime.

#### Describe the solution you'd like

Accept `pytest.warns(None)` as equivalent to `pytest.warns()` without error

```python

warn_typ = FutureWarning if dt_s_tup[0] == "nc" else None

model = VAR(endog, exog)
with pytest.warns(warn_typ):
    results_per_deterministic_terms[dt_s_tup] = model.fit(
        maxlags=4, trend=dt_s_tup[0], method="ols"
    )
```

from 

https://github.com/statsmodels/statsmodels/blob/948bfc4520791b2d867829259367f446bd107218/statsmodels/tsa/vector_ar/tests/test_var_jmulti.py#L133-L139

#### Alternative Solutions

I don't see any workaround.  As far as I know there is not easy way to work around this. Is the solution to use an empty *args expansion?  

This removal seems to have missed the relative challenge of calling a function with 1 argument vs 0 arguments.

**Comment by bashtage** [comment]
xref #8645

**Comment by The-Compiler** [comment]
See #9386. I don't see a reason to revert them.

**Comment by Zac-HD** [comment]
> Accept `pytest.warns(None)` as equivalent to `pytest.warns()` without error

Unfortunately this is off the table, because it would be a backwards-incompatible change compared to both the current and pre-deprecation behaviour (when passing `None` effectively disabled the check entirely).

> I need to dynamically catch warnings where whether the warning is issued or not depends on information that is only available at runtime.
> ```python
> warn_typ = FutureWarning if dt_s_tup[0] == "nc" else None
> 
> model = VAR(endog, exog)
> with pytest.warns(warn_typ):
>     ...
> ```

This is *precisely the point of the deprecation*: your test is not currently checking that no warning is emitted in the `None` case!  Try out 

```python
import contextlib, pytest, warnings

with pytest.warns(None):  # allows any warning!
    warnings.warn("", FutureWarning)

# The following will already work if you run tests with -Werror (a generally good idea);
# or if you have -Wignore it's equivalent!

warn_typ = FutureWarning  # or None
with pytest.warns(warn_typ) if warn_typ else contextlib.nullcontext():
    warnings.warn("", FutureWarning)
```

**Comment by bashtage** [comment]
@Zac-HD We can't run with -Werror because of past sins and far too many warnings int he test suite, so that isn't viable.  It would be a big improvement if there was an API way to pass a value that would indicate whether there is no error expected rather than no value for this case and a value in other cases.  It ultimately makes for hard to write code.  Similarly with the idea of `pytest.does_not_raise()` which can't be used at runtime in a sane way when code might process a warning under some circumstance but not others in parameterized tests.

**Comment by nicoddemus** [comment]
Please see https://github.com/pytest-dev/pytest/issues/9404.
