### ISSUE TITLE
Add way to ignore warnings emitted during doctest collection

### ISSUE THREAD

**Issue by jwodder** [pytest-dev/pytest#9403]
Our scenario: We are in the process of migrating a large code base to pytest, and some of the source files have doctests.  At the same time, a number of source files have been moved to new import paths, and the old import paths now contain stub files that import from the new path and emit a deprecation warning.  We want to make sure that normal use of our code base does not trigger any of its deprecation warnings, so we also have `filterwarnings = error::DeprecationWarning:^PACKAGE_NAME` set.  The combination of these factors means that pytest, while scanning the whole package for doctests, ends up importing various deprecated paths, which trigger warnings that are turned into errors, which make the test collection fail.  For now, we've eliminated the `filterwarnings` setting, but it would be desirable if there were some way to make pytest discard any warnings encountered during doctest collection yet also not ignore them should they then be emitted during regular testing.  Is such a thing possible?  Is there a better way to get what we want that doesn't involve passing every deprecated file to an `--ignore` option?

**Comment by nicoddemus** [comment]
> Is there a better way to get what we want that doesn't involve passing every deprecated file to an --ignore option?

I can't think of any other option other than hacking something together, like monkey patching the `warnings` plugin so it doesn't collect warnings during collection, something like:

```python
# conftest.py
from contextlib import contextmanager

import pytest
import unittest.mock

@contextmanager
def do_nothing(*args, **kwargs):
    yield

@pytest.hookimpl(hookwrapper=True, tryfirst=True)
def pytest_collection():
    with unittest.mock.patch("_pytest.warnings.catch_warnings_for_item", new=do_nothing):
        yield
```

This doesn't capture warnings for all modules (not only doctests), but might be an acceptable stop gap measure while the deprecated paths are around.

**Comment by jwodder** [comment]
I managed to get things to work to our liking by using `pytest_ignore_collect()` to skip any non-test source files that don't contain doctests like so:

```python
def pytest_ignore_collect(path):
    if path.basename.startswith("test_") or path.check(dir=1):
        return False
    if path.ext != ".py":
        return True
    return not any(re.match(r"^\s*>>>", ln) for ln in path.readlines())
```

Feel free to close this issue if you don't believe pytest will ever implement anything for it.

**Comment by nicoddemus** [comment]
Ahh good idea, you can programatically control what is ignored. 😁 

Closing this then, thanks for sharing. 👍
