### ISSUE TITLE
Unable to specify debugger to use

### ISSUE THREAD

**Issue by txomon** [pytest-dev/pytest#941]
Hi, I have realized that currently is not possible to run another debugger but pdb. I have created a patch just in case you want to run ipdb instead of pdb. It is a super ugly patch, but works alright.

I would love to have a feature like this officially supported however.

```
diff --git a/_pytest/pdb.py b/_pytest/pdb.py
index 78fedd3..5bd9a30 100644
--- a/_pytest/pdb.py
+++ b/_pytest/pdb.py
@@ -1,6 +1,10 @@
 """ interactive debugging with PDB, the Python Debugger. """
 from __future__ import absolute_import
-import pdb
+import ipdb
+from IPython.core.debugger import Pdb
+class pdb(object):
+    set_trace = ipdb.set_trace
+    Pdb = Pdb
 import sys
 
 import pytest
```

**Comment by pfctdayelise** [comment]
@txomon, this is a bit drastic to be merging to pytest core. :) Have you tried the pytest-ipdb plugin?

https://pypi.python.org/pypi/pytest-ipdb

The author mentioned here https://github.com/mverteuil/pytest-ipdb that they are no longer supporting it. We should probably try and get it moved to the pytest-dev team, but it would be good to know first if it works well or not.

**Comment by txomon** [comment]
Yeah, hahaha not meant to be merged, just to show it. I will test the
plugin when I come back.

**Comment by RonnyPfannschmidt** [comment]
closing due to lack of feedback
