### ISSUE TITLE
[prerelease] `ExceptionInfo.traceback[...].path` changed from py.path to pathlib.Path

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#9423]
As for the `ExceptionInfo.traceback[...].path` one: The PR looks good, but it seems to me that we should retain and perhaps deprecate the `path` attribute properly, instead of (more or less silently) replacing it, despite it being public API)?

_Originally posted by @The-Compiler in https://github.com/pytest-dev/pytest/discussions/9415#discussioncomment-1835181_

**Comment by nicoddemus** [comment]
Can we assess the impact of `path` changing from `py.path.local` to `pathlib.Path`? If it doesn't break the world, just adding a good note about it in the changelog might be sufficient. I suspect this is rarely used, with a trivial fix, so it might save us time and effort if we can avoiding a deprecation cycle.

**Comment by The-Compiler** [comment]
At least [a quick search](https://sourcegraph.com/search?q=context:global+%5C.traceback%5C%5B.*%5C%5D.path&patternType=regexp) seems to suggest that this is only an issue for `promise` indeed - so perhaps we should go ahead and just add that to the changelog and deprecation docs instead then?

**Comment by bluetech** [comment]
We've decided to accept this breaking change. Will send a PR to update the changelog.
