### ISSUE TITLE
Should `pytest-asyncio` be merged into this repo?

### ISSUE THREAD

**Issue by wjsi** [pytest-dev/pytest#9429]
#### What's the problem this feature will solve?
As [pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio) stops accepting PRs since June, 2021, the repo is keeping updating versions, while bug fixes (like https://github.com/pytest-dev/pytest-asyncio/pull/220 and https://github.com/pytest-dev/pytest-asyncio/pull/221) are not accepted.

#### Describe the solution you'd like
As asyncio tests are essential for a large number of projects, and `pytest-asyncio` itself is not a huge project, it is better to merge it into the main `pytest` repo, thus more maintainers can be attracted and bugs can be fixed as soon as possible.

**Comment by The-Compiler** [comment]
Personally I'd rather find a way to solve that issue without merging the plugin into the core. It's already part of pytest-dev, so all maintainers having access to this repository should also have access to the other one. I don't know how many of the pytest core maintainers are familiar with asyncio, but FWIW I am not.

**Comment by RonnyPfannschmidt** [comment]
as  far as im concerned, merging a plugin that clearly needs maintainer work to core will just make it more of a liability  to core

first the maintenance issue needs to be solved

for that a friendly maintainer reach out has to be done

**Comment by RonnyPfannschmidt** [comment]
i created https://github.com/pytest-dev/pytest-asyncio/issues/232 to unravel the bus factor of the plugin
