### ISSUE TITLE
[prerelease] pytest.TmpdirFactory is not importable anymore

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#9432]
Discovered in https://github.com/ClearcodeHQ/pytest-postgresql/issues/533#issuecomment-999567968 via #9415:

Doing e.g. `python3 -c "import pytest; pytest.TempdirFactory"` fails since  5e883f51959f900fcf985493ce2d09e07bad7e00. This is a bit similar to #9396, but #9400 won't help with this one.

Test modules often use `pytest.TempdirFactory` for type annotations - in fact, that's why [that was added](https://docs.pytest.org/en/stable/changelog.html#improvements) in 6.2.0.

However, it being set from a plugin means that:

a) Test modules aren't even importable anymore outside of pytest - in case of `pytest-postgresql`, this [breaks an importability check](https://github.com/ClearcodeHQ/pytest-postgresql/runs/4607221002?check_suite_focus=true), but I can imagine various other things breaking...
b) Perhaps more importantly, static analysis in IDEs or tools like mypy [aren't aware anymore](https://github.com/ClearcodeHQ/pytest-postgresql/runs/4607221090?check_suite_focus=true) that the attribute exists - however, after all, that's *the whole point* of it existing, and [lots of projects use it that way](https://sourcegraph.com/search?q=context:global+:%5C+*%28pytest%5C.%29%3FTempdirFactory+lang:python+-file:pytester.py&patternType=regexp). (Some import it from `_pytest.tmpdir`, probably because they did that before 6.2.0 - I'm not too worried about those, they knew what they're in for)

Reproducer:

```python
from pytest import TempdirFactory

def test_nothing(tmpdir: TempdirFactory):
    pass
```

Fails with mypy:

```
test_x.py:1: error: Module "pytest" has no attribute "TempdirFactory"; maybe "TempPathFactory"?
Found 1 error in 1 file (checked 1 source file)
```

What to do? I suppose as a stop-gap until we want to distribute the plugin independently from pytest, we could import the class from the plugin or so?

**Comment by RonnyPfannschmidt** [comment]
Let's provide the attribute, for python 3.7+ we can provide a deprecation using the module getattr special method

**Comment by The-Compiler** [comment]
I don't see how we could reasonably deprecate the type annotation without deprecating the `tmpdir_factory` fixture as a whole.

**Comment by bluetech** [comment]
Whoops didn't think of this. The stuff isn't deprecated yet, so for now we should just restore it somehow, i.e. instead of the plugin monkeypatching `pytest`, jus import it in `pytest` from `_pytest.legacypath`. When the time comes to deprecate the entire thing, we'll think how best to do it (hopefully by then we will have dropped python3.6 so module getattr is fully available).

**Comment by bluetech** [comment]
(Personal note: in the end I didn't have time for pytest this week, but I do of course intend to work on all of the regressions I caused when I get the chance)

**Comment by The-Compiler** [comment]
> Whoops didn't think of this. The stuff isn't deprecated yet, so for now we should just restore it somehow, i.e. instead of the plugin monkeypatching `pytest`, jus import it in `pytest` from `_pytest.legacypath`.

Sounds good to me!

> When the time comes to deprecate the entire thing, we'll think how best to do it (hopefully by then we will have dropped python3.6 so module getattr is fully available).

Note that this probably wouldn't help mypy and friends, which are the main consumers of the type annotation.

> (Personal note: in the end I didn't have time for pytest this week, but I do of course intend to work on all of the regressions I caused when I get the chance)

Don't worry about it - we still have quite some "unknown unknowns" in #9415 and topics other people are looking into (like #9404). As said before, I'd rather have a solid 7.0.0 release a bit later than a half-baked one which will cause us trouble down the road.

Also, please don't feel bad for it - you worked on a lot of very tricky topics for this release (which is very appreciated!), so it's somewhat natural that regressions happen to bisect to one of your commits - let us know if we can help somewhere, and thanks for handling the fallout!

**Comment by nicoddemus** [comment]
> Also, please don't feel bad for it - you worked on a lot of very tricky topics for this release (which is very appreciated!), so it's somewhat natural that regressions happen to bisect to one of your commits - let us know if we can help somewhere, and thanks for handling the fallout!

I second that! 👍
