### ISSUE TITLE
pytest_markeval_namespace isn't documented in the hooks page (only in change log)

### ISSUE THREAD

**Issue by fruch** [pytest-dev/pytest#9434]
`pytest_markeval_namespace` isn't documented in the hooks page (only in change log)

**Comment by The-Compiler** [comment]
Judging from a quick grep:

```
grep -o 'def pytest_[^(]*' src/_pytest/hookspec.py | cut -d" " -f2 | sort | uniq > hooks-spec
grep -o ':: pytest_.*' doc/en/reference/reference.rst | cut -d" " -f2 | sort | uniq > hooks-spec
```

and looking at the diff, it looks like some more are missing:

- `pytest_leave_pdb`
- `pytest_report_from_serializable`
- `pytest_report_to_serializable`

**Comment by fruch** [comment]
BTW, I found that in the unittests trying to figure out how to do something a bit more complex with the boolean strings
since we can't do `pytest.config` directly anymore...
