### ISSUE TITLE
Merging pytest-capturelog into core

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#946]
We talked a bit about this at EuroPython, but I think it's good to have a ticket to track this.

What about merging [pytest-capturelog](https://pypi.python.org/pypi/pytest-capturelog) into the core?

* It's a widely used functionality/plugin
* The author seems non-responsive and the project dead (see [issues](https://bitbucket.org/memedough/pytest-capturelog/issues?status=new&status=open))
* @bubenkoff created [an issue](https://bitbucket.org/memedough/pytest-capturelog/issues/3/move-under-pytest-dev-team) proposing to move it to pytest-dev in March, with no response
* There's a fork, [pytest-catchlog](https://pypi.python.org/pypi/pytest-catchlog), where the author is more responsive ([sometimes...](https://github.com/eisensheng/pytest-catchlog/issues/3)), but I don't think it's widely known/used.
* Having two options (`-catchlog` vs. `-capturelog`) with no clear list of differences is confusing for someone new to pytest.

Doing another pytest-somethinglog plugin under pytest-dev would just increase confusion even more - and since it's definitely a feature which is widely used, I'd propose just merging it into pytest (after bringing the code up to current standards, like using fixtures instead of funcargs and hookwrapper instead of `__multicall__`) and blacklisting `-catchlog` and `-capturelog`.

Alternative possibilities:

- I'll just contribute to `pytest-catchlog` and use that, and other people probably will continue to use `capturelog`
- We move `pytest-capturelog` under `pytest-dev` if @eisensheng agrees, so it's at least the more "official"/endorsed one.

What do you think?

**Comment by eisensheng** [comment]
> What do you think?

Absolutely fine with me. Like I stated at several occasions I forked the original repository only because the original author seems to have disappeared and I required some bug fixes and had some feature requests to assert certain log statements.

**Comment by RonnyPfannschmidt** [comment]
i'd like to discuss the general captureing mechanisms before the capturelog merge - i have some ideas i need to discuss with holger

**Comment by auvipy** [comment]
+1 make it offfishal

**Comment by nicoddemus** [comment]
There was a [thread](https://mail.python.org/pipermail/pytest-dev/2015-September/003166.html) discussing this in the mailing list, and it was decided to leave `pytest-catchlog` as a third-party plugin.
