### ISSUE TITLE
When multithreading executes pytest.main(), the browser is not closed starting from the second thread 

### ISSUE THREAD

**Issue by sijunji** [pytest-dev/pytest#9462]
I used Falsk + Multithreaded pool + PyTest + Selenium to set up a PyTest execution server. However, I encountered a problem that pyTest will only close the browser for the first request and will not close the browser for the rest of the requests. But it doesn't matter if there's only one request. Please help me and guide me how to solve this problem. thank you
This is my flask app file
![image](https://user-images.githubusercontent.com/37135199/147758155-38aefe46-56f1-4ab8-ad6f-a14bfd7bbf02.png)

This is the conftest.py file，and this method is executed before the pytest.mian() run ends, which closes the browser

![image](https://user-images.githubusercontent.com/37135199/147758192-1078e04c-bcfa-4ffd-b75f-bdb470ea558f.png)

**Comment by sijunji** [comment]
help me

**Comment by The-Compiler** [comment]
Can you please show a minimal but runnable example which demonstrates the issue? FWIW I doubt this is an issue in pytest itself.

**Comment by sijunji** [comment]
In a folder, start the Falsk site and run the Request client

conftest.py
`import pytest
from selenium import webdriver
global driver
@pytest.fixture(scope='session')
def web_driver_initialize():
    """
    Initialize the browser
    """
    global driver
    chrome_driver_path = '/Users/sijunji/ProjectFile/PYObject/TMT_QA_UI_Test/demo/chromedriver'
    driver = webdriver.Chrome(chrome_driver_path)
    return driver
@pytest.fixture(scope='function', autouse=True)
def quit_driver(request):
    """
    :return:
    """
    def _quit_driver():
        driver.quit()
    request.addfinalizer(_quit_driver)
`
flask site: app.py
`# !/usr/bin/python
# -*- coding: UTF-8 -*-
"""
import: pytest, flask, flask_cors
"""
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor
import pytest
from flask import Flask, request, make_response
from flask_cors import *
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
sys.path.append(os.path.dirname(__file__))


app = Flask(__name__)
app.config['JSON_AS_ASCII'] = False
CORS(app, supports_credentials=True)


app.executor = ThreadPoolExecutor(10)


def analytical_data(data, report_name):
    """
    将请求中的参数放入队列
    """
    pytest_run_data = ['-v', f'--html={report_name}']
    for i in data:

        if len(i) == 1:
            data_str = '' + i[0]
            pytest_run_data.append(data_str)
            continue
        else:
            data_str = '' + i[0] + '::'
            if issubclass(type(i[1][0]), list):
                for y in i[1][0]:
                    pytest_run_data.append(data_str + y)
                    continue
            elif len(i[1]) == 1:
                pytest_run_data.append(data_str + i[1][0])
                continue
            else:
                for y in i[1][1]:
                    pytest_run_data.append(data_str + i[1][0] + '::' + y)
    pytest.main(pytest_run_data)


@app.route('/run_ui_auto', methods=["POST"])
def run_ui_auto():
    """

    接口接收一个list
    [[test_file.py, [class_name, [model_name1, model_name2]]]]: 有类，有方法执行
    [[test_file.py, [[model_name1, model_name2]]]]: 没有类，指定方法执行
    [[test_file.py, []]]: 按照文件运行
    [
     [test_file.py, []],
     [test_file.py, [[model_name1, model_name2]]],
     [test_file.py, [类名, [model_name1, model_name2]]]
    ]: 多文件运行
    """
    report_key = str(int(time.time() * 1000))
    report_name = 'test_No.' + report_key + '.html'
    data_list = request.json.get('data_list')
    app.executor.submit(analytical_data, data_list, report_name)

    return make_response({'msg': 'running.....', 'report_key': report_key})



if __name__ == '__main__':
    app.run(debug=False, host='127.0.0.1', port=5005, threaded=False)
`
test_demo.py
`
import time

from selenium.webdriver.common.keys import Keys


def test_demo1(web_driver_initialize):
    driver = web_driver_initialize
    driver.get('https://www.google.com')
    driver.find_element_by_xpath('//input[@name="q"]').send_keys('pytest')
    driver.find_element_by_xpath('//input[@name="q"]').send_keys(Keys.ENTER)
    time.sleep(5)
    print('run ok')`

request client：

`import requests

session = requests.session()
data = {
    'data_list': [
        ['test_demo.py', [['test_demo1']]],
    ]
}

r = session.post('http://127.0.0.1:5005/run_ui_auto', json=data)
print(r.text)
`

**Comment by sijunji** [comment]
Problem recurrence steps:
Start the Flask site
Flask site calls Pytest.main () twice in a row using the Request client

**Comment by sijunji** [comment]
I found the problem. Since the driver I used was a global variable, the driver ID used when the fixture was recycled was caused by the same driver ID. Now I have solved the problem. Here are the corresponding code changes

`@pytest.fixture(scope='session', autouse=True)
def quit_driver(request, web_driver_initialize):
    """
    :return:
    """
    def _quit_driver():
        web_driver_initialize.quit()
    request.addfinalizer(_quit_driver)
`

**Comment by nicoddemus** [comment]
Thanks for sharing @sijunji
