### ISSUE TITLE
ENH, Query: a function capabale of "self-skipping" in parametrization

### ISSUE THREAD

**Issue by tylerjereddy** [pytest-dev/pytest#9473]
I've been spending some time on this design, and maybe it is something with a trivial solution, or maybe an idea for a plugin of some sort. My best solution so far involves manipulating `pytest_collection_modifyitems` (https://github.com/darshan-hpc/darshan/pull/587#issuecomment-1004497390), perhaps a bit more "hacking" than I'd like, but to summarize the problem I'd like to have a custom function like `get_log_path()` below that will either retrieve an asset that is used for testing (like a file path), or if it cannot find the asset, automatically inject a skipping event. A bit like being able to turn itself into `pytest.param(..., marks=pytest.mark.xfail)` without needing to manually place the `pytest.param..`.

```python
@pytest.mark.parametrize(
    "argv", [
        [os.path.abspath("./tests/input/noposix.darshan")],
        [os.path.abspath("./tests/input/noposix.darshan"), "--output=test.html"],
        [os.path.abspath("./tests/input/sample-dxt-simple.darshan")],
        [os.path.abspath("./tests/input/sample-dxt-simple.darshan"), "--output=test.html"],
        [get_log_path("imbalanced-io.darshan"), "--output=test.html"],
        [None],
    ]   
)
def test_main_without_args(tmpdir, argv):
    pass
```

I'm not sure if this is asking a lot or not. It seems like there are vaguely similar things like `pytest.importorskip`--in my case, looking for a bit more granularity and the skip happens with some custom logic rather than just import failure.

**Comment by RonnyPfannschmidt** [comment]
importorskip is a big gun that breaks a whole test module

without more context/details this is a big ask, as pretty much placing one parameter set in a explicit param is a very easy thing to do

btw, the example is too minimal to give good suggestions

**Comment by RonnyPfannschmidt** [comment]
my basic impression is that if the function was not made aware of pytest at all, and you just ran it in a global before , your single usage site could be fine with a simple conditional on whether it was possible to get the value

**Comment by hoefling** [comment]
If I understand the problem correctly, you could use the indirect parametrization to preprocess the test params. Smth like
```py
@pytest.fixture
def argv(request):
    filepath, *args = request.param
    try:
        preprocessed = get_log_path(filepath)
    except AnyError:
        pytest.skip(f'File {filepath} not found')
    return [preprocessed, *args]


@pytest.mark.parametrize(
    "argv", [
        [os.path.abspath("./tests/input/noposix.darshan")],
    ], indirect=True  # or restrict to single param via `indirect=['argv']`
)
def test_main_without_args(tmpdir, argv):
    f, *args = argv
```

**Comment by tylerjereddy** [comment]
I did link some example code above, but I can try to paste some isolated snippets to give you an idea of what we're trying to do, along with a bit more description. One thing to note is that the imperative skipping suggestion from @hoefling is part of the eventual design--I'd like the function to be able to skip when called either inside a test or from within a parametrization block. Within a test is much easier of course, just use `pytest.skip(message_string)`. Distinguishing between test collection time and test *run* time doesn't look too bad--there are some environment variables that might do the job for run time I think.

One of the deeper problems I've had here is that there appears to be a fundamental lock on manipulating the `args` attribute of the `Mark` objects--they are "frozen" objects I believe (I get frozen instance errors on direct manipulation). That made me jump through a few more hoops vs. say mutating the parameters directly.

Here is a draft version of the module containing the function, currently targeted at the hardest problem--skipping a parametrized test case when the asset is missing (the comments/docs are probably a bit out of date--I would just skim the code in `get_log_path()` that uses the custom `Skipper` class when `pytest` is running, then look at what is going on in the `conftest.py` module to identify the usage of `Skipper` and take some (currently crude) action). Note that for an isolated test with a parameter to skip it seems somewhat "ok," but it will collapse in the context of an entire module or test suite, because the `items` data structure gets a bit bigger/more complicated. That said, I *believe* it is possible to study the node/`items` structure and make it work somewhat more robustly.

```python
import platform
import sys
python_version = platform.python_version_tuple()
# shim for convenient Python 3.9 importlib.resources
# interface
if int(python_version[1]) < 9 and int(python_version[0]) == 3:
    import importlib_resources
else:
    # see: https://github.com/python/mypy/issues/1153
    import importlib.resources as importlib_resources # type: ignore

import os
import glob
from typing import Optional, Any

if 'pytest' in sys.modules:
    # only import pytest if used in a testing context
    import pytest
    pytest_session = True
    class Skipper:
        def __init__(self, err_msg):
            self.err_msg = err_msg
else:
    pytest_session = False

try:
    import darshan_logs
    has_log_repo = True
except ImportError:
    has_log_repo = False


def _locate_log(filename: str, project: str) -> Optional[str]:
    """Locates a log in a project."""
    p = importlib_resources.files(project) # type: Any
    if project == "darshan":
        # move up 2 directories for now
        p = p.parent.parent
    darshan_logs_paths = [str(p) for p in p.glob('**/*.darshan')]
    for log_path in darshan_logs_paths:
        if filename in log_path:
            return log_path
    # if log is not found
    return None

def get_log_path(filename: str) -> str:
    """
    Utility function for locating logs either
    locally or in the darshan-logs repo.

    Parameters
    ----------
    filename: filename of Darshan log to locate
    in PyDarshan or darshan-logs repo.

    Returns
    -------
    log_path: absolute path to the darshan log matching the input filename.

    Raises
    ------
    FileNotFoundError: if a log cannot be found that matches the input filename.

    Notes
    -----
    If used in the context of a pytest, `pytest.skip()` will
    be used if both A.) a local log cannot be found, and
    B.) the darshan-logs repo is unavailable.

    """
    # try local paths
    log_path = _locate_log(filename=filename, project='darshan')
    if log_path:
        return log_path
    # try the logs repo
    if has_log_repo:
        log_path = _locate_log(filename=filename, project='darshan_logs')
        if log_path:
            return log_path
        else:
            err_msg = f"File {filename} could not be found in any available resources."
            raise FileNotFoundError(err_msg)
    else:
        err_msg = f"File {filename} not found locally and darshan-logs repo unavailable."
        if pytest_session:
            return Skipper(err_msg)
        else:
            raise FileNotFoundError(err_msg)

```

`conftest.py`:

```python
import darshan
import platform
python_version = platform.python_version_tuple()

# shim for convenient Python 3.9 importlib.resources
# interface
if int(python_version[1]) < 9 and int(python_version[0]) == 3:
    import importlib_resources
else:
    # see: https://github.com/python/mypy/issues/1153
    import importlib.resources as importlib_resources # type: ignore


import pytest

try:
    import darshan_logs
    has_log_repo = True
except ImportError:
    has_log_repo = False

def pytest_configure():
    pytest.has_log_repo = has_log_repo

class CustomNode:
    def __init__(self, mimic_item):
        for attr in dir(mimic_item):
            if attr not in ["own_markers", "iter_markers"] and "__" not in attr:
                setattr(self, attr, getattr(mimic_item, attr))

def pytest_collection_modifyitems(config, items):
    new_items = []
    skip_indices = []
    for i, test_item in enumerate(items.copy()):
        param_marker = test_item.own_markers[0]
        num_args = int(len(param_marker.args) / 2)
        for arg_num in range(num_args):
            arg_name = param_marker.args[arg_num]
            arg_values = param_marker.args[arg_num + 1]
            for arg_val_num, arg_value in enumerate(arg_values[:]):
                skipper_found = 0
                for arg_sub_value in arg_value:
                    if isinstance(arg_sub_value, darshan.log_utils.Skipper):
                        err_msg = arg_sub_value.err_msg
                        if arg_val_num not in skip_indices:
                            skip_indices.append(arg_val_num)
                            customnode = CustomNode(test_item)
                            customnode.own_markers = pytest.mark.skip
                            def iter_marks(name):
                                yield pytest.mark.skip(reason=err_msg)
                            customnode.iter_markers = iter_marks
                            new_items.append(customnode)

    for i, item in enumerate(items.copy()):
        if i not in skip_indices:
            new_items.append(item)

    items.clear()
    items.extend(new_items)

```

**Comment by tylerjereddy** [comment]
The custom hacking in `pytest_collection_modifyitems` is probably the main thing `pytest` devs might have suggestions for improving?

**Comment by tylerjereddy** [comment]
And if the parametrized arguments are nested arbitrarily deeply, even that draft may not suffice for an isolated test (I imagine `pytest` itself has some tricky code for handling even the normal cases).

**Comment by RonnyPfannschmidt** [comment]
@tylerjereddy in the linked changes, it seemed like exactly a single test would use this, so the solution seems a bit like ![xkcd general problem](https://imgs.xkcd.com/comics/the_general_problem.png)

there are some considerations for pytest to take params object out of arametersets and merging them, however initial experiments demonstrated this to be error prone

i would strongly recommend to just make a helper that interprets the exception and returns a pytest.param for that particular case

**Comment by tylerjereddy** [comment]
We'd definitely use it for multiple tests, and multiple parameters within each test; single test was just for demo. The log/data files will be progressively added for regression testing to separate external repo over the lifetime of the project when new issues are discovered with those file formats, etc.

I'm not picky about the design--if a try/except approach is robust for test collection time error handling (you're saying it works just as easily as at test *run* time?) that's fine by me.

**Comment by tylerjereddy** [comment]
That said, I'm not fully clear on how you'll get the exact arguments to feed to `pytest.param`, which seems to me like part of the original problem we're facing. In other words, is it actually trivial to mimic the `pytest.param(..` one would write manually, programatically after the error happens and then continue test collection gracefully. There would be other parameters that the custom function may not be aware of without probing deeper? Are we talking about looking at the error message/string and parsing from that or?

**Comment by RonnyPfannschmidt** [comment]
you would make a additional helper that returns you the test parameters and wraps them in pytest.param

if you add a few more examples of the different ways where you want to use the path helper i may be able to suggest a matching test parameter helper

**Comment by tylerjereddy** [comment]
Any examples available where this has been done before? Even a link to some source code buried somewhere might be helpful.

Within the context of `pytest` it would mostly be:

1. the imperative case sometimes (simple to handle)
2. one or more parametrized cases on a given test--`pytest.mark.parametrize()` where some of the parameters are always guaranteed to be present (assets in the repo), while others can either be missing or present depending on local availability of the data files.
3. it won't be all tests that needs this, but safe to assume the sometimes-skipped tests will be spread heterogenously throughout different tests in different testing modules.

The most important scenario is for tests that mix guaranteed and sometimes-missing assets like this:

```python
@pytest.mark.parametrize(
    "log_file, number_of_images", [
        ["./tests/input/noposix.darshan", 2], # error if this is missing--should always be present
        ["./tests/input/noposix.darshan"), 3], # always present
        [("./tests/input/sample-dxt-simple.darshan"), 4], # always present
        [("./tests/input/sample-dxt-simple.darshan"), 1], #always present
        [get_log_path("imbalanced-io.darshan"), 17], # SKIP if asset missing
        [get_log_path("another_log.darshan"), 5], # SKIP if asset missing
        [None, 0], # `None` obviously always present
    ]   
)
def test_example(log_file, number_of_images):
    pass
```

It would be great if the `pytest` report shows the same skipping summary you'd get as if you manually marked skips on the two `get_log_path()` calls when the assets are missing.

**Comment by RonnyPfannschmidt** [comment]
@tylerjereddy if the form is always (log_path, parameters) i would propose to simply have a shortnamed helper function to turn the form o the dynamic get into a pytest.param

another way would e to have  a own parametrize marker, that maps log files and parameters to something smarter

```python
@check_logs("log_file, number_of_images", [
   (....),
   (....),)
   ])
   
 def mytest(....):
   ...
   ```

**Comment by Zac-HD** [comment]
Closing as discussion seems to have petered out.
