### ISSUE TITLE
cannot see ansi colors in the stdout capture call

### ISSUE THREAD

**Issue by alexzanderr** [pytest-dev/pytest#9483]
i had run `pytest` with `--color=yes` in terminal and some of my tests where printing something on stdout, pytest captured the output, but ansi colors where not present.

here was the full command: `pytest -vv -x -rP --color=yes --durations=0`

does pytest have ansi color output support from stdout call capture ?

here im testing a function that prints colored output in my terminal
![image](https://user-images.githubusercontent.com/54772464/148414355-32336498-ca2f-4011-a0d2-026c170f2466.png)

but not in pytest captured stdout call
![image](https://user-images.githubusercontent.com/54772464/148414318-ef47aeb3-ba46-42a0-8ed5-7b54b22c40ae.png)

or maybe im using the wrong flag ...

**Comment by RonnyPfannschmidt** [comment]
the `--color` flag for pytest only is about what pytest does about colors

the stdio capture pytest provides is not ansi color aware (the capture fd is not makred as a tty either)

so its quite likely that whatever you use for stdio coloring auto-disables it

**Comment by alexzanderr** [comment]
okey. thanks for reply. can i make a feature request from this issue?

**Comment by RonnyPfannschmidt** [comment]
we could, but i believe its unlikely that anyone will implement it, tools like rich for example already use higher level testing tools, and pytest itself just explicitly forces color on the tests that need to check the output 

its currently tricky to implement, as output capture has different behaviours thatn a normal terminal and im not aware of anyone wanting to dig into it

**Comment by alexzanderr** [comment]
okey lemme give it a try. just tell me which file/files needs to be modified.

**Comment by RonnyPfannschmidt** [comment]
the capture plugin would be a starting point

**Comment by alexzanderr** [comment]
nice. thanks.

**Comment by alexzanderr** [comment]
wow you do test pytest with itself. so cool.

**Comment by asottile** [comment]
even if this were possible to change within pytest it would be a big breaking change to consumers of pytest if the default `isatty` were to change (for which the current assumption is `isatty=False`)

usually it's best to individually test the coloring via mocking `isatty` or whatever trigger your coloring code uses -- for example [from all-repos](https://github.com/asottile/all-repos/blob/5279ff6cc91f234f7605cee8123b5b68fb4357dd/tests/grep_test.py#L104-L124) or [from pre-commit](https://github.com/pre-commit/pre-commit/blob/559d8a78d11881c8db352f64bfc926b9d66e151d/tests/color_test.py#L23-L54)

**Comment by alexzanderr** [comment]
how about making an option for command-line like `--ansi-stdout-call=True/False` and its up to the user to decide. And will let the default value to `False` to not break the entire code.

**Comment by asottile** [comment]
it wouldn't work for all methods of color detection -- only for those which use `isatty` (for instance some do color detection via `curses` or via `tput`)
