### ISSUE TITLE
[prerelease] pytest-isort and `if session is None: assert parent is None`

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#9487]
Another one from #9415 - I don't quite understand what's going on and would like some help here.

When running the tests of [`pytest-isort`](https://github.com/stephrdev/pytest-isort), they fail with pytest 7.0.0rc1, but they fail in three different ways when bisecting things:

After 22dad53a248f50f50b5e000d63a8d3c798868d98:

```pytb
pytest_isort/__init__.py:67: in pytest_collect_file
    return IsortItem.from_parent(parent, fspath=path)
../../../proj/pytest/src/_pytest/nodes.py:587: in from_parent
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)
../../../proj/pytest/src/_pytest/nodes.py:237: in from_parent
    return cls._create(parent=parent, **kw)
../../../proj/pytest/src/_pytest/nodes.py:128: in _create
    return super().__call__(*k, **kw)
pytest_isort/__init__.py:175: in __init__
    super(IsortItem, self).__init__(name=path, parent=parent, **kwargs)
../../../proj/pytest/src/_pytest/nodes.py:621: in __init__
    super().__init__(name, parent, config, session, nodeid=nodeid)
../../../proj/pytest/src/_pytest/nodes.py:549: in __init__
    path, fspath = _imply_path(path, fspath=fspath)
../../../proj/pytest/src/_pytest/nodes.py:100: in _imply_path
    raise ValueError(
E   ValueError: Path(local('/home/florian/tmp/pytest-bisect/pytest-isort/pytest_isort/__init__.py')) != <Session pytest-isort exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=0>
E   if both path and fspath are given they need to be equal
```

After d7b0e172052d855afe444c599330c907cdc53d93:

```pytb
pytest_isort/__init__.py:67: in pytest_collect_file
    return IsortItem.from_parent(parent, fspath=path)
../../../proj/pytest/src/_pytest/nodes.py:622: in from_parent
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)
../../../proj/pytest/src/_pytest/nodes.py:254: in from_parent
    return cls._create(parent=parent, **kw)
../../../proj/pytest/src/_pytest/nodes.py:131: in _create
    return super().__call__(*k, **kw)
pytest_isort/__init__.py:175: in __init__
    super(IsortItem, self).__init__(name=path, parent=parent, **kwargs)
../../../proj/pytest/src/_pytest/nodes.py:671: in __init__
    super().__init__(
../../../proj/pytest/src/_pytest/nodes.py:576: in __init__
    path, fspath = _imply_path(path, fspath=fspath)
../../../proj/pytest/src/_pytest/nodes.py:112: in _imply_path
    assert fspath is not None
E   AssertionError
===================
```

After f87df9c52eb1113799f241dbd35934efa1bef330 (also needs 63899c76a40a5feabc312eb37e869386faf316f8):

```pytb
/home/florian/tmp/pytest-bisect/pytest-isort/tests/test_plugin.py:187: in test_init
    test_obj = IsortItem.from_parent(parent, fspath=path)
/home/florian/proj/pytest/src/_pytest/nodes.py:623: in from_parent
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)
/home/florian/proj/pytest/src/_pytest/nodes.py:256: in from_parent
    return cls._create(parent=parent, **kw)
/home/florian/proj/pytest/src/_pytest/nodes.py:140: in _create
    return super().__call__(*k, **kw)
/home/florian/tmp/pytest-bisect/pytest-isort/pytest_isort/__init__.py:175: in __init__
    super(IsortItem, self).__init__(name=path, parent=parent, **kwargs)
/home/florian/proj/pytest/src/_pytest/nodes.py:676: in __init__
    super().__init__(
/home/florian/proj/pytest/src/_pytest/nodes.py:592: in __init__
    assert parent is not None
E   AssertionError
```

Note that you will need `pytest-isort` master (with https://github.com/stephrdev/pytest-isort/pull/39 in).

This might be caused by something `pytest-isort` does (see its [source](https://github.com/stephrdev/pytest-isort/blob/master/pytest_isort/__init__.py)), but honestly I'm pretty lost...

cc @RonnyPfannschmidt @bluetech @stephrdev @hroncok

**Comment by RonnyPfannschmidt** [comment]
It's likely related to the item + file inheritance

**Comment by stephrdev** [comment]
If there is something we can fix in pytest-isort, I'm willing to do whatever is needed maintaining backwards compatibility for at least 5 and 6.

**Comment by bluetech** [comment]
The model for the fixes needed for File+Item inheritance and path/fspath issues is pytest-pyflakes: https://github.com/asmeurer/pytest-flakes/blob/master/pytest_flakes.py

I can submit a PR for pytest-isort when I get a chance (and if someone else does feel free to ping me for review).

**Comment by The-Compiler** [comment]
Seems like nobody picked this up so far, so I guess we'll just live with this for 7.0.0. I guess that's acceptable given that it only seems to affect one plugin, at least from what @hroncok tested in Fedora.

If someone can take a look at fixing the underlying issue in pytest-isort, that'd be great though!

**Comment by nicoddemus** [comment]
Opened https://github.com/stephrdev/pytest-isort/pull/40 for this. 👍

**Comment by stephrdev** [comment]
Perfect, will look into this tonight.

**Comment by nicoddemus** [comment]
@stephrdev if you can go to the page earlier than that to at least let the CI run, it would be great. 👍 

![image](https://user-images.githubusercontent.com/1085180/151370219-e454bca1-aedc-4db0-85e8-d74ec9e439c0.png)

**Comment by nicoddemus** [comment]
Fixed in https://github.com/stephrdev/pytest-isort/pull/40
