### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by jjg-dressipi** [pytest-dev/pytest#9505]
In the [official documentation](https://docs.pytest.org/en/6.2.x/customize.html), it is stated that

> Many pytest settings can be set in a configuration file, which by convention resides on the root of your repository or in your tests folder.

but I find that `pytest.ini` is only included if it is in the root of the Python project, not if it is in the `tests` subdirectory.  This is  Python 3.7.5, pytest-7.0.0rc1

**Comment by eamanu** [comment]
Hi, I can confirm this behavior. I tested with Py3.9 and pytest: `7.0.0rc1`, `6.2.*`, `6.1.*`, `6.0.0` and `5.4.1`.

**Comment by nicoddemus** [comment]
>but I find that pytest.ini is only included if it is in the root of the Python project, not if it is in the tests subdirectory.

Running just `pytest` I assume? If you run `pytest tests`, then the configuration file gets picked up.

But I agree we should improve that sentence. Probably best to just remove the "on your tests folder", as I consider having it in the root of the repository the recommended/most common approach.

**Comment by eamanu** [comment]
> Probably best to just remove the "on your tests folder", as I consider having it in the root of the repository the recommended/most common approach.

I agree, that section talk about configurations files in general, not only `pytest.ini`
even pyproject.toml, setup.cfg, etc. And definitely the root of the repository it's the
most common place.
