### ISSUE TITLE
Missing graph with linearization

### ISSUE THREAD

**Issue by baevpetr** [pytest-dev/pytest#9523]
I assume that this section(https://docs.pytest.org/en/6.2.x/fixture.html#autouse-fixtures-are-executed-first-within-their-scope) is missing a picture with a linearized fixture call graph after line:
> Because c can now be put above d in the graph, pytest can once again linearize the graph to this:

**Comment by RonnyPfannschmidt** [comment]
i believe this was accidentally missed in https://github.com/pytest-dev/pytest/pull/7381/files#diff-c6e6006fd5743454db91ea46dbffac292b30d87f3cb00a6e688e9583b844a225R1446

@SalmonMode do you by chance have that around still?

**Comment by SalmonMode** [comment]
Ah interesting. Looks like that one slipped through the cracks. Thanks for catching this! I'll just make a PR for it super quick 🙂
