### ISSUE TITLE
Disable the creation of the __pycache__ directory... From pytest.ini / pyproject.toml

### ISSUE THREAD

**Issue by maxsu** [pytest-dev/pytest#9529]
### Problem Statement

In order to keep project directory structures clean and non-distracting, I'd like to:

1. Prevent the creation of `__pycache__` directories when running tests
2. Control this behavior from existing config files (pytest.ini or pyproject.toml)

### Use Case

Simple projects that don't benefit from bytecode caching would benefit from a cleaner directory structure. A solution would consolidate pytest configuration and reduce the need for extra files, eg, `.gitignore` or a `test-runner.sh`.

### Workarounds

1. Set an environment variable during pytest invokation, eg, `PYTHONDONTWRITEBYTECODE=1 pytest` (see: #200)
2. Create a post-test cleanup script to delete the cache
3. Ignore the cache directories via `.gitignore`

#### Caveats: 
- Solutions 1 and 2 require the user to manually configure pytest  behavior at invocation or pushes pytest behavior to an extra file (eg. `test-runner.sh`).
- Solution 3 cleans up the project at the git repository level but requires a `.gitignore` file and creates cache directories at a local level.

**Comment by The-Compiler** [comment]
FWIW I'm -1 on this. Anything importing your module will lead to Python writing `__pycache__`, so a knob to only turn this off for pytest only seems to be useful in one specific case (namely when you never import your code, nor use any tools which do so).

**Comment by RonnyPfannschmidt** [comment]
a possible consideration could be on whether pytest should support putting pyc files into the pytest cache folder based on a  argument

but thats not what this is about 

im also -1 on a pytest local option for this based on missed errors/issue in the past when running without bytecode

**Comment by maxsu** [comment]
@The-Compiler, unless I'm mistaken test-time creation of `__pycache__` directories seems like a distinct behavior from import-time creation. When deploying to a production environment, the runtime should create cache files as necessary. When testing locally, it would be nice to not clutter the directory tree with files irrelevant to the developer.

@RonnyPfannschmidt if testing without writing bytecode can lead to missed errors, that's a serious pain. That's unexpected to me, since the interpreter creates bytecode even if it doesn't cache to disk. On the other hand, if complex test scenarios would force the interpret to create and re-create the bytecode during testing, this could make a horrifying kind of sense. 

A couple questions:
1. Do we know why failing to write byte code can cause missed tests? Is it replicable, or is it the kind of stochastic horror-bug that strikes with no reason or logic?
1.  Does the risk of missed tests increase if we clean up the cache directory after testing (eg, workaround 2)?

If workaround 2 is safe, then perhaps a solution is a pytest plugin that does post-test cleanup.

**Comment by maxsu** [comment]
@The-Compiler I think your argument is analagous to this:

> Hi, I have a dog named Pytest, but it makes a mess. Can I train it to make less mess? 

> Look, I have five dogs, and they all make messes. So there's no use training Pytest. Let it be a dog!

But I really do just testing in most sessions, and if I deal with one mess at a time, my environment stays clean.

I would like to implement the feature and get it into the standard build or standard plugins. I would really appreciate suggestions that'll help the PR go through, thanks!

**Comment by maxsu** [comment]
@The-Compiler if I misunderstood and misrepresented your point, then I apologize. 

Most of the time I run only pytest, and want the option to run pytest without adding extra files to my source. I'm willing to deal with other tools on their own terms; this is part of an effort to deal with sources of cache files one tool at a time. I think that's reasonable.

**Comment by maxsu** [comment]
@nicoddemus @The-Compiler, I remain convinced that an option to suppress `__pycache__`  folder creation would nice to have in my own projects, and may be a good first Pytest plugin or PR for me. I'd need a pointer as to where to make this change, and I might reach out with a mentorship request in the future. For the help, I would be willing to handle other more important issues as well. I'll close this issue now, so as to keep the backlog clear of low value issues. Regards.

**Comment by Cheaterman** [comment]
I had a bit of an interesting SNAFU today where pyc's would be caching a host file path that would then be incorrect when running tests inside docker (python-dotenv blew up, I'm guessing because it does... interesting... tricks to find its own location - possibly something I should report there?).

**Comment by 0cjs** [comment]
For a start, "unit tests use different bytecode cache files from other tests and ad-hoc development runs" opens up new and interesting ways for tests to fail to properly test code. 

> But I really do just testing in most sessions, and if I deal with one mess at a time, my environment stays clean.

Which is all fine until you custom method of handling one mess conflicts with a generic method of handling all the messes. For example, you didn't even consider how this interacts with someone like me who sets `PYTHONPYCACHEPREFIX=$HOME/.cache/pycache__` in his personal environment.

(And you might consider doing exactly that; I believe it will solve the issue you're concerned about for all code, not just only certain uses of `python` in certain development repos.)
