### ISSUE TITLE
pytest-xprocess no longer shows process log on test failure

### ISSUE THREAD

**Issue by untitaker** [pytest-dev/pytest#953]
pytest-xprocess stopped showing the process' output when a testcase depending on that process fails. Reverting https://bitbucket.org/pytest-dev/pytest-xprocess/commits/2937e9008dd13fe8193f1d6a572bed6a5eca1e50 fixes this problem.

**Comment by untitaker** [comment]
@hpk42 Could you take a look at this? I'm hitting this problem again. It's somewhat annoying when trying to debug faulty command behavior in Travis (where there's no way to manually read from the logfiles).

**Comment by Zac-HD** [comment]
If this is still a problem, we should open an issue on https://github.com/pytest-dev/pytest-xprocess so someone working on `pytest-xprocess` actually sees it 😄
