### ISSUE TITLE
adding a link to the Python logging page

### ISSUE THREAD

**Issue by FIOpwK** [pytest-dev/pytest#9540]
#### What's the problem this feature will solve?
Finding information on logging levels may prove simple if link to:
Python docs: [https://docs.python.org/3/library/logging.html#logging-levels] 

was found on page:

 Pytest docs: [https://docs.pytest.org/en/6.2.x/logging.html#live-logs]

Perhaps include the link in the  `reference external` class.

**Comment by nicoddemus** [comment]
Good idea! Would you like to contribute that?

**Comment by itsyourOOP** [comment]
Is this issue open? I'd like to try my hand at it.

**Comment by The-Compiler** [comment]
@itsyourOOP it looks like @FIOpwK has opened a PR for this in the meantime (#9568), but thanks for your interest!

**Comment by Achintya-Chaware** [comment]
Is this issue still open?
