### ISSUE TITLE
arguments passing to request.params getting overwritted from test

### ISSUE THREAD

**Issue by nireshs** [pytest-dev/pytest#9541]
Hi,

I am facing issue with parameterize test, arguments passing via request.prams getting overwritten from calling function.

Below is the steps,
1) Passing a list variable as argument to parameterize test.
2) The test is calling another function and the assigning the list variable is another local variable
3) Calling function sorting the list (local variable)

Issue: 
At the end of the test, both local variable of calling function and list variable passed as argument got sorted. 
I am expecting, only local variable from the calling function should be sorted and arguments passed to the function (global variable) should remains unsorted. So that i can use the variable to multiple tests.

Below is the code, Please help me to understand how this is working currently, is this the way it supposed to work.

`
from array import array
import pytest

test_params1 = {
    'array_list': [5,4,3,2,1],

}

@pytest.fixture(name='bubble_sort', scope='function')
def bubble_sort(request):
    arr = request.param['array_list']
    print('\nBefore Sorting from sort function', arr, request.param)
    for i in range(len(arr)-1):
        for j in range(0, len(arr)-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    print('After Sorting from sorting function', arr, request.param)
    return arr, request

@pytest.mark.bubble_sort1
@pytest.mark.parametrize("bubble_sort", [test_params1], indirect=True)
def test_bubble_sort_1(bubble_sort):
    print('After test end ', bubble_sort[0], bubble_sort[1].param)

@pytest.mark.bubble_sort
@pytest.mark.parametrize("bubble_sort", [test_params1], indirect=True)
def test_bubble_sort_2(bubble_sort):
    print('After test end ', bubble_sort[0], bubble_sort[1].param)

`

Below is the output from above code:
=====================================

`
pytest -s  .\pytest_bug.py
===================================================================== test session starts ====================================================================== 
platform win32 -- Python 3.10.1, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: C:\Users\Niresh Shanmugam\OneDrive\SN\workspace\current\arrays
plugins: cov-3.0.0, html-3.1.1, metadata-1.11.0
collected 2 items                                                                                                                                                

pytest_bug.py
Before Sorting from sort function [5, 4, 3, 2, 1] {'array_list': [5, 4, 3, 2, 1]}
After Sorting from sorting function [1, 2, 3, 4, 5] {'array_list': [1, 2, 3, 4, 5]}
After test end  [1, 2, 3, 4, 5] {'array_list': [1, 2, 3, 4, 5]}
.
Before Sorting from sort function [1, 2, 3, 4, 5] {'array_list': [1, 2, 3, 4, 5]}
After Sorting from sorting function [1, 2, 3, 4, 5] {'array_list': [1, 2, 3, 4, 5]}
After test end  [1, 2, 3, 4, 5] {'array_list': [1, 2, 3, 4, 5]}
`

**Comment by The-Compiler** [comment]
The value `[5, 4, 3, 2, 1]` only exists in memory once, you just happen to have two different names referring to that value. This is not an issue related to pytest though, you would see the same issue with pure Python code doing something similar.

You might find this helpful: https://bit.ly/pynames

**Comment by nireshs** [comment]
> The value `[5, 4, 3, 2, 1]` only exists in memory once, you just happen to have two different names referring to that value. This is not an issue related to pytest though, you would see the same issue with pure Python code doing something similar.
> 
> You might find this helpful: https://bit.ly/pynames

@The-Compiler Thanks for your response. I understand the way how it works now. But i just want to know what will be the solution to re-use single param variable to multiple test cases.
Even i tried to send the copy of the list as argument but seeing the same issue.

`
@pytest.mark.bubble_sort
@pytest.mark.parametrize("bubble_sort", [test_params1**.copy()**], indirect=True)
`

It will be helpful if can provide us some solution for this.

**Comment by The-Compiler** [comment]
If you do `test_params1.copy()`, you are copying the `test_params1` dictionary, not the list. It's a shallow copy. You'd need to either use the `deepcopy` module or store the list and `.copy()` that instead of copying the dict.
