### ISSUE TITLE
pytest fails to register pytest-cov

### ISSUE THREAD

**Issue by sunu** [pytest-dev/pytest#955]
I am trying to run tests with coverage reports using `pytest-cov`.  But pytest-cov plugin doesn't get registered in one of the cases and the tests fails with `py.test: error: unrecognized arguments: --cov=splash`

Here's an [example of a failing job](https://travis-ci.org/sunu/splash/jobs/76699967).
Here's the [travis config](https://github.com/sunu/splash/blob/codecov/.travis.yml).

**Comment by RonnyPfannschmidt** [comment]
try running with --collectonly, and take a look at the plugin list
also try a more recent py.test

**Comment by sunu** [comment]
Using a more recent py.test did fix the issue. Thanks :)
