### ISSUE TITLE
Backport workflow: Extend to allow labeling open PRs

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#9553]
Yep, I was thinking about that as well - that would probably need to be a slightly different trigger (or even a separate workflow) though, which triggers when a PR is merged and then checks that PR's labels. I think ideally we would have both, so that the labels can be applied at any time and the proper thing will happen.

@bluetech is this something you'd be interested in? Personally I should take care of some dayjob stuff at the moment, so pytest 7 keeps me busy enough :slightly_smiling_face:

_Originally posted by @The-Compiler in https://github.com/pytest-dev/pytest/issues/9430#issuecomment-1004813034_

**Comment by webknjaz** [comment]
Shameless plug (yet again!): https://github.com/apps/patchback. I've accounted for applying the labels both before and after merging.
