### ISSUE TITLE
Backport workflow: Add some feedback comments

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#9555]
It would be good to get some (automated) feedback for the backport workflow. The bot could e.g. add a comment with a link to the backported PR if successful (and also take care of adding the "backported" label maybe?). Perhaps more importantly, if not successful, it should add a comment asking for a manual backport.

Right now, it's kind of "fire and forget", and if we don't carefully double-check, we risk accidentally forgetting about backports which should have been done.

**Comment by RonnyPfannschmidt** [comment]
the back-port pr should auto-link by  referring the origin pr
on failure we should create a issue about bug fixing the backport and/or fixing the backporter

maybe we can use a label as indicator like "backport-failed", and taking the label off and/or switching it to backport needed again could re-trigger a backport

but that may bee a but pushing it on the mechanics

**Comment by The-Compiler** [comment]
> maybe we can use a label as indicator like "backport-failed", and taking the label off and/or switching it to backport needed again could re-trigger a backport

I think transient backporting failures will be very rare. The most common reason a backport will fail is that there are conflicts, and at that point, a human will need to intervene. Still, deleting the branch and applying the label again will already trigger a new backport PR anyways.

**Comment by webknjaz** [comment]
FYI I have a GitHub App for backporting @ https://github.com/apps/patchback.

Here's the comments I came up with, for example:
* https://github.com/aio-libs/aiohttp/pull/6498#issuecomment-1019343424
* https://github.com/aio-libs/aiohttp/pull/6588#issuecomment-1029297748

_(config: https://github.com/ansible-collections/community.general/blob/main/.github/patchback.yml)_

That's in case you'd want to borrow ideas or just use it — it's been online for quite a while now: https://github.com/ansible-collections/community.general/pulls?q=author%3Aapp%2Fpatchback.

P.S. I like the labeling idea. My bot doesn't do it but I should probably implement that :) I think it's a good way for providing a discovery mechanism for PRs with failed backports.
