### ISSUE TITLE
retrieve list of available fixtures

### ISSUE THREAD

**Issue by juarezjsonar** [pytest-dev/pytest#9588]
#### What's the problem this feature will solve?
I was looking for a clean way of retrieving all the available fixtures while running tests.
Eg: when you pass a non-existing fixture as a test parameter, you get the error message:
```d
E       fixture 'f' not found
>       available fixtures: a, b, c, ...
```
It would be nice to have a way of retrieving this available fixtures list.

#### Describe the solution you'd like
Add the following method to class `FixtureRequest` using the same code that generates the list in the error message.
Something like the lines below:

```
def getavailablefixtures(self) → List:
   """ Returns a list of every fixture available at this point in time.  (or a better description)"""
   available = []
   fm = self._fixturemanager
   parentid = self._pyfuncitem.parent.nodeid
   for name, fixturedefs in fm._arg2fixturedefs.items():
       faclist = list(fm._matchfactories(fixturedefs, parentid))
       if faclist:
           available.append(name)
   return available
```

**Comment by The-Compiler** [comment]
Can you explain your use-case in a bit more detail? You might just be looking for `pytest --fixtures` maybe?

**Comment by juarezjsonar** [comment]
Yes, sure. Basically, I have a scenario where each fixture is a connection (lots of them, and the list keeps growing) and I need to run connection tests. 

In this use case, I'm parameterizing a test with a list of fixtures. Back in the day, I would do

```
@pytest.mark.parametrize('connection', ['a', 'b', 'c'])
def test_connect(connection):
   # you get the idea
```

but then I would like to:
1. construct the connection list dynamically
2. Scale it "automatically", ie, whenever a new connection fixture is added, the new fixture is added to the available fixtures list and boom, done!

**Comment by nicoddemus** [comment]
Hi @juarezjsonar,

I would decouple the definition of "connections" from the fixture definitions, placing them somewhere that your code can access, and then construct the fixtures from that.

```python
connection_ids = ['a', 'b', 'c']

@pytest.fixture(params=connection_ids)
def connection(request):
    return Connection(request.param)
```

This way you don't need to actually list *fixtures*, you have the actual connections at your disposal.

**Comment by juarezjsonar** [comment]
Hi @nicoddemus ,

Unfortunately, there's a whole infrastructure built upon the idea of connection being a fixture so that's not really possible at this point.
