### ISSUE TITLE
Allow changing the number temporary directories pytest keeps which is currently 3

### ISSUE THREAD

**Issue by szabgab** [pytest-dev/pytest#9599]
Currently `pytest` will keep the last 3 root temporary directories for each testing session, for all tests.

As far as I can tell it is a hard-coded parameter here:
https://github.com/pytest-dev/pytest/blob/a53abe93d87083bbd5c183bd654f5787c0376934/src/_pytest/tmpdir.py#L148
that cannot be changed using a configuration option.

In my current situation a single run creates 12Gb of data and it is growing as we add more tests. It would be nice if there was a way to change this number. I'd sacrifice the debug-ability to save disk-space. At least till we can find other ways to reduce the disk usage. Others might want to keep more history.

This is related to #8141 as well.

**Comment by RonnyPfannschmidt** [comment]
[the basetmp option](https://docs.pytest.org/en/6.2.x/tmpdir.html#the-default-base-temporary-directory)
is a ideal way to enforce a specific folder that will be nuked at the start of the test-run

**Comment by szabgab** [comment]
That solves the problem for me. Maybe the documentation could be amended with :

"The number of entries currently cannot be changed, but using the `--basetemp` option will remove the directory before every run effectively meaning the tempfiles of only the most recent run will be kept."

**Comment by nicoddemus** [comment]
> "The number of entries currently cannot be changed, but using the --basetemp option will remove the directory before every run effectively meaning the tempfiles of only the most recent run will be kept."

Sounds good, would you like to contribute that to the docs?
