### ISSUE TITLE
Public `ExceptionInfo` and `RaisesContext`

### ISSUE THREAD

**Issue by wimglenn** [pytest-dev/pytest#9623]
(reproduced from [discussion 9613](https://github.com/pytest-dev/pytest/discussions/9613))

I have a plugin, [pytest-raisin](https://github.com/wimglenn/pytest-raisin), which allows using exception instances with `pytest.raises`. For example:

```
import pytest

def test_example():
    with pytest.raises(KeyError("x")):
        {}["x"]
```

Since pytest 7.0.0, there's a `PytestDeprecationWarning` appearing:

```
$ python -m pytest
============================================================= test session starts ==============================================================
platform darwin -- Python 3.10.1, pytest-7.0.0, pluggy-1.0.0
rootdir: /private/tmp/b
plugins: raisin-0.3
collected 1 item                                                                                                                               

test_example.py .                                                                                                                        [100%]

=============================================================== warnings summary ===============================================================
test_example.py::test_example
  /private/tmp/b/.venv/lib/python3.10/site-packages/pytest_raisin.py:91: PytestDeprecationWarning: A private pytest class or function was used.
    self.excinfo.__init__(tp)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================= 1 passed, 1 warning in 0.00s =========================================================
```

The line it indicates is [here](https://github.com/wimglenn/pytest-raisin/blob/v0.3/pytest_raisin.py#L91). 

Anything we could do either in pytest or in pytest-raisin to not trigger this warning? Would it be possible to expose `ExceptionInfo` and `RaisesContext` for use?

**Comment by RonnyPfannschmidt** [comment]
Your plugin should internally use the pytest.raises api instead of extending a type that's intentionally internal only

My basic understanding of python exceptions is that they don't safely compare, which is the key reason why we have the match parameter to raises and no support for matching via value

Personally i would strongly prefer if we could safely match exceptions by value or match expression

**Comment by wimglenn** [comment]
Hey Ronny, I'm not really sure what you mean by "internally use the pytest.raises api", how would that look? Without the plugin, it can not accept instances at all:

```
>>> with pytest.raises(SystemExit(1)):
...     sys.exit(1)
TypeError: 'SystemExit' object is not iterable
```

Exception instances compare by identity, by default - but I've found comparing by their `.args` attribute is more useful than using a regex match on the string representation, the majority of the time. The plugin only adds additional functionality, it does not modify the existing use-cases.

**Comment by RonnyPfannschmidt** [comment]
You can just make a context manager that internally uses pytest. Raises

In addition i strongly recommend to stop monkeypatching pytest

It's entirely fine to prove the functions of your plugin inside its own namespace

**Comment by wimglenn** [comment]
https://github.com/wimglenn/pytest-raisin/pull/7/
