### ISSUE TITLE
test_junitxml.py::TestPython::test_failure_function broke on CI

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#9629]
See e.g. https://github.com/pytest-dev/pytest/runs/5086149463?check_suite_focus=true - happens in multiple unrelated PRs. No idea why off-hand...

**Comment by asottile** [comment]
looks like test pollution -- let me see if I can find out why

**Comment by asottile** [comment]
these are the polluting tests:

```console
$ cat t8
testing/test_doctest.py::TestDoctests::test_valid_setup_py
testing/test_junitxml.py::TestPython::test_failure_function[xunit1-all]
```

**Comment by asottile** [comment]
looks like a regression in setuptools -- between 60.5.0 and 60.6.0

**Comment by asottile** [comment]
cc @jaraco

**Comment by jaraco** [comment]
Thanks @asottile. I see you have a workaround for pytest. If that isn't a permanent fix, can you at least summarize or characterize the missed expectation from setuptools? I have a clue, but you seem to have a deeper grasp of it at the moment.

**Comment by asottile** [comment]
I'm not really sure, something about the changed version there causes the root logger to get misconfigured as a side effect of `setup()`

**Comment by jaraco** [comment]
Between those versions, the only change that seems at all relevant is https://github.com/pypa/setuptools/pull/3042. If someone wishes to investigate deeper, I welcome it.

**Comment by Lewiscowles1986** [comment]
An even weirder part of this is that Anthony has a YouTube video which starts with [this commit](https://github.com/pytest-dev/pytest/commit/bc33ba0be95a1b66038a17329573aaa1666c1a0f), and shows a totally different test polution failure...
https://www.youtube.com/watch?v=FRteianaPMo 

I think, the version of setuptools used at the time [futureproofing statement as this may be different when someone reads, or when the code was added]:

When running setup(), configures Python’s logging module. Specifically, it adds a NullHandler to the 'distutils' logger and, in some cases, modifies the global logging configuration, which can affect log levels.

https://github.com/pypa/setuptools/blob/1fe0c5d2f46e141d6097910d2905a3fce5e30c52/setuptools/__init__.py#L111-L117

@jaraco I think you are mentioned on a related PR https://github.com/pypa/setuptools/pull/2974, Issue https://github.com/pypa/setuptools/issues/2973 and commit https://github.com/pypa/setuptools/commit/382037c446f45ebc2e91fd5144eda4dfa90c0281
