### ISSUE TITLE
Using @pytest.mark.skipif on a fixture silently fails.

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#964]
Since `pytest.skip(...)` can be used inside a fixture, I'd've expected that `@pytest.mark.skipif` does as well - turns out it seems to do nothing:

```python
import pytest

@pytest.fixture
@pytest.mark.skipif(True, reason='test')
def fixt():
    pass

def test_one(fixt):
    pass

def test_two(fixt):
    pass
```

```
test_foo.py ..

============= 2 passed in 0.01 seconds ==============
```

**Comment by RonnyPfannschmidt** [comment]
marks on fixtures are not considered or taken into account

**Comment by nicoddemus** [comment]
Perhaps it should be made explicit in the documentation about `mark`s?

**Comment by RonnyPfannschmidt** [comment]
good point

**Comment by nchammas** [comment]
Is there any design reason we cannot expand `skipif` to apply to fixtures (and thus automatically apply to any downstream tests) as well? Is that what #1368 is about?

**Comment by RonnyPfannschmidt** [comment]
its tricky, complicated, and impossible to implement correct on the current mark mechanism
