### ISSUE TITLE
Expand warnings output for ResourceWarning

### ISSUE THREAD

**Issue by fschulze** [pytest-dev/pytest#9644]
It is difficult to debug ``ResourceWarning`` from the existing output.

In [Python3.6 a ``source`` field was added](https://bugs.python.org/issue26567) to the ``warnings.WarningMessage`` objects.

Since pytest now requires Python 3.7 I propose the following addition to the existing ``warning_record_to_str``:

```python
def warning_record_to_str(warning_message: warnings.WarningMessage) -> str:
    """Convert a warnings.WarningMessage to a string."""
    warn_msg = warning_message.message
    msg = warnings.formatwarning(
        str(warn_msg),
        warning_message.category,
        warning_message.filename,
        warning_message.lineno,
        warning_message.line,
    )
    tb = tracemalloc.get_object_traceback(warning_message.source)
    if tb is not None:
        msg = "%sSource of unclosed object:\n%s" % (msg, '\n'.join(tb.format()))
    elif issubclass(warning_message.category, ResourceWarning):
        # tracemalloc is inactive
        # TODO needs to be adjusted, see below in ticket
        msg = "%sGet a traceback for where the unclosed object was allocated by ..." % msg
    return msg
```

The output looks like this as an example:
```
  /.../devpi/devel/lib/python3.8/enum.py:315: ResourceWarning: unclosed <socket.socket [closed] fd=53, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
    return cls.__new__(cls, value)
  Source of unclosed object:
    File "/.../devpi/devel/lib/python3.8/site-packages/urllib3/connection.py", line 205
      conn = self._new_conn()
    File "/.../devpi/devel/lib/python3.8/site-packages/urllib3/connection.py", line 174
      conn = connection.create_connection(
    File "/.../devpi/devel/lib/python3.8/site-packages/urllib3/util/connection.py", line 77
      sock = socket.socket(af, socktype, proto)
```

This requires that ``tracemalloc`` is active. So the open question is, when should ``tracemalloc.start()`` be called and how to pass the size of the stack trace to it, as the default of ``1`` is often too small (I needed 20 to find the source of an unclosed requests Response). I propose three possible solutions:

1. Document running pytest like this: ``python -X tracemalloc=20 -m pytest ...``
2. Add a command line option to enable ``tracemalloc`` with the limit as parameter.
3. Enable tracing when warnings for ``ResourceWarning`` are set to ``once`` or ``always`` and always use a stack trace limit of ``3``.

**Comment by bluetech** [comment]
I think this would be a very nice feature. :+1: from me.

AFAIK tracemalloc has a large memory overhead so enabling it by default is not an option, and neither is option 3 really.

Can the logic be something like this?

```py
if warning_message.source is not None:
    # If tracemalloc is active, and has captured the object's allocation, show where it was allocated.
    tb = tracemalloc.get_object_traceback(warning_message.source)
    if tb is not None:
        msg += "\nObject allocated at (most recent call first):\n" + (nice tb formatting here)
    else:
        Suggestion to enable tracemalloc (if it's not enabled), or increase the number of frames (if it is enabled)
        Is it helpful at all to do anything with `warning_message.source` here (like show its repr),
        or assume it's already covered by the warning message itself?
``` 

as for what to write in the suggestion, option 1 `pytest` -> `python -X tracemalloc=20 -m pytest` seems a bit awkward. An alternative is to suggest `PYTHONTRACEMALLOC=20 pytest`. Or we can just add the command line argument (option 2). Not sure which is better. Maybe avoid the cmdline argument at first, and only add if if people encounter difficulties without it.

**Comment by fschulze** [comment]
@bluetech I like the environment variable approach, I didn't think of that.

Your if statements will also work in case any other warning has a ``source`` field. So +1.

I don't think we need to do anything with ``warning_message.source``. It is already represented and there is nothing generic possible with it, except maybe printing ``vars(warning_message.source)``, which only works if it has a ``__dict__``. I think the usefulness is further restricted, because it is already garbage collected, but I'm not sure right now.

**Comment by fschulze** [comment]
🎉
