### ISSUE TITLE
7.0.0 regression: Existence of conftest.py messes up package discovery with importlib + pythonpath mode (ModuleNotFoundError: No module named 'tests.<test-packages>')

### ISSUE THREAD

**Issue by bluenote10** [pytest-dev/pytest#9645]
Consider the following demo project:

**`setup.cfg`**
```ini
# The idea is to use `pythonpath = .` to enable imports from the `tests` folder
# like `import tests.<subpackages>`.
# Note that all involved directories have proper __init__.py, and importing e.g.
# `import tests.subpath.helper` works from a Python REPL.
[tool:pytest]
pythonpath = .
addopts =
    --import-mode importlib
```

**`tests/__init__.py`**
```python
# just empty
```

**`tests/conftest.py`** (existence of this file breaks package discovery)
```python
# just empty
```

**`tests/subpath/__init__.py`**
```python
# just empty
```

**`tests/subpath/helper.py`**
```python
# just empty
```

**`tests/subpath/test_something.py`**
```python
import tests.subpath.helper


def test_something():
    assert True
```

pytest (version 7.0.0) errors with:

```
______________________________________________________________________________________________________________________________________________ ERROR collecting tests/subpath/test_something.py _______________________________________________________________________________________________________________________________________________
ImportError while importing test module '/tmp/demo_project/tests/subpath/test_something.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/subpath/test_something.py:1: in <module>
    import tests.subpath.helper
E   ModuleNotFoundError: No module named 'tests.subpath'; 'tests' is not a package
=========================================================================================================================================================== short test summary info ===========================================================================================================================================================
ERROR tests/subpath/test_something.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================================================================================== 1 error in 0.08s ===============================================================================================================================================================
```

What's particularly surprising: The example works, when renaming the `conftest.py` to e.g. `conftest2.py`. I.e., it seems that the existence of the `conftest.py` implies that it is no longer possible to import from `tests`. Imports like this used to work with pre 7 pytest versions in `importlib` mode despite the existence of a `conftest.py`.

**Comment by bluetech** [comment]
Bisected to b706a2c04840a8057610f41071fbcf3da1290eb5 (PR #7870), cc @nicoddemus.

**Comment by nicoddemus** [comment]
Hi @bluenote10, 

Thanks for the detailed report, we definitely appreciate it.

> What's particularly surprising: The example works, when renaming the conftest.py to e.g. conftest2.py

That's because `conftest2.py` are not special to pytest, while `conftest.py` files are handled specially. But I can see why it might seem surprising at first. 👍 

> Imports like this used to work with pre 7 pytest versions in importlib mode despite the existence of a conftest.py.

Just to clarify to make sure we are not missing anything: `pythonpaths` was added in 7.0.0, so `pythonpaths` in the `pytest.ini` had no effect in prior versions. How did you configure the PYHONPATH in pytest<7, with the directory layout you posted?

**Comment by nicoddemus** [comment]
OK, thanks.

So to be crystal clear: if we remove `pythonpath` from your example, then running the command `pytest` in pytest 6 **works**, but in pytest 7 it **does not work**, giving the `ModuleNotFoundError` above, right?

(Sorry if I'm being pedantic, but having an accurate understanding is important)

**Comment by nicoddemus** [comment]
Ahh OK thanks.

>  In any case importing from tests used to work, and in particular when specifying pythonpath = . in 7.0, it probably should according to the documentation.

I agree, I will investigate. Thanks again.

**Comment by bluetech** [comment]
I tested it with `PYTHONPATH=.`
