### ISSUE TITLE
improvement: make pytest-timeout failure message customizable

### ISSUE THREAD

**Issue by pjotal** [pytest-dev/pytest#965]
i was trying to customize the pytest-timeout failure message one of this days and notice there is no extension point (hook or argument) that allows me to do that. digging in the code i noticed that this is due to the failure message being hardcoded (see https://bitbucket.org/pytest-dev/pytest-timeout/src/ea3ba7b8f9b3ed4fe75d981f0f98765e71ef7a7a/pytest_timeout.py?at=default#pytest_timeout.py-225).
therefore, this ticket is to suggest allowing this failure message to be somehow customizable (preferably via hook).

**Comment by nicoddemus** [comment]
pytest-timeout has its own [issue tracker](https://bitbucket.org/pytest-dev/pytest-timeout/issues). Could you open this issue there and close this one? Thanks! :smile:

**Comment by pjotal** [comment]
sure, i thought we're supposed to open them here since pytest-timeout was recently moved to pytest-dev as per this: https://bitbucket.org/pytest-dev/pytest-timeout/issues/9/move-under-pytest-dev-team
but alright. i created: https://bitbucket.org/pytest-dev/pytest-timeout/issues/11/improvement-make-pytest-timeout-failure
let me know if the ticket is really supposed to be only there. if so, i'll pass by and close this one. just want to confirm you're aware of their repo move.

**Comment by nicoddemus** [comment]
Thanks @pjotal! 

The repository moved from @flub's account to [pytest-dev@bitbucket](https://bitbucket.org/pytest-dev), so I'm sure that's the appropriate place. :smile:

I'm closing this myself, thanks again.

(Btw, I noticed you posted the issue as anonymous).

**Comment by flub** [comment]
Yep, that's the right place to report it. Thanks
