### ISSUE TITLE
Support callable condition in skipIf

### ISSUE THREAD

**Issue by tuukkamustonen** [pytest-dev/pytest#9650]
#### What's the problem this feature will solve?

Attempting to skip tests based on some runtime property, I can:

```py
@pytest.fixture()
def runtime_config():
    return load_some_dict_somewhere()  # don't want (expensive) or can't load this up (depends on smth else, etc) right away

def something_going_on(runtime_config):
    return 'bar' in some_fixture  # assume it returns dict

def test_foo(runtime_config):
    if something_going_on(runtime_config):
        pytest.skip('yeah')
    ...
```

But that's too lengthy, if you want to re-use it.

```py
def skip_if_something_going_on(some_fixture, reason=None):
    if 'bar' in some_fixture
        pytest.skip(reason)
    ...

def test_foo(some_fixture):
    skip_if_something_going_on(some_fixture, reason='yeah')
    ...
```

But that's not "descriptive" enough. It doesn't hit the eye as easy. Plus it's not consistent if skipping is done via decorator on easy cases and within function on hard.

#### Describe the solution you'd like

```py
def something_going_on(runtime_config):
    return 'bar' in runtime_config

@pytest.mark.skipIf(something_going_on, reason='yeah')
def test_foo():
    ...
```

Pytest would inject (and initialize if needed) the fixtures to the callable function (like with test functions and fixtures themselves).

#### Alternative Solutions

I could use a fixture:

```py
@pytest.fixture()
def skip_if_something_going_on(runtime_config):
    if 'bar' in runtime_config:
        pytest.skip(msg='yeah')
    ...

@pytest.mark.usefixtures('skip_if_something_going_on')
def test_foo():
    ...
```

But that feels a bit hacky and I cannot set the skipping message with that (though, I'm kinda hard-coding the condition so message should be the same usually).

**Comment by The-Compiler** [comment]
This mostly seems like a duplicate of #7395 - FWIW I don't think fixtures would work like you describe though, as those are evaluated after the skipif marks, as far as I know.

**Comment by tuukkamustonen** [comment]
Indeed, it seems mostly duplicate. Closing as a dupe.

The biggest difference is maybe that in above suggestion you could inject fixtures to the callable, although this was mentioned in https://github.com/pytest-dev/pytest/issues/7395#issuecomment-647020048, too.
