### ISSUE TITLE
7.0.0 tag is not part of any branch

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#9655]
The [7.0.0 tag in this repo](https://github.com/pytest-dev/pytest/tree/7.0.0) is not part of any branch:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
 7.0.0 

`git log --all --graph` reveals:

```
| | * commit 3554b833c24f541af5c7272e47cfa52b89d8138d (tag: 7.0.0, upstream/release-7.0.0, origin/pr/9598, refs/pullreqs/9598, release-7.0.0)
| | | Author: Florian Bruhin <me@the-compiler.org>
| | | Date:   Thu Feb 3 12:31:36 2022 +0100
| | | 
| | |     Add note to changelog
| | | 
| | * commit 6ea7f990a040cacfbc671a8c29f2d76533d9d523
| |/  Author: pytest bot <pytestbot@gmail.com>
|/|   Date:   Thu Feb 3 16:08:04 2022 +0000
| |   
| |       Prepare release version 7.0.0
```

but that was then [squash-merged](https://github.com/pytest-dev/pytest/commit/e37fbe5685d330cbe7819c5a08d0a524df7299bf), which means there is now a new commit which is not the tagged one...

This means that, for example, `git describe --abbrev=0 --tags` returns 7.0.0.dev0, causing a wrong author list in #9654. It's also somewhat questionable from a trust perspective....

So we might want to remove the tag, reapply it at e37fbe5685d330cbe7819c5a08d0a524df7299bf (same content, different commit) and finally change the release instructions to mention that the release PR should *not* be squash-merged?

**Comment by nicoddemus** [comment]
Ahh that explains it then.

Moving tags however is considered [bad practice](https://git-scm.com/docs/git-tag#_on_re_tagging). Perhaps the correct way would be to tag e37fbe5 as `7.0.0.post1` or something like that?

**Comment by nicoddemus** [comment]
> finally change the release instructions to mention that the release PR should not be squash-merged?

Oh definitely!

**Comment by bluetech** [comment]
:+1: to `7.0.0.post1`

**Comment by The-Compiler** [comment]
I suppose that would trigger a PyPI release though, potentially breaking things for people who pinned on `!= 7.0.0` now... Maybe easier to just live with it, and adjust the 7.0.1 author list by hand based on `git log e37fbe5..HEAD --format=%aN | sort | uniq | grep -vF '[bot]'` which is:

```
Anthony Sottile
Bruno Oliveira
Ran Benita
```

**Comment by bluetech** [comment]
Can just cancel the action real quick :)

**Comment by The-Compiler** [comment]
Tag pushed: https://github.com/pytest-dev/pytest/tree/7.0.0.post1

For some reason I don't quite understand, I don't seem to see an action running for it. Fingers crossed that we don't suddenly see a new PyPI release out of nowhere.

See #9657 for the docs change.
