### ISSUE TITLE
Pytest dies silently on missing stderr

### ISSUE THREAD

**Issue by ulfllorenz** [pytest-dev/pytest#9667]
The issue affects pytest 6.2.5 under Windows with python 3.9, but should still be present in the development version.

We have a situation here where we started pytest in a venv from git bash with "pytest.exe" and with "python -m pytest", where the former dies silently while the latter works. We could not reproduce this issue well enough to warrant a bug report (reproducible on my machine, not reproducible on another developer's machine), but as a side-effect and follow-up, we found debugging to be particularly slow because pytest died _silently_.

The request / fix would hence be to not to silently, but try to issue some useful result.

Somehow, pytest ends up being started with an invalid sys.stderr (== None). Under Windows, it tries `to _reopen_stdio()` with stderr as argument in `capture._py36_windowsconsoleio_workaround()`. And there it raises because None has no attributes. However, the exception is swallowed further up the stack trace and the end result is pytest dying silently. 

This issue should be reproducable using for example a git bash under Windows and running e.g. `pytest.exe 2>&-`  to explicitly remove stderr.

**Comment by AlexanderWells-diamond** [comment]
I may be encountering the same issue - intermittently, I just see an abrupt termination of pytest's output when run under CI. For example[see here](https://github.com/dls-controls/pythonSoftIOC/runs/5181053453?check_suite_focus=true), but extracting the important part:

```
D:\a\pythonSoftIOC\pythonSoftIOC\tests\test_record_values.py::TestNoneValue::test_value_none_rejected_initial_value[boolOut] PASSED [ 58%]::endgroup::Testing wheel...
  ...............................................................::error::Command python -m pytest D:\a\pythonSoftIOC\pythonSoftIOC/tests --cov-report xml:D:\a\pythonSoftIOC\pythonSoftIOC/dist/coverage.xml --junit-xml=D:\a\pythonSoftIOC\pythonSoftIOC/dist/pytest-results.xml failed with code 3221226505. None
```

It seems that the test finished running, reports its status, and then the process abruptly terminates. I know its possible that there was something trying to print to stderr after the test terminates - some modules are running background operations which can fail.

The `::endgroup::Testing wheel...` part is how `cibuildwheel` attempts to format its output with collapsibles in GitHub Actions. It  however that Pytest is terminating is screwing up the formatting somehow. 

Cursory googling suggests that `3221226505` is a Windows error code seems to mean little more than "Internal process error".

I've seen this on "windows-latest" containers with pytest 7.0.1, with Python 3.7 and 3.9. 

I tried using `--capture=tee-sys`, and so far on 10 re-runs I haven't re-encountered this issue, but it seems sufficiently intermittent that I'm not convinced that it's gone. My tests are also pretty noisy, thus making the test output very hard to read, so this isn't an ideal workaround.

**Comment by asottile** [comment]
the `sys.stderr=None` is caused by pip https://github.com/pypa/pip/issues/10875 -- @AlexanderWells-diamond your issue is separate, it sounds like your testsuite is segfaulting python

**Comment by asottile** [comment]
`sys.stderr` should never be `None` -- a bug in the launcher scripts created by the latest version of pip is causing that.  and when `sys.stderr` is None python *itself* doesn't display the stacktrace because there's no stderr to write it to (so nothing pytest can do)

**Comment by Chronial** [comment]
Oh, sorry, you are right. I got confused by `traceback.print_exc()` (which writes to stdout) working correctly. This is definitely not a pytest bug but expected python behavior.

**Comment by DBraun** [comment]
@asottile It seems that pip 22.0.4 was supposed to fix the issue you recently described, but I'm still encountering an issue. I use GitHub actions with a Windows runner with cibuildwheel and pytest with `python -m pytest {project}/tests`. On my local Windows computer, these tests all pass. On the runner, they pass, but then there's an error which I don't understand despite searching.

```
  ============================= 32 passed in 23.79s =============================
                                                             ✕ 86.09s
Error: Command python -m pytest D:\a\DawDreamer\DawDreamer/tests failed with code 3221226505. None
```

I've tried using Windows-2019 and Windows-2022 as the runners. I've tried forcing distlib to be 0.3.3. I've tried forcing pip to be 22.0.4 and 21.x. Perhaps something is going wrong with a test, but why isn't it bubbling up in a more transparent way? Also, the `None` at the end of the error might be related to sys.stderr?

**Comment by asottile** [comment]
**if you're getting any output than your problem is unrelated to the one reported here**

the most likely cause is your program is segfaulting ( try googling that exit code, Microsoft is usually pretty good about documenting the specific crash)

you'll need to fire up a Windows box and debug why that's happening (usually using the visual studio tooling, it's actually quite good) -- modern.ie has free VMs
