### ISSUE TITLE
Treating warnings as errors may interrupt teardown

### ISSUE THREAD

**Issue by PiotrBatko-BlockchainWares** [pytest-dev/pytest#9670]
## Description
Treating warnings as errors (e.g. with option `-W error`) may interrupt teardown. When warning is reported (with `warnings.warn`) during teardown, teardown is stopped. Teardown interruption is serious problem which leads to leak of resources (e.g. processes are not closed or temporary files are not deleted).

Expected behavior is teardown completion and then displaying warning message as error.

## Minimal example
```python
import warnings

import pytest


@pytest.fixture
def example_fixture():
    yield
    print('Teardown started')
    warnings.warn('Some warning')
    print('Teardown finished')


def test_teardown_bug(example_fixture):
    pass
```

Without `-W error`, teardown is fully executed correctly. (Note "Teardown finished" in output below).
```
$ pytest -s
======================================== test session starts ========================================
platform linux -- Python 3.8.12, pytest-7.0.0, pluggy-1.0.0
rootdir: /home/dev/Desktop/pytest-bug-reproduction
collected 1 item                                                                                    

test_teardown_bug.py .Teardown started
Teardown finished


========================================= warnings summary ==========================================
test_teardown_bug.py::test_teardown_bug
  /home/dev/Desktop/pytest-bug-reproduction/test_teardown_bug.py:10: UserWarning: Some warning
    warnings.warn('Some warning')

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================== 1 passed, 1 warning in 0.00s ====================================
```

When warnings are treated as errors, then teardown is interrupted. (Note that now "Teardown finished" is missing in output below).
```
$ pytest -s -W error
======================================== test session starts ========================================
platform linux -- Python 3.8.12, pytest-7.0.0, pluggy-1.0.0
rootdir: /home/dev/Desktop/pytest-bug-reproduction
collected 1 item                                                                                    

test_teardown_bug.py .Teardown started
E

============================================== ERRORS ===============================================
______________________________ ERROR at teardown of test_teardown_bug _______________________________

    @pytest.fixture
    def example_fixture():
        yield
        print('Teardown started')
>       warnings.warn('Some warning')
E       UserWarning: Some warning

test_teardown_bug.py:10: UserWarning
====================================== short test summary info ======================================
ERROR test_teardown_bug.py::test_teardown_bug - UserWarning: Some warning
==================================== 1 passed, 1 error in 0.01s =====================================
```

## Environment
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

$ python --version
Python 3.8.12

$ pytest --version
pytest 7.0.0

$ pip list
Package    Version
---------- -------
attrs      21.4.0
iniconfig  1.1.1
packaging  21.3
pip        22.0.3
pluggy     1.0.0
py         1.11.0
pyparsing  3.0.7
pytest     7.0.0
setuptools 56.0.0
tomli      2.0.1
```

**Comment by PiotrBatko-BlockchainWares** [comment]
Similar problem from the past. Maybe it will help to solve this issue:
https://github.com/pytest-dev/pytest/pull/5729

**Comment by nicoddemus** [comment]
Hi @PiotrBatko-BlockchainWares,

Thanks for the report. 

What happens when warnings are configured as errors, is that `warning.warn` itself raises an exception.

So `warnings.warn('Some warning')` in that context is the same as (for example) `raise RuntimeError`: it will stop the execution of the code in that function.

I'm not sure if pytest should make a special case of catching warnings as part of the teardown process (#5729 was a different problem, is it would break pytest entirely).

That's my two cents, interested on hearing what others think.

**Comment by RonnyPfannschmidt** [comment]
im under the  impression that pytest should gain a own extra mode to report warnins as errors after a testrun

imho `-W error` is actually a test antipattern as it breaks test cleanup and code under test just to record the  error later

i beleive we had a short discussion on that on twitter a few days back

**Comment by nicoddemus** [comment]
> im under the impression that pytest should gain a own extra mode to report warnins as errors after a testrun

Not sure this will bring its own set of problems though... warnings are already a pretty complex topic as is, adding another layer of complexity seems at first glance it might make matters worse. But that's just an eagle's eye view opinion.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus bascially test runners should be able to error out on warnings without making the code that triggers warnings fall off the world all over the place

we already can go yellow on warnings, we should have a opt in to go into the reds 

it needs a little design to make sense in integration

**Comment by asottile** [comment]
@RonnyPfannschmidt that's kinda a strawman too -- an api change which raises an exception would have the same problem

I don't think we should deviate from what python does here, and with proper context management (`finally` / `with`) this isn't really an issue

**Comment by RonnyPfannschmidt** [comment]
@asottile i stongly  disagree, actual api bugs indeed need workarounds,
actual warnings that in normal usage don't break things shouldnt break things under test either

**Comment by asottile** [comment]
then you don't want `-W error` -- that's saying "I don't have any warnings and I want the tank to blow off if it does"

**Comment by RonnyPfannschmidt** [comment]
@asottile the thing is - when the test runner doesnt allow safe warning errors asa feature, thats just the next best thing
however people use it like for a compiler when its in fact  a test run

**Comment by asottile** [comment]
yeah I think our major disagreement is that in your scenario it's "ok" to write non-exception-safe code

**Comment by RonnyPfannschmidt** [comment]
@asottile its a known fact that beginners make that mistake, and even experts do - and it reflects on a api/framework on whether bad choices of a user stay just bad or turn horrendous

**Comment by PiotrBatko-BlockchainWares** [comment]
I found in `warnings` documentation that `warnings.warn` may raise exception ([source](https://docs.python.org/3/library/warnings.html#warnings.warn)). I didn't know about it during writing code using `warnings.warn`, so my code is non-exception-safe as @asottile wrote. Pytest behavior is now completely understandable, but... :)

I used `-W error`, because my intention was to never miss emitted warnings. By default pytest reports at the end of tests, that tests are finished successfully with some warnings and returns 0. In real use cases -- on CI or in PyCharm -- such warnings are very hard to notice.

I know, that pytest records warnings, because prints information about them in tests summary. For described use case would be enough, if pytest will be able to return non-zero and report about errors instead of warnings. Then CI will be red and IDEs will be able to show that tests failed. It is completely different behavior than `-W error`, so should be handled by another flag, let's say `--treat-warnings-as-errors`, and should be recommended instead of `-W error` in documentation, because this behavior is what users expects. Complete code execution followed by report about warnings (as errors) instead of interruption in the middle. If user wants interruption, writes `raise` instead of `warn`.

**Comment by Zac-HD** [comment]
I think we have two separate things here.

1. Code where cleanup logic is not exception-safe (using e.g. `with` or `try`/`finally`) may be broken by `-Werror`.  IMO this is a non-problem: the bug is in user code, and being "helpful" about this trades off against predictable semantics for those who know (or are learning) Python.

2. A new proposed `--fail-on-warnings` configuration, which treats tests that emitted warnings as failed even if they didn't raise an exception.

I think the latter is complex enough that it should have a separate issue to answer design questions.  For example, what should the behaviour be in `-Wignore` mode?  Or with ignored-by-default `PendingDeprecationWarning`?  What about if you get a `ResourceWarning`, caused by a preceeding test but triggered by garbage collection?
