### ISSUE TITLE
How should we handle PEP-654 `ExceptionGroup`s containing pytest `XFailed` or `Skipped` exceptions?

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#9680]
[PEP-654 `ExceptionGroup`](https://www.python.org/dev/peps/pep-0654/) has shipped in the 3.11 alphas, and [there's an `exceptiongroup` backport on PyPI](https://pypi.org/project/exceptiongroup/).  We already have an issue about supporting the tracebacks (https://github.com/pytest-dev/pytest/issues/9159) and raising `ExceptionGroup` from our own code (https://github.com/pytest-dev/pytest/issues/8217).

But what happens if an `ExceptionGroup` is raised from test code, *and it contains a special Pytest exception?*  Worse, what if it contains *more than one kind* of special exception, i.e. the test is both skipped and xfailed?  e.g. 
```python
BaseExceptionGroup("msg", [ValueError(), Skipped(), XFailed()])
```

My proposal is that `XFailed` should be *dropped* from exception groups, since it represents a non-error case.  Then, if the remainder of the exception group contains a `Skipped` exception the test is skipped.  Otherwise, we treat it as an ordinary failure (with a fancier traceback).  Note that for efficiency reasons we might implement these checks in reverse order :wink: 

*(This is a pretty niche edge case to care about, but I just sat down to handle it in Hypothesis and quickly realized that it might depend on how the test runner handles the situation.)*

**Comment by The-Compiler** [comment]
Forgive my ignorance, but I wonder if/why pytest needs to handle those at all? I think it would be good if you could elaborate a bit about Hypothesis' use case there.

While `Skipped` and `XFailed` are *technically* reachable via public API (via `pytest.(skip|xfail).Exception`, see [usage in the wild](https://sourcegraph.com/search?q=context:global+pytest.%28skip%7Cxfail%29.Exception+-file:%28%5E%7C/%29pytest/testing+-repo:pytest-dev/pytest&patternType=regexp)), they seem to be [undocumented](https://docs.pytest.org/en/latest/reference/reference.html) - I'm thus inclined to say that pytest is safe to assume that code outside of pytest needs to at least accommodate for its internals. Therefor, it follows that pytest does not need to take care of this as long as it doesn't raise things that way.

**Comment by Zac-HD** [comment]
On considerably more reflection, and investigation how the ecosystem would look across Pytest, Hypothesis, and Unittest, I've concluded that we should *not* have any handling for `ExceptionGroup`s containing special marker exceptions.

- Frameworks or libraries like Hypothesis should be (and are) careful to raise marker exceptions directly.
- If user-supplied test code raises an ExceptionGroup, that's not a Skipped or XFailed exception.  It's also much safer to fail loudly when a skip/xfail was expected than vice-versa.
- It seems infeasible to coordinate the ecosystem on any other exact behavior.
