### ISSUE TITLE
only inner xfail mark is considered

### ISSUE THREAD

**Issue by dchudz** [pytest-dev/pytest#9684]
Not certain if this is a bug or a feature request, but it seems like it'd be nice for multiple xfail marks to be evaluated until we find one that allows the test to be xfailed.

If I do this:

```
@pytest.mark.xfail(raises=TypeError)
@pytest.mark.xfail(raises=ValueError)
def test_aaa():
    raise TypeError
```

... then the test fails with:

```
>       raise TypeError
E       TypeError
```

If I reverse the order of the xfail marks:

```
@pytest.mark.xfail(raises=ValueError)
@pytest.mark.xfail(raises=TypeError)
def test_aaa():
    raise TypeError
```

... then the test is xfailed, as I expect: 

```
test_xfail.py::test_aaa XFAIL
```

I expected that the order wouldn't matter, and that they would be evaluated until one of them applied to xfail the test.

This is a small example demonstrating the issue, but in real life I encountered this in a more complicated situation: I'm using `pytest_collection_modifyitems` to implement custom xfail markers via `item.add_marker(pytest.mark.xfail())`, depending on parameter values. Those custom markers didn't have any effect if the test also had a `@pytest.mark.xfail(raises=ValueError)`, because the xfail expecting a ValueError was applied first, and failed the test.

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

<details>
<summary>version and OS details</summary>

OS: MacOS 11.6
`pytest     7.0.1`

```
pip list
Package    Version
---------- ---------
attrs      21.4.0
certifi    2021.10.8
iniconfig  1.1.1
packaging  21.3
pip        21.2.4
pluggy     1.0.0
py         1.11.0
pyparsing  3.0.7
pytest     7.0.1
setuptools 58.0.4
tomli      2.0.1
wheel      0.37.1
```
</details>

**Comment by asottile** [comment]
a test can only fail with one exception so stacking two `raises=...` doesn't make sense

fortunately you can accomplish what you intend by joining the two `raises` ([as the docs mentions](https://docs.pytest.org/en/6.2.x/skipping.html#raises-parameter)):

```python
import pytest

@pytest.mark.xfail(raises=(ValueError, TypeError))
def test_aaa():
    raise ValueError()
```
