### ISSUE TITLE
Add support for extras in plugin entry points

### ISSUE THREAD

**Issue by GergelyKalmar** [pytest-dev/pytest#9685]
#### What's the problem this feature will solve?
It is not possible to create optional extras at the moment in a pytest plugin.

#### Describe the solution you'd like
I would like to be able to do something like this in one of my plugins:
```
...
    entry_points={'pytest11': [
        'my_plugin = plugin.something',
        'my_plugin_extra = plugin.something_extra [extra]',
    ]},
```
That is, the `my_plugin_extra` should only be loaded when the `extra` extra is installed, similarly to how console_entrypoints works (see https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies).

**Comment by GergelyKalmar** [comment]
That is an excellent point, I should probably open a ticket for it in https://github.com/python/importlib_metadata then, right? Is there any workaround that could possibly be implemented in the meantime? (I guess I could put the entire plugin.something_extra module into an import guard but that does not feel very elegant.)

**Comment by RonnyPfannschmidt** [comment]
A common solution is to register optional /tricky things in pytest_configure and /or the plugin_registred hook

**Comment by GergelyKalmar** [comment]
Thanks to your tip I figured I can just do:
```
def pytest_addhooks(pluginmanager):
    if not importlib.util.find_spec('extra_package'):
        pluginmanager.set_blocked('extra_plugin')
```
This blocks the plugin from being imported, which was causing the issue when the necessary extra packages weren't installed. I guess it is as elegant as it gets.
