### ISSUE TITLE
One test is changing variables inside another, causing it to fail

### ISSUE THREAD

**Issue by adamoppenheimer** [pytest-dev/pytest#9696]
DESCRIPTION
--------------
I am working on a Python package ([BipartitePandas](https://github.com/tlamadon/bipartitepandas)) that has many tests. I recently added a new test, and when I added it another test started failing even though nothing should have changed to cause it to fail.

When I comment out the new test, the other test starts passing again.

The test that is failing is `test_dataframe_1()`, while the new test that seems to be causing the issue is `test_fill_time_24_4()`. What made it clear to me that the tests are somehow interconnected is that `test_dataframe_1()` was failing with an error referencing a column `rs`, which doesn't exist in that test, but does exist in the test `test_fill_time_24_4()` (and that column exists ONLY in this specific test).

MWE
-----
If you clone the [BipartitePandas](https://github.com/tlamadon/bipartitepandas) repository and run pytest, `test_dataframe_1()` should fail, but if you comment out `test_fill_time_24_4()` then it should pass.

Unfortunately I have no clue what is causing this to happen so cannot give a simpler example that causes this issue.

PIP LIST
--------
alabaster                         0.7.12
anyio                             2.2.0
appnope                           0.1.2
argcomplete                       1.12.3
argon2-cffi                       20.1.0
async-generator                   1.10
attrs                             21.2.0
Babel                             2.9.1
backcall                          0.2.0
bleach                            4.0.0
Bottleneck                        1.3.2
brotlipy                          0.7.0
build                             0.7.0
certifi                           2021.10.8
cffi                              1.14.6
charset-normalizer                2.0.4
colorama                          0.4.4
cryptography                      35.0.0
cycler                            0.11.0
daal                              2021.5.0
daal4py                           2021.5.0
debugpy                           1.4.1
decorator                         5.1.0
defusedxml                        0.7.1
docutils                          0.17.1
entrypoints                       0.3
fonttools                         4.28.2
idna                              3.2
igraph                            0.9.8
imagesize                         1.2.0
importlib-metadata                4.8.1
iniconfig                         1.1.1
ipykernel                         6.4.1
ipython                           7.27.0
ipython-genutils                  0.2.0
jedi                              0.18.0
Jinja2                            3.0.1
joblib                            1.1.0
json5                             0.9.6
jsonschema                        3.2.0
jupyter-client                    7.0.1
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.8.1
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyter-server                    1.4.1
jupyterlab                        3.1.7
jupyterlab-pygments               0.1.2
jupyterlab-server                 2.8.2
keyring                           23.2.1
kiwisolver                        1.3.2
line-profiler                     3.4.0
lxml                              4.6.5
MarkupSafe                        2.0.1
matplotlib                        3.5.0
matplotlib-inline                 0.1.2
mistune                           0.8.4
mkl-fft                           1.3.1
mkl-random                        1.2.2
mkl-service                       2.4.0
more-itertools                    8.10.0
nbclassic                         0.2.6
nbclient                          0.5.3
nbconvert                         6.1.0
nbformat                          5.1.3
nbsphinx                          0.8.7
nest-asyncio                      1.5.1
networkx                          2.6.3
notebook                          6.4.5
numexpr                           2.7.3
numpy                             1.21.2
packaging                         21.0
pandas                            1.3.3
pandocfilters                     1.4.3
parso                             0.8.2
patsy                             0.5.2
pep517                            0.12.0
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            8.4.0
pip                               22.0.3
pkginfo                           1.7.1
pluggy                            0.13.1
prometheus-client                 0.11.0
prompt-toolkit                    3.0.20
ptyprocess                        0.7.0
py                                1.10.0
pyamg                             4.1.0
pyarrow                           6.0.0
pybind11                          2.7.0
pycparser                         2.20
Pygments                          2.10.0
pyOpenSSL                         21.0.0
pyparsing                         2.4.7
pyrsistent                        0.17.3
PySocks                           1.7.1
pytest                            7.0.1
python-dateutil                   2.8.2
pytz                              2021.3
PyYAML                            6.0
pyzmq                             22.2.1
qpsolvers                         1.7.2
quadprog                          0.1.11
readme-renderer                   30.0
requests                          2.26.0
requests-toolbelt                 0.9.1
rfc3986                           1.5.0
scikit-learn                      1.0.1
scikit-learn-intelex              2021.5.0
scipy                             1.7.1
seaborn                           0.11.2
Send2Trash                        1.8.0
setuptools                        58.0.4
setuptools-scm                    6.3.2
six                               1.16.0
sniffio                           1.2.0
snowballstemmer                   2.1.0
Sphinx                            4.2.0
sphinx-rtd-theme                  1.0.0
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.5
statsmodels                       0.13.0
tbb                               2021.5.0
terminado                         0.9.4
testpath                          0.5.0
texttable                         1.6.4
threadpoolctl                     2.2.0
toml                              0.10.2
tomli                             1.2.2
tornado                           6.1
tqdm                              4.62.3
traitlets                         5.1.0
twine                             3.4.2
typing-extensions                 3.10.0.2
urllib3                           1.26.7
wcwidth                           0.2.5
webencodings                      0.5.1
wheel                             0.37.0
zipp                              3.6.0

PYTEST VERSION
------------------
pytest 7.0.1

OS
---
MacOS 10.15.7

**Comment by nicoddemus** [comment]
Hi @adamoppenheimer,

From your description it seems this is a problem with the test suite: some test is changing some global state which is affecting other tests. There's nothing related to pytest or something pytest can do here.

**Comment by adamoppenheimer** [comment]
I apologize, it was actually an issue related this [this](https://stackoverflow.com/a/54781084/17333120).

As you said, the issue did not have to do with pytest. Thank you for the quick response.
