### ISSUE TITLE
Rename internal "warnings" in the terminal output to "pytest-warnings"

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#970]
Currently when the a suite contains internal warnings (such as classes starting with "Test" but containing a `__init__` method) produce output like this:

```
=== 50 passed, 2 warnings in 24.72 seconds ===
```

In my experience, this is confusing for most users when they first see this, as they think the test suite is producing warnings from the builtin `warnings` module.

How about if we rename "warnings" to "pytest-warnings"? 

```
=== 50 passed, 2 pytest-warnings in 24.72 seconds ===
```

I think most users will immediately understand that the warnings are related to pytest, and not from their code.

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Comment by The-Compiler** [comment]
FWIW, :+1: from me as well

**Comment by alfredodeza** [comment]
I came here trying to find about "pytest-warnings" which were throwing me off. I've never seen those and something like a one line saying: "N pytest-warnings found, to get a report use $flags"

**Comment by bhearsum** [comment]
For what it's worth, "pytest-warnings" doesn't help make this more obvious for me. I'm running my own unit tests, so when I see something that says "warning" and turns yellow, I immediately blame my code. I think it would be really helpful if anything that caused an internal warning or error provided some output by default. After passing -rw I end up with a message like:
WI9 None could not create cache path /home/bhearsum/repos/master/balrog/.cache/v/cache/lastfailed

...which makes it immediately obvious that it's not an issue with my code.

**Comment by nicoddemus** [comment]
@bhearsum I agree... I'm thinking that ideally `pytest-warnings` should only be shown if they were generated by the code under test. It is not helpful at all to display pytest-warnings for plugins (for example), as this is outside the user's control.

**Comment by njsmith** [comment]
I also ended up here after spending a few baffled minutes trying to figure out why my results were yellow and trying every mechanism I knew for coaxing more output out of pytest (`-v`, `-s`, etc.), all of which failed.

**Comment by ssbarnea** [comment]
Any plans to fix this annoying issue? I really hate adding confusion to anyone that is trying to read the logs.

**Comment by RonnyPfannschmidt** [comment]
@ssbarnea this is fixed since last year and is released since a while

**Comment by nicoddemus** [comment]
@ssbarnea in pytest-3.0 now the warnings are displayed by default.

**Comment by The-Compiler** [comment]
@ssbarnea Note that you can pass `-rw` to pytest (< 3.0) to show the warning.
