### ISSUE TITLE
`pytest --collect-only --quiet` output is not "machine readable"

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#9704]
#### What's the problem this feature will solve?

I would like to programmatically collect the list of test ids from pytest.

current `pytest --collect-only --quiet` gets close, but has some non-machine-readable output at the end which is not desirable.

```console
$ pytest --collect-only --quiet tests | tail -5
tests/astpretty_test.py::test_typedast_support_cmdline_27
tests/astpretty_test.py::test_typedast_support_cmdline_3
tests/astpretty_test.py::test_pformat_py38_type_comments

28 tests collected in 0.02s
```

#### Describe the solution you'd like

I would like to add either a `--json` output to this so it can be machine-parsed. perhaps a structure like:

```console
$ pytest --collect-only --json
{
    "testids": [
        "...",
        "...",
        "..."
    ]
}
```

#### Alternative Solutions

I could write a plugin, but...

#### Additional context

I'm writing a tool to detect test pollution automatically.  also I suspect this would be useful for those attempting to distribute tests by id across runners -- for instance [pytest-select](https://pypi.org/project/pytest-select/)

**Comment by pared** [comment]
I have a similar problem: I would expect that providing `-q` option would result in displaying only the absolutely necessary info and in the case of `--collect-only` that (seemingly) would be the list of tests.

Inspecting the code I noticed that decreasing the verbosity might help:
https://github.com/pytest-dev/pytest/blob/00ad12b9db8d3309c361061fe1c4878b2e0cd51c/src/_pytest/terminal.py#L1036-L1038

So, I tried doing that and for the following sample repo:

```bash
#!/bin/bash

mkdir tests
echo -e "def test_very_important():
    assert 1+1 == 2
" > tests/test_something.py
```

I tried running with `-q` and `-qq`. Here are the results:

```bash
$ pytest --collect-only -q                                                                               
tests/test_something.py::test_very_important

1 test collected in 0.00s
```

```bash
$ pytest --collect-only -qq                                                                                 
tests/test_something.py: 1

```

My question is: is this behavior expected? Is there a way to get just 
```bash
tests/test_something.py::test_very_important
```
?

If it would be expected to display only the list of tests in one of the cases, I am willing to prepare a fix. I would appreciate some context thought, because I am not sure in which case should it be.

**Comment by elbehery95** [comment]
> I would like to programmatically collect the list of test ids from pytest.

I believe there are many ways to do this E.g.

Shell approach:

```sh
pytest --collect-only -q tests/test_hello.py | head -n -2 | python -c 'import sys; tests=[i.strip() for i in sys.stdin.readlines()]; print(tests)'
```

Python approach:

```python
import pytest

class MyCollectionPlugin:
  def __init__(self):
    self.tests = []
  def pytest_report_collectionfinish(self, items):
    self.tests = [item.nodeid for item in items]


if __name__ == "__main__":
  p = MyCollectionPlugin()
  pytest.main(["--collect-only"], plugins=[p])
  print(p.tests)
  # generate_json_from_items_nodeid_list(p.tests)
```

**Comment by RonnyPfannschmidt** [comment]
@asottile i tihnk this may be a nice chance to introduce some type of jsonlines based output for pytest that is similar to report log, but adds extras that other ux tools might be able to use

**Comment by asottile** [comment]
@elbehery95 `head -2` and `strip` are both hacks indicating that there is **not structured output** which is entirely what this issue is asking for -- you'll note that the original issue shows exactly the command you're using and doesn't help

adding a plugin of course makes this possible but the ask is for pytest to do this itself

**Comment by nicoddemus** [comment]
The idea of `pytest-reportlog` was to have it mature outside of the core, but to be eventually be merged, so I think this in line with the plans regarding it. 👍

**Comment by The-Compiler** [comment]
I'm all for extending `pytest-reportlog` to allow for this (and then perhaps adding it to the core at some point) rather than adding yet another JSON output format.

**Comment by pared** [comment]
Should we create the issue in `pytest-reportlog` repository? I tried playing around with it in my current setup and it produces nice, machine-readable output, though I am not sure I understand what needs to be implemented there to solve the current issue. What would be an expected output while using `--report-log`? Are we talking here that in case of no `FILE` provided, the output gets written into the `stdout`?

**Comment by jgarte** [comment]
Hi,

What's the status on this? A `--json` flag would be useful for me as well as I'm trying to implement a `consult-pytest` like package for Emacs. Having this could clean up the code on my side.

**Comment by ssbarnea** [comment]
While I usually encourage the use of plugins for enhancing pytest, I do still think that collection is a core feature that should have a machine parseable output, with a json output mode. This would be needed for integration with various tools and various tools would not be able to rely on presence of an extra plugin to integrate with pytest.

I would vote to reopen it. Any thumbs up/down please?

PS. The mentioned plugin cannot be used for collection as it does report only the collected files and not the tests, already tried it.

**Comment by ThermodynamicBeta** [comment]
Yeah this is pretty ridiculous, json output mode would be great
