### ISSUE TITLE
Document pytester plugin

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#971]
Create documentation on how to use the `pytester` plugin. 

It is an invaluable tool for plugin authors, so describing the high level API and linking it from `writing_plugins` would be a nice addition to the documentation.

**Comment by The-Compiler** [comment]
The page on writing plugins already has a [testing plugins](http://pytest.org/latest/writing_plugins.html#testing-plugins) section which at least mentions the basics of `testdir` - but I agree a full API documentation would be nice.

**Comment by nicoddemus** [comment]
Completely forgot about that. :sweat_smile:
