### ISSUE TITLE
--doctest-modules for native extensions

### ISSUE THREAD

**Issue by kevinheavey** [pytest-dev/pytest#9711]
Currently `pytest --doctest-modules` does not pick up native extension modules (those written in C, Rust etc). This was raised several years ago but closed because the author made a plugin for Cython only https://github.com/pytest-dev/pytest/issues/1498.

I don't know what docstring conventions people use for C or C++, but I do know people are writing Python libraries using Rust ([example](https://github.com/kevinheavey/pyheck/)) and the objects from these modules can have `__doc__` attributes.

Currently I can test the docstrings in such modules by setting up Sphinx docs and using Sphinx's `make doctest` command, but I would prefer not to use Sphinx at all.

Would support for native module doctests be in scope for Pytest? Speaking naively, I think it would be a matter of importing the module, checking the `__doc__` attribute of every member and running any doctest-style examples that are found.

**Comment by nicoddemus** [comment]
> Would support for native module doctests be in scope for Pytest?

I would say no, but perhaps in the scope of https://github.com/astropy/pytest-doctestplus? You could ask there and see what the developers have to say.

**Comment by kevinheavey** [comment]
Yeah it's an awkward issue that doesn't exactly fit in any project. 

I'm now thinking: what if pytest didn't try and extract docstrings from compiled extensions, but was at least able to test a list of docstrings (passed as regular strings) that were fetched by some other tool?

**Comment by nicoddemus** [comment]
> , but was at least able to test a list of docstrings (passed as regular strings) that were fetched by some other tool?

That is already possible today, it can extract doctests snippets off `.rst` files.

**Comment by kevinheavey** [comment]
> > , but was at least able to test a list of docstrings (passed as regular strings) that were fetched by some other tool?
> 
> 
> 
> That is already possible today, it can extract doctests snippets off `.rst` files.

So the idea would be to get the docstrings from the compiled extension, spit them out to a temporary .rst file and use pytest on that .rst?

**Comment by kevinheavey** [comment]
Yeah I'll try that and report back on how well it works

**Comment by nicoddemus** [comment]
Nice thanks!

Closing this for now then. 👍
