### ISSUE TITLE
allow fixture use in @pytest.mark.parametrize

### ISSUE THREAD

**Issue by ChristianF88** [pytest-dev/pytest#9715]
#### What's the problem this feature will solve?

_I am trying to pass a fixture (let's call it **make_parameter_list**) to pytest.mark.parametrize. The fixture **make_parameter_list** I am trying to pass depends on multiple other fixtures and will create a list of parameters to run a test on._ 

#### Describe the solution you'd like

_I need fixture **make_parameter_list** to be run before pytest.mark.parametrize, so that the parameters I want to test on are ready when pytest.mark.parametrize is evaluated._

#### Alternative Solutions

_Alternatively one could register a global variable via a fixture. But then I am unsure about how I could register the variable before the test parameterization is run._

#### Additional context

_Example feature wish:_
```python
import pytest

@pytest.fixture
def create_parameter_list(other, fixtures, here):
    parameter_list = [...]
    return parameter_list

@pytest.mark.parametrize("para", create_parameter_list)
def test_with_parameters_from_fixture(para):
    assert ...
```

_Example alternative:_
```python
import pytest

def pytest_namespace():
    return {'test_parameters': []}

@pytest.fixture
def create_parameter_list(other, fixtures, here):
    parameter_list = [...]
    pytest.test_parameters = parameter_list

#! But how to register global? !#

@pytest.mark.parametrize("para", pytest.test_parameters)
def test_with_parameters_from_fixture(para):
    assert ...
```

**Comment by nicoddemus** [comment]
@ChristianF88 currently that's not possible using plain pytest, but you can try [`pytest-lazy-fixture`](https://pypi.org/project/pytest-lazy-fixture/).

Closing for now, feel free to follow with further questions. 👍

**Comment by brandon-leapyear** [comment]
@nicoddemus do you know if there's a corresponding issue to this proposal: https://docs.pytest.org/en/6.2.x/proposals/parametrize_with_fixtures.html?

**Comment by nicoddemus** [comment]
Not from the top of my head (no time to search now too I'm afraid!)
