### ISSUE TITLE
tag the beginning of the 2.8 series with 2.8.0.dev to help setuptools_scm

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#972]
setuptools_scm currently thinks we are working on 2.7.3.dev* due to the lack of a tag signifying the start of the 2.8.0 series

**Comment by nicoddemus** [comment]
This requires a **git** tag?

**Comment by RonnyPfannschmidt** [comment]
exactly

**Comment by untitaker** [comment]
Not sure on which commit you would set such a tag until 2.8.0 is out.

On 27 August 2015 20:16:33 CEST, Ronny Pfannschmidt <notifications@github.com> wrote:
>exactly
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pytest-dev/pytest/issues/972#issuecomment-135512251

-- 
Sent from my phone. Please excuse my brevity.

**Comment by RonnyPfannschmidt** [comment]
@untitaker the .dev signifies that its not a final release, but leading up to a release instad

**Comment by hpk42** [comment]
i did ``git tag -a -m "2.8.0.dev" 2.8.0.dev 74019025b96502e16ce552b48b81a21fda976f58`` but it doesn't cause master to have a 2.8.0.devX tag.  probably doing something wrong?

**Comment by RonnyPfannschmidt** [comment]
@hpk42 afterwards you need to push the tag as well, git tags are detached from history and need to be communicated explicitly

**Comment by RonnyPfannschmidt** [comment]
this one no longer applies
