### ISSUE TITLE
Some code improvements

### ISSUE THREAD

**Issue by m0nk3ybraindead** [pytest-dev/pytest#9722]
#### What's the problem this feature will solve?

The code looks somewhat bad...
1. Importing in multiple lines [this](https://github.com/pytest-dev/pytest/blob/e466a87bb082ea5f7377f84038322e9bc8fba789/src/_pytest/main.py#L9)
1. Unpacking badly [this]()
1. Importing in the middle of the file [this](https://github.com/pytest-dev/pytest/blob/e466a87bb082ea5f7377f84038322e9bc8fba789/src/_pytest/config/__init__.py#L950) without context why is it there

#### Describe the solution you'd like

We can just improve this by rewriting

#### Alternative Solutions

1. Don't. If it's not broken don't fix it
1. Use Black, Isort and flake8

#### Additional context

None

**Comment by RonnyPfannschmidt** [comment]
Closing as unproductive / badly communicated

1. Is intentionally done by reorder-imports in pre-commit
2. Is missing the actual link
3. Looks like avoiding a import loop

In case 2/3 are fixable, im happy to approve a reasonable pr with the fix
