### ISSUE TITLE
Documentation removed

### ISSUE THREAD

**Issue by PhilippSelenium** [pytest-dev/pytest#9763]
Why was the documentation for https://docs.pytest.org/en/7.0.x/objects.inv' removed?

**Comment by The-Compiler** [comment]
We usually only keep documentation around for the most recent major versions (currently, 7.1.x, 6.2.x and 4.6.x). Can you elaborate how you need it, and why you can't use the 7.1.x version there? Hmm, or do we accidentally break all links to the old doc by doing this? That'd be rather bad...

**Comment by PhilippSelenium** [comment]
@The-Compiler Thanks for the fast reply.

I came across that because it lead to a failure in our CI sphinx build, since sphinx could not find the link to 7.0.x anymore

We usually reference a fixed version so the CI does not break on updates (referencing stable would brake for every major update) of pytest but in that case every minor update will brake our CI setup. 

Note: So currently stable and 7.1x would link to the same documentation?

**Comment by The-Compiler** [comment]
> Note: So currently stable and 7.1x would link to the same documentation?

I would expect them to, given that `stable` [should always link to the newest release](https://docs.readthedocs.io/en/stable/versions.html#states).

The reason we switched to branches for the default RTD version is that we want to be able to push doc/website updates without having to wait for a new release. This looks like it's a bit more manual work, though...

Maybe we should just keep around old versions on RTD for a longer time, to avoid breaking links? Or we could add a redirect for every release?

**Comment by PhilippSelenium** [comment]
Thanks (y)
