### ISSUE TITLE
Duplicate tests for placing brackets at the end of a command line

### ISSUE THREAD

**Issue by Drako2711** [pytest-dev/pytest#9773]
### Discussed in https://github.com/pytest-dev/pytest/discussions/9772

<div type='discussions-op-text'>

<sup>Originally posted by **Drako2711** March 15, 2022</sup>
Hi, I am using the pytest command:
`python3 -m pytest LoginTest.py --alluredir ./results `
Console:
```
platform win32 -- Python 3.9.10, pytest-7.0.1, pluggy-1.0.0
rootdir: D:\PROYECTOS\SELENIUM\Pruebas
plugins: allure-pytest-2.9.45
collected 7 items
```
to go through the tests in my file, but when I add square brackets the items found are duplicated, for example from 7 it goes to 14, and so on.
This is the command, even if I leave the square brackets empty, it duplicates the same, has anyone else had this happen?
`python3 -m pytest PurchaseTest.py --alluredir ./results [var]`
Console:
```
platform win32 -- Python 3.9.10, pytest-7.0.1, pluggy-1.0.0
rootdir: D:\PROYECTOS\SELENIUM\Pruebas
plugins: allure-pytest-2.9.45
collected 14 items
```</div>

**Comment by Zac-HD** [comment]
Closing as stale; maybe try StackOverflow?  (also possible that it's a shell issue, treating `[` and `]` as special characters)
