### ISSUE TITLE
locals' values are still truncated even if -vv is in adopts in pytest.ini?

### ISSUE THREAD

**Issue by bubenkoff** [pytest-dev/pytest#980]
Not sure how it's supposed to work exactly, but at the moment it looks like there's no way to see full values of locals even though -vvl argument is passed.
Am i missing something?

**Comment by RonnyPfannschmidt** [comment]
-l perhaps?

**Comment by bubenkoff** [comment]
sorry forgot to add l to what i pass already - just did
still the question remains

**Comment by RonnyPfannschmidt** [comment]
Then its a py.code issue and we should fix it after the move

**Comment by bubenkoff** [comment]
thanks

**Comment by NorthIsUp** [comment]
Just started bumping into this issue. Are there any updates on the current status?

**Comment by nicoddemus** [comment]
No progress, but thanks for the bump anyway. PRs are welcome!

**Comment by smurfix** [comment]
I propose to use "standard" pretty printing instead, at high verbosity levels.

**Comment by tadeoos** [comment]
I'd like to try and help out with this but since pytest has an impressive codebase maybe someone could point me to the module wherein prinitng out of locals is implemented?

**Comment by tadeoos** [comment]
ok, i found `FormattedExcinfo` class in `code.py`. I guess that's where I should start digging. Is there a way to check the verbosity parameter from inside this class?

**Comment by nicoddemus** [comment]
Hi @tadeoos, thanks for offering to help out!

`FormattedExcinfo` is created here:

https://github.com/pytest-dev/pytest/blob/0565a7a4e13bb6d2bdded30c09d023322948c45c/src/_pytest/_code/code.py#L469-L476

Which is called from here:

https://github.com/pytest-dev/pytest/blob/0565a7a4e13bb6d2bdded30c09d023322948c45c/src/_pytest/nodes.py#L290-L296

And `Node` has access to the config object.

At this point I think the best approach is to add a new `truncate_locals=False` parameter to `ExceptionInfo.getrepr` and `FormattedExcinfo`, which would be the current behavior. When using `-vv`, we should then pass `truncate_locals=True`.

Hope this helps, feel free to open a PR with some WIP and we can go from there. 👍

**Comment by tadeoos** [comment]
Thanks for help! 
One question: shouldn't the defaults be the other way around? Current behavior is that locals get truncated, so I would make `True` the default parameter for `truncate_locals`, right?

**Comment by nicoddemus** [comment]
Oh definitely, sorry about the brain fart! 😁

**Comment by tadeoos** [comment]
@nicoddemus no worries :) I've made a PR, for `truncate_locals=False` I simply used `pprint.pformat` as @smurfix suggested above.

**Comment by nicoddemus** [comment]
Fixed in #3681
