### ISSUE TITLE
pytest-7.1.1 pytest-metadata not works

### ISSUE THREAD

**Issue by treussart** [pytest-dev/pytest#9809]
When I upgraded pytest 7.1.0 to pytest 7.1.1, the pytest-metadata plugin is not called.

With pytest 7.1.1
`pytest --verbose --html=report.html --self-contained-html`

Do not display on the console and in the HTML report the Environment section.

and if I write this for example, _metadata does not exists and throw an INTERNAL_ERROR :

```
def pytest_configure(config: Config):
    config._metadata["Date_UTC"] = str(datetime.datetime.now(pytz.utc))
```

**Comment by headtr1ck** [comment]
Same problem as https://github.com/pytest-dev/pytest-html/issues/506
Since you closed this issue, could you solve the problem?

**Comment by BeyondEvil** [comment]
This is likely due to an issue in pytest-metadata 2.0.0. 

2.0.1 was just release, please try that. If it still doesn't work, please report the issue in the `pytest-metadata` repo. Thanks.

**Comment by headtr1ck** [comment]
updating to `pytest-metadata==2.0.1` worked, thanks.
