### ISSUE TITLE
Custom plugin not loading when --basetemp is set to a subdirectory within code repo

### ISSUE THREAD

**Issue by felipemoran** [pytest-dev/pytest#9819]
It seems that pytest fails to load the plugin I'm developing when I point --basetemp to a directory within my repo.

My repo is structured as follow:
```
repo_root\
    src\
       my_plugin\
          ...
          plugin.py <- pytest entrypoint
    tests\
        ...
    setup.py
    setup.cfg
    ...
```

Since I'm using a `src/` structure for the code, the plugin must first be packaged and installed (manually or with tox for example) before being used. Installing with `pip install -e .` works as well.

When I run `pytest` without extra cli arguments it works fine. If I do `pytest --basetemp='tmp'`, which should create and use a directory named `tmp` under `repo_root`, it fails. Running `pytest --basetemp=/tmp`, which creates a directory under the system root instead of the repo root, works fine.

**Comment by Zac-HD** [comment]
What specifically happens when it fails?  Without a repro or much more detail about the failure, it's almost impossible for anyone to help.

**Comment by Zac-HD** [comment]
Closing because we don't have the needed information to resolve this, happy to reopen if that changes 😕
