### ISSUE TITLE
Utilities to create temporary file hierarchies

### ISSUE THREAD

**Issue by kalekundert** [pytest-dev/pytest#9829]
Pretty much every test function that uses `tmp_path` starts by filling in that directory with whatever files are needed for the test.   Furthermore, the code to do this often accounts for a substantial fraction of the test (e.g. half the lines or more).  I've linked two good examples below, but there are many many more:

- [aio-libs/aiohttp/.../test_web_urldispatcher.py](https://github.com/aio-libs/aiohttp/blob/master/tests/test_web_urldispatcher.py)
  ```python
  @pytest.mark.parametrize(...)
  async def test_access_root_of_static_handler(
      tmp_path: Any,
      aiohttp_client: Any,
      show_index: Any,
      status: Any,
      prefix: Any,
      data: Any,
  ) -> None:
      # Tests the operation of static file server.
      # Try to access the root of static file server, and make
      # sure that correct HTTP statuses are returned depending if we directory
      # index should be shown or not.
      my_file = tmp_path / "my_file"
      my_dir = tmp_path / "my_dir"
      my_dir.mkdir()
      my_file_in_dir = my_dir / "my_file_in_dir"

      with my_file.open("w") as fw:
          fw.write("hello")

      with my_file_in_dir.open("w") as fw:
          fw.write("world")

      app = web.Application()

      # Register global static route:
      app.router.add_static(prefix, str(tmp_path), show_index=show_index)
      client = await aiohttp_client(app)

      # Request the root of the static directory.
      r = await client.get(prefix)
      assert r.status == status

      if data:
          assert r.headers["Content-Type"] == "text/html; charset=utf-8"
          read_ = await r.read()
          assert read_ == data
  ```
  - 8 lines to setup the temporary directory.
  - 9 lines to actually do the tests.
- [pytest-dev/pytest/.../test_findpaths.py](https://github.com/pytest-dev/pytest/blob/main/testing/test_findpaths.py):
  ```python
  class TestCommonAncestor:
      def test_has_ancestor(self, tmp_path: Path) -> None:
          fn1 = tmp_path / "foo" / "bar" / "test_1.py"
          fn1.parent.mkdir(parents=True)
          fn1.touch()
          fn2 = tmp_path / "foo" / "zaz" / "test_2.py"
          fn2.parent.mkdir(parents=True)
          fn2.touch()
          assert get_common_ancestor([fn1, fn2]) == tmp_path / "foo"
          assert get_common_ancestor([fn1.parent, fn2]) == tmp_path / "foo"
          assert get_common_ancestor([fn1.parent, fn2.parent]) == tmp_path / "foo"
          assert get_common_ancestor([fn1, fn2.parent]) == tmp_path / "foo"
  ```
  - 6 lines to setup the temporary directory.
  - 4 lines to actually do the tests.

I think it would make sense for pytest to include some utilities to simplify this process.  Specifically, my proposal is to (i) provide a stand-alone function that can create a file hierarchy specified by a dictionary and (ii) have `tmp_path` automatically invoke this function when indirectly parametrized.  The keys of this dictionary would be file paths.  The values would either be file contents (as a string), or a more complete description of the file type/mode/contents/etc (as a dict). For example, here's a dictionary representing the file hierarchy from the `aio-libs/aiohttp` test:
```python
{'my_file': 'hello', 'my_dir/my_file_in_dir': 'world'}
```
Here's a more complicated example, with a symlink and an executable script:
```python
{
  'greeting.txt': 'hello world',
  'greeting.lnk': {
    'type': 'symlink',
    'target': 'greeting.txt',
  },
  'greeting.sh': {
    'mode': 'rwxr--r--',
    'contents': '''\
#!/usr/bin/env sh
cat greeting.lnk
''',
  },
}
```
Here's the `aio-libs/aiohttp` test, rewritten to use the proposed indirect parametrization.  Note that the test code is fully devoted to the actual test now.  Even better, the tests aren't forced to share the same temporary directory structure anymore:
```python
@pytest.mark.parametrize(
    "tmp_path,show_index,status,prefix,data",
    [
        pytest.param({}, False, 403, "/", None, id="index_forbidden"),
        pytest.param(
            {'my_file': 'hello', 'my_dir/my_file_in_dir': 'world'},
            True,
            200,
            "/",
            b"<html>\n<head>\n<title>Index of /.</title>\n"
            b"</head>\n<body>\n<h1>Index of /.</h1>\n<ul>\n"
            b'<li><a href="/my_dir">my_dir/</a></li>\n'
            b'<li><a href="/my_file">my_file</a></li>\n'
            b"</ul>\n</body>\n</html>",
            id="index_root",
        ),
        pytest.param(
            {'my_file': 'hello', 'my_dir/my_file_in_dir': 'world'},
            True,
            200,
            "/static",
            b"<html>\n<head>\n<title>Index of /.</title>\n"
            b"</head>\n<body>\n<h1>Index of /.</h1>\n<ul>\n"
            b'<li><a href="/static/my_dir">my_dir/</a></li>\n'
            b'<li><a href="/static/my_file">my_file</a></li>\n'
            b"</ul>\n</body>\n</html>",
            id="index_static",
        ),
    ],
    indirect=['tmp_path'],
)
async def test_access_root_of_static_handler(
    tmp_path: Any,
    aiohttp_client: Any,
    show_index: Any,
    status: Any,
    prefix: Any,
    data: Any,
) -> None:
    # Tests the operation of static file server.
    # Try to access the root of static file server, and make
    # sure that correct HTTP statuses are returned depending if we directory
    # index should be shown or not.

    # Register global static route:
    app.router.add_static(prefix, str(tmp_path), show_index=show_index)
    client = await aiohttp_client(app)

    # Request the root of the static directory.
    r = await client.get(prefix)
    assert r.status == status

    if data:
        assert r.headers["Content-Type"] == "text/html; charset=utf-8"
        read_ = await r.read()
        assert read_ == data
```

I've found utilities like these to be very useful in my own projects.  If there's interest in adding something like this to pytest, I'd be happy to make a PR.

**Comment by RonnyPfannschmidt** [comment]
The utilities should evolve in a separate library for a while

**Comment by Zac-HD** [comment]
Yes, I'd consider adopting such utilities after they'd been written, tested, and used in the wild for a while, but this is too complex to bet on getting it right on the first attempt when we have backwards-compatibility constraints.  

Closing for now, but I encourage you to write up the helper functions that you'd like to see - and publish them on PyPI!

**Comment by kalekundert** [comment]
That makes sense.  If anyone is interested, here's a link to an implementation of the features described here:

https://pypi.org/project/pytest_tmp_files/
https://github.com/kalekundert/pytest_tmp_files

Feedback is welcome!
