### ISSUE TITLE
Feature request: pytest.match for regex-base equality-checking a la pytest.approx

### ISSUE THREAD

**Issue by DrewDevereux** [pytest-dev/pytest#9861]
One thing I really love about `pytest.approx` is that it means that I can do all equality checking the same way, regardless of whether it is approximate or exact. That is, I can do stuff like this:
```
@pytest.mark.parametrize(
    ("attribute", "expected_value"),
    [
        ("foo", 1),
        ("bah", pytest.approx(3.0)),
    ]
)
def test_attributes(object_under_test):
    assert getattr(object_under_test, attribute) == expected_value
```
I don't need separate tests for strict equality checking and approximate equality checking.

By the same token it would be great to have a `pytest.match` method that similarly reduces string matching to an equality check. This would let me
```
@pytest.mark.parametrize(
    ("attribute", "expected_value"),
    [
        ("foo", 1),
        ("bah", pytest.approx(3.0)),
        ("url", pytest.match(url_regex))
    ]
)
def test_attributes(object_under_test):
    assert getattr(object_under_test, attribute) == expected_value
```

**Comment by kalekundert** [comment]
FYI, you can already get this behavior using the `re_assert` package:
https://github.com/asottile/re-assert

**Comment by DrewDevereux** [comment]
Thanks Kale!

**Comment by Zac-HD** [comment]
I think the best way to address this is for the documentation for `pytest.approx()` to include a link to the `re_assert` package.
