### ISSUE TITLE
Proposal: revisit folding skipped tests in summary

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#9876]
Currently we "fold" skipped tests in the summary:

```
===================================== short test summary info =====================================
SKIPPED [1] .tmp\test_summary_1.py:20: not available on this platform
SKIPPED [1] .tmp\test_summary_1.py:35: not available on this platform
XFAIL .tmp\test_summary_1.py::test_mem_crash
  reason: quarantine due to crashes
XPASS .tmp\test_summary_1.py::test_mem_crash_new
FAILED .tmp\test_summary_1.py::TestSimple::test_name - NameError: name 'name' is not defined
FAILED .tmp\test_summary_1.py::test_boolean_ops - assert False is True
PASSED .tmp\test_summary_1.py::TestSimple::test_passes
PASSED .tmp\test_summary_1.py::TestSimple::test_passes1
PASSED .tmp\test_summary_1.py::test_passes_non_critical
================== 2 failed, 3 passed, 2 skipped, 1 xfailed, 1 xpassed in 0.09s ===================
```

They are the only entries which don't show the node id, showing the file name and line number instead, and also try to fold/accumulate the summaries which come from the same skip marker/reason.

I tracked it down to https://github.com/prokaktus/pytest/commit/3795b08e9500be276098969036e21f8c54b47f10, which introduced the `-r` option.

I wonder if this inconsistency is still worth having? Personally I would prefer the SKIPPED message to look the same as XFAIL/XPASS, and show up as once for each skipped test, instead of having them folded.

I notice there's a comment in the current code too regarding markers:

https://github.com/pytest-dev/pytest/blob/28e8c8582ea947704655a3c3f2d57184831336fd/src/_pytest/terminal.py#L1319-L1321

Perhaps @RonnyPfannschmidt can remark on that comment.

**Comment by RonnyPfannschmidt** [comment]
The folding was introduced for sensible reporting even when there are hundreds of skips for reasons

AFAIK those numbers tend to be hit with skips often enough to warrant it, i haven't observed similar usage for xfail /xpass which is used in very different use cases

Im explicitly in favour of the difference here

**Comment by eli-schwartz** [comment]
Hmm, hundreds of skips due to parameterization I assume?

I think I would personally prefer the test class::function name on its own instead of a line number, as I'd assume that has to be just as foldable as the line number
