### ISSUE TITLE
Unexpected behavior of pytest.approx() with pandas

### ISSUE THREAD

**Issue by janosh** [pytest-dev/pytest#9888]
- [x] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions: **pytest 7.1.1 and macOS 12.2.1**
- [x] minimal example if possible

```py
import pytest
import pandas as pd

pd.Series([1, 2, 3]) == pytest.approx(pd.Series([1, 2, 3]))
>>>
0    False
1    False
2    False
dtype: bool
```

I was expecting to get the output of either

```py
pd.Series([1,2,3]) == pd.Series([1,2,3])
>>>
0    True
1    True
2    True
dtype: bool
```

or

```py
[1,2,3] == pytest.approx([1,2,3])
>>> True
```

**Comment by asottile** [comment]
`==` against numpy arrays or pandas series / dataframe is a projection not an equality check

this is numpy/pandas behaviour and not something that can be helped from pytests's side -- use `numpy.testing.assert_equal` or `pandas.testing.assert_frame_equal` or `pandas.testing.assert_series_equal`
