### ISSUE TITLE
doctest-modules with NUMBER option ignores zero decimal precision

### ISSUE THREAD

**Issue by MatthewFlamm** [pytest-dev/pytest#9892]
- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

# Description
This was found in https://github.com/pyvista/pyvista/pull/2511.  Using NUMBER option causes zero-precision numbers to pass when the numbers are off by 1 by not by 2.  Also using NUMBER option in a module causes this behavior to leak out into other docstring tests that do not use NUMBER.  Not using NUMBER correctly fails the tests.

Thanks to @adeak who identified the off by 1 but not by 2 aspect of this.

Using commands `pytest --doctest-modules test_1.py` and `pytest --doctest-modules test_2.py`.

# MRE

```py
# test_1.py
def list_1():
    """
    Passes

    Examples
    --------
    >>> [0.]  # doctest: +NUMBER
    [1.]
    """

def list_2():
    """
    Passes

    Examples
    --------
    >>> [1.]  # doctest: +NUMBER
    [0.]
    """

def list_3():
    """
    Passes

    Examples
    --------
    >>> [0.0]  # doctest: +NUMBER
    [1.]
    """

def list_4():
    """
    Passes

    Examples
    --------
    >>> [1.0]  # doctest: +NUMBER
    [0.]
    """

def list_5():
    """
    Passes

    Examples
    --------
    >>> [1.]  # doctest: +NUMBER
    [2.]
    """

def list_6():
    """
    Fails

    Examples
    --------
    >>> [1.]
    [3.]
    """


def list_7():
    """
    Fails
    
    Examples
    --------
    >>> [1.1]  # doctest: +NUMBER
    [0.]
    """

def list_8():
    """
    Passes in this module

    Examples
    --------
    >>> [1.]  
    [0.]
    """
```

```py
# test_2.py
def list_8():
    """
    Fails in this module

    Examples
    --------
    >>> [1.]  
    [0.]
    """
```

# pip list
```txt
Package    Version
---------- -------
attrs      21.4.0
iniconfig  1.1.1
numpy      1.22.3
packaging  21.3
pip        22.0.4
pluggy     1.0.0
py         1.11.0
pyparsing  3.0.8
pytest     7.1.2
setuptools 41.2.0
tomli      2.0.1
```

# system version
CentOS 7.9

Edit: Added description of how I ran the tests.

**Comment by MatthewFlamm** [comment]
This also occurs if the numbers aren't inside a list, e.g.

```py
def number():
    """
    Passes.

    Examples
    --------
    >>> 1.  # doctest: +NUMBER
    0.
    """

**Comment by MatthewFlamm** [comment]
I've found that it uses `approx` under the hood [here](https://github.com/pytest-dev/pytest/blob/90b1c93f7ec2a03d706af093eef7705a9f59b24d/src/_pytest/doctest.py#L659) which means that it can be off by one in this case.  The description of `NUMBER` makes it sound like it should be more like a string comparison that ignores the extra precision.

> when enabled, floating-point numbers only need to match as far as the precision you have written in the expected doctest output. For example, the following output would only need to match to 2 decimal places:

>>> math.pi
3.14

>If you wrote 3.1416 then the actual output would need to match to 4 decimal places; and so on.

I'm not sure what causes the leaking of behavior outside of a function docstring doctest.

**Comment by MatthewFlamm** [comment]
I'm realizing there are two issues here.  One is the wording of the documentation, the other a leakage of the scope of `NUMBER`.  If preferred, I can open a second issue for the latter.

**Comment by nicoddemus** [comment]
I was about to create an issue for the second issue, however I get a failure in `list_8` even if execute only `test_2.py`...

Also, how the above works using the standard `doctest` module?

**Comment by MatthewFlamm** [comment]
It is expected to fail in `test_2.py` because the `NUMBER` option is not used.  In `test_1.py` it is an identical test (to my eyes), yet passes.  I'm guessing it is a leakage of the usage of the usage of `NUMBER` out of scope, but this is a bit speculative.

The built in doctest also fails this in `test_2.py` as expected.  It cannot run `test_1.py` because `NUMBER` is not supported.

**Comment by MatthewFlamm** [comment]
Would you prefer I simplify the MRE in a new example to focus on this issue?

**Comment by nicoddemus** [comment]
Ahh got it. Thanks, I appreciate it!
