### ISSUE TITLE
'maxfail' option: allow to opt-out from counting failed parametrizations

### ISSUE THREAD

**Issue by AIGeneratedUsername** [pytest-dev/pytest#9908]
# An example before we will go into details.

Imagine that there are total 10 tests:
 - 9 tests are regular simple tests
 - 1 test is parametrized with 50 arguments.
In other words, it will be 9 + 50 = 59 executions.

The goal: a user wants to stop Pytest session after 3 failed tests (not parametrizations!!!). 

# Current Pytest `maxfail` behavior

The `maxfail` counts every test call, including parametrizations. 
It is a bad experience for a developer because the developer may want to allow N tests to fail, but do not count that one of that tests is parametrized with 50 options.

In other words, if a developer will pass now `maxfail=3` and the first test is parametrized with 50 options, and a few options will fail, then Pytest even will not start the seconds test.

# Desired behavior 

Count only if a test failed or **all** parametrizations failed.

1. A developer passes `maxfail=3`. 
2. The first test that is parametrized with 50 arguments fails for some arguments, but we do not care about that. 
3. We still have 0 (zero) failed nodes count.
4. The seconds test fails. Only now we have 1 failed tests (or nodes, or whatever you name it) count.

# Syntax proposal

How do you name tests at collection time? Nodes? 
My proposal is to have a separate option, e.g. `--maxfail_nodes 3`.

**Comment by RonnyPfannschmidt** [comment]
Currently parameterization is part of test collection

Maxfail of per function definition is not yet implemented

**Comment by AIGeneratedUsername** [comment]
> Maxfail of per function definition 

Yes, this is is my idea that I tried to describe here. It would be great to have `maxfail` alternative of per function definition.

**Comment by asottile** [comment]
to pytest a different parameterization is a separate test -- I don't think that should change and another option seems like it would be both complex to implement, difficult to maintain, and difficult to explain (how do you then handle fixture parametrization, deduplication at the class level, nested parametrization, collection parametrization, etc.)
