### ISSUE TITLE
Document py.convert_unittest/pycmd in the unittest section

### ISSUE THREAD

**Issue by ionelmc** [pytest-dev/pytest#991]
This tool should be in core no? 

Is there any reason it shouldn't be provided by pytest?

**Comment by The-Compiler** [comment]
I'm guessing mainly for historical reasons - :+1: from me, especially because it's nearly impossible to find otherwise :wink:

Scripts:

* [convert_unittest.py](https://bitbucket.org/hpk42/pycmd/src/bf134aede218847720dd78facde72bbd55e48720/pycmd/pyconvert_unittest.py?at=default&fileviewer=file-view-default)
* [test_convert_unittest.py](https://bitbucket.org/hpk42/pycmd/src/bf134aede218847720dd78facde72bbd55e48720/test_convert_unittest.py?at=default&fileviewer=file-view-default)

**Comment by RonnyPfannschmidt** [comment]
its a completely separate command, and personally i'd like to keep it outside of pytest

**Comment by nicoddemus** [comment]
I'm leaning with @RonnyPfannschmidt on this one, seems to me more like a separate tool than being bundled and maintained inside pytest.

But I do agree that it is hard to find. How about we make it a separate project (pytest-dev/unittest2pytest), and explicitly mention it in the official docs?

**Comment by ionelmc** [comment]
What's the worst that could happen if pytest provides this bin? Seems harmless to me. 

The benefit of it being in the core is clear is it not? Users would have a straightforward way to convert those tests. Maybe one day pytest doesn't need to support TestCase tests anymore - you never know ;)

**Comment by RonnyPfannschmidt** [comment]
its a maintenance burden and its easier to have it in a separate release cycle
i'd rather put it together into a pytest plugin for unittest/nose compat than the other way around

**Comment by nicoddemus** [comment]
> What's the worst that could happen if pytest provides this bin? Seems harmless to me.

I'm thinking it is a matter of maintainability and release cycles. For example, if it is a separate tool it can support different pytest versions (for example, being able to generate for different pytest versions) and test against each version separately. Bug fixes could be released in a different timeframe as well.

> The benefit of it being in the core is clear is it not? Users would have a straightforward way to convert those tests. Maybe one day pytest doesn't need to support TestCase tests anymore - you never know ;)

I agree, but you get the same benefits if we move it to a separate tool in the pytest-dev organization.  :smile:

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt beat me to it. :smile:

**Comment by ionelmc** [comment]
The scenario I had in mind was something like:

* User installs pytest
* Types `py<TAB>` - "oh, look, there's a thing to covert those goddamn unittests, how did I not see this in the docs?!"

My main concern is that this tool won't have enough visibility if it's outside of core, even if documented. I mean, it's outside of core right now and no one knows about it.

**Comment by RonnyPfannschmidt** [comment]
we should introdice a pytest extra called `recommended` and instruct people to install `pytest[recommended]` and include things like xdist, cov (ipython does it that way as well)

**Comment by nicoddemus** [comment]
> My main concern is that this tool won't have enough visibility if it's outside of core, even if documented. I mean, it's outside of core right now and no one knows about it.

I agree that right now it is relatively unknown, but I think mentioning it in http://pytest.org/latest/unittest.html would be enough to raise awareness about it, don't you think?

**Comment by RonnyPfannschmidt** [comment]
never underestimate the stumbled uppon factor

**Comment by ionelmc** [comment]
Ok, I admit defeat :)

**Comment by nicoddemus** [comment]
Anyone interested in adopting the script and create a proper pytest-dev project for it? :smile:

**Comment by ionelmc** [comment]
I can do it if no one wants it. Shall we do some renaming? `py.convert-unittest` or `py.convertunittest`? How about `pytest-convert`?

Distribution/project name `pytest-convert-unittest`?

**Comment by nicoddemus** [comment]
Nice @ionelmc! :sunglasses: 

I think we should reserve `pytest-` prefix for actual pytest plugins (I was asked by @hpk42 to rename `pytest-plugs` to `plugincompat` for this reason).

I personally liked `convertunittest` for project name and `py.convertunittest` for the command (although one might argue that having the same name for both would be better to avoid confusion, in which case I would vote for both to be `convertunittest`). Other suggestions are welcome too. :smile:

**Comment by ionelmc** [comment]
How about `unittest-to-pytest`? @RonnyPfannschmidt opinion?

**Comment by nicoddemus** [comment]
@ionelmc  :+1: to `unittest-to-pytest`

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Comment by htgoebel** [comment]
You may be interested in my tool [unittest2pytest](https://pypi.python.org/pypi/unittest2pytest/), which uses lib2to3 for transformation and will handle context-handlers quite soon.

**Comment by nicoddemus** [comment]
@ionelmc, did you move this forward? If not, perhaps it would be better to join efforts with @htgoebel in `unittest2pytest`... using `lib2to3` seems like an excellent approach to the problem. :smile:

**Comment by ionelmc** [comment]
Ooops, I forgot about this :grimacing: 

@htgoebel is there anything that `py.convert_unittest` does and https://pypi.python.org/pypi/unittest2pytest/ doesn't?

**Comment by htgoebel** [comment]
@ionelmc AFAIK,  unittest2pytest coverts everything py.convert_unittest does – except installing in the `py` namespace, which IMHO is useless, as you will use this tool once for each project.

**Comment by ionelmc** [comment]
Well I guess then we should have some link to https://pypi.python.org/pypi/unittest2pytest/ in the pytest docs?

**Comment by htgoebel** [comment]
Well, I'd support this :-)
