### ISSUE TITLE
`EncodingWarning` raised in `cacheprovider`

### ISSUE THREAD

**Issue by AA-Turner** [pytest-dev/pytest#9910]
Sphinx recently enabled the `EncodingWarning` feature of Python 3.10+ in tests.[^1][^2]

[^1]: https://docs.python.org/3/library/io.html#io-encoding-warning
[^2]: https://docs.python.org/3/using/cmdline.html?highlight=warn_default_encoding#cmdoption-X

PyTest reports three `EncodingWarning`s in `_pytest/cacheprovider.py`, output below:

```text
.tox/du18/lib/python3.10/site-packages/_pytest/cacheprovider.py:199
  /home/runner/work/sphinx/sphinx/.tox/du18/lib/python3.10/site-packages/_pytest/cacheprovider.py:199: EncodingWarning: 'encoding' argument not specified
    readme_path.write_text(README_CONTENT)

.tox/du18/lib/python3.10/site-packages/_pytest/cacheprovider.py:189
.tox/du18/lib/python3.10/site-packages/_pytest/cacheprovider.py:189
  /home/runner/work/sphinx/sphinx/.tox/du18/lib/python3.10/site-packages/_pytest/cacheprovider.py:189: EncodingWarning: 'encoding' argument not specified
    f = path.open("w")

.tox/du18/lib/python3.10/site-packages/_pytest/cacheprovider.py:160
  /home/runner/work/sphinx/sphinx/.tox/du18/lib/python3.10/site-packages/_pytest/cacheprovider.py:160: EncodingWarning: 'encoding' argument not specified
    with path.open("r") as f:
```

The remedy is to add an explicit `encoding="..."` argument, most likely `"utf-8"`.

Reproducer is `python -X warn_default_encoding -m pytest ...` with a path to a test suite.

Test session preamble:

```text
============================= test session starts ==============================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0 -- /home/runner/work/sphinx/sphinx/.tox/du18/bin/python
cachedir: .tox/du18/.pytest_cache
libraries: Sphinx-5.0.0+/7970e6c, docutils-0.18.1
base tempdir: /tmp/pytest-of-runner/pytest-0
rootdir: /home/runner/work/sphinx/sphinx, configfile: setup.cfg, testpaths: tests
plugins: cov-3.0.0
```

A

**Comment by bluetech** [comment]
Thanks for reporting. Indeed the encoding should be `utf-8`. The README one is definitely UTF-8; the json ones currently don't pass `ensure_ascii=False`, so they're ASCII, which is a subset of UTF-8. Along the way I'd suggest also passing `ensure_ascii=False` to the `json.dumps` call, because why uglify the output if it's not needed?

**Comment by peymanslh** [comment]
Hi,
Can I work on this issue?

**Comment by AA-Turner** [comment]
Please! You just need to change the three calls in my orignal report to add an `encoding="utf-8"` argument, and probably also add `ensure_ascii=False` as @bluetech noted.

A
