### ISSUE TITLE
Support load_tests protocol

### ISSUE THREAD

**Issue by soltanmm** [pytest-dev/pytest#992]
The [load_tests protocol](https://docs.python.org/2/library/unittest.html#load-tests-protocol) is in the standard library but does not appear to be supported out of the box in `py.test`.

cc @nathanielmanistaatgoogle

**Comment by RonnyPfannschmidt** [comment]
And it will stay that way unless someone provides a very compelling reason to support those pretty limiting APIs directly

**Comment by nathanielmanistaatgoogle** [comment]
Please elaborate? What's limiting about them, and why wouldn't pytest want to be compatible with all aspects of the standard library's unittest module?

**Comment by nathanielmanistaatgoogle** [comment]
Also @RonnyPfannschmidt your expression "support those [...] APIs directly" suggests that there might be indirect support - is there a workaround we should be using?

**Comment by nicoddemus** [comment]
Hi @soltanmm, it might be possible to support `load_tests` protocol in `pytest`, although there might be added complexity and backward compatibility concerns.

Currently pytest will collect test methods from classes which subclass `unittest.TestCase` only, but if `pytest` starts calling any `load_tests` functions it finds in modules might break things for existing test suites which don't use `unittest` at all (perhaps a flag `--unittest-load-tests-protocol` or something like that could be added to preserve backward compatibility).

Perhaps you could explain the use cases you have to better give an idea to the amount of work it would take `pytest` to support that?

**Comment by RonnyPfannschmidt** [comment]
the collection and runner/execution concept is very different from pytest - bascially i never want to support that as it would cripple the ways in which py.test can be extended and evolved

i wouldn't mind if someone *else* made a *external* *non-core* plugin - but i expect it to be a chain of compat details - and i certainly don't want to support it

**Comment by jayvdb** [comment]
Also raised as https://bitbucket.org/pytest-dev/pytest/issues/772/

I am also interested in this, and have played with @soltanmm 's conftest solution [here](https://github.com/grpc/grpc/pull/3548/files).  It would be great if @soltanmm could package that into a plugin.

Our tracker for this is https://phabricator.wikimedia.org/T135912 , where I have noted a bug in the `conftest.py` and workaround.

**Comment by nicoddemus** [comment]
I think we can close this for now... if someone needs this, creating a separate plugin like mentioned in grpc/grpc#3548 is highly encouraged.

**Comment by Kentzo** [comment]
Did anything change to reconsider implementation of this feature as part of `pytest`?

**Comment by Kentzo** [comment]
In my case the project is tested with unittest, but we'd like to let people run pytest as well.

Implementing an external plugin is too much work for that.
