### ISSUE TITLE
Improve output for `any` and `all` when used with generator expressions

### ISSUE THREAD

**Issue by alexprengere** [pytest-dev/pytest#9929]
#### What's the problem this feature will solve?

When using `any` or `all` in a test:

```python
def test_all():
    assert all([j == 0 for j in range(10)])
```

We get a nice output:

```python
    def test_all():
>       assert all([j == 0 for j in range(10)])
E       assert False
E        +  where False = all([True, False, False, False, False, False, ...])
```

But if we switch to the generator expression form, the output is less helpful:

```python
    def test_all():
>       assert all(j == 0 for j in range(10))
E       assert False
E        +  where False = all(<generator object test_all.<locals>.<genexpr> at 0x...>)
```

#### Describe the solution you'd like

Ideally, it would be more useful is the generator expression form output would be closer to the list version, by showing the content of the generator for example. Thanks a lot for maintaining pytest!

**Comment by The-Compiler** [comment]
I don't think it's possible for pytest to do that: At the point the assertion fails, the generator is already (partially) exhausted, and pytest doesn't have a way to know what was in it before.

**Comment by alexprengere** [comment]
I figured as such, I wondered if maybe some remaining values might be displayed, but I agree it is just simpler to encourage the use of the list comprehensions here.
Thanks for your reply!
