### ISSUE TITLE
testing: failures on Python 3.11 due to Path.rglob("")

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#9930]
Failures in `testing/test_conftest.py` due to some test fixture using `path.rglob("")`. This is not a compat problem in pytest itself, just its test suite. Example run:

https://github.com/pytest-dev/pytest/runs/6348412015

I'll submit a workaround and maybe file a bug with python if this is a regression there.

**Comment by hroncok** [comment]
> maybe file a bug with python if this is a regression there.

[It was a regression](https://github.com/python/cpython/issues/92550)

**Comment by hugovk** [comment]
And will be in the next beta due on 2022-05-30, in case you want to remove the workaround:

https://peps.python.org/pep-0664/#release-schedule
