### ISSUE TITLE
Explicit note that tmpdir fixture is discouraged in favour of tmp_path

### ISSUE THREAD

**Issue by timhoffm** [pytest-dev/pytest#9937]
While https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures` mentions "These days, prefer to use tmp_path and tmp_path_factory", it's quite hidden in the text.

I propose to announce this more loudly using a note admonition. Additionally the note admonition should be placed in the docstrings:

- https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=tmpdir#std-fixture-tmpdir
- https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=tmpdir#pytest.legacypath.LegacyTmpdirPlugin.tmpdir

The same holds for `tmpdir_factory`.

**Comment by nicoddemus** [comment]
Definitely @timhoffm, thanks!

**Comment by vitaliyterziev** [comment]
Hello, I can help with that if not taken already, do you have any particular message you would like me to use for the notes under tmpdir function and TempdirFactory class and also for the docstrings in "pytest/blob/main/src/_pytest/legacypath.py"?

**Comment by DaniSancas** [comment]
Hi @timhoffm, from @clarityai-eng we'd like to contribute to the Pytest project by creating a PR to fix this issue.

We hope you find it useful, let us know if it fits your requirements.
