### ISSUE TITLE
Reversing +/- in diffs?

### ISSUE THREAD

**Issue by ctheune** [pytest-dev/pytest#994]
Hi,

is it possible to reverse the +/- meaning of diffs in the report?

I notice that I usually write my assumptions in this style:

```
    assert check_output.call_args_list == [
        call(['rbd', '--no-progress', 'snap', 'create',
             'test/foo@backy-f0e7292e-4ad8-4f2e-86d6-f40dca2aa802']),
        call(['rbd', '--no-progress', 'export-diff',
              'test/foo@backy-f0e7292e-4ad8-4f2e-86d6-f40dca2aa802',
              '{}/f0e7292e-4ad8-4f2e-86d6-f40dca2aa802.rbddiff'.format(tmpdir),
```

This causes the following output if something doesn't fit:

```
AssertionError: assert [call(['rbd',...0dca2aa802'])] == [call(['rbd', ... 'test/foo'])]
  Left contains more items, first extra item: call(['rbd', '--no-progress', 'snap', 'rm', 'test/foo@backy-f0e7292e-4ad8-4f2e-86d6-f40dca2aa802'])
  Full diff:
  [call(['rbd', '--no-progress', 'snap', 'create', 'test/foo@backy-f0e7292e-4ad8-4f2e-86d6-f40dca2aa802']),
  call(['rbd', '--no-progress', 'export-diff', 'test/foo@backy-f0e7292e-4ad8-4f2e-86d6-f40dca2aa802', '/private/var/folders/47/czcj479923g9ggvl6zn5fzpc0000gn/T/pytest-264/test_diff_backup0/f0e7292e-4ad8-4f2e-86d6-f40dca2aa802.rbddiff', '--from-snap', 'backy-ed968696-5ab0-4fe0-af1c-14cadab44661']),
  -  call(['rbd', '--no-progress', '--format=json', 'snap', 'ls', 'test/foo']),
  ?                                                                           ^
  +  call(['rbd', '--no-progress', '--format=json', 'snap', 'ls', 'test/foo'])]
  ?                                                                           ^
  -  call(['rbd', '--no-progress', 'snap', 'rm', 'test/foo@backy-f0e7292e-4ad8-4f2e-86d6-f40dca2aa802'])]
```

Interestingly the '-' is the stuff that was actually encountered in the output and the '+' is the stuff that is missing from the actual output.

Looking at the documentation examples I see that this style is also preferred in pytest. (The other style being named "Yoda" style assertions are obviously frowned upon.)

Was the existing way of reporting an explicit choice or just "came to be"?

Is there a chance to reverse this? Or at least make it optional? I find it hard to read and keep running into this as a mental barrier.

**Comment by RonnyPfannschmidt** [comment]
switch the order operands in the == expression?

**Comment by ctheune** [comment]
Uhm. Are you asking me to switch my statements around? That would result in exactly those "yoda" expressions that I wanted to avoid.

I was also asking whether the current order was intentional or accidental. :)

**Comment by untitaker** [comment]
There is no way to reverse the diff without reversing the operands. The current order kind of makes sense if you imagine that the diff for `a == b` gets produced as `diff a b`, i.e. no change takes place. I kind of understand where you're coming from but I don't see it as big as a deal.

**Comment by ctheune** [comment]
It's not a big deal in itself. It's more of a "thousand paper cuts" thing. I wondered for a long time why I used to write Yoda conditions in the old unittest structures and noticed it was because it made the comparisons more readable. But then again Yoda conditions are harder to read and write, as you pretty much _never_ get to fit the first item on a single line and then have to put everything in parentheses all the time.

**Comment by The-Compiler** [comment]
I think "how do I get from the left to the right" also is a logical way to think about the diff, but I also see how "how do I get from what I have to what I expected" with the normal `assert actual == expected` being easier to understand...

Either way I think it'd be a very bad idea to change this now, or even to make it configurable - if you have to check the pytest version/config each time you contribute to a project and something goes wrong, now *that* is some cognitive overhead...

**Comment by RonnyPfannschmidt** [comment]
Sounds like a job for a plugin or a pytest INI option

**Comment by nicoddemus** [comment]
I would rather a plugin then; I agree with @The-Compiler that an option would complicate matters

**Comment by RonnyPfannschmidt** [comment]
Closing as not actionable
