### ISSUE TITLE
Adding of parameters by default

### ISSUE THREAD

**Issue by mihalt** [pytest-dev/pytest#9955]
Hi! Nice lib. But I found little boring to set the same parameters in tests to use fixture. I would like to see something like that:
```
pytest.fixture(autouse=True, autoparam=True)
    def myfixture():
        return 1
​
class TestCase:
​
    def test_foo(self):
       assert myfixture + 1
​
 
    def test_bar(self):
       assert myfixture - 1
​
​
def module_func():
       assert myfixture + 2
```

Is it possible?

**Comment by mihalt** [comment]
> Hi @mihalt,
> 
> It is not, due to how Python works: a name cannot appear out of nowhere, it needs to be imported or declared somehow.

Could I use for tests in class maybe at least?

**Comment by nicoddemus** [comment]
The closest to that you can do is assigning the fixture value to `self`:

```python
​class TestCase:

    @pytest.fixture(autouse=True)
    def myfixture(self):
        self.value = 1
​
    def test_foo(self):
       assert self.value + 1
​ 
    def test_bar(self):
       assert self.value - 1
```

**Comment by mihalt** [comment]
> The closest to that you can do is assigning the fixture value to `self`:
> 
> ```python
> ​class TestCase:
> 
>     @pytest.fixture(autouse=True)
>     def myfixture(self):
>         self.value = 1
> ​
>     def test_foo(self):
>        assert self.value + 1
> ​ 
>     def test_bar(self):
>        assert self.value - 1
> ```

yes, I know this option. But as I understand, I have to duplicate myfixture() globaly for module to use on non-class tests. To another classes I can inherit at least.

**Comment by The-Compiler** [comment]
There's no way around this - to use a value in a function, it will need to be defined somewhere. Either as an argument, or as an attribute on a class.

(Yes, in theory, pytest could set global variables and then change them between tests, but... I'm pretty confident to say that ain't gonna happen, sorry)
