### ISSUE TITLE
filterwarnings inconsistently works

### ISSUE THREAD

**Issue by DoubleF3lix** [pytest-dev/pytest#9960]
I have used both a TOML config
```toml
[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning"
]
```
And a python decorator:
```py
@pytest.mark.filterwarnings("ignore::DeprecationWarning")
```
To stop deprecation warnings about invalid escape sequences (which I am trying to test), and when I run `pytest`, sometimes they work, sometimes they don't. I can run `pytest` and have them show up, and run it again (changing nothing) and the warnings won't show up.

Poetry list:
```
atomicwrites    1.4.0  Atomic file writes.
attrs           21.4.0 Classes Without Boilerplate
black           22.3.0 The uncompromising code formatter.
click           8.1.3  Composable command line interface toolkit
colorama        0.4.4  Cross-platform colored terminal text.
iniconfig       1.1.1  iniconfig: brain-dead simple config-ini parsing
mypy-extensions 0.4.3  Experimental type system extensions for programs checked with the mypy typechecker.
packaging       21.3   Core utilities for Python packages
pathspec        0.9.0  Utility library for gitignore style pattern matching of file paths.
platformdirs    2.5.2  A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
pluggy          1.0.0  plugin and hook calling mechanisms for python
py              1.11.0 library with cross-python path, ini-parsing, io, code, log facilities
pyparsing       3.0.9  pyparsing module - Classes and methods to define and execute parsing grammars
pytest          7.1.2  pytest: simple powerful testing with Python
tokenstream     1.4.1  A versatile token stream for handwritten parsers
tomli           2.0.1  A lil' TOML parser
```

Minimal example:
```py
@pytest.mark.filterwarnings("ignore::DeprecationWarning")
def test_q():
    assert list("\[\]") == ['\\', '[', '\\', ']']
```
Running `pytest` will randomly hide or show warnings.

**Comment by The-Compiler** [comment]
I believe the `filterwarnings` doesn't work at all, and the warning disappears because Python emits it only when compiling the file - similar to #8835.

You will see the same behavior when you run `python3 -Wall -c "import test_x"`: The warning gets emitted at import time (not when the code is executed, so the mark won't do anything); and as soon as you have a `__pycache__`, running the same command again will not trigger a warning.

Not sure if there's much we can do here?

**Comment by DoubleF3lix** [comment]
Oh, interesting. Thanks.

**Comment by The-Compiler** [comment]
`filterwarnings` works just fine - but if used as a decorator, it applies for warnings emitted while the test function is running.
