### ISSUE TITLE
`request` fixture contains a `path` property, but this is not in the documentation

### ISSUE THREAD

**Issue by dorak88783** [pytest-dev/pytest#9975]
In https://docs.pytest.org/en/7.1.x/_modules/_pytest/fixtures.html#FixtureRequest there is a (nice) property ` def path(self) -> Path`, but this is not in the documentation at `https://docs.pytest.org/en/7.1.x/reference/reference.html#std-fixture-request`.

Is this as expected?

**Comment by The-Compiler** [comment]
I don't think this is intended. The `.path` property was introduced by @RonnyPfannschmidt in 22dad53a248f50f50b5e000d63a8d3c798868d98, and back there, the old `fspath` was documented too (that then got dropped in 7c0011374c99a3738324db2c783d4e5d369cff23, probably somewhat unintentionally too).

**Comment by nicoddemus** [comment]
Hmm I had a vague recollection of we leaving it undocumented on purpose, but I'm remembering it wrong then

**Comment by paulreece** [comment]
Hi, I created a PR [here](https://github.com/pytest-dev/pytest/pull/10056) to fix this issue.

**Comment by paulreece** [comment]
@nicoddemus Just checking in if anything else is needed for this.  I created a PR [here](https://github.com/pytest-dev/pytest/pull/10056)

**Comment by nicoddemus** [comment]
Ahh I missed, thanks for the ping. 👍 

Just merged it, thanks again.
